### ISSUE TITLE
nitro output support for 404 handling with prerendered assets

### ISSUE THREAD

**Issue by Ben-VP** [nuxt/framework#10000]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.9.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `nitro`, `modules`, `googleFonts`, `vite`, `extends`, `generate`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/google-fonts@3.0.0-1`, `@nuxt/image-edge@1.0.0-27840416.dc1ed65`, `@formkit/nuxt@1.0.0-beta.12`
- Build Modules:    `-`

### Reproduction

When using nuxi generate, it generates a blank 404.html file.

### Describe the bug

In local development error.vue works as expected. However, once pushed to production and nuxi generate is used, the custom error page doesn't work.

error.vue is located in my sites directory along with app.vue etc.

Site is hosted on Vercel.

**Comment by Ben-VP** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

https://stackblitz.com/edit/github-vjdsh9?file=error.vue

I'm unsure how to run the production build on stackblitz. But that's the base reproduction, navigate to a path that doesn't exist the error page works fine. But in production is where the issue is.

Once you run nuxi generate and host it in a production environment the error page doesn't work.

Please let me know if there is anything else you need from me - first time submitting an issue with reproduction.

**Comment by danielroe** [comment]
Ah, I think I understand what you mean. In production, if you have prerendered your pages with `nuxt generate`, you would hope to see a 404 page when navigating to a page that doesn't exist. But Nuxt isn't running; your static host needs to know to render that 404 with a nuxt page, which you probably need to do with https://vercel.com/docs/project-configuration#routes/advanced/spa-fallback.

I think it might be worth doing this in a Nitro preset (generating build output api without functions) - wdyt @pi0?

**Comment by Ben-VP** [comment]
That's exactly it @danielroe, I'll try what you linked and update if that solves it.

Having this done automatically would be amazing.

**Comment by pi0** [comment]
Also a related issue in nitro https://github.com/unjs/nitro/issues/797. We shall also provide a `static: true` flag to nitro that enables `vercel-static` on auto detected environment 👍🏼

**Comment by danielroe** [comment]
Thanks for opening this @Ben-VP - we'll track in https://github.com/unjs/nitro/issues/818.
