### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'parentNode')

### ISSUE THREAD

**Issue by max-end** [nuxt/framework#10038]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `pages`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

`
{
            name: 'withdraw',
            path: '/withdraw',
            component: () => import('~/pages/withdraw.vue'),
            children:[
                {

                    name: 'withdraw-cash',
                    path: 'cash',
                    component: () => import('~/pages/withdraw/cash.vue')
                },
                {
                    name: 'withdraw-record',
                    path: 'record',
                    component: () => import('~/pages/withdraw/record.vue')
                }
            ]
}
`
### Describe the bug

Jump error between pages

TypeError: Cannot read properties of null (reading 'parentNode')

**Comment by danielroe** [comment]
Closing in favour of https://github.com/nuxt/framework/issues/2985.
