### ISSUE TITLE
Runtime.ImportModuleError - Error: Cannot find module 'server' Require stack: - /var/runtime/index.mjs

### ISSUE THREAD

**Issue by gjvengelen** [nuxt/framework#10050]
### Environment

Netlify preview, branch and production

### Reproduction

When you create a new deployment on netlify it returns:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/79509387/211893011-8eda2e32-5978-4ea4-84e3-3d622453547e.png">

There are numerous others complaint about it on Netllify, but Netlify points towards Nuxt

https://answers.netlify.com/t/this-function-has-crashed-nuxt-3-production/83046

### Describe the bug

<img width="859" alt="image" src="https://user-images.githubusercontent.com/79509387/211893168-ce2f0710-7be6-4171-9611-61590b2edcb6.png">

**Comment by jamaluddinrumi** [comment]
i'm just experience this too

![Screen Shot 2023-01-12 at 2 06 23 AM](https://user-images.githubusercontent.com/446780/211895744-8450e3f2-13cf-4d08-a2c1-44bfa6972e27.png)

visiting `/api/<path>` is also returning error as well
![Screen Shot 2023-01-12 at 2 06 23 AM](https://user-images.githubusercontent.com/446780/211896151-e14dfa9a-177f-443f-a127-7079ed41597b.png)

**Comment by gagglepod** [comment]
EXPERIMENT:
This runtime error is taking place even when you do a clean install.

This is what I did:

1. Installed Nuxt 3 application using: `npx nuxi init [project-name] `
2. Installed dependencies with: `npm install`
3. Created a git repo and then uploaded to GitHub
4. Created a Netlify Site and connected it to my GitHub repo
5. Deployed the site with default values
6. Netlify shows the deployment as "Published"
7. When you go to the Netlify URL it shows: 

`Runtime.ImportModuleError - Error: Cannot find module 'server' Require stack: - /var/runtime/index.mjs`

This is without ANY changes to the Nuxt 3 installation and doing everything from default.
Any ideas on how to solve this?

**Comment by fro-profesional** [comment]
I'm experience the same for all my projects of nuxt deployed since today 

sample: 
- code: https://github.com/clau-org/turibike-page
- netlify page: https://turibike-page.netlify.app/

**Comment by torstah** [comment]
Same here, very frustrating.

**Comment by danielroe** [comment]
We're aware of this and currently believe this is an upstream issue with Netlify rather than with Nuxt or its dependencies, but will be working closely with Netlify to figure out what's going on and get a satisfactory resolution.

I'll make sure to update here.

Thanks for your patience.

**Comment by danielroe** [comment]
This should now be resolved. Kudos to the netlify team for responding - even though it was close to midnight - and shipping a fix super quickly.

**Comment by ascorbic** [comment]
Thanks everyone for your help in reprting this. It looks like an update in our bundling code didn't play nicely with the entrypoint generated by Nitro. We've rolled it back and will investigate what happened. COuld anyone affected try deploying again? Sorry for the disruption.

**Comment by gagglepod** [comment]
Just did a new deployment of my out-of-the-box Nuxt 3 app to Netlify -- WORKED LIKE A CHARM!!
Thank you all for working hard to get this fixed!

**Comment by jrsamuel** [comment]
Thank you for fixing this.  Working for me as well!

**Comment by gjvengelen** [comment]
Works for me as well, I think this issue can be closed.
