### ISSUE TITLE
Error: nuxt instance unavailable yet it is imported from "#imports"

### ISSUE THREAD

**Issue by RijaCloud** [nuxt/framework#10064]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

````
<script>
import { mapState } from "pinia";
import { useNuxtApp } from "#imports";
const nuxt = useNuxtApp()

export default {
  name: "DilypsePlanGroupTab",
  props: {
    value: {
      type: [String, Number],
      default: "",
    },
  },
  computed: {
    ...mapState(nuxt.$useBuzzPaymentStore, { planGroups: "getplanGroups" }),
  },
  emits: ["input", "change"],
  data() {
    return { current: "" };
  },
  watch: {
    value: {
      immediate: true,
      handler(value) {
        this.current = value;
      },
    },
    planGroups: {
      immediate: true,
      handler(planGroups) {
        if (!this.current && planGroups[0]) {
          this.current = planGroups[0].id;
          this.emitChange();
        }
      },
    },
  },
  methods: {
    emitChange() {
      this.$emit("input", this.current);
      this.$emit("change", this.current);
    },
    onTabChange(current) {
      this.current = current;
      this.emitChange();
    },
  },
};
</script>
````

### Describe the bug

Here I made sure to have access to the store by creating a plugin like this 

````
import { defineNuxtPlugin } from "#app";
import { defineStore } from "pinia";
export default defineNuxtPlugin((nuxt) => {
  const useUserStore = defineStore("userStore", {
  });
  
  return {
    provide: {
      useUserStore
    }
  }
})

````

But for some reason the useNuxtApp function does not work

**Comment by danielroe** [comment]
You should only call `useNuxtApp()` within the `setup` function of your component. I think instead you should directly import the store in that component rather than using a Nuxt plugin to provide it.

**Comment by danielroe** [comment]
You should only call `useNuxtApp()` within the `setup` function of your component. I think instead you should directly import the store in that component rather than using a Nuxt plugin to provide it.

**Comment by RijaCloud** [comment]
Sorry but I have to reopen this ticket @danielroe  :) . 
I had to use plugin to provide the store because outside the setup, composables and plugins. Method like `useCookie` are not available in other directory which is used very often in my current application since rc8. But since the nuxt 3.0, everything that seems working in my app are no longer because of that. So importing it directly in my component is not doing it because of the nuxt method no longer available outside components.

**Comment by danielroe** [comment]
Just to be clear, the 'nuxt instance available' is not about which folder the function is being called, but at what point in the lifecycle. It either needs to be in a Nuxt plugin, middleware or in a component lifecycle function (like setup).
