### ISSUE TITLE
Composables and plugins  are undefined

### ISSUE THREAD

**Issue by RijaCloud** [nuxt/framework#10122]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `npm@9.2.0`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

`composables/usePaginate.ts`

````
import { useState } from "#app"
export default function usePaginate() {
    
   const generatePaginationQuery = (pageSize = 0, page = 0) => {
    return {
      _perPage: pageSize,
      _page: page,
    }
  }
  return useState('paginate', () => {
    return {
       generatePaginationQuery
    }
  } )
}
````

`plugins/data.ts`

````
import { defineNuxtPlugin } from "#app";
export default defineNuxtPlugin((pnuxt) => {
  return {
    provide: {
      iUsePaginate : () => {
        return nuxt.$paginate.generatePaginationQuery(1, 3)
      }
    }
  }
})
````

`components/test.vue`
````
<template>
   <div>test</div>
</template>
<script>
export default {
  setup() {
      const iUsePaginate = useNuxtApp().$iUsePaginate
      const paginate = usePaginate() // useNuxtApp().$paginate is also undefined
     return {
        iUsePaginate,
       paginate
     }
  },
  mounted() {
   console.log(this.iUsePaginate()) // return undefined
   console.log(this.paginate) // return undefined
  }
} 
</script>
````

### Describe the bug

For some reason both the plugin and composables are undefined. 

Thanks for your help.

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by RijaCloud** [comment]
Hi @manniL  I gave you an example of my current code above . It is approximatly what I did in my project to get this unknown error actualy.

**Comment by yassilah** [comment]
@RijaCloud it is undefined because `nuxt.$paginate` doesn't exist in your context; I'm not sure what you're trying to achieve but maybe you can try this instead:

```ts
// composables/usePaginate.ts
export default function usePaginate(pageSize = 0, page = 0) {
    return {
      _perPage: pageSize,
      _page: page,
    }
}
```

```ts
// plugins/data.ts
import { defineNuxtPlugin } from "#app";
import { usePaginate } from '#imports';

export default defineNuxtPlugin((nuxt) => {
  return {
    provide: {
      iUsePaginate : () => usePaginate(1, 3)
    }
  }
})
```

```vue
<template>
   <div>test</div>
</template>

<script>
export default {
  setup() {
      const iUsePaginate = useNuxtApp().$iUsePaginate

   console.log(iUsePaginate()) // { _perPage: 1, _page: 3 }

     return {
        iUsePaginate
     }
  }
} 
</script>
```

Also as defined in the docs, I believe [useState](https://nuxt.com/docs/examples/composables/use-state#usestate) is used for SSR so you probably shouldn't use it to store a function as it will get serialized on the client

**Comment by RijaCloud** [comment]
Hello and thank you for your answer @yassilah .
I am currently working on updating our application stuck on nuxt rc-8. Some of our functions have taken a little too much advantage of the ability to call the useCookie composables in all the application outside of a script or the setup function. 
Trying to keep the logic used I had to switch some methods calling nuxt composables into plugins and composables hence my current problem.

For example, pinia stores use and modify cookies directly in their actions, since v3 stable useCookie is only usable in setup, composables and plugins. The solution I had was to transpose the stores into plugins. 

Another explanation, here is a utils function that depends on the store : 

````javascript
const customUpdatePaginatedItemAction = (
  paginationState: Record<string, any>,
  pagedList: Record<string, any>[],
  data: Record<string, any>,
  store: string
  ) => {
  const echoPostStore = nuxt.$useEchoPostStore();
  const echoMediaStore = nuxt.$useEchoMediaStore();
  const echoQuestionStore = nuxt.$useEchoQuestionsStore();
  if (data && data.id) {
      const currentPage = paginationState.page;
  
      if (pagedList[currentPage]) {
      const currentList = pagedList[currentPage].list;
      const newList = currentList.map((item) => {
          if (item.id === data.id) {
          return {
              ...data,
          };
          } else {
          return item;
          }
      });
      if (store === "POSTS") {
          echoPostStore._postPages = {
          ...pagedList,
          [-1]: { isFetched: true, list: newList },
          };
      } else if (store === "MEDIA") {
          echoMediaStore._picturesPages = {
          ...pagedList,
          [-1]: { isFetched: true, list: newList },
          };
      } else if (store === "QUESTION") {
          echoQuestionStore._questionsPages = {
          ...pagedList,
          [-1]: { isFetched: true, list: newList },
          };
      }
      }
  }
  };
  
````

According to the logic I mentioned above, I said to myself to make a plugins / composables , but it does not work as I want because calling this function from my components I have an undefined

**Comment by RijaCloud** [comment]
> Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

Hey @manniL .Here is a repo for the reproduction : https://github.com/RijaCloud/nuxt-3test-composable

**Comment by manniL** [comment]
@RijaCloud Thanks!

I've opened the [repo on StackBlitz](https://stackblitz.com/github/RijaCloud/nuxt-3test-composable?file=plugins%2FmyPlugins.ts,app.vue) and am not sure what you are trying to accomplish.

The main issue there is that you try to pass a `function` as value of a `useState` and serialization of a function is not supported (and "technically" not possible") which is why you get an empty object. 
The console also tells you that:

```
[Function: generatePaginationQuery]                                                                      23:16:27
Cannot stringify a function generatePaginationQuery 
```
