### ISSUE TITLE
Bundeling not working

### ISSUE THREAD

**Issue by KlausSchaefersAtWork** [nuxt/framework#10128]
### Environment

I am using Nuxt3 to build a static website. I build the artefacts using 

```
npx nuxi generate
```

When I am checking the page requests, I see that there are a lot of tiny JS files loaded file by file. I would expect them to by some how bundled into one big file.

<img width="1656" alt="Screenshot 2023-01-16 at 17 11 19" src="https://user-images.githubusercontent.com/24679519/212733748-5772f9a1-3c17-4303-b13f-82ec81a511e4.png">

### Reproduction

Open https://www.quant-ux.com/features/how_it_works/ and check developer console

### Describe the bug

Too many JS files are loaded

**Comment by danielroe** [comment]
This is rollup behaviour - it never emits the same code in more than one chunk, so if you have a component used in more than one place it will be exported as a separate file.

You can customise this with `vite.build.rollupOptions.output.manualChunks` - see https://rollupjs.org/guide/en/#outputmanualchunks.
