### ISSUE TITLE
Add "clientProtocol" option to HMR config

### ISSUE THREAD

**Issue by HendrikJan** [nuxt/framework#10135]
### Describe the feature

When you are behind a reverse proxy that handles HTTPS for you, there should be a way to have a different protocol on the server and on the client for HMR websockets.

We already have "clientPort", so you can have a different port on the server and in the client.

The feature would be a "clientProtocol" option, so the server can use "ws://" while the client uses "wss://".

Usage:
```javascript
{
    vite: {
        server: {
            hmr: {
                protocol: "wss",
                clientProtocol: "ws",
            },
        },
    },
}
```

This could also be a solution for issue #1021

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by Atinux** [comment]
I believe this issue should be open in Vite repository

**Comment by HendrikJan** [comment]
Thanks.
I found this closed issue in the Vite repository: https://github.com/vitejs/vite/issues/5266
I'll see if I can start a discussion in the Vite repo to find a fix/workaround for my issue.
