### ISSUE TITLE
[FEATURE REQUEST] Preview mode for Nuxt 3

### ISSUE THREAD

**Issue by JonathanDoelan** [nuxt/framework#10177]
As I am using Nuxt in full static mode, I was wondering why the [Preview Mode](https://nuxtjs.org/docs/features/live-preview/), introduced in Nuxt 2, is missing in Nuxt 3?

Would be nice to have it in Nuxt 3 as well!

(Let me know if there is a workaround or if I can do it my own)

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/15639
