### ISSUE TITLE
Developer warnings present on optimized output

### ISSUE THREAD

**Issue by jpsc** [nuxt/framework#1049]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.17.4`
- Nuxt Version:     `3-3.0.0-27234123.a896c64`
- Package Manager:  `npm`
- Bundler:          `Webpack/Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug and expected behavior

After building a new application with nuxt 3 I see the output files containing console warnings directed to developer experience. Is that expected? It would expect them to not exist on a minified/optimized output.

eg:

```js
 console.warn(`Reactive ${o} contains both the raw and reactive versions of the same object${o === "Map" ? " as keys" : ""}, which can lead to inconsistencies. Avoid differentiating between the raw and reactive versions of an object and only use the reactive version if possible.`)`
```

### Steps to reproduce

1. Go to https://1st-nuxt3-app.vercel.app/ or a newly created nuxt 3 application
2. Check the entry.mjs output

**Comment by chz** [comment]
+1

**Comment by danielroe** [comment]
This is no longer reproducible. Let me know if you still encounter this, and I'll reopen it.

**Comment by jpsc** [comment]
I think most of them were removed. I just see one now:

> console.warn(`${r} hook has been deprecated`+(s.to?`, please use ${s.to}`:""))

**Comment by danielroe** [comment]
That is from https://github.com/unjs/hookable/blob/main/src/hookable.ts#L39-L48. It's not a Nuxt issue.
