### ISSUE TITLE
Unable to load Global Stylesheets using nuxt.config.ts

### ISSUE THREAD

**Issue by wrench1815** [nuxt/framework#1072]
I'm trying to create a project using Nuxt 3 so was configuring the nuxt.config.ts, adding some stylesheets to the project. as per the documentation it's 
![image](https://user-images.githubusercontent.com/38432479/137475044-b7bb5fb9-b189-4fbb-ad31-ea5be5d9f8d8.png)
ok but what's the syntax?
I tried the nuxt 2 syntax as
```
link: [
  {
    rel: 'stylesheet',
    type: 'text/css',
    href: 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700',
  }
]
```
But its not working. then i just simply added the link as 
```
link: ['https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700']
```
And it also didnt worked?
How is it supposed to work? There's not much information in docs. I understand that it's in Beta and just launched but there are proper hints on how things are supposed to work or any example. I did looked i the examples folder in Repo but there's nothing in nuxt.config.ts.

I dont usually do things in JS so I'm not that familiar with JS. I use it for Nuxt and Vue only. So if im missing something or if the cause of issue is my ignorance do tell me please.

**Comment by danielroe** [comment]
It's possible it's not easy to see, but that `link` goes within a `meta` property:

```js
import { defineNuxtConfig } from 'nuxt3';

export default defineNuxtConfig({
  meta: {
    link: [
      {
        rel: 'stylesheet',
        type: 'text/css',
        href: 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700',
      },
    ],
  },
})
```
