### ISSUE TITLE
Vite HMR stops working, when importing a async composable twice

### ISSUE THREAD

**Issue by chrispreisler** [nuxt/framework#1083]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.5.0`
- Nuxt Version:     `3-3.0.0-27238235.a1bcc53`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

I have created a composable to fetch data. I import the composable two times. Once in the app.vue and once in the pages/[..slug].vue. The code itself is working as intended, but when I change something in one of the files hmr stops working and I get an error, but only when I change something the app.vue.

Thanks for your help guys.

### Reproduction

https://stackblitz.com/edit/github-zdtycq?file=app.vue

### Logs

```shell
I got this logs, when changing something in the app.vue

runtime-core.esm-bundler.js:140 TypeError: instance.update is not a function
    at runtime-core.esm-bundler.js:62
    at Array.forEach (<anonymous>)
    at rerender (runtime-core.esm-bundler.js:54)
    at Object.rerender (runtime-core.esm-bundler.js:137)
    at app.vue:13
    at client.ts:424
    at client.ts:345
    at client.ts:205
    at Array.forEach (<anonymous>)
    at queueUpdate (client.ts:205)
(anonymous) @ runtime-core.esm-bundler.js:140
(anonymous) @ app.vue:13
(anonymous) @ client.ts:424
(anonymous) @ client.ts:345
(anonymous) @ client.ts:205
queueUpdate @ client.ts:205
async function (async)
queueUpdate @ client.ts:201
(anonymous) @ client.ts:72
handleMessage @ client.ts:70
(anonymous) @ client.ts:44
runtime-core.esm-bundler.js:141 [HMR] Something went wrong during Vue component hot-reload. Full reload required.
```

**Comment by danielroe** [comment]
|


T[

**Comment by chrispreisler** [comment]
Yes, thanks so much for looking into that and all the great effort you guys put in this framework.
