### ISSUE TITLE
Router.push auto change page

### ISSUE THREAD

**Issue by productfrontenddeveloper** [nuxt/framework#1095]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3-3.0.0-27237303.6acfdcd`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.0.6`
------------------------------

### Describe the bug

pages index.vue add lists router.push but auto change page

https://github.com/productfrontenddeveloper/nuxt3-app/blob/9ab4aff8af6fe550294ce35930266dc0297b3e34/pages/index.vue#L48

https://user-images.githubusercontent.com/38668796/137527128-8e31fbf9-fc2e-4faa-84b8-52bb4923201f.mp4

### Reproduction

https://github.com/productfrontenddeveloper/nuxt3-app/tree/router_bug

**Comment by danielroe** [comment]
The `router.push` is being evaluated when the array is created. Instead, make this change:
```diff
        const lists = ref<links[]>([
-         { id: 1, title: 'Pinia Store', url: router.push({ name: 'pinia' }) },
+         { id: 1, title: 'Pinia Store', url: () => router.push({ name: 'pinia' }) },
          { id: 1, title: 'Modal', url: '' },
          { id: 1, title: 'New soon...', url: '' },
        ])
```
