### ISSUE TITLE
useAsyncData error on dev, but ok in production

### ISSUE THREAD

**Issue by zernonia** [nuxt/framework#1097]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.16.1`
- Nuxt Version:     `3-3.0.0-27238235.a1bcc53`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `vite`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.0.0`

### Describe the bug

useAsyncData returns error (in console) and no data on development, but ok in production

### Reproduction

Reproduction showing error and no data on dev
https://codesandbox.io/s/lingering-sky-gc125?file=/app.vue

Image showing no problem when I run `yarn build` then `yarn start`

![image](https://user-images.githubusercontent.com/59365435/137527540-097e3e9d-9712-47b7-9125-5cead245155c.png)

***

Suspecting it is causes by async function `supabase.from("countries").select("*").limit(5)` does not have  `.catch` 

### Logs
```
[Vue warn]: Hydration text content mismatch in <p>:
- Client: {
  "data": null,
  "pending": false,
  "error": "TypeError: __vite_ssr_import_0__.default is not a function"
}
- Server: {
  "data": null,
  "pending": false,
  "error": null
} 
  at <App> 
  at <NuxtRoot> 
```

**Comment by wobsoriano** [comment]
Temporary the temporary fix

```ts
export default defineNuxtConfig({
  vite: false
});
```

**Comment by zernonia** [comment]
> Try the temporary fix
> 
> ```ts
> export default defineNuxtConfig({
>   vite: false
> });
> ```

Thank you for the suggestion. But my project is using some Vite plugins now, so I can't disable it unfortunately.

**Comment by danielroe** [comment]
This is no longer reproducible in that sandbox.
