### ISSUE TITLE
<template> Shows errors on variables despite being defined in <script> with Volar & Typescript

### ISSUE THREAD

**Issue by Luffyyy** [nuxt/framework#1130]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.6.2`
- Nuxt Version:     `2.16.0-27226092.034b9901`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27238235.a1bcc53`
------------------------------

### Describe the bug

![image](https://user-images.githubusercontent.com/11510099/137603950-9c38bd44-4e6c-4849-b2ee-b2a1021344ee.png)

Basically the image, I installed a clean Nuxt 2, converted it to bridge, made a tsconfig as described here https://github.com/nuxt/framework/issues/1082#issuecomment-944343764, added the following (from what I found regarding using Vue 2 with Volar): 
```json
    "compilerOptions": {
      "types": [
        "unplugin-vue2-script-setup/types"
      ]
    },
    "vueCompilerOptions": {
      "experimentalCompatMode": 2
    },
```
Tried installing @vue/runtime-dom and unplugin-vue2-script-setup, but nothing. The error is still there.
I tried defining them via options API too, seems to be broken there too.

I might have done something wrong, I mostly use JS but wanted to try TS at some point. Could also be a Volar issue, but I'm unsure. It works fine with Nuxt 3 or just Vue 3.

### Reproduction

https://github.com/Luffyyy/nuxt2-bridge-issue

**Comment by danielroe** [comment]
I don't believe this is a Nuxt Bridge issue; rather, it's a tooling issue (as `<script setup>` isn't squarely in the Vue 2 tooling).

Consider [raising an issue with Volar](https://github.com/johnsoncodehk/volar/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

**Comment by danielroe** [comment]
@johnsoncodehk Even without the path aliases in `tsconfig.json`, the same issue shows up... Do you have any more guidance for us?

**Comment by johnsoncodehk** [comment]
@danielroe After I reinstalled the repro case and built it, there is no problem, because `./.nuxt/tsconfig.json` is gone. What can I do to reproduce your problem?

<img width="275" alt="螢幕截圖 2021-11-03 下午12 50 47" src="https://user-images.githubusercontent.com/16279759/140011354-d09161a3-93ac-405b-93a2-c688c524e9a4.png">

**Comment by pleclech** [comment]
Hi,
Having the same problem, it seems that the line 

>       "vue": [
>        "node_modules/@nuxt/bridge/dist/runtime/vue2-bridge"
>      ],

in ./.nuxt/tsconfig.json break Volar type checking.
