### ISSUE TITLE
how to add variables of process.env in nuxt3  ?

### ISSUE THREAD

**Issue by sea-lanya** [nuxt/framework#1217]
### Environment

nuxt3 ^3.0.0-27243104.5e903ae
mac

### Describe the bug

I try all the methods but not success

### Reproduction

I find some solutions like https://github.com/nuxt/framework/pull/1086 but not success

**Comment by lukaszflorczak** [comment]
I don't see any difference between Nuxt 2. 

```ts
publicRuntimeConfig: {
    MY_VARIABLE: process.env.MY_VARIABLE
}
```

I use `3.0.0-27242646.117b3aa` now and it works.

**Comment by mlsjla** [comment]
thank @wobsoriano   @lukaszflorczak 

but my code include some others sdk 

sdk code require process.env.xxxxxx settings

so  I want to konw how to add variables like   process.env.SECRET

if I use  like this 
```
const config = useRuntimeConfig()
config.secret
```

I must change sdks code .... But I  can't do this.

**Comment by wobsoriano** [comment]
> thank @wobsoriano @lukaszflorczak
> 
> but my code include some others sdk
> 
> sdk code require process.env.xxxxxx settings
> 
> so I want to konw how to add variables like process.env.SECRET
> 
> if I use like this
> 
> ```
> const config = useRuntimeConfig()
> config.secret
> ```
> 
> I must change sdks code .... But I can't do this.

Do you have a `.env` file?
