### ISSUE TITLE
Nuxt 3 - fresh install on Windows - cannot find module

### ISSUE THREAD

**Issue by mnlj** [nuxt/framework#1226]
### Environment

Nuxt CLI v3.0.0-27243104.5e903ae                                                                              10:48:58
RootDir: c:\testing\nuxt3-app                                                                                 10:49:00
Nuxt project info:                                                                                            10:49:00

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27243104.5e903ae`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

Nuxt CLI reports it cannot find module, the web page is stuck on "Starting nuxt..." with NuxtJS logo and light/dark mode flashing background.

### Reproduction

Followed the New project in [docs](https://v3.nuxtjs.org/getting-started/installation#new-project).

```
npx nuxi init nuxt3-app
cd nuxt3-app
yarn install
yarn dev -o
```

(happens both with yarn and npm)

The directory of requested module, "nuxt3-app\.nuxt\server", doesn't exist. I only see "server" directory inside "nuxt3-app\.nuxt\dist\server", but that one doesn't have index.mjs

### Logs

```shell
Nuxt CLI v3.0.0-27243104.5e903ae                                                                          10:52:05
                                                                                                          10:52:05
  > Local:    http://localhost:3000/
  > Network:  http://172.24.96.1:3000/
  > Network:  http://172.18.48.1:3000/
  > Network:  http://192.168.56.1:3000/
  > Network:  http://192.168.86.79:3000/

i Vite warmed up in 685ms                                                                                 10:52:08
√ Generated nuxt.d.ts                                                                                     10:52:08
√ Vite server built in 956ms                                                                              10:52:09
√ Nitro built in 81 ms                                                                                    10:52:09

 WARN  [worker] Cannot find module 'c:\testing\nuxt3-app\.nuxt\server\index.mjs' imported from c:\testing\nuxt3-app\.nuxt\nitro\index.mjs

  at new NodeError (node:internal/errors:371:5)
  at finalizeResolution (node:internal/modules/esm/resolve:416:11)
  at moduleResolve (node:internal/modules/esm/resolve:932:10)
  at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:1044:11)
  at Loader.resolve (node:internal/modules/esm/loader:89:40)
  at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by danielroe** [comment]
This is no longer reproducible. If you're still experiencing this, would you create a reproduction please?

**Comment by mnlj** [comment]
@danielroe I'm afraid this is **still reproducible** using the reproduction from the original post. The only pre-requisite is to use Windows 10 operating system. I've tried it right now, with Nuxt updated to (at the moment latest) `3.0.0-27264486.37f86a0`, on latest Node versions 14.18.1 and 16.13.0. The logs output is exactly the same as the one the original post.

**Comment by danielroe** [comment]
@mnlj In that case, would you provide a reproduction?

**Comment by danielroe** [comment]
By reproduction, I mean a code sample that I can clone and test out myself.

> Please provide a link to a repo that can reproduce the problem you ran into. A [minimal reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction) is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided after we might close it.

**Comment by mnlj** [comment]
That's because it's a **fresh** install using only the four commands specified above, with zero additional modifications.

>...minimal reproduction is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem...

But sure, I've pushed the folder as is into https://github.com/mnlj/nuxt3-1226.

**Comment by danielroe** [comment]
Thank you; I'll have a look.

I did follow the instructions you provided above on Windows and was unable to reproduce, which is why I asked 🙃

**Comment by mnlj** [comment]
Ok, I understand :) Well I'm not sure if it is in some way related to some additional required Node configuration (as the error suggests it's about ES modules and imports), or if using NVM can have some effect on that as well. I would like to help debug it, but as it is, I'm not even sure where to start...

**Comment by wjk22** [comment]
This problem is a directory problem most likely due an incorrect path, so far the work around develop from C:\dev\appname ..

**Comment by phoenix-ru** [comment]
This always reproduces for me on latest bridge, regardless of OS or project. The same applies for my colleagues.

I migrate an existing Nuxt 2 project to Nuxt Bridge.

Output of `pwd`:
`/home/marsel/work/icons8/icons8-moose`

Output of `npx nuxi info`:
- Operating System: `Linux`
- Node Version:     `v14.19.2`
- Nuxt Version:     `2.15.8`
- Package Manager:  `npm@8.9.0`
- Builder:          `webpack`
- User Config:      `server`, `serverMiddleware`, `head`, `env`, `render`, `build`, `router`, `loading`, `sentry`, `css`, `modules`, `i18n`, `plugins`, `buildModules`, `styleResources`, `favicon`, `bridge`
- Runtime Modules:  `@nuxtjs/i18n@7.2.2`
- Build Modules:    `@nuxtjs/style-resources@1.2.1`, `@nuxt/bridge@3.0.0-27530716.c4f8671`

**Comment by kailight** [comment]
In my case the issue was related to using c:\ drive (in lowercase), switching to C:\ (uppercase) solved my issue

**Comment by Nathan-Binkley** [comment]
Having the same issue. I've got a folder named `Project` but the output is `project`. I've tried doing a find and replace for all instances of `project` -> `Project` but when I re-ran the `npm run dev` command, the changes I made go back to lowercase. I think this might be the source of this issue but I can't be sure if it's the case.

**Comment by rendomnet** [comment]
Same error here.

**Comment by bfond82** [comment]
Same here, on Windows, on a fresh install.

**Comment by mnlj** [comment]
On my current setup it always appears after restarting pc, goes away after I switch node versions with nvm (to random version and back to latest). On different pc I can't make it to work at all. Something somewhere, in the whole chain going from nuxt3 through nitro down to node itself is most likely taking windows paths case sensitively and the way the error presents itself to the developer makes it very hard to debug.
