### ISSUE TITLE
Error Unhandled error during execution of async component loader when alias is used

### ISSUE THREAD

**Issue by jd-0001** [nuxt/framework#1229]
### Environment

Nuxt CLI v3.0.0-27243104.5e903ae                                                                                                                       16:08:42
RootDir: /private/tmp/template                                                                                                                         16:08:42
Nuxt project info:                                                                                                                                     16:08:42

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27243104.5e903ae`
- Package Manager:  `npm`
- Bundler:          `Vite`
- User Config:      `alias`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

[Vue warn]: Unhandled error during execution of async component loader. Also I don't get hot reloading in my app.

### Reproduction

https://codesandbox.io/s/quirky-goodall-edfr7?file=/app.vue

### Additional context

Hot reload is not working for me. Check the log to see the error/warning

**Comment by danielroe** [comment]
Is this still an issue for you? If so, would you update your reproduction? (I can't now access it.)

**Comment by jd-0001** [comment]
I haven't tested it recently as I am now moved to another project.

Will reopen once I come and if I get the issue.

**Comment by danielroe** [comment]
@lukasborawski Would you open a new issue with a reproduction? 🙏

**Comment by lukasborawski** [comment]
@danielroe Here you go. https://github.com/nuxt/framework/issues/8919 Thanks for the quick reaction, if possible. Cheers.
