### ISSUE TITLE
globalName, globals and publicPath settings have no effect

### ISSUE THREAD

**Issue by stewones** [nuxt/framework#1254]
### Environment

Nuxt CLI v3.0.0-27243104.5e903ae                                                                                                                              16:12:01
RootDir: /Users/stewan/dev/stewan-nuxt                                                                                                                        16:12:02
Nuxt project info:                                                                                                                                            16:12:02

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.6`
- Nuxt Version:     `3.0.0-27243104.5e903ae`
- Package Manager:  `npm`
- Bundler:          `Vite`
- User Config:      `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

`globalName`, `globals` and `publicPath` settings have no effect

### Reproduction

I followed the basic setup for nuxt3 on docs

and tried this config

```
import { defineNuxtConfig } from "nuxt3";

export default defineNuxtConfig({
  globalName: "__stew",
  globals: {
    id: () => `__stew`,
  },
  css: ["~/assets/css/tailwind.css"],
  build: {
    publicPath: "stew/",
    postcss: {
      postcssOptions: {
        plugins: {
          tailwindcss: {},
          autoprefixer: {},
        },
      },
    },
  },
});

```

nothing works when building for production. in dev publicPath sometimes work, sometimes not

**Comment by stewones** [comment]
@pi0 please let me know if is whitelabeling a thing in your radar

**Comment by coryvirok** [comment]
I'm expecting that something like the `globalName` will be added back in once Nuxt3 goes GA. There were a ton of requests for it due to what @stewones mentioned. My 2 primary needs for it are related to hiding the tech stack and changing the CSS for the `<body><div id="__nuxt">` element. Without being able to change the global name for that element, Nuxt users will need to add CSS to their global styles that reference a DOM id that is hidden, (read: not configurable or documented) and could change at any time. 

I suppose a partial solution for me would be if we could change the attrs for that element via the meta composable, like we do for head and body. But that still leaves the tech-stack obfuscation issue.

**Comment by n0ch4t** [comment]
Is there any change?

**Comment by phlqp** [comment]
I need to get rid of __nuxt id in the html, please re-open this request

**Comment by cliqer** [comment]
I need to be able to change the __nuxt id to.
This is also a security concern, and Wappalyzer can extract tech used.

**Comment by Hyperblaster** [comment]
Yeah, this needs to be reopened. It's a step backwards from nuxt 2.

**Comment by 53rg0** [comment]
For many clients, this is important in terms of branding, and for developers, it is important to hide the technology from "auto-search" scripts. By removing this feature, you have added a big minus for NUXT3 and made it more obvious choice to NUXT2. I really hope you bring the globalName feature back.

**Comment by stewones** [comment]
I'm not worried et all. Those wrong design decisions made me open my mind get to try out Qwik. Today I'm pretty happy with it and will never look back 😎

**Comment by 53rg0** [comment]
> I'm not worried et all. Those wrong design decisions made me open my mind to get and try out [Qwik](https://qwik.builder.io/). Today I'm pretty happy with it and will never look back 😎

Nuxt in the plane of everything has gone much further. I just want this little thing back. The absence of this feature really forced many to switch to another technology.
