### ISSUE TITLE
[CF] External dependencies outside root folder not found (monorepo)

### ISSUE THREAD

**Issue by manniL** [nuxt/framework#126]
Hey 👋🏻

I'm here again, reporting a similar bug like #80, again due to a monorepo structure but this time limited to the CloudFlare preset.

## Reproduction

1. Clone the repo https://github.com/manniL/nitro-monorepo-vue-not-found
2. Install deps (`yarn`)
3. (optional) Run `cd packages/app && yarn dev` -> this works fine ✅
4. Run `NITRO_PRESET=cloudflare yarn generate` (still in the app subfolder) to generate your worker
5. See the following error

![image](https://user-images.githubusercontent.com/640208/116433583-ef8ce780-a849-11eb-9680-5c3deeb7b812.png)

The first trace points directly to `const Vue = __webpack_require__(/*! vue */ "vue");`

<details>
<summary>Stack trace</summary>

 FATAL  [worker] Cannot read property 'use' of undefined                                                                                                                                                                      17:47:42

  at Module.<anonymous> (node_modules/.cache/nuxt/dist/server/server.js:3852:24)
  at __webpack_require__ (node_modules/.cache/nuxt/dist/server/server.js:27:30)
  at Object.<anonymous> (node_modules/.cache/nuxt/dist/server/server.js:1629:18)
  at __webpack_require__ (node_modules/.cache/nuxt/dist/server/server.js:27:30)
  at node_modules/.cache/nuxt/dist/server/server.js:118:18
  at node_modules/.cache/nuxt/dist/server/server.js:121:1
  at createCommonjsModule (node_modules/.cache/nuxt/nitro/index.js:656:9)
  at Object.<anonymous> (node_modules/.cache/nuxt/nitro/index.js:14363:14)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │   ✖ Nuxt Fatal Error                                            │
   │                                                                 │
   │   TypeError: [worker] Cannot read property 'use' of undefined   │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.

</details>

In this case, `Vue.use` is called somewhere throughout the application but couldn't be found.

## Workaround

A very naive workaround is to change the [`moduleDirectories`](https://github.com/nuxt/framework/blob/main/packages/nitro/src/rollup/config.ts#L204-L209) to include `    upath.resolve(nitroContext._nuxt.rootDir, "../../node_modules")`. Then, the above error does not occur anymore. 

Of course, this isn't optimal but I'm not sure what the best strategy would be here for "full monoerepo support". Maybe making the `moduleDirectories` configurable? 🤔

`nohoist`ing some packages like `vue` would work as well but has major disadvantages (e.g. lots of package dupes, errors on circular deps etc).

**Comment by pi0** [comment]
I believe this should be fixed by the latest nitro improvements. Please ping to reopen if not.
