### ISSUE TITLE
composable auto import improvements

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1273]
Follow up #1176

- [ ] Cache parsing results when timestamps are not changed
  - pending for general caching to be applied for components discovery)
- [x] Allow overriding composables by user instead of warning + disable
  - pending for standardized `extend` (nuxt.config) and `level` (components dir) 
- [x] #2167
  - allows using composables in non-sfc files or situations auto-import is not possible reusing existing infrastructure
 - [x] #2170

**Comment by danielroe** [comment]
@Norel Auto imports don't currently work within the server scope. They just work within the Vue portion of your app.
