### ISSUE TITLE
.graphql, .gql import error

### ISSUE THREAD

**Issue by ririen** [nuxt/framework#1283]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27245461.ffb05fc`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `ssr`, `buildModules`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.0.3`
------------------------------

### Describe the bug

Rollup does not support graphql files.

```sh
 ERROR  Rollup error: Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)  
```

### Reproduction

Import graphql file like:

`import Product from './graphs/product.graphql';`

**Comment by fanckush** [comment]
Check out https://github.com/hronro/vite-plugin-graphql as a temp workaround

**Comment by ririen** [comment]
> Check out https://github.com/hronro/vite-plugin-graphql as a temp workaround

How exactly do I use this with Nuxt 3?

**Comment by LouisMazel** [comment]
@ririen directly in you `nuxt.config.ts`

```js
export default defineNuxtConfig({
  vite: {
    plugins: [graphqlPlugin],
  },
})
```

**Comment by ririen** [comment]
@LouisMazel @fanckush I checked, nothing has changed. This workaround is not working.

**Comment by fanckush** [comment]
I got to work but with another plugin. Here's how you can get it to work:

Frist install the [rollup graphQL Plugin](https://www.npmjs.com/package/@rollup/plugin-graphql): 
``` zsh
yarn add -D @rollup/plugin-graphql
```

``` js
// nuxt.config.ts
import { defineNuxtConfig } from "nuxt3";
import graphql from '@rollup/plugin-graphql';

export default defineNuxtConfig({
  vite: {
    plugins: [graphql()],
  },
});
```

**Comment by danielroe** [comment]
Closing as this isn't a bug. Likely integrations with graphql will be implemented with nuxt modules.
