### ISSUE TITLE
Document migration guide from `@nuxtjs/composition-api`

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1321]
[nuxt-community/composition-api](https://github.com/nuxt-community/composition-api) introduced an initial version of composition API support for nuxt 2 with the addition of some `define*` type helpers.

By introducing bridge, we do not support this module anymore due to incompatibility issues with nuxt 3 but providing a compatibility replacement makes it easier to migrate. Yet some messages are confusing as there is no clear migration path from `@nuxtjs/composition-api` to `@nuxt/bridge` (and replacement for type helpers)

**Comment by Atinux** [comment]
High priority
