### ISSUE TITLE
useFetch is undefined

### ISSUE THREAD

**Issue by cpt-n3mo** [nuxt/framework#1326]
### Environment

Nuxt project info:                                                                                                                           18:38:21

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.11.1`
- Nuxt Version:     `0.0.0`
- Package Manager:  `unknown`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

when using useFetch inside <script setup> or setup() 
useFetch is not defined
importing from `#app`  does not seem to work either

### Reproduction

create a new nuxt2 project with npx create-nuxt-app.
follow doc to convert to bridge version.
use useFetch somewhere.
page load fails with status 500 Object(...) is not a function
trying to log useFetch gives undefined

### Additional context

non

### Logs

```shell
500 Object(...) is not a function
```

**Comment by danielroe** [comment]
closed in https://github.com/nuxt/framework/issues/1321
