### ISSUE TITLE
In Dev, New Pages 404 Until You Restart The Server

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/framework#1367]
### Environment

Nuxt CLI v3.0.0-27247485.fb4359e
RootDir: /Users/joshdel/Documents/code/nuxt3
Nuxt project info:
------------------------------
- Operating System: `Darwin` (macOS Big Sur 11.6)
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.0.0-27247485.fb4359e`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

When running Nuxt 3 in dev mode, if you create a new file it will show a 404 in your browser until you stop/start your dev server.

### Reproduction

1. yarn dev
2. create a new file in /pages (notice Vite runs)
3. fill in the new page with content (notice Vite runs)
4. go to the new route in your browser (notice 404 error)
5. stop/start dev (notice page works)

**Comment by adamkif** [comment]
I'm still having the same issue, is there a solution for that?

- Operating System: `Mac Monterey`
- Node Version: `v17.0.0`
- Package Manager: `Npm`
- Bundler: `Vite`

**Comment by danielroe** [comment]
@adamkif What version of Nuxt are you on? Would you provide a reproduction?

**Comment by adamkif** [comment]
Nuxt CLI:  `v3.0.0-27258467.4e424d0`

**Comment by danielroe** [comment]
@adamkif How about your version of untyped? It needs to be 0.2.11 to benefit from the fix.

**Comment by adamkif** [comment]
@danielroe untyped version: `0.2.10` ,, Do  I need to change my node version or what ( `i have v17 `)? Because I just created the project yesterday

**Comment by danielroe** [comment]
The fix was only released this morning. You can try upgrading with `yarn upgrade untyped`

**Comment by adamkif** [comment]
@danielroe I upgrade the project and I still have the same problem 

untyped: `0.2.11`
Node : `v17.0.0`

**Comment by adamkif** [comment]
@danielroe this is my repo: https://github.com/adamkif/Nuxt-Hashnode

**Comment by hecktarzuli** [comment]
I removed my yarn.lock and node_modules, and reinstalled everything.  The problem still exists for me as well.

untyped: `0.2.11`
nuxt: `3.0.0-27265756.d30f4d8`
node: `v14.18.0`

**Comment by flakerimi** [comment]
After Investigation took place in nuxi package, I saw that it has to be /app/pages rather than /pages inorder to trigger app restart.

**Comment by catch6** [comment]
same for me

node: 16.13.1
nuxt: v3.0.0-27338323.1e98259

**Comment by craigharman** [comment]
This issue has been closed but is still happening for me in `3.0.0-rc.4` and Node `16.15.1`.

**Comment by danielroe** [comment]
@craigharman There was a more recent fix (https://github.com/nuxt/framework/pull/5002). But that should have been live in rc4 - so would you please open a new issue with a reproduction and more info?

**Comment by craigharman** [comment]
Have done. #5766 
Thanks @danielroe
