### ISSUE TITLE
Exports is not defined in ES module scope

### ISSUE THREAD

**Issue by eakhadov** [nuxt/framework#1380]
### Environment

------------------------------
- Operating System: `Windows_NT - Windows 10 Pro, Version 21H1 (OS Build 19043.1288), WFEP 120.2212.3920.0`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27248715.54549cf`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `srcDir`, `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

When using a third-party src folder (which is not the current folder) and when server rendering is enabled, an error 500 appears - `exports is not defined in ES module scope`

### Reproduction

1. run `npx nuxi init` and `yarn install`
2. create `src` dir and second `app.vue` for example (or pages/index.vue)
3. run yarn dev

I couldn't change the node js version on stackblitz and codesandbox, so I'm attaching my git repo for example
https://github.com/eakhadov/nuxt3-bug

### Additional context

`srcDir: './src', ssr: true` = error
`srcDir: './src', ssr: false` = ok

`srcDir: '.', ssr: true` = ok
`srcDir: '.', ssr: false` = ok

### Logs

```shell
Nuxt CLI v3.0.0-27248715.54549cf                                                                                                                              00:19:35  
                                                                                                                                                              00:19:35  
  > Local:    http://localhost:3000/
  > Network:  http://192.168.208.1:3000/
  > Network:  http://172.24.112.1:3000/
  > Network:  http://192.168.1.3:3000/
  > Network:  http://172.18.192.1:3000/

√ Generated nuxt.d.ts                                                                                                                                         00:19:41
i Vite warmed up in 1334ms                                                                                                                                    00:19:42
√ Vite server built in 2178ms                                                                                                                                 00:19:43
√ Nitro built in 288 ms                                                                                                                                       00:19:43
exports is not defined in ES module scope
  at $id_29efbadd (file:///C:/Users/Emil/Desktop/nuxt-err/.nuxt/dist/server/server.mjs:88:23)
  at __instantiateModule__ (file:///C:/Users/Emil/Desktop/nuxt-err/.nuxt/dist/server/server.mjs:8279:9)  
  at __ssrLoadModule__ (file:///C:/Users/Emil/Desktop/nuxt-err/.nuxt/dist/server/server.mjs:8227:25)     
  at ssrImport (file:///C:/Users/Emil/Desktop/nuxt-err/.nuxt/dist/server/server.mjs:8251:13)
  at $id_0a51e162 (file:///C:/Users/Emil/Desktop/nuxt-err/.nuxt/dist/server/server.mjs:15:37)
  at __instantiateModule__ (file:///C:/Users/Emil/Desktop/nuxt-err/.nuxt/dist/server/server.mjs:8279:9)  
  at __ssrLoadModule__ (file:///C:/Users/Emil/Desktop/nuxt-err/.nuxt/dist/server/server.mjs:8227:25)     
  at file:///C:/Users/Emil/Desktop/nuxt-err/.nuxt/dist/server/server.mjs:8292:22
  at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
  at async Loader.import (node:internal/modules/esm/loader:178:24)
```

**Comment by eakhadov** [comment]
Hi @cyruscollier. My win version - `Windows 10 Pro, Version 21H1 (OS Build 19043.1288), WFEP 120.2212.3920.0`

**Comment by TheLearneer** [comment]
@pi0 @danielroe  It seems this issue was closed but this issue still persists on latest commit as of writing this i.e. `^3.0.0-27264278.aba2d22`

And like mentioned above setting `ssr` to false solves it, but if ssr is true this error shows up

**Comment by danielroe** [comment]
@TheLearneer Would you provide a reproduction in that case?
