### ISSUE TITLE
More Fulsome Documentation on Components Directory

### ISSUE THREAD

**Issue by ratfoot** [nuxt/framework#1397]
Nested Directories in /Components don't  work out of the box in the same way as Nuxt 2:

`components:{
  dirs: [
    '~/components',
    '~/components/base/foo'
  ]
}
` 

https://nuxtjs.org/docs/directory-structure/components#nested-directories

Taking the following statement from docs as promise:

"The components/ directory is where you put all your Vue components which can then be imported inside your pages or other components "

A complex use case (not just flat directory structure and one simple component) would be greatly appreciated in the docs / examples.

Specifically it would be useful to know

-how to deal with nested directories structures 
-are imports required on components that use components? (the promise above is they shouldn't)
-is there a better way to understand bad linkages than the cryptic "500 - Cannot read properties of undefined (reading 'map')?

also:  "[Vue warn]: Failed to resolve component: COMPONENTNAME"

from where? which other page/component is trying to resolve COMPONENTNAME?

Do I need to disable vite in nuxt config like the examples? Why?

Any direction on best practices, and simple project structure would be awesome, thanks!

``

**Comment by danielroe** [comment]
@clemcode Do you think we can close this, or do we need more content?

https://v3.nuxtjs.org/guide/directory-structure/components#components-directory and https://v3.nuxtjs.org/examples/auto-imports/components.
