### ISSUE TITLE
Documentation - data-fetching

### ISSUE THREAD

**Issue by leku451** [nuxt/framework#1415]
### Environment

N/A

### Describe the bug

Documentation could be updated to clarify better or use better verbage to explain the differences between the two different proposed ways to perform data fetching with nuxt v3.

https://v3.nuxtjs.org/docs/usage/data-fetching

,,,
useAsyncData
Within your pages, components and plugins you can use useAsyncData to get access to data that resolves asynchronously.
,,,

,,,
useFetch
Within your pages, components and plugins you can use useFetch to **get universally fetch** from any URL.
,,,

The problem I mostly have with on this page is what is highlighted in bold, I think this needs to be rewritten

### Reproduction

N/A

**Comment by danielroe** [comment]
I think this is now resolved but let me know if you think differently and we can reopen...
