### ISSUE TITLE
Documentation - firebase deployment / hosting

### ISSUE THREAD

**Issue by leku451** [nuxt/framework#1422]
### Environment

Nuxt CLI v3.0.0-27238235.a1bcc53                                                                             13:16:56
RootDir: /Users/leku/src/nuxt3-chaseapp                                                                  13:16:58
Nuxt project info:                                                                                           13:16:58

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3-3.0.0-27238235.a1bcc53`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `srcDir`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

Nuxt 3 documentation for firebase hosting - https://v3.nuxtjs.org/docs/deployment/firebase/

When deploying with firebase hosting per the documentation and example, I am getting this error:

Error: Could not detect language for functions at .output/server

### Reproduction

firebase deploy

### Additional context

I'm unable to deploy to firebase hosting 

### Logs

```shell
firebase deploy

=== Deploying to 'XXXXX'...

i  deploying functions, hosting

Error: Could not detect language for functions at .output/server
```

**Comment by Sangarllo** [comment]
I got the same problem when deploying, but this is a problem deploying functions. If you just want to deploy hosting, you have to use:

`firebase deploy --only hosting`
