### ISSUE TITLE
Nuxt Page Transition Property Not Working

### ISSUE THREAD

**Issue by Kunoacc** [nuxt/framework#1440]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3-3.0.0-27237303.6acfdcd`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

The page transition property doesn't work

### Reproduction

https://codesandbox.io/s/immutable-wood-pk223?file=/pages/index.vue

**Comment by nandi95** [comment]
Transitions are not a thing yet in nuxt3 by the looks of it: https://v3.nuxtjs.org/getting-started/migration#nuxt-2-to-nuxt-3
