### ISSUE TITLE
Allow config extending

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1501]
Moving [nuxt-extend](https://github.com/nuxt-contrib/nuxt-extend) to `@nuxt/kit` and bridge allows starting natively supporting extending for multi-app and theming support. (some features like extending `pages/` would be exclusive to Nuxt 3 due to limitations of Nuxt 2. See https://github.com/nuxt/nuxt.js/pull/5818)

**Comment by danielroe** [comment]
This was implemented in https://github.com/nuxt/framework/pull/3008, with follow-up work in https://github.com/nuxt/framework/issues/3222.
