### ISSUE TITLE
Hot Reload doesn't work

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#1529]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27255771.f78ec93`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.0`
------------------------------

### Describe the bug

https://user-images.githubusercontent.com/38668796/139138186-7cd201f5-ab03-4a38-93bc-46ebe6cdc2d8.mp4

### Reproduction

https://github.com/productdevbook/nuxt3-app

### Additional context

This seems to me to be in vite.  because when I translate css, it fixes the project. There seems to be a problem with compiling Sass. but we're not entirely sure

### Logs

```shell
✔ Vite server built in 111ms
(node:15424) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by danielroe** [comment]
closing to follow in https://github.com/nuxt/framework/issues/1036

**Comment by FabioDavi** [comment]
I had the same problem but, doing nothing to fix.. I discover it works only at Network:  http://172.21.21.166:3000/ and not at Local:    http://localhost:3000/

**Comment by mirumirumi** [comment]
For all those for whom HMR does not work in WSL2,

First, as @FabioDavi  said, access with IP ( `172.26.21.102` etc...) instead of `localhost`. to access the dev server.
Next, add the following to `nuxt.config.ts` as often mentioned in other threads.

```js
  vite: {
    server: {
      watch: {
        usePolling: true, 
      },
    },
  },
```

This makes HMR working fine in my case!

(This workaround may cause Vue to issue a hydration warning if a hot reload rewrites an HTML element.
But I believe this is not inherently a problem in the sense that I want to visually see the code changes.)

**Comment by RodrigoReyes-vw** [comment]
none of the solutions seems to work for me, any other ideas?

**Comment by ymansurozer** [comment]
> I had the same problem but, doing nothing to fix.. I discover it works only at Network: http://172.21.21.166:3000/ and not at Local: http://localhost:3000/

This is the only thing that worked after trying everything in this thread and #1036. I finally have a working HMR!

**Comment by Thorin217** [comment]
For all those who still have the problem,

Make sure you haven't created a configuration file without the default export.

Example: (app.config.ts)

and they always check the browser console for some error.

**Comment by Venegrad** [comment]
same issue

**Comment by ahmetonurslmz** [comment]
I encounter the same issue and have fixed via this solution.

[https://en.ahmetonursolmaz.com.tr/nuxt-hot-reload-isnt-working/](https://en.ahmetonursolmaz.com.tr/nuxt-hot-reload-isnt-working/)

**Comment by Ghustavh97** [comment]
I had to open port `24678` for mine to work.
