### ISSUE TITLE
WARN  [SSR] Error transforming on windows

### ISSUE THREAD

**Issue by andysay** [nuxt/framework#1559]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-27257216.f5aea9f`
- Package Manager:  `npm`
- Bundler:          `Vite`
- User Config:      `vite`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

 WARN  [SSR] Error transforming ./node_modules/hookable/dist/index.mjs: Error: Missing "./dist/index.mjs" export in "hookable" package                                                    

 WARN  [SSR] Error transforming ./node_modules/vue/server-renderer/index.js: Error: Missing "./server-renderer/index.js" export in "vue" package                                                      

 WARN  [SSR] Error transforming ./node_modules/murmurhash-es/dist/index.mjs: Error: Missing "./dist/index.mjs" export in "murmurhash-es" package                                              

 WARN  [SSR] Error transforming ./node_modules/ohmyfetch/dist/index.mjs: Error: Missing "./dist/index.mjs" export in "ohmyfetch" package

### Reproduction

fresh install.

**Comment by parisnakitakejser** [comment]
Same issue when I use Windows 10, Node 16.13.0 both on yarn + npm

**Comment by Pamavoc** [comment]
The problem didn't exist a week ago, but now every project I start with Nuxt3 has this problem.

Tested with:
OS : Windows 10
PM : npm & yarn
Node version: 15, 16, 17

**Comment by vortechron** [comment]
i follow exactly as docs, face this issues

**Comment by vortechron** [comment]
I follow exactly as docs, but still got this issue

**Comment by lumavida** [comment]
same problem on Windows 10. 
But when i set `vite: false` in nuxt config it works.

**Comment by little3201** [comment]
same problem on windows 11.

![image](https://user-images.githubusercontent.com/34156125/139607806-7a9c9f45-6793-4bb7-9494-ef6b26427691.png)

**Comment by Nonovian** [comment]
Same on Windows 10
