### ISSUE TITLE
bug on server/api side.

### ISSUE THREAD

**Issue by andysay** [nuxt/framework#1561]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27257216.f5aea9f`
- Package Manager:  `npm`
- Bundler:          `Vite`
- User Config:      `vite`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

bug only on dev mode.
build woking fine.

i have next method.

 axios.post("/api/upload", formData, {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        });

formData have binary data.

on server 

        const uploadFolder = path.resolve('images')
        const form = formidable.IncomingForm();
        form.uploadDir = uploadFolder;

        form.parse(req, async (err, fields, files) => {
        console.log(fields);
        console.log(files);
        if (err) {
            console.log("Error parsing the files");
            }
        // Check if multiple files or a single file
           
        });

 ERROR  [proxy] write EPIPE                                                                                                                   10:14:03

  at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)

if server build and started will work fine.

### Reproduction

not have

**Comment by bfg-coding** [comment]
I can provide an example as I ran into this same issue


Client
``` ts
const fd = new FormData();
    fd.append("name", fileName);
    fd.append("image", file);

    axios.post("/api/avatars", fd, {
      headers: {
        'accept': 'application/json',
        'Accept-Language': 'en-US,en;q=0.8',
        'Content-Type': `multipart/form-data; boundary=${file._boundary}`,
      }
    }).then(resp => { console.log(resp)});
```

Nuxt3 `server/api/avatars`
```ts
import {IncomingMessage, ServerResponse} from "http";
import formidable from "formidable";

const form = new formidable.IncomingForm();

export default async (req: IncomingMessage, res: ServerResponse) => {
    form.parse(req, async (err, fields, files) => {
        console.log(err);
        console.log(fields);
        console.log(files);
    })
    res.end("Got data");
}
```

The error
```
 ERROR  [proxy] write EPIPE                                                                                                                                                                                                                                                                                                                                                                                                                                    

  at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
```

This code does work when the project is build using nuxt3 build script `nuxi build` and running npm start but will not work while using `nuxi dev`

**Comment by andysay** [comment]
> @danielroe I can provide an example as I ran into this same issue
> 
> Client
> 
> ```ts
> const fd = new FormData();
>     fd.append("name", fileName);
>     fd.append("image", file);
> 
>     axios.post("/api/avatars", fd, {
>       headers: {
>         'accept': 'application/json',
>         'Accept-Language': 'en-US,en;q=0.8',
>         'Content-Type': `multipart/form-data; boundary=${file._boundary}`,
>       }
>     }).then(resp => { console.log(resp)});
> ```
> 
> Nuxt3 `server/api/avatars`
> 
> ```ts
> import {IncomingMessage, ServerResponse} from "http";
> import formidable from "formidable";
> 
> const form = new formidable.IncomingForm();
> 
> export default async (req: IncomingMessage, res: ServerResponse) => {
>     form.parse(req, async (err, fields, files) => {
>         console.log(err);
>         console.log(fields);
>         console.log(files);
>     })
>     res.end("Got data");
> }
> ```
> 
> The error
> 
> ```
>  ERROR  [proxy] write EPIPE                                                                                                                                                                                                                                                                                                                                                                                                                                    
> 
>   at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
> ```
> 
> This code does work when the project is build using nuxt3 build script `nuxi build` and running npm start but will not work while using `nuxi dev`

yes approve it ! works only on build state.

**Comment by multiplehats** [comment]
Can confirm I run into the exact same issue.

**Comment by madebyfabian** [comment]
I ran into exactly this issue today, how did you resolve this?

**Comment by manniL** [comment]
> I ran into exactly this issue today, how did you resolve this?

Provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction) and there might be an answer to this question 😄

**Comment by madebyfabian** [comment]
@manniL Thanks for getting back on this, I've just found a solution at another issue https://github.com/unjs/h3/issues/43#issuecomment-1069225214. Would have provided one otherwise :)

**Comment by manniL** [comment]
Great to hear ☺️
