### ISSUE TITLE
node version detection is warning on compatible version

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#1586]
### Environment

codesandbox environment - linked below

### Describe the bug

```
 WARN  Current version of Node.js (14.18.1) is unsupported and might cause issues.
       Please upgrade to a compatible version (^14.16.0 || ^16.11.0 || ^17.0.0).
```

### Reproduction

https://codesandbox.io/s/wonderful-danny-qmodb?file=/nuxt.config.ts

**Comment by jiangzhangy** [comment]
I'm also getting this:

`Nuxt CLI v3.0.0-27258467.4e424d0                                                                                                                                                                                                 11:36:26

 WARN  Current version of Node.js (16.13.0) is unsupported and might cause issues.                                                                                                                                               11:36:27
       Please upgrade to a compatible version (^14.16.0 || ^16.11.0 || ^17.0.0).`

**Comment by danielroe** [comment]
If you're getting this, would you please run `yarn why semver` or `npm why semver` and let me know the output?

**Comment by danielroe** [comment]
This is an issue with rollup bundling semver into the `nuxi` bundle. The bundled file is (abbreviated):

```js
const Comparator$3 = comparator

class Comparator$2 {
  constructor (comp, options) {
    if (comp instanceof Comparator$2) {
      // ...
    }
  }
}

var comparator = Comparator$2;
```

In other words, we have a bit of mis-ordering of the file. So when `semver.satisfies` hits an error, because `Comparator$2` isn't an object, it swallows it and returns `false`.
