### ISSUE TITLE
defineNuxtPlugin doesn't provide inside nuxtApp

### ISSUE THREAD

**Issue by liqueflies** [nuxt/framework#1589]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.0`
- Nuxt Version:     `2.16.0-27256336.293dc11a`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `target`, `head`, `css`, `loading`, `publicRuntimeConfig`, `plugins`, `components`, `buildModules`, `modules`, `i18n`, `tailwindcss`, `pwa`, `sanity`, `gtm`, `sitemap`, `robots`, `build`
- Runtime Modules:  `@nuxtjs/i18n@7.1.0`, `@nuxtjs/robots@2.5.0`, `@nuxtjs/gtm@2.4.0`
- Build Modules:    `@nuxtjs/tailwindcss@4.2.1`, `@/modules/sitemapRouteGenerator`, `@nuxt/bridge@3.0.0-27257216.f5aea9f`
------------------------------

### Describe the bug

If I define a plugin that use defineNuxtPlugin I am not able to use the .provide as described in docs, but I find it inside the nuxt2Context object.

This is not great because when the project will finally move to nuxt3 another refactor will be necessary (and maybe not small cause in every template I assume to call nuxtApp.nuxt2Context.$myPlugin).

Here is a simple example: https://codesandbox.io/s/floral-paper-sn46i

### Reproduction

https://codesandbox.io/s/floral-paper-sn46i

**Comment by cdwmhcc** [comment]
same
