### ISSUE TITLE
jsx not working 

### ISSUE THREAD

**Issue by xhebox** [nuxt/framework#1593]
### Environment

Nuxt CLI v3.0.0-27254511.41ff3b8                                                                                   01:24:33
RootDir: /home/xhe/project/ioclub                                                                                  01:24:33
Nuxt project info:                                                                                                 01:24:33

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.4`
- Nuxt Version:     `3.0.0-27254511.41ff3b8`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                   01:24:33

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

Done in 1.19s.

### Describe the bug

Just create whatever jsx file.

```
[nuxt-dev] [Vue Router warn]: uncaught error during route navigation:
[nuxt-dev] TypeError: __vite_ssr_import_3__.ssrRegisterHelper is not a function
[nuxt-dev]     at $id_4aec7587 (file:///.../nuxt/dist/server/server.mjs:3095:23)
[nuxt-dev]     at async __instantiateModule__ (file:///.../.nuxt/dist/server/server.mjs:5124:3)
```

### Reproduction

```
diff --git a/node_modules/@nuxt/vite-builder/dist/index.mjs b/node_modules/@nuxt/vite-builder/dist/index.mjs
index ffc21b7..0648c46 100644
--- a/node_modules/@nuxt/vite-builder/dist/index.mjs
+++ b/node_modules/@nuxt/vite-builder/dist/index.mjs
@@ -191,7 +191,7 @@ async function transformRequest(opts, id) {
   }
   if (id && id.startsWith("/@fs/")) {
     id = id.slice("/@fs".length);
-  } else if (!id.includes("entry") && id.startsWith("/")) {
+  } else if (!id.includes("entry") && id.startsWith("/") && !id.includes('vue-jsx')) {
     id = "." + id;
   }
   if (await isExternal(opts, id)) {
```

This patch will fix the problem. Since `plugin-vue-jsx` will use `id === '/__vue-jsx...'` to match the id https://github.com/vitejs/vite/blob/70fd32c1569c3d93a231577b573dbd2b34da4de2/packages/plugin-vue-jsx/index.js#L72, but vite-builder adds an extra `.` before the id, it can not resolve the internal module.

**Comment by dadajam4** [comment]
I had a similar jsx problem, but when I applied the suggested patch code, the jsx problem was solved.

```
 && !id.includes('vue-jsx')
```
