### ISSUE TITLE
Nuxi not installed in "Getting Started: Bridge" scenario

### ISSUE THREAD

**Issue by Aareksio** [nuxt/framework#1597]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27257777.293dc11a`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27258467.4e424d0`
------------------------------

https://codesandbox.io/s/quirky-grass-x41sr

### Describe the bug

The "Getting Started: Bridge" scenario uses `@nuxt/bridge-edge` which depends on `nuxi-edge`. The `nuxi` binary is not aliased:

```sh
> npm run dev
> nuxi dev

'nuxi' is not recognized as an internal or external command,
operable program or batch file.
```

```sh
> npm ls nuxi

`-- @nuxt/bridge@npm:@nuxt/bridge-edge@3.0.0-27258467.4e424d0
  `-- nuxi@npm:nuxi-edge@3.0.0-27258467.4e424d0
```

Replacing script with `nuxi-edge dev` works:

```sh
> npm run dev
> nuxi-edge dev

Nuxt CLI v3.0.0-27258467.4e424d0 
```

Please note this **does not work** when using `pnpm`. `npm` moves all executables of deep dependencies to `node_modules/.bin`, while `pnpm` does so only for direct dependencies, thus making both `nuxi` and `nuxi-edge` unavailable.

```sh
> pnpm run dev
> nuxi-edge dev

'nuxi-edge' is not recognized as an internal or external command,
operable program or batch file.
```

### Reproduction

https://codesandbox.io/s/quirky-grass-x41sr

### Additional context

`pnpm` temporary fix:
```sh
> pnpm add -D nuxi@npm:nuxi-edge
```

You still have to use `nuxi-edge` in scripts since executables are not aliased

**Comment by jkoestinger** [comment]
Don't know if linked to this specific issue or if it should be another one, but using `nuxi-edge generate` fails in my case, the rest seems fine. The error is the following:

```bash
 ERROR  Command failed with ENOENT: npx nuxt generate                                                                                                                                                                                   15:00:45
spawn npx nuxt ENOENT

  spawn npx nuxt ENOENT
  at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
  at onErrorNT (internal/child_process.js:467:16)
  at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
