### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by LeadcodeDev** [nuxt/framework#1601]
### Environment

Windows 10
Node : 16.12.0

I can't use `npm nuxi info`..
![image](https://user-images.githubusercontent.com/8946317/139530787-2db5edba-0832-4d8a-a8c1-a4bb99b7b248.png)

### Describe the bug

When I would like to create new project from 0, I use `npx nuxi init nuxt3-app` and I have this error.

![image](https://user-images.githubusercontent.com/8946317/139530749-007b5442-26cb-40ef-9e40-cbd6cac612d5.png)

### Reproduction

Juste execute in your terminal `npx nuxi init nuxt3-app`

**Comment by danielroe** [comment]
Would you provide a reproduction please? 🙏

**Comment by LeadcodeDev** [comment]
Honestly, I have no idea, I just opened a terminal on my windows and ran the command `nuxi`...

I wouldn't know what to tell you...

By the way, for your information I tried it on my MAC and it works perfectly well

**Comment by LeadcodeDev** [comment]
Well, after a bunch of tests, it turns out that it was simply NPM that failed...

So I uninstalled NodeJS and all the tools related to it and reinstalled everything.

Everything works correctly!

I apologize for this unnecessary issue...

I wish you good luck!
You are doing a great job !
