### ISSUE TITLE
`$router` is not recognised in template

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#1602]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27258467.4e424d0`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `srcDir`, `buildModules`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.0.9`

### Describe the bug

`$route` and `$router` types are not recognised within the template

### Reproduction

https://github.com/Suyashtnt/website (remove last line of `layouts/default.vue`)

**Comment by namcodes** [comment]
hello @pi0 @danielroe .
how to use router, redirect in script
