### ISSUE TITLE
Recursive components not working

### ISSUE THREAD

**Issue by jd-0001** [nuxt/framework#1622]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27258467.4e424d0`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

When I use recursive component as mentioned in this docs: https://v3.vuejs.org/api/sfc-script-setup.html#recursive-components I get the following error in the console:
![Screenshot 2021-11-01 at 5 26 48 PM](https://user-images.githubusercontent.com/47495003/139667843-b2e43e97-9819-4367-8cd1-a7e69d4ee280.png)

According to docs as my file name is `Group.vue` then `Group` should auto render itself.the 

### Reproduction

CodeSandbox: https://codesandbox.io/s/admiring-shockley-kc2up?file=/app/components/Group.vue

*(BTW it keeps crashing)*

GitHub repo: https://github.com/jd-0001/nuxt-3-recursive-components

### Additional context

I think this should work as it is without doing any extra work from nuxt side, right?

### Logs

```shell
I already attached the screenshot
```

**Comment by jd-0001** [comment]
Here is codesandbox of same without nuxt: https://codesandbox.io/s/relaxed-frost-d32jm?file=/src/App.vue

**Comment by danielroe** [comment]
Resolved the error in screenshot in https://github.com/nuxt/framework/pull/1624.

---

However, about the recursive component issue, a few comments:

1. If you update your Nuxt codesandbox to have the same code as the Vue codesandbox, it works fine. And if you update your Vue sandbox to include the code from your Nuxt sandbox, it does not work.

2. It is correct that:

   > An SFC can implicitly refer to itself via its filename. E.g. a file named FooBar.vue can refer to itself as <FooBar/> in its template.

   However this is not the same issue. You'll find that using `<Group />` _does_ work in your example. It's not the same as referring to a component with a string, which [does not work](https://stackblitz.com/edit/vitejs-vite-mbaxua?file=src%2FApp.vue&terminal=dev) even without Nuxt. I would suggest [creating an issue upstream](https://github.com/vuejs/vue-next).
