### ISSUE TITLE
SASS nor STYL does not compile from config.css

### ISSUE THREAD

**Issue by terion-name** [nuxt/framework#1631]
### Environment

Nuxt CLI v3.0.0-27258467.4e424d0
RootDir: .......
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0-27258467.4e424d0`
- Package Manager:  `yarn@1.22.4`
- Bundler:          `Vite`
- User Config:      `buildModules`, `intlify`, `css`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.1.8`
------------------------------

### Describe the bug

Given nuxt config:

```js
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
    buildModules: ['@intlify/nuxt3'],
    intlify: {
        localeDir: 'locales',
    },
    css: ['assets/css/base.sass']
})
```

and assets/css/base.sass:
```sass
@import "normalize-scss"
```

with all loaders and compilers:
```json
{
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "@intlify/nuxt3": "^0.1.8",
    "fontmin": "^0.9.9",
    "nuxt3": "latest"
  },
  "dependencies": {
    "normalize-scss": "^7.0.1",
    "normalize-styl": "^8.0.1",
    "normalize.styl": "^3.0.3",
    "sass": "^1.43.4",
    "sass-loader": "^12.3.0",
    "stylus": "^0.55.0",
    "stylus-loader": "^6.2.0"
  }
}
```

Starting dev and seeing not applyed styles and this:

<img width="517" alt="Снимок экрана 2021-11-01 в 21 03 39" src="https://user-images.githubusercontent.com/1060205/139726730-6ca32794-0b3c-4038-bb79-0fcf37d67e2b.png">

http://localhost:3000/_nuxt/assets/css/base.sass:
```
import { createHotContext as __vite__createHotContext } from "/_nuxt/@vite/client";import.meta.hot = __vite__createHotContext("/assets/css/base.sass");import { updateStyle, removeStyle } from "/_nuxt/@vite/client"
const id = "....../assets/css/base.sass"
const css = ""
updateStyle(id, css)
import.meta.hot.accept()
export default css
import.meta.hot.prune(() => removeStyle(id))
```

Same with stylus

### Reproduction

[bug.zip](https://github.com/nuxt/framework/files/7455565/bug.zip)

**Comment by danielroe** [comment]
I can't reproduce this issue. Here's a working example: https://stackblitz.com/edit/github-fvdrbr
