### ISSUE TITLE
Cannot find module '0'

### ISSUE THREAD

**Issue by Vikash-Mehta** [nuxt/framework#1644]
### Environment

Nuxt project info:                                                                                              
------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.6`
- Nuxt Version:     `2.16.0-27263533.293dc11a`
- Package Manager:  `npm@6.14.15`
- Bundler:          `Webpack`
- User Config:      `head`, `loading`, `env`, `css`, `styleResources`, `vendor`, `plugins`, `buildModules`, `layoutTransition`, `axios`, `modules`, `pwa`, `buildDir`, `build`, `render`
- Runtime Modules:  `~/modules/logger`, `@nuxtjs/device@2.1.0`, `@nuxtjs/style-resources@1.2.1`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/google-analytics@2.4.0`, `@nuxtjs/pwa@3.3.5`
- Build Modules:    `@nuxtjs/router@1.6.1`, `@nuxtjs/dotenv@1.4.1`, `@nuxt/bridge@3.0.0-27264278.aba2d22`
------------------------------

### Describe the bug

 npm run build

> ambox-revamp@1.0.0 build /var/www/ambition_box/ambox_client
> nuxi build

Nuxt CLI v3.0.0-27264278.aba2d22                                                                                19:47:38
ℹ Production build                                                                                              19:47:39
ℹ Bundling for server and client side                                                                           19:47:39
ℹ Target: server                                                                                                19:47:39
✔ Builder initialized                                                                                           19:47:39
✔ Nuxt files generated                                                                                          19:47:39

 ERROR  Cannot find module '0'                                                                                  19:47:39
Require stack:
- /var/www/ambition_box/ambox_client/node_modules/@nuxt/core-edge/dist/core.js

### Reproduction

I just followed the steps in https://v3.nuxtjs.org/getting-started/bridge to migrate from nuxt 2 to nuxt 3 and then ran the command npm run build -> nuxi build

### Logs

```shell
npm run build

> ambox-revamp@1.0.0 build /var/www/ambition_box/ambox_client
> nuxi build

Nuxt CLI v3.0.0-27264278.aba2d22                                                                                19:47:38
ℹ Production build                                                                                              19:47:39
ℹ Bundling for server and client side                                                                           19:47:39
ℹ Target: server                                                                                                19:47:39
✔ Builder initialized                                                                                           19:47:39
✔ Nuxt files generated                                                                                          19:47:39

 ERROR  Cannot find module '0'                                                                                  19:47:39
Require stack:
- /var/www/ambition_box/ambox_client/node_modules/@nuxt/core-edge/dist/core.js

  Require stack:
  - node_modules/@nuxt/core-edge/dist/core.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
  at Function.resolve (internal/modules/cjs/helpers.js:98:19)
  at p (node_modules/jiti/dist/jiti.js:1:52925)
  at Resolver.g [as _require] (node_modules/jiti/dist/jiti.js:1:54200)
  at Resolver.requireModule (node_modules/@nuxt/core-edge/dist/core.js:274:29)
  at node_modules/@nuxt/webpack-edge/dist/webpack.js:632:56
  at Array.map (<anonymous>)
  at PostcssConfig.loadPlugins (node_modules/@nuxt/webpack-edge/dist/webpack.js:631:65)
  at PostcssConfig.config (node_modules/@nuxt/webpack-edge/dist/webpack.js:662:14)
  at StyleLoader.postcss (node_modules/@nuxt/webpack-edge/dist/webpack.js:721:39)
  at StyleLoader.apply (node_modules/@nuxt/webpack-edge/dist/webpack.js:767:42)
  at WebpackClientConfig.rules (node_modules/@nuxt/webpack-edge/dist/webpack.js:1303:28)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack-edge/dist/webpack.js:1451:21)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack-edge/dist/webpack.js:1573:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack-edge/dist/webpack.js:1797:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack-edge/dist/webpack.js:1802:12)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ambox-revamp@1.0.0 build: `nuxi build`
```

**Comment by Vikash-Mehta** [comment]
I just followed the steps in https://v3.nuxtjs.org/getting-started/bridge to migrate from nuxt 2 to nuxt 3 and then ran the command `npm run build` -> nuxi build

**Comment by danielroe** [comment]
By reproduction, I mean a code sample that I can clone and test out myself.

> Please provide a link to a repo that can reproduce the problem you ran into. A [minimal reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction) is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided after we might close it.

**Comment by brandonpittman** [comment]
Bumped into this issue too. No idea why.
