### ISSUE TITLE
`useNuxtApp` cannot be used in `app.vue`

### ISSUE THREAD

**Issue by cdwmhcc** [nuxt/framework#1645]
### Environment

------------------------------
- Operating System: `Windows 10`
- Node Version:     `v14.17.6/16.12.0`
- Nuxt Version:     `3.0.0-27264278.aba2d22`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `default`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

Providing helpers is invalid

https://v3.nuxtjs.org/docs/usage/nuxt-app#providing-helpers
https://v3.nuxtjs.org/docs/directory-structure/plugins#typing-plugins

### app.vue

``` typescript
<script setup lang="ts">
import { useNuxtApp } from '#app'
const nuxtApp = useNuxtApp()
console.log(nuxtApp.$hello("name"))
</script>
```

# Method 1

### /Plugins/hello.server.ts

``` typescript
import { defineNuxtPlugin } from '#app'
export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.provide('hello', (msg:string) => `Hello ${msg}!`);
})
```

### Error

`Uncaught (in promise) TypeError: nuxtApp.$hello is not a function`

# Method 2

### /Plugins/hello.server.ts

``` typescript
const nuxtApp = useNuxtApp()
nuxtApp.provide('hello', (name) => `Hello ${name}!`)
```

### Error

![image](https://user-images.githubusercontent.com/8030134/139866163-4c1bd8d7-dcf0-4af7-adda-4d57cd74d9b2.png)

**Comment by danielroe** [comment]
1. Your `~/plugins` directory should be lower-cased.
2. You can't use an injected function if you haven't injected it. So if you are using it on both server & client side then you have to inject it in both places.

**Comment by cdwmhcc** [comment]
> 1. Your `~/plugins` directory should be lower-cased.
> 2. You can't use an injected function if you haven't injected it. So if you are using it on both server & client side then you have to inject it in both places.

1. Use lower-cased `plugins` directory
2. create `hello.ts` in `plugins` directory

Same error

![image](https://user-images.githubusercontent.com/8030134/139968504-bea255ec-1e8c-46fd-b025-0c48bfea96e5.png)

**Comment by danielroe** [comment]
Seems to work fine for me: https://codesandbox.io/s/magical-bogdan-y5m0q?file=/app.vue

**Comment by cdwmhcc** [comment]
> Seems to work fine for me: https://codesandbox.io/s/magical-bogdan-y5m0q?file=/app.vue

Wow, need to stop and re-execute `yarn dev`

**Comment by cdwmhcc** [comment]
![image](https://user-images.githubusercontent.com/8030134/140000026-557614cf-277a-4b01-839b-6cab0b74b59d.png)

But when I console.log `nuxtApp`, there is no $hello, so I cannot prompt for the method in the ide

**Comment by danielroe** [comment]
Isn't it being logged in that screenshot, just to the left of the text `no $hello`?

If you are wanting IDE auto complete you do need to tell TypeScript about it: http://v3.nuxtjs.org/docs/directory-structure/plugins#typing-plugins

**Comment by cdwmhcc** [comment]
> Isn't it being logged in that screenshot, just to the left of the text `no $hello`?
> 
> If you are wanting IDE auto complete you do need to tell TypeScript about it: http://v3.nuxtjs.org/docs/directory-structure/plugins#typing-plugins

Thank you!!! It work.
