### ISSUE TITLE
HTML lang not working

### ISSUE THREAD

**Issue by adarshmadrecha** [nuxt/framework#1652]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27264486.37f86a0`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

Adding `<Head lang="en-in" />` in `app.vue` has no impact.
It should add `lang` in `html` tag `<html lang="en-in" >...</html>`

### Reproduction

https://codesandbox.io/s/dreamy-mendel-rbfmu

### Additional context

Ref: https://v3.nuxtjs.org/docs/usage/meta-tags#meta-components

**Comment by tarolive** [comment]
Hello,

I don't know if this is related, but if you put the meta tag with charset, it gets duplicated.

<img width="209" alt="image" src="https://user-images.githubusercontent.com/84419122/140680364-86829588-81e7-40fe-9eb8-2d5f27154415.png">

<img width="165" alt="image" src="https://user-images.githubusercontent.com/84419122/140680401-4e324376-179e-4aab-98b0-1820ef885b2b.png">

**Comment by f3ltron** [comment]
I found there is an issue inside:

<img width="1251" alt="Screen Shot 2021-11-08 at 10 28 53 PM" src="https://user-images.githubusercontent.com/11556276/140856886-e92fcf06-b827-4e04-9179-1564d7936693.png">

The props come with lang `undefined` and get removed by `removeUndefinedProps`

It's a bit hard to read 
`const setupForUseMeta = (metaFactory: (props: Props, ctx: SetupContext) => Record<string, any>, renderChild?: boolean) => (props: Props, ctx: SetupContext) => {`

How to read the metaFactory here @danielroe  ?

but the lang property is defined

```js
/ <head>
export const Head = defineComponent({
  name: 'Head',
  props: {
    ...globalProps,
    manifest: String,
    version: String,
    xmlns: String
  },
  setup: setupForUseMeta((headAttrs) => {
    console.log('log attrs======', headAttrs)
    return { headAttrs }
  }, true)
})
```
