### ISSUE TITLE
Cannot read properties of undefined (reading 'deep')

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#1659]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27264620.a62351a`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

Problem
` <AtomHobButton :kind="'success'" secondary >test a </AtomHobButton>` 
and dont see button

http://localhost:3000/

![CleanShot 2021-11-03 at 09 59 23](https://user-images.githubusercontent.com/38668796/140020104-4663aab6-a952-439d-a2cc-95d1c17566f5.png)

### Reproduction

https://github.com/productdevbook/nuxt3-bug

**Comment by danielroe** [comment]
The issue seems to be the lack of a corresponding server transform for the `v-focus` directive. For example, this might work:

```js
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  vue: {
    compilerOptions: {
      directiveTransforms: {
        focus: () => ({
          props: [],
          needRuntime: true
        })
      }
    }
  }
})
```

see also https://github.com/nuxt/framework/issues/1695#issuecomment-961065288

**Comment by productdevbook** [comment]
some problem

**Comment by productdevbook** [comment]
how to add vue directive ? plugins ?

**Comment by productdevbook** [comment]
Thank you, your write and fixed ✅ I forgot to add them as directive.
<img width="1281" alt="CleanShot 2021-11-07 at 17 58 46@2x" src="https://user-images.githubusercontent.com/38668796/140650313-23fea9ea-63f1-4a4a-b4e6-9f70721daea4.png">

**Comment by productdevbook** [comment]
yarn build 
Custom directive is missing corresponding SSR transform and will be ignored.                 

![CleanShot 2021-11-14 at 19 45 27](https://user-images.githubusercontent.com/38668796/141690142-fedf2eb6-e298-4037-ba95-653e80c0894c.png)

**Comment by productdevbook** [comment]
The problem is not with nuxt. [vue](https://github.com/vuejs/vitepress/issues/92#issuecomment-968327060)
