### ISSUE TITLE
 Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by andysay** [nuxt/framework#1664]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27264620.a62351a`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `vite`, `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

if use navigation browser, pages stop load.. and return this error.

 Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### Reproduction

nuxt page have style

.page-enter-active, .page-leave-active {
  transition: opacity .5s;
}
.page-enter, .page-leave-active {
  opacity: 0;
} 

nuxt link page1, page2 

forward and back 2-3 times

**Comment by danielroe** [comment]
Ensure you have only one root element for your pages, or within any custom transition element.

**Comment by yunyuyuan** [comment]
I have followed this [guide](https://v3.nuxtjs.org/docs/directory-structure/pages) to create dymanic page(very simple),and encounted the same error.

**Comment by yunyuyuan** [comment]
@danielroe Please check this: https://codesandbox.io/s/gallant-taussig-crx0r?file=/pages/index.vue

**Comment by syifeng** [comment]
> 

I got the same error with  Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

and with no transition

nuxt link page1, page2
forward and back 2-3 times

the error just showed up

confirmed that I don't have two element in <template>

**Comment by danielroe** [comment]
@syifeng Would you provide a reproduction in that case?

**Comment by syifeng** [comment]
> 
I found that the error  would show when i switch from 2 to 4. when i switched to 1 and switched to another router, the error showed up.
here is the code below

package.json
```
"devDependencies": {
    "@iconify/vue": "^3.1.1",
    "autoprefixer": "^10.4.0",
    "nuxt3": "latest",
    "postcss": "^8.4.5",
    "sass": "^1.44.0",
    "sass-loader": "^12.3.0",
    "tailwindcss": "^3.0.2",
    "unplugin-icons": "^0.12.23"
  },
  "dependencies": {
    "@headlessui/vue": "^1.4.2",
    "@heroicons/vue": "^1.0.5",
    "axios": "^0.24.0"
  }
```

/components/Base/Header.vue
```
<!-- This example requires Tailwind CSS v2.0+ -->
<template>
  <div>
    <NuxtLink v-for="item in navigation" :key="item.name" :to="item.href" :class="[$route.path == item.href ? 'bg-gray-900 text-white' : 'text-gray-300 hover:bg-gray-700 hover:text-white', 'px-3 py-2 rounded-md text-sm font-medium']" :aria-current="item.current ? 'page' : undefined">{{ item.name }}</NuxtLink>
  </div>

</template>

<script setup>
const navigation = [
  { name: '1', href: '/' },
  { name: '2', href: '/event' },
  { name: '3', href: '/debate' },
  { name: '4', href: '/about' },
]
</script>
```

/layouts/default.vue
```
<template>
  <div name="custom">
    <Header />
    <transition name="foobar">
      <div>

        <slot/>
      </div>
    </transition>    
  </div>
</template>
<script setup>
import Header from '@/components/Base/Header'
</script>
<style scoped>
.foobar-enter-from{
  opacity: 0;
  transform: translateY(15px);
}

.foobar-enter-active,
.foobar-leave-active {
  transition: all 0.5s;
}

.foobar-enter,
.foobar-leave-to {
  opacity: 0;
}
</style>
```
/pages/index.vue
```
<template>
  <div class="main-container bg-white grid grid-cols-12 mt-1" :class="```s-${statusNow}```">
    <div class="topic-box bg-slate-100" v-for="topicItem in topicsData.records" :key="topicItem" @click="topicSpread(topicItem)">
      <div class="topic-title title text-slate-800	">{{topicItem.title}}</div>
      <div class="topic-info">
        <div class="topic-created-time">{{topicItem.createdTime}}</div>
        <div class="tags-box" v-if="topicItem.tags">
          <span class="tag-item rounded bg-yellow-300 text-gray-600 p-0.5" v-for="tag in topicItem.tags.split(',')" :key="tag">{{tag}}</span>
        </div>
      </div>
    </div>
  </div>
</template>
<script setup>
import { ref, onMounted } from 'vue'
// import { useContext } from 'nuxt';
import { useNuxtApp } from '#app'
import { Icon } from '@iconify/vue';
const { $request } = useNuxtApp();
const langCountry = ref('cn')

// let range = (start, end) => new Array(end - start).fill(start).map((el, i) => start + i);
const statusNow = ref(1)
let topicActive = ref({})
let topicsData = ref({
  nomre: false,
  page: 1,
  total: 0,
  records: []
})
const eventsData = ref({
  nomre: false,
  page: 1,
  total: 0,
  records: []
})
const loadTopics = async (page) => {
  const { code, result } = await $request.get(```/api/cms/topic/page?page=${page || 1}&size=10```)
  topicsData.value = result
}
const loadEvents = async (page) => {
  const { code, result } = await $request.get(```/api/cms/event/page?```, { 
    params:  {page: page || 1, size: 10, topicId: topicActive.value.id}
  })
  eventsData.value = result
}
const topicSpread = async topic => {
  topicActive.value = topic
  statusNow.value = 2
  await loadEvents(1)
}
onMounted(async () => {
  await loadTopics(1)
})
</script>
```

/pages/event.vue
```
<template>
  <div>
    <span>event</span>
  </div>
</template>
<script setup>
</script>
```
/pages/about.vue
```
<template>
  <div><span>about</span></div>
</template>
<script setup>
</script>
```
/pages/debate.vue
```
<template>
<div><span>debate</span></div>
</template>
<script setup>
</script>
```

**Comment by syifeng** [comment]
> @syifeng Would you provide a reproduction in that case?

I just found the reason what caused the Error.

I commented the code  element in the template.

a wired Error. hard to found.
/pages/index.vue
```
--- bad
<template>
 <!-- <div class="bg-emerald-300 leading-9">
    <span>{{statusNow}}</span>
  </div> -->
 <div>
main body
</div>
</template>

--- good
<template>
 <div>
main body
</div>
</template>
``

**Comment by mutuadavid93** [comment]
Am using Nuxt 2 and the issue was I was using the fragment npm package on my layouts. After swapping the fragment component with an HTML element e.g. section, nuxt-link now works like a charm.

**Comment by ShashankaNataraj** [comment]
The vue docs need to have this in them, this was killing me till now: "Do not have a comment in the first line of your template".

**Comment by baermathias** [comment]
@danielroe I see it the same way, please add to the docs routing section, that no comments should be on the same level as the root tag.

**Comment by manniL** [comment]
@baermathias Feel free to send in a PR (e.g. [here](https://github.com/nuxt/framework/edit/main/docs/content/2.guide/3.directory-structure/10.pages.md))! ☺️

**Comment by danielroe** [comment]
It is already there: https://v3.nuxtjs.org/guide/directory-structure/pages#usage. Improvements welcome 🙏

**Comment by AliN11** [comment]
This happened to me because there was the following code in a component:
```
<template>
  <div v-if="...">
    ...
  </div>
  <div v-else>
    <nuxt-child />
  </div>
</template>
```

Two root elements but without any errors.

**Comment by kristus123** [comment]
i thought the new nuxt version would not need to have a single root element

**Comment by manniL** [comment]
> i thought the new nuxt version would not need to have a single root element

It does not need to have. Then you have to disable transitions though

**Comment by shba007** [comment]
![image](https://user-images.githubusercontent.com/48382105/192844735-6fc89366-01bf-4640-8247-4cf45d164260.png)

`definePageMeta({
	layout: false,
});`

adds `<!--[-->` which causes `Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

**Comment by steffenstolze** [comment]
@shba007 good catch. That's what causing an error within our app, too!

Our original setup looked like this and caused the error as well:

```vue
<script setup>
definePageMeta({
	layout: false
});
</script>

<template>
	<NuxtLayout name="auth">
               <div class="flex flex-col flex-grow justify-center py-12 sm:px-6 lg:px-8">
                  ....
               </div>
	</NuxtLayout>
</template>
```

We changed it to this and got rid of the error message:

```vue
<script setup>
definePageMeta({
	layout: 'auth'
});
</script>

<template>
	<div class="flex flex-col flex-grow justify-center py-12 sm:px-6 lg:px-8">
           ....
        </div>
</template>
```

**Comment by narsingm** [comment]
![11hardik](https://user-images.githubusercontent.com/52418216/209081682-05c6f872-a876-47c2-9159-bc259bd0c502.jpg)

**Comment by parsagholipour** [comment]
I get this error when I navigate before transition is complete.
Using global page transition:
`app: {
    pageTransition: { name: 'page', mode: 'out-in' },
  },`
