### ISSUE TITLE
import externals with full path for nitro dev 

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1670]
In development, we generate `.nuxt/nitro/index.mjs` with externals implicitly pointing to `node_modules` (like `import destr from 'destr';`) . This makes two major issues:
- Node.js has different search path for `node_modules` than the one configured for rollup and as a result hoisting issues
- With pnp (#581) we need explicit dependencies while imports like `h3` are actually not a dependency of the project

**Comment by negezor** [comment]
Any updates?

**Comment by pi0** [comment]
This issue is finally resolved in nitropack project. Will be available soon!
