### ISSUE TITLE
Add `useLazyAsyncData` and `useLazyFetch`

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1688]
Currently, it is possible to use `useAsyncData` both as an awaited composable and not awaiting with `defer: true` and adding `pending` guard in template

Using an explicit alias:
- Allows easier explanation in docs about cons/pros of each method and why swr-like non-blocking navigation is better
- Allows backporting non-blocking lazy version to Nuxt Bridge
- Allows decoupling implementation in the future to improve blocking and non blocking composables individually

**Comment by Atinux** [comment]
This is interesting, I believe that we should stay consistent with the option though.

Two choices:
- `useDeferAsyncData` / `useDeferFetch`
- Rename `defer` to `lazy` option

**Comment by pi0** [comment]
I vote for `Lazy` mostly since is lazier to write and same as `defineLazyComponent`

**Comment by Luffyyy** [comment]
Dunno about others, but for me `lazy` is an "easier" word, like I can understand more or less what it means straightaway, while defer is a little less. Could be just because the word is more commonly used.

**Comment by Atinux** [comment]
Then I believe renaming `defer` option to `lazy` makes sense 😊  (we can add a warning to say that `defer` option will be removed when Nuxt 3 hits RC)
