### ISSUE TITLE
Add  `useNuxt2Meta`

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1689]
By introducing explicit Nuxt2 composable, we can finalize the migration path and provide docs for Bridge ~> Nuxt 3 migration once had a better idea about meta support in Nuxt 3.

**Comment by danielroe** [comment]
@pi0 I think we can replace `useNuxt2Store` with `useNuxtApp`, e.g.:
```js
const { $store } = useNuxtApp()
```

with the proviso that we can't expose `$store` to the template in a `<script setup>` as it is already available there because it is a property of the instance...
