### ISSUE TITLE
Windows OS: [worker] Named export 'isWindows' not found.

### ISSUE THREAD

**Issue by cpreston321** [nuxt/framework#1697]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27267163.9b8d44d`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `srcDir`, `css`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.0.11`
------------------------------

### Describe the bug

Project doesn't load in browser on windows with one package installed inside nuxt3. Which is windi-css and everything is up to date,.  This didn't happen the other day as it was mainly file paths not getting resolved now this is the problem.

Where it's breaking: [Click Here](https://github.com/nuxt/framework/blob/3cd44947706c70fd70d838985fd480642382f976/packages/nitro/src/runtime/entries/dev.ts#L7)

Maybe it's rooting from the `std-env` module.  [Click Here](https://github.com/unjs/std-env/blob/main/package.json)

### Reproduction

The log seems like it tells exactly where it is at in the nitro server and only can reproduce on windows. 

### Additional context

nuxt.config.js

```js
import { defineNuxtConfig } from 'nuxt3';

export default defineNuxtConfig({
  srcDir: 'src/',
  buildModules: ['nuxt-windicss'],
});
```

### Logs

```shell
[worker] Named export 'isWindows' not found. The requested module 'std-env' is a CommonJS module, which may not support all module.exports as named exports.                                      11:24:33
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'std-env';
const { provider, isWindows } = pkg;


  import { provider, isWindows } from 'std-env';
  ^^^^^^^^^
  SyntaxError: Named export 'isWindows' not found. The requested module 'std-env' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'std-env';
  const { provider, isWindows } = pkg;
  
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)
  at async Loader.import (node:internal/modules/esm/loader:178:24)
  at async Object.loadESM (node:internal/process/esm_loader:68:5)
  at async handleMainPromise (node:internal/modules/run_main:63:12)
```

**Comment by pi0** [comment]
Hi @cpreston321 Do you mind recreating lock file or directly adding std-env to project? Seems a hoisting issue that v2 is installed on top level.

**Comment by cpreston321** [comment]
@pi0 Trying that now.

**Comment by nandi95** [comment]
I had the same thing, except it was on macos with no warnings. installing `std-env` has in fact fixed it for me too.

**Comment by nandi95** [comment]
For me it continiously reloads if I don't give it the ssl cert and key. If I do it still reloads but with couple seconds between reloads. Installing `std-env` does not help.

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27272804.ca557e7`
- Package Manager:  `npm@8.1.3`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `ssr`, `target`, `meta`, `build`, `css`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```
