### ISSUE TITLE
No helpful logs in console when using nuxt bridge on a fresh nuxt 2 project.

### ISSUE THREAD

**Issue by ayalon** [nuxt/framework#1698]
### Environment

Nuxt project info:                                                                                            17:26:23

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27266415.3ab12f9f`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `build`, `bridge`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `@nuxt/typescript-build@2.1.0`
------------------------------

### Describe the bug

I created a new nuxt2 project with `npx create-nuxt-app nuxt2-app`. Then I followed the documentation and upgraded it to `"nuxt-edge": "latest"` added the bridge module and did the suggested config changes:

https://v3.nuxtjs.org/getting-started/bridge/

When doing a `npm run dev` i have no output except this:

```
> nuxt2-app@1.0.0 dev
> nuxi dev
Nuxt CLI v3.0.0-27267163.9b8d44d                                                                           
 > Local:    http://localhost:3000/
 > Network:  http://172.28.167.215:3000/
``` 

If I do a nuxt build I have this output:
```
> nuxt2-app@1.0.0 build
> nuxi build
Nuxt CLI v3.0.0-27267163.9b8d44d
```

Is it really true, that I have no error logs and no feedback at all? Not even a file change triggers a message in the command line.

### Reproduction

Here is a full repo, that show, that NO console output from the plugin is generated. I added the most simple plugin and called some console output but it is not displayed at all.

https://stackblitz.com/github/ayalon/nuxt2-brigde-console-log

### Additional context

Is there an option to show the usual logs as in nuxt2?

**Comment by ayalon** [comment]
Reproduction:
Here is a full repo, that show, that NO console output from the plugin is generated. I added the most simple plugin and called some console output but it is not displayed at all.

https://stackblitz.com/github/ayalon/nuxt2-brigde-console-log

**Comment by danielroe** [comment]
@ayalon Your reproduction was not actually using Bridge, just `nuxi`. Make sure to follow [this section](https://v3.nuxtjs.org/getting-started/bridge/#update-nuxtconfig) of the migration guide.

```js
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  // ...
})
```

Then, hopefully you'll see this:
<img width="326" alt="CleanShot 2021-11-05 at 13 38 40@2x" src="https://user-images.githubusercontent.com/28706372/140519141-89b9fdd9-07e9-4ad9-8392-a8574d1828e8.png">

**Comment by ayalon** [comment]
Thanks for the help! This was a mistake on my side.

But I still think, that a lot of console logging is missing. We have a module that does a lot of logs but non of them are displayed with nuxt bridge.

I also had a code error in a module but instead of displaying the error, just nothing was displayed. Is there an option to enable logging from nuxt modules and nuxt server middleware plugins with nuxt bridge?

**Comment by pi0** [comment]
@ayalon We had a regression in nuxt-edge (on std-env) that caused hiding most of the logs. Would you mind upgrading to latest `nuxt-edge` and recreating lockfile?

**Comment by XLordalX** [comment]
This seems to still be happening on the latest version. Only `console.error` is logging anything.
