### ISSUE TITLE
Error when integrating Firebase V9 only with Nuxt Bridge

### ISSUE THREAD

**Issue by jeverduzco** [nuxt/framework#1700]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27266415.3ab12f9f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `publicRuntimeConfig`, `head`, `components`, `modules`, `css`, `plugins`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27267163.9b8d44d`

### Describe the bug

I have a Firebase V9 integration with Nuxt 2.15.8 and it works perfect. But when I try to do the same integration with Nuxt Bridge I get this error in console:

`Uncaught TypeError: Cannot destructure property '__extends' of '_tslib_js__WEBPACK_IMPORTED_MODULE_0___default.a' as it is undefined.
    at eval (index.js?8a15:3)
    at Module../node_modules/tslib/modules/index.js (app.js:417)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (index.esm.js?ffa6:1)
    at Module../node_modules/@firebase/component/dist/index.esm.js (app.js:23)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (index.esm2017.js?5606:1)
    at Module../node_modules/@firebase/app/dist/index.esm2017.js (app.js:11)`

### Reproduction

I made a project in Code Sandbox for a better reproduction of the problem which can be accessed here: [https://codesandbox.io/s/icy-dawn-c7eri?file=/nuxt.config.js](https://codesandbox.io/s/icy-dawn-c7eri?file=/nuxt.config.js)

The problem is visible by opening in a new tab and checking the browser console.

It only happens when loading the `firebase.js` file located in the plugins folder. The same plugin in Nuxt 2.15.8 works perfectly.

**Comment by ErwinAI** [comment]
I have the same problem as @jeverduzco . However, I am using Firebase 8, not 9. And I am using @nuxtjs/firebase .

Operating System: Windows
Node Version: v16.13.0
Nuxt Version: 2.15.8
Package Manager: npm@8.1.0
Build Modules: @nuxt/bridge-edge@^3.0.0-27296423.f3082ca

`"dependencies": {
    "@nuxtjs/firebase": "^7.6.1",
    "core-js": "^3.9.1",
    "firebase": "^8.10.0", 
    "nuxt-edge": "latest",
    "std-env": "^3.0.1" // explicit dependency for fixing a different issue
  },
  "devDependencies": {
    "@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27296423.f3082ca"
  }`

`TypeError: Cannot destructure property '__extends' of '_tslib_js__WEBPACK_IMPORTED_MODULE_0___default.a' as it is undefined.
    at eval (index.js?8a15:3)
    at Module../node_modules/tslib/modules/index.js (12fdb331.js:59)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (index.esm.js?cc84:1)
    at Module../node_modules/@firebase/app/dist/index.esm.js (12fdb331.js:11)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (index.esm.js?2591:1)
    at Module../node_modules/firebase/dist/index.esm.js (signup.js:203)`

**Comment by ErwinAI** [comment]
For anyone that just tried to use Nuxt Bridge and runs into the same problems: disabling Nuxt Bridge, for now, will make the error go away.

in `nuxt.config.js`:
```
export default defineNuxtConfig({
    bridge: false
})
```

**Comment by danielroe** [comment]
let's follow in https://github.com/nuxt/framework/issues/1151

**Comment by mfreeman451** [comment]
> For anyone that just tried to move from Nuxt 2 to using Nuxt Bridge and runs into the same problems: disabling Nuxt Bridge, for now, will make the error go away.
> 
> in `nuxt.config.js`:
> 
> ```
> export default defineNuxtConfig({
>     bridge: false
> })
> ```

Disabling the bridge brings a new set of problems.
