### ISSUE TITLE
production Node.js server with HTTPS

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1701]
Currently, the default target [node server](https://v3.nuxtjs.org/docs/deployment/presets/server) generates a standalone node HTTP server. ([code](https://github.com/nuxt/framework/blob/main/packages/nitro/src/runtime/entries/server.ts))

While in %99 of cases we should always run this sever behind a reverse proxy like nginx or Cloudflare that terminates SSL, there might be cases it is handy to directly terminate on node handler.

For this, we might introduce `NITRO_SSL_CERT` and `NITRO_SSL_KEY` environment variables to be picked on runtime.

An alternative would be supporting `options.nitro.node.ssl` but is probably a dangerous operation since this way we are adding sensitive data to the production bundle and if image or CI artifcat leaks, attackers can use to do MITM.

**Comment by dataexcess** [comment]
This does not work I always get the following error:

`NITRO_HOST=0.0.0.0 NITRO_PORT=3001 NITRO_SSL_CERT=/home/***/signing/my_website.crt NITRO_SSL_KEY=/home/***/signing/my_website.key node .output/server/index.mjs`

```
node:_tls_common:155
    context.setCert(cert);
            ^

Error: error:0909006C:PEM routines:get_name:no start line
    at setCerts (node:_tls_common:155:13)
    at Object.createSecureContext (node:_tls_common:210:7)
    at Server.setSecureContext (node:_tls_wrap:1336:27)
    at Server (node:_tls_wrap:1191:8)
    at new Server (node:https:67:14)
    at file:///home/dataexcess/SubNeu_staging/SubNeu/.output/server/chunks/nitro/node-server.mjs:1446:30
    at ModuleJob.run (node:internal/modules/esm/module_job:152:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

**Comment by pi0** [comment]
@dataexcess Can you check if your crt and key files are valid an in PEM format? They should start with `-----BEGIN CERTIFICATE-----` and `-----BEGIN PRIVATE KEY-----`

**Comment by dataexcess** [comment]
Yes I checked. they are.

**Comment by pi0** [comment]
There seems an issue with nitro for production. Please followup https://github.com/unjs/nitro/issues/749 for workaround and fix.
