### ISSUE TITLE
Could not resolve './globalThis.js'

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#1713]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27267816.6bd7186`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.0.11`
------------------------------

### Describe the bug

yarn build

### Reproduction

https://github.com/productdevbook/productdevbook.com

### Logs

```shell
yarn run v1.22.17
$ nuxi build
Nuxt CLI v3.0.0-27267528.292b524                                                                                                                                                                                        06:46:08

 ERROR  Could not resolve './globalThis.js' from node_modules/@apollo/client/utilities/globals/index.js                                                                                                                 06:46:12


 ERROR  Could not resolve './globalThis.js' from node_modules/@apollo/client/utilities/globals/index.js                                                                                                                 06:46:12

  at error (node_modules/rollup/dist/shared/rollup.js:158:30)
  at ModuleLoader.handleResolveId (node_modules/rollup/dist/shared/rollup.js:22306:24)
  at node_modules/rollup/dist/shared/rollup.js:22300:26

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nachtfunke** [comment]
Did you maybe find a solution for this? I am facing the exact same issue, but with `globalThis.scss`.

**Comment by nachtfunke** [comment]
Should anyone stumble upon the same issue, just renaming the files in question actually will help to circumvent [this specific issue](https://github.com/nuxt/framework/issues/1006#issuecomment-963993110).

**Comment by AeonFr** [comment]
Getting the same error when running `npx nuxi build`

Using node 14 and npm 6

```
❯ npx nuxi build
Nuxt CLI v3.0.0-27274229.29599f0                                                                                                                                      10:19:03
ℹ Vite warmed up in 1026ms                                                                                                                                            10:19:05

 ERROR  Could not resolve '../util/globalThis' from ../util/globalThis?commonjs-external                                                                              10:19:06


 ERROR  Could not resolve '../util/globalThis' from ../util/globalThis?commonjs-external                                                                              10:19:06

  at error (node_modules/rollup/dist/shared/rollup.js:158:30)
  at ModuleLoader.handleResolveId (node_modules/rollup/dist/shared/rollup.js:22306:24)
  at node_modules/rollup/dist/shared/rollup.js:22300:26
```

**Comment by AeonFr** [comment]
This is probably an insane solution, but I managed to get build to work by following this steps:

1. Add this to your nuxt config:

```js
  vite: {
    resolve: {
      alias: {
        "../util/globalThis": "./dirty-hack.js",
      },
    },
  },
```

(in my case, unlike OP's, the problematic import was `../util/globalThis`, so I added an alias for that. If you are having issues with `../globalThis` instead, adjust the alias)

2. Create a `dirty-hack.js` file in the root of the project. I'm not sure if the content is important, I left mine black except for a comment

```js
// Trying to bypass showstopper bug that prevents builds
// See issue status: https://github.com/nuxt/framework/issues/1713
```

After those steps building the app should be possible

**Comment by genffy** [comment]
this bug cause by this line https://github.com/nuxt/framework/blob/bf716f39783508e001a590c01956ac57937f6bd2/packages/vite/src/client.ts#L21 
doc in vite describe this config mean just simple replace variable when build
https://github.com/vitejs/vite/blob/f6d08c7430906d6262ee1df729d2ea193a80fa6c/packages/vite/src/node/config.ts#L110
```
/**
 * Define global variable replacements.
 * Entries will be defined on `window` during dev and replaced during build.
 */
define?: Record<string, any>
```
when file path has some variable in `define`, also will be repaced.

**Comment by pi0** [comment]
@danielroe Do you mind checking this?
