### ISSUE TITLE
Error when call useNuxtApp() 

### ISSUE THREAD

**Issue by weisiqian** [nuxt/framework#1715]
### Environment

![image](https://user-images.githubusercontent.com/19994951/140478844-2edf5e61-aa69-434d-9cf9-622ed71331ae.png)

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-27267095.2166661`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

a simple component. here is the component code.

```
<template>
  <div>
    test page
    <div @click="handleNavigate">click</div>
  </div>
</template>

<script lang="ts" setup>
import { defineComponent } from 'vue'
import { useNuxtApp } from '#app';

const handleNavigate = () => {
  try {
    const nuxtApp = useNuxtApp();
    alert(nuxtApp)
    console.error('nuxtApp', nuxtApp)
  } catch(e){
    console.error(e)
    alert(e)
  }
}
</script>

</script>

```

when i click it，browser throws this error.

![image](https://user-images.githubusercontent.com/19994951/140480316-89d6a782-88f3-43cf-b3ba-d8dbf42e57a4.png)

### Reproduction

[https://github.com/weisiqian/nuxt3-app.git](https://github.com/weisiqian/nuxt3-app.git)

**Comment by danielroe** [comment]
You shouldn't call `useNuxtApp()` within a function - it's meant to be called directly in `setup()` or in a plugin.

For example:
```js
<template>
  <div>
    test page
    <div @click="handleNavigate">click</div>
  </div>
</template>

<script lang="ts" setup>
import { defineComponent } from 'vue'
import { useNuxtApp } from '#app';

const nuxtApp = useNuxtApp();

const handleNavigate = () => {
  console.log('nuxtApp', nuxtApp)
}
</script>
```

**Comment by nhan-ho-saltovn** [comment]
I cannot import {useNuxtApp} from '#app'. Is it require any configuration to use it?

**Comment by danielroe** [comment]
@nhan-ho-saltovn Please raise a new discussion rather than commenting on an old (closed) issue.
