### ISSUE TITLE
Server does not support dynamic route

### ISSUE THREAD

**Issue by willin** [nuxt/framework#1719]
### Environment

Nuxt CLI v3.0.0-27267816.6bd7186                                                                                                                                                                                17:34:26
RootDir: /home/willin/Documents/v0/nuxt3-app                                                                                                                                                                    17:34:27
Nuxt project info:                                                                                                                                                                                              17:34:27

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-27267816.6bd7186`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                                                                17:34:27

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Describe the bug

does not support dynamic  like:
- [slug].ts
- [...slug].ts
- _slug.ts

### Reproduction

add `server/api/[slug].ts` for test

**Comment by danielroe** [comment]
closing to follow at https://github.com/nuxt/framework/issues/872
