### ISSUE TITLE
vite reload problem

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#1720]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27268388.4da062a`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

yarn dev

change index css or div dont change. and page reload. no hot reload.

### Reproduction

https://github.com/productdevbook/productdevbook.com

### Logs

<img width="771" alt="CleanShot 2021-11-05 at 13 10 13@2x" src="https://user-images.githubusercontent.com/38668796/140494479-84d951fe-939e-4c52-b791-bf02d6849a67.png">

_No response_

**Comment by pi0** [comment]
Thanks for the report. Should be fixed by #1734
