### ISSUE TITLE
Hydration text content mismatch

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#1742]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27268685.6d300d2`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

yarn dev

### Reproduction

https://github.com/productdevbook/productdevbook.com

### Additional context

<img width="538" alt="CleanShot 2021-11-05 at 19 13 35@2x" src="https://user-images.githubusercontent.com/38668796/140542896-6cd64287-39fb-4039-855b-f4820d26ff68.png">

**Comment by danielroe** [comment]
This means your state on server & client don't match. Lots of things can cause it, but it's not a Nuxt bug. Try identifying what element is different, and then console log the state that produces that HTML to see what the cause might be.

**Comment by productdevbook** [comment]
> This means your state on server & client don't match. Lots of things can cause it, but it's not a Nuxt bug. Try identifying what element is different, and then console log the state that produces that HTML to see what the cause might be.

![CleanShot 2021-11-05 at 20 19 43@2x](https://user-images.githubusercontent.com/38668796/140552145-5ef4f91f-941e-4e99-ba54-5e85810d379d.png)

and suspanse used some problem :/
