### ISSUE TITLE
can not use router.push() in composable and utils directory

### ISSUE THREAD

**Issue by weisiqian** [nuxt/framework#1750]
I tried to use useRouter() in composables directory and utils directory.

in composable directory

```
import { useRouter } from 'vue-router';

const router = useRouter()

export function navigateTo(url: string) {
  router.push(url)
}
```

in utils directory

```
import { useRouter } from 'vue-router';

const router = useRouter()

export function navigateTo(url: string) {
  router.push(url)
}
```

but it throws a undefined Error when I call navigateTo function in component 。

![image](https://user-images.githubusercontent.com/19994951/140602379-ab1613af-024b-4311-a2a5-d4c929a02d8b.png)

I create a mini repository here : [https://github.com/weisiqian/nuxt3-app.git](https://github.com/weisiqian/nuxt3-app.git)

_Originally posted by @weisiqian in https://github.com/nuxt/framework/discussions/1749#discussioncomment-1598478_

**Comment by danielroe** [comment]
You need to call `useRouter` within `setup()`, not within ambient JavaScript. So you can create a composable that calls `useRouter` and returns a closure that references the router

**Comment by namcodes** [comment]
@danielroe con you provide me a demo please
i have same problem

**Comment by weisiqian** [comment]
@danielroe  still confusing. Can you provide a demo please? How to use `useRouter ` in composables directory?

**Comment by danielroe** [comment]
```ts
import { useRouter } from 'vue-router';

export function useNavigation() {
  const router = useRouter()
  function navigateTo(url: string) {
    router.push(url)
  }
  return { navigateTo }
}
```

**Comment by weisiqian** [comment]
thank you

**Comment by weisiqian** [comment]
thank you @danielroe
