### ISSUE TITLE
It looks like #config isn't defined for TypeScript?

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#1751]
### Discussed in https://github.com/nuxt/framework/discussions/1745

<div type='discussions-op-text'>

<sup>Originally posted by **jeremeevans** November  5, 2021</sup>
tsconfig.json has: `"extends": "./.nuxt/tsconfig.json"` but I still get this error. It does build and work... so not breaking things, just wondering if I need to update something.

![image](https://user-images.githubusercontent.com/1747006/140578014-53d97d25-3adb-4f47-a9ad-bb47683adaf0.png)
</div>

**Comment by tobiasdiez** [comment]
It would be nice if it could infer the type based on what is specified for public/privateRuntimeConfig in the nuxt config. The same applies to `useRuntimeConfig`.

By the way, `#config` doesn't seem to be documented yet.
