### ISSUE TITLE
Errors after add nuxt bridge to clean project

### ISSUE THREAD

**Issue by maZ123akalidov** [nuxt/framework#1764]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27270734.ab1c6cb4`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `pwa`, `build`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/pwa@3.3.5`
- Build Modules:    `@nuxt/bridge@3.0.0-27268729.5b8e10f`

### Describe the bug

`error: failed to load plugin '@typescript-eslint' declared in '.eslintrc.js » @nuxtjs/eslint-config-typescript': cannot find module 'typescript'`

```
/home/runner/work/project/project/pages/index.vue
Error:   1:1  error  Component name "index" should always be multi-word  vue/multi-word-component-names
```

### Reproduction

run clean project and add nuxt bridge

**Comment by danielroe** [comment]
This doesn't look like an issue with Nuxt Bridge. If you think it is, would you provide a reproduction and I'll reopen this?

**Comment by eerison** [comment]
I'm with the same error :/ it's happen after I install nuxt bridge 😞

**Comment by Balthasar42** [comment]
I have the same error too. Also with layouts/default.vue
 1:1  error  Component name "default" should always be multi-word  vue/multi-word-component-names

**Comment by vladimir-golovchenko** [comment]
It looks like it is coming from [eslint-plugin-vue](https://eslint.vuejs.org/rules/multi-word-component-names.html).
.To fix it add *index* name to *ignore*-list in *eslintrc*:
```
{
  ..
  "rules": {
    ..
    "vue/multi-word-component-names": [
      "error",
      {
        "ignores": ["index"]
      }
    ]
  }
}
```
