### ISSUE TITLE
Vue Warn: Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js"

### ISSUE THREAD

**Issue by jimhucksly** [nuxt/framework#1766]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.0.0-27268729.5b8e10f`
- Package Manager:  `npm@6.14.15`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

```
[Vue warn]: Component provided template option but runtime compilation is not supported in this build of Vue. Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js". 

runtime-core.esm-bundler.js:6568 [Vue warn]: Hydration node mismatch:
```

### Reproduction

https://gitlab.com/jimhucksly/pitertour/-/tree/master

**Comment by rjurado01** [comment]
I have the same problem when I try to use `.js` components instead of `.vue`:

```js
export default {
  template: '<h1>App</h1>',

  setup() {
    console.log('setup')
  }
}
```

I tried to fix this warn added this to nuxt config:

```js
import { defineNuxtConfig } from 'nuxt3'

import vue from '@vitejs/plugin-vue'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  target: 'static',

  vite: {
    resolve: {
      alias: {
        vue: 'vue/dist/vue.esm-bundler'
      }
    },

    plugins: [
      vue()
    ]
  }
})
```

But then I have this other warn: `runtime-core.esm-bundler.js:6589 [Vue warn]: Component is missing template or render function. at <NuxtRoot>`

How we should configure nuxt3 to work with `template` option ?

**Comment by rjurado01** [comment]
I see that Nuxt use default rootComponent that is not configurable: https://github.com/nuxt/framework/blob/13dd2b98ea020df310a905b5a9eee9e5705496cd/packages/nuxt3/src/core/app.ts#L66
