### ISSUE TITLE
infer types for runtimeConfig

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#1785]
Follow-up on https://github.com/nuxt/framework/pull/1783#discussion_r744606478

**Comment by rrmesquita** [comment]
Hi @danielroe, where you are in this issue? I was able to get the framework to generate simple `typeof` results of the keys in the runtime config and output them on `.nuxt/types/schema.d.ts` which I found appropriate. Private ones are added as optional as they can be unavailable in certain contexts. For more complex inferences, I believe we would have to use TypeScript's compilation API, [this SO question](https://stackoverflow.com/q/67222224/8434690) shows a hint on how to achieve that.

FYI: https://github.com/rrmesquita/framework/commit/ca999a70847beb8bbfc3da0cba78c6f8635f7bbb is a sketch of what it could look like

Thanks!
