### ISSUE TITLE
$router types missing

### ISSUE THREAD

**Issue by nandi95** [nuxt/framework#1794]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27272804.ca557e7`
- Package Manager:  `npm@8.1.3`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `ssr`, `target`, `meta`, `build`, `css`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Describe the bug

In defineNuxtPlugin I did not see a router property. I tried to use useRouter() but that returned undefined. On inspection of the given nuxt to the callback, it in fact has a $router property.
This has happened while having multiple pages.
It seem this should be documented to the user as per this suggestion: https://github.com/nuxt/framework/issues/1707#issuecomment-961983939

### Reproduction

none

### Additional context

https://github.com/nuxt/framework/pull/1781
https://github.com/nuxt/framework/pull/1603

**Comment by danielroe** [comment]
This should now be resolved in https://github.com/nuxt/framework/pull/2001, with the proviso that plugin injections are not typed via the nuxtApp passed into the plugin, but can be typed like so:
```js
export default defineNuxtPlugin(() => {
  const { $router } = useNuxtApp()
})
```
