### ISSUE TITLE
loadNuxt not found

### ISSUE THREAD

**Issue by jbmolle** [nuxt/framework#1795]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27274229.29599f0`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `buildModules`, `intlify`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.1.8`, `nuxt-windicss@2.0.12`

### Describe the bug

nuxt-windicss use @nuxt/kit: latest as a dependency.
As soon as I download the package nuxt-windicss, my app cannot start and throws an error "loadNuxt not found".

In packages/nuxi/src/utils/kit.ts, we have the function loadKit.
This function is called in packages/nuxi/src/commands/dev.ts at line 36
```
const { loadNuxt, buildNuxt } = await loadKit(rootDir)
```
The problem is that loadKit returns a default key. So we should either do 
```
const { default as defaultKit } = await loadKit(rootDir)
const { loadNuxt, buildNuxt } = defaultKit
```
Or change packages/nuxi/src/utils/kit.ts with
```
import { importModule } from './cjs'

export const loadKit = async (rootDir: string): Promise<typeof import('@nuxt/kit')> => {
  try {
    const module = await importModule('@nuxt/kit', rootDir) as typeof import('@nuxt/kit')
    return module.default
  } catch (e) {
    if (e.toString().includes("Cannot find module '@nuxt/kit'")) {
      throw new Error('nuxi requires `@nuxt/kit` to be installed in your project. Try installing `nuxt3` or `@nuxt/bridge` first.')
    }
    throw e
  }
}
```

### Reproduction

The problem comes from the last version of nuxt-windicss which uses @nuxt/kit: latest.
Reproduction:
npx nuxi init nuxt3-app

Then add in package.json, devDependencies -> "nuxt-windicss": "^2.0.12"

npm run dev fails with "Cannot start nuxt:  loadNuxt is not a function"

**Comment by jbmolle** [comment]
Hi @pi0 @danielroe 
Actually the problem arises when I use @nuxt/kit
I don't know why but the lib uses CJS so when I start the app I get the warning message: "You are using CommonJS version of `@nuxt/kit` that is an ESM-only package. CJS support will be dropped in stable release."
And loadKit returns a default key.
If I replace @nuxt/kit with @nuxt/kit-edge then everything works fine and I'm using ESM.
Shouldn't we use the proxy package?
Thanks for your feedback

**Comment by WhiteR4bbitt** [comment]
Just wanted to confirm I ran into this as well and took the notes about proxy, just want to share the update for anyone unaware.

Add (or update) `@nuxt/kit` in your local package:
`"@nuxt/kit": "npm:@nuxt/kit-edge@latest"`

Which seems to resolve the issue for now (I also have `nuxt-windicss` installed and noticed this is how they are injecting `kit`)

**Comment by jbmolle** [comment]
Yes that the solution but the last version of nuxt-windicss (2.0.12) is using "@nuxt/kit": "latest" so one should stick to version 2.0.11 for the moment.

**Comment by f3ltron** [comment]
Is anyone have create an issue with windi ?

**Comment by pi0** [comment]
Hi. To avoid mixed syntax issues I removed CJS support from [`@nuxt/kit` stub](https://github.com/nuxt/nuxt3-stubs/tree/main/packages/kit) in `0.8.0-edge` so it is identical to `@nuxt/kit-edge` now.

The issue with the CJS default export should be gone if you recreate the lock file (Using `npx nuxi upgrade --force`)

**Comment by jbmolle** [comment]
@pi0 you rock!
Thanks a lot, it's all good

**Comment by f3ltron** [comment]
It works for me too 🚀
