### ISSUE TITLE
cant not use typescript decorator 

### ISSUE THREAD

**Issue by weisiqian** [nuxt/framework#1802]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-27274229.29599f0`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

error when using typescript decorator. I just define a class. here is the code.

```
import {
  Contains,
  IsInt,
  Length,
  IsEmail,
  IsFQDN,
  IsDate,
  Min,
  Max,
} from 'class-validator';

export class Post {
  @Length(10, 20)
  title: string;

  @Contains('hello')
  text: string;

  @IsInt()
  @Min(0)
  @Max(10)
  rating: number;

  @IsEmail()
  email: string;

  @IsFQDN()
  site: string;

  @IsDate()
  createDate: Date;
}
```

then import the class in componet.

```
<template>
  <div>
    page 1
  </div>
</template>

<script lang="ts" setup>
import { Post } from '@/entity/post';
// import {
//   validate,
//   validateOrReject
// } from 'class-validator';

let post = new Post();
post.title = 'Hello'; // should not pass
post.text = 'this is a great post about hell world'; // should not pass
post.rating = 11; // should not pass
post.email = 'google.com'; // should not pass
post.site = 'googlecom'; // should not pass

// validate(post).then(errors => {
//   // errors is an array of validation errors
//   if (errors.length > 0) {
//     console.log('validation failed. errors: ', errors);
//   } else {
//     console.log('validation succeed');
//   }
// });

// validateOrReject(post).catch(errors => {
//   console.log('Promise rejected (validation failed). Errors: ', errors);
// });

</script>

```

when i run ```npm run dev```, then open browser. the dev server throw a Error.

![image](https://user-images.githubusercontent.com/19994951/140939398-819b8f82-2f28-41a0-9232-13e857b386aa.png)

### Reproduction

[repo](https://github.com/weisiqian/nuxt3-app)

**Comment by ayalon** [comment]
Add this to your nuxt.config.js and try again. It will work but you will run into other issues. nuxt auto component import will not work for example.

```
  build: {
     transpile: ['vue-property-decorator'],
   },
```

**Comment by danielroe** [comment]
Please see https://v3.nuxtjs.org/concepts/esm. These are upstream issues with these libraries.

Here's a workaround.

```js
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  build: {
    transpile: ['class-validator', 'libphonenumber-js'],
  }
})
```
