### ISSUE TITLE
Add example using `defineNuxtConfig`

### ISSUE THREAD

**Issue by Atinux** [nuxt/framework#1811]
https://v3.nuxtjs.org/docs/directory-structure/nuxt.config

![Screenshot 2021-11-10 at 00 40 41](https://user-images.githubusercontent.com/904724/141023164-e2943e6b-5336-44b6-bea7-18155b840dfc.png)

**Comment by f3ltron** [comment]
Do you mean for each sub part right @Atinux  ?  Going to work on it already added one for meta

**Comment by n4an** [comment]
how to use await inside defineNuxtConfig
```
export default async defineNuxtConfig({})
```

**Comment by n4an** [comment]
```
export default defineNuxtConfig(async () => {}) ?

export default defineNuxtConfig(async () => { return {} }) ?
```

**Comment by pi0** [comment]
@n4an ~> https://github.com/nuxt/framework/issues/3667
