### ISSUE TITLE
Netlify Build Failing 

### ISSUE THREAD

**Issue by fanckush** [nuxt/framework#1826]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `0.0.0`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug
Am I doing something wrong?

Netlify Deploy is failing
``` sh
1:48:13 PM:   2. Functions bundling                                         
1:48:13 PM: ────────────────────────────────────────────────────────────────
1:48:13 PM: ​
1:48:13 PM: Packaging Functions from .netlify/functions-internal directory:
1:48:13 PM:  - server/server.ts
1:48:13 PM: ​
1:48:13 PM:  > .netlify/functions-internal/server/node_modules/node-fetch/src/index.js:9:17: error: Could not resolve "node:http" (mark it as external to exclude it from the bundle)
1:48:13 PM:     9 │ import http from 'node:http';
1:48:13 PM:       ╵                  ~~~~~~~~~~~
1:48:13 PM:  > .netlify/functions-internal/server/node_modules/node-fetch/src/index.js:10:18: error: Could not resolve "node:https" (mark it as external to exclude it from the bundle)
1:48:13 PM:     10 │ import https from 'node:https';
1:48:13 PM:        ╵                   ~~~~~~~~~~~~
1:48:13 PM:  > .netlify/functions-internal/server/node_modules/node-fetch/src/index.js:11:17: error: Could not resolve "node:zlib" (mark it as external to exclude it from the bundle)
1:48:13 PM:     11 │ import zlib from 'node:zlib';
1:48:13 PM:        ╵                  ~~~~~~~~~~~
1:48:13 PM:  > .netlify/functions-internal/server/node_modules/node-fetch/src/index.js:12:52: error: Could not resolve "node:stream" (mark it as external to exclude it from the bundle)
1:48:13 PM:     12 │ import Stream, {PassThrough, pipeline as pump} from 'node:stream';
1:48:13 PM:        ╵                                                     ~~~~~~~~~~~~~
1:48:13 PM:  > .netlify/functions-internal/server/node_modules/node-fetch/src/body.js:8:34: error: Could not resolve "node:stream" (mark it as external to exclude it from the bundle)
1:48:13 PM:     8 │ import Stream, {PassThrough} from 'node:stream';
1:48:13 PM:       ╵                                   ~~~~~~~~~~~~~
1:48:13 PM:  > .netlify/functions-internal/server/node_modules/node-fetch/src/body.js:9:31: error: Could not resolve "node:util" (mark it as external to exclude it from the bundle)
1:48:13 PM:     9 │ import {types, deprecate} from 'node:util';
1:48:13 PM:       ╵                                ~~~~~~~~~~~
1:48:13 PM:  > .netlify/functions-internal/server/node_modules/node-fetch/src/request.js:10:34: error: Could not resolve "node:url" (mark it as external to exclude it from the bundle)
1:48:13 PM:     10 │ import {format as formatUrl} from 'node:url';
1:48:13 PM:        ╵                                   ~~~~~~~~~~
1:48:13 PM:  > .netlify/functions-internal/server/node_modules/node-fetch/src/headers.js:7:20: error: Could not resolve "node:util" (mark it as external to exclude it from the bundle)
1:48:13 PM:     7 │ import {types} from 'node:util';
1:48:13 PM:       ╵                     ~~~~~~~~~~~
1:48:13 PM:  > .netlify/functions-internal/server/node_modules/node-fetch/src/headers.js:8:17: error: Could not resolve "node:http" (mark it as external to exclude it from the bundle)
1:48:13 PM:     8 │ import http from 'node:http';
1:48:13 PM:       ╵                  ~~~~~~~~~~~
1:48:13 PM:  > .netlify/functions-internal/server/node_modules/fetch-blob/from.js:1:59: error: Could not resolve "node:fs" (mark it as external to exclude it from the bundle)
1:48:13 PM:     1 │ import { statSync, createReadStream, promises as fs } from 'node:fs'
1:48:13 PM:       ╵                                                            ~~~~~~~~~
1:48:13 PM: 10 of 12 errors shown (disable the message limit with --log-limit=0)
1:48:13 PM: ​
1:48:13 PM: ────────────────────────────────────────────────────────────────
1:48:13 PM:   Dependencies installation error                               
1:48:13 PM: ────────────────────────────────────────────────────────────────
1:48:13 PM: ​
```

### Reproduction

-

**Comment by danielroe** [comment]
@fanckush See if you can set `NODE_VERSION=16` (or 14.13.1+) in the [environment variables](https://docs.netlify.com/configure-builds/environment-variables/) configuration section.

**Comment by fanckush** [comment]
@danielroe thanks for the quick reply, 
I get the same error with both `NODE_VERSION=16` as well as `NODE_VERSION=`

**Comment by danielroe** [comment]
Then I think this should be raised upstream with Netlify as it's happening not within the Nuxt build step but within packaging functions.

cc: @ascorbic

**Comment by fanckush** [comment]
Thanks! interestingly, in the logs Netlify says:
```
A Netlify Function failed to require one of its dependencies
Please make sure it is present in the site's top-level "package.json"
```
this makes it seem like it's on my end to add something

**Comment by danielroe** [comment]
@fanckush My reading of the error message is that the script bundling the functions is expecting `node:http` (for example) to be a dependency, not realising that it is a node built-in.

**Comment by Hrishikesh-K** [comment]
There's a related thread on Netlify Forums: https://answers.netlify.com/t/deploying-a-new-nuxt-3-app-result-to-error/47029

**Comment by netlify-team-account-1** [comment]
This seems like a regression related to a change I introduced into Netlify's bundling process. Looking into it!

**Comment by netlify-team-account-1** [comment]
I was able to reproduce & fix this in https://github.com/netlify/zip-it-and-ship-it/pull/802 🥳

**Comment by pi0** [comment]
Thanks for fix @netlify-team-account-1 <3

I'm wondering why netlify has to re-bundle nitro functions that are already made for Nelify? /cc @ascorbic

**Comment by ascorbic** [comment]
Correct. AWS lambda doesn't support ESM, so we need to transpile it all. If Nitro can generate a node 14 -compatible cjs bundle then it could run it unchanged

**Comment by pi0** [comment]
> Correct. AWS lambda doesn't support ESM, so we need to transpile it all. If Nitro can generate a node 14 -compatible cjs bundle then it could run it unchanged

I was kinda assuming Netlify does dark magic for supporting ESM with lambda till today 😆 But of course we can update netlify preset to emit CJS (or CJS entry). We need it for generic AWS support anyway.

BTW may I ask how it works? If the function is using `.js` netlify won't use esbuild or there is a specific configuration to test?

**Comment by danielroe** [comment]
I think it just might be possible to emit the right kind of entrypoint (while keeping the rest of the lambda ESM). There are some examples out there of people who've done the same with AWS Lambda.

**Comment by productdevbook** [comment]
### Environment


------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27277330.202617b`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.5`
------------------------------

### Describe the bug

https://v3nuxt.netlify.app

<img width="1287" alt="CleanShot 2021-11-11 at 17 33 30@2x" src="https://user-images.githubusercontent.com/38668796/141315700-5cf252bf-66c9-4414-b2ba-bc58c9def2ad.png">


### Reproduction

https://github.com/productdevbook/nuxt3-app

### Additional context

_No response_

### Logs

_No response_

**Comment by ascorbic** [comment]
> I was kinda assuming Netlify does dark magic for supporting ESM with lambda till today 😆 But of course we can update netlify preset to emit CJS (or CJS entry). We need it for generic AWS support anyway.
> BTW may I ask how it works? If the function is using .js netlify won't use esbuild or there is a specific configuration to specify not building?

That does sound like the simplest solution. Changing it to .js should just work: it will switch back to the default bundler, which doesn't compile anything. I made the entrypoint `.ts` because at the time that was the simplest way to switch the bundler into `esbuild` mode without needing to add any config (now `.mjs` will do the same).

**Comment by ascorbic** [comment]
> I think it just might be possible to emit the right kind of entrypoint (while keeping the rest of the lambda ESM). There are some examples out there of people who've done the same with AWS Lambda, e.g. here.

@danielroe Would this give any benefit aside from consistency in compiling most targets to ESM?

**Comment by pi0** [comment]
>  Would this give any benefit aside from consistency in compiling most targets to ESM?

Yes! Most importantly for dealing with `esm-only` packages. We have another option to not use vercel/nft and bundle all `node_modules` but it removes benefit of externals support.

**Comment by florian-lefebvre** [comment]
> 
> ### Environment
> 
>     * Operating System: `Darwin`
> 
>     * Node Version:     `v16.13.0`
> 
>     * Nuxt Version:     `3.0.0-27277330.202617b`
> 
>     * Package Manager:  `yarn@1.22.15`
> 
>     * Bundler:          `Vite`
> 
>     * User Config:      `buildModules`, `build`
> 
>     * Runtime Modules:  `-`
> 
>     * Build Modules:    `@pinia/nuxt@0.1.5`
> 
> 
> ### Describe the bug
> 
> https://v3nuxt.netlify.app
> 
> <img alt="CleanShot 2021-11-11 at 17 33 30@2x" width="1287" src="https://user-images.githubusercontent.com/38668796/141315700-5cf252bf-66c9-4414-b2ba-bc58c9def2ad.png">
> ### Reproduction
> 
> https://github.com/productdevbook/nuxt3-app
> ### Additional context
> 
> _No response_
> ### Logs
> 
> _No response_

I have the same right now, I'll use Vercel until this issue is resolved.

**Comment by ascorbic** [comment]
@florian-lefebvre Did you just deploy that? The fix should have been live for a while now but it will need to be a new deploy before it will work.

**Comment by florian-lefebvre** [comment]
It still doesn't work. I just deployed it, here is the link https://youthful-gates-3fd198.netlify.app/.

**Comment by arnauddsj** [comment]
I confirm same problem here. Had the same error as the original post and now getting same error as florian-lefebvre on my site https://stoic-fermat-995d10.netlify.app/

![image](https://user-images.githubusercontent.com/49342194/141358198-c347ecea-3328-4b81-bd48-1577adef9e74.png)

**Comment by Thomasevano** [comment]
Hello, same issue here using nuxt 3 too
<img width="2095" alt="Capture d’écran 2021-11-12 à 01 31 10" src="https://user-images.githubusercontent.com/22095896/141388289-e839c1bc-a021-4842-ab17-2cf8fd598ff2.png">

**Comment by netlify-team-account-1** [comment]
Importing Node modules with the `node:` prefix was introduced in [Node v14](https://github.com/nodejs/node/releases/tag/v14.18.0). The stacktraces seem like they're from Node v12, which is currently the default runtime on Netlify (probably going to be v14 soon). Please upgrade your deployment to v14 by setting the `AWS_LAMBDA_JS_RUNTIME` environment variable to `nodejs14.x`. This should resolve the error you're seeing.

**Comment by netlify-team-account-1** [comment]
Updated env vars only go into effect on new deploys, did you redeploy your site?

**Comment by leon0399** [comment]
@netlify-team-account-1 just tried to re-deploy my site with these envs, still same error
![image](https://user-images.githubusercontent.com/1759654/141450418-8a605cbd-e278-4c86-9a59-a478ee6ba0a6.png)
```json
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'node:http'\nRequire stack:\n- /var/task/.netlify/functions-internal/server/server.js\n- /var/task/server.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'node:http'",
    "Require stack:",
    "- /var/task/.netlify/functions-internal/server/server.js",
    "- /var/task/server.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
    "    at Module.load (internal/modules/cjs/loader.js:937:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}
```

**Comment by ascorbic** [comment]
Thanks. That is very strange. We'll be looking into it today.

**Comment by ascorbic** [comment]
It seems the frustrating answer is that the AWS Lambda runtime is currently on Node v14.17.4, while `node:` prefix support was introduced in Node 14.18! We're trying to think of a solution that's not "don't use `node:` prefixes"

**Comment by ascorbic** [comment]
It's node-fetch that's the problem: they claim to support Node 12, but in the latest release changed all the imports to use the prefix. I'm going to open an issue.

**Comment by ascorbic** [comment]
OK, this is the issue covering it: https://github.com/node-fetch/node-fetch/issues/1367
We're looking into implementing the esbuild plugin solution. Thanks everyone for your patience!

**Comment by ascorbic** [comment]
> I think it just might be possible to emit the right kind of entrypoint (while keeping the rest of the lambda ESM). There are some examples out there of people who've done the same with AWS Lambda, e.g. here.

Separately, @danielroe: I've confirmed that this should work for us too, and would mean it woudln't be re-bundled.

**Comment by ascorbic** [comment]
And, of course, should work for the regular lambda preset too

**Comment by netlify-team-account-1** [comment]
I deployed https://github.com/netlify/zip-it-and-ship-it/pull/806 to production. The issue should not occur anymore. If it does, please let me know :)

**Comment by productdevbook** [comment]
> I deployed [netlify/zip-it-and-ship-it#806](https://github.com/netlify/zip-it-and-ship-it/pull/806) to production. The issue should not occur anymore. If it does, please let me know :)

fixed thank you

**Comment by florian-lefebvre** [comment]
Fixed !

**Comment by fanckush** [comment]
Works great!! The Manual ENV vars are not needed either! I was able to get it working out-of-the-box 
I'll close the issue
