### ISSUE TITLE
yarn dev nuxt telementry disabled

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#1830]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27257777.293dc11a`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Webpack`
- User Config:      `components`, `buildModules`, `privateRuntimeConfig`, `plugins`, `manifest`, `plausible`, `image`, `colorMode`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.0.9`, `@nuxt/image@0.6.0`, `@nuxtjs/pwa@3.3.5`, `vue-plausible@1.2.1`, `@nuxtjs/html-validator@0.6.0`, `@nuxtjs/color-mode@2.1.1`, `@nuxt/bridge@3.0.0-27258294.bdbfa36`
------------------------------

### Describe the bug

![CleanShot_2021-11-10_at_19 52 48](https://user-images.githubusercontent.com/38668796/141168642-b13ac47d-fb47-45fd-8f88-7d56ecfb4252.gif)
<img width="961" alt="CleanShot_2021-11-10_at_20 56 132x" src="https://user-images.githubusercontent.com/38668796/141168688-e5655dab-cd1f-4baf-9e24-bc3de8d73c6a.png">

### Reproduction

https://github.com/productdevbook/modules/tree/new_design

### Additional context

@danielroe say `NUXT_TELEMETRY_DISABLED=1 yarn dev` and fixed

**Comment by pi0** [comment]
You can permanently disable telemetry using `echo "telemetry.enabled=false" > ~/.nuxtrc`. 

I couldn't reproduce issue with `nuxi` CLI and pressing `Y` [enter] enables telemetry:

![image](https://user-images.githubusercontent.com/5158436/141188557-136a5c3d-dc41-4d1f-956d-6999295c7287.png)

If you still experience issues, please report to [nuxt/telemetry](https://github.com/nuxt/telemetry)
