### ISSUE TITLE
yarn build/start import @apollo/client/core/core.cjs.js?

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#1846]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27276275.abfbd2f`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

yarn build
yarn start

### Reproduction

https://github.com/productdevbook/productdevbook.com

### Logs

```shell
➜  productdevbook.com git:(main) yarn start
yarn run v1.22.15
$ node .output/server/index.mjs
Listening on http://localhost:3000
Directory import '/Users/productdevbook/Documents/GitHub/productdevbook.com/.output/server/node_modules/@apollo/client/core' is not supported resolving ES modules imported from /Users/productdevbook/Documents/GitHub/productdevbook.com/.output/server/chunks/app/server.mjs
Did you mean to import @apollo/client/core/core.cjs.js?
  at new NodeError (node:internal/errors:371:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:412:17)  
  at moduleResolve (node:internal/modules/esm/resolve:932:10)  
  at defaultResolve (node:internal/modules/esm/resolve:1044:11)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)  
  at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by ririen** [comment]
Workaround, import Apollo like this:

```js
import { ApolloClient, InMemoryCache } from '@apollo/client/core/core.cjs.js'
```

**Comment by tobiasdiez** [comment]
I have the same problem with a couple of libraries (mostly graphql/apollo related) but the workaround of @ririen worked in these cases as well: https://github.com/JabRef/JabRefOnline/pull/480/commits/afc92ac85f317fb81d32f07be00944209eebfdae

**Comment by danielroe** [comment]
This is a helpful link: https://v3.nuxtjs.org/concepts/esm

These are upstream issues with these libraries and should probably be reported there.

**Comment by productdevbook** [comment]
@danielroe https://github.com/apollographql/apollo-client/issues/9048#issuecomment-979014870

**Comment by danielroe** [comment]
@productdevbook Have you tried using named imports?

**Comment by productdevbook** [comment]
> named imports

import {ApolloClient,
  InMemoryCache,
  createHttpLink} from '@apollo/client/core/core.cjs';

yes some problem

**Comment by xxSkyy** [comment]
I've got same problem, no workarounds provided above works

**Comment by xxSkyy** [comment]
Applying those patches work for temporary workaround
https://github.com/JabRef/JabRefOnline/tree/afc92ac85f317fb81d32f07be00944209eebfdae/patches

**Comment by pipinet** [comment]
Same problem，how to fix it?

**Comment by ddegooijer** [comment]
How can you apply those patches? Can't seem to get it working for a production build :(

**Comment by tobiasdiez** [comment]
You can use `patch-package` to apply these patches automatically in your repo.

**Comment by ddegooijer** [comment]
Thanks, but how do you apply those patches? First time i'm using this. 

Tried downloading the patches and put them in the patches dir, but get the following warning: Unrecognized patch file in patches directory patch.patch

**Comment by tobiasdiez** [comment]
No idea, never had this issue. Maybe you use a different version of the packages, or try to apply patches for packages that you are not using. You can always change the files in `node_modules` manually and then use `patch-package` to create the patches for your setup. Note also that some of the patches are dealing with different issues I had during the upgrade from nuxt2 > bridge. I think for this issue here only https://github.com/JabRef/JabRefOnline/blob/main/patches/%40vue%2Bapollo-composable%2B4.0.0-alpha.16.patch is needed.

**Comment by libreyvip** [comment]
Hi, I have the same problem, have you solved it?
