### ISSUE TITLE
[DEV] Bridge fixture breaks on Vite Dev

### ISSUE THREAD

**Issue by antfu** [nuxt/framework#1848]
### Environment

In development of this repo

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0`
- Package Manager:  `yarn@3.1.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------the 

### Describe the bug

Check out at d701238d275eed9fe94f872130a8d6683fa541d7

```bash
cd test/fixtures/bridge
TEST_BRIDGE_VITE=1 yarn dev
```

Will emit this error:

```bash
 WARN  [worker] Named export 'isWindows' not found. The requested module 'std-env' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'std-env';
const { provider, isWindows } = pkg;


  import { provider, isWindows } from 'std-env';
  ^^^^^^^^^
  SyntaxError: Named export 'isWindows' not found. The requested module 'std-env' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'std-env';
  const { provider, isWindows } = pkg;
```

Yarn Why:

```bash
➜ yarn why std-env
├─ @nuxt/cli@npm:2.15.8
│  └─ std-env@npm:2.3.1 (via npm:^2.3.0)
│
├─ @nuxt/config@npm:2.15.8
│  └─ std-env@npm:2.3.1 (via npm:^2.3.0)
│
├─ @nuxt/kit@workspace:packages/kit
│  └─ std-env@npm:3.0.1 (via npm:^3.0.1)
│
├─ @nuxt/nitro@workspace:packages/nitro
│  └─ std-env@npm:3.0.1 (via npm:^3.0.1)
│
├─ @nuxt/telemetry@npm:1.3.6
│  └─ std-env@npm:2.3.1 (via npm:^2.3.0)
│
├─ @nuxt/webpack@npm:2.15.8
│  └─ std-env@npm:2.3.1 (via npm:^2.3.0)
│
├─ webpackbar@npm:4.0.0
│  └─ std-env@npm:2.3.1 (via npm:^2.2.1)
│
├─ webpackbar@npm:5.0.2
│  └─ std-env@npm:3.0.1 (via npm:^3.0.1)
│
├─ webpackbar@npm:4.0.0 [92108]
│  └─ std-env@npm:2.3.1 (via npm:^2.2.1)
│
└─ webpackbar@npm:5.0.2 [db454]
   └─ std-env@npm:3.0.1 (via npm:^3.0.1)
```

### Reproduction

-

### Additional context

Potential Solution:

- Avoid using named exports for `std-env`
- Release a new patch of `std-env` v2 which ships ESM
- Use yarn's `resolutions` to enforce the latest version of `std-env` locally (if it does not break anything)

**Comment by pi0** [comment]
Nuxt edge is already updated with std-env. We need to update local lock :)

**Comment by michael-observerly** [comment]
Just wondering what the workaround is for this? Seems to be thrown since running from a fresh install of Nuxt latest?

**Comment by danielroe** [comment]
@michael-observerly If you're experiencing a problem, would you [create a fresh issue](https://github.com/nuxt/framework/issues/new?assignees=&labels=pending+triage%2Cbridge&template=bug-report-bridge.yml)?

**Comment by amery** [comment]
is there a version of nuxt-bridge with this problem fixed?
