### ISSUE TITLE
`useFetch` doesn't work when triggered it outside the setup function

### ISSUE THREAD

**Issue by webfansplz** [nuxt/framework#1852]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.16.1`
- Nuxt Version:     `3.0.0-27276275.abfbd2f`
- Package Manager:  `pnpm@6.17.1`
- Bundler:          `Vite`
- User Config:      `vite`, `env`, `alias`, `srcDir`, `dev`, `app`, `build`, `publicRuntimeConfig`, `meta`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/core/nuxt@6.8.0`, `@pinia/nuxt@0.1.2`

### Describe the bug

```vue
<template>
  <div>
    <h1 @click="fetch">
      hello world
    </h1>
  </div>
</template>

<script setup>

async function fetch() {
  const [{ data: organization }, { data: repos }] = Promise.all([
    useFetch('https://api.github.com/orgs/nuxt'),
    useFetch('https://api.github.com/orgs/nuxt/repos'),
  ]).then(() => {
    console.log(organization)
  })
}
</script>
```
![](https://user-images.githubusercontent.com/22515951/141258360-fb9b5ec4-f4a9-4a46-b76e-6460c0ea795a.png)

### Reproduction

use `useFetch` in the click handle

**Comment by webfansplz** [comment]
https://github.com/nuxt/framework/blob/d701238d275eed9fe94f872130a8d6683fa541d7/packages/nuxt3/src/app/nuxt.ts#L186

That seems to be the reason, `getCurrentInstance()` was return null.

**Comment by danielroe** [comment]
This is by design. `useFetch` shouldn't be triggered in a method; like most composables, it is designed to be run in `setup()`. If you need an on-demand fetch use `$fetch()` instead. Alternatively, you can implement like so:

```js
function useMyThing () {
  const { data, refresh } = 
  const [{ data: organization, refresh: refreshOrganization }, { data: repos, refresh: refreshRepos }] = Promise.all([
    useFetch('https://api.github.com/orgs/nuxt'),
    useFetch('https://api.github.com/orgs/nuxt/repos'),
  ])
  return {
    organization,
    repos,
    fetch: () => Promise.all([refreshOrganization(), refreshRepos()])
  }
}
```

**Comment by webfansplz** [comment]
@danielroe thx
