### ISSUE TITLE
Undefined body in API Routes

### ISSUE THREAD

**Issue by ririen** [nuxt/framework#1860]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27276275.abfbd2f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `buildModules`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.0.12`

### Describe the bug

The API `~/server/api` does not support body in `POST` requests.

### Reproduction

https://codesandbox.io/s/wonderful-darwin-ew029?file=/app.vue

**Comment by ririen** [comment]
I got it. API file must look like this:

```js
import { useBody } from 'h3'

export default async (req, res) => {
    
    const body = await useBody(req)

    return body;
}
```

**Comment by TJacoob** [comment]
@ririen comment worked for me as well. It could be added to the docs, probably on the server folder page.

**Comment by gregg-cbs** [comment]
This needs to be  added to the docs please.
