### ISSUE TITLE
automatically type injections from plugins

### ISSUE THREAD

**Issue by fmcdigital** [nuxt/framework#1863]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-27276275.abfbd2f`
- Package Manager:  `npm@8.0.0`
- Bundler:          `Vite`
- User Config:      `css`, `vite`, `dir`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

The functions from auto imported plugins folder are not recognized by TS

My `can.ts` file:

```
import { defineNuxtPlugin } from '#app';
import { PermissionAttributes } from '@/../types/Permission';
import { Roles } from '@/assets/ts/enums';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.provide('can', async (permission: PermissionAttributes['code']) => {
    const { getUser } = useUser();

    const user = getUser().value;

    const userHasPermission = (perm: PermissionAttributes['code']) =>
      user.Permissions.find((p: PermissionAttributes) => p.code === perm);

    if (userHasPermission(Roles.Master)) return true;

    if (userHasPermission(Roles.Admin) && permission !== Roles.Master) return true;

    if (!userHasPermission(permission)) return false;

    return true;
  });
});
```

And when I use it on a `.vue` file, it works, but TS doesn't recognizes it:

![image](https://user-images.githubusercontent.com/12851638/141297990-8a9c80a8-55e0-4b4d-b513-39c5124d88e1.png)

### Reproduction

https://codesandbox.io/s/infallible-river-1be8h?file=/app.vue

On codesandbox the error is not shown, but it happens using VS Code.

**Comment by danielroe** [comment]
[Here are the docs](https://v3.nuxtjs.org/docs/directory-structure/plugins#typing-plugins) on how to type plugin injections. I've raised [an RFC](https://github.com/nuxt/framework/discussions/1864) to improve things, and will leave this open as a potential feature request, for now.

**Comment by pi0** [comment]
Let's track from one place until reaching to a working idea :) For now, it is possible to augment `#app.NuxtApp` interface for this.
