### ISSUE TITLE
AWS Lambda not compatible with nitro preset Lambda

### ISSUE THREAD

**Issue by needfortri** [nuxt/framework#1872]
### Describe the bug

I'm trying to deploy my nuxt3 build into a AWS Lambda handler using this official [documentation](https://v3.nuxtjs.org/docs/deployment/presets/lambda) 

Following the tutorial, I created a index.js file at the root of the final build (obtained by running `nuxi build`) and uploaded the whole code on my Lambda.

index.js file :
```
import { handler } from './.output/server'

exports.handler = async event => {
  const { statusCode, headers, body } = handler({ path: '/' })
  return { statusCode, headers, body }
}
```

Which is importing handler from ./.output/server/index.mjs, a file produced by `nuxi build`

Repo : 
[https://github.com/needfortri/nuxt3-lambda-testing-deploy](https://github.com/needfortri/nuxt3-lambda-testing-deploy)

### Issue

AWS Lambda w Node 14.x is not supporting native import.
`SyntaxError: Cannot use import statement outside a module`

Replacing `import` by `require` won't work either, because the target is a .mjs file (index.mjs)

How may we fix this please ?

### Reproduction

Create a sample app
```
npx nuxi init nuxt3-lambda
cd nuxt3-lambda
npm install
```

Change nuxt.config.ts file to
```
import { defineNuxtConfig } from 'nuxt3'
export default defineNuxtConfig({
  nitro: {
    preset: 'lambda'
  }
})
```

Build the app
```
npm run build
```

Add index.js at the root that contains :  
```
import { handler } from './.output/server'

exports.handler = async event => {
  const { statusCode, headers, body } = handler({ path: '/' })
  return { statusCode, headers, body }
}
```

At this stage you will end up with a source code like this : 
[https://github.com/needfortri/nuxt3-lambda-testing-deploy](https://github.com/needfortri/nuxt3-lambda-testing-deploy)

Upload the whole code to a AWS Lambda function and try to test it with a random payload
This will result with error :  
```
{
  "errorType": "Runtime.UserCodeSyntaxError",
  "errorMessage": "SyntaxError: Cannot use import statement outside a module",
  "trace": [
    "Runtime.UserCodeSyntaxError: SyntaxError: Cannot use import statement outside a module",
    "    at _loadUserApp (/var/runtime/UserFunction.js:98:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
    "    at Module.load (internal/modules/cjs/loader.js:937:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}
```

**Comment by newbeea** [comment]
you need add index.mjs，and use esm syntax.
like following:
```
"use strict";
import { handler as _handler } from "./server/index.mjs";

const handler = async (event) => {
  const { statusCode, headers, body } = await _handler({ path: "/" });
  return { statusCode, headers, body };
}; 
export {
  handler
};
```

**Comment by danielroe** [comment]
Do you still find this to be true? It seems on 6 January AWS Lambda added support for native ESM. It seems that it should be sufficient to name the entrypoint (as we do) with a `.mjs` extension.

**Comment by danielroe** [comment]
Closing to follow in https://github.com/nuxt/framework/issues/1895

**Comment by jerryisbusy** [comment]
I can deploy the default nuxt3 project to aws lambda, by specify the handler to '.output/server/index.hander' which is imported from "./chunks/nitro/aws-lambda.mjs".

May be you can try ?
