### ISSUE TITLE
npx nuxi init nuxt3-app err

### ISSUE THREAD

**Issue by chaotianque** [nuxt/framework#1878]
### Environment

npx: installed 2 in 4.094s
Nuxt CLI v3.0.0-27277498.850ef69                                                                              15:48:15
RootDir: D:\work\projects\WebstormProjects\vue3                                                               15:48:15
Nuxt project info:                                                                                            15:48:15

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.17.3`
- Nuxt Version:     `0.0.0`
- Package Manager:  `unknown`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt.js/issues/new                                                15:48:15

👉 Suggest an improvement: https://github.com/nuxt/nuxt.js/discussions/new

👉 Read documentation: https://nuxtjs.org

### Describe the bug

npx: installed 2 in 3.069s
Nuxt CLI v3.0.0-27277498.850ef69                                                                              15:40:15

 WARN  could not fetch remote https://github.com/nuxt/starter                                                 15:40:37

 WARN  Make sure you have installed git correctly

### Reproduction

npx: installed 2 in 3.069s
Nuxt CLI v3.0.0-27277498.850ef69                                                                              15:40:15

 WARN  could not fetch remote https://github.com/nuxt/starter                                                 15:40:37

 WARN  Make sure you have installed git correctly

**Comment by J-Kern** [comment]
@chaotianque `"WARN Make sure you have installed git correctly"` indicates that you may not have git setup correctly, it may not be available in your path.

Can you please post the output of running the command: `git --version`?

**Comment by chaotianque** [comment]
![image](https://user-images.githubusercontent.com/17331025/141599406-d96d656b-dc2b-4e7a-96ec-fe8a069fca5a.png)

**Comment by J-Kern** [comment]
Please make sure you have an active internet connection whilst creating the nuxt app. 
The error may be caused by a git pull timeout.

**Comment by 0xbul1** [comment]
same error with me,
maybe its caused by vpn software.

> 1. keep vpn software global connect('直连').
> 2. make sure you can get github content in this status.

I solved this by these steps.

**Comment by bosswhale** [comment]
Same issue for me:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/17161816/170227444-dd2be298-0c34-4e2d-80ef-245aa6b48e0c.png">

**Comment by Quartzar** [comment]
Same issue for me also:
![image](https://user-images.githubusercontent.com/79379455/170254277-22f4e02e-b28b-4e0e-b7c7-925cb97e9914.png)

**Comment by Quartzar** [comment]
@danielroe on the official [Nuxt Content get-started page](https://content.nuxtjs.org/get-started/), that is the command it gives. I want to use `content-v2` as I am just starting and don't want to later have to manually rewrite my project for version 2.

**Comment by manniL** [comment]
@Quartzar `npx nuxi init content-app -t content` will create a project with Nuxt3 (latest RC) and Nuxt Content v2 ☺️

**Comment by Quartzar** [comment]
@manniL this worked, thank you very much. Is there a way to create a Nuxt3 project w/ Nuxt Content v2 with all of the create-nuxt-app configuration options?

**Comment by zkjDream** [comment]
Same issue for me:
![image](https://user-images.githubusercontent.com/63485477/170862996-9a3a3d98-ef01-43d9-83e6-003effc8c527.png)

**Comment by zkjDream** [comment]
> npx nuxi init content-app -t content
I tried but it didn't work

**Comment by zkjDream** [comment]
After many attempts, he finally succeeded in creating

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/171320689-702a0602-09c1-49f1-9736-70fd85faf0c2.png)

some

**Comment by m-sam-mohamadi** [comment]
> npx nuxi init content-app -t content

how?

**Comment by m-sam-mohamadi** [comment]
> 

how?

**Comment by m-sam-mohamadi** [comment]
> After many attempts, he finally succeeded in creating

how?
