### ISSUE TITLE
Missing docs for `<NuxtPage>` and `<NuxtLayout>`

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1882]

**Comment by danielroe** [comment]
Current docs:
* https://v3.nuxtjs.org/docs/directory-structure/app#usage-with-pages
* https://v3.nuxtjs.org/docs/directory-structure/layouts#example-using-with-slots

**Comment by pi0** [comment]
Indeed but it would be nice if we have dedicated `## <NuxtPage>` and `## <NuxtLayout>` sections in each too. Reason of creating this issue was examples was hard to find.

**Comment by reqwire** [comment]
I second this. I would like to embed an entire page as a component but you can't access the pages directory to include them as components natively

**Comment by ennioVisco** [comment]
These and other Nuxt components now have very nice doc here: https://v3.nuxtjs.org/api/components/
