### ISSUE TITLE
Cannot add any custom directive (locally or globally)

### ISSUE THREAD

**Issue by kay017** [nuxt/framework#1885]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27277498.850ef69`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

It's impossible to add any custom directive (locally or globally).

 I get this: 
`[SSR] Error transforming /Users/Me/Desktop/nuxt3-app/pages/index.vue: SyntaxError: Custom directive is missing corresponding SSR transform and will be ignored.`

### Reproduction

https://codesandbox.io/s/elastic-frog-4c8fr?file=/pages/index.vue

**Comment by wobsoriano** [comment]
https://github.com/nuxt/framework/issues/1659#issuecomment-962033910

**Comment by kay017** [comment]
@wobsoriano Ok I guess my level is not good enough to understand all of this. In nuxt 2 it's very simple to add new directives. I hope it's going to be the same with nuxt 3 eventually...

**Comment by andysay** [comment]
in 3.0.0-27303093.00e6043 works fine!

**Comment by kay017** [comment]
I tried with your version. Still not working for me and neither on [codesandbox.io](codesandbox.io)...

**Comment by andysay** [comment]
> I tried with your version. Still not working for me and neither on [codesandbox.io](codesandbox.io)...

in nuxt config try add this 
```

import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  vue: {
    compilerOptions: {
      directiveTransforms: {
        focus: () => ({
          props: [],
          needRuntime: true
        })
      }
    }
  }
})

```

**Comment by hermesalvesbr** [comment]
> > I tried with your version. Still not working for me and neither on [codesandbox.io](codesandbox.io)...
> 
> in nuxt config try add this
> 
> ```
> 
> import { defineNuxtConfig } from 'nuxt3'
> 
> export default defineNuxtConfig({
>   vue: {
>     compilerOptions: {
>       directiveTransforms: {
>         focus: () => ({
>           props: [],
>           needRuntime: true
>         })
>       }
>     }
>   }
> })
> ```

Didn't work wit Nuxt CLI v3.0.0-27313139.1c88580

**Comment by speedyvic** [comment]
```
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  vue: {
    compilerOptions: {
      directiveTransforms: {
        focus: () => ({
          props: [],
          needRuntime: true
        })
      }
    }
  }
})
```
Tried with the latest nuxt3@3.0.0-27313139.1c88580, and as stated by Hermes, Directives do not work, but also Vuelidate 2.0.0 stopped working. Hope this helps somehow

**Comment by speedyvic** [comment]
Hi.

Adding the patch from this post [patch-vue-directive-ssr](https://github.com/vueuse/patch-vue-directive-ssr) solved the issue with styleclass/ripple primevue directives. Helmer, please try, hope it works for you as well.  Do not forget to remove the vue compilerOptions from nuxt.config. 

Boomer!  Started experiencing Vue Hydration Node Mismatchs. Perhaps the patch uncover something I'm doing wrong.

**Comment by hermesalvesbr** [comment]
Thank you for your great attention. Work's fine!
