### ISSUE TITLE
emit cjs wrapper for lambda + netlify nitro presets

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#1895]
> I think it just might be possible to emit the right kind of entrypoint (while keeping the rest of the lambda ESM). There are some examples out there of people who've done the same with AWS Lambda, e.g. here.

Separately, @danielroe: I've confirmed that this should work for us too, and would mean it woudln't be re-bundled.

_Originally posted by @ascorbic in https://github.com/nuxt/framework/issues/1826#issuecomment-967077006_

**Comment by danielroe** [comment]
It seems it [should now (since 6 Jan) be possible to support native esm](https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/) in the latest AWS Node runtime.

It seems that it should be sufficient to name the entrypoint (as we do) with a .mjs extension.

@ascorbic - can you confirm whether this is possible with Netlify functions?

Related: https://github.com/netlify/zip-it-and-ship-it/issues/750.

**Comment by ascorbic** [comment]
Hi @danielroe 
No, not yet, but we're working on it right now so I would expect it'll be supported at some point this week.

**Comment by pi0** [comment]
I suppose this is something we can improve later on on nitropack.
