### ISSUE TITLE
State not work with methods/functions

### ISSUE THREAD

**Issue by ririen** [nuxt/framework#1900]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27277498.850ef69`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `buildModules`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.0.12`
------------------------------

### Reproduction

https://codesandbox.io/s/amazing-heisenberg-1wm56?file=/app.vue

### Describe the bug

Attempting to `useState` in functions inside `<script setup>` ends with error: `Unhandled Promise Rejection: Error: nuxt instance unavailable`

**Comment by webfansplz** [comment]
This is by design.`useState` only works during `setup` or `Lifecycle Hooks`

The same as `useFetch` , you can see detail : https://github.com/nuxt/framework/issues/1852#issuecomment-966161569

**Comment by milesingrams** [comment]
How might I access useNuxtApp in beforeRouteEnter? This is a lifecycle hook but still getting 'nuxt instance unavailable'
