### ISSUE TITLE
Hydration Error at use teleport

### ISSUE THREAD

**Issue by hoiheart** [nuxt/framework#1907]
### Environment

* node: LTS
* nuxt: latest

### Reproduction

https://codesandbox.io/s/nuxt3-teleport-bug-6b2vr

### Describe the bug

Hello 😀

Hydration error occurs when using teleport in nuxt3.
I inserted a teleport target in app.vue and it works normally until code movement.
However, since hydration mismatch occurs, the function of the code to be teleported cannot operate normally.

### Logs

```shell
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 
  at <Example> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
undefined
> key="/" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <NuxtLayout key=0 name=undefined > 
  at <RouterView> 
  at <NuxtPage> 
  at <App> 
  at <Root> 

Hydration completed but contains mismatches.
```

**Comment by cdwmhcc** [comment]
same

**Comment by danielroe** [comment]
This may be an issue with how teleport is implemented in vue. We either need to recommend that users use teleport only  for elements _outside_ of their nuxt app, or possibly consider whether there's an enhancement we can adopt to improve Vue SSR/hydration + teleport usage.

**Comment by hoiheart** [comment]
@danielroe 
Add a few more information.
- App.html doesn't seem to work on nuxt3, so I couldn't try to insert a teleport target outside the app.
- Hydration error does not occur if a code exists inside the component using the [disabled property](https://v3.vuejs.org/api/built-in-components.html#teleport) of the teleport.

**Comment by ms-fadaei** [comment]
@danielroe 
Is this not related to the [Handling Teleports](https://github.com/vuejs/vue-next/tree/master/packages/server-renderer#handling-teleports) section of the Vue 3 `server-renderer`?

**Comment by cdwmhcc** [comment]
Has this problem been resolved?

**Comment by Tahul** [comment]
Hey :)

We also have this problem working on Docus.

Here is another reproduction concerning the hydration issue:
https://codesandbox.io/s/epic-pond-p04ek?file=/app.vue

If anything else is needed, please let me know! 🙏

**Comment by nixstrom** [comment]
I have also created a reproduction repository.

https://github.com/nixstrom/nuxt3-teleport-issue.git

I also created the same scenario in a "vanilla" Vue/Vue-router setup. This was working as expected; the issue only occurs for me when I add Nuxt3 to the mix.

**Comment by Mini-ghost** [comment]
That is work below, avoid use <Teleport> with SSR,  but that are not a best practice.

```html
<ClientOnly>
  <Teleport to="body">
    <div>
      <!-- content-->
    </div>
  </Teleport>
</ClientOnly>
```

**Comment by sangyoo91** [comment]
what i found was that when i got teleport to work inside vue, on initial mount it will work. But when navigating away then back, teleport will break

**Comment by MuhammadKhizar7** [comment]
It still shows same error when using teleport when using content module. I am using component in Markdown which uses teleport     to take content outside of prose class div but ClientOnly fixes client side render not SSR
