### ISSUE TITLE
Meta Components reports Cannot read properties of null (reading'$nuxt') error

### ISSUE THREAD

**Issue by cdwmhcc** [nuxt/framework#1909]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0-27277498.850ef69`
- Package Manager:  `yarn@1.22.4`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

`App.vue` or any components

``` vue
<Head>
<Title>Test</Title>
<Meta name="description" content="My page's description" />
</Head>
```

### Describe the bug

Meta Components reports `Cannot read properties of null (reading'$nuxt')` error

![image](https://user-images.githubusercontent.com/8030134/141671117-5a0bb80f-09bc-456b-8684-3597dcfc9e23.png)

**Comment by AeonFr** [comment]
This error might have started appearing after https://github.com/nuxt/framework/pull/1835 was merged. Does it make sense? Reverting to a version of nuxt before that commit seems to fix it in our repo.

**Comment by cdwmhcc** [comment]
> 3.0.0-27274229.29599f0

It work.

**Comment by danielroe** [comment]
Would you check whether this is still the case on the latest version, and if so provide a reproduction?

**Comment by AeonFr** [comment]
I created a small repo to reproduce the issue. After running `npm run dev` and loading the index page, the error appears:

https://github.com/AeonFr/nuxt3-usemeta-example

**Comment by jwahdatehagh** [comment]
This error disappears for me when wrapping the `<Head>` component in an `<Hmtl>` component...

**Comment by megasanjay** [comment]
> This error disappears for me when wrapping the `<Head>` component in an `<Hmtl>` component...

Tried this but I keep getting the same error. In my repo, I added a Head tag to my layouts to get a dynamic canonical URL. Not sure if there is a different way of creating this.
