### ISSUE TITLE
Importing and using nuxt3 functions directly does not work

### ISSUE THREAD

**Issue by djohalo2** [nuxt/framework#1910]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27277498.850ef69`
- Package Manager:  `npm@6.14.15`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/hungry-elion-u5p8w?file=/pages/index.vue

### Describe the bug

In a typescript nuxt3 project I'm trying to use the `useFetch` composable. As found in the documentation this composable is globally available without imports. This is not something Typescript likes however, therefore I tried importing it from `nuxt3` like: `import { useFetch } from 'nuxt3'`.

In that case my types work and I get autocomplete, but nuxt crashes and shows a `vue-router` error? I've provided a reproduction codesandbox, where it seems anything imported through `nuxt3` package breaks the server (like `defineComponent` for example).

It might be that this is not the intended usage, in which case I hope someone might be able to help with another way to make this work with Typescript.

Thanks!

### Logs

```shell
[Vue Router warn]: uncaught error during route navigation:
TypeError: Cannot read property '__vccOpts' of undefined
at ~/node_modules/vue-router/dist/vue-router.cjs.js:2022:55
at processTicksAndRejections (internal/process/task_queues.js:95:5)
Cannot read property '__vccOpts' of undefined
at ./node_modules/vue-router/dist/vue-router.cjs.js:2022:55
at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:72021) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__vccOpts' of undefined
at ~/node_modules/vue-router/dist/vue-router.cjs.js:2022:55
at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:72021) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)
[Vue Router warn]: uncaught error during route navigation:
TypeError: Cannot read property '__vccOpts' of undefined
at ~/node_modules/vue-router/dist/vue-router.cjs.js:2022:55
at processTicksAndRejections (internal/process/task_queues.js:95:5)
Cannot read property '__vccOpts' of undefined
at ./node_modules/vue-router/dist/vue-router.cjs.js:2022:55
at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:72021) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__vccOpts' of undefined
at ~/node_modules/vue-router/dist/vue-router.cjs.js:2022:55
at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:72021) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 24)
```

**Comment by frabrg** [comment]
Hi,

I also encountered this kind of error while trying to run a function imported from a composable file.

```
500
Cannot read property '__vccOpts' of undefined
at ./node_modules/vue-router/dist/vue-router.cjs.js:2022:55
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by danielroe** [comment]
You should import `useFetch` from `#app`. To get TS to recognise these global imports, you can include the following in your `tsconfig.json`:
```json5
{
  // https://v3.nuxtjs.org/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}

```

**Comment by djohalo2** [comment]
@danielroe Importing from `#app` seems to work, thanks for that! I already have the mentioned tsconfig extend, but it might actually be a Jetbrains IDE issue (using Rider), as I'm seeing much better IDE support in VSCode and Volar plugin.

**Comment by danielroe** [comment]
I would personally recommend using global imports, but we do need to ensure this is in the documentation. Also relevant is #1471.
