### ISSUE TITLE
'build' w/ node.js preset doesn't generate a running application in Node v16 LTS

### ISSUE THREAD

**Issue by Zizaco** [nuxt/framework#1913]
### Environment

```
npx nuxi info
Nuxt CLI v3.0.0-27277498.850ef69
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27277498.850ef69`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

**Stackblitz link:**
https://stackblitz.com/edit/github-fchd76?devtoolsheight=33&file=THEBUG.md

_⚠️ But the error is not visible in Stackblitz, because it doesn't run the LTS version of node. Stackblitz is stuck in node v14_

## Steps to reproduce bug:

Use node.js **16.13.0 LTS**
The bug happens only when the "build" command runs on node 16.13.0 LTS

Build project normally (with node.js preset):
_(This doesn't generate any errors)_

```bash
npm run build
```

Run application that was built

```bash
npm run start
# node .output/server/index.mjs # also works
```

Simply open the application on the browser.

Check console:

```
error: Uncaught TypeError: false.accept is not a function at entry-51da4355.mjs:1
(anonymous) @ entry-51da4355.mjs:1
```

I've reproduced it with nodejs **v16.13.0 LTS**. It doesn't happen with nodejs **v14.18.1** :fire:

### Describe the bug

Whenever the `build` command is run with node **v16.13.0 LTS**, the shipped `.output` doesn't run properly.

When running `node .output/server/index.mjs`, the browser application crashes on a javascript error that blocks any hydration to take place:

```
error: Uncaught TypeError: false.accept is not a function
  at entry-51da4355.mjs:1
(anonymous) @ entry-51da4355.mjs:1
```

### Additional context

![Bug screenshot](https://i.imgur.com/7yrIlIF.png)

### Logs

```shell
error: Uncaught TypeError: false.accept is not a function
  at entry-51da4355.mjs:1
(anonymous) @ entry-51da4355.mjs:1
```

**Comment by danielroe** [comment]
I can't reproduce this locally with the same code/lockfile on Node 16.13.0. Could you provide a repository with code that reproduces this issue for you? 🙏

**Comment by lyoko515** [comment]
I also encountered a similar situation. I created a brand new project and had the same problem. I was using v16.13.1. 

entry-75e43b79.mjs:1 Uncaught TypeError: false.accept is not a function at entry-75e43b79.mjs:1
<img width="1244" alt="Screen Shot 2021-12-23 at 10 39 23" src="https://user-images.githubusercontent.com/11769334/147184566-9a0a64b8-9c0b-4a1a-a9f1-f85c4d2ba486.png">

<img width="765" alt="Screen Shot 2021-12-23 at 10 29 30" src="https://user-images.githubusercontent.com/11769334/147184249-b2459e92-8568-4acf-9dd8-c4780a65c174.png">
code if you need
[frontend.zip](https://github.com/nuxt/framework/files/7766579/frontend.zip)

Thanks for the support

**Comment by andreas83** [comment]
Looks like i have a similar error.

bootstrap-8042a496.mjs:8 Uncaught TypeError: false.accept is not a function
    at bootstrap-8042a496.mjs:8
(anonymous) @ bootstrap-8042a496.mjs:8

node v16.13.1

**Comment by jarraga** [comment]
Same as @andreas83, I had NODE_ENV=development in my .env
Modifying or deleting that line worked!

**Comment by svedova** [comment]
@danielroe the same seems to happen when building on Stormkit as well. 

## Steps to reproduce

1. Checkout https://github.com/svedova/stormkit-node-env-problem
2. Set `NODE_ENV=development` in the environment variables settings
3. Deploy the app
4. Check the link. It generates the same error written above.

## Examples

1. This was built using node.js 16: https://nuxt-env-development-problem--62130764006674.stormkit.dev/ (has the error)
2. This was built using node.js 14: https://nuxt-env-development-problem--62129119204323.stormkit.dev/ (no error)

**Comment by alecgerona** [comment]
Sorry, can this be reopened? This is still happening on `3.0.0-rc.4` and there's a repository submitted to reproduce the problem. The fix above also works but a permanent fix would be appreciated. This might be affecting some other environment variable down the road.

**Comment by danielroe** [comment]
A permanent fix has been introduced: https://github.com/nuxt/framework/pull/5417.

Regardless, you should not override NODE_ENV.
