### ISSUE TITLE
Volar support for bridge

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#1920]
When generating `tsconfig.json` for Nuxt bridge, we shall set `experimentalCompatMode` that helps work Volar with Vue 2/Bridge out of the box. 

To test: Not sure if volar also resolves `tsconfig.json` with `extend` for `experimentalCompatMode` support or not. /cc @johnsoncodehk

Bonus: Would be nice DX if we can somehow also eliminate requirement of `@vue/runtime-dom` being installed

Refs: (I could find)
- https://github.com/johnsoncodehk/volar/commit/647391f6d72ba7c6d2154c541d5151a0e11b5364
- https://github.com/nuxt/modules/commit/cd127cd879d08be934e0e88e9ec5d634be5d3c6e

**Comment by danielroe** [comment]
Oops, just found this - see https://github.com/nuxt/framework/pull/1924 which may possibly close this.

From what I can tell, `@vue/runtime-dom` is not always required, but it is necessary to have the `experimentalCompatMode` set in the _top-level_ tsconfig, and it doesn't work if set in the generated one.

**Comment by antfu** [comment]
I guess we could still have it in the generated one and open a ticket for Volar to see if it can pick them up in the future?

**Comment by johnsoncodehk** [comment]
I just missed the extends `vueCompilerOptions` use case, will be nice to open a FR for tracking. :)

But please note that the `experimentalCompatMode` option may be deprecated in v0.30. If so, I will open a topic to explain the migration.
