### ISSUE TITLE
Nuxi prepare with target static fails

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/framework#1946]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v17.0.1`
- Nuxt Version:     `2.16.0-27273615.ab1c6cb4`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Webpack`
- User Config:      `target`, `bridge`, `vite`, `alias`, `nitro`, `ssr`, `head`, `css`, `plugins`, `components`, `tailwindcss`, `buildModules`, `modules`, `serverMiddleware`, `watch`, `privateRuntimeConfig`, `build`, `storybook`   
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@4.2.1`, `portal-vue/nuxt`, `@nuxt/postcss8@1.1.3`, `@pinia/nuxt@0.1.0`, `nuxt-route-meta@2.3.2`, `@nuxt/bridge@3.0.0-27283410.c53b6a5`

### Reproduction

https://github.com/JabRef/JabRefOnline/pull/480

### Describe the bug

Run `nuxi prepare` with `target: static` yields
```
FATAL  [nitro] Please use nuxt generate for static target                                                                                                                                                                   21:20:28  

  at setupNitroBridge (/D:/Programming/JabRefOnline/node_modules/@nuxt/bridge/dist/chunks/module.mjs:132:11)
  at setup (/D:/Programming/JabRefOnline/node_modules/@nuxt/bridge/dist/chunks/module.mjs:975:13)
  at ModuleContainer.wrappedModule (/D:/Programming/JabRefOnline/node_modules/@nuxt/kit/dist/index.mjs:1212:22)
  at node_modules\@nuxt\bridge\module.cjs:3:58
  at async ModuleContainer.addModule (node_modules\@nuxt\core-edge\dist\core.js:174:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core-edge\dist\core.js:45:7)
  at async Nuxt._init (node_modules\@nuxt\core-edge\dist\core.js:346:5)
```

### Additional context

The error is thrown here
https://github.com/nuxt/framework/blob/850ef69a878294bb2854fdfe07d1d8bc71d0d52d/packages/bridge/src/nitro.ts#L14-L16
I had a look but couldn't find a clear way to specify the information "this is a prepare run" from https://github.com/nuxt/framework/blob/36f3691bf8d3d60b3c5e01ee5df3ed90c6c4780d/packages/nuxi/src/commands/prepare.ts#L18 to the bridge init code.

**Comment by pi0** [comment]
This is a bug for sure to be resolved but in the meantime why would you need manual `nuxi prepare`? both dev and build/generate commands should generate it normally

**Comment by tobiasdiez** [comment]
Without `nuxi prepare` eslint and typecheck fail on CI (and it's overkill to run dev or build only to generate the nuxt type config).

I would even suggest to add that `nuxi prepare` should be added to the postinstall script section of the package.json upon migrating to bridge. Otherwise it's quite irritating that there is no proper typescript support until one builds the server once.

**Comment by tobiasdiez** [comment]
Thanks, it is working now!
