### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by pixelpaulaus** [nuxt/framework#1950]
### Environment

latest versions

### Reproduction

` <img :src="require('~/assets/image.png')">`  anywhere in vue component.

### Describe the bug

require is not defined when using it such as....

` <img :src="require('~/assets/image.png')">`

### Logs

```shell
at $id_9513b4f8 (file://./.nuxt/dist/server/server.mjs:10135:22)
at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:10596:9)
at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:10543:25)
at ssrImport (file://./.nuxt/dist/server/server.mjs:10568:13)
at $id_45a9f067 (file://./.nuxt/dist/server/server.mjs:9928:37)
at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:10596:9)
at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:10543:25)
at ssrImport (file://./.nuxt/dist/server/server.mjs:10568:13)
at $id_7689e89d (file://./.nuxt/dist/server/server.mjs:1935:37)
at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:10596:3)
```

**Comment by danielroe** [comment]
If you are using vite then `require` will not work; it's webpack-only. Instead, just use:

```vue
<template>
  <div class="app">
    <img src="~/assets/image.png">
  </div>
</template>
```

**Comment by pixelpaulaus** [comment]
thats the weird thing, i am not using vite O_o
and i am wanting to use  require from a variable value.

**Comment by danielroe** [comment]
@pixelpaulaus You can set `vite: false` in your `nuxt.config`.

**Comment by kayoderock** [comment]
Yeah @pixelpaulaus, I had this same issue, how can I make a dynamic src using Vite?

**Comment by kayoderock** [comment]
Yeah found it https://vitejs.dev/guide/assets.html#new-url-url-import-meta-url - Vite docs

```
imgUrl () {
    return new URL(`../assets/${this.icon}.svg`, import.meta.url).href
  }
```

**Comment by tsulatsitamim** [comment]
> Yeah found it https://vitejs.dev/guide/assets.html#new-url-url-import-meta-url - Vite docs
> 
> ```
> imgUrl () {
>     return new URL(`../assets/${this.icon}.svg`, import.meta.url).href
>   }
> ```

not work in ssr

**Comment by spot-mathis** [comment]
any solutions for this?

**Comment by juancarlos-ctg** [comment]
if you're using nuxt 3 just put the img src  as `"assets/<whatever path to your img>"`. 

By default nuxt 3 will not use the `@` for specifying the path in the Vue.js

So dynamically loading images using urls like so: 
```vue
<img :src="element.src">
```
Where your `element.src` is `assets/path/to/img.png` will work! 😭

**Comment by paidge** [comment]
Thanks @juancarlos-ctg. This solution works with Nuxt3. But how to import the image dynamically ?
My component has a String prop with the asset name and I would like to import the image depending on this prop.

**Comment by zhouzilong2020** [comment]
> Thanks @juancarlos-ctg. This solution works with Nuxt3. But how to import the image dynamically ?
> My component has a String prop with the asset name and I would like to import the image depending on this prop.

Maybe use a helper function which takes the name as imput and output the right module(image)? 
I organize all the icon's import logic in [./composables](https://v3.nuxtjs.org/guide/directory-structure/composables), and this works for me.

**Comment by paidge** [comment]
I finally put my images in the `public `folder. With this method, images are not compressed but I compressed them before with another tool.

**Comment by power-cut** [comment]
Any straightforward solution for this ?

**Comment by kiketordera** [comment]
Yeah, I want to do something like this, but I can't:
```
 <img :src="require('@assets/'+img)" alt="">
```

**Comment by EmmyMay** [comment]
> Yeah, I want to do something like this, but I can't:
> 
> ```
>  <img :src="require('@assets/'+img)" alt="">
> ```

Require does not work with vite 3

**Comment by steel89ita** [comment]
We now know that require does not work with vite, 
but which could be the solution to import the image dynamically with ssr?

For example, I was importing the image using "require" and combining it with a string prop, 
but can't see a way of doing something similar with vite ssr, as import.meta.url is not working.

**Comment by mjzarrin** [comment]
An example of changing images dynamically while using Vite:

``<img :src="`/assets/${dynamic_image_name}.jpeg`"/>``

**Comment by EmmyMay** [comment]
> An example of changing images dynamically while using Vite:
> 
> `` <img :src="`/assets/${dynamic_image_name}.jpeg`"/> ``

This works on SSR?

**Comment by papadi166** [comment]
Maybe use `'type': 'commonjs'` in package.json and add this in your nuxt.config.ts file:

I have configuration like this, but nothing worked after building because of this type: common.js. I tried before many things, was googling for some hours reading documentations of rollup, nuxt, plugins, vite, commonjs etc. 
```
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill'
import { NodeModulesPolyfillPlugin } from '@esbuild-plugins/node-modules-polyfill'
import rollupNodePolyFill from 'rollup-plugin-node-polyfills'
```

`ite: {

    plugins: [

    ],
    resolve: {
      alias: {
          // This Rollup aliases are extracted from @esbuild-plugins/node-modules-polyfill, 
          // see https://github.com/remorses/esbuild-plugins/blob/master/node-modules-polyfill/src/polyfills.ts
          // process and buffer are excluded because already managed
          // by node-globals-polyfill
          util: 'rollup-plugin-node-polyfills/polyfills/util',
          sys: 'util',
          events: 'rollup-plugin-node-polyfills/polyfills/events',
          stream: 'rollup-plugin-node-polyfills/polyfills/stream',
          path: 'rollup-plugin-node-polyfills/polyfills/path',
          querystring: 'rollup-plugin-node-polyfills/polyfills/qs',
          punycode: 'rollup-plugin-node-polyfills/polyfills/punycode',
          url: 'rollup-plugin-node-polyfills/polyfills/url',
          string_decoder: 'rollup-plugin-node-polyfills/polyfills/string-decoder',
          http: 'rollup-plugin-node-polyfills/polyfills/http',
          https: 'rollup-plugin-node-polyfills/polyfills/http',
          os: 'rollup-plugin-node-polyfills/polyfills/os',
          assert: 'rollup-plugin-node-polyfills/polyfills/assert',
          constants: 'rollup-plugin-node-polyfills/polyfills/constants',
          _stream_duplex:
              'rollup-plugin-node-polyfills/polyfills/readable-stream/duplex',
          _stream_passthrough:
              'rollup-plugin-node-polyfills/polyfills/readable-stream/passthrough',
          _stream_readable:
              'rollup-plugin-node-polyfills/polyfills/readable-stream/readable',
          _stream_writable:
              'rollup-plugin-node-polyfills/polyfills/readable-stream/writable',
          _stream_transform:
              'rollup-plugin-node-polyfills/polyfills/readable-stream/transform',
          timers: 'rollup-plugin-node-polyfills/polyfills/timers',
          console: 'rollup-plugin-node-polyfills/polyfills/console',
          vm: 'rollup-plugin-node-polyfills/polyfills/vm',
          zlib: 'rollup-plugin-node-polyfills/polyfills/zlib',
          tty: 'rollup-plugin-node-polyfills/polyfills/tty',
          domain: 'rollup-plugin-node-polyfills/polyfills/domain'
      },
    },
    optimizeDeps: {
      esbuildOptions: {
          // Node.js global to browser globalThis
          define: {
              global: 'globalThis'
          },
          // Enable esbuild polyfill plugins
          plugins: [
              NodeGlobalsPolyfillPlugin({
                  process: true,
                  buffer: true
              }),
              NodeModulesPolyfillPlugin()
          ]
      }
  },

    build: {
      rollupOptions: {
        plugins: [
            // Enable rollup polyfills plugin
            // used during production bundling
            rollupNodePolyFill()
        ]
    }
  },`

**Comment by terwer** [comment]
Still not work

**Comment by den-kar** [comment]
I kind of found a work-around by replacing `<img>` with a `<div>` and setting the background-image with a Tailwind class.
Changed from:
```js
const logoFilename = 'logo-1.svg';
<img :src="`~/assets/img/logos/${logoFilename}`" ... />
```
to:
```js
const logoTailwindBgImage = 'bg-[url(~/assets/img/logos/logo-1.svg)]'
<div class="w-full ..." :class="logoTailwindBgImage" ...></div>
```
This works in production too, but only when passing the whole Tailwind class as a single string.

Concatenating the class name only works with `yarn dev`:
```js
const concatenatedTailwindClass = `bg-[url(~/assets/img/logos/${logoFilename})]`
<div class="w-full ..." :class="concatenatedTailwindClass" ...></div>
```
`yarn build` exits with an error:
> ERROR  [vite:css] ENOENT: no such file or directory, open 'path/to/project/root/assets/img/logos/${logoFilename}'
> file: /path/to/project/root/assets/css/tailwind.css
> 
> ERROR  ENOENT: no such file or directory, open '/path/to/project/root/assets/img/logos/${logoFilename}'                                                                                                     
> 
> error Command failed with exit code 1.

It's no one-to-one replacement, but at least the images are rendered in production and are available at e.g. `http://www.example.io/_nuxt/logo-1.ccb82e2f.svg`.

Might be helpful to someone

**Comment by slavco86** [comment]
Trying  to integrate Azure application insights with our Nuxt 3 app to monitor requests which Nuxt is making server side.
According to app insights docs - I have to use `require` in order to initialise the package, which I am trying to do via server side plugin, but like it was mentioned above - also getting an error saying `required is not defined`
https://www.npmjs.com/package/applicationinsights

Is there a work around?

**Comment by danielroe** [comment]
Can you not `import` instead of `require`? (I would request that you move this to a discussion rather than a long-closed and unrelated issue.)

**Comment by slavco86** [comment]
https://github.com/nuxt/framework/discussions/7391

**Comment by slavco86** [comment]
> Can you not `import` instead of `require`? (I would request that you move this to a discussion rather than a long-closed and unrelated issue.)

No, the package doesn't support `import` - I'm getting `undefined` with `import`

**Comment by manniL** [comment]
Even with `import * as MY_VAR from 'package'`?

**Comment by slavco86** [comment]
Bingo! 
Thanks!!!

**Comment by schnetzi** [comment]
@slavco86 @manniL your discussion and solution is not related to this problem. The problem is/was to import/require a dynamic image path and not a package.

To the problem with loading dynamic images:
I found a solution in stack-overflow: https://stackoverflow.com/a/71514878/7866722

My solution turned out like that
```ts
const imageUrl = new URL(`../../assets/images/${props.src}`, import.meta.url).href;
```

<details>
  <summary>Full code for an Article Image with Nuxt Content</summary>
  
  ```vue
  <!-- components/content/ArticleImage.vue -->
  <template>
    <img :src="imgSrc()" :alt="alt" class="article-image" />
  </template>

  <script setup lang="ts">
  const props = defineProps<{
    src: string;
    alt: string;
  }>();

  function imgSrc() {
    try {
      const imageUrl = new URL(`../../assets/images/${props.src}`, import.meta.url).href;

      return imageUrl;    
    } catch (error) {
      console.error(error);
    }
  }
  </script>
  ```
</details>

**Comment by danielroe** [comment]
Check out https://vitejs.dev/guide/features.html#glob-import and follow https://github.com/nuxt/framework/issues/7121.

**Comment by mpincipientinfo** [comment]
After running "npm run start" I am getting same error. https://prnt.sc/88YDQo6HRvCj
I used image with same syntax still getting same error. Even I removed images everywhere to test. No avail.
Is there anyone  who can help me to fix it?
