### ISSUE TITLE
support for extending build within `nuxt.config`

### ISSUE THREAD

**Issue by liqueflies** [nuxt/framework#1954]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.0`
- Nuxt Version:     `3.0.0-27277498.850ef69`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `target`, `css`, `publicRuntimeConfig`, `buildModules`, `modules`, `intlify`, `robots`, `build`
- Runtime Modules:  `@nuxtjs/robots@2.5.0`
- Build Modules:    `nuxt-windicss@2.0.12`, `@intlify/nuxt3@0.1.8`
------------------------------

### Reproduction

https://codesandbox.io/s/gallant-danny-xuwkr?file=/nuxt.config.ts

### Describe the bug

I am trying to add a loader to my nuxt application.
in Nuxt 2 I usually use the build.extend function to extend rules and add my rule, but in Nuxt 3 I am not able to do that.
If you look at reproduction, there is a type error for `extend` key on error.

How to do that?
In documentation is missing.

Thank you for help!

**Comment by fmcdigital** [comment]
I also need to use `extend()`

**Comment by danielroe** [comment]
For now, for vite, you can use `vite:extend` or `vite:extendConfig`. For webpack, you can use `webpack:config`.

```js
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  hooks: {
    'vite:extend' ({ nuxt, config }) {},
    'vite:extendConfig' (clientConfig, { isClient, isServer }) {},
    'webpack:config' (configs) {}
  }
})
```

**Comment by liqueflies** [comment]
Hi daniel, before this answer I came up with:

```
  vite: {
    plugins: [myVitePlugin()],
  },
```

Is this still a valid solution or I have to extend?

Also I suggest to add into nuxt.config.js docs to be clearer as possible.

Thank you! <3

**Comment by danielroe** [comment]
I think we've decided that the best approach is to use direct configuration of `vite` or `webpack` keys, hooks, or a custom module with `extendWebpackConfig`, `extendViteConfig`, `addWebpackPlugin` or `addVitePlugin` (utilities exported from `@nuxt/kit`).

cc: @pi0

**Comment by aacassandra** [comment]
Hi @danielroe 
how using web worker in nuxt 3?

in nuxt 2 im using like this
```
  build: {
    extend(config: any, ctx: any) {
      if (ctx.isClient) {
        config.module.rules.push({
          test: /\.worker\.ts$/,
          loader: 'worker-loader',
          exclude: /(node_modules)/,
        })
      }
    },
  },

https://thewebdev.info/2021/10/09/how-to-run-background-tasks-in-a-nuxt-app-with-web-workers/
```

**Comment by aacassandra** [comment]
> Hi @danielroe how using web worker in nuxt 3?
> 
> in nuxt 2 im using like this
> 
> ```
>   build: {
>     extend(config: any, ctx: any) {
>       if (ctx.isClient) {
>         config.module.rules.push({
>           test: /\.worker\.ts$/,
>           loader: 'worker-loader',
>           exclude: /(node_modules)/,
>         })
>       }
>     },
>   },
> 
> https://thewebdev.info/2021/10/09/how-to-run-background-tasks-in-a-nuxt-app-with-web-workers/
> ```

ignore this. cause in the webpack v5, we can use Web Workers without worker-loader
https://webpack.js.org/guides/web-workers/

Awesome
