### ISSUE TITLE
computed value not updating?

### ISSUE THREAD

**Issue by pixelspark** [nuxt/framework#1955]
### Environment

Nuxt CLI v3.0.0-27283410.c53b6a5                                      10:45:15
RootDir: /Users/work/Git/XX                                         10:45:16
Nuxt project info:                                                    10:45:16

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27283410.c53b6a5`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

````ts
<template>
    <div>{{ processed }}</div>
</template>
<script setup lang="ts">
import { computed } from 'vue';
const { data, refresh, pending } = await useAsyncData('/api/data', () => $fetch('/api/data'));

const processed = computed(() => {
	console.log("COMPUTED GW", data, !!pending);
	return (!pending && data) ? data.length : 0;
});
````

### Describe the bug

First of all, great work on Nuxt 3! Love where it is going.

It might be just me using this wrong, but I can't seem to get computed properties to work (esp. not when using async data). 

Abbreviated example above. This leaves 'processed' at 0 and only runs the computed function once, showing 'pending' as 'true'. When I do similar processing from inside the template (i.e. just say `{{data.length}}`) it seems to work fine.

Are computed values supposed to work this way, or is it a bug?

**Comment by danielroe** [comment]
Both `data` and `pending` are refs so are always truthy. Check `pending.value` if you want to know whether it is indeed pending or not.

This works:
```vue
<template>
  <div>{{ processed }}</div>
</template>
<script setup lang="ts">
import { computed } from 'vue'
const { data, refresh, pending } = await useAsyncData('/api/data', () => $fetch('/api/data'))

const processed = computed(() => {
  console.log('COMPUTED GW', data.value, !!pending)
  return (!pending.value && data.value) ? data.value.length : 0
})
</script>
```

**Comment by pixelspark** [comment]
Thanks, I should have known this!
