### ISSUE TITLE
Meta scripts execute multiple times on a single load

### ISSUE THREAD

**Issue by heychazza** [nuxt/framework#1963]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27283410.c53b6a5`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `css`, `meta`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

**nuxt.config.ts**
```ts
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
    meta: {
        script: [
            {
                src: 'https://my-script-url.com',
                'data-site': 'my-test-attribute',
                'defer': true
            }
        ],
    },
})
```

### Describe the bug

When utilising the meta script option from the nuxt config file, it seems to continue to send requests to that script (multiple times). When utilised with say an analytics platform, this skews the numbers and ends up with the browser being rate limited by such.

### Additional context

![image](https://user-images.githubusercontent.com/47271716/141984069-3c012583-4cc8-4653-996e-d135f1346c2f.png)
As you can see here, upon loading the browser has sent something like 5-7 requests, and attempted to continue to send them in turn.

**Comment by danielroe** [comment]
This may be an upstream issue: https://github.com/vueuse/head/issues/44

**Comment by heychazza** [comment]
Hey @danielroe, the bug has been fixed in upstream, do you know when it'll land now within Nuxt?

**Comment by danielroe** [comment]
@heychazza It should already have landed in https://github.com/nuxt/framework/pull/2009. You might need to upgrade it or refresh your lockfile.

**Comment by heychazza** [comment]
Oh damn got put 5 days ago, I'm late haha, thanks a ton Daniel!
