### ISSUE TITLE
`extendRoutes` from modules broken with Bridge

### ISSUE THREAD

**Issue by Tahul** [nuxt/framework#1965]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `2.16.0-27282256.ab1c6cb4`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/modest-currying-8liys?file=/pages/test.vue

### Describe the bug

Using `this.extendRoutes()` from a regular module (`async function () { console.log(this) }`) is broken since latest versions of Bridge.

I couldn't identify which version tag is breaking it exactly, but it seem not to be more than a week old (or two).

### Additional context

I spotted that by debugging an issue coming from `@nuxtjs/i18n`.

The error was that the additional routes generated by this module were not added to the routes list.

Console was spammed with these error messages:
```
[vue-router] Route with name 'test___fr' does not exist
```

Here are the code references:

The place where `this.extendRoutes` is called:
https://github.com/nuxt-community/i18n-module/blob/main/src/index.js#L87

The function that never gets executed:
https://github.com/nuxt-community/i18n-module/blob/555e66e183f5188e61477b7bb6f10ba872bf5714/src/core/hooks.js#L22

The patch used to resolve the issue:
https://github.com/docusgen/app/blob/dev/patches/%40nuxtjs%2Bi18n%2B7.2.0.patch

### Logs

```shell
There is no logs to be provided, as this issue does not seem to throw a specific error, apart from the one being thrown by the modules that relies on that feature.

You can find more context in the reproduction though.
```

**Comment by pi0** [comment]
Thanks for investigating. Seems a regression from #1740. We probably needed to keep ModuleContainer as-is

**Comment by pi0** [comment]
In the linked sandbox, you are using `build:extendRoutes` hook while i18n uses legacy `options.extendRoutes`. It get's called **after hook** ([see here](https://github.com/nuxt/nuxt.js/blob/dev/packages/builder/src/builder.js#L385)) that's why you cannot see changes by i18n module. 

If you really need to keep using Kit, here is a workaround:


```js
        await installModule(nuxt, function () {
          // [Nuxt 2] extendRoutes is called **after** `build:extendRoutes` 
          this.extendRoutes((routes) => console.log(routes));
        });
```


https://codesandbox.io/s/relaxed-brook-5jj2q?file=/nuxt.config.js:305-503

**Comment by kazupon** [comment]
I also just found this issue in nuxt/i18n prototyping, so I was going to send the PR. :)
I was able to temporarily avoid by the below:
https://github.com/kazupon/nuxt-i18n-next/commit/7d778b94c9a5ebbfc91bf711788b9acf39292e96#diff-d9307a9d3d7b36df3148429b68b9693960869b65efebfb286725b3d56b55e7c9R51-R61

Thank you quick fix!
