### ISSUE TITLE
Nuxi generate: exits with success in case of an error

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/framework#1968]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v17.0.1`
- Nuxt Version:     `2.16.0-27273615.ab1c6cb4`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Webpack`
- User Config:      `target`, `bridge`, `vite`, `alias`, `nitro`, `ssr`, `head`, `css`, `plugins`, `components`, `tailwindcss`, `buildModules`, `modules`, `serverMiddleware`, `watch`, `privateRuntimeConfig`, `build`, `storybook`   
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@4.2.1`, `portal-vue/nuxt`, `@nuxt/postcss8@1.1.3`, `@pinia/nuxt@0.1.0`, `nuxt-route-meta@2.3.2`, `@nuxt/bridge@3.0.0-27283410.c53b6a5`

### Reproduction

https://github.com/JabRef/JabRefOnline/pull/480, and in particular the "build" step in https://github.com/JabRef/JabRefOnline/runs/4218058544?check_suite_focus=true 

### Describe the bug

If there is an error during the nitro server build (in my case  #1967), then `nuxi generate` just keeps going and returns the exit code 0 (success). Thus the CI workflow passes although it should fail in the presence of an error.

**Comment by lihbr** [comment]
Related: https://twitter.com/dan_spratling/status/1490813978712449031

**Comment by lihbr** [comment]
[repro-1968.zip](https://github.com/nuxt/framework/files/8022965/repro-1968.zip)

Find attached a minimal reproduction.

1. Download and extract;
2. Install dependencies;
3. Run the `dev` script;
   > You should see a "Hello Nuxt" page
4. Run the `generate` script;
   > You should seen thrown errors in the console but the script succeeding, actually generating HTML for "Internal Server Error"
5. To fix the issue here you need to uncomment line 6 in `nuxt.config.ts` to transpile the dependency
   > Actually this might be another issue, but it's quite off that it works fine in dev but breaks once generating for production, but well, ESM Hell 🔥

**Comment by tobiasdiez** [comment]
Thanks @danielroe, this seems to work fine!
