### ISSUE TITLE
[worker] Cannot find module on start (windows 10)

### ISSUE THREAD

**Issue by giticon** [nuxt/framework#1974]
### Environment

Windows 10

### Reproduction

[https://github.com/giticon/nuxt3-app](https://github.com/giticon/nuxt3-app)

### Describe the bug

![cmd_2021-11-16_17-02-44](https://user-images.githubusercontent.com/27739275/142029570-55cdec0b-106c-497f-80c6-5d4346717ebc.png)

**Comment by kondrieger** [comment]
same problem
Any resolves?

**Comment by danielroe** [comment]
I can't reproduce this with your repro. Would you provide more information, for example by filling in the environment section? Particularly, I would confirm your node version.

**Comment by giticon** [comment]
with node 14 o 16, same error: nuxt does not start and remains stuck in the loading screen

yarn 1.22.10
node 16.13.0
Windows 10

😕

**Comment by mnlj** [comment]
I've already reported it here: https://github.com/nuxt/framework/issues/1226 judging by the error text it's the same issue.

**Comment by TomKingTech** [comment]
I am also following the Nuxt3 installation docs here: [https://nuxtjs.org/docs/get-started/installation](Nuxt3 Get Started Installation)

I receive the same error as stated above when I run the command `npm run dev` : `ERROR  [worker] Cannot find module 'F:\websites\ntgt\.nuxt\server\index.mjs' imported from F:\websites\ntgt\.nuxt\nitro\index.mjs`

Fresh install, new project. Running Windows 10.0.19043 build 19043, npm version is `8.1.3`

**Comment by januszj** [comment]
Issue is with the path..
I have same error here on Windows 11 after creating new app, Node version v14.18.1 when my app was in folder:
c:\Users\XXXX\source\repos\1\nuxt3-abp\
but it works fine in c:\Cloud\nuxt\nuxt3-abp\

**Comment by mnlj** [comment]
@januszj That might be a different problem, possibly with unicode characters in the username folder XXXX, however this "cannot find module" we are getting happens to me even if I try your path exactly:
` ERROR  [worker] Cannot find module 'c:\Cloud\nuxt\nuxt3-abp\.nuxt\server\index.mjs' imported from c:\Cloud\nuxt\nuxt3-abp\.nuxt\nitro\index.mjs`

**Comment by giticon** [comment]
@mnlj I confirm: 

with 

C:\Users\user\Desktop\nuxtre> **it works.** 

but 

C:\xampp\htdocs\nuxt3-app **it doesn't work**

**Comment by januszj** [comment]
@danielroe at least we have some hint it's folder depended, that's why you could not replicate

**Comment by ladislavsulc** [comment]
Same problem here. Using latest stable WIN10, NVM and Node 16.3.0.

**Comment by Kjue** [comment]
It might be worth to mention a comment from @mnlj in the other thread, that using NVM may have some influence. I am using NVM on Win10, and I run into the same issue.

I have not yet tested without NVM.

I did try to copy the solution directory under Desktop folder. That worked for me as well. Just directly copied the entire folder there.

**Comment by niklasfjeldberg** [comment]
I had this problem yesterday with `Nuxt CLI v3.0.0-27383920.81ee59c`, but now with a new update that issue is gone and I have a new one with the following build.
```
Nuxt CLI v3.0.0-27385496.7a1cf62
RootDir: x
Nuxt project info:

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27385496.7a1cf62`
- Package Manager:  `npm@8.3.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

New issue.
 ```
ERROR  Cannot start nuxt:  Cannot find module '#ansi-styles'
Require stack:
- (..)/node_modules/chalk/source/index.js

  Require stack:
  - (..)/node_modules/chalk/source/index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at _resolve (node_modules\jiti\dist\jiti.js:1:192527)
  at jiti (node_modules\jiti\dist\jiti.js:1:194514)
  at (..)/node_modules/chalk/source/index.js:1:296
  at jiti (node_modules\jiti\dist\jiti.js:1:195952)
  at (..)/node_modules/@nuxt/nitro/dist/index.mjs:9:37
  at jiti (node_modules\jiti\dist\jiti.js:1:195952)
  at (..)/node_modules/nuxt3/dist/index.mjs:14:14
  at jiti (node_modules\jiti\dist\jiti.js:1:195952)
```

Could the issues be related?

**Comment by morneluckybeard** [comment]
> I had this problem yesterday with `Nuxt CLI v3.0.0-27383920.81ee59c`, but now with a new update that issue is gone and I have a new one with the following build.
> 
> ```
> Nuxt CLI v3.0.0-27385496.7a1cf62
> RootDir: x
> Nuxt project info:
> 
> ------------------------------
> - Operating System: `Windows_NT`
> - Node Version:     `v16.13.1`
> - Nuxt Version:     `3.0.0-27385496.7a1cf62`
> - Package Manager:  `npm@8.3.0`
> - Bundler:          `Vite`
> - User Config:      `-`
> - Runtime Modules:  `-`
> - Build Modules:    `-`
> ------------------------------
> ```
> 
> New issue.
> 
> ```
> ERROR  Cannot start nuxt:  Cannot find module '#ansi-styles'
> Require stack:
> - (..)/node_modules/chalk/source/index.js
> 
>  Require stack:
>  - (..)/node_modules/chalk/source/index.js
>  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
>  at _resolve (node_modules\jiti\dist\jiti.js:1:192527)
>  at jiti (node_modules\jiti\dist\jiti.js:1:194514)
>  at (..)/node_modules/chalk/source/index.js:1:296
>  at jiti (node_modules\jiti\dist\jiti.js:1:195952)
>  at (..)/node_modules/@nuxt/nitro/dist/index.mjs:9:37
>  at jiti (node_modules\jiti\dist\jiti.js:1:195952)
>  at (..)/node_modules/nuxt3/dist/index.mjs:14:14
>  at jiti (node_modules\jiti\dist\jiti.js:1:195952)
> ```
> 
> Could the issues be related?

Getting the same on a fresh install

**Comment by medairbit** [comment]
Getting the same on a fresh install as well:
https://github.com/nuxt/framework/issues/2919

**Comment by nicholaslopiccolo** [comment]
I got the same issue on windows and I fix like that:
In this file` C:\Users\XXXX\Documents\Progetti\hello-world\node_modules\@nuxt\nitro\node_modules\chalk\source\index.js`
I replace the first two imports with those (simply removing the #):

```
// Before
import ansiStyles from '#ansi-styles';
import supportsColor from '#supports-color';
// After
import ansiStyles from 'ansi-styles';
import supportsColor from 'supports-color';

```
It works fine for me.

**Comment by Bjornnyborg** [comment]
I had this problem on windows 11, node 16.14.0, i felt like it appeared out of nowhere. 
But the problem was that i was running the commands in the folder `c:/work/project` when the folder is actually called `c:/Work/project`. So if your an noob like me, make sure your casing is correct. 😁

**Comment by danielroe** [comment]
I can't reproduce this on latest nuxt + nitro. If you're still encountering it, please open a new one with a reproduction.
