### ISSUE TITLE
npx nuxi init error

### ISSUE THREAD

**Issue by intermundos** [nuxt/framework#1980]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `0.0.0`
- Package Manager:  `unknown`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Reproduction is unavailable. The bug is on bootstrap level.

### Describe the bug

When trying to create a new nuxt project with `npx nuxi init`  following error shown 

Nuxt CLI v3.0.0-27284664.232fdd8                                                                                                                        

 WARN  could not fetch remote https://github.com/nuxt/starter                                                                                                     

 WARN  Make sure you have installed git correctly

### Additional context

git installed - git version 2.26.0

 internet connection works

**Comment by danielroe** [comment]
see https://github.com/nuxt/framework/issues/1878 (with suggestions for solving).

**Comment by intermundos** [comment]
I don't understand why you close the issue. 

#1878 does not have any suggestion for solving the issue. 

I use no VPN, my git installation is OK and apparently internet connection is ok too. 

I tried resetting npm caches, reinstalling the nuxi, different node versions and still get the same error. 

Would be lovely to see you helping instead of closing the issue straight away.

**Comment by danielroe** [comment]
@intermundos Would you share some more details about your debugging so far?
