### ISSUE TITLE
Router Scrollbehavior

### ISSUE THREAD

**Issue by folamy** [nuxt/framework#1989]
### Environment

Linux

### Reproduction

New feature

### Describe the bug

Is there a way to set a custom scroll behavior on the router? I don't think there is any as of now. 
It will be good to have that configuration from a plugin file or nuxt.config.ts

**Comment by nandi95** [comment]
Duplicate of https://github.com/nuxt/framework/issues/1707

**Comment by folamy** [comment]
Thanks @danielroe. Yeah, I got the hack from  #1707.
