### ISSUE TITLE
Vue router hooks

### ISSUE THREAD

**Issue by loremru** [nuxt/framework#1998]
How to use Vue router hooks in nuxt 3?
How to use _onBeforeRouteLeave_ hook in composition api?

**Comment by danielroe** [comment]
Next time, please don't use issues to ask questions. You should be able to see the different options at https://github.com/nuxt/framework/issues/new/choose.

But you can find documentation for `onBeforeRouteLeave` [here](https://next.router.vuejs.org/api/#onbeforerouteleave).
