### ISSUE TITLE
Vite: Default import yields more than default export

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/framework#1999]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27285136.ab1c6cb4`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `plugins`, `bridge`, `target`, `ssr`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27286006.a08b435`

### Reproduction

https://codesandbox.io/s/strange-tree-9fdkz

### Describe the bug

VueTailwind defines
```
    exports.BaseComponent = Component;
    exports.default = plugin;
```
With `bridge.vite = true` the import `import VueTailwind from "vue-tailwind"` (in a plugin) yields the object 
```
{
   BaseCompont: ....
   default: { install: ... }
}
```
instead of the default plugin `{ install: ... }`. With disabled `vite` everything works as expected.

As with webpack everything is fine, I suspect there is a problem with bridge instead of with the library VueTailwind.

**Comment by ayalon** [comment]
The issue is, that nuxt vite automatically adds some default exports but does not consider named default exports. I described the issue here:
https://github.com/nuxt/vite/issues/203

**Comment by pi0** [comment]
[vue-tailwind@2.5.0](https://unpkg.com/browse/vue-tailwind@2.5.0/dist/vue-tailwind.js) is only exporting a cjs file in umd format. You need to report it to [upstream](https://github.com/alfonsobries/vue-tailwind) for [native esm support](https://v3.nuxtjs.org/concepts/esm).

Here is a proper workaround usage for Vue2/Bridge:

```js
import VueTailwind from "vue-tailwind";
import Vue from "vue";
import { TInput } from "vue-tailwind/dist/components";

const VueTailwindPlugin =
  // @ts-ignore
  VueTailwind.default?.default || VueTailwind.default || VueTailwind;

Vue.use(VueTailwindPlugin, {
  "t-input": {
    component: TInput,
    props: {
      classes: "border-2 block w-full rounded text-gray-800"
      // ...More settings
    }
  }
});

export default {};
```

Note that `nuxtApp.vueApp.use` is not right to install Vue2 plugins. It adds overhead to each request.

BTW it seems the upcoming version is being rebranded to `variantjs` (https://github.com/alfonsobries/vue-tailwind/issues/214)

**Comment by tobiasdiez** [comment]
Thanks a lot, this worked nicely. Maybe its worthwhile to add this strategy/workaround to the documentation, as I guess there are quite a few libraries that are not yet supporting esm.

By the way, I took the `nuxtApp.vueApp.use` from https://v3.nuxtjs.org/docs/directory-structure/plugins#vue-plugins. I guess that's the right way with nuxt3 but not with bridge then?

**Comment by pi0** [comment]
Good idea for adding de-default workarounds to [esm troubleshoot](https://v3.nuxtjs.org/concepts/esm#troubleshooting-esm-issues)👍  

> By the way, I took the nuxtApp.vueApp.use from https://v3.nuxtjs.org/docs/directory-structure/plugins#vue-plugins. I guess that's the right way with nuxt3 but not with bridge then?

Indeed. Docs are following vue3/nuxt3 best practices. We probably need to add some notes to the bridge section about installing vue2 plugins or make `vue2App` compat better to avoid calling plugin install each time.

**Comment by tobiasdiez** [comment]
Okay, follow up at https://github.com/nuxt/framework/issues/2037 and #2036.
