### ISSUE TITLE
component typescript problem

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#2002]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27286006.a08b435`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

tree: bug_ts

https://github.com/productdevbook/nuxt3-bug/tree/bug_ts

### Describe the bug

<img width="966" alt="CleanShot 2021-11-17 at 20 54 13@2x" src="https://user-images.githubusercontent.com/38668796/142255562-ca3f6bb9-9162-445c-ab73-ac943e53f2f9.png">

and custom change fix
![142249949-a9861183-0ea6-43f2-af59-4a99055d6d7e](https://user-images.githubusercontent.com/38668796/142255604-45cfd98b-d128-405b-95aa-16dcc1442c7f.png)

**Comment by productdevbook** [comment]
`"include": ["./**/*.ts", "./**/*.vue"]` delete and fixed

**Comment by productdevbook** [comment]
@johnsoncodehk say

I think .nuxt/nuxt.d.ts is missing /// <reference path="components.d.ts" />, please consider report to nuxt 3 repo.

**Comment by danielroe** [comment]
@productdevbook @johnsoncodehk

I can't reproduce any issue with `components.d.ts` not being included when there are components that are detected.

By manually setting `include` value rather than using the one inherited from `.nuxt/tsconfig.json` you are actually excluding the `nuxt.d.ts` declaration file from your project.

**Comment by productdevbook** [comment]
@danielroe "types": ["jest"] example add how to add ?

**Comment by ThomasBerne** [comment]
Sorry for reopening this but, personally, I'm simply missing components.d.ts.
![image](https://user-images.githubusercontent.com/23033483/142836396-30f956fb-e928-49ea-82b1-b0d718f0f0b7.png)
Here is my tsconfig.json:
`{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "types": ["unplugin-vue2-script-setup/types"]
  },
  "vueCompilerOptions": {
    "experimentalCompatMode": 2
  }
}
`
I run yarn dev who does nuxi dev. but the file is still missing and I don't understand why
