### ISSUE TITLE
Auto imported component's style is loaded even if I don't use component

### ISSUE THREAD

**Issue by jd-solanki** [nuxt/framework#2015]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27274229.29599f0`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `alias`, `buildModules`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/core/nuxt@6.8.0`, `unplugin-icons/nuxt`, `~/@core/layouts/nuxt`
```

### Reproduction

https://codesandbox.io/s/determined-sky-77qrl?file=/app.vue:19-43

### Describe the bug

Nuxt 3 docs state "It will automatically import the components only if used".

Does components placed inside component dir is registered globally?

If the component is only get imported then why style is loaded even if the component is not used.

In this codesandbox: https://codesandbox.io/s/determined-sky-77qrl?file=/app.vue:19-43

I don't use the custom button component but still, the style from that component is loaded? 🤔

**Comment by productdevbook** [comment]
some problem

![CleanShot_2021-11-18_at_14 16 33](https://user-images.githubusercontent.com/38668796/142451361-f1fdf427-5ef6-4dc9-9885-3e5614bc781e.png)

**Comment by antfu** [comment]
Is this only happens on dev?

**Comment by productdevbook** [comment]
> Is this only happens on dev?

@antfu no, dev + (build + start) two problem

**Comment by productdevbook** [comment]
some vue component 6 copy add header :D
<img width="1027" alt="CleanShot 2021-11-19 at 20 22 36@2x" src="https://user-images.githubusercontent.com/38668796/142664829-a540d77d-f74f-4f7f-af69-a41ffa053ac1.png">

**Comment by antfu** [comment]
Fixes:

- [ ] https://github.com/nuxt/framework/pull/2067
- [ ] https://github.com/nuxt-contrib/vue-bundle-renderer/pull/19

**Comment by antfu** [comment]
Bring back by https://github.com/nuxt/framework/pull/2227

**Comment by shinguweb96** [comment]
bump
any news about that?

**Comment by danielroe** [comment]
Also see https://github.com/nuxt/framework/issues/4475.

**Comment by HochinChan** [comment]
Are there any solutions? I had the same problem.😭
![image](https://user-images.githubusercontent.com/65072526/185362889-bb85ca0b-9662-4d7a-9094-97d89d6fe24e.png)

**Comment by danielroe** [comment]
@HochinChan Your situation is not related, I think. I would recommend not using global components for exactly these kind of performance reasons, but instead to rely on Nuxt to auto-import them where required. You can track https://github.com/nuxt/framework/issues/6638 for more prefetching improvements.

**Comment by danielroe** [comment]
Reproduction with latest Nuxt: https://stackblitz.com/edit/github-nd6mk4.

**Comment by HochinChan** [comment]
> Reproduction with latest Nuxt: https://stackblitz.com/edit/github-nd6mk4.

https://stackblitz.com/edit/nuxt-starter-eyapnx

When I access pages/index (without using any components), the styles of all the components and the styles of other pages are also loaded

![image](https://user-images.githubusercontent.com/65072526/185387903-cb25b949-47f6-4153-b337-bf4cbd61642b.png)

**Comment by danielroe** [comment]
That should no longer be the case for pages on the edge channel, but yes, that was the purpose of my reproduction link - to show the issue.

**Comment by HochinChan** [comment]
> That should no longer be the case for pages on the edge channel, but yes, that was the purpose of my reproduction link - to show the issue.

Sorry, I'm not quite sure what you mean, but I was wondering how to make it load only the style of the current page

**Comment by danielroe** [comment]
Use https://v3.nuxtjs.org/guide/going-further/edge-channel. See https://github.com/nuxt/framework/pull/6662. It will still load component styles; that's what this issue is about. But it won't load page styles.

**Comment by HochinChan** [comment]
> Use https://v3.nuxtjs.org/guide/going-further/edge-channel. See #6662. It will still load component styles; that's what this issue is about. But it won't load page styles.

I see, thanks. The other page styles won't load when I use @latest.

**Comment by pi0** [comment]
We are working to make preload/prefetch smarter. Let's track the issue of global components in #6876. If there is any extra prefetch/preloading issue not caused by usage of global components please make another new issue with reproduction 🙏🏼
