### ISSUE TITLE
[Vue warn]: Invalid vnode type when creating vnode: undefined.

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#2020]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27286006.a08b435`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction
branch bug_ts

https://github.com/productdevbook/nuxt3-bug/tree/bug_ts

### Describe the bug

yarn dev

### Logs

```shell
ERROR  [proxy] connect ENOENT /var/folders/7c/jdnkxg5n6f3fz8425m0cwbsr0000gp/T/nitro/worker-47129-1.sock                    22:24:22

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)


 ERROR  [proxy] connect ENOENT /var/folders/7c/jdnkxg5n6f3fz8425m0cwbsr0000gp/T/nitro/worker-47129-1.sock                    22:24:38

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
```

**Comment by productdevbook** [comment]
update reproduction

branch bug_ts
https://github.com/productdevbook/nuxt3-bug/tree/bug_ts

**Comment by codebykenny** [comment]
Constantly getting this error as well

**Comment by Mxkkxa** [comment]
I am also having the same problem, I upgraded my project to bridge a month ago or so, when I got back to it I had this problem suddenly after doing a fresh npm i

**Comment by dergunovs** [comment]
[Vue warn]: Invalid vnode type when creating vnode: undefined.
Invalid value used as weak map key

Same error in dev mode when using component library. When i use <ClientOnly> tag everything is ok, in production even without <ClientOnly> all is ok.

**Comment by danielroe** [comment]
Looking at this, I couldn't initially reproduce as the reproduction doesn't run. (Missing end tag in a component, and incorrect colors.)

Updating to latest nuxt and fixing those issues, I had to make this change to your code:

```diff
- import { omit } from 'lodash'
+ import omit from 'lodash/omit'
```

With that, it runs fine.
