### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by adityar15** [nuxt/framework#2025]
### Environment

Nuxt CLI v3.0.0-27287661.1e0e881                                                                              22:32:31
RootDir: L:\adirani\app                                                                                       22:32:32
Nuxt project info:                                                                                            22:32:32

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27286577.ab1c6cb4`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Webpack`
- User Config:      `target`, `head`, `css`, `plugins`, `components`, `buildModules`, `generate`, `modules`, `axios`, `pwa`, `build`, `serverMiddleware`, `env`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/pwa@3.3.5`
- Build Modules:    `@nuxtjs/tailwindcss@4.2.1`, `@nuxt/bridge@3.0.0-27287661.1e0e881`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                              22:32:32

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

I have followed the steps as it is described here
https://v3.nuxtjs.org/getting-started/bridge

I was using @nuxt/composition-api package which is removed.

### Describe the bug

When I run npm run dev 
I get the following error
```
 WARN  [worker] Invalid or unexpected token                                                                   22:31:12

  at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)
  at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)
  at async link (node:internal/modules/esm/module_job:67:21)
```

The target in nuxt.config.js is static.

**Comment by danielroe** [comment]
Would you provide a reproduction please? 🙏

**Comment by OleMariusKohmann** [comment]
I have the same problem. with a clean nuxt2 project(following the guide for nuxt2). 
node version: 16.13.0
npm version: 7.24.2 (also tested with npm version 8.x)
Steps for nuxt2 installer:
1. npm init nuxt-app nuxt2-app
2. Programming Language: Typescript
3. Package manager: Npm
4. UI Framework: Tailwind CSS
5. Nuxt.js modules: Axios
6. Linting tools: ESLint, Prettier, StyleLint
7. Testing Framework: none
8. Rendering mode: Universal
9. Deployment target: Server
10. Development tools: None
11. Continous integration: None
12. Version control system: Git

nuxt2 app testet ok with npm run dev

installing nuxt3-bridge following the steps written @ https://v3.nuxtjs.org/getting-started/bridge

*Note
Every stops working at the step where you need to add:
export default defineNuxtConfig({
in nuxt.config.js. I tried to run the project for every change in the migration guide, and this is where it first happens.
Warning in terminal is then:

 WARN  [worker] Invalid or unexpected token

  at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)
  at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)
  at async link (node:internal/modules/esm/module_job:67:21)

attached project with this problem:
[nuxt2-app.zip](https://github.com/nuxt/framework/files/7570838/nuxt2-app.zip)

**Comment by pi0** [comment]
@OleMariusKohman Thanks for repro. Checking it, `@nuxtjs/tailwindcss` is not compatible yet with Nuxt3. (and not an issue with nuxt3 itself). 

You can wait for Nuxt 3 support (https://github.com/nuxt-community/tailwindcss-module/pull/399) or use [Windicss Module](https://github.com/windicss/nuxt-windicss). 

Here is a list of modules tested to be compatible with Nuxt bridge: https://modules.nuxtjs.org/?version=2.x-bridge

**Comment by pi0** [comment]
@adityar15 I guess you are facing same issue. If removing modules can also reproduce please mention so I will reopen.

**Comment by adityar15** [comment]
Hi, thanks @pi0 and @danielroe  for the comments. Unfortunately, I cannot reshare the repo as it is a private one. But I will try to reproduce it...

**Comment by imzedi** [comment]
Hi,
I faced the same issue even with a fresh install of Nuxt v2 and then followed the exact steps from [here](https://v3.nuxtjs.org/getting-started/bridge)

**Comment by danielroe** [comment]
@imzedi In that case can you provide that installation as a reproduction?

**Comment by imzedi** [comment]
Here is the full flow @danielroe 

## Sys info
OS: macOS Big Sur v11.6
Node: v12.22.1
NPM: v6.14.12

## Steps
1.  `npx create-nuxt-app hola`
3.  Removed node_modules and package-lock.json
2.  Replaced `nuxt` with `"nuxt-edge": "latest"` and re-installed all by `npm i`
3.  Installed nuxt bridge by `npm install -D @nuxt/bridge@npm:@nuxt/bridge-edge`
4.  Updated dev script to ` "dev": "nuxi dev"` (i need only this at the moment)
5.  Updated nuxt config like this 
```
import { defineNuxtConfig } from '@nuxt/bridge'
export default defineNuxtConfig({
    // Your existing configuration
})
```

6. Run `npm run dev`

##  Error
![image](https://user-images.githubusercontent.com/48899828/142760945-5817f6b9-7734-404e-8b4e-94db49682a66.png)

Please let me know if you need more.

**Comment by pi0** [comment]
@imzedi You are using an unsupported Node.js version (2.12). It should be 14 or 16

**Comment by imzedi** [comment]
Thanks, @pi0 for the quicker response, let me upgrade it and try!

**Comment by imzedi** [comment]
@pi0 Upgraded Node to LTS.
Working now!!
Superfast  🚀
