### ISSUE TITLE
isWindow not found

### ISSUE THREAD

**Issue by adityar15** [nuxt/framework#2026]
### Environment

Nuxt CLI v3.0.0-27287661.1e0e881                                                                              23:09:16
RootDir: L:\adirani\app                                                                                       23:09:17
Nuxt project info:                                                                                            23:09:17

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27286577.ab1c6cb4`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Webpack`
- User Config:      `target`, `head`, `css`, `plugins`, `components`, `buildModules`, `generate`, `modules`, `axios`, `pwa`, `build`, `serverMiddleware`, `env`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/pwa@3.3.5`
- Build Modules:    `@nuxtjs/tailwindcss@4.2.1`, `@nuxt/bridge@3.0.0-27287661.1e0e881`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                              23:09:17

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

When I run 

```
npm run build

```

### Describe the bug

After running npm run build got the following error

```
 FATAL  [worker] Named export 'isWindows' not found. The requested module 'std-env' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'std-env';
const { provider, isWindows } = pkg;


  import { provider, isWindows } from 'std-env';
  ^^^^^^^^^
  SyntaxError: Named export 'isWindows' not found. The requested module 'std-env' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:

  import pkg from 'std-env';
  const { provider, isWindows } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
  at async loadESM (node:internal/process/esm_loader:88:5)
  at async handleMainPromise (node:internal/modules/run_main:65:12)


   ╭───────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                   │
   │   ✖ Nuxt Fatal Error                                                                              │
   │                                                                                                   │
   │   SyntaxError: [worker] Named export 'isWindows' not found. The requested module 'std-env' is a   │
   │   CommonJS module, which may not support all module.exports as named exports.                     │
   │   CommonJS modules can always be imported via the default export, for example using:              │
   │                                                                                                   │
   │   import pkg from 'std-env';                                                                      │
   │   const { provider, isWindows } = pkg;                                                            │
   │                                                                                                   │
   │                                                                                                   │
   ╰───────────────────────────────────────────────────────────────────────────────────────────────────╯


 ERROR  Command failed with exit code 1: npx nuxt generate                                                    23:03:02

  at makeError$1 (/L:/adirani/app/node_modules/nuxi/dist/chunks/generate.mjs:1083:11)
  at handlePromise (/L:/adirani/app/node_modules/nuxi/dist/chunks/generate.mjs:1772:26)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.invoke (/L:/adirani/app/node_modules/nuxi/dist/chunks/generate.mjs:1942:7)
  at async _main (/L:/adirani/app/node_modules/nuxi/dist/chunks/index.mjs:386:7)

```

**Comment by danielroe** [comment]
See https://v3.nuxtjs.org/concepts/esm for more information.

**Comment by danielroe** [comment]
It looks like an older version of `std-env` might be in your lockfile. Can you try upgrading the version manually?

**Comment by adityar15** [comment]
Thought so too.. I will give it a try, thanks...

**Comment by pi0** [comment]
Tip: you can use `npx nuxi upgrade --force` to update all deps. It should fix the issue. Also check using latest version of `nuxt-edge`

**Comment by danielroe** [comment]
Closing as I think it's resolved. Let me know if it isn't.

**Comment by PixelBoii** [comment]
I encountered this as well and my guess would be that it comes from `@nuxt/telemetry` which uses v2.3.0 of `std-env`. I got it working by manually updating the versions inside the lock-file, but I assume it would be a pretty simply PR to the telemetry to get it sorted (I can make one if that sounds like a good fix).

**Comment by goldelehr** [comment]
> I encountered this as well and my guess would be that it comes from `@nuxt/telemetry` which uses v2.3.0 of `std-env`. I got it working by manually updating the versions inside the lock-file, but I assume it would be a pretty simply PR to the telemetry to get it sorted (I can make one if that sounds like a good fix).

Would you mind giving me a hint how you fixed this issue? I'm encountering a similar issue:

`
import { provider, isWindows } from 'std-env';
  ^^^^^^^^
  SyntaxError: Named export 'provider' not found. The requested module 'std-env' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
`

I tried to change std-env version manually in package-lock.json to 3.0.1 but the error still remains.

**Comment by MartinX3** [comment]
I added `std-env` as devDependency.

**Comment by Lehoczky** [comment]
> I added `std-env` as devDependency.

Thank you, I had the same issue today while following the bridge installation steps, and installing `std-dev` solved the problem.

**Comment by madebyfabian** [comment]
Having the same issue, and adding `std-env` as devDependency indeed helps! Thanks :)

**Comment by DominusKelvin** [comment]
> npx nuxi upgrade --force

Seems the upgrade command has been removed?

**Comment by danielroe** [comment]
You might have an older version cached.

Try `npx nuxi@latest upgrade --force`

**Comment by DominusKelvin** [comment]
Thanks @danielroe checking it out

**Comment by DominusKelvin** [comment]
<img width="1091" alt="Screenshot 2022-03-05 at 11 21 31" src="https://user-images.githubusercontent.com/24433274/156879113-9fc01e30-1cfc-4d7b-a218-35d6385c26ef.png">
@danielroe now I get this

**Comment by danielroe** [comment]
Ah. The command currently only works with nuxt3, not bridge.

**Comment by DominusKelvin** [comment]
Interesting. So there is no way to fix this Nuxt bridge issue @danielroe ?

**Comment by danielroe** [comment]
No, you can upgrade your dependencies or refresh your lockfile manually.

**Comment by mirono** [comment]
I tried to follow the bridge upgrade steps and have the same issue.
Adding "std-env": "^2.3.1", to dev deps didn't help.
Is there another way to solve this?

**Comment by FieldMarshallVague** [comment]
@mirono I added version "std-env": "^3.0.1" and it works, maybe try the newer version.
