### ISSUE TITLE
Tried to install Nuxt3 using the documentation site, failed. because of schema-edge

### ISSUE THREAD

**Issue by timothymarois** [nuxt/framework#2061]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `latest`
- Package Manager:  `yarn@1.22.5`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

It's easy, go here: 

https://v3.nuxtjs.org/getting-started/installation

run `npx nuxi init .`

then `npm install` 

and it failed. 

### Describe the bug

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nuxt/schema-edge@3.0.0-27291865.d68318f.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'nuxt3'
npm ERR! notarget 
```

**Comment by timothymarois** [comment]
`yarn install` also fails, but does give you this massive list of version builds to choose from **which is ridiculous.**

<img width="554" alt="Screen Shot 2021-11-21 at 11 36 29 AM" src="https://user-images.githubusercontent.com/2489333/142770788-f3d802a9-18a1-4d74-b16d-0bb6b1d9f49f.png">

yarn error: 

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by Zibbp** [comment]
I'm having the same issue as well when re-installing node modules for an existing project.
![image](https://user-images.githubusercontent.com/21207065/142772543-5e2eeae9-3927-442e-8c4b-8a38e93492e5.png)

**Comment by weleo** [comment]
I'm having the same issue as well when installing node modules for a new project.
![Screenshot 2021-11-21 at 18 28 57](https://user-images.githubusercontent.com/57549150/142772638-0c52f0e7-c9f5-4b24-8941-3df9906f6bf5.png)

**Comment by Niron68** [comment]
Same issue here, i temporary installed using this version and it works for people who want to install: 3.0.0-27291847.07c7a20

**Comment by pkej** [comment]
Use overrides to work around it. The error I got was:

```shell
ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @nuxt/webpack-builder@npm:@nuxt/webpack-builder-edge@3.0.0-27291865.d68318f
```
I fixed this by adding the following in the overrides in the package.json file:

```json
{
"overrides": {
      "@nuxt/webpack-builder": "npm:@nuxt/webpack-builder-edge@latest",
      "@nuxt/webpack-builder-edge": "latest"
    }
}
```

My full overrides are:
```json
{
 "pnpm": {
    "overrides": {
      "@nuxt/kit": "npm:@nuxt/kit-edge@latest",
      "@nuxt/kit-edge": "latest",
      "@nuxt/schema": "npm:@nuxt/schema-edge@latest",
      "@nuxt/schema-edge": "latest",
      "@nuxt/vite-builder": "npm:@nuxt/vite-builder-edge@latest",
      "@nuxt/vite-builder-edge": "latest",
      "@nuxt/webpack-builder": "npm:@nuxt/webpack-builder-edge@latest",
      "@nuxt/webpack-builder-edge": "latest"
    }
  }
}
```

**Comment by codebykenny** [comment]
d68318f9d5ee25f6377edb866cd1b5846e8bfdce seems to have caused this error.

I temporarily got around this issue by using the nuxt3 version before it. (3.0.0-27291847.07c7a20)

```
{
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "node .output/server/index.mjs"
  },
  "devDependencies": {
    "nuxt3": "3.0.0-27291847.07c7a20"
  }
}
```

**Comment by amery** [comment]
I have the same issue with nuxt/bridge

**Comment by pi0** [comment]
There was an issue with auto-release script access. Sorry for the inconvenience. 

Fresh installs with `latest` (`3.0.0-27292434.d68318f` or later) should be fine now and if you have issue with a previously updated version, `npx nuxi upgrade --force` should do the trick.
