### ISSUE TITLE
use nuxt 3 components implementation for nuxt bridge

### ISSUE THREAD

**Issue by ThomasBerne** [nuxt/framework#2069]
I'm simply missing ./.nuxt/components.d.ts.
![image](https://user-images.githubusercontent.com/23033483/142836396-30f956fb-e928-49ea-82b1-b0d718f0f0b7.png)
Here is my tsconfig.json:
`{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "types": ["unplugin-vue2-script-setup/types"]
  },
  "vueCompilerOptions": {
    "experimentalCompatMode": 2
  }
}
`
I run yarn dev who does nuxi dev. but the file is still missing and I don't understand why.
For the editor I'm using vscode with volar extension. It seems to work great but not for the components.

_Originally posted by @ThomasBerne in https://github.com/nuxt/framework/issues/2002#issuecomment-975325850_

**Comment by ThomasBerne** [comment]
I'm using nuxt bridge and here is my package.json : 
![image](https://user-images.githubusercontent.com/23033483/142839632-1b05339a-0a64-4ec5-b9f6-5fe6884e51a6.png)
And in my nuxt.config.ts I set components: true

**Comment by danielroe** [comment]
@ThomasBerne - The [nuxt 2 components module](https://github.com/nuxt/components/) does not generate a type definition file; that's currently a feature of the Nuxt 3 components implementation.

@pi0 - what do you think about swapping nuxt3 components implementation in bridge for `@nuxt/components`?

**Comment by pi0** [comment]
Probably worth a try but it might be also tricky since new module is highly depending on `nuxt3` build hooks. Alternatively we can simply use nuxt2 components hook inside `@nuxt/bridge` to extend types.

**Comment by ThomasBerne** [comment]
The components.d.ts isn't imported in the nuxt.d.ts
