### ISSUE TITLE
Nitro Watcher Needs Polling Config

### ISSUE THREAD

**Issue by peteromano** [nuxt/framework#2091]
### Environment

Docker, Windows, WSL

### Reproduction

Run the most minimal Nuxt3 boilerplate setup via the docs in a simple docker container.

### Describe the bug

For all typical/known Docker+WSL file watcher issues:

Vite polling works with `usePolling: true`.

Webpack works with chokidar or polling config options set.

**Nitro has no (documented) support for the equivalent.**

Polling option needs to be added, or if it's already supported, the docs need to be much clearer on how to enable polling.

~~(And development should have better testing for Docker+WSL.)~~

**Comment by peteromano** [comment]
@pi0

**Comment by pi0** [comment]
PR Welcome @peteromano you need to update [here](https://github.com/nuxt/framework/blob/main/packages/nitro/src/build.ts#L114).

BTW I always developed within WSL2 environment with no issues. Maybe we need to enable polling for specific environments known to watching issues?

**Comment by peteromano** [comment]
@pi0 Thanks for the response, and the lead!!

Yep, I'm still on WSL 1..

And, actually, it looks like the main issue is that `rollupConfig` (https://github.com/nuxt/framework/blob/main/packages/nitro/src/rollup/config.ts) isn't being made with any possible options to extend the hardcoded config.

So.. 

A) There would need to be an option from nuxt.config (is there a `nitro` config already?) I.e., `nitro.rollupConfig`
B) Let rollupConfig honor config options from nuxt.config, directly in the rollup/config.ts file (or it could be done at the nitro _watch function.)

Thoughts?

**Comment by pi0** [comment]
@peteromano Checking [chokidar](https://github.com/paulmillr/chokidar) docs, it seems there is a possibility to override polling by setting `CHOKIDAR_USEPOLLING=1 ` environment variable. Does that solve issue with Docker on WSL1 maybe?

**Comment by peteromano** [comment]
@pi0 Ugh.. I SINCERELY appreciate the reubber-ducking for exactly that reason of missing that in the doc; I don't dont know HOW i just glanced over that!! 

It fixes nitro AND its not needed in vite config anymore either -- way more elegant soution (as it IS env specific problem..)

Thank you SO much for taking another look!
