### ISSUE TITLE
nuxt2 error method in nuxt3 when using useAsyncData or useFetch

### ISSUE THREAD

**Issue by ziaadini** [nuxt/framework#2124]
### Environment

dos not matter

### Reproduction

there is no way to set error response code programmatically in nuxt3
for example if i have a product page and product slug dos not exist in backend how can i programitically load 404 error and
set response code of my route to 404 for seo purposes.

### Describe the bug

checkout reproduction section above.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/discussions/559.

**Comment by awacode21** [comment]
I am dealing with the same topic and have a question.

i have fully unknown generic routes (coming from cms).
So i use the [...slug].vue variant for catch-all-routes, as mentioned in the docs https://v3.nuxtjs.org/docs/directory-structure/pages

obviously it is now up to [...slug].vue to do the error handling.

Now my question, in nuxt 2 there was the possibility to use the validate() hook. When returning false the user got redirected to error page. also there was the error() function to navigate to error page. Is there any equivalent in nuxt 3??? how can i send the user to error page when i recognize an error within my [...slug].vue ?

**Comment by danielroe** [comment]
@awacode21 Agreed, we need to be able to handle errors in a catch all page like that - your thoughts are welcome on [the RFC](https://github.com/nuxt/framework/discussions/559).
