### ISSUE TITLE
Firebase Hosting Deploy Error ERR_PACKAGE_PATH_NOT_EXPORTED 

### ISSUE THREAD

**Issue by timotheeduran** [nuxt/framework#2151]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27296423.f3082ca`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

The problem happens on a fresh install of Nuxt using _yarn_ or _npm_ and by following [the official Firebase Hosting guide](https://v3.nuxtjs.org/docs/deployment/firebase) with both methods: [Using Nitro](https://v3.nuxtjs.org/docs/deployment/firebase#using-nitro) and [Using Firebase CLI](https://v3.nuxtjs.org/docs/deployment/firebase#using-firebase-cli).

A minimal reproduction can be found [on this git](https://github.com/timotheeduran/nuxt-firebase-issue).

1. `npx nuxi init nuxt3-app`
2. `cd nuxt3-app`
3. `yarn install`
4. `yarn global add firebase-tools`
5. `yarn add --dev firebase-admin firebase-functions firebase-functions-test`
6. `firebase init hosting`
- Please select an option: `Use an existing project`
- Select a default Firebase project for this directory: `<project name>`
- What do you want to use as your public directory? `.output/public`
- Configure as a single-page app (rewrite all urls to /index.html)? `No`
- Set up automatic builds and deploys with GitHub? `No`
6. `NITRO_PRESET=firebase yarn build`
7. `firebase deploy`

### Describe the bug

At the beginning things seem to work:
```
=== Deploying to '<project-name>'...

i  deploying functions, hosting
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  functions: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
```

And then this issue happens:
```
Error: Error occurred while parsing your function triggers.

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './runtime/polyfill/fetch.node' is not defined by "exports" in /Users/duran/Git/firebase-test/.output/server/node_modules/unenv/package.json imported from /Users/duran/Git/firebase-test/.output/server/index.mjs
    at throwExportsNotFound (internal/modules/esm/resolve.js:292:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at packageResolve (internal/modules/esm/resolve.js:612:14)
    at moduleResolve (internal/modules/esm/resolve.js:662:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:755:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:46:40)
    at link (internal/modules/esm/module_job.js:45:36)
```

### Additional context

* firebase-tools version 9.23.0
* Blaze (pay-as-you-go) plan activated
* No logs on Firebase Web Console
* Tried with _npm_ and _yarn_

**Comment by tobiasdiez** [comment]
I get similar errors for other libraries as well:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/index.mjs' is not defined by "exports" in D:\Programming\JabRefOnline\node_modules\murmurhash-es\package.json imported from D:\Programming\JabRefOnline\.nuxt\nitro\index.mjs

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './esm/index.js' is not defined by "exports" in D:\Programming\JabRefOnline\node_modules\throttle-debounce\package.json imported from D:\Programming\JabRefOnline\.nuxt\nitro\index.mjs
```
so maybe this is a more general issue?

**Comment by timotheeduran** [comment]
@danielroe This might be linked to your fix in PR #1360 for issue #1266. Both bugs are caused by the import of `unenv/runtime/polyfill/fetch.node`. With:
```
Error: Error occurred while parsing your function triggers.
/home/devjinnial/projects/krile-bot/website/.output/server/index.js:1
import 'unenv/runtime/polyfill/fetch.node';
```

Compared to this one:

```
Error: Error occurred while parsing your function triggers.

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './runtime/polyfill/fetch.node' is not defined by "exports" in /Users/duran/Git/firebase-test/.output/server/node_modules/unenv/package.json imported from /Users/duran/Git/firebase-test/.output/server/index.mjs
```

I don't have sufficient knowledge to dig this further yet. Do you have an idea?

**Comment by danielroe** [comment]
I can't reproduce this with your repo. The only thing I change is the project ID. I would assume this indicates a difference of project configuration on the firebase end. Could you tell me where your deployment logs diverge from mine?

```bash
❯ git clone https://github.com/timotheeduran/nuxt-firebase-issue
❯ cd nuxt-firebase-issue
❯ yarn install

# ....
# <update id in .firebaserc and firebase.json>

❯ NITRO_PRESET=firebase yarn build

Nuxt CLI v3.0.0-27296423.f3082ca
ℹ Vite warmed up in 1167ms
ℹ Client built in 1242ms
ℹ Building server...
✔ Server built in 573ms
ℹ Nitro preset is firebase
ℹ Cleaning up .output
start Generating public...
✔ Generated public .output/public
start Building server...
start Writing server bundle...
✔ Server built
  ├─ .output/server/index.mjs (69 kB) (23.5 kB gzip)
  ├─ .output/server/chunks/index.mjs (390 kB) (89.9 kB gzip)
  ├─ .output/server/chunks/app/vue3.mjs (284 B) (200 B gzip)
  ├─ .output/server/chunks/app/server.mjs (157 kB) (40.1 kB gzip)
  ├─ .output/server/chunks/app/render.mjs (22.7 kB) (6.28 kB gzip)
  └─ .output/server/chunks/app/client.manifest.mjs (224 B) (157 B gzip)
Σ Total size: 16.8 MB (2.86 MB gzip)
✔ Ready to run firebase deploy
✨  Done in 11.60s.

❯ firebase deploy

=== Deploying to '<project-id>'...

i  deploying functions, hosting
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  functions: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing .output/server directory for uploading...
i  functions: packaged .output/server (188.49 KB) for uploading
✔  functions: .output/server folder uploaded successfully
i  hosting[<project-id>]: beginning deploy...
i  hosting[<project-id>]: found 2 files in .output/public
✔  hosting[<project-id>]: file upload complete
i  functions: updating Node.js 14 function server(us-central1)...
✔  functions[server(us-central1)] Successful update operation.
Function URL (server(us-central1)): https://us-central1-<project-id>.cloudfunctions.net/server
i  functions: cleaning up build files...
i  hosting[<project-id>]: finalizing version...
✔  hosting[<project-id>]: version finalized
i  hosting[<project-id>]: releasing new version...
✔  hosting[<project-id>]: release complete

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/<project-id>/overview
Hosting URL: https://<project-id>.web.app
```

**Comment by jontybrook** [comment]
I have just had the same issue with a fresh project as per OP. I am able to reproduce the issue using the provided example repo. Following the same steps as you @danielroe - I get the OP's error. 


`
❯ NITRO_PRESET=firebase yarn build                                                                                 ─╯
yarn run v1.22.17
$ nuxi build
Nuxt CLI v3.0.0-27296423.f3082ca                                                                            13:42:16
ℹ Vite warmed up in 336ms                                                                                   13:42:17
ℹ Client built in 529ms                                                                                     13:42:18
ℹ Building server...                                                                                        13:42:18
✔ Server built in 251ms                                                                                     13:42:18
ℹ Nitro preset is firebase                                                                                  13:42:18
ℹ Cleaning up .output                                                                                       13:42:18
start Generating public...                                                                                  13:42:18
✔ Generated public .output/public                                                                           13:42:18
start Building server...                                                                                    13:42:18
start Writing server bundle...                                                                              13:42:21
✔ Server built                                                                                              13:42:22
  ├─ .output/server/index.mjs (69 kB) (23.5 kB gzip)
  ├─ .output/server/chunks/index.mjs (390 kB) (89.9 kB gzip)
  ├─ .output/server/chunks/app/vue3.mjs (284 B) (200 B gzip)
  ├─ .output/server/chunks/app/server.mjs (157 kB) (40.1 kB gzip)
  ├─ .output/server/chunks/app/render.mjs (22.8 kB) (6.29 kB gzip)
  └─ .output/server/chunks/app/client.manifest.mjs (224 B) (157 B gzip)
Σ Total size: 16.8 MB (2.86 MB gzip)
✔ Ready to run firebase deploy                                                                              13:42:22
✨  Done in 5.88s.

❯  firebase deploy                                                                                                 ─╯

=== Deploying to '<projctid-redacted>'...

i  deploying functions, hosting
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  functions: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled

Error: Error occurred while parsing your function triggers.

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './runtime/polyfill/fetch.node' is not defined by "exports" in /Users/jonty/workspaces/nuxt-firebase-issue/.output/server/node_modules/unenv/package.json imported from /Users/jonty/workspaces/nuxt-firebase-issue/.output/server/index.mjs
    at throwExportsNotFound (internal/modules/esm/resolve.js:292:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at packageResolve (internal/modules/esm/resolve.js:612:14)
    at moduleResolve (internal/modules/esm/resolve.js:662:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:755:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:46:40)
    at link (internal/modules/esm/module_job.js:45:36)
`

I am using Node v16.13.0, firebase CLI v9.23.0

**Comment by benoitlahoz** [comment]
Same here with a Gandi instance... Any clue on this?

**Comment by benoitlahoz** [comment]
That doesn't seem to be related to Firebase exclusively.

After digging a bit with the ERR_PACKAGE_PATH_NOT_EXPORTED error, I found this _Storybook.js_ related issue: https://github.com/storybookjs/storybook/issues/16623.

It says that while prior Node.js versions where only throwing a warning, **Node.js >=17.x.x is now throwing an error** for this case. Checking how the "exports" entry is written in the _unenv_ package.json, I don't how it would have to be refactored to avoid this error, though.

**Comment by FRostri** [comment]
You are still checking this? I'm getting the same error when i just want to test it

**Comment by pi0** [comment]
I guess we shouldn't have this issue anymore since the migration to nitropack. Please try with the latest dependencies (`npx nuxi upgrade --force`) and share a recent reproduction to investigate 🙏🏼
