### ISSUE TITLE
Vue3Mq is not installed in this app. Please follow the installation instructions and try again.

### ISSUE THREAD

**Issue by loremru** [nuxt/framework#2152]
Vue3Mq is not installed in this app. Please follow the installation instructions and try again.

`"nuxt3": "3.0.0-27296151.c5eed5e"`

In older versions of nuxt3 it works with `nuxtApp.app.use()`, but in new it doesn't

![image](https://user-images.githubusercontent.com/66596500/143413587-96eb25eb-c8e0-4989-9966-5b0d6ad24a1b.png)

![image](https://user-images.githubusercontent.com/66596500/143413803-b7873c90-a877-4467-8728-28580ced9c3c.png)

**Comment by danielroe** [comment]
Would you provide a reproduction, and fill out the other sections of the [new issue template](https://github.com/nuxt/framework/issues/new/choose), please? 🙏

**Comment by loremru** [comment]
@danielroe https://github.com/nuxt/framework/issues/2154
