### ISSUE TITLE
Vue3Mq is not installed in this app. Please follow the installation instructions and try again.

### ISSUE THREAD

**Issue by loremru** [nuxt/framework#2154]
### Environment

Nuxt CLI v3.0.0-27296423.f3082ca                                                                                                                   17:18:52
RootDir: C:\Users\Ilya\Desktop\nuxt3-app                                                                                                           17:18:54
Nuxt project info:                                                                                                                                 17:18:54

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27296423.f3082ca`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/loremru/nuxt3-bugreport-1

https://codesandbox.io/s/beautiful-cartwright-v4w07?file=/composables/useMq.ts

### Describe the bug

Vue3Mq is not installed in this app. Please follow the installation instructions and try again.

"nuxt3": "3.0.0-27296423.f3082ca"

In older versions of nuxt3 it works with nuxtApp.app.use(), but in new it doesn't

![image](https://user-images.githubusercontent.com/66596500/143457749-6ce40df0-c1bb-43ed-87e0-01e265ae12ac.png)

![image](https://user-images.githubusercontent.com/66596500/143457796-e51ac316-1268-4856-814c-7623aa7b422f.png)

**Comment by danielroe** [comment]
You were only installing vue3mq on client-side, which meant it couldn't render on the server: https://codesandbox.io/s/loving-wilbur-m64ht?file=/plugins/mq.js
