### ISSUE TITLE
Allow disabling automatic plugin imports

### ISSUE THREAD

**Issue by phoenix-ru** [nuxt/framework#2163]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.17.3`
- Nuxt Version:     `3.0.0-27296423.f3082ca`
- Package Manager:  `npm@7.24.2`
- Bundler:          `Webpack`
- User Config:      `buildModules`, `plugins`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `./modules/build/ModuleFederationModule.ts`

### Reproduction

In any project, try using `~/plugins` for plugins which don't follow the Nuxt structure.
**DO NOT** include such plugins in `nuxtConfig.plugins`

### Describe the bug

Currently Nuxt tries to auto-import plugins from `~/plugins`. However, this way, all the code placed inside this folder is considered a Nuxt plugin and therefore can't be used as anything else or disabled.

Toying around with `nuxtConfig.autoImports` doesn't seem to disable automatic imports, which in my setup is a destructive rather than useful feature.

### Logs

```shell
ERROR in ./.nuxt/plugins/client.mjs 17:2-15
export 'default' (imported as 'auth_8a8742aa') was not found in '<omitted>/plugins/remote/auth.ts' (possible exports: <omitted>)
```

**Comment by danielroe** [comment]
@phoenix-ru Yes, this isn't the `autoImports` feature (which has to do with automatically importing `defineComponent` etc.).

For now, a workaround would be to use the `app:resolve` hook to remove plugins you don't want added, or to use a different directory name.

https://github.com/nuxt/framework/blob/d68318f9d5ee25f6377edb866cd1b5846e8bfdce/packages/nuxt3/src/core/app.ts#L73-L80

Example:
```js
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  hooks: {
    'app:resolve'(app) {
      app.plugins = app.plugins.filter(p => !p.src.includes('/my/plugin/dir')
    }
  }
})

```

**Comment by phoenix-ru** [comment]
Thank you!
This may be not the most optimal way, though, as it may also filter out the explicitly specified plugins. Still, it is much better than nothing 👍

**Comment by pi0** [comment]
I think we should add back nuxtignore support for Nuxt3 (and plugin imports). This way we can ignore unwanted paths from plugins.
