### ISSUE TITLE
Support auto imports in template

### ISSUE THREAD

**Issue by antfu** [nuxt/framework#2170]

**Comment by antfu** [comment]
Did some research, well I think this is trickier than it looks.

Assuming we are talking about `<script setup>` (since auto importing in options API does not make that much sense.

![image](https://user-images.githubusercontent.com/11247099/143600262-b578cfa4-2d13-4da7-baf8-9aa803178636.png)

As we can see in the playground, when we use something in the template, the SFC compiler actually looked up the existing identifiers in `<script setup>` and use them directly. When it's not presented, it will fallback to use the component context (`this` object) - so that's the reason auto-importing won't work in the template. So I guess even tho we could replace `_ctx.xx` with auto importing, I think it could be a dangerous move since the user might actually want the `xx` in the runtime context. Introducing another plugin that runs before Vue's might be possible to inject the entry in `<script setup>` before SFC compilation - but I am not sure if the complexity is worth it (since we have #2168).

**Comment by pi0** [comment]
It makes sense that now we have `#imports` we can simply document workaround. This way type hinting should work and we won't have context similarity conflicts.
