### ISSUE TITLE
renders fragment or text root nodes issue

### ISSUE THREAD

**Issue by thejsbaguette** [nuxt/framework#2175]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27296423.f3082ca`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `buildModules`, `css`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.0.12`, `./modules/fonts/index.ts`
------------------------------

### Reproduction

- Open console
- Open or navigate between the pages:

https://stackblitz.com/edit/github-paupax?file=pages/second.vue

### Describe the bug

I think an image is always better. It should support fragments no ?

<img width="468" alt="Screen Shot 2021-11-26 at 11 10 45 PM" src="https://user-images.githubusercontent.com/11556276/143667574-bdcd7543-bc86-40a4-b945-c673b17787e9.png">

**Comment by productdevbook** [comment]
maybe this problem -> https://github.com/vuejs/vue-next/issues/4817

**Comment by danielroe** [comment]
No, you need a single root node for pages.

https://v3.nuxtjs.org/docs/directory-structure/pages
