### ISSUE TITLE
hello，I have a problem in <nuxt />

### ISSUE THREAD

**Issue by liming-xxw** [nuxt/framework#2179]
### Environment

   "nuxt3": "3.0.0-27277330.202617b",
    "postcss": "8.3.11",
    "sass": "1.43.4",
    "sass-loader": "12.3.0",
    "tailwindcss": "3.0.0-alpha.1"

### Reproduction

no

### Describe the bug

![image](https://user-images.githubusercontent.com/56504602/143671866-51199d62-a8ab-4747-ad5d-9713d7e7905a.png)
There were no mistakes before

**Comment by yauri-io** [comment]
@liming-xxw could you put your code in example repo?

**Comment by danielroe** [comment]
Nuxt 3 doesn't use `<Nuxt />`. Layouts take a `<slot />` and within your `app.vue`, you would use `<NuxtPage />`.

A migration guide is [here](https://v3.nuxtjs.org/getting-started/migration).
