### ISSUE TITLE
allow auto-imports inside node_modules

### ISSUE THREAD

**Issue by yassilah** [nuxt/framework#2180]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.11.1`
- Nuxt Version:     `2.16.0-27299536.ab1c6cb4`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `bridge`, `components`, `autoImports`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/core/nuxt@7.1.2`, `@nuxt/bridge@3.0.0-27296423.f3082ca`

### Reproduction

-

### Describe the bug

The auto-imports feature excludes by default all files inside 'node_modules' from being transformed. As I am currently developing a library, I would have liked to have the possibility to write auto-imported composables that can be overwritten by the user. If I want them to be overwritable, I cannot set an explicit import statement but it is currently impossible to explicitly transform a given file/folder inside node_modules. I hope this makes sense, here's an example use case:

### Example:
```ts
// node_modules/library/composables/bar.ts
export function useBar() {
    return 'bonjour'
}
```
```vue
// node_modules/library/components/Foo.vue
<script setup lang="ts">
const foo = useBar()
</script>

<template>
  <div>{{ foo }}</div>
</template>
```
```vue
// pages/index.vue
<script setup lang="ts">
import Foo from 'library/components/Foo.vue'
</script>


<template>
  <Foo /> <!-- should be <div>bonjour</div> -->
</template>
```
After overwriting my composable:
```ts
// composables/bar.ts
export function useBar() {
    return 'salut'
}
```

```vue
// pages/index.vue
<script setup lang="ts">
import Foo from 'library/components/Foo.vue'
</script>


<template>
  <Foo /> <!-- should be <div>salut</div> -->
</template>
```

**Comment by danielroe** [comment]
You can achieve this result also by explicitly importing from `#imports`, e.g.:

```js
import { myOverwrittenComposable } from '#imports'`
```

**Comment by yassilah** [comment]
hi! thanks for your tip, though if I need to explicitly import it, it's not really auto-imported 😕
