### ISSUE TITLE
await useFetch make 2 request  on one time  in NuxtChild

### ISSUE THREAD

**Issue by andysay** [nuxt/framework#2194]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27296423.f3082ca`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.5`
------------------------------

### Reproduction

-

### Describe the bug

If we build app with NuxtChildren and in child use await useFetch we have 2 request on one time

/page/parent to /page/parent/child 

let data = await useFetch("/api/test");
console.log(data);

![Снимок экрана 2021-11-28 в 16 06 56](https://user-images.githubusercontent.com/5610952/143769121-15685b71-1fc6-4374-b5fd-da737eb09d25.png)

**Comment by pi0** [comment]
Hi @andysay. Do you mind making a minimal reprodution?

**Comment by andysay** [comment]
@pi0  https://codesandbox.io/s/nuxt3-project-test-with-vue3-xonvu?file=/pages/parent.vue > useFetch link

**Comment by danielroe** [comment]
@andysay Several observations:

1. Pages need a single root node
2. By doing this, you're setting the asyncData value to void:
   ```js
   const post = await useFetch(`/api/res`).then((a) => {
     console.log(a);
   });
   ```

With these addressed, I can't replicate the issue.

**Comment by andysay** [comment]
> * Pages need a single root node

@danielroe @pi0  https://codesandbox.io/s/confident-gagarin-l6v7q?file=/pages/index.vue i make new sandbox, and what i have
![ScreenRecorderProject11](https://user-images.githubusercontent.com/5610952/143928718-8c05e245-6ead-4066-be9f-548ec37ee35f.gif)

why child page have 2 request ??/

**Comment by danielroe** [comment]
You need to return a value from `.then`.

**Comment by andysay** [comment]
> You need to return a value from

i make 

<script setup>
const post = await useFetch(`/api/hello`)
  .then((a) => {
    return a;
  })
  .catch((err) => {
    console.log(err);
  });
console.log(post);
</script>

 but 2 still two request ...

**Comment by danielroe** [comment]
What makes you think there are multiple requests? I can't see them.

**Comment by andysay** [comment]
> What makes you think there are multiple requests? I can't see them.

ok in network we get 1 request, so why in console data return 2 times ?

**Comment by danielroe** [comment]
root issue is https://github.com/nuxt/framework/issues/2309
