### ISSUE TITLE
lost privateRuntimeConfig on ssr mode

### ISSUE THREAD

**Issue by liuqian1996** [nuxt/framework#2201]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.17.6`
- Nuxt Version:     `3.0.0-27296423.f3082ca`
- Package Manager:  `npm@6.14.15`
- Bundler:          `Vite`
- User Config:      `meta`, `css`, `vite`, `privateRuntimeConfig`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

use `router.push()` to another page
In another page
`useRoute()` lost params on terminal log

### Describe the bug

![image](https://user-images.githubusercontent.com/11707934/143816364-c4e7ab10-32d7-449c-a88b-a56d4686ecf8.png)

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏 

Are you including the query in the router.push?

**Comment by liuqian1996** [comment]
yeah, this question maybe reasons of **baseUrl**, baseUrl defined in privateRuntimeConfig

```ts
  privateRuntimeConfig: {
    baseUrl: process.env.BASE_URL || 'http://localhost:9000/api',
  }
```

[CodeSandBox](https://codesandbox.io/s/lost-private-runtime-config-vjioo)

you can see **privateTitle** show and hidden on the draft

**Comment by danielroe** [comment]
yes, privateRuntimeConfig is not accessible on client-side, and if you use it in your template you'll have a hydration error.

**Comment by liuqian1996** [comment]
so, If I want to use privateRuntimeConfig, should I wrapper **useRuntimeConfig** on server-side?

**Comment by danielroe** [comment]
On server-side, you'll get the privateRuntimeConfig from `useRuntimeConfig()`. You just have to make sure only to use it on SSR, and not use it within your HTML or you'll cause a hydration error.
