### ISSUE TITLE
Error when integrating AmChart V4 with Nuxt Bridge

### ISSUE THREAD

**Issue by Ali-Nasir-01** [nuxt/framework#2207]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27300977.ab1c6cb4`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Webpack`
- User Config:      `head`, `bridge`, `ssr`, `css`, `dev`, `plugins`, `components`, `render`, `router`, `buildModules`, `modules`, `server`, `axios`, `proxy`, `auth`, `recaptcha`, `gtm`, `i18n`, `pwa`, `vuetify`, `loading`, `pageTransition`, `layoutTransition`, `vue`, `security`, `dir`, `env` 
- Runtime Modules:  `@dansmaculotte/nuxt-security@0.0.2`, `@nuxtjs/auth-next@5.0.0-1624817847.21691f1`, `@nuxtjs/axios@5.13.6`, `nuxt-i18n@6.28.1`, `@nuxtjs/toast@3.3.1`, `@nuxtjs/proxy@2.1.0`, `@nuxtjs/recaptcha@1.0.4`, `@nuxtjs/gtm@2.4.0`, `@nuxtjs/pwa@3.3.5`
- Build Modules:    `@nuxtjs/vuetify@1.12.1`, `@nuxtjs/device@2.1.0`, `@nuxt/bridge@3.0.0-27296423.f3082ca`

### Reproduction

The problem is visible by opening in a new tab and checking the browser console.

https://codesandbox.io/s/suspicious-tereshkova-b2uk8

### Describe the bug

I have a AmChart with Nuxt 2.15.8 and it works perfect. But when I try to do the same integration with Nuxt Bridge I get this error in console:
`Uncaught TypeError: Cannot destructure property '__extends' of '_tslib_js__WEBPACK_IMPORTED_MODULE_0___default.a' as it is undefined.
    at eval (index.js?5795:3)
    at Module../node_modules/@amcharts/amcharts4/node_modules/tslib/modules/index.js (app.js:2711)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (EventDispatcher.js?daec:1)
    at Module../node_modules/@amcharts/amcharts4/.internal/core/utils/EventDispatcher.js (app.js:2327)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (Registry.js?84cf:1)
    at Module../node_modules/@amcharts/amcharts4/.internal/core/Registry.js`

**Comment by danielroe** [comment]
let's follow in https://github.com/nuxt/framework/issues/1151
