### ISSUE TITLE
 [proxy] connect ENOENT /tmp/nitro/worker-128-82.sock    at PipeConnectWrap.afterConnect [as oncomplete]

### ISSUE THREAD

**Issue by andysay** [nuxt/framework#2208]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27296423.f3082ca`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `privateRuntimeConfig`, `publicRuntimeConfig`, `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/nuxt3-project-test-with-vue3-xonvu?file=/pages/upload.vue

### Describe the bug

try upload file nitro return 

[proxy] write EPIPE                                                                                                                                            13:48:21
at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)

**Comment by misaon** [comment]
@andysay i have same issue on latest Nuxt bridge version. How you solve it?

**Comment by andysay** [comment]
> @andysay i have same issue on latest Nuxt bridge version. How you solve it?

thats work only on build state.. in dev bugged .
