### ISSUE TITLE
build error when set build.extractCSS to true and build with webpack

### ISSUE THREAD

**Issue by sanfengliao** [nuxt/framework#2217]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.15.5`
- Nuxt Version:     `3.0.0-27303148.ac98373`
- Package Manager:  `npm@6.14.11`
- Bundler:          `Webpack`
- User Config:      `vite`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

The problem happens when set `build.extractCSS` to true and build with webpack

A minimal reproduction can be found [on this git](https://github.com/sanfengliao/nuxt-demo).

- clone repository to local device
- `cd nuxt-demo`
- `npm install`
- `npm run build or npm. run dev`

### Describe the bug

build error

![image](https://user-images.githubusercontent.com/31816772/143884874-1e284858-ac0f-43d3-9009-d6344a20dde1.png)

![image](https://user-images.githubusercontent.com/31816772/143884743-590d1777-6309-4d98-b35d-7c5b1ad6b138.png)

**Comment by steklopod** [comment]
Please, try:
```js
import { defineNuxtConfig } from '@nuxt/bridge'
```
instead of `import { defineNuxtConfig } from 'nuxt3'`.

I have the same preset as you, but I don't have errors

**Comment by sanfengliao** [comment]
> 

![image](https://user-images.githubusercontent.com/31816772/144045529-25ae3418-07a0-4c41-ab3b-84f056bebecc.png)

Another error is thrown when I use
when using
```typescript
import { defineNuxtConfig } from '@nuxt/bridge'
```
And this project was created by `npx nuxi init nuxt3-app`, since it cannot be built successfully with this configuration, it shows that this is indeed a bug

**Comment by sanfengliao** [comment]
> 

![image](https://user-images.githubusercontent.com/31816772/144045529-25ae3418-07a0-4c41-ab3b-84f056bebecc.png)

Another error is thrown when I use
when using
```typescript
import { defineNuxtConfig } from '@nuxt/bridge'
```
And this project was created by `npx nuxi init nuxt3-app`, since it cannot be built successfully with this configuration, it shows that this is indeed a bug
@steklopod

**Comment by chz** [comment]
i have same issue but without error but css not extracted if remove extractCSS line it will work but styles is inlined
