### ISSUE TITLE
Replace of 'undefined' in router middleware

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/framework#2221]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `2.16.0-27299536.ab1c6cb4`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Webpack`
- User Config:      `ssr`, `components`, `devtools`, `sourcemap`, `productionTip`, `telemetry`, `modern`, `bridge`, `publicRuntimeConfig`, `privateRuntimeConfig`, `head`, `manifest`, `pwa`, `loading`, `plugins`, `modules`, `buildModules`, `buildDir`, `router`, `styleResources`, `css`, `vite`, `axios`, `io`, `auth`, `dateFns`, `fontawesome`, `toast`, `sentry`, `stripe`, `render`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/pwa@3.3.5`, `@nuxtjs/auth-next@5.0.0-1637745161.ea53f98`, `@nuxtjs/sentry@5.1.6`, `@nuxtjs/toast@3.3.1`, `nuxt-stripejs@1.1.6`, `portal-vue/nuxt`, `v-wave/nuxt`
- Build Modules:    `@nuxtjs/date-fns@1.5.0`, `@nuxtjs/fontawesome@1.1.2`, `@nuxtjs/style-resources@1.2.1`, `@nuxt/postcss8@1.1.3`, `@nuxt/bridge@3.0.0-27296423.f3082ca`
------------------------------

### Reproduction

Add the following to `nuxt.config.js`:

```js
router: {
    base: '/',
    middleware: ['auth'],
    linkActiveClass: 'active',
    linkExactActiveClass: 'exact-active',
    extendRoutes(routes) {
      routes.push({
        path: '/',
        redirect: '/write',
      })
    }
  },
```

The important part that fails is `middleware: ['auth']` as specified in the `@nuxtjs/auth-next` module docs as well as in the Nuxt docs.

Try to start the dev server.

### Describe the bug

When running `yarn dev` the following error appears:

![image](https://user-images.githubusercontent.com/2703233/143912009-be59066c-0bc8-4725-9084-a107579fa754.png)

This is bc in `node_modules/@nuxt/bridge/dist/chunks/module2.mjs`:

![image](https://user-images.githubusercontent.com/2703233/143912111-08a918ec-acee-4237-967d-011b6ba5eee3.png)

at `map((m) => ...)` where `m` is simply the string `"auth"` and therefore `m.src` is undefined.

I raised this error already in the `@nuxt/auth` repo [here](https://github.com/nuxt-community/auth-module/issues/1323#issuecomment-980787536), but they think it is a Nuxt Bridge problem and I agree, bc it shows up when following the Nuxt docs.

**Comment by danielroe** [comment]
Would you provide a minimal reproduction?

**Comment by toniengelhardt** [comment]
Hey @danielroe, thanks for taking a look!

Here is the reproduction:

Github: https://github.com/toniengelhardt/nuxt-bridge-debug 
CodeSandBox: https://codesandbox.io/s/cool-benji-c0ryp
