### ISSUE TITLE
Cannot start nuxt:  str.startsWith is not a function

### ISSUE THREAD

**Issue by zorro1rr** [nuxt/framework#2222]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.17.0`
- Nuxt Version:     `2.16.0-27302415.ab1c6cb4`
- Package Manager:  `npm@6.14.13`
- Bundler:          `Webpack`
- User Config:      `ssr`, `telemetry`, `bridge`, `server`, `privateRuntimeConfig`, `router`, `env`, `head`, `loading`, `css`, `plugins`, `buildModules`, `tailwindcss`, `modules`, `appInsights`, `render`, `build`, `serverMiddleware`
- Runtime Modules:  `@nuxtjs/dotenv@1.4.1`, `@nuxtjs/google-gtag@1.0.4`, `nuxt-mq@2.0.2`
- Build Modules:    `@nuxtjs/eslint-module@3.0.2`, `@nuxtjs/tailwindcss@2.0.0`, `@nuxtjs/applicationinsights@1.2.2`, `@nuxt/bridge@0.10.1`

### Reproduction

N/A

### Describe the bug

Getting an error running "nuxi dev"

### Logs

```shell
ERROR  Cannot start nuxt:  str.startsWith is not a function                                                                                                                                                       10:34:57

  at node_modules/@nuxt/utils-edge/dist/utils.js:161:77
  at Array.some (<anonymous>)
  at node_modules/@nuxt/utils-edge/dist/utils.js:161:61
  at Object.r2 [as r] (node_modules/@nuxt/utils-edge/dist/utils.js:179:7)
  at node_modules/@nuxt/builder-edge/dist/builder.js:449:24
  at Array.map (<anonymous>)
  at Builder.resolveCustomTemplates (node_modules/@nuxt/builder-edge/dist/builder.js:446:65)
  at Builder.generateRoutesAndFiles (node_modules/@nuxt/builder-edge/dist/builder.js:296:16)
  at async Builder.build (node_modules/@nuxt/builder-edge/dist/builder.js:259:5)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6719:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6756:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:382:7)
```

**Comment by mdarrik** [comment]
To add to this, it looks like it's related to `meta.mjs`.  If I log out the strings that the startsWithAlias helper is processing, it returns an object with the filename `meta.mjs`. 

Looks like maybe that file is getting resolved somehow before being passed to the helpers: 

```js
{                                                                                                                                                                                                                                                                                                                            
  filename: 'meta.mjs',
  getContents: [Function: getContents],
  dst: '/Users/darrik/github/getnacelle/nuxt-reference-store-bridge/node_modules/.cache/nuxt/meta.mjs'
}
```

Looking a bit further it looks like the expectation is that object has a src property that's not there. 

```js
//@nuxt/builder-edge/dist
// line 447
const src = t.src ||  t;
```

Reverting back to `3.0.0-27296423.f3082ca` for nuxt/bridge fixes the issue.

**Comment by jerry-jpreng** [comment]
Same issue with nuxt 2.16.0-27303855.ab1c6cb4.
node: 16.12.0

**Comment by olivervorasai** [comment]
This error occurs on the recommended code sandbox template when creating an new nuxt-bridge issue:

https://codesandbox.io/s/github/nuxt/starter/tree/bridge-codesandbox

**Comment by pigfoot** [comment]
`3.0.0-27303091.b7a429c` -> first commit to reproduce this issue
`3.0.0-27303090.f5d1d9a` -> build successfully
Hope it helps.
