### ISSUE TITLE
Flash of unstyled content (FOUC)  with Nuxt 3、Vite

### ISSUE THREAD

**Issue by webfansplz** [nuxt/framework#2224]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.16.1`
- Nuxt Version:     `3.0.0-27303148.ac98373`
- Package Manager:  `yarn@1.22.5`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Mini Repo : https://github.com/webfansplz/nuxt3-fouc-repo/tree/main

### Describe the bug

After building it with yarn build (nuxt build) and starting the server with yarn start (node .output/server/index.mjs) we still get a flash of unstyled content on load.

This problem also existed in develop mode . 

The `FOUC` leads to very annoying developer experience and user experience . 💔

**Comment by webfansplz** [comment]
seems [this commit](https://github.com/nuxt/framework/commit/a149225e6362c3ca90f017671e97898b0697417d#diff-73d24e0438084e6b6e73889c3113b4fa1c27f2c3e03e70349beed1cadd3c9696) caused  , i go back to the version before this commit,it's work fine .

cc @antfu  (sorry to ping you )

**Comment by antfu** [comment]
@webfansplz Can you help confirm if reverting a149225e6362c3ca90f017671e97898b0697417d fix only dev or also build?
I feel the prod build might related to https://github.com/nuxt-contrib/vue-bundle-renderer/pull/19

**Comment by webfansplz** [comment]
> @webfansplz Can you help confirm if reverting [a149225](https://github.com/nuxt/framework/commit/a149225e6362c3ca90f017671e97898b0697417d) fix only dev or also build? I feel the prod build might related to [nuxt-contrib/vue-bundle-renderer#19](https://github.com/nuxt-contrib/vue-bundle-renderer/pull/19)

@antfu Only fixed in develop mode (already confirmed)

**Comment by antfu** [comment]
- https://github.com/nuxt-contrib/vue-bundle-renderer/pull/21
- https://github.com/nuxt/framework/pull/2227

**Comment by webfansplz** [comment]
Thank you for your quick response !

**Comment by steklopod** [comment]
I have the same preset as author and I got flashing effect on my main page. I added in `nuxt.config.ts`
```js
build: {
    extractCSS: true
}
```
and the effect gone. Did I make it right way?  🤷🏻

**Comment by webfansplz** [comment]
> I have the same preset as author and I got flashing effect on my main page. I added in `nuxt.config.ts`
> 
> ```js
> build: {
>     extractCSS: true
> }
> ```
> 
> and the effect gone. Did I make it right way? 🤷🏻

This is only applied in webpack , we have the same problem, but not the same reason .
