### ISSUE TITLE
The 15.nuxt.config.md file is missing from the documentation

### ISSUE THREAD

**Issue by whylost** [nuxt/framework#2238]
The 15.nuxt.config.md file is missing from the documentation
![image](https://user-images.githubusercontent.com/62528887/144154722-1152e3a4-b728-4b08-8667-c3954803412c.png)

**Comment by n2ptune** [comment]
I think it's probably intentional. as it is registered in `docs/.gitignore`

```
schema
15.nuxt.config.md
```

It seems to be created dynamically by script (`docs/scripts/gen-docs.ts`), `npm run gendocs`

But, why?

**Comment by whylost** [comment]
ok, I have generated this file
