### ISSUE TITLE
useState() after async causes nuxt instance unavailable

### ISSUE THREAD

**Issue by coryvirok** [nuxt/framework#2241]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27304790.cad09fe`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/focused-forest-8brjk?file=/app.vue

### Describe the bug

Calling `useState()` after an async call in the setup method causes the following error to throw:

```
Error: nuxt instance unavailable
    at Module.useNuxtApp (file:///sandbox/.nuxt/dist/server/server.mjs:244:13)
    at Module.useState (file:///sandbox/.nuxt/dist/server/server.mjs:660:38)
    at Module.useCounter (file:///sandbox/.nuxt/dist/server/server.mjs:1901:41)
    at setup (file:///sandbox/.nuxt/dist/server/server.mjs:1849:60)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

However, if the `useState()` is moved to before the async call, no error is thrown.

**Comment by danielroe** [comment]
@coryvirok This is a consequence of how `async setup` works. This [helpful article](https://antfu.me/posts/async-with-composition-api) explains why. You can use the built-in solution @antfu mentions by using `<script setup>` instead of `<script>`.

**Comment by coryvirok** [comment]
Oh, fascinating. Thanks for the article.

I can imagine this is going to bite a lot of people who are creating composables that don't know they're being called after an async operation. Is there a general recommendation to make for them?

e.g.

```ts
// composables/useLocalUser.ts

import { useState } from '#app'

export default function useLocalUser() {
  const state = useState<{id: string}>('localUser', () => {id: null})
  function setLocalUser(user: { id: string }) {
    state.value = { id: user.id }
  }

  return {
    state,
    setLocalUser
  }
}

// composables/useFetchRemoteUser.ts

import useLocalUser from '~/composables/useLocalUser'

export default function useFetchRemoteUser() {
  async function fetch(id: string): Promise<{ id: string } | null> {
    const result = await fetchFromAPI(id)

    const { setLocalUser } = useLocalUser()  // Will fail with the `nuxt instance unavailable` error
    setLocalUser(result.user)
  
    return result.user
  }
}
```

The sync `useLocalUser` composable is called after an async operation, which will lead to this error, IIUC. Is there a general solution that doesn't require the author of a composable to know when their composable will be called, (i.e. before or after an async operation?)

**Comment by danielroe** [comment]
Composables should always be called within `setup()`, not within a function within it (as with your `fetch()` example). You should be able to assume that your composable is being called with access to the nuxt app instance (or Vue current instance), either because the user is using `<script setup>` or because they have taken care not to call a composable after an await.

**Comment by coryvirok** [comment]
Thanks for the tips. Does that mean composables shouldn't be used in Nuxt plugins? This is where I originally ran into the problem.

**Comment by danielroe** [comment]
You can use Nuxt-specific helper functions in Nuxt plugins, but you should call them before doing any awaiting.

**Comment by coryvirok** [comment]
FWIW and for anyone else who comes across this, I ended up moving all of my composables into Pinia datastores. I'm not sure if the same issue occurs with Pinia, but I haven't ran into it yet. And not having to worry about what happens before vs after async is pretty important for me to keep my codebase maintainable.

For whoever might be following along, I think there's an opportunity for Vue/Nuxt folks to better describe the intended use cases for composables. I *thought* it was to decouple logic and make it reusable in *any* part of your codebase, (e.g. templates, setup, router guards, plugins.) But from what I gather, this isn't entirely true. So, some guidance on what's kosher in the way of examples would be tremendously helpful. 

Normally, I'd offer to help write the docs/examples. But I feel pretty far out of my depth on this topic.

**Comment by danielroe** [comment]
You're right that composables do enable you to decouple logic and make it reusable. But what most people mean by _composables_ are effectively setup functions that have to be run in `setup()`. They do whatever you need to 'set up' your functionality, and then return functions/state/etc.

So you can't just run those setup functions at any time - they almost always need to be run within the setup function to close over whatever key instances or values you can access there.

For example, to refactor your composable:
```diff
// composables/useLocalUser.ts

import { useState } from '#app'

export default function useLocalUser() {
  const state = useState<{id: string}>('localUser', () => {id: null})
  function setLocalUser(user: { id: string }) {
    state.value = { id: user.id }
  }

  return {
    state,
    setLocalUser
  }
}

// composables/useFetchRemoteUser.ts

import useLocalUser from '~/composables/useLocalUser'

export default function useFetchRemoteUser() {
+ const { setLocalUser } = useLocalUser()  // Will fail with the `nuxt instance unavailable` error
  async function fetch(id: string): Promise<{ id: string } | null> {
    const result = await fetchFromAPI(id)

-   const { setLocalUser } = useLocalUser()  // Will fail with the `nuxt instance unavailable` error
    setLocalUser(result.user)
  
    return result.user
  }

  return {
    fetch
  }
}
```

**Comment by coryvirok** [comment]
Thanks, Daniel!

**Comment by misaon** [comment]
> You're right that composables do enable you to decouple logic and make it reusable. But what most people mean by _composables_ are effectively setup functions that have to be run in `setup()`. They do whatever you need to 'set up' your functionality, and then return functions/state/etc.
> 
> So you can't just run those setup functions at any time - they almost always need to be run within the setup function to close over whatever key instances or values you can access there.
> 
> For example, to refactor your composable:
> 
> ```diff
> // composables/useLocalUser.ts
> 
> import { useState } from '#app'
> 
> export default function useLocalUser() {
>   const state = useState<{id: string}>('localUser', () => {id: null})
>   function setLocalUser(user: { id: string }) {
>     state.value = { id: user.id }
>   }
> 
>   return {
>     state,
>     setLocalUser
>   }
> }
> 
> // composables/useFetchRemoteUser.ts
> 
> import useLocalUser from '~/composables/useLocalUser'
> 
> export default function useFetchRemoteUser() {
> + const { setLocalUser } = useLocalUser()  // Will fail with the `nuxt instance unavailable` error
>   async function fetch(id: string): Promise<{ id: string } | null> {
>     const result = await fetchFromAPI(id)
> 
> -   const { setLocalUser } = useLocalUser()  // Will fail with the `nuxt instance unavailable` error
>     setLocalUser(result.user)
>   
>     return result.user
>   }
> 
>   return {
>     fetch
>   }
> }
> ```

thanks for the extensive explanation! this should be a must have thing in the documentation.
