### ISSUE TITLE
useBody doesn't resolve Promise on local call when body is empty

### ISSUE THREAD

**Issue by Norel** [nuxt/framework#2247]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.0.0-27304790.cad09fe`
- Package Manager:  `npm@8.1.4`
- Bundler:          `Vite`
- User Config:      `privateRuntimeConfig`, `publicRuntimeConfig`, `css`, `meta`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-kzkntz

### Describe the bug

Reposting here after being asked (https://github.com/unjs/h3/issues/49)

I tested with an api endpoint on a Nuxt3 project but you can probably reproduce with any local call I guess.

server/api/user.ts
```
export default async (req: IncomingMessage, res: ServerResponse) => {
    const body = await useBody(req)
}
```

Using ohmyfetch to call the api locally with default GET method (and without body)
```
await $fetch('/api/user')
```

The Promise in the useRawBody function never gets resolved because the req.on is never called https://github.com/unjs/h3/blob/25a61950f54fa1fe89b9d50fab71b3d040de0bf2/src/utils/body.ts#L29-L41

I guess it's tied to unenv fetch setting the req.body to null
https://github.com/unjs/unenv/blob/909d75e48667ce0732ce0fa8b6a2af4895f54d8e/src/runtime/fetch/call.ts#L31
```
req.body = context.body || null
```

I don't know if it's something that needs to be fixed here or in unenv.

As solution in h3 could be using this syntax (Node.js v10 + only) :
```
const bodyData = [];

for await (const chunk of req) {
    bodyData.push(chunk);
}

req[RawBodySymbol] = Buffer.concat(bodyData) 
resolve(encoding ? req[RawBodySymbol].toString(encoding) : req[RawBodySymbol]) 
```

**Comment by pi0** [comment]
Thanks for reprodution issue @Norel.

Explanation: We should only consume body with `POST`, `PUT`, and `PATCH` HTTP methods. `fetch` uses `GET` by default and cannot have body. We should use fetch like this:

```js
const { data: user } = await useFetch("/api/user", {
  method: "POST",
  body: { name: "Stuart" },
});
```

Full example: https://codesandbox.io/s/laughing-solomon-3jcqy?file=/app.vue

---

The latest version of `h3` has several fixes for unenv integration and also by default throws 405 error when using `useBody` in a `GET` request. (please use `npx nuxi upgrade --force` again 👍 )

You can guard usage optionally with `method(req, 'GET') { }` if API handler is supposed to support both get and post.

**Comment by Norel** [comment]
Thank you for the changes. The 405 error is much easier to debug than a never ending fetch !
