### ISSUE TITLE
Cannot start nuxt: cannot find package '<path>\node_modules\table\' imported from <path>\node_modules\@nuxt\nitro\dist\index.mjs

### ISSUE THREAD

**Issue by dochoss** [nuxt/framework#2250]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27306125.af6f91e`
- Package Manager:  `npm@8.1.4`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Fresh project, followed instructions at [Nuxt 3 - Installation](https://v3.nuxtjs.org/getting-started/installation).

npx nuxi init my-app
cd my-app
npm install
npm run dev

### Describe the bug

Project won't start, throws error in title.  This is a fresh project, no updates, no new NPM packages, followed exactly steps in repro.  Not sure what's happening because this worked last night.

ERROR  Cannot start nuxt:  Cannot find package 'C:\my-path\node_modules\table\' imported from C:\my-path\node_modules\@nuxt\nitro\dist\index.mjs

**Comment by pi0** [comment]
Fixed few minutes ago: https://github.com/gajus/table/issues/198 waiting for release :)

**Comment by pi0** [comment]
@dochoss You can get the fix using `npx nuxi upgrade --force`

**Comment by dochoss** [comment]
Thanks for the fast response @pi0 !  I'll do that upgrade operation later today and report back if I have more issues.
