### ISSUE TITLE
$auth object not available in defineNuxtPlugin() context

### ISSUE THREAD

**Issue by sppmstar** [nuxt/framework#2253]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.16.1`
- Nuxt Version:     `2.16.0-27305297.ab1c6cb4`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Webpack`
- User Config:      `alias`, `apollo`, `auth`, `axios`, `bridge`, `build`, `buildModules`, `css`, `head`, `i18n`, `modules`, `plugins`, `proxy`, `publicRuntimeConfig`, `render`, `router`, `server`, `serverMiddleware`, `storybook`, `styleResources`, `telemetry`
- Runtime Modules:  `@nuxtjs/apollo@4.0.1-rc.5`, `@nuxtjs/auth-next@5.0.0-1616003482.75c20e6`, `@nuxtjs/axios@5.13.1`, `@nuxtjs/i18n@7.2.0`, `@nuxtjs/proxy@2.1.0`, `cookie-universal-nuxt@2.1.4`, `nuxt-winston-log@1.2.0`, `portal-vue/nuxt`
- Build Modules:    `@nuxtjs/eslint-module@3.0.2`, `@nuxtjs/stylelint-module@4.0.0`, `@nuxtjs/style-resources@1.0.0`, `@nuxt/bridge@3.0.0-27304790.cad09fe`

### Reproduction

- Install and configure $nuxt/auth plugin
- Create a plugin using the `defineNuxtPlugin` method
- Check the arguments passed to the method

### Describe the bug

It works fine with the old plugin format, such as:

```
export default ({ $auth, $config }) => {
  $auth.options.redirect.login = $config.loginUrl;
  $auth.options.redirect.logout = $config.logoutUrl;
};
```

but `$auth` is somehow not accessible this way:

```
import { defineNuxtPlugin } from "#app";

export default defineNuxtPlugin(({ nuxt2Context }) => {
  const { $config, $auth } = nuxt2Context;
  $auth.options.redirect.login = $config.loginUrl;
  $auth.options.redirect.logout = $config.logoutUrl;
});
```

What is more strange is: if i put a console.log() in `defineNuxtPlugin` for `nuxt2Context` , i do see the `$auth` property on that object, but i get an error about `options of undefined`.

**Comment by SkaJess** [comment]
I have the same issue with auth config.

**Comment by danielroe** [comment]
The error you're getting is probably just TS telling you this object may or may not be defined (here's some [info on why](https://auth.nuxtjs.org/recipes/extend)). Previously this was untyped so you won't have been receiving any type hinting. To resolve, likely just check it exists:

```js
import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin(() => {
  const { $config, $auth } = useNuxtApp()
  if (!$auth) return
  $auth.options.redirect.login = $config.loginUrl
  $auth.options.redirect.logout = $config.logoutUrl
})
```

If that's not the case, just reply with a reproduction and I'll reopen.
