### ISSUE TITLE
useCookies - Unhandled error during execution of setup function

### ISSUE THREAD

**Issue by tguelcan** [nuxt/framework#2255]
### Environment

The [example](https://v3.nuxtjs.org/docs/usage/cookies/) no longer works. 

[Stackblitz](https://stackblitz.com/github/nuxt/framework/tree/main/examples/use-cookie?terminal=dev)

any workaround for that?

### Reproduction

Copy Paste the [example code](https://v3.nuxtjs.org/docs/usage/cookies/)

### Describe the bug

`[Vue warn]: Unhandled error during execution of setup function
  at <Test onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/test" >`

**Comment by danielroe** [comment]
This should be resolved with https://github.com/nuxt/framework/pull/2260
