### ISSUE TITLE
Cannot find module '/app/.output/server/node_modules/subscriptions-transport-ws/dist/message-types' imported from /app/.output/server/chunks/app/server.mjs

### ISSUE THREAD

**Issue by sppmstar** [nuxt/framework#2256]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.16.1`
- Nuxt Version:     `2.16.0-27305297.ab1c6cb4`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Webpack`
- User Config:      `alias`, `apollo`, `auth`, `axios`, `bridge`, `build`, `buildModules`, `css`, `head`, `i18n`, `modules`, `nitro`, `plugins`, `proxy`, `publicRuntimeConfig`, `render`, `router`, `server`, `serverMiddleware`, `storybook`, `styleResources`, `telemetry`
- Runtime Modules:  `@nuxtjs/apollo@4.0.1-rc.5`, `@nuxtjs/auth-next@5.0.0-1616003482.75c20e6`, `@nuxtjs/axios@5.13.1`, `@nuxtjs/i18n@7.2.0`, `@nuxtjs/proxy@2.1.0`, `cookie-universal-nuxt@2.1.4`, `nuxt-winston-log@1.2.0`, `portal-vue/nuxt`
- Build Modules:    `@nuxtjs/eslint-module@3.0.2`, `@nuxtjs/stylelint-module@4.0.0`, `@nuxtjs/style-resources@1.0.0`, `@nuxt/bridge@3.0.0-27304790.cad09fe`

### Reproduction

- build an app using @nuxt/bridge with `nuxi build` command
- run the app with `node .output/server/index.mjs`
- access the app via a web browser at http://localhost:3000/
- check the logs in the terminal

### Describe the bug

I tried using the nitro property for the nuxt config, as such:

```
nitro: {
    preset: "server",
    timing: true,
},
```
But it did not seem to solve it. it seems the app starts fine, but when you access the app in a web browser, you get the 500 error page, and the following error in the terminal:

```
$ node .output/server/index.mjs
> Cold Start (6ms)
Listening on http://localhost:3000
> Load chunks/nitro/static (0ms)
> Load chunks/app/render (0ms)
> Load chunks/app/client.manifest (0ms)
Cannot find module '/Users/sppmstar/work/app/.output/server/node_modules/subscriptions-transport-ws/dist/message-types' imported from /Users/sppmstar/work/app/.output/server/chunks/app/server.mjs
Did you mean to import subscriptions-transport-ws/dist/message-types.js?
  at finalizeResolution (internal/modules/esm/resolve.js:276:11)  
  at moduleResolve (internal/modules/esm/resolve.js:699:10)  
  at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)  
  at Loader.resolve (internal/modules/esm/loader.js:86:40)  
  at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)  
  at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)  
  at link (internal/modules/esm/module_job.js:55:36)
Cannot find module '/Users/sppmstar/work/app/.output/server/node_modules/subscriptions-transport-ws/dist/message-types' imported from /Users/sppmstar/work/app/.output/server/chunks/app/server.mjs
Did you mean to import subscriptions-transport-ws/dist/message-types.js?
  at finalizeResolution (internal/modules/esm/resolve.js:276:11)  
  at moduleResolve (internal/modules/esm/resolve.js:699:10)  
  at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)  
  at Loader.resolve (internal/modules/esm/loader.js:86:40)  
  at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)  
  at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)  
  at link (internal/modules/esm/module_job.js:55:36)
```

The app itself works fine when running it with `nuxi dev`.

**Comment by danielroe** [comment]
[These docs](https://v3.nuxtjs.org/concepts/esm/) may help. Likely try adding that module to your `build.transpile` array.

If that doesn't help, feel free to open a discussion (ideally with a reproduction).

**Comment by Laerolf** [comment]
@sppmstar I have the same issue as described here, what was the solution for you?
At the moment I got this in build.transpile:

['subscriptions-transport-ws']

I have no issue when using nuxi dev but when I want to do a nuxi generate, it fails
