### ISSUE TITLE
'nuxi build' not working

### ISSUE THREAD

**Issue by rocwong** [nuxt/framework#2259]
### Environment

- Operating System: `Darwin` (Mac M1)
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27306529.1ef6e3f`
- Package Manager:  `npm@7.13.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

npx nuxi init nuxt3-app
cd nuxt3-app
npm install
npm run build

### Describe the bug

`npm run dev` is ok

`npm run build`
show this and stop here without error message (wait for several minutes)

<img width="334" alt="QQ20211202-100146@2x" src="https://user-images.githubusercontent.com/728760/144343811-cea6633c-19e0-41fc-ac65-79084832c733.png">

**Comment by JKnorr91** [comment]
Same Issue here on Mac (Big Sur) with Intel i9.
I tried multiple Node Versions from 14 up to 17 with no improvement.

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by JKnorr91** [comment]
As @rocwong mentioned: it is happening in a fresh project directly after dependency install (i used yarn, he used npm) and then running the build command.
I tried to build it with a node docker container. Same issue , but with additional warning output:
` [SSR] Error transforming /projectpath/packages/components/src/components/Headline.vue: Error: The package "esbuild-darwin-64" could not be found, and is needed by esbuild.`
So the Problems seems to be related with esbuild and a global (or local) install of the latest version fixed it in the docker container. On Mac this workaround had no effect.
