### ISSUE TITLE
Generated image urls for files in the public directory result in 404's when running the built server.

### ISSUE THREAD

**Issue by Jos-de-Boss** [nuxt/framework#2261]
#### Local:
------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-27303148.ac98373`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `meta`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
#### Remote (Slightly older version of nuxt but still has the same problem):
------------------------------
- Operating System: `Linux`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-27294839.7e5e50b`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `meta`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

When running the dev server images work fine: https://codesandbox.io/s/nuxt-3-missing-images-dev-2xj0y

However when running the `nuxi build` command and then running `(node) .output/server/index.mjs` all images result in 404s: https://codesandbox.io/s/nuxt-3-missing-images-prod-rvge4

### Describe the bug

When building the server all images urls that reference a file in the public directory get parsed and prefixed with `/_nuxt/`.

So this code (referring to the file `/project/public/images/my-logo.jpg`):
```vue
<img href="/images/my-logo.jpg" />
```
Will be turned into:
```vue
<img href="/_nuxt/images/my-logo.jpg" />
```

It seems ever since version `3.0.0-27296423.f3082ca` these urls have resulted in 404's when running the built server. (The images work fine when running the local development server as this doesn't prefix the urls)

### Additional context

Might be related to:
* #2024
* #2242
* #2135

Personally I find it a little ulgy-looking that the urls of the files I put in my public directory get prefixed with `/_nuxt/`. I would instead expect only my compiled `js` and  `css` to be prefixed like that. Although that's just personal preference to be fair.

**Comment by Jos-de-Boss** [comment]
As mentioned [here](https://github.com/nuxt/framework/issues/2298#issuecomment-987129087) in #2298 this also seems to affect font urls within `@font-face` definitions.

**Comment by kms-rscholz** [comment]
Can confirm, I am running into the same issue with @font-face.

**Comment by thevuong** [comment]
Same issue with me. https://nuxt3-jackroad-miutr38x0-thevuong.vercel.app/

**Comment by DrewLiberty** [comment]
Same https://github.com/nuxt/framework/pull/2262#issuecomment-993376961

**Comment by heychazza** [comment]
Facing this as well..

**Comment by webfansplz** [comment]
Same issue with me...

**Comment by Wharley01** [comment]
Facing same issue

**Comment by webfansplz** [comment]
😂 Waiting the PR to merge.

Maybe this is a high priority, because so many ppl are facing this problem.

**Comment by Wharley01** [comment]
for anyone else facing this issue, you can temporarily roll back to this version: 3.0.0-27272804.ca557e7

run>> npm i nuxt3@3.0.0-27272804.ca557e7

**Comment by heychazza** [comment]
Any update when this will be fixed?

**Comment by Wharley01** [comment]
Any update on this issue?

**Comment by valgeirb** [comment]
This is the only thing preventing me from deploying my site at the moment, is there anything I can do to help with this?

**Comment by Wharley01** [comment]
> This is the only thing preventing me from deploying my site at the moment, is there anything I can do to help with this?

Literally same here,

**Comment by danielroe** [comment]
You should see a PR handling this land this week ☺️

**Comment by Wharley01** [comment]
> You should see a PR handling this land this week ☺️

Hopefully! well done to all the contributors!

**Comment by Wharley01** [comment]
> You should see a PR handling this land this week ☺️

😞

**Comment by Wharley01** [comment]
I have temporary solution to this, change your images from <img src="/bla/bla.jpg"> to <img :src="`/bla/bla`">

**Comment by Jos-de-Boss** [comment]
@danielroe I just checked the fixed version. It looks like it's working again for `img` elements though it isn't working for background-images yet. Is this a known issue?

View this sandbox for updated reproduction: https://codesandbox.io/s/nuxt-3-missing-images-prod-3-0-0-27375427-d07d572-37ri2

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/2777...
