### ISSUE TITLE
Several issues about dependencies (node:*) not found

### ISSUE THREAD

**Issue by azpery** [nuxt/framework#2265]
### Environment

Nuxt CLI v3.0.0-27307420.6a25d3e                                             15:39:57
RootDir: /Users/robindelaporte/Documents/Workspace/tenk                      15:39:57
Nuxt project info:                                                           15:39:57

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.10.0`
- Nuxt Version:     `2.16.0-27306734.ab1c6cb4`
- Package Manager:  `npm@7.24.0`
- Bundler:          `Webpack`
- User Config:      `buildModules`, `$bect`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27307420.6a25d3e`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new             15:39:57

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

I followed the steps to migrate from nuxt 2 to nuxt 3 until this step : https://v3.nuxtjs.org/getting-started/bridge/#update-nuxtconfig 

Then I have dependencies errors with node:http node:https, etc..

### Describe the bug

While building the project I have dependencies errors coming from @nuxt/bridge 

please see the log file attached
[nuxt bug.log](https://github.com/nuxt/framework/files/7642781/nuxt.bug.log)

**Comment by danielroe** [comment]
@azpery Would you provide a reproduction? 🙏

**Comment by azpery** [comment]
Actually no, I only have a private repo to share.. 

While trying to make one, I think it has something to do with a dependency I have coupled with my code. 
Now it's coming from babel : 

 WARN  Compiled with 1 warnings                              friendly-errors 17:21:30


 WARN  in ./node_modules/unplugin-vue2-script-setup/dist/chunk-IEW4T7YP.js

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
                                                             friendly-errors 17:21:30

 ERROR  Failed to compile with 17 errors                     friendly-errors 17:21:30

These dependencies were not found:                           friendly-errors 17:21:30
                                                             friendly-errors 17:21:30
* fs in ./node_modules/@babel/core/lib/transformation/normalize-file.js, ./node_modules/@nodelib/fs.scandir/out/adapters/fs.js and 7 others
* module in ./node_modules/@nuxt/bridge/dist/module.mjs      friendly-errors 17:21:30
* net in ./node_modules/@nuxt/bridge/node_modules/node-fetch/src/utils/referrer.js
* node:http in ./node_modules/@nuxt/bridge/node_modules/node-fetch/src/index.js
* node:https in ./node_modules/@nuxt/bridge/node_modules/node-fetch/src/index.js
* node:stream in ./node_modules/@nuxt/bridge/node_modules/node-fetch/src/index.js
* node:url in ./node_modules/@nuxt/bridge/node_modules/node-fetch/src/request.js
* node:util in ./node_modules/@nuxt/bridge/node_modules/node-fetch/src/body.js
* node:zlib in ./node_modules/@nuxt/bridge/node_modules/node-fetch/src/index.js
                                                             friendly-errors 17:21:30
To install them, you can run: npm install --save fs module net node:http node:https node:stream node:url node:util node:zlib

**Comment by danielroe** [comment]
Are you importing from `@nuxt/bridge` anywhere but `nuxt.config`?

**Comment by chris-gassner** [comment]
I ran into the same issue, in my case it was solved explicitly installing a node-fetch 2.x.x version.
