### ISSUE TITLE
Two Vue runtimes on client

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/framework#2276]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27308177.ab1c6cb4`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Webpack` (not sure why this is reporting webpack, but Vite is activated and used)
- User Config:      `target`, `bridge`, `ssr`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27307420.6a25d3e`

### Reproduction

https://github.com/tobiasdiez/bridge-test

Start with `yarn dev` and then go to the browser console.

### Describe the bug

If `Vue` is imported in a store (in my case this originally happened via pinia) and the composition api is used, then two Vue runtimes are present in the browser (see screenshot below from the browser console).
One is loaded directly from `node_modules/vue/dist` (the one imported via the store) and the other one from a chunk in `node_modules/.cache/vite/client` (the one imported via the composition API).
This duplication of runtimes leads to further problems with some libraries.

![image](https://user-images.githubusercontent.com/5037600/144603365-52d838b5-9745-428a-a7c1-4d817661a1be.png)

**Comment by yassilah** [comment]
Hi, I can confirm I'm having the same issue. The only thing I know is that it must be due to a very recent update of @nuxt/bridge as I was not getting this error until yesterday after updating my lockfile. I'll try to see which version is responsible for this.

**Comment by yassilah** [comment]
It seems the issue goes away when forcing this version of @nuxt/kit in package.json:

```json
"dependencies": {
    "@nuxt/kit": "npm:@nuxt/kit-edge@3.0.0-27304790.cad09fe",
    "@nuxt/kit-edge": "3.0.0-27304790.cad09fe"
}
```
The issue starts with version `3.0.0-27306007.d52acbf`, so I'd assume it's due to this [commit](https://github.com/nuxt/framework/commit/d52acbffd828e399e698f50df66cd0adab2a9796#diff-9188a0edf46974cdac387412afdeac08024b83ebd45b351c7716899ed882355c)?
```

**Comment by tobiasdiez** [comment]
@danielroe @antfu I tried to further investigate this issue and provide a PR fixing it, but I am a bit lost on where to start. Do you have any idea what is triggering the second import? Also which of the two imports is the correct one?

**Comment by tobiasdiez** [comment]
For  me this is now fixed in the latest version. @yassilah if its also working for you now, then we can close this issue.

**Comment by yassilah** [comment]
yeah, it's fixed as well 🙂
