### ISSUE TITLE
Response status code is not 404 but 200 with custom pages/404.vue

### ISSUE THREAD

**Issue by levchak0910** [nuxt/framework#2278]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27265876.3cd4494`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-tpmisr

### Describe the bug

When using a `pages/` directory and navigating to non existent page, result is a default nuxt 404 page and **statusCode = 404**. This is expected
After adding a custom `pages/404.vue` page, the content of the page is returned as expected, **but statusCode = 200** which is not _expected*_

### Additional context

If this behavior by design, how _expected*_ behavior could be achieved?

**Comment by levchak0910** [comment]
One more interesting thing
If forcefully set statusCode to 404, custom `pages/404.vue` is ignored and shown default nuxt 404 page

```javascript
// pages/404.vue
setup() {
    if(process.server) {
      const nuxtApp = useNuxtApp()
      const error = new Error()
      error.statusCode = 404
      nuxtApp.ssrContext.error = error
    }
  },
```

**Comment by danielroe** [comment]
Agreed - let's track this in https://github.com/nuxt/framework/discussions/559.

**Comment by maxdzin** [comment]
@danielroe I'm still getting the same 200 rather than 404. It still not yet corrected or it's required some additional things to make it work?

**Comment by 7ute** [comment]
@maxdzin @levchak0910 This works for me, effectively setting the right status code (nuxt `3.0.0-27338323.1e98259`)
```diff
setup() {
    if (process.server) {
        const nuxtApp = useNuxtApp();
        const error = new Error();
        error.statusCode = 404;
-       nuxtApp.ssrContext.error = error;
+       nuxtApp.ssrContext.nuxt.error = error;
    }
},
```

**Comment by maxdzin** [comment]
> 

@7ute Great, thanks! I thought that it is supposed to return a `404` error automatically. :)
