### ISSUE TITLE
Option to prevent Vite clearScreen on start-up

### ISSUE THREAD

**Issue by peteromano** [nuxt/framework#2281]
### Environment

Nuxt CLI v3.0.0-27307420.6a25d3e                                                                                                                                                                                       22:48:45
RootDir: /srv/codelaunch                                                                                                                                                                                               22:48:46
Nuxt project info:                                                                                                                                                                                                     22:48:46

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.6`
- Nuxt Version:     `3.0.0-27307420.6a25d3e`
- Package Manager:  `unknown`
- Bundler:          `Vite`
- User Config:      `srcDir`, `server`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Run `npm run dev`

### Describe the bug

Vite has a `clearScreen` CLI option which defaults to `true`.

In an attached docker-compose environment, it's quite annoying to have Vite clear the screen on container start-up, if you're looking for logs from other services, or initial container logs before vite starts, etc.

Nuxt should be able to proxy the --clearScreen false CLI option to vite. I suppose something like `nuxi dev --clearScreen false` ?

### Additional context

https://vitejs.dev/config/#clearscreen

**Comment by danielroe** [comment]
You should be able to configure this like so:

```js
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  vite: {
    clearScreen: false
  }
})
```

**Comment by pi0** [comment]
Since nuxi is already doing this, maybe we could turn it to false for vite for more consistent DX.

**Comment by peteromano** [comment]
@danielroe Unless im missing something, that doesn't work (tried it before opening the issue). I think it has to be CLI-level; that's why vite docs mentions only a --clearScreen false flag from the CLI.

@pi0 Nuxi does this? I tried adding to the nuxi command as well before opening the issue, didnt seem to work..

**Comment by peteromano** [comment]
@pi0 Yea, easiest thing is to maybe have nuxt/nuxi just always use clearScreen false for vite; personally, i dont know the huge value of clearing the screen; honestly seems pretty obnoxious to have it on by default; i was thinking of opening an issue with vite instead to default it to false or something. Definitely an oversight for the container folks..

**Comment by pi0** [comment]
nuxi only does it once BTW on startup to avoid confusing with previous startup logs. But totally agree doesn't makes much sense for tty-less output streams. We might suggest same default adjustment for vite too :) 

@peteromano Would you mind sharing a screenshot of current docker-compose output?

**Comment by peteromano** [comment]
Any traction on this?

Should we formally opened a vite PR as well to change the default behavior?

Is this a quick "win", or slightly more involved to resolve?

If @pi0 agrees that maybe nuxt should run vite process with `--clearScreen false`, I can open a PR to do that.

Thoughts?

**Comment by peteromano** [comment]
@pi0 this is REALLY REALLY painful and killing me.... It also seems like it's supposed to already be supported (but not documented): https://github.com/nuxt/framework/blob/2a29c6aa1a9abc2bac7db77b9cf2adf37a2af489/packages/nuxi/src/index.ts#L19

What's the deal with mri args? Nothing works:
nuxi dev no-clear
nuxi dev --no-clear
nuxi dev --clear=false
nuxi dev --clear false
nuxi dev --no-clear --clear false
etc. etc. etc.

How is `args.clear` even `true` by default?

**Comment by peteromano** [comment]
@pi0 and anyone watching:

Until a fix is merged for this, this hack works in your (unix) setup after installing nuxt3:

`$ sed -i 's/\(\\x1b\[0f\)\|\(\\x1b\[2J\)//g' node_modules/nuxi/dist/chunks/index.mjs`

**Comment by OJFord** [comment]
@peteromano `nuxi dev --no-clear` works for me.

Thanks for mentioning it though, `nuxi dev --help` doesn't. (And _does_ clear the screen itself, for help... I know some people like it for continuous stuff like webservers, but that's surely excessive to anyone.)

Now just to find why it messes up ANSI escape sequences somehow on exit.

**Comment by danielroe** [comment]
I'm putting in a PR to fix the `nuxi dev --help` issue, as you're quite right - the original requested behaviour does now work.

Please feel free to open a new issue about the ANSI escape sequences, though 🙏
