### ISSUE TITLE
Devtools: In dev mode getting "Devtools inspection is not available because it's in production mode or explicitly disabled by the author"

### ISSUE THREAD

**Issue by terion-name** [nuxt/framework#2284]
### Environment

Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0-27307420.6a25d3e`
- Package Manager:  `yarn@1.22.4`
- Bundler:          `Vite`
- User Config:      `buildModules`, `dev`, `build`, `intlify`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.1.9`
------------------------------

### Reproduction

n/a

### Describe the bug

Starting nuxt with `yarn dev` or `yarn dev --devtools`, with or without `dev: true` in config, in any case getting from `vue devtools`:

Nuxt.js + Vue.js is detected on this page.
Devtools inspection is not available because it's in production mode or explicitly disabled by the author.

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by terion-name** [comment]
@danielroe What reproduction? It is default behavior of default setup of framework. Just open any project on nuxt3 and click vue devtools chrome extension
5 дек. 2021 г., 14:25 +0200, Daniel Roe ***@***.***>, писал:

**Comment by danielroe** [comment]
@terion-name It shouldn't be the default behaviour. I would guess you're using an old version of the Vue Devtools.

**Comment by terion-name** [comment]
@danielroe 5.3.4, it's latest on chrome store (not beta channel)

One thing that I use it in brave browser, not chrome itself. But it is chromium based and all extensions work fine there. But I'll double check chrome itself

**Comment by danielroe** [comment]
You need the beta version of the devtools for Vue 3 support.

**Comment by terion-name** [comment]
Yeap, in chrome it is the same

**Comment by terion-name** [comment]
> You need the beta version of the devtools for Vue 3 support.

Aaaa, that's the trick. Thank you, I'll try. It's just not mentioned anywhere

**Comment by terion-name** [comment]
@danielroe yes, beta works, thank you. It would be great if this had been written somewhere)

**Comment by metalaureate** [comment]
I have this same problem, but it is not fixed by beta build. I can't get devtools to work on Chrome Version 98.0.4758.80. I am using Vue 3 and I have tried both the latest Beta build and Chrome extension store builds. The Vue extension shows only this message: "Vue.js is detected on this page.
Devtools inspection is not available because it's in production mode or explicitly disabled by the author." 
I am running in development mode.  `vue-cli-service serve`

**Comment by casualmatt** [comment]
Hello, 
I still have the same issue with both [beta ](https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg) and stable version. 

Any advice what could be?

**Comment by T-Zahil** [comment]
Same here

**Comment by ATLANT-Z** [comment]
Same

**Comment by reilnuud** [comment]
same

**Comment by tbb2** [comment]
same here, using esm-browser version
![image](https://user-images.githubusercontent.com/5879301/164711361-849948a9-0397-4c0f-b4fa-d37a9900bbbf.png)

**Comment by krthr** [comment]
Same

**Comment by tobiasdiez** [comment]
It is also not working for me (nuxt3 rc). The vue extension checks `window.__VUE_DEVTOOLS_GLOBAL_HOOK__` which for me yields
```
{
  "devtoolsVersion": "6.0",
  "Vue": null,
  "_buffer": [],
  "store": null,
  "initialState": null,
  "storeModules": null,
  "flushStoreModules": null,
  "apps": []
}
```
For the devtools extension to work, both vue and apps have to be present.

Can this please be reopened?

**Comment by DamianGlowala** [comment]
@danielroe shall we reopen? Having the same issue. Fresh Nuxt project without DevTools working. Are they working for you locally?

**Comment by danielroe** [comment]
@DamianGlowala I can't reproduce this. I think it's more likely a browser issue or a Vue devtools issue rather than a problem with nuxt. Would you test in a fresh Chrome browser profile and ensure you're installing https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?

If you reproduce it, then may I suggest creating a new issue either here or upstream at https://github.com/vuejs/devtools. Feel free to tag me in it and I'll have a look.

**Comment by mlpierce22** [comment]
Not sure if this will help anybody, but I my issue was the `build.transpile`  option. I need this for prod builds, not development, so I just changed it to the following and it seems to work for now:
```
  build: {
    transpile: process.env.NODE_ENV === "development" ? [] : ["element-plus"],
  },
```
After playing around a little while, I think that this is either an uncaught error or a race condition of some kind. I can reproduce it consistently by putting an incorrect css path into the nuxt config (devtools not found, but no errors thrown).

Using devtools v6.1.4
Repro: https://stackblitz.com/edit/github-b6sebj?file=nuxt.config.ts&view=editor

**Comment by steel89ita** [comment]
> 

The last part fixed my issue.
In my case the problem was that I defined a css file in the nuxt.config.ts, but was not present in the assets directory.
Adding the file back solved the issue and now the Vue tab is showing as expected.

**Comment by upepo-mwindaji** [comment]
If you are experiencing this issue on a cloud VM dev environment (e.g. Codespace), try updating your vite config as per #6096

**Comment by qiwang97** [comment]
> https://stackblitz.com/edit/github-b6sebj?file=nuxt.config.ts&view=editor

sorry but vue devtool is still not working.
nuxt 3.0.0-rc.8
vue-devtool 6.2.1

**Comment by danielroe** [comment]
Please see https://github.com/nuxt/framework/issues/2284#issuecomment-1132160740.
