### ISSUE TITLE
Changing child routes will rerender parent

### ISSUE THREAD

**Issue by thomasowow** [nuxt/framework#2309]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27304790.cad09fe`
- Package Manager:  `yarn@1.19.2`
- Bundler:          `Vite`
- User Config:      `build`, `components`, `css`, `publicRuntimeConfig`, `srcDir`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Watch console logging setup whenever the route is changing to child route and back.

https://codesandbox.io/s/relaxed-grothendieck-dvsjz

### Describe the bug

As seen in the reproduction the parent of child routes is rendered every time the route changes. This could lead to a lot of unnecessary overhead in the parent.

I suspect both [`Page.vue`](https://github.com/nuxt/framework/blob/694e95b2b436d23a492d207a894801f7e58b6cbb/packages/nuxt3/src/pages/runtime/page.vue) and [`Child.vue`](https://github.com/nuxt/framework/blob/694e95b2b436d23a492d207a894801f7e58b6cbb/packages/nuxt3/src/pages/runtime/child.vue) to be the cause. Both of them are applying a `:key="$route.path"` to its dynamic component. Removal of this would solve this problem immidiately (tested this).

What would have been the reason to apply this `:key="$route.path"`? Would a PR that removes this code be rejected?

**Comment by Harkonnen13** [comment]
Ye i noticed this before. Thats wierd behavior, using same route.path key for every view. In normal case, it should replace only child component, not everything including parent. 
For example, if my parent view has menu with some local state (open/close), it will be lost.

**Comment by Atinux** [comment]
The CodeSandBox does not work for me, I duplicated on StackBlitz: https://stackblitz.com/edit/nuxt-starter-7eeck7?file=pages%2Findex.vue

**Comment by thomasowow** [comment]
> The CodeSandBox does not work for me, I duplicated on StackBlitz: https://stackblitz.com/edit/nuxt-starter-7eeck7?file=pages%2Findex.vue

Shouldn't we remove the `app.vue`?

**Comment by Atinux** [comment]
Should be good
