### ISSUE TITLE
The watch function always returns value and oldValue the same

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#2311]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27313139.1c88580`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `css`, `watch`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```
const banners = ref([])

watch(
    banners,
    async (value, oldValue) => {
      let eventName
      console.log(value.length, oldValue.length)
      console.dir(value)
      console.dir(oldValue)
      if (value.length > oldValue.length) eventName = 'add'
      if (value.length === oldValue.length) eventName = 'change'
      if (value.length < oldValue.length) eventName = 'delete'
      console.log(eventName)
      // ToDo: get add/change/delete items
    },
    {deep: true}
)
```

![Screenshot 2021-12-07 at 16 27 10](https://user-images.githubusercontent.com/13822438/145057636-f10919f8-8a04-4612-9427-67e75a1a41c9.png)

### Describe the bug

The watch function is returning the same for value and oldValue.

**Comment by danielroe** [comment]
Yes, it's returning the same object, which is the expected behaviour. (Vue doesn't clone/snapshot an object or array in this context.)

**Comment by frbuceta** [comment]
> Yes, it's returning the same object, which is the expected behaviour. (Vue doesn't clone/snapshot an object or array in this context.)

Is it by using composition api or by using Nuxt?

**Comment by danielroe** [comment]
@frbuceta If I understand the question, this is not related to Nuxt. You should experience the same behaviour in any Vue 3 project.

**Comment by frbuceta** [comment]
> @frbuceta If I understand the question, this is not related to Nuxt. You should experience the same behaviour in any Vue 3 project.

I've already gotten it to work. You can see how I have done it.
```js
import _ from 'lodash'
const banners = reactive([])

watch(
    () => _.cloneDeep(banners),
    async (value, oldValue) => {
      let eventName
      if (value.length > oldValue.length) eventName = 'add'
      if (value.length === oldValue.length) eventName = 'change'
      if (value.length < oldValue.length) eventName = 'delete'
      console.log(eventName)
      // ToDo: get add/change/delete items
    },
    {deep: true}
)
```
