### ISSUE TITLE
Trying configure reouter.scrollBehavior

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#2330]
### Environment

Nuxt CLI v3.0.0-27313139.1c88580                                                                                                                                            21:40:20  
RootDir: C:\Users\SuPP\Documents\Code\santrek-review                                                                                                                        21:40:25
Nuxt project info:                                                                                                                                                          21:40:25

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27313139.1c88580`
- Package Manager:  `npm@8.1.4`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `modern`, `ssr`, `css`, `build`, `meta`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[Play Demo](https://codesandbox.io/s/morning-water-towh1?file=/plugins/router.scrollBehavior.js)

### Describe the bug

Cant configure router.scrollBehavior for navigate on the page.

**Comment by lucpotage** [comment]
I have the same issue and likes the possibility to define scrollBehavior in Nuxt config. I also have a reproduction link: https://stackblitz.com/edit/github-dkvrep?file=nuxt.config.ts

**Comment by mihail727** [comment]
> I have the same issue and liked the possibility to define scrollBehavior in Nuxt config in Nuxt 2. I also have a reproduction link: https://stackblitz.com/edit/github-dkvrep?file=nuxt.config.ts

Thanks for commen. But I'm trying to scroll on the current page... not go to a new page....

**Comment by lucpotage** [comment]
> Thanks for commen. But I'm trying to scroll on the current page... not go to a new page....

I know, whatever the desired outcome, it implies overriding the default `scrollBehavior`.

**Comment by lucpotage** [comment]
The plugin approach worked for me. Sorry for the noise.
https://github.com/nuxt/framework/issues/1707

**Comment by lucpotage** [comment]
At least, I found a solution to your problem. Try the following:

```js
if (to.hash) {
  return {
    el: to.hash,
  }
}
```

Option `selector` was replaced by `el` in v4.

Working example: https://codesandbox.io/s/polished-waterfall-4fs85?file=/plugins/router.scrollBehavior.js

**Comment by mihail727** [comment]
> At least, I found a solution to your problem. Try the following:
> 
> ```js
> if (to.hash) {
>   return {
>     el: to.hash,
>   }
> }
> ```
> 
> Option `selector` was replaced by `el` in v4.
> 
> Working example: https://codesandbox.io/s/polished-waterfall-4fs85?file=/plugins/router.scrollBehavior.js

Thank you very much.... its work for me!
Here is my final solution:
`./plugin/router.scrollBehavior.js`
```
import { defineNuxtPlugin } from '#app';

export default defineNuxtPlugin((nuxtApp) => {
	nuxtApp.$router.options.scrollBehavior = (to, from, savedPosition) => {
		if (to.hash) {
			return {
				el: to.hash,
				behavior: 'smooth',
			};
		}
	};
});
```
