### ISSUE TITLE
Trying to use Suspense

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#2331]
### Environment

Nuxt CLI v3.0.0-27313139.1c88580                                                                                                                                               22:30:08
RootDir: C:\Users\SuPP\Documents\Code\santrek-review\components\Assortment                                                                                                     22:30:10
Nuxt project info:                                                                                                                                                             22:30:10

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27313139.1c88580`
- Package Manager:  `npm@8.1.4`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[Play Demo](https://codesandbox.io/s/reverent-mendel-17x4j?file=/pages/index.vue)

### Describe the bug

Suspense works only with `<ClientOnly>`.

**Comment by danielroe** [comment]
Note that pages need to render a single root node. Apart from that, the sandbox seems to be working fine.

The `<Suspense>` docs may be helpful: [vue 3 docs](https://v3.vuejs.org/guide/migration/suspense.html#suspense).

**Comment by mihail727** [comment]
@danielroe Please write some example..... i read this document but to no avail

**Comment by danielroe** [comment]
@mihail727 I'd suggest creating a GitHub Discussion and explaining a bit about what you're attempting.

**Comment by mihail727** [comment]
@danielroe please check this
