### ISSUE TITLE
nitro/lambda: Redirect (301) using middleware throwing server errors

### ISSUE THREAD

**Issue by volkipp** [nuxt/framework#2335]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27315376.ab1c6cb4`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `ssr`, `nitro`, `target`, `head`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `styleResources`, `server`, `plugins`, `components`, `buildModules`, `modules`, `build`
- Build Modules:    `nuxt-windicss@2.0.15`, `@nuxtjs/style-resources@1.2.1`, `@nuxt/bridge@3.0.0-27313139.1c88580`
------------------------------

### Reproduction

Minimal reproduction repo here: https://codesandbox.io/s/angry-dubinsky-uivit

- Download the package
- Run `yarn build`
- Run `node ./test-handler.mjs`

An error will be thrown: 
> Error
> Cannot read property 'toString' of undefined

Changing the path in /test-handler.mjs to any other path will not throw an error and provide an appropriate status code.

### Describe the bug

When running in a lambda environment, hitting the route which causes the redirect will display "Internal Server Error" on the page.

This error happens when using server middleware as well as anonymous middleware when there is no response body because of a redirect. The bug appears to be in unjs/unenv. This pull request appears to fix the problem: https://github.com/unjs/unenv/pull/22

**Comment by alexblunck** [comment]
Same error occurs when using server middleware in Nuxt 3 (`3.0.0-27319101.3e82f0f`).

Example:
`server/middlware/redirect.js`
```js
export default async (req, res) => {
    res.writeHead(302, { Location: '/some/path' })
    res.end()
  }
}
```

A temporary workaround that seems to work is passing data into the `res.end` function: 
```js
res.end('some string')
```

**Comment by danielroe** [comment]
@volkipp Would you confirm whether this is fixed after upgrading to use the latest version of `unenv`?

**Comment by alexblunck** [comment]
@danielroe I know you're not asking me, but latest Nuxt 3 version (3.0.0-27324955.23397e6) fixes the issue for me

**Comment by danielroe** [comment]
Thanks for checking! 😊
