### ISSUE TITLE
VITE  SyntaxError @babel does not provide an export named 'default'

### ISSUE THREAD

**Issue by andysay** [nuxt/framework#2336]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27313139.1c88580`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.6`
------------------------------

### Reproduction

if vite:false, work fine.
https://codesandbox.io/s/nervous-mcclintock-yxht0?file=/pages/index.vue

### Describe the bug

bug only on DEV state !!!

SyntaxError: The requested module '/_nuxt/node_modules/@babel/runtime/regenerator/index.js?v=0d9ba971' does not provide an export named 'default'

**Comment by danielroe** [comment]
Would you provide a reproduction please? 🙏

**Comment by andysay** [comment]
> Would you provide a reproduction please? 🙏

https://codesandbox.io/s/nervous-mcclintock-yxht0?file=/pages/index.vue
