### ISSUE TITLE
useMeta removes existing tags and then adds them all again

### ISSUE THREAD

**Issue by nndnha** [nuxt/framework#2337]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3-3.0.0-27237303.6acfdcd`
- Package Manager:  `npm`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-jmj87r?file=app.vue

https://user-images.githubusercontent.com/12961516/145565306-7df3339a-3a11-4268-ab07-cc0fb9240d24.mp4

### Describe the bug

The body's background color is set to `#000` in the `style` tag when the page has loaded, when client hydrated that `style` is removed firstly then added again, this makes the screen flickering.

I added an extra script that uses `MutationObserver` to logs the add/remove element events. It shows that the `style` element is removed firstly then added again.  I think `useMeta` shouldn't touch these existing tags.

**Comment by danielroe** [comment]
Resolved with the latest version of `@vueuse/head`.
