### ISSUE TITLE
Nuxt3 `<NuxtLink>` error when the page component has no root html tag

### ISSUE THREAD

**Issue by maoweifan** [nuxt/framework#2358]
### Environment

Nuxt CLI v3.0.0-27313139.1c88580 
- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-27313139.1c88580`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

none，Very easy to reproduce

### Describe the bug

In vue3, `<template>` can have no root html tag, but in nuxt3, if the component (page) does not have a root html expression, using `<NuxtLink>` to will cause the page to be blank.
My guess is that if there is no root html tag on the component under pages, the route will not be registered, but when refreshing, you can see the page, indicating that the route has indeed been registered, and the page will only be displayed in the case of `<NuxtLink>` to blank.

**Comment by maoweifan** [comment]
When using `useRouter`, the `push` method is the same, the page is blank

**Comment by maoweifan** [comment]
Narrow the scope, even if the target page component has an html root tag, it will not work. Once the component where `<NuxtLink>` has no html root tag, the problem will reproduce, and the same is true for `useRouter`

**Comment by danielroe** [comment]
Pages need to have a single root element.
