### ISSUE TITLE
comment breaks router on dev

### ISSUE THREAD

**Issue by lookis** [nuxt/framework#2361]
### Environment

Nuxt project info:                          

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27319101.3e82f0f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction
```shell
npx nuxi init buggy
cd buggy
yarn
rm app.vue
mkdir pages
```

touch pages/index.vue:
```vue
<template>
  <div>
    <NuxtLink to="/helloworld"> HelloWorld </NuxtLink>
  </div>
</template>
```

touch pages/helloworld.vue
```vue
<template>
  <!-- comment breaks -->
  <div>
    <NuxtLink to="/"> Index </NuxtLink>
  </div>
</template>
```

start server with ```yarn dev```

### Describe the bug

It should just works fine

**Comment by danielroe** [comment]
You need to have one root element for a page, and the comment 'counts' as an element.
