### ISSUE TITLE
Error: Parse failure: Identifier 'ssrRegisterHelper' has already been declared

### ISSUE THREAD

**Issue by cdwmhcc** [nuxt/framework#2364]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27307420.6a25d3e`
- Package Manager:  `yarn@1.22.4`
- Bundler:          `Vite`
- User Config:      `meta`, `loading`, `privateRuntimeConfig`, `publicRuntimeConfig`, `alias`, `modules`, `css`, `buildModules`, `vue`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `v-tooltip/nuxt`, `@pinia/nuxt@0.1.6`, `nuxt-windicss@2.0.12`

### Reproduction

/components/badge.tsx

```
import {
    defineComponent,
} from 'vue';

export default defineComponent({
    setup(props, { emit, attrs, slots }) {
        return () => {
        };
    },
});
```

/pages/index.vue

```
<template>
  <Badge>test</Badge>
</template>
```

### Describe the bug

```
 WARN  [SSR] Error transforming D:/Work/nuxt-3/components/badge.tsx: Error: Parse failure: Identifier 'ssrRegisterHelper' has already been declared (18:9)                                                                                                       10:27:08
Contents of line 18: import { ssrRegisterHelper } from "/__vue-jsx-ssr-register-helper"

[Vue warn]: Invalid vnode type when creating vnode: undefined.
Invalid value used as weak map key
  at WeakMap.set (<anonymous>)
```

**Comment by danielroe** [comment]
I can't reproduce this with the code you've given. Would you provide a reproduction please? 🙏

**Comment by cdwmhcc** [comment]
> I can't reproduce this with the code you've given. Would you provide a reproduction please? 🙏

After investigation, it was because I accidentally created an extra file in the root directory.

Sorry, the reason is my mistake.
