### ISSUE TITLE
"express is not a function", when using express in server middleware

### ISSUE THREAD

**Issue by HendrikJan** [nuxt/framework#2367]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27322574.c1d02ea3`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Webpack`
- User Config:      `srcDir`, `head`, `publicRuntimeConfig`, `css`, `plugins`, `components`, `buildModules`, `vuetify`, `i18n`, `modules`, `axios`, `compilerOptions`, `build`, `watchers`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `pinia/nuxt`, `@nuxtjs/vuetify@1.12.3`, `@nuxtjs/i18n@7.2.0`, `@nuxt/bridge@3.0.0-27319101.3e82f0f`
------------------------------

### Reproduction

https://codesandbox.io/s/nostalgic-waterfall-zb1pt?file=/package.json

Restart the server if needed.
Get the error:

ERROR [worker] express is not a function

### Describe the bug

When trying to start a server with express in /server/middleware, I get the error.

### Additional context

I try to move from @nuxt/composition-api to @nuxt/bridge.

My old setup used this piece of code (running nuxt as a middleware of express): 
```javascript
  const nuxt = await loadNuxt(isDev ? 'dev' : 'start');
  app.use(nuxt.render);
```

According to this remark: https://github.com/nuxt/framework/discussions/1451#discussioncomment-1548835 the best way to get the server working again is to run my express server as a middleware of nuxt). That is what I am trying to do.

**Comment by danielroe** [comment]
You should use `import` rather than `require`. More info [here](https://v3.nuxtjs.org/concepts/esm/).

This should work fine:

```js
import express from "express"
const app = express()

// register your routes ...

export default app
```
