### ISSUE TITLE
transition-group has no class or data attribute

### ISSUE THREAD

**Issue by xxSkyy** [nuxt/framework#2370]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27319101.3e82f0f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/nuxt3-ssr-broken-transition-group-99h1q

### Describe the bug

transition-group with `tag` don't have classes, also it don't includes data-element, classes and data attribute only shows after changing transition-group property on hot reload but after refresh or in build-start it doesn't work 

![obraz](https://user-images.githubusercontent.com/16470866/145859718-52ab9762-8ff3-4b2b-a516-942bbfab7dc9.png)

**Comment by olivervorasai** [comment]
This bug is still present as of `3.0.0-27376999.6abf75d` (latest on Jan 20, 2022)

https://codesandbox.io/s/nuxt3-transition-group-no-classes-bug-rlu7m?file=/app.vue

**Comment by danielroe** [comment]
Would you raise it as an issue in the Vue repo? https://github.com/vuejs/core/issues

**Comment by xxSkyy** [comment]
It is since long time and has open PR request.
https://github.com/vuejs/core/issues/5141

**Comment by danielroe** [comment]
Perfect. Thank you ❤️

**Comment by mctweb** [comment]
This issue is still present.

```
<transition-group name="list" tag="ul" >
      <li v-for="item in sortedList" :key="item.uid">
          {{item}}
       </li>
</transition-group>
````
`.list-move{
transition: all 1s;
}`

The list displays correctly, however the class isn't applied upon changing the order of the list. As such the transition doesn't work.
I've tried wrapping with `<ClientOnly>`  however this makes no difference.

Regular `<Transition>` tags are working ok.

There has been no movement upstream in https://github.com/vuejs/core/issues/5141

**Comment by xxSkyy** [comment]
Fixed in https://github.com/vuejs/core/commit/aed10c507279900f8afc4861dc01ca4f2b95acb8
Checked in [codesandbox](https://codesandbox.io/s/nuxt3-ssr-broken-transition-group-99h1q) on latest Nuxt3 and it's working as it should.
