### ISSUE TITLE
allow adding scripts within `<body>`

### ISSUE THREAD

**Issue by dev23jjl** [nuxt/framework#2374]
### Environment

**Nuxt CLI v3.0.0-27319101.3e82f0f**

Nuxt project info:

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27313139.1c88580`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `head`, `meta`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.0.15`
------------------------------

#### First Bug/Issue Link:
[body: true not working](https://codesandbox.io/s/script-link-error-2gpsk)

#### Second Bug/Issue Link:
[linking script globally not working](https://codesandbox.io/s/script-link-error-global-j3gfj)

### Using "body: true" when linking a script will not insert the script into the body

I have a project in which I have a script that runs to get various items from the DOM in order to add an event listener that triggers audio to play. The only problem is that the script loads before the DOM loads because it is located in the head. In Nuxt 2, the body: true part when linking a script positioned the script in the body. However, Nuxt 3 does not seem to be allowing this. My project still works... as of this point, but when I was creating the Codesandbox project that I made to reproduce the issue, it wouldn't even trigger the function. It returns the item as being "null" because the item is nonexistent when the script loads. Am I linking it correctly? I would think not because it worked with Nuxt 2. Is it different in Nuxt 3 now?

### I cannot link the script globally

I've tried doing multiple things globally, as this, which may just be the fact that Nuxt 3 is still undergoing development, but I just wanted to bring this up to make sure that it was known about. I have the script linked in the `nuxt.config.ts` file. However, when I open the dev tools to check the head to see if the script is linked, it's not there and obviously, nothing works then. I've also tried globally declaring the title (would be useful for the project that I am working on now, but generally, probably not) and it won't work. Declaring it per page works fine (in between the Vue document <script> tags), just not globally per the `nuxt.config.ts`.

### Logs

```shell
//Logs from body:true bug

Uncaught TypeError: el is null
    <anonymous> https://2gpsk.sse.codesandbox.io/script.js:10
script.js:10:1

[vite] connecting... client.ts:22:8

<Suspense> is an experimental feature and its API will likely change. runtime-core.esm-bundler.js:897:47

Uncaught TypeError: newEl.textContent is not a function
    myFunction https://2gpsk.sse.codesandbox.io/script.js:3
    EventListener.handleEvent* https://2gpsk.sse.codesandbox.io/script.js:10
script.js:3:9

​
```

**Comment by danielroe** [comment]
For global script insertion, you use `meta` key in `nuxt.config`:

```js
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  meta: {
    script: [{ src: "script.js" }],
  },
})
```

Currently, Nuxt 3 doesn't support adding scripts anywhere but in `<head>`, so let's keep this open as a feature-request.

**Comment by 23johanningmeierjl** [comment]
Thanks! I didn't realize that I was linking it wrong using the global method. Also, I'm happy that I'll be able to insert scripts into the body (instead of the head) in the future! I have to say that I enjoy Nuxt 3 even better than Nuxt 2, and I enjoy Nuxt (in general) better than using plain, old HTML. I'm finding that I can do so much more with Nuxt without having to know my computer inside out. Thanks to Nuxt, I find that I enjoy coding more (and would like to do it more often, even though I don't always have time). Now that I started using the framework, I honestly couldn't say that I would use anything else.

**Comment by 23johanningmeierjl** [comment]
Just wanted to say, I found that you can also use an event listener to wait until the DOM loads, like this:
 
`document.addEventListener("DOMContentLoaded", myFunction);`

That got rid of all the errors in the console on my project, therefore, this will work for the current moment as a temporary workaround.

**Comment by harlan-zw** [comment]
This is now supported in the latest nuxt v3 fyi, https://github.com/nuxt/framework/issues/5014#issuecomment-1200140609 & https://github.com/vueuse/head/pull/67

```
useHead({
  script: [
    {
      children: `console.log('Hello world!')`,
      body: true
    },
  ],
})
```

**Comment by bmlyon** [comment]
> 

Could you please provide more context for your code example? What part of what file would I put that in? That looks like something I could put in a layout file in the script section under export default, but I tried that and it didn't work. I also tried adding it to the nuxt config.
