### ISSUE TITLE
Blob support

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#2378]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27319101.3e82f0f`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `css`, `watch`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/fetch-blob-error-5nq1h

### Describe the bug

Nuxt is not able to return Blobs.

### Additional context

See unjs/unenv#23 and unjs/ohmyfetch#38

**Comment by danielroe** [comment]
See https://github.com/unjs/ohmyfetch/issues/38#issuecomment-993638306 - the only issue you'll experience when you implement my change is that Blobs can't be stringified (converted to text on SSR and re-converted back to text when hydrating HTML). (But I don't think that was your use case.)

**Comment by pi0** [comment]
Shall we close this?

**Comment by pi0** [comment]
Let's track unenv issue via https://github.com/unjs/unenv/issues/23 this is not a nuxt issue anymore.

(please ping to reopen if you think there is something relevant we can do in nuxt)
