### ISSUE TITLE
Cannot start nuxt:  No "exports" main defined in `@nuxt/kit` when using defineNuxtModule

### ISSUE THREAD

**Issue by victorgarciaesgi** [nuxt/framework#2397]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27324955.23397e6`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `modules`, `typedRouter`
- Runtime Modules:  `nuxt-typed-router@1.0.0-alpha-8`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/charming-glade-mkeg3?file=/nuxt.config.ts

### Describe the bug

I'm rewriting one of my Nuxt module (nuxt-typed-router) to be compatible with Nuxt 3. I'm using `@nuxt/kit` and `defineNuxtModule`. And when I test it on an app, I always got this error:

![image](https://user-images.githubusercontent.com/15092120/146158000-60d9b7c7-a4a4-4be7-bf04-6a556052b93d.png)

The code for the module is here: https://github.com/victorgarciaesgi/nuxt-typed-router/tree/next.

I've setup my tsconfig with esnext output, maybe it should be different? I struggled to find docs on `@nuxt/kit`

### Logs

```shell
ERROR  Cannot restart nuxt:  No "exports" main defined in /sandbox/node_modules/nuxt-typed-router/node_modules/@nuxt/kit/package.json

  at new NodeError (internal/errors.js:322:7)
  at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)
  at packageExportsResolve (internal/modules/esm/resolve.js:511:7)
  at resolveExports (internal/modules/cjs/loader.js:450:36)
  at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
  at Function.resolve (internal/modules/cjs/helpers.js:99:19)
  at p (node_modules/jiti/dist/jiti.js:1:52925)
  at g (node_modules/jiti/dist/jiti.js:1:54200)
  at node_modules/nuxt-typed-router/lib/module.js:1:174
```

**Comment by danielroe** [comment]
@victorgarciaesgi A few comments:

* Your module isn't importable in Node - it's ESM but with `.js` extension. See https://v3.nuxtjs.org/concepts/esm/ for more info. There's also no `module` or `exports` field: https://github.com/victorgarciaesgi/nuxt-typed-router/blob/next/package.json
* The default import of your package is './lib/module.js' but you're importing `useTypedRouter` from `nuxt-typed-router`. That's not exported from `lib/module` so it won't work. See https://codesandbox.io/s/practical-aryabhata-n1cbc?file=/pages/index.vue.

Having said that, we plan to release a module builder and some guidance for creating modules for Nuxt 3 that should resolve these issues for you. I'm closing this issue for now, but please feel free to follow up with a discussion once we release the module author guide.

**Comment by victorgarciaesgi** [comment]
Thanks @danielroe for the answer! Sorry if it was a dumb question!
I didn't find any info or exemples on Nuxt 3 modules appart from the migration to `@nuxt/kit`.
(Btw I fixed my error by importing from `@nuxt/kit-edge`)

The problem with the `.js` extension is that Typescript `tsc` doesn't support generating `.mjs`. Do I have to use Rollup or something?

**Comment by danielroe** [comment]
@victorgarciaesgi [`unbuild`](https://github.com/unjs/unbuild) should solve that - but I'd recommend waiting for the Nuxt module builder 🙃

**Comment by victorgarciaesgi** [comment]
Yeah I'm trying `unbuild` right now! I'm was looking at how `@pinia/nuxt` was doing to output mjs :) 
I cannot wait for it then! I'm already experimenting on it :)
