### ISSUE TITLE
How to use vuex in nuxt3?

### ISSUE THREAD

**Issue by xyzz0121** [nuxt/framework#2407]
### Environment

vue3
vite

### Reproduction

How to use vuex in nuxt3?

### Describe the bug

How to use vuex in nuxt3 (vue3, vite)?

**Comment by danielroe** [comment]
Feel free to create a discussion.

**Comment by richardeschloss** [comment]
Please re-open this. it's a bug. Nuxt3 can register namespaced stores ok, but intermittently fails to register the root store.

**Comment by danielroe** [comment]
@richardeschloss Thanks for reporting that. It's a different issue from this one though. Any chance you could create an issue?
