### ISSUE TITLE
Route problem with nuxt3 

### ISSUE THREAD

**Issue by hermesalvesbr** [nuxt/framework#2418]
### Environment

npx nuxi info
Nuxt CLI v3.0.0-27324955.23397e6                                                                                                                                                                                 11:58:15
RootDir: /Users/hermes/www/nuxt/escolar-digital                                                                                                                                                                  11:58:19
Nuxt project info:                                                                                                                                                                                               11:58:19

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27324955.23397e6`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `ssr`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                                                                 11:58:19

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

Just the yarn dev and the route problem appear.  I have create the repository to show the bug https://github.com/hermesalvesbr/Primeblocks-Nuxt3-Primevue 

The page didn't open and show the router problem. We discuss about this in primevue discord chat. https://discord.com/channels/787967399105134612/873204279031242752/920934863157223484 

### Describe the bug

Cannot read properties of undefined (reading '__vccOpts')
at ./node_modules/vue-router/dist/vue-router.cjs.js:2022:55

### Additional context

I'm trying to use NUXT3 with primevue.

**Comment by danielroe** [comment]
The issue is the same as https://github.com/nuxt/framework/issues/1885, though the error message is obscured (fix incoming in https://github.com/nuxt/framework/pull/2420).
