### ISSUE TITLE
useFetch and useAsyncData can't works in event

### ISSUE THREAD

**Issue by liuqian1996** [nuxt/framework#2436]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.17.6`
- Nuxt Version:     `3.0.0-27328916.daec432`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `css`, `buildModules`, `vite`, `unocss`
- Runtime Modules:  `-`
- Build Modules:    `@unocss/nuxt@^0.16.4`, `@vueuse/nuxt@7.3.0`

### Reproduction

**index.vue**
```vue
<script setup lang="ts">
const onTestClick = async () => {
  const { data } = await useFetch('/api/time')
  console.log(data.value)
}
</script>

<template>
<button @click="onTestClick">Click</button>
</template>
```

**server/api/time.ts**
```ts
export default () => {
  const time = new Date().toLocaleTimeString();
  return { time };
};
```

### Describe the bug

click button has no effect, `data.value` loged **null** on console

**Comment by liuqian1996** [comment]
[codesandbox](https://codesandbox.io/s/cool-sea-vb7kc?file=/app.vue) only used in top? it seems to correctly yestoday

**Comment by danielroe** [comment]
Yes, they should be called within the setup function or a plugin, not in an event handler. You call them then, and you can use the reference you get back within the event handler.
