### ISSUE TITLE
yarn build not creating index.html

### ISSUE THREAD

**Issue by olivinesguerra** [nuxt/framework#2438]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v17.2.0`
- Nuxt Version:     `3.0.0-27328916.daec432`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `ssr`, `target`, `css`, `modern`, `features`, `build`, `typescript`, `dev`, `debug`, `head`, `plugins`, `buildModules`, `publicRuntimeConfig`, `privateRuntimeConfig`, `modules`, `buildDir`, `nitro`, `appTemplatePath`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `@pinia/nuxt@0.1.6`
------------------------------

### Reproduction

Just run yarn build.

### Describe the bug

I'm trying to deploy a nuxt3 project on cloudfront. It uses a standalone app(not SSR). But the problem is the dist folder is not generating index.html for deploying it only has manifest.json.

### Additional context
 Config:
import { defineNuxtConfig } from "nuxt3";
import { resolve } from "path";

export default defineNuxtConfig({
  ssr: false,
  target: "static",
  css: ["@/assets/tailwind.scss"],
  modern: "client",
  features: {
    componentClientOnly: true,
  },
  build: {
    parallel: true,
    standalone: true,
    postcss: {
      postcssOptions: {
        plugins: {
          tailwindcss: {},
          autoprefixer: {},
        },
      },
    },
  },
  typescript: {
    strict: true,
  },
  dev: false,
  debug: false,
  head: {
    title: "Seahawk",
    htmlAttrs: {
      lang: "en",
    },
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1.0" },
      { hid: "description", name: "description", content: "" },
      { name: "format-detection", content: "telephone=no" },
    ],
    link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }],
  },
  plugins: [],
  buildModules: ["@pinia/nuxt"],
  publicRuntimeConfig: {
    axios: {
      baseURL: process.env.API_URL || "",
      proxyHeaders: false,
    },
    BASE_URL: process.env.API_URL || "",
    DEFAULT_TIMEZONE: "",
    ENV: process.env.ENV || "",
  },
  privateRuntimeConfig: {},
  modules: [["@nuxtjs/axios", { proxyHeaders: false }]],
  buildDir: "build",
  nitro: {
    preset: "browser",
  },
});

**Comment by olivinesguerra** [comment]
any workaround is pretty much appreciated. Thanks

**Comment by danielroe** [comment]
At the moment `nuxi build` creates a server rather than HTML files, even if you have set `ssr: false` (all this means is that the server will serve a page with a shell rather than server-rendering all the HTML).

For the moment, if you need to produce HTML, I would recommend using `@nuxt/bridge` with Nuxt 2. 

But don't worry, this is high on our priority list. The discussion to follow is https://github.com/nuxt/framework/discussions/560.

**Comment by olivinesguerra** [comment]
hi @danielroe . Any tentative date on generating static html? Thanks
