### ISSUE TITLE
Cloudflare CDN Service (Apps Option) Causes Rendering Twice

### ISSUE THREAD

**Issue by sefacndmr01** [nuxt/framework#2439]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27324955.23397e6`
- Package Manager:  `npm@7.14.0`
- Bundler:          `Vite`
- User Config:      `nitro`, `app`, `build`, `privateRuntimeConfig`, `alias`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Can't reproduct.

### Describe the bug

When cloudflare cdn service has apps option on, nuxt renders page twice even no apps on open. To solve this problem I need to the add page rules and close apps option.

### Additional context

I think this is caused by the javascript files that cloudflare adds. 

### Logs

```shell
No log
```

**Comment by danielroe** [comment]
It sounds like a hydration issue caused by Cloudflare changing the server rendered HTML so that it can't be matched up to what the client side Vue wants to render.

There may be some things you can do on Cloudflare's end to change this, but it's not a bug with Nuxt or Vue.
