### ISSUE TITLE
`useRoute` is not updated after initially being set

### ISSUE THREAD

**Issue by Diizzayy** [nuxt/framework#2441]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.2`
- Nuxt Version:     `3.0.0-27328916.daec432`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `meta`, `css`, `buildModules`, `unocss`, `vite`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@7.4.0`, `@unocss/nuxt@0.16.4`

### Reproduction

Reproduction simply requires multiple (`/a and /b` ) routes to be created in the `pages` directory.

navigate to `/a` then check useRoute().path, it's value will be `/a` as expected

however though, upon navigating to `/b` then checking useRoute().path. You'll notice that the current route instance has not been updated and still reflects the route that was initially navigated to, ie: `/a`

### Describe the bug

[#2406](https://github.com/nuxt/framework/pull/2406)

the changes to useRoute() made in the above PR prevents the current route from being correctly reflected after it is initially set.

**Comment by milesingrams** [comment]
Same issue here. Thought it was a vue-router issue but only happens using the Nuxt 3 composable.

**Comment by Diizzayy** [comment]
@milesingrams a PR rectifying this issue has been made and will be merged soon enough 👍🏽 This won't be an issue for much longer.

**Comment by adb-sh** [comment]
I'm still facing this issue in nuxt 3.0.0 :/

**Comment by manniL** [comment]
> I'm still facing this issue in nuxt 3.0.0 :/

Please open a new issue then with reproduction (and feel free to link to this one) ☺️
