### ISSUE TITLE
host 0.0.0.0 setting do not work in production mode

### ISSUE THREAD

**Issue by chenej9797** [nuxt/framework#2446]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27319101.3e82f0f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `buildModules`, `css`, `privateRuntimeConfig`, `meta`, `vite`, `build`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.1.1`, `@intlify/nuxt3@0.1.9`

### Reproduction

`nuxt.config.js`
```javascript=
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
    ...,
    vite: {
        server: {
            host: '0.0.0.0'
        }
    }
})
```

### Describe the bug

When I run `yarn dev`, it works as I expect:
```
> Local:    http://localhost:5555/
> Network:  http://xxx.xxx.x.xxx:5555/
```

But when running `yarn build` & `yarn start`:
I can only access `http://localhost:3000/`
```
Listening on http://localhost:3000
```

I'm not sure is that a bug or not. Or, is there any way to access the public address in production mode?

**Comment by K-Honkawa** [comment]
Currently I think we need to set environment variables such as NUXT_PORT or PORT and NUXT_HOST or HOST.

> https://github.com/nuxt/framework/blob/a896c64b1232dba1d01874159a9953d5f79bccc4/packages/nitro/src/runtime/entries/server.ts#L8-L9

**Comment by kevinadhiguna** [comment]
Hi @K-Honkawa , I set HOST and PORT to `.env` but it still runs on port 3000.

`.env` :
```
NUXT_HOST=0.0.0.0
HOST=0.0.0.0
NUXT_PORT=4000
PORT=4000
```

------

Running `yarn dev` : 
```bash
Nuxt CLI v3.0.0-27335375.b41a1d2

  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.2:3000/
  > Network:  http://10.3.1.2:3000/
```

Running `yarn build` then `yarn start` : 
```bash
yarn run v1.22.17
$ node .output/server/index.mjs
Listening on http://localhost:3000
```

-----

What is expected : 

Running `yarn dev` : 
```bash
Nuxt CLI v3.0.0-27335375.b41a1d2

  > Local:    http://localhost:4000/ 
  > Network:  http://192.168.1.2:4000/
  > Network:  http://10.3.1.2:4000/
```

Running `yarn build` then `yarn start` : 
```bash
yarn run v1.22.17
$ node .output/server/index.mjs
Listening on http://localhost:4000
```


Any help is appreciated.

**Comment by chenej9797** [comment]
Hi, @kevinadhiguna. I don't know how to set Nuxt env in the most correct way. But maybe you can try this one:

`.env`
```
NUXT_HOST=0.0.0.0
NUXT_PORT=4000
```

`package.json`
```
...
"scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "eval $(grep '^NUXT_HOST' .env) $(grep '^NUXT_PORT' .env) node .output/server/index.mjs"
 }
...
```

It works for me.

**Comment by kevinadhiguna** [comment]
Worked like a charm, thanks @chenej9797 !

**Comment by banlify** [comment]
> Hi @K-Honkawa , I set HOST and PORT to `.env` but it still runs on port 3000.
> 
> `.env` :
> 
> ```
> NUXT_HOST=0.0.0.0
> HOST=0.0.0.0
> NUXT_PORT=4000
> PORT=4000
> ```
> 
> Running `yarn dev` :
> 
> ```shell
> Nuxt CLI v3.0.0-27335375.b41a1d2
> 
>   > Local:    http://localhost:3000/ 
>   > Network:  http://192.168.1.2:3000/
>   > Network:  http://10.3.1.2:3000/
> ```
> 
> Running `yarn build` then `yarn start` :
> 
> ```shell
> yarn run v1.22.17
> $ node .output/server/index.mjs
> Listening on http://localhost:3000
> ```
> 
> What is expected :
> 
> Running `yarn dev` :
> 
> ```shell
> Nuxt CLI v3.0.0-27335375.b41a1d2
> 
>   > Local:    http://localhost:4000/ 
>   > Network:  http://192.168.1.2:4000/
>   > Network:  http://10.3.1.2:4000/
> ```
> 
> Running `yarn build` then `yarn start` :
> 
> ```shell
> yarn run v1.22.17
> $ node .output/server/index.mjs
> Listening on http://localhost:4000
> ```
> 
> Any help is appreciated.

1. install `cross-env` pkg.
```shell
npm i cross-env -D
```

2. `package.json`
```json
{
  "scripts": {
    "dev": "nuxi dev --host 0.0.0.0",
    "build": "nuxi build",
    "start": "cross-env HOST=0.0.0.0 cross-env PORT=5000 node .output/server/index.mjs"
}
```
