### ISSUE TITLE
Unintended attribute binding for components

### ISSUE THREAD

**Issue by xxSkyy** [nuxt/framework#2450]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.3`
- Nuxt Version:     `3.0.0-27328916.daec432`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `buildModules`, `srcDir`, `build`, `env`, `windicss`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.6`, `nuxt-windicss@2.1.1`
------------------------------

### Reproduction

https://codesandbox.io/s/nuxt3-ssr-attr-binding-bug-lztoi

When you'll inspect "Welcome" label it has `type="text"` attribute while only input should have provided attributes by parent.

### Describe the bug

With provided example SSR adds attributes for `BaseLabel` while they are bound to `Input`.

**Comment by danielroe** [comment]
Would you raise an issue upstream on https://github.com/vuejs/vue-next/issues? (Seems like this also may be linked to https://github.com/nuxt/framework/issues/2219.)

**Comment by xxSkyy** [comment]
Done it 👌

**Comment by xxSkyy** [comment]
@danielroe should I close upstream labeled issues or wait till upstream issues I made will be fixed?

**Comment by xxSkyy** [comment]
Fixed in this [commit](https://github.com/vuejs/core/commit/516bc548fce295f6d564c7fb371c8067ead7cd71). 
I've updated codesandbox to latest Nuxt version and can confirm it got fixed.
