### ISSUE TITLE
how to use keep-alive

### ISSUE THREAD

**Issue by xiaojieajie** [nuxt/framework#2452]
### Environment

‘’

### Reproduction

‘’

### Describe the bug

how to use keep-alive

**Comment by danielroe** [comment]
`KeepAlive` should work normally for Nuxt Bridge. If you've found a bug, please raise an issue with a reproduction - or, if you're just looking for some help, please raise a discussion instead of any issue. If you're asking about Vue 3 support, let's track in in discussion #2426.

**Comment by xiaojieajie** [comment]
> `KeepAlive`Nuxt Bridge 应该可以正常工作。如果您发现了一个错误，请在复制时提出问题 - 或者，如果您只是在寻求帮助，请提出讨论而不是任何问题。如果您正在询问 Vue 3 支持，让我们跟踪讨论#2426。

ok
