### ISSUE TITLE
the project in some folder alway display the loading animation, no matter modified file or not, but in some another folder the project everything is ok!

### ISSUE THREAD

**Issue by firedragon68** [nuxt/framework#2485]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27334872.6e32bde`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

only modified the app.vue
<template>
  <div>
    test page
  </div>
</template>

### Describe the bug

the project in some folder alway display the loading animation, no matter modified file or not, but in some another folder the project everything is ok!

**Comment by danielroe** [comment]
What folder names have you tried?

**Comment by firedragon68** [comment]
when i create the project in download folder in my mac pro book is ok, but in desktop i create a floder, then init the project, the loading animation is always display.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel ***@***.***&gt;; 
发送时间: 2021年12月21日(星期二) 晚上10:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nuxt/framework] the project in some folder alway display the loading animation, no matter modified file or not, but in some another folder the project everything is ok! (Issue #2485)





 
What folder names have you tried?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by danielroe** [comment]
What are the full paths to each folder? (Run `pwd` from the command line within each folder.)
