### ISSUE TITLE
improve cdnURL handling/behaviour

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#2488]
## Background

It should be possible to host generated assets on a CDN, and this should be possible to configure at runtime via Nitro. If omitted, assets should be served from the Nitro static middleware.

Related issues: https://github.com/nuxt/framework/issues/1467, https://github.com/nuxt/framework/issues/2242

## Asset types

There are two kinds of assets we serve from Nitro:

1. **static assets** originally from the `public/` folder that are not the product of the build
2. **build outputs**. As a matter of best practice these should be located in a separate folder so we can apply different caching rules

## Proposed configuration

Instead of attempting to configure all of this through `router.base` and `build.publicPath`, it makes sense to configure it with the following three values:

- basePath: `/`
- buildAssetsPath: `/_nuxt`
- cdnURL?

```js
export default defineNuxtConfig({
  // nuxtApp configuration
  app: {
    basePath, // Relative to ./
    buildAssetsPath, // Relative to basePath
	cdnURL? // Absolute URL 
  }
})
```

### Runtime

At runtime the following values will be calculated, allowing for dynamic override via Nitro (or within server):

* `getRouterBase()` - returns the vue router base which should be prepended to all paths for client-side navigation
   **computed**: `basePath`
*  `getPublicAssetsURL()` - returns the public URL that corresponds to `.output/public` - which might be a CDN URL or the router base
   **computed**: `cdnURL || basePath`
* `getBuildAssetsURL()` - returns the full computed path to the `_nuxt` folder that serves build assets
   **computed**: `cdnURL ? ${cdnURL}/${assetsPath} : ${basePath/${assetsPath}`

**Comment by pi0** [comment]
basePath` should remain absolute unless starting with `.` which I suggest introducing in a second iteration for relative base support

Regarding Runtime options shall be functions like `getRouterBase()` to clearly state they are computed and avoid accidentally caching their value or inlining in bundle. 

Improved proposal:

App config:
- `basePath` 
- `buildAssetsPath`
- `cdnURL?`

Computed:
- `getRouterBase()`
- `getPublicAssetsURL()`
- `getBuildAssetsURL()`
