### ISSUE TITLE
Nuxt 2 & 3 compatible module stops working after nuxt3 update

### ISSUE THREAD

**Issue by Baroshem** [nuxt/framework#2497]
### Environment

Development

### Reproduction

1. Create Nuxt 3 application.
2. Add nuxt-bigcommerce module to it. (https://github.com/Baroshem/nuxt-bigcommerce)
3. Start the project using yarn dev

### Describe the bug

I have been using Nuxt 3 project with nuxt-bigcommerce package. It works just fine with "nuxt3": "3.0.0-27324955.23397e6", but it stopped working after updating to the newer latest versions like "nuxt3": "3.0.0-27335068.804b323". It results with following bug
 `ERROR  Cannot start nuxt:  Nuxt module should be a function: nuxt-bigcommerce,[object Object]`

**Comment by pi0** [comment]
Seems issue is with inline options. Should fix this usage b41a1d2d189a68856a834b65edac1f3e664f6bf0

**Comment by Baroshem** [comment]
I can confirm that it works with the latest version. Thanks @pi0!
