### ISSUE TITLE
Nuxt hook "listen" is not firing

### ISSUE THREAD

**Issue by richardeschloss** [nuxt/framework#2499]
### Environment

Node LTS (16) on Linux / nuxt-bridge / nuxt-edge / vite

### Reproduction

The nuxt "listen" hook does not seem to be firing. Please add it back in if it was deleted.

```js
import { defineNuxtModule } from '@nuxt/kit'
export default defineNuxtModule({
  hooks: {
    listen( ) {
      // Never called
    }
  }
})
```

### Describe the bug

The nuxt "listen" hook does not seem to be firing. Please add it back in if it was deleted.

**Comment by richardeschloss** [comment]
I'm guessing this line needs the callHook?
https://github.com/nuxt/framework/blob/b41a1d2d189a68856a834b65edac1f3e664f6bf0/packages/nitro/src/server/dev.ts#L119

**Comment by danielroe** [comment]
(Related: https://github.com/nuxt/framework/issues/523). Because Nuxt is build-time only, there is nothing to call these server hooks. Instead we will implement via the ability to extend Nitro itself. I'm going to close this issue - but do follow the RFC at https://github.com/nuxt/framework/discussions/1690.

**Comment by pi0** [comment]
Indeed nuxt is build-time only and listener server is initiated before nuxt via nuxi cli. Still would be nice if we can _fake_ hook for backward compatibility or possible edge case uses.

**Comment by richardeschloss** [comment]
Fwiw, some background on this issue: my use case was waiting for the listen hook to fire so that I could re-use nuxt's server instance. Specifically, for socket.io. This way socket.io and nuxt could share the same port without requiring additional configuration. However, for the time being, I decided to just keep the two separate (on separate ports). 

The more I think about it, it may be better design for Nuxt to treat it's own server instance as private and to remove the listen hook from the type definitions so people don't attempt to use the hook. It's properties though, like current host and port, may still be useful for developers to access.

**Comment by hareku** [comment]
@danielroe Is there any way to set keepaliveTimeout etc for Node.js server in `nuxi preview`?
