### ISSUE TITLE
FetchError: Failed to execute 'fetch' on 'Window': Illegal invocation ()

### ISSUE THREAD

**Issue by nndnha** [nuxt/framework#2502]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27335375.b41a1d2`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-lbsaqp?file=app.vue

### Describe the bug

Click the load my todo button, this error will be shown in the console log.

**Comment by andysay** [comment]
+1 same problem

**Comment by pi0** [comment]
It was a regression with ohmyfetch latest changes fixed by https://github.com/unjs/ohmyfetch/commit/8ea2d2b5f9dcda333de5824862a7377085fd8bb4

Using `npx nuxi upgrade --force` should solve the issue.

**Comment by itshizhan** [comment]
Nice
