### ISSUE TITLE
PrimeVue integration fails load on runtime

### ISSUE THREAD

**Issue by smorcuend** [nuxt/framework#2516]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27335375.b41a1d2`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `css`, `transpile`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/smorcuend/nuxt3-test

### Describe the bug

Last changes on nuxt3 CI generates error after build process. The result code on bundling process not showing errors but `npx nuxi preview` throw this error on console when serving:

```
Directory import '/home/myproject/.output/server/node_modules/primevue/config' is not supported resolving ES modules imported from /home/myproject/.output/server/chunks/app/server.mjs
Did you mean to import primevue/config/config.cjs.js?
  at new NodeError (node:internal/errors:371:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:412:17)  
  at moduleResolve (node:internal/modules/esm/resolve:932:10)  
  at defaultResolve (node:internal/modules/esm/resolve:1044:11)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)  
  at link (node:internal/modules/esm/module_job:75:36)
```

Regarding development server is serving correctly.

### Additional context

I am trying to deploy on Netlify but server response HTTP 500 Error when serving. The build process has no errors on console as in local environment.

**Comment by selucaciu** [comment]
I'm having the same problem when trying to deploy. Development server is working correctly. Any ideas?

**Comment by denys119** [comment]
I stumbled upon the same problem too..

**Comment by danielroe** [comment]
This is an upstream packaging issue with PrimeVue. When you change the imports following the console log recommendation, they work fine (noting that custom directives would also need to be registered):

```js
import { defineNuxtPlugin } from '#app';
import PrimeVue from 'primevue/config/config.cjs.js';
import Button from 'primevue/button/button.cjs.js';
import ToastService from 'primevue/toastservice/toastservice.cjs.js';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(PrimeVue, { ripple: true });
  nuxtApp.vueApp.use(ToastService);
  nuxtApp.vueApp.component('Button', Button);
  //other components that you need
});
```

**Comment by Onlymix** [comment]
> This is an upstream packaging issue with PrimeVue. When you change the imports following the console log recommendation, they work fine (noting that custom directives would also need to be registered):
> 
> ```js
> import { defineNuxtPlugin } from '#app';
> import PrimeVue from 'primevue/config/config.cjs.js';
> import Button from 'primevue/button/button.cjs.js';
> import ToastService from 'primevue/toastservice/toastservice.cjs.js';
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   nuxtApp.vueApp.use(PrimeVue, { ripple: true });
>   nuxtApp.vueApp.use(ToastService);
>   nuxtApp.vueApp.component('Button', Button);
>   //other components that you need
> });
> ```

Hi i have similar probler but didn't know how to solve it
So problem is i got errors after build and start project. It throw many errors like
`[nuxt] [request error] Directory import '/home/dark/nuxt3-fullstack/.output/server/node_modules/primevue/api' is not supported resolving ES modules imported from /home/dark/nuxt3-fullstack/.output/server/chunks/app/server.mjs
Did you mean to import primevue/api/api.cjs.js?`
I got this becouse trying to import from component 
`import { FilterMatchMode } from "primevue/api";
import { useToast } from "primevue/usetoast";`
in <script setup lang="ts"> block so import cjs isn't a case
