### ISSUE TITLE
Composables dir, scanned only top files level

### ISSUE THREAD

**Issue by k0mar12** [nuxt/framework#2531]
### Environment

- Operating System: `Darwin`
- Node Version:     `v17.2.0`
- Nuxt Version:     `3.0.0`
- Package Manager:  `yarn@3.1.1`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Create files in **composables** dir with few levels, for example: 

> composables

>>admin

>>>useFetch.js

>>cora.js

>>useAdmin.js

### Describe the bug

Files which deep then top level not autoloaded

[Screen](http://dl4.joxi.net/drive/2021/12/24/0016/1034/1111050/50/d9ce8ab2f5.png)

Problem in **globby**, i guess

**Comment by shinguweb96** [comment]
On Nuxt 2 bridge components are not auto-imported too

**Comment by k0mar12** [comment]
> On Nuxt 2 bridge components are not auto-imported too

We are not talking about components.
