### ISSUE TITLE
Couldn't resolve #app 

### ISSUE THREAD

**Issue by alexjoverm** [nuxt/framework#2542]
### Environment

Nuxt CLI v3.0.0-27338323.1e98259                                                                                                  16:17:52
RootDir: /Users/alexjm/WebDev/@storyblok/storyblok-nuxt/tests/nuxt3-app                                                           16:17:54
Nuxt project info:                                                                                                                16:17:54

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Webpack`
- User Config:      `buildModules`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@storyblok/nuxt@3.0.0-beta.1`
------------------------------

### Reproduction

I have no repo link, but have some clear steps:

- Create new Nuxt 3 app
- Install [@storyblok/nuxt](https://www.npmjs.com/package/@storyblok/nuxt) by following the 2 steps 
- In node_modules/@storyblok/nuxt/composables/dist/composable.es.js comment out the first line where the `#app` is
- You'll see the following error

<img width="1204" alt="Screenshot 2021-12-25 at 15 40 16" src="https://user-images.githubusercontent.com/5701162/147393616-f5a66823-b07c-407c-be49-efcde0393908.png">

### Describe the bug

Describe in reproduction steps

**Comment by Ryoto-kubo** [comment]
Similar error.
<img width="373" alt="スクリーンショット 2021-12-27 19 53 11" src="https://user-images.githubusercontent.com/50362462/147465183-00afcae1-929a-417a-9354-ca6fa01ad6c0.png">

```bash
Package import specifier "#app" is not defined in package /Users/user_name/project/package.json imported from /Users/user_name/project/.nuxt/nitro/index.mjs
```

I did as per the bridge document.

https://v3.nuxtjs.org/getting-started/bridge

**Comment by richardeschloss** [comment]
I'm able to get it working, I'm guessing you need either one of the following:

1. A nuxt.config which exports a proper default (`defineNuxtConfig`):

```js
import { defineNuxtConfig } from '@nuxt/bridge'
export default defineNuxtConfig({ // <-- this function inserts the nuxt bridge into buildModules.
  bridge: {
    vite: true
  },
  ...
})
```


2. @nuxt/bridge as a buildModule in the nuxt config.

I've only tried the first step and it's the only way I can get Nuxt-edge or Nuxt3 to work right with plugins.

**Comment by alexjoverm** [comment]
Just for clarification, the original issue is reported on Nuxt 3

**Comment by danielroe** [comment]
@alexjoverm The composables directory isn't being transpiled, so it wouldn't be able to use Nuxt aliases. If you were to add it to the transpile array, it would likely work.

**Comment by alexjoverm** [comment]
@danielroe we have to add the nuxt core composables folder to `build.transpile`? As you can see in my image, the issue appears in nuxt internals, and according to @Ryoto-kubo and @richardeschloss comments it happens also in plugins or nuxt config... probably we shouldn't close this yet 😉

**Comment by danielroe** [comment]
I'm referring to your composables directory. [For example](https://unpkg.com/browse/@storyblok/nuxt@3.0.0-beta.2/composables/dist/composables.mjs).

**Comment by alexjoverm** [comment]
That's something we can do... but would it solve the errors on nuxt core utilities? Like the ones you see on the image above

**Comment by danielroe** [comment]
@alexjoverm Let me know if the errors you're seeing above persist once you've done so, ideally with a reproduction. I'd be happy to help 😊

**Comment by richardeschloss** [comment]
FWIW, I was also able to get this working in Nuxt3. @alexjoverm 

Working nuxt.config here ==> https://github.com/richardeschloss/nuxt-socket-io/blob/feat/nuxt3/nuxt.config.js (it seems like it needs the `defineNuxtConfig` to work); the feat/nuxt3 branch in that repo contains working module/plugin code as a reference if you want.

**Comment by richardeschloss** [comment]
Hi, I can reproduce this issue when the plugin sits in node_modules. Please consider re-opening this issue.

The simplest repro is this: place a plugin inside node_modules, and give it the most basic scaffolding:

```js
import { defineNuxtPlugin } from '#app'
export default defineNuxtPlugin(() => {})
```

In your app's nuxt.config, specify the plugin:

```js
...
plugins: ['vendor/plugin.js']  // For this example, place plugin.js in node_modules/vendor/plugin.js
```

When you attempt to run the app, you'll encounter the "couldn't resolve #app" error. 

The workarounds to this are:

1. Move the plugin to the application's workspace (but this might not be ideal)
2. Create a module in the "node_modules/vendor" folder that adds the vendor/plugin.js. Then install the module in one of two ways:
  1. Specify the module in nuxt.config as `modules: [vendor/module.js]`. 
  2. Use a local module to add that vendor module with `installModule`. But in order for this to work, the local module also has to push the 'vendor/module.js' to nuxt.options.modules. If that part is missing, you'll encounter "couldn't resolve app" error. 

I hope this info helps.

**Comment by danielroe** [comment]
@richardeschloss Anything in node modules that imports from `#app` or other Nuxt aliases needs to be added to `build.transpile`.

**Comment by richardeschloss** [comment]
Thanks. Can I suggest an edit to this section in the docs: https://v3.nuxtjs.org/concepts/esm#transpiling-libraries . The specific sentence "Anything in node modules that imports from #app or other Nuxt aliases needs to be added to build.transpile." I could see being very useful there.
