### ISSUE TITLE
Docs: Releases notes for each package

### ISSUE THREAD

**Issue by Atinux** [nuxt/framework#255]
https://tauri.studio/en/release-notes

![Screenshot 2021-06-21 at 14.57.57.png](https://maintainers.s3.fr-par.scw.cloud/Screenshot_2021_06_21_at_14_57_57_76f0820a80.png)

**Comment by f3ltron** [comment]
something like `npx release-it --release-version` may be worth to explorate. We are using it in my company and looks really nice @Atinux 

simple .release-it.json

```
{
	"git": {
		"requireCleanWorkingDir": false,
		"changelog": "npx auto-changelog --output=CHANGELOG.md --commit-limit false -v ${version} --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs"
	},
	"npm": false,
	"release-version": true,
	"increment": "minor"
}

```

**Comment by f3ltron** [comment]
That can also be added simply with a github action 

https://github.com/release-it/release-it

**Comment by Atinux** [comment]
It also seems that GitHub can generate the release notes now :)

**Comment by pi0** [comment]
Github release notes are not suitable for our monorepo. Filtering, per-package changelog, and edge changelog (non tags) are not possible. We need to port a changelog script similar the one we have for Nuxt2.

**Comment by Atinux** [comment]
I will let you handle this, too bad for that :joy:

**Comment by Atinux** [comment]
I think showing the releases notes shall be enough now :blush:
