### ISSUE TITLE
Custom 404 error page

### ISSUE THREAD

**Issue by svaldivia2** [nuxt/framework#2556]
I'm trying to customize my 404 error page using ~/layouts/error.vue but it's not working on my Nuxt 3 project.

https://v3.nuxtjs.org/docs/directory-structure/layouts

Docs not mention it, so I don't know if this even possible yet.

Is there a way to customize 404 not found page?

Thanks.

**Comment by chenej9797** [comment]
Adding `404.vue` under `pages/` folder works for me.

**Comment by TrungRueta** [comment]
I also need find way to customize page 500. but look like Nuxt3 hardcoded error page for now. only 404 can customize.

**Comment by svaldivia2** [comment]
> Adding `404.vue` under `pages/` folder works for me.

Thanks!

Solved.

**Comment by awacode21** [comment]
I am dealing with the same topic and have a question.

i have fully unknown generic routes (coming from cms).
So i use the [...slug].vue variant for catch-all-routes, as mentioned in the docs https://v3.nuxtjs.org/docs/directory-structure/pages

obviously it is now up to [...slug].vue to do the error handling.

Now my question, in nuxt 2 there was the possibility to use the validate() hook. When returning false the user got redirected to error page. also there was the error() function to navigate to error page. Is there any equivalent in nuxt 3??? how can i send the user to error page when i recognize an error within my [...slug].vue ?
