### ISSUE TITLE
Extending useFetch

### ISSUE THREAD

**Issue by san4io** [nuxt/framework#2557]
### Environment

Nuxt CLI v3.0.0-27338323.1e98259

### Reproduction

I'm trying to extend useFetch

```
const useApiFetch = async (url: string, options) => {
    const config = useRuntimeConfig()

    return useFetch(url, {
        baseURL: config.API_URL,
        async onRequest(ctx) {
            const accessToken = await useCookie('access_token' ,{ default: undefined })

            if (undefined !== accessToken) {
                ctx.options.headers.append('Authorization', accessToken.value)
                // ctx.options.headers.set('Authorization', accessToken.value)
                // ctx.options.headers['Authorization'] = `Bearer ${accessToken.value}`
            }
        },
        ...options
    });
}

export default useApiFetch
```

And use it to retrieve data.
```
const { data } = await useApiFetch("item/item-categories/search", {
        params: {
          query:'Hello world',
          limit: 5
        }
      });
```

I can set params in interceptors, but I can't set headers. If I set headers, fetch doesn't work, it even doesn't fires request.

### Describe the bug

Impossible to extend useFetch with interceptors

**Comment by K-Honkawa** [comment]
I think there is a problem [here](https://github.com/nuxt/framework/blob/47c004ac97fbe8bc80f210806981b77fb437cbbe/packages/nitro/package.json#L55).

This version does not support onRequest.

**Comment by san4io** [comment]
> I think there is a problem [here](https://github.com/nuxt/framework/blob/47c004ac97fbe8bc80f210806981b77fb437cbbe/packages/nitro/package.json#L55).
> 
> > https://github.com/nuxt/framework/blob/47c004ac97fbe8bc80f210806981b77fb437cbbe/packages/nitro/package.json#L55
> 
> This version does not support onRequest.
> 
> I think it should be at least v0.4.13 or higher.

Hmm, maybe you're right.

But the interesting part is that if  I just console.log something, it's printed. :D

**Comment by K-Honkawa** [comment]
Probably due to undefined in ctx.options.headers.

Since the version up of ohmyfetch has been done, it seems that the current situation is working.

I think that it will work if you do the following.

```diff
const useApiFetch = async (url: string, options) => {
    const config = useRuntimeConfig()

    return useFetch(url, {
        baseURL: config.API_URL,
        async onRequest(ctx) {
            const accessToken = await useCookie('access_token' ,{ default: undefined })

            if (undefined !== accessToken) {
+                 ctx.options.headers = new Headers(ctx.options.headers)
                ctx.options.headers.append('Authorization', accessToken.value)
                // ctx.options.headers.set('Authorization', accessToken.value)
                // ctx.options.headers['Authorization'] = `Bearer ${accessToken.value}`
            }
        },
        ...options
    });
}

export default useApiFetch
```

**Comment by danielroe** [comment]
You also shouldn't be calling `useCookie` within the request, but rather within the setup portion of your composable, and note that it returns a Ref - e.g.:

```diff
const useApiFetch = async (url: string, options) => {
    const config = useRuntimeConfig()
+   const accessToken = useCookie('access_token')

    return useFetch(url, {
        baseURL: config.API_URL,
        async onRequest(ctx) {
-            const accessToken = await useCookie('access_token' ,{ default: undefined })
+            if (!accessToken.value) {
-            if (undefined !== accessToken) {
                ctx.options.headers.append('Authorization', accessToken.value)
                // ctx.options.headers.set('Authorization', accessToken.value)
                // ctx.options.headers['Authorization'] = `Bearer ${accessToken.value}`
            }
        },
        ...options
    });
}

export default useApiFetch
```

If you need a hand, do feel free to create a GitHub Discussion, or post a reproduction if you think there's a bug.s

**Comment by aligzl** [comment]
> You also shouldn't be calling `useCookie` within the request, but rather within the setup portion of your composable, and note that it returns a Ref - e.g.:
> 
> ```diff
> const useApiFetch = async (url: string, options) => {
>     const config = useRuntimeConfig()
> +   const accessToken = useCookie('access_token')
> 
>     return useFetch(url, {
>         baseURL: config.API_URL,
>         async onRequest(ctx) {
> -            const accessToken = await useCookie('access_token' ,{ default: undefined })
> +            if (!accessToken.value) {
> -            if (undefined !== accessToken) {
>                 ctx.options.headers.append('Authorization', accessToken.value)
>                 // ctx.options.headers.set('Authorization', accessToken.value)
>                 // ctx.options.headers['Authorization'] = `Bearer ${accessToken.value}`
>             }
>         },
>         ...options
>     });
> }
> 
> export default useApiFetch
> ```
> 
> If you need a hand, do feel free to create a GitHub Discussion, or post a reproduction if you think there's a bug.s

@danielroe how to make it work with dynamic urls for refresh/refetch

```
const id = ref(1)


  const { data, refresh } = await useApiFetch( "https://example.com/characters/" + id.value) )
  const getNextChar = () => {
    id.value += 1
    refresh()
  }
```
