### ISSUE TITLE
Weird fetch bug? No fetch at all...

### ISSUE THREAD

**Issue by michael-observerly** [nuxt/framework#2564]
### Environment

```
Nuxt CLI v3.0.0-27338323.1e98259                                                                                                                                                        14:42:31
RootDir: /Users/michael/observerly/observerly-nuxt-3                                                                                                                                    14:42:31
Nuxt project info:                                                                                                                                                                      14:42:31

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `meta`, `ssr`, `buildModules`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.2.1`, `@vueuse/nuxt@7.4.1`
------------------------------
```

### Reproduction

https://github.com/observerly/observerly-nuxt3

### Describe the bug

Essentially I have a custom Vue 3 components library that performs a prefetching of data on the onMounted() lifecycle hook. 

However, the fetch is never made.

Something akin to this:

```ts
const fetchData = async () => {
    try {
        const response = await fetch('url-to-endpopint')
        return await response.json()
     } catch (err) {
        console.error(err)
        return []
     }
}

const data = ref([])

onMounted(async () => {
    data.value = await fetchData()
})
```

When using this component in a pure Vue 3 setup, with both Vue and Vite, the component works perfectly.

However, when I have built this component library as a module ... and used within Nuxt 3 ... I don't see any fetching of the data. The data simply does not fetch, there's nothing in Network logs - no errors thrown.

I do see this particular error:

```
[Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function. 
```

But for me, I don't use render functions in my component library ... this error is only seen when utilising this component library with Nuxt.

### Additional context

You may need access to some of our private npm projects - please contact michael@observerly.com for this or comment directly below.

**Comment by sjonibek** [comment]
const data = ref([])

const fetchData = async () => {
  try {
    const response = await fetch('url-to-endpopint')
    data.value = await response.json()
  } catch (err) {
    console.error(err)
  }
}

onMounted(() => {
  fetchData()
})

**Comment by michael-observerly** [comment]
@sjonibek I see what you mean - but unfortunately I have defined `fetchData` as an async function (I just missed this out in the description). I've updated the description.

**Comment by michael-observerly** [comment]
I'm kind of concerned because a Vue 3 component library should, for the most part, just work with Nuxt 3, right? I can't see why the onMounted() call isn't being made ...

**Comment by michael-observerly** [comment]
So, update on this: this seems to be an issue with a dependency that my component library.

I went back through dependencies for my component library, and I had one dependency (an astronomy library I have written for specific tasks) and recognised that it wasn't being exported as a ES module ... at all. D'oh! I chore'd through it, and found that the issues were no longer a problem.
