### ISSUE TITLE
layouts with camelcase throws 'Invalid layout' 

### ISSUE THREAD

**Issue by Fanna1119** [nuxt/framework#2567]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.17.0`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/stupefied-saha-zighf

### Describe the bug

Having the layout name set using camelCase throws  'Invalid layout' 
It works fine with hyphens like `default-layout.vue`

**Comment by Fanna1119** [comment]
possibly related to #2518

**Comment by fosterdouglas** [comment]
@pi0 It looks like this may have been reintroduced. Using the [changing layout](https://v3.nuxtjs.org/guide/directory-structure/layouts#example-changing-the-layout) example in the guide, it's simple to repro:

_pages/some-page.vue_
```
<template>
  <div>
    <button @click="enableCustomLayout('customA')">Dashboard</button>
    <button @click="enableCustomLayout('customB')">Users</button>
    <button @click="enableCustomLayout('customC')">Invoicing</button>

    <NuxtLayout :name="route.meta.layout">
      <template #header>{{ route.meta.layout }}</template>
    </NuxtLayout>
  </div>
</template>

<script setup lang="ts">
const route = useRoute();
function enableCustomLayout(customLayout) {
  route.meta.layout = customLayout;
}

definePageMeta({
  layout: "customA",
});
</script>
```

With the associated files in `layouts/customA.vue`, `layouts/customB.vue`, `layouts/customC.vue`

The above provides the same 'Invalid Layout' warning. Replacing them with `custom-a`, `custom-b`, `custom-c` fixes it.

**Comment by danielroe** [comment]
@fosterdouglas Layout names are normalised to kebab case and should be used that way.

**Comment by fosterdouglas** [comment]
Ah ha, I see it now. Shamed for skipping reading the last sentence of the layouts page intro. 😬  Thanks.
