### ISSUE TITLE
TS2345: Argument of type '{ buildModules: string[]; x: { url: string; }; }' is not assignable to parameter of type 'NuxtConfig'

### ISSUE THREAD

**Issue by jannikbuscha** [nuxt/framework#2578]
### Environment

Nuxt CLI v3.0.0-27338323.1e98259                                                                              05:12:56
RootDir: C:\Projects\astolfo                                                                                  05:12:58
Nuxt project info:                                                                                            05:12:58

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `buildModules`, `strapi`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/strapi@0.3.4`
------------------------------

### Reproduction

completely empty and new nuxt3 project

### Describe the bug

Hey, as soon as I want to set up a new nuxt3 project with strapi I get the following error:

TS2345: Argument of type '{ buildModules: string[]; strapi: { url: string; }; }' is not assignable to parameter of type 'NuxtConfig'.   Object literal may only specify known properties, and 'strapi' does not exist in type 'NuxtConfig'.

I actually did it the same way as in the "example", except that I specified "'@nuxtjs/strapi'" instead of "module", as it also says in the doc.

My nuxt.config.ts:
![image](https://user-images.githubusercontent.com/74017697/147802912-f64c7ad4-0f53-492c-9ab1-29d6fae7f4f1.png)

**Comment by ShaggyTech** [comment]
One way to solve this is to add a typescript shim for `@nuxt/schema` to add the `StrapiOptions` type to NuxtConfig and NuxtOptions.  Something like this:


`nuxt-schema-shim.d.ts `
```ts

import type { StrapiOptions } from '@nuxtjs/strapi';

declare module '@nuxt/schema' {
  interface NuxtConfig {
    strapi?: StrapiOptions;
  }
  interface NuxtOptions {
    strapi?: StrapiOptions; 
  }
}

```

Then you can augment the NuxtOptions and NuxtConfig in this file whenever needed.

**Comment by jannikbuscha** [comment]
> 

Great :) the error message disappears from the ide, but the whole thing still does not start :(

![image](https://user-images.githubusercontent.com/74017697/147896622-493b5de7-2c18-4861-952c-0c4b11137405.png)
![image](https://user-images.githubusercontent.com/74017697/147896632-56685311-59b3-46c2-b21e-eb42b4204e9f.png)

**Comment by danielroe** [comment]
That version of `@nuxtjs/strapi` isn't compatible with Nuxt 3. Keep an eye on its releases though!
