### ISSUE TITLE
Test using platform-specific CLIs

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#26]
The following providers have their CLIs [installed in GitHub actions](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) so it would be possible to test within CI/CD
- [ ] Vercel
- [ ] Netlify
- [ ] Azure

If this would be useful, I can investigate & put together a basic test suite based on their dev environments. (cc @pi0)

**Comment by pi0** [comment]
Hi @raulfdm. Actually, you don't need to configure anything to deploy on netlify! When using `nuxt build`, nitro detects netlify and generated necessary configuration for CI ([how works](https://github.com/nuxt/framework/blob/main/packages/nitro/src/presets/netlify.ts)). And it is same for nuxt 3 and bridge as both use same build of nitro.

**Comment by pi0** [comment]
I belive best would be end-to-end testing of deployments with anyhow they are supposed to be deployed (https://github.com/unjs/nitro-deploys) 

Still happy to discuss and rework this in nitropack.

**Comment by danielroe** [comment]
No, agreed.
