### ISSUE TITLE
How does nuxt3 use lodash

### ISSUE THREAD

**Issue by zedream** [nuxt/framework#2602]
### Environment

dev

### Reproduction

...

### Describe the bug

500

### Additional context

How does nuxt3 use lodash

**Comment by danielroe** [comment]
If you're experiencing a bug, please provide answers to the questions in the [new issue form](https://github.com/nuxt/framework/issues/new?assignees=&labels=pending+triage%2Cnuxt3&template=bug-report-nuxt3.yml) and I'd be glad to help.
