### ISSUE TITLE
CSS image paths are unnecessarily rewritten during build

### ISSUE THREAD

**Issue by msdsk** [nuxt/framework#2616]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.2.0`
- Nuxt Version:     `3.0.0-27338323.1e98259`
- Package Manager:  `npm@8.1.4`
- Bundler:          `Vite`
- User Config:      `meta`, `vite`, `nitro`, `css`, `typescript`, `components`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/msdsk/minimum-css-paths

### Describe the bug

# What is wrong

Nuxt revrites the css declaration from `background: url("/polka.svg")` to `background: url(/_nuxt/polka.svg)`, which is right for the dev process, but nuxt keeps it for the production build too, where static assets are served directly from the root. Images that were visible on dev thus disappear on production.

## What is wrong #2

Trying to reproduce the issue I've found out that without using pages, css was loaded normally on dev but with production build it seemed to not be loaded whatsoever, regardless if I kept it as a separate file referenced from `nuxt.config.ts` or as a `<style>` tag inside `app.vue`.

**Comment by K-Honkawa** [comment]
I feel like https://github.com/nuxt/framework/issues/2261

**Comment by danielroe** [comment]
Yes, let's follow in #2261
