### ISSUE TITLE
Autocomplete and Typechecking broken with auto imported components 

### ISSUE THREAD

**Issue by AXSJ** [nuxt/framework#2619]
### Environment

Any Nuxt 3 app

### Reproduction

Create a Nuxt 3 project, then create a component and try to import that component into app.vue

### Describe the bug

Autocomplete and type-checking does not work in VS-Code with auto-imported components

**Comment by danielroe** [comment]
Does this work if you restart the dev server?s

**Comment by AXSJ** [comment]
Hi Daniel, no it seems to happen across all my Nuxt 3 projects

**Comment by danielroe** [comment]
I can't reproduce this. Let me know if it's still occuring for you and I'll reopen it

<img width="896" alt="CleanShot 2022-04-15 at 20 56 13@2x" src="https://user-images.githubusercontent.com/28706372/163626161-929e735a-2ee4-40d8-9c6a-216ccc7561e6.png">
.
