### ISSUE TITLE
Import typescript files inside virtual templates/create typescript templates

### ISSUE THREAD

**Issue by farnabaz** [nuxt/framework#2635]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27265876.3cd4494`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `modules`
- Runtime Modules:  `~/modules/templater`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-xx9rpa?file=modules%2Ftemplater.ts

### Describe the bug

I want to create a plugin system that users can inject their custom plugin from `nuxt.config`. These plugins should import and load inside a virtual template.

The problem is in dev-mode the plugins are `.ts` files and when they import inside template, their path ends with `.ts` and Nitro raise ` WARN  [worker] Unknown file extension ".ts"` exception

### Additional context

Even changing template type from `.mjs` into `.ts` won't help and Nitro still can't load ts files

**Comment by danielroe** [comment]
related: https://github.com/nuxt/framework/issues/454
