### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/framework#2642]
The `nuxt/nitro` packages contains a few distribution-specific dependencies such as
```
@cloudflare/kv-asset-handler
@netlify/functions
@vercel/nft
```
However, one probably only pushes to one of these providers and thus the other ones are unnecessary. Better let the user decide where the want to distribute to, and then install the dependency needed for this.

Moreveor, nito relies on `@nuxt/design`. I think this is unnecessary.
Similarly, `bridge` needs `@babel/plugin-transform-typescript` which should not be necessary if one uses vite (+rollup), right?

**Comment by pi0** [comment]
Hi @tobiasdiez. Coming back to this, overhad of optional dependencies is so low (~3.4Mb) and `@vercel/nft` is actually a useful library we use for even Node.js target.

I've moved improvement to https://github.com/unjs/nitro/issues/82
