### ISSUE TITLE
No css in production with Vite

### ISSUE THREAD

**Issue by zumm** [nuxt/framework#2651]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27356801.e9128f3`
- Package Manager:  `npm@8.1.3`
- Bundler:          `Vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```bash
npx nuxi create mr
cd mr
npm i
vi app.vue
npm run build
npm run start
```

```vue
// app.vue
<template>
  <h1 class="test-class">
    Hello World!
  </h1>
</template>

<style>
.test-class {
  color: red;
}
</style>
```

### Describe the bug

In production mode Vite generates css bundle and connects it like this:

```html
<link rel="prefetch" href="/_nuxt/assets/bootstrap.5232f7ae.css">
```

But this bundle is not actually used. So page stays unaffected with css.

### Additional context

This issue does not appear with `vite: false` because webpack connects styles inline.

**Comment by kms-rscholz** [comment]
Probably related to: https://github.com/nuxt/framework/issues/25533

**Comment by danielroe** [comment]
yes, closing to follow in https://github.com/nuxt/framework/issues/2553
