### ISSUE TITLE
@ alias does not work on Nuxt 3 + Components

### ISSUE THREAD

**Issue by yungsilva** [nuxt/framework#2677]
- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.0.0-27356801.e9128f3`
- Package Manager:  `npm@8.1.1`
- Bundler:          `Vite`
- User Config:      `css`, `components`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

`npx nuxi init project`

`cd project && npm i`

create:

`assets/css/index.css`
`components/atoms/Button.vue`

in `nuxt.config.ts` add:

```ts
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  css: ['@/assets/css/index.css'], // @ works fine
  components: ['@/components/atoms'] // @ does not work
})
```

>  WARN  Components directory not found: @/components/atoms

and I split my components into folders, `atoms`, `molecules`, `organisms`, `templates`

in nuxt 2 I just need to do:

```ts
components: [{ path: '@/components', pathPrefix: false }],
```

in nuxt 3 i receiver this error: 

>  WARN  Components directory not found: @/components

already tried:

```ts
components: [{ path: '~/components', pathPrefix: false }]
```

> [Vue warn]: Failed to resolve component: Button

It only works with the verbose code below:

```ts
components: [
  '~/components/atoms',
  '~/components/molecules',
  '~/components/organisms',
  '~/components/templates'
]
```

### Describe the bug

@ alias does not work on Nuxt 3 + Components

**Comment by arb85** [comment]
You can use directly in your page / component:
```vue
<template>
<AtomButton />
</template>
```
Check documentation here:

https://v3.nuxtjs.org/docs/directory-structure/components/#component-names

**Comment by danielroe** [comment]
[**Reproduction**](https://stackblitz.com/edit/github-9ahmkg?file=nuxt.config.ts&terminal=dev).

**Comment by yungsilva** [comment]
The issue has been closed, but one issue still remains:

```ts
components: [{ path: '@/components', pathPrefix: false }],
```

this works perfectly on nuxt 2 but not on nuxt 3.

@danielroe @pi0

**Comment by danielroe** [comment]
@yungsilva I have raised this as a separate issue: https://github.com/nuxt/framework/issues/2748
