### ISSUE TITLE
exports is not defined and m.default is not a function

### ISSUE THREAD

**Issue by little3201** [nuxt/framework#2679]
### Environment

System: macOS 12.1
nuxt3: 3.0.0-27365509.a2e2e04
yarn: 3.1.1
node: 16.13.0

### Reproduction

https://codesandbox.io/embed/github/nuxt/starter/tree/v3-codesandbox/?fontsize=14&hidenavigation=1&theme=dark

### Describe the bug

getting error as shown below:
<img width="1018" alt="Screen Shot 2022-01-12 at 08 30 04" src="https://user-images.githubusercontent.com/34156125/149042593-daaeac54-8c13-4f12-8804-09d55ad84ceb.png">

**Comment by Teranode** [comment]
Im getting this also on a fresh install

**Comment by keithn** [comment]
I just upgraded a project and I'm getting the same also.

**Comment by richardeschloss** [comment]
Fwiw, I am encountering this issue too and had to revert to nuxt 3.0.0-27365391.7479eac get back to a working state

**Comment by yamin90** [comment]
having same problem, it only happen on development, production seem working ok, revert back to previous release

**Comment by Teranode** [comment]
add this to your config:

```js
vite: {
    resolve: {
        mainFields: ['module', 'jsnext:main', 'jsnext']
    }
}
```

**Comment by misaon** [comment]
The problem occurred with me after merge https://github.com/nuxt/framework/pull/2636

**Comment by pi0** [comment]
Sorry for the inconvenience. Changes of #2636 are reverted until more investigation.
