### ISSUE TITLE
Error "exports are not defined" when using defineNuxtModule to export Vue library components

### ISSUE THREAD

**Issue by markteekman** [nuxt/framework#2683]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.16.1`
- Nuxt Version:     `3.0.0-27356801.e9128f3`
- Package Manager:  `npm@7.20.5`
- Bundler:          `Vite`
- User Config:      `buildModules`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@voormeerwaarde/vue-components-library/nuxt@0.12.0`
------------------------------

### Reproduction

https://codesandbox.io/s/nuxt-3-with-vue-library-components-vhq9d?file=/app.vue

### Describe the bug

When trying to use components imported from a Vue components library NPM package ([as explained here in the docs](https://v3.nuxtjs.org/docs/directory-structure/components/#library-authors)) it throws the following error: "Cannot start nuxt:  No "exports" main defined in /Users/markteekman/local/nuxt3-app-test/node_modules/@voormeerwaarde/vue-components-library/node_modules/@nuxt/kit/package.json".

This can be solved by using @nuxt/kit-edge instead of @nuxt/kit, but the docs example says to use @nuxt/kit.

### Additional context

This is the test NPM package that's being used as a library in the reproduction: https://www.npmjs.com/package/@voormeerwaarde/vue-components-library

**Comment by pi0** [comment]
Hi @markteekman. Sorry for lack up documentation about using kit in modules. In `vue-components-library/package.json` you should have something like this for `dependencies`:

```json
{
  "dependencies": {
    "@nuxt/kit": "npm:@nuxt/kit-edge@latest",
  }
}

**Comment by markteekman** [comment]
No problem @pi0, thanks for the explanation!
