### ISSUE TITLE
Server middlewear docs uncomplete. Missing next() function.

### ISSUE THREAD

**Issue by DarraghOFlaherty** [nuxt/framework#2688]
I believe the [docs for server middlewear](https://v3.nuxtjs.org/docs/directory-structure/server#server-middleware) are incomplete for Nuxt3. I believe the example code is missing the `next()` function call. Otherwise the middleware just hangs.

It's in this section of the [docs](https://v3.nuxtjs.org/docs/directory-structure/nuxt.config#servermiddleware) but I believe it should be in both places to avoid confusion.

I have a pull request ready for this, as long as I haven't overlooked something. First time contributing to OSS so tell me if I'm doing anything wrong.

**Comment by pi0** [comment]
Hi @DarraghOFlaherty. It would be nice to mention `next` possibility but this is a future of [h3](https://github.com/unjs/h3) async middleware if not having 3rd argument, it assumes when async promise resoves going to the next middleware.

**Comment by pi0** [comment]
Legacy middleware briefly mentioned in docs now https://v3.nuxtjs.org/guide/features/server-routes#return-a-legacy-handler-or-middleware
