### ISSUE TITLE
[nuxt-bridge / nuxt3] error? is prefetching components and pages in <head>

### ISSUE THREAD

**Issue by shinguweb96** [nuxt/framework#2691]
### Discussed in https://github.com/nuxt/framework/discussions/2690

Read discussion: https://github.com/nuxt/framework/discussions/2690
In production mode every vue pages/components get prefetch in head.

`<link type="module" rel="prefetch" href="/_nuxt/test-page-293c04c1.mjs"><link type="module" rel="prefetch" href="/_nuxt/test-component-2af6bc3c.mjs">`

**I am not calling them with nuxt-link.**
Test project: https://stackblitz.com/edit/nuxt3-custom-layout-qhbp4t

**Comment by mrChumi** [comment]
hi! didn't find any solution?
