### ISSUE TITLE
Hydration node mismatch in custom transition component

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt/framework#2700]
### Environment

- Operating System: `Darwin`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-27366343.1d741cb`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Repo: https://github.com/lukaszflorczak/nuxt3-demo
Branch: `test/transition-component`

Just run the project

### Describe the bug

I use some custom transition components with structure like that:

```vue
<template>
  <transition name="my-transition" @event="onEvent" ...>
    <slot/>
  </transition>
</template>
```

Then I use it this way:

```vue
<template>
  <my-transition>
    <my-component v-if="show"/>
  <my-transition>
</template>
```

As I remember it works without any problems in Nuxt 2, but now I get hydration warning:

<img width="717" alt="Zrzut ekranu 2022-01-13 o 09 56 25" src="https://user-images.githubusercontent.com/1818979/149298905-d855f585-9e54-4ba7-9be4-d8ca9cb3286d.png">

**Comment by jroxendal** [comment]
I had a similar problem and found that wrapping the transition with `<ClientOnly>` got rid of the error, so in your case:

```
<template>
  <ClientOnly>
    <my-transition>
      <my-component v-if="show"/>
    <my-transition>
  </ClientOnly>
</template>
```

**Comment by lukaszflorczak** [comment]
I found now also this and probable it's connected: https://v3.vuejs.org/guide/migration/transition-as-root.html#overview

I changed my components like that and now it works without hydration errors:

```
<template>
  <transition name="my-transition" @event="onEvent" ...>
    <div v-if="show">
      <slot/>
    </div>
  </transition>
</template>

<script setup>
  const props = defineProps({
    show: { type: Boolean, default: false }
  })
</script>
```

 Usage:

```vue
<template>
  <my-transition :show="show">
    <my-component/>
  <my-transition>
</template>
```
