### ISSUE TITLE
Components cannot be registered by Vue plugins

### ISSUE THREAD

**Issue by clemcode** [nuxt/framework#2709]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0`
- Package Manager:  `yarn@3.1.1`
- Bundler:          `Vite`
- User Config:      `modules`, `css`, `vite`
- Runtime Modules:  `@nuxt/ui`
- Build Modules:    `-`

### Reproduction

[Stackblitz](https://stackblitz.com/edit/github-xaivba?file=plugins%2Findex.js&terminal=dev)

`npm run build`
`npm run start`

### Describe the bug

See `plugins` folder in the repro

Expected : The component Test should be registered by `vuePlugin.js` 

Happening : The component is not registered correctly. I added a counter and a log to illustrate that the plugin function is called twice, once with `vueApp` passed as parameter, the second time with `nuxtApp` as parameter.

**Comment by danielroe** [comment]
[Amended repro](https://stackblitz.com/edit/github-xaivba-wvwxtq?file=lib%2FvuePlugin.js&terminal=dev) - looks like it was an issue with the component name (`Ntest` should be called as `<ntest>` - but if we want `<n-test>` we need to register as `NTest` instead).
