### ISSUE TITLE
Got an error when followed the getting started instructions on the official website

### ISSUE THREAD

**Issue by vhass** [nuxt/framework#2710]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.17.3`
- Nuxt Version:     `3.0.0-27367970.e0fec80`
- Package Manager:  `npm@8.3.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

A reproduction can be seen even from the link on the official website's installation instructions:
https://v3.nuxtjs.org/getting-started/installation 
more specifically here: https://codesandbox.io/s/github/nuxt/starter/tree/v3-codesandbox?file=/README.md

### Describe the bug

The dev server can't be started. A 500 error displays instead of the NuxtWelcome.

**Comment by ludo237** [comment]
Probably related to #2711

**Comment by vhass** [comment]
yeah, they are the same, and it is solved now. 

> Probably related to #2711
