### ISSUE TITLE
bundle renderer prefetches all chunks (even unused)

### ISSUE THREAD

**Issue by shinguweb96** [nuxt/framework#2713]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27265876.3cd4494`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt3-custom-layout-qhbp4t

### Describe the bug

In production mode all vue files (pages and components), also unused file, they come loaded in head tag.
In Nuxt2 only necessary files was loaded in a specific case.
In the test project I am not calling those files from Nuxt-Link, the files are just been created.

Example:
```
rel="prefetch" href="/_nuxt/test-page-ba5a07d3.mjs"
rel="prefetch" href="/_nuxt/test-component-56182cf8.mjs"
```

It happens on **bridge** and **nuxt 3**.

### Additional context

https://stackblitz.com/edit/nuxt3-custom-layout-qhbp4t
1. npm run build
2. npm run start
3. look html source-code, see prefetched js files in <head>

**Comment by shinguweb96** [comment]
[Fixed by #](https://github.com/nuxt/framework/pull/2067)

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/2237
