### ISSUE TITLE
No way of using dynamic images

### ISSUE THREAD

**Issue by Bryanoxx** [nuxt/framework#2715]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27366343.1d741cb`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/competent-monad-2dhl6?file=/app.vue

### Describe the bug

An image with a dynamic src attribute will not work, for example :
`<img :src="imgPath" />`

In Nuxt 2 the fix was to use `require(imgPath)` around the variable, but it does not exist under Nuxt 3 and the `import(imgPath)` or  `import.meta.globEager(imgPath)` don't work too.

There was already a [discussion](https://github.com/nuxt/framework/discussions/868) about this but no issue, that's why I'm creating it.

Thank you for the great work with Nuxt 3 🙏

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/1693
