### ISSUE TITLE
Switching `Vite.server.open` to false does not work

### ISSUE THREAD

**Issue by theArtechnology** [nuxt/framework#2720]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `0.0.0`
- Package Manager:  `unknown`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Inside `nuxt.config.ts` disable vite browser open feature on startup:
```json
 vite: {
        server: {
            open: false,
        }
 }
 ```

### Describe the bug

On my host machine, when disabling this feature, it keeps opening the URL.
On my docker environment, I received:

```
frontend_1  |  ERROR  [uncaughtException] spawn xdg-open ENOENT
frontend_1  | 
frontend_1  |   at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
frontend_1  |   at onErrorNT (node:internal/child_process:477:16)
frontend_1  |   at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by danielroe** [comment]
Would you provide a reproduction?

**Comment by theArtechnology** [comment]
There it is: https://github.com/theArtechnology/nuxt3-docker

**Comment by danielroe** [comment]
The reason it's opening is because you are telling it to do so at this line:

https://github.com/theArtechnology/nuxt3-docker/blob/main/Dockerfile#L19

Just change that:
```diff
- CMD ["yarn", "dev", "--", "-o"]
+ CMD ["yarn", "dev"]
```
