### ISSUE TITLE
You have to restart Nuxt to see a new page

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#2722]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27368185.a4f300b`
- Package Manager:  `npm@8.3.0`
- Bundler:          `Vite`
- User Config:      `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://user-images.githubusercontent.com/13822438/149491954-e3cacdc0-4d96-461b-a24f-1e6ca22b0c96.mov

### Describe the bug

Nuxt is not able to add a new page to the router. When you create an `index.vue` file inside a folder (`dashboard/index.vue` for example) and have Nuxt started, Nuxt restarts but doesn't get the path. You have to restart it manually for the path to appear.

**Comment by danielroe** [comment]
let's follow this on https://github.com/nuxt/framework/issues/1367
