### ISSUE TITLE
Requested module does not provide export named 'default'

### ISSUE THREAD

**Issue by abdulhadi-lababidi** [nuxt/framework#2733]
### Environment

- Node Version: v14.16.0
- Nuxt Version: 3.0.0
- Package Manager: npm@7.17.0
- Bundler: Vite

### Reproduction

here you can see a very simple reproduction link
https://stackblitz.com/edit/github-nl4dyg?file=app.vue

```npm run dev```

### Describe the bug

I'm trying to use [class-validator](https://www.npmjs.com/package/class-validator) packages.
first I faced a problem  [mentioned here](https://v3.nuxtjs.org/concepts/esm/#what-kinds-of-problems-can-there-be) and solved it by adding this package to ``` build.transpile ``` in ```nuxt.config.ts``` file.

then this error starts to show up
```SyntaxError: The requested module '/_nuxt/node_modules/validator/lib/isLatLong.js?v=cba03522' does not provide an export named 'default'```
_the validator package is one of class-validator dependencies._

### the weird part is that the code runs perfectly on the server process
and the error only occurs on the browser 
and it works fine on both server and browser in production mode!

**Comment by danielroe** [comment]
This seems to be solved by disabling 'optimizeDeps' on this module:

```js
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  build: {
    transpile: ["class-validator"],
  },
  vite: {
    optimizeDeps: {
      exclude: ['class-validator']
    }
  }
})
```

**Comment by abdulhadi-lababidi** [comment]
> This seems to be solved by disabling 'optimizeDeps' on this module:
> 
> ```js
> import { defineNuxtConfig } from 'nuxt3'
> 
> // https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
> export default defineNuxtConfig({
>   build: {
>     transpile: ["class-validator"],
>   },
>   vite: {
>     optimizeDeps: {
>       exclude: ['class-validator']
>     }
>   }
> })
> ```

NO it's not, the problem still exits
please try it on the [Reproduction link](https://stackblitz.com/edit/github-nl4dyg?file=app.vue)
it's still just working on the server process
here you can see the output at stackblitz:
![image](https://user-images.githubusercontent.com/88906061/149631593-2b001d85-0ecd-4986-8a3f-b159ac057ac6.png)

**Comment by abdulhadi-lababidi** [comment]
I found a workaround for this issue by using Webpack instead of Vite.

you can [enable Webpack](https://github.com/nuxt/framework/discussions/2740#discussioncomment-1979072) by setting vite to false in nuxt.config.ts
```
export default defineNuxtConfig({
  vite: false
})
```

but you should remove the ```class-validator``` package from ```build.transpile```

**Comment by leoolivier** [comment]
Is there any progress about using `class-validator` with Nuxt 3 and Vite?

**Comment by Luferov** [comment]
Same problem. I've built the types using the openApi but I can't import them.
Use zero configuration with Vite.

![image](https://user-images.githubusercontent.com/26242554/176297799-cff1d0af-34ef-447d-aec6-318b30b10e72.png)

**Comment by Luferov** [comment]
Webpack works good, but added pug, pug-plain-loader, vue-demi... Vite better then webpack, but should works.

**Comment by slavco86** [comment]
Same here - can we please get an update if this is being looked at?
Shame not to be able to use Nuxt3 for large scale apps, which benefit greatly from Class Validator package.
@danielroe ?

**Comment by PFY1213** [comment]
nuxt.config.ts 
build: {
		transpile: ['element-plus/es'],
	},

**Comment by ArjunAtlast** [comment]
I am still facing similar issue with `@amcharts/amcharts5` package when using the map polygon series.

# Environment:
- Node: 16.15.1
- Nuxt: 3.0.0-rc.11
- Package Manager: npm 8.11.0
- Bundler: vite

# Reproduction
Please checkout this reproduction link
https://stackblitz.com/edit/github-nl4dyg-lpawak

`npm run dev`

# Describe the bug

I'm trying to use [@amcharts/amcharts5](https://www.npmjs.com/package/@amcharts/amcharts5) to create a world map chart similar to the one described [here](https://www.amcharts.com/docs/v5/charts/map-chart/map-polygon-series/).
I placed the amcharts library in `build.transpile` in `nuxt.config.ts`.

This error shows up in the client:

```
MapPolygon.ts:6 Uncaught SyntaxError: The requested module '/_nuxt/node_modules/polylabel/polylabel.js?v=3340e452' does not provide an export named 'default' (at MapPolygon.ts:6:8)
```

I inspected the `polylabel.js` file and it does have an export named default. I came across this issue and it has all similarities. 

The code builds without issue and works perfectly in production mode. The problem only exists in the development mode just like this issue mentioned here.

**Comment by danielroe** [comment]
Check out https://vitejs.dev/config/dep-optimization-options.html#dep-optimization-options.

**Comment by ArjunAtlast** [comment]
@danielroe Thank you. Added these settings to vite config and it is working fine now:

```
optimizeDeps: {
  exclude:['@amcharts/amcharts5', '@amcharts/amcharts5-geodata'],
  include: ['@amcharts/amcharts5-geodata > polylabel']
},
```
