### ISSUE TITLE
publicRuntimeConfig not evaluated at runtime

### ISSUE THREAD

**Issue by Xowap** [nuxt/framework#2745]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27369360.33ebb01`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `head`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I've created a repo with[ two identical projects](https://github.com/Xowap/nuxt-runtime-config), except one is Nuxt 2 and the other is Nuxt 3. The Nuxt 2 project behaves as I would expect while the other one does not.

In order to run the test, from the respective root of each project:

```
docker build -t runtime-nuxt2 --pull .
docker run -p 3000:3000 -e FOO=bar -it runtime-nuxt2
```

```
docker build -t runtime-nuxt3 --pull .
docker run -p 3000:3000 -e FOO=bar -it runtime-nuxt3
```

Then you can visit http://localhost:3000 in order to see a dump of the `$config`.

### Describe the bug

If you visit http://localhost:3000 for each project, you'll quickly realize that `FOO` is read in the Nuxt 2 project but not in the Nuxt 3 project.

Effectively, this means that the runtime config is not read at runtime, which is kind of breaking my build pipeline (since configuration is unknown at time of build).

I hope this can be resolved :)

**Comment by danielroe** [comment]
The key difference with Nitro is that you can only override runtime config with the same name as the environment variable. For example:

```js
export default defineNuxtConfig({
  publicRuntimeConfig: {
    BASE_URL: process.env.BASE_URL
  },
  privateRuntimeConfig: {
    API_SECRET: process.env.API_SECRET
  }
})
```

More info: http://v3.nuxtjs.org/docs/usage/runtime-config#environment-variables

**Comment by Xowap** [comment]
Ah well. Thanks for the fix. That's completely misleading though, the documentation says:

> Tip: While it is not necessary, by using identical runtime config names as env variables, you can easily override them in production using platform environment variables.

What I understand there is that it's "not necessary" to name the variable the same way.

If I might suggest a way for other people to not lose hours on this:

- Either remove the limitation
- Either state it explicitly in the documentation using a blinking red background

What do you think?
