### ISSUE TITLE
Suspense defineAsyncComponent issue

### ISSUE THREAD

**Issue by gijsroge** [nuxt/framework#2766]
### Environment

```
RootDir: /home/projects/github-augpmj
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27265876.3cd4494`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-augpmj?file=pages/sub.vue

The link does not work, you should go directly to **/sub** to see the error.

### Describe the bug

It seems like `defineAsyncComponent` is not supported with the current Nuxt setup? I don't have much more to add, repro link should be straight forward.

Error that is thrown: 
```
Cannot read properties of null (reading 'suspense')
```

Maybe this is still w.i.p. just wanted to let you know.

**Comment by danielroe** [comment]
There are a couple issues with how you were using the async component. Most importantly, it takes a component import and not an image asset. It also needs to be wrapped in a suspense boundary. See [working stackblitz](https://stackblitz.com/edit/github-augpmj-oeqycn?file=pages%2Fsub.vue).

**Comment by gijsroge** [comment]
@danielroe Thanks, I know, the image should have been a component through a vite svg loader plugin, my bad. 

But wrapping it with another `<suspense>` would cause it to render only on the client would it not? I would assume that if you don't wrap it, it should keep the root `<suspense>` in pending mode, causing it to SSR?

**Comment by danielroe** [comment]
Seems like an issue with the vue context. If you import from `vue`, or omit the import and trust auto-imports, all is well.

https://stackblitz.com/edit/github-augpmj-kdkcwb?file=pages%2Fsub.vue

**Comment by gijsroge** [comment]
@danielroe ah I see yes, `@vue/runtime-core` [should not be used indeed](https://www.npmjs.com/package/@vue/runtime-core#:~:text=This%20package%20is%20published%20only%20for%20typing%20and%20building%20custom%20renderers.%20It%20is%20NOT%20meant%20to%20be%20used%20in%20applications.). My editor just auto imported this from there :shrug: 

Thanks, works fine now.
