### ISSUE TITLE
nested plugins are no longer auto imported

### ISSUE THREAD

**Issue by peteromano** [nuxt/framework#2780]
### Environment

Nuxt CLI v3.0.0-27369360.33ebb01                                                                                                                                                                                  

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.6`
- Nuxt Version:     `3.0.0-27369360.33ebb01`
- Package Manager:  `unknown`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

^ This is NOT the breaking version; one of the latest versions between this version and latest is breaking.

### Reproduction

No idea.

### Describe the bug

I have 0 leads as to what is wrong... I have a companion Storybook app where urql and auth is all working correctly. After a fresh npm install today, Nuxt COMPLETELY blows up:

Can't find $urql, function on my $auth are undefined (these errors come from SSR-side), the layout doesn't appear to be working (my header component doesnt load and NuxtWelcome doesnt load, but the slot/page renders), and 0 client errors.

Rolling back to v3.0.0-27369360.33ebb01 and it works again..

Did somebody break layouts or providers?

IMO: **THIS NEEDS TO BE INVESTIGATED AND FIXED ASAP.** Literally all of Nuxt is broken.

Looking through PRs, but triaging is virtually impractical since tons of PRs were merged yesterday.

**UPDATE:** Real bug: `$auth` provider is now `undefined` after latest releases, so provider registration doesn't work anymore.

**Comment by sewalsh** [comment]
Have you tried deleting your `node_modules`?

For the layout issue, you must now use `definePageMeta`. https://v3.nuxtjs.org/docs/directory-structure/layouts

**Comment by peteromano** [comment]
@sewalsh Ok, so 2 issues: The layout issue (solved thanks to you), but **one of the releases in the past 2 hours breaks** the providers.

I have been blowing away and reinstalling node modules for the past 2 hours btw.

**Comment by peteromano** [comment]
Linking for reference: https://github.com/nuxt/framework/discussions/2639#discussioncomment-1926482

@danielroe Mentioned using 

```
export default defineNuxtPlugin(() => {
  return {
    provide: {
      auth: useAuth0(options)
    }
  }
})
```

Which _did_ work.. And `inject` didn't because inject is not a function.

**Comment by peteromano** [comment]
Ok, as of 3.0.0-27375406.8588f74, this still works:

```
  return {
    provide: {
      auth: useAuth0(options)
    }
  }
```

**Comment by peteromano** [comment]
And for the record, i would consider these "breaking" changes, despite beta, and we need a way to communicate these kinds of changes (i would imagine in GH Discussions!)

I check Discussions like every day, so it hurts my head to think changes like these aren't announced...

**Comment by peteromano** [comment]
Should we do this now instead?

`vueApp.config.globalProperties.$auth = useAuth()`

**Comment by danielroe** [comment]
It is likely this: https://github.com/nuxt/framework/pull/2774, which only recognises top level files (and index files in subdirectories) when auto scanning plugins.

You can browse a list of commits after running `npx nuxi upgrade` by clicking the URL it gives you.

I very much appreciate that you are using the beta version of Nuxt, with all that means. I appreciate it and recognise that this must be inconvenient to you.

I would recommend locking the version of Nuxt you use (rather than `latest`) so that you can deal with changes at a time of your choosing.

**Comment by peteromano** [comment]
@danielroe I can't use the lockfile unfortunately for very specific reasons.

Very much appreciate the response as well, btw.

BUT, the fact remains that that PR still broke something that should be working.. I'm not doing anything special on the Nuxt side of things, why would that PR affect provider registration from plugins?

**Comment by peteromano** [comment]
I just confirmed, on latest, that my plugins arent being loaded at all, that's the problem.

**Comment by peteromano** [comment]
My plugins directory **is being symlinked** to /plugins/apps/myApp/plugin1.ts etc. 

So .... please bring back that functionality, otherwise i have to abort using nuxt entirely...... That PR i guess breaks following symlinks

**Comment by peteromano** [comment]
@danielroe @pi0 Do we have a say in features here? This new featurew of only top level plugins not only undoes work ive done in 2 months, but makes it virtually impossible for what im trying to accomplish, NO OTHER nuxt directories work this way... Why is that PR needed?? What was broken about plugins directory?? 

PLEASE PLEASE PLEASE bring back the original behavior, if this isnt something that users specifically requested!

**Comment by peteromano** [comment]
Why can't we just bring back `**/*`? And symlinking would still need to work, in this case. @danielroe @pi0

**Comment by peteromano** [comment]
THIS: https://github.com/nuxt/framework/pull/2774#issuecomment-1015931470

**Comment by peteromano** [comment]
What's the story /status with this? Do I need to abandon nuxt or what?

**Comment by pi0** [comment]
Dear @peteromano I can understand your frustration of change but please consider there were good merits that we first introduced auto scan for `plugins/` directory in Nuxt 3 and then limited it to top-level to allow keep nested folders for utilities (this is a common pattern many other projects was already relying on). 

Would you mind please creating a small reproduction repo of your current setup using symlinks? We might find a better solution for you while keeping the current change or provide a flag/option if it makes sense for a general usecase.

**Comment by peteromano** [comment]
@pi0 Its really just symlinkg, i.e.,:

`/somePackage/plugins -> /plugins/packages/somePackage`

I get what youre saying, but then how would hot reloading work when working on a package's plugin? That might still be enough reason to have to fork if that cant work.

Ill try using the plugins array, but dont see any nuxt3 docs for them -- imperatively registering plugins would work with hot reloading?

**Comment by danielroe** [comment]
@peteromano Here's an example of what you could do to auto-register all files within your directories - no symlinking required, in fact: [stackblitz](https://stackblitz.com/edit/github-sjceku?file=nuxt.config.ts&terminal=dev).

Hot reloading should work just as it does with the plugins directory.

**Comment by danielroe** [comment]
I'm going to ... tentatively ... close this issue. 🙏

Details of the breaking change and workaround are now found at https://github.com/nuxt/framework/discussions/2883.
