### ISSUE TITLE
Is useMeta() bugged?

### ISSUE THREAD

**Issue by ryanaltvater** [nuxt/framework#2785]
### Discussed in https://github.com/nuxt/framework/discussions/2729

<div type='discussions-op-text'>

<sup>Originally posted by **ryanaltvater** January 14, 2022</sup>
```
<script>
export default {
    setup () {
        useMeta({
            title: 'ABC123',
            bodyAttrs: {
                class: ''
            }
        })
    }
};
</script>
```

I'm using the code above to set individual page titles. When I spin up the site locally, each page shows their respective meta title. The problem is when I update a title and save, the page refreshes and renders blank. When I manually click refresh, the page renders correctly. If I remove the code above and make any changes to the page, it refreshes and renders perfectly fine. It's only when the code above exists and I update the page title or body class that the page renders blank upon dynamic refresh. Wondering if this code is causing an issue or not, and I'm just not sure. Thanks for the help in advance!</div>

**Comment by multiplehats** [comment]
I'm running into the same issue. It seems like it's rendering client side, but not server side. And sometimes it does. I don't know, can't exactly pinpoint it

**Comment by danielroe** [comment]
I'm going to close this to follow in #2730. If that issue doesn't exactly match yours, would you create a new one with a reproduction and following the issue form?
