### ISSUE TITLE
Choose what type of router

### ISSUE THREAD

**Issue by VincentThomas06** [nuxt/framework#2787]
Hi Devs! I love NuxtJs and the file structure it has! There is only few slight issues for me. I'm coming from an angular background and love the angular router, its not a file-based router tho. This would be the absolute best framework if you could make the dev decide if they want to use the file-based router or like angular-router & vue-router. If you decide to inplement this feature that would be really nice for other people that comes from angular and me 😀. I know this is allot to ask, but i really believe this will up the DX! Cheers 😊

**Comment by richardeschloss** [comment]
It's already implemented in nuxt kit with `extendPages`. You can choose to structure routes in the pages directory and/or use `extendPages` exposed by their API.

**Comment by VincentThomas06** [comment]
Can i use nuxt kit with nuxt 3?

**Comment by richardeschloss** [comment]
Yes. It comes with nuxt3. It will be in " node_modules/@nuxt/kit". The most common use would probably be to use that kit in a module. In Nuxt3, the method is `extendPages`.

**Comment by VincentThomas06** [comment]
Sorry i can't find the method, i looked in the next.config.ts but it did not work. How do get manual routing?

**Comment by richardeschloss** [comment]
This framework is NuxtJS, so the config file you would use is nuxt.config.js or nuxt.config.ts not next.config.ts. If you want to use manual routing, first you have to make sure you installed nuxt3 and not nuxt (`npm i nuxt3`). Installing nuxt3 will also install @nuxt/kit, which exposes an API you can use for extending pages (formerly called "extendRoutes", it's now "extendPages"). So you could use that method directly, and that would be the most manual way to go, however, there is something easier...

The kit also calls a hook called "pages:extend" which you can listen for in your nuxt.config:

```js
export default defineNuxtConfig({
  hooks: {
    'pages:extend'(pages) {
      /* here, pages will be of type NuxtPage[] */
      pages.push(/* Page */) // <-- extend the pages here
    }
  }
})
```
The schema it expects is [`NuxtPage`](https://github.com/nuxt/framework/blob/c80870ad8c4a1c1b044d7a5ae27e41e997f8a75f/packages/schema/src/types/hooks.ts#L36)

**Comment by VincentThomas06** [comment]
Thanks!
