### ISSUE TITLE
The requested module does not provide an export named 'meta'

### ISSUE THREAD

**Issue by richardeschloss** [nuxt/framework#2788]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27375427.d07d572`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `ssr`, `vite`, `css`, `target`, `head`, `buildModules`, `stories`, `telemetry`
- Runtime Modules:  `-`
- Build Modules:    `~/lib/module.js`
------------------------------

### Reproduction

Use `extendPages` with or without providing meta, and this error will be encountered.

```js
extendPages({
  name: 'myRoute,
  path: `/myRoute`,
  file: myRouteComponent, // export default { render () { ... } }
  meta: {} // <-- with or without this, error is encountered
})
```

### Describe the bug

As alluded to in #2678, if the component does not export `meta`, the error "The requested module does not provide an export named 'meta'" will occur. The workaround is to do `export const meta = {}`. 

### Additional context

I can't seem to find any updates to the automated tests in that merge request. If tests exist, can someone please point me in the right direction?

**Comment by richardeschloss** [comment]
I appreciate the PR. It works only  for .vue components, but not .js components. Can you please re-open this?

**Comment by danielroe** [comment]
What makes you think it doesn't work for .js? Do you have a repro?

**Comment by richardeschloss** [comment]
Yeah I have a repro. Let me try to port it to stackblitz.

**Comment by richardeschloss** [comment]
I have a repro. I just updated to 3.0.0-27376999.6abf75d and I'm encountering the error. Is this MR included in that version or a later one?

The repro is:
```js
extendPages({ // in lib/module.js 
  name: 'myRoute',
  path: `/myRoute`,
  file: myRouteComponent, // export default { render () { ... } }
  meta: {} // <-- with or without this, error is encountered
})
```

Then inside a .js component (myRouteComponent.js):
```js
// meta not defined
export default {
  render () { ... } // For simplicity, keep it empty
}
```
The error will occur.

However, inside a .vue component (myRouteComponent.vue)
```html
<template>
  <div></div>
</template>

<script>
export default {} // works without error.
</script>
```

I know it seems insignificant, but the reason I'm making such a push for the ".js" way is that it makes automated testing, especially for coverage, much faster and easier.

**Comment by danielroe** [comment]
@richardeschloss I can't reproduce it. Here's a repro that's working fine: https://github.com/danielroe/extend-routes. It might be that you have an older version of `@nuxt/kit`?

If you are able to tweak it so you experience this issue, and open a new issue with a reproduction, that would be very kind. 🙏

**Comment by richardeschloss** [comment]
ok thanks. I'm currently troubleshooting to see what the exact differences are.

**Comment by richardeschloss** [comment]
I figured out what the bug is. `export const meta = {}` if it is written in the component but *commented out*, it still gets analyzed as being in the component, but then since the component is not actually exporting that (it's commented out), the transformer gets confused and throws the error mentioned above.
