### ISSUE TITLE
Nuxt3 no longer honors the `layout` property in Options API structured components

### ISSUE THREAD

**Issue by richardeschloss** [nuxt/framework#2789]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27375427.d07d572`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `ssr`, `vite`, `css`, `target`, `head`, `buildModules`, `stories`, `telemetry`
- Runtime Modules:  `-`
- Build Modules:    `~/lib/module.js`
------------------------------

### Reproduction

The following was working just yesterday, but now it isn't:

```js
export default {
  layout: 'custom',
  render() { ... }
}
``` 

Custom layout won't be rendered. Instead, this will work: (for those that use render functions instead of templates)
```js
export const meta = {
  layout: 'custom'
}

export default {
  render() { ... }
}
```

### Describe the bug

The old way of specifying layouts no longer works, but it's simplicity was very nice. It's very possible that a lot of your existing users who want to go from Nuxt 2 to 3 will want their existing layouts to just work without having to search all their components and update them.

**Comment by danielroe** [comment]
You should now define route metadata like this:

```
definePageMeta({
  layout: 'custom'
})
```

It's important that this isn't on the component options because it's a route-level property - for example, a nested page can set the layout, which should override the layout option of its parent page. See https://github.com/nuxt/framework/discussions/2468 for more about the justification.

**Comment by richardeschloss** [comment]
If a nested page wants to set the layout, wouldn't that make it a page/component property? It's the page that precisely cares about what layout to use. Consider the following use case, which may be encountered by @nuxt/ui:

Suppose you want to design some multi-device viewer, and you want to easily toggle between 5 different layouts. I imagine such a component would have a dropdown tied to the layouts property, and changing that one property would let you see the different layouts. Wouldn't changing that single property be easier than this: https://v3.nuxtjs.org/docs/directory-structure/layouts#example-changing-the-layout . Compare that to [2.x custom layouts](https://nuxtjs.org/docs/directory-structure/layouts#custom-layout) which seems to be easier to use. Less coding to accomplish the same task.

It's very possible your approach is the better one, but there may be use cases we haven't thought about where people will still want the former way to work. You even said in the discussion you'd want to support in both and yes, that would be a huge benefit because millions of 2.x users who want to upgrade to 3.x won't experience as much friction.

**Comment by danielroe** [comment]
The point is that you may have a parent page, e.g. '~/admin/index.vue` that sets a layout that should be inherited by all children. So the children may have no explicit layout property.

We can definitely improve the DX of changing the layout - I think it may be sensible to force it to be a ref, for example, and possibly add a `setLayout`or `useLayout` composable.
