### ISSUE TITLE
Build error on fresh Nuxt Bridge project

### ISSUE THREAD

**Issue by Tiagogv** [nuxt/framework#2790]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27375427.d07d572`
------------------------------

### Reproduction

https://codesandbox.io/s/github/nuxt/starter/tree/v2-bridge-codesandbox

### Describe the bug

Running bridge on a fresh Nuxt 2 project leads to build error: 

` 
ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'length')                                              
  at normalizeLayer (node_modules/h3/dist/index.mjs:625:36)
  at use (node_modules/h3/dist/index.mjs:580:20)
  at Function.app.use (node_modules/h3/dist/index.mjs:567:35)
  at createDevServer (node_modules/@nuxt/nitro/dist/index.mjs:1796:7)
  at createNuxt2DevServer (node_modules/@nuxt/bridge/dist/chunks/module.mjs:269:18)
  at setupNitroBridge (node_modules/@nuxt/bridge/dist/chunks/module.mjs:163:19)
  at setup (node_modules/@nuxt/bridge/dist/chunks/module.mjs:1054:13)
  at ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:501:29)
`

**Comment by MrDizzystick** [comment]
Downgrading and pinning "@nuxt/bridge" to 3.0.0-27375411.b38e394 ("npm:@nuxt/bridge-edge@3.0.0-27375411.b38e394") appears to fix this for me, for what it's worth.

**Comment by Ttou** [comment]
same problem

**Comment by LouieRichardson99** [comment]
> Downgrading and pinning "@nuxt/bridge" to 3.0.0-27375411.b38e394 ("npm:@nuxt/bridge-edge@3.0.0-27375411.b38e394") appears to fix this for me, for what it's worth.

Thank you! This seemed to solve my issue too.

**Comment by Feelixe-tin** [comment]
> Thank you! This seemed to solve my issue too.

Same problem, that worked. Thank you.

**Comment by Feelixe-tin** [comment]
> Downgrading and pinning "@nuxt/bridge" to 3.0.0-27375411.b38e394 ("npm:@nuxt/bridge-edge@3.0.0-27375411.b38e394") appears to fix this for me, for what it's worth.

Hade same problem, that solved it, thank you.

**Comment by danielroe** [comment]
For now, a workaround is:

```js
export default defineNuxtConfig({
  app: {
    baseURL: '/'
  }
})
```
