### ISSUE TITLE
vite hmr isn't working

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#2794]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27375427.d07d572`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `buildModules`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

https://github.com/productdevbook/nuxt3-app

### Describe the bug

iam change pages/index.vue but dont reload change. Iam custom chrome reload http://localhost:3000/ but dont change code some problem :/

**Comment by productdevbook** [comment]
dont fix some problem

**Comment by danielroe** [comment]
@productdevbook Could you raise an issue?

**Comment by productdevbook** [comment]
1. now update library, iam index change code or text and chrome refresh dont refresh. 
2. nuxt very slow dev. It turns on after restarting 2-3(yarn dev) times.
