### ISSUE TITLE
different default scrollBehavior that resets page scroll on navigation

### ISSUE THREAD

**Issue by fanckush** [nuxt/framework#2817]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v17.3.1`
- Nuxt Version:     `3.0.0-27369360.33ebb01`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `vite`, `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

No reproduction needed imo

### Describe the bug

When navigating using a `<NuxtLink to="/othePage" />` the page scroll is not resetting.
In other words, the page does not `scrollToTop` on route change

**Comment by K-Honkawa** [comment]
It may be solved by installing a plugin for router.

https://github.com/nuxt/framework/issues/1707#issuecomment-961983939

**Comment by fanckush** [comment]
@K-Honkawa thanks! i'll try that but the default behaviour should be to reset the scroll so i'll keep this open as a bug

**Comment by K-Honkawa** [comment]
I don't think this is a Nuxt3 issue as NuxtLink is RouterLink in `vue-router` and is the default behavior of vue-rouer.

>  https://github.com/nuxt/framework/blob/c80870ad8c4a1c1b044d7a5ae27e41e997f8a75f/packages/nuxt3/src/pages/runtime/router.ts#L20

**Comment by fanckush** [comment]
That could be the case but it is possible that NuxtLink extends RouterLink and overrides it's behaviour

**Comment by daver987** [comment]
Any news on this issue, or is there a quick fix to get pages to scroll to top on page change. :)

**Comment by danielroe** [comment]
@daver987 See above: https://github.com/nuxt/framework/issues/2817#issuecomment-1017155226

**Comment by jamaluddinrumi** [comment]
and in case you wanna add a bit delay, you can check it out

https://github.com/nuxt/framework/discussions/1661#discussioncomment-2159828

**Comment by danielroe** [comment]
This is now configurable with https://github.com/nuxt/framework/pull/3485. See https://v3.nuxtjs.org/docs/directory-structure/pages#router-options for documentation.

**Comment by fanckush** [comment]
@danielroe awesome! this should replace the workaround mentioned above https://github.com/nuxt/framework/issues/2817#issuecomment-1017155226
but if my understanding is correct it doesn't fix the default behavior which is originally described in this issue. If that's the case then I won't close this just yet

**Comment by Bodokh** [comment]
I tried adding a plugin do change the scroll behavior like so:
`export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.$router.options.scrollBehavior = () => {
      return { left: 0, top: 0 }
    }
  });`

Works when running "nuxi dev"
But when running using "nuxi build" and "nuxi preview" It does not work.

**Comment by richgcook** [comment]
What is slightly undesirable about the `router.options.ts` option is that when using page transitions, you see the scroll to top on the current page before the current page fades out, for example. I'm wondering if there's an option to connect this with specific page transitions so it jumps to the top of the page as the current page has faded out but but the new page fades in.

```
export const usePageTransitionConfig = {
	mode: 'out-in',
	appear: true,
	css: false,
	onEnter(el, done) {
		loaderStore.value.isActive = false
		gsap.fromTo(el, {
			autoAlpha: 0,
			duration: 0.5
		}, {
			autoAlpha: 1,
			duration: 0.5,
			onComplete: done
		})
	},
	onLeave(el, done) {
		loaderStore.value.isActive = true
		gsap.fromTo(el, {
			autoAlpha: 1,
			duration: 0.5
		}, {
			autoAlpha: 0,
			duration: 0.5,
			onComplete: done
		})
	}
}
```

**Comment by fanckush** [comment]
heads up, the PR #3851 just got merged 🎉

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

Let me know if not and I'll reopen.
