### ISSUE TITLE
allow `redirect()` from nuxtApp

### ISSUE THREAD

**Issue by folamy** [nuxt/framework#2856]
### Environment

Nuxt 3

### Reproduction

Have redirect() from in useNuxtApp()

### Describe the bug

We have **redirect()** in nuxt 2 [Context](https://nuxtjs.org/docs/internals-glossary/context/#the-context), but it's missing in nuxt 3
Is there a workaround for this feature?

**Comment by folamy** [comment]
@danielroe, thanks for the response on this!

**Comment by shinguweb96** [comment]
Missing error() too!
