### ISSUE TITLE
(Nuxt Bridge) building for production successfully starts the server, but the server wont accept any requests

### ISSUE THREAD

**Issue by Jay-Madden** [nuxt/framework#2860]
### Environment

RootDir: /Users/jaymadden/programming/projects/ClemBot/ClemBot.Site
Nuxt project info:

------------------------------
- Operating System: `Darwin (MacOs 12.1 M1 ARM)`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `server`, `publicRuntimeConfig`, `privateRuntimeConfig`, `head`, `axios`, `auth`, `css`, `plugins`, `components`, `buildModules`, `modules`, `bridge`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/auth-next@5.0.0-1642755117.7a526bb`, `nuxt-buefy@0.4.14`
- Build Modules:    `@nuxtjs/dotenv@1.4.1`, `@nuxt/bridge@3.0.0-27379487.e0cf2d7`
------------------------------

### Reproduction

Clone and build this site from the nuxt-upgrade branch https://github.com/Jay-Madden/ClemBot/tree/nuxt-upgrade/ClemBot.Site and run `yarn build && yarn start` and try to go to to the locally hosted preview

### Describe the bug

Nitro production server starts up but will not accept any requests. Either from browser or from a simple cURL
![image](https://user-images.githubusercontent.com/25359755/150592913-0f339559-fafa-4f0d-95c2-057e0dca7e23.png)

### Logs

```shell
No debug or log output is seen
```

**Comment by danielroe** [comment]
I would update your runtimeConfig as follows (fyi):

```js
  publicRuntimeConfig: {
    DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
    OAUTH_PERMISSIONS: process.env.OAUTH_PERMISSIONS,
    DEFAULT_PREFIX: process.env.DEFAULT_PREFIX,
  },
  privateRuntimeConfig: {
    DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
  },
```

(This is needed at the moment to support truly runtime configuration.)

However, I can't reproduce your issue - I just get an error (`Getting public guild stats failed`). Would you create a more minimal reproduction that will reproduce the error when I clone it? 🙏

**Comment by Jay-Madden** [comment]
Hi @danielroe, 
I can reproduce this reliably on my machine with a bare minimum nuxt3 installation from the docs as well as a nuxt-bridge installation. 

Here is a repo that fails to accept any requests on my machine when the server is built with yarn build. yarn dev works fine. 
https://github.com/Jay-Madden/nuxt-repro

Commands run:
```
npx nuxi init nuxt3-app
cd nuxt3-app  
yarn install  
yarn build
yarn start 
```

![image](https://user-images.githubusercontent.com/25359755/150617665-682fd765-1f4d-48a8-a569-a4b9a5298073.png)

**Comment by danielroe** [comment]
I cannot reproduce this with node 16.13.0 and that repository. I feel it must be something specific with your computer/setup. What's the output of `pwd` in the directory where you have your project? Is there any other server running on your machine? (Try running `lsof -i :3000`.) Does it work if you run `PORT=4000 yarn start`?

**Comment by Jay-Madden** [comment]
Yep this was a pebcak problem, i had a random process on that port. Thank you for your help
