### ISSUE TITLE
AWS Amplify generates runtime crash

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/framework#2874]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27366343.1d741cb`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `typescript`, `css`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@7.5.3`
------------------------------

### Reproduction

I tried to provide a minimal reproduction in [this](https://codesandbox.io/s/affectionate-cloud-lnub8?file=/app.vue) sandbox instance, although I cannot really understand how it works.

I'm providing in that environment some testing configurations for the convenience of the developers, I will shut them down when the problem is solved.

### Describe the bug

When using @aws-amplify/auth for connecting to an AWS Cognito user pool, nuxt provides a runtime error very hard to debug. (See below).

In general, it would be very nice to have a more informative stacktrace about these kinds of issues.

### Logs

```shell
Stacktrace of the bug

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\..\repo\url' imported from C:\Users\..\repo\.nuxt\dist\server\server.mjs
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:416:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ESMLoader.import (node:internal/modules/esm/loader:276:22)
    at importModuleDynamically (node:internal/modules/esm/translators:111:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at $id_28e5ebab (file:///C:/Users/../repo/.nuxt/dist/server/server.mjs:13500:233) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
```

**Comment by rvmourik** [comment]
Hi, I am having the exact same issue. Not only the url but several packages that come from amplify are not properly resolved.

**Comment by ennioVisco** [comment]
I finally was able to solve the issue, thanks to https://github.com/nuxt/framework/discussions/2308, to https://github.com/nuxt/framework/issues/2070#issue-1059957544, and to [nuxt3 docs](https://v3.nuxtjs.org/concepts/esm#transpiling-libraries), I'll summarize the solution here, of which you can see a minimal reproduction in [this sandbox environment](https://codesandbox.io/s/rough-sunset-wqnvsl?file=/app.vue).
### Step 1 - Polyfill definition:
Include a polyfill like in https://github.com/nuxt/framework/issues/2070#issue-1059957544, (a typical location is `public/js/polyfill.js`, but any other is fine as long as you update the paths accordingly) with the following content:
```js
// public/js/polyfill.js
if (global === undefined) {
    var global = window;
}
```
### Step 2 - Polyfill inclusion:
Include the polyfill as a loaded script at the main entry point of your app, a typical example is shown here for a basic `app.vue`:
```vue
<!-- app.vue -->
<template>
  <div>
    <Script src="./js/polyfills.js" />
    <!-- content here --> 
  </div>
</template>
```
### Step 3 - Plugin setup:
Add the information for setting up an Amplify plugin. The following shows a typical usage for just the `Auth` module of Amplify, other can be added similarly. Note also that this steps assumes an `aws-exports.ts` file at the root of your nuxt3 app containing the settings for Amplify, an example can be found in the sandbox environment at the beginning of this post, otherwise refer to the [official Amplify documentation](https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource) for the details.
```ts
// plugins/amplify.ts
import { defineNuxtPlugin } from '#app';

import awsConfig from '../aws-exports';
import { Amplify } from '@aws-amplify/core';
import { Auth } from '@aws-amplify/auth';

export default defineNuxtPlugin(nuxtApp => {
    Amplify.configure(awsConfig);

    return {
        provide: {
            auth: Auth,
        },
    };
});

```
### Step 4 - Transpiling: 
Set the nuxt config to transpile the `amazon-cognito-identity-js` dependency  of the `aws-sdk`:
```ts
// nuxt.config.ts
export default defineNuxtConfig({
    // ... 
    build: {
        transpile: ['amazon-cognito-identity-js'],
    },
    // ... 
})
```
___
That's it for the setup, now it can be used in various way. Note, however, as pointed out in https://github.com/nuxt/framework/discussions/2308, that plugin dependencies might not be available at setup time, so two usages approach can be considered. I show here an example for an `authenticated` variable from mt-u in a classical vue style and in a more idiomatic composable style.
#### Approach 1: `onMounted()` 
```vue
<!-- app.vue -->
<script setup lang="ts">
const { $auth } = useNuxtApp();

const authenticated = ref(false);     // then {authenticated} can be used in component's <template>

onMounted(async function () {
  authenticated.value = !!(await $auth.currentAuthenticatedUser());
});
</script>
```
#### Approach 2: `composable` 
```ts
// composables/useIsAuthenticated.ts
export default function () {
  const { $auth } = useNuxtApp();

  const isAuthenticated = useState('authenticated', () => false);

  return {
    isAuthenticated,
    refresh: async () => {
      isAuthenticated.value = !!(await $auth.currentAuthenticatedUser());
    },
  };
}
```
which can then be used in components in the following way:
```vue
<!-- component.vue -->
<script setup lang="ts">
const isAuthenticated = useIsAuthenticated()
</script>
```
I'll close the issue here, I recommend to continue on the related discussion https://github.com/nuxt/framework/discussions/2308, in case of other issues.

**Comment by ennioVisco** [comment]
Updated previous message to be on track with new updates of https://github.com/nuxt/framework/discussions/2308.

**Comment by sachin-hegde-yml** [comment]
> nuxt3 docs

@ennioVisco Thanks for the detailed explanation on this, it was helpful. Able to run the app and connect to AWS Amplify auth. We have added Storage as well along with the Auth.

But we are unable to build the app, we getting following error,

```
ERROR  Rollup error: Could not load @aws-amplify/core/lib/lib: ENOENT: no such file or directory, open '@aws-amplify/core/lib/lib'
ERROR  Could not load @aws-amplify/core/lib/lib: ENOENT: no such file or directory, open '@aws-amplify/core/lib/lib'  
```

### nuxt.config.ts
```
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
    alias: {
        '@aws-amplify/core': '@aws-amplify/core/lib',
        '@aws-amplify/auth': '@aws-amplify/auth/lib',
        '@aws-amplify/storage': '@aws-amplify/storage/lib',
    },
    meta: {
        script: [{ src: '/polyfill.js' }],
   },
});
```

### amplify.ts
```
import { Amplify } from '@aws-amplify/core';
import { Auth } from '@aws-amplify/auth';
import { AwsConfig } from '../aws-exports';
import { Storage } from '@aws-amplify/storage';
import { defineNuxtPlugin } from '#app';

export default defineNuxtPlugin(() => {
  const awsConfig = AwsConfig();

  Amplify.configure(awsConfig);

  return {
    provide: {
      auth: Auth,
      storage: Storage,
    },
  };
});
```

### package.json
```
"dependencies": {
    "aws-amplify": "^4.3.19"
  },
  "devDependencies": {
    "nuxt": "^3.0.0-rc.1",
    "typescript": "^4.6.3"
  },
```

**Comment by sachin-hegde-yml** [comment]
@ennioVisco Thanks for the detailed explanation on this, it was helpful. Able to run the app and connect to AWS Amplify auth. We have added Storage as well along with the Auth.

But we are unable to build the app, we getting following error,

```
ERROR  Rollup error: Could not load @aws-amplify/core/lib/lib: ENOENT: no such file or directory, open '@aws-amplify/core/lib/lib'
ERROR  Could not load @aws-amplify/core/lib/lib: ENOENT: no such file or directory, open '@aws-amplify/core/lib/lib'  
```

### nuxt.config.ts
```
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
    alias: {
        '@aws-amplify/core': '@aws-amplify/core/lib',
        '@aws-amplify/auth': '@aws-amplify/auth/lib',
        '@aws-amplify/storage': '@aws-amplify/storage/lib',
    },
    meta: {
        script: [{ src: '/polyfill.js' }],
   },
});
```

### amplify.ts
```
import { Amplify } from '@aws-amplify/core';
import { Auth } from '@aws-amplify/auth';
import { AwsConfig } from '../aws-exports';
import { Storage } from '@aws-amplify/storage';
import { defineNuxtPlugin } from '#app';

export default defineNuxtPlugin(() => {
  const awsConfig = AwsConfig();

  Amplify.configure(awsConfig);

  return {
    provide: {
      auth: Auth,
      storage: Storage,
    },
  };
});
```

### package.json
```
"dependencies": {
    "aws-amplify": "^4.3.19"
  },
  "devDependencies": {
    "nuxt": "^3.0.0-rc.1",
    "typescript": "^4.6.3"
  },
```

**Comment by gnemanja** [comment]
We are having the same issue as @sachin-hegde-yml 
If we use ssr: false in nuxt config, the project can be built. Obviously, this is not a solution...

**Comment by ennioVisco** [comment]
@gnemanja and @sachin-hegde-yml 
you don't need the `alias` parameters anymore. Just get rid of them, and everything should work.

**Comment by sachin-hegde-yml** [comment]
@ennioVisco If I don't include `alias` I am getting following error when I run `npm run dev`

```
[nuxt] [request error] Identifier 'module' has already been declared
  at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:117:18)  
  at ESMLoader.moduleProvider (node:internal/modules/esm/loader:337:14)  
  at async link (node:internal/modules/esm/module_job:70:21) 
```

### nuxt.config.ts
```
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
  srcDir: 'src/',
  alias: {
    './runtimeConfig': './runtimeConfig.browser',
  },
  define: {
    global: {},
    buffer: {},
    process: {},
  },
  target: 'server',
});
```

### package.json
```
"nuxt": "^3.0.0-rc.4",
"aws-amplify": "^4.3.26",
```

**Comment by ennioVisco** [comment]
@sachin-hegde-yml as stated in the discussion thread, this is the fix that seems to work for everybody, both in SSG and node. Please confirm that it works for you as well. In my case the `package.json` is a bit different, because I only use the auth module.

```ts
// nuxt.config.ts
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
    alias: { // Amplify fix, pt. 1
        './runtimeConfig': './runtimeConfig.browser'
    },

    vite: {
        define: {
            'window.global': {} // Amplify fix, pt. 2
        },
    }
})

```

`package.json`:
```json
{
   ...
    "@aws-amplify/auth": "^4.5.8",
   ...
}
```

**Comment by sachin-hegde-yml** [comment]
@ennioVisco I have tied installing `@aws-amplify/core` `@aws-amplify/auth` and `@aws-amplify/storage` instead of `aws-amplify` I had earlier. 

Still if I remove alias I am getting the issue `Identifier 'module' has already been declared`.

If I add alias it works with `npm run dev` but `npm run build` gives following error

```
 ERROR  Rollup error: Could not load @aws-amplify/auth/lib/lib (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open '@aws-amplify/auth/lib/lib'

 ERROR  Could not load @aws-amplify/auth/lib/lib (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open '@aws-amplify/auth/lib/lib'
```

**Comment by ennioVisco** [comment]
> @ennioVisco I have tied installing `@aws-amplify/core` `@aws-amplify/auth` and `@aws-amplify/storage` instead of `aws-amplify` I had earlier.
> 
> Still if I remove alias I am getting the issue `Identifier 'module' has already been declared`.
> 
> If I add alias it works with `npm run dev` but `npm run build` gives following error
> 
> ```
>  ERROR  Rollup error: Could not load @aws-amplify/auth/lib/lib (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open '@aws-amplify/auth/lib/lib'
> 
>  ERROR  Could not load @aws-amplify/auth/lib/lib (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open '@aws-amplify/auth/lib/lib'
> ```

this doesn't seem right, try to delete `yarn.lock`/`package-lock.json` and `node_modules`. Also, make sure that you are using the most recent version of amplify (which to date is `4.5.8`).

**Comment by markovickosta** [comment]
@ennioVisco I still have problems with the same issue as them.
I created the same polyfill as you mentioned in [#2874 (comment)](https://github.com/nuxt/framework/issues/2874#issuecomment-1046285059)
My plugin looks like this:
```typescript
import { defineNuxtPlugin } from '#app';
import awsconfig from '../aws-exports';
import { Amplify, Auth } from 'aws-amplify';

export default defineNuxtPlugin(nuxtApp => {
	Amplify.configure(awsconfig);

	return {
		provide: {
			auth: Auth,
		},
	};
});
```
My nuxt.config.ts:
```typescript
alias: { // Amplify fix, pt. 1
	'./runtimeConfig': './runtimeConfig.browser'
},

vite: {
	define: {
		'window.global': {} // Amplify fix, pt. 2
	},
},
```
And my package.json:
```json
{
	"private": true,
	"scripts": {
		"build": "nuxt build",
		"dev": "nuxt dev",
		"generate": "nuxt generate",
		"preview": "nuxt preview"
	},
	"devDependencies": {
		"@iconify-json/ic": "^1.1.4",
		"@nuxtjs/google-fonts": "^1.3.0",
		"@nuxtjs/tailwindcss": "^5.1.2",
		"nuxt": "^3.0.0-rc.4",
		"sass": "^1.53.0",
		"unplugin-icons": "^0.14.3"
	},
	"dependencies": {
		"@pinia/nuxt": "^0.1.9",
		"aws-amplify": "^4.3.26",
		"pinia": "^2.0.14"
	}
}
```
When I run 'npm run dev' I get the following error:
```
[nuxt] [request error] Identifier 'module' has already been declared
  at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)  
  at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)  
  at async link (node:internal/modules/esm/module_job:67:21)
```
I can run 'npm run build' and 'npm run preview' after, without any problems.
BUT when I try to publish that to amplify hosting I get "AccessDenied".

**Comment by ennioVisco** [comment]
> @ennioVisco I still have problems with the same issue as them. I created the same polyfill as you mentioned in [#2874 (comment)](https://github.com/nuxt/framework/issues/2874#issuecomment-1046285059) My plugin looks like this:
> 
> ```ts
> import { defineNuxtPlugin } from '#app';
> import awsconfig from '../aws-exports';
> import { Amplify, Auth } from 'aws-amplify';
> 
> export default defineNuxtPlugin(nuxtApp => {
> 	Amplify.configure(awsconfig);
> 
> 	return {
> 		provide: {
> 			auth: Auth,
> 		},
> 	};
> });
> ```
> 
> My nuxt.config.ts:
> 
> ```ts
> alias: { // Amplify fix, pt. 1
> 	'./runtimeConfig': './runtimeConfig.browser'
> },
> 
> vite: {
> 	define: {
> 		'window.global': {} // Amplify fix, pt. 2
> 	},
> },
> ```
> 
> And my package.json:
> 
> ```json
> {
> 	"private": true,
> 	"scripts": {
> 		"build": "nuxt build",
> 		"dev": "nuxt dev",
> 		"generate": "nuxt generate",
> 		"preview": "nuxt preview"
> 	},
> 	"devDependencies": {
> 		"@iconify-json/ic": "^1.1.4",
> 		"@nuxtjs/google-fonts": "^1.3.0",
> 		"@nuxtjs/tailwindcss": "^5.1.2",
> 		"nuxt": "^3.0.0-rc.4",
> 		"sass": "^1.53.0",
> 		"unplugin-icons": "^0.14.3"
> 	},
> 	"dependencies": {
> 		"@pinia/nuxt": "^0.1.9",
> 		"aws-amplify": "^4.3.26",
> 		"pinia": "^2.0.14"
> 	}
> }
> ```
> 
> When I run 'npm run dev' I get the following error:
> 
> ```
> [nuxt] [request error] Identifier 'module' has already been declared
>   at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)  
>   at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)  
>   at async link (node:internal/modules/esm/module_job:67:21)
> ```
> 
> I can run 'npm run build' and 'npm run preview' after, without any problems. BUT when I try to publish that to amplify hosting I get "AccessDenied".

Ok, but in your case you are relying on the full amplify stack, so I cannot help you, we are using only the SDK and only the Auth library specifically.
Honestly, amplify is trash, I'd recommend avoiding it as it forces you to rely on a huge pile of software from Amazon... And the community already experienced many times how bad Amazon is in updating software.
If I could go back, I'd not use Aws services unless at very high scale.

**Comment by markovickosta** [comment]
@ennioVisco I'm just trying to host this for now and get something to work, would you recommend changing my packages to '@aws-amplify/core'?
I was using firebase but didn't like how long it took for functions to finish so I decided to try amplify.
What would you use then instead of Aws?

Yeah, this is the latest version of the 'aws-amplify' package.

**Comment by ennioVisco** [comment]
> @ennioVisco I'm just trying to host this for now and get something to work, would you recommend changing my packages to '@aws-amplify/core'? I was using firebase but didn't like how long it took for functions to finish so I decided to try amplify. What would you use then instead of Aws?
> 
> Yeah, this is the latest version of the 'aws-amplify' package.

I build it as SSG and host it on a regular AWS S3, but if you don't want to deal with the Https painful setup, even GitHub pages works fine!

**Comment by markovickosta** [comment]
> I build it as SSG and host it on a regular AWS S3, but if you don't want to deal with the Https painful setup, even GitHub pages works fine!

Thank you very much for the advice.

**Comment by markovickosta** [comment]
@ennioVisco I have managed to host it as SSG without a problem, but I still get this error when running 'npm run dev':
```
[nuxt] [request error] Identifier 'module' has already been declared
  at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)  
  at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)  
  at async link (node:internal/modules/esm/module_job:67:21)
```
Things I have changed:
```json
"@aws-amplify/auth": "^4.5.8",
"@aws-amplify/core": "^4.5.8",
```
and
```typescript
//plugins/amplify.ts
import { Amplify } from '@aws-amplify/core';
import { Auth } from '@aws-amplify/auth';
```

**Comment by ennioVisco** [comment]
> @ennioVisco I have managed to host it as SSG without a problem, but I still get this error when running 'npm run dev':
> 
> ```
> [nuxt] [request error] Identifier 'module' has already been declared
>   at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)  
>   at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)  
>   at async link (node:internal/modules/esm/module_job:67:21)
> ```
> 
> Things I have changed:
> 
> ```json
> "@aws-amplify/auth": "^4.5.8",
> "@aws-amplify/core": "^4.5.8",
> ```
> 
> and
> 
> ```ts
> //plugins/amplify.ts
> import { Amplify } from '@aws-amplify/core';
> import { Auth } from '@aws-amplify/auth';
> ```

@markovickosta I checked and tried to reproduce it here: https://codesandbox.io/s/long-resonance-hcodk3?file=/nuxt.config.ts

It seems that when you don't have `ssr: false` in your `nuxt.config.ts` it doesn't work, i.e. Amplify doesn't work with SSR (probably some extra flag must be provided).
Note that in SSG you **must** have `ssr: false`.

**Comment by sachin-hegde-yml** [comment]
@ennioVisco I need ssr to be true, then sadly there is no other way till Nuxt and Amplify fix it

**Comment by androbi-com** [comment]
Thanks for the solution @ennioVisco ! Is there a way to hook into the amplify UI so I know when the user logs in/out and I can refresh my UI accordingly? (like "Hello user!"/"No user logged in"). I can do that inside the Authenticator component, but how to refresh authentication status in the rest of the app?

**Comment by ennioVisco** [comment]
> Thanks for the solution @ennioVisco ! Is there a way to hook into the amplify UI so I know when the user logs in/out and I can refresh my UI accordingly? (like "Hello user!"/"No user logged in"). I can do that inside the Authenticator component, but how to refresh authentication status in the rest of the app?

Ah good question! Tbh we are not using their UI, we are only using the SDK as JavaScript utilities to handle the user session. However, if you are using an Authenticator component, they should work just fine.

You can give a look at the method we are using here: https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/

**Comment by androbi-com** [comment]
Thanks again! The Authenticator component works fine, but I have not been able to update my own components when the connection status changes. From the source code there seems to be an AmplifyEventBus, I'll check if this can be used.
