### ISSUE TITLE
Rollup failed to resolve import "#config" from "vite/preload-helper"

### ISSUE THREAD

**Issue by birdlavv** [nuxt/framework#2882]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27383750.2b86345`
- Package Manager:  `npm@8.3.0`
- Bundler:          `Vite`
- User Config:      `ssr`, `vite`, `target`, `buildModules`, `meta`, `loading`, `typescript`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.2.1`

### Reproduction

I was able to reproduce the error message by creating blank project and:

1. Adding minimal `/pages/index.vue`
2. Setting `ssr: false` in `nuxt.config.ts`

https://github.com/birdlavv/nuxt3-ssr-false-build-reproduction

### Describe the bug

Nuxt 3 fails to build with ssr: false
Looks related to https://github.com/nuxt/framework/issues/886 but according to https://github.com/nuxt/framework/pull/2708#issuecomment-1018630819 it is a separate issue.

### Logs

```shell
ℹ Client built in 21391ms                                                                  06:50:50
ℹ Building server...                                                                       06:50:50

ERROR  [vite]: Rollup failed to resolve import "#config" from "vite/preload-helper".       06:50:50
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`


ERROR  [vite]: Rollup failed to resolve import "#config" from "vite/preload-helper".       06:50:50
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  at onRollupWarning (node_modules/vite/dist/node/chunks/dep-f5552faa.js:37915:19)
  at onwarn (node_modules/vite/dist/node/chunks/dep-f5552faa.js:37693:13)
  at Object.onwarn (node_modules/rollup/dist/shared/rollup.js:23153:13)
  at ModuleLoader.handleResolveId (node_modules/rollup/dist/shared/rollup.js:22431:26)
  at node_modules/rollup/dist/shared/rollup.js:22392:26```
```

**Comment by toniengelhardt** [comment]
I have the same. Worth mentioning that this affects only the build, dev server works fine.

**Comment by yabuking84** [comment]
I also have the same issue setting ssr: false in nuxt.config.ts :-(
