### ISSUE TITLE
regression with import protection - This module cannot be imported in the Vue part of your app

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#2884]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.17.3`
- Nuxt Version:     `3.0.0-27383858.03cc191`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```
npx nuxi init nuxt3-app
yarn && yarn dev
```

### Describe the bug

```
 ERROR  This module cannot be imported in the Vue part of your app. [importing /private/tmp/fresher/node_modules/@nuxt/nitro/dist/runtime/app/nitro.client.mjs from virtual:/private/tmp/fresher/.nuxt/plugins/server.mjs]`
```

**Comment by evanlong0926** [comment]
`This module cannot be imported in the Vue part of your app. [importing pages/node_modules/@nuxt/kit/dist/index.mjs?macro=true from virtual:nuxt:C:/Users/Administrator/Desktop/evanlong.cn/.nuxt/routes.mjs]` 😢
