### ISSUE TITLE
Nuxt build and deploy

### ISSUE THREAD

**Issue by PMLS3** [nuxt/framework#2890]
### Environment

Node Version: v17.3.1
Nuxt Version: 3.0.0-27383920.81ee59c
Package Manager: yarn@1.22.15
Bundler: Vite
User Config: build

### Reproduction

https://github.com/ctwhome/top-nuxt3

### Describe the bug

We are trying to get PWA to work on nuxt3 - repo https://github.com/ctwhome/top-nuxt3

When built locally and running nuxt start, everything is working 100%.

but once build on deployment (google cloud, netlify) the build doesn't create a crucial file: /usr/src/app/.output/server/chunks/client.manifest.mjs

Does anyone know why it will build locally and not in cloud?

We have a open issue on this ctwhome/top-nuxt3#3

**Comment by richardeschloss** [comment]
Can you please provide the Google cloud logs? If they can't be downloaded, can they be copy-n-pasted? 

If we figure out what's going on, perhaps we can take a stab at updating the docs for deployment to Google cloud

**Comment by PMLS3** [comment]
Hi @richardeschloss , yes please see the txt file... 
[build.log (1).txt](https://github.com/nuxt/framework/files/7955423/build.log.1.txt)

**Comment by richardeschloss** [comment]
Ok, from the logs I see this:
> Step #0 - "Build":   ├─ .output/server/chunks/app/render.mjs (22.2 kB) (6.13 kB gzip)
Step #0 - "Build":   ├─ .output/server/chunks/app/config.mjs (886 B) (449 B gzip)
Step #0 - "Build":   ├─ .output/server/chunks/app/client.manifest.mjs (164 kB) (13.3 kB gzip)
Step #0 - "Build":   └─ .output/server/chunks/api.mjs (8.37 kB) (1.77 kB gzip)

It says it generated the client.manfest.mjs file. It's in ".output/server/chunks/app/client.manifest.mjs" . 

It seems like the app was built successfully and is running? 

> Step #0 - "Build": Step 11/11 : CMD [ "npm", "run", "start" ]
Step #0 - "Build":  ---> Running in df97f6e29a3e
Step #0 - "Build": Removing intermediate container df97f6e29a3e

(I apologize, I'm not really familiar with Google cloud specifics; I'm not sure how one would connect to that app now that it's running)

**Comment by PMLS3** [comment]
That's where I am lost as well, on local build and npm run start it works. I'ts not just Google Cloud, we tried Netlify as well. The issue is not that the deployment is not showing, it is to get full PWA functionality, with local build the starter_url is picked up but not when build in production. The site is working but not the PWA side of it

I have taken the "pwa" out in the meantime and that is a fresh build you see on that link... ha ha

**Comment by richardeschloss** [comment]
What do the logs show when the pwa stuff is put back in? Is it possible https://github.com/nuxt-community/pwa-module/issues/492 is the issue to follow?

**Comment by danielroe** [comment]
@PMLS3 Are you perhaps talking about a PWA manifest? That's a different thing from the client manifest you are seeing in the build output, which is a required part of the SSR lifecycle (injecting meta and link tags in the rendered HTML), but is not for consumption by a browser.

For PWA support, keep your eyes peeled. We will either be upgrading the existing PWA module or integrating it into Nuxt 3 more directly.

**Comment by PMLS3** [comment]
Thanks @danielroe @richardeschloss , I'll close this issue for now and wait for the PWA module. Appreciate all the feedback and hard work...

**Comment by userquin** [comment]
@danielroe it is a problem on the server/cloud build, we need `.output/server/chunks/app/client.manifest.mjs` to get pages and so add them (filtering page entries) to the sw precache manifest to allow work offline: all pages not included on the sw precache manifest will not work on offline.
