### ISSUE TITLE
NuxtLink

### ISSUE THREAD

**Issue by misaon** [nuxt/framework#2894]
### Environment

- Operating System: `Linux`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-27383920.81ee59c`
- Package Manager:  `yarn@3.1.1`
- Bundler:          `Vite`
- User Config:      `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `normalizedModule()`, `normalizedModule()`

### Reproduction

Use NuxtLink in template

### Describe the bug

![image](https://user-images.githubusercontent.com/15806356/150858013-d78e0d9b-3f39-49a0-9790-417fa894a5f7.png)

**Comment by danielroe** [comment]
Would you provide a minimal reproduction, please? You can [start here](https://codesandbox.io/s/infallible-parm-r1fnt?file=/pages/index.vue).

**Comment by misaon** [comment]
@danielroe After remove .nuxt folder and regenerate vite, works again. I will close issue.
