### ISSUE TITLE
Global styles are not inline on HTML

### ISSUE THREAD

**Issue by Tiagogv** [nuxt/framework#2896]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `css`, 'target'
- Runtime Modules:  -
- Build Modules:   -
------------------------------

### Reproduction

https://codesandbox.io/s/nuxt-bridge-inline-css-0b3ek?file=/pages/index.vue

### Describe the bug

Global styles defined in nuxt.config are not inlined in HTML like styles defined in components. 
They are loaded instead by a separated js file.
Not inlining global styles, leads to sometimes the page being rendered without styling for a few milliseconds, causing flickering.
This is more noticeable if using CSS frameworks like TailwindCSS.

Global styles should have the same behaviour as styles defined in components.
These is easily checked by analysing the HTML received by the server.

Even generating full static pages, the global styles are not inlined.

nuxt.config.ts
```ts

css: ['~/assets/css/main.css']

```

assets/css/main.css
```css
html { 
   background-color: red;
}
```

pages/index.vue
```vue
...
<style scoped>
.test {
  color: red;
}
</style>
...
```

HTML received by the server
```html
<head>
    <-- Global Styles loaded by one of these scripts --/>
    <link rel="preload" href="/_nuxt/1e0eb7e.js" as="script" /> 
    <link rel="preload" href="/_nuxt/2854b23.js" as="script" />
    <link rel="preload" href="/_nuxt/48336d1.js" as="script" />
    <link rel="preload" href="/_nuxt/ba7b32c.js" as="script" />
    <link rel="preload" href="/_nuxt/7f7ebf7.js" as="script" />
    <style data-vue-ssr-id="3f264f57:0,197917fc:0">
      .nuxt-progress {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        height: 2px;
        width: 0;
        opacity: 1;
        transition: width 0.1s, opacity 0.4s;
        background-color: #000;
        z-index: 999999;
      }
      .nuxt-progress.nuxt-progress-notransition {
        transition: none;
      }
      .nuxt-progress-failed {
        background-color: red;
      }
      .test[data-v-0c7476f7] { /* Component Style Inlined */
        color: red;
      }
    </style>
  </head>
```

**Comment by Tiagogv** [comment]
Manage to find a workaround, by importing the global css file into the <style> tag of my layout component instead adding it to nuxt.config

**Comment by danielroe** [comment]
Thanks for reporting. Let's track in https://github.com/nuxt/framework/issues/1207 (I've changed title to make it clearer that it's the same issue).
