### ISSUE TITLE
Path to local font, attached through css @font-face url()

### ISSUE THREAD

**Issue by ztxone** [nuxt/framework#2913]
@font-face css rule from /assets/css/main.css seems doesn't build correct path to font after nuxi build command

@font-face {
  font-family: 'RF Dewi Expanded';
  src: url('assets/fonts/rf-dewi/RFDewiExpanded-Black.ttf') format('truetype');
// or even if point this path src: url('/assets/fonts/rf-dewi/RFDewiExpanded-Black.ttf') format('truetype');
// or this path src: url('./assets/fonts/rf-dewi/RFDewiExpanded-Black.ttf') format('truetype');
// or this path src: url('~/assets/fonts/rf-dewi/RFDewiExpanded-Black.ttf') format('truetype');
}

In browser console it shows 404 and path http://localhost:3000/__NUXT_BASE__/RFDewiExpanded-Black.0e1a5c76.ttf

![Screen Shot 2022-01-25 at 14 14 15](https://user-images.githubusercontent.com/39146381/150975241-84d47f4b-ae8f-4724-9eff-197375176ca1.png)

in the first line font serves from http://localhost:3000/_nuxt/RFDewiExpanded-Black.0e1a5c76.ttf
in the second line font serves from http://localhost:3000/__NUXT_BASE__/RFDewiExpanded-Black.0e1a5c76.ttf

The Info from docs doesn't clear this issue

_Originally posted by @ztxone in https://github.com/nuxt/framework/issues/2888#issuecomment-1021129319_

**Comment by ztxone** [comment]
upgrade to nuxt3@3.0.0-27383920.81ee59c solves 404 error.
But why it serves double font from one place now? Sorry for silly questions

![Screen Shot 2022-01-25 at 14 36 57](https://user-images.githubusercontent.com/39146381/150978256-a55b4f81-fe84-4680-9955-50a2ca7aca9a.png)

Both from http://localhost:3000/_nuxt/RFDewiExpanded-Black.0e1a5c76.ttf

and one else thing:
in dev mode fonts serves correctly from http://localhost:3000/_nuxt/assets/fonts/rf-dewi/RFDewiExpanded-Black.ttf
but after build it serves from http://localhost:3000/_nuxt/RFDewiExpanded-Black.0e1a5c76.ttf - and webpage doesn't recognise it(

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/2888.

**Comment by ztxone** [comment]
> Let's track in #2888.
> 
> The path changing is just Vite's default behaviour.

Wrong path to font, font does not applies, and doubled. Is it ok?

**Comment by yungParrot** [comment]
I'm encountering a similar issue to @ztxone:

- my code can be [found here](https://gitlab.com/fabb.zone/website/-/tree/deployment-update) and the fonts [are loaded here](https://gitlab.com/fabb.zone/website/-/blob/deployment-update/frontend/app.vue)
- the deployed code [is here](https://staging.fabb.zone/)

I can't seem to load `.tff` fonts and I don't know if it's really caused by Vite or Nuxt. I've tried to use the *working* version of nuxt -> `nuxt3@3.0.0-27383920.81ee59c` but it doesn't seem to work:

![image](https://user-images.githubusercontent.com/39010895/151132444-693383ca-e151-4b6e-93f3-1a3527e0faa3.png)

I've tried loading the fonts with:
```
url("@/assets/...)
url("~/assets/...)
url("~assets/...)
url("assets/...)
```
in the `app.vue` component, but every time I get a 404 error, although running `yarn dev` works correctly and fonts are loaded correctly.  
I don't know if it's related to [this issue](https://github.com/nuxt/framework/issues/2888) 🤔

**Comment by danielroe** [comment]
@yungParrot Yes, the issue is the same as the one you linked.

**Comment by M1seRy** [comment]
Hi, thks for your time。so in the end, how to solve this problems，same error in my dev bridge version environment，when I upgrade to nuxt bridge version, the public css and font file response 404：
![image](https://user-images.githubusercontent.com/10118666/182089365-3272da90-56d5-41bd-89c4-a94fe855f6bc.png)


my project info:

>  Nuxt project info:                                                                                           14:40:29

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.16.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.17.3`
- Builder:          `webpack`
- User Config:      `telemetry`, `hooks`, `mode`, `target`, `head`, `css`, `plugins`, `components`, `modules`, `build`, `srcDir`, `server`, `loading`, `render`, `publicRuntimeConfig`, `privateRuntimeConfig`, `proxy`, `serverMiddleware`, `router`, `serverHandlers`, `devServerHandlers`, `bridge`, `buildModules`
- Runtime Modules:  `@nuxtjs/proxy@2.1.0`, `@nuxt/http@0.5.13`, `@nuxtjs/device@1.2.7`, `@nuxtjs/svg@0.1.12`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27636329.42ea75b`

file structure:

```
- public
 - iconfont
   - font file
   - index.css 
```

nuxt.config.ts

```
link: [
     {
        rel: 'stylesheet',
        href: '/iconfont/index.css',
      }
]
```

**Comment by danielroe** [comment]
If you are using Bridge, please file issues at https://github.com/nuxt/bridge. Nuxt 2/Bridge uses `~/static` rather than `~/public` so likely just renaming that folder should resolve the issue for you.

**Comment by M1seRy** [comment]
> If you are using Bridge, please file issues at https://github.com/nuxt/bridge. Nuxt 2/Bridge uses `~/static` rather than `~/public` so likely just renaming that folder should resolve the issue for you.

@danielroe thanks，I will revert to static folder.
