### ISSUE TITLE
Cannot start nuxt: Cannot find module '#ansi-styles' (Fresh Install - Windows 10) 

### ISSUE THREAD

**Issue by medairbit** [nuxt/framework#2919]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27385496.7a1cf62`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Cloned the starter project `npx nuxi init nuxt3-app`
2. `yarn install`
3. `yarn dev`

### Describe the bug

I've followed the installation steps, and after `yarn dev` I receive this error:
`ERROR  Cannot start nuxt:  Cannot find module '#ansi-styles' `

### Logs

```shell
ERROR  Cannot start nuxt:  Cannot find module '#ansi-styles'                                                                                                   

Require stack:
- .../nuxt3-app/node_modules/@nuxt/nitro/node_modules/chalk/source/index.js

  Require stack:
  - .../nuxt3-app/node_modules/@nuxt/nitro/node_modules/chalk/source/index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at _resolve (node_modules\jiti\dist\jiti.js:1:192527)
  ...
```
```

**Comment by ggdiam** [comment]
Same issue
created repo using
`npx nuxi init nuxt3-app`

have error:
`Cannot start nuxt:  Cannot find module '#ansi-styles'`

### Solution:
remove `node_modules`
replace package-lock.json content by this one
use this [package-lock.json](https://gist.github.com/ggdiam/709449124ca7cca80ead4e6d6428efb2)
run `npm i`

now `npm run dev` works

**Comment by medairbit** [comment]
The issue come from the `chalk` latest version dependency, downgrading to its previous version seems to fix it.
Quick workaround in your package.json:
```json
{
  "devDependencies": {
    "chalk": "^4.1.2",
    "nuxt3": "latest"
  },
  "resolutions": {
    "chalk": "^4.1.2"
  }
}
```

**Comment by ggdiam** [comment]
no, have same issue

**Comment by medairbit** [comment]
> no, have same issue i'm using npm

In that case, hard editing your package-lock.json is the only temp solution for now, until they fix it 😄

**Comment by ggdiam** [comment]
for **npm 8.3.2** it's
```
"devDependencies": {
  "nuxt3": "latest"
},
"overrides": {
  "chalk": "^4.1.2"
}
```
make sure using latest npm 8.3.2 (`npm install -g npm@latest` to update)

**Comment by MrChen-Fly** [comment]
jiti@1.12.13 bug

**Comment by danielroe** [comment]
It looks like this may have been fixed. Can you reproduce with a fresh install or (`npx nuxi upgrade --force`)?

**Comment by medairbit** [comment]
Fixed thank you!
