### ISSUE TITLE
font rejected by sanitizer in production

### ISSUE THREAD

**Issue by StevenJPx2** [nuxt/framework#2931]
### Environment

Nuxt CLI v3.0.0-27386644.9444647
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.3.1`
- Nuxt Version:     `3.0.0-27386644.9444647`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Load any normal font-face in the assets directory.

Use it for any element, it will work in dev, but not in prod.

### Describe the bug

`downloadable font: rejected by sanitizer (font-family: "Joyride STD" style:normal weight:400 stretch:100 src index:0) source: http://localhost:3000/_nuxt/JoyrideSTD.66498a98.woff2`

Builds 'v3.0.0-27272804.ca557e7' and 'v3.0.0-27319101.3e82f0f' do not have this issue.

**Comment by danielroe** [comment]
This should be resolved in the latest version of nuxt: https://github.com/nuxt/framework/pull/2930. Let me know if it persists after you run `npx nuxi upgrade`.

**Comment by StevenJPx2** [comment]
This is on the current latest version of Nuxt on npm.

**Comment by danielroe** [comment]
The version you are on is one version behind the version with the fix. The current latest version is `3.0.0-27386759.b449d0b`

**Comment by StevenJPx2** [comment]
Works perfectly! Just had to reload the npm page, I think it cached the previous load haha!
