### ISSUE TITLE
Locomotive Scroll crashes dev and prod build

### ISSUE THREAD

**Issue by StevenJPx2** [nuxt/framework#2933]
### Environment

Nuxt CLI v3.0.0-27386759.b449d0b
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.3.1`
- Nuxt Version:     `3.0.0-27386759.b449d0b`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

`yarn add locomotive-scroll`

```vue
<script setup lang="ts">
import LocomotiveScroll from 'locomotive-scroll'

onMounted(() => {
  console.log(LocomotiveScroll)
})
</script>
```

### Describe the bug

document is not defined
  at $id_0361de3b (file://./.nuxt/dist/server/server.mjs:8353:7)
  at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:11446:9)
  at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:11393:25)
  at ssrImport (file://./.nuxt/dist/server/server.mjs:11418:13)
  at $id_2b46e842 (file://./.nuxt/dist/server/server.mjs:7985:37)
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:11446:3)

It does look like an ssr error, but this shouldn't be an issue if we're loading it after mount?

### Additional context

Another oddity, if you paste `console.log(LocomotiveScroll)` into the above location and allow it to hot-reload, it works. It only fails after a manual reload and every subsequent reload.

**Comment by StevenJPx2** [comment]
Works perfectly now! Had to add `"esModuleInterop": true` in my tsconfig for it work properly.

Another thing, the plugin route isn't giving me proper type support. I have defined the plugin as loco, and it is being called successfully as $loco from useNuxtApp, but the type is any and the autocomplete also doesn't detect that as a key either.

**Comment by danielroe** [comment]
@StevenJPx2 I'd happily look at a reproduction.
