### ISSUE TITLE
In Dev, New Pages Render a Blank Page Until You Restart The Server

### ISSUE THREAD

**Issue by samuglz** [nuxt/framework#2942]
### Environment

Nuxt CLI v3.0.0-27386975.6e06d2b
Nuxt project info:

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.2.0`
- Nuxt Version:     `3.0.0-27386975.6e06d2b`
- Package Manager:  `npm@8.3.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. npm run dev
2. create a new file in /pages
3. fill in the new page with content
4. go to the new route in your browser, a blank page will be rendered
5. stop/start dev and page works

### Describe the bug

When running Nuxt 3 in dev mode, if you create a new page it will rendered in your browser a blank page until you stop/start your dev server.

### Logs

```shell
Browser Logs:
- vue-router.esm-bundler.js?v=ed3bc494:72 [Vue Router warn]: No match found for location with path "/posts"

- [Vue warn]: Hydration node mismatch:
  Client vnode: Symbol(Comment) 
  Server rendered DOM: <!--[--> (start of fragment) 
  at < RouterView > 
  at < NuxtPage > 
  at < App > 
  at < NuxtRoot >

- Hydration completed but contains mismatches.
```

**Comment by doomspec** [comment]
I am also facing this problem and wondering whether this is a problem of Nuxt3 or Vite.

**Comment by Agusnez** [comment]
Super weird bug! Using version `^3.0.0-27398533.8edd481` in production mode (after running `npm run build` & `npx nuxi preview`) it shows this error.

Deleting `package-lock.json` and changing `"devDependencies": {
        "nuxt3": "latest"
      }` then running a fresh `npm install` again, solved the bug!

But other bugs appears: https://github.com/nuxt/framework/issues/2793

**Comment by sefacicekli** [comment]
Still doesn't work with ```3.0.0-rc.12```

**Comment by danielroe** [comment]
Believe it or not, it's a different, but similar, issue, which should be resolved by https://github.com/nuxt/framework/pull/8389
