### ISSUE TITLE
No such file or directory, stat 'node_modules/.cache'

### ISSUE THREAD

**Issue by shinguweb96** [nuxt/framework#2951]
### Environment

Nuxt project info:                                                                                                                                                                   14:16:55

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27386975.6e06d2b`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `privateRuntimeConfig`, `vite`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

cannot reproduce, just doing a normal npx nuxi upgrade and got the error

### Describe the bug

```
Nuxt CLI v3.0.0-27386975.6e06d2b                                                                                                                                                     14:15:43
ℹ Package Manager: yarn 1.22.17                                                                                                                                                      14:15:43
ℹ Current nuxt version: 3.0.0-27386975.6e06d2b                                                                                                                                       14:15:43
ℹ Upgrading nuxt...                                                                                                                                                                  14:15:43

 ERROR  (node:643168) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead 14:15:43
(Use `node --trace-deprecation ...` to show where the warning was created)


 ERROR  ENOENT: no such file or directory, stat 'node_modules/.cache' 
```

**Comment by nandi95** [comment]
This might have been introduced by some recent commits. Also happening in my environment:
```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-27388331.8ea6b65`
- Package Manager:  `npm@8.3.1`
- Bundler:          `Webpack`
- User Config:      `publicRuntimeConfig`, `srcDir`, `ssr`, `target`, `vite`, `typescript`, `autoImports`, `build`, `meta`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```
It is perhaps this commit: https://github.com/nuxt/framework/commit/6e06d2b4c9c7dd8f59442e93962f48e4a8bb156b#diff-6adc9cccbbc7f61fcf38abdc8a1521338913c2215e3d099d1b71ebadbfc53b9dR47
