### ISSUE TITLE
Page with dynamic route ([...slug].vue) doesn't call script setup when route change

### ISSUE THREAD

**Issue by smcyr** [nuxt/framework#2956]
### Environment

Nuxt CLI v3.0.0-27383686.83a959a                                                                                                                                                                                   11:21:46
RootDir: C:\projects\nuxt3-router-problem                                                                                                                                                                          11:21:47
Nuxt project info:                                                                                                                                                                                                 11:21:47

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27383686.83a959a`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Here is a simple repo to see the problem:
https://github.com/smcyr/nuxt3-router-problem
When you change between the two links, you can see that the variable `{{ $route.path }}` changes but not the one what comes from the api from `useFetch`: `{{ data.uri }}`

### Describe the bug

In the commit https://github.com/nuxt/framework/commit/83a959a67b71333f2ae2eaa358b64abe22d619b9, the `:key="route.path"` was removed from `<component :is="Component" :key="route.path" />` inside `packages/nuxt3/src/pages/runtime/page.vue`. So, now, if the route changes with `<NuxtLink>`, the page with a dynamic route (named `[...slug].vue`) doesn't call `<script setup>`, so `useFetch` isn't called and nothing changes on the page. It work fines with the previous GIT commit from Nuxt3.

**Comment by danielroe** [comment]
let's follow in https://github.com/nuxt/framework/issues/2903
