### ISSUE TITLE
Nuxt hosting SSR  With firebase Cloud Functions

### ISSUE THREAD

**Issue by bynicodevelop** [nuxt/framework#2963]
### Environment

Nuxt project info:                                                                                                               07:36:05

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0-27376943.f219f63`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Vite`
- User Config:      `srcDir`, `css`, `build`, `serverMiddleware`, `publicRuntimeConfig`, `privateRuntimeConfig`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

It's same as in the documentation : https://v3.nuxtjs.org/docs/deployment/firebase

```
{
  "hosting": {
    "public": ".output/public",
    "target": "www",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "function": "server"
      }
    ]
  },
  "functions": {
    "source": ".output/server"
  },
  "emulators": {
    EMULATOR
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  }
}
```

### Describe the bug

Ma question est que dans le cadre de cette configuration, il n'est pas possible d'utiliser le dossier des fonctions cloud proposé par Firebase dont la configuration est :

```
{
  "hosting": {
    "public": ".output/public",
    "target": "www",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "function": "server"
      }
    ]
  },
  "functions": {
    "source": "functions" <-- modification
  },
  "emulators": {
    EMULATOR
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  }
}
```

It becomes impossible to make coexist in the same Nuxt 3 project with a Firebase project (firestore, cloud function).

Unless there is a solution to code the functions in the Nuxt server folder?

Thanks for your feedback

### Additional context

No

### Logs

```shell
No
```

**Comment by danielroe** [comment]
Would you open a feature request on https://github.com/unjs/nitro with some examples of what you want? In general we're trying to have a single source of truth for server endpoints within Nitro.
