### ISSUE TITLE
"Inject" inside library ignores default value

### ISSUE THREAD

**Issue by MichaelGitArt** [nuxt/framework#2964]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27388331.8ea6b65`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `meta`, `alias`, `components`, `buildModules`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@7.4.0`, `@pinia/nuxt@0.1.8`, `nuxt-windicss@2.1.1`

### Reproduction

https://stackblitz.com/edit/nuxt3-windicss-4qvgza?file=app.vue

Build and start output server:
npm run build
node ./.output/server/index.mjs

### Describe the bug

Bug with using **'gitart-vue-dialog'** package after building an app.

There we have component GDialogRoot that has an **injection** with a default value:

![image](https://user-images.githubusercontent.com/34610289/151521005-21008d23-4397-4c24-88e7-cb153d63ef8f.png)

And **it works fine during development**. But after building and running the output server it doesn't accept the default value:

![image](https://user-images.githubusercontent.com/34610289/151521696-af3df4b8-1692-4b20-8fc1-1df60e593024.png)

And we have an error. Not sure that's exactly the Nuxt error, but I can't find a solution...

**Comment by justin-schroeder** [comment]
I can confirm this is an issue! It appears to only affect plugins/modules that are installed in node_modules — im unable to duplicate the issue with files in the repository itself. It only happens during SSR on built files when there are dependencies that use Vue’s provide/inject. It's not restricted to symbol injections either, happens even with string injections which makes me think somehow the version of vue being given to dependencies in the node_modules is not the same instance of vue as that being given to the built server environment.

**Comment by danielroe** [comment]
At the moment, until Vue provides ESM server builds, you will need to ensure that any file or library you have that imports from `vue` is added to the `build.transpile` array.

**Comment by justin-schroeder** [comment]
Boom — pretty sure that’s it @danielroe 🙏 many thanks!

**Comment by MichaelGitArt** [comment]
Yes, I just needed to add my package to `build.transpile`

```typescript
export default defineNuxtConfig({
  build: {
    transpile: ['gitart-vue-dialog'],
  },
});
```

Thank you!
