### ISSUE TITLE
serverMiddle: process.env.VARIABLE is undefined

### ISSUE THREAD

**Issue by dungonfq** [nuxt/framework#2965]
### Environment

Production.

Nuxt3 version `^3.0.0-27386975.6e06d2b`

### Reproduction

https://stackblitz.com/edit/github-rkga9h?file=server/middleware/api.ts

1. Add .env file
```
API_HOST="https://api.example.com
```

2. Create a middleware api.ts file in folder `server/middleware`
```js
export default function (req, res, next) {
  console.log(process.env.API_HOST)
  next()
}
```

3. nuxi build
4. nuxi start
5. open `localhost:3000` & see the log
- It show `undefined`

### Describe the bug

I cannot access process.env.VARIABLE in production env. It works well on development.

Is there any way to work around? Please help.

Thank you.

**Comment by danielroe** [comment]
Instead of using `process.env`, you should [use `runtimeConfig`](https://v3.nuxtjs.org/docs/usage/runtime-config).

**Comment by dungonfq** [comment]
Hi @danielroe , thank but I tried:

```js
export default function (req, res, next) {
  const config = useRuntimeConfig();
  console.log(config.API_HOST)
  next()
}
```

But it shows error `useRuntimeConfig is not defined`

**Comment by dungonfq** [comment]
Thank you a lots @danielroe.

This works for me https://v3.nuxtjs.org/docs/usage/runtime-config/#api-routes
