### ISSUE TITLE
useAsyncData refresh can not be called until promise is resolved

### ISSUE THREAD

**Issue by benneq** [nuxt/framework#2973]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v17.3.0`
- Nuxt Version:     `3.0.0-27388331.8ea6b65`
- Package Manager:  `npm@8.3.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Here's an example at StackBlitz: https://stackblitz.com/edit/github-r3snh3-hfb3yx?file=app.vue
And the same at CodeSandbox: https://codesandbox.io/s/serene-proskuriakova-wvp26?file=/app.vue

It's a fake search-as-you-type app: While typing in the `<input>` element, it will execute an async search for the current input value. The delay for the search repsonse is emulated using a `setTimeout`.

As you can see: While the timeout is running (= promise has not resolved yet), it's not possible to trigger a new refresh.

### Describe the bug

It's not possible to implement a "search-as-you-type" function using `useAsyncData`, because keystrokes are ignored until the Promise has resolved.

For search-as-you-type `refresh` should allow to be called at any time, and just use the result of the Promise from the most recent call. When there's already a Promise running while `refresh` is called, its result should be ignored and the new Promise should be executed.

**Comment by YuLogun** [comment]
+++ faced the same issue

**Comment by YuLogun** [comment]
Could you please share have you found a workaround?
