### ISSUE TITLE
build with `ssr: false` cause errors

### ISSUE THREAD

**Issue by yaquawa** [nuxt/framework#2996]
### Environment

Nuxt CLI v3.0.0-27389502.88da719 

### Reproduction

1. `npx nuxi init nuxt3-app`
2. in `nuxt.config.ts` set the `ssr` to `false`
3. run `yarn build`

### Describe the bug

I got errors reported, and can't find the entry `index.html` file in the `.output` directory.

**Comment by danielroe** [comment]
Would you provide a reproduction please? 🙏

**Comment by yaquawa** [comment]
Hi @danielroe , I'm just using the regular `npx nuxi init nuxt3-app` without any modifications.

**Comment by danielroe** [comment]
Let's track in #2882 then.
