### ISSUE TITLE
Nuxi typecheck fails on Node 16.13

### ISSUE THREAD

**Issue by leo91000** [nuxt/framework#2997]
### Environment

RootDir: /sandbox                                                                  12:55:02
Nuxt project info:                                                                 12:55:02

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27389502.88da719`
------------------------------

### Reproduction

I can't find a way to make a reproduction setup  since code sandbox is on 16.12.0, and it work fine there.

If they decide to upgrade, here is the link : https://codesandbox.io/s/winter-snowflake-4cynx?file=/package.json

### Describe the bug

The command `nuxi typecheck` fails on node 16. The following error is thrown :

```
Nuxt CLI v3.0.0-27389502.88da719                                                                              17:13:44
npm ERR! Cannot read properties of undefined (reading 'replace')

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\maill\AppData\Local\npm-cache\_logs\2022-01-30T16_13_49_688Z-debug.log

 ERROR  Command failed with exit code 1: npx -p vue-tsc -p typescript vue-tsc --noEmit                        17:13:49

  at makeError (/D:/Projets/webpage/node_modules/nuxi/dist/chunks/index3.mjs:1240:11)
  at handlePromise (/D:/Projets/webpage/node_modules/nuxi/dist/chunks/index3.mjs:2067:26)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.invoke (/D:/Projets/webpage/node_modules/nuxi/dist/chunks/typecheck.mjs:41:7)
  at async _main (/D:/Projets/webpage/node_modules/nuxi/dist/chunks/index.mjs:384:7)
```

**Comment by fbrbovic** [comment]
Getting the same error, I downgraded to 16.12.0  on my machine and it still shows the same error. 
Running, Nuxt3 (3.0.0-27338323.1e98259), linux

**Comment by halimb** [comment]
Same here using nuxt-bridge
`Nuxt CLI v3.0.0-27379487.e0cf2d7`
`node -v 16.13.1`

**Comment by danielroe** [comment]
I can't replicate this with latest node 16 (or 16.13), using the `package.json` from the codesandbox.

Does it make a difference if you run `npx nuxi@latest typecheck`?

**Comment by halimb** [comment]
@danielroe it stopped happening on the latest commits (from around early February)
all is good for me

**Comment by greyvugrin** [comment]
I spun my wheels on that error for a while before realizing that the error was due to `vue-tsc` not being installed.

`npm i --save-dev vue-tsc` fixed it!

**Comment by danielroe** [comment]
I can't reproduce this with the reproduction and node v16.14.2. If you are experiencing it, try `npx nuxi@latest typecheck` to force using an updated version of `nuxi`.

If it's not resolved, let me know and I'll reopen.
