### ISSUE TITLE
UMD import fails in development with Vite

### ISSUE THREAD

**Issue by Tahul** [nuxt/framework#3016]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27394404.1672148`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `modules`
- Runtime Modules:  ``
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/vitejs-vite-89evtk

### Describe the bug

There is an issue when importing a module that imports another module using `umd` format.

This only happens in development, when using Vite, so can easily be worked-around by disabling Vite.

We replicated this during a call with @danielroe.

### Additional context

https://github.com/nuxt/framework/pull/2795

This pull request has been mentioned as a possible solution.

**Comment by danielroe** [comment]
This is no longer reproducible with Vite 3: https://stackblitz.com/edit/github-g2hwt4.
