### ISSUE TITLE
.env variables not read into process.env anymore

### ISSUE THREAD

**Issue by nandi95** [nuxt/framework#3017]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-27394404.1672148`
- Package Manager:  `npm@8.3.1`
- Bundler:          `Webpack`
- User Config:      `publicRuntimeConfig`, `srcDir`, `ssr`, `target`, `vite`, `modules`, `typescript`, `build`, `meta`, `css`
- Runtime Modules:  `~/modules/router.ts`
- Build Modules:    `-`
------------------------------
```

### Reproduction

Update from: https://github.com/nuxt/framework/commit/083f90b719e0af6a60bc34e8ef347db422fc2db5
to: https://github.com/nuxt/framework/commit/1672148a87106591c2af6627f7d1c76f5fa81d2e
where dotenv was removed in favour of [unjs/c12](https://github.com/unjs/c12)

### Describe the bug

env variables that has been previously been read into process.env are not anymore.
This breaks setting of the runtime configs

**Comment by toniengelhardt** [comment]
Same problem!

**Comment by kenta92** [comment]
Same here ...
