### ISSUE TITLE
Vue devtools inspection not available

### ISSUE THREAD

**Issue by chisomgbata** [nuxt/framework#3019]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27394404.1672148`
- Package Manager:  `npm@8.3.2`
- Bundler:          `Vite`
- User Config:      `vue`
- Runtime Modules:  `-`
- Build Modules:    `-`
- Browser: Chrome
- Devtool version: 6.0.0.21

### Reproduction

A new install nuxt project

### Describe the bug

After a clean Install of Nuxt and i run the development server, for some reason Vue Devtools inspection doesn't work and it gives this message.
"Devtools inspection is not available because it's in production mode or explicitly disabled by the author."
I also tried adding this to the nuxt config file but same error
` vue: {
    config: {
      devtools: true
    }
  },`

**Comment by niklasfjeldberg** [comment]
I have the same issue.

- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27394404.1672148`
- Package Manager:  `npm@8.3.2`
- Bundler:          `Vite`
- User Config:      `ssr`, `buildModules`, `strapi`, `vue`, `publicRuntimeConfig`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/strapi@1.2.0`

**Comment by tobiasdiez** [comment]
I had the same issue. For vue3 support you need the latest version of the devtools available from https://github.com/vuejs/devtools/releases. With this it is working for me (make sure to disable the 5.x version of the devtools).

**Comment by chisomgbata** [comment]
> I had the same issue. For vue3 support you need the latest version of the devtools available from https://github.com/vuejs/devtools/releases. With this it is working for me (make sure to disable the 5.x version of the devtools).

Yeah I know about that, as you can see in the environment, I am already using the latest version of devtools.

Here is a reproduction link
https://stackblitz.com/edit/nuxt-starter-dxhyqn?

@danielroe

**Comment by danielroe** [comment]
<img width="1036" alt="CleanShot 2022-02-07 at 23 54 55@2x" src="https://user-images.githubusercontent.com/28706372/152891856-49a06836-9021-47e9-ac8c-ad2acb60310b.png">

I can't reproduce this on that stackblitz link - see above. So I think it must be specific to your environment. Try a different browser. And ensure you have no service worker serving up a production version of your app (incognito mode is a helpful quick debug step).
