### ISSUE TITLE
Execution order of Vite Proxy and Nuxt Plugins

### ISSUE THREAD

**Issue by k0mar12** [nuxt/framework#3025]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-27385362.4a59377`
- Package Manager:  `npm@8.3.1`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `buildDir`, `nitro`, `vite`, `buildModules`, `plugins`, `css`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

1. Create Vite proxy in `nuxt.config.ts`

```
vite: {
    server: {
        proxy: {
            '/spa': {
                target: 'http://server.app.local',
                changeOrigin: true
            },
        },
    }
} 
```

2. Create server plugin with fetching data from proxy

```
import { defineNuxtPlugin } from '#app';

/**
 * Init data
 */
export default defineNuxtPlugin(async () => {
    await $fetch('/spa/cookie');
});
```

### Describe the bug

The problem is that first executed `Plugin` and then running `Proxy` and as result - `Plugin's` fetch failed, because route `/spa/cookie` not exist at execution moment of Plugin.

**Comment by danielroe** [comment]
I think in this case the reason is that `$fetch` is making a local fetch - it's not even hitting the network layer on SSR. So it's not encountering the proxy. But likely it works on client-side, right?

**Comment by k0mar12** [comment]
@danielroe right, on client-side everything is fine

**Comment by danielroe** [comment]
In that case this is expected behaviour. You can use the full path to ensure a network call if you need to hit the API.

**Comment by makkarpov** [comment]
What is expected workaround then? E.g. how one would write a code that is universal for client and server, but hits internal API when executed inside of SSR and public API on same domain on client?

E.g. when you have nginx in front that redirects root to Nuxt and `/api` to some backend, how to write a reusable code that will reach backend from SSR?
