### ISSUE TITLE
suspense.resolve() is called without a pending branch

### ISSUE THREAD

**Issue by gijsroge** [nuxt/framework#3027]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.5`
- Nuxt Version:     `3.0.0-27369360.33ebb01`
- Package Manager:  `yarn@1.22.11`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://github.com/gijsroge/vue-suspense-bug

Start dev server and follow instructions

### Describe the bug

Switching between two route's that both have either async data or defineAsyncComponent's causes suspense pending issues.

### Additional context

I'm not sure if this is a Nuxt issue or not. If it's not I'm happy to rewrite the test case without Nuxt and report it on the Vue issue tracker.

**Comment by gijsroge** [comment]
@danielroe will do

**Comment by danielroe** [comment]
Any update on this? Were you able to confirm?
