### ISSUE TITLE
Feature "loading" like Nuxt 2

### ISSUE THREAD

**Issue by bynicodevelop** [nuxt/framework#3039]
### Environment

Nuxt 3

### Reproduction

In nuxt 2 there was this feature: https://nuxtjs.org/docs/features/loading/

### Describe the bug

My question is: is it available in Nuxt 3?
I don't see it in the docs.

Where is it present under another feature?

**Comment by wobsoriano** [comment]
Someone implemented this https://github.com/nuxt/framework/discussions/2100

**Comment by retuerto** [comment]
[The loading indicator Property](https://nuxtjs.org/docs/features/loading/#the-loading-indicator-property)
very interesting feature for SPA

**Comment by ennioVisco** [comment]
Available as of `v3.0.0.rc6`. See https://v3.nuxtjs.org/api/components/nuxt-loading-indicator.
The issue can be closed 😊

cc @pi0
