### ISSUE TITLE
[Middleware] Hydration node mismatch

### ISSUE THREAD

**Issue by bynicodevelop** [nuxt/framework#3040]
### Environment

Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0-27396610.ed4f4f5`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Vite`
- User Config:      `css`, `build`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Middleware (is global `auth.global.ts` ) code : 

```typescript
export default defineNuxtRouteMiddleware((to, from) => {
    // return a function 'onGetCookie' with undefined or the value
    const { onGetCookie } = useCookieManager();

    const protectedRoutesName = ['adminer'];

    if (protectedRoutesName.includes(to.name as string) && !onGetCookie("authenticated")) {
        console.log("Redirecting to auth page");

        return navigateTo('/auth');
    }
})
```

### Describe the bug

The console show this : 

<img width="528" alt="CleanShot 2022-02-03 at 09 31 03@2x" src="https://user-images.githubusercontent.com/32275195/152307484-9e2fd647-26b1-47c4-8a80-aa808d289b60.png">

**Comment by bynicodevelop** [comment]
The problem came from a missing "div" in a layout.

**Comment by bynicodevelop** [comment]
Clarification: All my templates have a div at the root

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by sasial-dev** [comment]
@aw-0 and I were able to repro this issue on his end only - not mine.
This is when we used a Visual Studio Code Live Share session that I hosted, and had :3000 & :24678 shared.
The weird thing was it didn't repro on my end, only his...

**Comment by sasial-dev** [comment]
Our middleware code is:
```ts
import { useUserStore } from "~/store/user"

export default defineNuxtRouteMiddleware((to, from) => {
	if (useUserStore().isLoggedIn) {
		if (to.path.startsWith("/auth/")) {
			return navigateTo("/")
		}
	} else {
		if (!to.path.startsWith("/auth/")) {
			return navigateTo("/auth/login")
		}
	}
})
```

**Comment by danielroe** [comment]
I can't reproduce this. I suspect it's to do with your `useUserStore().isLoggedIn`, which I can't test. If you're still experiencing this, would you provide an online sandbox with a reproduction so I can investigate it, and I'll reopen?

**Comment by ziaadini** [comment]
i have same issue but my issue is clear  first of all look at this code please:
```
import { useAuthStore } from "~~/composables/auth/Auth.store";
import { isAuthRoute } from "~~/helpers/authHelper";

export default defineNuxtRouteMiddleware((to, from) => {
    const nuxtApp = useNuxtApp();
    const authStore = useAuthStore(nuxtApp.pinia)
    console.log("isLoggedIn", authStore.isLoggedIn)
    if (process.client) {
        const hasAccess = authStore.isLoggedIn || !isAuthRoute(to.path)
        console.log("hasAccess", hasAccess);
        if (!hasAccess) {
            return navigateTo('/auth')
        }
    }
})

```
the problem is when process is in client (on page reload not navigate from another page it's clear on navigation there is no hydration at all) and we call   `return navigateTo('/auth')`.
needless to say i can't check in the server because i don't load token in server because of my project cache policy
