### ISSUE TITLE
`useNuxtApp` type `any`

### ISSUE THREAD

**Issue by ewilan-riviere** [nuxt/framework#3051]
### Environment

Nuxt CLI v3.0.0-27389502.88da719
RootDir: C:\workspace\current\bookshelves-front
Nuxt project info:

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.18.2`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I've create a clean repository: <https://gitlab.com/ewilan-riviere/nuxt-bridge>

- Node: v14.18.0
- Yarn: v1.2

```bash
git clone https://gitlab.com/ewilan-riviere/nuxt-bridge
cd nuxt-bridge
yarn
yarn dev
```

In `pages/index.vue`, the method `useNuxtApp()` have `any` type.

I've built a [CodeSandebox example](https://codesandbox.io/s/nuxt-bridge-rpjjh?file=/pages/index.vue)

### Describe the bug

*I know Nuxt Bridge evolve, I just need to know if it's a problem within my configuration or if isn't not implemented yet.*

I use [nuxt bridge documentation](https://v3.nuxtjs.org/getting-started/bridge-composition-api#usecontext-and-withcontext) to install bridge on my project.
With [composition api](https://composition-api.nuxtjs.org/), when I use `useContext()` I have type and autocompletion.

```js
import { defineComponent, useContext } from '@nuxtjs/composition-api'

export default defineComponent({
  setup() {
    const { store } = useContext()
    store.dispatch('myAction')
  },
})
```

With `bridge`, when I use new syntax, the method `useNuxtApp()` return `any` and I haven't not autocompletion.

```js
import { useNuxtApp } from '#app'
const { $axios } = useNuxtApp()
```

I think isn't a bug but I didn't find any issue about this, so I don't know if it's my config.

### Additional context

![image](https://user-images.githubusercontent.com/48261459/152348221-1d20f707-5401-417d-9f88-8e5586cdcbc7.png)

**Comment by danielroe** [comment]
What IDE are you using?

**Comment by ewilan-riviere** [comment]
I use Visual Studio Code with Volar.

I have this config for typescript

```json
{
  "typescript.tsdk": "./node_modules/typescript/lib",
}
```

**Comment by ewilan-riviere** [comment]
Thanks, it works perfectly now!
