### ISSUE TITLE
Can not access to component methods in page using `this.$refs`

### ISSUE THREAD

**Issue by alijmlzd** [nuxt/framework#3054]
### Environment

- Operating System: `Darwin`
- Node Version:     `v17.0.0`
- Nuxt Version:     `3.0.0-27396610.ed4f4f5`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `css`, `build`, `publicRuntimeConfig`, `serverMiddleware`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Create a component and add a method like this:

```js
// ~/components/player.vue
<script>
export default {
    methods: {
        play() {
            // Play something
        },
    },
}
</script>
```

2. Create a page and use the player component and assign a ref to it:

```js
// ~/pages/index.vue
<template>
    <Player ref="player" />
</template>
```

3. Now in the page `index.vue` I should be able to access player component's methods like this:

```js
// ~/pages/index.vue
<script>
export default {
    mounted() {
        this.$refs.player.play()
    },
}
</script>
```

But it is not working and occurs an error:

```
Uncaught (in promise) TypeError: this.$refs.player.play is not a function
```

### Describe the bug

In Nuxt 2 we can use a component's methods in another component or page by using `$refs`.
Currently, in Nuxt 3 I can not use this approach.

### Logs

```shell
Uncaught (in promise) TypeError: this.$refs.player.play is not a function
```

**Comment by danielroe** [comment]
> $refs are only populated after the component has been rendered. It is only meant as an escape hatch for direct child manipulation - you should avoid accessing $refs from within templates or computed properties.

See https://v3.vuejs.org/guide/component-template-refs.html#template-refs.

I'm closing it as it looks to me as though you're simply accessing a ref before the component has been rendered. But if you think it's a Nuxt issue, feel free to provide a reproduction and I'll have a look.

**Comment by alijmlzd** [comment]
I'm using `$refs` in the `mounted` state just like the guide link you mentioned but not works as expected.
I have not tested this issue with Vue 3 standalone but in Nuxt 3 It obviously does not work.

**Comment by alijmlzd** [comment]
@danielroe  I've edited the reproduction code to show you exactly what I want to do.
Just to remind, can you check that and help to resolve this issue because it is not resolved actually.

**Comment by danielroe** [comment]
@alijmlzd Would you [provide a reproduction](https://v3.nuxtjs.org/community/reporting-bugs#create-a-minimal-reproduction) using either codesandbox or stackblitz?

**Comment by alijmlzd** [comment]
@danielroe Sure, here is the reproduction on CodeSandbox:
https://codesandbox.io/s/sad-voice-uhkb2?file=/components/player.vue
It is very strange, when I use any composable in `player.vue` component, then calling the `$refs` in `app.vue` occurs the error but without composable in `player.vue` it is working!

I've also created this reproduction using StackBiltz and it is working on it.
https://stackblitz.com/edit/github-nzup6k?file=components/player.vue
I don't know what is the difference on the StackBiltz environment to make it works but Its node version is `14.17.0` which I've tested this version with my project and not been successful.

**Comment by danielroe** [comment]
I've looked into this and the change in behaviour was [introduced in Vue 3.2.25](https://github.com/vuejs/core/blob/main/CHANGELOG.md#3225-2021-12-12). Would you raise an issue [there](https://github.com/vuejs/core) instead?

**Comment by alijmlzd** [comment]
Thank you @danielroe,
It is not clear to me, is there any alternative or quick fix for this situation on nuxt?
I can create a new issue on Vue repo but first I need to understand the issue on vue and have a reproduction.

**Comment by alijmlzd** [comment]
I moved the composable const from script tag to `setup()` like this and it is working fine for now.
```js
setup() {
        const test1 = useTest1()
        return { test1 }
},
```
