### ISSUE TITLE
Import of types in `<script setup lang="ts">` is causing SSR to fail when using `<template lang="pug">`

### ISSUE THREAD

**Issue by qnp** [nuxt/framework#3061]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27373739.0ed2d4a`
- Package Manager:  `yarn@1.17.3`
- Bundler:          `Vite`
- User Config:      `typescript`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Here is a minimal repro project (could not manage to use nuxt 3 in codesandbox reliably)

[script-setup-ts-types-import.zip](https://github.com/nuxt/framework/files/7998126/script-setup-ts-types-import.zip)

Run `yarn install` then `yarn dev`

### Describe the bug

Two identical components have been created, one using a pug template (`PugButton.vue`), the other one a regular html template (`OkButton.vue`). Both are importing the type
```ts
import { RouteLocationRaw } from "vue-router"
``` 
to use it in Props definition.

Toggle in `page/index.vue` the button you want to use. In the case of `PugButton.vue`, you will see a runtime error in browser console : 

```
PugButton.vue:9 
Uncaught (in promise) SyntaxError: The requested module '/_nuxt/node_modules/.vite/vue-router.js?v=38aac643' does not provide an export named 'RouteLocationRaw'
Promise.then (async)
entry @ entry.mjs:1
(anonymous) @ entry.mjs:3
```

**Comment by qnp** [comment]
For the record, we managed to circumvent the problem by exposing what we need in a typescript definition file `index.d.ts` as such:
```
declare {
  export { RouteLocationRaw } from "vue-router"
}
```
that allows us not to import it on the `.vue` SFC file

**Comment by qnp** [comment]
Another way to bypass the problem is to specify that we import a `type`:
```ts
import type { RouteLocationRaw } from "vue-router"
```

**Comment by danielroe** [comment]
This is [reproducible in vite](https://stackblitz.com/edit/vitejs-vite-mzp5by?file=src%2FApp.vue&terminal=dev) and is not a Nuxt issue. Personally I would simply use `import type` syntax, but if not, I'd suggest [raising an issue in the Vite repo](https://github.com/vitejs/vite).
