### ISSUE TITLE
Cannot read file /.nuxt/tsconfig.json

### ISSUE THREAD

**Issue by dungonfq** [nuxt/framework#3086]
### Environment

Production: `nuxi build`

Nuxt3: `^3.0.0-27398533.8edd481`

### Reproduction

My project is now running with Docker on Jenskin. This is our Dockerfile to setup:
```
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# If you are building your code for production
# RUN npm install --only=production
RUN npm install
#RUN npm install acorn-dynamic-import --save-dev
# Bundle app source
COPY . .
RUN npm run build
ENV HOST 0.0.0.0
ENV PORT 3000
EXPOSE 3000
CMD [ "npm", "start" ]
```

My `tsconfig.json`
```json
{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "moduleResolution": "node",
    "types": [
      "nuxt-windicss",
      "jest"
    ]
  }
}
```

Step we can reproduce:
1. npm install
2. npm run build
3. npm run test

### Describe the bug

Jenskin build cannot detect` ./.nuxt/tsconfig.json` in `tsconfig.json`
![cannot-read-tsconfig](https://user-images.githubusercontent.com/57652048/152718904-82394c6c-e66b-446f-93cf-cb9d23f29e53.jpeg)

Same happens when I deleted `.nuxt` folder on local:
<img width="772" alt="tsconfig" src="https://user-images.githubusercontent.com/57652048/152718964-eee038fd-f51f-400d-be9a-1b035e740b05.png">

This is my project after `npm run build` locally, which has `./.nuxt/tsconfig.json`. But seem like Jenskin + Docker are missing this folder.
<img width="912" alt="project" src="https://user-images.githubusercontent.com/57652048/152718995-b49bd3d2-e449-43e6-a125-1387e2a53eae.png">

Pls, help to take a look. Thank u a lot.

### Additional context

#1912

**Comment by dungonfq** [comment]
#3067
#1912

**Comment by HendrikJan** [comment]
To my non-expert eyes this seems more like a docker configuration problem than a nuxt issue.

It seems like you run `npm run dev` inside `/usr/src/app` based on these lines in your dockerfile:
```dockerfile
WORKDIR /usr/src/app
RUN npm run build
```

Then you try to start the your test in folder `/home/ec2-user/workspace/fer-com_fe-customer-account_PR-6` based on your screenshot:
```
docker run .... -w /home/ec2-user/workspace/fer-com_fe-customer-account_PR-6 ...
```

So `.nuxt` is created in `/usr/src/app` while your test code tries to find it in `/home/ec2-user/...`, so it fails.

Maybe you can find a way to print out your project inside docker after `npm run build` to check that the `.nuxt` folder is there.
(something like `docker exec -it $IMAGE_NAME:test bash` and then use the `ls` command to list). That might help you debug.

**Comment by dungonfq** [comment]
Thank @HendrikJan, I thought the same & trying to check the project inside docker.

**Comment by HendrikJan** [comment]
@dungonfq Good luck!
