### ISSUE TITLE
can't return `navigateTo` after await in route middleware (on server)

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#3105]
Hello. I am trying to implement route middleware, and have some issues with that.

```
export default defineNuxtRouteMiddleware(async (to) => {
    const { fetchList } = useList();
    const { start, finish, fail } = useProgress();

    try {
        const {
            query: { page },
        } = to;

        const currentPage = page ? Number(page) : null;

        start();
        const res = await fetchList(currentPage);
        finish();
        console.log(res, 'finish');
    } catch (error) {
        fail();
        if (process.server) return navigateTo('/');
        else return abortNavigation();
    }
});
```

So, the point is - i am loading data list, and accepting the route only if fetch is complete.
If loading fails, on server side it should redirect to main page, on client side - just abort navigation.

I thought middlewares should be isomorthic and works same way on server and client sides, but when i call "navigateTo('/')" on server side, i see this: 

![image](https://user-images.githubusercontent.com/28978908/152785743-6ae3fc15-12a6-4b3d-bac1-ca3700149c34.png)

on client side it works perfectly.
Any thoughts?

_Originally posted by @Harkonnen13 in https://github.com/nuxt/framework/discussions/3100_

**Comment by pi0** [comment]
What about moving `navigateTo` and `abortNavigation` to `nuxtApp` instance? `useNuxtApp()` can be cached before any await operator. Or we could support a AST transformer to restore context similar to `script setup` and use for `defineNuxtRouteMiddleware`, `defineNuxtPlugin`, `async setup() {}`, etc

**Comment by danielroe** [comment]
This should now be resolved in https://github.com/nuxt/framework/pull/3884. Let me know if not and I can reopen.

**Comment by cirkuzant** [comment]
I have the same problem in middleware (Nuxt 3.0.0-rc.4):

```
import {defineNuxtRouteMiddleware, navigateTo} from 'nuxt/app';

export default defineNuxtRouteMiddleware((from, to) => {
  return navigateTo('https://www.google.com');
});
```

Throws error:
```
[nuxt] [request error] nuxt instance unavailable
```

**Comment by danielroe** [comment]
You should not import from `nuxt/app` but from `#imports`. If you are still experiencing a problem, please open a new issue with a reproduction.
