### ISSUE TITLE
Layouts not working with definePageMeta

### ISSUE THREAD

**Issue by folamy** [nuxt/framework#3114]
### Environment

Nuxt 3

### Reproduction

Nil

### Describe the bug

Just updated nuxt3@latest,  and discovered that definePageMeta is not working anymore

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/discussions/2883: `<NuxtLayout>` has been extracted from `<NuxtPage>` and needs to be manually added to `app.vue` if you are using it.
