### ISSUE TITLE
Object type parameters cannot be used in fetch

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#3124]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27404660.0f9bcbf`
- Package Manager:  `npm@8.4.1`
- Bundler:          `Vite`
- User Config:      `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/flamboyant-leavitt-63k09

### Describe the bug

The parameters are not sent correctly in fetch. Something like `/articles?filter=[object+Object]` is sent when I'm sending something like:
```
filter: {
  include: ['images', 'category', 'attributes']
}
```

The correct path would be something like `/articles?filter[include][0]=category&filter[include][1]=attributes&filter[include][2]=images`

**Comment by frbuceta** [comment]
Following the trace, the error may be the [ufo](https://github.com/unjs/ufo) package

**Comment by danielroe** [comment]
I've had a look, and I think that the current is likely the correct behaviour. See https://url.spec.whatwg.org/#urlsearchparams (and follow the rabbit hole!). How are you intending to parse the query string that is generated here?

**Comment by frbuceta** [comment]
> I've had a look, and I think that the current is likely the technically correct behaviour. See https://url.spec.whatwg.org/#urlsearchparams (and follow the rabbit hole!). How are you intending to parse the query string that is generated here?
> 
> ```js
> const search = new URLSearchParams()
> search.set('filters', { include: [1, 2, 3] })
> search.toString()
> // "filters=%5Bobject+Object%5D"
> ```

It's weird... You can see what I'm trying to do [here (qs library)](https://github.com/ljharb/qs).

For example:
```js
qs.stringify({ a: { b: { c: 'd', e: 'f' } } });
// 'a[b][c]=d&a[b][e]=f'
```

**Comment by danielroe** [comment]
Yes, understood. `qs` implements its own pattern, and there are other patterns as well, which is part of the issue - there's no single clear pure JS standard to implement within `ufo`.

**Comment by danielroe** [comment]
I'm closing this for now as it's an `ohmyfetch` feature request. The upstream issue to track is https://github.com/unjs/ufo/issues/41.
