### ISSUE TITLE
Support firebase regions other than the default

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#3126]
See https://firebase.google.com/docs/functions/manage-functions#modify-region

context: https://github.com/nuxt/framework/discussions/3123

**Comment by pi0** [comment]
https://github.com/unjs/nitro/issues/90

**Comment by mulhoon** [comment]
It would be nice to define the default region somehow, but `firebase.json` doesn't support that.  So regions are usually defined per function: 

```js
exports.webhookEurope = functions
    .region('europe-west1')
    .https.onRequest((req, res) => {
            res.send("Hello from Europe");
    });
```

How could it be defined in the nuxt handler?

```js
export default defineEventHandler((event) => {
  return {
    message:"Hello"
  }
})
```

This seems tricky... Could it be that we use the folder structure somehow? For example, if you're using Firebase then you could do the following:

```
server/api/europe-west1/posts.get.ts
server/api/asia-southeast1/posts.get.ts
```

or...

```
server/api/posts.get.europe-west1.ts
server/api/posts.get.asia-southeast1.ts
```
