### ISSUE TITLE
Nuxt config components dirs behavior

### ISSUE THREAD

**Issue by Harkonnen13** [nuxt/framework#3129]
### Discussed in https://github.com/nuxt/framework/discussions/3128

<div type='discussions-op-text'>

<sup>Originally posted by **Harkonnen13** February  8, 2022</sup>
Hello. Previously i had config like that, for the namespace reasons:

```
export default defineNuxtConfig({
    components: {
        dirs: [
            '~/components', 
            { path: '~/components/controls', extensions: ['vue'] },
        ],
    },
})
```
and it doesn't work for now:

![image](https://user-images.githubusercontent.com/28978908/152989120-c76b6629-d3bb-4214-9aab-740f45b58336.png)

I think, its related to https://github.com/nuxt/framework/pull/3108, but just to be sure - can i make nested dirs inside components directory?

or should i put them into top level directory like this?

```
export default defineNuxtConfig({
    components: {
        dirs: [
            '~/components', 
            '~/controls', 
        ],
    },
})
```</div>

**Comment by danielroe** [comment]
This issue should now be resolved.
