### ISSUE TITLE
non-`<head>` locations for scripts

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#3130]
We currently use `@vueuse/head` for managing meta tags, but we don't have support for rendering script tags outside of `<head>` - required (for example) by https://github.com/nuxt-community/color-mode-module.

It would be nice to add support either to nuxt 3 or upstream.

**Comment by baixiaoyu2997** [comment]
hi, danielroe， is there any way to make `script ` in `useHead` to sync ? 
now like:
```js
// public/test.js
window.test=123
```
```
useHed({
    script:[{ src :'/test.js'}]
})
onMounted(()=>{
    console.log(window.test)   // undefined
})
```
how can i do

**Comment by loubingzhuxue** [comment]
Any update of this ?
