### ISSUE TITLE
null response on load of the nested child when using useLazyFetch on bridge

### ISSUE THREAD

**Issue by csechuan** [nuxt/framework#3135]
### Discussed in https://github.com/nuxt/framework/discussions/3083

<div type='discussions-op-text'>

<sup>Originally posted by **csechuan** February  7, 2022</sup>
### Reproduction 
[https://github-rxxzhp-cpxf9c--3000.local.webcontainer.io/](url)

Steps
1. Open your console
2. Click "Go cinema"
3. Click "Watch movie"
```
// console output
movie env client res {"data":{"value":null},"pending":{"value":true},"error":{"value":null}}
```
4. Click "Back"
5. Click "Go cinema" again
```
// console output
movie env client res {"data":{"value":{A_LOT_OF_DATA_HERE}},"pending":{"value":true},"error":{"value":null}}

// check the network tab for movie. you should see the API response fine.
```
6. Repeating steps 4-5 will have the same result

### Description of the bug
Fetch response does not have data on first try. Subsequently it prints some data.

### Additional context
Besides, i found another bug during debugging this issue. The `pending` flag is always true when `useLazyFetch` runs on client. I may not use the function correctly.

```
<script setup>
// since vue2 on nuxt bridge cant use top-level await
useLazyFetch('URL_HERE').then(res => console.log(res))
</script>
```
</div>

**Comment by danielroe** [comment]
Would you provide a reproduction?

**Comment by csechuan** [comment]
yeah. i've included the link 

https://github-rxxzhp-cpxf9c--3000.local.webcontainer.io/

**Comment by danielroe** [comment]
That link only works on your computer. I need the link to the stackblitz reproduction.

**Comment by csechuan** [comment]
sorry. terrible mistake. didnt notice that. try this

https://codesandbox.io/s/morning-moon-t23s3

**Comment by danielroe** [comment]
The data from `useLazyFetch` isn't meant to be used within the setup function (that's why it's `lazy`). Instead it returns a reactive ref that gets filled in later. So you handle it like this: https://v3.nuxtjs.org/docs/usage/data-fetching#example-3
