### ISSUE TITLE
All components are wrapped into defineAsyncComponent

### ISSUE THREAD

**Issue by Tahul** [nuxt/framework#3144]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27406801.569aaeb`
- Package Manager:  `yarn@3.1.1`
- Bundler:          `Vite`
- User Config:      `modules`
- Runtime Modules:  `nuxt-windicss@2.2.4`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/Tahul/nuxt-3-components

- yarn install
- yarn dev
- Search for `components = {` in `.nuxt/dist/server.mjs`

### Describe the bug

When using `components` key from `nuxt.config`, it seems like every imported component will be injected into the Vue app wrapped into a `defineAsyncComponent` function.

For some component implementations, this behavior is a blocker, as it avoids the render function to access the said component and to guess its type.

I think it is necessary for users and modules to know if the component they inject will be treated asynchronously or not.

Also, as seen in the screenshot, components prefixed with `Lazy` and those who aren't seem to be pointing to the same key.

### Additional context

<img width="1136" alt="CleanShot 2022-02-09 at 23 16 40@2x" src="https://user-images.githubusercontent.com/1385263/153299504-4f9a666d-b060-4516-a385-7687d33acc3c.png">

Reference in framework code:
https://github.com/nuxt/framework/blob/main/packages/nuxt3/src/components/templates.ts#L35

**Comment by pi0** [comment]
When global flag is enabled (by default), **in addition to** inlining components, a global plugin registers async version of components which makes it possible to dynamically import them even if build-time cannot eagerly add to proper chunks. (when using `<component :is"">` for example)

If you check page chunks, components are directly imported in chunk:

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/5158436/153304057-8ed7b864-e02c-4f87-99db-b0eda924a052.png">

**Comment by pi0** [comment]
(This is rather a confusing behavior BTW. PR more than welcome to clarify in docs)

**Comment by pi0** [comment]
No there is no option to force add components in main bundle (nor I would recommend to introduce). We might find better ways to prefetch the necessary components for dynamic scenarios.

**Comment by Tahul** [comment]
Hello @pi0 😄 

We actually walked on this one while building the unwrap feature for the Markdown component of @nuxt/content.

This feature allows theme authors / people creating components to use the `<Markdown>` component to replace slot of their components by a Markdown-renderer slot which takes their markdown content and uses Prose components to render it.

Unwrap allows the Markdown component to render nested Markdown components properly when used to fill a component.

As an example:

```
// content.md

::my-custom-list-component
- foo
- bar
- baz
::

// MyCustomListComponent.vue
<template>
   <ul>
	  <!-- Use unwrap here because we don't want to manage the ul tag locally -->
      <Markdown :use="$slot.default" unwrap="ul" />
   </ul>
</template>
```

This example is really specific, but manipulating slots content can be required if you want to build things with render functions.

If we want to reach a complete implementation of this feature, we need the resolveComponent function from Vue to return the correct component when called. It actually returns AsyncComponentWrapper for any component.

What I suggest is to add an option for users to configure how their components are registered into the Vue instance.

I think this ain't the only case in which this kind of components registering could be problematic, as it can make interactions with slots and render functions harder.

A complete reproduction to this problem can be found here:
https://github.com/nuxt/content-next/pull/12

Run the branch with `yarn && yarn dev`, visit `/unwrap` page and open console.
