### ISSUE TITLE
When can the request nuxt3 be recommended for production? When is the official version expected to be released? Thank you

### ISSUE THREAD

**Issue by JessieChen5** [nuxt/framework#3152]
### Environment

When can the request nuxt3 be recommended for production? When is the official version expected to be released? Thank you

### Reproduction

When can the request nuxt3 be recommended for production? When is the official version expected to be released? Thank you

### Describe the bug

When can the request nuxt3 be recommended for production? When is the official version expected to be released? Thank you

**Comment by danielroe** [comment]
In future, please raise this kind of question in Discussions, rather than as an issue. 🙏

We expect a release candidate at the end of the first quarter of this year, and a final release by the end of the year at the latest.
