### ISSUE TITLE
ERROR  [worker] Cannot read properties of undefined (reading 'getSSRProps')   

### ISSUE THREAD

**Issue by andysay** [nuxt/framework#3154]
### Environment

Nuxt CLI v3.0.0-27406801.569aaeb                                                                                                                                                           10:01:04
RootDir: /Users/andreyleonov/Desktop/SS                                                                                                                                                    10:01:05
Nuxt project info:                                                                                                                                                                         10:01:05

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27406801.569aaeb`
- Package Manager:  `npm@8.1.0`
- Bundler:          `Vite`
- User Config:      `vue`, `privateRuntimeConfig`, `publicRuntimeConfig`, `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```
export default defineNuxtConfig({
    vue: {
        compilerOptions: {
            directiveTransforms: {
                motion: () => ({
                    props: [],
                    needRuntime: true
                })
            }
        }
    }
})

```

[Vue warn]: Failed to resolve directive: motion

 ERROR  [worker] Cannot read properties of undefined (reading 'getSSRProps')     

https://codesandbox.io/s/affectionate-glade-37lkf?file=/pages/index.vue
    

### Describe the bug

after update 

 nuxt3  3.0.0-27403901.b3e9cf6  →  3.0.0-27406801.569aaeb

**Comment by danielroe** [comment]
You need also to have a directive.

[Working example](https://codesandbox.io/s/gifted-shape-21pyh?file=/plugins/directive.ts).

**Comment by svdtz** [comment]
Hi,
unfortunately this solution does not work in my use case:

https://gist.github.com/BananaAcid/65ac40bdbaba8d3daff1754a77c70691

the code works as expected but it throws errorMessages and warnings:

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/60693612/183415487-8adfdf84-48ce-463f-b845-cf87ed543911.png">

I'm using nuxt 3.0.0-rc.6 in my project.


Does anyone have a bug fix for this problem?

thanks a lot

**Comment by danielroe** [comment]
The issue is not caused by Nuxt but likely by some directive in your project that is not compatible with SSR.

**Comment by BananaAcid** [comment]
I believe the documentation is missing something or there is a bug about getSSRProps: https://v3.nuxtjs.org/guide/directory-structure/plugins/#vue-directives

When I copy the content and paste it into `/plugins/focus.ts` or `/plugins/focus.client.ts` I get the same getSSRProps missing error as anyone above - but the besides the error, it seems to work on most mounted elements.

(To check, the `.focus()` changed to `.style.color = 'green'` did its job)

**Comment by sh0ber** [comment]
I got this error when creating a plugin with a .client.js suffix (the plugin created a directive).  Removing the `client` extension fixed it.  This wasn't obvious at first.

**Comment by davestewart** [comment]
Hello, I managed to trigger this by adding an unknown directive to a template:

```vue
<template>
  <div v-test />
</template>
```
```
500
Cannot read properties of undefined (reading 'getSSRProps')

at _sfc_ssrRender (./src/app.js:27:134)
...
```

It would be nice to defend against this if possible, or maybe throw a more friendly error message such as "unknown directive `test`"
