### ISSUE TITLE
definePageMeta doesnt apply the correct layout

### ISSUE THREAD

**Issue by Blakeinstein** [nuxt/framework#3155]
### Environment

```
RootDir: /sandbox                                                                    06:59:32
Nuxt project info:                                                                   06:59:32

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27406801.569aaeb`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://codesandbox.io/s/silent-brook-m9q8l?file=/pages/test.vue

### Describe the bug

With the recent breaking change, discussed here, https://github.com/nuxt/framework/discussions/2883 . Only the default layout seems to be getting applied. Notice the test page, it should use the custom layout, but doesnt do so and ends up using the default layout.

**Comment by Blakeinstein** [comment]
> also in your repro.
> 
> <img alt="Bildschirmfoto 2022-02-10 um 20 19 05" width="377" src="https://user-images.githubusercontent.com/20044441/153480899-f24aacf8-9b1c-49da-9e17-d3aee9d58357.png">

Strange, maybe a recent pr has fixed this? I actually created this issue after we confirmed this over discord.

**Comment by Patrick-Remy** [comment]
Did you probably forgot to wrap into `<NuxtLayout><NuxtPage /></NuxtLayout>` when you migrated to `definePageMeta()`? I fall myself into this on my first attempt.

**Comment by danielroe** [comment]
Can you still reproduce this locally if you upgrade your nuxt instance with `npx nuxi upgrade` @Blakeinstein?

**Comment by ennioVisco** [comment]
> Did you probably forgot to wrap into `<NuxtLayout><NuxtPage /></NuxtLayout>` when you migrated to `definePageMeta()`? I fall myself into this on my first attempt.

I have the same issue, what do you mean? [Here](https://v3.nuxtjs.org/docs/directory-structure/layouts/) it says that `<NuxtLayout><NuxtPage /></NuxtLayout>`  is only required when `layout` is false

**Comment by Patrick-Remy** [comment]
If you have a custom `app.vue`, you previously only needed the `<NuxtPage />` element.  
See: https://v3.nuxtjs.org/docs/directory-structure/app

**Comment by ennioVisco** [comment]
> If you have a custom `app.vue`, you previously only needed the `<NuxtPage />` element. See: https://v3.nuxtjs.org/docs/directory-structure/app

Actually I just found out the hard way, too bad I didn't see your reply. 
I can confirm, the problem appears when a custom `app.vue` is defined that calls a `<NuxtPage />` without wrapping it in a `<NuxtLayout>`.

**Comment by danielroe** [comment]
Just to be clear, that is the current desired behaviour. Make sure to check https://github.com/nuxt/framework/discussions/2883 when upgrading beta versions of Nuxt.

**Comment by Patrick-Remy** [comment]
> Just to be clear, that is the current desired behaviour. Make sure to check https://github.com/nuxt/framework/discussions/2883 when upgrading beta versions of Nuxt.

@danielroe how about mention this in the README?

**Comment by danielroe** [comment]
In these pre-RC versions, we will keep the discussion I linked up to date, rather than updating the readme. The docs were already updated in the PR that made the change.

**Comment by Patrick-Remy** [comment]
I think for the developers who are already using nuxt3 to report issues, a short hint with a link to the BC discussion inside the docs would be helpful.

**Comment by danielroe** [comment]
Both good suggestions, and PRs would be welcome.

**Comment by Blakeinstein** [comment]
>  PRs would be welcome.

Will gladly take this up.
