### ISSUE TITLE
Auto import for shared composable not generating correctly when exporting from file

### ISSUE THREAD

**Issue by nurdism** [nuxt/framework#3157]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27406801.569aaeb`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/priceless-wood-1lhpb

`~/composables/test.ts`

```ts
export { useTestMe1 } from "@/test/foo1";
export { useTestMe2 } from "@/test/foo2";
export { useTestMe3 } from "@/test/foo3";
```

`cat .nuxt/types/auto-imports.d.ts`

```ts
const useTestMe3: typeof import("../../composables/test")['useTestMe3']
```

only the last export is produced

### Describe the bug

Only the last export is produced when exporting shared composables that export from a file

**Comment by danielroe** [comment]
Regression introduced in https://github.com/unjs/mlly/pull/39.
