### ISSUE TITLE
[Nuxt3] Dynamic router middleware in plugins do not trigger on initial load when in index file in subdirectory

### ISSUE THREAD

**Issue by oysandvik94** [nuxt/framework#3164]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27403956.614e87e`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `buildModules`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

Simple plugin using the dynamic middleware example from https://v3.nuxtjs.org/docs/directory-structure/middleware
```
import { defineNuxtPlugin } from '#app'
import { AuthClient } from './auth/authClient';

export default defineNuxtPlugin(nuxtApp => {
  addRouteMiddleware('global-test', () => {
    console.log('this global middleware was added in a plugin and will be run on every route change')
  }, { global: true })
})
```

If this is in a file `test.ts`directly in the `plugins` directory, then the console.log will fire on page load. 

If this is in a file `index.ts` under a `test` directory under the `plugins`directory then it will only fire on route changes (router.push events and so on).

### Describe the bug

Dynamic router middleware behaves differently when it's in a plugin that's structured in a sub-directory vs a plugin directly in the plugin directory. 

When in subdirectoy it will not fire on page-load, while when in a plugin in the "plugins" directory it will fire on all of them. 

### Additional context

Not sure if it's relevant, but I noticed that it resolves all the plugins directly in the `plugins` directory before it resolves the ones in subdirectory. So the plugin load order here:

~/plugins
    - aPlugin/index.ts
    - bPlugin.ts
    - cPlugin.ts

Would be initialized/resolved in this order:
1. bPlugin.ts
2. cPlugin.ts
3. aPlugin.ts

**Comment by danielroe** [comment]
I cannot reproduce this. Would you provide a reproduction? 🙏

**Comment by danielroe** [comment]
This should be resolved now that we are running all plugins before running middleware. Let me know if not and I'll reopen.

**Comment by oysandvik94** [comment]
Sorry, forgot about the reproduction!

Everything is working fine now, thank you very much 🧨
