### ISSUE TITLE
nuxi generate: ReferenceError: System is not defined

### ISSUE THREAD

**Issue by yassilah** [nuxt/framework#3172]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `target`, `srcDir`, `dir`, `bridge`, `head`, `components`, `generate`, `build`, `plugins`, `buildModules`, `modules`, `alias`, `vite`, `hooks`, `layouts`, `autoImports`, `database`, `info`, `style`, `fonts`
- Runtime Modules:  `normalizedModule()`
- Build Modules:    `@nuxt/bridge@3.0.0-27408103.b243891`, `normalizedModule()`, `normalizedModule()`, `normalizedModule()`, `normalizedModule()`, `normalizedModule()`, `normalizedModule()`, `normalizedModule()`, `normalizedModule()`, `normalizedModule()`, `@vueuse/nuxt@7.6.1`, `unplugin-icons/nuxt`, `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

Simply run `nuxi generate` in a nuxt bridge project, then run `nuxi preview`.

### Describe the bug

An error is thrown from the `entry-legacy` file: `Uncaught (in promise) ReferenceError: System is not defined`.

**Comment by IlyaSemenov** [comment]
It's not only `nuxi generate` but also `nuxi build`. There is no SystemJS runtime in the final production build, and all client-side code doesn't load and doesn't start.
