### ISSUE TITLE
Improve warning about `definePageMeta()` outside `setup`

### ISSUE THREAD

**Issue by Patrick-Remy** [nuxt/framework#3175]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27408580.aece351`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `target`, `head`, `srcDir`, `css`, `plugins`, `components`, `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```vue
<script lang="ts">
definePageMeta({
  layout: 'hero'
})

export default defineComponent({
 // ...
})
</script>
```

### Describe the bug

In a recent update, a new warn has been added when using `definePageMeta()` outside the `setup()` method. But it's a bit misleading, as it insinuates that it's *only* usable inside `<script setup>`. But it is indeed possible inside
```ts
export default defineComponent({
  setup () {
    definePageMeta({
      layout: false
    })
  },
  // ....
})
```

### Additional context

Output of `npm run dev`
```
✔ Nitro built in 129 ms
definePageMeta() is a compiler-hint helper that is only usable inside <script setup> of a single file component. Its arguments should be compiled away and passing it at runtime has no effect.
✔ Vite server built in 416ms                      
```

Causing lines:
https://github.com/nuxt/framework/blob/68a227af037cc7c91b00787cadbd2653676e00ad/packages/nuxt3/src/pages/runtime/composables.ts#L27-L29

**Comment by luisfrocha** [comment]
I'm also getting it now, using Nuxt 3.0.0-rc.13. Sample code is:
```
<script setup>
  definePageMeta();
</script>
```
That triggers the message, no matter what config I put inside the parentheses.

**Comment by danielroe** [comment]
@luisfrocha Please open a new issue with a reproduction.

**Comment by acidjazz** [comment]
@luisfrocha have you opened an issue for this? I'm getting the same
