### ISSUE TITLE
pageTransition doesnt work

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#3184]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-27405808.7825e2a`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `css`, `app`, `nitro`, `srcDir`, `build`, `buildModules`, `modern`, `tailwindcss`, `meta`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.0-3`
------------------------------

### Reproduction

[example](https://codesandbox.io/s/friendly-goodall-guqc4?file=/pages/index.vue)

### Describe the bug

pageTransition doesnt work.
console.log => `definePageMeta() is a compiler-hint helper that is only usable inside <script setup> of a single file component. Its arguments should be compiled away and passing it at runtime has no effect.`
and no effect for page....

### Additional context

on my local machine there is no error, as well as no effect

**Comment by danielroe** [comment]
Transitions apply between page navigations.

https://codesandbox.io/s/sweet-maxwell-3bm5w?file=/pages/%5B...slug%5D.vue
