### ISSUE TITLE
Router scrollBehavior works only when  the page is loaded first time

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt/framework#3185]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-27409509.e727bb4`
- Package Manager:  `npm@8.3.1`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

Repository: https://github.com/lukaszflorczak/nuxt3-demo/tree/test/scroll-behavior (branch `test/scroll-behavior`)

1. Visit `http://localhost:300/#section-3`
2. Page should scroll smoothly to that section (the title should have 30px offset on top – from scroll behavior settings)
3. Scroll to the top and use the navigation – there is no smooth scrolling and offset

### Describe the bug

It looks that `scrollBehavior` works properly only when the page is loaded the first time. Each next event is ignored, even though it is handled by the appropriate condition (for example `if (to.hash)` – we get console log message).

https://user-images.githubusercontent.com/1818979/153574614-698866e7-467e-4599-8ee4-a6e0dd7e894b.mov

The plugin with settings: https://github.com/lukaszflorczak/nuxt3-demo/blob/test/scroll-behavior/plugins/router.ts

**Comment by danielroe** [comment]
It seems to be working fine.

![CleanShot 2022-02-14 at 09 19 20](https://user-images.githubusercontent.com/28706372/153835412-76db0434-b192-44b4-a37a-44a3f0ac7ca9.gif)

**Comment by Aareksio** [comment]
Reproduced on provided repository (Windows 10):
- [Chrome 98.0.4758.102](https://yko.im/9PzE.mp4) - no animation
- [Firefox 97.0](https://yko.im/iU_Z.mp4) - partial animation (exactly as on the video above)

Please also notice how the partial animation visible on my Firefox video as well as on @danielroe's video above differs from full animation visible on reload. Programmatically scrolling to elements (using either `scrollIntoView` or `scrollTo` with `behavior: 'smooth'`) does not give this janky effect.

**Comment by danielroe** [comment]
I don't believe this to be a Nuxt issue - would you raise it upstream at https://github.com/vuejs/vue-router? 🙏

**Comment by danielroe** [comment]
It's now possible to provide your own scrollBehavior with https://github.com/nuxt/framework/pull/3485. See https://v3.nuxtjs.org/docs/directory-structure/pages#router-options for documentation.
