### ISSUE TITLE
It's not possible (?) to redirect to custom error page

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt/framework#3195]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.0`
- Nuxt Version:     `3.0.0-27409701.61188e1`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ngtcnj?devtoolsheight=33&file=pages/index.vue

1. Visit for example `/test` page (it's not exist) => the custom `404.vue` page is used
2. Visit `/`page where is manually redirection after error returned from `useAsyncData()` => default Nuxt 404 page is used

### Describe the bug

Nuxt 3 uses the default error page in situations other than a not existing page in the `/page` directory. 

### Additional context

I use this code to do redirection (I found it in discussions or other issue):

```ts
if (error.value) {
  const err = new Error(`Page not found`);
  err.statusCode = 404;
  ssrContext.error = err;
}
```

https://user-images.githubusercontent.com/1818979/153594168-530d676e-3baa-41d0-9142-e776cd7038c5.mov

**Comment by danielroe** [comment]
Let's track progress on https://github.com/nuxt/framework/discussions/559
