### ISSUE TITLE
Layouts doesn't work

### ISSUE THREAD

**Issue by bacon-delight** [nuxt/framework#3206]
### Environment

Nuxt CLI v3.0.0-27409701.61188e1                                                                                                                                                                                       01:56:17
                                                                                                                                                                        01:56:18
Nuxt project info:                                                                                                                                                                                                     01:56:18

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.1`
- Nuxt Version:     `3.0.0-27409701.61188e1`
- Package Manager:  `npm@8.5.0`
- Bundler:          `Vite`
- User Config:      `css`, `vite`, `meta`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- Create a new nuxt project
- Remove `NuxtWelcome` in `app.vue` and add `NuxtPage`
- Create `layouts/default.vue` as
```vue
<template>
   <div>
      <div>Navigation</div>
      <slot />
   </div>
</template>
```

- Create `pages/index.vue` as
```vue
<template>
   <div>hello</div>
</template>

<script>
export default {
	layout: "default", // this should be optional
};
</script>
```

- Result is only `hello`, the `Navigation` is not rendered. Basically the layout is not being used, I tried with a `layout/custom.vue` and adding `layout: "custom"` in `pages/index.vue` also.

### Describe the bug

Layout is not being used, I tried with a `layout/custom.vue` and adding `layout: "custom"` in `pages/index.vue` also.

### This works perfectly in an earlier version:

Nuxt CLI v3.0.0-27337794.cac70e4                                                                                                                                                                                01:56:42
                                                                                                                                             01:56:43
Nuxt project info:                                                                                                                                                                                              01:56:43

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.1`
- Nuxt Version:     `3.0.0-27337794.cac70e4`
- Package Manager:  `npm@8.5.0`
- Bundler:          `Vite`
- User Config:      `css`, `vite`, `meta`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

**Comment by bacon-delight** [comment]
I also tried with:
```
definePageMeta({
  layout: "default", // also tried with another "custom" layout
});
```

This also doesn't work

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/discussions/2883 - the third one down.

**Comment by lukaszflorczak** [comment]
Add in `app.vue`:

```html
<nuxt-layout>
  <nuxt-page/>
</nuxt-layout>
```
