### ISSUE TITLE
Custom 500 error pages

### ISSUE THREAD

**Issue by chaorenluo** [nuxt/framework#3230]
### Environment

Operating System: macOS
Node Version: v14.18.0
Nuxt Version: 3.0.0-27404660.0f9bcbf
Package Manager: npm@6.14.15
Bundler: Vite
User Config: css, buildDir, build, buildModules, hooks
Runtime Modules: -
Build Modules: @nuxtjs/google-fonts@1.3.0

### Reproduction

Can you add custom 500 error pages

### Describe the bug

Can you add custom 500 error pages

**Comment by danielroe** [comment]
Let's follow in https://github.com/nuxt/framework/discussions/559
