### ISSUE TITLE
abortNavigation("message") crashes server when triggered on inital page load

### ISSUE THREAD

**Issue by oysandvik94** [nuxt/framework#3242]
### Environment

------------------------------

    Operating System: Linux
    Node Version: v16.13.2
    Nuxt Version: 3.0.0-27415326.3c563fa
    Package Manager: yarn@1.22.17
    Bundler: Vite
    User Config: publicRuntimeConfig, buildModules, build, vite
    Runtime Modules: -
    Build Modules: @pinia/nuxt@0.1.8

------------------------------

### Reproduction

Router middleware that looks like this:

```
export default defineNuxtRouteMiddleware((to, from) => {
    if (to.path === "/test") {
        return abortNavigation("My error message");
    }

    return;
});
```

When I navigate to /test the server crashes. 

Error is on serverside. 

`if (process.client && to.path === "/test") {` will not throw error, but navigation will still occur. 

### Describe the bug

When abortNavigation() is triggered on page load in route middleware it crashes the server. 

Production mode:

> 
>   [Vue Router warn]: uncaught error during route navigation:
> 
>   ERROR [worker] My error message
> 
>   at Module.abortNavigation (.nuxt/dist/server/server.mjs:3262:40)
>   at middleware (.nuxt/dist/server/server.mjs:8215:40)
>   at Module.callWithNuxt (.nuxt/dist/server/server.mjs:520:20)
>   at .nuxt/dist/server/server.mjs:2077:50
>   at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
>   ERROR [proxy] socket hang up 15:13:31
> 
>   at connResetException (node:internal/errors:691:14)
>   at Socket.socketOnEnd (node:_http_client:471:23)
>   at Socket.emit (node:events:402:35)
>   at Socket.emit (node:domain:475:12)
>   at endReadableNT (node:internal/streams/readable:1343:12)
>   at processTicksAndRejections (node:internal/process/task_queues:83:21)

Non-dev:

> 
>   Error: My error message
>   at abortNavigation (file:////frontend/.output/server/chunks/app/server.mjs:3474:40)
>   at middleware (file:////frontend/.output/server/chunks/app/server.mjs:5793:14)
>   at callWithNuxt (file:////frontend/.output/server/chunks/app/server.mjs:341:21)
>   at file:////frontend/.output/server/chunks/app/server.mjs:6286:28
>   at processTicksAndRejections (node:internal/process/task_queues:96:5)
>   My error message
>   at abortNavigation (file://./.output/server/chunks/app/server.mjs:3474:40)
>   at middleware (file://./.output/server/chunks/app/server.mjs:5793:14)
>   at callWithNuxt (file://./.output/server/chunks/app/server.mjs:341:21)
>   at file://./.output/server/chunks/app/server.mjs:6286:28
>   at processTicksAndRejections (node:internal/process/task_queues:96:5)
>   node:internal/process/promises:246
>   triggerUncaughtException(err, true /* fromPromise */);
>   ^
> 
>   Error: My error message
>   at abortNavigation (file:////frontend/.output/server/chunks/app/server.mjs:3474:40)
>   at middleware (file:////frontend/.output/server/chunks/app/server.mjs:5793:14)
>   at callWithNuxt (file:////frontend/.output/server/chunks/app/server.mjs:341:21)
>   at file:////frontend/.output/server/chunks/app/server.mjs:6286:28
>   at processTicksAndRejections (node:internal/process/task_queues:96:5)
>   error Command failed with exit code 1.

**Comment by danielroe** [comment]
What do you mean by "crashes server"? I see that we're logging the error, but you should still be returning a response and the server should still be working.

**Comment by oysandvik94** [comment]
I'm not very experienced with node/JS so this might be a personal error, but when I'm running the server with `node .output/server/index.mjs`and abortNavigation("error") is triggered the server exits with "exit code 1". If I'm hosting it in a docker container then the container exits. If I'm running the server via `yarn dev` or `nuxi dev` then I get this "Pipe closed" error and I have to restart the `yarn dev` command to get stuff running again. 

Same thing happens if I were to try and access something that is `undefined`, for example calling toString() on undefined.

**Comment by danielroe** [comment]
Would you check whether the server still exits when errors are called? This should no longer be occuring with the latest nitro, e.g. https://stackblitz.com/edit/github-x98sql.

**Comment by antfu** [comment]
Reproduction here https://stackblitz.com/edit/github-eblmj9?file=middleware%2Findex.global.ts from #4418
