### ISSUE TITLE
useMeta and Dynamic Meta no longer working starting with:  3.0.0-27415318.ef69e74

### ISSUE THREAD

**Issue by i07** [nuxt/framework#3256]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-27415318.ef69e74`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `ssr`, `publicRuntimeConfig`, `css`, `vite`, `buildModules`, `intlify`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.1.10`
------------------------------

### Reproduction

set devDependencies to `"nuxt3": "latest"` or `"nuxt3":"3.0.0-27415318.ef69e74"` start application all meta related entries in the application no longer have any effect. setting `"nuxt3":"3.0.0-27414150.3589a2d"` in package.json restores the functionality.

eg.
```
<script setup>
useMeta({
  title: 'My Website'
})
</script>
```
does not set the Title to 'My Website'

### Describe the bug

As described in the reproduction. No errors are shown, it is just not parsing any of the meta.
The dynamic meta also stops working `<Html>` `<Head>` `<Link>` `<Style>` etc.

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by i07** [comment]
@danielroe thank you for asking me to reproduce it on a new project ;-) .. on a blank project it's working just fine, I would need some more time to figure out why it is a problem on an existing nuxt3 project. Can we park this, or do I raise this later when I can actually reproduce it correctly.

**Comment by danielroe** [comment]
Might be worth running `npx nuxi@latest upgrade` and, if that fails to resolve the issue, `npx nuxi@latest upgrade --force`.

I'm happy for this to be left open until you have a reproduction.

**Comment by i07** [comment]
@danielroe sadly the instructions you provided didn't change a thing. To actually produce a reproduction was a bit much to write in this issue, so I have created two git repositories, that will show how meta is not being processed and in what use-case, I believe that it will demonstrate this the most clear.

https://github.com/i07/nuxt-issue-1 <-- using "latest" and meta not processed
https://github.com/i07/nuxt-issue-2 <-- using "3.0.0-27414150.3589a2d" (last version where the meta is working fine)

I hope this clears it up a bit. Thanks

**Comment by danielroe** [comment]
This is Nuxt 2 behaviour and isn't related to Bridge.

See [example codesandbox](https://codesandbox.io/s/nuxt-bridge-load-all-css-files-forked-65wy0k?file=/pages/about.vue).

The difference between your sandboxes is that the one that isn't working is a nested route. In that case, in Nuxt 2, we pick the layout of the parent page, not the child page.

**Comment by i07** [comment]
can confirm this also fixes it for my project, thanks for fixing this so quickly ❤️
