### ISSUE TITLE
`useFetch` type return

### ISSUE THREAD

**Issue by ewilan-riviere** [nuxt/framework#3263]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27415326.3c563fa`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

I use *Visual Studio Code* with *Volar*

### Reproduction

In `app.vue`, I fetch data with `useFetch()`

```vue
<script setup lang="ts">
interface Book {
  title: string
  authors: string[]
  serie?: string
}

const { data } = await useFetch<Book>('/books?per-page=32', {
  baseURL: 'https://bookshelves.ink/api',
  lazy: true,
})
console.log(data.value)
</script>
```

[CodeSandbox](https://codesandbox.io/s/nice-torvalds-zyrqb5) is available.

### Describe the bug

When I want to add type to `useFetch()`, I've an error

> Type 'Book' does not satisfy the constraint 'string'.

```vue
<script setup lang="ts">
const { data } = await useFetch<Book>('/books?per-page=32', {
  baseURL: 'https://bookshelves.ink/api',
  lazy: true,
})
</script>
```

It works with `useAsyncData()`

### Additional context

![image](https://user-images.githubusercontent.com/48261459/154294646-1dc5f5ab-302d-40f9-890a-e4972aac5858.png)

**Comment by danielroe** [comment]
You can update it like this:
```diff
  script setup lang="ts">
- const { data } = await useFetch<Book>('/books?per-page=32', {
+ const { data } = await useFetch<string, Book>('/books?per-page=32', {
    baseURL: 'https://bookshelves.ink/api',
    lazy: true,
  })
</script>
```

**Comment by ewilan-riviere** [comment]
Oh thanks, it works perfectly!

Do I close this issue?

**Comment by danielroe** [comment]
let's leave it open as a documentation issue

**Comment by pi0** [comment]
It would be nice if we could reorder generics. Typing URL does not makes much sense for end-users and makes usage different than `$fetch`

**Comment by danielroe** [comment]
I don't think it was possible, because the inferred return type _depends_ on the URL.
