### ISSUE TITLE
layout not working

### ISSUE THREAD

**Issue by yaquawa** [nuxt/framework#3265]
### Environment

nuxt/bridge

### Reproduction

This won't use the `myLayout` layout. 

```vue
<template>
   <div>hello</div>
</template>

<script>
export default {
  layout: "myLayout",
}
</script>
```

But the old way seems to work

```vue
<template>
   <div>hello</div>
</template>

<script>
import Vue from 'vue'

export default Vue.extend({
  layout: 'myLayout',
})
</script>
```

`myLayout.vue`
```vue
<div>
  <h1>Hi</h1>
  <nuxt />
</div>
```
### Describe the bug

x

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by yaquawa** [comment]
@danielroe 
Here you go.
You can confirm that the layout "auth" won't be used.

https://codesandbox.io/s/nuxt-bridge-load-all-css-files-forked-i1h3nm?file=/pages/about/index.vue

**Comment by danielroe** [comment]
This is Nuxt 2 behaviour and isn't related to Bridge.

See [example codesandbox](https://codesandbox.io/s/nuxt-bridge-load-all-css-files-forked-65wy0k?file=/pages/about.vue).

The difference between your sandboxes is that the one that isn't working is a nested route. In that case, in Nuxt 2, we pick the layout of the parent page, not the child page.

**Comment by josempineiro** [comment]
Same here! I updated today my dependencies (only nuxt)

reproduction:
https://codesandbox.io/s/layout-not-working-38bcsw?file=/pages/stuff.vue

**Comment by danielroe** [comment]
@josempineiro See https://github.com/nuxt/framework/discussions/2883 and specifically https://github.com/nuxt/framework/pull/3011.

**Comment by josempineiro** [comment]
Sorry @danielroe, my bad! Thx!

**Comment by yaquawa** [comment]
@danielroe Do you mean if in Nuxt 3, it's possible to select a specific layout to be used?

**Comment by danielroe** [comment]
Yes.
