### ISSUE TITLE
Meta tags not being updated. ie: updateDom() is only called on initial render

### ISSUE THREAD

**Issue by Diizzayy** [nuxt/framework#3267]
### Environment

Nuxt project info:                                                                                                      16:43:16

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27415326.3c563fa`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Create two pages `index.vue` and `b.vue`, within each page call `useMeta` to set a page title. Notice that on initial render, the page title is correctly set to the title set by `useMeta` in `index.vue`, however though, after navigating to `/b` you'll notice that the meta tags haven't updated (title from previous page is still being show).

### Describe the bug

Meta tags are only being applied on the initial render when `updateDOM` is called, hence subsequent changes to meta tags are no longer being applied.

This bug was introduced by changes made in #3212.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/3256
