### ISSUE TITLE
Cannot use composable in composable

### ISSUE THREAD

**Issue by brogier** [nuxt/framework#3270]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27408580.aece351`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `privateRuntimeConfig`, `vite`, `build`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

See description

### Describe the bug

Hi! I'm having trouble using composables in composables.

I have the following code which seems to fail.

Given error is: `nuxt instance unavailable`

```ts
// app.vue
const { authenticate } = useAuth()
authenticate()
```

```ts
// composables/useAuth.ts
export default () => {
  const user = useState('users', () => null)

  const getUser = async () => {
    const { data, error } = await useApiFetch(`/api/me`)

    if (data.value) {
      user.value = data.value
    }
  }

  const authenticate = async () => {
    // Getting new refresh token from cookie
    // Some other login

    await getUser()
  }

  return {
    user,
    authenticate
  }
}
```

and 

```ts
// composables/useApiFetch.ts
const useApiFetch = async (url: string, options) => {
  console.log('this is printed to console')
  let { BASE_URL } = useRuntimeConfig(); // this fails
}

export default useApiFetch
```

Anyone any idea why this is?

Kind regards,

Rogier

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/issues/1852#issuecomment-966161569.
