### ISSUE TITLE
navigateTo: router is undefined in a client context

### ISSUE THREAD

**Issue by Teranode** [nuxt/framework#3272]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27417251.289d54e`
- Package Manager:  `npm@8.4.1`
- Bundler:          `Vite`
- User Config:      `srcDir`, `css`, `buildModules`, `googleFonts`, `axios`, `auth`, `publicRuntimeConfig`, `vite`, `build`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.2.5`, `@nuxtjs/auth@file:project/modules/@nuxtjs/auth`, `@nuxtjs/axios@file:project/modules/@nuxtjs/axios`, `@nuxtjs/pinia@file:project/modules/@nuxtjs/pinia`, `@nuxtjs/google-fonts@file:project/modules/@nuxtjs/google-fonts`

### Reproduction

a codesanbox link has been provided, just click the button and open your devtools.
https://codesandbox.io/s/hardcore-pateu-z5jcif

### Describe the bug

_**navigateTo function**_

https://github.com/nuxt/framework/blob/77aeaa3288f90bdeb1d34c373e9a3a05a8b31970/packages/nuxt3/src/pages/runtime/composables.ts#L74

`window.$nuxt.router` is supposed to be `window.$nuxt.config.globalProperties.$router` this will then allow redirection in a client context.

**_redirection with layouts_**

Regardless of this however, if you try to redirect when a page uses a different layout, regardless of this fix there is an error with layouts, so this function can only be used when all pages utilize the same layout. I've also tested this with the router composable and that same error occurs in regards to layouts.  So that's just an entirely different issue altogether.

### Additional context

I suppose this also has to do with this: https://github.com/nuxt/framework/issues/1750

**Comment by danielroe** [comment]
@Teranode Thank you for this - and good spot! Any chance of creating another issue (with repro) about the layout error you mention?
