### ISSUE TITLE
Netlify builder preset lacks ttl parameter

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/framework#3285]
### Environment

Any

### Reproduction

No need

### Describe the bug

`netlify_builder` preset lacks a way to handle the [ttl](https://docs.netlify.com/configure-builds/on-demand-builders/#time-to-live-ttl) response parameter.

### Additional context
In a bridge environment, I've tried to manipulate the config like so:
```js
    entry: resolve(__dirname, 'nitro/entries/builder.js'),
    preset: 'netlify_builder',
```
```js
// builder.js
import { builder } from '@netlify/functions'
// @ts-ignore
import { handler as _handler } from '@nuxt/nitro/dist/runtime/entries/lambda.js'

// console.log('here')

// console.log(_handler)

const ttlHandler = async function (...args) {
  const handlerResponse = await _handler.apply(this, args)
  return {
    ...handlerResponse,
    ttl: 120,
  }
}

export const handler = builder(ttlHandler)
```
But `yarn build` froze after writing server bundle.

**Comment by Rigo-m** [comment]
@danielroe any advice on how to implement it before the issue gets tackled?

**Comment by danielroe** [comment]
Let's track directly in https://github.com/unjs/nitro/issues/93.
