### ISSUE TITLE
Cannot use Tailwindcss classes from composables

### ISSUE THREAD

**Issue by Der-Alex** [nuxt/framework#3298]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.16.0`
- Nuxt Version:     `3.0.0-27418474.8adff2e`
- Package Manager:  `npm@6.14.11`
- Bundler:          `Vite`
- User Config:      `buildModules`, `tailwindcss`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.0-2`

### Reproduction

- Clone repo from `https://github.com/Der-Alex/nuxt3-tailwind-composables-bug` ( this repo contains nuxt3 and nuxt3 tailwind module 5.0.0-2)
- `npm i` and `npm run dev` 
- after the app started you will see a button without colors. The expected behaviour is, that styles passed through via prop `type-style="primary"` create a blue background and light grey text for the button.

### Describe the bug

Short description: 

When using a composable that returns tailwind css classes, the corresponding styles dont get rendered / the css isnt created, as long as these classes only occur inside the composable. When writing the css classes e.g. inside a comment everything works.

Long description:

I'm not sure if this is a bug with nuxt3 or tailwind. I tested that with installing tailwind manually and with the new tailwind module 5.0.0-2. Both have the same behaviour in a nuxt 3 environment.

My goal was to create a composable `useButtonTypeStyles`, that returns tailwind css classes, when I set a specific prop for my button component. I wanted to use a composable because I have different button types like default button, toggle buttons, dropdown buttons etc, that use the same logic.

So in the `pages/index.vue` you find my `button-base` with the prop `type-style="primary"`. `primary` is a tailwind css class configured inside tailwind.config.js. It is also defined inside the `composables/buttonTypeStyles.js` as a switch case that gets returned.

As you can see in the dev-tools, the css classes get rendered inside the html tag but the styles arent available. It seems like tailwind doesn't create css for these styles when they are coming from a composable.

I also tried to create a button and directly write these css classes onto it. Then the corresponding styles are created. It also works if you write the css class as a comment inside the template part. Then tailwind styles are created.
But they don't get created when using composables.

I hope it is understandable what I mean :)

**Comment by Atinux** [comment]
I think you need to add `./composables/**/*.{ts,js}` in your `tailwind.config.js`

**Comment by Der-Alex** [comment]
Oh dear... when you work too much and cannot see the forest for the trees....
Thank you. I'll close this 😅
