### ISSUE TITLE
Cache ci build artifacts

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#3310]
Currently, each CI job runs `yarn build` on monorepo to generate non-stubbed `dist` artifacts but it takes `~1.:30` which is only needed once! We might cache it in a prepared job and restore `packages/*/dist` on the next steps.

**Comment by clarkdo** [comment]
Sure, I can have a look

**Comment by clarkdo** [comment]
@pi0 Let me know when the pending issue is resolved.

**Comment by pi0** [comment]
@clarkdo I think we can implement prepare cache to use for `lint`, `test-types` and `build-release` jobs. Only `test-fixture-*` steps temporarily need stub.

**Comment by clarkdo** [comment]
Cool, I’ll work on it this weekend

**Comment by clarkdo** [comment]
@pi0 PR: https://github.com/nuxt/framework/pull/3335
