### ISSUE TITLE
Components are not rendered when using <component is="someComponent"/>

### ISSUE THREAD

**Issue by fmcdigital** [nuxt/framework#3320]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-27404037.29171bd`
- Package Manager:  `npm@8.0.0`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `css`, `vite`, `dir`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```
<script lang="ts">
export default defineComponent({
props:{
    button: ''
}
});

</script>

<template>
   <component :is="`btn-${button}`"></component>
</template>
```

### Describe the bug

The component inside the dir `btn/Edit` is not rendered.

The code is rendered as the following

```
<btn-edit></btn-edit>
```

**Comment by Rigo-m** [comment]
Take a look at this https://github.com/nuxt/framework/pull/3305

**Comment by danielroe** [comment]
... and check out https://github.com/nuxt/framework/discussions/2883 for a one-line migration. Sorry for the inconvenience 🙏
