### ISSUE TITLE
 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')

### ISSUE THREAD

**Issue by Jackliu007888** [nuxt/framework#3336]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.17.6`
- Nuxt Version:     `3.0.0-27420403.16e2a54`
- Package Manager:  `npm@6.14.15`
- Bundler:          `Vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

runtime-core.esm-bundler.js:1085 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')

https://stackblitz.com/edit/github-sqcc5j?file=app.vue

### Describe the bug

the demo  is in https://stackblitz.com/edit/github-sqcc5j?file=app.vue

click the second option, error appeared.

### Additional context

"ant-design-vue": "^3.0.0-beta.9" , nuxt3: v3.0.0-27418641.56aabd6

**Comment by danielroe** [comment]
What makes you think this is a Nuxt issue, rather than a bug with `ant-design-vue`?

**Comment by YvesChen** [comment]
> 是什么让您认为这是 Nuxt 问题，而不是`ant-design-vue`?

It's the problem of Ant Design Vue in vue3. It has nothing to do with nuxt
