### ISSUE TITLE
HMR broken when using ClientOnly component

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt/framework#3340]
### Environment

See reproduction...

### Reproduction

StackBlitz:
https://stackblitz.com/edit/client-only-ssr-bug?file=pages%2Findex.vue

### Describe the bug

I can only partially reproduce this bug. 

If you look at the StackBlitz and open `pages/index.vue`, there is a `<ClientOnly>` component with a paragraph and a custom component inside. If you change the text in the paragraph that says CHANGE THIS TEXT (or anything inside the `<ClientOnly>` component) to trigger an HMR update the custom component disappears and it will be gone until you reload the page. 

The reproduction doesn't  show any errors or warnings but in my project I get such warnings:

<img width="836" alt="Screen Shot 2022-02-20 at 19 47 11" src="https://user-images.githubusercontent.com/2703233/154861331-e0682047-c831-4660-b1e9-0eac36aa9ee2.png">

That's what I mean with "I can only reproduce partially".

Some background why I have this setup:

I use `Pinia` together with the `pinia-plugin-persistedstate` plugin, which leads to hydration mismatch errors if I do not wrap components that render data from locally persisted state in the `<ClientOnly>` component. This makes sense bc the server doesn't have the data from localstorage available.

**Comment by toniengelhardt** [comment]
**Update:**

If I import the components explicitly like so:

```ts
import ClientOnly from '#app/components/client-only.mjs'
import AppSomeComponent from '~/components/app/SomeComponent.vue'
```

the problem goes away.

It seems like the ClientOnly component and all components inside it get excluded from the auto-import for some reason...

**Comment by toniengelhardt** [comment]
**Update:**

With the above fix, changing HTML works, but changing css (or in my case scss with windi) still creates hydration errors.

**Comment by everatch** [comment]
I have got a similar issue when i use a third-party component (naive-ui) by using vite plugin `unplugin-vue-components`

Pattern A makes all components resolved failed with HMR
```ts
// Pattern A
components: true,
vite: {
  plugins: [
    Components({
      resolvers: [NaiveUiResolver()],
    }),
  ],
},
```

Pattern B makes naive-ui components works, but my components(in components directory) resolved failed with HMR
```ts
// Pattern B
components: false,
vite: {
  plugins: [
    Components({
      dirs: ['components'],
      directoryAsNamespace: true,
      resolvers: [NaiveUiResolver()],
    }),
  ],
},
```

**Comment by danielroe** [comment]
cc: @antfu

**Comment by SkyaTura** [comment]
I'm still experiencing the exact same issue related here and in #3849 .

There is any required change os configuration to do in order to fix it after the last updates?

**Comment by danielroe** [comment]
@SkyaTura Would you open a new issue with a reproduction? 🙏

**Comment by SkyaTura** [comment]
@danielroe just figured it was related to the fact I'm using vite-plugin-vue-type-imports to use imported types on `defineProps`. Sorry for bothering, and thank you for the lightning fast response.

_(I must been too much time awake for not noticing that a vite plugin that take over imports could be related with import problemas 🙈 )_

Removing the plugin worked like a charm.

I still don't know how to use imported types on props, tho...

**Comment by sangemi** [comment]
Same error. I use ant design vue, and
````
        "ant-design-vue": "latest",
        "unplugin-vue-components": "^0.22.9"
````

````
vite: {
        // for ant design vue auto-importing 
        plugins: [
            Components({ 
                resolvers: [AntDesignVueResolver({resolveIcons: true, importStyle: 'css'})],
            }),
        ],
        ssr: {
            noExternal: ['moment', 'compute-scroll-into-view', 'ant-design-vue','@ant-design/icons-vue'],
        },
    },
````
