### ISSUE TITLE
lodash/pick cannot be found in production build

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt/framework#3343]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27420403.16e2a54`

### Reproduction

https://codesandbox.io/s/billowing-mountain-r79cng

* Download the minimal reproduction as a zip archive.
* Run: `yarn && yarn build && yarn start`
* Open http://localhost:3000

### Describe the bug

Importing `lodash/pick` (as suggested at https://github.com/nuxt/framework/issues/2178#issuecomment-1004774184) leads to runtime crash in production build:

```
Cannot find module '.../.output/server/node_modules/lodash/pick' imported from .../.output/server/chunks/app/server.mjs
Did you mean to import lodash/pick.js?
```

### Additional context

Named imports such as `import { pick } from "lodash"` are also badly broken. Ideally, I would expect them to work, same as they work in babel/webpack.

I understand that lodash is not managing its modules well, they should be compiled as mjs files. However, lodash is way too popular, it is used broadly by nuxt packages as well, so I believe it deserves some attention. The underlying problem is not specific to lodash, some other packages suffer from it as well, so some generic solution/workaround would be helpful.

### Logs

```shell
$ node .output/server/index.mjs
Listening on http://localhost:3000/
Cannot find module '/Users/semenov/Downloads/r79cng/.output/server/node_modules/lodash/pick' imported from /Users/semenov/Downloads/r79cng/.output/server/chunks/app/server.mjs
Did you mean to import lodash/pick.js?
  at new NodeError (node:internal/errors:371:5)
  at finalizeResolution (node:internal/modules/esm/resolve:416:11)
  at moduleResolve (node:internal/modules/esm/resolve:932:10)
  at defaultResolve (node:internal/modules/esm/resolve:1044:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by danielroe** [comment]
Have you tried `import pick from 'lodash/pick.js'`?

**Comment by IlyaSemenov** [comment]
Yes, and it works, but it looks ugly in the code.

**Comment by danielroe** [comment]
Unfortunately, that's just a requirement of native ESM (see [node docs](https://nodejs.org/api/esm.html#esm_mandatory_file_extensions)). The solution for 'prettier code' is likely for lodash to provide a package export map.

We may, however, be able to do something to improve the DX (for example, automatically fixing code like this).

**Comment by IlyaSemenov** [comment]
I believe a documented recipe for something like `vite-plugin-import` would suffice (and also help to work around `import { pick } from "lodash"` problem), but I didn't manage to find a decent properly configurable vite/rollup plugin for doing that.

**Comment by danielroe** [comment]
This is no longer reproducible in the latest nuxt/nitropack.
