### ISSUE TITLE
Creating a unique id is impossible in Nuxt 3

### ISSUE THREAD

**Issue by jshimkoski** [nuxt/framework#3346]
### Environment

```
sandbox@sse-sandbox-u1udu3:/sandbox$ npx nuxi info
Nuxt CLI v3.0.0-27424151.dbab979
RootDir: /sandbox
Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27424151.dbab979`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

sandbox@sse-sandbox-u1udu3:/sandbox$
```

### Reproduction

[Reproduction URL](https://codesandbox.io/s/romantic-shockley-u1udu3?file=/components/ExampleComponent.vue)

If you don't see the issue at first, try refreshing the preview.

### Describe the bug

When attempting to create a unique identifier in a component (using Options API, Composition API, or setup sugar), The id changes between the server and the client.

This makes it impossible for components that require access to a unique HTML id (for accessibility reasons or other) and causes hydration issues.

**Comment by jshimkoski** [comment]
How would a component library author handle this when `useAysncData` is unavailable to them?

For example, if their Vue 3 components are developed using Vite.

When Nuxt 3 pulls in the third-party components, they break.

This didn't happen in Nuxt 2.

**Comment by danielroe** [comment]
> This didn't happen in Nuxt 2.

This also throws an error in Nuxt 2: https://codesandbox.io/s/async-cookies-ur28r1?file=/pages/index.vue.

I'm closing this as it's not an error but a consequence of client-side hydration, but I'd recommend you create a discussion with some more information on what you're trying to do, what your key needs are, and we can think about how to achieve that. (For example, why do you need unique IDs?)

**Note**: You may find [this section of the Vue docs](https://vuejs.org/guide/scaling-up/ssr.html#writing-ssr-friendly-code) helpful in answering some of your questions.

**Comment by jshimkoski** [comment]
Thank you. I'll start up a discussion thread.

Regarding the "why do you need unique IDs" question:

Unique IDs are a pretty big part of accessibility or being able to reference different parts of the DOM for libraries such as `popperjs`.

One small example related to accessibility is [`aria-labelby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby):

```
<template>
  <span role="checkbox" aria-checked="false" tabindex="0" aria-labelledby="tac"></span>
  <span id="tac">I agree to the Terms and Conditions.</span>
</template>
```

If you have multiple instances of a component with that code, it breaks the HTML since an `id` must always be unique.

This issue doesn't stop there and it's a pretty common necessity (just do a simple google search to see what I mean).

I wish component instance IDs were baked into Vue 3. It would solve all of this.

Thanks again.
