### ISSUE TITLE
add option to remove components pathprefix

### ISSUE THREAD

**Issue by kahiii** [nuxt/framework#3349]
### Environment

all

### Reproduction

instead of :
components/Buttons /Download.vue   
and call "ButtonsDownload"

i just want to call my component with "Download" like in nuxt 2 with this config :
  components: [{ path: '~/components', pathPrefix: false }],

### Describe the bug

  components: [{ path: '~/components', pathPrefix: false }],

**Comment by danielroe** [comment]
This is a recent regression. [**Reproduction**](https://stackblitz.com/edit/github-r1d18x?file=components%2Ftest%2FMyComponent.vue&terminal=dev).
