### ISSUE TITLE
composables autoimport not updating after change

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#3353]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.5.0`
- Nuxt Version:     `3.0.0-27424151.dbab979`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `css`, `app`, `components`, `router`, `nitro`, `srcDir`, `build`, `buildModules`, `modern`, `tailwindcss`, `meta`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.0-4`, `@vueuse/nuxt@7.6.2`
------------------------------

### Reproduction

no need

### Describe the bug

I'll tell you step by step:
1) create `@/composables/useSomeObject.ts`
```js
export const useSomeObject = () => {
    return {
        name: 'John',
        age: '27'
    }
}
```

2) We use it somewhere, for example in `@/pages/index.vue`
3) After that, we change the fields in `@/composables/useSomeObject.ts`, for example:
```js
export const useSomeObject = () => {
    return {
        fullname: 'John', // old filed is 'name'
        age: '27'
    }
}
```
4) All works but.... now typescript throws an error => Property 'fullname' does not exist on type ...

### Additional context

-

### Logs

```shell
-
```

**Comment by danielroe** [comment]
That sounds like a typescript glitch in your IDE. TS hasn't detected the change in the file; there's nothing Nuxt can do about it. Does it persist after you restart your IDE?

**Comment by mihail727** [comment]
> That sounds like a typescript glitch in your IDE. TS hasn't detected the change in the file; there's nothing Nuxt can do about it. Does it persist after you restart your IDE?

hm..... sorry probably my bad.... yesterday I restarted vscode and it did not help... today all works fine... restarting the computer may have helped.
