### ISSUE TITLE
@nuxtjs/dotenv works with "nuxi dev" but not with "nuxi build && nuxi start"

### ISSUE THREAD

**Issue by HendrikJan** [nuxt/framework#3355]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.12.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `buildModules`, `bridge`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/dotenv@1.4.1`, `@nuxt/bridge@3.0.0-27424151.dbab979`
------------------------------

### Reproduction

https://codesandbox.io/s/nuxt-bridge-dotenv-r1054o?file=/package.json

1. click on "restart server"
2. wait for `nuxi build` and `nuxi start` to finish
3. look in the Sandbox terminal to see the console.log output of "process.env"
4. see that "MY_VARIABLE" is not in process.env
(the expected situation is that "MY_VARIABLE" is set to "My DotEnv Variable")

To see that in "dev" mode it does work, use these steps:
5. replace "dev": "nuxi build && nuxi start" with "dev": "nuxi dev"
6. restart the server
7. see that 

### Describe the bug

I am using a `.env` file in my root folder.
I am using `@nuxtjs/dotenv` to load the contents into `process.env`

* When using "nuxi dev" the contents of `.env` is loaded into `process.env`
* THE BUG: When using "nuxi build" and "nuxi start", the contents of `.env` is not loaded into `process.env`

It seems like Nuxt does read the .env-file because if I change the config to
```
['@nuxtjs/dotenv', { filename: `.env.wrongfilename` }],
```
I do get an error which I don't get with
```
['@nuxtjs/dotenv', { filename: `.env` }],
```

### Additional context

Nuxt.config.js:
```javascript
import { defineNuxtConfig } from "@nuxt/bridge";
import dotenv from "dotenv";
dotenv.config();

export default defineNuxtConfig({
  buildModules: ["@nuxtjs/dotenv"]
});
```

`/server/middleware/www.mjs`:
```javascript
import express from 'express'; // Minimalist web framework
var app = express();

console.log("ENVIRONMENT: ", process.env);

export default app;
```

**Comment by danielroe** [comment]
With Nuxt Bridge and Nuxt 3, there is no such thing as a runtime module - or even a runtime Nuxt at all. Instead, you should use `publicRuntimeConfig` to define and access runtime environment variables.
