### ISSUE TITLE
#app index.d.ts not present at it was in previous versions

### ISSUE THREAD

**Issue by ThomasBerne** [nuxt/framework#3361]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `head`, `bridge`, `css`, `plugins`, `components`, `buildModules`, `modules`, `typescript`, `build`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/markdownit@2.0.0`, `@nuxtjs/i18n@7.2.0`, `@nuxtjs/svg-sprite@0.5.2`, `@nuxtjs/dotenv@1.4.1`, `@nuxtjs/gtm@2.4.0`
- Build Modules:    `@nuxtjs/vuetify@1.12.3`, `@pinia/nuxt@0.1.8`, `@nuxt/bridge@3.0.0-27424151.dbab979`
------------------------------

### Reproduction

No reproduction needed.

### Describe the bug

I'm using nuxt and nuxt bridge and it seems I have a problem with latests updates of @nuxt/bridge-edge. The #app isn't typed anymore in my application. The only thing that change is that the file that the #app points on is now index.d.mts and not index.d.ts. And the link of #app doesn't precise the extension of the file so typescript doesn't succeed to interpolate the index.d.mts.

#app not well defined because of index.d.mts not being handled by typescript.

**Comment by hinaloe** [comment]
It looks since around https://github.com/nuxt/framework/commit/68a227af037cc7c91b00787cadbd2653676e00ad, right?
