### ISSUE TITLE
Proxies are currently only working Dev but not in Build

### ISSUE THREAD

**Issue by lperez22** [nuxt/framework#3362]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.0.0-27389502.88da719`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `alias`, `nitro`, `build`, `css`, `modules`, `proxy`, `vite`, `vue`, `hooks`, `components`, `privateRuntimeConfig`, `publicRuntimeConfig`
- Runtime Modules:  `@nuxtjs/proxy@2.1.0`
- Build Modules:    `-`
------------------------------
```

### Reproduction

Here you can see a sample proxy working when the dev command is run but not working after a build and start
https://stackblitz.com/edit/nuxt-starter-g2m6nk

### Describe the bug

I have a few proxies setup that did work in Nuxt 2 with the @nuxtjs/proxy module. But now I am doing this with Vite and it does work in dev. But when I build or deploy to a test site none of my proxies work at all and I get a 404 page. I went ahead and installed the @nuxtjs/proxy module in my Nuxt 3 project and I get the same results in dev and build.

**Comment by danielroe** [comment]
`@nuxtjs/proxy` is not yet compatible with Nitro. You can raise an issue there if one doesn't yet exist.

**Comment by lperez22** [comment]
Oh I'm sorry I meant to say that I also tried the proxy module, but I am using the Vite configuration within the nuxt.config.ts file like this
```
  vite: {
    server: {
      proxy: {
        '/test': {
          target: 'http://192.168.1.104:3000/api/hello',
          ws: true,
        },
      },
    },
  },
```

**Comment by danielroe** [comment]
Ah yes - I'm afraid the same reasoning applies. If you want a proxy, you can create a file in `~/server/middleware/proxy.ts` and add a handler there.

**Comment by lperez22** [comment]
Thank you so much for this suggestion making a file in server/middleware does work for me

**Comment by msonowal** [comment]
@danielroe  @lperez22 

Could you please provide an example to proxy the api calls using that approach as I also wanted to try that approach before axios or proxy module is ready.

Thanks

**Comment by danielroe** [comment]
Here's someone's code: https://github.com/nuxt/framework/discussions/1223#discussioncomment-1960448
