### ISSUE TITLE
Throw "Hydration node mismatch" error when using teleport

### ISSUE THREAD

**Issue by msidolphin** [nuxt/framework#3385]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-27428764.271289c`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Vite`
- User Config:      `meta`, `css`, `build`, `buildModules`, `components`, `vite`, `vueuse`, `windicss`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@nuxtjs/svg@0.4.0`, `@vueuse/nuxt@7.6.2`, `nuxt-windicss@2.2.6`, `unplugin-icons/nuxt`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-dyh5gp?file=app.vue

### Describe the bug

here is mini reproduction
```vue
<template>
  <teleport to="body" disabled>
      <div v-show="visible">Hydration node mismatch</div>
  </teleport>
</template>

<script lang="ts" setup>
import { defineProps } from 'vue'
defineProps({
    visible: {
        type: Boolean,
        default: false,
    }
})
</script>
```

```vue
<template>
  <teleport-example :visible="state.visible"></teleport-example>
  <button @click="state.visible = !state.visible">toggle1</button>
</template>

<script lang="ts" setup>
import TeleportExample from './comp.vue'
const state = reactive({
  visible: false,
});
</script>

```

<img width="864" alt="image" src="https://user-images.githubusercontent.com/26672484/155649509-79151e9f-3026-4e8b-ba0b-8a7b1585e80f.png">

our users have given us feedback on this issue [6233](https://github.com/element-plus/element-plus/issues/6233)

### Logs

```shell
[Vue warn]: Hydration node mismatch:
- Client vnode: button 
- Server rendered DOM: <div style=​"display:​none;​">​Hydration node mismatch​</div>​  
  at <Examples> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <App> 
  at <NuxtRoot>
```

**Comment by danielroe** [comment]
Let's follow in #1907
