### ISSUE TITLE
page does not finish loading after abortNavigation

### ISSUE THREAD

**Issue by bwp618** [nuxt/framework#3387]
### Environment

Nuxt CLI v3.0.0-27424151.dbab979                                                                                                                                                                            14:04:24
RootDir: /Users/byeongwookpark/marvel/thor                                                                                                                                                                  14:04:25
Nuxt project info:                                                                                                                                                                                          14:04:25

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27424151.dbab979`
- Package Manager:  `npm@8.5.1`
- Bundler:          `Vite`
- User Config:      `srcDir`, `rootDir`, `buildDir`, `typescript`, `meta`, `css`, `build`, `modules`, `publicRuntimeConfig`, `serverMiddleware`, `router`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.4`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                                                            14:04:25

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

// in middleware/permission.global.ts
```js
export default defineNuxtRouteMiddleware((to, from) => {
  const [autheState] = useAuthentication()
  const user = autheState.value?.user
  //console.log(to)
  if(to.path.startsWith('/admin') && !user?.authorities?.includes(AuthorityRole.ADMIN)) {
    return abortNavigation()
    //return navigateTo({ path: '/404' })
  }
  if (to.meta?.role && !user?.authorities?.includes(to.meta.role)) {
    //console.log('no permission',autheState.value, to.meta?.role,roles)
    return abortNavigation()
    //return navigateTo({ path: '/404' })
  }
})
```
### Describe the bug

It continues to show as in progress, and the page does not finish loading.

### Additional context

// in users page uses "useFetch"

### Logs

```shell
ERROR  [worker] Route navigation aborted: /admin/users                                                                                                                                                     13:55:04

  at Module.createError (node_modules/h3/dist/index.mjs:516:15)
  at .frontend/dist/server/server.mjs:2083:57
  at processTicksAndRejections (node:internal/process/task_queues:96:5)


 ERROR  [proxy] connect ENOENT /var/folders/83/d5djxdb96n1d2xrs6m7_6q3r0000gn/T/nitro/worker-62887-1.sock                                                                                                   13:55:14

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
```

**Comment by danielroe** [comment]
Would you provide a reproduction please? 🙏

**Comment by uyamazak** [comment]
@danielroe 
Hello, I had the same error and have created a repository to reproduce it.
It seems that even if it do not use abortNavigation in middleware, just returning false will cause the same situation.

https://github.com/uyamazak/nuxt3-abort-navigation-error

**Environment**
- Operating System: macOS Monterey
- Node Version: v17.2.0
- Nuxt Version: 3.0.0-27444434.856c01a

1.  git clone and yarn install
2. yarn dev
3. open http://localhost:3000/test-test -> OK
4. open http://localhost:3000/test-abort -> get below error and hang up server
5. open http://localhost:3000/test-false -> get same error

```
 ERROR  [worker] testVal is abort                                                                                                                                       10:09:25

  at Module.abortNavigation (.nuxt/dist/server/server.mjs:947:40)
  at .nuxt/dist/server/server.mjs:2311:34
  at Module.callWithNuxt (.nuxt/dist/server/server.mjs:251:20)
  at .nuxt/dist/server/server.mjs:1902:50
  at processTicksAndRejections (node:internal/process/task_queues:96:5)


 ERROR  [proxy] connect ENOENT /var/folders/7m/248nqxxn3kz0b19d71m752g80000gn/T/nitro/worker-11307-1.sock                                                               10:09:26

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)


 ERROR  [proxy] connect ENOENT /var/folders/7m/248nqxxn3kz0b19d71m752g80000gn/T/nitro/worker-11307-1.sock                                                               10:09:27

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)


 ERROR  [proxy] connect ENOENT /var/folders/7m/248nqxxn3kz0b19d71m752g80000gn/T/nitro/worker-11307-1.sock                                                               10:10:21

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
```

**Comment by danielroe** [comment]
This is no longer replicable - the server hang seems fixed upstream 👍
