### ISSUE TITLE
Auto import of components broken

### ISSUE THREAD

**Issue by jiblett1000** [nuxt/framework#3393]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27429889.e45a780`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jiblett1000/test

### Describe the bug

With the latest update on npm as of this writing, auto importing of components seems to be completely broken. I've linked a reproduction with a fresh nuxt3 install with a single component in the components directory. Running yarn dev results in this error:

``
[Vue warn]: Failed to resolve component: Test
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
``

**Comment by ennioVisco** [comment]
Oh, so it's not only me. Can someone revert to some versions where this works? It seems it is a dependency problem.

**Comment by danielroe** [comment]
This isn't a dependency issue - it's resolved by #339, and you can work around for the moment by configuring `components: { global: true }`. Make sure to revert that change after that PR is merged.

**Comment by ennioVisco** [comment]
> This isn't a dependency issue - it's resolved by #339, and you can work around for the moment by configuring `components: { global: true }`. Make sure to revert that change after that PR is merged.

I think you are mentioning the wrong PR

**Comment by danielroe** [comment]
Sorry - https://github.com/nuxt/framework/pull/3396.

**Comment by scipiotech** [comment]
Glad to see its not only me.

**Comment by Baiyuetribe** [comment]
Everything was fine before the nuxt3 dependency was updated, so it seems to be a problem with the latest version

**Comment by hamidooChe** [comment]
> > > This isn't a dependency issue - it's resolved by #3396, and you can work around for the moment by configuring `components: { global: true }`. Make sure to revert that change after that PR is merged.
> > 
> > 
> > I tried adding this to my nuxt config however it does not seem to work for me. 😟
> 
> You temporarily need to roll back to an older version `yarn add -D nuxt3@3.0.0-27428764.271289c`

or you can temporarily just add those lines in your nuxt.config it should work

```
  components: {
    global: true,
    dirs: ['~/components']
  }
```

**Comment by Jos-de-Boss** [comment]
> or you can temporarily just add those lines in your nuxt.config it should work
> 
> ```
>   components: {
>     global: true,
>     dirs: ['~/components']
>   }
> ```

Thanks! Adding the `dirs` option seems to do the trick. 👍

**Comment by vinyll** [comment]
Same here, lost a couple of hours reading the doc over again convinced that it was me misusing the lib…
[@hamidooChe's config tip](https://github.com/nuxt/framework/issues/3393#issuecomment-1052405158) did the trick ✅

**Comment by smorcuend** [comment]
This issue makes me crazy few days ago. I'm using [primevue](https://github.com/primefaces/primevue) plugin and latest changes breaks the components registration on the application.

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27470343.19842ce`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `meta`, `css`, `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

* primevue: "3.12.2"


Browser console throws:
```
runtime-core.esm-bundler.js:38 [Vue warn]: Property "$primevue" was accessed during render but is not defined on instance. 
  at <Default > 
  at <AsyncComponentWrapper > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="layout" mode="out-in" > 
  at <Anonymous> 
  at <App key=1 > 
  at <NuxtRoot>
warn2 @ runtime-core.esm-bundler.js:38
runtime-core.esm-bundler.js:38 [Vue warn]: Failed to resolve component: Button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <AppTopbar onMenuToggle=fn<bound onMenuToggle> > 
  at <Default > 
  at <AsyncComponentWrapper > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="layout" mode="out-in" > 
  at <Anonymous> 
  at <App key=1 > 
  at <NuxtRoot>
```

PrimeVue plugin for Nuxt3:

```
import { defineNuxtPlugin } from "#app";
import PrimeVue from "primevue/config";
import Button from "primevue/button";

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(PrimeVue, {ripple: true});
    nuxtApp.vueApp.component('Button', Button);
    //other components that you need
});
``` 
On nuxt.config.ts
```
 // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    transpile: [
      'primevue'
    ],
  },
```

**Comment by the94air** [comment]
@smorcuend you might want to make a new issue since this one is closed!

**Comment by smorcuend** [comment]
Problem solved!  I deleted the node_modules directory, package-lock.json and the npm cache and reinstalling the npm packages the problem went away.

**Comment by ColinRosati** [comment]
> Problem solved! I deleted the node_modules directory, package-lock.json and the npm cache and reinstalling the npm packages the problem went away.

@smorcuend  this work for me, thanks!
