### ISSUE TITLE
[Documentation needed] Fetching data with Nuxt Bridge

### ISSUE THREAD

**Issue by Kagigz** [nuxt/framework#3401]
After reading carefully through the documentation, I do not understand how to fetch data from an API with Nuxt Bridge.

I understand only "useLazyFetch" is available, but I see no examples of how to actually use it in a component.

The only thing I see is this ([here](https://v3.nuxtjs.org/getting-started/bridge-composition-api/#useasync-and-usefetch)):

```
<script setup>
- import { useFetch } from '@nuxtjs/composition-api'
- const posts = ref([])
- const { fetch } = useFetch(() => { posts.value = await $fetch('/api/posts') })
+ const { data: posts, refresh } = useLazyAsyncData('posts', () => $fetch('/api/posts'))
+ // or, more simply!
+ const { data: posts, refresh } = useLazyFetch('/api/posts')
  function updatePosts() {
-   return fetch()
+   return refresh()
  }
</script>
```

What is updatePosts here? How to use posts in the component template? 
Could someone please help, and maybe we could add a more detailed example to the docs?

Thank you

**Comment by danielroe** [comment]
How's this?
```html
<template>
  <div v-if="posts">
    <div v-for="post in posts"><!-- do something -->
  </div>
</template>

<script setup>
const { data: posts, refresh } = useLazyFetch('/api/posts')
onMounted(() => {
  // refresh list of posts every 5 seconds - don't do this!
  setInterval(refresh, 5000)
})
</script>

**Comment by Kagigz** [comment]
@danielroe thank you, 2 questions:
- I see that you're only using "/api/posts" => How can we configure the BASE_URL ? I usually use axios and you can create the axios client with your config but with fetch it's not clear 
- You're providing an example with something that we shouldn't do - since you can't await with useLazyFetch, I think it would be good to show an example with the best practice

**Comment by danielroe** [comment]
@Kagigz I only mean you shouldn't fetch data with setInterval, but I wanted to show you what `refresh` would do. Just remove that call, and the example is good.

You can set baseURL in the fetch options - check out the documentation: https://v3.nuxtjs.org/docs/usage/data-fetching/#usefetch.
