### ISSUE TITLE
Question: number of files limitation

### ISSUE THREAD

**Issue by soongsta** [nuxt/framework#3408]
### Environment

- Nuxt Version:     `3.0.0-27430570.4cfad4d`
- Package Manager:  `npm@8.4.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/soongsta/nuxt3-maxed-out

1. Git clone project
2. Run "node createimages.js" from the command line
3. Run "npm run dev" from the command line

Notes:

- createimages.js will create 100,000 test images
- Run from command line, dont use VSCode. It will cause VSCode to hang due to the number of images

### Describe the bug

npm run dev just hangs after "Vite warmed up in 53455ms" message

### Additional context

We are testing a NUXT3 project (previously written in Nuxt 2.15.8)
It's a blog with currently 34000 images
We were wanting to know if NUXT3 was capable of handling that many images
All the images previously were stored in static/uploads folder
We tested the NUXT3 project with all images in the public/images folder
It failed with the following error.

<--- Last few GCs --->

[10336:000001F5EA639E70]   202208 ms: Mark-sweep (reduce) 4071.2 (4142.7) -> 4071.0 (4143.5) MB, 4500.6 / 0.3 ms  (average mu = 0.164, current mu = 0.003) allocation failure scavenge might not succeed
[10336:000001F5EA639E70]   206748 ms: Mark-sweep (reduce) 4072.0 (4143.5) -> 4072.0 (4144.5) MB, 4539.1 / 0.3 ms  (average mu = 0.086, current mu = 0.000) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF76031401F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
 2: 00007FF7602A3146 DSA_meth_get_flags+65542
 3: 00007FF7602A3FFD node::OnFatalError+301
 4: 00007FF760BD5ADE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF760BC000D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF760A635FC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
elegate::SetupHeap+494417
elegate::SetupHeap+494417
12: 000001F5ECC11AC7

We created a simple project https://github.com/soongsta/nuxt3-maxed-out
It has 1 app.vue file and the project does not display any images
But the project has 100,000 images
when we run "npm run dev" it hangs
We can only assume its trying to read or load all the images
Is there a reason why NUXT3 is doing this and NUXT2 is not?

Kind regards

**Comment by danielroe** [comment]
Yes, Nitro creates a static file handler - including pre-calculating etags, mime-types, etc. - for optimal deployment to services like Cloudflare, and fast response times. Obviously in production a CDN (or something like nginx) is always likely to be the better option, and I'm sure that's what you'll be planning on doing.

However, I think there's an opportunity to improve things. For example, we can probably reduce the pre-calculation step in development (other than collecting the filenames).

**Comment by Megarsh** [comment]
> Yes, Nitro creates a static file handler - including pre-calculating etags, mime-types, etc. - for optimal deployment to services like Cloudflare, and fast response times. Obviously in production a CDN (or something like nginx) is always likely to be the better option, and I'm sure that's what you'll be planning on doing.
> 
> However, I think there's an opportunity to improve things. For example, we can probably reduce the pre-calculation step in development (other than collecting the filenames).

Can you also think about adding some kind of a nuxt.config option that will disable the processing/copying of the public folder.

I have a blog/news website project deployed on my server and all the images are served via nginx which makes the processing of public folder obsolete. Also in the future when the project goes live and the public folder grows there're definitely going to be problems with the duplication of all the images.

Right now I've decided to use a different folder outside of nuxts scope (static for example) which works fine on the server and local `npm run dev` environment, however when testing locally the image links break when I run `npm run build` and `npm run start` which makes the development and testing awkward.

Would like to hear your thoughts about this, maybe the public folder wasn't designed to contain thousands of files or there's already a way around this issue. Thanks in advance.

**Comment by soongsta** [comment]
Happy days, look like they are working on it with #3432

**Comment by danielroe** [comment]
This issue is no longer reproducible for me.
