### ISSUE TITLE
npx nuxi init nuxt3-app  and download template error

### ISSUE THREAD

**Issue by Alexander-yang-hub** [nuxt/framework#3430]
npx nuxi init nuxt3-app
Nuxt CLI v3.0.0-27434337.d6102de 

ERROR  could not download https://github.com/nuxt/starter/archive/4c952d210cf85df8211ecb14994e46e5e1175d8a.tar.gz

nodejs version
v16.14.0

**Comment by danielroe** [comment]
I can't reproduce this - could it be aan issue on your machine/firewall/VPN?

**Comment by gavrilrebrov** [comment]
I have some problem

I can download through the browser, but it doesn’t work through npx

**Comment by danielroe** [comment]
I think this is likely a problem with your environment. Can you run `npx degit 'nuxt/starter#v3' nuxt3-app`?

**Comment by gavrilrebrov** [comment]
![image](https://user-images.githubusercontent.com/12533726/158578442-5aa93387-6718-402a-928f-5df3d70442a3.png)

**Comment by danielroe** [comment]
I think that's a pretty good indication that it's your environment. Possibly a firewall? You could raise an issue on https://github.com/tiged/tiged, which is what we use. And you should probably confirm you're using the latest nuxi by running `npx nuxi@latest nuxt3-app` first.

**Comment by tsaqib** [comment]
```
Nuxt CLI v3.0.0-rc.3                                                                                                                     

 ERROR  could not download https://github.com/nuxt/starter/archive/a322f481ff248ff5673b0ca23c5e7a421d46fc9b.tar.gz                        

  at Degit._cloneWithTar (/Users/x/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:10204:10)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Degit.clone (/Users/x/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:9999:4)
  at async Object.invoke (/Users/x/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:10566:7)
  at async _main (/Users/x/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/cli.mjs:46:20)
```

**Comment by raind33** [comment]
> npx degit 'nuxt/starter#v3' nuxt3-app

i have met the same problem. You resolved?

**Comment by Aruelius** [comment]
try this:

npm install -g nuxi

then change file:

C:\Users\{username}\AppData\Roaming\npm\node_modules\nuxi\dist\chunks\init.mjs

change the proxy address at 9991 lines:

this.proxy = 'http://127.0.0.1:10800';

then use:

nuxi init your-app-name

**Comment by Charuru** [comment]
Same problem, can't find this either:

change the proxy address at 9991 lines:

this.proxy = 'http://127.0.0.1:10800';
