### ISSUE TITLE
The request url * is outside of Vite serving allow list

### ISSUE THREAD

**Issue by ririen** [nuxt/framework#3433]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.6.0`
- Nuxt Version:     `3.0.0-27434337.d6102de`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `modules`, `buildModules`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.4`
- Build Modules:    `@unocss/nuxt@0.26.4`, `@nuxtjs/strapi@1.3.0`
------------------------------

### Reproduction

 Use in template:
 
 ```vue
  <img class="h-8" src="@/assets/logo.svg" />
  ```

### Describe the bug

```sh
ERROR  The request url "/home/ririen/projects/test/assets/logo.svg" is outside of Vite serving allow list. 
```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by ririen** [comment]
@danielroe  look here: https://codesandbox.io/s/thirsty-hill-3opepn

**Comment by danielroe** [comment]
Thanks. Looks like this is an issue with the strapi module.
