### ISSUE TITLE
Rollup error: Could not load * client.manifest.mjs

### ISSUE THREAD

**Issue by ririen** [nuxt/framework#3435]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.6.0`
- Nuxt Version:     `3.0.0-27434337.d6102de`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `modules`, `buildModules`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.4`
- Build Modules:    `@unocss/nuxt@0.26.4`, `@nuxtjs/strapi@1.3.0`
------------------------------

### Reproduction

Build:

```sh
yarn build
```

### Describe the bug

```sh
start Building server...                                                                                                                                                             16:54:

 ERROR  Rollup error: Could not load /home/ririen/projects/test/.nuxt/dist/server/client.manifest.mjs (imported by node_modules/@nuxt/nitro/dist/runtime/app/render.mjs): ENOENT: no such file or directory, open '/home/ririen/projects/test/.nuxt/dist/server/client.manifest.mjs'

 ERROR  Could not load /home/ririen/projects/test/.nuxt/dist/server/client.manifest.mjs (imported by node_modules/@nuxt/nitro/dist/runtime/app/render.mjs): ENOENT: no such file or directory, open '/home/ririen/projects/test.nuxt/dist/server/client.manifest.mjs'
 ```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by ririen** [comment]
@danielroe here: https://codesandbox.io/s/thirsty-hill-3opepn
