### ISSUE TITLE
restore context with ast transformer for middleware & plugins

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#3438]
We could support a AST transformer to restore context similar to `script setup` and use for `defineNuxtRouteMiddleware`, `defineNuxtPlugin`, `async setup() {}`, etc making it possible to use navigate utils in async contexts.

(as a simpler solution, we could move `navigateTo` and `abortNavigation` to `nuxtApp` instance? `useNuxtApp()` can be cached before any await operation)

_Originally posted by @pi0 in https://github.com/nuxt/framework/issues/3105#issuecomment-1031788002_

**Comment by pi0** [comment]
Linked issue: https://github.com/unjs/unctx/issues/2

**Comment by 4KDA** [comment]
Any news?

**Comment by antfu** [comment]
On my plan for next week :)
