### ISSUE TITLE
Nested `_nuxt` folder with vite in Bridge

### ISSUE THREAD

**Issue by manniL** [nuxt/framework#3441]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `bridge`, `nitro`, `target`, `components`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27445576.02e683d`

### Reproduction

1. **Clone [the repo](https://github.com/manniL/nuxt-bridge-3441)** *or*
* 1. Create a Nuxt 2 application
* 2. Migrate to Nuxt bridge according to the docs
* 3. Ensure that you have static site generation enabled
* 4. Use the image as src (`<img src="@/assets/bridge.8c6fab54.svg" alt="broken during deployment">`
2. Run `yarn build` (or `yarn nuxi generate`)
3. Check the `.output` folder
4. Deploy the content if you like (e.g. `npx http-server .ouput/public`) and see that the alt text is visible

### Describe the bug

The structure of the output folder has a twice nested _nuxt folder:
* `.output/public/_nuxt/_nuxt/bridge.8c6fab54.svg`
* `.output/public/_nuxt/_nuxt/AppFooter.ba4c1b1d.js`

This isn't an issue per se as the JS chunks are resolved correctly. The actual problem is that images (and likely other static assets) are being looked up in `_nuxt/` and not `_nuxt/_nuxt`

Expected: `_nuxt/bridge.8c6fab54.svg`
Actual: `_nuxt/_nuxt/bridge.8c6fab54.svg`

### Additional context

![grafik](https://user-images.githubusercontent.com/640208/156036544-96fdcef0-f834-4cac-bcb0-48d45a856cf8.png)

A possible workaround for now is manually rewriting the paths and duplicating the `/_nuxt` part. 🤔 

Might be related: https://github.com/nuxt/framework/blob/16e2a54528dfee54becdc3f8e41b37ec92364312/packages/vite/src/server.ts#L101

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by manniL** [comment]
> Would you provide a reproduction? 🙏

Repo linked 👍

**Comment by danielroe** [comment]
Thanks! A workaround for now is to disable `vite` in bridge mode.

**Comment by manniL** [comment]
Still reproducible. Updated the linked repo.

```
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `bridge`, `nitro`, `target`, `components`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27445576.02e683d`
------------------------------
```

**Comment by manniL** [comment]
Can confirm this is fixed now but now we have another issue with CSS file URLs 😄 
Will create a dedicated issue for that

**Comment by danielroe** [comment]
rats! that's another easy fix as we already have a solution for nuxt3 + vite.
