### ISSUE TITLE
Dynamic components with component is

### ISSUE THREAD

**Issue by Blemming** [nuxt/framework#3442]
### Environment

```
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27434419.754ff0c`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `typescript`, `buildModules`, `css`, `intlify`
- Runtime Modules:  `-`
- Build Modules:    `@intlify/nuxt3@0.1.10`, `nuxt-windicss@2.2.7`, `@vueuse/nuxt@7.7.0`
------------------------------
```

### Reproduction

[Codesandbox](https://codesandbox.io/s/winter-pine-0jde0b)

### Describe the bug

Trying to render a dynamic component with the `<component :is="componentName"></component>` is not working. It works perfectly fine in a basic example see [here](https://stackblitz.com/edit/nuxt3-windicss-myone7)

But somewhere along the way it stops working. Maybe an interaction with the i18n module ? 
Can anyone enlighten me if I am doing something wrong?

**Comment by danielroe** [comment]
Check out https://github.com/nuxt/framework/discussions/2883 - you'll need to set `components.global` to true to enable this kind of usage.

**Comment by Blemming** [comment]
Setting the `components.global` to true seems to do the opposite, it no longer recognizes any of my components, the only globally imported components are the `nuxtwelcome` and `clientonly` ( according to the `.nuxt/types/components.d.ts` ) where as they where being imported globally just fine before ... any pointers ?
