### ISSUE TITLE
16.nuxt.config.md could not be found

### ISSUE THREAD

**Issue by xiao-e-yun** [nuxt/framework#3451]
### Environment

In docs

### Reproduction

https://github.com/nuxt/framework/tree/main/docs/content/3.docs/2.directory-structure/

### Describe the bug

16.nuxt.config.md not in [framework/docs/content/3.docs/2.directory-structure/](https://github.com/nuxt/framework/tree/main/docs/content/3.docs/2.directory-structure/) .  

And https://v3.nuxtjs.org/docs/directory-structure/nuxt.config#alias of example.  
`import { resolve } from 'pathe'` << `pathe => path`

**Comment by danielroe** [comment]
It is generated in the build process. https://github.com/nuxt/framework/blob/dccc0c9c6faa86533ef4bcfb0117232ec631f65a/docs/scripts/gen-docs.ts#L6-L11

If you are looking to edit the docs, you can do so within `packages/schema/src/config`

But note that `pathe` is not a typo: see https://github.com/unjs/pathe.

**Comment by xiao-e-yun** [comment]
`pathe` and `path` are used in the two examples respectively, should the same imports be maintained?

**Comment by danielroe** [comment]
Yes - we should use `pathe` in both places 👍

**Comment by xiao-e-yun** [comment]
`import path from 'path'` in example of [hooks](https://v3.nuxtjs.org/docs/directory-structure/nuxt.config#hooks)
