### ISSUE TITLE
nuxt generate fails with vite and assets folder

### ISSUE THREAD

**Issue by Scratchy144** [nuxt/framework#3453]
### Environment

RootDir: /sandbox                                                                     03:49:34
Nuxt project info:                                                                    03:49:34

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- User Config:      `ssr`, `target`, `components`, `buildModules`, `modules`, `bridge`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27434755.39f7eb2`
------------------------------

### Reproduction

https://codesandbox.io/s/sharp-brook-yfpx1m?file=/pages/index.vue

### Describe the bug

I am trying to use an svg for an image as described [here](https://nuxtjs.org/docs/directory-structure/assets/).

The development server shows the svg fine, however running **nuxt generate** returns
```
Error: Could not load /sandbox/assets/svg.svg (imported by                  │
   │   pages/index.vue?vue&type=template&lang.js): The "fileName" or "name"        │
   │   properties of emitted files must be strings that are neither absolute nor   │
   │   relative paths, received "/svg.4e2f3e7c.svg".  
```

### Additional context

Relevant nuxt config:
```ssr: false,
target: 'static',
bridge: {
    nitro: false,
    vite: true,
  }
```

**Comment by danielroe** [comment]
This is no longer reproducible for me. Let me know if you're still experiencing it and I'll reopen.
