### ISSUE TITLE
`@nuxt/test-utils`: Using tests utils requires installing playwright

### ISSUE THREAD

**Issue by farnabaz** [nuxt/framework#3470]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-27436017.7b6252a`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-dvdfm1?file=test%2Fbasic.test.ts

### Describe the bug

When using Nuxt test utils to load and start a fixtures, it requires install playwright as dependencies. This happens even when I explicitly  disable `browser` option in `setup` function

```ts
await setup({
    rootDir: fileURLToPath(new URL('./fixtures/basic', import.meta.url)),
    server: true,
    browser: false,
  });
```

Installing `playwright` as dependency or commenting `import('playwright')` from package source will solve the issue and I get green success in test result.

### Logs

```shell
❯ test/basic.test.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/basic.test.ts [ test/basic.test.ts ]
Error: Failed to resolve import "playwright" from "node_modules/@nuxt/test-utils/dist/index.mjs". Does the file exist?
 ❯ formatError node_modules/vite/dist/node/chunks/dep-9c153816.js:38098:46
 ❯ TransformContext.error node_modules/vite/dist/node/chunks/dep-9c153816.js:38094:19
 ❯ normalizeUrl node_modules/vite/dist/node/chunks/dep-9c153816.js:69819:26
 ❯ async TransformContext.transform node_modules/vite/dist/node/chunks/dep-9c153816.js:69959:57
 ❯ async Object.transform node_modules/vite/dist/node/chunks/dep-9c153816.js:38334:30
 ❯ async doTransform node_modules/vite/dist/node/chunks/dep-9c153816.js:53030:29

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed (1)
     Tests  no tests
      Time  2.17s (in thread 0ms, Infinity%)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```
```

**Comment by danielroe** [comment]
This seems to be an upstream bug, as even though `createBrowser` is never being called, I think it's still looking to resolve the dynamic import.

See https://github.com/vitest-dev/vitest/issues/326 and https://github.com/vitejs/vite/issues/7010.

cc: @antfu

**Comment by antfu** [comment]
Yes, it's a bug of Vite and we are working on it

**Comment by pi0** [comment]
Can we do a workaround on Nuxt side to make it unpredictable? Something like `await import('play' + 'wright')`

**Comment by antfu** [comment]
> Can we do a workaround on Nuxt side to make it unpredictable? Something like `await import('play' + 'wright')`

Yes I think so
