### ISSUE TITLE
Nitropack: integration does not provide `$fetch` in client

### ISSUE THREAD

**Issue by farnabaz** [nuxt/framework#3475]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-27436017.7b6252a`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `experimentNitropack`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/node-af71an?file=app.vue

Try running `yarn dev` and `yarn dev:legacy`

### Describe the bug

In legacy mode nitro injects a plugin (AKA `nitro.client.mjs`) to provide `$fetch` in client side, but in nitropack migration this is broken.
https://github.com/nuxt/framework/blob/main/packages/nuxt3/src/core/nitro-legacy.ts#L48-L50

**Comment by farnabaz** [comment]
Should we create another similar plugin in `nuxt3/src/core` to add back `$fetch` or it should place in `nuxt3/src/app/entry.ts` ?

**Comment by pi0** [comment]
Thanks for the issue @farnabaz. More thinking, probably adding back Nitropack's client entry in order to support new features like functions API in the future.
