### ISSUE TITLE
Can't use tsx in .vue file

### ISSUE THREAD

**Issue by xiao-e-yun** [nuxt/framework#3477]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27436017.7b6252a`
- Package Manager:  `pnpm@6.32.2`
- Bundler:          `Vite`
- User Config:      `typescript`, `app`, `vite`, `css`, `router`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

index.vue
```
<template lang="pug">

</template>

<script lang="tsx" setup>
defineComponent({
  render(){
    return <div></div>
  }
})
</script>
```

package.json
```
{
  "private": true,
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "full-install": "pnpm i --shamefully-hoist",
    "lint": "eslint . --fix"
  },
  "pre-commit": [
    "lint"
  ],
  "dependencies": {
    "tslib": "^2.3.1"
  },
  "devDependencies": {
    "@types/formidable": "^2.0.4",
    "@types/mime-types": "^2.1.1",
    "@typescript-eslint/eslint-plugin": "^5.13.0",
    "@typescript-eslint/parser": "^5.13.0",
    "cross-env": "^7.0.3",
    "eslint": "^8.10.0",
    "eslint-plugin-vue": "^8.5.0",
    "file-type": "^17.1.1",
    "formidable": "^2.0.1",
    "mime-types": "^2.1.34",
    "mysql2": "^2.3.3",
    "nuxt3": "latest",
    "postcss": "^8.4.7",
    "pre-commit": "^1.2.2",
    "pug": "^3.0.2",
    "rollup": "^2.69.0",
    "sass": "^1.49.9",
    "typescript": "^4.6.2",
    "vanilla-lazyload": "^17.6.1"
  }
}
```

### Describe the bug

Can't use tsx in .vue file
I have used npm and pnpm but neither works
I recreate new project it is work

### Additional context

nuxt.config.ts
```
import { defineNuxtConfig } from "nuxt3"
// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  typescript:{
    shim:false,
  },
	vite: {
		css: {
			modules: {
				scopeBehaviour: "local",
				generateScopedName: "[local]-[hash:base64:5]"
			},
			preprocessorOptions: {
				scss: {
					additionalData: "@use \"@/assets/scss/color\";@import \"@/assets/scss/vars.scss\";",
				},
			},
		},
	},
	css: [
		"@/assets/scss/page.scss"
	],
	router: {
		mode:"history",
	},
})
```

tsconfig.json
```
{
  "compilerOptions": {
    "forceConsistentCasingInFileNames":true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "importHelpers": true,
    "strict": true,
  },
  // https://v3.nuxtjs.org/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}
```

.eslintrc.json
```
{
    "env": {
        "browser": true,
        "es2021": true,
        "node": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:vue/essential",
        "plugin:@typescript-eslint/recommended"
    ],
    "parserOptions": {
        "ecmaVersion": 13,
        "parser": "@typescript-eslint/parser",
        "sourceType": "module"
    },
    "plugins": [
        "vue",
        "@typescript-eslint"
    ],
    "rules": {
        "react/jsx-filename-extension":[0],
        "no-mixed-spaces-and-tabs":0,
        "indent": [
            "error",
            "tab"
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "double"
        ],
        "semi": [
            "error",
            "never"
        ]
    }
}
```

[pnpm-lock.yaml](https://cdn.discordapp.com/attachments/679190719226970136/948634661352009799/pnpm-lock.yaml)

### Logs

```shell
ERROR  上午1:21:47 [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: D:/work_space/serve/pages/index.vue?vue&type=script&setup=true&lang.tsx&macro=true
  14 |  defineComponent({
  15 |    render(){
  16 |      return <div></div>
     |                        ^
  17 |    }
  18 |  })
      at formatError (D:\work_space\serve\node_modules\.pnpm\vite@2.8.6_sass@1.49.9\node_modules\vite\dist\node\chunks\dep-9c153816.js:38098:46)
      at TransformContext.error (D:\work_space\serve\node_modules\.pnpm\vite@2.8.6_sass@1.49.9\node_modules\vite\dist\node\chunks\dep-9c153816.js:38094:19)
      at TransformContext.transform (D:\work_space\serve\node_modules\.pnpm\vite@2.8.6_sass@1.49.9\node_modules\vite\dist\node\chunks\dep-9c153816.js:69775:22)
      at async Object.transform (D:\work_space\serve\node_modules\.pnpm\vite@2.8.6_sass@1.49.9\node_modules\vite\dist\node\chunks\dep-9c153816.js:38334:30)
      at async doTransform (D:\work_space\serve\node_modules\.pnpm\vite@2.8.6_sass@1.49.9\node_modules\vite\dist\node\chunks\dep-9c153816.js:53030:29)
```

**Comment by danielroe** [comment]
There are a few issues with your code. Try this instead: https://stackblitz.com/edit/github-sbambk?file=app.vue&terminal=dev.

**Comment by xiao-e-yun** [comment]
I have to change all pages files from ts to tsx?
```
WARN  [SSR] Error transforming /pages/tkvs/index.vue?vue&type=script&lang.tsx&macro=true: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

  at formatError (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38098:46)
  at TransformContext.error (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38094:19)
  at TransformContext.transform (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:69779:22)
  at async Object.transform (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38334:30)
  at async doTransform (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:53030:29)
```

**Comment by danielroe** [comment]
I'm not really sure what you're asking. No, you don't need to change non-tsx files to tsx.

**Comment by xiao-e-yun** [comment]
If I use tsx in .vue file
do I need change all .vue file
from `<script lang="ts">` to `<script lang="tsx">` ?

**Comment by danielroe** [comment]
No.

**Comment by danielroe** [comment]
Make sure you upgrade your dependencies. There was a vite bug, recently fixed, with using tsx within `~/pages~

**Comment by xiao-e-yun** [comment]
> Make sure you upgrade your dependencies. There was a vite bug, recently fixed, with using tsx within `~/pages` ([vitejs/vite#7118](https://github.com/vitejs/vite/issues/7118)).

I try but not work...

**Comment by danielroe** [comment]
Then would you provide a reproduction?

**Comment by xiao-e-yun** [comment]
Sure,but tomorrow, now is 3am.

**Comment by xiao-e-yun** [comment]
Dependencies are all upgraded
`"nuxt3": "^3.0.0-27437402.494f85a"`

> Make sure you upgrade your dependencies. There was a vite bug, recently fixed, with using tsx within `~/pages` ([vitejs/vite#7118](https://github.com/vitejs/vite/issues/7118)).

Has this issue been fixed?

**Comment by danielroe** [comment]
ah, it only seems to have fixed `~/pages/index.tsx`, but not `index.vue` with tsx. Would you create an issue on https://github.com/vitejs/vite 🙏

**Comment by xiao-e-yun** [comment]
Isn't this limited to Nuxt's ~/pages/*.vue ?

**Comment by yunyuyuan** [comment]
It seems that there are only apps Vue can be used. Nuxt version `3.0.0-rc.1`

**Comment by avernusx** [comment]
@danielroe facing the same issue although it seems I have latest nuxt and vite.

```
[plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

/home/avernus/Work/cable/nuxt3/modules/TestModule/page.vue:6:20

4  |      return () => {
5  |        return (
6  |          <div></div>
   |                     ^
7  |        )
8  |      }
```

Repository to reproduce:
https://github.com/avernusx/nuxt3-tsx-bug

Using node 18.2.0 and yarn 1.22.18

**Comment by zch233** [comment]
the same with me

**Comment by zch233** [comment]
> @danielroe facing the same issue although it seems I have latest nuxt and vite.
> 
> ```
> [plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
> 
> /home/avernus/Work/cable/nuxt3/modules/TestModule/page.vue:6:20
> 
> 4  |      return () => {
> 5  |        return (
> 6  |          <div></div>
>    |                     ^
> 7  |        )
> 8  |      }
> ```
> 
> Repository to reproduce: https://github.com/avernusx/nuxt3-tsx-bug
> 
> Using node 18.2.0 and yarn 1.22.18

the same with me

**Comment by danielroe** [comment]
This should be resolved in rc4. If not, would you raise a new issue with a reproduction?

**Comment by zch233** [comment]
> This should be resolved in rc4. If not, would you raise a new issue with a reproduction?

work in https://stackblitz.com/edit/nuxt-starter-mhh1gq?file=pages%2Findex.vue,app.vue

dont work in https://github.com/zch233/nuxt3-tsx-in-vue-bug

in app.vue is ok,but dont work in pages/*.vue

![image](https://user-images.githubusercontent.com/30221824/174252079-d5bde123-60f4-46cc-a182-9cc908c5f7be.png)

**Comment by danielroe** [comment]
Seems to be working fine in latest rc4: https://stackblitz.com/github/zch233/nuxt3-tsx-in-vue-bug

**Comment by zch233** [comment]
im using rc4,

yea,its work online stackblitz

but  has this error in local project uncertainly

**Comment by danielroe** [comment]
Try regenerating your lockfile.
