### ISSUE TITLE
Allow artibarary keys for `NuxtConfig` interface

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#3478]
In case of using a legacy module, disabled module, or for some reason module types not being registered, we shall simply allow any arbitrary key for `nuxt.config`. (src: https://github.com/nuxt/framework/blob/main/packages/schema/src/types/config.ts#L7)

The downside is that we have less strict types so config is more likely to have typos. Maybe we can use a `@deprecated` tag for `[key: string]: any` ?

**Comment by lihbr** [comment]
This would also remove the type error when installing a new module and configuring it for the first time (before types gets generated after running the server/prepare command again)

**Comment by cyruscollier** [comment]
There is a documented way to add customer typed keys to the public or private runtime config: https://v3.nuxtjs.org/docs/usage/runtime-config#typing-runtime-config

Would a similar approach work to augment the entire config type?

**Comment by lihbr** [comment]
> There is a documented way to add custom typed keys to the public or private runtime config: [v3.nuxtjs.org/docs/usage/runtime-config#typing-runtime-config](https://v3.nuxtjs.org/docs/usage/runtime-config#typing-runtime-config)
> 
> Would a similar approach work to augment the entire config type?

afaik it works yeah, you can extend the `NuxtConfig` interface the same way, but I'm not sure that's the path we want to use here 🤔
