### ISSUE TITLE
Nuxt cache API

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#348]
**placeholder** - feel free to edit directly

We could use a Nuxt cache API, for example, with data fetching.

* `asyncData` could register a handler, make a 'get' request.
* Ideally could also support SSE/ws/swr for triggering reactive data update...

**Comment by hermesalvesbr** [comment]
I'm implementing nuxt3 with wordpress rest api. It would be great if there was a way to cache it so it doesn't call the api twice.

How do you make the cache stay on the client? Do you use local.storage?

**Comment by pi0** [comment]
Nitro now provides a caching API https://nitro.unjs.io/guide/cache.html (as well as experimental route caching rules). Let's stabilize it first and see how much more low-level caching we need.

**Comment by pi0** [comment]
> How do you make the cache stay on the client? Do you use local.storage?

@hermesalvesbr Best is to trust HTTP cache headers and browser to to it by itself :)

**Comment by pi0** [comment]
Hi @phroggyy.

Actually, this one was a little bit different than whole-page caching strategies but directly for a low-level cache of `fetch` and `asyncData` calls. Which is a little bit tricky and complex DX. 

Regarding SSR/HTML cache, Once the top-level `routes` option is available, certainly would love to have your help in documenting this ❤️ 

There is a chance that we introduce a shorter option for SSR route caching not pending for the stable nitro `routes` feature and using `h3` utils. Please have an eye on new issues and PRs.
