### ISSUE TITLE
Loading components with style section caused error

### ISSUE THREAD

**Issue by shisoAqron** [nuxt/framework#3483]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27437402.494f85a`
- Package Manager:  `npm@8.3.1`
- Bundler:          `Vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

using config is bulma: https://v3.nuxtjs.org/docs/directory-structure/nuxt.config#css

and using modules(nuxt.config.js) is as follows
```
  "devDependencies": {
    "nuxt3": "latest",
    "sass": "^1.49.9",
    "sass-loader": "^12.6.0"
  },
  "dependencies": {
    "bulma": "^0.9.3"
  }
```

### Reproduction

repository: https://github.com/ManabuMiwa/nuxt3-app-demo/tree/faild_build

`npm run dev` is not problem. `npm run start` (after build) caused problem.

### Describe the bug

![スクリーンショット 2022-03-03 17 18 39](https://user-images.githubusercontent.com/7846773/156524710-1920f3dd-350a-45b7-a1d9-dadd8cc7630b.png)

1. I made a repository according to the [Installation](https://v3.nuxtjs.org/getting-started/installation).
2. Write config of bulma.
3. Create pages directory and index.vue(remove app.vue).
4. Create components directory and .vue file.
5. `npm run start` (after build) caused problem.

I have confirmed the following
- <style> section at /pages/index.vue is ok.
- Loading components is ok.
- <style> section in components file (components/TitleHeader.vue) caused error.

![スクリーンショット 2022-03-03 17 18 58](https://user-images.githubusercontent.com/7846773/156524726-e95e7ad4-7ae7-4ac7-8493-e8ccc00a1cf6.png)
It seems css url is wrong. 
- incorrect: /index.02999dda.css
- correct: **/_nuxt**/index.02999dda.css

![スクリーンショット 2022-03-03 17 20 51](https://user-images.githubusercontent.com/7846773/156524970-00bcd744-71a9-40f0-a6d9-e8f68e9c09a4.png)

Please tell me if it has already been resolved or a bug 🙏 

### Additional context

example of style
```
// in /pages/index.vue
<!-- this style is ok -->
<style>
  .red {
    color: red;
  }
</style>
```
```
//  in components/TitleHeader.vue
<!-- This style is NG -->
<style>
  .title {
    margin-left: 2rem;
    margin-right: 2rem;
  }
</style>
```

### Logs

```shell
build log

~/Documents/nuxt3-app-demo faild_build 22s
❯ npm run build

> build
> nuxi build

Nuxt CLI v3.0.0-27437402.494f85a
ℹ Vite warmed up in 4744ms
ℹ Client built in 5255ms
ℹ Building server...
✔ Server built in 1938ms
ℹ Nitro preset is server
ℹ Cleaning up .output
start Generating public...
✔ Generated public .output/public
start Building server...
start Writing server bundle...
✔ Server built
  ├─ .output/server/index.mjs (285 B) (178 B gzip)
  ├─ .output/server/chunks/nitro/static.mjs (3.34 kB) (1.32 kB gzip)
  ├─ .output/server/chunks/nitro/server.mjs (71.3 kB) (24.4 kB gzip)
  ├─ .output/server/chunks/index.mjs (395 kB) (91 kB gzip)
  ├─ .output/server/chunks/app/vue3.mjs (284 B) (200 B gzip)
  ├─ .output/server/chunks/app/server.mjs (129 kB) (33.1 kB gzip)
  ├─ .output/server/chunks/app/render.mjs (22.4 kB) (6.24 kB gzip)
  └─ .output/server/chunks/app/client.manifest.mjs (562 B) (259 B gzip)
Σ Total size: 967 kB (240 kB gzip)
ℹ You can preview this build using nuxi preview
```

browser console
```
GEThttp://localhost:3000/index.02999dda.css
[HTTP/1.1 404 Page not found: /index.02999dda.css 4ms]

Error: Unable to preload CSS for /index.02999dda.css
    NuxtJS 18
entry-575cf0ad.mjs:5:20661

Error while mounting app: TypeError: e.ssrContext is undefined
    NuxtJS 7
entry-575cf0ad.mjs:5:39767
```
```

**Comment by danielroe** [comment]
This seems to be the same issue: https://github.com/nuxt/framework/issues/3469

**Comment by shisoAqron** [comment]
Thank you @danielroe san 🙏  
I will see  https://github.com/nuxt/framework/issues/3469 and comment.
