### ISSUE TITLE
Nuxt 3 one tier setup breaks after version 3.0.0-27375411.b38e394

### ISSUE THREAD

**Issue by Vincent17201** [nuxt/framework#3492]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27437402.494f85a`
- Package Manager:  `npm@6.14.15`
- Bundler:          `Vite`
- User Config:      `app`, `target`, `ssr`, `vite`, `router`, `meta`, `css`, `components`, `modules`, `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

Relevant nuxt config:

 target: "static",
 ssr: false,

### Reproduction

- Backend Server running and serving nuxt entry html with entry div <div id=”__nuxt”></div> and scripts @port xxxx
- Nuxt 3 running in dev @port yyyy
- Calling backend server route responsible for serving nuxt 3 SPA

### Describe the bug

When nuxt 3 is served through my backend server (django) during development @port 8000 with the following entry html template everything worked fine till nuxt version 3.0.0-27375411.b38e394

```
<!DOCTYPE html>
<html>
<body>
  <div id="__nuxt"></div>
  {% if debug %}
  <script type="module" src="http://localhost:3000/@vite/client"></script>
  <script type="module" src="http://localhost:3000/_nuxt/entry.mjs"></script>
  {% endif %}
</body>
</html>
```

After that this error occured:

entry.mjs:39 Error while mounting app: TypeError: Cannot read properties of undefined (reading 'app')
at router.mjs:20:41
at callWithNuxt (nuxt.mjs:91:20)
at applyPlugin (nuxt.mjs:48:29)
at applyPlugins (nuxt.mjs:57:11)
at async initApp (entry.mjs:28:5)

![nuxt3-useRuntimeConfig](https://user-images.githubusercontent.com/90750980/156632254-4c0b4072-d781-4e7e-98e5-30ad64dcf749.png)

### Additional context

The error only occurs when serving nuxt via the backend server. In comparison to the nuxt 3 standard standalone I noticed that in my case (served through backend server) in the nuxtApp payload Proxy are some things missing - eg. the config Object. But this matter exists before as well as after version 3.0.0-27375411.b38e394.

Every hint to get this setup working again is appreciated.

nuxt standalone `npm run dev:`
![nuxt3-standalone](https://user-images.githubusercontent.com/90750980/156633586-9da78ed5-b14f-466d-9d68-42f9dab1599a.png)

nuxt served through backend server during development:
![nuxt3-served-by-django](https://user-images.githubusercontent.com/90750980/156634095-5c62e5e1-cc87-4775-b113-d6aed9c7e5ba.png)

**Comment by danielroe** [comment]
If you are effectively trying to generate your own SPA template, you should ensure you are also providing a payload:

```diff
  <!DOCTYPE html>
  <html>
  <body>
    <div id="__nuxt"></div>
    {% if debug %}
    <script type="module" src="http://localhost:3000/@vite/client"></script>
    <script type="module" src="http://localhost:3000/_nuxt/entry.mjs"></script>
    {% endif %}
+   <script>window.__NUXT__ = { data: {}, state: {}, _errors: {}, serverRendered: false, config: { app: { baseURL: "\u002F", buildAssetsDir: "\u002F_nuxt\u002F", assetsPath: {}, cdnURL: null } } }</script>
  </body>
  </html>
```

**Comment by Vincent17201** [comment]
This way it is working. Thank you!

Is there a way to get it running with the template provided by nuxt? Did not know it better.

**Comment by danielroe** [comment]
I'm not sure I understand the question.
