### ISSUE TITLE
<component> using v-for silently fails with <script setup>

### ISSUE THREAD

**Issue by levimichael** [nuxt/framework#3505]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-27437402.494f85a`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/levimichael/Nuxt-3-Component-Bug-Reproduction/tree/master

### Describe the bug

Attempting to iterate over an array of component strings silently fails when using `<script setup>`. Using the options API however, works as expected.

**Comment by danielroe** [comment]
Looking at this, I think this is just how Vue 3 behaves. A string only works as an argument to `:is` if it is a registered component.

[Example](https://stackblitz.com/edit/vitejs-vite-fblzcw?file=src%2Fmain.js&terminal=dev)
[Docs](https://vuejs.org/api/built-in-special-elements.html#component)
