### ISSUE TITLE
Implement titleTemplate from vue-meta

### ISSUE THREAD

**Issue by command-tab** [nuxt/framework#3522]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-27386975.6e06d2b`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Attempt to use `titleTemplate` like Nuxt 2 offers, and observe that it is ignored.

### Describe the bug

Following on the issue from https://github.com/nuxt/nuxt.js/issues/10073, it appears that `titleTemplate` from vue-meta is not implemented in Nuxt 3. It is implemented in Nuxt 2.

I make use of `titleTemplate` in all of my Nuxt 2 applications, and I'm curious what the official recommended replacement is for this feature. How can I arrange to have my page titles be something like "PageName - ApplicationName" in Nuxt 3? In Nuxt 2, I would set `titleTemplate` to `%s - ApplicationName` in the default layout, then set `title` in each of my pages' `head` section of the Options API. In Nuxt 3, there doesn't appear to be a way to do this without porting this feature forward from Nuxt 2. Happy to be wrong about this :)

**Comment by jiblett1000** [comment]
This is what you need right here @command-tab.

https://v3.nuxtjs.org/docs/usage/meta-tags/

You can use it either in the script tag or as components. Pretty cool stuff. So you would just set in app.vue or whatever your default layout is and then you can use it per page as well.

**Comment by command-tab** [comment]
If you useMeta in script tags, can pages _add to_ the layout’s title? I see that I can set the page title in each page, but I’m trying to avoid including my app’s name in every page (like titleTemplate elegantly solves).

**Comment by jiblett1000** [comment]
Ok, I did some poking around. I think you're going to need this. The documentation seems a little tucked away (maybe should be referenced in the useMeta docs?).

https://v3.nuxtjs.org/docs/directory-structure/pages#page-metadata

and then maybe something like this in default route...

```
const route = useRoute();

useMeta({
  title: `Main Title - ${route.meta.title}`,
});
```

Sorry, don't have routing set up in my current project but I'm guessing something like this should accomplish what you're looking for.

**Comment by command-tab** [comment]
Cool, thanks — I’ll give this a whirl in a Nuxt 3 test app tomorrow 👍🏻

**Comment by danielroe** [comment]
That's exqactly how I'd do it. A PR to the docs with an example would be very welcome if you're able 😊

**Comment by jiblett1000** [comment]
@danielroe  Will Do :)

**Comment by command-tab** [comment]
@danielroe Progress! This works well for initial SSR, but it does not seem to update upon client-side route changes. I'm doing this in `layouts/default.vue`:

```html
<script setup>
const route = useRoute()
useMeta({
  title: `AppName - ${route.meta.title}`
})
</script>
```

And then each page has some variant of:

```html
<script setup>
definePageMeta({
  title: 'Home'
})
</script>
```

Whatever page gets SSR'ed, its `<title>` tag is set correctly. But If I follow `nuxt-link`s and navigate to other pages, the title tag does not update (unless of course I do a full reload and thus re-SSR). Here's a repro: https://stackblitz.com/edit/github-3afwwg-nzu4uc?file=layouts/default.vue (`npm install && npm run dev`)

I wasn't sure if the `title` set in the `definePageMeta` object param needed to be reactive to fix that, so I tried creating a `ref` like the [page-metadata page](https://v3.nuxtjs.org/docs/directory-structure/pages/#page-metadata) indicate, but the example from the docs...

```html
<script setup>
const title = ref('Home')
definePageMeta({
  title
})
</script>
```

...results in a 500 error:

```
m.default is not a function
at eval (file://./.nuxt/dist/server/server.mjs:19:126)
at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:257:19)
at async renderMiddleware (file://./.nuxt/nitro/index.mjs:214:20)
at async handle (file://./node_modules/h3/dist/index.mjs:635:19)
```

**Comment by danielroe** [comment]
Try using a computed instead:

```vue
<script setup>
const route = useRoute()
useMeta({
  title: computed(() => `AppName - ${route.meta.title}`)
})
</script>
```

**Comment by command-tab** [comment]
That works! Thank you!

One last question: How can I reference other variables or constants in `definePageMeta`? Let's say I wanted to set a page's title to a value from a JSON response fetched from a remote server via `useAsyncData`. If I do this:

```html
<script setup>
const { data } = await useAsyncData('thingdetail', () => $fetch('https://example.com/api/things/123'))

definePageMeta({
  title: data.some_field
})
</script>
```

Nuxt errors, saying that `data` does not exist, but I just defined it on the line above. In Nuxt 2, I would do:

```html
<script>
export default {
  async asyncData () {
    const thing = await $axios.$get('https://example.com/api/things/123')
    return {
      thing
    }
  },
  head () {
    return {
      title: this.thing.some_field
    }
  }
}
</script>
```

**Comment by danielroe** [comment]
`definePageMeta` is a compiler macro - it's extracted from the component so it can't depend on the result of a fetch.

**Comment by command-tab** [comment]
Hmm. So, there's no way to have a computed page title that also contains the result of a fetch? This was so easy in Nuxt 2, and it's something I do on almost every page of my dozens of Nuxt 2 apps 😞

**Comment by danielroe** [comment]
You can do it before calling `useMeta` - but not before calling `definePageMeta`.

**Comment by command-tab** [comment]
I'm not sure I understand. It seems like I must use `definePageMeta` to send a page-level string to the interpolation happening in the layout. If I performed a fetch and `useMeta` to set the page title based on the results of the fetch, I would be using `useMeta`, not `definePageMeta`, and thus would no longer be sending a string to the layout for interpolation. Do you mean that it's only possible to do one or the other, but not both?

**Comment by danielroe** [comment]
meta is a new feature that didn't exist in Nuxt 2. It's actually set and visible for any of your pages, no matter what is loaded. So it's really powerful but can't depend on the loading lifecycle of a page.

If you have a pattern that you're fetching the page title from a CMS then the approach above of defining the title in page meta is likely not going to work. Instead, there are lots of other ways to do what you want rather than using `definePageMeta`. Such as using a global store, setting the current title via `useState('pageTitle')`, etc. All of which would work with the same kind of computed approach for `useMeta`.

**Comment by jamaluddinrumi** [comment]
> Try using a computed instead:
> 
> ```
> <script setup>
> const route = useRoute()
> useMeta({
>   title: computed(() => `AppName - ${route.meta.title}`)
> })
> </script>
> ```

it's still didn't work for me 
i want to follow https://v3.nuxtjs.org/docs/usage/meta-tags#example-usage-with-definepagemeta 

/layouts/default.vue
```
<script setup>
const route = useRoute();

useMeta({
  title: computed(() => `${route.meta.title} | Site Name`),
});
</script>
```

/pages/sub/_slug.vue
```
<script setup>

const title = ref(
  `This is the page title`
);

definePageMeta({
  title,
});
</script>
```

but it's returned error 500

![localhost_3000_rumah_prv_](https://user-images.githubusercontent.com/446780/157386780-63c2a4d6-0ad4-4349-b0dd-6f38f5fc2248.png)

**Comment by jiblett1000** [comment]
@jamaluddinrumi Remove the ref from the page title and just define it directly. The page title I'm guessing doesn't need to be reactive since the title is already reactive in the layout using the computed property. So, in your page:

```
definePageMeta({
title: 'My Title'
})
```

**Comment by jamaluddinrumi** [comment]
> @jamaluddinrumi Remove the ref from the page title and just define it directly. The page title I'm guessing doesn't need to be reactive since the title is already reactive in the layout using the computed property. So, in your page:
> 
> ```
> definePageMeta({
> title: 'My Title'
> })
> ```

yes, passing only string is works 

but, actually i want to pass such a variable in title such as route params
and i try code below 
and still not works

/layouts/default.vue
```
<script setup>
const route = useRoute();

useMeta({
  title: computed(() => `${route.meta.title} | Site Name`),
});
</script>
```

/pages/sub/[slug].vue
```
<script setup>
import startCase from "lodash.startcase";

const route = useRoute();

definePageMeta({
  title: `Find ${startCase(route.params.slug)} in this page`,
  meta: [
    {
      name: "description",
      content: `Find the best ${startCase(route.params.slug)} in this page.`,
    },
  ],
});
</script>
```

![localhost_3000_rumah_cinere_](https://user-images.githubusercontent.com/446780/157398930-97a71556-0b03-4d59-b96d-50fbc80d2c60.png)

looks like definePageMeta doesn't accept variables instead of only string

**Comment by danielroe** [comment]
* `definePageMeta` is a macro and can't access your component state (useRoute can only be run within a component setup function)
* Just to be clear, you cannot set meta tags within `definePageMeta`

**Comment by jamaluddinrumi** [comment]
> * `definePageMeta` is a macro and can't access your component state (useRoute can only be run within a component setup function)
> * Just to be clear, you cannot set meta tags within `definePageMeta`

hi, @danielroe 
feels honor replied by the core team 
thank's for taking time for this

**Comment by danielroe** [comment]
Your approach seems to be working fine for me: https://stackblitz.com/edit/github-sjdeqx

**Comment by command-tab** [comment]
Closing this one out.

With `useState`, a working solution ends up looking like this in a layout:

```html
<script setup>
const pageTitle = useState('pageTitle')
useMeta({
  title: computed(() => `My App Name - ${pageTitle.value}`)
})
</script>
```

And this on a simple page:

```html
<script setup>
const pageTitle = useState('pageTitle')
pageTitle.value = 'Some Page Title'
</script>
```

And when using `useAsyncData` to load external content in a page and using a value from that content in the page title:

```html
<script setup>
const { data } = await useAsyncData('userDetail', () => $fetch('https://api.github.com/users/command-tab'))
const pageTitle = useState('pageTitle')
pageTitle.value = data.value.name
</script>
```

Doing the equivalent with a store like Pinia instead of Nuxt State would likely be a very similar implementation.

Thanks to @danielroe for all the help! 🙌🏻
