### ISSUE TITLE
 onMounted in setup script not working.

### ISSUE THREAD

**Issue by St2r** [nuxt/framework#3526]
### Environment

RootDir: /Users/st2r/Projects/plagiarism-checker/web                                                                                                              02:34:49
Nuxt project info:                                                                                                                                                02:34:49

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.2.0`
- Nuxt Version:     `3.0.0-27439932.78761c2`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `css`, `build`, `ssr`, `env`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/St2r/plagiarism-checker

The Code is under directory /web. Thank you

### Describe the bug

Using onMounted lifecycle in /web/pages/index.vue went error while SSR. I tried to insert debugger or alert inside onMounted, but nothing happened.

### Logs

```shell
[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
```

**Comment by danielroe** [comment]
Import it from `vue` or rely on auto imports.
