### ISSUE TITLE
definePageMeta should be referenced in useMeta page of docs

### ISSUE THREAD

**Issue by jiblett1000** [nuxt/framework#3529]
### Environment

N/A

### Reproduction

N/A

### Describe the bug

After looking into solutions for https://github.com/nuxt/framework/issues/3522#issuecomment-1060068192, I stumbled on 

https://v3.nuxtjs.org/docs/directory-structure/pages#page-metadata

It seems to me that it would be helpful having at least a quick reference in the meta tags docs to definePageMeta as I would think they'd be commonly used together.

**Comment by danielroe** [comment]
May be worth mentioning that it's not available in Bridge (small note only): https://github.com/nuxt/framework/issues/2979

**Comment by jiblett1000** [comment]
Just to clarifiy....Is useMeta not available in bridge as well or just definePageMeta?

**Comment by danielroe** [comment]
⚠️ `useMeta` is available experimentally in bridge if users opt-in ⚠️
