### ISSUE TITLE
Documentation Cannot find module '../../packages/schema/schema/config.schema.json'

### ISSUE THREAD

**Issue by VidarDev** [nuxt/framework#3550]
### Environment

'''Nuxt project info:                                                                                                07:49:18

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27216014.034b9901`
- Package Manager:  `yarn@1.23.0-20210103.1434`
- Bundler:          `Vite`
- User Config:      `rootDir`, `themeName`, `themeDir`, `head`, `colorMode`, `css`, `components`, `plugins`, `modules`, `vite`, `meta`, `buildModules`, `target`, `server`, `typescript`, `generate`, `build`, `image`, `alias`, `loading`, `windicss`, `publicRuntimeConfig`, `hooks`
- Runtime Modules:  `wrappedModule()`, `@nuxtjs/color-mode@2.1.1`, `@docus/windicss@1.1.5`, `@docus/app/dist/i18n@1.3.5`    
- Build Modules:    `nuxt-vite@0.2.4`, `@nuxtjs/pwa@3.3.5`, `@nuxt/image@0.6.0`, `@nuxtjs/composition-api/module@0.29.3`, `@nuxt/postcss8@1.1.3`, `@docus/core@1.1.2`, `@docus/app/dist/app/index@1.3.5`, `@docus/app/dist/settings@1.3.5`, `@docus/app/dist/context@1.3.5`, `@nuxt/typescript-build@2.1.0`, `@docus/github@1.0.4`, `vue-plausible@1.3.1`
------------------------------'''

### Reproduction

Fork framework
git clone it 
go to /docs folder
npx yarn install
npx yarn dev

### Describe the bug

I wanted to help with the documentation. I noticed that some wording is misleading for beginners. Now I have made a fresh fork and executed everything as described. I ran npx yarn install in the /docs folder then npx yarn dev and got this error.

### Logs

```shell
npx yarn dev        
yarn run v1.23.0-20210103.1434
$ yarn gendocs && nuxt dev
$ jiti ./scripts/gen-docs.ts
Updating docs on C:/Users/vidar/Projekte/Developement/GitHub repositorys/framework/docs/content/3.docs/2.directory-structure/16.nuxt.config.md
Error: Cannot find module '../../packages/schema/schema/config.schema.json'
Require stack:
- C:\Users\vidar\Projekte\Developement\GitHub repositorys\framework\docs\scripts\gen-docs.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at _resolve (C:\Users\vidar\Projekte\Developement\GitHub repositorys\framework\docs\node_modules\jiti\dist\jiti.js:1:192841)
    at jiti (C:\Users\vidar\Projekte\Developement\GitHub repositorys\framework\docs\node_modules\jiti\dist\jiti.js:1:195025)
    at generateDocs (C:\Users\vidar\Projekte\Developement\GitHub repositorys\framework\docs\scripts\gen-docs.ts:120:22)     
    at async main (C:\Users\vidar\Projekte\Developement\GitHub repositorys\framework\docs\scripts\gen-docs.ts:10:3) {       
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\vidar\\Projekte\\Developement\\GitHub repositorys\\framework\\docs\\scripts\\gen-docs.ts'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by danielroe** [comment]
You'll need to run `yarn stub` first in the top level directory - see https://github.com/nuxt/framework#-development.

I see this is missing from the Contribution guide so I'll leave this issue open until we add it in.

**Comment by VidarDev** [comment]
> You'll need to run `yarn stub` first in the top level directory - see https://github.com/nuxt/framework#-development.
> 
> I see this is missing from the Contribution guide so I'll leave this issue open until we add it in.

Wouldn't it be so easier if people like me, who only pay attention to documentation section and not to development section?

#3551
