### ISSUE TITLE
Error loading external "@purge-icons/generated"

### ISSUE THREAD

**Issue by wayearn** [nuxt/framework#3557]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.3`
- Nuxt Version:     `3.0.0-27446051.40d325e`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/wayearn/nuxt3-demo

### Describe the bug

When I want to use iconfiy as an icon library, using Vite's plugin integration https://www.npmjs.com/package/vite-plugin-purge-icons, in app.vue, after importing @purge-icons/generated, the page will immediately icon, but after refreshing, the page will show 500 errors.

**Comment by manniL** [comment]
Can reproduct.
It seems that the vite externals aren't resolved correctly.

In the `.nuxt/dist/server/server.mjs`, the path is missing `node_modules` and the entry file (e.g. `index.js` or `index.mjs`).
When editing the path manually, it seems to work.
![grafik](https://user-images.githubusercontent.com/640208/157420230-ba1a6560-caf7-40c0-bcf0-2a0c0a40de4b.png)


Actual:
```js

// --------------------
// Request: /@id/@purge-icons/generated
// Parents: 
// - /app.vue ($id_2b46e842)
// Dependencies: 

// --------------------
const $id_72f06905 = (global, exports, importMeta, ssrImport, ssrDynamicImport, ssrExportAll) => import("file:///C:/Users/USERNAME/Documents/VSCode%20documents/nuxt3-demo/@purge-icons/generated").then(r => { exports.default = r.default; ssrExportAll(r) }).catch(e => { console.error(e); throw new Error("[vite dev] Error loading external \"@purge-icons/generated\".") })
```

Expected (?):
```js
// --------------------
// Request: /@id/@purge-icons/generated
// Parents: 
// - /app.vue ($id_2b46e842)
// Dependencies: 

// --------------------
const $id_72f06905 = (global, exports, importMeta, ssrImport, ssrDynamicImport, ssrExportAll) => import("file:///C:/Users/USERNAME/Documents/VSCode%20documents/nuxt3-demo/node_modules/@purge-icons/generated/index.mjs").then(r => { exports.default = r.default; ssrExportAll(r) }).catch(e => { console.error(e); throw new Error("[vite dev] Error loading external \"@purge-icons/generated\".") })
```

---

Possibly related:

https://github.com/nuxt/framework/blob/main/packages%2Fvite%2Fsrc%2Fdev-bundler.ts#L74-L86

https://github.com/nuxt/framework/issues/3549

**Comment by danielroe** [comment]
I'm not familiar with the project, but possibly this path could be updated:

https://github.com/antfu/purge-icons/blob/main/packages/constants/index.ts#L1-L5

cc: @antfu

**Comment by antfu** [comment]
TBH Purge Icons is kinda deprecated. I'd recommand to use UnoCSS or unplugin-icons instead. 😅

**Comment by wayearn** [comment]
@antfu thx
