### ISSUE TITLE
CSS file URL contains duplicate `_nuxt`

### ISSUE THREAD

**Issue by manniL** [nuxt/framework#3570]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `bridge`, `nitro`, `target`, `components`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27447086.6c083f3`

### Reproduction

1. Clone [https://github.com/manniL/nuxt-bridge-3441](the repo)
2. `yarn`
3. `yarn build`
4. `npx http-server -p 3033 .output/public/`
5. Open http://localhost:3033/
6. Check the Network tab
7. See that the CSS (`client.HASH.css`) throws a 404

### Describe the bug

After #3441 has been resolved assets do not contain a duplicate `_nuxt` in the path anymore. Except the CSS paths that still do and thus return a 404 🙈

**Comment by danielroe** [comment]
This should be resolved in https://github.com/nuxt/framework/pull/4005. Let me know if not and I'll reopen.
