### ISSUE TITLE
Tailwind module not working

### ISSUE THREAD

**Issue by jiblett1000** [nuxt/framework#3588]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27428764.271289c`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `build`, `css`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@nuxtjs/tailwindcss@5.0.0`

### Reproduction

Not sure one is really necessary, but I am happy to add one if needed.

### Describe the bug

Version [3.0.0-27428764.271289c](https://www.npmjs.com/package/nuxt3/v/3.0.0-27428764.271289c) is the last working version for the tailwindcss module(v5.0.0). Something breaks after this version of nuxt and it seems some classes work oddly but not others. Posting this in the hope that it might help others and hopefully to find some better insight.

P.S. There were no error messages when tailwind stopped working to provide me a trail of breadcrumbs.

**Comment by danielroe** [comment]
Any chance it's the same as this? https://github.com/nuxt-community/tailwindcss-module/issues/433.

If you think it isn't, would you raise an issue [at the module](https://github.com/nuxt-community/tailwindcss-module/issues) instead?

**Comment by jiblett1000** [comment]
I'm not entirely certain but I don't think that it is, partly because I'm not using any custom postcss config. I'm just working with the defaults in the module. Also, using the older module version https://www.npmjs.com/package/@nuxtjs/tailwindcss/v/5.0.0-4 with the latest nuxt is broken as well. It seems just the JIT classes are not working. Not sure if that helps at all. I'll of course raise the issue over there if you still think that's where it belongs.

**Comment by danielroe** [comment]
Would you raise it against that repo then? I've also submitted a PR there just in case the schema change is the cause.

**Comment by jiblett1000** [comment]
Will Do :)
