### ISSUE TITLE
Vite-node support progress

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#3598]
Using vite-node integration, we could lazily load and evaluate server chunks just like clients without bundling the whole app each time. Since this is a rather big change, we are progressively rolling it out.

Opting in: Use `experimental.viteNode: true` in `nuxt.config` or `EXPERIMENTAL_VITE_NODE=1` environment variable.

```js
// nuxt.config
experimental: { viteNode: true }
```

- [x] Initial support (https://github.com/nuxt/framework/pull/2795)
- [x] Use nuxt server middleware
- [x] Use envrionemnt variables to provide config instead of template
- [x] Generate files outside of runtime (endpoint to get manifest)

**Comment by Atinux** [comment]
What are the current blockers to have progress on this?

**Comment by pi0** [comment]
Nothing is blocker on nuxt side I suppose. We only need to iterate to move the feature out of the experimental state with more stability.

**Comment by pi0** [comment]
The initial checklist is done. However we need still testing to move it out of the experimental flag.
