### ISSUE TITLE
Nuxt2 upgrade Bridge error: No matching version found for pretty-bytes@^6.0.0

### ISSUE THREAD

**Issue by M1seRy** [nuxt/framework#3642]
### Environment

node v14.16.0
npm v 6.14.11
nuxt 2.13.3

### Reproduction

I Use the following command for a standard installation

### Describe the bug

I read the [guide](https://v3.nuxtjs.org/getting-started/bridge) to upgrade bridge from nuxt2.  from step2 I use  this command to install nuxt/bridge-edge get the error :
```
npm install -D @nuxt/bridge@npm:@nuxt/bridge-edge
```

### Logs

```shell
✦3 ❯ npm install -D @nuxt/bridge@npm:@nuxt/bridge-edge
npm ERR! code ETARGET
npm ERR! notarget No matching version found for pretty-bytes@^6.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@nuxt/nitro'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/misery/.npm/_logs/2022-03-14T10_09_42_823Z-debug.log
```

**Comment by danielroe** [comment]
It [exists](https://unpkg.com/browse/pretty-bytes@6.0.0/), so this is likely a temporary npm issue.

**Comment by danielroe** [comment]
I don't experience it, so I would just keep on trying at your end.

**Comment by M1seRy** [comment]
> I don't experience it, so I would just keep on trying at your end.

Thanks I find the way to solve the problem by sync package pretty-bytes，because I used a local NPM repository ~
