### ISSUE TITLE
Nuxt Bridge dev error: Cannot start nuxt:  Cannot find module 'nuxt'

### ISSUE THREAD

**Issue by M1seRy** [nuxt/framework#3662]
### Environment

✦3 ❯ npx nuxi info
Nuxt CLI v3.0.0-27454252.7bf338d                                                             15:31:27
RootDir: /Users/misery/workspace/nuxt2_pro                          15:31:33
Nuxt project info:                                                                           15:31:33

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.16.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@6.14.11`
- Bundler:          `Webpack`
- User Config:      `telemetry`, `hooks`, `mode`, `target`, `head`, `css`, `plugins`, `components`, `modules`, `build`, `srcDir`, `server`, `loading`, `render`, `publicRuntimeConfig`, `privateRuntimeConfig`, `proxy`, `serverMiddleware`, `router`, `bridge`, `buildModules`
- Runtime Modules:  `@nuxtjs/proxy@2.1.0`, `@nuxt/http@0.5.13`, `@nuxtjs/device@1.2.7`, `@nuxtjs/svg@0.1.12`
- Build Modules:    `@nuxt/bridge@3.0.0-27454252.7bf338d`

-----

"@nuxt/kit": "npm:@nuxt/kit-edge@^3.0.0-27454252.7bf338d",

### Reproduction

I read the [guide](https://v3.nuxtjs.org/getting-started/bridge) to upgrade bridge from nuxt2. from step3 I use this command to start dev environment but get the following error

### Describe the bug

```
>  nuxi dev

ERROR  Cannot start nuxt:  Cannot find module 'nuxt'                                        15:27:46
Require stack:
- /Users/misery/workspace/nuxt2_pro /index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
  at Function.resolve (internal/modules/cjs/helpers.js:94:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:192841)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:227:29)
  at importModule (node_modules/@nuxt/kit/dist/index.mjs:250:24)
  at loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:641:92)
  at async load (node_modules/@nuxt/bridge/node_modules/nuxi/dist/chunks/dev.mjs:6729:25)
  at async Object.invoke (node_modules/@nuxt/bridge/node_modules/nuxi/dist/chunks/dev.mjs:6771:5)
  at async _main (node_modules/@nuxt/bridge/node_modules/nuxi/dist/chunks/index.mjs:384:7)

```

thanks, need some help~

**Comment by danielroe** [comment]
Would you please provide a reproduction? 🙏

**Comment by M1seRy** [comment]
> Would you please provide a reproduction? 🙏

@danielroe Thank you for your quick reply, I found that it was a problem with my environment, caused by inconsistent versions of the global installation, after deleting lock file and clearing the cache reload and reinstall solved the problem
