### ISSUE TITLE
Dynamically creating <NuxtLink> with <Component> no longer works

### ISSUE THREAD

**Issue by ataylor32** [nuxt/framework#3672]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.17.6`
- Nuxt Version:     `3.0.0-27454426.4cefce4`
- Package Manager:  `npm@8.5.4`
- Bundler:          `Vite`
- User Config:      `meta`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-92nabt?file=app.vue

### Describe the bug

Code like this used to work, but no longer does:

```html
<Component :is="1 === 1 ? 'NuxtLink' : 'a'" to="/example">
  This should be a link to the "Example" page
</Component>
```

### Additional context

Two others with the same problem:

https://discord.com/channels/473401852243869706/897487139888062506/953235583403196476

https://discord.com/channels/473401852243869706/897487139888062506/953281246472056882

**Comment by manniL** [comment]
With https://github.com/nuxt/framework/pull/3544, this might not be necessary anymore 😋 

Nevertheless, creating `NuxtLink` via `<component is="">` should still be possible.

**Comment by ja1984** [comment]
@manniL In this example it happens to be a NuxtLink, but I think <component :is=""> is broken, I'm having issues getting it working locally, and I also took the liberty to update @ataylor32 s example https://stackblitz.com/edit/github-92nabt-973keb?file=app.vue and as you can see it does not render the test component, it tries to render a <test> component.

**Comment by snarcraft** [comment]
I think it comes from this MR https://github.com/nuxt/framework/pull/3544
A workaround would be to use an instance of NuxtLink from defineNuxtLink
```
const nl = defineNuxtLink({})
```

**Comment by przyb** [comment]
While the new `NuxtLink` is much more robust and you won't need to dynamically exchange it with an `a` like in the OP's example, we still need to be able to do that when we need to do a "sometime-a-link". My use case is a list of projects on a portfolio website. Some of them will link locally to a case study, others to external websites. But for some older projects, I only want to list them, so I need to replace a `NuxtLink` with a simple `div`. The workaround with `defineNuxtLink({})` worked well but I feel it would be nice to be able to import `NuxtLink` or at least have this better documented :)

**Comment by jerryjappinen** [comment]
Also ran into this. I very often have components that might or might not render a link, just like @przyb mentioned there. I might have a button component that does something like this:

```js
  computed: {
    is () {
      if (this.to) {
        return 'NuxtLink'
      } else if (this.href || this.mailto || this.tel) {
        return 'a'
      }

      return 'button'
    }
  }
```

Mostly I just do this, so that I don't have to duplicate or spread other relevant button logic/styling between multiple components.

Another reason I might do this, is that part of the data might still be loading. I might know that I want to render a list of objects, but e.g. a component of the URL necessary to render the link is not available yet. Maybe client is still waiting for the rest of the data to load, or the data is only available after hydration but not server-side.

**Comment by danielroe** [comment]
The new way to pull in a component that is not globally registered is to use `resolveComponent`.

See https://github.com/nuxt/framework/issues/3885#issuecomment-1077810348.

**[Example with NuxtLink](https://stackblitz.com/edit/github-58urlz?file=app.vue).**

**Comment by Jones-S** [comment]
What if I have the same problem but with nuxt2. Is there also a solution somewhere?
Thanks in advance. 👍
