### ISSUE TITLE
windows bridge fails when running dev

### ISSUE THREAD

**Issue by caikan** [nuxt/framework#3675]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.1.2`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/caikan/bug-nuxt-framework/tree/repro-dev-startup-fatal

### Describe the bug

It seems to happen only on Windows platform, so I can't repro it in codesandbox.

### Logs

```shell
FATAL  Cannot read properties of null (reading 'close')

  at Builder.unwatch (node_modules\@nuxt\builder-edge\dist\builder.js:666:30)
  at Builder.close (node_modules\@nuxt\builder-edge\dist\builder.js:674:10)
  at node_modules\@nuxt\builder-edge\dist\builder.js:195:42
  at node_modules\hable\dist\hable.js:1:990
  at node_modules\hable\dist\hable.js:1:208
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Nuxt.callHook (node_modules\hable\dist\hable.js:1:959)
  at async Nuxt.close (node_modules\@nuxt\core-edge\dist\core.js:363:5)
  at async load (/project/node_modules/nuxi/dist/chunks/dev.mjs:6727:11)
  at async /project/node_modules/nuxi/dist/chunks/dev.mjs:6687:11

i Preparing project for development
i Initial build may take a while
i Discovered Components: .nuxt/components/readme.md
√ Builder initialized
√ Nuxt files generated

 ERROR  Failed to compile with 1 errors


 ERROR  in ./.nuxt/client.js

Module build failed (from ./node_modules/unplugin/dist/webpack/loaders/transform.js):
Error: ENOENT: no such file or directory, open '\project\.nuxt\client.js'

 @ multi ./node_modules/@nuxt/bridge/dist/runtime/capi.plugin.mjs ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

**Comment by vis97c** [comment]
Same happened to me after reinstalling the dependencies. Also on windows.

**Comment by senar9** [comment]
same problem

**Comment by vis97c** [comment]
> @vis97c Which nodejs version are you using, pnpm? npm? or yarn?

Node @14.17.0 with yarn

**Comment by vis97c** [comment]
I restored and old yarn.lock & installed from there so now is working for me.

Comparing it to the reproduction repo we are using the same version of nuxt.

My yarn lock
```
nuxt-edge@latest:
  version "2.16.0-27358576.777a4b7f"
  resolved "https://registry.yarnpkg.com/nuxt-edge/-/nuxt-edge-2.16.0-27358576.777a4b7f.tgz#915edaf69657d8959270caf85153715b44ab3645"
  integrity sha512-cXgbo4MrXxh6YJSB1wEKod34QrH+6kJ1VoLTe1znRktWJZU3o+FDlDg6IRUf9NgcUSTdcp+Z7ZzyORCytUYNjQ==
  dependencies:
    "@nuxt/babel-preset-app-edge" "2.16.0-27358576.777a4b7f"
    "@nuxt/builder-edge" "2.16.0-27358576.777a4b7f"
    "@nuxt/cli-edge" "2.16.0-27358576.777a4b7f"
    "@nuxt/components" "^2.2.1"
    "@nuxt/config-edge" "2.16.0-27358576.777a4b7f"
    "@nuxt/core-edge" "2.16.0-27358576.777a4b7f"
    "@nuxt/generator-edge" "2.16.0-27358576.777a4b7f"
    "@nuxt/loading-screen" "^2.0.4"
    "@nuxt/opencollective" "^0.3.2"
    "@nuxt/server-edge" "2.16.0-27358576.777a4b7f"
    "@nuxt/telemetry" "^1.3.6"
    "@nuxt/utils-edge" "2.16.0-27358576.777a4b7f"
    "@nuxt/vue-app-edge" "2.16.0-27358576.777a4b7f"
    "@nuxt/vue-renderer-edge" "2.16.0-27358576.777a4b7f"
    "@nuxt/webpack-edge" "2.16.0-27358576.777a4b7f"
```

Reproduction package-lock.json
```
"node_modules/nuxt-edge": {
      "version": "2.16.0-27358576.777a4b7f",
      "resolved": "https://registry.npmjs.org/nuxt-edge/-/nuxt-edge-2.16.0-27358576.777a4b7f.tgz",
      "integrity": "sha512-cXgbo4MrXxh6YJSB1wEKod34QrH+6kJ1VoLTe1znRktWJZU3o+FDlDg6IRUf9NgcUSTdcp+Z7ZzyORCytUYNjQ==",
      "hasInstallScript": true,
      "dependencies": {
        "@nuxt/babel-preset-app-edge": "2.16.0-27358576.777a4b7f",
        "@nuxt/builder-edge": "2.16.0-27358576.777a4b7f",
        "@nuxt/cli-edge": "2.16.0-27358576.777a4b7f",
        "@nuxt/components": "^2.2.1",
        "@nuxt/config-edge": "2.16.0-27358576.777a4b7f",
        "@nuxt/core-edge": "2.16.0-27358576.777a4b7f",
        "@nuxt/generator-edge": "2.16.0-27358576.777a4b7f",
        "@nuxt/loading-screen": "^2.0.4",
        "@nuxt/opencollective": "^0.3.2",
        "@nuxt/server-edge": "2.16.0-27358576.777a4b7f",
        "@nuxt/telemetry": "^1.3.6",
        "@nuxt/utils-edge": "2.16.0-27358576.777a4b7f",
        "@nuxt/vue-app-edge": "2.16.0-27358576.777a4b7f",
        "@nuxt/vue-renderer-edge": "2.16.0-27358576.777a4b7f",
        "@nuxt/webpack-edge": "2.16.0-27358576.777a4b7f"
      },
      "bin": {
        "nuxt": "bin/nuxt.js"
      }
    }
```

I don't have a lot of time right now but I will add more details if necessary.

**Comment by hsmfawaz** [comment]
Same any updates
i tried node 14 and 16 with npm and yarn same problem and its a fresh nuxt 2 project

**Comment by admiralsemu** [comment]
I'm also getting this issue. My config is:

- Operating System: `Windows_NT`
- Node Version:     `v16.14.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.5.0`
- Builder:          `webpack`
- User Config:      `target`, `build`, `head`, `plugins`, `components`, `buildModules`, `modules`, `colorMode`, `axios`, `generate`, `googleAnalytics`, `pwa`, `sitemap`, `bridge`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `nuxt-interpolation@0.2.7`, `nuxt-protected-mailto@0.0.8`, `@nuxtjs/sitemap@2.4.0`
- Build Modules:    `@nuxtjs/color-mode@2.1.1`, `@nuxtjs/tailwindcss@4.2.1`, `@nuxtjs/svg@0.2.0`, `@nuxtjs/google-analytics@2.4.0`, `@nuxtjs/pwa@3.3.5`, `@nuxt/bridge@3.0.0-27470397.9ebea90`

My Log is (slightly modified to remove project name):

`Nuxt CLI v3.0.0-27470397.9ebea90                                                                                                                               
                                                                                                                                                                
  > Local:    http://localhost:3000/ 
  > Network:  http://10.0.0.20:3000/

i Using Tailwind CSS from ~/assets\css\tailwind.css                                                                                           
i Merging Tailwind config from ~/tailwind.config.js                                                                                             
i Preparing project for development                                                                                                                             
i Initial build may take a while                                                                                                                                
i Discovered Components: .nuxt/components/readme.md                                                                                                             
√ Builder initialized                                                                                                                                           
i Directory components/ created. Restarting nuxt...                                                                                                             

 FATAL  Cannot read properties of null (reading 'close')                                                                                                        

  at Builder.unwatch (node_modules\@nuxt\builder-edge\dist\builder.js:666:30)
  at Builder.close (node_modules\@nuxt\builder-edge\dist\builder.js:674:10)
  at node_modules\@nuxt\builder-edge\dist\builder.js:195:42
  at node_modules\hable\dist\hable.js:1:990
  at node_modules\hable\dist\hable.js:1:208
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Nuxt.callHook (node_modules\hable\dist\hable.js:1:959)
  at async Nuxt.close (node_modules\@nuxt\core-edge\dist\core.js:363:5)
  at async load (/C:/Users/Project/node_modules/nuxi/dist/chunks/dev.mjs:6748:11)
  at async _applyPromised (/C:/Users/Project/node_modules/nuxi/dist/chunks/dev.mjs:6696:10)
`

**Comment by Eckhardt-D** [comment]
Same issue, clean install of nuxt2 with Vuetify and migrated to edge using the official guide (works on Mac) `npx nuxi info` output:

```
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.18`
- Builder:          `webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `axios`, `vuetify`, `build`, `bridge`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27477996.646c2f6`
------------------------------
```
## Fatal Error
![image](https://user-images.githubusercontent.com/37825447/161006330-b9d33b85-25aa-4eb7-9a2b-e3fa88d23955.png)

## Info
`nuxi build` and `nuxi preview` works just fine. Temporarily changed as a workaround on dev (this sucks though because the tsconfig.json isn't injected to `./.nuxt/tsconfig.json`):

```json
"scripts": {
    "dev": "nuxt dev"
}
```

**Comment by yinfoyuan** [comment]
```
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.17.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27478517.9c2e208`
------------------------------
```
![image](https://user-images.githubusercontent.com/35027364/161025024-008d130b-6d90-4655-9368-6b0efb014355.png)
