### ISSUE TITLE
Warnings import from #app and vue

### ISSUE THREAD

**Issue by Luferov** [nuxt/framework#3727]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.4.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `app`, `bridge`, `alias`, `ssr`, `target`, `publicRuntimeConfig`, `head`, `loading`, `css`, `plugins`, `components`, `buildModules`, `modules`, `apollo`, `i18n`, `typescript`, `router`, `vuetify`, `build`
- Runtime Modules:  `@nuxtjs/color-mode@3.0.2`, `@nuxtjs/apollo@4.0.1-rc.5`, `cookie-universal-nuxt@2.1.5`
- Build Modules:    `@nuxt/bridge@3.0.0-27457855.7c0b914`, `@pinia/nuxt@0.1.8`, `@nuxtjs/vuetify@1.12.3`, `@nuxtjs/i18n@7.2.0`

### Reproduction

https://github.com/devind-team/devind-template 

Steps:
- cd client
- yarn
- yarn run dev

### Describe the bug

I gotting warnings when run in dev and prod mode.

warn in in ./.nuxt/imports.mjs:
- "export 'clearError' was not found in '#app'  
- "export 'defineNuxtLink' was not found in '#app'
- "export 'effect' was not found in 'vue' 
- "export 'isProxy' was not found in 'vue'
- "export 'isShallow' was not found in 'vue' 
- "export 'onRenderTracked' was not found in 'vue' 
- "export 'onRenderTriggered' was not found in 'vue'
- "export 'throwError' was not found in '#app'
- "export 'useCssVars' was not found in 'vue'
- "export 'useError' was not found in '#app' 
- "export 'useTransitionState' was not found in 'vue'
- "export 'withCtx' was not found in 'vue' 
- "export 'withDirectives' was not found in 'vue' 
- "export 'withKeys' was not found in 'vue'
- "export 'withMemo' was not found in 'vue'
- "export 'withModifiers' was not found in 'vue'
- "export 'withScopeId' was not found in 'vue'

### Additional context

![image](https://user-images.githubusercontent.com/26242554/158769532-a5ac41a9-a6a2-4a0b-862e-0cbdc24a3092.png)

**Comment by alekcahdp** [comment]
I have the same problem

**Comment by rvmourik** [comment]
Same here

**Comment by AndreyYolkin** [comment]
Same

**Comment by ahmedmkamal** [comment]
I'm having another warning

```
 WARN  [SSR] Error transforming virtual:/project-root/.nuxt/paths.mjs: Failed to resolve import "#_config" from "virtual:/project-root/.nuxt/paths.mjs". Does the file exist?

  at formatError (node_modules/vite/dist/node/chunks/dep-9c153816.js:38098:46)
  at TransformContext.error (node_modules/vite/dist/node/chunks/dep-9c153816.js:38094:19)
  at normalizeUrl (node_modules/vite/dist/node/chunks/dep-9c153816.js:69819:26)
  at async TransformContext.transform (node_modules/vite/dist/node/chunks/dep-9c153816.js:69959:57)
  at async Object.transform (node_modules/vite/dist/node/chunks/dep-9c153816.js:38334:30)
  at async doTransform (node_modules/vite/dist/node/chunks/dep-9c153816.js:53030:29)
```

not sure if it's related to this one?

**Comment by danielroe** [comment]
@ahmedmkamal No, that's a different issue, which should now be resolved by https://github.com/nuxt/framework/pull/3848.

**Comment by ahmedmkamal** [comment]
@danielroe Okay, thank you!
