### ISSUE TITLE
Autoimport components dir

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#3746]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.6.0`
- Nuxt Version:     `3.0.0-27458584.91fd16a`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `privateRuntimeConfig`, `app`, `components`, `nitro`, `srcDir`, `build`, `buildModules`, `modern`, `tailwindcss`, `meta`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.2`
------------------------------

### Reproduction

--

### Describe the bug

when i trying to start my project with new version of nuxt 3 i have error:
- `[Vue warn]: Failed to resolve component: NavLink
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Invalid value used as weak map key`

my `nuxt.config.ts`:
```ts
import { defineNuxtConfig } from 'nuxt3';

export default defineNuxtConfig({
	privateRuntimeConfig: {
		secretJWT: process.env.SECRET_JWT,
	},
	app: {
		buildAssetsDir: 'assets/',
	},
	components: {
		global: true,
		dirs: ['~/components'],
	},
	nitro: {
		output: {
			dir: 'build',
		},
		externals: {
			inline: ['uuid'],
		},
	},
	srcDir: 'src',
	build: {
		splitChunks: {
			pages: true,
			layouts: true,
		},
	},
	buildModules: ['@nuxtjs/tailwindcss'],
	modern: true,
	tailwindcss: {
		configPath: '~~/tailwind.config.js',
		viewer: false,
	},
	meta: {
		title: 'Santrek Admin',
		link: [
			{
				rel: 'icon',
				href: '/favicon.svg',
				type: 'image/svg+xml',
			},
		],
	},
});

```

### Additional context

-

### Logs

```shell
-
```

**Comment by johannschopplich** [comment]
Same problem here. When extending another Nuxt instance (different `srcDir` path), none of the components can be auto imported. 

Thrown error:

```
[Vue warn]: Failed to resolve component: PanelEnvironment
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

 ERROR  [worker] Invalid value used as weak map key                                                                                                                           10:08:30
```

**Comment by little3201** [comment]
same problem on "nuxt3": "^3.0.0-27459267.f69126e",
![image](https://user-images.githubusercontent.com/34156125/158988481-78d6db3b-d934-489a-b260-8d97cb732b15.png)
![image](https://user-images.githubusercontent.com/34156125/158988524-58c6906c-566c-4c47-aa22-1bf95629f58a.png)

**Comment by duckies** [comment]
I'm encountering a similar issue where component resolution is failing when using a non-default `srcDir`. [Reproduction](https://stackblitz.com/edit/github-owuv4h-x4gv4k?file=src/app.vue).

You can temporarily fix this by appending `srcDir` to your component directories, e.g.
```Javascript
export default defineNuxtConfig({
  srcDir: 'src/',
  components: ['~/src/components']
});
```

**Comment by Teranode** [comment]
@mihail727 do this instead for components:

```ts
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
    hooks: {
        'components:dirs' (dirs) {
            dirs.push({
                path: '~/components'
            })
        }
    },
    components: {
        global: true
    },
})
  ```
  ----
  
  @duckies yea I can also see this issue, in the stackblitz repo, use `@/components` as that one is working as `~/components` isn't for the array

**Comment by rjcpereira** [comment]
Have your tried to use the `dirs` array of `components` property in `nuxt config`?
```javascript
export default defineNuxtConfig({
    components = { 
        dirs: [ '~/src/components' ]
    }
}};
```

**Comment by johannschopplich** [comment]
@Teranode That works in my setup. Thanks!

**Comment by mihail727** [comment]
> I'm encountering a similar issue where component resolution is failing when using a non-default `srcDir`. [Reproduction](https://stackblitz.com/edit/github-owuv4h-x4gv4k?file=src/app.vue).
> 
> You can temporarily fix this by appending `srcDir` to your component directories, e.g.
> 
> ```js
> export default defineNuxtConfig({
>   srcDir: 'src/',
>   components: ['~/src/components']
> });
> ```

that works for me thanks

**Comment by mihail727** [comment]
@danielroe oh shit..... in another larger project, this solution did not work(
error: ![](https://i.imgur.com/L0CwhXd.png)
