### ISSUE TITLE
meta script tags in nuxt.config.ts escape or htmlencode `&`

### ISSUE THREAD

**Issue by acidjazz** [nuxt/framework#3758]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27459267.f69126e`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `srcDir`, `meta`, `css`, `components`, `buildModules`, `publicRuntimeConfig`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.1.1`, `@tailvue/nuxt@0.1.58`, `nuxt-windicss@2.2.8`
------------------------------

### Reproduction

```ts
meta: {
  script: [
      {
        async: true,
        hid: 'maps-googleapis',
        src: `https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_API_KEY}&libraries=places`,
      },
  ]
}
```

will result in this when viewing source:

```html
<script async hid="maps-googleapis" src="https://maps.googleapis.com/maps/api/js?key=???&amp;libraries=places"></script>
```
=
### Describe the bug

the  & is ..  htmlencoded?

Duplicated env: 

https://stackblitz.com/edit/github-3elxbc?file=nuxt.config.ts

open a new window and view source:

<img width="212" alt="image" src="https://user-images.githubusercontent.com/967369/159113924-73cb06b2-ada6-4a77-9493-b3cf7ac39d9d.png">

**Comment by acidjazz** [comment]
@danielroe nice find! Yes I'll raise an issue there and keep track here

**Comment by harlan-zw** [comment]
This should be good to close
