### ISSUE TITLE
Builder webpack option, script dev is failed

### ISSUE THREAD

**Issue by DongKyuuuu** [nuxt/framework#3759]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27439932.78761c2`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `builder`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Code sendbox: https://codesandbox.io/s/sharp-booth-z4m7jb?file=/nuxt.config.ts

### Describe the bug

When i nuxt.config.ts option changed `builder: 'webpack'`, dev and build script is failed.
```
 ERROR  Cannot start nuxt:  Cannot destructure property 'bundle' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.

  at bundle (node_modules/nuxt3/dist/chunks/index.mjs:1379:19)
  at async build (node_modules/nuxt3/dist/chunks/index.mjs:1355:5)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6734:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6771:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:384:7)
```

**Comment by danielroe** [comment]
You also need to install the webpack builder.

See https://github.com/nuxt/framework/discussions/2883

**Comment by danielroe** [comment]
I'm going to reopen this until we make the error message better. 🙏

**Comment by namereva** [comment]
I have same error, but i use default builder (vite).
