### ISSUE TITLE
Duplicated imports "definePageMeta" the one from "[app_root]/node_modules/nuxt3/dist/pages/runtime/composables" has been ignored.

### ISSUE THREAD

**Issue by ndr47** [nuxt/framework#3768]
After a fresh install I keep getting this warning in the `nuxi dev` command console every time I save a file.

### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27459267.f69126e`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Steps to reproduce:
```
yarn nuxi init nuxt3-app
cd nuxt3-app
yarn install
yarn dev -o
```
Then I delete the `app.vue` file.
Edit the `nuxt.config.ts`:
```
import { defineNuxtConfig } from 'nuxt3'
export default defineNuxtConfig({
	srcDir: './src'
})
```

Create the directory `./src`.
Create the directory `./src/pages`.
Create the file `./src/pages/index.ts`.

### Describe the bug

And I get the Warning:
```
Duplicated imports "definePageMeta" the one from "[app_root]/node_modules/nuxt3/dist/pages/runtime/composables" has been ignored.
```

How can this be fixed?

**Comment by joel-wenzel** [comment]
It also seems like anything added to `autoImports` also gives this warning (only on nuxt 3 and not bridge):
```typescript
 autoImports: {
    imports: [
      {
        from: '@apollo/client/core',
        name: 'gql',
      },
      {
        from: '@vue/apollo-composable',
        name: 'useQuery',
      },
      {
        from: '@vue/apollo-composable',
        name: 'useResult',
      },
  ]
}
```

```
Nuxt CLI v3.0.0-27460489.53fbca7

  > Local:    http://localhost:3000/  
  > Network:  http://172.21.0.1:3000/ 
  > Network:  http://10.48.0.182:3000/


 WARN  Duplicated imports "gql", the one from "@apollo/client/core" has been ignored


 WARN  Duplicated imports "useQuery", the one from "@vue/apollo-composable" has been ignored


 WARN  Duplicated imports "useResult", the one from "@vue/apollo-composable" has been ignored
```

**Comment by danielroe** [comment]
This should now be resolved upstream in `unimport`. Let me know if not and I'll reopen.

**Comment by danielroe** [comment]
Still getting this with unimport 0.1.4.

cc: @antfu

**Comment by antfu** [comment]
I am not able to reproduce it, can anyone share a reproduction link? Thanks

**Comment by acidjazz** [comment]
I'm able to duplicate this with a brand new project

```
 WARN  Duplicated imports "definePageMeta", the one from "../node_modules/nuxt/dist/pages/runtime/composables" has been ignored
```

**Comment by Aareksio** [comment]
I can also consistently reproduce as per https://github.com/nuxt/framework/issues/4522 - it happens when the page file is added when dev server is running.

```
add pages/test.vue                                                                                                                                                                                           12:51:47

 WARN  Duplicated imports "definePageMeta", the one from "X:/_polygon/nuxt3-issues/node_modules/nuxt3/dist/pages/runtime/composables" has been ignored                                                       12:51:47

√ Vite server built in 151ms                                                                                                                                                                                 12:51:47
```

**Comment by acidjazz** [comment]
> I can also consistently reproduce as per #4522 - it happens when the page file is added when dev server is running.
> 
> ```
> add pages/test.vue                                                                                                                                                                                           12:51:47
> 
>  WARN  Duplicated imports "definePageMeta", the one from "X:/_polygon/nuxt3-issues/node_modules/nuxt3/dist/pages/runtime/composables" has been ignored                                                       12:51:47
> 
> √ Vite server built in 151ms                                                                                                                                                                                 12:51:47
> ```

Same!

**Comment by bbaltutat** [comment]
After the update, it has moved to the console on browser - Uncaught SyntaxError: Duplicate export of 'definePageMeta' (at imports.mjs:5:26).

**Comment by bbaltutat** [comment]
Each time I save a file and it renders, it rewrites the file and adds another ```definePageMeta```. This is any example of saving a file 3 times.

.nuxt/imports.d.ts

```export { definePageMeta, definePageMeta, definePageMeta, definePageMeta } from 'xxxx/node_modules/nuxt/dist/pages/runtime/composables';```

**Comment by gsabater** [comment]
I'm having the same issue, for me it seems that this happens after creating a new page while the server is running.
I have found that it can be solved by stopping and starting the development server again.

**Comment by mbrodt** [comment]
> I'm having the same issue, for me it seems that this happens after creating a new page while the server is running. I have found that it can be solved by stopping and starting the development server again.

I am also having the same issue, but restarting the server does not have any effect. I also didn't create any new pages while the server was running. 

I'm specifically getting the issue when adding a Layout to the application, by creating the `layouts/` directory and adding a `default.vue` layout in there - and the result is the same browser error as @bbaltutat

**Comment by lucassimines** [comment]
I'm having the same issue by saving a file inside `compososables directory` while running on `dev` mode

**Comment by Harkonnen13** [comment]
Can confirm, same issue with composables.
![image](https://user-images.githubusercontent.com/28978908/165756529-34d9cff6-8134-49b5-960e-650a3687f9d0.png)

**Comment by lucassimines** [comment]
@Harkonnen13 I changed my nuxt version to `"nuxt": "npm:nuxt3@latest"` and this issue no longer exists
