### ISSUE TITLE
Middleware is not able to redirect with parameters

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#3784]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27460024.7d37a13`
- Package Manager:  `npm@8.5.4`
- Builder:          `vite`
- User Config:      `css`, `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`

### Reproduction

https://codesandbox.io/s/heuristic-lalande-3ke38m?file=/middleware/auth.global.ts

### Describe the bug

When in the navigateTo function I send query parameters, Nuxt does two redirects and loses the query parameter.

For example:

I call the URL https://3ke38m.sse.codesandbox.io/?categoryId=3 and it takes me to https://3ke38m.sse.codesandbox.io/auth/sign-in?redirectTo=/ when it should be https://3ke38m.sse.codesandbox.io/auth/sign-in?redirectTo=/?categoryId=3

**Comment by bayramorhan** [comment]
is this even resolved?
