### ISSUE TITLE
hot reload color problem

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#3791]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.1`
- Nuxt Version:     `3.0.0-27460489.53fbca7`
- Package Manager:  `yarn@3.2.0`
- Builder:          `vite`
- User Config:      `buildModules`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

https://github.com/productdevbook/nuxt3-app

### Describe the bug

https://user-images.githubusercontent.com/38668796/159122024-8e93ba2d-5d3d-4850-b29a-0ca7cabb4dd6.mp4

**Comment by danielroe** [comment]
Would you provide a minimal reproduction rather than your entire project, and first check that this isn't reproducible without Nuxt?

https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main

I can't reproduce in this minimal repro using `@nuxtjs/tailwindcss`: https://stackblitz.com/edit/github-gawbbu.

**Comment by productdevbook** [comment]
I use it this way on the Vue side, there is no problem. But nuxt does not change color at the same settings.

**Comment by danielroe** [comment]
Here's a minimal reproduction that also doesn't reproduce the issue:

* Nuxt 3: https://stackblitz.com/edit/github-binsah
* Vue 3 SSR: https://stackblitz.com/edit/github-xpqq14

Would you modify the Nuxt 3 one to align with your setup until it reproduces the issue please?

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/161964059-fde3b084-b500-44cf-99bf-ff5c639132bd.png)

some problem upgrade https://github.com/productdevbook/nuxt3-app

**Comment by productdevbook** [comment]
```
optimizeDeps: {
            include: [
                '@headlessui/vue', '@heroicons/vue/solid', '@heroicons/vue/outline', 'vue', 'pinia', 'ufo'
            ]
        }
```

nuxt config add and fixed. interested

**Comment by danielroe** [comment]
Thanks for the info @productdevbook. I think this is likely library-specific and not something we can resolve within Nuxt itself. (But ideas welcome if you think differently.)
