### ISSUE TITLE
custom pageTransition / layoutTransition docs unclear

### ISSUE THREAD

**Issue by jiblett1000** [nuxt/framework#3797]
Hello,

I was going through the "pages" docs and thought the bit on customizing the page and/or layout transitions was a bit vague:

https://v3.nuxtjs.org/docs/directory-structure/pages#layouttransition-and-pagetransition

On reading it, it's hard to tell how exactly the transition properties can be customized within nuxt. I would be more than happy to open a PR for this including an example. However, I would need some insight first into how this is handled.

**Comment by jiblett1000** [comment]
Awesome, thanks @danielroe!

**Comment by jiblett1000** [comment]
@danielroe So, I've got this working in definePageMeta just fine. However, I have to define it for each page. Not a huge deal, but wondering if there is a way to define the page transition properties globally?

**Comment by danielroe** [comment]
I agree I think that would be useful. It would be worth opening an issue, and of course a PR would be welcome too.

**Comment by jiblett1000** [comment]
@danielroe I'll definitely open an issue. I'm probably too much on the novice side to contribute much PR-wise, but if you can point me in the right direction to where that might be handled, I would be more than happy to try :)
