### ISSUE TITLE
loadConfig makes array type item duplicated.

### ISSUE THREAD

**Issue by higuaifan** [nuxt/framework#3800]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0`
- Package Manager:  `pnpm@6.32.3`
- Builder:          `vite`
- User Config:      `extensions`, `modules`
- Runtime Modules:  `./modules/markdown`
- Build Modules:    `-`
------------------------------

### Reproduction

I don't think it might be necessary.

### Describe the bug

if my `nuxt.config.ts` like this:
``` ts
import { defineNuxtConfig } from 'nuxt3';

export default defineNuxtConfig({
  extensions:['.md'],
  modules:[
    './modules/markdown'
  ],
})
```

in `loadNuxtConfig`, after run `loadConfig`,`nuxtConfig` will like this:

``` json
{
  "extensions": [
    ".md",
    ".md"
  ],
  "modules": [
    "./modules/markdown",
    "./modules/markdown"
  ],
}
```
I believe it is a bug .. or this is a new feature (I don't know much about `individual config layers for extending`)?

-------

in this line used `loadConfig` ,
https://github.com/nuxt/framework/blob/53fbca77d4b84ac9b8eadd582d7afbbbc5819fa1/packages/kit/src/loader/config.ts#L3
and `c12` is upgrade to `^0.2.0` , support individual config layers for extending.
https://github.com/unjs/c12/blob/8808f3793875cf862326163196087cc68c75dae3/src/loader.ts#L99-L125
``` ts
 const baseLayers = [
    opts.overrides && { config: opts.overrides, configFile: undefined, cwd: undefined },
    { config, configFile: opts.configFile, cwd: opts.cwd },
    opts.rcFile && { config: configRC, configFile: opts.rcFile }
  ].filter(l => l && l.config)

  // Allow extending
  if (opts.extend) {
    await extendConfig(r.config, opts)
    r.layers = [
      ...baseLayers,
      ...r.config._layers
    ]
    delete r.config._layers
    r.config = defu(
      r.config,
      ...r.layers.map(e => e.config)
    ) as T
  }

  // Apply defaults
  if (opts.defaults) {
    r.config = defu(r.config, opts.defaults) as T
  }

  // Return resolved config
  return r
```
`baseLayers` includes `config` and then `defu` `config` to `r.config`...I think the problem might be here.. 

-------
anyway.. It will makes module load twice..

**Comment by pi0** [comment]
Thanks for the detailed issue @higuaifan. This issue should be resolved by https://github.com/unjs/c12/commit/367cbf876bad7c389a462409c1cb1481c7b61804. Can you please try upgrading using `npn nuxi upgrade --force`?
