### ISSUE TITLE
Nuxt 3 postcss 8 support

### ISSUE THREAD

**Issue by ieshan** [nuxt/framework#3805]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27460489.53fbca7`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `css`, `buildModules`, `build`, `srcDir`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/postcss8@1.1.3`
------------------------------

### Reproduction

Followed both [approach 1](https://tailwindcss.com/docs/guides/nuxtjs) and [approach 2](https://stackoverflow.com/questions/70302520/nuxtjs-v3-and-tailwindcss-v3-postcss8-not-compatible) to use tailwind with nuxt 3, getting this error

```
Cannot start nuxt:  postcss@8 is not compatible with current version of nuxt (0.0.0). Expected: >=2.15.3 
```

### Describe the bug

It seems like nuxt 3 doesn't support postcss 8, I am trying to use tailwind with nuxt 3 and having this issue.

**Comment by florian-lefebvre** [comment]
I think nuxt3 has built-in postcss 8 support (`postcss` key in nuxt.config.ts).
If you want to see how to add Tailwind CSS without using the official module, have a look at my site: https://github.com/florian-lefebvre/portfolio

**Comment by danielroe** [comment]
As @florian-lefebvre says, `nuxt/postcss8` module is for bringing postcss v8 support to Nuxt 2. Nuxt 3 has it built-in by default.
