### ISSUE TITLE
Route middleware dies at abortNavigation()

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#3808]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27460489.53fbca7`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `privateRuntimeConfig`, `app`, `nitro`, `components`, `srcDir`, `build`, `buildModules`, `modern`, `tailwindcss`, `meta`, `modules`, `colorMode`
- Runtime Modules:  `@nuxtjs/color-mode@3.0.2`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.2`
------------------------------

### Reproduction

no need

### Describe the bug

i have a middleware `@/middleware/is-admin.ts`
```ts
export default defineNuxtRouteMiddleware(async (to, from) => {
	const isAdmin = await useRequest<boolean>({ API: '/api/is-user-admin' });
	console.log(isAdmin);
	if (!isAdmin) {
		return abortNavigation('Access denied');
	}
});
```
When the abortNavigation function fires, the server dies completely with error:
![](https://i.imgur.com/c5knbEp.png)

in production mode:
![](https://i.imgur.com/BQ3mneT.png)
![](https://i.imgur.com/uxa8Doj.png)

**Comment by danielroe** [comment]
Would you provide a reproduction? We ask for that for a good reason. 🙏 

In this case, it seems like the contents of your `useRequest` function are relevant, given the logs.

**Comment by danielroe** [comment]
I'm only seeing the route navigation errors being logged in the console - which is the intended behaviour.

**Comment by mihail727** [comment]
@danielroe my project just diyng...
dev mode: ![](https://i.imgur.com/Ix28ohD.png)
production mode: ![](https://i.imgur.com/iQvBUCC.png)

**Comment by danielroe** [comment]
I agree the logging is messy, and would be in favour of tidying it up (for handled errors).

However, the errors you're experiencing are likely issues with your code rather than the default behaviour, which is why I asked for a reproduction. Are you getting them with the repro you linked above?

**Comment by mihail727** [comment]
> I agree the logging is messy, and would be in favour of tidying it up (for handled errors).
> 
> However, the errors you're experiencing are likely issues with your code rather than the default behaviour, which is why I asked for a reproduction. Are you getting them with the repro you linked above?

Now I've noticed this behavior:
- if you go to the protected page ("/") through NuxtLink, then everything is fine and everything is clear in the server console: ![](https://i.imgur.com/AXfcyZA.png)

- if directly through the address bar of the browser, then the project dies

**Comment by mihail727** [comment]
I guessed what my mistake was .... sorry for your wasted time
`@/middleware/is-admin.ts`
```ts
export default defineNuxtRouteMiddleware(async (to, from) => {
	let isAdmin = false;

	try {
		isAdmin = await useRequest<boolean>('/api/is-user-admin');
	} catch (error) {
		return abortNavigation('Доступ запрещен');
	}

	if (!isAdmin) {
		return navigateTo('/auth/login');
	}
});
```
If the server does not find the user by ID or the cookie value did not arrive at the server at all, then the project was dying

**Comment by mihail727** [comment]
I guessed what my mistake was .... sorry for your wasted time
`@/middleware/is-admin.ts`
```ts
export default defineNuxtRouteMiddleware(async (to, from) => {
	let isAdmin = false;

	try {
		isAdmin = await useRequest<boolean>('/api/is-user-admin');
	} catch (error) {
		return navigateTo('/auth/login');
	}

	if (!isAdmin) {
		return abortNavigation('Доступ запрещен');
	}
});
```
If the server does not find the user by ID or the cookie value did not arrive at the server at all, then the project was dying
