### ISSUE TITLE
Modules conflict @nuxtjs/device and @nuxtjs/color-mode

### ISSUE THREAD

**Issue by nicolaslima321** [nuxt/framework#3820]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27460489.53fbca7`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `buildModules`, `device`, `modules`, `vite`
- Runtime Modules:  `@nuxtjs/color-mode@3.0.2`
- Build Modules:    `unplugin-icons/nuxt`, `@nuxtjs/device@2.1.0`, `@nuxtjs/color-mode@3.0.2`, `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

use `'@nuxtjs/device'` and `'@nuxtjs/color-mode',` at the same time at **buildModules**, or even device in buildModules (As docs says) and color-mode in **modules** (`modules: ['@nuxtjs/color-mode'],`)

### Describe the bug

When these booth modules are enabled in the nuxt 3 project, you are not able to switch **$colorMode.preference** through Vue components.

### Additional context

this log error always appears when application start
![image](https://user-images.githubusercontent.com/23743072/159388542-eb5f3b85-5319-4adb-9d7c-d3d96388b987.png)

i tried to switch color mode as oriented by docs, https://color-mode.nuxtjs.org/#usage but no success
![image](https://user-images.githubusercontent.com/23743072/159388726-de0b6b41-e722-4539-84f9-6f14a61c7986.png)
note the **system** label does not changed to "dark"

**Comment by nicolaslima321** [comment]
I forget to complement, but when I removed `@nuxtjs/device` from **buildModules**, the preference state started to change/work

**Comment by nasirDoe** [comment]
@nicolaslima321 because `@nuxtjs/device` not supported for `nuxtjs v3`. you can check at https://modules.nuxtjs.org/?q=device&sortBy=asc
