### ISSUE TITLE
Nitro aliases cannot be imported in the Vue part of your app. [importing #config from service/index.ts]

### ISSUE THREAD

**Issue by Mini-ghost** [nuxt/framework#3832]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-27465767.70f067a`
- Package Manager:  `yarn@1.22.4`
- Builder:          `vite`
- User Config:      `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

`nuxt.config.ts`
```ts
import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  publicRuntimeConfig: {
    ENV_TEXT: process.env.ENV_TEXT
  }
})
```

`./service/index.ts`
```ts
import config from '#config'
export const useService = () => {
  // ...
  console.log(config.ENV_TEXT)
  // ...
}
```

// `./pages/index.vue`
```vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { useService } from '@/service'

onMounted(() => {
  console.log(useService)
})
</script>

<template>
  <div>

  </div>
</template>
```

### Describe the bug

I tried to use `import config from '#config'` in service according to the documentation but it doesn't work

**error log**
```text
 ERROR  下午8:47:18 [vite] Internal server error: Failed to resolve import "#config" from "service\index.ts". Does the file exist?
       20:47:18
  Plugin: vite:import-analysis
  File: D:/Alex/nuxt3-app/service/index.ts
  1  |  import config from "#config";
     |                      ^
  2  |  export const useService = () => {
  3  |    console.log(config.ENV_TEXT);
```

**document**
https://v3.nuxtjs.org/docs/usage/runtime-config#api-routes

### Logs

```shell
[plugin:vite:import-analysis] Failed to resolve import "#config" from "service\index.ts". Does the file exist?
D:/Alex/nuxt3-app/service/index.ts:1:0
1  |  import config from "#config";
   |                      ^
2  |  export const useService = () => {
3  |    console.log(config.ENV_TEXT);
```

**Comment by pi0** [comment]
You shouldn't import any code from `server/` directory or nitro into universal app. 

Instead create a composable in `composables` that returns service:

```js
export const useService = () => {
  const config = useRuntimeConfig()
  console.log(config.ENV_TEXT)
  // We can call nitro API using `$fetch`
}
```

**Comment by Mini-ghost** [comment]
@pi0 Thanks for your quick answer! But have any ways can get env variable from other folder?

**Comment by pi0** [comment]
`useRuntimeConfig()` returns same object as `#config` by nitro.

For adding env, we need to register them in nuxt config like this:

```js
export default defineNuxtConfig({
  publicRuntimeConfig: {
    ENV_TEXT: 'default value or empty string'
  }
})
```

In nitro and api routes:

```js
import config from '#config'

console.log(config.ENV_TEXT)
```

In comoposables:

```js
  const config = useRuntimeConfig()
  console.log(config.ENV_TEXT)
```

**Comment by Mini-ghost** [comment]
@pi0 `useRuntimeConfig ()` is work in comoposables, I can use this on my project very well, but when I tried to use `#config` at other folders, like `./api`, `.xxx` ...etc., these didn't work and give the same error alert


```bash
 ERROR  Nitro aliases cannot be imported in the Vue part of your app. [importing #config from api/index.ts]
```

**Comment by pi0** [comment]
Can you please try `server/api/index.ts`? (note that api is not a top-level directory)

**Comment by Mini-ghost** [comment]
Ohhh! Thank you very much for your patient answer 🎉
