### ISSUE TITLE
Listen hook not called again on hot reload

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/framework#3835]
### Environment

Nuxt project info:                                                                                                                                                                                       14:32:14

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.2`
- Nuxt Version:     `3.0.0-27404337.c9c0171`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `privateRuntimeConfig`, `buildModules`, `googleFonts`, `css`, `vite`, `ngrok`
- Runtime Modules:  `-`
- Build Modules:    `~/modules/google-fonts`, `~/modules/ngrok`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                                                         14:32:14

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

✨  Done in 2.68s.

### Reproduction

```ts
import ngrok from "ngrok";
import type { Ngrok } from "ngrok";
import { defineNuxtModule } from "@nuxt/kit";
import consola from "consola";

// https://github.com/bubenshchykov/ngrok
export type ModuleOptions = Partial<Ngrok.Options>;
declare module "@nuxt/schema" {
  interface NuxtConfig {
    [CONFIG_KEY]?: ModuleOptions;
  }
}
const CONFIG_KEY = "ngrok";

export default defineNuxtModule({
  meta: {
    // Usually  npm package name of your module
    name: "ngrok",
    // The key in `nuxt.config` that holds your module options
    configKey: CONFIG_KEY,
    // Compatibility constraints
    compatibility: {
      nuxt: "^3.0.0",
    },
  },
  // Default configuration options for your module
  defaults: {},
  hooks: {},
  async setup(moduleOptions, nuxt) {
    nuxt.hook("listen", async () => {
      consola.success("I am listening...");
    });

    // Disconnect ngrok connection when closing nuxt
    nuxt.hook("close", () => {
      consola.log("I have stopped listening");
    });
  },
});

```

### Describe the bug

In my ngrok module that I'm working on for Nuxt 3, I need to listen to the `listen` hook and then connect to ngrok.

When I save my file, I see that the server s restarted because I get the local and network URLs in my console, but the listen event is not fired. I close the ngrok connection on the `close` hook just as is done in the Nuxt 2 version of the ngrok module.

If you re-save the nuxt config file you'll see the disconnect/close happen and the listen hook never fired again.

**Comment by HarmNullix** [comment]
As far as I can see, ngrok does not work well yet with the new Nuxt.

If i do a `ngrok http 3000` it spins up, but it keeps connecting. I do not really know what goes wrong but it does not work as excepted..

**Comment by silverbackdan** [comment]
@HarmNullix I have a working module for Nuxt 3 if you're interested now:
https://github.com/nuxt-community/ngrok-module/issues/21#issuecomment-1119650186

**Comment by silverbackdan** [comment]
Although the issue I've raised there isn't having much attention, I feel it's the right place for it, unless we can work out a general issue that we can start another issue here for. This issue is closed and stale now so we should continue the conversation elsewhere.
