### ISSUE TITLE
"Failed to resolve component" on HMR

### ISSUE THREAD

**Issue by zSoulweaver** [nuxt/framework#3849]
### Environment

Nuxt CLI v3.0.0-27466220.7c0d2e1                                                                                                                                                  
RootDir: E:\Projects\screenshottr\component-error                                                                                                                                 
Nuxt project info:                                                                                                                                                                

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27466220.7c0d2e1`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Repo: https://github.com/zSoulweaver/nuxt-component-hmr-error
StackBlitz: https://stackblitz.com/edit/github-rzz8t3

Within the repo is a button component called `BaseButton`, when changing the information in the slot the component the browser dev console will spit out `Failed to resolve component: BaseButton` and fail to load the component properly. Upon full refresh of the browser the component loads fine. The same issue occurs when changing the props, the button has a `disabled` bool when changed will also produce the same error.

### Describe the bug

When changing any information in regards to a component upon HMR on the browser it will produce an error in the dev console and fail to render the component. This will also cause any other components on the page to error out and fail to render as well. In the repo above the `NuxtLink` component will also produce errors.

### Additional context

I did find that when I was reproducing it on stackblitz it was initially working fine, it only occurred after I upgraded the nuxt version. 

### Logs

```shell
[Vue warn]: Failed to resolve component: BaseButton
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Upload onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > key="/upload" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <App key=1 > 
  at <NuxtRoot>
```

**Comment by danielroe** [comment]
Possibly related to https://github.com/nuxt/framework/issues/3340.

**Comment by zSoulweaver** [comment]
Did some testing of some older nuxt versions, from what I can gather https://github.com/nuxt/framework/commit/87eb7d0d392e2fb1ed36cdb8f4c96c69720c2276 is where the issue pops up. Setting the components back to global in the config semi fixes it, but you will still see errors with nuxt components like `NuxtLink`. Obviously there is something else awry with the components, but I hope this helps somewhat.

**Comment by toniengelhardt** [comment]
Same here, a previous fix resolved https://github.com/nuxt/framework/issues/3340 for me in some places, but in others it is still showing up...

**Comment by henrycunh** [comment]
same here, every time HMR is prompted to work, some auto-imported components disappear leaving this error:
```
runtime-core.esm-bundler.js:38 [Vue warn]: Failed to resolve component: CommonTabs
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > key="/" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <Default > 
  at <AsyncComponentWrapper > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="layout" mode="out-in" > 
  at <Anonymous> 
  at <App key=1 > 
  at <NuxtRoot>
```
explicitly importing components works
