### ISSUE TITLE
importing from #app on a .ts file

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/framework#3863]
### Environment

Nuxt project info:                                                                                                                                                                                            03:28:18

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `srcDir`, `ssr`, `dev`, `alias`, `image`, `generate`, `head`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `loading`, `loadingIndicator`, `plugins`, `components`, `buildModules`, `modules`, `apollo`, `proxy`, `axios`, `vuetify`, `build`, `bridge`
- Runtime Modules:  `@nuxt/image@0.6.2`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/apollo@4.0.1-rc.5`, `@nuxtjs/proxy@2.1.0`, `nuxt-social-meta@1.0.0`
- Build Modules:    `@nuxtjs/router@1.7.0`, `nuxt-compress@5.0.0`, `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27467056.93c4dfe`
------------------------------

### Reproduction

Please check the screenshot thank you

### Describe the bug

<img width="816" alt="image" src="https://user-images.githubusercontent.com/3810177/159780440-0e1f6cc8-7fd9-4a52-bf86-4986134a2736.png">

I says Cannot find module '#app' or its corresponding type declarations.

But this is perfectly working and no error present if I use this on a js file instead of ts

May I request for a tsconfig?

### Additional context

current tsconfig.json
{
    "extends": "./.nuxt/tsconfig.json",
    "compilerOptions": {
        "target": "ES2018",
        "module": "ESNext",
        "moduleResolution": "node",
        "lib": ["ESNext", "ESNext.AsyncIterable", "DOM", "webworker"],
        "esModuleInterop": true,
        "allowJs": true,
        "sourceMap": true,
        "strict": true,
        "noEmit": true,
        "experimentalDecorators": true,
        "skipLibCheck": true,
        "baseUrl": "client",
        "types": [
            "unplugin-vue2-script-setup/types",
            "unplugin-vue2-script-setup/ref-macros",
            "@types/node",
            "@nuxt/types",
            "@nuxtjs/axios",
            "@nuxt/image"
        ]
    },
    "vueCompilerOptions": {
        "experimentalCompatMode": 2
    },
    "exclude": ["node_modules", ".nuxt", "dist"]
}

**Comment by danielroe** [comment]
You should remove most of what you've added to that tsconfig file. It's overriding the Nuxt defaults.

Particularly your `exclude` setting is removing the Nuxt IDE hints. If you do need to configure the generated `tsconfig`, you can do so in your `nuxt.config` via the `typescript.tsConfig` option.

**Comment by stephenjason89** [comment]
Thank you for the reply :)
