### ISSUE TITLE
Can't resolve worker_threads

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/framework#3864]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `srcDir`, `ssr`, `dev`, `alias`, `image`, `generate`, `head`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `loading`, `loadingIndicator`, `plugins`, `components`, `buildModules`, `modules`, `apollo`, `proxy`, `axios`, `vuetify`, `build`, `bridge`
- Runtime Modules:  `@nuxt/image@0.6.2`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/apollo@4.0.1-rc.5`, `@nuxtjs/proxy@2.1.0`, `nuxt-social-meta@1.0.0`
- Build Modules:    `@nuxtjs/router@1.7.0`, `nuxt-compress@5.0.0`, `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27467056.93c4dfe`
------------------------------

### Reproduction

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/3810177/159781460-c864b9c5-f7ed-4312-93af-f99ca68876ff.png">

### Describe the bug

I get a console warning regarding worker_threads

This warning is not present on nuxt 2.15 before migrating to nuxt-bridge

### Additional context

Currently, I think it is just a warning because everything is working as it should

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by stephenjason89** [comment]
I don't think a reproduction is needed anymore. I have found out that 

import { jsPDF } from 'jspdf'

then create a test method with 
<img width="293" alt="image" src="https://user-images.githubusercontent.com/3810177/162042079-6c6cb56e-22ed-43d7-babf-a0800b2a3a4a.png">

you'll see the error

Thank you

**Comment by danielroe** [comment]
Seems to work fine for me.

https://stackblitz.com/edit/github-kwlwgr

**Comment by danielroe** [comment]
Update: bridge _also_ working fine: https://stackblitz.com/edit/github-2db5vk?file=package.json

**Comment by stephenjason89** [comment]
Hello @danielroe bridge works fine.
jsPDF package when used with bridge causes this error. On regular nuxt 2.15, error doesnt exist.

**Comment by stephenjason89** [comment]
@danielroe Hello, here's a minimal reproduction https://github.com/stephenjason89/NUXTREPRODUCTION

Thank you so much for looking in to this.

**Comment by stephenjason89** [comment]
@danielroe Please also notice when page is rendered with SSR then before hydration, all vuetify styling is not present. When it hydrates then vuetify styling is applied.

It's not like this on regular nuxt 2.15

**Comment by stephenjason89** [comment]
Hello @danielroe since this issue is closed, should i open a new one? Can't find the option to reopen this.

Thank you

**Comment by danielroe** [comment]
@stephenjason89 Yes, thank you - please do create a new issue. But the reproduction should be more minimal than the one you've linked. Ideally with only the code necessary to reproduce the issue. (See https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction.)

**Comment by stephenjason89** [comment]
@danielroe Thank you will try to lessen it
