### ISSUE TITLE
Cookies not set when using useLazyAsyncData and $fetch

### ISSUE THREAD

**Issue by tiborpino** [nuxt/framework#3871]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27467464.a0c4d6e`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `modules`, `buildModules`, `dev`, `build`, `css`, `meta`, `app`, `publicRuntimeConfig`, `privateRuntimeConfig`
- Runtime Modules:  `@nuxtjs/sitemap@2.4.0`
- Build Modules:    `nuxt-purgecss@1.0.0`, `~/modules/pages`

### Reproduction

Cart.vue

```
const { data: cart } = await useLazyAsyncData('mini-cart', () =>
    $fetch('/api/cart', {
        headers: useRequestHeaders(['cookie']),
    })
)
```

api/cart.ts

`setCookie(res, 'X-Cart-Session-Id', data.data.session_id, options) // not set in browser`

But it works when using $fetch

Cart.vue

```
const cart = await $fetch('/api/cart', {
    headers: useRequestHeaders(['cookie']),
})
```

api/cart.ts

`setCookie(res, 'X-Cart-Session-Id', data.data.session_id, options) // set correctly in browser`

### Describe the bug

Cookies from server api not set in browser when usint useLazyAsyncData method

**Comment by danielroe** [comment]
See https://v3.nuxtjs.org/docs/usage/data-fetching#example-pass-on-cookies-from-server-side-api-calls-on-ssr-response

**Comment by tiborpino** [comment]
And what's the reason it works witch $fetch and it doesn't with built-in fetch functions?

**Comment by danielroe** [comment]
If I understand your question correctly: https://v3.nuxtjs.org/docs/usage/data-fetching/#isomorphic-fetch
