### ISSUE TITLE
Cannot read cookies on first entry in route middleware

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#3876]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27467464.a0c4d6e`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `css`, `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`

### Reproduction

https://stackblitz.com/edit/github-h9l1lm?view=preview (Middleware not working in stackblitz)

### Describe the bug

When a RouteMiddleware is set and you enter the application for the first time, the route is not a component and therefore its name is undefined, and cookies cannot be read at that time either.

### Logs

```shell
FROM:
{
    "path": "/",
    "params": {},
    "query": {},
    "hash": "",
    "fullPath": "/",
    "matched": [],
    "meta": {}
}

TOKEN: undefined

TO:
{
    "fullPath": "/dashboard",
    "path": "/dashboard",
    "query": {},
    "hash": "",
    "name": "dashboard",
    "params": {},
    "matched": [
        {
            "path": "/dashboard",
            "name": "dashboard",
            "meta": {
                "layout": "dashboard"
            },
            "props": {
                "default": false
            },
            "children": [],
            "instances": {
                "default": {}
            },
            "leaveGuards": {},
            "updateGuards": {},
            "enterCallbacks": {},
            "components": {
                "default": {}
            }
        }
    ],
    "meta": {
        "layout": "dashboard"
    },
    "href": "/dashboard"
}
```

**Comment by frbuceta** [comment]
I haven't been able to get nuxt to run the middleware on Stackblitz, you'll have to download it and run it locally

**Comment by Teranode** [comment]
I have an additional question to this.
What's the difference between using  the hook `pages:middleware:extend` and `addRouteMiddleware`?

**Comment by frbuceta** [comment]
@danielroe, can you think of what it could be?
