### ISSUE TITLE
nuxt-bridge  ERROR  only on WINDOWS OS - [worker] Cannot find module

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/framework#3883]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.17.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `srcDir`, `ssr`, `dev`, `alias`, `image`, `generate`, `head`, `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `css`, `loading`, `loadingIndicator`, `plugins`, `components`, `buildModules`, `modules`,
`apollo`, `proxy`, `axios`, `vuetify`, `build`, `bridge`
- Runtime Modules:  `@nuxt/image@0.6.2`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/apollo@4.0.1-rc.5`, `@nuxtjs/proxy@2.1.0`, `nuxt-social-meta@1.0.0`
- Build Modules:    `nuxt-storm@1.1.3`, `@nuxtjs/router@1.7.0`, `nuxt-compress@5.0.0`, `@nuxtjs/vuetify@1.12.3`, `@nuxt/bridge@3.0.0-27467056.93c4dfe`
------------------------------

### Reproduction

![image](https://user-images.githubusercontent.com/3810177/159923644-4113497d-3f0c-4af8-be93-8007655283a1.png)
![image](https://user-images.githubusercontent.com/3810177/159923719-478f8186-9829-4e39-a26f-6dd12f7b6579.png)
![image](https://user-images.githubusercontent.com/3810177/159923840-ba2e81aa-ac0a-4bff-84a1-a2b095bdcd9a.png)
![image](https://user-images.githubusercontent.com/3810177/159922855-798e3ed2-ff3f-4767-b51e-45ad0b031376.png)

### Describe the bug

I keep getting this error and it goes in an infinite loop of rebuilding the project.
This same project works without problem on my Macbook

### Additional context

The part where it says ERROR  Cannot start nuxt:  Plugin not found: C:\Users\stephenjasonwang\Development\foodat.ph\.nuxt\apollo-module.js

I can clearly see that the file is present in .nuxt\apollo-module.js

This is a working branch on my macbook running macos monterey

**Comment by danielroe** [comment]
Would you provide a minimal reproduction? 🙏 It's okay if it's just a GH repo, but it should be minimal.

**Comment by stephenjason89** [comment]
Here you go 
https://github.com/stephenjason89/nuxt-reproduction
I hope this helps
Deleted unnecessary files.

**Comment by stephenjason89** [comment]
Hello sir @danielroe is the reproduction okay? Let me know if you need something else.

Thank you
