### ISSUE TITLE
Dynamic component with auto imported components (component is)

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/framework#3885]
### Environment

Stackblitz

### Reproduction

https://stackblitz.com/edit/nuxt3-windicss-rktywp?file=components/Dynamic.vue

### Describe the bug

`<component :is` doesn't import components if they are not registered inside the dynamic component itself. From my recollection, this didn't occur in Nuxt2.

**Comment by danielroe** [comment]
You either need to set `components.global` to true, or you can specifically resolve components you need, e.g.:

```vue
<template>
  <component :is="computedComp" />
</template>

<script setup>
const computedComp = computed(() => thing ? resolveComponent('LazySomeComponent') : resolveComponent('SomeOtherComponent'))
</script>
```

See https://github.com/nuxt/framework/discussions/2883.

**Comment by danielroe** [comment]
Yes. It will generate async chunks which will be prefetched. So I would recommend instead using the `resolveComponent` approach above - note that you have to have a string in the call to resolveComponent; the name can't be fully dynamic.

Or you could set the `global` option just on a single components directory, e.g. `~/components/global`.

**Comment by danielroe** [comment]
The point is that it has to be a string so we can _know_ to import it at build time. If you want to handle it dynamically you will need to set that component directory as a global component (or indeed all of your components as globally registered).
