### ISSUE TITLE
500 Cannot read property 'switchRef' of undefined

### ISSUE THREAD

**Issue by jamaluddinrumi** [nuxt/framework#3887]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27468803.23e7afb`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.2`, `@vueuse/nuxt@7.7.1`, `@nuxtjs/partytown@1.1.0`, `@unlighthouse/nuxt@0.3.7`

### Reproduction

https://github.com/jamaluddinrumi/jamal.indomascot.com

### Describe the bug

it works on local, but not in live

https://preeminent-starship-5e80e0.netlify.app/

**Comment by jamaluddinrumi** [comment]
it works by moving it from netlify to cloudflare workers

**Comment by danielroe** [comment]
Are you still experiencing this?

**Comment by jamaluddinrumi** [comment]
hi @danielroe 
it's already works on netlify too after updating nuxt3 to the latest version `3.0.0-27500677.83d27bd`

here's the link https://inquisitive-pavlova-c15087.netlify.app/ 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27500677.83d27bd`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`, `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.2`, `@vueuse/nuxt@7.7.1`, `@nuxtjs/partytown@1.1.0`
------------------------------
