### ISSUE TITLE
Nuxi generate doesn't generate any styling

### ISSUE THREAD

**Issue by Kagigz** [nuxt/framework#3889]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `pnpm@6.24.2`
- Builder:          `vite`
- User Config:      `buildModules`, `css`, `target`, `components`, `bridge`, `googleAnalytics`, `router`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.2.5`, `@vueuse/core/nuxt@6.9.2`, `@nuxt/bridge-edge@3.0.0-27468803.23e7afb`, `@nuxtclub/feathericons@1.0.0`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/google-analytics@2.4.0`

### Reproduction

Link a minimal repro repo: https://github.com/Kagigz/nuxt-frontend-repro

How to reproduce:
run pnpm i
run pnpm dev: the app works locally

run npx nuxi generate
run nuxi preview: the app doesn't render any css. Also, not featured in this repo, but on my actual app the other pages won't load.

### Describe the bug

The generated static files don't include any styling.

**Comment by danielroe** [comment]
let's follow in https://github.com/nuxt/framework/issues/1207.
