### ISSUE TITLE
Issue with NuxtLink and catch-all route on root

### ISSUE THREAD

**Issue by toooni** [nuxt/framework#3893]
### Environment

It's not tied to this environment. See reproduction link
```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27465767.70f067a`
- Package Manager:  `npm@8.3.0`
- Builder:          `vite`
- User Config:      `meta`, `css`, `buildModules`, `build`, `privateRuntimeConfig`, `publicRuntimeConfig`, `serverMiddleware`, `hooks`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/eslint-module@3.0.2`, `8n-routing`, `~/modules/image`, `@pinia/nuxt@0.1.8`
------------------------------
```

### Reproduction

https://github-qknbvu--3000.local.webcontainer.io/test

Setup: https://stackblitz.com/edit/github-qknbvu?file=pages/test.vue

### Describe the bug

I am using a `pages/[...slug].vue` catch-all route (root) and am trying to create a `NuxtLink` link which leads to home (with an empty `slug` param). The link does work (internally) but when the user tries to right-click and "open in new tab" the current url will be used insted of `/` (home).

The generated href from NuxtLink is empty like this: `<a href="" class="">link</a>` 
But it should result in this `<a href="/" class="">link</a>`

**Comment by danielroe** [comment]
Would you raise this upstream at https://github.com/vuejs/router? This is the default RouterLink behaviour.

**Comment by thierrymarianne** [comment]
Hello dear maintainers 👋🏼,

I encountered some difficulties when following the [Dynamic Routes example documentation](https://v3.nuxtjs.org/docs/directory-structure/pages#example).  

After reading your above comment, I figured using [Vue Router syntax](https://router.vuejs.org/guide/essentials/route-matching-syntax.html) would work for the use case I had:

```
# Catch-all for `/pages/${something}`
├── index.vue
└── pages
    └── *.vue
``` 

```
# Named param when accessing `/${paramName}`
└── :namedParam.vue
``` 

Other than that the bridge worked extraordinarily for me 💯   
(I had to migrate a tiny app from `nuxt-2` to `nuxt-3` and it went very smoothly).

Thank you!

**Comment by toooni** [comment]
@danielroe I don't get it. I tried to create a reproduction only with vue3. The link does still have an empty href attribute but does work as intended when using right click/open in new tab: https://stackblitz.com/edit/vue3-vue-fallback-route-demo

The parsed html seems to be the same. The behaviour with nuxt seems to be different than only with vue3/vue-router.

**Comment by danielroe** [comment]
This should now be resolved in the latest `vue-router` release (with https://github.com/vuejs/router/commit/2f1e9b976d7c5c1ada38c57f276304688d31b7e4). You can upgrade with `yarn upgrade nuxt` or `npm upgrade nuxt` to benefit from it.
