### ISSUE TITLE
Upgrade required

### ISSUE THREAD

**Issue by Dragonlord1005** [nuxt/framework#3912]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27470397.9ebea90`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/Dragonlord1005/nuxt-boi

Run yarn dev on replit

### Describe the bug

When running yarn dev, I go to the local site, and it says Upgrade Required

### Additional context

Running on replit

**Comment by Dragonlord1005** [comment]
Just setup on bridge, seems to be an issue directly related to vite, but running it on a separate repo using vite, the issue doesn't occur

**Comment by danielroe** [comment]
Hm. See https://github.com/vitejs/vite/issues/5770. Could you try removing `node_modules` and reinstalling?

**Comment by Dragonlord1005** [comment]
seems to be a replit issue, ran it on my home computer and it booted just fine, might have something to do with how replit forwards localhost a new URL, I am going to close this for now, and if I find a solution, I will leave a comment

**Comment by Dragonlord1005** [comment]
Just found the solution, by adding the --port flag and setting it to 443, it works properly
