### ISSUE TITLE
API returning empty Set() when fetching to page

### ISSUE THREAD

**Issue by rashidmya** [nuxt/framework#3918]
### Environment
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27468761.cd8dbdc`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction
**/server/api/whatever.ts**
```js
import type { IncomingMessage, ServerResponse } from "http";

export default async (req: IncomingMessage, res: ServerResponse) => {
  const tags = new Set(['im','so','sleepy']);

  return {
      tags
  }
};
```

**/pages/whatever.vue**
```vue
<script setup>
const { data } = await useAsyncData('tags', () => $fetch('/api/tags/all'))
</script>

```
------------------------------

### Describe the bug

getting an empty set when fetching `tags` to page

**Comment by Diizzayy** [comment]
@rashidmya This behavior isn't a bug, The result is returning an empty object because data stored within a set aren't stored as properties.

A workaround would be to express your set as an array as seen below:
```ts
import type { IncomingMessage, ServerResponse } from 'http'

export default async (req: IncomingMessage, res: ServerResponse) => {
  const tags = new Set(['im', 'so', 'sleepy'])

  return {
    tags: [...tags]
  }
}
```

**Comment by danielroe** [comment]
Agreed. You could raise an issue on https://github.com/unjs/h3/ but I'm inclined against it. Allowing direct return of Set cast to an array won't resolve the issue of a Set within an object returned directly, which will still be serialized as `{}`.
