### ISSUE TITLE
tried to access @nuxt/kit

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#3926]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `latest`
- Package Manager:  `yarn@3.2.0`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/productdevbook/productdevbook.com/tree/151ba71f54d0c794a9c559acbe253a1de10e25a6

### Describe the bug

![image](https://user-images.githubusercontent.com/38668796/160296459-7cb20fd1-22f9-4f3f-9201-c124b4d37a94.png)

### Additional context

yarn install
yarn dev and problem see

**Comment by CiiDyR** [comment]
Running into the same issue
