### ISSUE TITLE
first install nuxt but vite new dependencies found: ufo, vue ... 

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#3927]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27470397.9ebea90`
- Package Manager:  `yarn@3.2.0`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/productdevbook/productdevbook.com/tree/7a8ddac0ab22492f5086a8b620284f1d05a29a06

### Describe the bug

![image](https://user-images.githubusercontent.com/38668796/160296670-f0426520-c377-411c-8320-48c9677f4dd5.png)

### Additional context

![image](https://user-images.githubusercontent.com/38668796/160296677-495ca06c-aded-4bcb-bd0b-abffc13e8c96.png)

iam custom add and fixed.

**Comment by danielroe** [comment]
A fresh install doesn't print the message for me. Let me know if you can still reproduce.
