### ISSUE TITLE
modulepreload does not use CDN url

### ISSUE THREAD

**Issue by pierres** [nuxt/framework#3932]
### Environment

- Operating System: `Linux`
- Node Version:     `v17.8.0`
- Nuxt Version:     `3.0.0-27470397.9ebea90`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `vue`, `vite`, `css`, `app`, `publicRuntimeConfig`, `build`, `buildModules`, `modern`, `hooks`, `meta`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`

### Reproduction

* Define a CDN url via e.g. NUXT_APP_CDN_URL
* Run `server/index.mjs` in production mode
* Look for `<link "modulepreload"...>` There should be redundant entries: One with just a path and one with the correct CDN url
* Note: The incorrect tags are injected on client side; SSR renders the correct urls

### Describe the bug

If a CDN url is defined, `<link>` tags with `modulepreload` will be injected into `<head>` that wont have the CDN url prefixed. This happens on the client resulting in duplicated link tags: with and without  CDN url. The actual import uses the correct url though.

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

I can't reproduce this out of the box.

**Comment by yoruponder** [comment]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/9858714/163798666-9cb37ac9-ad79-4945-99e1-4ab94dadc3b4.png">

`<link rel="modulepreload" as="script" crossorigin="" href="/_nuxt/detail-be2e289a.mjs">`

hi danielroe, I have the same problem, this line is dynamic generation by entry-c2ef0d47.mjs, also with the keyword `modulepreload` are dynamic generation by entry-c2ef0d47.mjs  @danielroe

**Comment by danielroe** [comment]
Would you provide a reproduction please?

**Comment by pierres** [comment]
@danielroe How would we best provide a reproducible sample? This probably needs a more complex example e.g. a proxy which listens on cdn.localhost and proxies to the node server.

**Comment by danielroe** [comment]
you can just provide the code and I set up the environment, but this is what I use to test cdn:

```bash
npx server .output/public --cors
npx ngrok http 5000 --host-header=rewrite
NUXT_APP_CDN_URL=http://<id>.ngrok.io node .output/server/index.mjs
```

**Comment by pierres** [comment]
This issues has been fixed with RC-3. Thanks a lot!

**Comment by ErickLuis00** [comment]
Anyone else experiencing this in version 3.0.0-rc.8?

**Comment by danielroe** [comment]
@ErickLuis00 Would you open a new issue with a reproduction?
