### ISSUE TITLE
dont server res add custom headers  add netlify

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#3947]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27474482.90415d4`
- Package Manager:  `yarn@3.2.0`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/productdevbook/productdevbook.com

### Describe the bug

iam custom res headers add but dont return getheaders

https://productdevbook.com/api/graphql and click apollo

https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fproductdevbook.com%2Fapi%2Fgraphql

![image](https://user-images.githubusercontent.com/38668796/160535614-9f971f73-2db8-4ba8-921a-1e87b1f7d65b.png)

### Logs

```shell
Mar 29, 07:52:14 AM: 45bdb4e9 Duration: 1.83 ms	Memory Usage: 84 MB	Mar 29, 07:52:23 AM: 97424a16 INFO   https://studio.apollographql.com reqOrigin
Mar 29, 07:52:23 AM: 97424a16 INFO   https://studio.apollographql.com
Mar 29, 07:52:23 AM: 97424a16 INFO   https://studio.apollographql.com is allowed
Mar 29, 07:52:23 AM: 97424a16 INFO   {
  'access-control-allow-origin': 'https://studio.apollographql.com',
  'access-control-allow-credentials': 'true'
} res.getHeaders()
```

**Comment by danielroe** [comment]
The headers seem not to be set because you are getting back a 502 error. Investigate what is causing that first.

**Comment by productdevbook** [comment]
In localhost working https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fproductdevbook.com%2Fapi%2Fgraphql 

link is available, but these do not work after build and netlify pass.
There is nothing as the build side and release are related to nuxt.
