### ISSUE TITLE
Router plugin working not working on build

### ISSUE THREAD

**Issue by LessComplexity** [nuxt/framework#3948]
### Environment

My computer:
------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.17.1`
- Nuxt Version:     `3.0.0-27474482.90415d4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `router`, `env`, `server`, `build`, `css`, `buildModules`, `ignore`, `publicRuntimeConfig`, `vite`, `storybook`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@vueuse/nuxt@8.1.2`, `./modules/fonts/index.ts`
------------------------------

Server:
------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.1`
- Nuxt Version:     `3.0.0-27474482.90415d4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `router`, `env`, `server`, `build`, `css`, `buildModules`, `ignore`, `publicRuntimeConfig`, `vite`, `storybook`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@vueuse/nuxt@8.1.2`, `./modules/fonts/index.ts`
------------------------------

### Reproduction

In the plugin directory I've added a `router.ts`, also tried with `router.client.ts`, containing the following code:
```javascript
export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.$router.options.scrollBehavior = () => {
      	return { left: 0, top: 0 }
    }
});
```

Then building and starting the application doesn't scroll back up when routing to other pages, but if we run the application in dev mode (i.e. nuxi dev), then scrolling up works as defined.

### Describe the bug

We want to add a scrolling up feature when a user is routing to a new page using the plugins directory.
In development mode using `nuxi dev` this feature works.
In production mode using `nuxi build` followed by `node .output/server/index.mjs`, the router code seems to not run at all (I've tried to log from there but nothing happens).

**Comment by danielroe** [comment]
Would you try using `~/app/router.options.ts` instead? (See https://v3.nuxtjs.org/docs/directory-structure/pages#router-options.)

**Comment by danielroe** [comment]
I'm closing this in favour of using custom router options, but feel free to ping me if you think there's a bug here we need to investigate.
