### ISSUE TITLE
vue2App cannot read synchronously

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/framework#3950]
### Environment

see below reproduction

### Reproduction

https://codesandbox.io/s/nuxt-bug-report-n8j1hv?file=/plugins/ui.client.js

### Describe the bug

in plugin ,can't use `nuxtApp.vue2App`, i want get `Vue.prototype.$isServer` from this

**Comment by danielroe** [comment]
You won't be able to get that from `vue2App`. It is a compat adapter for Vue2 -> Vue3.

**Comment by baixiaoyu2997** [comment]
@danielroe  i know i should use this,but `element-ui` internal use `Vue.prototype.$isServer`
https://github.com/ElemeFE/element/blob/473ef53f9317ad6ca8c629655982244902751e63/packages/loading/src/directive.js#L10
i think i can manual setting something like  that `Vue.prototype.$isServer = process.server`, if this not bridge issue
