### ISSUE TITLE
Click on NuxtLink renders empty page with error: The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by tiborpino** [nuxt/framework#3953]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27470397.9ebea90`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `modules`, `buildModules`, `dev`, `build`, `css`, `meta`, `app`, `publicRuntimeConfig`, `privateRuntimeConfig`
- Runtime Modules:  `@nuxtjs/sitemap@2.4.0`
- Build Modules:    `nuxt-purgecss@1.0.0`, `~/modules/pages`

### Reproduction

Page pages/typo.vue

```
<template>
    <ContainerFluid>
        <article class="mt-10 mb-10">
            <h1>Headings</h1>
            <h1>H1 title</h1>
            <h2>H2 title</h2>
            <h3>H3 title</h3>
            <h4>H4 title</h4>
            <h5>H5 title</h5>
        </article>
    </ContainerFluid>
</template>
```

Link

```
<NuxtLink to="/typo">
     Typo
</NuxtLink>
```

### Describe the bug

Everytime I click on NuxtLink, Nuxt renders empty page. Node `<div id="__nuxt"></div>` is always empty.

Randomly there is en error in the console: 

`Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

**Comment by danielroe** [comment]
Do your pages and layouts all have a single root node? I would check what that `ContainerFluid` is rendering.

Without a reproduction I can't help any more, sadly.

**Comment by tiborpino** [comment]
I temporarily removed all layouts from layout/ folder. No change, still empty page. A edited typo.vue and moved content from <ContainerFluid> to to root element, also no change

typo.vue
`<template>Content from typo</template>`

app.vue

```
<template>
    <div>
        <NuxtLayout>
            <NuxtPage />
        </NuxtLayout>
    </div>
</template>
```

ContainerFluid.vue

```
<template>
    <div class="container-fluid">
        <slot />
    </div>
</template>
```

**Comment by danielroe** [comment]
As you see, you do not have a root element in your `typo.vue` file.

**Comment by tiborpino** [comment]
Still empty page

pages/type.vue

`<template>
    <div>Content from typo</div>
</template>`

**Comment by danielroe** [comment]
Would you please provide a reproduction?

**Comment by tsulatsitamim** [comment]
In my case nuxt3 doesn't render if I switch between page which use layout, but working fine switch between which use layout and note use layout.

temporary solution is importing layout as component instead of use as layout.

**Comment by danielroe** [comment]
It sounds like you do not have a single root node in your layout or page. Please provide a reproduction. 🙏

**Comment by tsulatsitamim** [comment]
I can confirm that I have multiple root in layout and page. wrapping into single root element in page solve the problem. thank you.

**Comment by tsulatsitamim** [comment]
I'm sorry, after testing multiple time, I still randomly get empty page (slot in layout not rendered). sometimes with error message in console sometimes not. I also wrap both layout and page into single root element. The error:

```Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.```

sorry still cannot create reproduction, try create new nuxt3 project and create simple route and page working fine.

**Comment by tiborpino** [comment]
> I can confirm that I have multiple root in layout and page. wrapping into single root element in page solve the problem. thank you.

Same for me
