### ISSUE TITLE
Hydration completed but contains mismatches

### ISSUE THREAD

**Issue by Pikoulol** [nuxt/framework#3971]
### Environment

npx nuxi info
Nuxt CLI v3.0.0-27477342.43007c6                                                                                                                                                                        16:55:07
RootDir: test\nuxt3-app                                                                                                                                       
Nuxt project info:                                                                                                                                                                                      
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27477342.43007c6`
- Package Manager:  `npm@8.5.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Create a default project then after setup things, run `npm run dev`

### Describe the bug

Chrome devtools indicates :
```
[Vue warn]: Hydration node mismatch:
- Client vnode: App 
- Server rendered DOM: <div>​…​</div>​  
  at <NuxtRoot>

in runtime-core.esm-bundler.js?v=a790cc28:38
```

This does not happen when I run `npm run build`  + `npm run start`, only in dev mode

### Additional context

I used to run `npx nuxi upgrade` everyday, something has been broken with the last few changes

**Comment by msonowal** [comment]
same here just todays recent changes broke

**Comment by danielroe** [comment]
This should be resolved with https://github.com/nuxt/ui/commit/c31c6996ab17b09cecdb91ab9c725146a2d9d0b7.

Let me know if you can still reproduce it with a new project (or after running `npx nuxi upgrade`).
