### ISSUE TITLE
Building as service worker doesn't work

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/framework#3976]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-27477794.df188d7`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

To reproduce the bug, 

1. Run `npx nuxi init nuxt3-app` to set up a new Nuxt app
2. change the file `nuxt.config.ts` to have the following content:
```ts
import { defineNuxtConfig } from 'nuxt3'
export default defineNuxtConfig({
    nitro: {
        preset: 'browser'
    },
})

```
3. Run `yarn build`
4. Copy the content of `.output/public` to a web server (Apache or any other. I tested with (i) AWS Cloudfront, (ii) localhost [XAMPP](https://www.apachefriends.org/download.html))  

### Describe the bug

The service worker throws TypeError and gets stacked in the initialization stage.

### Additional context

Detail of the error as reported from Chrome Dev Tools:
![image](https://user-images.githubusercontent.com/740025/160931593-ab46c070-fe11-4789-918c-0596f362096d.png)

**Comment by pi0** [comment]
This should have been fixed with [nitro migration](https://github.com/unjs/nitro). https://unjs.github.io/nitro-deploys/

Please upgrade dependencies and try again. If still broken would be glad to help and fix.
