### ISSUE TITLE
The vue propertie of vite is missing from the configuration

### ISSUE THREAD

**Issue by kecrily** [nuxt/framework#3987]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.1`
- Nuxt Version:     `3.0.0-27477996.646c2f6`
- Package Manager:  `pnpm@6.32.3`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

In nuxt.config.ts, add
```ts
vite: {
    vue: {
      reactivityTransform: true,
    },
}
```

### Describe the bug

The vue propertie of vite is missing from the configuration.

https://github.com/nuxt/framework/issues/2591#issuecomment-1005579830

### Logs

```shell
(property) reactivityTransform: boolean
Type '{ vue: { reactivityTransform: true; }; }' is not assignable to type 'InlineConfig | { configFile?: string | false; envFile?: false; root?: string; base?: string; publicDir?: string | false; cacheDir?: string; mode?: string; define?: Record<string, any> | { ...; }; ... 17 more ...; worker?: { ...; } | { ...; }; }'.
  Object literal may only specify known properties, and 'vue' does not exist in type 'InlineConfig | { configFile?: string | false; envFile?: false; root?: string; base?: string; publicDir?: string | false; cacheDir?: string; mode?: string; define?: Record<string, any> | { ...; }; ... 17 more ...; worker?: { ...; } | { ...; }; }'.ts(2322)
```

**Comment by danielroe** [comment]
We now have support via https://github.com/nuxt/framework/pull/3737 - configure instead via `experimental: { reactivityTransform: true }`
