### ISSUE TITLE
Migration of simple Nuxt project to Bridge - `npm run dev` error

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/framework#3993]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.1.2`
- Builder:          `webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`, `bridge`
- Runtime Modules:  `@nuxtjs/i18n@7.2.0`
- Build Modules:    `@nuxt/bridge@3.0.0-27478656.5b2ed85`

### Reproduction

[GitHub repo](https://github.com/DamianGlowala/nuxt-bridge-i18n-test)
(@danielroe, I have added you as a collaborator)

### Describe the bug

![image](https://user-images.githubusercontent.com/48835293/161037423-a68f2896-8382-4d30-9d6b-7503565ac1bc.png)

**Comment by danielroe** [comment]
Thanks for the repo! It looks like this is a Windows-only issue, as I can't reproduce on MacOS.

I think we can track in https://github.com/nuxt/framework/issues/3675.
