### ISSUE TITLE
Module / @Nuxt/kit cant resolve relative path, | __dirname | ERROR  Cannot access '_require' before initialization 

### ISSUE THREAD

**Issue by cpt-n3mo** [nuxt/framework#3994]
### Environment

npx: installed 2 in 3.387s
Nuxt CLI v3.0.0-27478712.3238038                                                         12:48:52
RootDir: /home/n3m0                                                                      12:48:52
Nuxt project info:                                                                       12:48:52

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.6.0
- Nuxt Version:     `3.0.0`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Create a module from starter kit
use `fs.readFileSync(path.join(__dirname,"../someDirectory/someFile"))` inside module

### Describe the bug

unable to get the local directory using __dirname
module build fails   

### Additional context

i have been working on a module, 
and i need to read in a file as a template, in nodejs i can do something like the following.

```
let template = fs.readFileSync(path.join(__dirname, `/../templates/template.js`))
```
but inside a module this does not seem to work,
this fails the build process with the below error.
im unsure if this is a bug or if im doing something wrong .. "am i not allowed to use __dirname..?"

### Logs

```javascript
let template = fs.readFileSync(path.join(__dirname, `/../templates/template.js`))

```
```
 ERROR  Cannot access '_require' before initialization                                   

  at NuxtCMS/dist/module.mjs:10:46
  at jiti (node_modules/jiti/dist/jiti.js:1:196506)
  at src/build.ts:45:76
  at async rollup:done (src/build.ts:44:26)
  at async rollupBuild (node_modules/unbuild/dist/chunks/build.mjs:470:3)
  at async build (node_modules/unbuild/dist/chunks/build.mjs:730:3)
  at async buildModule (src/build.ts:16:3)
  at async main (src/cli.ts:11:3)
```

this is module.mjs

```javascript
// -- Unbuild CommonJS Shims --
import __cjs_url__ from 'url';
import __cjs_path__ from 'path';
import __cjs_mod__ from 'module';
const __filename = __cjs_url__.fileURLToPath(import.meta.url); <<<< line 10
const __dirname = __cjs_path__.dirname(__filename);
const require = __cjs_mod__.createRequire(import.meta.url);

```

**Comment by danielroe** [comment]
Yes, you should avoid cjs dependencies like __dirname. See http://v3.nuxtjs.org/concepts/esm for more, and ideally use the example in the module starter: https://github.com/nuxt/starter/blob/module/src/module.ts#L19

**Comment by cpt-n3mo** [comment]
I see.. perfect thx!

That seems to work like a charm!!  not really sure how to know something is cjs or mjs, but ill have to dig into that for abit   
what is the reason for  `nuxt.options.build.transpile.push(runtimeDir) `
as it seems to build and run fine without this line..
also i see this in allot places `import.meta.url`
is there any docs on this..? as in what does it do..

kind regards..

**Comment by danielroe** [comment]
Here's some information about `import.meta.url`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta

Transpiling isn't always required.

**Comment by cpt-n3mo** [comment]
Ah perfect ill take a look !

and i noticed something Interesting..
this drove me abit crazy but when i changed my `js` fiels to `mjs` files, i noticed that even when you have `// __dirname` commented out in your file the build still fails as it does not seem to notice that its commented out! im not sure if this is common behavior but this is good to know. as in `module.mjs`  `__dirname`  got declared but the value was never used.

regards!

**Comment by productdevbook** [comment]
@danielroe how to server in import.meta.url used ? -> https://github.com/nuxt/framework/discussions/4252
