### ISSUE TITLE
Nuxt Config - Auto Imports seem to be broken

### ISSUE THREAD

**Issue by joel-wenzel** [nuxt/framework#4004]
### Environment

Nuxt CLI v3.0.0-27479058.e4956c5
RootDir: C:\code\Tempest\tempest-vue3
Nuxt project info: 

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27479058.e4956c5`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-2di6ew-oskeeq?file=nuxt.config.ts

```
[worker] gql is not defined                                                                                                    14:53:22

  at setup (.nuxt/dist/server/server.mjs:2954:19)
  at _sfc_main.setup (.nuxt/dist/server/server.mjs:2982:23)
  at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
  at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6977:29)
  at setupComponent (node_modules/@
```

### Describe the bug

Auto imports defined explicitly in `nuxt.config` seem to be broken in the latest release. I can at least confirm it was working in version `3.0.0-27460489.53fbca7`.

In my nuxt config i have 
```typescript
...
autoImports: {
    imports: [
      {
        from: 'graphql-tag',
        name: 'gql',
      },
```

Upon running the app locally though it fails to start with the error: `gql is not defined`

I do see it added to `.nuxt/imports.d.ts` and `.nuxt/types/auto-imports.d.ts` however.

**Comment by danielroe** [comment]
let's follow in https://github.com/nuxt/framework/issues/3977
