### ISSUE TITLE
`useFetch` data return null with mismatching client/request options

### ISSUE THREAD

**Issue by misaon** [nuxt/framework#4017]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27480123.4c77c88`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

In clean Nuxt project:

```vue
<template>
  <div>
    <NuxtWelcome />
  </div>
</template>

<script lang="ts" setup>
const [{ data: organization }, { data: repos }] = await Promise.all([
  useFetch(`https://api.github.com/orgs/nuxt`),
  useFetch(`https://api.github.com/orgs/nuxt/repos`)
])

console.log(organization.value) // null

const { data: organization } = await useFetch(`https://api.github.com/orgs/nuxt`)
console.log(organization.value) // null
</script>
```

### Describe the bug

useFetch started returning null to the "data" property

**Comment by danielroe** [comment]
You are redeclaring `organization`. Once fixed, I can't replicate this. Would you provide a reproduction if that doesn't fix it for you? 🙏

**Comment by misaon** [comment]
@danielroe Try this:

```
<template>
  <pre>
    {{ xxx }}
  </pre>
  <pre>
    {{ yyy }}
  </pre>
</template>

<script lang="ts" setup>
const [{ data: xxx }, { data: yyy }] = await Promise.all([
  useFetch(`https://jsonplaceholder.typicode.com/todos/1`),
  useFetch(`https://api.github.com/orgs/nuxt/repos`)
])

console.log(xxx.value) // { userId: 1, id: 1, title: 'delectus aut autem', completed: false }
console.log(yyy.value) // null
</script>
```

**Comment by danielroe** [comment]
Also works fine for me. Are you sure you aren't rate limited by GitHub or something?

**Comment by misaon** [comment]
@danielroe 

I've spent time testing the problem now. I am developing a locally based self-hosted certificate. If I use the url address on our production API for `useFetch`, everything works fine. If I give the local URL, it returns null. Also interesting is that `$fetch`, returns **completely correct data** and `useFetch` returns null. therefore, `useFetch` must have extra logic that returns null instead of data in some cases.

```
  const { data: countries } = await useFetch(`https://shop.localhost/api/v2/shop/countries?page=1&itemsPerPage=30`)
  const countries2 = await $fetch(`https://shop.localhost/api/v2/shop/countries?page=1&itemsPerPage=30`)

  console.log(countries.value)    // null
  console.log(countries2)         // correct data
```

**Comment by danielroe** [comment]
You can see the source here: https://github.com/nuxt/framework/blob/323803832a87b7bf2783210e1769f2f7f39a3d5b/packages/nuxt3/src/app/composables/fetch.ts#L53-L57.

Are you calling useFetch on the same URL elsewhere but not awaiting it?

**Comment by misaon** [comment]
Good point

**Comment by misaon** [comment]
@danielroe i debug asyncData.ts file flow and this part:
https://github.com/nuxt/framework/blob/323803832a87b7bf2783210e1769f2f7f39a3d5b/packages/nuxt3/src/app/composables/asyncData.ts#L140-L150
is not processed on my side... every usefetch falls to watch and onUnmount only.

**Comment by danielroe** [comment]
The best approach is for you to create a minimal reproduction running in stackblitz so I can actually investigate.

**Comment by misaon** [comment]
unfortunately I can't reproduce our code. This is a large project built on the Sylius API and we are under copyright and we must not share. I know that without reproduction, it's only difficult if you can't think of what it could be. At least point in the direction so I can detect a potential bug. Thanks again for the help.

**Comment by misaon** [comment]
thanks @danielroe and @pi0 
code:
```
<script lang="ts" setup>
import { useFetch } from '#app'

const [a, b] = await Promise.all([
  useFetch(`https://shop.localhost/api/v2/shop/countries?page=1&itemsPerPage=30`),
  useFetch(`https://shop.localhost/api/v2/shop/countries?page=1&itemsPerPage=10`),
])

console.log('A:', a.data.value, a.error.value)
console.log('B:', b.data.value, b.error.value)
</script>
```

console:
```
A: null true
B: null true
```

**Comment by danielroe** [comment]
Can you use onRequestError option to log the error?

**Comment by misaon** [comment]
More from underground

```vue
<script lang="ts" setup>
import { useFetch } from '#app'

// web-server for docker, '' for browser
const baseUrl = process.server ? 'http://web-server' : ''

const [a, b] = await Promise.all([
  useFetch(`${baseUrl}/api/v2/shop/countries?page=1&itemsPerPage=30`),
  useFetch(`${baseUrl}/api/v2/shop/countries?page=1&itemsPerPage=10`),
])

console.log('A:', a.data.value, a.error.value)
console.log('B:', b.data.value, b.error.value)
</script>
```

console:
```
A: null null
B: null null
```

Nuxt app console:
```
 A: {
   '@context': '/api/v2/contexts/Country',
   '@id': '/api/v2/shop/countries',
   '@type': 'hydra:Collection',
   'hydra:member': [
     {
       '@id': '/api/v2/shop/countries/CZ',
       '@type': 'Country',
       code: 'CZ',
       provinces: [],
       name: 'Česko'
     }
   ],
   'hydra:totalItems': 1,
   'hydra:view': {
     '@id': '/api/v2/shop/countries?itemsPerPage=30',
     '@type': 'hydra:PartialCollectionView'
   }
 } null
 B: {
   '@context': '/api/v2/contexts/Country',
   '@id': '/api/v2/shop/countries',
   '@type': 'hydra:Collection',
   'hydra:member': [
     {
       '@id': '/api/v2/shop/countries/CZ',
       '@type': 'Country',
       code: 'CZ',
       provinces: [],
       name: 'Česko'
     }
   ],
   'hydra:totalItems': 1,
   'hydra:view': {
     '@id': '/api/v2/shop/countries?itemsPerPage=10',
     '@type': 'hydra:PartialCollectionView'
   }
 } null

```

**Comment by danielroe** [comment]
Any chance the URL isn't resolving within your docket container, but is within your machine browser?

**Comment by misaon** [comment]
@danielroe this works fine.
in server logs everything looks fine (correct data from console.log). but in Browser is null

**Comment by danielroe** [comment]
Ah. I've just seen what you're doing with baseURL. The key is based on the URL so by changing the URL between server and client, there is a mismatch.

In your case, you could use useAsyncData and pick a key manually.

**Comment by misaon** [comment]
Yes, youre right! Thanks a lot! Any idea to solve it, like a human? 😄

**Comment by pi0** [comment]
For giving manual key and baseURL to useFetch:

```js
await useFetch(`${baseUrl}/api/v2/...`, { baseURL, key: 'countries-api })
```

This will make keys same.

----

Interesting find @danielroe!

I would still assume it is a bug that the client-side is returning `null` instead of re-attempt to fetch! 

It is not safe to remove `baseURL` or any other option from auto key generation. Two instances of `useFetch` with different baseURL will conflict this way.

Thinking about some possible improvements. Supporting proxy for me seems best approach. In the meantime, we should improve documentation and warn about this that if URL or options between client/server are not same, `useFetch` needs explicit key or will need to refetch (currently mismatch)

**Comment by tntsoft** [comment]
For me, useFetch doesn't call the backend at all sometimes.

What I'm doing is:
- I send a Login request to the backend (Laravel Sanctum), get authenticated, get the CSRF token in the header, I then redirect to the homepage
- On the homepage I'm attempting to list users - so I fetch them from the backend
- At first it works, everything appears, but if I refresh the tab, the useFetch request does not fire (does not appear on the Network tab whatsoever) thus returning null and causing random errors inside Vue3. 

Might it be the same issue as described here, or should I maybe open a new issue?

Or maybe there's something I'm missing? Does UseFetch cache or something?

**Comment by danielroe** [comment]
`useFetch` fires on the server, so you won't see the result in your Network tab. And likely the issue is that _that_ request doesn't have a correct CSRF token or other header.... See https://v3.nuxtjs.org/guide/features/data-fetching/#isomorphic-fetch-and-fetch for more info, and raise a discussion if you have any questions.

**Comment by tntsoft** [comment]
@danielroe This makes sense, but in my case, it definitely is not firing at all, not even server side as I've implemented and checked Logs on the server end.

```
async function callBackend(url) {
    const config = useRuntimeConfig();

    if(process.browser)
    {
      let {error, data, refresh} = await useFetch(url, {
        baseURL: config.BASE_URL,
        credentials: 'include',
        headers: {
          Accept: 'application/json',
          'X-XSRF-TOKEN': useCookie('XSRF-TOKEN').value,
        },
      });

      if (error.value && error.value.response.status === 401) {
        useAuth().logout();
      }

      return [data, refresh];
    }
    else
    {
      let {error, data, refresh} = await useFetch(url, {
        baseURL: config.BASE_URL,
        credentials: 'include',
        headers: useRequestHeaders(['X-XSRF-TOKEN', 'Accept', 'laravel_session', 'XSRF-TOKEN', 'cookie'])
      });

      if (error.value && error.value.response.status === 401) {
        useAuth().logout();
      }

      return [data, refresh];
    }
  } 
```

This is the function that I'm calling - the Browser part is running perfectly, whilst the SSR is not firing at all.

**Comment by danielroe** [comment]
@tntsoft Would you create a new issue with a reproduction? (This is not related to this issue.)

**Comment by tntsoft** [comment]
@danielroe Thanks a lot! I've opened #4486 and have made a public repository in order to reproduce this issue. 

Please reach out to me if you need anything, I'm happy to help in any way I can in order to resolve this. Nuxt 3 is looking great, I appreciate you, the team, and your hard work!
