### ISSUE TITLE
useCookie sets path different from root

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#4018]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27480156.02d2d1a`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `css`, `buildModules`, `vite`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`

### Reproduction

There's no need.

![Captura de pantalla de 2022-04-01 13-03-28](https://user-images.githubusercontent.com/13822438/161251648-37e8f333-42fe-400c-b870-1ab7ce74bb8a.png)

![Captura de pantalla de 2022-04-01 13-04-34](https://user-images.githubusercontent.com/13822438/161251689-2897fb70-2397-4ce1-9717-3800be249b31.png)

### Describe the bug

When useCookie is used in a nested page (for example `/auth/sign-in`) and a value is set... The cookie is saved with the path `/auth`.

Also useCookie cannot be told to use the `/` path.

This can cause issue #3876.

**Comment by danielroe** [comment]
When you say it 'cannot be told to use the / path' have you tried:

```js
const testCookie = useCookie('test', {
  path: '/',
});
```

**Comment by frbuceta** [comment]
> When you say it 'cannot be told to use the / path' have you tried:
> 
> ```js
> const testCookie = useCookie('test', {
>   path: '/',
> });
> ```

Sorry, in my ide I didn't autocomplete and I thought I couldn't pass it on. I close the issues. My problem has been fixed.

Thank you very much for the help and sorry for the confusion
