### ISSUE TITLE
serve-placeholder configuration (for dev)

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#403]
We're currently using `serve-placeholder` for the Nitro dev server since https://github.com/nuxt/framework/commit/0b886cf57ff2f55c693507d343c28e4979aa7b7d:

https://github.com/nuxt/framework/blob/858e31c7fce0167042e9ca2ca181dddf35878a90/packages/nitro/src/server/dev.ts#L71-L72

It would be good to allow configuration for this (or drop it?), given that we don't have this middleware in production and otherwise users' dev sites will behave differently than production.

**edit**: I note that this is only applied on `/_nuxt/` path so seems unlikely that it would be a significant problem.

cc: @pi0

**Comment by pi0** [comment]
Adding as a subtask to https://github.com/unjs/nitro/issues/94
