### ISSUE TITLE
Handling errors on nuxt3 usefetch

### ISSUE THREAD

**Issue by dokolenko24cm** [nuxt/framework#4031]
### Environment

This may not be a bug but I cannot examine errors on usefetch post request.
```
const { error, data } = useFetch('https://example.app/api/contact', {
   method: "POST",
   headers: { "Content-Type": "application/json" },
   body: {
      name: form.name.value,
      email: form.email.value,
      message: form.message.value
   }
});
console.log(error.value, error)
```
Via console I see that error returns ref that contains error._value.data.message, however I can't get to it in code it returns undefined or null all the time.

Any help with this? I tried then and catch version as well and for errors it doesnt catch them..

### Reproduction

Just a new app with index page and useFetch for request on button click

### Describe the bug

Can't handle errors..

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/2122
