### ISSUE TITLE
Error reporting using echarts-wordcloud

### ISSUE THREAD

**Issue by warmer1914** [nuxt/framework#4033]
### Environment

![image](https://user-images.githubusercontent.com/28683760/161362474-8b779ce4-371b-437f-bf3a-d9d896fa6dd4.png)

### Reproduction

![image](https://user-images.githubusercontent.com/28683760/161362519-444eaabc-08dd-423e-9676-7ab4ef738829.png)

### Describe the bug

![image](https://user-images.githubusercontent.com/28683760/161362158-9ea6a32a-8616-418d-862a-9d8f515f5bf4.png)
![image](https://user-images.githubusercontent.com/28683760/161362533-6c4869f2-c5d6-4a19-b01b-4e5052a159b9.png)

`import 'echarts-wordcloud/dist/echarts-wordcloud';
 import 'echarts-wordcloud/dist/echarts-wordcloud.min';`
 How can this plug-in method be referenced?

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏 

You could try loading it in a client-only plugin as it appears to need to be run in a browser context (e.g. `~/plugins/echarts.client.ts`).
