### ISSUE TITLE
HMR randomly fails to update

### ISSUE THREAD

**Issue by Luffyyy** [nuxt/framework#4038]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.0.0-27480376.fdd38f9`
- Package Manager:  `npm@8.0.0`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Happens on a clean install of nuxt via `npx nuxi init nuxt3-app && npm install`. The way I get it to trigger is just editing the app.vue file, like adding a number or something and *sometimes* it will ignore the change and the page will not reload in the browser.

### Describe the bug

HMR mostly works, however sometimes fails to update. I could only confirm this on Windows, could not make it happen in the browser with a sandbox (StackBlitz, I think CodeSandbox doesn't have it working at all)

### Additional context

No errors are given. Terminal just says "√ Vite server built in Xms", console in browser has no errors either.

**Comment by anburocky3** [comment]
I too face this problem. I mostly see this with `Tailwind 3`.

**Comment by zSoulweaver** [comment]
+1 for also having the same problem. Occurs with ordinary style tags for me, specifically with sass, but I'm pretty sure it occurs with vanilla too.

**Comment by frbuceta** [comment]
I also see this error a lot (it is solved by constantly restarting)

```
 ERROR  [proxy] socket hang up                                                                                                                                                                                               12:39:27

  at connResetException (node:internal/errors:691:14)
  at Socket.socketOnEnd (node:_http_client:471:23)
  at Socket.emit (node:events:402:35)
  at Socket.emit (node:domain:475:12)
  at endReadableNT (node:internal/streams/readable:1343:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by danielroe** [comment]
Would you let me know if [this solution](https://github.com/nuxt/framework/issues/2047#issuecomment-1091292440) solves things for you?

**Comment by Luffyyy** [comment]
> Would you let me know if [this solution](https://github.com/nuxt/framework/issues/2047#issuecomment-1091292440) solves things for you?

Works 👍

**Comment by danielroe** [comment]
Great. Then let's close this issue in favour of https://github.com/nuxt/framework/issues/2047.
