### ISSUE TITLE
useFetch fetching only once

### ISSUE THREAD

**Issue by MohammadKhalaji** [nuxt/framework#4053]
### Environment

Nuxt project info:                                                     

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27480376.fdd38f9`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

**This reproduction works as expected! But the exact same example on my machine (and after deploying to heroku) doesn't! The problem is described later.** 

https://stackblitz.com/edit/nuxt3-windicss-7mwkkj?file=package.json

### Describe the bug

1. Open the reproduction link
2. Open the network tab on devtools
3. Click on the button that says "Link To Some Page"
4. The data is fetched and shown, as expected
5. Click on the button that says "Back To Home"
6. Click on the button that says "Link To Some Page" Again
7. As seen in the network tab, the data is being fetched again, which is what I would expect

HOWEVER, the exact same minimal problem on my machine, shows a different output: 
In step 7, instead of re-fetching data, nothing is fetched, and the data that was fetched before is being shown. BUT, the value of pending is stuck to "True." Caching is disabled on my browser. What is going on?

**Comment by danielroe** [comment]
This is intentional: see https://github.com/nuxt/framework/pull/3985.

The discrepancy is that stackblitz is using an older version of Nuxt 3, before this change was implemented.

**Comment by MohammadKhalaji** [comment]
> This is intentional: see #3985.
> 
> The discrepancy is that stackblitz is using an older version of Nuxt 3, before this change was implemented.

Thanks!

What about the pending value getting stuck at true? Is that intentional as well?

**Comment by danielroe** [comment]
Nope! Missed that in your report, and looking now.
