### ISSUE TITLE
useAsyncData does not update data after first load

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#4061]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27484349.dda0ceb`
- Package Manager:  `npm@8.6.0`
- Builder:          `vite`
- User Config:      `css`, `buildModules`, `vite`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`

### Reproduction

https://stackblitz.com/edit/github-b51pph-pi4u8k

### Describe the bug

I have a main page with articles and when I click on an article it goes to another page that has a useAsyncData, the first time it loads but then I go to the main page and click on another article and it continues to show me the first one.

**Comment by danielroe** [comment]
This is intentional: see https://github.com/nuxt/framework/pull/3985.

**Comment by frbuceta** [comment]
Solved, thanks @danielroe
