### ISSUE TITLE
Template Refs inside v-for not working with Composition API

### ISSUE THREAD

**Issue by dikesh** [nuxt/framework#4080]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27484505.9f6eff7`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Sharing the SFC code.

```
<template>
  <div>
    <div v-for="i in 3" :key="i" class="content" ref="contentRef">
      Lorem ipsum dolor sit amet consectetur adipisicing elit.
    </div>
  </div>
</template>

<script setup>
const contentRef = ref([]);

onMounted(() => {
  console.log("On Mounted Ref:");
  console.log(JSON.stringify(contentRef.value.map((cr) => cr)));
});
</script>


<style scoped>
.content {
  display: table;
  padding: 30px;
  height: 60px;
  border-bottom: 1px solid grey;
}
</style>
```

### Describe the bug

I am trying to use Template Refs inside v-for loop. But the corresponding reference returns an empty array.

The same [example runs correctly](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxkaXYgdi1mb3I9XCJpIGluIDNcIiA6a2V5PVwiaVwiIGNsYXNzPVwiY29udGVudFwiIHJlZj1cImNvbnRlbnRSZWZcIj5cbiAgICAgIExvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0IGNvbnNlY3RldHVyIGFkaXBpc2ljaW5nIGVsaXQuXG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7cmVmLCBvbk1vdW50ZWR9IGZyb20gJ3Z1ZSdcbmNvbnN0IGNvbnRlbnRSZWYgPSByZWYoW10pO1xuXG5vbk1vdW50ZWQoKCkgPT4ge1xuICBjb25zb2xlLmxvZyhjb250ZW50UmVmLnZhbHVlLm1hcCgoY3IpID0+IGNyKSk7XG59KTtcbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmNvbnRlbnQge1xuICBkaXNwbGF5OiB0YWJsZTtcbiAgcGFkZGluZzogMzBweDtcbiAgaGVpZ2h0OiA2MHB4O1xuICBib3JkZXItYm90dG9tOiAxcHggc29saWQgZ3JleTtcbn1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSJ9) on Vue SFC Playground.

### Logs

```
On Mounted Ref:
[]
```

**Comment by danielroe** [comment]
This is a Vue SSR bug: see [reproduction without Nuxt](https://stackblitz.com/edit/github-6ovsn2?file=src%2FApp.vue&terminal=dev).

You can track at https://github.com/vuejs/core/issues/5525.

See also https://github.com/nuxt/framework/discussions/3661.

**Comment by ririen** [comment]
@danielroe latest `Vue` probably fixed this: https://github.com/vuejs/core/blob/main/CHANGELOG.md#3232-2022-04-12

**Comment by danielroe** [comment]
Any chance you could test with latest vue to see?

**Comment by ririen** [comment]
Updated reproduction in StackBlitz: https://stackblitz.com/edit/github-6ovsn2-9srfej

**I also check latest Nuxt after https://github.com/nuxt/framework/pull/3968 and also works! :tada: :partying_face:** 

**_A little note. Using `JSON.stringify` on reproduction returns empty objects instead of DOM tree elements._**

Before `3.2.32`:
![Zrzut ekranu z 2022-04-12 12-46-03](https://user-images.githubusercontent.com/18102267/162943656-7f060564-6502-4ad3-a666-a475efdcc312.png)

With `3.3.32`:

![Zrzut ekranu z 2022-04-12 12-47-39](https://user-images.githubusercontent.com/18102267/162943791-79095461-48b1-444f-97d5-3a7ca98c08d5.png)

**Comment by dikesh** [comment]
It is working as expected now with vue@3.2.32.
