### ISSUE TITLE
after update nuxt 3 i have error "write EPIPE"

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#4085]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27484505.9f6eff7`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `privateRuntimeConfig`, `app`, `nitro`, `router`, `components`, `srcDir`, `build`, `buildModules`, `modern`, `tailwindcss`, `meta`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.2`, `@vueuse/nuxt@8.2.4`
------------------------------

### Reproduction

-

### Describe the bug

i have a server route:

<details>
 <summary><code>@/server/api/data.ts</code></summary>

```ts
import { createApp, createRouter, useQuery, useBody } from 'h3';
import { itemService, userService } from '../services';

const app = createApp();
const router = createRouter();

app.use(router);

router.get('/users', async () => await userService.getUsers());

router.get('/items/:', async (req, res): Promise<IServerResponse<any>> => {
	const { type, id } = useQuery(req);

	try {
		if (type && id) {
			const item = await itemService.getItem(type.toString(), id.toString());

			return { success: true, response: item };
		} else if (type) {
			const items = await itemService.getItems(type.toString());

			return { success: true, response: items };
		} else {
			return { success: false, reason: 'Неверные параметры запроса' };
		}
	} catch (e) {
		return { success: false, reason: e.message };
	}
});

router.post('/items/:', async (req, _res) => {
	try {
		const { type, id } = useQuery(req) as { type: string; id: string };
		const payload = await useBody(req);

		if (type && id && payload) {
			const item = await itemService.setItem(type, id, payload);

			return { success: true, response: item };
		} else {
			return { success: false, reason: 'Неверные параметры запроса' };
		}
	} catch (e) {
		return { success: false, reason: e.message };
	}
});

export default app;
```
</details>

by using Postman i'm trying to get data from this API.... The data on the total passes, but an error appears in the console
![](https://camo.githubusercontent.com/5b6ea3decc56d9add7fecb75f97c21aa5bb58b85926a06bf6e803c5dfc715225/68747470733a2f2f692e696d6775722e636f6d2f5550494d6130442e706e67)

Postman request: `localhost:3000/api/data/items/?type=assortment`

### Additional context

-

### Logs

```shell
-
```

**Comment by pi0** [comment]
This issue is probably resolved with nitropack migration. Please upgrade to the latest using `npx nuxi upgrade --force` and ping to reopen if you can still spot this problem.
