### ISSUE TITLE
suspend route object until route suspense resolves

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#4086]
At the moment the route changes before the route component fully loads ([sandbox](https://stackblitz.com/edit/nuxt3-windicss-bm1znm?file=app.vue)).

We already provide our own `useRoute` composable. We can update our implementation so the `route` object returned continues to show the past route until the route component suspense resolves, so this kind of inconsistency is not present.

**Comment by Tahul** [comment]
Here is a reproduction of the same implementation in Nuxt 2:
https://stackblitz.com/edit/nuxt-starter-rusq6i?file=pages%2Findex.vue
