### ISSUE TITLE
Calling 404 api in middleware causes infinite loop

### ISSUE THREAD

**Issue by farnabaz** [nuxt/framework#4097]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27485997.c426f3e`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/node-4gdlnd?file=middleware%2Ftest.global.ts

Start the project and look at browser console, you can see infinite logs there

<img width="402" alt="Screen Shot 2022-04-05 at 4 29 52 PM" src="https://user-images.githubusercontent.com/2047945/161777187-ee8e9ad8-cbf4-4bba-a171-2fdea01d2369.png">

### Describe the bug

Calling an API inside middleware causes infinite loop when if the API return 404

**Comment by lukaszflorczak** [comment]
Shouldn't you just add `abortNavigation(err)` in the `catch`?

**Comment by farnabaz** [comment]
It never reaches to `catch` block @lukaszflorczak

**Comment by danielroe** [comment]
This [is no longer replicable](https://stackblitz.com/edit/node-ymmjrp) - let me know if you still experience it.
