### ISSUE TITLE
Migration error when running project

### ISSUE THREAD

**Issue by MakeSense1212** [nuxt/framework#4113]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.17.5`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@6.14.14`
- Builder:          `webpack`
- User Config:      `bridge`, `server`, `head`, `css`, `plugins`, `components`, `buildModules`, `eslint`, `modules`, `axios`, `build`, `i18n`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `nuxt-sweetalert2@1.0.0`, `cookie-universal-nuxt@2.1.5`, `nuxt-i18n@6.28.1`
- Build Modules:    `@nuxtjs/eslint-module@3.0.2`, `@nuxtjs/tailwindcss@5.0.2`

### Reproduction

**Package.json**
 "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "start": "nuxi preview",
    "generate": "nuxt generate",
    "lint:js": "eslint --ext \".js,.vue\" --ignore-path .gitignore .",
    "lint": "npm run lint:js",
    "lintfix": "npm run lint:js -- --fix"
  },

**nuxt.config.js**
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({

### Describe the bug

Hello everyone,

I tried to migrate from Nuxt 2 to Nut bridge using this tutorial : https://v3.nuxtjs.org/getting-started/bridge/#upgrade-nuxt-2

Upgrading nuxt to nuxt-edge works well, I can start the project after that.

But when I try to launch Nuxt Bridge (npm run dev) I got this error : 

Nuxt CLI v3.0.0-27486226.7a70644

  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.186:3000/
  > Network:  http://172.19.96.1:3000/
  > Network:  http://172.24.160.1:3000/
  > Network:  http://172.19.192.1:3000/

 ERROR  No "exports" main defined in D:\Users\maxen\Desktop\app-ruche\node_modules\@nuxt\kit\package.json

I did try to write `bridge: false` in nuxt.congif.js but it doesn't change anything
I don't know what to do as I followed the tutorial.

Thanks for your help !

### Logs

```shell
Nuxt CLI v3.0.0-27486226.7a70644                                                         08:57:33
                                                                                         08:57:33
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.186:3000/
  > Network:  http://172.19.96.1:3000/
  > Network:  http://172.24.160.1:3000/
  > Network:  http://172.19.192.1:3000/


 ERROR  No "exports" main defined in D:\Users\maxen\Desktop\app-ruche\node_modules\@nuxt\kit\package.json

  at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
  at packageExportsResolve (internal/modules/esm/resolve.js:488:7)
  at resolveExports (internal/modules/cjs/loader.js:449:36)
  at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
  at Function.resolve (internal/modules/cjs/helpers.js:98:19)
  at resolveModule (/D:/Users/maxen/Desktop/app-ruche/node_modules/nuxi/dist/chunks/cjs.mjs:19:29)
  at importModule (/D:/Users/maxen/Desktop/app-ruche/node_modules/nuxi/dist/chunks/cjs.mjs:32:24)
  at loadKit (/D:/Users/maxen/Desktop/app-ruche/node_modules/nuxi/dist/chunks/kit.mjs:5:18)
  at Object.invoke (/D:/Users/maxen/Desktop/app-ruche/node_modules/nuxi/dist/chunks/dev.mjs:6738:43)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-ruche@1.0.0 dev: `nuxi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app-ruche@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\maxen\AppData\Roaming\npm-cache\_logs\2022-04-06T06_57_33_125Z-debug.log
```

**Comment by MakeSense1212** [comment]
### UPDATE ### 
After installing a vanilla Nuxt 2 project and tried to migrate it to Nuxt Bridge, I noticed I had an extra @nuxt/kit: ^0.8.1-edge in my package.json that wasn't there is my vanilla. So I removed it and npm i.

Then I had an error asking me to add "@nuxt/ui-templates-edge": "0.0.0-27479051.598a8a0".

After that, my project was compiling, but it was a loop compiling. I found #3147, they give a few advices to avoid loop compilation. So now I can run the project, but there's no CSS as Tailwind doesn't work ...

**Comment by danielroe** [comment]
Yes, if you're using npm@6, see https://github.com/nuxt/framework/issues/3608#issuecomment-1073803039.

Tailwind should work. If not, please raise it with https://github.com/nuxt-community/tailwindcss-module/.

I think we can close this issue as you resolved the problem with the `No "exports" main` issue you experienced. (By the way, when we enter RC, a lot of these issues with `-edge` versions will disappear.)
