### ISSUE TITLE
pnpm run build fails to place traced files in a normal node_modules structure

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#4119]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27487080.ec32cf9`
- Package Manager:  `pnpm@6.32.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/danielroe/nuxt3-repros/tree/pnpm-tracing

### Describe the bug

Building a project installed with `pnpm i --shamefully-hoist` results in a project that can't be deployed.

`.output/server/node_modules` only contains a `.pnpm` folder with the following contents:

```
cookie-es@0.5.0            fetch-blob@3.1.5           node-fetch@3.2.3           ufo@0.7.11
data-uri-to-buffer@4.0.0   formdata-polyfill@4.0.10   ohmyfetch@0.4.15           ufo@0.8.3
defu@6.0.0                 h3@0.4.2                   pathe@0.2.0                unenv@0.4.3
destr@1.1.0                node-domexception@1.0.0    radix3@0.1.1               web-streams-polyfill@3.2.0
```

This is not deployable, and will trigger the following error:

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'unenv' imported from /tmp/output/server/index.mjs
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:932:9)
    at moduleResolve (node:internal/modules/esm/resolve:978:18)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Possibly related

https://github.com/vercel/nft/pull/238

**Comment by kkukelka** [comment]
Same here. Using pnpm without vite but with nitro enabled. Disabling nitro works as a workaround.

**Comment by danielroe** [comment]
-> https://github.com/unjs/nitro/issues/106
