### ISSUE TITLE
export 'BaseTransition' was not found in '/var/app/node_modules/@nuxt/bridge/dist/runtime/vue2-bridge.mjs

### ISSUE THREAD

**Issue by HendrikJan** [nuxt/framework#4120]
### Environment

RootDir: /var/app
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.3.1`
- Builder:          `webpack`
- User Config:      `rootDir`, `bridge`, `telemetry`, `nitro`, `head`, `publicRuntimeConfig`, `css`, `plugins`, `components`, `buildModules`, `vuetify`, `i18n`, `modules`, `axios`, `compilerOptions`, `build`, `watchers`, `ssr`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `@nuxtjs/vuetify@1.12.3`, `8n`, `@nuxtjs/dotenv@1.4.1`, `@nuxt/bridge@3.0.0-27485997.c426f3e`
------------------------------

And in my package.json:
```
"scripts": {
    "dev": "nuxi dev --https --port 9004 --host $DOMAIN --ssl-cert $CRT_FILE --ssl-key $KEY_FILE",
}
```

### Reproduction

* Clone this repo: https://github.com/HendrikJan/nuxt-error-demo
* Run 'npx nuxi dev'
* See the errors

### Describe the bug

When running `npm run dev` I get the error:

```
 WARN  Compiled with 67 warnings                          friendly-errors 09:35:32


 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js

"export 'BaseTransition' was not found in '/var/app/node_modules/@nuxt/bridge/dist/runtime/vue2-bridge.mjs'
                                                          friendly-errors 09:35:32

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js

"export 'EMPTY_ARR' was not found in '/var/app/node_modules/@nuxt/bridge/dist/runtime/vue2-bridge.mjs'

...

 WARN  in ./.nuxt/imports.mjs                             friendly-errors 09:35:32

"export 'clearError' was not found in '#app'              friendly-errors 09:35:32

...

 WARN  in ./node_modules/@nuxt/bridge/dist/runtime/vue2-bridge.mjs

"export 'default' (imported as 'Vue') was not found in 'vue'
```

### Additional context

I'm using Express in serverMiddleware

**Comment by HendrikJan** [comment]
I've added a dependency: 

```
npm install -d @nuxt/ui-templates@npm:@nuxt/ui-templates-edge@latest
```

This seems to fix most of the errors, only 6 remain:

```
 WARN  Compiled with 5 warnings

 WARN  in ./.nuxt/imports.mjs 

"export 'clearError' was not found in '#app' 

 WARN  in ./.nuxt/imports.mjs

"export 'defineNuxtLink' was not found in '#app'                                                                                                                                                                                      

 WARN  in ./.nuxt/imports.mjs

"export 'throwError' was not found in '#app'

 WARN  in ./.nuxt/imports.mjs    

"export 'useError' was not found in '#app'   

 WARN  in ./.nuxt/imports.mjs           

"export 'useMeta' was not found in '#head'                      
```

**Comment by danielroe** [comment]
Would you run `npm why unimport`? This looks to me like you have an older version installed. You can also try running `npm upgrade unimport` or `npm install -D unimport` to force an unimport version bump.

**Comment by HendrikJan** [comment]
`npm install -D unimport` tells me "up to date".

**Comment by brolnickij** [comment]
https://github.com/nuxt/framework/issues/4094

**Comment by HendrikJan** [comment]
I can confirm that #4094 is also an issue in my case.
Browser console tells me: "Uncaught TypeError: Object(...) is not a function"
