### ISSUE TITLE
Can't import some dependencies in nuxt

### ISSUE THREAD

**Issue by asvae** [nuxt/framework#4128]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27487491.eb22ce9`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

* clone https://github.com/asvae/nuxt-3-lodash-issue
* run `npm install`
* run `npm run build && npm run start`
* open `http://localhost:3000`
* look into console and see multiple errors

### Describe the bug

The problem is that when I try to add some dependencies (in repo it's `lodash`) - build crashes. `dev` works fine though.

* The project in repro is *fresh nuxt 3 project*, generated with `npx nuxi init nuxt3-app`. 
* On top of that I installed `lodash` and added import to `app.vue.`

### Additional context

Happy to help with this issue as it really hampers [our project](https://github.com/epicmaxco/vuestic-ui) transition to nuxt 3. But hope to get a bit of connection with nuxt team to know if it's something simple or maybe something you're working on already.

We tried different approaches, i.e. using lodash-es, webpack build, turning on transpiling (then `dev` dies), trying other dependencies, using other devices etc. Let me know if we need this data or this issue is clear enough.

Cheers.

### Logs

I'm getting error like this, then JS goes out of memory 🥲 .

```bash
Cannot find module '/Users/me/2-Projects/7-epicmax/1-epicmax/15-nuxt-test-lodash-repro/.output/server/node_modules/lodash/sortBy' imported from /Users/me/2-Projects/7-epicmax/1-epicmax/15-nuxt-test-lodash-repro/.output/server/chunks/app/server.mjs
Did you mean to import lodash-repro/.output/server/node_modules/lodash/sortBy.js?
  at new NodeError (node:internal/errors:371:5)
  at finalizeResolution (node:internal/modules/esm/resolve:418:11)
  at moduleResolve (node:internal/modules/esm/resolve:983:10)
  at defaultResolve (node:internal/modules/esm/resolve:1080:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
  at link (node:internal/modules/esm/module_job:78:36)
```

**Comment by danielroe** [comment]
Try following the instructions in the error message...

See https://github.com/nuxt/framework/issues/3988.

I'm closing to follow in https://github.com/nuxt/framework/issues/3343.
