### ISSUE TITLE
Error `Failed to execute 'insertBefore' on 'Node'` with `navigateTo` in page 

### ISSUE THREAD

**Issue by Atinux** [nuxt/framework#4136]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27487836.540e23c`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rhwgzj?file=pages%2Fnavigate-to.vue

### Describe the bug

- Open the preview in a new window
- Click on `navigateTo('/secret')` link
- Page is blank and an error is displayed in the console

See video:

https://user-images.githubusercontent.com/904724/162048318-85744704-cfc0-4562-9bb9-4de743b0a8c2.mp4

### Additional context

The error happens also if `navigateTo` is not inside an `useAsyncData`, same as if we use `router.push`.

I believe this might be an issue related to `<Suspense>`?

**Comment by pi0** [comment]
You should't make any side-effect from `useAsyncData` and also `await` on `navigateTo`. This seems working fine for me without hydration.

```js
<script setup>
await navigateTo('/secret');
</script> 
```

**Comment by Atinux** [comment]
Agree for side-effects but this can be related to `asyncData` in Nuxt 2 where we offered `redirect` and `error` inside of it (even though implementation is different).

Thanks for the fast answer ❤️
