### ISSUE TITLE
Bug: `throwError` on SSR is giving different DX

### ISSUE THREAD

**Issue by Atinux** [nuxt/framework#4137]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27487836.540e23c`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rhwgzj?file=pages%2Ferror.vue

### Development

- Open the preview in the new window
- Click on `throwError('oups')` link
- Refresh the page

https://user-images.githubusercontent.com/904724/162049241-108e5782-faa9-436f-ab6f-144132a1e945.mp4

### Production

- Stop the dev server, run `yarn build && yarn start` in StackBlitz terminal
- Open the preview in the new window
- Click on `throwError('oups')` link
- Refresh the page

https://user-images.githubusercontent.com/904724/162049430-986d2635-37e6-4bb5-8979-55bc800070cb.mp4

### Additional context

I believe the UX should be similar when refreshing the page.

In development, I have no idea why we have the whole file rendered, I am displaying `props.error` in the `error.vue`: https://stackblitz.com/edit/nuxt-starter-rhwgzj?file=error.vue

**Comment by danielroe** [comment]
The development issue is a vite peculiarity - it allows you to directly access all files in your source directory by typing them in - so `/app` will render `app.vue` 🤦 

The reason the development experience is different is that the navigation to `/error` never completes - instead we stay on `/` and display the error handling page. When you click refresh it doesn't display the error.

If you try https://stackblitz.com/edit/nuxt-starter-elujbx?file=app.vue and visit `/err` it should work more intuitively

**Comment by danielroe** [comment]
This should be resolved with https://github.com/nuxt/framework/pull/7234.
