### ISSUE TITLE
Async Middleware - No active Pinia

### ISSUE THREAD

**Issue by shinguweb96** [nuxt/framework#4144]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27484505.9f6eff7`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `vite`, `privateRuntimeConfig`, `publicRuntimeConfig`, `css`, `buildModules`, `intlify`, `vueuse`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@vueuse/nuxt@8.2.4`, `@intlify/nuxt3@0.1.10`
------------------------------

### Reproduction

check-auth.global.ts:

```
`import { useUserStore } from "~/stores/user";

export default defineNuxtRouteMiddleware(async () => {
    // check if user is authenticated by using cookie and pinia

    const session = useCookie('laravel_session').value || null
    const userStore = useUserStore();
    
    await userStore.fetchUser();

})`

```
### Describe the bug

`getActivePinia was called with no active Pinia. Did you forget to install pinia? const pinia = createPinia() app.use(pinia) This will fail in production.`

Using async middleware, pinia is not getting started.

**Comment by danielroe** [comment]
https://github.com/vuejs/pinia/issues/1211

**Comment by Teranode** [comment]
@danielroe is it intentional that when using the global route middleware, that plugins are not loaded before it cause them to not be available?

**Comment by danielroe** [comment]
@Teranode No. I've made a note to fix - thanks for the ping.

**Comment by serhez** [comment]
Are there any updates on this issue? I'm using RC 3 and this is still not working.
