### ISSUE TITLE
The requested module '/_nuxt/node_modules/unenv/runtime/mock/proxy.cjs?import' does not provide an export named 'default'

### ISSUE THREAD

**Issue by rvmourik** [nuxt/framework#4154]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27488730.0cbc9cb`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```
npx nuxi init nuxt3-app
yarn install
yarn dev
```

### Describe the bug

Uncaught SyntaxError: The requested module '/_nuxt/node_modules/unenv/runtime/mock/proxy.cjs?import' does not provide an export named 'default'

### Additional context

It happens with initializing a new empty project and starting the dev server afterwards.

**Comment by danielroe** [comment]
This may be a consequence of https://github.com/unjs/unenv/commit/0d64253de8f3b343072fca3bde74e95fa1c4c543. For now you can likely workaround by installing `unenv@0.4.4`.

cc: @pi0

**Comment by AndreyYolkin** [comment]
> This may be a consequence of [unjs/unenv@0d64253](https://github.com/unjs/unenv/commit/0d64253de8f3b343072fca3bde74e95fa1c4c543). For now you can likely workaround by installing `unenv@0.4.3`.


Probably you need 'has workaround' label for such issues?

**Comment by pi0** [comment]
I cannot reproduce this issue anymore with the latest dependencies. Please **remove any pinned version of unenv** and try upgrading with `npx nuxi upgrade --force`
