### ISSUE TITLE
@nuxtjs/sentry package not working with nuxt bridge

### ISSUE THREAD

**Issue by viktorkrepak** [nuxt/framework#4178]
### Environment

Nuxt CLI v3.0.0-27488730.0cbc9cb                                                                                                 21:04:04
                                                          21:04:05
Nuxt project info:                                                                                                               21:04:05

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.16.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.3.2`
- Builder:          `webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `modules`, `i18n`, `sentry`, `axios`, `proxy`, `privateRuntimeConfig`, `build`, `bridge`, `buildModules`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`, `@nuxtjs/sentry@5.1.7`, `nuxt-i18n@6.28.1`
- Build Modules:    `@nuxt/bridge@3.0.0-27488730.0cbc9cb`
------------------------------

### Reproduction

Just install the latest https://www.npmjs.com/package/@nuxtjs/sentry module, and add the module into nuxt.config and set up the initial config and then try to run the dev server.

### Describe the bug

I've migrated from Nuxt2 to Nuxt bridge, and everything works smoothly, but nuxtjs sentry module isn't working. I get this error when starting dev server index.js:29 Uncaught TypeError: Cannot destructure property '__extends' of '_tslib_js__WEBPACK_IMPORTED_MODULE_0___default.a' as it is undefined.

### Additional context

![image](https://user-images.githubusercontent.com/27999815/162268074-1fa0e2c0-0a98-457e-8169-5f9195cfd619.png)

### Logs

```shell
Uncaught TypeError: Cannot destructure property '__extends' of '_tslib_js__WEBPACK_IMPORTED_MODULE_0___default.a' as it is undefined.
    at eval (index.js:29:5)
    at Module../node_modules/tslib/modules/index.js (app.js:1661:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (index.js:3:63)
    at Module../node_modules/@sentry/browser/esm/index.js (app.js:239:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (sentry.client.js:6:73)
    at Module../.nuxt/sentry.client.js (app.js:334:1)
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/1151. (Check the issue for a workaround.)
