### ISSUE TITLE
`IncomingMessage` and `ServerResponse` not assignable to `CompatabilityEvent`

### ISSUE THREAD

**Issue by ikadix** [nuxt/framework#4180]
### Environment

❯ npx nuxi info
Nuxt CLI v3.0.0-27489107.7379184                                                                                 
RootDir: /home/projects/github-8rmpp2                                                                            
Nuxt project info:                                                                                              

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27489107.7379184`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-8rmpp2?file=server/api/test.ts

### Describe the bug

When typing `req` and `res` in an api handler as described in the docs [here](https://v3.nuxtjs.org/guide/directory-structure/server/#async-function) 

If you attempt to follow the examples for passing `req` into any of the h3 utilities such as `useBody`, `useQuery` or `useCookie` or similarly pass `res` into relevant utilites like `setCookie` you will be met with the following error.

```
Argument of type 'IncomingMessage' is not assignable to parameter of type 'CompatibilityEvent'.
  Type 'import("http").IncomingMessage' is not assignable to type 'import("stackblitz:/node_modules/h3/dist/index").IncomingMessage'.(2345)
  ```
  
  Unclear if this should be raised here or in the h3 repo, please let me know if the latter and I will raise over there.

**Comment by ikadix** [comment]
I see the conversation here https://github.com/nuxt/framework/pull/4174 mentions moving away from this style of handler. 

Should we not be writing these kinds of handlers now / in future ?

**Comment by Diizzayy** [comment]
@ikadix 

> Should we not be writing these kinds of handlers now / in future ?

Indeed, H3 is slowly veering away from supporting legacy `(req, res)` handlers, as it currently holds back the framework from evolving to support more features. More info at (https://github.com/unjs/h3/issues/73)

**Comment by danielroe** [comment]
Yes, this is a case of migrating your handler to `event`:

```js
import type { IncomingMessage, ServerResponse } from 'http';
import { useBody, useCookies, useQuery, setCookie, eventHandler } from 'h3';

export default eventHandler(async (event) => {
  const query = useQuery(event);
  const body = await useBody(event); // only for POST | PUT | PATCH | DELETE requests
  const cookies = useCookies(event);

  setCookie(event, 'test', 'test');
});
```
