### ISSUE TITLE
Infinite live reload when --https is active

### ISSUE THREAD

**Issue by SupianIDz** [nuxt/framework#4191]
### Environment

Nuxt CLI v3.0.0-27489614.315e5b5
RootDir: /Users/supianidz/Sites/foo
Nuxt project info:                                                                                          
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27489614.315e5b5`
- Package Manager:  `yarn@1.23.0-20220130.1630`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. npx nuxi init foo
2. cd foo
3. yarn install
4. generate certificate using mkcert
5. yarn dev --https --ssl-cert ./dev.crt --ssl-key ./dev.key

### Describe the bug

When the `--https` parameter is included along with the certificate from mkcert in the `yarn dev` command, nuxt3 will reload the page in a few seconds without stopping. So I have to run `yarn build` when I want to test the page without being bothered by weird reloads.

This is very annoying when dealing with form fields.

But it will all be normal if I don't include `--https`

https://user-images.githubusercontent.com/37969970/162358912-ecba2c1b-a5af-484b-84e9-cdfad08c584e.mp4

**Comment by Diizzayy** [comment]
@SupianIDz  The issue you're facing is due to failure to connect to Vite's HMR, hence the repeated reloading in attempt to gain connection.

Judging by the developer logs before the page reloads as well as your setup, you might be able to circumvent the hmr failure by strictly settings it's protocol to `ws` as opposed to `wss (https)`

`nuxt.config.ts`
```ts
export default defineNuxtConfig({
  vite: {
    server: { hmr: { protocol: 'ws' } }
  }
})
```

**Comment by pi0** [comment]
@Diizzayy Do you mind making a PR to set `ws` as default?

**Comment by SupianIDz** [comment]
> @SupianIDz The issue you're facing is not due to Nuxt, but caused by failure to connect to Vite's HMR, hence the repeated reloading in attempt to gain connection.
> 
> Judging by the developer logs before the page reloads as well as your setup, you might be able to circumvent the HMR connection failure by strictly settings it's protocol to `ws` as opposed to `wss (https)`
> 
> `nuxt.config.ts`
> 
> ```ts
> export default defineNuxtConfig({
>   vite: {
>     server: { hmr: { protocol: 'ws' } }
>   }
> })
> ```

Hi, your suggestion works really well. Thank you.

**Comment by Diizzayy** [comment]
@SupianIDz Perfect! I'm glad it helped

> Do you mind making a PR to set ws as default?

@pi0 Sure thing! I'll have it ready
