### ISSUE TITLE
NuxtLink doesn't change page correctly

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/framework#4208]
### Environment

https://stackblitz.com/edit/github-t2n64t-vk46jh?file=pages%2F[slug].vue

### Reproduction

https://stackblitz.com/edit/github-t2n64t-vk46jh?file=pages%2F[slug].vue

### Describe the bug

Changing route with await useFetch shows blank template 
Go to /test, click on /test2

**Comment by danielroe** [comment]
Pages need a single root element.

**Comment by Rigo-m** [comment]
For the record:
In my local project I still got the error even after I checked there was only one root element. This was because the template looked like this:

```html
<template>
  <!-- single element -->
  <div></div>
</template>
```

That was because the comment counted as an element to be parsed.

Shouldn't that not count as an element?

Gonna put a tip in the docs so that people can avoid falling into this problem
