### ISSUE TITLE
Global page transition configuration

### ISSUE THREAD

**Issue by jiblett1000** [nuxt/framework#4223]
### Environment

n/a

### Reproduction

n/a

### Describe the bug

Right now it is possible to set page transitions in each page using definePageMeta. However, this has to be done per page. Ideally, there would be a way to set the page transition globally and per page.

**Comment by jiblett1000** [comment]
I would be happy to give a PR a shot if someone can point me in the right direction. :)

**Comment by danielroe** [comment]
This was implemented in https://github.com/nuxt/framework/issues/5729. Apologies for not getting back to you @jiblett1000!

**Comment by jiblett1000** [comment]
@danielroe No worries! Thanks for the reply and the awesome work :)
