### ISSUE TITLE
With new latest version of Nuxt i cant run my project [SIGSEGV]

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#4225]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27491748.3186841`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `publicRuntimeConfig`, `privateRuntimeConfig`, `app`, `nitro`, `router`, `srcDir`, `build`, `buildModules`, `modern`, `tailwindcss`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.2`, `@vueuse/nuxt@8.2.5`
------------------------------

### Reproduction

-

### Describe the bug

i just trying to run my project after update nuxt....
`yarn dev`
after running i get error:
`error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by mihail727** [comment]
with clear project all works fine......
if u have time a can show my project in discord

**Comment by danielroe** [comment]
I'm going to close this as there's not much we can do without a minimal reproduction or more information. Feel free to ping me on Discord 😉

**Comment by mihail727** [comment]
> I'm going to close this as there's not much we can do without a minimal reproduction or more information. Feel free to ping me on Discord wink

where i can find u discord name?

**Comment by danielroe** [comment]
It's ... danielroe.

**Comment by mihail727** [comment]
> It's ... danielroe.

0_0 but i need discord tag 
or I don't know how to search for users without a tag)
