### ISSUE TITLE
Runtimeconfig public/private does not get merged

### ISSUE THREAD

**Issue by weeuwee** [nuxt/framework#4230]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.18.2`
- Nuxt Version:     `3.0.0-27491748.3186841`
- Package Manager:  `pnpm@6.32.4`
- Builder:          `vite`
- User Config:      `meta`, `buildModules`, `publicRuntimeConfig`, `privateRuntimeConfig`, `typescript`, `vueuse`, `unocss`, `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.2.5`, `@unocss/nuxt@0.30.12`, `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-pbfhfv?file=app.vue

### Describe the bug

public and private runtime should be merged on server side. Instead the public was split out.

```json
{
  app: { baseURL: '/', buildAssetsDir: '/_nuxt/', cdnURL: '' },
  nitro: { routes: {}, envPrefix: 'NUXT_' },
  build: { buildTest2: 'buildTest2' },
  label: { labelTest2: 'labelTest2' },
  public: {
    build: { buildTest1: 'buidlTest1' },
    label: { labelTest1: 'labelTest1' },
    app: undefined
  }
}
```
This happens on build `3.0.0-27491748.3186841` but its fine on `3.0.0-27487836.540e23c`

**Comment by msonowal** [comment]
related #4126

**Comment by pi0** [comment]
This is an intentional semi-breaking change with nitropack migration that `public` is splited out. As you can see top-level keys are merged and overridden with `privateRuntimeConfig` but `public` includes only `publicRuntimeConfig`. We are adopting this new convention also for nuxt runtime config (#4254)
