### ISSUE TITLE
Cookie can't be set together with redirect

### ISSUE THREAD

**Issue by Lanayx** [nuxt/framework#4244]
### Environment

Nuxt CLI v3.0.0-27491748.3186841                                                                                                    11:06:50  
RootDir: C:\Work\Test                                                                                                                        11:06:56
Nuxt project info:                                                                                                                               11:06:56

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27491748.3186841`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `css`, `build`, `buildModules`, `vite`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

When using this code and performing SSR request (when this code is executed on server side)
```
useCookie('myCookie').value = '123';
await navigateTo('/test');
```
cookie "myCookie" is not set

### Describe the bug

Setting cookie together with redirecting doesn't work when executing SSR request

### Additional context

A bit context why is this needed. When using external auth server it redirect to callback url together with the token (for example `http://localhost:3000/loggedIn?accessToken=abcd`). I want to write down this token to the cookie and redirect user further (for example `http://localhost:3000/dashboard`), so I need both set cookie and redirect functionality

### Logs
On simple pages it just silently fails, in more complex case I see the following warning:

```shell
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```

**Comment by danielroe** [comment]
This is because we defer writing the server cookie until the HTML is fully rendered (in case it's set more than once) - but if you redirect then we never reach that point... If you want to set a cookie _and_ redirect, you can do this manually:

```js
import { serialize } from 'cookie-es'
import { appendHeader } from 'h3'

export default defineNuxtPlugin(async () => {
  const route = useRoute()
  if (route.path === '/') {
    const event = useRequestEvent()
    appendHeader(event, 'Set-Cookie', serialize('test', '123'))
    await navigateTo('/test')
  }
})
```

**Comment by Lanayx** [comment]
@danielroe Thank you, I'll try that way! But it would be nice if this could be done not only inside plugin, but inside any component as well.

**Comment by danielroe** [comment]
The same code can be run in a component setup function.

**Comment by pi0** [comment]
This is not a bug. Navigation should be the last operation happening in the SSR lifecycle as it closes requests. BTW we can improve both error DX by showing more relevant message from h3 and introduce universal `setCookie` and `trySetCookie`.

**Comment by Lanayx** [comment]
@pi0 in my case the navigatio **is** the last, that's why I perceived it as a bug (I expected cookie header to be set at the point navigation starts)

**Comment by pi0** [comment]
@danielroe Will work on a fix shortly :)
