### ISSUE TITLE
Ability to use computed in `useHead`

### ISSUE THREAD

**Issue by Atinux** [nuxt/framework#4258]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27494471.1091d45`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-onqjwc?file=app.vue

### Describe the bug

Using a computed to set as title is not reactive:

```ts
const firstname = ref('')
const lastname = ref('')
const fullname = computed(() => {
  return `${firstname.value} ${lastname.value}`.trim() || 'Account'
})
useHead({
  title: fullname.value,
})
```

- Open in a new window
- Update the firstname and/or lastname input
- The window title should be updated

Passing the `ref` will result with an `[object object]` as window title.

### Additional context

It only works when using the components: https://stackblitz.com/edit/nuxt-starter-wrxbyb?file=app.vue

If this is a normal behaviour, I believe this should be documented.

**Comment by shinguweb96** [comment]
It'll be usefull for definePageMeta too.
So if we get data from api, we could send to useHead the title.

**Comment by danielroe** [comment]
regression from https://github.com/nuxt/framework/pull/4221
