### ISSUE TITLE
add back `nitro:generate` hook

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#4265]
### Discussed in https://github.com/nuxt/framework/discussions/4264

<sup>Originally posted by **benoitdemaegdt** April 11, 2022</sup>
Hey there 👋 

Few days ago **nitro:generate** hook was removed (see this [comment](https://github.com/nuxt/framework/pull/4187#discussion_r845623039)).

---

We should deprecate this hook BTW and introduce something more meaningful for nuxt 3.

**Comment by fiamma06** [comment]
What about it?

**Comment by danielroe** [comment]
Just noticed that this is causing the regression of https://github.com/nuxt/framework/issues/1192.

Might be worth reopening https://github.com/nuxt/framework/pull/4304.
