### ISSUE TITLE
How to use nuxtApp or plugin on server

### ISSUE THREAD

**Issue by soixt** [nuxt/framework#4270]
### Environment

Nuxt CLI v3.0.0-27490192.4253d2e                                                                                                                     23:15:35  
RootDir: C:\Users\Lenovo\Desktop\AA                                                                                                                  23:15:39
Nuxt project info:                                                                                                                                   23:15:39

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27490192.4253d2e`
- Package Manager:  `npm@8.1.4`
- Builder:          `vite`
- User Config:      `buildModules`, `css`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `nuxt-windicss@2.2.8`
------------------------------

### Reproduction

Call useNuxtApp() within server routes

### Describe the bug

```
export default async() => {
    const config = useRuntimeConfig()
    const { $apiFetch } = useNuxtApp()
    const data = await $apiFetch(`/projects`)
    return data.data
}
```
I get "useNuxtApp is not defined", where $apiFetch is customized $fetch with base url and headers. So is there a way to use plugin within server routes?  For useRuntimeConfig() it works.

The plugin itself is:

```
import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin(nuxtApp => {
  const config = useRuntimeConfig()

  nuxtApp.provide(
    'apiFetch',
    $fetch.create({
      baseURL: config.apiBaseUrl,
      headers: {
        Accept: 'application/json',
      },
    })
  )
})
```

**Comment by pi0** [comment]
Hi @sasaorasanin. No not auto imports are same for `server/` routes and we cannot access nuxtApp within them. You might create a shared `utils/` dir and reuse it both for `composables/` and `server/api`. `$fetch` is global.

**Comment by sasaorasanin** [comment]
@pi0 Hi again, for some reason I have issues here:

In utils/apiFetch.ts
```
import { Headers } from 'ohmyfetch'
import Cookies from 'js-cookie'

const config = useRuntimeConfig()
const auth = Cookies.get('auth') // useCookie('auth') seems like it would work only in setup/composables
const headers = new Headers();
headers.append('Accept', 'application/json')
if (auth && auth.token) {
    headers.append('Authorization', auth.token)
}
export const apiFetch = $fetch.create({
    baseURL: config.apiBaseUrl,
    headers: headers,
})
```
In server/api/projects.ts
```
import { apiFetch } from "~/utils/apiFetch"

export default async() => {
    const data = await apiFetch(`/projects`)
    return data?.data
}
```
This throws "Cannot access 'projects$1' before initialization" on /api/projects route. Even when I use useCookie('auth'), it throws the same error. Not sure why tho. Any help?

**Comment by danielroe** [comment]
It's not clear why you have that error @soixt - I'd suggest raising a discussion or asking on Discord - and it would be helpful to see a [full minimal reproduction](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz).
