### ISSUE TITLE
Nuxt instance unavailable on all pages

### ISSUE THREAD

**Issue by tiborpino** [nuxt/framework#4287]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.15.8`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `modules`, `buildModules`, `dev`, `build`, `css`, `meta`, `app`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/sitemap@2.4.0`
- Build Modules:    `nuxt-purgecss@1.0.0`, `~/modules/pages`

### Reproduction

Start dev environment via `yarn dev`

### Describe the bug

On every page I get the error 

```
nuxt instance unavailable

  at useNuxtApp (./.nuxt/dist/server/server.mjs:587:13)
  at Module.useRuntimeConfig (./.nuxt/dist/server/server.mjs:595:10)
  at $id_bbf8dc5e (./.nuxt/dist/server/server.mjs:41284:38)
  at async __instantiateModule__ (./.nuxt/dist/server/server.mjs:42697:3)
```

### Additional context

I use useNuxtApp in app.vue

./app.vue

```
const nuxtApp = useNuxtApp()

nuxtApp.hook('page:finish', () => {
    window.scrollTo(0, 0)
})
```

**Comment by danielroe** [comment]
Would you provide a reproduction please? 🙏

**Comment by antlionguard** [comment]
https://github.com/nuxt/framework/issues/3904 is got same error. Is there a possibility of being related?

**Comment by danielroe** [comment]
No, I don't believe these are the same issue.

**Comment by tiborpino** [comment]
We don't use Pinia. It shouldn't be related. It is very hard to provide a reproduction, because our codebase is huge and is under heavy development :-/

**Comment by tiborpino** [comment]
Are there any logs I can send to help you identify the cause of the error?

**Comment by tiborpino** [comment]
We are using useRuntimeConfig on many places server and client side, public and private. We already use new useRuntimeConfig().public syntax

**Comment by tiborpino** [comment]
Now we are on 3.0.0-27497374.59593a0 version and getting error

`{
  "statusCode": 404,
  "statusMessage": "Not Found",
  "stack": []
}`

Some console.log from server.mjs: 597

nuxtAppCtx

`nuxt app ctx:  {
  use: [Function: use],
  set: [Function: set],
  unset: [Function: unset],
  call: [Function: call],
  callAsync: [AsyncFunction: callAsync]
}`

const vm = __vite_ssr_import_0__.getCurrentInstance();
`vm object:  null`

**Comment by danielroe** [comment]
Are you ever using it outside of a component setup, nuxt plugin or middleware? I want to know what is at this point:

```
  at $id_bbf8dc5e (./.nuxt/dist/server/server.mjs:41328:38)  
```

(The bit that is _calling_ `useRuntimeConfig`.)

**Comment by eMeRiKa13** [comment]
I have the same error. What is the way to access runtime config from a server file?

I used `import config from '#config';` but I tried to switch to import { useRuntimeConfig } from '#app';

**Comment by danielroe** [comment]
You should now just run `useRuntimeConfig()` without an import: https://v3.nuxtjs.org/guide/features/runtime-config#server-routes

**Comment by leccyril** [comment]
@danielroe  i am using it im a vue file and have same error

`const config = useRuntimeConfig().public
methods: {
    	handleSubmit: async function() {
			const test = await $fetch(config.BASE_URL, {
  				method: 'PUT', body: this.form,
				headers: { "Content-Type": "application/json", "domain": "www.properti.es" }, 
			});
      }
    }
`
and in nuxt config js

`import { defineNuxtConfig } from 'nuxt3'

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
	runtimeConfig: {
		secretKey: '', // variables that can only be accessed on server-side
		public: {
		  BASE_URL: process.env.BASE_URL || 'http://localhost:8080/rest/enquiry/create'
		}
	  },
	plugins: [
		{ src: '~/plugins/bootstrap.client.js'}
    ],
})`

i followed documentation but it seems i use it in a normal way (client side)

**Comment by danielroe** [comment]
Here's an example of this working. https://stackblitz.com/edit/github-sb3eyy.

Would you modify this so it matches your project and doesn't work?

**Comment by leccyril** [comment]
still same issue :/

**Comment by leccyril** [comment]
to make it work for my case i made this :+1: 

nuxt.js.config

    `import { defineNuxtConfig } from 'nuxt3'

    // https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
    export default defineNuxtConfig({
	publicRuntimeConfig: {
		  REST_API:  process.env.REST_API || 'http://localhost:8080/rest/enquiry/create',
	},
	css: [
		'@fortawesome/fontawesome-svg-core/styles.css',
	],
	plugins: [
		{ src: '~/plugins/bootstrap.client.js'},
    ],
    })
    `

and in code 
`    const response =await $fetch.raw(useRuntimeConfig().REST_API
`

i am not use setup part because my component is complicated and i had to specified publicRuntimeConfig, so if i have server side properties i dont know how to make it work...

**Comment by leccyril** [comment]
it works but we have to clean yarn lock and make yarn install :/

**Comment by danielroe** [comment]
@leccyril That's a deliberate choice: https://github.com/nuxt/framework/pull/4016#discussion_r840439465. Glad things are working for you after upgrade 😊 

@tiborpino Are you still encountering this? Could you provide any answers to https://github.com/nuxt/framework/issues/4287#issuecomment-1098460416?

**Comment by leccyril** [comment]
@danielroe so for production mode what is advised ? thanks

**Comment by tiborpino** [comment]
> @leccyril That's a deliberate choice: [#4016 (comment)](https://github.com/nuxt/framework/pull/4016#discussion_r840439465). Glad things are working for you after upgrade 😊
> 
> @tiborpino Are you still encountering this? Could you provide any answers to [#4287 (comment)](https://github.com/nuxt/framework/issues/4287#issuecomment-1098460416)?

I've identified two problems and the error is now fixed

1.  We used to import like this import { useRuntimeConfig } from '#nitro' - now not needed
2. We use useRuntimeConfig outside defineNuxtPlugin 

```
const config = useRuntimeConfig()
export default defineNuxtPlugin(() => {}
```

moved inside function solved the error

```
export default defineNuxtPlugin(() => {
    const config = useRuntimeConfig()
}
```

**Comment by iRunner** [comment]
I am getting this error when running tests through jest... am i missing something with nuxt to run tests on a component level?

**Comment by Horpey** [comment]
> 

It works

**Comment by uuf6429** [comment]
I get this same error during nuxi generate. Here's how it looks like:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/230049/178222354-d5ab6ce6-cb3b-4ff7-bee8-03f5f63e2c3f.png">
and the `at setup` point:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/230049/178222497-cd37db1a-50cb-4c40-b472-dfc483c28be6.png">

**Comment by Horpey** [comment]
> I get this same error during `nuxi generate` (note that `nuxi dev` works perfectly fine). Here's how it looks like: <img alt="image" width="747" src="https://user-images.githubusercontent.com/230049/178222354-d5ab6ce6-cb3b-4ff7-bee8-03f5f63e2c3f.png"> and the `at setup` point: <img alt="image" width="650" src="https://user-images.githubusercontent.com/230049/178222497-cd37db1a-50cb-4c40-b472-dfc483c28be6.png">
> 
> Personally, I'd rather not use setup, but unfortunately as mentioned in another ticket, I'm not able to do what I need because the composables do not have a non-composable version (or if they do, I haven't been able to see that in the docs or examples).

If you have any imports in your component file from `nuxt/app` or `#app`, you can remove them, try to run the app and also generate it again to see if the error is gone.

**Comment by max5432112345** [comment]
I also get error `nuxt instance unavailable` if directory api is empty.

> [nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable
> at Module.useNuxtApp (file:///nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:415:13)
   
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "dependencies": {
    "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.6"
  }
}
```

**Comment by danielroe** [comment]
Feel free to open an issue with a reproduction. :pray:

**Comment by max5432112345** [comment]
> Feel free to open an issue with a reproduction. pray

I think I found, with  strategy: 'prefix' not work, but without work

```
  i18n: {
    locales: [
      {
        code: 'en',
        file: 'en.json'
      },
    ],
    lazy: true,
    langDir: 'locales',
    defaultLocale: 'en',
    strategy: 'prefix'
  },
  ```

**Comment by max5432112345** [comment]
> Feel free to open an issue with a reproduction. pray

https://github.com/nuxt/framework/issues/6300
