### ISSUE TITLE
Suggest allow define api/route server filename with multi dot

### ISSUE THREAD

**Issue by TrungRueta** [nuxt/framework#4292]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27495976.e31c604`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `typescript`, `buildModules`, `components`, `windicss`, `autoImports`, `router`, `experimental`, `features`, `globalName`, `build`, `vite`, `loading`, `cli`, `alias`, `privateRuntimeConfig`, `publicRuntimeConfig`, `css`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.2.5`, `nuxt-windicss@2.2.10`
------------------------------

### Reproduction

- create new nuxt project
- create new folder `api`
- create new file named: `test.get.ts` and define route use `defineEventHandler`
- Request to url `/api/test` with `GET` method will work.
- change filename to `test.txt.get.ts`
- Try request again, this times it will broken.

### Describe the bug

Follow document : [Matching HTTP method](https://v3.nuxtjs.org/guide/features/server-routes#matching-http-method) we can strict method by adding postfix between filename and file extension, delimit by [dot].

In many cases, we need custom manipulate router to serve "dynamic" content and response like a file, such as:
- auto-generate sitemap.xml . url `<domain>/sitemap.xml` be default
- auto-generate robots.txt, url `<domain>/robots.txt` be default
- stream pdf file by url, ex: `<domain>/file-pdf/<id>.pdf`

However, api and routes server for now only work with normal filename, it not working with multi dot, ex i want create `/sitemap.xml` route, i will have file `/server/routes/sitemap.xml.get.ts`, but this case not work.

**Comment by TrungRueta** [comment]
@Diizzayy yeah you right, i agree that sitemap and robot should write into build module. But about third example (`<domain>/file-pdf/<filename>.pdf`) how we can have this route use `server routes` or `api routes`?

In reality, sometimes we need to stream a file from hidden server through Nuxt to viewer and keep url like "real file". Yes, if we can freely to put other url solution i will choose format `<domain>/file-pdf/<filename>`, but if task require url must same like link to a file, then current server route logic will not work.

Other workaround is use `server middleware` and catch url format to response with file stream or let it pass. But it not legal ...

**Comment by pi0** [comment]
Hi. This issue should be fixed in `nitropack@v0.2.8`. Please try upgrading using `npx nuxi upgrade --force`.

Supporting API routes ending with an extension is certainly a valid use-case and was supported by nitro but was making problems for development because of a global fallback middleware.
