### ISSUE TITLE
Types for defineNuxtPlugin and nuxtApp

### ISSUE THREAD

**Issue by abarke** [nuxt/framework#4297]
### Environment

IDE PhpStorm 2021.3.3

$ tsc --version
Version 4.6.3

"name": "nuxt3",
"version": "3.0.0-27484505.9f6eff7",
"repository": "nuxt/framework",

### Reproduction

I created this stackblitz but I can't quite get the `"strict": true` to work 😣

https://stackblitz.com/edit/github-1j3sw2

### Describe the bug

TS7022: 'plugin' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

![image](https://user-images.githubusercontent.com/34715541/162958374-4c36d908-76aa-4f65-a6ed-8f820827b0aa.png)

### Additional context

What is the recommended way to type a plugin so that nuxtApp is fully typed? e.g.

```typescript
import type { NuxtApp } from "nuxt3"
import { defineNuxtPlugin } from "nuxt3"

const plugin = defineNuxtPlugin((nuxtApp: NuxtApp) => {
  const myplugin = {}
  nuxtApp.provide('myplugin', myplugin)
}
```

Would be great to update the nuxt3 docs with the corresponding types here: 
https://v3.nuxtjs.org/guide/directory-structure/plugins/#creating-plugins

**Comment by abarke** [comment]
Ahh seems the solution is to simply import defineNuxtPlugin and the types are inferred by the IDE.

```typescript
import { defineNuxtPlugin } from "nuxt3/app"
```

![image](https://user-images.githubusercontent.com/34715541/162978668-39225cf7-55f8-4437-bf96-12930ce56808.png)

**Comment by abarke** [comment]
Thanks @danielroe, for some reason my IDE was not autoimporting the types... now I see it resolving to `auto-imports.d.ts`

Apologies for the confusion.
![image](https://user-images.githubusercontent.com/34715541/163006366-bbad1eb9-1dda-4c2f-9a53-ee003d324b48.png)

**Comment by abarke** [comment]
@danielroe does adding a generic here instead of `unknown` bring any advantages when using the plugin?

**Comment by danielroe** [comment]
It is a generic, and should fill out as soon as you provide a plugin within `defineNuxtPlugin`.

**Comment by abarke** [comment]
Thanks for the clarity 👏
