### ISSUE TITLE
url with an image url always returns a gif

### ISSUE THREAD

**Issue by ririen** [nuxt/framework#4310]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27495976.e31c604`
- Package Manager:  `pnpm@6.32.4`
- Builder:          `vite`
- User Config:      `publicRuntimeConfig`, `css`, `modules`, `buildModules`, `vueuse`, `unocss`, `experimental`
- Runtime Modules:  `@nuxtjs/partytown@1.1.0`
- Build Modules:    `@vueuse/nuxt@8.2.5`, `@unocss/nuxt@0.31.0`, `nuxt-graphql-client@0.0.17`
------------------------------

### Reproduction

https://codesandbox.io/s/gifted-leaf-ux7hbh

-> Work IPX: https://ux7hbh.sse.codesandbox.io/
-> Work Page: https://ux7hbh.sse.codesandbox.io/aaa/bbb
-> Always GIF: https://ux7hbh.sse.codesandbox.io/old.jpg
-> Always GIF: https://ux7hbh.sse.codesandbox.io/image.png
-> Always GIF: https://ux7hbh.sse.codesandbox.io/anything.svg

### Describe the bug

I wanted to make `middleware` that does proxy to images or modifies them, for example with `IPX`.

It turns out that everything with the `jpg, svg, png` image ending ... returns the `GIF` format in the browser as an invalid image and middleware code is ignored.

**Comment by ririen** [comment]
@pi0 I understand how it works by https://github.com/unjs/serve-placeholder – If the image does not exist, it returns a pixel. The problem arises when you want to convert such a URL with `middleware` because the `serve-placeholder` has priority and overwrites the `middleware`.

**Comment by pi0** [comment]
Indeed. Unless a base path is a known prefix for public assets we should avoid such placeholder generation.

**Comment by pi0** [comment]
Hi. This issue should be fixed in `nitropack@v0.2.8`. Please try upgrading using `npx nuxi upgrade --force`.
