### ISSUE TITLE
Parameters in server cannot be three characters long.

### ISSUE THREAD

**Issue by jhughes-dev** [nuxt/framework#4313]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-27496606.e43ba6e`
- Package Manager:  `npm@8.5.2`
- Builder:          `vite`
- User Config:      `typescript`, `privateRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I have a server folder with 

`server/api/[uid].get.ts`

I just return the context.params
```
export default defineEventHandler( async ( event ) => {
    console.log(event.context.params)
    event.res.end(JSON.stringify(event.context.params))
})
```

This is empty, but if I change it to 
`server/api/[name].get.ts`

I see parameter returned. I tried a few different four letter words and they seem to work. One and two letter words work. longer names work.

### Describe the bug

parameter names with three letters are ignored by the server. Interestingly, the route is still hit, but the parameter isn't available in context.

**Comment by pi0** [comment]
Hi. This issue should be fixed in `nitropack@v0.2.8`. Please try upgrading using `npx nuxi upgrade --force`.
