### ISSUE TITLE
Adding a suffix to an api file named `index.ts` matches incorrectly.

### ISSUE THREAD

**Issue by TheColaber** [nuxt/framework#4314]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27495976.e31c604`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `modules`, `colorMode`, `buildModules`
- Runtime Modules:  `@nuxtjs/color-mode@3.0.2`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@nuxtjs/tailwindcss@5.0.2`

### Reproduction

https://github.com/TheColaber/nuxt-3-bug

### Describe the bug

When adding the `.get` suffix, or any for that matter, to an API file named `index.ts`. It matches `/api/index` instead of `/api`.

**Comment by pi0** [comment]
Hi. This issue should be fixed in `nitropack@v0.2.8`. Please try upgrading using `npx nuxi upgrade --force`.
