### ISSUE TITLE
Can't use express router for api routes

### ISSUE THREAD

**Issue by Gusb3ll** [nuxt/framework#4316]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27495976.e31c604`
- Package Manager:  `yarn@4.0.0-rc.2`
- Builder:          `vite`
- User Config:      `meta`, `components`, `css`, `plugins`, `serverMiddleware`, `modules`, `buildModules`, `typescript`, `windicss`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.2.10`, `@vueuse/nuxt@8.2.5`, `@pinia/nuxt@0.1.8`

### Reproduction

I wanted to build serverless api using express with these config

- nuxt.config.ts
```
serverMiddleware: [{ path: '/api', handler: '~/server/api' }]
```

- server/api/index.ts
```
import express from 'express'
import authRouter from './routes/v1/auth'

const app = express()
app.use(express.json())

app.use('/v1/auth', authRouter)

app.use((req, res) => {
  res.status(200).json({ Status: 'API OK', created: Date.now().toString(), version: '1.0.0' })
})

export default app
```

- server/api/routes/auth.ts
```
import { Router } from 'express'

import stellar from '../../objects/stellar'

const authRouter = Router()

authRouter.get('/login', (req, res) => { return res.redirect(stellar.getLoginUrl()) })

export default authRouter
```

### Describe the bug

When I try to access ```/api/v1/auth/login``` I got the response 

```
{
"url": "/api/v1/auth/login",
"statusCode": 404,
"statusMessage": "Page not found: /api/v1/auth/login",
"message": "Page not found: /api/v1/auth/login"
}
```

but with only ```/api``` I got

```
{
"Status": "API OK",
"created": "1649827202155",
"version": "1.0.0"
}
```

### Logs

```shell
[Vue Router warn]: No match found for location with path "/api/v1/auth/login"
```

**Comment by ahku** [comment]
Kind of funny: I had this _exact setup_ (down to the `/v1/api` path) working last friday, as a solution to support dynamic API routes with more control over the methods, and had structured all my routes, controllers, etc. Then on sunday I was debugging stuff and at one point I just decided to update to "all the latest stuff". Suddenly my custom express server stopped working, as well as all my previous Nuxt api routes. After a lot of digging I realized that Nuxt has changed the API (`defineEventHandler()`). After a lot of refactoring and debugging I got the Nuxt stuff working but the custom server dream was dead.

On the plus side, Nuxt now supports the stuff I wanted to do with the express server (I think), but it feels a bit scary to move forward with a beta API tbh. The lock-in might be disadvantagous later if I decide to detach the server stuff and deploy it separately.

**Comment by danielroe** [comment]
would you provide a reproduction? 🙏

**Comment by Gusb3ll** [comment]
https://github.com/Gusb3ll/nuxt3-issue

**Comment by Sgadmer** [comment]
Hello, is there any solution?
I thought this guy found one (https://github.com/Gusb3ll/nuxt3-template)
He used pnpm to install dependencies. In this case, the application will work. But time after time. It may break after installing some new package, and even deleting node_modules won't help. Also, as I understand it, he did not use npx nuxi init, but a fork of your repository. I'm really looking forward to finding a solution to this problem.

**Comment by Sgadmer** [comment]
Hello, is there any solution?

**Comment by Aareksio** [comment]
@Sgadmer @Gusb3ll 
https://stackblitz.com/edit/github-5bzsuf?file=server%2Fapi.ts

Full example with `express`, works well once set up properly. Avoid `server/api` and `server/middleware` paths as they are automatically imported by nuxt. I'd recommend something akin to `server/app`.

I am not sure how compatible is h3's req/res with express, but seems to work with the basic example derived from OP's code.

**Comment by Sgadmer** [comment]
Holy Moly, its working) Thank you so much!
Actual solution was in this lines:
```
    { path: '/api', handler: '~/server/api.ts' }, // `/api/**` does NOT handle /api
    { path: '/api/**', handler: '~/server/api.ts' },
```
I washt use second (/**) prop, because in earlier version of nuxt (3.0.0-27488206.1ffcc74), it was just fine to send only first one and everything works well

**Comment by Gusb3ll** [comment]
> Holy Moly, its working) Thank you so much! Actual solution was in this lines:
> 
> ```
>     { path: '/api', handler: '~/server/api.ts' }, // `/api/**` does NOT handle /api
>     { path: '/api/**', handler: '~/server/api.ts' },
> ```
> 
> I washt use second (/**) prop, because in earlier version of nuxt (3.0.0-27488206.1ffcc74), it was just fine to send only first one and everything works well

Ah I see, I didn't use the ```/**``` prop too as it works for the prev version of nuxt3.
