### ISSUE TITLE
404 error when created file in /pages and redirect new router(page), until restart the srerver

### ISSUE THREAD

**Issue by metamist** [nuxt/framework#4318]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27496606.e43ba6e`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://v3.nuxtjs.org/guide/directory-structure/pages
i follow the doc guaid about pages, run with local environment

update(17/04) :
1. npx nuxi init nuxt3-app >> cd nuxt3-app >> npm install >> npm run dev

2. create a home page in /pages
  index.vue
  `<template><div>index page, go to <nuxt-link to='/test'>test</nuxt-link></div></template>`
  when i created index.vue and change code in app.vue to this
  `<template><NuxtPage/></template>`
 the home page can auto render, it works

3. but when i created test.vue in /pages
  `<template><div>test</div></template>`
  i click the test link in home page or i open the router link in broswer manually, the page render by 404 page
4. i restart the server, then it works

### Describe the bug

i created a new page file in /pages like /pages/test.vue
then the /test response 404 error
if i restart the server, then it works

**Comment by danielroe** [comment]
Would you provide a reproduction please? 🙏

**Comment by danielroe** [comment]
Does this happen for you on a fresh install?

**Comment by metamist** [comment]
> Does this happen for you on a fresh install?
i try new install three times, the issue is still.  then I gave up

**Comment by metamist** [comment]
> 

i sorry about that, because it's local dev environment, So i can't provide a demo

**Comment by metamist** [comment]
> Would you provide a reproduction please? 🙏


i sorry about that, because it's local dev environment, So i can't provide a demo

**Comment by danielroe** [comment]
As long as it's a fresh install, I can treat that as a reproduction - thanks 👍

**Comment by metamist** [comment]
> As long as it's a fresh install, I can treat that as a reproduction - thanks 👍

Sorry for taking so long to reply, This is how I go on

1. npx nuxi init nuxt3-app >> cd nuxt3-app >> npm install >> npm run dev

2. create a home page in /pages
  index.vue
  `<template><div>index page, go to <nuxt-link to='/test'>test</nuxt-link></div></template>`
  when i created index.vue and change code in app.vue to this
  `<template><NuxtPage/></template>`
 the home page can auto render, it works

3. but when i created test.vue in /pages
  `<template><div>test</div></template>`
  i click the test link in home page or i open the router link in broswer manually, the page render by 404 page
4. i restart the server, then it works

At first I thought it maybe cause by my computer, but after I changed the computer, it was still the same issue, I even reinstalled the win10 os

the terminal or broswer console didn't show more info except
`[Vue Router warn]: No match found for location with path "/test"`
`[Vue Router warn]: No match found for location with path "/__nuxt_error?url=/test&statusCode=404&statusMessage=Page+not+found:+/test&message=Page+not+found:+/test&description`

**Comment by Aareksio** [comment]
I stumbled upon this _issue_ multiple times during dev on Windows. A restart is required for routing to detect the new file. It may be specific to the OS.

**Comment by tintin10q** [comment]
It may be good to add this to the docs until it is fixed?

**Comment by danielroe** [comment]
I can't reproduce this. This  fix _should_ have resolved the issue: https://github.com/nuxt/framework/pull/4133. Would you add the following to your Nuxt config and let me know what it logs when you create a new path in your project?

```diff
  import { defineNuxtConfig } from 'nuxt3'

  export default defineNuxtConfig({
+   hooks: {
+     'builder:watch': console.log
+   }
  })
```

**Comment by metamist** [comment]
> I can't reproduce this. This fix _should_ have resolved the issue: #4133. Would you add the following to your Nuxt config and let me know what it logs when you create a new path in your project?
> 
> ```diff
>   import { defineNuxtConfig } from 'nuxt3'
> 
>   export default defineNuxtConfig({
> +   hooks: {
> +     'builder:watch': console.log
> +   }
>   })
> ```

I will display the following log in terminal according to the way you provided
` WARN  Duplicated imports "definePageMeta", the one from "D:/Node/nuxt3-app/node_modules/nuxt3/dist/pages/runtime/composables" has been ignored`

But I think the reason for this issue may be that the ide editor generates files, such as webstorm .idea or vscode .vscode
I try to use Notepad++ to create files in /pages, it works

**Comment by Aareksio** [comment]
When creating a new file via "New > File" and visiting `http://localhost:3000/test`
```
Nuxt CLI v3.0.0-27501460.04a72f8                                                                                                                                                                             12:51:29
                                                                                                                                                                                                             12:51:29
  > Local:    http://localhost:3000/
  > Network:  http://10.5.0.2:3000/
  > Network:  http://192.168.1.101:3000/

i Vite client warmed up in 1029ms                                                                                                                                                                            12:51:36
i Vite server warmed up in 575ms                                                                                                                                                                             12:51:36
√ Vite server built in 1126ms                                                                                                                                                                                12:51:37
√ Nitro built in 373 ms                                                                                                                                                                                nitro 12:51:37
add pages/test.vue                                                                                                                                                                                           12:51:47

 WARN  Duplicated imports "definePageMeta", the one from "X:/_polygon/nuxt3-issues/node_modules/nuxt3/dist/pages/runtime/composables" has been ignored                                                       12:51:47

√ Vite server built in 151ms                                                                                                                                                                                 12:51:47
√ Vite server built in 71ms                                                                                                                                                                                  12:51:47
change .git/index                                                                                                                                                                                            12:51:48
change pages/test.vue                                                                                                                                                                                        12:51:58
√ Vite server built in 114ms                                                                                                                                                                                 12:51:58
change .idea/workspace.xml                                                                                                                                                                                   12:51:58
√ Vite server built in 77ms                                                                                                                                                                                  12:51:58
```

When creating a new file via "New > Vue Component"

```
Nuxt CLI v3.0.0-27501460.04a72f8                                                                                                                                                                             12:53:31
                                                                                                                                                                                                             12:53:31
  > Local:    http://localhost:3000/                                                                                                                                                                                 
  > Network:  http://10.5.0.2:3000/                                                                                                                                                                                  
  > Network:  http://192.168.1.101:3000/                                                                                                                                                                             

i Vite client warmed up in 1080ms                                                                                                                                                                            12:53:38
i Vite server warmed up in 532ms                                                                                                                                                                             12:53:38
√ Vite server built in 1074ms                                                                                                                                                                                12:53:39
√ Nitro built in 384 ms                                                                                                                                                                                nitro 12:53:39
change pages/test.vue                                                                                                                                                                                        12:53:55
√ Vite server built in 79ms                                                                                                                                                                                  12:53:55
add .git/objects/21/08a3b6d9acb7cac2d7c2bb7879492d405337e4                                                                                                                                                   12:53:57
change pages/test.vue                                                                                                                                                                                        12:54:06
√ Vite server built in 103ms                                                                                                                                                                                 12:54:06
change .idea/workspace.xml                                                                                                                                                                                   12:54:07
√ Vite server built in 97ms                                                                                                                                                                                  12:54:07
[Vue Router warn]: No match found for location with path "/test"
[Vue Router warn]: No match found for location with path "/test"
[Vue Router warn]: No match found for location with path "/__nuxt_error?url=/test&statusCode=404&statusMessage=Page+not+found:+/test&message=Page+not+found:+/test&description"
[Vue Router warn]: No match found for location with path "/test"                                                                                                               
```

This is reproducible.

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`                                                                                                                                                                                       
- Nuxt Version:     `3.0.0-27501460.04a72f8`                                                                                                                                                                         
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `hooks`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

WebStorm 2022.1
Build #WS-221.5080.193, built on April 10, 2022

**Comment by metamist** [comment]
> 

I don't know . I'll use the candidate version and have a look

**Comment by metamist** [comment]
It may be specific to the OS, close issue

**Comment by metamist** [comment]
It may be specific to the OS, close issue

**Comment by tintin10q** [comment]
> It may be specific to the OS, close issue

I was on ubuntu when it happened to me.

**Comment by metamist** [comment]
> > It may be specific to the OS, close issue
> 
> I was on ubuntu when it happened to me.

**Comment by metamist** [comment]
> > It may be specific to the OS, close issue
> 
> I was on ubuntu when it happened to me.

Do you use webstorm? Try vscode instead, but using vscode will register the route in real time, but it will not refresh the browser page content

**Comment by metamist** [comment]
now i use Nuxt CLI v3.0.0-rc.2, vscode is not working too, I'm going crazy

**Comment by AjaeOnTheRun** [comment]
it's still not working. fresh install for me every time. i hope this gets sorted out soon. in the meantime it's back to normal vue3.

**Comment by frbuceta** [comment]
It's happening to me too in `v3.0.0-rc.2-27530889.9e5a3cd`

**Comment by metamist** [comment]
> It's happening to me too in `v3.0.0-rc.2-27530889.9e5a3cd`

Have you solved this problem?

**Comment by Administrator-M** [comment]
I was on windows,It works when I access it with the tag "<NuxtLink to="/test">",but when open the router link in broswer manually, the page render by 404 page

**Comment by Administrator-M** [comment]
I was on windows,It works when I access it with the tag "NuxtLink",but when open the router link in broswer manually, the page render by 404 page
