### ISSUE TITLE
server-side publicRuntimeConfig is empty

### ISSUE THREAD

**Issue by shinguweb96** [nuxt/framework#4322]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `bridge`, `runtimeConfig`, `publicRuntimeConfig`, `privateRuntimeConfig`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.2.5`, `@nuxt/bridge@3.0.0-27496606.e43ba6e`
------------------------------

### Reproduction

https://codesandbox.io/s/cocky-sanderson-p66s2i?file=/pages/index.vue

you can check the console.log in server is empty and in client is correctly.

### Describe the bug

In Nuxt2 Bridge SERVER SIDE publicRuntimeConfig & privateRuntimeConfig are totally empty, in client side are okay..
In the reproduction in index page I show a console.log($config) and is empty in server side.

**Comment by danielroe** [comment]
see https://github.com/nuxt/framework/issues/4294#issuecomment-1097884013
