### ISSUE TITLE
Nuxi info command throws 'Invalid or unexpected token' error

### ISSUE THREAD

**Issue by markusgeert** [nuxt/framework#4331]
### Environment

Error occurs both on my local Windows 10 machine and the Codesandbox, on the latest Nuxt version (3.0.0-27497374.59593a0)

### Reproduction

https://codesandbox.io/s/interesting-breeze-7uip0w

`npx nuxi info`

### Describe the bug

The `nuxi info` command throws `Invalid or unexpected token` error on a fresh Nuxt project.

### Logs

```shell
Nuxt CLI v3.0.0-27497374.59593a0                                                                                                      

 ERROR  Invalid or unexpected token                                                                                                   

  at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:115:18)
  at ESMLoader.moduleProvider (node:internal/modules/esm/loader:289:14)
```

**Comment by pi0** [comment]
Should be resovled by https://github.com/nuxt/framework/pull/4336
