### ISSUE TITLE
.nuxt/views/document.template.mjs' does not provide an export named 'default'

### ISSUE THREAD

**Issue by mlsjla** [nuxt/framework#4349]
### Environment

    "@pinia/nuxt": "^0.1.8",
    "@vueuse/nuxt": "^7.4.2",
    "autoprefixer": "^10.4.2",
    "bootstrap-icons": "^1.8.1",
    "daisyui": "^2.0.6",
    "element-plus": "^2.0.2",
    "eslint": "^8.5.0",
    "nuxt3": "^3.0.0-27496606.e43ba6e",
    "pinia": "^2.0.11"

### Reproduction

```
 ERROR  [worker reload] [worker init] The requested module '/Users/mac/.webcode/gin-nuxt/web/.nuxt/views/document.template.mjs' does not provide an export named 'default'

  import htmlTemplate from '.nuxt/views/document.template.mjs';
  ^^^^^^^^^^^^
  SyntaxError: The requested module '.nuxt/views/document.template.mjs' does not provide an export named 'default'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
  at async loadESM (node:internal/process/esm_loader:88:5)
```

### Describe the bug

npm run dev  show this

**Comment by danielroe** [comment]
Would you provide a reproduction please? 🙏

**Comment by mlsjla** [comment]
@danielroe   I can not provide the repo because the code is so more

but I  find  when I import ElementPlus  https://github.com/element-plus/element-plus  
the error show

and when I remove  ElementPlus  ,  It done.

version of  last mounth It's OK but the latest version run show error

**Comment by danielroe** [comment]
I would guess there is another error message above this one, which should indicate the real problem.

**Comment by mlsjla** [comment]
@danielroe  

I  remove some code ...
https://github.com/mlsjla/testnuxt3

But  I   tun  10 times ....  only once get error .  others  is run no error.

**Comment by mlsjla** [comment]
I wonder  if is the file too big？
