### ISSUE TITLE
nuxt3 meta tag error

### ISSUE THREAD

**Issue by todaynogada** [nuxt/framework#4394]
### Environment

node 16.2
npm 8.5.0

### Reproduction
https://v3.nuxtjs.org/guide/directory-structure/nuxt.config
https://v3.nuxtjs.org/guide/features/head-management
I followed the guide in the documentation.

### Describe the bug

nuxt3 meta tag error

1. nuxt.config.ts
`{ charset: 'utf-8' },`
output - html
```html
<meta charset="utf-8">
<meta charset="utf-8">
```
Two appear as duplicates.

2. nuxt.config.ts
` { name: 'title', content: 'asd' },`
output - html
```html
<meta hid:'title' name: 'title', content: 'asd' >
```

In html, hid is also output. can i get rid of this?
Also, does the hid phrase affect seo?

And when meta tags are entered together in nuxt.config.ts and individual pages, both appear. It appears as a duplicate, and even if both are aliased with hid, 2 are output as duplicates.

3. nuxt.config.ts
4. 
` { hid:'canonical', rel: 'canonical', href: 'https://domain/' }`

index.vue
```js
 useHead({
            link: [
                { hid:'canonical', rel: 'canonical', href: 'https://domain/' }
            ],
        })
    }
```
Catalina also shows 2 duplicate tags in html.

nuxt.confug.ts common option add
```
    ssr : false,
    target: 'server',
```
help.

Lastly, after build, not only meta tag, but also sitemap should be provided to optimize for reflection in seo?

It seems that the tags do not recognize the SEO optimization on the Naver site.
https://www.naver.com/
![eqqeggeqgeqgqegeqgqe](https://user-images.githubusercontent.com/35400023/163665803-3a8bf49c-2810-421c-9e73-ef599033008f.PNG)

![qqgeqgeeqgeqg](https://user-images.githubusercontent.com/35400023/163666003-f51e19cd-343d-472d-ac39-e4c6cf290830.PNG)

**Comment by danielroe** [comment]
Would you provide a reproduction please? 🙏

**Comment by danielroe** [comment]
[Here's a reproduction](https://stackblitz.com/edit/github-e3vjhm) to start from. I can only replicate the `<link rel="canonical">` issue and have raised an upstream bug report with `vueuse/head` to track: https://github.com/vueuse/head/issues/64.

**Comment by jan-miksik** [comment]
before, sites
https://developers.facebook.com/tools/debug/
https://cards-dev.twitter.com/validator
did not show metatags for me

After change to `ssr: true,` it loads the metatags
