### ISSUE TITLE
Cannot start nuxt:  Nitro entry is missing! Is "server" preset correct? 

### ISSUE THREAD

**Issue by codelegant** [nuxt/framework#4397]
### Environment

- Operating System: `Darwin`
- Node Version:     `v17.7.1`
- Nuxt Version:     `3.0.0-27501460.04a72f8`
- Package Manager:  `npm@8.5.2`
- Builder:          `vite`
- User Config:      `nitro`, `publicRuntimeConfig`, `privateRuntimeConfig`, `app`, `css`, `build`, `modules`, `alias`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.1.8`
- Build Modules:    `-`

### Reproduction

I can't Reproduction in codesandbox

### Describe the bug

Install the latest Nuxt3，and run `npx nuxi dev`
<img width="741" alt="image" src="https://user-images.githubusercontent.com/12785928/163673332-693b846d-abf7-4d03-b1c3-0d0c364a5d9f.png">

**Comment by hi94740** [comment]
Same issue here. I tried `browser` and `browser-worker` and got the same error.

**Comment by anish2690** [comment]
@danielroe it can be reproducible with 

```ts
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  nitro:{
    preset:'server'
  }
})

**Comment by danielroe** [comment]
The preset has been renamed. See https://nitro.unjs.io/guide/presets.html for a list of available presets.
