### ISSUE TITLE
Cloudflare - Cookies not parsed in server

### ISSUE THREAD

**Issue by xar** [nuxt/framework#4402]
### Environment

Nuxt CLI v3.0.0-27501460.04a72f8                                            21:56:40
Nuxt project info:                                                          21:56:42

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-27501460.04a72f8`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `css`, `publicRuntimeConfig`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Use `useCookie` on cloudflare / miniflare in server middleware or `api` route.

### Describe the bug

When deploying on CF Workers or running via miniflare locally - there is some problem with parsing of `event.req` because cookies are empty - when I try to debug it I can see that `event.req.headers` is array of type `HeadersList`(https://github.com/cloudflare/miniflare/blob/6c26e320611f5209ba928cb5fba0013b8d4f2a20/packages/core/src/standards/http.ts#L67) but It seems like nuxt is not doing any parsing - because when running outside CF enviroment that request get converted and `headers` are accessible as Object.

```
event.req.headers in (server/api)
HeadersList(40) [
  'accept',
  'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'accept-encoding',
  'gzip, deflate, br',
  'accept-language',
  'en-GB,en-US;q=0.9,en;q=0.8',
  'cache-control',
  'no-cache',
  'cf-connecting-ip',
  '127.0.0.1',
  'cf-ipcountry',
  'SK',
  'cf-ray',
  'ff8694c8c4f9c515',
  'cf-visitor',
  '{"scheme":"https"}',
  'cookie',
  'sb:ac....
```

**Comment by xar** [comment]
I was able to fix that by calling in middleware:
```
if (event.req.headers?.keys?.()) {
        const newHeaders = {};
        for (const header of event.req.headers) {
            newHeaders[header[0]] = header[1];
        }
 }
``` - so manually parsing Headers. After that I'm able to at least get object with all the headers and cookie to parse.

Would love to help fix that overall in framework - but not sure where and how to start.

**Comment by PhaxeNor** [comment]
It's part of H3. https://github.com/unjs/h3/blob/main/src/utils/cookie.ts
Where it's using `event.req.headers.cookie`, which doesn't work on CF (`event.req.headers.get('cookie')` is whats used there)
I've just taken the useCookies and useCookie part, and created a temporary util that uses what CF supports. 

I guess this would be the relevant issue on H3 https://github.com/unjs/h3/issues/81

**Comment by danielroe** [comment]
This is no longer reproducible for me. Let me know if not and I can reopen.
