### ISSUE TITLE
Setting NUXT_APP_BASE_URL causes memory leak when navigating to route that does not exist 

### ISSUE THREAD

**Issue by adamcikado** [nuxt/framework#4404]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27501460.04a72f8`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Add `<NuxtPage />` to `app.vue`
2. Create `pages/index.vue`
3. Build the app
4. Run the app with `NUXT_APP_BASE_URL=/foo node .output/server/index.mjs`
5. Navigate to page that does not exist `http://localhost:3000/foo/test` or `http://localhost:3000`
6. Page will load indefinitely until it crashes because of `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`

### Describe the bug

`NUXT_APP_BASE_URL` env variable does not work as expected.

**Comment by anburocky3** [comment]
Any update?

**Comment by danielroe** [comment]
This should now be resolved if you run `npx nuxi upgrade` or `yarn upgrade nuxt3`/`npm up nuxt3`: https://github.com/unjs/nitro/pull/122. Let me know if not...
