### ISSUE TITLE
Bridge + Pinia = a shit 

### ISSUE THREAD

**Issue by n4an** [nuxt/framework#4405]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.5.4`
- Builder:          `webpack`
- User Config:      `bridge`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `pwa`
- Runtime Modules:  `@nuxtjs/pwa@3.3.5`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@nuxt/bridge@3.0.0-27498038.f18e68b`

### Reproduction

It say to remove incompatible and obsolete modules remove like @vue/composition-api from your dependencies.

But when try to use Pinia it say vue-composition-api is required.

WTF

### Describe the bug

Nuxt bridge not work.
Nuxt 3 not work.
Nothing not work.
It's a shit!

**Comment by pi0** [comment]
I've to close this issue because of a bad tune and lacking details. If you do this again, unfortunately, we have to ban you completely. Thanks for understanding.
