### ISSUE TITLE
How to deploy Firebase Hosting?

### ISSUE THREAD

**Issue by anburocky3** [nuxt/framework#4416]
i have these `firebase.json`

```json
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "source": ".output/server",
    "runtime": "nodejs16"
  },
  "hosting": {
    "public": ".output/public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}

```

```
λ firebase deploy

=== Deploying to 'project-79XXX'...

i  deploying firestore, functions, hosting
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
+  cloud.firestore: rules file firestore.rules compiled successfully

Error: There was an error reading .output\server\package.json:

 .output\server\index.js does not exist, can't deploy Cloud Functions
```

Any example would be better.

**Comment by dikesh** [comment]
Can you provide the project info and steps to reproduce the problem?

**Comment by anburocky3** [comment]
> Can you provide the project info and steps to reproduce the problem?

For the reproduce, here is the [repo](https://github.com/anburocky3/iragugal-web)

**Comment by danielroe** [comment]
What are the commands you are running before `firebase deploy`?

**Comment by anburocky3** [comment]
> 

```properties
yarn build (which runs nuxi build)
yarn start (tried to check the build, before pushing production, **It worked, I can see the output**)
````

**Comment by danielroe** [comment]
You should follow the instructions here: https://v3.nuxtjs.org/docs/deployment/firebase. These are the commands you should run:

```bash
NITRO_PRESET=firebase yarn build
firebase deploy
```

**Comment by anburocky3** [comment]
> You should follow the instructions here: https://v3.nuxtjs.org/docs/deployment/firebase. These are the commands you should run:
> 
> ```shell
> NITRO_PRESET=firebase yarn build
> firebase deploy
> ```

I received this error.
![image](https://user-images.githubusercontent.com/15264938/164013181-a02f2781-7abd-46dd-a070-1860b8da9f45.png)

**Comment by anburocky3** [comment]
Do we need to install these, even though we are not using any in our codes? Is this for hosting alone?

```
yarn add -D firebase-admin firebase-functions firebase-functions-test
```

**Comment by danielroe** [comment]
Yes, firebase requires that these are installed.

**Comment by anburocky3** [comment]
Great, as per the docs, it is saying, I have to be in `blaze plan` to work. can't we host it somewhere like `github-pages` for this simple stuff? Just some hobby project and not likely to enroll into blaze plan for just the hosting.

**Comment by danielroe** [comment]
There are lots of other deployment targets other than firebase. See https://nitro.unjs.io/guide/presets.html.
