### ISSUE TITLE
Meta url is empty object in production build

### ISSUE THREAD

**Issue by m0ksem** [nuxt/framework#4429]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.0.0-27501460.04a72f8`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

app.vue on fresh project

```vue
<template>
  <div>
    {{ meta }}
    {{ url }}
  </div>
</template>

<script setup>
const meta = import.meta
const url = import.meta.url
</script>
```

### Describe the bug

import_meta compiles to empty object after running `build` script.

### Additional context
I want to load submodules using ` import.meta.globEager` (I know ` import.meta.glob` not working yet), so I need a path from current module, that I can use as key in ` import.meta.globEager` return.

Should I use `mlly`?

This work well in develop mode.

**Comment by danielroe** [comment]
Looks like there have been some commits upstream in vite to resolve this issue. You might follow https://github.com/vitejs/vite/issues/5270.

**Comment by danielroe** [comment]
This is no longer reproducible.
