### ISSUE TITLE
nuxt3-rc generate and  url is not relative Url 

### ISSUE THREAD

**Issue by mlsjla** [nuxt/framework#4484]
### Environment

Nuxt CLI v3.0.0-rc.0-27508091.78fcbcf                                                                             10:48:08
RootDir: /Users/mac/.webcode/gin-nuxt/web                                                                         10:48:11
Nuxt project info:                                                                                                10:48:11

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.0-27508091.78fcbcf`
- Package Manager:  `npm@8.5.4`
- Builder:          `vite`
- User Config:      `meta`, `ssr`, `buildModules`, `css`, `components`, `publicRuntimeConfig`, `experimental`, `vite`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@7.7.1`, `@pinia/nuxt@0.1.8`

### Reproduction

all

### Describe the bug

```
<head >
  <link rel="stylesheet" href="/_nuxt/entry.cabc84ae.css">
</head>
```

I run  `npm run generate .`

But I  get  path `/`

I  wish It is `./`

### Additional context

no

### Logs

```shell
no
```

**Comment by danielroe** [comment]
You can either run:

```
NUXT_APP_BASE_URL=./ npm run generate
```

Or set it in your nuxt config:

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  app: {
    baseURL: process.env.NODE_ENV === 'production' ? './' : '/'
  }
})
```

Does that solve your issue?

**Comment by mlsjla** [comment]
thanks I  generate success.... 
But  I  find  a error 

```
entry-5c534801.mjs
```

chrome  Can't referer  because  of "cross-origin"

```
Request URL: .output/public/_nuxt/entry-5c534801.mjs
Referrer policy: strict-origin-when-cross-origin
Provisional headers are shown
Learn more
Origin: null
Referer
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1
```

**Comment by danielroe** [comment]
That sounds like an issue with your hosting rather than Nuxt. Would you provide a reproduction?

**Comment by mlsjla** [comment]
thank u for reply...

I  update  the repo..   
https://github.com/mlsjla/testnuxt3

**Comment by mlsjla** [comment]
I  just  open the index.html file  in  finder...
so The host is   file path...

**Comment by danielroe** [comment]
Would you try with the latest version, currently 3.0.0-rc.2-27530596.a862a67? (A related issue was resolved in https://github.com/nuxt/framework/pull/4844.)

**Comment by mlsjla** [comment]
I try again  and find some files is done ,but three files is also cros error.

```
.output/public/_nuxt/default-8aafa2a6.mjs
output/public/_nuxt/index-7262e5c7.mjs
```
