### ISSUE TITLE
useFetch not firing in SSR

### ISSUE THREAD

**Issue by tntsoft** [nuxt/framework#4486]
### Environment

Nuxt CLI v3.0.0-27506322.90da56a                                                                                                                                                09:17:48
RootDir: /opt/homebrew/var/www/PHP8.0/rr-frontend                                                                                                                               09:17:49
Nuxt project info:                                                                                                                                                              09:17:49

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.9.0`
- Nuxt Version:     `3.0.0-27506322.90da56a`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `server`, `publicRuntimeConfig`, `build`, `buildModules`, `css`, `intlify`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@intlify/nuxt3@0.1.10`
------------------------------

### Reproduction

**Repo:** [https://github.com/tntsoft/nuxt-use-fetch-ssr-reproduction](https://github.com/tntsoft/nuxt-use-fetch-ssr-reproduction)

**Note:**
I am using https://jsonplaceholder.typicode.com/ as the base URL, I've included the .env file in this repo. I've basically left all my modules and configurations in exactly as my main project, stripping out the non-essentials in order to just demonstrate the problem.

**Instructions:** 
- use http://frontend.test.localhost:3000 to access the site (not sure if it matters or not)
- at first the posts will load and the JSON will display
- refresh the page, nothing comes up

### Describe the bug

When first accessing the page, the JSON displays. Upon refreshing the page, it does not show up.

### Additional context
This is in reference to the comments posted in #4017

**Comment by danielroe** [comment]
It is not firing on ssr because it is in `mounted` which only runs on client-side. See updated reproduction: https://stackblitz.com/edit/github-y6onct?file=components%2FBillboard.vue

**Comment by tntsoft** [comment]
Oh, man, I'm sorry for wasting your time @danielroe. Appreciate your time, and thank you for the updated reproduction code!

I am getting a response now from the server (yay)... but it's an HTML response instead of JSON as the headers aren't registering in SSR. I'm using ```headers: useRequestHeaders(['Accept', 'Cookie', 'X-XSRF-TOKEN'])```, but it does not send my previously sent ```'Accept: 'application/json'``` or ```'Cookie'``` headers.

I can't really wrap my head around how exactly SSR works, how it communicates with the frontend in order to get the correct Headers from it. Is there any tutorial (paid or otherwise), or documentation that is currently out that can help me? I understand that the documentation for Nuxt 3 is still being written...

**Comment by danielroe** [comment]
When you request an HTML page from Nuxt (e.g. `/about`), `useRequestHeaders` will take the headers you specify from that request and pass them on to any 'internal' fetches that happen on the server. It won't do it automatically, and it won't preserve cookies or headers between those requests - you have to be explicit about it: https://v3.nuxtjs.org/guide/features/data-fetching/#isomorphic-fetch-and-fetch.

**Comment by danielroe** [comment]
`Cookie` will just be a string at this point, not an object. And it will be lowercase. There is a `useCookie` helper that handles getting & parsing the cookie for you. https://v3.nuxtjs.org/api/composables/use-cookie#usecookie.
