### ISSUE TITLE
Can't infer correct NuxtApp property type after registering @nuxtjs/color-mode

### ISSUE THREAD

**Issue by LoTwT** [nuxt/framework#4496]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.7.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/color-mode@3.0.2`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-yq4qz8

### Describe the bug

When using a property provided by a custom plugin, it can't infer correct NuxtApp property type that always shows `any` after registering `@nuxtjs/color-mode`. 

But it works when the property used in template alone.

Please try the demo in VS Code.

**Comment by danielroe** [comment]
Thank you! Moved to https://github.com/nuxt-community/color-mode-module/issues/138 for now. If it's an issue with Nuxt itself, I'll reopen here.
