### ISSUE TITLE
When build app useFetch with transform option will return data with value null on client side

### ISSUE THREAD

**Issue by lhahut96** [nuxt/framework#4497]
### Environment

Operating System: Windows_NT
Node Version: v16.14.2
Nuxt Version: 3.0.0-rc.1
Package Manager: npm@8.7.0
Builder: vite
User Config: modules
Runtime Modules: @nuxtjs/color-mode@3.0.2
Build Modules: -

### Reproduction

https://github.com/ntt1182/reproduction-nuxt3

### Describe the bug

When using nuxi dev app will run normally without return normal data but when build and start code with node, client-side will return null value data
![image](https://user-images.githubusercontent.com/67304218/164433298-e15ae219-03ba-4819-a14b-2399f9b9869f.png)

**Comment by danielroe** [comment]
The workaround for the moment is to provide a custom key, e.g.:

```js
const { data } = await useFetch('/some/path', {
  transform: data => data,
  key: 'my-key'
})
```

**Comment by Aareksio** [comment]
In relation to #4553, this leads to strange behavior (_bailed hydration?_), _probably_ related to swallowed error. It may be good idea to figure out where the error is caught and ignored, in case similar issue occurs in the future.

<details>
<summary>Dev</summary>

![image](https://user-images.githubusercontent.com/11166786/165073691-5242a02a-1830-4b54-ab25-f8b9b7f6353b.png)

</details>

<details>
<summary>Build + Preview</summary>

![image](https://user-images.githubusercontent.com/11166786/165073589-6f50cc39-def0-46d1-8b9e-58e73fbdf511.png)

</details>

https://stackblitz.com/edit/github-ycnvlb
