### ISSUE TITLE
Cannot import json files containing an `exports` key

### ISSUE THREAD

**Issue by lihbr** [nuxt/framework#4503]
## Environment

- Operating System: `Windows_NT` (didn't try on MacOS as this doesn't seem like an OS-related issue)
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`

### How to reproduce
1. Setup a new app
   ```bash
   npx nuxi init nuxt-app && cd nuxt-app && npm install
   ```
2. Create a new JSON file featuring and `exports` key
   ```bash
   echo { "foo": "bar", "exports": "baz" } > data.json
   ```
3. Import file in `app.vue`
   ```vue
   <template>
     <div>
       {{ data }}
     </div>
   </template>

   <script setup>
   import data from './data.json'
   </script>
    ```
4. Launch Nuxt
   ```bash
   npm run dev
   ```

### Reproductions

(left right, top bottom: `rc.1` working > `rc.1` broken > 14d9e8e last working commit > 51ae426 first breaking commit)

![image](https://user-images.githubusercontent.com/25330882/164453121-e0ae02d4-85eb-41b6-bc43-214d5629bec6.png)

#### `rc.1` working example (no `exports` key)
[rc.1-working.zip](https://github.com/nuxt/framework/files/8530637/rc.1-working.zip)

#### `rc.1` broken example (featuring `exports` key)
[rd.1-broken.zip](https://github.com/nuxt/framework/files/8530641/rd.1-broken.zip)

#### 14d9e8e last working commit example (featuring `exports` key)
[14d9e8e-lastWorkingCommit.zip](https://github.com/nuxt/framework/files/8530644/14d9e8e-lastWorkingCommit.zip)

#### 51ae426 first breaking commit example (featuring `exports` key)
[51ae426-firstBreakingCommit.zip](https://github.com/nuxt/framework/files/8530648/51ae426-firstBreakingCommit.zip)

### Describe the bug

Nuxt errors when trying to import a JSON file featuring an `exports` key and likely others(?).

### Additional context

I think I managed to pinpoint the source of the issue/regression:

Working on this commit: https://github.com/nuxt/framework/commit/14d9e8e4ae16c07a813b0fd73b4b1c1bff1542ad
Broke after this commit: https://github.com/nuxt/framework/commit/51ae426d4cce2fb5084ed855d06dea970198bf81
Diffs: https://github.com/nuxt/framework/compare/14d9e8e4ae16c07a813b0fd73b4b1c1bff1542ad...51ae426d4cce2fb5084ed855d06dea970198bf81

I discovered that one as we import our `package.json` file to retrieve the package name in Prismic module: https://github.com/nuxt-community/prismic-module/blob/6c9931b3dfb777322e182bc1aa1bb80a39405794/src/runtime/plugin.ts#L6

Related (Prismic module): https://github.com/nuxt-community/prismic-module/issues/160

I fallback to hardcode the value for now, but it'll be nice to be able to do it again ☺️

Cheers 💚

**Comment by rseeley** [comment]
I'm also getting the `[nuxt] [request error] Identifier 'exports' has already been declared` error, but we're not importing any JSON files with the key `exports` directly in our code. I'm currently on `v3.0.0-27488206.1ffcc74` and don't experience this error, but upgrading to `v3.0.0-rc.1`, it shows up. 

I'm using `@nuxtjs/prismic` (`3.0.0-alpha.5`) and removing it fixes the issue.

**Comment by lihbr** [comment]
> I'm also getting the `[nuxt] [request error] Identifier 'exports' has already been declared` error, but I'm not importing any JSON files with the key `exports` directly in our code. I'm currently on `v3.0.0-27488206.1ffcc74` and don't experience this error, but upgrading to `v3.0.0-rc.1`, it shows up.
> 
> I'm using `@nuxtjs/prismic` (`3.0.0-alpha.5`) and removing it fixes the issue.

If you can provide a minimal repro with `rc.1` like above that'd help ☺️

**Comment by danielroe** [comment]
This is now resolved on the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) (or you can enable `experimental.viteNode` if you are on a previous RC).
