### ISSUE TITLE
Primevue: Toast duplicates elements after it

### ISSUE THREAD

**Issue by cmgriffing** [nuxt/framework#4513]
### Environment

- Operating System: `Darwin`
- Node Version:     `v17.9.0`
- Nuxt Version:     `3.0.0-27491748.3186841`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `plugins`, `modules`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Example: https://nuxt3-primevue-toast-issue.vercel.app/
Source: https://github.com/cmgriffing/nuxt3-primevue-toast-issue

### Describe the bug

When using PrimeVue, their Toast component causes items after it to be duplicated during the hydration step.

The navigation issue seen in the demo is separate.

### Additional context

I have reported this bug over on primevue as well. I wanted to report it here in case there needs to be cross-communication between the projects.

https://github.com/primefaces/primevue/issues/2482

### Logs

```shell
runtime-core.esm-bundler.js:38 [Vue warn]: Hydration node mismatch:
- Client vnode: div 
- Server rendered DOM: <!--teleport end-->  
  at <Broken onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/broken" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView > 
  at <NuxtPage> 
  at <App key=1 > 
  at <NuxtRoot>
```

**Comment by danielroe** [comment]
This is resolved upstream.
