### ISSUE TITLE
 WARN  [SSR] Error transforming D:/wstStudy/blog-ssr/types: EISDIR: illegal operation on a directory, read   

### ISSUE THREAD

**Issue by laobg** [nuxt/framework#4517]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `dev`, `publicRuntimeConfig`, `css`, `meta`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

.

### Describe the bug

I trying to import an interface from  ``~~/types/index.d.ts``.Throws a warning when I start dev,and it can't run.
![1650598730(1)](https://user-images.githubusercontent.com/23148342/164591596-3bc80973-a076-435d-b7df-562a932d1c34.png)
![1650598751(1)](https://user-images.githubusercontent.com/23148342/164591631-456674f7-dac3-4c61-bcdb-60fbe2014109.png)
![1650598777(1)](https://user-images.githubusercontent.com/23148342/164591657-adb440cc-f602-4de1-9bc6-0bda090d69b0.png)

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

Also, I would advise against importing from a declaration file. Instead, you can rename `~/types/index.d.ts` to `~/types/index.ts`, and I'd also suggest trying `import type { ArticleList }`.

**Comment by laobg** [comment]
Thanks,``import type { ArticleList }``  solved my problem.
