### ISSUE TITLE
[NuxtLink] active-class works like exact-active-class

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#4526]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1-27510277.648a70e`
- Package Manager:  `npm@8.7.0`
- Builder:          `vite`
- User Config:      `css`, `buildModules`, `vite`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`

### Reproduction

https://stackblitz.com/edit/github-u2sqdh?file=layouts/default.vue

### Describe the bug

In the nuxt-link component, the `active-class` prop works like `exact-active-class`.

For example as in playback:
path `/`: `active-class` is working and `exact-active-class` too.
path `/[id]`: `active-class` does not work and `exact-active-class` does not and should not work.

**Comment by danielroe** [comment]
This is a change in Vue Router: https://router.vuejs.org/guide/migration/#removal-of-the-exact-prop-in-router-link

**Comment by frbuceta** [comment]
I am not using the exact prop. You can see it in the example. @danielroe

**Comment by danielroe** [comment]
This is vue-router behaviour: https://stackblitz.com/edit/github-u2sqdh-pxek8u.

**Comment by maximilliangeorge** [comment]
I think the router link classes aren't being applied unless you add a pages and/or layouts directory. After adding these the link classes started getting applied as expected.
