### ISSUE TITLE
runtimeConfig array values duplication

### ISSUE THREAD

**Issue by Megarsh** [nuxt/framework#4529]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Create a Nuxt3 app
2. Add runtimeConfig with any array properties

### Describe the bug

Array properties of  `useRuntimeConfig()` are returned with duplicate values

### Additional context

Example usage in my case
```
runtimeConfig: {
    public: {
        locales: [
            {
                code: 'code',
                name: 'name'
            },
            {
                code: 'code',
                name: 'name'
            }
        ]
    }
}
```

Also tested outside of the public scope same issue there

**Comment by danielroe** [comment]
Is this just on server-side? Possibly tracked in https://github.com/unjs/nitro/issues/139.

**Comment by Megarsh** [comment]
> Is this just on server-side? Possibly tracked in [unjs/nitro#139](https://github.com/unjs/nitro/issues/139).

As far as I can tell the same issue is persistent with any useRuntimeConfig() usage (client/server/plugin etc..)

**Comment by Tahul** [comment]
Hey @danielroe ; I can confirm it's the same issue! 😄

Exactly the same setup as the reproduction in the issue!

**Comment by danielroe** [comment]
This should be resolved if you run `yarn upgrade nuxt` or `npm upgrade nuxt `.

Let me know if not and we can reopen.

**Comment by Megarsh** [comment]
> 

Didn't work with `npm upgrade nuxt` had to remove `.nuxt`, `package.lock.json`, `node_modules` and do fresh install but the issue seems fixed

**Comment by engvie** [comment]
This happened to me too:

nuxt.config.ts
`    runtimeConfig: {
        public: {
            locales: ['sv', 'en'],
        },
    },`
`const locales = useRuntimeConfig().public.locales;
console.log(locales);`

> ["sv","en","sv","en"]
