### ISSUE TITLE
Server Routes defineEventHandler TypeScript typing error on complex return types

### ISSUE THREAD

**Issue by zelid** [nuxt/framework#4532]
### Environment

https://stackblitz.com/

### Reproduction

Open https://stackblitz.com/edit/github-bfy4sf?file=server%2Fapi%2Fmountain.ts

### Describe the bug

On https://v3.nuxtjs.org/guide/features/server-routes new `defineEventHandler()` has been mentioned as a new recommended way to define server routes.

Any complex return type gives TypeScript error like:

```
Argument of type '() => { ok: true; something: { prop1: boolean; }[]; }' is not assignable to parameter of type 'EventHandler<H3Response>'.
  Type '{ ok: true; something: { prop1: boolean; }[]; }' is not assignable to type 'H3Response'.
    Type '{ ok: true; something: { prop1: boolean; }[]; }' is not assignable to type 'Record<string, _JSONValue<string | number | boolean>>'.
      Property 'something' is incompatible with index signature.
        Type '{ prop1: boolean; }[]' is not assignable to type '_JSONValue<string | number | boolean>'.
          Type '{ prop1: boolean; }[]' is not assignable to type '(string | number | boolean)[]'.
            Type '{ prop1: boolean; }' is not assignable to type 'string | number | boolean'.
              Type '{ prop1: boolean; }' is not assignable to type 'true'.(2345)
```

For example this code gives TypeScript error:
```
import { defineEventHandler } from 'h3';

export default defineEventHandler(() => {
  return {
    ok: true,
    something: [
      {
        prop1: true,
      },
    ],
  };
});
```

While this code works well:
```
import { defineEventHandler } from 'h3';

export default defineEventHandler(() => {
  return {
    ok: true,
    something: [
     'a', 'b', 'c'
    ],
  };
});
```

Should `defineEventHandler()` be avoided with TypeScript or is there a way to resolve the type mismatch issue?

**Comment by zelid** [comment]
Could be this is the fix:
https://github.com/unjs/h3/commit/e9a07cbef57df04c104fa169af5fef7f2613daae

**Comment by danielroe** [comment]
The originally reported example should be resolved with latest h3, although we can keep this issue open to track https://github.com/unjs/h3/issues/112.
