### ISSUE TITLE
Cannot run v3.0.0-rc.1 in my computer - "Cannot find module"

### ISSUE THREAD

**Issue by lucassimines** [nuxt/framework#4542]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

This error only occurs in my computer, can't reproduce on StackBlitz.

### Describe the bug

Cannot start the application with Nuxt `v3.0.0-rc.1`.

### Additional context

I'm currently using the version `"nuxt3": "^3.0.0-rc.0-27507546.fc8bcdb"` that actually works in my computer.

### Logs

```shell
Nuxt CLI v3.0.0-rc.1                                                  14:12:08
                                                                      14:12:08
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.68.102:3000/

ℹ Vite client warmed up in 399ms                                      14:12:10
ℹ Vite server warmed up in 208ms                                      14:12:10
✔ Vite server built in 390ms                                          14:12:11

 ERROR  [worker reload] [worker init] Cannot find module '/Users/lucassimines/FMCX/nuxt-app/.nuxt/views/document.template.mjs' imported from /Users/lucassimines/FMCX/nuxt-app/.nuxt/dev/index.mjs

  at new NodeError (node:internal/errors:371:5)
  at finalizeResolution (node:internal/modules/esm/resolve:418:11)
  at moduleResolve (node:internal/modules/esm/resolve:983:10)
  at defaultResolve (node:internal/modules/esm/resolve:1080:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
  at link (node:internal/modules/esm/module_job:78:36)
```
```

**Comment by Aareksio** [comment]
Have you followed [all migration steps](https://github.com/nuxt/framework/discussions/4479) when upgrading to rc? This includes removing `package.lock.json` and `node_modules`

**Comment by lucassimines** [comment]
> Have you followed [all migration steps](https://github.com/nuxt/framework/discussions/4479) when upgrading to rc? This includes removing `package.lock.json` and `node_modules`

Yes, and It doesn't work on a simple new project, using the `npx nuxi init` command.

**Comment by lucassimines** [comment]
I tested creating a new app using `pnpm dlx nuxi init nuxt-app` and `npx nuxi init nuxt-app`, and I get the same error on both when trying to run the `nuxt dev` script.

**Comment by lukaszflorczak** [comment]
I had a similar problem, but it was a problem with one of the dependencies and not Nuxt directly. Do you use any external modules?

**Comment by lucassimines** [comment]
> I had a similar problem, but it was a problem with one of the dependencies and not Nuxt directly. Do you use any external modules?

As I mentioned, it's ocurring with the `minimal reproduction app`, with `no` external dependencies, here is my `package.json`

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.1"
  }
}
```

**Comment by lucassimines** [comment]
And that's the `nuxt.config.ts`

```
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({

})
```

**Comment by Aareksio** [comment]
I tried to reproduce on M1 mac, could you try bisecting the releases until you find which one broke it?
Here is the version list: https://www.npmjs.com/package/nuxt3

You probably only need to test the selected releases:
![image](https://user-images.githubusercontent.com/11166786/164809986-fb56aeb9-3e52-477b-9be3-d8871ec55189.png)

**Comment by lucassimines** [comment]
> I failed to reproduce on M1 mac, could you try bisecting the releases until you find which one broke it? Here is the version list: https://www.npmjs.com/package/nuxt3
> 
> You probably only need to test the selected releases: ![image](https://user-images.githubusercontent.com/11166786/164809986-fb56aeb9-3e52-477b-9be3-d8871ec55189.png)

I had no issues now running any of these versions, tried even the `rc.0@...` and the latest `rc.1@3.0.0-rc.1-27510703.46ecbc5` on my M1 mac. Thanks @Aareksio.

**Comment by latranchee** [comment]
I'm having the same issue as @danielroe . Curious to see if you've found a fix!

**Comment by Kalo0m** [comment]
Same, I'm having this issue when I migrated from Nuxt 2 to Nuxt bridge. If anyone has an idea ?

**Comment by latranchee** [comment]
I eventually started a new nuxt2 project and copied all my files over. That fixed it for me. However, I'm hit with a different error when building the app. Works fine in dev mode though.
