### ISSUE TITLE
useFetch didn´t work params?

### ISSUE THREAD

**Issue by hermesalvesbr** [nuxt/framework#4544]
### Environment

```
npx nuxi info
Nuxt CLI v3.0.0-rc.1-27510277.648a70e                                                                                              14:55:19
RootDir: /home/hermes/Projetos/nuxt/prefeitura-de-araripina                                                                        14:55:20
Nuxt project info:                                                                                                                 14:55:20

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.1-27510277.648a70e`
- Package Manager:  `yarn@3.2.0`
- Builder:          `vite`
- User Config:      `modules`, `publicRuntimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.3`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                   14:55:20

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

```

### Reproduction

```
async getDoses() {
    try {
      const token = this.encodeBase64();
      const myHeaders = {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Allow-Methods': 'GET,POST,OPTIONS,DELETE,PUT',
        Authorization: `Basic ${token}`,
      };

      var raw = JSON.stringify({
        query: {
          match: {
            estabelecimento_municipio_codigo: '260110',
          },
        },
        size: 0,
        aggs: {
          most_popular: {
            terms: {
              field: 'vacina_descricao_dose',
              size: 5,
            },
            aggs: {
              unique: {
                cardinality: {
                  field: 'paciente_id',
                },
              },
              uniqueCount_bucket_sort: {
                bucket_sort: {
                  sort: [
                    {
                      unique: {
                        order: 'asc',
                      },
                    },
                  ],
                },
              },
            },
          },
        },
      });

      var requestOptions = {
        method: 'GET',
        headers: myHeaders,
        body: raw,
      };
      //@ts-ignore
      const { data } = useFetch(
        'https://imunizacao-es.saude.gov.br/desc-imunizacao/_search',
        requestOptions
      );
      console.log('Data fetch ', data);
    } catch (e) {
      console.log(e);
    }
  }
}
```

### Describe the bug

Brazilian public api:
```
 urlApi = 'https://imunizacao-es.saude.gov.br/desc-imunizacao/_search';
 username = 'imunizacao_public';
 password = 'qlto5t&7r_@+#Tlstigi';
```

useFetch works **correctly** if there are no query params. It connects and gets the data if it is **without** params query. But if I put params, it stops working.

![image](https://user-images.githubusercontent.com/379850/164768996-b547aa61-2cb1-4690-b0b2-906e928b896e.png)

### Additional context

I also tried other ways.

![unknown](https://user-images.githubusercontent.com/379850/164769527-1039a1d1-57bc-4f5e-bee9-c0995f8aae4f.png)

Show me another errors:
`_rawValue: FetchError: Request with GET/HEAD method cannot have body ()`

**Comment by Aareksio** [comment]
```js
const params = { a: 1 }
const headers = { 'Authorization': 'Bearer <token>' }

const { data } = await useFetch(
  'https://httpbin.org/get', 
  { params, headers }
)
```

**Comment by hermesalvesbr** [comment]
No, it's not required. But the query parameters it's accept by body raw only.

![Screenshot_20220423_094455](https://user-images.githubusercontent.com/379850/164895780-392fdc51-6429-4a6a-87ea-dade4a9ab574.png)

**Comment by Aareksio** [comment]
Can you do a POST request instead of GET? Or maybe does this API support method spoofing?

GET + body is **unsupported** by design. 
If the API requires you to do such request, you must fall back to older XMLHttpRequest (eg. via `axios`).

**Comment by hermesalvesbr** [comment]
@Aareksio  First of all, I want to thank you for investing your time in trying to help me solve this problem. Thanks.

I tried with params, with body and with post. All return empty in my terminal. And in postman it works with get or post. But only with the raw body.

May I have to convert the body to raw? Or is it my code that is written incorrectly?

![Captura de tela de 2022-04-23 22-25-05](https://user-images.githubusercontent.com/379850/164951803-166cf6b5-9509-4301-a8da-61bf0e199853.png)

![Captura de tela de 2022-04-23 22-29-43](https://user-images.githubusercontent.com/379850/164951833-4e8d4cfd-dd70-4c17-943c-093c35434562.png)

**Comment by Aareksio** [comment]
https://github.com/unjs/ohmyfetch#%EF%B8%8F-json-body

Do not stringify the body yourself and it should work. Either way it is not an issue with nuxt 3, so you can close.

![image](https://user-images.githubusercontent.com/11166786/164971202-2a9dd46d-f5e9-476b-8c93-38e4516e7223.png)

**Comment by hermesalvesbr** [comment]
Sim, agora funcionou. E não deu um bug com o nuxt 3.

![image](https://user-images.githubusercontent.com/379850/165088965-23e564ce-ee68-406f-be95-aed0187304da.png)
