### ISSUE TITLE
Support nuxt build --spa

### ISSUE THREAD

**Issue by alexcroox** [nuxt/framework#4546]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `srcDir`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

In Nuxt 2 you could control the build via CI using `npm run build -- --spa` which would build for SPA.

This was useful when you need to build for native app web views.

You can enable SPA with ssr: false but this requires editing source code between web and mobile app deployments which isn't ideal

### Describe the bug

No --spa flag for build in nuxt 3

**Comment by Aareksio** [comment]
Should do the job for now:

```js
import { defineNuxtConfig } from 'nuxt'

const spa = process.argv.includes('--spa')

export default defineNuxtConfig({
  ssr: !spa
})
```

```
npm run build -- --spa
```

**Comment by alexcroox** [comment]
Good idea thanks!

**Comment by danielroe** [comment]
I wouldn't recommend adding a `--spa` flag globally as it seems very targeted at this use case. Particularly as the direction we're going in with hybrid builds means building nuxt in many cases isn't going to be just a matter of flipping ssr on or off.

I think @Aareksio's solution works well for this use case, and indeed you could create a custom module that applies more configuration changes between mobile/web builds without the need for editing configuration.
