### ISSUE TITLE
Differences between dev and build when using the transform function in useFetch

### ISSUE THREAD

**Issue by AndreyKindin** [nuxt/framework#4553]
### Environment

Nuxt CLI v3.0.0-rc.1                                                                                                                                                                      15:36:24
RootDir: /home/projects/github-zvnotk-qj4tyf                                                                                                                                              15:36:26
Nuxt project info:                                                                                                                                                                        15:36:26

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-zvnotk-qj4tyf

If you start 'npm run dev' div's with content test a, test g, b and c are visible. But if you start 'npm run build && npm run preview' the two containers with content b and c disappear. This behavior only occurs when the transform function is used.
the alternative use is commented out for testing purposes

### Describe the bug

Something is wrong with the transform function

**Comment by Aareksio** [comment]
```html
<template>
  <div>
    <div>Static Before</div>
    <div v-for="content in response" :key="content">{{ content }}</div>
    <div>Static After</div>
  </div>
</template>

<script setup>
  const { data: response } = await useFetch('/api/test', { transform: r => r.data });
</script>
```
Dev:
![image](https://user-images.githubusercontent.com/11166786/164916922-d4494961-319e-4b2b-8da6-d1b4658a10e9.png)
![image](https://user-images.githubusercontent.com/11166786/164917012-50662257-05cb-45e6-a982-11ceb89f1f81.png)

Build + Preview:
![image](https://user-images.githubusercontent.com/11166786/164916937-6e6596ee-90ea-4873-b5ea-8fd957a73996.png)
![image](https://user-images.githubusercontent.com/11166786/164917005-5ee907e0-7341-410a-b9e2-c02d02259cae.png)


Build + Preview returns proper server generated HTML, but the client app breaks.

---

The difference between chunks with and without transform.
![image](https://user-images.githubusercontent.com/11166786/164918796-d206a21d-9319-44f7-8411-6820939a60d4.png)

**Comment by Aareksio** [comment]
Adding `{ key: 'my-key' }` fixes the issue for my example, possibly related to #4497. 
I am very interested in seeing what ultimately lead to the render being aborted mid-way without visible error.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/4497.
