### ISSUE TITLE
sync route state smartly with suspended route

### ISSUE THREAD

**Issue by johannesstricker** [nuxt/framework#4574]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.1-27510703.46ecbc5`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `pageTransition`, `runtimeConfig`, `css`, `build`, `postcss`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ugufpl?file=pages/index.vue

### Describe the bug

Computed route parameters update before navigation has finished in combination with `useAsyncData`. 

E.g. `/path/with/[slug]` uses the slug to fetch data from the backend:
```
const slug = computed(() => route.params.slug);
const { data, refresh } = useAsyncData('key', $fetch(`/api/movie/${slug}`));
watch(slug, refresh);
```

Now when I navigate to `/another-path`, which also uses `useAsyncData` and takes a while to finish loading, the slug becomes `undefined` for a brief moment and triggers another api request to `/api/movie/undefined`.

I've started a discussion [here](https://github.com/nuxt/framework/discussions/4535), but after I did some research it appears to me that this is a bug rather than me not using the api properly.

**Comment by johannesstricker** [comment]
Thanks, didn't know `useActiveRoute`. You're right, that fixes the issue, but leads to another one: while the new pages loads, the `slug` is undefined there. I've created [another reproduction here](https://stackblitz.com/edit/github-ugufpl-gkcchu?file=pages/[slug].vue).

If you open the devtools you'll see "FOO IS: undefined` while navigation to the nested route.

**Comment by Aareksio** [comment]
I think you should manually check for undefined or rely on `useAsyncData` built-in refresh on route change.

That said, I see some problems:
https://stackblitz.com/edit/github-ac5hak

**Comment by johannesstricker** [comment]
Okay and any idea how to get around these problems? 🤔

**Comment by bittermeatball** [comment]
@emazyka @Aareksio @johannesstricker thanks, i created a reproduce stackblitz here:
https://stackblitz.com/edit/nuxt-starter-v8dui3?file=pages/[slug].vue

Using `useActiveRoute()` will fetch the API twice though, once with undefined slug, once identified, it makes sense in term of routing (clear and set new route), but do we have any better solution on Route navigation + API fetch?

![image](https://user-images.githubusercontent.com/46400321/167382551-1e6f7d58-1ca5-492c-882b-616ec5b508f5.png)

https://user-images.githubusercontent.com/46400321/167382317-de30fe59-0f97-4b0d-99c5-3e75dcf111c8.mp4

**Comment by johannesstricker** [comment]
Are there any plans to work on this? I'd be happy to help with this if you can point me in the right direction.

**Comment by danielroe** [comment]
This was resolved in https://github.com/nuxt/framework/pull/6275. Apologies for not getting back to you @johannesstricker.
