### ISSUE TITLE
[h3] write EPIPE

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#4576]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `buildModules`, `modules`, `tailwindcss`, `app`, `nitro`, `build`, `modern`, `css`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.3`
- Build Modules:    `@vueuse/nuxt@8.3.1`
------------------------------

### Reproduction

*

### Describe the bug

i am trying to upload file from client to server
on the client, I split the file into chunks and send a stack of requests to the server.
This error only occurs when uploading large files.

### Additional context

<details>
<summary><code>@/pages/upload.vue</code></summary>

```vue
<script setup lang="ts">
	const { open, file } = useFileSystemAccess({ dataType: 'Blob' });

	const onUpload = async () => {
		const size = 1024 * 50;
		const fileChunks: Array<Blob> = [];
		for (let cur = 0; cur < file.value.size; cur += size) {
			fileChunks.push(file.value.slice(cur, cur + size));
		}
		const uploadList = fileChunks.map(async (item) => {
			let formData = new FormData();
			formData.append('filename', file.value.name);
			formData.append('chunk', item);
			return $fetch('/api/upload', { method: 'POST', body: formData });
		});
		await Promise.all(uploadList);
		alert('done');
	};
</script>

<template>
	<div class="flex space-x-6 w-full items-center justify-center">
		<button @click="open()">Open File</button>
		<button @click="onUpload">Upload</button>
	</div>
</template>
```
</details>

<details>
<summary><code>@/server/api/upload.ts</code></summary>

```ts
import { CompatibilityEvent } from 'h3';
import multiparty from 'multiparty';
import fs from 'fs';

export default async (event: CompatibilityEvent): Promise<IServerResponse> => {
	const form = new multiparty.Form();
	form.parse(event.req, (err, fields, files) => {
		let filename = fields.filename[0];
		let chunk = files.chunk[0];
		try {
			const buffer = fs.readFileSync(chunk.path);
			const ws = fs.createWriteStream(filename);
			ws.write(buffer);
			ws.close();
		} catch (error) {
			console.error(error);
		}
	});
	return { success: true };
};
```
</details>

<details>
<summary>Errors</summary>

![](https://i.imgur.com/IntUdn0.png)
![](https://i.imgur.com/tGlM1HF.png)
</details>

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/4524.
