### ISSUE TITLE
Support router in hash mode (spa)

### ISSUE THREAD

**Issue by 1isten** [nuxt/framework#4579]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

-

### Describe the bug

How to config nuxt 3 router to use [hash-mode](https://router.vuejs.org/guide/essentials/history-mode.html#hash-mode)?

I know the docs is not finished yet, so I searched the source code, but it seems there is no way to use the `createWebHashHistory`

https://github.com/nuxt/framework/blob/0eebb0a390c53c05c5bcbcb4fbda64d59a8945b6/packages/nuxt/src/pages/runtime/router.ts#L64

**Comment by Aareksio** [comment]
Hash mode would not work with SSR, as [clever people on StackOverflow explained](https://stackoverflow.com/questions/3664257/why-is-the-hash-part-of-the-url-not-available-on-the-server-side). Might be useful only in SPA mode - making this a feature request, I guess.

**Comment by 1isten** [comment]
I want to use Nuxt 3 to build an SPA and pack it into a desktop app using [Electron](https://electronjs.org/). According to the vue-router [docs](https://router.vuejs.org/api/#createwebhashhistory), hash mode is

> Useful for web applications with no host (e.g. file://) or when configuring a server to handle any URL isn't an option.

**Comment by dominixz-dzvz** [comment]
I think I need this too. I want to do website that deploy on IPFS and I can't enter page by directly from Browser URL

**Comment by SvetlozarValchev** [comment]
I didn't even know this wasn't part of 'core' features, I'm using Nuxt for purely static client-side web apps and always have set the router mode to 'hash' in Nuxt 2, but the lack of this option seems to be a breaking change if I want to migrate my projects to 3.0

**Comment by o1lab** [comment]
Ahh we need this badly - we're almost through with migrating to nuxt3 and are struggling with this :sob: 

@danielroe : can you please help ?

**Comment by danielroe** [comment]
This was implemented in https://github.com/nuxt/framework/pull/6980.
