### ISSUE TITLE
Navigation fails if pages do not have single root element

### ISSUE THREAD

**Issue by henningko** [nuxt/framework#4598]
### Environment

  * Operating System: `macOS 12.3.1`

  * Node Version:     `v16.14.2`

  * Nuxt Version:     `3.0.0-rc.1`

  * Package Manager:  `yarn@1.23.0`

  * Builder:          `vite`

  * User Config:      `-`

  * Runtime Modules:  `-`

  * Build Modules:    `-`

### Reproduction
Create a new Nuxt3 app with the following files:

`app.vue`
```vue
<template>
  <div>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
```

`pages/index.vue`
```vue
<template>
  <div>Home</div>
  <NuxtLink to="/thankyou">thanks</NuxtLink>
</template>
```

`pages/thankyou.vue`
```vue
<template>
  <div>
    <h1>thank you</h1>
  </div>
</template>

```
### Describe the bug

When navigating from `/` to `/thankyou` using `NuxtLink` (as well as `navigateTo` and `router.push`, the result is an empty page.

When wrapping the content of `pages/index.vue` into a single div, the problem disappears.

No error messages are given.

**Comment by Aareksio** [comment]
Reproduction: [StackBlitz](https://stackblitz.com/edit/github-6syimm)

![image](https://user-images.githubusercontent.com/11166786/165155470-c5ed60d6-56fd-4de0-890f-b79b0be01e14.png)

Documentation ([source](https://v3.nuxtjs.org/guide/directory-structure/pages#usage)):
> Pages **must have a single root element** to allow route transitions between pages. (HTML comments are considered elements as well.)

Couldn't this be caught by Nuxt and surfaced with better error message? Perhaps adding yellow alert in docs may be helpful too.

**Comment by henningko** [comment]
Shoot, yes, totally missed that in the docs (perhaps also because I understand transitions to be animated).

IIRC, in it would throw an error in Nuxt2—so no (explicit) error/warning makes it hard to understand what's going on.
