### ISSUE TITLE
Nitro Server Routes

### ISSUE THREAD

**Issue by kogi-dev** [nuxt/framework#4599]
### Environment

Nuxt project info:                                                                                                                      
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.17.5`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.11`
- Builder:          `vite`
- User Config:      `css`, `build`, `vue`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Repo: [https://github.com/kogi-dev/Nuxt3RCTests](https://github.com/kogi-dev/Nuxt3RCTests)

### Describe the bug

I followed the server route guide for route params here: https://v3.nuxtjs.org/guide/features/server-routes#matching-route-parameters.
But it doesn't seem to work and the params object is empty and it is being executed by the index.ts of the folder instead of the [parameter].ts . The fallback route [...].ts as described here: https://v3.nuxtjs.org/guide/features/server-routes/#catch-all-route didn't work, but calling it index.ts seems to somewhat work, but the params are empty as I wrote before:

Error with [...].ts:
![image](https://user-images.githubusercontent.com/70855028/165149875-d44be43e-0061-4f5a-a998-08c4543a1224.png)

![image](https://user-images.githubusercontent.com/70855028/165147715-57552c36-3ec5-45d2-959a-81e55334de4d.png)

index.vue:
![image](https://user-images.githubusercontent.com/70855028/165148425-62555fd9-e671-4920-badb-ba5009f3adb0.png)

And this fetch is executed twice fro some reason, as you can see above

**Comment by Aareksio** [comment]
Prams from `event.context.params` are not the same `params` as the ones you pass to `$fetch`.

`$fetch` params = "Search Params"
`event.context.params` = "Route Params"

As confusing as it sounds, to access "Search Params" on server, you must use helper function `useQuery`. Because "Search Params" are also sometimes referred to as "url query". Do not ask, accept your fate as a javascript developer.

```js
// server/api/hello/index.ts
export default defineEventHandler(event => {
  const query = useQuery(event)
  return `Hello, ${query.name}`
})

// app.vue
$fetch('/api/hello', { params: { name: 'Gregor' } })
```

---

Not a bug in Nuxt

**Comment by kogi-dev** [comment]
> Prams from `event.context.params` are not the same `params` as the ones you pass to `$fetch`.
> 
> `$fetch` params = "Search Params" `event.context.params` = "Route Params"
> 
> As confusing as it sounds, to access "Search Params" on server, you must use helper function `useQuery`. Because "Search Params" are also sometimes referred to as "url query". Do not ask, accept your fate as a javascript developer.
> 
> ```js
> // server/api/hello/index.ts
> export default defineEventHandler(event => {
>   const query = useQuery(event)
>   return `Hello, ${query.name}`
> })
> 
> // app.vue
> $fetch('/api/hello', { params: { name: 'Gregor' } })
> ```
> 
> Not a bug in Nuxt

**Comment by kogi-dev** [comment]
> > Prams from `event.context.params` are not the same `params` as the ones you pass to `$fetch`.
> > `$fetch` params = "Search Params" `event.context.params` = "Route Params"
> > As confusing as it sounds, to access "Search Params" on server, you must use helper function `useQuery`. Because "Search Params" are also sometimes referred to as "url query". Do not ask, accept your fate as a javascript developer.
> > ```js
> > // server/api/hello/index.ts
> > export default defineEventHandler(event => {
> >   const query = useQuery(event)
> >   return `Hello, ${query.name}`
> > })
> > 
> > // app.vue
> > $fetch('/api/hello', { params: { name: 'Gregor' } })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not a bug in Nuxt

Thank you for clarifying. That's certainly an oddity. But I think I can live with it.

**Comment by pi0** [comment]
I would probably rename unfetch option to `query` making it more clear.
