### ISSUE TITLE
NuxtLink to="/" renders blank page

### ISSUE THREAD

**Issue by webceyhan** [nuxt/framework#4624]
### Environment

- Operating System: `Darwin`
- Node Version:     `v17.7.1`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.4`
- Builder:          `vite`
- User Config:      `app`
- Runtime Modules:  `-`
- Build Modules:    `-`

-------------------------------------
navigator.userAgent
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'

### Reproduction

I use vanilla project with following structure:

pages:
 - index.vue
 - restaurants
    - index.vue
    - [name].vue
  

### Describe the bug

When navigating with NuxtLink component, every route works perfectly fine except <NuxtLink to="/"> which navigates to index.vue as expected but without rendering the contents..

There is no console.error message on the browser side neither on the server side.

**Comment by webceyhan** [comment]
I've just noticed that my nested dynamic route doesn't work either..

 <NuxtLink :to="`/restaurants/${name}`">{{ name }}</NuxtLink>

Clicking on the above link produce the same issue, route changes correctly but i am getting a blank page.

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by webceyhan** [comment]
Okay, i've done the same on here:
https://stackblitz.com/edit/nuxt-starter-fzrc1r?file=layouts/default.vue

Although i've noticed another thing, after implementing NuxtLayout, now we can get the navigation but the content is still blank..

**Comment by antfu** [comment]
The `restaurants` layout is missing in your repro. Add it then it works fine.

https://stackblitz.com/edit/nuxt-starter-dv4xgm?file=layouts%2Frestaurants.vue

**Comment by danielroe** [comment]
@webceyhan The issue remaining is that your `~/pages/restaurants/index.vue` does not have a single root element.

**Comment by DannyFeliz** [comment]
I have the same issue, having a single root element fixed in the problem.

**Comment by zhixXiang** [comment]
I have the same issue, and I also have a single root element, but it still render blank page

**Comment by thruthesky** [comment]
same here

**Comment by thruthesky** [comment]
> Feel free to open an issue with a reproduction.

It was my mistake. I forgot to do the `single root element`.
