### ISSUE TITLE
useHead memory leak

### ISSUE THREAD

**Issue by baronkoko** [nuxt/framework#4630]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Create a new Nuxt 3 app, build it and run the built app.

### Describe the bug

I noticed that the production app is constantly increasing the amount of used memory. So, I made measurements with Chrome allocation instrumentation on the timeline and made 10000 requests to this app via `ab` (Apache HTTP server benchmarking tool).

**Results:**

![Screenshot 2022-04-26 at 18 03 23](https://user-images.githubusercontent.com/27996386/165331353-5f3f9915-1d6d-434a-931a-248d34fb43d5.png)

Thus, it showed a large amount of data that remains even after their use. Namely, the potential source of the problem is `metaConfig.globalMeta`.

So, after that, I commented this line. 

<img width="559" alt="Screenshot 2022-04-26 at 18 07 04" src="https://user-images.githubusercontent.com/27996386/165332518-594e1738-d24e-4bfc-b877-6c5797550a59.png">

And made the same measurements again.

**Results:**

![Screenshot 2022-04-26 at 18 10 43](https://user-images.githubusercontent.com/27996386/165332886-9807b4c1-5691-451d-b320-018eb16106de.png)

And the problem disappeared. The `selected size` decreased from `46.3 MB` to `9.1 MB`.

Can you look at this, please?

**Comment by danielroe** [comment]
Thanks - really appreciate it.

I'm closing to track in https://github.com/nuxt/framework/issues/4426 but this debugging should be hugely helpful in resolving.
