### ISSUE TITLE
optional route param naming (`[[param]]`) don't work as documented

### ISSUE THREAD

**Issue by eden** [nuxt/framework#4634]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

StackBlitz Link: https://stackblitz.com/edit/github-yp4zaf

1. Create any page that has the name to signify optional parameters (e.g. `[[param]].vue`). This is documented [here](https://v3.nuxtjs.org/guide/directory-structure/pages#dynamic-routes).
2. Try to navigate to that page (either with or a value). The link 404s.
3. Renaming it to `[param].vue` works but is no longer optional.

### Describe the bug

Can't create pages using the optional parameter naming scheme documented here: https://v3.nuxtjs.org/guide/directory-structure/pages#dynamic-routes

**Comment by pi0** [comment]
Apologies for adding early documentation. This feature will be available for RC.2. In the meantime you can try it by switching to nuxt edge:

{
  "devDependencies": {
--    "nuxt": "^3.0.0-rc.1"
++    "nuxt": "npm:nuxt3@latest"
  }
}

**Comment by edwh** [comment]
@pi0 Apologies if I'm missing something, but I'm using Edge and not seeing this work.  Here's a repro using a fork of @eden's.

https://stackblitz.com/edit/github-yp4zaf-gigghx?file=README.md
