### ISSUE TITLE
Global server at /api

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/framework#4641]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `target`, `bridge`, `vite`, `alias`, `nitro`, `ssr`, `meta`, `css`, `tailwindcss`, `modules`, `watch`, `runtimeConfig`, `build`, `storybook`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.2`, `@pinia/nuxt@0.1.8`
- Build Modules:    `-`

### Reproduction

https://github.com/JabRef/JabRefOnline/pull/1009

### Describe the bug

Not sure if this is a bug report or a feature request.

For graphql servers, it's quite common to only expose a single server route. However, I was not able to expose the server at `/api`. I tried adding a `/server/api/index.ts` file, but then the server would be available at `/api/index`. With `/server/api/[...].ts` one has to use `/api/` with slash.

**Comment by Hungrynow666** [comment]
> ### Environment
> 
> - Operating System: `Linux`
> 
> - Node Version:     `v16.13.0`
> 
> - Nuxt Version:     `3.0.0-rc.1`
> 
> - Package Manager:  `yarn@1.22.17`
> 
> - Builder:          `vite`
> 
> - User Config:      `target`, `bridge`, `vite`, `alias`, `nitro`, `ssr`, `meta`, `css`, `tailwindcss`, `modules`, `watch`, `runtimeConfig`, `build`, `storybook`
> 
> - Runtime Modules:  `@nuxtjs/tailwindcss@5.0.2`, `@pinia/nuxt@0.1.8`
> 
> - Build Modules:    `-`
> 
> ### Reproduction
> 
> https://github.com/JabRef/JabRefOnline/pull/1009
> 
> ### Describe the bug
> 
> Not sure if this is a bug report or a feature request.
> 
> 
> 
> For graphql servers, it's quite common to only expose a single server route. However, I was not able to expose the server at `/api`. I tried adding a `/server/api/index.ts` file, but then the server would be available at `/api/index`. With `/server/api/[...].ts` one has to use `/api/` with slash.
> 
> ### Additional context
> 
> _No response_
> 
> ### Logs
> 
> _No response_

**Comment by Aareksio** [comment]
Not sure if this is a bug or a feature, but you should be able to work around it with `serverMiddleware` in config like so:
```js
serverMiddleware: {
	{ path: '/api', handler: '~/server/graphql.ts' }
}
```

**Comment by danielroe** [comment]
This seems to work fine for me with `~/server/api/index.ts` as of the latest Nuxt/Nitro releases: https://stackblitz.com/edit/github-bgnqbx

**Comment by tobiasdiez** [comment]
Thanks for the update. I can confirm that with a file at `~/server/api/index.ts` the `/api` route works as expected. However, the route with a slash, `/api/` shows now the main index page (in the above stackbliz you linked to) or a 404 error (in my repo).

**Comment by danielroe** [comment]
Let's follow that request in https://github.com/nuxt/framework/issues/7458.
