### ISSUE TITLE
nuxt config ts error

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#4655]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.1-27516498.2bfd749`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `meta`, `runtimeConfig`, `buildModules`, `tailwindcss`, `vite`, `css`, `router`, `nitro`, `srcDir`, `build`, `modern`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.3`, `@vueuse/nuxt@8.3.1`
------------------------------

### Reproduction

*

### Describe the bug

i have nuxt config with multitiple fields:
`@/nuxt.config.ts`
```ts
import { defineNuxtConfig } from 'nuxt';
import nuxtMetaConfig from './configs/nuxt.meta.config';
import nuxtRuntimeConfig from './configs/nuxt.runtime.config';
import nuxtModulesConfig from './configs/nuxt.modules.config';

export default defineNuxtConfig({
	...nuxtMetaConfig,
	...nuxtRuntimeConfig,
	...nuxtModulesConfig,
	css: ['~/assets/css/main.css', '~/assets/scss/main.scss'],
	router: {
		prefetchLinks: false,
	},
	nitro: {
		output: {
			dir: '~~/build',
		},
		externals: {
			inline: ['uuid'],
		},
	},
	srcDir: 'src',
	build: {
		splitChunks: {
			pages: true,
			layouts: true,
		},
	},
	modern: true,
});
```
and my IDE throwing error:
`Type instantiation is too deep and possibly infinite.ts(2589)`

### Additional context

![](https://i.imgur.com/aFeyplH.png)

**Comment by danielroe** [comment]
Would you provide a reproduction? This is likely to do with how you're defining the sections of config you're importing.

**Comment by dvdmlln** [comment]
I'll get this error only for the vite section in nuxt config. The error occured after an npm update, vite updated from 2.9.5 to 2.9.6.
If I manually add vite to devDependencies and set the version to 2.9.5 the error disappears.

![Screenshot 2022-04-28 072340](https://user-images.githubusercontent.com/64189384/165682670-0f550b38-c164-42dd-ba6f-5b9f038af515.png)

**Comment by mihail727** [comment]
Nuxt version: `v3.0.0-rc.2-27526179.f74a523`
the problem is still there
