### ISSUE TITLE
Cannot have dots . in app name

### ISSUE THREAD

**Issue by HampusLilja** [nuxt/framework#4658]
### Environment

Nuxt CLI v3.0.0-rc.1 
RootDir: c:\Development\Foo\My.New.App 
Nuxt project info: 

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.4.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

npx nuxi init My.New.App

### Describe the bug

When having an app (root folder) with dots in the name the generated tsconfig path aliases becomes faulty.

### Additional context

I'll get the app to build but when using alias import such as 
`import { collection } from '~~/helper/collection'`

I get an:  _Cannot find module '~~/helper/collection' or its corresponding type declarations_

**Comment by danielroe** [comment]
Should be resolved in https://github.com/nuxt/framework/pull/4595. It's available now in [edge releases](https://v3.nuxtjs.org/guide/going-further/edge-channel) or in the next RC release.
