### ISSUE TITLE
All examples look the same

### ISSUE THREAD

**Issue by hdzierz** [nuxt/framework#4659]
### Environment

I am attempting to work on this example web site:

https://v3.nuxtjs.org/examples/auto-imports/components

All examples display the default welcome site. This also happens if you run the examples locally.

Cheers

### Reproduction

Go to e.e. the [components examples](https://v3.nuxtjs.org/examples/auto-imports/components)

### Describe the bug

All components examples show a default page

EDIT:
![image](https://user-images.githubusercontent.com/877361/165490837-da1ff44f-4ccf-465a-bbce-987c1ae37f35.png)

**Comment by danielroe** [comment]
> All examples display the default welcome site. This also happens if you run the examples locally.

If this is happening for you locally, would you provide more details about your environment?

**Comment by hdzierz** [comment]
> 

Hi There,

Thanks for looking into this. Locally it seems to be a memory issue:

![image](https://user-images.githubusercontent.com/877361/165530670-f6a941af-83b0-4aa6-8eb1-edc0270d16f8.png)

Env:

- OP: Linux ... #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
    DISTRIB_ID=LinuxMint
    DISTRIB_RELEASE=20.2
    DISTRIB_CODENAME=uma
    DISTRIB_DESCRIPTION="Linux Mint 20.2 Uma"
- Visual Studio Code 1.66.2
- Nuxt Deps:

```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.1"
  },
  "dependencies": {
    "@nuxt/ui": "^0.1.0",
    "@nuxt/ui-templates": "^0.1.0"
  }
}
```

**Comment by hdzierz** [comment]
Now I am getting this:
![image](https://user-images.githubusercontent.com/877361/165532627-00b16f58-bc72-47fc-8ddf-3f7c0090a6b8.png)

**Comment by hdzierz** [comment]
It seems that the web server uses up to 4GB of RAM before it finally returns a 503 error status
Locally:

![image](https://user-images.githubusercontent.com/877361/165536352-361b22a6-aa8f-4908-bb17-653d9a421c27.png)

On CodeSandbox:

![image](https://user-images.githubusercontent.com/877361/165535979-fc6a2308-ff1d-4b6b-aa42-34c669299cfd.png)

**Comment by danielroe** [comment]
This is no longer reproducible.
