### ISSUE TITLE
`transition-group` works only with `client-only`

### ISSUE THREAD

**Issue by ewilan-riviere** [nuxt/framework#4670]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `pnpm@6.31.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.3`
- Build Modules:    `-`

### Reproduction

[Example repository](https://gitlab.com/ewilan-riviere/nuxt-3-transition-group) on gitlab, I've create [a sandbox](https://codesandbox.io/s/strange-bell-oxo63d) (but `client-only` not works as expected).

I advice to use [this repository](https://gitlab.com/ewilan-riviere/nuxt-3-transition-group).

```
git clone git@gitlab.com:ewilan-riviere/nuxt-3-transition-group.git
cd nuxt-3-transition-group
pnpm i
pnpm dev
```

### Describe the bug

When I use [`transition-group`](https://vuejs.org/guide/built-ins/transition-group.html#transitiongroup), it not works as expected. My example use a grid to display elements.

- When I use `client-only`, the grid always works.
- When I **refresh manually**, the grid is broken without `client-only`. But when I **change page** and I come back without refresh, it works

**Comment by danielroe** [comment]
See https://github.com/vuejs/core/issues/5141 and https://github.com/nuxt/framework/issues/2370. I believe this is the same as your issue (but it's not clear from reading your description above). Let me know if not.
