### ISSUE TITLE
I Cann't Change Port After Build Project

### ISSUE THREAD

**Issue by chaule97** [nuxt/framework#4676]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `buildModules`, `head`, `css`, `build`, `intlify`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`, `@intlify/nuxt3@0.2.1`
------------------------------

### Reproduction

npm install

### Describe the bug

I want to change port when build project, but result is also 3000 default

```
C:\Users\NGOCSON\Documents\bds.net\Source\WebUser\bds-app> node .output/server/index.mjs
Listening on http://0.0.0.0:3000/
```

I have tried many ways but no change.

**Comment by sewalsh** [comment]
`NITRO_PORT=4000 node .output/server/index.mjs` 

https://v3.nuxtjs.org/guide/deploy/node-server
