### ISSUE TITLE
useLazyAsyncData ignores initialCache:false option

### ISSUE THREAD

**Issue by gnugomez** [nuxt/framework#4702]
### Environment

Nuxt CLI v3.0.0-rc.1-27517945.7e912e7
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1-27517945.7e912e7`
- Package Manager:  `pnpm@6.32.9`
- Builder:          `vite`
- User Config:      `meta`, `components`, `experimental`, `loading`, `srcDir`, `css`, `modules`, `buildModules`, `tailwindcss`, `i18n`, `vueuse`, `publicRuntimeConfig`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-alpha.0-27516108.1766d8d`
- Build Modules:    `@vueuse/nuxt@8.3.1`, `@nuxtjs/tailwindcss@5.0.3`, `@pinia/nuxt@0.1.8`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

```
const { data: postsArchive, pending } = await useLazyAsyncData<
  ArchiveResponse<Post>
>(
  `posts_${locale.value}`,
  () =>
    $content
      .posts()
      .perPage(9)
      .page(page.value)
      .param('lang', locale.value)
      .orderby('date')
      .get(),
  {
    initialCache: false,
    watch: [page],
  }
)
```

### Describe the bug

When I fetch the next page (infinite scroll), and then I navigate, when I return to the previous page and `useLazyAsyncData` is called, it returns the last page even with initialCache set to false and page ref set to 1.

`useAsyncData` works as expected

**Comment by Aareksio** [comment]
[Reproduction on StackBlitz](https://stackblitz.com/edit/github-ug9cjf?file=pages%2Findex.vue)
