### ISSUE TITLE
Route in plugin is always /

### ISSUE THREAD

**Issue by dvdmlln** [nuxt/framework#4703]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.1`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-trznob?file=plugins/plugin.ts

### Describe the bug

Hi,

I am trying to get the current path in a plugin using `useRoute()` but it always returns the route with the path `/`.

```
export default defineNuxtPlugin((nuxt) => {
    const route = useRoute()
    console.log(route.path) // always '/'
})
```

My workaround is to use the `app:created` hook in the plugin and call `useRoute()` outside the hook and access the path inside the hook:

```
export default defineNuxtPlugin((nuxt) => {
    const route = useRoute()
    nuxt.hook('app:created', () => {
        console.log(route.path) // works
    })
})
```

If I call `useRoute()` inside the hook I get a nuxt `instance unavailable error`:

```
export default defineNuxtPlugin((nuxt) => {
    nuxt.hook('app:created', () => {
        const route = useRoute() // error
        console.log(route.path)
    })
})
```

Shouldn't the nuxt instance be available inside `app:created` hook?
My goal is to call an API on init in a nuxt module based on the current path. Is there another recommended way to do this?

Best regards
David

**Comment by dvdmlln** [comment]
With https://github.com/nuxt/framework/pull/4645 useRoute() works as expected, thanks!

What about the `instance unavailable error` in the `app:created` hook? Is this a bug or expected behaviour? I can access the nuxt instance like this

```
nuxt.hook('app:created', (app) => {
    console.log(app.$nuxt)
})
```
but I can't use composables like useFetch() or use Route().

**Comment by danielroe** [comment]
Composables are not meant to be used within Nuxt hooks.
