### ISSUE TITLE
useHead cannot be used in async functions

### ISSUE THREAD

**Issue by NidMo** [nuxt/framework#4706]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `pnpm@7.0.0-rc.6`
- Builder:          `vite`
- User Config:      `modules`, `experimental`, `vueuse`, `unocss`, `colorMode`
- Runtime Modules:  `@vueuse/nuxt@8.3.0`, `@unocss/nuxt@0.31.8`, `@pinia/nuxt@0.1.8`, `@nuxtjs/color-mode@3.0.2`
- Build Modules:    `-`
------------------------------

### Reproduction

```ts

<script lang="ts">
import { defineComponent } from 'vue'

function mockApi() {
  return new Promise((resolve) => {
    resolve({ title: 'test title' })
  })
}

export default defineComponent({
  async setup() {
    const data = await mockApi()

    useHead({
      title: '11111111111',
    })
  },
})
</script>
```

throw error

[nuxt] [request error] nuxt instance unavailable

### Describe the bug

using useHead() in async function will throw an error:

**[nuxt] [request error] nuxt instance unavailable**

**Comment by danielroe** [comment]
Two issues:

1. `useHead` should be used in setup, not in a function. (I know your example showed it being used in setup, correctly, but I'm just observing this for future reference.)
2. The vue compiler does special optimisations for `<script setup>` tags that allows async usage of composables, but this is not true if you are using the defineComponent format. Try:

```vue
<script setup lang="ts">
import { defineComponent } from 'vue'

function mockApi() {
  return new Promise((resolve) => {
    resolve({ title: 'test title' })
  })
}

const data = await mockApi()

useHead({
  title: '11111111111',
})
</script>
```
