### ISSUE TITLE
built-in nuxt-layout component lost dynamic classes when it was used by top markup

### ISSUE THREAD

**Issue by TangsWang** [nuxt/framework#4726]
### Environment

nuxt3 rc
node 16.14

### Reproduction

when i use like that
`  <nuxt-layout name="1l-3s"  :class="{'fixed':isFixed}"> ...`

fixed will lost

### Describe the bug

when i use like that
`  <nuxt-layout name="1l-3s"  :class="{'fixed':isFixed}"> ...`

fixed will lost

**Comment by Aareksio** [comment]
Can not reproduce: [StackBlitz](https://stackblitz.com/edit/github-kp21b8?file=app.vue)
