### ISSUE TITLE
`createError` does not return data

### ISSUE THREAD

**Issue by Matix-Media** [nuxt/framework#4728]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `typescript`, `app`, `modules`, `buildModules`
- Runtime Modules:  `@nuxtjs/pwa@3.3.5`
- Build Modules:    `@nuxtjs/pwa@3.3.5`
------------------------------

### Reproduction

`server/api/test-route.ts`
```ts
export default defineEventHandler((event) => {
    return createError({statusCode: 400, statusMessage: "This is a test error", data: {foo: "bar"}});
})
```

### Describe the bug

You would expect the data to be included in the response as the h3 documentation states: https://www.jsdocs.io/package/h3/v/0.7.6#H3Error

The problem is, it does not get included in the response. The response:
```json
{
    "url":"/api/test-route.ts",
    "statusCode":400,
    "statusMessage":"This is a test error",
    "message":"This is a test error",
    "description":"<pre><span class=\"stack internal\">at createError (/D:/Development/JS/car-booking-system/node_modules/h3/dist/index.mjs:185:15)</span>\n<span class=\"stack\">at /D:/Development/JS/car-booking-system/.nuxt/dev/index.mjs:661:10</span>\n<span class=\"stack internal\">at processTicksAndRejections (node:internal/process/task_queues:96:5)</span>\n<span class=\"stack internal\">at async /D:/Development/JS/car-booking-system/node_modules/h3/dist/index.mjs:417:19</span>\n<span class=\"stack internal\">at async Server.nodeHandler (/D:/Development/JS/car-booking-system/node_modules/h3/dist/index.mjs:367:7)</span></pre>"
}
```

### Logs

```shell
[nuxt] [request error] This is a test error
  at createError (/D:/Development/JS/car-booking-system/node_modules/h3/dist/index.mjs:185:15)
  at /D:/Development/JS/car-booking-system/.nuxt/dev/index.mjs:661:10
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async /D:/Development/JS/car-booking-system/node_modules/h3/dist/index.mjs:417:19
  at async Server.nodeHandler (/D:/Development/JS/car-booking-system/node_modules/h3/dist/index.mjs:367:7)
```

**Comment by Aareksio** [comment]
Reproduction: https://stackblitz.com/edit/github-6nr6j4?file=server%2Fapi%2Ftest.js

I am positive nuxt overrides [default h3 error handler](https://github.com/unjs/h3/blob/0692656c59074c3900b92b203151590f4ab8e055/src/error.ts#L48-L83) with [its own](https://github.com/nuxt/framework/blob/b82c6e3e962ca52ae6556251655642e0e344b456/packages/nuxt/src/core/runtime/nitro/error.ts#L6-L46) which does not respect `data` property.

**Comment by Matix-Media** [comment]
Okay, I am going to check this out and maybe create a pr if I find the origin of this issue.

**Comment by Matix-Media** [comment]
> Reproduction: https://stackblitz.com/edit/github-6nr6j4?file=server%2Fapi%2Ftest.js
> 
> I am positive nuxt overrides [default h3 error handler](https://github.com/unjs/h3/blob/0692656c59074c3900b92b203151590f4ab8e055/src/error.ts#L48-L83) with [its own](https://github.com/nuxt/framework/blob/b82c6e3e962ca52ae6556251655642e0e344b456/packages/nuxt/src/core/runtime/nitro/error.ts#L6-L46) which does not respect `data` property.

Nvm, you already send the sources. If you want to, you can create the pr, if you do not feel like it, let me know so that I can patch it.

**Comment by Aareksio** [comment]
Feel free to create PR adding `data` property @Matix-Media. 

I am not sure whether skipping `data` was intended or not - perhaps the team intended for it to be stripped for some reason. A PR won't hurt, if it was not intentional, having PR may be the fast track of getting it fixed :).

Also the error handler for JSON response seems weird in general, eg. wrapping `stack` in `<pre>` inside `description` is strange at best. The code is fairly fresh, perhaps the team knows something we do not.

**Comment by Matix-Media** [comment]
> Also the error handler for JSON response seems weird in general, eg. wrapping `stack` in `<pre>` inside `description` is strange at best. The code is fairly fresh, perhaps the team knows something we do not.

I noticed that too, I thought that it maybe only would be in debug mode, as a way for the error display to display the error properly.

I also tracked the source further down to unjs/nitro (the nuxt engine) where the function normalizeError does not return the data too.

https://github.com/unjs/nitro/blob/4fbeef9bfd5c8e064817865a31d61927addc5e2a/src/runtime/utils.ts#L43

**Comment by Matix-Media** [comment]
https://github.com/nuxt/framework/blob/b82c6e3e962ca52ae6556251655642e0e344b456/packages/nuxt/src/core/runtime/nitro/error.ts#L16
Yeah the pre wrapped description only shows in dev mode.
