### ISSUE TITLE
`useFetch`'s data type is `any` in `<template>` but correct in `<script>`

### ISSUE THREAD

**Issue by PiotrekPKP** [nuxt/framework#4740]
### Environment

```
- Operating System: `Linux`
- Node Version:     `v17.9.0`
- Nuxt Version:     `3.0.0-27369360.33ebb01`
- Package Manager:  `yarn@1.22.18`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

https://github.com/PiotrekPKP/use-fetch-ts-bug

### Describe the bug

`useFetch` utility should generate / inherit type of returned data from server route (in above example: `/server/api/hello.ts`). However, type is available only in `<script>`. In `<template>`, data is of type `any`.

```vue
<template>
  <div> {{ data }} </div>
</template>

<script setup lang="ts">
  const { data } = await useFetch("/api/hello");
</script>
```

The problem also occures if I specify the return type manually:
```vue
const { data } = await useFetch<string, SampleType>("/api/hello");
```

### Additional context

Problem occures in all code editors with TypeScript server on.

**Comment by danielroe** [comment]
I can't replicate this. I suspect it's an issue with your IDE. Have you [set Volar up](https://v3.nuxtjs.org/getting-started/quick-start#prerequisites)?

<img width="698" alt="CleanShot 2022-05-01 at 10 06 05@2x" src="https://user-images.githubusercontent.com/28706372/166137579-94519b39-5127-4a02-9e43-9d43682cc08e.png">

**Comment by PiotrekPKP** [comment]
> I can't replicate this. I suspect it's an issue with your IDE. Have you [set Volar up](https://v3.nuxtjs.org/getting-started/quick-start#prerequisites)?
> 
> <img alt="CleanShot 2022-05-01 at 10 06 05@2x" width="698" src="https://user-images.githubusercontent.com/28706372/166137579-94519b39-5127-4a02-9e43-9d43682cc08e.png">

I'm using PhpStorm. I did not check this with VS Code and it looks like it's problem with JetBrains' IDE. Previosly I had this problem with both editors so I didn't check it with VS Code this time. Sorry for the inconvinience!
