### ISSUE TITLE
Cannot deploy to Firebase Hosting

### ISSUE THREAD

**Issue by oscarlomas09** [nuxt/framework#4767]
### Environment

Nuxt CLI v3.0.0-rc.1                  
Nuxt project info:                       
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `pnpm@6.32.3`
- Builder:          `vite`
- User Config:      `alias`, `buildModules`, `css`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

On a Windows environment, firebase deployments are failing. Testing on a bare-bones nuxt app to which I enabled firebase
*Note: Firebase Blaze plan was also enabled

following instructions in this Nitro [documentation ](https://nitro.unjs.io/deploy/providers/firebase.html#local-preview)

Steps I followed:

1. Initialize firebase project

2. 
`firebase.json`
```json
{
  "functions": {
    "source": ".output/server"
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "hosting": {
    "public": ".output/public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}
```

3. `npx cross-env NITRO_PRESET=firebase npm run build` (builds successfully)
4. `firebase deploy`

### Describe the bug

```js
i  deploying firestore, functions, hosting
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
+  cloud.firestore: rules file firestore.rules compiled successfully

Error: package.json in functions directory has an engines field which is unsupported. Valid choices are: {"node": "10"}, {"node":"12"}, and {"node":"14"}.
```
the build command sets the engine to `"node": "16"`. Manually setting to a lower version (to test) `"node": "14"` results in the following error:

```js
Error: Error occurred while parsing your function triggers.

Error [ERR_REQUIRE_ESM]: require() of ES Module \.output\server\index.mjs not supported.
Instead change the require of \.output\server\index.mjs to a dynamic import() which is available in all CommonJS modules.
    at \AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:19:15
    at Object.<anonymous> (\AppData\Roaming\npm\node_modules\firebase-tools\lib\triggerParser.js:57:3)
```

**Comment by snakeshift** [comment]
>Error [ERR_REQUIRE_ESM]: require() of ES Module \.output\server\index.mjs not supported.

I also encountered that isuue and resolve. #4465

**Comment by oscarlomas09** [comment]
Thanks @snakeshift, this seems to solve the issue. Maybe the docs should have a warning for this
