### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by baronkoko** [nuxt/framework#4769]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-acf1ba-8jx3xw?file=nuxt.config.ts

### Describe the bug

After updating to `"nuxt": "^3.0.0-rc.2"` I had this error when using the Vite plugin, do we have the ability to use them?

Error:
<img width="660" alt="Screenshot 2022-05-03 at 09 14 01" src="https://user-images.githubusercontent.com/27996386/166411354-167579df-a9a9-4c7d-8f64-829bde339570.png">

**Comment by danielroe** [comment]
Thanks for reporting this regression. This is an issue with the schema types, so everything should work apart from the warning.

**Context**: https://github.com/nuxt/framework/pull/4695

**Comment by baronkoko** [comment]
@danielroe got it, many thanks
