### ISSUE TITLE
`import.meta` support for server routes

### ISSUE THREAD

**Issue by miguelramos** [nuxt/framework#4771]
### Environment

nuxt 3

### Reproduction

When using server routes, if es module is used to resolve __dirname for instance esbuild complains about unsupported feature.

### Describe the bug

You can see it here reproduced:

https://codesandbox.io/s/cool-germain-qel5wt?file=/package.json

### Logs

```shell
Done in 2.76s.
ℹ Vite client warmed up in 1322ms                                     07:47:13
ℹ Vite server warmed up in 399ms                                      07:47:13
✔ Vite server built in 2431ms                                         07:47:15
✔ Vite server built in 12496ms                                        07:47:15

 WARN  [esbuild] (server/routes/hello.ts:4:40) "import.meta" is not available in the configured target environment ("es2019") and will be empty

✔ Nitro built in 1315 ms                                        nitro 07:47:16
Nuxt CLI v3.0.0-rc.2-27525415.a8d42d5                                 07:47:16
                                                                      07:47:16
  > Local:    http://localhost:3000/
  > Network:  http://192.168.203.9:3000/

[nitro] [dev] [uncaughtException] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
```

**Comment by danielroe** [comment]
You can work around this for the moment by changing the esbuild target:

```js
export default defineNuxtConfig({
  nitro: {
    esbuild: {
      target: 'node14'
    }
  }
})
```

**Comment by pi0** [comment]
Hi @miguelramos. You probably don't want to depend on file system paths and `import.meta.url` from runtime (server API routes and other places). When dist is bundled, this path is completely different and therefore unreliable to depend on.

A more reliable source is [storage API](https://nitro.unjs.io/guide/storage.html). During development, `/src/` and `/root/` paths are available to access filesystem paths.

PS: I've created an upstream issue to support universal `import.meta` (https://github.com/unjs/nitro/issues/181).
