### ISSUE TITLE
custom attrs in <Html> component

### ISSUE THREAD

**Issue by sahmadreza** [nuxt/framework#4779]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `css`, `buildModules`, `meta`, `postcss`, `build`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.3`, `@pinia/nuxt@0.1.8`

### Reproduction

https://github.com/nuxt/framework/pull/1820

### Describe the bug

This alert is displayed when I try to add custom attrs to `<Html>` component.

Code (App.vue):
```vue
<template>
   <Html lang="en" :data-theme="appStore.getTheme">
      <NuxtLayout>
        <NuxtPage />
      </NuxtLayout>
   </Html>
</template>

<script setup lang="ts">
import { useAppStore } from "./stores/app";
const appStore = useAppStore();
</script>
```

Warn: 
```vue
runtime-core.esm-bundler.js:38 [Vue warn]: Extraneous non-props attributes (data-theme) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <Html lang="en" data-theme="light" > 
  at <App key=1 > 
  at <NuxtRoot>
```

Of course, the code works properly but this warning is displayed

**Comment by danielroe** [comment]
For custom attributes, you will need to call `useHead` rather than using the `<Html>` component. Vue only allows us to accept _defined_ props, which we can't do in your case.
