### ISSUE TITLE
'nuxt dev' breaks on a fresh install with ssr: false

### ISSUE THREAD

**Issue by mario-neuhold** [nuxt/framework#4784]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/mario-neuhold/nuxt3-starter/tree/v3

### Describe the bug

`nuxt dev` is looking for `.nuxt/dist/server/server.mjs` which does not get created when `ssr: false` is on, so it crashes.

Workaround:
- remove `ssr: false`
- run `nuxt dev` - be happy its working (server.mjs got created)
- add `ssr: false` again
- `nuxt dev` is still working - keep on being happy (server.mjs is still there)

Reproduce:
- delete `.nuxt` folder
- be sure `ssr: false` is on
- `nuxt dev` is not working anymore - be sad
- start again with Workaround

### Logs

`ERROR  Rollup error:  Could not load file:///C:/Users/mario/Documents/dev/nuxt3-starter/.nuxt/dist/server/server.mjs: ENOENT: no such file or directory, open 'C:\Users\mario\Documents\dev\nuxt3-starter\file:\C:\Users\mario\Documents\dev\nuxt3-starter\.nuxt\dist\server\server.mjs'`

**Comment by huang-julien** [comment]
with ssr false, nuxt should create a .nuxt/dev folder instead of .nuxt/server

**Comment by huang-julien** [comment]
it might have been fixed with rc2 ?

**Comment by micahlt** [comment]
This is a pretty critical bug - any updates?

**Comment by 849203846** [comment]
This is a pretty critical bug - any updates?

**Comment by 849203846** [comment]
> This is a pretty critical bug - any updates?

**Comment by 849203846** [comment]
This is a pretty critical bug - any updates?

**Comment by danielroe** [comment]
@svedova You mean when you run `nuxi dev` locally it fails with `ssr: false`, but deployed on Stormkit Cloud `nuxi build` runs fine? Can you provide any more info or a reproduction repo?

**Comment by svedova** [comment]
@danielroe I used https://github.com/viandwi24/nuxt3-awesome-starter. 

Locally (with or without Stormkit), if I run `npm run build` I receive the error above. On [stormkit.io](https://stormkit.io) it works though, I was able to build. 

Here's the sysinfo of my local machine:

```
      System Version: macOS 12.2.1 (21D62)
      Kernel Version: Darwin 21.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Savas’s MacBook Pro
      User Name: Savas Vedova (savasvedova)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 97 days 1:55
```

**Comment by lucasctd** [comment]
In my case it's looking for a package.json inside server.mjs, which doesn't make sense for me.
I just upgraded my dependencies so it doesn't seem to be fixed yet.

![image](https://user-images.githubusercontent.com/5876679/177794692-37b830bd-4353-4f27-8336-6b0e63d94980.png)

Does anyone know a workaround for this?

Thanks =D

**Comment by lucasctd** [comment]
Downgrading to version: 3.0.0-rc.3-27579668.27a0084 "solved" the problem for now.

**Comment by lucasctd** [comment]
> @lucasctd If you can provide a reproduction I can test whether the linked PR solves it 👍

@danielroe, So, on the latest version if I run `nuxi build` with SSR false, it will display the same error reported on this issue. However, if I set SSR to true, run `nuxi build` and then set SSR back to false, it'll display the error I posted above.

Does it help?

**Comment by danielroe** [comment]
@lucasctd Are you on the latest edge version?

**Comment by lucasctd** [comment]
When I had that issue, I was on the latest version at the time I wrote the issue which was: 3.0.0-rc.4-27619747.ad8b5f9 from yesterday.

**Comment by danielroe** [comment]
Unfortunately, that version predated the fix.

**Comment by davinma** [comment]
When run `yarn dev` and code changed, there is an error like this:

```bash
ERROR  ENOENT: no such file or directory, open '/Users/mac/myrepo/.nuxt/dist/server/server.js'    
```

BTW, only occasionally this error occurs.
