### ISSUE TITLE
Cannot find module /.nuxt/base-module - After importing package in /server/api

### ISSUE THREAD

**Issue by birdlavv** [nuxt/framework#4785]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `ssr`, `target`, `buildModules`, `meta`, `typescript`, `publicRuntimeConfig`, `privateRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.3.1`

### Reproduction

https://stackblitz.com/edit/github-xufswv-vtqwsw?file=package.json
1. Create a blank project
2. Add `server/api/test.ts`
3. Try to import a package like `@magic-sdk/admin` in `server/api/test.ts`

### Describe the bug

When certain packages, `@magic-sdk/admin`, in my case are used in a server route, the dev server stops working.

The console says ` ERROR  [worker reload] [worker init] Cannot find module project-root/.nuxt/base-module' imported from project-root/.nuxt/dev/index.mjs` when running `npm run dev`

### Additional context

I tested other packages, `luxon` works fine

**Comment by robinscholz** [comment]
Running into the same problem with a local dependency within a turborepo setup.

**Comment by birdlavv** [comment]
Possibly related to rollup & nitro - https://github.com/unjs/nitro/issues/200
I've tried to reproduce in raw nitro: https://stackblitz.com/edit/node-nbvgzy?file=routes%2Findex.ts
The build has trouble resolving its dependencies (`npx nitropack build`)

**Comment by birdlavv** [comment]
This isssue is partially resolved as of `nitropack@0.4.24`.

It now has the following error ```'/var/task/node_modules/ethereum-cryptography/keccak' imported from /var/task/chunks/raw/index.mjs
Did you mean to import ethereum-cryptography/keccak.js?```
Closing this issue.

Adding the package to `build.transpile` in `nuxt.config.ts` as a workaround does not work.

This new message looks similar to https://github.com/unjs/nitro/issues/386, tracking there. 
https://github.com/unjs/nitro/pull/387 may resolve the issue.
