### ISSUE TITLE
vscode ts hover hint: Cannot find name 'defineEventHandler' 

### ISSUE THREAD

**Issue by xiangnanscu** [nuxt/framework#4789]
### Environment

Nuxt CLI v3.0.0-rc.2                                                                                                               15:00:39
RootDir: /root/nuxt-app                                                                                                            15:00:40
Nuxt project info:                                                                                                                 15:00:40

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                   15:00:40

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

Just follow the official get started doc:
```
npx nuxi init nuxt-app
cd nuxt-app
yarn install
npx nuxi add api hello
```
and open file `server/api/hello.ts`,
```
export default defineEventHandler((event) => {
  return 'Hello hello'
})
```
cursor on token `defineEventHandler`, you will get:
![nuxt](https://user-images.githubusercontent.com/8246344/166636240-b56faed4-0026-4424-8b7a-801fc89c71d2.png)

### Describe the bug

![nuxt](https://user-images.githubusercontent.com/8246344/166636240-b56faed4-0026-4424-8b7a-801fc89c71d2.png)

**Comment by xiangnanscu** [comment]
volar is in take over mode, and
## nuxt.config.ts
```
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  typescript: {
    shim: false
  }
})

```
## tsconfig.json
```
{
  // https://v3.nuxtjs.org/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "lib": ["esnext"],
    "esModuleInterop": true
  },
  "include": ["server/**/*.ts", "src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
  "vueCompilerOptions": {
    "experimentalCompatMode": 2,
    "experimentalTemplateCompilerOptions": {
      "compatConfig": { "MODE": 2 } // optional
    }
  }
}

```

**Comment by danielroe** [comment]
You should remove the `include` setting in your `tsconfig`, which excludes the Nuxt-generated types within `.nuxt`.

**Comment by xiangnanscu** [comment]
thanks
