### ISSUE TITLE
@click event doesnot work

### ISSUE THREAD

**Issue by IakobMirotadze** [nuxt/framework#4796]
vue 3 (nuxt)
....
methods: {
    myFunction(){
       ....
    }
}

i try to catch click event like this on div

1.  @click="myFunction"
2.  @click="myFunction()"
3.  @click="()=> myFunction()"
4.  @click="()=> ..."

none of the above works :( cant figure out what happens

**Comment by Luferov** [comment]
Same in bridge, maybe it depends with defu? Have you any errors in console?

**Comment by IakobMirotadze** [comment]
no, no errors,
other events doesnot work too with "@" symbol(@click, @input, @mouseover...),
 with "on" (for example "onclick") it works but says that function is not defined

**Comment by Luferov** [comment]
And if add .native to event, for example, @click.native="myFunction"?

**Comment by IakobMirotadze** [comment]
same... nothing changes,

**Comment by Luferov** [comment]
I think a reproduction is needed, is it possible?

**Comment by IakobMirotadze** [comment]
https://github.com/IakobMirotadze/NuxtReproduction

**Comment by Luferov** [comment]
Are you using Vite or Webpack?

**Comment by danielroe** [comment]
Let me know if you still think there is a bug in Nuxt and I'll reopen.

**Comment by IakobMirotadze** [comment]
its not custom event, and to check if custom events cause that problem i deleted all custom ( emitting) event, but still the same. non of the default events work ( input, click, mouseover...)

**Comment by IakobMirotadze** [comment]
> Let me know if you still think there is a bug in Nuxt and I'll reopen.

i still cant fix it :( there might be issue

**Comment by danielroe** [comment]
Would you provide a reproduction then?

**Comment by yk-sgr** [comment]
I'm having the same issue. It used to work and then all of a sudden it didn't. I didn't investigate it further at first because I thought I had broken something. Now after closer examination I found out that no click event works.
But I can't give a real reproduction either.

```
export default defineNuxtConfig({
  css: ['~/assets/css/fonts.css'],
  modules: [
    '@nuxtjs/tailwindcss',
    '@pinia/nuxt'
  ],
  nitro: {
    prerender: {
      crawlLinks: true,
      routes: ['/']
    },
  },
})
```
* removing the nitro settings doesn't change anything

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^5.3.1",
    "nuxt": "3.0.0-rc.8"
  },
  "dependencies": {
    "@headlessui/vue": "^1.6.7",
    "@pinia/nuxt": "^0.4.0",
    "mande": "^2.0.3",
    "pinia": "^2.0.18"
  }
}
```

Node: v16.16.0

I also tested in on Windows and Mac. Bot not working.

**Comment by yk-sgr** [comment]
```
<template>
  <div>
    <p>Ref Value: {{ testRef }}</p>
    <button @click="updateVal()">Update Value</button>
  </div>
</template>

<script lang="ts" setup>
const testRef = ref('value_1');

const updateVal = () => {
  testRef.value = 'changed_2';
};
</script>
```

Works on Stackblitz, does not work in my project.

**Comment by yk-sgr** [comment]
Actually was able to find the issue.

This line caused the events not working. Removing the `process.env` worked.
Funny thing is, this line was not even called on the test page I created, and all the code that relies on that variable worked without a single problem. The only problems were the events.

`export const baseUrl = process.env.API_URL || "https://api.xxx.com";`

**Comment by bachdgvn** [comment]
Try clear site data. It helps to solve my problem. I think it might be cached.
![image](https://user-images.githubusercontent.com/30729887/203099415-1a21d229-b59a-402a-831b-12dafac078d4.png)

**Comment by zwoefler** [comment]
> Let me know if you still think there is a bug in Nuxt and I'll reopen.

@danielroe Can you at tell us noobs how we would be able to debug this?

**Comment by danielroe** [comment]
You can start with your project, and gradually remove pages/components/plugins/modules until the issue doesn't reoccur. Then add back the thing that caused it, and remove other pieces, until you're left with a very minimal reproduction of _just_ what is causing the bug.

For this, you can start a new branch in your repository and just ruthlessly comment stuff out/delete pages files. Feel free to add commits if you want to track your progress so you can go back and see the process.

Once you have boiled it down to the cause, if you find it's not cause by a dependency or your own code, you can then open a new issue, tag me, and I'll happily look at it.

**Comment by larsalbrecht** [comment]
Here is what I have found out (so far):

I have two setups: 
With Docker
Without Docker

When I start in Docker (1:1 the same code), I don't have any clickhandlers.

In Docker I already fixed the hot-reload, but I still get error messages:
entry.mjs:1 GET https://localhost/_nuxt/@fs/opt/frontend/node_modules/.vite/deps/vue.js?v=92797187 403
entry.mjs:3 GET https://localhost/_nuxt/@id/virtual:nuxt:/opt/frontend/.nuxt/paths.mjs net::ERR_ABORTED 403
entry.mjs:5 GET https://localhost/_nuxt/@id/virtual:nuxt:/opt/frontend/.nuxt/css.mjs net::ERR_ABORTED 403
entry.mjs:6 GET https://localhost/_nuxt/@id/virtual:nuxt:/opt/frontend/.nuxt/plugins/client.mjs?t=1670240886220 net::ERR_ABORTED 403
entry.mjs:7 GET https://localhost/_nuxt/@id/virtual:nuxt:/opt/frontend/.nuxt/root-component.mjs?t=1670241224296 net::ERR_ABORTED 403
entry.mjs:8 GET https://localhost/_nuxt/@id/virtual:nuxt:/opt/frontend/.nuxt/nuxt.config.mjs net::ERR_ABORTED 403


Do others with this problem also have Docker running?

**Comment by danielroe** [comment]
The click handler is not working because no JS is being loaded as you are not able to connect to your dev server via docker. Search the GitHub Discussions in this repo - there are lots of example configurations that people are using successfully.

**Comment by larsalbrecht** [comment]
@danielroe Yes, that is my guess as well. 
Maybe the others (in this thread) also have the problem without having seen it.

**Comment by frankrousseau** [comment]
Hello there,
I experienced the same problem. The @click listener didn't work. It was due to an error in the console related to Nuxt. 
I had this error:  `TypeError: process.env is undefined`. It was raised by a library named `fs.realpath` in file named `old.js`. I had to remove the `stylus` dependency to get my event listeners back.

**Comment by leogargioni** [comment]
I'm facing this issue too. Here is a very simple reproduction: https://stackblitz.com/edit/github-jsuxnz?file=app.vue

**Comment by danielroe** [comment]
@leogargioni it seems to work fine in your reproduction.

![CleanShot 2023-01-07 at 09.34.45@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_01_07_at_09_34_45_2x_b85dd19c61.png)

**Comment by leogargioni** [comment]
Thanks for the quick reply @danielroe! It must be something with my machine then... I'm trying both in Firefox and Chrome, and in both I can't see the "not working". I'm on Windows 10.

**Comment by danielroe** [comment]
Have you opened dev tools? The Stackblitz terminal will only show the console log on server, not client side.

**Comment by leogargioni** [comment]
Interesting... In Chrome I can't see the "not working" in dev tools (both remote and locally), but in Firefox I could see it :) Thanks for the support.
