### ISSUE TITLE
Firebase initializeApp() with Nuxt 3

### ISSUE THREAD

**Issue by m6keller** [nuxt/framework#4799]
### Environment

Operating System version: macOS 10.15.7
Firebase version: 10.7.2
Firebase Product: firestore (auth, hosting)
Nuxt: 3.0.0-rc.2

### Reproduction

The bug is with a single function used a file under the "plugins" directory:

```
import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";

export default defineNuxtPlugin( (nuxtApp) => {
    
    const config = useRuntimeConfig();
    
    const firebaseConfig = {
        apiKey: config.FIREBASE_API_KEY
      };
    
    // Initialize Firebase
    initializeApp(firebaseConfig);

    initUser();
  
    const auth = getAuth();
  
    nuxtApp.vueApp.provide('auth', auth);
    nuxtApp.provide('auth', auth);  
});
```

### Describe the bug

I am receiving this error:
```
Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
```
This is resolved after commenting out:
```
const auth = getAuth();
  
nuxtApp.vueApp.provide('auth', auth);
nuxtApp.provide('auth', auth);  
```
Other similar issues on GitHub suggest that firebase should be initialized before using other firebase functions but this is true in my code. I could not find similar issues with using the Nuxt 3 framework. 

### Additional context

I was unsure if this was a bug or an issue with my code. I opened a discussion here: [#4798](https://github.com/nuxt/framework/discussions/4798)

**Comment by DevJoghurt** [comment]
Since it's not a nuxt bug, I replied to you in your discussion
https://github.com/nuxt/framework/discussions/4798#discussioncomment-2692276
