### ISSUE TITLE
Excessive stack depth comparing types 'NuxtModule<ModuleOptions>' and 'NuxtModule<ModuleOptions>' + Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by florian-lefebvre** [nuxt/framework#4818]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.17.1`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `yarn@1.22.5`
- Builder:          `vite`
- User Config:      `modules`, `css`, `build`, `runtimeConfig`, `tailwindcss`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.4`, `@pinia/nuxt@0.1.9`, `@vueuse/nuxt@8.4.1`, `./modules/storesAutoImports`
- Build Modules:    `-`

### Reproduction

https://github.com/florian-lefebvre/nuxt3-starter-medusa/tree/3e2b13d7a6d42542e80894298c6208176bc40577

### Describe the bug

In the Nuxt config file, the tailwindcss config throws the following errors:

- Excessive stack depth comparing types 'NuxtModule<ModuleOptions>' and 'NuxtModule<ModuleOptions>' [ts(2321)]
- Type instantiation is excessively deep and possibly infinite [ts(2589)]

### Additional context

Related: https://github.com/nuxt/framework/discussions/4754

Screenshot:
![image](https://user-images.githubusercontent.com/69633530/166925445-74a1ac62-16d3-426e-9fb8-e35dfae110a9.png)

**Comment by qnp** [comment]
+1 experiencing the same issue with only:
```
export default defineNuxtConfig({
  telemetry: true,
});
```

on:
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `yarn@1.17.3`
- Builder:          `vite`
- User Config:      `telemetry`
- Runtime Modules:  `-`
- Build Modules:    `-`

**Comment by danielroe** [comment]
I can't reproduce this. Let me know if you are still experiencing it and I'll reopen. :pray:
