### ISSUE TITLE
Take commented out code as import

### ISSUE THREAD

**Issue by potatozerg** [nuxt/framework#4826]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.17.4`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `components`, `srcDir`, `buildModules`, `css`, `build`, `alias`, `meta`, `app`, `vite`, `router`, `typescript`, `runtimeConfig`, `modules`, `sitemap`
- Runtime Modules:  `~/modules/sitemap`
- Build Modules:    `@pinia/nuxt@0.1.8

### Reproduction

N/A

### Describe the bug

I commented out this function in composables/utils.ts
![image](https://user-images.githubusercontent.com/3282773/166966557-54dd98e6-65a2-4ea7-a4eb-31273f74a2ed.png)

However, it seems like Nuxt still takes it as an import (composables auto imports). After I delete the code, it works fine.
![image](https://user-images.githubusercontent.com/3282773/166967092-055547f7-3d36-4303-aa60-c2a0846cbc8b.png)

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by Lyokolux** [comment]
I have tried to reproduct this bug without success: https://stackblitz.com/edit/nuxt-starter-uswxkp?file=composables%2Futils.ts,app.vue

I wrote this function, used it (or not), commented it. Nothing special happened.

**Comment by potatozerg** [comment]
I tried other functions and experienced the same issue. Maybe this is just for me?

**Comment by Lyokolux** [comment]
> I tried other functions and experienced the same issue. Maybe this is just for me?

Can you try to provide a reproduction on Stackblitz close to your code ? This should however not happen 🤔

**Comment by aazvf** [comment]
I think I have the same problem on my machine.

@Lyokolux I tried reproducing on stackblitz but it's not triggering

I can reproduce it on my local machine quite simply

```
npx nuxi init freshapp
cd freshapp && npm install
mkdir composables
nano composables/use-things.ts
```

The composable file simply contains the commented code
```
// export function useNotThings
```

After starting `npm run dev` I can now see in the terminal

![Screenshot from 2022-05-17 14-59-46](https://user-images.githubusercontent.com/70022208/168829942-08233ed6-512a-4834-b9f3-0da9c3c5549a.png)

------------------

```
Linux machine 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.8.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

The problematic line in the file `imports.mjs` is

```
export { useNotThings } from '/mnt/slowdata/projects/current/nuxt/freshapp/composables/use-things';
```

Changing the comment also changes this import, putting a typo in `export function` prevents the bug from happening. It was this effect which finally confirmed for me what was going wrong in my project. As I said, this didn't reproduce on stackblitz, surely there's something @potatozerg and I have in common if others haven't reported this by now. For now I'll give a little extra attention to what I'm commenting out.
