### ISSUE TITLE
defineEventHandler() is undefined in ~/server/api on Stackblitz

### ISSUE THREAD

**Issue by Lyokolux** [nuxt/framework#4835]
### Environment

Stackblitz starter template

------------------------------
Nuxt CLI v3.0.0-rc.2 (and Nuxt CLI v3.0.0-rc.1) 
RootDir: /home/projects/nuxt-starter-sh8cyl                                      10:06:48
Nuxt project info:                                                               10:06:48

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-sh8cyl?file=server/api/hello.ts

### Describe the bug

The `defineEventHandler()` function used in the `~/server/api` folder is marked as undefined.

Error message: 
`Cannot find name 'defineEventHandler'.(2304)
any`

### Additional context

As stated in the documentation,
>Nuxt exposes every auto-import with the #imports alias that can be used to make the import explicit if needed

`import { defineEventHandler } from '#import';` returns an error too: `Cannot find module '#import' or its corresponding type declarations.`

**Comment by danielroe** [comment]
I believe this is caused by the fact that stackblitz hides the `.nuxt` folder. Let's see what the team there might be able to do.

**Comment by mumumilk** [comment]
managed to get it working by adding h3 as a dependency and calling it explicitly:

in `server/api/middleware/log.js`
```js
import { defineEventHandler } from 'h3';

export default defineEventHandler((ev) => console.log(ev.req.url));
```

**Comment by danielroe** [comment]
@HendrikJan That repository is old (pre-RC) and the version of nitropack/nuxt installed there doesn't have support for auto-importing in server files.

**Comment by danielroe** [comment]
This has now been implemented in Stackblitz.
