### ISSUE TITLE
__dangerouslyDisableSanitizers not available on head method

### ISSUE THREAD

**Issue by DiogoDuart3** [nuxt/framework#4854]
### Environment

"__dangerouslyDisableSanitizers" is not available on the head method.

### Reproduction

Create a new project and on the <script> insert
`head(){
return { __dangerouslyDisableSanitizers: ['script'], script: [
        {
          type: 'application/ld+json',
          innerHTML: JSON.stringify(this.structuredData),
        },
      ], } }`

### Describe the bug

The property is not being read or is not available

**Comment by HarrisWebApps** [comment]
Not an answer to your bug, but a work around:  [nuxt-jsonld](https://www.npmjs.com/package/nuxt-jsonld).

**Comment by danielroe** [comment]
`__dangerouslyDisableSanitizers` is a feature of `vue-meta` and is not applicable in Nuxt 3. You can directly return the code you want to be displayed there:

```js
<template>
  <div>
    <NuxtWelcome />
  </div>
</template>

<script>
export default {
  head() {
    return {
      script: [
        {
          children: 'console.log("some stuff")',
        },
      ],
    };
  },
};
</script>
```

See https://stackblitz.com/edit/github-zgdvgz?file=app.vue.
