### ISSUE TITLE
useAsyncData can‘t watch slug

### ISSUE THREAD

**Issue by NidMo** [nuxt/framework#4855]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `pnpm@6.23.6`
- Builder:          `vite`
- User Config:      `modules`, `experimental`, `unocss`, `colorMode`
- Runtime Modules:  `@vueuse/nuxt@8.3.1`, `@unocss/nuxt@0.32.9`, `@pinia/nuxt@0.1.8`, `@nuxtjs/color-mode@3.0.2`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-wp5lsq-fyzsuf?file=pages/[slug].vue

### Describe the bug

useAsyncData cannot update data correctly when watch slugs

**Comment by NidMo** [comment]
Now I use a stupid method, using a meaningless flag to trigger the watch

```
const flag = ref(true)
const { data: article } = await useAsyncData('key', async() => {
  // code
return await xxApi(slug)
}, {
  watch: [flag],
})

onMounted(() => {
  flag.value = false
})
```

**Comment by harysonii** [comment]
@NidMo try this.

`{
watch: [route]
}`

**Comment by danielroe** [comment]
This is no longer reproducible in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/): https://stackblitz.com/edit/github-wp5lsq-s1qr17.

Likely resolved by https://github.com/nuxt/framework/pull/7055.

**Comment by windel07** [comment]
@NidMo You can set the `watch` value to `[() => flag.value]`

**Comment by sangyookim-ogq** [comment]
```
async setup() {
    const route = useRoute()
    const {data: noticeData} = useAsyncData(
      ()=> $fetch('/api/notice/single', {
        method: 'get',
        headers: useRequestHeaders(['cookie']),
        params: {
          noticeId: route.params.noticeId
        }
      }, {
        initialCache: false,
        watch: [route]
      })
    )
    return {
      noticeData
    }
  }
  ```
  
My data wont refresh after the first time.

PageA -> PageB[AsyncData with param 1| Works] -> Back button to Page A -> PageB[AsyncData with param2|  stuck in param 1 data]

**Comment by manniL** [comment]
@sangyookim-ogq kindly create a new issue instead of replying to old closed ones ☺️ (Feel free to link this one in your new issue though). And please provide a reproduction!
