### ISSUE TITLE
Unhandled error when navigating to a route that doesn't exist

### ISSUE THREAD

**Issue by oysandvik94** [nuxt/framework#4862]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.2-27530889.9e5a3cd`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I'm struggling to make it run on this sandbox thing, sorry, but running these files locally reproduces the error by going to a random path, i.e. "http://localhost:3000/asd"
https://codesandbox.io/s/async-microservice-qj7wic?file=/pages/foo/index.vue

### Describe the bug

When I hit an incorrect route that would produce a 404, I'm getting an unhandled error somewhere inside the Nuxt error handling.

> [nitro] Error while generating error response FetchError: 301  (/__nuxt_error?url=/asd&statusCode=404&statusMessage=Page+not+found:+/asd&message=Page+not+found:+/asd&description&data)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.errorhandler [as onError] (file:///D:/dev/jobb/test/nuxt-app/.output/server/chunks/node-server.mjs:317:16)
    at async Server.nodeHandler (file:///D:/dev/jobb/test/nuxt-app/.output/server/node_modules/h3/dist/index.mjs:370:9)
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

> Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at Object.errorhandler [as onError] (file:///D:/dev/jobb/test/nuxt-app/.output/server/chunks/node-server.mjs:321:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server.nodeHandler (file:///D:/dev/jobb/test/nuxt-app/.output/server/node_modules/h3/dist/index.mjs:370:9) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

If I remove the middleware it works as expected.

This also works as expected in RC-1.

**Comment by huang-julien** [comment]
It seems to be triggered only on initial load, might be linked with #4865 ? Hitting the route with a router.push after initial load does not trigger the error

**Comment by huang-julien** [comment]
nvm, i couldn't make the router work on rc-2

**Comment by huang-julien** [comment]
So because your page does not exist in the vue router it throws an 404 error , maybe should you use a serverMiddleware to handle the redirection ? there is a helper called addServerHandler() to add a handler to nitro through modules

**Comment by huang-julien** [comment]
[oysandvik94](https://github.com/oysandvik94) this should work on nuxt rc 2
````ts
import { defineNuxtConfig } from 'nuxt'
import { defineEventHandler, sendRedirect } from 'h3'
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  serverMiddleware: [
    defineEventHandler((evt) => {
      if (evt.req.originalUrl !== "/foo") {
        sendRedirect(evt.res, "/foo");
      }
    }),
  ],
});

````

stackblitz : https://codesandbox.io/s/nuxt-rc-2-initialurl-redirection-y5ebub

However it logs vue-router error in the console but you will get your page rendered.

**Comment by oysandvik94** [comment]
Sorry, I didnt get a chance to try the workaround, but in the latest build I'm not getting same error. 

I am getting the 301 FetchError, but the unhandled 
"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client" 
error is not presetn anymore. I think it's due to this https://github.com/nuxt/framework/pull/4913

Thanks for the help!
