### ISSUE TITLE
PageTransition JavaScript Hooks problem

### ISSUE THREAD

**Issue by mak33v** [nuxt/framework#4880]
Greetings. I ran into a problem when calling javascript transition hooks.

I have reproduced the issue here:

https://stackblitz.com/edit/nuxt-starter-6qvzci?file=pages/second.vue

Can you please tell me if I can assign global transitions for all pages, as it is implemented, for example, in vue router.

`<router-view v-slot="{ Component }">
    <transition name="fade" mode="out-in">
        <component :is="Component" />
    </transition>
</router-view>`

**Comment by jiblett1000** [comment]
As far as I know global transitions are not yet implemented. I've already raised an issue regarding this. https://github.com/nuxt/framework/issues/4223

**Comment by mak33v** [comment]
> As far as I know global transitions are not yet implemented. I've already raised an issue regarding this. #4223

If I can access the javascript transition hook I could implement it myself, but I can't do it, I have implemented it in the problem example. You don't know how to do it?

**Comment by jiblett1000** [comment]
I know 'page:start' and 'page:finish' are available on 'nuxtApp', but I haven't got a working implementation just yet. Not entirely sure those are going to be the best hooks for it anyways. I'll post back here if I get something working.

**Comment by derz** [comment]
You could use a middleware to do that, for example:

`
export default defineNuxtRouteMiddleware((to, from) => {
    // don't overwrite default transition...
    if ( to.meta.pageTransition == null) {
        to.meta.pageTransition = {
            name: 'default-transition',
            mode: 'in-out',
        };
    }
});
`

**Comment by mak33v** [comment]
Thank you for your answers, thanks to them I have implemented everything I wanted.

@jiblett1000 Thanks to your tip on these hooks, I implemented a java script logic for transitions:

`
// app.vue
const nuxtApp = useNuxtApp()
nuxtApp.hook('page:start', () => {
  ....
})
nuxtApp.hook('page:finish', () => {
  ....
})
`

@derz Your answer helped implement transition properties globally for all pages
