### ISSUE TITLE
NuxtLink scrollBehavior broken

### ISSUE THREAD

**Issue by jiblett1000** [nuxt/framework#4888]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.2-27530889.9e5a3cd`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jiblett1000/nuxt-scroll-test

### Describe the bug

Scroll behavior is completely broken. This seems to be with NuxtLink at least. I've included a regular <a> link in the reproduction to show that scrolling to a href isn't working with NuxtLink.

**Comment by Catrionaa** [comment]
Same issue here

**Comment by danielroe** [comment]
This is not a Nuxt issue. You can see that this behaviour is also present in the `RouterLink` component from `vue-router` without Nuxt:

https://stackblitz.com/edit/github-g9wpe2?file=src%2FApp.vue&terminal=dev

You can raise an issue upstream at https://github.com/vuejs/router.

**Comment by jshimkoski** [comment]
@jiblett1000, Add `/app/router.options.ts` to your project with this following content and see if this helps:

```javascript
import type { RouterConfig } from '@nuxt/schema';

// https://router.vuejs.org/api/#routeroptions
export default <RouterConfig> {
  scrollBehavior(to, _from, savedPosition) {
    // return a promise with a 100ms delay to correct hard refresh timing issues
    return new Promise((resolve, _reject) => {
      setTimeout(() => {
        if (savedPosition) {
          resolve(savedPosition)
        } else {
          resolve({
            el: to.hash,
            // top: 0 // offset from top if you need it, i.e., you have a sticky header
          })
        }
      }, 100)
    })
  },
};
```

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

Let me know if not and I'll reopen.

**Comment by jiblett1000** [comment]
I don't have this test repo up and running at the moment, but I updated to the edge release and the default router behavior seems to be working great. Nice to be able to remove my custom router.config.ts. Appreciate all the hard work! :)
