### ISSUE TITLE
How to introduce wangEditor in nuxt3

### ISSUE THREAD

**Issue by chen-ccll** [nuxt/framework#4893]
### Environment

  "nuxt": "3.0.0-rc.2"

### Reproduction

https://github.com/chen-ccll/nuxt3-demo

### Describe the bug

How to introduce wangEditor in nuxt3, according to the nuxt3 plug-in, it does not take effect, I don't know if it is a problem with my reference method
```javascript
<template>
  <div class="content">
    <div class="card-container">
      <a-tabs v-model:activeKey="activeKey" type="card">
        <a-tab-pane key="1">
          <template #tab>
            <span>
              <fire-outlined />
              AAA
            </span>
          </template>
          <div style="border: 1px solid #ccc">
            <Toolbar
              style="border-bottom: 1px solid #ccc"
              :editor="editorRef"
              :defaultConfig="toolbarConfig"
              :mode="mode"
            />
            <Editor
              style="height: 500px; overflow-y: hidden"
              v-model="valueHtml"
              :defaultConfig="editorConfig"
              :mode="mode"
              @onCreated="handleCreated"
            />
          </div>
        </a-tab-pane>
        <a-tab-pane key="2">
          <template #tab>
            <span>
              <question-outlined />
              BBB
            </span>
          </template>
          BBB
        </a-tab-pane>
        <a-tab-pane key="3">
          <template #tab>
            <span>
              <edit-outlined />
               CCC
            </span>
          </template>
          <p>CCC</p>
        </a-tab-pane>
      </a-tabs>
    </div>
  </div>
</template>
<script setup>
import {
  FireOutlined,
  EditOutlined,
  QuestionOutlined,
} from "@ant-design/icons-vue";
import { Editor, Toolbar } from "@wangeditor/editor-for-vue";
definePageMeta({
  layout: "custom",
});
const activeKey = ref("1");

useHead({
  titleTemplate: `MoneyBoxs`,
});
</script>
```

### Logs

```shell
[nuxt] [request error] window.cancelAnimationFrame is not a function
  at caf (D:\nuxt3-demo\node_modules\ant-design-vue\lib\_util\raf.js:22:19)
  at Function.wrapperRaf.cancel (D:\nuxt3-demo\node_modules\ant-design-vue\lib\_util\raf.js:61:10)
  at immediate (D:\nuxt3-demo\node_modules\ant-design-vue\lib\menu\src\PopupTrigger.js:78:20)
  at callWithErrorHandling (D:\nuxt3-demo\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
  at callWithAsyncErrorHandling (D:\nuxt3-demo\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:166:21)
  at doWatch (D:\nuxt3-demo\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:1744:13)
  at watch (D:\nuxt3-demo\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:1656:12)
  at setup (D:\nuxt3-demo\node_modules\ant-design-vue\lib\menu\src\PopupTrigger.js:75:20)
  at callWithErrorHandling (D:\nuxt3-demo\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
  at setupStatefulComponent (D:\nuxt3-demo\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7027:29)
```

**Comment by yzqdev** [comment]
Maybe this is not a nuxt issue. Your reference method is right. I run nuxt with wangEditor very well. Maybe you have some dependencies which have conflicts with wangEditor. You could check your dependencies.

![image](https://user-images.githubusercontent.com/20037151/167401718-cf3a036d-2551-4de7-8650-b0d9de2a9bf0.png)

**Comment by chen-ccll** [comment]
I used antd design vue in the project. I deleted the dependencies. After reinstalling, it still reported an error. Can you post how you introduced and used wangEditor?thank you
![image](https://user-images.githubusercontent.com/59905508/167524777-248ceb79-9c4d-4dd6-a4f6-84b76671de3d.png)

**Comment by chen-ccll** [comment]
> Maybe this is not a nuxt issue. Your reference method is right. I run nuxt with wangEditor very well. Maybe you have some dependencies which have conflicts with wangEditor. You could check your dependencies.
> 
> ![image](https://user-images.githubusercontent.com/20037151/167401718-cf3a036d-2551-4de7-8650-b0d9de2a9bf0.png)

**Comment by chen-ccll** [comment]
I used antd design vue in the project. I deleted the dependencies. After reinstalling, it still reported an error. Can you post how you introduced and used wangEditor?thank you
![image](https://user-images.githubusercontent.com/59905508/167524998-0a2f13c8-cc43-4381-861b-56259647cc6f.png)

**Comment by yzqdev** [comment]
@chen-ccll  Just as the official wangEditor document says. Here is a minimal repo. https://stackblitz.com/edit/github-6l1avr?file=package.json,app.vue
