### ISSUE TITLE
allow throwing error within async function

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/framework#4897]
### Environment

https://stackblitz.com/edit/nuxt-starter-4amzzp?file=app.vue

### Reproduction

https://stackblitz.com/edit/nuxt-starter-4amzzp?file=app.vue

### Describe the bug

As with the reproduction, I can't throw an error after calling a server api endpoint

**Comment by danielroe** [comment]
Similar issue to https://github.com/nuxt/framework/issues/4902#issuecomment-1122109918. This should be resolved by https://github.com/nuxt/framework/pull/4539 providing a way to directly throw an error that doesn't depend on having the Nuxt context available...
