### ISSUE TITLE
sfc setup await cannot get nuxtApp

### ISSUE THREAD

**Issue by taoxhsmile** [nuxt/framework#4902]
### Environment

Nuxt CLI v3.0.0-rc.2

### Reproduction
```vue
<template>
  <div>index</div>
</template>
<script type="ts" setup>
const delay = (ms) => {
  return new Promise((resolve) => {
    setTimeout(resolve, ms)
  })
}

const fn = async () => {
  await delay(1000);
  if(process.server){
    navigateTo("/login")
  }
};

await fn();
</script>
```

### Describe the bug

We need to log in to access the home page, but I don't want to define auth middleware. Instead, when we visit the home page and request the API on the server side, a code will be returned to indicate that we need to log in. At this time, I call navigateto ("/ login") through $fetch onrequest callback. But it didn't work. What should I do?

**Comment by wobsoriano** [comment]
Not really a bug... it's because of `if(process.server){}`. It's already false after that 1 second delay

**Comment by danielroe** [comment]
Vue is able to preserve context between awaits within a setup function, but that is not the case within additional functions that you are calling within a setup function.

You would be better off doing:

```js
const router = useRouter()
const myFunc = async () => {
  await delay(3000)
  await router.push('/')
}
```

However, I would add a note of caution to the general approach you are taking. Perhaps open a discussion with more information about what you are trying to do, and others can advise?
