### ISSUE TITLE
setting `global` in `vite.define` breaks build

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/framework#4916]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `yarn@3.1.1`
- Builder:          `vite`
- User Config:      `ssr`, `runtimeConfig`, `typescript`, `css`, `buildModules`, `alias`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.4.2`, `@intlify/nuxt3@0.1.10`
------------------------------

### Reproduction

Simply set these settings, and execute `npx nuxi generate` or `nuxi build`.
```ts
// nuxt.config.ts
export default defineConfig({
  // ...
  alias: {
    // ...
    './runtimeConfig': './runtimeConfig.browser',
  },
  vite: {
    // ...
    define: {
      "global": {},
    }
  }
});
```

### Describe the bug

More precisely, it seems that the global variable conflicts with nuxt's middleware or something similar. 
However, this error does not appear when running `nuxi dev`.

### Additional context

This **global** parameter is the currently _standard_ flag that is added to solve runtime issues with AWS Amplify. 
See #2308 for the related discussion.

### Logs

```
------------------------------
67:   nuxtApp._activeRoute = reactive(activeRoute);
68:   nuxtApp._middleware = nuxtApp._middleware || {
69:     global: [],
        ^
70:     named: {}
71:   };


 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)   

 ------------------------------
```

**Comment by danielroe** [comment]
It looks like this is an upstream bug, either in vite or esbuild, rather than a Nuxt issue. See https://stackblitz.com/edit/github-apto8d...

Would you raise an issue at https://github.com/vitejs/vite and comment here so we can track it?

**Comment by ennioVisco** [comment]
> It looks like this is an upstream bug, either in vite or esbuild, rather than a Nuxt issue. See https://stackblitz.com/edit/github-apto8d...
> 
> Would you raise an issue at https://github.com/vitejs/vite and comment here so we can track it?

Sure, but why does it work in dev mode then? What's the difference there?

**Comment by pi0** [comment]
The linked issue regarding `global` polyfill for vite: https://github.com/nuxt/framework/issues/1922

**Comment by danielroe** [comment]
It seems linked to the server build.

If you have any comments about support in amplify, let's raise at https://github.com/unjs/nitro/issues/80 so we can create a preset that doesn't require workarounds.

**Comment by ennioVisco** [comment]
> unjs/nitro#80

It's not related to the Amplify hosting environment but to the Amplify SDK. 
Quite unfortunately, Amazon calls both the same way but they can be -and frequently are- used independently.

**Comment by danielroe** [comment]
In that case the issue to follow is #1922 linked above by @pi0.

**Comment by rvmourik** [comment]
> In that case the issue to follow is #1922 linked above by @pi0.

@danielroe In addition to my reply, is there a work-a-round for the time being that you know of? We tried to add a .js-file from the public folder, through either a `<Script>` component or through the `nuxt.config.ts` but the moment that gets loaded is too late and the aws-sdk libraries will complain about the missing `global`. 

Thanks in advance

**Comment by rvmourik** [comment]
@danielroe just to make sure, you want me to setup an reproduction with nuxt and amplify set-up? So you can check if the fix works? Or you want me to test this branch? I tried cloning this branch into Stackblitz but in ran into an exception.

**Comment by rvmourik** [comment]
@danielroe I just updated Nuxt to the latest version in my project, and when I run `yarn build` the same error pops up as mentioned in this issue. Would you like me to create a reproduction repo which you can test against?

**Comment by danielroe** [comment]
@rvmourik That would be great 🙏

**Comment by rvmourik** [comment]
@danielroe Here you go:

https://stackblitz.com/github/vbwiajbmk

Some context:

Server Side Rendering is disabled, when enabled it crashes instantly on an issue with amplify. As you can see in the `nuxt.config.ts` a define global is present. In dev it works, if you use `yarn build` it will crash.

When you remove the define from `nuxt.config.ts` you will see the errors we encounter with amplify libs.

Thanks in advance.

**Comment by rvmourik** [comment]
Posted a work-around here: https://github.com/nuxt/framework/discussions/2308#discussioncomment-2766426
