### ISSUE TITLE
useCookie example is misleading

### ISSUE THREAD

**Issue by cram0** [nuxt/framework#4925]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.1`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/cram0/nuxt

clone this repo ^
```bash
npm install
npm run dev
```

browse to `localhost:3000`

On Chrome : 

- Press F12
- Go to the Application tab
- In "Storage", click on "Cookies" then "Localhost:3000"

There should be a cookie with name "foo" and value "bar", but that's not the case because of the bug explained below.

### Describe the bug

I want my client to get access to a specific cookie based on an example function given in the documentation here :
https://v3.nuxtjs.org/guide/features/data-fetching#example-pass-on-cookies-from-server-side-api-calls-on-ssr-response

The only modification is that I added an object which sets the method type to `GET` and `useRequestHeaders()` which is needed in my case (even if you remove it, it doesn't change much).

But I get an error 500 : nuxt instance unavailable (i.e. Logs)

### Logs

```shell
[Vue warn]: Unhandled error during execution of setup function 
  at <App>
[nuxt] [request error] nuxt instance unavailable
  at Module.useNuxtApp (./.nuxt/dist/server/server.mjs:396:13)  
  at Module.useRequestEvent (./.nuxt/dist/server/server.mjs:1234:58)  
  at readRawCookies (./.nuxt/dist/server/server.mjs:1122:62)  
  at Module.useCookie (./.nuxt/dist/server/server.mjs:1101:19)  
  at Module.fetchWithCookie (./.nuxt/dist/server/server.mjs:3428:26)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async setup (./.nuxt/dist/server/server.mjs:3374:12)
```

**Comment by cram0** [comment]
Please ignore the following line 
- `The bug is that the browser should have a cookie named foo with value bar`

**Comment by danielroe** [comment]
In this case the docs are misleading. In your case you could amend to:

```js
export const fetchWithCookie = async (url, options) => {
	const foo = useCookie("foo")
	const response = await $fetch.raw(url, options);
	if (process.server) {
		const cookies = Object.fromEntries(
			response.headers
				.get("set-cookie")
				?.split(",")
				.map((a) => a.split("="))
		);
		if (cookies["foo"]) {
			foo.value = cookies["foo"];
		}
	}
	return response._data;
};
```

Composables like `useCookie` should not really be called in an async function directly, though we do make it possible for this for better DX if it is directly in `<script setup>`, a plugin or middleware. The better code would be to call `useCookie` at the beginning, and then return a fetch function that could be _used_ as a result of the composable.

**Comment by cram0** [comment]
This is exactly how I fixed my problem and yes that part of the documentation is a bit misleading at first, thanks for the help.

**Comment by cram0** [comment]
This is exactly how I fixed my problem and yes that part of the documentation is misleading.

It would be nice to have a proper example if anyone else wants to do the same.

**Comment by StanleyMasinde** [comment]
> In this case the docs are misleading. In your case you could amend to:
> 
> ```js
> export const fetchWithCookie = async (url, options) => {
> 	const foo = useCookie("foo")
> 	const response = await $fetch.raw(url, options);
> 	if (process.server) {
> 		const cookies = Object.fromEntries(
> 			response.headers
> 				.get("set-cookie")
> 				?.split(",")
> 				.map((a) => a.split("="))
> 		);
> 		if (cookies["foo"]) {
> 			foo.value = cookies["foo"];
> 		}
> 	}
> 	return response._data;
> };
> ```
> 
> Composables like `useCookie` should not really be called in an async function directly, though we do make it possible for this for better DX if it is directly in `<script setup>`, a plugin or middleware. The better code would be to call `useCookie` at the beginning, and then return a fetch function that could be _used_ as a result of the composable.

[Slightly Off-topic] I did not know you could do this with `$fetch` it is no where in the docs. I had to go back to using the good old Axios which works fine. Does anyone know why $fetch was preferred over Axios?

**Comment by antoineanorra** [comment]
@danielroe This solution is not practical because we have to define the cookie to retrieve in advance, but in some situations we have to wait for the return of the $fetch to parse the set-cookie and get the keys and their values.
It would be cool to propose an example with a plugin

**Comment by k0mar12** [comment]
@antoineanorra 

I'm not sure in 100% that my solution works fine, but as temporary, maybe good.

```
import { appendHeader } from 'h3'
import { parse, splitCookiesString as split } from 'set-cookie-parser'
import { serialize } from 'cookie'

export const useSsrFetch = () => {
    const nuxtApp = useNuxtApp()

    const withCookie = async (path) => {
        const { headers, _data } = await $fetch.raw(path)

        const cookies = (parse(split(headers.get('set-cookie')))).map(cookie => serialize(cookie.name, cookie.value, cookie))

        appendHeader(useRequestEvent(nuxtApp), 'Set-Cookie', cookies)

        return _data
    }

    return {
        withCookie
    }
}
```

**Comment by sharkfin009** [comment]
going to go back to document.cookie for now, and see if that works better
