### ISSUE TITLE
navigateTo doesn't respect baseUrl.

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#4932]
I have some questions about baseUrl.
If i set up baseUrl in my config or .env, should navigateTo works relative to it?

```
export default defineNuxtConfig({
    app: {
        baseURL: process.env.NUXT_APP_BASE_URL || '/',
    },
});
```

```
export default defineNuxtRouteMiddleware(async (to, from) => {
    const { state, parseRoutePath, fetchData } = useList();
    const { start, finish, fail } = useProgress();
    const isServer = process.server;

    try {
        if (state.value.isPrefetch) {
            state.value.isPrefetch = false;
            return;
        }

        const { path, fullPath } = to;
        const { path: pathFrom } = from;

        const isEnter = isServer || path !== pathFrom;
        const body = parseRoutePath(fullPath);

        start();
        await fetchData(body, isEnter, isServer);
        finish();
    } catch (error) {
        fail();
        if (isServer) return navigateTo('/');
        else return abortNavigation();
    }
});
```

As u can see, when fetch fail on server, i call navigateTo('/'), and that navigate me to root, not to baseUrl.
And i think it makes some inconsistent behavior, because for example NuxtLink resolves urls relative to my baseUrl, but navigateTo doesn't. In terms of application, there are no routes besides baseUrl.

It forces me make workaround, like this

```
const config = useRuntimeConfig();
return navigateTo(config.app.baseURL);
```

But i think it should resolve path internally, respectful and relative to baseUrl
What u think about that guys?
@danielroe @pi0

_Originally posted by @Harkonnen13 in https://github.com/nuxt/framework/discussions/4930_

**Comment by Harkonnen13** [comment]
@danielroe Ty vm for fast reply Daniel! But i have another question about baseUrl. As i remembered, vue-router have option to set baseUrl. Does nuxt3 set baseUrl to vue-router? i mean when i use useRouter hook, should i construct url with runtime config when i use router.replace/push manually?

**Comment by Harkonnen13** [comment]
that's some example of code that i use in app.vue

```
router.beforeEach((to, from, next) => {
    if (authState.inProcess) return false;
    if (to.path.includes('/auth') && !authState.bypassAuth && authState.isLogin) return next('/');
    if (!to.path.includes('/auth') && !authState.bypassAuth && !authState.isLogin) return next('/auth/login');
    return next();
});
```

**Comment by danielroe** [comment]
No, you shouldn't need to add the baseURL yourself.
