### ISSUE TITLE
Nux3 3.0.0-rc.2 met  Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

### ISSUE THREAD

**Issue by wohui** [nuxt/framework#4936]
### Environment

my package json

{
  "private": true,
  "scripts": {
    "dev": "nuxt dev",
    "build": "nuxt build",
    "start": "node .output/server/index.mjs",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "lint": "eslint --ext \".ts,.js,.vue\" --ignore-path .gitignore .",
    "lintfix": "eslint --fix --ext \".ts,.js,.vue\" --ignore-path .gitignore ."
  },
  "type": "module",
  "dependencies": {
    "less": "^4.1.2",
    "primeicons": "^5.0.0",
    "primevue": "^3.12.6",
    "sass": "^1.51.0",
    "vue": "^3.2.33"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config-typescript": "^10.0.0",
    "@nuxtjs/eslint-module": "^3.1.0",
    "eslint": "^8.15.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-nuxt": "^3.2.0",
    "eslint-plugin-prettier": "^4.0.0",
    "nuxt": "^3.0.0-rc.2",
    "prettier": "^2.6.2",
     "mitt": "^3.0.0",
    "music-score-transition": "^0.0.5",
    "tone": "^14.7.77",
    "typescript": "^4.6.4"
  }
}

### Reproduction

my nuxt-config.js
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  build: {
    transpile: ['primevue','tone'],
  },
  buildModules: ['@nuxtjs/eslint-module']
})

i used at page.vue:
import * as Tone from 'tone'

### Describe the bug

The error happend while use nuxt3+tone
code import * as Tone from 'tone' it works fine on vue3 vite
only occured with nuxt3

### Logs

```shell
✔ Vite server built in 5190ms                                                                                                                                     23:59:52
✔ Vite server built in 3026ms                                                                                                                                     00:00:05
✔ Vite server built in 2279ms                                                                                                                                     00:00:08
(node:10045) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
✔ Vite server built in 3525ms
```

**Comment by wohui** [comment]
@pi0  can you help me to see the problem ,thank you

**Comment by wohui** [comment]
like this issues https://github.com/nuxt/framework/issues/1911

**Comment by florian-lefebvre** [comment]
@bittermeatball with ESM you can't use `require`. I guess what you can do instead is:
```ts
import { defineNuxtConfig } from "nuxt";
import postcssOptions from "./postcss.config.js";

export default defineNuxtConfig({
  build: {
    postcss: {
      postcssOptions
    }
  }
});
```

**Comment by pi0** [comment]
Starting with `nitropack@0.4.4` and `unenv@0.5.2` we are using a cross-version compatible of `node-fetch` ([unjs/node-fetch-native](https://github.com/unjs/node-fetch-native)) that should resolve this issue when multiple versions of `node-fetch` exist in a project (v2 and v3 by different dependencies).

Please use `npx nuxi upgrade --force` to receive the fix.

If still having problems, please share your environment and also double check installed version  of nitro from `node_moudles/nitropack/package.json`.

For the context, there is still another underlying issue that caused v2 and v3 of node-fetch being merged and therefore this error (https://github.com/unjs/nitro/issues/161) we are tracking it but should not be relevant anymore at least regarding `node-fetch`.

Cheers!

**Comment by wohui** [comment]
> Starting with `nitropack@0.4.4` and `unenv@0.5.2` we are using a cross-version compatible of `node-fetch` ([unjs/node-fetch-native](https://github.com/unjs/node-fetch-native)) that should resolve this issue when multiple versions of `node-fetch` exist in a project (v2 and v3 by different dependencies).
> 
> Please use `npx nuxi upgrade --force` to receive the fix.
> 
> If still having problems, please share your environment and also double check installed version of nitro from `node_moudles/nitropack/package.json`.
> 
> For the context, there is still another underlying issue that caused v2 and v3 of node-fetch being merged and therefore this error ([unjs/nitro#161](https://github.com/unjs/nitro/issues/161)) we are tracking it but should not be relevant anymore at least regarding `node-fetch`.
> 
> Cheers!

Still can not resolve by use `npx nuxi upgrade --force` the version of nuxt is nux3-rc3
the node_moudles/nitropack/package.json below
`{
  "name": "nitropack",
  "version": "0.4.4",
  "description": "Build and Deploy Universal JavaScript Servers",
  "license": "MIT",
  "type": "module",
  "exports": {
    ".": "./dist/index.mjs",
    "./cli": "./dist/cli.mjs",
    "./runtime/*": "./dist/runtime/*.mjs",
    "./dist/runtime/*": "./dist/runtime/*.mjs"
  },
  "main": "./dist/index.mjs",
  "types": "./dist/index.d.ts",
  "bin": {
    "nitro": "./dist/cli.mjs",
    "nitropack": "./dist/cli.mjs"
  },
  "files": [
    "dist"
  ],
  "resolutions": {
    "nitropack": "link:."
  },
  "dependencies": {
    "@cloudflare/kv-asset-handler": "^0.2.0",
    "@netlify/functions": "^1.0.0",
    "@rollup/plugin-alias": "^3.1.9",
    "@rollup/plugin-commonjs": "^22.0.0",
    "@rollup/plugin-inject": "^4.0.4",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^13.3.0",
    "@rollup/plugin-replace": "^4.0.0",
    "@rollup/plugin-wasm": "^5.2.0",
    "@rollup/pluginutils": "^4.2.1",
    "@types/jsdom": "^16.2.14",
    "@vercel/nft": "^0.18.2",
    "archiver": "^5.3.1",
    "c12": "^0.2.7",
    "chalk": "^5.0.1",
    "chokidar": "^3.5.3",
    "consola": "^2.15.3",
    "cookie-es": "^0.5.0",
    "defu": "^6.0.0",
    "destr": "^1.1.1",
    "dot-prop": "^7.2.0",
    "esbuild": "^0.14.38",
    "etag": "^1.8.1",
    "fs-extra": "^10.1.0",
    "globby": "^13.1.1",
    "gzip-size": "^7.0.0",
    "h3": "^0.7.8",
    "hookable": "^5.1.1",
    "http-proxy": "^1.18.1",
    "is-primitive": "^3.0.1",
    "jiti": "^1.13.0",
    "klona": "^2.0.5",
    "listhen": "^0.2.11",
    "mime": "^3.0.0",
    "mlly": "^0.5.2",
    "mri": "^1.2.0",
    "node-fetch-native": "^0.1.2",
    "ohash": "^0.1.0",
    "ohmyfetch": "^0.4.16",
    "pathe": "^0.3.0",
    "perfect-debounce": "^0.1.3",
    "pkg-types": "^0.3.2",
    "pretty-bytes": "^6.0.0",
    "radix3": "^0.1.2",
    "rollup": "^2.72.1",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-visualizer": "^5.6.0",
    "scule": "^0.2.1",
    "semver": "^7.3.7",
    "serve-placeholder": "^2.0.1",
    "serve-static": "^1.15.0",
    "source-map-support": "^0.5.21",
    "std-env": "^3.1.1",
    "table": "^6.8.0",
    "ufo": "^0.8.4",
    "unenv": "^0.5.2",
    "unimport": "^0.2.1",
    "unstorage": "^0.4.1"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config-typescript": "^10.0.0",
    "@types/aws-lambda": "^8.10.97",
    "@types/etag": "^1.8.1",
    "@types/fs-extra": "^9.0.13",
    "@types/http-proxy": "^1.17.9",
    "@types/node-fetch": "^2.6.1",
    "@types/object-hash": "^2.2.1",
    "@types/semver": "^7.3.9",
    "@types/serve-static": "^1.13.10",
    "c8": "^7.11.2",
    "eslint": "^8.15.0",
    "execa": "^6.1.0",
    "miniflare": "^2.4.0",
    "standard-version": "^9.3.2",
    "typescript": "^4.6.4",
    "unbuild": "^0.7.4",
    "vitepress": "^0.22.4",
    "vitest": "^0.12.4"
  },
  "packageManager": "pnpm@7.0.1",
  "engines": {
    "node": "^14.16.0 || ^16.11.0 || ^17.0.0 || ^18.0.0"
  },
  "scripts": {
    "build": "unbuild",
    "dev": "pnpm nitro dev playground",
    "dev:build": "pnpm nitro build playground",
    "dev:start": "node playground/.output/server/index.mjs",
    "docs:build": "vitepress build docs",
    "docs:dev": "vitepress dev docs",
    "docs:serve": "vitepress serve docs",
    "lint": "eslint --ext .ts,.mjs,.cjs .",
    "nitro": "jiti ./src/cli.ts",
    "release": "pnpm test && pnpm build && standard-version && pnpm publish && git push --follow-tags",
    "stub": "unbuild --stub",
    "test": "pnpm lint && vitest run --silent"
  }
}`
my nuxt config
`import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  build: {
    transpile: ['primevue','tone'],
  },
  buildModules: ['@nuxtjs/eslint-module'],
  css: [
    'primevue/resources/themes/mdc-dark-indigo/theme.css', // theme
    'primevue/resources/primevue.min.css', // core css
    'primeicons/primeicons.css', // icons
  ],
})
`
my package.json
`{
  "private": true,
  "scripts": {
    "dev": "nuxt dev",
    "build": "nuxt build",
    "start": "node .output/server/index.mjs",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "lint": "eslint --ext \".ts,.js,.vue\" --ignore-path .gitignore .",
    "lintfix": "eslint --fix --ext \".ts,.js,.vue\" --ignore-path .gitignore ."
  },
  "dependencies": {
    "less": "^4.1.2",
    "primeicons": "^5.0.0",
    "primevue": "^3.12.6",
    "sass": "^1.51.0",
    "tone": "^14.8.39",
    "vue": "^3.2.33"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config-typescript": "^10.0.0",
    "@nuxtjs/eslint-module": "^3.1.0",
    "eslint": "^8.15.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-nuxt": "^3.2.0",
    "eslint-plugin-prettier": "^4.0.0",
    "mitt": "^3.0.0",
    "music-score-transition": "^0.0.5",
    "nuxt": "^3.0.0-rc.2",
    "prettier": "^2.6.2",
    "typescript": "^4.6.4"
  }
}
`
only met the erroy  when i used  "import * as Tone  from 'tone" in the page/index.vue
`<template>
  <div>
  </div>
</template>
<script setup>
**import * as Tone  from 'tone'**
</script>`

**Comment by wohui** [comment]
@pi0  the code: https://stackblitz.com/edit/github-cmudtt?file=app.vue
thank you

**Comment by pi0** [comment]
Dear @wohui I've answered your question at https://github.com/Tonejs/Tone.js/issues/1081#issuecomment-1124751788. It is not related to `node-fetch` but another dependency that is not ESM compatible and needs transpilation.

**Comment by wohui** [comment]
> Dear @wohui I've answered your question at [Tonejs/Tone.js#1081 (comment)](https://github.com/Tonejs/Tone.js/issues/1081#issuecomment-1124751788). It is not related to `node-fetch` but another dependency that is not ESM compatible and needs transpilation.

I saw it, thank you very much for your answer，so cool !!!
