### ISSUE TITLE
Global components per-directory setting not working properly

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/framework#4947]
### Environment

https://stackblitz.com/edit/nuxt-starter-qrjlf7?file=nuxt.config.ts,components%2Fcms%2FTest.vue,app.vue

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qrjlf7?file=nuxt.config.ts,components%2Fcms%2FTest.vue,app.vue

### Describe the bug

Am I missing something or this configuration should work with `component :is`?

Check `nuxt.config.ts` and `app.vue`

**Comment by 516310460** [comment]
Use error.
Link: https://v3.nuxtjs.org/guide/directory-structure/components, https://stackblitz.com/edit/nuxt-starter-qrjlf7?file=nuxt.config.ts,components%2Fcms%2FTest.vue,app.vue
Correct as follows:
<template>
  <div>
    <cms-test /><br />
    <component :is="cmsTest" />
  </div>
</template>
<script setup>
const cmsTest = resolveComponent('cms-test');
</script>

**Comment by Rigo-m** [comment]
> Use error. Link: https://v3.nuxtjs.org/guide/directory-structure/components, https://stackblitz.com/edit/nuxt-starter-qrjlf7?file=nuxt.config.ts,components%2Fcms%2FTest.vue,app.vue Correct as follows:
> 
> " "
> 
> <script setup> const cmsTest = resolveComponent('cms-test'); </script>

Documentation also states:
`Alternatively, though not recommended, you can register all your components globally, which will create async chunks for all your components and make them available throughout your application.`
And:
`The global option can also be set per component directory.`

**Comment by 516310460** [comment]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/17541676/168023783-831894c0-64db-4718-b268-75639a35f5aa.png">

**Comment by danielroe** [comment]
The issue here is that Nuxt won't re-add components that have already been added. Changing the config to this should solve the issue:

```diff
  import { defineNuxtConfig } from 'nuxt';
  // https://v3.nuxtjs.org/api/configuration/nuxt.config
  export default defineNuxtConfig({
    components: {
      dirs: [
-       '~/components',
        {
          global: true,
          path: '~/components/cms',
          prefix: 'Cms',
        },
+       '~/components',
      ],
    },
  })
```

**Comment by Rigo-m** [comment]
@danielroe makes complete sense. My mind worked like I was going to re-define props on a spreaded object.
