### ISSUE TITLE
getting error when starting my nuxt project

### ISSUE THREAD

**Issue by Emmybritt** [nuxt/framework#4954]
### Environment

getting an error after writing npm run dev -- -o for nuxt 3 application

### Reproduction

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\user\Desktop\workspace\shoppingGo\new-app\.nuxt\app.mjs' imported from C:\Users\user\Desktop\workspace\shoppingGo\new-app\.nuxt\dev\index.mjs
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:418:11)
    at moduleResolve (node:internal/modules/esm/resolve:983:10)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap. (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36)

### Describe the bug

Am getting an error when trying to work on my apllication after running my application to dev server

**Comment by dikesh** [comment]
You need to provide code instead of error message for reproduction.

**Comment by damieng** [comment]
I get the exact same error with every nuxt3 project I've tried.

For example I just checked out https://github.com/Atinux/content-wind and did `yarn install` which completed but then `yarn dev` results in:

```
$ nuxi dev
Nuxt CLI v3.0.0-rc.3                                                                                                      19:29:51
                                                                                                                          19:29:51
  > Local:    http://localhost:3001/
  > Network:  http://10.0.4.57:3001/

√ Using ~/components/content for components in Markdown                                                     @nuxt/content 19:29:53
i Using default Tailwind CSS file from runtime/tailwind.css                                              nuxt:tailwindcss 19:29:53
i Merging Tailwind config from ~/tailwind.config.js                                                      nuxt:tailwindcss 19:29:53
i Tailwind Viewer: http://localhost:3001/_tailwind/                                                      nuxt:tailwindcss 19:29:54
i Vite server warmed up in 566ms                                                                                          19:29:57
i Vite client warmed up in 2145ms                                                                                         19:29:57
√ Vite server built in 1741ms                                                                                             19:29:58
√ Nitro built in 85 ms                                                                                              nitro 19:29:58

 ERROR  [worker reload] [worker init] Cannot find module 'e:\src\content-wind\.nuxt\app.mjs' imported from e:\src\content-wind\.nuxt\dev\index.mjs

  at new NodeError (node:internal/errors:371:5)
  at finalizeResolution (node:internal/modules/esm/resolve:416:11)
  at moduleResolve (node:internal/modules/esm/resolve:932:10)
  at defaultResolve (node:internal/modules/esm/resolve:1044:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
  ```

**Comment by kailight** [comment]
I am getting this error `cannot find module .nuxt/app.mjs` when trying to run from custom console (ConEmu with Powershell), even with admin rights.

But I am able to run nuxt3 app from Idea terminal with Powershell.

So I guess these are some Windows permission rights in some of later Win10 flavors.

**Comment by cybercoder-naj** [comment]
My project on Windows was working perfectly fine until yesterday. Today I am getting this issue: `Cannot find module '.\.nuxt\app.mjs'` I don't know how to solve this.

**Comment by danielroe** [comment]
Would you run `npx nuxi upgrade` and let me know if the problem persists? If so, would you share a reproduction project in a GitHub repo?

**Comment by cybercoder-naj** [comment]
I have run that command and it worked! The error no longer persists. Thank you!
