### ISSUE TITLE
imports.d.ts contain the absolute path to the source files

### ISSUE THREAD

**Issue by misaon** [nuxt/framework#4957]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@3.2.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `normalizedModule()`, `normalizedModule()`
- Build Modules:    `-`
------------------------------

### Reproduction

```ts
const runtimeDirectory = fileURLToPath(new URL('runtime', import.meta.url))
nuxt.hook('autoImports:dirs', (directories) => {
  directories.push(resolve(runtimeDirectory, 'composables'))
})
```

### Describe the bug

Auto import correctly resolves source file paths, but there is a problem when I use the IDE and Nuxt is running in a Docker container. The IDE then doesn't map correctly because in `imports.d.ts` the path is `/app/packages/nuxt/src/runtime/composables/api/index` (inside container), and in the IDE the project is in `/home/misaon/PhpStormProjects/xxx/src/client/packages/nuxt/src/runtime/composables/api/index`. IDE does not know this file and does not suggest it.

### Additional context

Use relative paths?

**Comment by misaon** [comment]
Workaround for this moment:
```ts
nuxt.hook('build:done', () => {
  const projectDirectory = '/app/'
  const importsDtsFilePath = resolve(nuxt.options.buildDir, 'imports.d.ts')

  readFile(importsDtsFilePath, 'utf8', (error, data) => {
    const modifiedContent = data.replaceAll(projectDirectory, '')
    writeFile(importsDtsFilePath, modifiedContent, 'utf8', (error) => {
      if (error) {
        console.log(error)
      }
    })
  })
})
```

**Comment by danielroe** [comment]
What do you think @antfu? Would relative paths be equally good in https://github.com/unjs/unimport?
