### ISSUE TITLE
ipv4 / ipv6 - Problem when using $fetch() while testing with vitest

### ISSUE THREAD

**Issue by Beiri22** [nuxt/framework#4959]
### Environment

Nuxt 3 rc3
Vitest rc3
tested in windows and linux

### Reproduction

Create an api endpoint that returns some text.
Create a simple test
```
import { describe, test, expect, beforeAll, beforeEach } from 'vitest'
import { setup, $fetch, fetch, useTestContext } from '@nuxt/test-utils'
import { fileURLToPath } from 'node:url'

describe('xxx', async () => {

    await setup({server:true})

    test('my test', async () => {
        const res = await $fetch('/api/demo')
        expect(res).toBe("hallo")
    })
})
```

Error message: ECONNRESET ::1 cannot fetch

### Describe the bug

The problem is the following:
The url in testcontext is initialized with "localhost" + random port
The server is started - only in ipv4 mode, which seems the default
When using $fetch() and fetch()  the hostname localhot is resolved to ipv6 ::1 - that is not served.

My little hack is:
```
    beforeEach(()=>{
        const ctx = useTestContext();
        ctx.url = ctx.url?.replace("localhost", "127.0.0.1")
     })
```

But i think there must be a better way.

**Comment by itsmnthn** [comment]
I've the same issue resolved to ipv6 ::1  with different error message.

I have tried [Beiri22](https://github.com/Beiri22)'s Little hack and it works like a charm thanks to him. But yes Bug Fix is needed here.
