### ISSUE TITLE
`useFetch` does not refresh when a params object is used

### ISSUE THREAD

**Issue by vasisouv** [nuxt/framework#4970]
### Environment

Linux

### Reproduction

Go to: https://stackblitz.com/edit/github-mt2nv8?file=app.vue

Try to increase the page by pressing the respective button. The same request is performed with each button press.

As described in the sandbox, using the `_start` param as part of the url works properly.

### Describe the bug

The `refresh` function of the `useFetch` composable does not properly refresh requests that depend on params object instead of params in the url itself.

**Comment by danielroe** [comment]
For this, we provide the `watch` option. Try this:

```js
const { data: todos, refresh } = await useFetch(
  () => `https://jsonplaceholder.typicode.com/todos?_limit=3&_start=${page.value}`,
  { watch: [page] }
);
```

**Comment by vasisouv** [comment]
Hey daniel thanks for responding,

I did not find the `watch` option as part of the [UseFetchOptions](https://v3.nuxtjs.org/api/composables/use-fetch#type) in the docs but it does not seem to fix the issue here.

Also, the code you provided above does not utilize a params object which is my issue initially

```
const { data: todos, refresh } = await useFetch(
  () => `https://jsonplaceholder.typicode.com/todos?_limit=3`,
  { params: { _start: page.value}, watch: [page] }
);
```
The above does not seem to be working. I created a separate stackblitz here: https://stackblitz.com/edit/github-de9m9d?file=app.vue

Am I doing something wrong?

**Comment by danielroe** [comment]
Yes. You should instead use it in the URL directly, as the params are 'frozen' in time when the setup function runs.

**Comment by vasisouv** [comment]
Alright I see, thanks! So for multiple params I will have to manually stringify into the url instead.

**Comment by Maxim-Filimonov** [comment]
I think, I might have encountered the same issue. I don't really follow how to fix it in my case. 
I have a super simple [app](https://github.com/Maxim-Filimonov/crypto_binance_exchange_calculator) with one page and when I try to use the refresh button and it doesn't work. I see the HTTP request going through, but no code runs after the line where the first http request happens - which is what I'm trying to refresh.

**Comment by manniL** [comment]
@Maxim-Filimonov you might want to watch the returned `data` through a Vue `watch`/`watchEffect` so you can react whenever the data refreshes ☺️

**Comment by Maxim-Filimonov** [comment]
@manniL that did help ! Thanks 🙏
Got some weird warning after doing watch:
```
Vue warn]: Hydration children mismatch in <ul>: server rendered element contains more child nodes than client vdom. 
  at <App key=1 > 
  at <NuxtRoot>
```
But it does refresh now. Will go RTFM Vue reactivity, after React it's a quite surprising at times. Thanks!

**Comment by konradsienkowski** [comment]
@danielroe how about values from Pinia state? Is there a way to use them in a request path along with the refresh method?

**Comment by shtse8** [comment]
> Yes. You should instead use it in the URL directly as I have done above, as the params are 'frozen' in time when the setup function runs. (This is not unique to Nuxt, but is a caveat of Vue reactivity.)

when using it in url, the response type cannot be solved in typescript. type will become `unknown`.
I suggest we can have something like
```ts
const next = ref('')
const { data } = await useFetch('/api/list', {
    params: {
      next: () => next.value,
    },
  })
```
