### ISSUE TITLE
Issue with v-calendar and nuxt 3

### ISSUE THREAD

**Issue by valiknet18** [nuxt/framework#4979]
### Environment

- Operating System: `Darwin`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `typescript`, `buildModules`, `modules`, `css`, `build`, `postcss`, `components`, `vite`, `env`, `publicRuntimeConfig`, `tailwindcss`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.8`
- Build Modules:    `@pinia/nuxt@0.1.9`, `unplugin-icons/nuxt`, `@nuxtjs/tailwindcss@5.0.4`

### Reproduction

I'm install a library, and imported into my component 

```
<template>
        <client-only>
           <Calendar />
         </client-only>
</template
         
<script setup lang="ts">
import { Calendar } from 'v-calendar';
</script>
```

### Describe the bug

Instead to see a working calendar, i see an error 

_**
ReferenceError: document is not defined
    at m (/node_modules/v-calendar/lib/v-calendar.umd.min.js:1:137448)
    at v (/node_modules/v-calendar/lib/v-calendar.umd.min.js:1:137279)
    at h (/node_modules/v-calendar/lib/v-calendar.umd.min.js:1:136755)
    at Object.e052 (/node_modules/v-calendar/lib/v-calendar.umd.min.js:1:201587)
    at n (/node_modules/v-calendar/lib/v-calendar.umd.min.js:1:413)
    at Object.bdb3 (/node_modules/v-calendar/lib/v-calendar.umd.min.js:1:180951)
    at n (/node_modules/v-calendar/lib/v-calendar.umd.min.js:1:413)
    at Module.2af9 (/node_modules/v-calendar/lib/v-calendar.umd.min.js:1:70255)
    at n (/v-calendar/lib/v-calendar.umd.min.js:1:413)
    at Object.<anonymous> (/node_modules/v-calendar/lib/v-calendar.umd.min.js:1:126315)
**_

However i'm wrapped a component into ClientOnly component. Looks like this component not working as expected.
If u need any additional context information, feel free to ask me.

**Comment by ilijanovic** [comment]
You can do a workaround like this:

```
<template>
           <component :is="comp" />
</template
         
<script setup lang="ts">
let comp = ref()
if(process.client){
   let { Calendar } = await import("v-calendar");
   comp.value = Calendar
}
</script>
```

**Comment by Kapcash** [comment]
The problem is that [`v-calendar`](https://github.com/nathanreyes/v-calendar) doesn't support SSR.
This is not related with Nuxt itself.

Follow this issue on the library github for SSR support and workarounds: https://github.com/nathanreyes/v-calendar/issues/559

**Comment by valiknet18** [comment]
> It does not support SSR. However, you can load it dynamically with `import()`
> 
> You can do a workaround like this:
> 
> ```
> <template>
>    <component :is="comp" />
> </template
>          
> <script setup lang="ts">
>    let comp = ref()
>    onMounted(async () => {
>       let { Calendar } = await import("v-calendar");
>       comp.value = Calendar
>    })
> </script>
> ```

Thank you for idea. I will try.
