### ISSUE TITLE
Nginx + PM2 ( Windows )

### ISSUE THREAD

**Issue by complianceux001** [nuxt/framework#4986]
This error is occurring when using nginx with pm2 on windows, I did the build but when looking at the log in pm2 I get this error.

![4](https://user-images.githubusercontent.com/46327877/168449491-45177fa7-82de-4b33-81a5-5e914d8f2658.png)

**Comment by vencho-mdp** [comment]
same error here

**Comment by danielroe** [comment]
Would you provide a reproduction please? 🙏
