### ISSUE TITLE
[SSG] No `200.html` is being rendered

### ISSUE THREAD

**Issue by manniL** [nuxt/framework#5003]
### Environment

RootDir: /sandbox 
Nuxt project info:                                                           

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Open the [sandbox](https://codesandbox.io/s/nuxt3-5003-tdw495) (and possibly clone locally)
2. Run `yarn generate`
3. See that a fallback file is missing

### Describe the bug

When using `target: 'static'`, I expected that a `200.html` (or differently named) fallback file is being rendered. Unfortunately, no such file is being generated at the moment.

Even with `generate.fallback` set to `true` or `200.html`, no file is present after the generation process.

### Additional context

_Originally posted by @edwh in https://github.com/nuxt/framework/discussions/4967_

**Comment by some-user123** [comment]
A 200.html and 404.html is generated if `ssr: false` is set in `nuxt.config.ts`. That might be a workaround. Not sure what the side effects are... The [documentation](https://v3.nuxtjs.org/guide/deploy/static-hosting#static-hosting) is quite sparse.

**Comment by oezkancodes** [comment]
@some-user123

For projects with SSG, it is very important to have a `200.html` or `400.html` fallback file, for example for hosting on Netlify. Otherwise, you will have no error page. If you add your error page in `error.vue`, this won't help either, as there will be no `404.html` file generated. It is only for client-side errors.

I currently use a workaround, injecting the route `/404.html` to the routes to generate.
```ts
// nuxt.config.ts

nitro: {
  prerender: {
    routes: ['/404.html']
  }
},
```

**Comment by manniL** [comment]
> I currently use a workaround, injecting the route `/404.html` to the routes to generate.

But this will render the `404.html` with the error layout "as is" and won't allow SPA-like fallback. Which means solving "only" half of the issue.

**Comment by some-user123** [comment]
@oezkancodes That's understood. You also need it for "wildcard" pages like [slug].vue.
Have you tried setting `ssr` to false? I've got a 200.html and 404.html.

**Comment by oezkancodes** [comment]
@manniL yes, this is very true! That's the only reason I'm still going with Nuxt 2. SPA fallback doesn't work in Nuxt 3 with SSG.

**Comment by manniL** [comment]
> @oezkancodes That's understood. You also need it for "wildcard" pages like [slug].vue.
> Have you tried setting `ssr` to false? I've got a 200.html and 404.html.

That's correct but then you don't have SSR. And chances for mismatches between the "non-SSR" generated fallback files and the rest of the app seem to bad for actual production usage 🙈
