### ISSUE TITLE
 Cannot stringify arbitrary non-POJOs Promise warning

### ISSUE THREAD

**Issue by lucassimines** [nuxt/framework#5010]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.8.0`
- Builder:          `vite`
- User Config:      `alias`, `typescript`, `runtimeConfig`, `css`, `vite`, `nitro`, `modules`, `postcss`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.4`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/pensive-swanson-04nzr9?file=/app.vue

### Describe the bug

When trying to useFetch inside a composable, a warning message is displayed:

`Cannot stringify arbitrary non-POJOs Promise`

The data response works, but this warning keeps displaying.

### Logs

```shell
Cannot stringify arbitrary non-POJOs Promise
```

**Comment by n0ch4t** [comment]
same problem nuxt2

**Comment by danielroe** [comment]
`useState` doesn't take an async factory function. The error is caused by the fact that you can't stringify the return type of that function, which is a Promise.
