### ISSUE TITLE
Add Javascript At the end of the body

### ISSUE THREAD

**Issue by michelveloso** [nuxt/framework#5014]
### Environment

```
`// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
    app: {
        head: {
            script: [
                {
                    src: "https://code.jquery.com/jquery-3.5.1.min.js",
                    body: true
                },
            ],
        },
    },    `
```

### Reproduction

![image](https://user-images.githubusercontent.com/346317/168694524-596d86fe-f9d7-45d7-b5a1-8ecc09c6c9c8.png)

### Describe the bug

Is it possible to add external Javascript at the end of the body like NuxtJs 2?

https://stackoverflow.com/questions/50138074/how-to-append-js-files-in-nuxt-before-body-ends

![image](https://user-images.githubusercontent.com/346317/168694877-38f2e32a-24da-421b-a97c-bb9c86908c42.png)

Or is it possible to add them as a plugin?
https://deltener.com/blog/nuxt-third-party-code-is-poison/

**Comment by danielroe** [comment]
See https://github.com/vueuse/head/issues/53.

**Comment by sey** [comment]
Do you have any idea when the PR will be merged? or a workaround in the meantime to hardcode the script tag at the end of the body?

**Comment by danielroe** [comment]
This should now be supported in the latest vueuse/head. You can run `npx nuxi upgrade` to pull it in.
