### ISSUE TITLE
Nuxt 3 Vite server proxy does not work after build

### ISSUE THREAD

**Issue by sikeat7** [nuxt/framework#5015]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `components`, `buildModules`, `typescript`, `css`, `plugins`, `unocss`, `runtimeConfig`, `vueuse`, `vite`, `build`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.5.0`, `@pinia/nuxt@0.1.9`, `@unocss/nuxt@0.33.5`
------------------------------

### Reproduction

**nuxt.config.ts**
`vite: {
    server: {
      proxy: {
        "/proxy_path": {
          target: "https://domain.com",
          changeOrigin: true
        },
    }
}`
<img width="373" alt="Screen Shot 2022-05-17 at 8 55 54 AM" src="https://user-images.githubusercontent.com/12691222/168714451-2bf798b7-f9c7-4528-af33-5ca650cc4380.png">

### Describe the bug

After run build success I'm start command `node .output/server/index.mjs` to preview build but it's got an error (**page not found**). 
**_Note: Development work fine._**

<img width="1429" alt="Screen Shot 2022-05-17 at 8 59 37 AM" src="https://user-images.githubusercontent.com/12691222/168714026-93053839-f0fa-4d34-9642-dc7b2fa895ce.png">

**Comment by danielroe** [comment]
Setting a vite proxy only works in development; this is even true when not using Nuxt: https://vitejs.dev/config/#server-proxy.

Follow https://github.com/unjs/nitro/issues/113 for built-in proxy support in Nitro. Until then you can implement manually using Nitro server middleware.

**Comment by ElderlyBoy** [comment]
You can use `Nginx` or another proxy service to proxy your http requests in build env.

**Comment by tomimandalap** [comment]
You can use ```@nuxtjs-alt/proxy``` as a temporary solution.

**Comment by wiseadme** [comment]
Hi for everyone! it is not clear why the proxy does not work, I seem to be doing everything right
`
{  
vite: {
    server: {
      proxy: {
        '/v1': {
          target: 'http://localhost:5000',
          changeOrigin: true,
        }
      }
    }
  },
}
`

**Comment by manniL** [comment]
FYI: I'd suggest to use Nitro's [`devProxy`](https://nitro.unjs.io/config#devproxy) instead

**Comment by wiseadme** [comment]
> FYI: I'd suggest to use Nitro's [`devProxy`](https://nitro.unjs.io/config#devproxy) instead

thank you, but it didn't help either, I tried it before writing, only installing @nuxtjs-alt/proxy helped
