### ISSUE TITLE
[Kit] Support the method suffix in `addServerHandler`

### ISSUE THREAD

**Issue by Atinux** [nuxt/framework#5020]
It would be nice to support the suffix for `addServerHandler`:

```ts
addServerHandler({
  route: '/api/hello',
  handler: resolve('./api/hello.get.ts'),
})
```

Will be same as:

```ts
addServerHandler({
  route: '/api/hello',
  method: 'get',
  handler: resolve('./api/hello.get.ts'),
})
```

See example on https://stackblitz.com/edit/nuxt-starter-gfos9a?file=nuxt.config.ts,module%2Findex.ts,module%2Fapi%2Fhello.get.ts

We do support it for `addPlugin` 😊

**Comment by Rigo-m** [comment]
As a side note, since we are here, it's unclear/undocumented wether we can create parametric routes via kit (same as we can call a server api `/server/api/[some][param].get.ts`. Can we?

**Comment by huang-julien** [comment]
> As a side note, since we are here, it's unclear/undocumented wether we can create parametric routes via kit (same as we can call a server api `/server/api/[some][param].get.ts`. Can we?

shouldn't be the params defined in the route key of the NitroEventHandler object for this helper ?

```ts
 addServerHandler({
       handler: "./api/test.post.ts",
       route:"/test/:id"
 })
```
It should be available in event.context.params from the defineEventHandler callback

**Comment by richardeschloss** [comment]
Hey guys, can the handler also be a function by any chance?
