### ISSUE TITLE
[nuxt] [request error] Directory import '...\.output\server\node_modules\@apollo\client\core' is not supported resolving ES modul es imported from ...\.output\server\chunks\server.mjs Did you mean to import @apollo/client/core/index.js?

### ISSUE THREAD

**Issue by loremru** [nuxt/framework#5023]
### Environment

Nuxt CLI v3.0.0-rc.3                                                                                                                              14:35:02
RootDir: C:\Users\Ilya\Desktop\nuxt-app                                                                                                           14:35:06
Nuxt project info:                                                                                                                                14:35:06

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/loremru/bug-reproduction

https://stackblitz.com/edit/github-pskqpw?file=package.json,nuxt.config.ts,app.vue,package-lock.json,graphql%2Fquery.js

yarn build
yarn start

### Describe the bug

Apollo Client doesnt work in a BUILD with SSR: true. In DEV or SSR off its ok.

[nuxt] [request error] Directory import '...\.output\server\node_modules\@apollo\client\core' is not supported resolving ES modul es imported from ...\.output\server\chunks\server.mjs Did you mean to import @apollo/client/core/index.js?

![image](https://user-images.githubusercontent.com/66596500/168803217-841ed962-6b05-4453-a866-c17502b43017.png)

https://stackblitz.com/edit/github-pskqpw?file=package.json,nuxt.config.ts,app.vue,package-lock.json,graphql%2Fquery.js

yarn build
yarn start

**Comment by 516310460** [comment]
See: https://v3.nuxtjs.org/guide/directory-structure/plugins
plugins/***.client.js
or
plugins/***.server.js

**Comment by loremru** [comment]
> See: https://v3.nuxtjs.org/guide/directory-structure/plugins
> plugins/_**.client.js or plugins/**_.server.js
@516310460 and how can this help me if I need to have ApolloClient on server and on client?

**Comment by 516310460** [comment]
"@apollo/client": "^3.6.4",
It seems that this can only be used on the customer service side

**Comment by 516310460** [comment]
"@apollo/client": "^3.6.4",
This plug-in only supports clients

**Comment by loremru** [comment]
> Apollo should work fine on both, server and client side. But it likely must be transpiled.
> 
> Add `'@apollo/client'` and `'ts-invariant/process'` to your `transpile` array in the nuxt.config.js/.ts
> 
> example:
> 
> ```ts
> defineNuxtConfig({
>   build: {
>     transpile: ['@apollo/client', 'ts-invariant/process']
>   }
> })
> ```
@manniL 
Same error with transpile.

**Comment by manniL** [comment]
> Same error with transpile.

Feel free to check out [this module](https://github.com/newbeea/nuxt3-apollo-module/) which should work fine AFAIK and adds apollo as well. I saw that you e.g. need to use `ssrMode: true` when creating your apollo client on the server side (see [here](https://github.com/newbeea/nuxt3-apollo-module/blob/master/src/plugin.ts#L28)).

**Comment by manniL** [comment]
There is a manual workaround though:

After building, open `.output/server/chunks/server.mjs`, go to the line:

`import * as core from '@apollo/client/core/';`
and change it to
`import * as core from '@apollo/client/core/index.js';`
as the error message suggests. But even when using the exact `index.js` import in the source code, the build process strips out the `index.js` part. Not sure if it is an issue on the Nuxt or Apollo end though.

**Comment by VladTchk** [comment]
The same problem.

**Comment by loremru** [comment]
@manniL 
Any news here? After temporary fix i noticed that other packages also throws errors in build mode (only ssr). 
![image](https://user-images.githubusercontent.com/66596500/169797358-e6efe4df-7172-47c3-976e-54acfe4d64ab.png)

**Comment by newbeea** [comment]
> > Same error with transpile.
> 
> Feel free to check out [this module](https://github.com/newbeea/nuxt3-apollo-module/) which should work fine AFAIK and adds apollo as well. I saw that you e.g. need to use `ssrMode: true` when creating your apollo client on the server side (see [here](https://github.com/newbeea/nuxt3-apollo-module/blob/master/src/plugin.ts#L28)).
> 
> Seems that the StackBlitz reproduction works now ☺️

 [this module](https://github.com/newbeea/nuxt3-apollo-module/) <0.1.0 works fine with nuxt3 but not nuxt@rc
0.1.1 works for nuxt@rc now

**Comment by luvejo** [comment]
> Apollo should work fine on both, server and client side. But it likely must be transpiled.
> 
> Add `'@apollo/client'` and `'ts-invariant/process'` to your `transpile` array in the nuxt.config.js/.ts
> 
> example:
> 
> ```ts
> defineNuxtConfig({
>   build: {
>     transpile: ['@apollo/client', 'ts-invariant/process']
>   }
> })
> ```

@manniL  Could you possibly explain why it should be transpiled?
