### ISSUE TITLE
:key="$router.path" component not refresh..

### ISSUE THREAD

**Issue by andysay** [nuxt/framework#5029]
### Environment

Nuxt project info:                                                    23:20:15

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `buildModules`, `modules`, `build`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.4`
- Build Modules:    `@pinia/nuxt@0.1.9`
------------------------------

### Reproduction

https://codesandbox.io/s/nuxt3-project-test-with-vue3-forked-xmz0i9?file=/pages/index.vue

### Describe the bug

https://user-images.githubusercontent.com/5610952/168902994-368afc78-1df8-46cf-891a-b4accfab814b.mp4

open editor ok , back and reopen bad.

**Comment by manniL** [comment]
The provided CodeSandbox contains an error (as there is no `Editor` component but only an `editor` page).

**Comment by andysay** [comment]
> https://codesandbox.io/s/nuxt3-project-test-with-vue3-forked-xmz0i9?file=/pages/index.vue

in safari will be opened

**Comment by andysay** [comment]
> ~The provided CodeSandbox contains an error (as there is no `Editor` component but only an `editor` page).~
> 
> Nvm, the Editor component is provided via tinymce. Still, there is an `[nuxt] [request error] Maximum call stack size exceeded` error when accessing `/editor`

in safari will be opened

**Comment by manniL** [comment]
> in safari will be opened

I can't verify this. But in both, Firefox and Chrome, the infinite recursion error is stated in the CodeSandbox console for me 🙈. Unfortunately, I can't debug further than this.

**Comment by andysay** [comment]
> > in safari will be opened
> 
> I can't verify this. But in both, Firefox and Chrome, the infinite recursion error is stated in the CodeSandbox console for me 🙈. Unfortunately, I can't debug further than this.

u can try on u local machine , i see that error , but im record video for simple.

**Comment by danielroe** [comment]
The error is because you are only registering that component on client-side, not server. So it can't render it on server side. Wrap it in `<ClientOnly>` if you only want to register the component on client-side.

**Comment by andysay** [comment]
> The error is because you are only registering that component on client-side, not server. So it can't render it on server side. Wrap it in `<ClientOnly>` if you only want to register the component on client-side.

yes , but key $route.path not refresh component....

works only with example

<button @click="forceUpdate">recreate</button>

 <component :key="updateKey" />

```
  data() {
    return {
      updateKey: 0,

     }
}

methods() {

    forceUpdate() {
      this.updateKey += 1;
    }, 

}
```

**Comment by andysay** [comment]
> `:key` works fine to forcefully re-render components based on the route path.. See [this example](https://nuxt-starter-ttgvat--3000.local-corp.webcontainer.io). If you want to incorporate query params as well, use `route.fullPath` instead.

i'm recreate reproduction 

https://codesandbox.io/s/nuxt3-project-test-with-vue3-forked-xmz0i9?file=/pages/index.vue


https://user-images.githubusercontent.com/5610952/169042885-3f2b98fc-782c-432d-9c02-5365abba2500.mp4

can you make this example with route.path? thank you so  much.

**Comment by andysay** [comment]
@manniL 
@danielroe 
video example... why when i'm back component not loading again? how fix it.

https://user-images.githubusercontent.com/5610952/169045547-a0ba669a-11a6-40db-a3bf-05b8532e7733.mp4
