### ISSUE TITLE
Route middleware abortNavigation/navigateTo missing options

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/framework#5041]
### Environment

n/a

### Reproduction

n/a

### Describe the bug

We should be able to return the error code (e.g.: 404) in abortNavigation, and we should be able to choose the type of redirect in navigateTo (e.g.: 301, 302 etc).

**Comment by manniL** [comment]
`navigateTo` already accepts the status code for the redirect ☺️ 

See https://github.com/nuxt/framework/blob/main/packages/nuxt/src/app/composables/router.ts#L71

**Comment by Rigo-m** [comment]
> `navigateTo` already accepts the status code for the redirect ☺️
> 
> See https://github.com/nuxt/framework/blob/main/packages/nuxt/src/app/composables/router.ts#L71
> 
> For `abortNavigation` it is not available though and I agree, it would be nice to set the status code as `h3`'s [`createError`](https://github.com/unjs/h3/blob/cf2c1a7af7614d00990cc15f6e8468b500134a76/src/error.ts#L26) is accepting it as well.

Missing in docs then :D

**Comment by noriyuki106** [comment]
I think `navigateTo` ignores options (including statusCode), when called inside middleware. is it expected?
https://github.com/nuxt/framework/blob/main/packages/nuxt/src/app/composables/router.ts#L63-L65
