### ISSUE TITLE
how to avoid clearing terminal

### ISSUE THREAD

**Issue by autumnblazey** [nuxt/framework#5052]
I would like for nuxt to provide an option to not clear the screen on startup / possibly other events. It is especially annoying when I have previous terminal output which I would like to keep, but nuxt just bulldozes over it. Perhaps like [vite does it](https://vitejs.dev/config/#clearscreen)?

**Comment by pi0** [comment]
Hi @autumnblazey, actually we do have it! Try `npx nuxi dev --no-clear`.

Perhaps the CLI docs could include this (https://v3.nuxtjs.org/api/commands/dev)

**Comment by autumnblazey** [comment]
oh! yeah perhaps some documentation on it would be nice. thank you!

**Comment by manniL** [comment]
> oh! yeah perhaps some documentation on it would be nice. thank you!

PR welcome 😋

**Comment by autumnblazey** [comment]
alright! I am considering it, heh (why I left the issue open)

**Comment by autumnblazey** [comment]
hmm, documentation added in #5197 (thanks! was going to do it soonish but hadnt realised that someone already did it) and rc 4, so I believe it is good to close this now
