### ISSUE TITLE
location.href baseURL removed after hydration

### ISSUE THREAD

**Issue by daniel-fahl** [nuxt/framework#5058]
### Environment

------------------------------
- Operating System: `Linux` (in Docker on M1 MacBook)
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `app`, `target`, `modules`, `strapi`, `css`, `nitro`, `vite`
- Runtime Modules:  `@nuxtjs/strapi@1.3.2`
- Build Modules:    `-`
------------------------------

### Reproduction

See repo: [nuxt-app-baseurl-bug](https://github.com/daniel-fahl/nuxt-app-baseurl-bug)

After `yarn install`, run `NUXT_APP_BASE_URL=/test/ yarn dev -o` (or `NUXT_APP_BASE_URL=/test/ yarn generate`)
_(Note: I think setting NUXT_APP_BASE_URL wouldn't even be necessary...)_

### Describe the bug

**Prerequisites:**
`app.baseURL` is set to `/test/` in nuxt.config.ts

**Expected behavior:**
* Application is available at URL [http://localhost:3000/test/](http://localhost:3000/test/)
* After visiting, URL in browser still shows `http://localhost:3000/`

**Actual / observed behavior:**
* After visiting, URL in browser changes to `http://localhost:3000/` after a brief delay (after hydration?)

**Comment by danielroe** [comment]
This should be resolved in https://github.com/nuxt/framework/pull/4933.

You can use the edge channel release to confirm. Let me know if there are any continuing issues.

**Comment by daniel-fahl** [comment]
Thanks @danielroe - it appears to be working now.
One behavior that I'm unsure about:
Assuming baseURL==/test/, when I visit localhost:3000/ the url changes to localhost:3000/test/ as expected, however the application is already rendered, showing a 404 error. Is that expected behavior?

**Comment by danielroe** [comment]
I would expect a 404 error if they visit a URL that isn't the base url - rather than redirecting on client-side to `/test`.
