### ISSUE TITLE
NuxtLink active-classes are not applied on parents of non-nested pages 

### ISSUE THREAD

**Issue by vanling** [nuxt/framework#5087]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-27bwem-nojgd6?file=pages/blog/index.vue

### Describe the bug

Had a small back and forth with  [duboiss](https://github.com/duboiss) @ https://github.com/nuxt/framework/discussions/2086#discussioncomment-2793732 

The active-classes are not always applied.

> if your pages folder structure is /blog/index.vue && /blog/[slug].vue the active class is broken because 'index' is not the 'slugs' parent (i think)
> 
> if your structure is blog.vue([with NuxtPage](https://v3.nuxtjs.org/guide/directory-structure/pages#nested-routes)) && blog/index.vue && blog/[slug].vue the active classes works

And im not sure if this is intended behavior or not. @duboiss said this used to work in v2 and that triggered me to create this bug-report just in case.

> The folder structure is well /blog/index.vue & /blog/[slug].vue.
> On Nuxt 2 it was /blog/index.vue & /blog/_slug.vue.

current "workaround" is an adding a parent page with 
```
<template>
  <div>
    <NuxtPage />
  </div>
</template>
```
which seems a bit much

**Comment by duboiss** [comment]
I have created a stackblitz about Nuxt 2.
[https://stackblitz.com/edit/nuxt-starter-lahuyz?file=layouts/default.vue](https://stackblitz.com/edit/nuxt-starter-lahuyz?file=layouts/default.vue)
On `/blog/a-slug` page we have:
```html
<a href="/" class="">Home</a>
<a href="/blog" class="nuxt-link-active">Blog</a> <!-- nuxt-link-active is added to "route parent" -->
<a href="/blog/a-slug" class="nuxt-link-exact-active nuxt-link-active" aria-current="page">Blog page</a>
```

**Comment by vanling** [comment]
The following shows why it is not working in nuxt3 ( as expected? )

_Without an nuxt-page in parent_
```
    {
        name: "blog-test-slug",
        path: "/blog-test/:slug",
        file: "/home/projects/github-27bwem-nojgd6/pages/blog-test/[slug].vue",
        children: [],
    },
    {
        name: "blog-test",
        path: "/blog-test",
        file: "/home/projects/github-27bwem-nojgd6/pages/blog-test/index.vue",
        children: [],
    },
```

_vs a parent with nuxt-page_

```
{
    path: "/blog",
    file: "/home/projects/github-27bwem-nojgd6/pages/blog.vue",
    children: [
        {
            name: "blog-slug",
            path: ":slug",
            file: "/home/projects/github-27bwem-nojgd6/pages/blog/[slug].vue",
            children: [],
        },
        {
            name: "blog",
            path: "",
            file: "/home/projects/github-27bwem-nojgd6/pages/blog/index.vue",
            children: [],
        }
    ],
},
```

**Comment by vanling** [comment]
Also tried a third way @duboiss no <nuxt-page/> or extra page required.
```
/pages/blog.vue
/pages/blog/[slug].vue
```

```
{
    name: "blog-3",
    path: "/blog-3",
    file: "/home/projects/github-27bwem-nojgd6/pages/blog-3.vue",
    children: [
      {
        name: "blog-3-slug",
        path: ":slug",
        file: "/home/projects/github-27bwem-nojgd6/pages/blog-3/[slug].vue",
        children: [],
      }
    ],
  },
  ```
  
  @danielroe if above would be the intended way of doing a page structure like this, this "bug" changes into an DX improvement. So we could group pages into the folder and have the same behavior. 
  
Example:
  
 ```
pages/blog.vue
pages/blog/[slug].vue
 ```
and 
  ```
pages/blog/index.vue
pages/blog/[slug].vue
 ```
Would result in the same routing structure.

**Comment by vanling** [comment]
_My previous statement was wrong, and i've hidden the comment._

**Comment by Surof1n** [comment]
It might not work because of https://router.vuejs.org/guide/migration/index.html#removal-of-the-exact-prop-in-router-link and https://github.com/ vuejs/rfcs/blob/master/active-rfcs/0028-router-active-link.md#summary

**Comment by Surof1n** [comment]
@danielroe is this really a bug? vue-router suggests implementing this via slot.

**Comment by danielroe** [comment]
Yes, I agree. The key question is whether the routes generated are correct. (You can view at http://localhost:3000/_vfs/%23build%2Froutes.) Beyond that, the behaviour of the classes applied is a question for vue-router.

**Comment by Surof1n** [comment]
@danielroe Please could you tell me the status of the slot api implementation for nuxt-link?

**Comment by esbeto** [comment]
Hi, I don't understand the situation here. I'm creating a blog that has a simple folder structure:
```
├── [category]
│   ├── [post].vue
│   └── index.vue
```

As it is, there's no way for my blog category menu to have a `router-link-active` link when I open a post of a specific category?

The only solution I could find was to create a parent `[category].vue` with a simple:
```vue
<template>
  <NuxtPage />
</template>
```

And that does give the links `router-link-active`, but when navigating, it flashes a white page, instead of the nice navigation transition you get from the previous folder structure. (?)

What should I do?

**Comment by patrickmonteiro** [comment]
As I have a Sidebar.vue file I decided to do the following logic: 

script:

```js
const activeRoute = ref('');

const route = useRoute();
watch(route, (r) => {
  activeRoute.value = r.path;
});

const activeMenu = (routeMenu: string) =>
  activeRoute.value.includes(routeMenu) ? '-active' : '';
```

template:

```php
:class="[ itemLink ? activeMenu(itemLink) : '' ]"
```

**Comment by danielroe** [comment]
You can see a good explanation of this behaviour at https://github.com/nuxt/framework/discussions/2086#discussioncomment-4575574.
