### ISSUE TITLE
To redirect in middleware hook makes `write after end` error. (with Vercel) 

### ISSUE THREAD

**Issue by peterkimzz** [nuxt/framework#5092]
### Environment

Nuxt CLI v3.0.0-rc.3                                                                                                17:43:59
RootDir: /Users/peterkimzz/Projects/nuxt3                                                      17:44:01
Nuxt project info:                                                                                                  17:44:01

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```ts
// middleware/auth.ts
export default defineNuxtRouteMiddleware((to, from) => {
  try {
    // const member = useMember();
    // if (!member.value) {
    //   return navigateTo(`/login?redirect=${to.fullPath}`);
    // }

    return `/login?redirect=${to.fullPath}`;
  } catch (err) {
    console.log(err);
  }
});
```

```vue
// layouts/dashboard.vue
<template>
  <div class="flex justify-between">
    <Sidebar class="w-[240px]" />
    <div class="flex-1 pl-[240px]">
      <div class="mx-auto max-w-screen-lg flex-1 px-6 py-10">
        <slot />
      </div>
    </div>
  </div>
</template>
```

```vue
// pages/dashboard.vue
<template>
  <div>
    Dashboard
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: ["auth"],
  layout: "dashboard",
});
</script>
```

### Describe the bug

Hi,
I'm hosting my nuxt3 app to Vercel. It perfectly supports SSR without any configuration. Awesome.

But when I try to redirect a user to any pages in a middleware hook, Vercel returns 500 error.

`return any string` or `navigateTo()` makes error `write after end`. Sometimes this one occurs when we call `res.send()` twice.

### Additional context

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/20244536/169643500-8c1bf052-d64c-483c-9937-82c5b2bce62b.png">

### Logs

I'm attaching Vercel log.

```shell
2022-05-21T08:36:22.435Z	c8ace4e7-1329-46c4-86be-89ed7a38e724	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"write after end","code":"ERR_STREAM_WRITE_AFTER_END","stack":["Error [ERR_STREAM_WRITE_AFTER_END]: write after end","    at new NodeError (internal/errors.js:322:7)","    at writeAfterEnd (_http_outgoing.js:694:15)","    at ServerResponse.end (_http_outgoing.js:815:7)","    at ServerResponse.res.end (file:///var/task/chunks/nitro/vercel.mjs:65:10)","    at Immediate._onImmediate (file:///var/task/node_modules/h3/dist/index.mjs:117:17)","    at processImmediate (internal/timers.js:464:21)"]}
Unknown application error occurred
```

**Comment by peterkimzz** [comment]
This issue has been resolved when I changed the package manager `yarn` to `npm`. I don't know why this changing resolves that. Anyway, I'll close this issue.

**Comment by andyBobro** [comment]
Had the same issue, and npm helped, thx @peterkimzz

**Comment by peterkimzz** [comment]
@andyBobro Still get the error in rc.4 version?

**Comment by Kolobok12309** [comment]
> @andyBobro Still get the error in rc.4 version?

Yea, we get same error with `rc.4` version
