### ISSUE TITLE
Hydration node mismatch 

### ISSUE THREAD

**Issue by cawa-93** [nuxt/framework#5098]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

GitHub: https://github.com/cawa-93/Nuxt-hydration-node-mismatch-issue-reproduction
StackBlitz: https://stackblitz.com/edit/github-pqjhga?file=pages/index.vue

### Describe the bug

When the component uses `useFetch` and there is an element with `v-if="false"` in `<Teleport>` then:
- When you load a page from the server, it loads, but it occurs directly.
- When you try to go to such a page by following the link, the navigation breaks and the white screen remains.

https://user-images.githubusercontent.com/1662812/169662746-bba5aa89-8506-42d4-adfb-2735f533d1f6.mp4

### Additional context

According to my observations, this problem is present not only in the DEV environment but also in the PROD

**Comment by QiroNT** [comment]
I think it's duplicated with #4711.

**Comment by cawa-93** [comment]
This seems to have been fixed at https://github.com/vuejs/core/commit/70c2d5bbc066585febd12536a6ab39c4384b277b
