### ISSUE TITLE
Aborted?

### ISSUE THREAD

**Issue by whichdew** [nuxt/framework#5134]
### Environment

Nuxt CLI v3.0.0-rc.3                                                         16:50:00
RootDir: /src/frontend/nuxt3-all-in-one                                      16:50:01
Nuxt project info:                                                           16:50:01

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.10.0`
- Builder:          `vite`
- User Config:      `alias`, `ssr`, `buildModules`, `vite`, `meta`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@7.7.1`
------------------------------

### Reproduction

migrate from `"nuxt3": "3.0.0-27376999.6abf75d` to `    "nuxt": "3.0.0-rc.3","@nuxt/vite-builder": "3.0.0-rc.3",`

### Describe the bug

 WARN  auto-imports: presets.names is deprecated, use presets.imports instead                                                                               16:43:49

 WARN  auto-imports: presets.names is deprecated, use presets.imports instead                                                                               16:43:49

 WARN  Duplicated imports "useHead", the one from "#head" has been ignored                                                                                  16:43:49

 WARN  Duplicated imports "useHead", the one from "#head" has been ignored                                                                                  16:43:49

 WARN  [@vue/compiler-sfc] defineExpose is a compiler macro and no longer needs to be imported.                                                             16:43:52

✔ Nitro built in 1836 ms                                                                                                                              nitro 16:43:53
node[3681979]: ../src/node_file-inl.h:160:node::fs::FSReqPromise<AliasedBufferT>::~FSReqPromise() [with AliasedBufferT = node::AliasedBufferBase<double, v8::Float64Array>]: Assertion `finished_' failed.
 1: 0xb00d90 node::Abort() [node]
 2: 0xb00e0e  [node]
 3: 0xafbcda  [node]
 4: 0xb07512 node::fs::FSReqAfterScope::~FSReqAfterScope() [node]
 5: 0xb079fe node::fs::AfterOpenFileHandle(uv_fs_s*) [node]
 6: 0x1555bad  [node]
 7: 0x155a336  [node]
 8: 0x156c7a4  [node]
 9: 0x155ac68 uv_run [node]
10: 0xa3dfe5 node::SpinEventLoop(node::Environment*) [node]
11: 0xbc96c2 node::worker::Worker::Run() [node]
12: 0xbc9e58  [node]
13: 0x7f407f90cea7  [/lib/x86_64-linux-gnu/libpthread.so.0]
14: 0x7f407f83cdef clone [/lib/x86_64-linux-gnu/libc.so.6]
Aborted

**Comment by 516310460** [comment]
Link: https://www.github.com/***/****

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by xdandyx** [comment]
> Would you provide a reproduction? 🙏

After some exploration, I found the problem. 

The first is the problem that the error log is not detailed enough, which should be a problem with `nuxt dev`. 
> When I delete the `.nuxt`, the error message is clear, so it is recommended to delete the `.nuxt` every time `npm run dev` in the dev environment to avoid the impact of caching. 

In addition, the specific information of this problem is that 
1. I have `a .js` file under the `nuxt-app/service`
2.  the `a .js` has such a line of code `import logger from '~/mylib/src/util'`
but when `run dev`, the error is **can not find ~**, and it is normal in using 3.0.0-beta, but it is not easy to determine whether the previous normal is because I did not completely update the .nuxt. 

Finally, **how to import** in nuxt and combine `tsconfig.alias`, `nuxt.config.path`, can you give some advice? Much appreciated.
> ssr:true/false

**Comment by danielroe** [comment]
You should add any aliases to your nuxt config directly - they will then be updated in the generated `tsconfig.json`:

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  alias: {
    // add here
  }
})
```

I still don't have enough information to reproduce this. Would you provide it via https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz ? 🙏

**Comment by whichdew** [comment]
> You should add any aliases to your nuxt config directly - they will then be updated in the generated `tsconfig.json`:
> 
> ```js
> import { defineNuxtConfig } from 'nuxt'
> 
> export default defineNuxtConfig({
>   alias: {
>     // add here
>   }
> })
> ```
> 
> I still don't have enough information to reproduce this. Would you provide it via https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz ? 🙏

To be honest, in the process of using nuxt3, I gradually feel tired, and it seems that various bugs appear inexplicably. 

It's possible that this bug depends on other bugs, so I suggest that you can delay fixing my bug because my bug can't be reproduced in a new project, but it does exist in my project, which is very strange. 

Also, in the process of reproducing this bug, I found that nuxt's API routing is also problematic! You can clone the repository below and try the following command: 
1. curl 127.0.0.1:3000/api
> my index does not work, why {hello:world} returned
3. curl 127.0.0.1:3000/api/test 
> my test not work
5. curl 127.0.0.1:3000/
> route/index works
4. middleware/log doesn't work

**Comment by danielroe** [comment]
The bug is https://github.com/unjs/nitro/issues/283 (that `~/server/routes/index.ts` overrides every request).

When you get rid of that and remove the vite proxy you created, everything seems to be working fine: https://stackblitz.com/edit/github-ennu93.

**Comment by whichdew** [comment]
> The bug you encountered is [unjs/nitro#283](https://github.com/unjs/nitro/issues/283) (that `~/server/routes/index.ts` overrides every request).
> 
> When you get rid of that and remove the vite proxy you created, everything seems to be working fine: https://stackblitz.com/edit/github-ennu93.
> 
> I'm going to close this issue as it's not clear what it refers to and I believe the reproduction you shared is for other possible bugs but please feel free to open new ones for each individual issue you encounter, and I will very happily look into them. 🙏

Thank you. After removing `vite.proxy`, `/api/*` work. My fault 🤦‍♂️.
