### ISSUE TITLE
HMR does't work in WSL 2

### ISSUE THREAD

**Issue by cawa-93** [nuxt/framework#5135]
### Environment

------------------------------
- Operating System: `Linux` (WSL 2 with `Ubuntu`)
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3-27550969.a4a3cff`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `telemetry`, `modules`, `typescript`, `runtimeConfig`, `css`
- Runtime Modules:  `trpc-nuxt@0.1.16`
- Build Modules:    `-`
------------------------------

### Reproduction

I'm trying to run development mode in WSL. 

### Describe the bug

I got 

```node
 ERROR  [h3] write EPIPE                                                              

  at afterWriteDispatched (node:internal/stream_base_commons:160:15)
  at writeGeneric (node:internal/stream_base_commons:151:3)
  at Socket._writeGeneric (node:net:817:11)
  at Socket.connect (node:net:799:12)
  at Object.onceWrapper (node:events:641:28)
  at Socket.emit (node:events:539:35)
  at Socket.emit (node:domain:475:12)
  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1173:10)
```

And HMR doesn't work. I'm making changes to the vue components, but I don't see a message in the console that the development server saw changes in the files and tried to update

**Comment by misaon** [comment]
I also have WSL2 and HMR is working properly. Try a clean Nuxt 3

**Comment by SirMishaa** [comment]
Is the project in WSL? In my case, WSL 2 and HMR is working good too. 

Can you go to your project folder and do the following commands: 
```bash
> pwd
> whereis node
```

**Comment by cawa-93** [comment]
> 

```
node: /usr/bin/node /usr/include/node /mnt/c/Program Files/nodejs/node.exe /usr/share/man/man1/node.1.gz
```

**Comment by cawa-93** [comment]
@misaon  ok. In clean setup i realy don't see described h3 error but HMR still doesn't work

https://user-images.githubusercontent.com/1662812/170940702-e2200c1f-e28b-47ee-9c0f-6f3dce5a225a.mp4

**Comment by SirMishaa** [comment]
Don't put your project files in your Windows system. 

Instead, put them directly on WSL (in your home folder directory). Otherwise, you will have performance issue and hot reload / watch will not work. 
![image](https://user-images.githubusercontent.com/42717232/170974909-e47ff182-a899-40d5-bff4-b550e315e2a3.png)

**Comment by cawa-93** [comment]
@SirMishaa Oh. I see. Thank
