### ISSUE TITLE
Auto imports not detected in typescript files by VS Code

### ISSUE THREAD

**Issue by jf908** [nuxt/framework#5136]
### Environment

- Operating System: `Linux` (WSL)
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `srcDir`, `target`, `build`, `meta`, `css`, `components`, `modules`, `runtimeConfig`, `vue`
- Runtime Modules:  `@vueuse/nuxt@8.5.0`, `@pinia/nuxt@0.1.9`
- Build Modules:    `-`

### Reproduction

Example of it not working on .ts file in /plugins.

https://stackblitz.com/github/nuxt/framework/tree/main/examples/routing/middleware?file=plugins%2Fadd.ts

### Describe the bug

VS Code (and Stack Blitz) is not detecting nuxt's auto imports in typescript files such as in /middleware, /plugins, etc.
Dev/Build commands work fine but VS Code is not inferring the correct types.

eg. `Cannot find name 'defineNuxtPlugin'.(2304)`

### Additional context

- VS Code: `1.67.2`
- Typescript Version: Tested `4.6.3` and `4.6.4`

**Comment by danielroe** [comment]
Stackblitz doesn't detect the auto-imports owing to the fact that it doesn't take into account the `.nuxt` folder. (They are on it, though, so 🤞.)

I can't reproduce the issue locally with the code you provided.

<img width="850" alt="CleanShot 2022-05-25 at 13 45 15@2x" src="https://user-images.githubusercontent.com/28706372/170254581-2be8d629-dfeb-4114-b9bd-5754ac860cde.png">

**Comment by jf908** [comment]
Thanks, it turns out it was something specific to my project. I solved it by changing my tsconfig.json to no longer include all subdirectories.
```json
{
  "extends": "./.nuxt/tsconfig.json",
  "include": [
    "./.nuxt/nuxt.d.ts",
    "./*",
    "./client/**/*"
  ]
}
```
There must have been some file somewhere in my project that was messing with ts.
