### ISSUE TITLE
Cannot Push With Hash

### ISSUE THREAD

**Issue by YusufcanY** [nuxt/framework#5137]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `buildModules`, `build`, `app`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.9`, `@intlify/nuxt3@0.2.2`, `./modules/auto-import-eslint`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-uhtjer?file=pages/index.vue

### Describe the bug

I want to push with router to another div with id. It doesnt work

**Comment by YusufcanY** [comment]
I tried in your stackblitz and it didnt work. I tried with 4 pc in my office different users and all things are different. Its still dont work. I can't understand how its work on your pc.

**Comment by danielroe** [comment]
Maybe you could create a screencast showing what you experience and describing what you expect?
