### ISSUE TITLE
useHead seems to ignore `links`

### ISSUE THREAD

**Issue by ffxsam** [nuxt/framework#5147]
### Environment

Nuxt CLI v3.0.0-rc.3
RootDir: /Volumes/SuperData/Sites/reelcrafter/v2-microservices
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@3.0.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-gvzqsb?file=app.vue

### Describe the bug

Some properties such as `meta` seem to work fine, but `links` appears to be ignored by `useHead()`.

**Comment by 516310460** [comment]
See: https://v3.nuxtjs.org/guide/features/head-management#usehead-composable

**Comment by ffxsam** [comment]
Gotcha, thanks! Sorry, TypeScript support isn't working for me since I'm in a monorepo and the Nuxt app is in a subfolder.
