### ISSUE TITLE
Unable to use AWS v3 SDK due to error: Identifier 'module' has already been declared

### ISSUE THREAD

**Issue by ffxsam** [nuxt/framework#5148]
### Environment

Nuxt CLI v3.0.0-rc.3
RootDir: /Volumes/SuperData/Sites/reelcrafter/v2-microservices
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@3.0.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-d2pz9b?file=app.vue

### Describe the bug

When importing and using classes and functions from the AWS v3 SDK, the following error is thrown when loading the Nuxt app in a browser:

```
[nuxt] [request error] Identifier 'module' has already been declared
  at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
  at async link (internal/modules/esm/module_job.js:67:21)
```

**Comment by ffxsam** [comment]
Did some more digging into this and discovered something:

These SDK packages from AWS have a couple of different entry points in package.json:

```json
  "main": "./dist-cjs/index.js",
  "module": "./dist-es/index.js",
```

Since we're doing an `import { RDSDataClient } from '@aws-sdk/client-rds-data'`, it seems to be using `dist-es/index.js`. However, if I change the import statement:

```js
import { RDSDataClient } from '@aws-sdk/client-rds-data/dist-cjs';
```

Then the code works ok, but of course any TypeScript annotations are lost. There's also an error on the server side:

`ERROR  Vite Error, /_nuxt/node_modules/.vite/deps/@aws-sdk_client-rds-data_dist-cjs.js?t=1653519601297&v=2c763316 optimized info should be defined`

**Comment by ffxsam** [comment]
More details:

This only happens in dev mode (`yarn dev`). When I build the application and run it via API Gateway -> Lambda, it runs perfectly fine.

So it would seem there's something different about the dev build process.

**Comment by ffxsam** [comment]
Similar, possibly related:

`@casl/ability` also doesn't seem to work with Nuxt's dev mode. `yarn dev` results in this:

```
[Vue warn]: Unhandled error during execution of setup function
  at <PrivateReel data= { reelIdOrUsername: 'b1mGMmMYQNC8sjUcxvq3hQ', slug: undefined } >
[nuxt] [request error] __vite_ssr_import_1__ is not defined
  at $id_ee6a35a1 (./nuxt/.nuxt/dist/server/server.mjs:3537:741)
  at async __instantiateModule__ (./nuxt/.nuxt/dist/server/server.mjs:3936:3)
```

Nuxt doesn't seem to like packages with different entry points:

```json
  "main": "dist/es6c/index.js",
  "module": "dist/es5m/index.js",
  "es2015": "dist/es6m/index.mjs",
  "legacy": "dist/umd/index.js",
```

**Comment by 2681137811** [comment]
similar problem too

**Comment by ffxsam** [comment]
I've worked around this `module` issue in AWS Amplify by just creating a Nuxt plugin:

## plugins/graphql.client.ts
```ts
import { API } from 'aws-amplify';

export default defineNuxtPlugin(() => {
  return {
    provide: { API },
  };
});
```

Then whenever I want to use the API:

```ts
const { $API } = useNuxtApp();
const data = await $API.graphql(...);
```

**Comment by danielroe** [comment]
This is no longer reproducible on latest RC, with the new `vite-node` devBundler (enabled by default): https://stackblitz.com/edit/github-d2pz9b-b9tyjs.
