### ISSUE TITLE
Nuxt 3 built server loaded duplicated vue instance when require from 3rd library

### ISSUE THREAD

**Issue by mmis1000** [nuxt/framework#5151]
### Environment

Nuxt project info:                                                                                       14:57:19

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@6.14.17`
- Builder:          `vite`
- User Config:      `publicRuntimeConfig`, `buildModules`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.9`
------------------------------

### Reproduction

Setup
1. install 'pinia' and its plugin into a nuxt3 project
2. define a store
3. use a store
4. run `store.$subscribe(() => {})`

Debug
1. build the server
2. set a breakpoint on the [`store.$subscribe(() => {})` and](https://github.com/vuejs/pinia/blob/af030da326e4bd4c99aeeb60af4d22e412f2be18/packages/pinia/src/store.ts#L406) (inside the callback)
3. start the server with debug
4. read the stacktrace
5. realize there are two copy of vue in the stack

### Describe the bug

![圖片](https://user-images.githubusercontent.com/2993977/170436158-9a5a5f91-87fd-4677-8015-1fece06ad306.png)

The built server loaded two copy of vue into the process, which is a unsupported usage and will break things

### Additional context

This seems happen because the nuxt missed itself from the `<root>/.output/server/node_modules`, and thus cause `vue` in the `<root>/node_modules` to be loaded by accident.

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by mmis1000** [comment]
@danielroe 
https://github.com/mmis1000/nuxt3-bug-issue-5151/tree/b0ce96d53cf975a9820422c0d5d74ae03ed658a8

Just run build, and start `preview` with debugger.

Source code of `third-party/test-module-1.0.0.tgz` is in `third-party/test-module-1.0.0`. 
This has to be packed because it will be inlined otherwise

**Comment by danielroe** [comment]
This is no longer reproducible for me. Let me know if not and we can reopen.
