### ISSUE TITLE
defineComponent is not defined when a component is used from a module via @nuxt/kit

### ISSUE THREAD

**Issue by michaelpumo** [nuxt/framework#5158]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `vite`, `typescript`, `runtimeConfig`, `meta`, `css`, `tailwindcss`, `components`, `target`, `ssr`, `loadingIndicator`, `modules`, `postcss`, `build`, `router`, `server`
- Runtime Modules:  `@michaelpumo/components-nuxt/nuxt@0.0.2`, `@nuxtjs/tailwindcss@5.1.2`, `@storyblok/nuxt@4.0.1`
- Build Modules:    `-`
------------------------------

### Reproduction

This is not easily reproducible on a StackBlitz but the module in question below is publicly available to test at @michaelpumo/components-nuxt.

### Describe the bug

I have a Nuxt 3 app running and any component is able to use `defineComponent` without it having to be imported (it's global).

Some components, we wished to live in NPM, so I created a Nuxt module in a new repository like so (nuxt.js file in root) with the intent to import it into the main site:

```
import { join } from 'pathe'
import { defineNuxtModule } from '@nuxt/kit'

export default defineNuxtModule({
  hooks: {
    'components:dirs'(dirs) {
      dirs.push({
        path: join(__dirname, 'src/components'),
        prefix: 'greggs'
      })
    }
  }
})
```

In the consuming site, I am using this module via nuxt.config.ts like so:

```
modules: [
  '@michaelpumo/components-nuxt/nuxt'
]
```

In my pages, I am using the component like `<GreggsContentMedia />` etc. This component is picked up correctly in the site but throws an error regarding globals like `defineComponent`. "defineComponent is not defined".

<img width="705" alt="Screenshot 2022-05-26 at 14 10 26" src="https://user-images.githubusercontent.com/4269460/170495530-3dab6347-f990-47e0-bbbf-cc622501c06e.png">

It seems odd that globals like `defineComponent` that are _able_ to be used in the main consuming site are _not_ available in components imported from a module? These exact components unchanged will run just fine if used in the main site and not via the module.

This includes other globals for Vue like reactive, ref etc.

### Additional context

If I import like so in the library component:

`import { defineComponent, reactive, computed } from '#imports'`

It works. But ideally, I don't want to have to import globals like this. Is this simply a config concern and not a bug? I have `tsconfig.json` etc set up that imports from Nuxt.

Funny enough, the other components that _this_ component imports do not appear to require an explicit import for themselves such as `defineComponent`, `ref`, `computed` etc. I wonder why that is? They are fine as-is.

**Comment by danielroe** [comment]
This is currently intended behaviour. See https://github.com/nuxt/framework/issues/5027#issue-1238600458 for a suggestion to do this automatically when building a module. (An issue to track would be welcome.)
