### ISSUE TITLE
Cannot start nuxt:  Cannot find module '@nuxt/vite-builder'

### ISSUE THREAD

**Issue by ColinEspinas** [nuxt/framework#5165]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.9.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `modules`, `vite`, `build`, `css`, `typescript`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/supabase@0.1.14`
- Build Modules:    `-`
------------------------------

### Reproduction

Dev branch of https://github.com/WorkEvent/website/tree/dev

Cloning, installing and running the project should give the error.

You can also check it out on https://stackblitz.com/github/WorkEvent/website/tree/dev?file=README.md

### Describe the bug

When trying to run the project through `nuxi dev`, I get an error about `@nuxt/vite-builder` being missing.

### Additional context

Was on version `3.0.0-rc.1` and upgraded, cannot start the project since.

I already tried to remove my node_modules, package-lock and installing again. The error is even reproductible from cloud instances like stackblitz. I also tried doing the same on multiple devices and couldn't get the project to run.

### Logs

```shell
ERROR  Cannot start nuxt:  Cannot find module '@nuxt/vite-builder'
Require stack:
- /home/colin/projects/univ/work-event/website/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:192841)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:242:29)
  at importModule (node_modules/@nuxt/kit/dist/index.mjs:265:24)
  at bundle (node_modules/nuxt/dist/index.mjs:1675:82)
  at build (node_modules/nuxt/dist/index.mjs:1650:11)
  at async Promise.all (index 1)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6736:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6777:5)
```

**Comment by qin-guan** [comment]
I was able to resolve the issue by recreating `package-lock.json`. There were also other Typescript related errors which need to be fixed by installing Typescript, please see the screenshot with the working project:

![image](https://user-images.githubusercontent.com/10321883/170767432-10a710a5-5441-4bb0-aae7-422f397f4033.png)

I hope this helps!

**Comment by ColinEspinas** [comment]
Thanks @qin-guan , I was aware of the typescript error it occurs when you don't have any Typescript language server running. Adding typescript in here is indeed a good idea.

I succeeded to make it work on stackblitz. But I can't get this to work on my machine, I've removed `package-lock.json`, removed `node_modules`, and cleared npm cache. Also tried on another machine and can't get it to work either. I have the exact same `package.json`. 

I just can't get it to work.

I ran the following:
```sh
> rm -rf node_modules
> rm package-lock.json
> rm -rf .nuxt
> npm cache clear -f
```
Then tried to install again:
```sh
> npm i
> npm run dev
```

I still get the exact same error. I think I just can't get npm to install `@nuxt/vite-builder` as it doesn't appear in my `node_modules` directory.

Is there an invisible cache or something that prevents me from doing a correct installation?

**Comment by ColinEspinas** [comment]
When I run `npm i -D @nuxt/vite-builder` I get an ERESOLVE error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vue@3.0.2
npm ERR! node_modules/vue
npm ERR!   peer vue@">=3" from @vueuse/head@0.7.6
npm ERR!   node_modules/@vueuse/head
npm ERR!     @vueuse/head@"^0.7.6" from nuxt@3.0.0-rc.3
npm ERR!     node_modules/nuxt
npm ERR!       dev nuxt@"^3.0.0-rc.3" from the root project
npm ERR!   peer vue@"^3.0.0 <3.0.3" from phosphor-vue@4.4.0
npm ERR!   node_modules/phosphor-vue
npm ERR!     phosphor-vue@"^4.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @nuxt/vite-builder@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@3.2.33
npm ERR! node_modules/vue
npm ERR!   peer vue@"3.2.33" from @nuxt/vite-builder@3.0.0-rc.3
npm ERR!   node_modules/@nuxt/vite-builder
npm ERR!     dev @nuxt/vite-builder@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/colin/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/colin/.npm/_logs/2022-05-27T18_36_19_053Z-debug-0.log
```

Could the dependency installation fail silently because of this when installing the nuxt package?

**Comment by ColinEspinas** [comment]
Just got it to work. Hurray!

Steps I did:
```sh
# Clear current deps just in case
> rm -rf node_modules
> rm package-lock.json
> rm -rf .nuxt
> npm cache clear -f

# Install packages with the --legacy-peer-deps option
> npm i --legacy-peer-deps
> npm run dev

# Have fun!
```

Thanks for the help, have a great day.

**Comment by vytenisstaugaitis** [comment]
I had this and other errors when attempting to run dev. Switching to Node 16.9.0 immediately fixed all the problems.
