### ISSUE TITLE
Dynamic Routes match route and vue files error when in deep  finder

### ISSUE THREAD

**Issue by mlsjla** [nuxt/framework#5168]
### Environment

Nuxt CLI v3.0.0-rc.3                                                                                                        00:17:33
RootDir: /Users/mac/.webcode/gin-nuxt/web                                                                                   00:17:36
Nuxt project info:                                                                                                          00:17:36

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.4`
- Builder:          `vite`
- User Config:      `meta`, `ssr`, `buildModules`, `app`, `css`, `components`, `publicRuntimeConfig`, `experimental`, `vite`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.5.0`, `@pinia/nuxt@0.1.9`
------------------------------

### Reproduction

no

### Describe the bug

```
-| pages/
---| article/
---| ---| [group].vue
---| ---| [group]
---| ---| ---| [id].vue
```
When I  request  /article/aaa      It match    pages/article/ [group].vue    success

But when I  request  /article/aaa/bbb   It also  match pages/article/ [group].vue 

I hope /article/aaa/bbb   It also  match pages/article/ [group]/[id].vue

**Comment by Der-Alex** [comment]
shouldn't it be 
````
-| pages/
---| article/
---| ---| [group]
---| ---| ---| index.vue
---| ---| ---| [id].vue
````
?

**Comment by lqh1008** [comment]
I also encountered the same problem, the dynamic routing nested two levels can not find the page

**Comment by danielroe** [comment]
If you want to match _exclusively_ then use this:

```
-| pages/
---| article/
---| ---| [group]
---| ---| ---| index.vue
---| ---| ---| [id].vue
```

Otherwise, the structure in your original message describes a parent/child relationship. (So you would add `<NuxtPage />` within your `[group].vue` and then the child route would render 'within' it.)
