### ISSUE TITLE
$fetch: Client and server are inconsistent

### ISSUE THREAD

**Issue by 516310460** [nuxt/framework#5170]
### Environment

Operating System: Linux、Mac、Windows
Node Version: v17.9.0
Nuxt Version: 3.0.0-rc.3
Package Manager: npm@8.5.5
Builder: vite
User Config: modules, vite, build, css, typescript, runtimeConfig
Runtime Modules: -
Build Modules: -

### Reproduction

server/api/count.ts
`
let counter = 0
export default () => {
  counter++
  return JSON.stringify(counter)
}
`
app.vue
`
<template>
    <div>
        {{data}}
    </div>
</template>
<script setup>
const data = await $fetch('/api/count')
</script>
`

### Describe the bug

![image](https://user-images.githubusercontent.com/17541676/170650584-2e358084-67db-48fb-a80f-71aa558c7ac8.png)
$fetch: Client and server are inconsistent

### Additional context

--

### Logs

```shell
--
```

**Comment by SirMishaa** [comment]
Can you provide a minimal reproduction in the form of a repository, please ?

**Comment by 516310460** [comment]
https://stackblitz.com/edit/github-421era-jwshz6?file=server%2Fapi%2Fcount.ts,app.vue
Open console

**Comment by danielroe** [comment]
This is because on server, it's 1 and on client in the hydration process it's 2. When working with a Vue framework with client and server, you have to ensure that the state _matches_ between server and client. You should use a helper like `useAsyncData`, `useState` or `useFetch` to ensure that client and server state match each other.

**Comment by 516310460** [comment]
useFetch

> This is because on server, it's 1 and on client in the hydration process it's 2. When working with a Vue framework with client and server, you have to ensure that the state _matches_ between server and client. You should use a helper like `useAsyncData`, `useState` or `useFetch` to ensure that client and server state match each other.

Set 'server: false' in usefetch. It will not be executed after 'nuxt link' jump, but only when the page is refreshed
