### ISSUE TITLE
`validate` function in `definePageMeta`

### ISSUE THREAD

**Issue by antfu** [nuxt/framework#5172]
In Nuxt v2: https://nuxtjs.org/docs/components-glossary/validate/

Using middleware could indeed achieve the same, but it would be a bit verbose to create and might lose the context since now they are in different files in different directories. I think it would be nice to support the `validate` function in `definePageMeta`. For example:

```vue
<script setup>
definePageMeta({
  validate({ params }) {
    return ['foo', 'bar'].includes(params.type)
  }
})
</script>
```

**Comment by pi0** [comment]
This would be possible using a router middleware to implement but a nice addition for sure! 

As a small note, while we have the chance of breaking changes, it might be nice to also rethink about naming and behavior of the function. In Nuxt 2, a falsy validate means page is 404 basically. We could:
 - Use a clearer name if 404 check is only need such as `isRouteMatches()`
 - Allow extended behavior by returning other codes such as `return 400 // Bad Request` or `return { statusCode: 404, statusMessage: 'invalid id param'}`

**Comment by cawa-93** [comment]
1. Why not implement this feature at the vue-router level?
2. It would be fantastic to reconcile this with typing
	```ts
	  definePageMeta({
	    validate(context): context is ContextWithParams<{type: 'foo' | 'bar'}> {
	      return ['foo', 'bar'].includes(context.params.type)
	    }
	  })

	useRoute().params // {type: 'foo' | 'bar'}
	  ```
