### ISSUE TITLE
Plugin "provide" feature not working

### ISSUE THREAD

**Issue by ffxsam** [nuxt/framework#5179]
### Environment

N/A

### Reproduction

https://stackblitz.com/edit/github-uj6ngr?file=app.vue,plugins%2Ftest.ts

### Describe the bug

Followed [these docs](https://v3.nuxtjs.org/guide/directory-structure/plugins#automatically-providing-helpers), and `provide` doesn't seem to work.

**Comment by danielroe** [comment]
```diff
  export default defineNuxtPlugin(() => {
    console.log('Plugin loading');
    return {
      provide: {
-       $hello: () => 'world',
+       hello: () => 'world',
      },
    };
  });
```
