### ISSUE TITLE
[unhandledRejection] Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by mak33v** [nuxt/framework#5183]
[unhandledRejection] Cannot set headers after they are sent to the client                                                                                                                                                   

  at new NodeError (node:internal/errors:372:5)
  at ServerResponse.setHeader (node:_http_outgoing:576:11)
  at sendError (/H:/nuxt%20projects/trademark/node_modules/h3/dist/index.mjs:216:13)
  at nodeHandler (/H:/nuxt%20projects/trademark/node_modules/h3/dist/index.mjs:375:15)

Due to a problem with dynamic imports, I moved all the resources of the application to the /public folder and now I constantly get this error, what could be the problem?

**Comment by D2theR** [comment]
I'm getting a similar error. 

`ERROR  [unhandledRejection] Cannot set headers after they are sent to the client                                                                                                                                                                                             

  at new NodeError (internal/errors.js:322:7)
  at ServerResponse.setHeader (_http_outgoing.js:561:11)
  at sendError (node_modules/h3/dist/index.mjs:216:13)
  at nodeHandler (node_modules/h3/dist/index.mjs:375:15)`

I'm not using a public folder.

**Comment by bitmonti** [comment]
Getting this error to.

 ERROR  [unhandledRejection] Cannot set headers after they are sent to the client                                                                                                11:05:14

  at new NodeError (node:internal/errors:372:5)
  at ServerResponse.setHeader (node:_http_outgoing:576:11)
  at sendError (node_modules/h3/dist/index.mjs:216:13)
  at nodeHandler (node_modules/h3/dist/index.mjs:376:15)


node v16.15.0

  "devDependencies": {
    "@intlify/nuxt3": "^0.2.2",
    "@nuxtjs/tailwindcss": "^5.1.2",
    "nuxt": "3.0.0-rc.3"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.1.9",
    "@stripe/stripe-js": "^1.31.0",
    "graphql": "^16.5.0",
    "pinia": "^2.0.14",
    "villus": "^1.1.0"
  }

**Comment by bitmonti** [comment]
Does anyone use AdGuard adblocker?

**Comment by YusufcanY** [comment]
same error in rc4
```
 ERROR  [unhandledRejection] Cannot set headers after they are sent to the client

  at new NodeError (node:internal/errors:371:5)
  at ServerResponse.setHeader (node:_http_outgoing:576:11)
  at sendError (node_modules/h3/dist/index.mjs:219:13)
  at nodeHandler (node_modules/h3/dist/index.mjs:378:15)
```

**Comment by mak33v** [comment]
> Does anyone use AdGuard adblocker?

I don't use blockers and I get this error

**Comment by Jocabin** [comment]
I'm getting the same error as @bitmonti, only on Firefox too. It appears twice when refreshing the page (CTRL+R).

```
 ERROR  [unhandledRejection] Cannot set headers after they are sent to the client

  at new NodeError (node:internal/errors:372:5)
  at ServerResponse.setHeader (node:_http_outgoing:576:11)
  at sendError (/C:/Users/kobyf/Dev/idb/node_modules/h3/dist/index.mjs:216:13)
  at nodeHandler (/C:/Users/kobyf/Dev/idb/node_modules/h3/dist/index.mjs:375:15)
```
```
`Node v16.15.0`
  ```
```
  "devDependencies": {
    "nuxt": "3.0.0-rc.3"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.1.9",
    "pinia": "^2.0.14",
    "sass": "^1.52.0",
    "sass-loader": "^13.0.0"
  }
  ```

**Comment by bitmonti** [comment]
I removed package-lock.json and node_modules. Than updated nuxt version "3.0.0-rc.3" to "**3.0.0-rc.4**".

This solved the problem for me.

**Comment by Jocabin** [comment]
For me too, thanks !

**Comment by Deyjandi** [comment]
I deleted the package lock file, the node_modules and the .nuxt directory. Then I installed the packages.

My nuxt entry in ```package.json``` is the following ```"nuxt": "npm:nuxt3@latest"```.

The problem still persists. I m using firefox developer edition.

**Comment by misaon** [comment]
still persists for me (running inside Docker)

**Comment by evilnemesis** [comment]
I have same issue. 
For me this error is shown only in development mode in docker using https
I run Nuxt in docker with HTTPS proxy (via nginx in docker).

**I figured out that error is thrown when using `useHead()` for `links` in component or setting `app.head.link` in `nuxt.config.ts`. 
Does not matter if links files are from nuxt or from external URL**

docker-compose.yaml
```
version: '3.8'

services:
  app:
    container_name: my-app
    build: .
    command:
      - sleep
      - '9999999999'
    ports:
      - '80:80'
    volumes:
      - .:/app:cached

  https-proxy:
    container_name: my-app-https-proxy
    image: nginx
    volumes:
      - './https-proxy-cert.cert:/var/https-proxy-cert.cert'
      - './https-proxy-cert.key:/var/https-proxy-cert.key'
      - './https-proxy.conf:/etc/nginx/conf.d/http-proxy.conf'
    ports:
      - '443:443'
      - '24678:24678'

volumes:
  node_modules:
```

https-proxy.conf
```
server {
    listen 443 ssl http2;
    server_name _;

    location / {
        proxy_pass http://app:80;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    ssl_protocols TLSv1.2;

    ssl_certificate     /var/https-proxy-cert.cert;
    ssl_certificate_key /var/https-proxy-cert.key;

    access_log /dev/stdout;
    error_log /dev/stderr;
}

server {
    listen 24678 ssl http2;
    server_name _;

    location / {
        proxy_pass http://app:24678;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    ssl_protocols TLSv1.2;

    ssl_certificate     /var/https-proxy-cert.cert;
    ssl_certificate_key /var/https-proxy-cert.key;

    access_log /dev/stdout;
    error_log /dev/stderr;
}
```

**Comment by Georglider** [comment]
Have the same problem

**Comment by bitmonti** [comment]
I'm not using useHead() or app.head.link. Error still exists.

**Comment by ennioVisco** [comment]
> I'm not using useHead() or app.head.link. Error still exists.

I assume the problem is more related to having pointers to external resources via Https than the `useHead` composable. Try maybe to comment out these external `<link>`s or `<img>`s, and see whether the problem disappears :)

**Comment by bitmonti** [comment]
I'm not using any external resources either on links or images in any place of the app.

**Comment by marty-mcgee** [comment]
I'm using RC5 and the instant I add a file to the /public directory (like my favicon.ico file), I receive this error.
`[unhandledRejection] Cannot set headers after they are sent to the client`

**Comment by genu** [comment]
I'm also facing this issue. (on rc.6)

I've tried various solutions mentioned above but none seem to resolve. I do notice that its somewhat sporadic (Possibly why some users are saying it has resolved the issue).

I haven't determined where the failure is, or whether a manual restart of nuxt is required to verify if a solution has any effect.

**Comment by ennioVisco** [comment]
> I'm also facing this issue. (on rc.6)
> 
> I've tried various solutions mentioned above but none seem to resolve. I do notice that its somewhat sporadic (Possibly why some users are saying it has resolved the issue).
> 
> I haven't determined where the failure is, or whether a manual restart of nuxt is required to verify if a solution has any effect.

It seems it only appears at development time, so it shouldn't be a big issue anyway.

**Comment by damevin** [comment]
Any updates about this issue :( ?

**Comment by Mnigos** [comment]
I'm also facing this issue. 
```json
 "nuxt": "3.0.0rc.6"
 ```

**Comment by Morpheu5** [comment]
Same here, it happens randomly but it seems it's triggered when I use `useCookie` in a plugin or route middleware (but I think it also happened in a component at one point).

This one is very hard to pin down because I can't find a reliable trigger. Sometimes it happens when a 500 error is triggered, sometimes it happens without apparent causes. I'm on **3.0.0-rc.8** and running straight on my machine, not in a Docker container.

**Comment by Morpheu5** [comment]
I suspect it may be caused by an error somewhere, it would make more sense than the others because I'm pretty sure I'm not doing any of that myself. However, I can't get enough logging to know for sure. Any time this happens, I only get a laconic 500 no-can-do error and no context.

I don't suppose `useCookie` or `parseCookies` do try to *set* cookies, right? Although, on occasion, I get a "can't read value X of `undefined`" apparently on these two calls, and it turns out the `undefined` part is the cookies themselves (as in: there is nothing to parse). I can circumvent this with a definedness check, but it would be good to figure out why this may happen. Should I open a bug in Nitro or H3?

**Comment by danielroe** [comment]
Yes, the (vue app composable) `useCookie` will try to set a cookie if the value has changed from the initial value. I'm very happy for you to comment here with a reproduction, but it's probably a nuxt issue if there's a problem with the vue app composable.

**Comment by Morpheu5** [comment]
I couldn't reproduce it on an MRE but it doesn't look like it's `useCookie` trying to set a cookie at the wrong time. I get this error on the server's console instead

```
 ERROR  [unhandledRejection] Cannot set headers after they are sent to the client                                                                                                                                                                             20:16:37

  at new NodeError (node:internal/errors:377:5)
  at ServerResponse.setHeader (node:_http_outgoing:595:11)
  at sendError (node_modules/h3/dist/index.mjs:287:13)
  at nodeHandler (node_modules/h3/dist/index.mjs:450:15)
```

which points me to `node_modules/h3/dist/index.mjs:287:13` which is 

```
  event.res.statusCode = h3Error.statusCode;
  event.res.statusMessage = h3Error.statusMessage;
  event.res.setHeader("Content-Type", MIMES.json); // <--- setHeader is is at 287:13 precisely
  event.res.end(JSON.stringify(responseBody, null, 2));
```

but I can't get any more out of this. Would there be a way of getting more debug logging perhaps?

**Comment by danielroe** [comment]
**Reproduction for a way of triggering this**: https://stackblitz.com/edit/github-u3et7v. HT: @benjamincanac.

**Comment by paramula** [comment]
> Your Nuxt app si running inside Docker container?

yes its in docker container, i there is error sometime

**Comment by gregg-cbs** [comment]
Getting this error too.

`"nuxt": "3.0.0-rc.11"`

```
 ERROR  [unhandledRejection] Cannot set headers after they are sent to the client                                          17:19:51

  at new NodeError (node:internal/errors:371:5)
  at ServerResponse.setHeader (node:_http_outgoing:576:11)
  at sendError (/D:/Devbox/Dare/ms-amlin/node_modules/h3/dist/index.mjs:72:13)
  at nodeHandler (/D:/Devbox/Dare/ms-amlin/node_modules/h3/dist/index.mjs:550:15)
```

**Comment by gregg-cbs** [comment]
Right so it seems the issue I had was that I was using a package called 'nuxt-security', these errors started so I removed the package but continued to see the error.

It seems nuxt was caching and including packages that were removed from the config and npm, even after re-running the dev server.

Only way to rid the error was to remove .nuxt and node_modules folder. I dont think this is the intended behaviour, let me know.

**Comment by danielroe** [comment]
Hm. We've implemented a solution for this - what version of nuxt are you on?

**Comment by gregg-cbs** [comment]
Infact in the .nuxt folder I could see references to components that no longer exist and quite a few of them...

**Comment by gregg-cbs** [comment]
> Hm. We've implemented a solution for this - what version of nuxt are you on?

`"nuxt": "3.0.0-rc.11"`

**Comment by danielroe** [comment]
These should be removed if you are using nuxi newer than rc9: https://github.com/nuxt/framework/pull/6672. Can you confirm your nuxi version in particular?

**Comment by gregg-cbs** [comment]
> These should be removed if you are using nuxi newer than rc9: #6672. Can you confirm your nuxi version in particular?

`"nuxi": "3.0.0-rc.11",`

**Comment by SchneiderOr** [comment]
3.0.0-rc.11 solved the issue for us, it was a shot on the dark, Thanks!

**Comment by adrianwix** [comment]
@danielroe Which would be the best place to set a cookie in the nuxt lifecycle? I am using Nuxt 2 and getting this error when setting the cookies for the auth module inside a layout's created hook. Maybe I should do it inside mounted?

**Comment by danielroe** [comment]
@adrianwix This is the repository for Nuxt 3. Would you create a new discussion at https://github.com/nuxt/nuxt.js with more information about what you are trying?

**Comment by leccyril** [comment]
I have the same issue, nuxtjs3.0.0 i just add auth.js in middleware and this piece of code : 
```
 export default defineNuxtRouteMiddleware((to, from) => {
	console.log('try to get token')
	const auth = useState('isConnected')

	if (!auth) {
		return navigateTo('/login')
	}
	return navigateTo('/')
})
```
and in index.vue: 

```
<script lang="ts" setup>
definePageMeta({
	middleware: ['auth']
})
</script>
```

something special to do to make work middleware ?

**Comment by danielroe** [comment]
@leccyril If that isn't working feel free to create a new issue with a reproduction.
