### ISSUE TITLE
NODE_ENV overwriting results in weird errors

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/framework#5196]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@3.1.1`
- Builder:          `vite`
- User Config:      `ssr`, `runtimeConfig`, `typescript`, `css`, `buildModules`, `intlify`, `alias`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.4.2`, `@intlify/nuxt3@0.1.10`
------------------------------

### Reproduction

I stumbled into an issue very similar to the one of https://github.com/nuxt/framework/issues/1913 and https://github.com/nuxt/framework/issues/3730, i.e. overriding `NODE_ENV` environment variable. 
This results in a weird blank page, with no clear info on what happened.

I believe it deserves a warning in the https://v3.nuxtjs.org/guide/features/runtime-config/#environment-variables, it took me a week to figure out that that was the problem.

### Describe the bug

-

**Comment by svedova** [comment]
Quoting the same [comment](https://github.com/nuxt/framework/issues/1913#issuecomment-1151737626) for transparency.

You can reproduce this while building on Stormkit:

## Steps to reproduce

1. Checkout https://github.com/svedova/stormkit-node-env-problem
2. Set `NODE_ENV=development` in the environment variables settings
3. Deploy the app
4. Check the link. It generates the same error written above.

## Examples
1. This was built using node.js 16: https://nuxt-env-development-problem--62130764006674.stormkit.dev/ (has the error)
2. This was built using node.js 14: https://nuxt-env-development-problem--62129119204323.stormkit.dev/ (no error)

**Comment by svedova** [comment]
As [mentioned here](https://github.com/nuxt/framework/issues/1913#issuecomment-1151737626), one of our users reported the same issue. I believe the problem is because development modules are being included when the `NODE_ENV=development`. Maybe Nuxt can print a warning in the console when it's built using `development` environment?
