### ISSUE TITLE
Save & building append error

### ISSUE THREAD

**Issue by LY-Net** [nuxt/framework#5198]
### Environment

node: v16.15.0
npm: v8.5.5
vscode  ide

### Reproduction

Error in code save build & It was accidental

### Describe the bug

FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 00007FF66E197A1F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114207
 2: 00007FF66E126096 DSA_meth_get_flags+65542
 3: 00007FF66E126F4D node::OnFatalError+301
 4: 00007FF66EA45CD5 v8::V8::FromJustIsNothing+53
 5: 00007FF66E10F083 v8::base::CPU::has_sse+31507
 6: 00007FF66E1FA997 uv_timer_stop+1207
 7: 00007FF66E1F6F2B uv_async_send+331
 8: 00007FF66E1F66BC uv_loop_init+1292
 9: 00007FF66E1F685A uv_run+202
10: 00007FF66E1C56C5 node::SpinEventLoop+309
11: 00007FF66E05E740 v8::internal::wasm::SignatureMap::Freeze+35776
12: 00007FF66E059D98 v8::internal::wasm::SignatureMap::Freeze+16920
13: 00007FF66E1E6F2D uv_poll_stop+557
14: 00007FF66F000200 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
15: 00007FFCBFE97974 BaseThreadInitThunk+20
16: 00007FFCC28EA2F1 RtlUserThreadStart+33
error Command failed with exit code 134.

**Comment by danielroe** [comment]
This is a Node ESM cache error, sadly not solvable in Nuxt.

Closing in favour of https://github.com/nuxt/framework/issues/837.
