### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module _nuxt/login

### ISSUE THREAD

**Issue by dungonfq** [nuxt/framework#5199]
### Environment

npm run build

### Reproduction
https://account.roadsurfer.com/de/login?token=tHsgHh5i4kvXR0agNgx4myy2bfR
The `_nuxt` folder includes both modules after production built, but the server can't fetch them sometimes.

### Describe the bug

My app on Production is facing many issues `Failed to fetch dynamically imported module` or `403` issue. This is how Sentry log the error:

Page `login`
![sentry-error](https://user-images.githubusercontent.com/57652048/170941684-02cc883c-d852-4b75-a270-db498c5c78b1.png)

Middleware `auth` 
![sentry-error-2](https://user-images.githubusercontent.com/57652048/170942016-aac33ce3-77ae-4193-b189-b59f05ce3807.png)

Component `ModalNavBar`
![sentry-error-3](https://user-images.githubusercontent.com/57652048/170944157-9aede8e1-d86b-4f5d-9dbf-509891378cf9.png)

_**Luckily, this error doesn't break the application. My website still runs normally while Chrome's Devtool is logging the error.**_

Have anyone faced the same issue and have idea to fix it?

Thank all.

**Comment by manniL** [comment]
Does the time of the errors correlate with new deployments? If so, it could be https://github.com/nuxt/nuxt.js/issues/3389

**Comment by danielroe** [comment]
I do sometimes get:

<img width="518" alt="CleanShot 2022-05-30 at 14 27 03@2x" src="https://user-images.githubusercontent.com/28706372/170992225-d9b37dd3-ffa9-4526-9c5a-b04dbccdab64.png">

which triggers a 404 page: 

<img width="752" alt="CleanShot 2022-05-30 at 14 28 37@2x" src="https://user-images.githubusercontent.com/28706372/170992461-d555007c-8e1d-4da8-bcfa-524410240ed1.png">

How are you hosting your site? Is there any reason your static assets are behind auth?

**Comment by dungonfq** [comment]
@manniL Yes, it usually happens after new deployments

**Comment by dungonfq** [comment]
@danielroe Yes, sometime we can't get the module because of a 403 error, It redirects u to the error page (404).

I don't do the DevOp stuff so can not give u details on how we're hosting the site. In short, we're using **Jenkin** to build & deploy Production with **Docker**, and run it on a Docker image. We push the container images to an Amazon ECR repository.


**Note**: While Chrome's Devtool logs the 403 error - failed to fetch module, but the site still works normally. For example:
- I have a module called ModalNavBar (https://account.roadsurfer.com/_nuxt/ModalNavbar-0aa827f7.mjs). After loading the page, it logged an error
![error-ModalNavBar-403](https://user-images.githubusercontent.com/57652048/171087081-35b47d62-7b78-4305-99de-c10b6d4ab312.png)

- But when open the navbar (on mobile), it works normally
![navbar-mobile](https://user-images.githubusercontent.com/57652048/171087205-64f19d38-983e-4032-9584-1b1dfdbd7197.png)

**Comment by dungonfq** [comment]
Found the root cause by the rate limit of my server.

I created another issue for the solution on Nuxt side: https://github.com/nuxt/framework/issues/5260

**Comment by ziyali** [comment]
![image](https://user-images.githubusercontent.com/38575596/172008226-25388274-55d6-422c-8581-fc5de33b2538.png)

I encountered the same problem after deployment，What should I do

**Comment by dungonfq** [comment]
@ziyali 
my issue is Nuxt loads too many modules at a time. On PROD, the site fetches & prefetches > 100 requests per second which exceed our server's rate limit (100r/s). Therefore, some of my modules cannot load "Failed to fetch...".

The rate limit also happens if users access the page at the same time & send too many requests.

If u're facing the same problem u can try troubleshooting ur rate limit by turning it off. There's is nothing to do for now, we have to wait. You can keep track the solution with Nuxt here: https://github.com/nuxt/framework/issues/4475

Cheers
