### ISSUE TITLE
Dynamic Components with resolveComponent(variableName) results in Vue warning and not rendering the component

### ISSUE THREAD

**Issue by Der-Alex** [nuxt/framework#5200]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/resolvecomponent-test-r98s25?file=/app.vue

### Describe the bug

I try to create dynamic components. for reference I used this nuxt 3 documentation:
https://v3.nuxtjs.org/guide/directory-structure/components#dynamic-components

The component name that is also the filename comes from a variable. When passing that variable into the `resolveComponent` function, the component doesn't get rendered. Instead I get a vue warning: 

> [Vue warn]: Failed to resolve component: BaseBar
> If this is a native custom element, make sure to 
> exclude it from component resolution via compilerOptions.isCustomElement.

The expected behaviour would be that the component gets rendered correctly. 
When using the components name as a string directly inside the function, the component gets rendered. Only when using a variable it doesn't.

Rendering the component should still work when passing a variable into that function. A typical use case would be that you get the components name that should get rendered from a cms / api.

**Comment by danielroe** [comment]
No, it should not work. Nuxt looks for a literal string within `resolveComponent`.

**Comment by davidhellmann** [comment]
Ok this works now:

nuxt.config
```ts
...
 components: {
    "dirs": [
      {
        "path": "~/components/global",
        "global": true
      },
      "~/components"
    ]
  },

...
```


[...slug].vue
```ts
<template>
  <div>
    <template v-if="entry">
      <Component :is="renderView" :entry="entry" />
    </template>
  </div>
</template>

<script lang="ts" setup>
import {useFirstLetterUppercase} from "~/composables/useFirstLetterUppercase";

const route = useRoute()
interface IGQLQueryResponse {
  data: any,
  refresh: any
}

// Fetch Pages Data
const {
  data: {value: { entry }}
}: IGQLQueryResponse = await useAsyncData('entry', () => GqlEntry({
  uri: route.path.slice(1)
}));

const resolveDynamicComp = () => {
  const sectionHandle = useFirstLetterUppercase({text: entry.sectionHandle})
  const typeHandle = useFirstLetterUppercase({text: entry.typeHandle})
  return `Views${sectionHandle}${typeHandle}`
}

const renderView = resolveComponent(resolveDynamicComp())
</script>
```


But how can I handle it to have a fallback if the `resolveComponent` is not available. 🤔

**Comment by danielroe** [comment]
In that case you should register the dynamic components as global components: https://v3.nuxtjs.org/guide/directory-structure/components#dynamic-components.

**Comment by davidhellmann** [comment]
Yes, that works fine now. But is there a way to check if the `resolveComponent('xxx')` component exists?

**Comment by davidhellmann** [comment]
@danielroe I've solved it this way. Does anything speak against this solution? 

```ts
<template>
  <div>
    <template v-if="entry">
      <Component :is="renderView" :entry="entry" />
    </template>
  </div>
</template>

<script lang="ts" setup>
import {getCurrentInstance} from "vue";
import {useFirstLetterUppercase} from "~/composables/useFirstLetterUppercase";

const route = useRoute()
interface IGQLQueryResponse {
  data: any,
  refresh: any
}

// Fetch Pages Data
const {
  data: {value: { entry }}
}: IGQLQueryResponse = await useAsyncData('entry', () => GqlEntry({
  uri: route.path.slice(1)
}));

const resolveDynamicComp = () => {
  const instance = getCurrentInstance();
  const sectionHandle = useFirstLetterUppercase({text: entry.sectionHandle})
  const typeHandle = useFirstLetterUppercase({text: entry.typeHandle})
  const compToResolve = `Views${sectionHandle}${typeHandle}`

  return typeof instance?.appContext.components === "object" &&
  compToResolve in instance.appContext.components ? compToResolve : 'ViewsDefault'
}

const renderView = resolveComponent(resolveDynamicComp())
</script>
```

**Comment by bjcooper** [comment]
@davidhellmann, thanks for sharing that! It works for me, trying to do something very similar where I resolve a Vue component dynamically based on a backend response. Awesome!
