### ISSUE TITLE
Support for vue devtools

### ISSUE THREAD

**Issue by Lyokolux** [nuxt/framework#5201]
### Environment

Nuxt CLI v3.0.0-rc.3                                                             12:11:47
RootDir: /home/projects/nuxt-starter-5yy2bd                                      12:11:53
Nuxt project info:                                                               12:11:53

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-5yy2bd?file=app.vue

### Describe the bug

Running `nuxt dev` does not allow the vue devtools extension to work.

It has the following popup message:
>Nuxt.js + Vue.js is detected on this page.
Devtools inspection is not available because it's in production mode or explicitly disabled by the author. 

### Additional context

It does not work on the local machine and on stackblitz too.

### Logs

Here some log errors after toggling the vue tabs in the devtools:
<img width="713" alt="Bildschirmfoto 2022-05-30 um 12 14 46" src="https://user-images.githubusercontent.com/29046067/170971183-3cfecf22-9e3e-460c-958c-7f4d4c525093.png">

**Comment by manniL** [comment]
Can't reproduce issues with the starter template (Devtools version 6.1.4) ☺️ 

![grafik](https://user-images.githubusercontent.com/640208/170984123-09da5024-b92f-4e3f-abb2-4c69550a7df3.png)

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/issues/2284#issuecomment-1132160740 for some debugging steps.

**Comment by Lyokolux** [comment]
> Can't reproduce issues with the starter template nor the linked StackBlitz (Devtools version 6.1.4) ☺️
> 
> ![grafik](https://user-images.githubusercontent.com/640208/170984123-09da5024-b92f-4e3f-abb2-4c69550a7df3.png)

Ok I have the version `6.0.0.2` flagged as beta. It is then my bad,
