### ISSUE TITLE
Auto import Nitro plugins

### ISSUE THREAD

**Issue by Atinux** [nuxt/framework#5211]
Like `plugins/` but for Nitro plugins, located in `server/plugins/`.

https://nitro.unjs.io/guide/plugins.html

**Comment by BracketJohn** [comment]
FYI for future readers, the correct link to plugin documentation is: https://nitro.unjs.io/guide/advanced/plugins

**Comment by pi0** [comment]
It is already implemented in latest nitropack release.

**Comment by BracketJohn** [comment]
> It is already implemented in latest nitropack release.

I think it has not been documented in nuxt docs yet, that one can now use `server/plugins` though, right? Maybe I'm misunderstanding what has been implemented though.

**Comment by pi0** [comment]
Yes. This is a feature of nitro and documented here: https://nitro.unjs.io/guide/advanced/plugins. PR welcome to improve this page mentioning it is auto imported.

**Comment by BracketJohn** [comment]
Correct me if I'mr wrong, but in the docs you linked it actually is documented that you have to manually specify the import via:
```ts
// nitro.config.ts
import { defineNitroConfig } from 'nitropack'

export default defineNitroConfig({
  plugins: [
    '~/plugins/test'
  ]
})

```
