### ISSUE TITLE
`nuxi analyze`: Nitro server bundle stats unavailable

### ISSUE THREAD

**Issue by Atinux** [nuxt/framework#5230]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- `nuxi init nuxt3-app`
- `cd nuxt3-app`
- `yarn install`
- `npx nuxi analyze`

Open http://localhost:3000/ and click on [Nitro server bundle stats](http://localhost:3000/nitro)

### Describe the bug

```
 ERROR  [h3] ENOENT: no such file or directory, open '/Users/atinux/Downloads/ams-demo/.nuxt/stats/nitro.html'
```

![Screenshot 2022-05-31 at 20 36 34](https://user-images.githubusercontent.com/904724/171261189-d1d7376a-20fa-4f35-8813-eea3a7fed34b.png)

**Comment by billymaulana** [comment]
any updates?

**Comment by danielroe** [comment]
this was resolved in https://github.com/nuxt/framework/pull/6871.
