### ISSUE TITLE
Cannot specify PostCSS config path

### ISSUE THREAD

**Issue by ashgo-x** [nuxt/framework#5237]
### Environment

- Operating System: `macOS`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.1.7`
- Builder:          `vite`
- User Config:      `css`, `postcss`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

[nuxt.config#config](https://v3.nuxtjs.org/api/configuration/nuxt.config#config)

There is no option to specify the config path for PostCSS.

**Comment by danielroe** [comment]
Would you explain a little more about your use-case?

**Comment by ashgo-x** [comment]
@danielroe, I have to set PostCSS options in `nuxt.config.ts` currently.

Would be nice if I could have the option to seperate the PostCSS configs in `postcss.config.js`.
Just like how Vite automatically reads the `postcss.config.js`.

**Comment by pi0** [comment]
Hi @ashgo-x. After talking with @danielroe we are finally going to deprecate external config also for webpack. You can always use `nuxt.config` to add custom postcss config or manually import postcss config in top of `nuxt.config` file to provide it. 

Follow up issue to track: https://github.com/nuxt/framework/issues/5368

**Comment by ashgo-x** [comment]
Thanks!
