### ISSUE TITLE
useBase doesn't work with GET params

### ISSUE THREAD

**Issue by drewdru** [nuxt/framework#5242]
### Environment

    Operating System: Ubuntu 22.04
    Node Version: v16.15.0
    Nuxt Version: 3.0.0-rc.3
    Package Manager: yarn@1.22.18
    Builder: vite
    User Config: -
    Runtime Modules: -
    Build Modules: -

### Reproduction

https://stackblitz.com/edit/github-pfhmzf?file=server/api/posts/index.js

### Describe the bug

I got error "404 - Cannot find any route matching ?limit=1. | Nuxt" when I went to /api/posts?limit=1

### Additional context

I guess it happens here:
https://github.com/unjs/h3/blob/4723880ea0ae3e482545b9340d13d63a7cc331b8/src/handler.ts#L67

I added logs around withoutBase and got this:
before withoutBase: ```req.url = "/api/posts?limit=1"```
after withoutBase: ```req.url ="?limit=1"```
Is req.url should be ```"/?limit=1"``` after using useBase?

**Comment by danielroe** [comment]
This should be resolved in the latest h3, which you can get with `yarn upgrade nuxt` or `npm upgrade nuxt`.

Let me know if not and I'll reopen.
