### ISSUE TITLE
client data bug

### ISSUE THREAD

**Issue by lqh1008** [nuxt/framework#5248]
### Environment

macos m1 
node 16.0

### Reproduction

We found that in the setup lifecycle data.value will have a probability on the client side to return the correct, in most cases null. If you want it to be correct, for example, in an asynchronous function.

### Describe the bug

We found that in the setup lifecycle data.value will have a probability on the client side to return the correct, in most cases null. If you want it to be correct, for example, in an asynchronous function.

**Comment by danielroe** [comment]
I'm going to close this as there's not enough information here to understand the issue, and no reproduction has been provided. Please feel free to comment with a reproduction and more info and I'll happily look into it.
