### ISSUE TITLE
[windows] package import specifier "#imports" is not defined in package

### ISSUE THREAD

**Issue by BlackYuzia** [nuxt/framework#5257]
### Environment

Tested with (first) [**example**](https://github.com/nuxt/framework/tree/main/examples/routing/layouts):
```js
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3-27567768.c1f728e`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/ui@0.1.1`
- Build Modules:    `-`
```

and with custom (second) build:

```js
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `css`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### First 

You get fail if:

1. Clone or download from [**source**](https://github.com/nuxt/framework/tree/main/examples/routing/layouts).
2. npm i
3. npm run dev
4. Success! You get error!

![image](https://user-images.githubusercontent.com/25010528/171564989-7b71f8b2-7467-4087-a0ee-6b80051b23e1.png)

You get success run if:

1. Clone...
2. npm i
3. npm run build
4. npm run start
5. Success! Your application is run success (why?)

### Second

> Currently, I can't share with a code to reproduce, but trouble a bit semi with the/a first one. I try create repo with reproduce code ... a bit later.

1. npm i
2. npm run dev
3. Open any page with layout... 
4. Profit! You get error with “invalid layout”
4.1 I do the same as in [**example**](https://github.com/nuxt/framework/tree/main/examples/routing/layouts)

![image](https://user-images.githubusercontent.com/25010528/171565361-e8ef0d03-28c1-4205-afd0-28361f78ec10.png)

### Describe the bug

**When you try run app in dev mode, you get error or your layout won't work.**. In the production (npm run build & npm run start) all work's fine.

### Additional context

1. As I say, I try to make/give a repo with reproduce code for second build/code ...
2. **First** - that is a source code from example, **second** - that is my own code what I wrote. In this source I also use **vuetify** as `plugin/vuetify.ts`.

**Comment by danielroe** [comment]
For now, you can work around this with:

```diff
  import { defineNuxtConfig } from 'nuxt'
  
  export default defineNuxtConfig({
+   build:{
+     transpile: [/@vueuse\/nuxt/]
+   },
    modules: [
      '@nuxt/ui'
    ]
  })
``

The issue is that `@vueuse/nuxt` is pushing a non-normalised path to the transpile array (cc: @antfu): https://github.com/vueuse/vueuse/blob/main/packages/nuxt/index.ts#L78-L83

But Nuxt should cope with this; PR incoming shortly.
