### ISSUE TITLE
Shared state update causes hydration mismatch

### ISSUE THREAD

**Issue by dvdmlln** [nuxt/framework#5258]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-n9zprf?file=pages%2Findex.vue

### Describe the bug

Hi,

I've just stumbled over a hydration mismatch when using a shared state.
My app.vue template outputs a value from a shared state and contains a nuxt page (or any component, it doesn't matter) as well.
Updating the shared state in the script setup of the nuxt page (or component) causes a hydration mismatch.

Best regards,
David

**Comment by danielroe** [comment]
This isn't a Nuxt issue. Basically you are updating the state in your `app.vue` in a child of it - because of how SSR works, `app.vue` is _already rendered_ and can't be updated - SSR isn't 'reactive.'
