### ISSUE TITLE
Cannot set title with useHead

### ISSUE THREAD

**Issue by ashgo-x** [nuxt/framework#5259]
### Environment

- Operating System: `macOS`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.1.7`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

`~/pages/some-page.vue`

### Describe the bug
[head-management#example-usage-with-definepagemeta](https://v3.nuxtjs.org/guide/features/head-management#example-usage-with-definepagemeta)

Followed the example in the documentation, but the title is still `localhost:3000/some-page`.

### Additional context

`~/layouts/default.vue`
```vue
<script setup>
	const route = useRoute()
	useHead({
		meta: [{ name: 'og:title', content: `App Name - ${route.meta.title}` }]
	})
</script>

<template>
	<div>
		<div>default</div>
		<slot></slot>
	</div>
</template>
```

`~/pages/some-page.vue`
```vue
<script setup>
	definePageMeta({
		title: 'Some Page'
	})
</script>

<template>
	<div>some-page</div>
</template>
```

**Comment by danielroe** [comment]
You likely need to use computed within `useHead`, e.g.:

```diff
	useHead({
-		meta: [{ name: 'og:title', content: `App Name - ${route.meta.title}` }]
+		meta: [computed(() => ({ name: 'og:title', content: `App Name - ${route.meta.title}` }))]
	})
```

**Comment by ashgo-x** [comment]
I tried, it still did not work.

**Comment by ashgo-x** [comment]
@danielroe Consider reopen this? I used mounted within useHead, and did not work.

**Comment by danielroe** [comment]
Would you share your code?

**Comment by ashgo-x** [comment]
Here is the reproduction [ashgo-x/nuxt-app](https://github.com/ashgo-x/nuxt-app).

**Comment by ashgo-x** [comment]
@danielroe Here is the reproduction [ashgo-x/nuxt-app](https://github.com/ashgo-x/nuxt-app).

**Comment by bnbc** [comment]
Hello, it work for me when i add in my layout :
`useHead({
    title: `App Name- ${route.meta.title}`,  
})`

But this work fine on the first load of the page, next if you navigate on your pages, the title is not updated.
If someone have an idea ?

**Comment by danielroe** [comment]
Apologies, that was my mistake. It should be:

```vue
<script setup>
const route = useRoute();
useHead({
  meta: [
    {
      name: 'og:title',
      content: computed(() => `App Name - ${route.meta.title}`),
    },
  ],
});
</script>
```
