### ISSUE TITLE
Nuxt 3 / Vite prefetch all assets & modules while starting page

### ISSUE THREAD

**Issue by dungonfq** [nuxt/framework#5260]
### Environment

Development & Production

### Reproduction

Production
1. Visit https://account.roadsurfer.com/
2. Open Devtool => Network tabs
3. Reload the page to see all the modules, .css files was prefetched

Development:
https://stackblitz.com/edit/github-o1kjbh-8gikuu
1. Visit https://github-o1kjbh-8gikuu--3000.local.webcontainer.io/
2. Open Devtool => Network tabs
3. Reload the page to see all the modules, .css files was prefetched. It even loads lodash modules

### Describe the bug

Hi team, I'm facing the rate limit issue which cause 403 error on my server. What I discoveried is Nuxt's trying to prefetch all modules, .js, .css files at once on the first time I visit a page.

https://rp1-6114-account.sg.dev.roadsurfer.com/de/login?token=Gch3mSBpIFcscJbTIKp51JdFd4NFzlXuxJfLIAxcSsVza2TFEsA9cYeojCunAy1x

**Do we have a config in `nuxt.config.ts` to limit the loaded module OR loading module on demand only OR preven prefetching?** _Instead of fetching all modules every time visiting a page, we only need to load components, css or modules which were used  / imported in the current page only_

For example, my page Login should only load login.mjs, header.mjs, ModalNavBar.mjs, etc... But instead, Nuxt loads the files from another page too. This huge load meets our server's rate limit.

On Production:
![production](https://user-images.githubusercontent.com/57652048/171600798-a413c359-3645-4dbb-ab61-bf6b1a5d41eb.png)

On development, Nuxt even load the files from `node_modules`, `lodash`...
https://stackblitz.com/edit/github-o1kjbh-8gikuu
![production](https://user-images.githubusercontent.com/57652048/171600983-9e4c93d6-73e6-4a44-913f-9718f9791918.png)

### Additional context

https://stackoverflow.com/questions/70883763/vitejs-is-loading-the-whole-bundle-size-instead-of-the-selected-ones
https://github.com/nuxt/framework/issues/4475

Possible solution?
https://github.com/nuxt-contrib/vue-bundle-renderer/pull/30

**Comment by danielroe** [comment]
Thanks. Let's track this in #4475 👍
