### ISSUE TITLE
Cookie gets rewritten on read (using useCookie)

### ISSUE THREAD

**Issue by Lanayx** [nuxt/framework#5262]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `css`, `build`, `buildModules`, `vite`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.8`
------------------------------

### Reproduction

`useCookie("x-abc").value`

Cookie value: `{"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"}`

Make request with the following cookie (it must be valid JWT token)

### Describe the bug

Once useCookie recieves valid JWT cookie Nuxt decides to overwrite it on cookie read (and adds set-cookie header in response). If cookie value is a simple string bug is not reproduced

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by Lanayx** [comment]
@danielroe steps
1) Create clean nuxt app using guide
2) Add the following script to app.vue
```
<script setup>
const test= useCookie("x-abc").value
</script>
```
3) Using DevTools create cookie x-abc with the value above (encoded value will be `%7B%22accessToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c%22%7D`) , set Expires/Max age to some value to see that it will be reset to Session
4) Run app, explore the response header, also explore that cookie expiration date was reset
![изображение](https://user-images.githubusercontent.com/3329606/171868941-6d0bc2ae-2956-45f9-8bcf-43cb09cebb2b.png)

**Comment by codingcn** [comment]
@danielroe The expiration time of the stored object type data will be reset, and the stored string type is normal
