### ISSUE TITLE
Extends support - wrong import in server files

### ISSUE THREAD

**Issue by beyer-johannes** [nuxt/framework#5265]
### Environment

Nuxt project info:                                                                                                                                                          15:26:19

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.5`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Here's a minimal reproduction: https://github.com/beyer-johannes/nuxt3-extends-trouble

### Describe the bug

Server api endpoints from the main project can not import files from 
an other directory.

It will throw an error like:

    ERROR  Rollup error: Could not load /[ABSOLUTE_PATH]/nuxt3-extends-trouble/foo-app/server/helper/useHelloWorld:    ENOENT: no such file or directory, open '/[ABSOLUTE_PATH]/nuxt3-extends-trouble/foo-app/server/helper/useHelloWorld'

Was implemented [here](https://github.com/nuxt/framework/issues/3222)

**Comment by danielroe** [comment]
For now you will need to use relative paths rather than aliases.

It is intended behaviour that aliases like `~` and `~~` will be resolved relative to the 'root' project, though we do plan to expose named aliases that refer to individual layers: see https://github.com/nuxt/framework/issues/3222.
