### ISSUE TITLE
<NuxtChild /> is reloading parent page in Nuxt 3.

### ISSUE THREAD

**Issue by michaelpumo** [nuxt/framework#5291]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `typescript`, `modules`, `tailwindcss`
- Runtime Modules:  `@nuxtjs/supabase@0.1.16`, `@nuxtjs/tailwindcss@5.1.2`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/nuxt-3-child-routes-ony35p?file=/pages/index.vue

### Describe the bug

`<NuxtChild />` routes should not reload the parent page and lose state.

If I navigate to child 1 or child 2, the parent index page is re-rendered / loaded when it should simply load in the child and maintain its state. I believe this is the behaviour in Nuxt 2.

I have a reproduction link above but even on CodeSandbox, the script is not working for some reason. It's not 100% needed to demonstrate the bug but would make the reloading issue more apparent as the count gets reset back to zero on each navigation within the parent index (this same code works locally but there appears to be an issue on CodeSandbox regarding this).

### Additional context

This could be a bug or it could be a misunderstanding with how routes and layouts now work in Nuxt 3. Unfortunately the documentation in Nuxt 3 regarding routing is very minimal so I'm not able to see if it's this way by design and instead some misconfiguration on my part.

**Comment by danielroe** [comment]
You can control this behaviour by setting `key` in `definePageMeta`.

**Comment by michaelpumo** [comment]
> https://codesandbox.io/s/nuxt-3-child-routes-ony35p?file=/pages/index.vue

I've also tried this using `definePageMeta` and `<NuxtChild page-key="" />` to no success.

Are you able to demonstrate on the above CodeSandbox link at all?

Thank you.

**Comment by danielroe** [comment]
The issue was that `<NuxtLayout>` was the root element of your page. It needs to be wrapped in another element. We could possibly add a comment about that in the docs.

Here's your repro, with only that change made: https://github-tlz3zz--3000.local-corp.webcontainer.io/child-2

**Comment by michaelpumo** [comment]
Wow, thank you so much @danielroe - I was trying everything possible and it seems such a small change "fixed" it. Definitely worth a mention in the docs I think as it's quite a mysterious gotcha. Have a lovely day.

**Comment by danielroe** [comment]
~> https://github.com/nuxt/framework/pull/5345
