### ISSUE TITLE
scrolltotop is not ok

### ISSUE THREAD

**Issue by TangsWang** [nuxt/framework#5293]
### Environment

nuxt rc2

### Reproduction

`router: {
    scrollBehavior: (to, from, savedPosition) => {
      console.log(123123)
      return { top: 0 }
    },
  },`

### Describe the bug

config in nuxt.config.ts

`router: {
    scrollBehavior: (to, from, savedPosition) => {
      console.log(123123)
      return { top: 0 }
    },
  },`

do not exec.

**Comment by florian-lefebvre** [comment]
Scroll behavior needs to be set in a special file: https://v3.nuxtjs.org/guide/directory-structure/pages#router-options
