### ISSUE TITLE
nuxt-link

### ISSUE THREAD

**Issue by tinegaCollins** [nuxt/framework#5295]
my code keeps presenting this error message
[nuxt] [request error] Cannot destructure property 'options' of 'vue.inject(...)' as it is undefined.

i have tried everything but i still cant fix it, help.

**Comment by chris-visser** [comment]
Same here. I'm getting this error after upgrading to Nuxt 3 RC 4. It did not happen on RC 3.

**Comment by chris-visser** [comment]
I used to get this error. It is likely a mismatch in Vue version used by Nuxt under the hood vs Vue used in another package. In my case I had another version of Vue installed (part of package.json) and when I removed that one everything started working fine. 

Can you check if you have vue as dependency and try to remove it?

**Comment by tinegaCollins** [comment]
in

**Comment by tinegaCollins** [comment]
fixed this issue by reinstalling nuxt again
