### ISSUE TITLE
Nitro bundling does not seem to convert the typescript decorator.

### ISSUE THREAD

**Issue by izure1** [nuxt/framework#5299]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.3.0`
- Builder:          `vite`
- User Config:      `typescript`, `app`, `css`, `build`, `runtimeConfig`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/sleepy-mestorf-hh7edv?file=/server/utils/sequelize.ts

### Describe the bug

I apologize for my poor English and use a translator.

If the source code includes a typescript decorator, the bundling of rollup does not end.
I think it's the same issue as the https://github.com/nuxt/framework/issues/5235 post.

Here are the results of the my `nuxi dev`:

```
Vite client warmed up in 9811ms 00:02:29
Vite server warmed up in 430ms 00:02:31
Vite server built in 12457ms
```

I checked exactly where it stopped.

And the `esbuild` rollup plugin used in the `getRollupConfig` function in the `node_modules/nitropack/dist/chunks/prerender.mjs` file does not seem to process files that use typescript decorators.
And I found out that the `autoImport` plugin excluded files that are using decorators from the processing list.

One weird thing is, after the first nuxt app was created, it worked.
This issue occurred after deleting the `node_modules` folder and reinstalling all packages.

I deleted the file `node_modules`, `.vite`, `.nuxt`, `package-lock.json`, and deleted the cache using the `npm clean verify` command. Nevertheless, the problem has not been solved.

Also, after deleting the `node_modules` folder and reinstalling the package, an explicit installation of the `@nuxt/vite-builder` package was required. This was not required immediately after the app was created with the `nuxi` command.

I've prepared minimal reproduction, but I don't know how it'll work.

**Comment by djschilling** [comment]
this seems to make sense, i also use decorators for the package `typeorm` and i created the issue https://github.com/nuxt/framework/issues/5235. How can we further debug this and get it working again?

**Comment by izure1** [comment]
@djschilling I solved the problem by adding the following settings.

`npm i -D rollup-plugin-typescript2`

And in the `nuxt.config.js` file,

```
import rollupPluginTs from 'rollup-plugin-typescript2'

export default defineNuxtConfig({
  nitro: {
    rollupConfig: {
      plugins: [
        rollupPluginTs()
      ]
    }
  }
})
```

However, it would be better if the typescript decorator is supported by nuxt3 by default.

**Comment by pi0** [comment]
We use ESBuild to transform typescript files both with Vite and Nitro. Last update for decorator support: https://github.com/evanw/esbuild/issues/104#issuecomment-1100130046

I think adding rollup plugin would be the best.

**Comment by pi0** [comment]
Thanks for the followup @izure1. I've escalated this to https://github.com/nuxt/framework/issues/5371 and https://github.com/unjs/nitro/issues/273 for having an experimental flag for built-in support while ESBuild and Spec are stable.

**Comment by djschilling** [comment]
@izure1 thanks for the tip. Now its at least throwing an error.

```

 WARN  Multiple major versions of package parse5 are being externalized. Picking latest version.                                                                         16:36:33
  - /Users/david/projects/work/finder/churchtools-finder/node_modules/parse5@5.1.1
  - /Users/david/projects/work/finder/churchtools-finder/node_modules/parse5-htmlparser2-tree-adapter/node_modules/parse5@6.0.1


 ERROR  Rollup error: Could not resolve './scheduler' from ./scheduler?commonjs-external                                                                           nitro 16:36:34


 ERROR  Could not resolve './scheduler' from ./scheduler?commonjs-external                                                                                               16:36:34

  at error (node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at ModuleLoader.handleResolveId (node_modules/rollup/dist/es/shared/rollup.js:22375:24)
  at node_modules/rollup/dist/es/shared/rollup.js:22338:26
```

Did you also get this error?

**Comment by BracketJohn** [comment]
Brief update: The fix of @izure1 worked out in RC2-RC4, with RC5 it stopped working and we get [the error from above](https://github.com/nuxt/framework/issues/5299#issuecomment-1151205620) again:
```sh
start Building server...                                                                                                                                                      nitro 12:48:20

 WARN  Multiple major versions of package parse5 are being externalized. Picking latest version.                                                                                    12:48:28
  - /Users/nils/repos/clients/suez/shift-book/app/node_modules/cli-highlight/node_modules/parse5@5.1.1
  - /Users/nils/repos/clients/suez/shift-book/app/node_modules/parse5@6.0.1


 ERROR  Rollup error: Could not load /Users/nils/repos/clients/suez/shift-book/app/.nuxt/dist/server/server.mjs (imported by node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs): ENOENT: no such file or directory, open '/Users/nils/repos/clients/suez/shift-book/app/.nuxt/dist/server/server.mjs'


 ERROR  Could not load /Users/nils/repos/clients/suez/shift-book/app/.nuxt/dist/server/server.mjs (imported by node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs): ENOENT: no such file or directory, open '/Users/nils/repos/clients/suez/shift-book/app/.nuxt/dist/server/server.mjs'

```

**Comment by BracketJohn** [comment]
Ah nice, thanks for the info, that's awesome!

Anyways, regarding my report: I think then this problem is probably the same as https://github.com/nuxt/framework/issues/5899!

Sorry for the intrusion here ✋
