### ISSUE TITLE
Nuxt processes the layout twice

### ISSUE THREAD

**Issue by RihanArfan** [nuxt/framework#5301]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-is2u2e?file=pages%2Fmanage%2F[manage].vue,layouts%2Fmanage.vue

**Go to URL `/manage/1` and `/manage/2` inside the StackBlitz preview**

### Describe the bug

When a page route param's name (`[manage]`) and layout (`manage`) have the same name, the layout is specified with definePageMeta, and the slot is inside a v-for, the layout is processed twice.

Inside StackBlitz, comment out `layout: 'manage'` inside `[manage].vue` and the layout is only used once.

**Preview key**
-  Orange border is v-for
-  Blue border is slot
-  Red background is page (slot content)

**How it is:**
![image](https://user-images.githubusercontent.com/20425781/172085600-65e77b7e-6b18-47e1-bf29-9c0b559c864d.png)
![image](https://user-images.githubusercontent.com/20425781/172085626-d241a330-2308-4e41-ba12-38dcf4f82366.png)

**How it should be**
Reproduction for this is commenting out `layout: 'manage'`
![image](https://user-images.githubusercontent.com/20425781/172085648-7ba7c45a-81ac-4ff7-b9b6-c0ef97913f81.png)

**Comment by danielroe** [comment]
If you wish to use a custom layout (ie. `<NuxtLayout>` component) then you should set `layout: false` in your `definePageMeta` - see https://v3.nuxtjs.org/guide/directory-structure/layouts/#example-manual-control-with-pages.
