### ISSUE TITLE
Question: defineNuxtPlugin access old context.req

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/framework#5305]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.1.3`
- Builder:          `vite`
- User Config:      `srcDir`, `css`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction
```
import { defineNuxtPlugin } from "#app"

export default defineNuxtPlugin((nuxtApp) => {
  console.log(nuxtApp) // doesn't have context or context.req
})
```
### Describe the bug

Creating a plugin on nuxt 2 i only use
```
export default (context) => {
   console.log(context.req) //here i can access context.req
}
```

How can I get context.req if i also need to use defineNuxtPlugin((nuxtApp)) ?

Thank you for the help

**Comment by danielroe** [comment]
You can use `useRequestEvent` composable - so:

```js


export default defineNuxtPlugin((nuxtApp) => {
  const event = useRequestEvent()
})
```

**Comment by stephenjason89** [comment]
Thank you @danielroe, you are a lifesaver.

**Comment by danielroe** [comment]
Reopening to track merge of #5326.

**Comment by stephenjason89** [comment]
Hello @danielroe 
I have a nuxt3 project and i only added apollo graphql and vuetify in it.

whenever i try to use
<img width="340" alt="image" src="https://user-images.githubusercontent.com/3810177/178156116-ac774721-2fdf-4b24-9cad-56be63f406e2.png">

I can see that it is being logged in the node server console.

but at the same time, my client side throws me an error
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/3810177/178156155-6db6ad41-3733-44fc-9c90-bbdef39976d5.png">

removing that console.log(event.req) solves the problem.
I don't know what is happening, i can't use event.req.headers or anything related to the req because it breaks the client side vuetify

**Comment by danielroe** [comment]
Check if event is set before trying to read properties from it. It won't be set on client side, and this is likely the cause of your error.

**Comment by stephenjason89** [comment]
Hello @danielroe,
event is set and i can see all the information on the node console.

I have removed most of my packages to try and see what went wrong

this is what it looks like
<img width="712" alt="image" src="https://user-images.githubusercontent.com/3810177/178157039-d4e8f3d0-3cde-439a-bd4c-5feb9f0c42e2.png">

and after you uncomment line 11 and 12 of client.js
<img width="474" alt="image" src="https://user-images.githubusercontent.com/3810177/178157057-85c9881e-901e-4722-baa7-5206242c53e4.png">

then this is what it looks like
<img width="706" alt="image" src="https://user-images.githubusercontent.com/3810177/178157071-f7a38fee-8f7e-4b54-9665-2bc0fdf7e408.png">

graphql is not being executed anymore.

Here's a reproduction.
https://github.com/stephenjason89/nuxt3


Thank you so much

**Comment by danielroe** [comment]
It is certainly defined on server side, but I'm making the point that it won't be defined on client side as there is no request event there.

**Comment by stephenjason89** [comment]
Oh i'm getting your point now, 
I'm so sorry, i have overlooked this issue. :D 
As always, you are a lifesaver.
Thank you so much
