### ISSUE TITLE
dev error: (node:42372) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension. (Use `node --trace-warnings ...` to show where the warning was created)

### ISSUE THREAD

**Issue by hehehai** [nuxt/framework#5332]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.1.6`
- Builder:          `vite`
- User Config:      `modules`, `build`, `experimental`, `unocss`, `colorMode`
- Runtime Modules:  `@vueuse/nuxt@8.4.2`, `@unocss/nuxt@0.33.2`, `@pinia/nuxt@0.1.9`, `@nuxtjs/color-mode@3.0.3`, `./modules/arco`
- Build Modules:    `-`

### Reproduction

project: https://github.com/hehehai/arco-nuxt3

### Describe the bug

``` ts
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  modules: [
    '@vueuse/nuxt',
    '@unocss/nuxt',
    '@pinia/nuxt',
    '@nuxtjs/color-mode',
    ['./modules/arco', { icon: true }],
  ],
  // build
  build: {
    transpile: ['@arco-design/web-vue'],
  },
  experimental: {
    reactivityTransform: true,
    viteNode: true,
  },
  unocss: {
    preflight: true,
  },
  colorMode: {
    classSuffix: '',
  },
})
```

```vue
<script setup>
import {Message} from "@arco-design/web-vue";

Message.success("测试")
</script>
```

run `dev` then open host
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/12692552/172392850-b5256769-97c0-460f-8c37-acb7c91a80ad.png">

only `dev` show this error, `build` and `start` all success

### Additional context

ref: https://github.com/hehehai/arco-nuxt3/issues/2

**Comment by hehehai** [comment]
first open sometime ok, but refresh has error

**Comment by y-migita** [comment]
same issue

**Comment by danielroe** [comment]
This is likely an issue with a dependency: https://v3.nuxtjs.org/concepts/esm#what-are-valid-imports-in-a-nodejs-context.

See https://github.com/nuxt-community/supabase-module/issues/54#issuecomment-11696716784 for a full explanation.

**Comment by liuzycc** [comment]
【See https://github.com/nuxt-community/supabase-module/issues/54#issuecomment-11696716784 for a full explanation.】It didn't solve my problem
version: Nuxt 3.0.0-rc.6
The same error as above turned out to be a three-way dependency package problem
Discover through code debugging 
solution：
nuxt.config.js:
build: { transpile: ["xxx"] }
