### ISSUE TITLE
ignore pages not work

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/framework#5374]
### Environment

Nuxt project info:                                                                                                                                                                           22:39:31

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3-27579668.27a0084`
- Package Manager:  `pnpm@6.32.10`
- Builder:          `vite`
- User Config:      `ssr`, `ignore`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/ie2o2h?file=/nuxt.config.js

### Describe the bug

i want ignore route of  `pages/**/items/*.vue` ,
but set `ignore` don't work ,
when `yarn build` or `yarn generate` ,these routes are still accessible

**Comment by baixiaoyu2997** [comment]
hi , i not sure this is bug, so i ask here, `r4` can use ignore， but in `dev mode`,  in `ignore files` paths，like `/pages/**/items/*.vue`, when change code, there is no hot update

for now ,i change my config to `ignore: isProd ? ['pages/**/items/*.vue'] : []`

**Comment by danielroe** [comment]
Yes, that is a consequence of ignoring the files.
