### ISSUE TITLE
Detect typos in nuxt.config

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#5390]
Ref: https://github.com/nuxt/framework/issues/5294#issuecomment-1152108622_

We added support for `[key: string]: any]` in nuxt.config since 1) some modules might not have provided types and 2) making easier during module development to not have errors before stubbing

But this seems having a negative DX effect as increases chance of unnoticed typos in config file.

I think we shall try making it strict again...

**Comment by chris-visser** [comment]
Maybe we could somehow provide a way to "losen up" the config interface to ensure typechecking would not fail for libs without types. I'm not a TS guru, but maybe something like this?

```ts
declare namespace Nuxt {
    interface NuxtConfig {
        someModule: any;
    }
}
```

**Comment by bendwarn** [comment]
Vote for strict. It's pretty easy to suppress error with ts-expect-error during module development.
