### ISSUE TITLE
Setting route.meta.layout causes a flash of the default layout when server rendering

### ISSUE THREAD

**Issue by dan-hammond** [nuxt/framework#5408]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@6.14.16`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[Minimal reproduction repo](https://github.com/dan-hammond/nuxt-3-layout-flash-repro)

I tried recreating it in CodeSandbox but had issues with `route.meta.layout` working at all, it seemed to take no effect, hence the GitHub link above.

The bug can be reproduced in both development and production using the standard commands. 

Visiting the /test route will cause a small flash where the default layout is downloaded and rendered on the client before the custom layout takes over.

### Describe the bug

I would have expected setting `route.meta.layout` in `<script setup>` to have set the correct layout while server side rendering, so there's no flicker of the default layout as the page loads for the first time. 

Instead what happens is the default layout is sent to the browser and rendered, then the custom layout is downloaded and rendered. This causes a flash on screen as the correct layout is downloaded.

### Additional context

I cannot use `definePageMeta` as in my project I must be able to set the layout at run time based on the response from an API call. 

I am trying to find a v3 way of solving this issue I raised in 2020 for Nuxt 2:
https://github.com/nuxt/nuxt.js/issues/7437

**Comment by danielroe** [comment]
The issue is that on SSR, things are not reactive - the layout has already been rendered by the time the component begins to be rendered, and Vue can't go back and rewrite the HTML it's already rendered. If you need to set the layout programmatically, you should do so in a plugin or in `app.vue`.

**Comment by dan-hammond** [comment]
@danielroe Thank you for the response, that's helpful to understand. Could I please request some more advice on what I need to do in order to get this working? 

I have had a read of the documentation for Nuxt plugins and can see it primarily involves working with hooks. I'm unsure which hooks I need to use, or how I tie those in with the wider solution I'm trying to make.

Essentially what I want to do is the same as I outlined in the issue for Nuxt 2, linked [here](https://github.com/nuxt/nuxt.js/issues/7437). There's a lot more detail in that issue, but here's a summary:

- I want to create a Nuxt module which allows developers to create a new top level folder next to `/pages`, which we'll call `/templates`.

- When a user visits the site, I want to make an API call to my CMS to fetch any content associated with that URL. 

- Based on the CMS response, I want to load a matching component from `/templates`, passing in the response data (the content) as a prop, and setting the layout + transition for that template. 

- Essentially the components in `/templates` work exactly like pages, but without the routing, as that has been decided by the CMS.

- I need this functionality as the CMS I use is extremely flexible about what content exists at a given URL, and CMS users can (and do) change things without developer intervention. I can't create rigid routes in my `/pages` folder for anything content driven for this reason. 

- I wouldn't mind retaining the `/pages` routing as well, preferring a route that's defined in `/pages` if found. There may be no `/pages` folder though, if it's a small site that's entirely CMS driven.

I've tried tackling this problem many ways, primarily in Nuxt 2, but haven't found anything that really works. 

My latest attempt, associated with this bug report, was to copy a bit of what Nuxt Content is doing. I created a `[...slug].vue` page which has a `<TemplateRenderer>` component. The `<TemplateRenderer>` is responsible for making the API call and doing a `<component :is>` based on the response. I wanted to set the layout and transition in the `<TemplateRenderer>` component. This is where I hit the stumbling block. 

Is what I'm describing achievable at all? What's the right way to go about implementing it, please?

**Comment by danielroe** [comment]
@dan-hammond That's very achievable and there are several ways of doing it, probably best through middleware as it's per route. If I get a chance, I'll create a stackblitz to show how it might work. You could also open a discussion or post in the Nuxt Discord.

**Comment by dan-hammond** [comment]
@danielroe Thank you, that's very reassuring. I'd definitely appreciate a Stackblitz if you do get the opportunity. I'll create a discussion for it shortly, as I wouldn't want it to be lost in the noise of the Discord channel. Thanks again.
