### ISSUE TITLE
dev server hangs indefinitely with css in nuxt.config.ts

### ISSUE THREAD

**Issue by jiblett1000** [nuxt/framework#5414]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.3-27581242.8831e4a`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `typescript`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jiblett1000/inter-test

### Describe the bug

`yarn build` works fine but the dev server hangs indefinitely when importing css files in `nuxt.config.ts`. Removing the css import from the config fixes the dev server hang.

**Comment by danielroe** [comment]
@jiblett1000 Does this still occur with the latest nuxt edge release? I think it might also have been resolved by https://github.com/nuxt/framework/pull/5409.

**Comment by jiblett1000** [comment]
@danielroe yep, still happening for me with 3.0.0-rc.3-27581242.8831e4a

**Comment by jiblett1000** [comment]
@danielroe @pi0 Works great now. Thanks!
