### ISSUE TITLE
Confusing error of router and onMounted in component

### ISSUE THREAD

**Issue by rowdy-dowdy** [nuxt/framework#5415]
### Environment

Operating System: `Window 11`
Node Version: `v16.15.0`
Nuxt Version: `3.0.0-rc.3`

### Reproduction

project: [https://github.com/rowdy-dowdy/nuxt-learn](https://github.com/rowdy-dowdy/nuxt-learn)

### Describe the bug

1. The generated id code is not the same

This is my code

![image](https://user-images.githubusercontent.com/33823245/173177216-50905912-d3cb-4ac5-9f33-564427911f80.png)

But the result id of element and id in onmounted are different

![image](https://user-images.githubusercontent.com/33823245/173176979-6a574fec-ea17-4056-a99e-1718d575b767.png)

2. I use this component on 2 pages. but the second time they appear, the content in onmounted seems to be run before rendering the component.

> The reason is when I put settimeout 1s in onmounted it works. But that's not how I want it

> Even the icon is error while using only css. :))

Here is my code

![image](https://user-images.githubusercontent.com/33823245/173177628-ab6b61bd-de58-4501-a57e-544eaf6cc98a.png)

While running

https://user-images.githubusercontent.com/33823245/173177724-e3be12af-92df-4a10-ae90-53943dca8929.mp4

I'm just new to nuxt and vue. I cannot understand what is happening. Help me

**Comment by danielroe** [comment]
This looks like the same issue as https://github.com/nuxt/framework/issues/3587. Let's track there. (You can work around it by disabling transitions.)
