### ISSUE TITLE
Dynamic Components with resolveComponent results in Vue warning and not rendering the component

### ISSUE THREAD

**Issue by m7rlin** [nuxt/framework#5419]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@6.14.16`
- Builder:          `vite`
- User Config:      `css`, `meta`, `modules`, `buildModules`, `formkit`, `typescript`, `build`, `vueuse`, `nitro`, `runtimeConfig`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.8`, `()`
- Build Modules:    `@vueuse/nuxt@8.5.0`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-1ubaok-atppgx

### Describe the bug

resolveComponent: if the component name is too long it won't resolve the component

It is working with normal import and with shorter names (e.g. HeaderSimple).

### Additional context

```js
<script setup>
// Working
// import HeaderBrandedBackgroundImage from '../header/HeaderBrandedBackgroundImage.vue'

// Not working
const HeaderBrandedBackgroundImage = resolveComponent(
    'HeaderBrandedBackgroundImage',
)

// console.log(HeaderBrandedBackgroundImage)
</script>
```

**Comment by edgarsn** [comment]
I guess it should be:

`resolveComponent('HeaderHeaderBrandedBackgroundImage')`

**Comment by m7rlin** [comment]
> I guess it should be:
> 
> `resolveComponent('HeaderHeaderBrandedBackgroundImage')`

No, this is not working. If the component is in e.g. "header" folder nuxt will automatically add it to the Components name.
