### ISSUE TITLE
Favicon.ico seems to ignores app.cdnURL when set

### ISSUE THREAD

**Issue by DRoet** [nuxt/framework#5425]
### Environment

S3 buckets + cloudfront / AWS-lambda, build using Nuxt `v3.0.0-rc.3`

### Reproduction

Use custom cdnURL for production:

```ts
export default defineNuxtConfig({
  nitro: {
    preset: 'aws-lambda'
  },
  app: {
    cdnURL: 'https://cdn.website.com/'
  }
})
```

### Describe the bug

The client tries to load the favicon using the regular baseURL:
`https://lambda.website.com/favicon.ico`

Instead of using the cdnURL:
`https://cdn.website.com/favicon.ico`

### Additional context

I serve my static `public` folder using S3 buckets / cloudfront and the `server` folder using AWS-lambda.

**Comment by danielroe** [comment]
That is your browser making the request, and is not Nuxt's behaviour.

**Comment by DRoet** [comment]
@danielroe oh right I totally forgot about that, thanks for pointing me towards the right direction.

I tried adding the link manually to my `app.head` config, but is there a way to reference the dynamic path inside my href?

for example:
```js
app: {
  head: {
    link: [
      // I want this to become: https://cdn.website.com/favicon.ico
      { rel: 'icon', type: 'image/x-icon', href: '~/favicon.ico' }
    ]
  },
  cdnURL: 'https://cdn.website.com/'
}
```

Or will I have to hardcode the CDN path for every link?

**Comment by danielroe** [comment]
@DRoet Try setting it in a Nuxt server plugin.

**Comment by bros4president** [comment]
Hi @DRoet!

Did you manage to make this work?

I'm struggling right now with this issue since I have pages of the form pages/[foo].vue that cause problems when no favicon.ico is available at /favicon.ico. Nuxt's router will try to render a page with [foo].vue, so I need to tell the browser where to request the icon.

Thanks in advance :)!

**Comment by DRoet** [comment]
@bros4president yeah I ended up writing a small plugin using useHead() + useRuntimeConfig():

```ts
export default defineNuxtPlugin(() => {
  const config = useRuntimeConfig()
  return useHead({
    link: [
      { rel: 'icon', type: 'image/x-icon', href: `${config.app.cdnURL}/favicon.ico` }
    ]
  })
})
```
