### ISSUE TITLE
hang when building app with `¿`

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#5435]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.1.0`
- Nuxt Version:     `3.0.0-rc.3-27584539.9d28c0a`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `css`, `buildModules`, `vite`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.1.9`

### Reproduction

I don't know what is failing.

npm run build
```
➜  nuxt-project git:(main) ✗ npm run build

> build
> nuxi build

Nuxt CLI v3.0.0-rc.3-27584539.9d28c0a                                                                      10:16:45
ℹ Vite client warmed up in 7876ms                                                                          10:16:55
ℹ Client built in 9936ms                                                                                   10:16:57
ℹ Building server...
(It freezes)
```

npm run dev
```
Nuxt CLI v3.0.0-rc.3-27584539.9d28c0a                                                                      10:21:32
                                                                                                           10:21:32
  > Local:    http://localhost:3000/ 

ℹ Vite server warmed up in 295ms                                                                           10:21:40
ℹ Vite client warmed up in 5325ms
(It freezes)
```

### Describe the bug

Nuxt never loads since I updated to the version mentioned above. The log is frozen and does not load.

**Comment by pi0** [comment]
Do you mind to make a reproduction sandbox? 🙏🏼

**Comment by frbuceta** [comment]
> Do you mind to make a reproduction sandbox? 🙏🏼

I didn't reproduce it because I didn't know what was wrong. But I have detected the piece of code that makes nuxt fail.
```html
<div class="text-sm">
  <a href="#" class="font-medium text-blue-600 hover:text-blue-500"> ¿Olvidaste tu contraseña? </a>
</div>
```

It looks like it's the first question because if I remove it, it works.

```diff
<div class="text-sm">
  <a href="#" class="font-medium text-blue-600 hover:text-blue-500">
-    ¿Olvidaste tu contraseña?
+    Olvidaste tu contraseña?
  </a>
</div>
```

**Comment by danielroe** [comment]
@frbuceta I can't reproduce that. Would you be able to reproduce via https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?

**Comment by ram-you** [comment]
I confirm the issue. It seems that nuxt (v3.0.0-rc4) compiler does not accept special character, ® in my case.

**Comment by pi0** [comment]
Thanks for the report and confirmation. It seems a regression from a dependency of Nuxt. Please try pinning `unimport` to `0.2.5` using `package.json`:

(npm)

```js
{
  "overrides": {
    "unimport": "0.2.5"
  }
}
```

(pnpm)

```js
  "pnpm": {
    "overrides": {
      "unimport": "0.2.5"
    }
  }
```

(yarn)
```js
  "resolutions": {
    "unimport": "0.2.5"
  },
```

**Comment by vanling** [comment]
> Thanks for the report and confirmation. It seems a regression from a dependency of Nuxt. Please try pinning `unimport` to `0.2.5` using `package.json`:

🙌  This fixed it for me. _Will have to check where I have used ant special characters._
