### ISSUE TITLE
Incoherent behaviour of build --static

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/framework#5452]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `ssr`, `typescript`, `hooks`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Just initialize a starter nuxt 3 project and see the section below.

### Describe the bug

By executing `npx nuxi generate` we have:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/740025/173440969-dcdf84b5-b1cf-4714-8327-59fa652637bd.png">

While by executing `yarn build --static` we get: 
<img width="943" alt="image" src="https://user-images.githubusercontent.com/740025/173441199-679b028c-be74-4e4b-811d-418cd3925ea9.png">

### Additional context

For completeness, the scripts I currently have in my `package.json`:
```json
...
  "scripts": {
    "dev": "nuxi dev",
    "build": "nuxi build",
    "build --static": "npx nuxi generate",
    "start": "node .output/server/index.mjs"
  },
...
```

**Comment by danielroe** [comment]
Try renaming your `build --static` script to `build:static`. Spaces in script names are not supported.

```diff
    "dev": "nuxi dev",
    "build": "nuxi build",
-   "build --static": "npx nuxi generate",
+   "build:static": "nuxi generate",
    "start": "node .output/server/index.mjs"
```
