### ISSUE TITLE
[ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"

### ISSUE THREAD

**Issue by doantu05150** [nuxt/framework#5453]
### Environment

node: 16.15.1 (I've tried 16.14.2)
npm: 8.11.0

Nuxt version:
"nuxt": "3.0.0-rc.3",
"@nuxtjs/composition-api": "^0.32.0",

### Reproduction

Here is my minimal demo: https://codesandbox.io/s/busy-ride-0r9df8?file=/components/Button.vue
All my dependencies on package.json
Notice on Button.vue component and app.vue file. My project just have only two these files but I'm getting error `503 Server Unavailable`

<img width="797" alt="Screen Shot 2022-06-14 at 07 42 28" src="https://user-images.githubusercontent.com/29808554/173470030-ba0642da-2f3d-4465-98e6-ef06d0ff1e00.png">

### Describe the bug

```
✘ [ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
    node_modules/@nuxtjs/composition-api/dist/runtime/index.mjs:1:7:
      1 │ import Vue from 'vue';
        ╵        ~~~

✘ [ERROR] No matching export in "node_modules/nuxt/dist/app/compat/capi.mjs" for import "default"
```

<img width="1504" alt="Screen Shot 2022-06-13 at 23 26 42" src="https://user-images.githubusercontent.com/29808554/173400439-5390effc-567d-417b-9c37-038df04c8106.png">

Can someone explain to me why I'm getting this bug?

### Updated
I clean my code and add the button

**Comment by doantu05150** [comment]
Does Nuxt3 + Vite not ready for production?

**Comment by danielroe** [comment]
`@nuxtjs/composition-api` is not compatible with Nuxt 3 - you do not need it in Nuxt 3.

**Comment by doantu05150** [comment]
thank you

**Comment by Caesy707** [comment]
Are all these module import problems due to incompatibility?

**Comment by danielroe** [comment]
I'm not sure what you mean. But yes, this issue was caused by trying to use Vue 2 library in a Vue 3 project. If you are experiencing another issue, please open a new issue with a reproduction and I might be able to help more specifically.

**Comment by Caesy707** [comment]
Is it compatible with vue3 or vite? I have a confusing question. 
No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"

**Comment by danielroe** [comment]
Nuxt 3 is compatible with Vue 3 and Vite - that's what it uses. Your error indicates you are trying to use some other library that is not compatible with Vue 3.
