### ISSUE TITLE
Identifier 'xxx' has already been declared after upgrade to RC-4

### ISSUE THREAD

**Issue by misaon** [nuxt/framework#5454]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@3.2.1`
- Builder:          `vite`
- User Config:      `modules`, `oxyshopNuxt`
- Runtime Modules:  `normalizedModule()`, `normalizedModule()`
- Build Modules:    `-`
------------------------------

### Reproduction

Upgrade from RC-3 to RC-4 and try build

### Describe the bug

https://github.com/nuxt/framework/discussions/5445#discussioncomment-2941788

![image](https://user-images.githubusercontent.com/15806356/173523269-176729ee-b5c3-4263-ba0d-fe983315eff1.png)

### Logs

```shell
start Building server...                                                                                                                                                                                                

 WARN  rollup-plugin-inject: failed to parse /home/misaon/PhpStormProjects/nextgen-go/src/client/.nuxt/dist/server/server.mjs. Consider restricting the plugin to particular files via options.include

 ERROR  Rollup error: Identifier 'useRuntimeConfig' has already been declared (Note that you need plugins to import files that are not JavaScript)                                                                      

 ERROR  Identifier 'useRuntimeConfig' has already been declared (Note that you need plugins to import files that are not JavaScript)                                                                                          

  at error (node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (node_modules/rollup/dist/es/shared/rollup.js:12422:16)
  at Module.tryParse (node_modules/rollup/dist/es/shared/rollup.js:12799:25)
  at Module.setSource (node_modules/rollup/dist/es/shared/rollup.js:12704:24)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/rollup.js:22178:20)
```

**Comment by lyykfi** [comment]
The same problem

**Comment by msonowal** [comment]
confirmed

**Comment by msonowal** [comment]
duplicate https://github.com/nuxt/framework/issues/5450

**Comment by KahrLu** [comment]
today I met the same error, What's more strange is that I have been using the RC1 version so far without any change, but this error occurred suddenly today.
This error will not be reported when I build locally, but only when I build in docker onlive.
![image](https://user-images.githubusercontent.com/76502123/173529318-96299921-5eb8-4654-89a6-0961c72ca41f.png)
