### ISSUE TITLE
nested NuxtPage not rendering

### ISSUE THREAD

**Issue by NidMo** [nuxt/framework#5457]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.0.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `plugins`, `meta`, `build`, `buildModules`, `pageTransition`, `vueuse`, `strapi`, `i18n`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.4.2`, `@nuxtjs/tailwindcss@5.1.2`, `@pinia/nuxt@0.1.9`, `@nuxtjs/strapi@1.4.0`, `@nuxtjs/i18n@8.0.0-alpha.0`
------------------------------

### Reproduction

1. nested nuxtpage
2. The innermost nuxtpage uses useAsyncData

### Describe the bug

the innermost page will not be rendered in the node environment

**Comment by danielroe** [comment]
Would you provide a reproduction?
