### ISSUE TITLE
vue-router doesn't work when in dev mode

### ISSUE THREAD

**Issue by terranboy** [nuxt/framework#5470]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `modules`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.1.2`
- Build Modules:    `-`

### Reproduction

N/A

### Describe the bug

when in `npm run dev` ,  use `<NuxtLink>` render a link , then clicked the link, the whole page refreshed.
when after  `npm run bulid`, then started the server, the vue-router worked fine.

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by terranboy** [comment]
This issue is something about hmr didn't  run correctly. It is likely resolved in [#1113](https://github.com/nuxt/framework/issues/1113)
Please close this issue. Thank you.
