### ISSUE TITLE
Route Middleware does not get triggered if its defined inside layout 

### ISSUE THREAD

**Issue by ilijanovic** [nuxt/framework#5501]
### Environment

- Package Manager:  `npm@8.9.0`
- Builder:          `vite`
- User Config:      `modules`, `ssr`, `vite`, `plugins`, `css`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.1.2`, `@pinia/nuxt@0.1.9`
- Build Modules:    `-`
------------------------------

### Reproduction

StackBlitz URL: https://stackblitz.com/edit/github-ghahvp?file=middleware/testmid.ts

### Describe the bug

middlewares are working for pages, but not for layouts see stackblitz.

```
definePageMeta({
     middleware: ["somelayout"]
})
```

If you use this code inside an page, it works. But if you use it inside an layout, and an page uses that layout it does not get triggered. This functionality actually works in Nuxt2

### Additional context

My intention was:

I have 2 layouts:
     - Default (no auth)
     - Dashboard (with auth)

In nuxt 2 i was able to put my middleware inside of the dashboard layout. Whenever i made a new page for the dashboard, i just added `layout: "dashboard"` and the dashboard CSS with the authentication middleware got applied.

**Comment by danielroe** [comment]
`definePageMeta` only applies to pages, not to layouts.

**Comment by lobo-tuerto** [comment]
Is there a plan to support middleware inside layouts?

**Comment by lobo-tuerto** [comment]
Or what's the recommended way to protect like 20-30 pages that need auth middleware ---I also have like 10-20 public pages--- besides adding the following to every protected page?

```ts
<script setup lang="ts">
definePageMeta({
  middleware: 'is-authenticated',
})
</script>
```

**Comment by danielroe** [comment]
@lobo-tuerto You can define the middleware in a parent page, for example.

```bash
admin.vue <-- set here
admin/index.vue <-- applies here
admin/[slug].vue <-- and here
```

**Comment by lobo-tuerto** [comment]
@danielroe Thanks for the prompt reply. Yes that's one strategy, but I was wondering how to go about that for top level directory pages (without nesting). :thinking:

**Comment by VeselyJan92** [comment]
@lobo-tuerto 

I have used plugin:

```
export default defineNuxtPlugin(({$pinia})=>{
  const router = useRouter()
  
  router.afterEach((to, from) => {
    const internal = useInternalStore($pinia)
    internal.menuOpened = false
  })
})
```

However, in nuxt 2 it was possible to define middleware on layout.

> Middleware lets you define custom functions that can be run before rendering either a page or a group of pages (layout).
https://nuxtjs.org/docs/directory-structure/middleware
