### ISSUE TITLE
Component from module doesn't render for static generated site

### ISSUE THREAD

**Issue by thepragmaticprogrammer1** [nuxt/framework#5507]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `typescript`, `ssr`, `css`, `modules`, `plugins`, `runtimeConfig`, `cookies`, `nitro`
- Runtime Modules:  `@pinia/nuxt@0.1.9`, `../modules/nuxt-cookie-control`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/smartmelonsystems/nuxt3-ssg-example

### Describe the bug

I know static site generation is not stable yet, but thought i would put this example into the mix.....

I have a custom module (for cookie consent purposes) and have included that in my application.
Inside the module is a component (`<CookieControl />`). This is used inside a common layout. (layouts/new-default.vue)
Everything functions using dev tools. But after static site generation and running the static site.
The component from the module is not rendered, just an empty `<div>`
If I move the component from the module to the components dir of the application. It does then render, but there are still issues, such as reactivity doesn't work.

### Additional context
This appears to be related to the use of &lt;ClientOnly&gt;. If I remove that tag, the component is rendered.
However this is a target: static, ssr: false website. So ClientOnly shouldn't make any difference i.e. the content inside ClientOnly should be rendered for a static generated site - correct?

_No response_

**Comment by danielroe** [comment]
What was the issue? How did you resolve this?

**Comment by thepragmaticprogrammer1** [comment]
@danielroe - thanks for the interest.
I have this as a mono repo whilst i was coding the module. The module was directly included into the main Nuxt 3 app just pathing in the modules:[] section e.g. "mymodule":"../modules/mytestmodule"
For running dev this all works. But building the main app as a static site, everything breaks.
However building the module as a node package and npm installing it into the main app, both dev and static versions work correctly.
So something behaves differently for modules when locally referenced vs npm installed, is all can say.
