### ISSUE TITLE
css files are being loaded as script module in dev with `ssr: false` (webpack)

### ISSUE THREAD

**Issue by gsmeira** [nuxt/framework#5508]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `builder`, `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- `npx nuxi init nuxt-app`
- `cd nuxt-app`
- `yarn add -D @nuxt/webpack-builder`
- add to `nuxt.config.js`: `builder: 'webpack'` / `ssr: false`
- `yarn dev`

### Describe the bug

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css"
```

I tested using vite and works fine, but when I set the builder to webpack all css files are being loaded as an script module.

![Screenshot from 2022-06-17 15-18-49](https://user-images.githubusercontent.com/1690400/174355770-87d67bd7-bada-4d5b-b4c0-c61b02c514b8.png)
![Screenshot from 2022-06-17 15-18-36](https://user-images.githubusercontent.com/1690400/174355780-e3892bd6-bdda-4ada-81b1-36466d44edd0.png)

**Comment by bachilli** [comment]
Same here.

When I open my browser at http://localhost:3000/, this happen:

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by BurakGur** [comment]
Same issue but i use vite

**Comment by bachilli** [comment]
Any updates about this issue?

**Comment by danielroe** [comment]
reproduction: https://stackblitz.com/edit/github-bu3umw.

**Comment by chengzhuo5** [comment]
这个问题后面还有进展吗

**Comment by mannok** [comment]
same here. Will it be fixed?
