### ISSUE TITLE
`Object.defineProperty called on non-object`

### ISSUE THREAD

**Issue by amery** [nuxt/framework#5516]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `pnpm@7.2.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

create a fresh project and open it on a browser
```sh
pnpx nuxt@rc init nuxt-app
cd nuxt-app/
pnpm install --shamefully-hoist
pnpm dev -o
```
and open http://localhost:3000/

### Describe the bug

```
Nuxt CLI v3.0.0-rc.4

  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.32.128:3000/
  > Network:  http://172.17.0.1:3000/

ℹ Vite client warmed up in 746ms
ℹ Vite server warmed up in 153ms
✔ Vite server built in 1223ms
✔ Nitro built in 298 ms
[nuxt] [request error] Object.defineProperty called on non-object
  at Function.defineProperty (<anonymous>)  
  at $id_a7972da4 (./.nuxt/dist/server/server.mjs:129:8)  
  at __instantiateModule__ (./.nuxt/dist/server/server.mjs:20116:9)  
  at __ssrLoadModule__ (./.nuxt/dist/server/server.mjs:20054:25)  
  at ssrImport (./.nuxt/dist/server/server.mjs:20079:13)  
  at $id_fe0c645f (./.nuxt/dist/server/server.mjs:17:37)  
  at __instantiateModule__ (./.nuxt/dist/server/server.mjs:20116:9)  
  at __ssrLoadModule__ (./.nuxt/dist/server/server.mjs:20054:25)  
  at ./.nuxt/dist/server/server.mjs:20131:22  
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
```

the offending line is
```ts
Object.defineProperty(exports, '__esModule', { value: true });
```

### Additional context

skeleton project pushed to https://gitlab.com/mnemoc/nuxt3-pnpm-issue-5516

**Comment by amery** [comment]
exact same happens when using a fresh `pnpm` store btw.
```sh
pnpm install --shamefully-hoist --store=$PWD/.fresh-pnpm-store
```

**Comment by danielroe** [comment]
I can't reproduce with the repo, a fresh install, or a fresh store. Can you provide me any more info?

**Comment by amery** [comment]
@danielroe uhm. I tried on gitpod and it worked fine :-/ https://gitpod.io/#https://gitlab.com/mnemoc/nuxt3-pnpm-issue-5516

any suggestion on how to troubleshoot this locally?

**Comment by amery** [comment]
my laptop and build container are:
```
OS: Ubuntu 22.04 LTS
nvm version: v16.15.1
```
I just made some deep cleanup

```
$ rm -rf ~/.nvm ~/.npm ~/.local/*/pnpm
$ sudo rm -rf /usr/local/lib/node_modules
$ git clean -dfx
$ npm version
{
  npm: '8.5.1',
  node: '12.22.9',
  v8: '7.8.279.23-node.56',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '72',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '2.1.4',
  http_parser: '2.9.4',
  openssl: '1.1.1m',
  cldr: '40.0',
  icu: '70.1',
  tz: '2022a',
  unicode: '14.0'
}
$ nvm version
system
```
and start over:
```
$ nvm install 16
Now using node v16.15.1 (npm v8.11.0)
$ nvm version
v16.15.1
$ npm i -g npm
$ npm i -g pnpm
$ pnpm i --shamefully-hoist
$ pnpm dev -o
...
Nuxt CLI v3.0.0-rc.4

  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.32.128:3000/

ℹ Vite server warmed up in 532ms
ℹ Vite client warmed up in 1161ms
✔ Vite server built in 1360ms
✔ Nitro built in 470 ms
[nuxt] [request error] Object.defineProperty called on non-object
  at Function.defineProperty (<anonymous>)  
  at $id_b79b7992 (./.nuxt/dist/server/server.mjs:127:8)  
  at __instantiateModule__ (./.nuxt/dist/server/server.mjs:10064:9)  
  at __ssrLoadModule__ (./.nuxt/dist/server/server.mjs:10002:25)  
  at ssrImport (./.nuxt/dist/server/server.mjs:10027:13)  
  at $id_7dbdb4dc (./.nuxt/dist/server/server.mjs:17:37)  
  at __instantiateModule__ (./.nuxt/dist/server/server.mjs:10064:9)  
  at __ssrLoadModule__ (./.nuxt/dist/server/server.mjs:10002:25)  
  at ./.nuxt/dist/server/server.mjs:10079:22  
  at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
```

@danielroe any idea?

**Comment by amery** [comment]
workspace attached just in case
[5516.tar.gz](https://github.com/nuxt/framework/files/8934395/5516.tar.gz)

**Comment by BracketJohn** [comment]
I had the same error when defining transpile functions like so:
```ts
    transpile: [
      // @ts-expect-error fucntion signature is not exported but only documented
      ({ isDev }) => !isDev && 'dayjs',
      // @ts-expect-error fucntion signature is not exported but only documented
      ({ isDev }) => !isDev && 'lodash',
    ],
```

Leading to:
```
[nuxt] [request error] Object.defineProperty called on non-object
  at Function.defineProperty (<anonymous>)  
  at $id_60f0615f (./.nuxt/dist/server/server.mjs:1338:8)  
  at __instantiateModule__ (./.nuxt/dist/server/server.mjs:172482:9)  
  at __ssrLoadModule__ (./.nuxt/dist/server/server.mjs:172420:25)  
  at ssrImport (./.nuxt/dist/server/server.mjs:172445:13)  
  at $id_9a53e296 (./.nuxt/dist/server/server.mjs:17:37)  
  at __instantiateModule__ (./.nuxt/dist/server/server.mjs:172482:9)  
  at __ssrLoadModule__ (./.nuxt/dist/server/server.mjs:172420:25)  
  at ./.nuxt/dist/server/server.mjs:172497:22  
  at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
```

Probably due to the `undefined` return of `transpile` when `isDev = true`?

**Comment by shtse8** [comment]
I have the same issue when I am transpilling `graphql`.
After removing `graphql` in transpile, everything works fine.

**Comment by kasvith** [comment]
Im also getting this with transpiling

**Comment by danielroe** [comment]
I think this should no longer be the case as we now use `vite-node` as the default devBundler. If you are still experiencing this, please feel free to provide a reproduction and I will reopen.

**Comment by Akm-mt** [comment]
I have same issue with nuxt-3.0.0 no problem when i run 'nuxt dev' but when i run 'nuxt generate'  no ssr  i have this error.

`entry.3fe19eac.js:1 Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at VT (entry.3fe19eac.js:1:622474)
    at kN (entry.3fe19eac.js:1:649242)
    at entry.3fe19eac.js:1:452187`

This my nuxt.config.ts
`export default defineNuxtConfig({
  ssr: false,
  app: {
    head: {
      title: 'AKMT',
      charset: 'utf-16',
      viewport: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover",
      link: [
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Cairo&display=swap', crossorigin: '' }
      ],
    },
  },
  modules: ["@pinia/nuxt",
    '@pinia-plugin-persistedstate/nuxt',
    ['@nuxtjs/i18n',
      {
        vueI18nLoader: true,
        vueI18n: {
          legacy: false,
          locale: 'en',
          messages: {
            en: enUs,
            fr: frFr
          },
          datetimeFormats: datetimeFormats,
          fallbackLocale: 'en',
          globalInjection: true,
        },
        customRoutes: false,
        strategy: 'no_prefix',
        locales: [
          {
            code: 'en',
            file: 'en.json',
            iso: 'en-US'
          },
          {
            code: 'fr',
            file: 'fr.json',
            iso: 'fr-FR'
          }
        ],
        lazy: true,
        langDir: 'lang',
        defaultLocale: 'en'
      },
    ],
  ],
  vite: {
    resolve: {
      alias: {
        './runtimeConfig': './runtimeConfig.browser'
      }
    },
    define: {
      'window.global': {}
    },
    build: {
      minify: "terser",
      terserOptions: {
        compress: {
          defaults: true,
          drop_console: true // <-- This is what you want
        },
        mangle: {
          eval: true,
          module: true,
          toplevel: true,
          safari10: true,
          properties: false
        },
        output: {
          comments: false
        }
      }
    }
  },
  css: ["~/assets/css/tailwind.css", "~/assets/css/style.scss"],
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  alias: {
    "@aws-amplify/core": "@aws-amplify/core/lib",
    "@aws-amplify/auth": "@aws-amplify/auth/lib",
    // "./runtimeConfig": "./runtimeConfig.browser",
  },
  // router: {
  //   middleware: ["use-at-global"],
  // },
});`

**Comment by Akm-mt** [comment]
I have same issue with nuxt-3.0.0 no problem when i run 'nuxt dev' but when i run 'nuxt generate' no ssr i have this error.

```
entry.3fe19eac.js:1 Uncaught TypeError: Object.defineProperty called on non-object 
at Function.defineProperty (<anonymous>) 
at VT (entry.3fe19eac.js:1:622474) 
at kN (entry.3fe19eac.js:1:649242) at entry.3fe19eac.js:1:452187

```
This my nuxt.config.ts

```
export default defineNuxtConfig({
  ssr: false,
  app: {
    head: {
      title: 'AKMT',
      charset: 'utf-16',
      viewport: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover",
      link: [
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Cairo&display=swap', crossorigin: '' }
      ],
    },
  },
  modules: ["@pinia/nuxt",
    '@pinia-plugin-persistedstate/nuxt',
    ['@nuxtjs/i18n',
      {
        vueI18nLoader: true,
        vueI18n: {
          legacy: false,
          locale: 'en',
          messages: {
            en: enUs,
            fr: frFr
          },
          datetimeFormats: datetimeFormats,
          fallbackLocale: 'en',
          globalInjection: true,
        },
        customRoutes: false,
        strategy: 'no_prefix',
        locales: [
          {
            code: 'en',
            file: 'en.json',
            iso: 'en-US'
          },
          {
            code: 'fr',
            file: 'fr.json',
            iso: 'fr-FR'
          }
        ],
        lazy: true,
        langDir: 'lang',
        defaultLocale: 'en'
      },
    ],
  ],
  vite: {
    resolve: {
      alias: {
        './runtimeConfig': './runtimeConfig.browser'
      }
    },
    define: {
      'window.global': {}
    },
    build: {
      minify: "terser",
      terserOptions: {
        compress: {
          defaults: true,
          drop_console: true // <-- This is what you want
        },
        mangle: {
          eval: true,
          module: true,
          toplevel: true,
          safari10: true,
          properties: false
        },
        output: {
          comments: false
        }
      }
    }
  },
  css: ["~/assets/css/tailwind.css", "~/assets/css/style.scss"],
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  alias: {
    "@aws-amplify/core": "@aws-amplify/core/lib",
    "@aws-amplify/auth": "@aws-amplify/auth/lib",
    // "./runtimeConfig": "./runtimeConfig.browser",
  },
});;
```
