### ISSUE TITLE
Extending h3 app via nitro plugin isn't working

### ISSUE THREAD

**Issue by walmartwarlord** [nuxt/framework#5527]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `pnpm@7.3.0`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Create a fresh nuxt 3 app
2. Create a plugin somewhere 
3. Import it in `nuxt.config.ts`

```ts
// ~/server/nitro/plugin.ts
import { createRouter } from 'h3'

const router = createRouter()
 .get('/api/hello', () => `Hello world!`)

export default (nitroApp) => {
  nitroApp.h3App.use(router)
};
```

```ts
export default defineNuxtConfig({
  nitro: {
    plugins: ['~/server/nitro/plugin.ts']
  }
})
```

```bash
[Vue Router warn]: No match found for location with path "/api/hello"
```

### Describe the bug

Nitro plugin don't recognize custom route

**Comment by danielroe** [comment]
The issue here is that the route is being registered, but below the catchall route.

This would be a workaround:

```js
import { createRouter } from 'h3'

const router = createRouter()
  .get('/api/hello', () => 'Hello world!')

export default (nitroApp) => {
  nitroApp.h3App.stack.unshift({ route: '/', ...router })
}
```

Perhaps we could use a Nitro plugin to inject the vue renderer for Nuxt to ensure it's injected last - wdyt @pi0?

**Comment by pi0** [comment]
We might expose `router` as well to the `nitroApp` context to allow registering custom dynamic routes. Shifting/Pushing to the middleware stack is probably not the best idea.

**Comment by danielroe** [comment]
When the next version of nitropack is released, you should be able to upgrade with `yarn upgrade nuxt` or `npm upgrade nuxt` and change your code to:

```js
export default (nitroApp) => {
  nitroApp.router.use('/api/hello', () => 'Hello world!')
}
```

**Comment by danielroe** [comment]
This should be resolved in the latest nitropack, which you can get with `yarn upgrade nuxt` or `npm upgrade nuxt`.

Let me know if not and I'll reopen.
