### ISSUE TITLE
PostCSS does not work when running through vite.

### ISSUE THREAD

**Issue by SebbeJohansson** [nuxt/framework#5532]
### Environment

Nuxt project info:                                                                                                                                          13:02:30  

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `telemetry`, `ssr`, `target`, `generate`, `app`, `css`, `modules`, `storyblok`, `build`
- Runtime Modules:  `@storyblok/nuxt@4.0.1`
- Build Modules:    `-`
------------------------------

### Reproduction

- Create a new empty project.
- Add styling to something that should be processed by postcss.
- Check that the styling has not been processed.

Minimal reproduction:
https://stackblitz.com/edit/nuxt-starter-ws9vqv?file=nuxt.config.ts
The only changes from a clean project is:
- Changed the postcss config to have a custom overrideBrowserslist that would result in modified CSS on flex.
- Created styling on <html> that should result in a CSS that has prefixed flex styling.

### Describe the bug

For my project I have a certain set of config for postcss that would result in the styling that I expect. Key things in my config is a "overrideBrowserslist" and 'postcss-custom-media' plugin for custom media queries.
Postcss doesn't seem to be running at all.

### Additional context

Branch for my custom project that has this issue:
https://github.com/SebbeJohansson/sebbejohansson-front/tree/features/nuxt3-storyblok

**Comment by danielroe** [comment]
You configure `postcss` with a top-level `postcss` key in your config: https://v3.nuxtjs.org/api/configuration/nuxt.config#postcss. Like this: https://stackblitz.com/edit/nuxt-starter-bvebel.

**Comment by SebbeJohansson** [comment]
Okay, interesting. I went with the suggestion that came up from intellisense in vscode, but I now see that its from webpack.
