### ISSUE TITLE
weird behavior with vite-node

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/framework#5543]
### Environment

Nuxt project info:                                                                                                        03:29:29

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `components`, `experimental`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/v45ojk?file=/pages/index.vue:98-109

switch `viteNode` will see different

### Describe the bug

enable `vite-node` then style lost, I think the problem is caused by `y-button` code comments :
```
<!-- <y-button disabled dark block></y-button> -->
```

when i delete this comments ,will works
but disabled vite-node ,don't need delete this comments also works

### Additional context

蹲一个婷婷

**Comment by danielroe** [comment]
cc: @antfu
