### ISSUE TITLE
_unref not defined on build

### ISSUE THREAD

**Issue by StevenJPx2** [nuxt/framework#5546]
### Environment

Nuxt CLI v3.0.0-rc.4
RootDir: /Users/stevenjohn/Documents/Projects/SAFT/website-v2
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.1.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `buildModules`, `vite`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.7.4`
------------------------------

### Reproduction

[Minimal reproduction](https://stackblitz.com/edit/github-yzejmv?file=app.vue)

### Describe the bug

When a value from a composable is used in a `v-bind` in CSS, it fails in previewing the build, giving the error `_unref is not defined`. 

## Glue fix for people who are facing this issue
Just add this to the top of your `vue` file wherever you have this use-case:
```vue
<script setup>
import {unref as _unref} from 'vue';

// ...
</script>
```

## What I've found
In `server.mjs`: it is resolving the composable `ref` value using `_unref` instead of using `vue_cjs_prod.unref`. When I did that to the build file, it ran with no issue.

**Comment by danielroe** [comment]
cc: @antfu

**Comment by antfu** [comment]
Weird your repro works fine on my side
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/11247099/174758702-0606285e-52fa-41d3-9136-3f71aa61c8bd.png">

**Comment by StevenJPx2** [comment]
It will work on dev, and I'm stackblitz it still works fine in build, but you do get the error message saying that `unref is not defined`. When I hosted it on Netlify and also tried running it locally, it kept crashing the entire website.

**Comment by DamianGlowala** [comment]
I have also discovered a weird behavior, might be related to this (ignore underlined ESLint-related `v-model` warnings).

When I run `npm run build` with the following indentation of lines 207-209, this is the error that gets shown:

![image](https://user-images.githubusercontent.com/48835293/174765340-1a310909-cbcb-4640-adea-de3e46554d86.png)

On contrary, when I manually revert what ESLint formatted to the same line, the error isn't shown anymore :)

...that is: `v-model:number-of-items-per-page="numberOfItemsPerPage"`

**Comment by cainaf** [comment]
i get exactly the same error when using v-bind is css from a composable value... oddly enough it happens only in a couple files where others (also using v-bind from a composable value) the error does not occur

it happens only when running after a build. dev is fine.

@StevenJPx2 suggestion of importing `import {unref as _unref} from 'vue';` did solve the problem

**Comment by antfu** [comment]
This is a Vue bug, close as duplicated for https://github.com/nuxt/framework/issues/6567#issuecomment-1217544634
