### ISSUE TITLE
How does Nuxt2 upgrade to NUXT3?

### ISSUE THREAD

**Issue by bianliuzhu** [nuxt/framework#5556]
### Environment

➜  nuxt-app-v3 npx nuxi info
Nuxt CLI v3.0.0-rc.4                                                                   14:35:13
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

NUXT2 updates the NUXT3 guide

### Describe the bug

NUXT2 updates the NUXT3 guide

### Additional context

NUXT2 updates the NUXT3 guide

### Logs

```shell
NUXT2 updates the NUXT3 guide
```

**Comment by danielroe** [comment]
https://v3.nuxtjs.org/migration/overview/
