### ISSUE TITLE
tree-shake client-only components and composables

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#5559]
At the moment, slots passed to client-only components are still rendered in SSR, which means they are also still included in the bundle and this leads to the strange behaviour that wrapping a component that's incompatible with SSR in `<ClientOnly>` doesn't actually fix anything for users.

This is also true when dynamically importing a library in `onMounted`; the chunk will still be generated in the server bundle.

We can utilise an unplugin to enable tree-shaking on client-only components + client-only composables like `onMounted` and `onBeforeUnmount`, as well as dev-only composables and server-only composables.

**Comment by Al-Planet** [comment]
can you show me how?

**Comment by Al-Planet** [comment]
its working as ssr on client side
