### ISSUE TITLE
[Nuxt build error] builder:webpack

### ISSUE THREAD

**Issue by liuzycc** [nuxt/framework#5566]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.4`
- Builder:          `webpack`
- User Config:      `builder`, `css`, `typescript`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Have you met anyone

### Describe the bug

default builder vite is ok

### Additional context

package:
"dependencies": { "@nuxt/webpack-builder": "3.0.0-rc.4", }

### Logs

```shell
Nuxt CLI v3.0.0-rc.4 20:43:12

ERROR Nuxt build error 20:43:19

at compile (node_modules/@nuxt/webpack-builder/dist/index.mjs:1056:19)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async bundle (node_modules/@nuxt/webpack-builder/dist/index.mjs:988:5)
at async build (node_modules/nuxt/dist/index.mjs:1650:5)
at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:41:5)
at async _main (node_modules/nuxi/dist/cli.mjs:46:20)

error Command failed with exit code 1.
```

**Comment by ffxsam** [comment]
@danielroe I took my app which was not building via webpack* and kept culling chunks of code until the test repo worked.

Turns out the inclusion of SCSS is what's causing it, at least for me:

### app.vue
```vue
<script setup lang="ts">
import './src/styles/main.css';
import './src/styles/vuetify-custom.scss';
</script>

<template>
  <div>Hello</div>
</template>
```

I'm guessing there's no sass loader for webpack, but I'm not really sure how to set that up in `nuxt.config.ts`. `webpack.rules` is not a thing.

Here's the repo: https://github.com/ffxsam/repro-nuxt-webpack

**Comment by ffxsam** [comment]
@liuzycc I solved this for myself.

Make sure you've done the following:

1. Install `sass-loader` as a dev dependency.
2. If you use path aliases (e.g. `import { thing } from '@/utils'`), you'll need to add this to `nuxt.config.ts`:

```ts
import path from 'path';
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
  alias: {
    '@': path.resolve(__dirname, './src'),
  },
});
```

**Comment by danielroe** [comment]
You should not need to add that alias as Nuxt adds it for you assuming you have set `srcDir` in your config.

**Comment by weihongyu12** [comment]
If you use `npm` to install dependencies, a compilation error will occur. Using `yarn` will not cause webpack compilation errors
