### ISSUE TITLE
runtimeConfig behavior is strange at build time

### ISSUE THREAD

**Issue by sumiren** [nuxt/framework#5567]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `typescript`, `css`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/sumiren/nuxt3rc-issue-reproduction

* npm install
* npm run reproduce-issue:intuitive-but-not-works
  * you can reproduce the issue.
* npm run reproduce-issue:intuitive-but-not-works
  * you can understand the issue more.

#### Context

As you will see [this page](https://v3.nuxtjs.org/migration/runtime-config#runtime-config), 
you configure runtime config as follwoing.
```
export default defineNuxtConfig({
  runtimeConfig: {
    secretKey: '', // variable that can only be accessed on the server side
    public: {
      BAR: process.env.BAR || 'DEFAULT' // variable that can also be accessed on the client side
    }
  },
})
```

This example implicitly explains that when you'd like to override BAR, you can do it like following.
`export BAR=xxx`

And, this works at least at development server(nuxt dev).

#### Problem

However, at build time, `export BAR=xxx` does not work.
When specifying environment variable as above and running built server,  BAR is configured as `DEFAULT`(assuming the aforementioned runtimeConfig).

#### Detail

I read post-build code, which `nuxt build` emitted, and found following code snippet in `.output/server/chunks/nitro/node-server.mjs`.

```
...

import { snakeCase } from 'scule/dist/index.js';
import destr from 'destr';

const _runtimeConfig = {"app":{"baseURL":"/","buildAssetsDir":"/_nuxt/","cdnURL":""},"nitro":{"routes":{},"envPrefix":"NUXT_"},"public":{"BAR":"BAR"},"FOO":"FOO"};
const ENV_PREFIX = "NITRO_";
const ENV_PREFIX_ALT = _runtimeConfig.nitro.envPrefix ?? process.env.NITRO_ENV_PREFIX ?? "_";
const getEnv = (key) => {
  const envKey = snakeCase(key).toUpperCase();
  return destr(process.env[ENV_PREFIX + envKey] ?? process.env[ENV_PREFIX_ALT + envKey]);
};
function isObject(input) {
  return typeof input === "object" && !Array.isArray(input);
}
function overrideConfig(obj, parentKey = "") {
  for (const key in obj) {
    const subKey = parentKey ? `${parentKey}_${key}` : key;
    const envValue = getEnv(subKey);
    if (isObject(obj[key])) {
      if (isObject(envValue)) {
        obj[key] = { ...obj[key], ...envValue };
      }
      overrideConfig(obj[key], subKey);
    } else {
      obj[key] = envValue ?? obj[key];
    }
  }
}
overrideConfig(_runtimeConfig);
```

Looking at the above code, I found that it works when I specified environment variables as following.
```
NITRO_PUBLIC_BAR=SPECIFIED
```

About private config, specification like following works.
```
NITRO_FOO=SPECIFIED
```

#### Why this is problem

Following code misleads that you should specify environment variable as `export BAR=xxx`.
```
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      BAR: process.env.BAR || 'DEFAULT' // variable that can also be accessed on the client side
    }
  },
})
```

At least, it's problem that the way you specify environment variables is different between development and production environments.

#### Additional Information

I found this problem when specifying aws-lambda preset.
So this problem is not limited to node-server.

**Comment by danielroe** [comment]
The prefixing behaviour is by design and is specified in https://v3.nuxtjs.org/guide/features/runtime-config. A PR to improve the docs would be welcome.

**Comment by sumiren** [comment]
@danielroe 
Thanks for your response!

Actually I migrated from nuxt3 to nuxt:3.0.0-rc, so I read following page.
https://v3.nuxtjs.org/migration/runtime-config#runtime-config

So, are `Migration` and `Example` sections not required?
