### ISSUE TITLE
Client side not working

### ISSUE THREAD

**Issue by chemist-repo** [nuxt/framework#5587]
### Environment

Nuxt CLI v3.0.0-rc.4                                                      16:22:50
RootDir: /sandbox                                                         16:22:53
Nuxt project info:                                                        16:22:53

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new          16:22:53

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

https://codesandbox.io/s/long-paper-o4fx3f?file=/app.vue

### Describe the bug

On click, the ref should change, but this does not happen. Other client events don't work either.

**Comment by danielroe** [comment]
I think codesandbox is currently broken for Nuxt 3 as the Vite HMR cannot connect. Here's a stackblitz working fine: https://stackblitz.com/edit/github-ki1er5?file=app.vue.
