### ISSUE TITLE
[ERROR] Cannot read properties of undefined (reading 'vueApp')

### ISSUE THREAD

**Issue by angelhdzmultimedia** [nuxt/framework#5589]
### Environment

Nuxt CLI v3.0.0-rc.4

### Reproduction

I used a reproduction repo on Stackblitz but had others issues, and it was nuxt-vite's fault, so I removed it , and then started a new project locally in VSCode.

### Describe the bug

I'm trying to add Quasar to Nuxt 3 project. At first, I installed nuxt-vite, so I can add Quasar as a Vite Plugin as I normally do, but nuxt-vite seems to not be working with Nuxt 3.

So I removed any trace of Vite and nuxt-vite and @quasar/vite-plugin and started fresh.

Followed Nuxt 3 guide to add plugins, to figure out a way of adding Quasar myself directly into Nuxt 3, but I'm getting an error with the `nuxtApp `parameter of the callback function passed to `defineNuxtConfig`:

### nuxt.config.ts

```ts
import { defineNuxtConfig } from 'nuxt' //@3.0.0-rc.4
import {Quasar} from 'quasar' //@2.7.3

export default defineNuxtConfig((nuxtApp) => {
   
    
 nuxtApp.vueApp.use(Quasar, {config: {}})
 
  return {
    components: true,
  }
 
 })
```

### Error
` ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'vueApp') `

### Final Words
I'm new to Nuxt and I just want to try it with Vite and Quasar. Any solution will be appreciated.

**Comment by danielroe** [comment]
The issue you're getting is that you are  mixing up Nuxt plugins & your Nuxt config file.

Here's an example of how it could be done: https://stackblitz.com/edit/github-9gw5h9

But note that I've made the plugin client-only - you'll probably need to follow some other steps to ensure that it works on SSR.

**Comment by angelhdzmultimedia** [comment]
> The issue you're getting is that you are mixing up Nuxt plugins & your Nuxt config file.
> 
> Here's an example of how it could be done: https://stackblitz.com/edit/github-9gw5h9
> 
> But note that I've made the plugin client-only - you'll probably need to follow some other steps to ensure that it works on SSR.

Thanks for your time and information.

Quasar already works on Vite with the @quasar/vite-plugin.
That's why I'm trying it on Nuxt. It should work out of the box by installing it as a quasar plugin. But I get a "window is not defined" error...

**Comment by angelhdzmultimedia** [comment]
### Solved

I spent a lot of time and energy trying to solve this basic task.
Until a kind soul, gave me the solution.

All I needed to do was rename the custom plugin quasar.ts to quasar.client.ts, as it's a plugin to be loaded only in the frontend.

So if somone else is struggling to add Quasar to Nuxt 3 RC, these are the steps:

1. Create a plugins folder
2. Create a quasar.client.ts file.
3. Inside quasar.client.ts, add the following code:
```ts
import { NuxtApp, defineNuxtPlugin } from 'nuxt/app';
// Quasar extras
import '@quasar/extras/roboto-font/roboto-font.css';
import '@quasar/extras/material-icons/material-icons.css';
import '@quasar/extras/fontawesome-v6/fontawesome-v6.css';
import { Quasar } from 'quasar';
// Quasar style
import 'quasar/dist/quasar.css';

export default defineNuxtPlugin((nuxtApp: NuxtApp): unknown => {
  nuxtApp.vueApp.use(Quasar, { config: {} });

  return {};
});
```
