### ISSUE TITLE
provide can only be used inside setup, with swiper.js

### ISSUE THREAD

**Issue by leosin** [nuxt/framework#5592]
### Environment

Nuxt CLI v3.0.0-rc.4
RootDir: /home/projects/github-1o6cga
Nuxt project info: 
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-1o6cga?file=app.vue

### Describe the bug

I use swiperJS in nuxt3 rc4
No errors reported in development mode

But when running under the server after build, an warn is reported

```
[Vue warn]: provide() can only be used inside setup().

[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

[Vue warn]: onBeforeUpdate is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

[Vue warn]: onUpdated is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

[Vue warn]: onBeforeUnmount is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

```

![image](https://user-images.githubusercontent.com/3676670/175482807-05334d1c-e319-4fa1-a5d9-1fbc85900b8b.png)

**Comment by leosin** [comment]
Can this be used only under client-only?

with `<client-only>` there is no warn reported

**Comment by vanling** [comment]
If SwiperJS is not working with SSR (for example if its using window/browser functions) then it will only work with clientonly

**Comment by Sitronik** [comment]
I have this same bug when using this module https://github.com/mengxiong10/vue-datepicker-next, but I have this bug in nuxt mode ```ssr: false```
I was able to find out that this has something to do with ```@vue/runtime-core```
If install nuxt - ```npm:nuxt3@3.0.0-rc.4-27588443.cf25525``` it will pull up the version ```@vue/runtime-core - 3.2.37``` and the vue-datepicker-next module will not work with it and will be exactly same console output as @leosin 

But if I install version - ```npm:nuxt3@3.0.0-rc.3-27545866.cd37a21``` everything works and there is no this output in the console, since the version of the module is installed ```@vue/runtime-core - 3.2.36```

**Comment by Sitronik** [comment]
> We can track in #4084. For now, you will need to add any dependencies that are importing `vue` into your `build.transpile` array.

Thank you, I added my dependency ```vue-datepicker-next``` to ```build.transpile``` and everything works correctly
