### ISSUE TITLE
Adding  local java script libraries causing the error : "Uncaught SyntaxError: Cannot use import statement outside a module (at XXXX.js:1:1)"

### ISSUE THREAD

**Issue by kkurt** [nuxt/framework#5594]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.13.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

It can be reproduced at stackblitz.
Project: https://stackblitz.com/edit/nuxt-starter-ac6eer

### Describe the bug

When adding local js libraries via useHead(), a line  always being added like "import { h } from XXXX" as first line in that library at the client. 

> useHead({ 
>   script: [                      
>         { src:"assets/js/owl.carousel.min.js", type: "text/javascript"},                
>         { src:"assets/js/custom.js", type: "text/javascript"}                        
>       ]    
> });
Than error occures at console:
> Uncaught SyntaxError: Cannot use import statement outside a module (at jquery.magnific-popup.min.js:1:1)

**Comment by joemcbroom** [comment]
I'm curious why don't you just import them normally?

**Comment by kkurt** [comment]
> I'm curious why don't you just import them normally?

How normally? Including "script" tag? Nuxt does not alow to use default way ... You can try it.

**Comment by danielroe** [comment]
You should put any assets you wish to import in this way in your `~/public` directory so they will not be included in your build: https://stackblitz.com/edit/nuxt-starter-t72fjf.
