### ISSUE TITLE
useNuxtApp is not defined

### ISSUE THREAD

**Issue by syqaaa** [nuxt/framework#5595]
### Environment

Node Version: v16.14.2
Nuxt Version: v3.0.0-rc.1

### Reproduction

/composables/usePages.js

const { $config } = useNuxtApp();
console.log($config);
export default function usePages() {}

### Describe the bug

>>npm run dev

ReferenceError: useNuxtApp is not defined
    at file:///.../composables/usePages.js:1:21
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24

**Comment by syqaaa** [comment]
@vanling Thanks very much. It works, so does useNuxtApp, but I still don't understand why it doesn't work outside the function...

**Comment by danielroe** [comment]
It is a composable, so it can't be run in ambient JS context - it needs to be run within a plugin, route middleware or setup function.
