### ISSUE TITLE
Nuxt Dev Port

### ISSUE THREAD

**Issue by lperez22** [nuxt/framework#5596]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `alias`, `nitro`, `build`, `meta`, `css`, `vite`, `vue`, `hooks`, `components`, `privateRuntimeConfig`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                         08:31:26

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

https://codesandbox.io/s/bold-varahamihira-c9jtsr?file=/package.json

### Describe the bug

In the release candidate branch my local dev no longer respects ports that are under 4 digits, if I try to use port 60 or 600 nuxt dev defaults to port 3000, if I choose port 6000 than nuxt uses the port I specified. This issue is only dev, when run build and start my ports work fine I'm able to specify port 60.

In the reproduction link in CodeSandbox open a new terminal and run npm run dev.

**Comment by pi0** [comment]
Hi @lperez22. Ports below 1024 (like `80`) can be only opened by **root** user and when nuxi dev cli cannot access the port, it falls back to the default (3000, 3001

You have to run as a root user using `sudo su` and `PORT=80 yarn dev` if want to use port 80. Alternatively, you can set a firewall rule to DNAT requests from port 80 to 3000:

```sh
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 3000
````

Nuxt (using get-port-please) also disallows a list of known and unstafe to listen ports for HTTP server. You can see the list here: https://github.com/unjs/get-port-please/blob/main/src/unsafe-ports.ts

--- --- 


<img width="392" alt="image" src="https://user-images.githubusercontent.com/5158436/175925969-8e184988-7e59-4ad6-aa44-897bf5043ace.png">

**Comment by danielroe** [comment]
I believe this is now resolved with the latest `listhen`, which you can get with `yarn upgrade nuxt` or `npm upgrade nuxt`.

Let me know if not and I'll reopen.

**Comment by danielroe** [comment]
(My mistake - won't be resolved until next RC.)

**Comment by danielroe** [comment]
now resolved in https://github.com/nuxt/framework/pull/6434.
