### ISSUE TITLE
Can't create new nuxi module

### ISSUE THREAD

**Issue by vencho-mdp** [nuxt/framework#5606]
### Environment

```
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
```

### Reproduction

Run ```npx nuxi init -t module my-module```

### Describe the bug

This logs in the console: ``` ERROR  Invalid template name: module   ```

**Comment by JulianMar** [comment]
hey, which version of nuxi are you using?
Can you try `npx nuxi --help`?

**Comment by danielroe** [comment]
Try using `npx nuxi@latest ` as npx can cache older versions of commands.
