### ISSUE TITLE
watch route.query works  but it's value doesn't be updated

### ISSUE THREAD

**Issue by terranboy** [nuxt/framework#5614]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `modules`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.1.3`, `@pinia/nuxt@0.1.9`
- Build Modules:    `-`

### Reproduction

[https://stackblitz.com/edit/github-b9vcmu?file=pages/index.vue](https://stackblitz.com/edit/github-b9vcmu?file=pages/index.vue)

### Describe the bug

when go to `?page=3` watch route.query works, but the value doesn't be updated, it's still 1. So the refresh() can't work correctly.

**Comment by Aynh** [comment]
You got a reactivity loss there since you reassign the value of `route.query.page` into `page` variable. `page` variable here won't get updated.

```javascript
const page = route.query.page ?? 1;
```

In order to retain reactivity, you need to use `computed ref` on the `page` variable like so.

```diff
-const page = route.query.page ?? 1;
+const page = computed(() => route.query.page ?? 1);
```

Keep in mind that you also need to use `.value` whenever you're using a `computed ref` on `<script>`.

```diff
const { data: news, refresh } = useFetch(
- `https://jsonplaceholder.typicode.com/posts?page=${page}`
+ `https://jsonplaceholder.typicode.com/posts?page=${page.value}`
);
-console.log(page);
+console.log(page.value);
watch(
  () => route.query,
- () => console.log(page)
+ () => console.log(page.value)
);
```

**Comment by terranboy** [comment]
Thanks @Aynh , follow your steps, `console.log` can output correct page 3, but `refresh()` still request `page=1`

**Comment by Aynh** [comment]
As seen [here](https://v3.nuxtjs.org/guide/features/data-fetching#refreshing-data), I think you might need to wrap the url in a function like this.

```diff
const { data: news, refresh } = useFetch(
- `https://jsonplaceholder.typicode.com/posts?page=${page.value}`
+ () => `https://jsonplaceholder.typicode.com/posts?page=${page.value}`
);
```

**Comment by terranboy** [comment]
Thank you @Aynh. Please close this issue.
