### ISSUE TITLE
useAsyncData refresh unexpectedly when using Route Params values in the fetch url

### ISSUE THREAD

**Issue by odai-alali** [nuxt/framework#5615]
### Environment

Nuxt CLI v3.0.0-rc.4                                                                                 18:04:38
RootDir: /home/projects/github-nrxzh8                                                                18:04:40
Nuxt project info:                                                                                   18:04:40

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-nrxzh8?file=pages/dog/[breed].vue

* run dev
* click on Show Dog, route `/dog/bouvier` will be loaded and a random image from API will be displayed.
* Click on the button **chihuahua** (nothing happens)
* Click on **germanshepherd** and  an image of chihuahua will be displayed (from the previews request)

It seems that the data from `useAsyncData` is not updating correctly

### Describe the bug

When using `useAsyncData` with a `route.param` value, the behavior of refresh is not as expected to be. 

 

### Additional context

I haven't seen the same behavior when the url in `useAsyncData` contains only values from `route.query`

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/4855.
