### ISSUE TITLE
when adding the module, request error in `nuxi dev`

### ISSUE THREAD

**Issue by kazupon** [nuxt/framework#5618]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-alpha.0-27596800.2df94e2`
- Build Modules:    `-`
------------------------------

### Reproduction

The reproduction repo link is here:
https://github.com/kazupon/nuxt3-repro-with-nuxt-i18n-1

### Describe the bug

When we add the `nuxtjs/i18n` and start dev server with `nuxi dev`, we get the below error:

```
[nuxt] [request error] Object.defineProperty called on non-object
  at Function.defineProperty (<anonymous>)
  at $id_60f0615f (./.nuxt/dist/server/server.mjs:128:8)
  at __instantiateModule__ (./.nuxt/dist/server/server.mjs:18499:9)
  at __ssrLoadModule__ (./.nuxt/dist/server/server.mjs:18437:25)
  at ssrImport (./.nuxt/dist/server/server.mjs:18462:13)
  at $id_2f80843d (./.nuxt/dist/server/server.mjs:17:37)
  at __instantiateModule__ (./.nuxt/dist/server/server.mjs:18499:9)
  at __ssrLoadModule__ (./.nuxt/dist/server/server.mjs:18437:25)
  at ./.nuxt/dist/server/server.mjs:18514:22
  at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
```

### Additional context

the below is partial of generate code in server.mjs (from stack error `$id_60f0615f (./.nuxt/dist/server/server.mjs:128:8)`)

```js
const $id_60f0615f = async function (global, module, exports, __vite_ssr_exports__, __vite_ssr_import_meta__, __vite_ssr_import__, __vite_ssr_dynamic_import__, __vite_ssr_exportAll__) {
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var compilerDom = require('@vue/compiler-dom');
var runtimeDom = require('@vue/runtime-dom');
var shared = require('@vue/shared');

function _interopNamespace(e) {
  if (e && e.__esModule) return e;
  var n = Object.create(null);
  if (e) {
    Object.keys(e).forEach(function (k) {
      n[k] = e[k];
    });
  }
  n['default'] = e;
  return Object.freeze(n);
}

var runtimeDom__namespace = /*#__PURE__*/_interopNamespace(runtimeDom);

...
```

When I start up the vite development server with `nuxi dev`, it seems to have bundled vue.cjs.js.

The following is server.mjs without `nuxtjs/i18n` added as a module:

```js
const $id_60f0615f = (global, module, _, exports, importMeta, ssrImport, ssrDynamicImport, ssrExportAll) =>
import("file:///path/to/nuxt3/node_modules/vue/dist/vue.cjs.js")
  .then(r => {
    if (r.default && r.default.__esModule)
      r = r.default
    exports.default = r.default
    ssrExportAll(r)
  })
  .catch(e => {
    console.error(e)
    throw new Error("[vite dev] Error loading external \"/path/to/nuxt3/node_modules/vue/dist/vue.cjs.js\".")
  })
```

**Comment by danielroe** [comment]
This doesn't seem to be reproducible with the repository above on the latest nuxt rc.

[Stackblitz](https://stackblitz.com/edit/github-rwklof?file=package.json).

Let me know if it's still occurring for you and I'll reopen.
