### ISSUE TITLE
[nuxi generate] nuxt is generating wrong content on manifest file 

### ISSUE THREAD

**Issue by jamaluddinrumi** [nuxt/framework#5642]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `tailwindcss`, `modules`, `pwa`, `buildModules`, `storyblok`, `build`
- Runtime Modules:  `@kevinmarrec/nuxt-pwa@0.3.1`
- Build Modules:    `@nuxtjs/tailwindcss@5.1.3`, `@vueuse/nuxt@8.7.5`, `@nuxtjs/partytown@1.2.1`, `@storyblok/nuxt@4.0.1`
------------------------------

### Reproduction

https://github.com/jamaluddinrumi/getanah.v3

### Describe the bug

both in local & live, when i do `nuxi generate`, manifest file is generating wrong content.

however, manifest file content is fine when i do `nuxi build`.

i'm looking the content inside of manifest file, it's shown below

![Screen Shot 2022-06-28 at 2 32 48 PM](https://user-images.githubusercontent.com/446780/176121088-0e841740-54ad-4147-aa77-217175a08859.png)

and devtools returning error as shown below 

![devtools](https://user-images.githubusercontent.com/446780/176121033-d29d34cf-ed84-467a-bc06-88929f92400a.png)

and i tried to run with `nuxt generate` it shows an error when `Initializing prerenderer` 

![Artboard](https://user-images.githubusercontent.com/446780/176150492-8eecb2ba-cb12-45a0-ab54-b4359c35b8b7.png)

### Logs

```shell
cat manifest.21161d7d.json

{"url":"/manifest.21161d7d.json","statusCode":404,"statusMessage":"Page not found: /manifest.21161d7d.json","message":"Page not found: /manifest.21161d7d.json","description":""}
```

**Comment by danielroe** [comment]
Closing in favour of https://github.com/kevinmarrec/nuxt-pwa-module/issues/7.
