### ISSUE TITLE
on SSG: useFetch called the API on route change instead of using pre-saved data

### ISSUE THREAD

**Issue by ilyasmez** [nuxt/framework#5644]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-immkf3?file=pages/[[name]].vue

- Run `npm run generate && npm run preview`.
- Open the Network tab in DevTools.
- Click on a link (e.g. `Sara`).
- You'll see that a request is has been sent to the API again, and the user has to wait for this data to be fetched again.

### Describe the bug

`useFetch` and `useAsyncData` call the API again when the site is statically generated. But they shouldn't.
When the user changes the page, the data should be retrieved from the statically generated pages instead of calling the external API again.

### Additional context

Next.js for instance, uses the data that was generated on build, and doesn't call the API again at runtime (on SSG mode).

**Comment by ilyasmez** [comment]
Perfect! Thank you @manniL. Looking forward to the full support.

**Comment by max5432112345** [comment]
> We'll need proper education on that one @manniL. I have some plans coming up overall in the upcoming weeks/months. green_heart I'll probably make a YouTube series on various glossary terms, like `SSG`, `SSR`, `ISR`, `full static`, `[X] hydration` etc...

no need articles or video, need functional :)
