### ISSUE TITLE
`Uncaught (in promise) SyntaxError: import not found: default` When import @googlemaps/markerclusterer

### ISSUE THREAD

**Issue by chaule97** [nuxt/framework#5645]
### Environment

Nuxt project info:                                                                                                                               18:12:09

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `modules`, `head`, `css`, `build`, `intlify`, `vite`, `runtimeConfig`, `hooks`, `components`
- Runtime Modules:  `@pinia/nuxt@0.1.9`, `@intlify/nuxt3@0.2.1`
- Build Modules:    `-`
------------------------------

### Reproduction

cannot import library `@googlemaps/markerclusterer`

### Describe the bug

When I write `import { MarkerClusterer } from "@googlemaps/markerclusterer";` then browser show error:

`Uncaught (in promise) SyntaxError: import not found: default [index.esm.js:2:7]`

the bug in the line of code: `import equal from '/_nuxt/node_modules/fast-deep-equal/index.js?v=fafab82c';`

**Comment by danielroe** [comment]
This isn't a Nuxt issue. You can find out a bit more at https://v3.nuxtjs.org/concepts/esm#what-are-valid-imports-in-a-nodejs-context.

You can try experimenting with `vite.optimizeDeps` and see if that resolves things for you: https://vitejs.dev/config/#dep-optimization-options. You can also try adding the affected dependency tree to your `build.transpile`.
