### ISSUE TITLE
Dev server won't start with @apply rule in style block

### ISSUE THREAD

**Issue by mwohlan** [nuxt/framework#5647]
### Environment

Nuxt project info:                                                                    

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.1`
- Nuxt Version:     `3.0.0-rc.4-27605536.8c2c80e`
- Package Manager:  `pnpm@7.3.0`
- Builder:          `vite`
- User Config:      `modules`, `autoImports`, `ssr`, `experimental`, `unocss`, `colorMode`, `typescript`
- Runtime Modules:  `@vueuse/nuxt@8.7.5`, `@unocss/nuxt@0.41.1`, `@pinia/nuxt@0.1.9`, `@nuxtjs/color-mode@3.1.4`, `@nuxtjs/supabase@0.1.17`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-qsbpta?file=app.vue

### Describe the bug

This only applies to the edge-channel. The latest rc4 doesn't have this issue.

As soon as any "@ apply" (Unocss/Tailwind) rules are present in the style block, the following type of errors appear preventing the dev server to start:
![image](https://user-images.githubusercontent.com/76627776/176187129-972206a5-f834-458f-a7c9-2dc7a673e1fa.png)

**Comment by danielroe** [comment]
Resolved in https://github.com/nuxt/framework/pull/5398.
