### ISSUE TITLE
useFetch refresh not working when params change

### ISSUE THREAD

**Issue by SamEdwardes** [nuxt/framework#5653]
### Environment

Nuxt CLI v3.0.0-rc.4                                                                                                                                                                                        18:15:14
RootDir: /Users/samedwardes/git/embeddedapp/webapp-frontend                                                                                                                                                 18:15:15
Nuxt project info:                                                                                                                                                                                          18:15:15

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.2.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.9.0`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.1.2`, `@formkit/nuxt@1.0.0-beta.8`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                                                            18:15:15

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

The example from the docs works.

```vue
<script setup>
const page = ref(1);

const { data: users, pending, refresh, error } = await useFetch(() => `users?page=${page.value}&take=6`, { baseURL: config.API_BASE_URL }
);

function previous(){
  page.value--;
  refresh();
}

function next() {
  page.value++;
  refresh();
}
</script>
```

When I pass `page` into the `params` option it does not work.

```vue
<script setup>
const page = ref(1);

const { data: users, pending, refresh, error } = await useFetch(() => `users`, {
  baseURL: config.API_BASE_URL ,
  params: { 
    page: page.value,
    take: 6
  }
}
);

function previous(){
  page.value--;
  refresh();
}

function next() {
  page.value++;
  refresh();
}
</script>
```

The API is still called again, but always with `page` set to a value of 1.

### Describe the bug

The API is still called again, but always with `page` set to a value of 1.

### Additional context

Is this expected behaviour, or is this a bug?

**Comment by danielroe** [comment]
This is how Vue reactivity works - the value is frozen in time when you call `useFetch`: see https://github.com/nuxt/framework/issues/4970. If you want to keep it reactive, you can use `useAsyncData` and provide a custom fetcher function. Something like this: https://stackblitz.com/edit/github-c4jssa.

**Comment by SamEdwardes** [comment]
Thank you for the response @danielroe. I will take a look at the examples you shared to see if I understand.

**Comment by ddavid67** [comment]
there should be a way to automaticaly refetch based on a reactive search params
this is already the current behevior with the first parameter of usefetch
even refresh() does not provide a way to inject new params

**Comment by SamEdwardes** [comment]
I just wanted to close the loop on this for future readers. I was able to get my desired behaviour with a single file component that looks like this:

```vue
<!-- app.vue -->

<template>
  <div>
    <div>Type a name below to get the predicted age:</div>
    <input type="text" v-model="name" />
    <div>Selected name is: {{ name }}</div>
    <div>Predicted age is: {{ age }}</div>
  </div>
</template>

<script setup>
const name = ref('sam');

const { data: age } = await useAsyncData(
  'age',
  () => $fetch('https://api.agify.io', {
    params: {
      name: name.value,
    },
  }),
  { watch: [name] }
);
</script>

```

**Comment by optimistic-raisin** [comment]
This should be put included in official docs. Or is it already there?
