### ISSUE TITLE
Can't use @casl/ability

### ISSUE THREAD

**Issue by ppodds** [nuxt/framework#5654]
### Environment

Nuxt CLI v3.0.0-rc.4                                                                              15:55:04
RootDir: /home/ppodds/project/bug                                                                 15:55:05
Nuxt project info:                                                                                15:55:05

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[https://github.com/ppodds/nuxt3-casl-bug](https://github.com/ppodds/nuxt3-casl-bug)

### Describe the bug

Can't use classes provided by `@casl/ability`.

e.g.
```vue
<script setup lang="ts">
import { Ability } from "@casl/ability";
Ability;
</script>
```

Error:
```
[nuxt] [request error] __vite_ssr_import_1__ is not defined
  at $id_ee6a35a1 (./.nuxt/dist/server/server.mjs:3583:741)  
  at async __instantiateModule__ (./.nuxt/dist/server/server.mjs:3848:3)
```

**Comment by danielroe** [comment]
This should be working with the latest edge releases (possibly RC): https://stackblitz.com/edit/github-xjwwpq.
