### ISSUE TITLE
Cloudlfare preset and node-fetch-native not working

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/framework#5672]
### Environment

https://stackblitz.com/edit/nuxt-starter-1qb78a?file=package.json,server%2Fapi%2Ftest.ts,app.vue

### Reproduction

https://stackblitz.com/edit/nuxt-starter-1qb78a?file=package.json,server%2Fapi%2Ftest.ts,app.vue

### Describe the bug

Running build with cloudflare nitro preset throws an error if we are trying to import node-fetch-native polyfill in a server api

@archetipo95 FYI

**Comment by pi0** [comment]
You don't need to add `node-fetch-native/polyfill` Nitro should already provide it (only for development and Node.js since cloudflare has global native fetch)

**Comment by Rigo-m** [comment]
I'll give some context:

We are working on a module that dynamically adds server apis to our nuxt application, and it uses urql to fetch some data from a graphQL api.
As you can see [here](https://github.com/FormidableLabs/urql/issues/283), urql needs a fetch polyfill.
Since we are building this module to be used in nuxt applications that can be run on any deployment environment (lambdas, netlify, cloudflare etc), how can we know if we have to import the fetch polyfill or not?
We should be able to import it anyway and then if it's already present it should be a burden. Any workaround in the nuxt app realm to circumvent this issue?

**Comment by Rigo-m** [comment]
> You don't need to add `node-fetch-native/polyfill` Nitro should already provide it (only for development and Node.js since cloudflare has global native fetch) why do you need this?

I see what you are saying now. I guess I need to re-check why urql failed then. Since nitro already polyfills it, urql shouldn't've bothered me before. I'll take a look at it. Maybe it was an older version of nuxt and fetch wasn't already polyfilled?

**Comment by pi0** [comment]
Indeed. Global fetch is always polyfilled for Nuxt in Node.js (SSR and API routes) :)

**Comment by Rigo-m** [comment]
Can confirm that it's readily available without the need to manually polyfilling it. Thanks
