### ISSUE TITLE
call `useFecth` with `Blob` as body got error

### ISSUE THREAD

**Issue by dallaslu** [nuxt/framework#5690]
### Environment

Nuxt CLI v3.0.0-rc.4-27611167.a41644e

### Reproduction

```typescript
useFetch(`/api/any-endpoint`, {
    method: "POST",
    body: new Blob(['any_value']),
  })
```

### Describe the bug

> Error: Hashing Blob objects is currently not supported
Use "options.replacer" or "options.ignoreUnknown"

**Comment by dallaslu** [comment]
Add a `key` field in opts and it works.

```typescript
useFetch(`/api/any-endpoint`, {
    method: "POST",
    body: new Blob(['any_value']),
    key: `any_value`
  })
```

**Comment by danielroe** [comment]
Yes, you will need to add a key as creating an automatic key for options with a blob is not supported.
