### ISSUE TITLE
Nuxt 3 preloads all pages, styles, fonts, svg. Adds everything in head to rel="prefetch"

### ISSUE THREAD

**Issue by Aleksandr-om** [nuxt/framework#5711]
### Environment

* Operating System: `Ubuntu`
* Node Version: `v16.15.1`
* Nuxt Version: `3.0.0-rc.4` / `v3.0.0-rc.4-27611167.a41644e`
* Package Manager: `yarn@1.22.19`
* Builder: `vite`
* User Config: `target, nitro, runtimeConfig, css, buildDir, modules, intlify, typescript, build`
* Runtime Modules: -
* Build Modules: -

### Reproduction

[https://github.com/Aleksandr-om/nuxt-3-issue/tree/main/nuxt-app](https://github.com/Aleksandr-om/nuxt-3-issue/tree/main/nuxt-app)

```console
git clone https://github.com/Aleksandr-om/nuxt-3-issue.git
cd nuxt-app
yarn install
yarn build
yarn start
```

### Preloading of pages, fonts, styles, images does not work correctly

* Installed the latest Nuxt.
* Added a few pages. `test-no-preload*` - there are no links to these pages anywhere. `two-page.vue` - we can go to this page from the main one.
* Added styles to each page with the loading of woff and woff2 fonts.

After the project is built and launched, Nuxt preloads all data and pages.

![](https://raw.githubusercontent.com/Aleksandr-om/nuxt-3-issue/main/nuxt-app/readme-sources/nuxt-issue-source.png) 
![](https://raw.githubusercontent.com/Aleksandr-om/nuxt-3-issue/main/nuxt-app/readme-sources/nuxt-issue-dom.png)

As you can see, all resources are added to the preload `<link rel="prefetch" ...>`, all pages, even those that are not used anywhere.

Should work like on [https://nuxt-prefetch.surge.sh/](https://nuxt-prefetch.surge.sh/)   
Only those pages should be preloaded, links to which are visible in the browser and after the current page is fully loaded.    
Also, fonts should not be preloaded from all pages in advance.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/4475.
