### ISSUE TITLE
[nuxt] [request error] computed is not defined: error when computed property is declared after import.meta.globEager

### ISSUE THREAD

**Issue by AlexSua** [nuxt/framework#5716]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.19.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `components`, `buildModules`, `modules`, `intlify`, `css`, `build`, `vite`, `content`, `nitro`, `generate`, `ssr`, `target`
- Runtime Modules:  `@nuxt/content@2.0.1`
- Build Modules:    `@intlify/nuxt3@0.2.2`, `nuxt-windicss@2.4.2`
------------------------------

### Reproduction

I receive this error when I execute `import.meta.globEager()` before a computed property inside `<script setup>`

**This fails**:
```ts
<script setup lang="ts">
  const { t } = useI18n()
  const modules = import.meta.globEager("/assets/img/*");
  const title = computed(() => {
    return t(`profile.title`)
  });
  const getSrc = (path) => {
    return modules["/assets/img/"+path].default;
  };
</script>
```
Gives the following error:
![image](https://user-images.githubusercontent.com/8196195/177186957-e1bee7a1-b328-4467-9af7-ea2fb39c1a28.png)

**This works**:
```ts
<script setup lang="ts">
  const { t } = useI18n()
  const title = computed(() => {
    return t(`profile.title`)
  });
  const modules = import.meta.globEager("/assets/img/*");
  const getSrc = (path) => {
    return modules["/assets/img/"+path].default;
  };
</script>
```

### Describe the bug

When `import.meta.globEager()` is executed before a `computed()`  property inside a `<script setup>` the code generated in .nuxt/dist/server/server.mjs is wrong.

Code generated inside `server.mjs` with `import.meta.globEager()` before a `computed()` property. **Fails**:
```ts
const modules = {"/assets/img/logo.png": __vite_ssr_import_0__"};//globEager()
const { t } = __vite_ssr_import_6__.useI18n();
const title = computed(() => { //Error! Computed not defined.
  return t(`profile.title`);
});
```

Code generated inside `server.mjs` with `import.meta.globEager()` after a `computed()` property. **Works**:
```ts
const { t } = __vite_ssr_import_7__.useI18n();
const title = __vite_ssr_import_5__.computed(() => {
  return t(`profile.title`);
});
const modules = {"/assets/img/logo.png": __vite_ssr_import_0__"};//globEager()
```

### Additional context
**This error first appeared when I migrated from version v3.0.0-rc.3 to v3.0.0-rc.4**

### Logs
```
[nuxt] [request error] computed is not defined
  at setup (./.nuxt/dist/server/server.mjs:14427:19)  
  at _sfc_main.setup (./.nuxt/dist/server/server.mjs:14461:23)  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7084:29)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7039:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)  
  at _sfc_ssrRender (./.nuxt/dist/server/server.mjs:14296:31)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
```

**Comment by danielroe** [comment]
Please see https://github.com/nuxt/framework/issues/5650#issuecomment-1173696987 - this issue has already been resolved and will be present in the next RC (or you can opt-in sooner with edge channel).
