### ISSUE TITLE
Obscure documentation

### ISSUE THREAD

**Issue by uuf6429** [nuxt/framework#5736]
https://github.com/nuxt/framework/blob/00cd2608047a405d78b4fc15dd7daaad11b88355/docs/content/3.api/5.commands/build.md?plain=1#L14

> or as command-line argument. 

What command line argument? How?

**Comment by danielroe** [comment]
For questions, please use discussions.

A PR would be welcomed to clarify this.

**Comment by uuf6429** [comment]
@danielroe this is not a question, the documentation is ambiguous and possibly wrong (see below). I doubt that confusing readers is a desired behaviour...

@LuckyWindsck firstly, that's not a cli argument, it's an inline/local env var. Secondly, if that's supposed to work, then env vars should have worked (but they don't, and the documentation seems to exclude that already). I tried adding the variable in the end (being "a cli argument" and since that running `nuxi --help` it mentions `[args]` at the end), but that didn't work either (although the command didn't seem to complain at all).


Anyway, my solution ended up with skipping this altogether and use my own env var.

**Comment by danielroe** [comment]
@LuckyWindsck is correct, it was the intended meaning. Moreover, they were trying to help and I would appreciate it if you would treat them with more consideration.

The reason setting the variable on the command line didn't work for you is that behaviour has changed following https://github.com/nuxt/framework/pull/5417; I've opened a PR to update the docs. Thanks for reporting the issue.
