### ISSUE TITLE
Imports from server routes are not passed via Vite plugins

### ISSUE THREAD

**Issue by makkarpov** [nuxt/framework#5752]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `modules`, `css`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.1.3`
- Build Modules:    `-`

### Reproduction

Register new Vite plugin which will simply log all resolution requests it receives:

**nuxt.config.ts**:
```typescript
export default defineNuxtConfig({
    vite: {
        plugins: [
            {
                name: 'meow-meow-plugin',
                enforce: 'pre',

                load(id) {
                    if (id.indexOf('meow') !== -1) console.log('load: ', id);
                },

                resolveId(id) {
                    if (id.indexOf('meow') !== -1) console.log('resolveId: ', id);
                }
            }
        ]
    }
}
```

Add some weird import to regular page or component:
**pages/index.vue**:
```vue
<template>{{ meow }}</template>
<script setup lang="ts">
import meow from "meowing-page";
</script>
```

Add similar weird import to server route:
**server/routes/test.ts**:
```typescript
import meow from "meowing-route";
console.log(meow);
```

### Describe the bug

You will see logs related to import fom regular page. You will not see any resolution attempts for route import, and build process will eventually fail there.

Even simple Vite's `?raw`, `?url` do not work in server route context.

**Comment by danielroe** [comment]
The server part of the build is not processed by vite at all. Rather, the vite _output_ is processed alongside the server part of the build by Nitro.

You can add a rollup plugin to Nitro like this:

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  nitro: {
    rollupConfig: {
      plugins: []
    }
  }
})
```

**Comment by makkarpov** [comment]
Thanks a lot, tried to plug that code into every possible place, but didn't noticed that `nitro` also has it's own set of plugins.
