### ISSUE TITLE
Pages not automatically appearing when created while npm run dev running

### ISSUE THREAD

**Issue by craigharman** [nuxt/framework#5766]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```bash
npx nuxi init nuxt-app
cd nuxt-app
npm install
npm run dev -- -o
```

Add a new page into /pages folder (eg. test.vue)

In your browser visit: http://localhost:3000/test
Get a 404

Stop/Start `npm run dev -- -o`
In your browser visit: http://localhost:3000/test
Get the page!

### Describe the bug

Any files added to /pages folder while development server is running should be reachable in the browser straight away. Instead you have to restart nuxt.

**Comment by ojvribeiro** [comment]
I can confirm this in `3.0.0-rc.4`.

**Comment by lawnch-daniel** [comment]
This seems to still be an issue. I'm on rc11 and experiencing this. @pi0

**Comment by danielroe** [comment]
Please open a new issue with a reproduction. 🙏

**Comment by ojvribeiro** [comment]
I just tested RC11 here and can confirm the issue.

I made a repro on Stackblitz: https://stackblitz.com/edit/nuxt-starter-e8cv5m?file=pages/index.vue

## Steps

- Create an `about.vue` page
- Try to navigate to `/about`

Then we get a 404, unless we manually reload the page (this time around we do not have to restart the server at least).
