### ISSUE TITLE
Errors when trying to import Turf.js

### ISSUE THREAD

**Issue by ejfox** [nuxt/framework#5774]
### Environment

```
➜  npx nuxi info
Nuxt CLI v3.0.0-rc.4                                                                      13:07:40
RootDir: /Users/ejfox/code                                                                13:07:40
Nuxt project info:                                                                                  13:08:16

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `env`, `performance`, `head`, `css`, `nitro`, `runtimeConfig`, `publicRuntimeConfig`, `modules`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/proxy@2.1.0`
- Build Modules:    `-`
------------------------------
```

### Reproduction

<https://stackblitz.com/edit/github-tgazga-1vebrg?file=components/TurfTest.vue>

From Nuxt start:

## Add [Turf](https://turfjs.org)
```bash
yarn add @turf/turf
```

## Import in component
Then in a component in the `/components/` folder, import anything (let's try point) from Turf
```js
import { centroid, point, distance } from '@turf/turf'
```

In Chrome/Safari console:

```
@turf_turf.js?v=d9e1057d:19542 Uncaught TypeError: Cannot read properties of undefined (reading 'POLYGON_CLIPPING_MAX_QUEUE_SIZE')
    at @turf_turf.js?v=d9e1057d:19542:85
```

### Describe the bug

When trying to include Turf js, get an error a Turf dependency looking for `process.env`

```
Uncaught TypeError: Cannot read properties of undefined (reading 'POLYGON_CLIPPING_MAX_QUEUE_SIZE')
```

This error comes from the `polygon-clipping` dependency in Turf: <https://github.com/mfogel/polygon-clipping/blob/b064f942061e9820c53a462ebcccda7407330007/src/operation.js#L10>

### Additional context

I tried maybe trying to hack it by adding the value to the `process.env` that the dependency is looking for, which may have been misguided, and did not work in any case:

### nuxt.config.ts
```js
  env: {
    POLYGON_CLIPPING_MAX_QUEUE_SIZE: 100,
  },
  runtimeConfig: {
    POLYGON_CLIPPING_MAX_QUEUE_SIZE: 100,
  },
  publicRuntimeConfig: {
    POLYGON_CLIPPING_MAX_QUEUE_SIZE: 100,
  }
```

**Comment by 516310460** [comment]
It may be the problem with this package

link https://github.com/geoman-io/leaflet-geoman/discussions/1162

**Comment by danielroe** [comment]
Yes, this is an issue with the underlying package. It's assuming that if `process` is defined then it's running in node, but we polyfill process but don't make `process.env` available.

The good news is that there is a straightforward solution:

```js
import { defineNuxtConfig } from 'nuxt';

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  vite: {
    define: {
      'process.env.POLYGON_CLIPPING_MAX_QUEUE_SIZE': '1000000',
      'process.env.POLYGON_CLIPPING_MAX_SWEEPLINE_SEGMENTS': '1000000',
    },
  },
});
```

[stackblitz](https://stackblitz.com/edit/github-tgazga-szt3bd)
