### ISSUE TITLE
plug and play support

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#581]
WIP:  #685

We should allow users to install and use nuxt3 with pnpm and yarn pnp.

- [ ] pnpm
- [ ] yarn pnp

## Reproduction

```
npx degit "nuxt/starter#v3" nuxt3-pnp
```

## pnpm

```
Module not found: Error: Can't resolve 'esbuild-loader'
Module not found: Error: Can't resolve 'webpack-hot-middleware/client?reload=true&timeout=30000&path=%2F__webpack_hmr%2Fclient&ansiColors=%7B%7D&overlayStyles=%7B%7D&name=client'
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'unenv'
```

## yarn pnp

```
[error] Error: Your application tried to access @nuxt/kit, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

**Comment by LifeIsStrange** [comment]
The officiel Vue repository switched to pnpm (this it is the fastest package manager), it would be a shame if nuxt didn't support it https://github.com/vuejs/vue-next/pull/4766

**Comment by aparajita** [comment]
@pi0 Off the bat, most of the imports in [nitro](https://github.com/nuxt/framework/blob/main/packages/nitro/src/runtime/server/index.ts) are failing. Could be more would fail if I could get those to work without using `shamefully-hoist=true` in `.npmrc`.

I first brought up the unfortunate dependency on a flat package structure — an undocumented, internal implementation detail — 2 1/2 years ago. At the time you [agreed with me](https://github.com/nuxt/nuxt.js/issues/5008#issuecomment-526929486), and said it would eventually get fixed. Fast forward to today, and Evan You has just officially switched to using pnpm in the Vue 3 workflow, so I think the time has come to fix this in Nuxt.

You guys are really, really smart; there must be a way to write code in such a way that you aren't relying either on implicit dependencies or on the dependency tree being flattened.

**Comment by aparajita** [comment]
@pi0 Example error message:

```
WARN  [worker] Cannot find package 'unenv' imported from /path/to/project/.nuxt/nitro/index.mjs
```

**Comment by aparajita** [comment]
Since vite and vue-next are using pnpm, wouldn't it seem better to use pnpm for nuxt as well?

**Comment by tobiasdiez** [comment]
May I ask if there is already a timeline for this feature?

I'm about to start a new project from scratch and would like to use yarn pnp for this and would like to judge if I should wait for a bit or start now without pnp and migrate later to it. So this question is not meant as an annoying "please hurry guys". I do understand that you are working hard on nuxt3!

**Comment by FallDownTheSystem** [comment]
pnpm now has support for a flat node_modules without symlinks, that might be of interest. [https://github.com/pnpm/pnpm/releases/tag/v6.25.0](https://github.com/pnpm/pnpm/releases/tag/v6.25.0)

**Comment by avaranze** [comment]
Today I figured I'd give Nuxt3 a try after using Next.js for a long time.  I use pnpm in my projects.  Here's what I am seeing:

```
Nuxt CLI v3.0.0-27375427.d07d572

  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.0.120:3000/
  > Network:  http://192.168.153.120:3000/
  > Network:  http://192.168.109.2:3000/

ℹ Vite warmed up in 166ms
✔ Vite server built in 329ms
✔ Nitro built in 151 ms

 ERROR  [worker] Cannot find package 'unenv' imported from /path/to/project/.nuxt/nitro/index.mjs
Did you mean to import unenv@0.4.3/node_modules/unenv/runtime/polyfill/fetch.node.cjs?

  Did you mean to import unenv@0.4.3/node_modules/unenv/runtime/polyfill/fetch.node.cjs?
  at new NodeError (node:internal/errors:371:5)
  at packageResolve (node:internal/modules/esm/resolve:884:9)
  at moduleResolve (node:internal/modules/esm/resolve:929:18)
  at defaultResolve (node:internal/modules/esm/resolve:1044:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
```

Thank you for the work being put into this issue.

**Comment by VidarDev** [comment]
Hey I have now read ale 2 times through, but a solution somehow not seen.

Node v16.14.0
Yarn 3.2.0

**npx nuxi init test
cd test
yarn set version stable**

`➤ YN0000: Retrieving https://repo.yarnpkg.com/3.2.0/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.2.0.cjs
➤ YN0000: Done in 0s 609ms`

**yarn dev -o**

```
Nuxt CLI v3.0.0-27444434.856c01a
                                                                                                   
  > Local:    http://localhost:3000/
  > Network:  http://192.168.178.77:3000/
  > Network:  http://172.26.208.1:3000/


 ERROR  Your application tried to access @nuxt/kit, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @nuxt/kit (via "@nuxt\kit")
Required by: C:\Users\vidar\Projekte\24x7dev\test\

Require stack:
- C:\Users\vidar\Projekte\24x7dev\test


  Required package: @nuxt/kit (via "@nuxt\kit")
  Required by:

  Require stack:
  - C:\Users\vidar\Projekte\24x7dev\test
  at Function.require$$0.Module._resolveFilename (.pnp.cjs:16359:13)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at resolveModule (/C:/Users/vidar/Projekte/24x7dev/test/.yarn/cache/nuxi-edge-npm-3.0.0-27444434.856c01a-08238a568b-7e1ac30169.zip/node_modules/nuxi-edge/dist/chunks/cjs.mjs:19:29)
  at importModule (/C:/Users/vidar/Projekte/24x7dev/test/.yarn/cache/nuxi-edge-npm-3.0.0-27444434.856c01a-08238a568b-7e1ac30169.zip/node_modules/nuxi-edge/dist/chunks/cjs.mjs:32:24)
  at loadKit (/C:/Users/vidar/Projekte/24x7dev/test/.yarn/cache/nuxi-edge-npm-3.0.0-27444434.856c01a-08238a568b-7e1ac30169.zip/node_modules/nuxi-edge/dist/chunks/kit.mjs:137:18)
  at Object.invoke (/C:/Users/vidar/Projekte/24x7dev/test/.yarn/cache/nuxi-edge-npm-3.0.0-27444434.856c01a-08238a568b-7e1ac30169.zip/node_modules/nuxi-edge/dist/chunks/dev.mjs:6717:43)
  at async _main (/C:/Users/vidar/Projekte/24x7dev/test/.yarn/cache/nuxi-edge-npm-3.0.0-27444434.856c01a-08238a568b-7e1ac30169.zip/node_modules/nuxi-edge/dist/chunks/index.mjs:384:7)```

**Comment by danielroe** [comment]
@VidarDev For now you will need to set the node modules linker in your `.yarnrc.yml`:

```yaml
nodeLinker: node-modules
```

**Comment by VidarDev** [comment]
> @VidarDev For now you will need to set the node modules linker in your `.yarnrc.yml`:
> 
> ```yaml
> nodeLinker: node-modules
> ```

thanks a lot

**Comment by danielroe** [comment]
@pi0 Is it worth raising an issue for yarn pnp too?

**Comment by zlz9** [comment]
![image](https://user-images.githubusercontent.com/95131054/196907140-dc690398-a216-4a84-bb53-8c9ea79f0640.png)
The initialization project reported error 500

**Comment by danielroe** [comment]
@zlz9 That is a completely unrelated issue, but has been resolved in https://github.com/nuxt/framework/pull/8299. For now, you can use a higher version of node to work around it.
