### ISSUE TITLE
context.store plugin

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/framework#5812]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `css`, `build`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

context.store.state?.auth 

### Describe the bug

Before we can access
context.store.state?.auth on a plugin

how do we do it now with the new nuxtApp
can't seem to find a store available inside the nuxtApp

Thank you so much

**Comment by danielroe** [comment]
There is no default store in Nuxt 3, so this is probably a question for pinia, Harlem, etc. and I would suggest checking their documentation.

Or feel free to raise this as a discussion or in the Nuxt Discord server.
