### ISSUE TITLE
Respect dynamic params when calling `refresh()` returned by `useFetch`

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/framework#5814]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `modules`, `css`, `typescript`, `alias`, `build`, `ssr`, `runtimeConfig`, `vue`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.1.3`, `floating-vue/nuxt`, `@pinia/nuxt@0.1.9`, `@vueuse/nuxt@8.6.0`, `unplugin-icons/nuxt`
- Build Modules:    `-`
------------------------------

### Reproduction

n/a

### Describe the bug

In the following example, I would like the `refresh()` function to take into account any reactive data sources, rather than saving their initial values and using these in further calls to `refresh()` (that is, every time the `searchQuery` watcher is triggered, the call would contain an empty string param rather than the user-typed value). Documentation shows these can be embedded into the url string, but I find it completely unmaintainable for more than two or three params.
```
const searchQuery = ref('')

const { data, pending, error, refresh } = useFetch('/api/(...)', {
    params: {
        searchQuery: encodeURIComponent(searchQuery.value)
    }
})

watch(searchQuery, () => {
    refresh()
})
```

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/issues/5653#issuecomment-1173935225.
