### ISSUE TITLE
When two useFetch used clientside at same time only one of them updates

### ISSUE THREAD

**Issue by volk234** [nuxt/framework#5818]
### Environment

Nuxt CLI v3.0.0-rc.4

### Reproduction

https://stackblitz.com/edit/github-ymf7zt-tynvn4?file=app.vue,TestComponent.vue

### Describe the bug

When two useFetch used clientside at same time in multiple components, only one of them becomes resolved.

### Additional context

Maybe this is related to #5627

**Comment by danielroe** [comment]
Let's track in #5627.
