### ISSUE TITLE
`addPlugin` from `@nuxt/kit` prepends plugins

### ISSUE THREAD

**Issue by Aareksio** [nuxt/framework#5835]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@/modules/pinia`, `@/modules/my-module`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ba6rwp?file=nuxt.config.ts

### Describe the bug

`addPlugin`, by default, prepends to the list of plugins. This is great for the purpose described in [code comment](https://github.com/nuxt/framework/blob/main/packages/kit/src/plugin.ts#L62-L63).

There are two problems though:

a) a module depends on other modules, the natural approach is to order them in a manner that dependencies are first
```js
modules: [
  '@pinia/nuxt', 
  'my-module-depends-on-pinia' // <-- uses pinia
]
```

b) a module can expose more than one plugin depending on each other
```js
addPlugin(resolver.resolve('./plugins/api.js')
addPlugin(resolver.resolve('./plugins/auth.js') // <-- calls api
```

In both cases, the module / plugin registered later does not have access to the plugins added prior. Adding `{ append: true }` is not ideal, as it puts the module plugins after user plugins.

**Comment by Aareksio** [comment]
Perfectly reasonable, thanks for the answer. `append: true` indeed does not solve the problem, but using hooks is perfect solution. An opinionated approach would be helpful. In nuxt 2 it was valid to call `await auth.init()` which relied on vuex store straight from plugin declaration - the same approach is not valid in nuxt 3.

**Comment by Aareksio** [comment]
Linking here as discussions tend to be overlooked and it is heavily related:
https://github.com/nuxt/framework/discussions/6436

**Comment by pi0** [comment]
Hi @Aareksio These two are not related with the built-in `app:created` hook and plugin ordering.

Closing this issue because preprend behavior is intended explained in previous comment.
