### ISSUE TITLE
`useRequestHeaders` to pass headers on SSR causes "nuxt instance unavailable" error on retry

### ISSUE THREAD

**Issue by Aareksio** [nuxt/framework#5837]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ogom7a?file=app.vue

### Describe the bug

1. By default, `ohmyfetch` retries once for methods without payload, eg. `GET`. 
2. The [code example from documentation](https://v3.nuxtjs.org/guide/features/data-fetching#example-pass-client-headers-to-the-api) suggests using `useRequestHeaders` to pass headers (eg. cookies) on SSR. 
3. Nuxt context is not preserved during the retry, resulting in "nuxt instance unavailable" error.

It is not obvious right away where the error roots. May be especially hard to debug in situations when the server is inaccessible very briefly, for limited set of users only, think 502. Even with retry disabled on server by default, user may opt-in for this feature.

**Comment by danielroe** [comment]
We should update the docs. It should be:

```js
const cookieHeaders = useRequestHeaders(['cookie'])
const { error } = await useFetch('https://httpbin.org/status/500', {
  onRequest({ request, options }) {
    if (process.server) {
      options.headers = cookieHeaders;
    }
  },
});
```

**Comment by danielroe** [comment]
That might work. Depends a bit on when you are calling `fetchWithCookie` - is it always in setup? - and whether the context is available at that point in time.

**Comment by Aareksio** [comment]
The goal is to communicate with internal API, always passing the cookies. Setting the options for each call is cumbersome. We use `createFetch` to create a client with shared properties (baseUrl, error handling, cookie handling). Framework approach / solution for such scenario would be helpful, this seems like a very common problem when working with an API.
