### ISSUE TITLE
data not changing with useAsyncData watch route 

### ISSUE THREAD

**Issue by graphicfox** [nuxt/framework#5838]
Hello,

I experience following bug when Im using useAsyncData while watching the route. On the initial page load the correct data from the strapi api is stored in `pageData`. After clicking on the nuxt link (/news) the useAsyncData gets triggert again and with console.log inside useAsyncData the correct data gets fetched. But in the template `pageData` is the old Object. If i now go back to the previous path (/) i will get the data from /news.

`/pages/[...slug].vue`

```
<template>
    <div>
        <nuxt-link href="/news">News</link-wrap>
        <div>{{ pageData }}</div>
    </div>
</template>
```

```
const {data: pageData} = await useAsyncData("pageData",
    () => find<Strapi4Response<any>>("pages", {filters: {slug: {$eq: route.path}}}), {watch: [route]});
```

**Comment by ahoiroman** [comment]
Same here.

**Comment by graphicfox** [comment]
Adding `{initialCache: false}` to the options resolves the problem. But I don´t know if this is intended. Watching the route is not necessary with this, because the data will get updateed now.

````
const {data: pageApiData} = await useAsyncData("pageApiData", () => setPageData(), {initialCache: false});
````

**Comment by kuizuo** [comment]
> Adding `{initialCache: false}` to the options resolves the problem. But I don´t know if this is intended. Watching the route is not necessary with this, because the data will get updateed now.
> 
> ```
> const {data: pageApiData} = await useAsyncData("pageApiData", () => setPageData(), {initialCache: false});
> ```

it's worked!

**Comment by AaronWangCong** [comment]
需要设置一个属性 key  就可以重新请求了，目前是这样设置的。

**Comment by ennioVisco** [comment]
I had a similar issue with `useFetch`. I have the feeling that the key generation algorithm doesn't work. 
I fixed it by forcing the `key` field in the `options` parameter, which I set to the value of the endpoint and it works fine.

**Comment by danielroe** [comment]
There are several issues here, but let's track the originally reported one in https://github.com/nuxt/framework/issues/4855.
