### ISSUE TITLE
auto-imports editor

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/framework#5843]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `pnpm@7.1.3`
- Builder:          `vite`
- User Config:      `srcDir`, `css`, `typescript`, `build`, `modules`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.1.9`
- Build Modules:    `-`
------------------------------

### Reproduction

<img width="760" alt="image" src="https://user-images.githubusercontent.com/3810177/178430996-74070103-86a3-4f56-a74e-2cd867eb4641.png">

### Describe the bug

My editor warns me of a missing import statement.
It should automatically detect it like
<img width="197" alt="image" src="https://user-images.githubusercontent.com/3810177/178431567-917d33f6-97ea-47c3-9097-f4ae57f82103.png">

this is my tsconfig
<img width="329" alt="image" src="https://user-images.githubusercontent.com/3810177/178431635-fe817dd6-f5b2-4f2c-beb9-f9594c39df69.png">

Thank you so much

**Comment by danielroe** [comment]
Check out https://github.com/nuxt/framework/issues/2320.

**Comment by stephenjason89** [comment]
Thank you for pointing this out @danielroe 
Custom buildDir fixed the problem.
