### ISSUE TITLE
nuxt 3 layouts old options api syntax

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/framework#5844]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `pnpm@7.1.3`
- Builder:          `vite`
- User Config:      `srcDir`, `css`, `typescript`, `build`, `modules`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.1.9`
- Build Modules:    `-`
------------------------------

### Reproduction

<img width="240" alt="image" src="https://user-images.githubusercontent.com/3810177/178432227-57a486ea-0377-4a99-8c6a-e8f42f208389.png">

### Describe the bug

Defining the layout in export default doesn't work anymore.

It would be nice if we can still use the old syntax together with this

```
definePageMeta({
    layout: 'custom',
})
```

Thank you

**Comment by danielroe** [comment]
It doesn't rely on `<script setup>`. You can simply do:

```vue
<script>
definePageMeta({
    layout: 'custom',
})

export default {
  name: 'something'
}
</script>
