### ISSUE TITLE
ERROR  [nuxt] [request error] Invalid value used as weak map key (Vuetify elements)

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/framework#5848]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `pnpm@7.1.3`
- Builder:          `vite`
- User Config:      `buildDir`, `srcDir`, `css`, `typescript`, `build`, `modules`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.1.9`
- Build Modules:    `-`
------------------------------

### Reproduction

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/3810177/178465527-75959d37-b3cc-43be-8f4b-d8af517cbab0.png">

### Describe the bug

Running nuxi generate produces
ERROR  [nuxt] [request error] Invalid value used as weak map key 
issue is probably related to https://github.com/nuxt/framework/discussions/4588

I also believe that this might cause the error
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/3810177/178465709-7dce3423-544b-46b4-8f42-6c1ef10d4552.png">

During nuxt dev, no errors are present.

**Comment by danielroe** [comment]
That means that you have not registered those components on server-side.

**Comment by stephenjason89** [comment]
@danielroe This happens only happens in nuxi generate.
nuxi build don't produce this errors.

I can also see that before hydration on nuxt dev that these elements are present

**Comment by danielroe** [comment]
Would you provide a reproduction then?

**Comment by stephenjason89** [comment]
Yes,
https://github.com/stephenjason89/nuxt3

Thank you for looking in to it.

**Comment by danielroe** [comment]
The issue was actually in your apollo plugin, and was the following line:

```js
const host = event?.req?.headers?.host ?? location?.hostname
```

This was failing on the first instance.

Update it to this (or similar) and you should be good to go 👍:

```js
const host = (process.server ? event?.req?.host : location?.hostname) ?? 'http://localhost:3000'
```

**Comment by stephenjason89** [comment]
Thank you for pointing this out.
Everything works now.
