### ISSUE TITLE
nuxt build & nuxt preview is not supported resolving ES modules

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/framework#5849]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `pnpm@7.1.3`
- Builder:          `vite`
- User Config:      `buildDir`, `srcDir`, `css`, `typescript`, `build`, `modules`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.1.9`
- Build Modules:    `-`
------------------------------

### Reproduction

run nuxt build then nuxt preview
visit the site at http://[0.0.0.0](http://0.0.0.0:3000/):3000/
then see the console error
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/3810177/178468908-b0c6bac3-b245-4aa6-82b2-840dd78b0345.png">

### Describe the bug

After building and running preview, 
console error runs in a loop.

I cannot view the site.
During nuxt dev, no errors are present.

I also tried changing my imports from
```import { InMemoryCache, ApolloClient, ApolloLink } from '@apollo/client/core'```
to
```import { InMemoryCache, ApolloClient, ApolloLink } from '@apollo/client/core/core.cjs'```

then manually changing app/server.mjs
<img width="414" alt="image" src="https://user-images.githubusercontent.com/3810177/178470340-3fd94c6e-f744-4bbd-b1f1-792c53a862a5.png">
from
<img width="809" alt="image" src="https://user-images.githubusercontent.com/3810177/178470630-df6cf5f5-fb3a-45fc-bac8-71aaa911897d.png">
to
<img width="870" alt="image" src="https://user-images.githubusercontent.com/3810177/178470511-6260196f-6dd2-4bfa-bf48-8df2ac6a4b3f.png">

Kinda fixed the problem on nuxt build but breaks nuxt dev with this error
<img width="670" alt="image" src="https://user-images.githubusercontent.com/3810177/178472782-9acd9405-a343-45c5-9021-70183e13a1aa.png">

This also happens with
<img width="629" alt="image" src="https://user-images.githubusercontent.com/3810177/178470801-49951f2a-405c-49f0-95c6-6a8ec1aa15b1.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/3810177/178470820-50698518-090a-4b3c-943c-9809a27fd920.png">
Had to explicitly define the cjs file

**Comment by danielroe** [comment]
This is an upstream issue with `@apollo/client`. See https://v3.nuxtjs.org/concepts/esm for more on what is going on and for some possible workarounds.
