### ISSUE TITLE
New components created in custom srcDir are not recognized until restart

### ISSUE THREAD

**Issue by doseofted** [nuxt/framework#5888]
### Environment

Nuxt CLI v3.0.0-rc.5
RootDir: /home/projects/github-b4wrmp-hjzjfy
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `srcDir`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[Issue can be seen here](https://stackblitz.com/edit/github-b4wrmp-hjzjfy?file=nuxt.config.ts) by creating a new component in `src/components` folder and then trying to use that component from `src/pages/index.vue` while `npm run dev` is running. The component is not recognized until dev command is restarted by running `npm run dev` again.

### Describe the bug

When a custom `srcDir` is used, components created while `npm run dev` is running are not recognized until it is restarted. When using the default `srcDir`, components are immediately recognized.

### Additional context

The `srcDir` is very useful when working with Nuxt in containerized environments to bind a single "src" folder on the host system to the container instead of each Nuxt folder (such as pages, layouts, components, etc).

As a workaround I am not using the srcDir but it's a great feature that makes working with Nuxt in a container easy.

**Comment by danielroe** [comment]
@doseofted I'd appreciate your confirmation that the linked PR resolves the issue for you. It did for me, but it doesn't seem to be linked to a custom `srcDir`, so please do let me know if it persists for you.

**Comment by doseofted** [comment]
@danielroe I just tested it out with the latest build (`nuxt3@3.0.0-rc.6-27640211.4d80c43`) and it works perfectly!
