### ISSUE TITLE
refactor `WebpackBundler` and `PostcssConfig`

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#589]
[`WebpackBundler`](https://github.com/nuxt/framework/blob/main/packages/webpack/src/webpack.ts) and [`PostcssConfig`](https://github.com/nuxt/framework/blob/main/packages/webpack/src/utils/postcss.ts#L39) are almost only leftovers from Nuxt 2 code base that are not migrated and using legacy syntax. During refactor, we shall remove dependency on `options.build.*` and support new `options.webpack` interface. (#1466)

**Comment by danielroe** [comment]
I believe this is done in #2812.
