### ISSUE TITLE
Config alias `theme` to `extends`

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#5919]
It is more semantic to have single `theme` for when extending a theme layer. In addition, we can have an object shortcut syntax to provide layer options. (Depends on [#24)](https://github.com/unjs/c12/issues/24))

From:

```js
export default defineNuxtConfig({ 
  extends: 'docus',
  // https://github.com/unjs/c12/issues/9
  extends: { from: 'docus', override: { featureFlag: true } }
}
```

To:

```js
export default defineNuxtConfig({ 
  theme: 'docus',
  theme: [docus, { featureFlag: true }]
}
```

---

Q: What about theme configuration? It goes under app namespace as a runtime config: (or better `app/theme.config` file https://github.com/nuxt/framework/issues/5918)

```js
export default defineNuxtConfig({ 
  app: {
    theme: { }
  }
}
```

**Comment by pi0** [comment]
Feature flags are for (build time -- same as nuxt config) theme/extends layer customization. Like disabling a module that the layer has or adding page prefix (https://github.com/nuxt/framework/issues/3222#issuecomment-1077861575)

> I am not fond of the array syntax personally (the module ecosystem proves that the community prefer to level option in the nuxt.config)

I'm also advocating for explicit key for modules but it can be much straight forward to override them like this instead of more verbose `{ from: 'docus', overrides: {} }` syntax.

**Comment by Tahul** [comment]
This is an excellent idea! :)

Also, I really like the idea of being able to overwrite some parts of the extended layer before it gets merged.

That would be especially useful for things that are dependent on ordering like modules for instance.

**Comment by sawden** [comment]
I took a closer look at the extends feature over the past few days and found that it is currently not possible to switch between the different versions during the runtime, as only a final version of the app is being built. 

This means for the scenario described [here](https://github.com/nuxt/framework/issues/3222#issuecomment-1184656628), that a separate version of the app has to be deployed for each "theme". 

Could we implement switching between themes at runtime?
My suggestion would be to add a theme switch to the `<NuxtPage />` component.

```js
defineNuxtConfig({
   extends: [
      './base',
      {
            path: './themeB',
            name: 'theme-b'
       },
      {
            path: './themeC',
            name: 'theme-c'
       }
   ]
})
```

```html
<template>
    <NuxtPage extendsName="theme-b" />
</template>
```

This would take themes to the nuxt level 😉.
I open to any feedback and would try to implement the feature if desired.

**Comment by pi0** [comment]
Thanks for your feedback and ideas @sawden. Extends (and Theme alias) are built-time features coming with their cons and pros (Pro: not everything is possible to be changed on runtime and tree-shaked build time gives it. Con: Cannot change theme variants at runtime) 

I think this definitely worth to discuss more about runtime themeing (Now we have `app.config` could enable this too!)
