### ISSUE TITLE
overriding global metadata is not working on Netlify but works on Vercel. what is the issue?

### ISSUE THREAD

**Issue by jonmes** [nuxt/framework#5920]
### Environment

```
_SHELL=/bin/bash
WSL_DISTRO_NAME=Ubuntu-22.04
Package = {
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.5"
  }
}
```

### Reproduction

[Netlify Link](https://main--nuxt3-metadata.netlify.app/)
[Vercel Link](https://nuxt3-metadata-jelhk3jzp-jonmes.vercel.app/)
[Github Repo](https://github.com/jonmes/Nuxt3-Metadata.git)

### Describe the bug

when I try to override the global metadata of this app [repo](https://github.com/jonmes/Nuxt3-Metadata) which is deployed on netlify [deployed app Link](https://main--nuxt3-metadata.netlify.app/), Netlify won't update/override the global metadata with page specific metadata.  but this problem is not happening in vercel you can check here [Link](https://nuxt3-metadata-jelhk3jzp-jonmes.vercel.app/) I used the default configuration for deployment on both deployment services.

**Comment by johannschopplich** [comment]
Having a similar issue here – state isn't hydrated correctly on Netlify.

**Comment by jonmes** [comment]
> 

I have it working for about a day, then stacks, no more overriding. even on the exact file, I used on Vercel.
