### ISSUE TITLE
`rc.5` breaks hydrating payload data on Netlify/Vercel

### ISSUE THREAD

**Issue by johannschopplich** [nuxt/framework#5921]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `pnpm@7.5.1`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

- [GitHub repo](https://github.com/johannschopplich/nuxt3-fetch-error-repro)

- Since this seems to be specific to deployment on Vercel/Netlify, here a reproduction:
   👉 [Live demonstration of the bug](https://spectacular-semolina-dc26b5.netlify.app/)

#### Preamble

Source of the bug is the same to https://github.com/nuxt/framework/issues/5895. It does _not_ origin in a missing unique `key` from the `useFetch` composable. A key _is_ provided.

#### The Bug Itself

On Netlify the server-rendered Nuxt instance fetches custom data, but doesn't write it to the `nuxt.payload.data` key or even renders the page's template correctly.

Thus, the `useFetch` request runs again when the client loaded. 

### Additional context

- It seems to work when no `pages` is present and the `useFetch` runs directly in `app.vue`. Does the bug originate in https://github.com/nuxt/framework/pull/5709 maybe?
- It seems like a problem specific to Netlify. If I `pnpm run build` locally and serve the app, it is working.

**Comment by AgustinBanchio** [comment]
The same thing is happening with Vercel!

**Comment by johannschopplich** [comment]
The error persists in Nuxt 3 rc.6.

**Comment by cinob** [comment]
Same issue

**Comment by vinayakkulkarni** [comment]
Yep, facing the same issue with Nuxt content

**Comment by EmmyMay** [comment]
hi everyone. I am having the same issues on vercel. The page and its prop fails to render. 
![image](https://user-images.githubusercontent.com/31524469/182050557-76009812-8387-4c76-ba5b-ec8c7297d167.png)

**Comment by EmmyMay** [comment]
> hi everyone. I am having the same issues on vercel. The page and its prop fails to render. ![image](https://user-images.githubusercontent.com/31524469/182050557-76009812-8387-4c76-ba5b-ec8c7297d167.png)

It got fixed by a change in the folder structure which also changed the naming convention of the component.

**Comment by johannschopplich** [comment]
With the workaround from https://github.com/nuxt/framework/issues/6204#issuecomment-1201398080 this issue is resolved temporarily. 🎉

**Comment by pi0** [comment]
Thanks for confirming @johannschopplich 🚀 Then let's track it from linked issue in one place.

@vinayakkulkarni @EmmyMay Would you please also confirm if it fixes your issue and if not opening a new issue with reproduction? 🙏🏼

**Comment by EmmyMay** [comment]
@pi0 thanks for your prompt replies. Unfortunately, I am unable to submit a concise bug report as I would need to put the entire repo out and the project is proprietary. I am still getting the hydration mismatch errors on vercel. I will come back to attempting a reproduction bug as soon as I can. Apologies for not being able to do this right now.

**Comment by pi0** [comment]
No worries @EmmyMay and thanks! Do you mind using https://github.com/nuxt/framework/issues/6204#issuecomment-1201398080 and also switching your app to [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel)? It can narrow down if there is any other unknown issue.

**Comment by vinayakkulkarni** [comment]
> @pi0 thanks for your prompt replies. Unfortunately, I am unable to submit a concise bug report as I would need to put the entire repo out and the project is proprietary. I am still getting the hydration mismatch errors on vercel. I will come back to attempting a reproduction bug as soon as I can. Apologies for not being able to do this right now.

Yep, can confirm that the issues on netlify deployments are also not solved using this.
I’ve listed the steps here - https://github.com/nuxt/content/issues/1188#issuecomment-1174584187

**Comment by pi0** [comment]
Thanks for confirmation. Using nuxt edge and (soon upcoming) rc.7 you no longer need a workaround and deployments should start working out of the box.

**Comment by vinayakkulkarni** [comment]
> Thanks for confirmation. Using nuxt edge and (soon upcoming) rc.7 you no longer need a workaround and deployments should start working out of the box.

Looking forward to rc.7 🚀
