### ISSUE TITLE
typeCheck: true does nothing

### ISSUE THREAD

**Issue by StefanCardnell** [nuxt/framework#5923]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.5.0`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1) Create a new Nuxt 3 project with `nuxi init app`.
2) Add the following at the top of `app.vue`:

```
<script setup lang="ts">
  const add = function(a: number, b: number) {
    return a + b;
  }
  console.log(add(2,"3"));
</script>
```

IDE will warn that `add(2, "3")` is not valid.

3) Add the following to `nuxt.config.ts`:

```
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
    typescript: {
        strict: true,
        typeCheck: true
    }
})
```

3) Run `npm run dev`
4) At this point I experience an issue that TypeScript is not installed. I'm confused, because the documentation does not mention installing TypeScript manually to be able to able to perform type checking (https://v3.nuxtjs.org/guide/concepts/typescript). Nevertheless use `npm install typescript --save-dev`
5) Run `npm run dev` again. It is successful when it should complain that the types of the function arguments are incorrect.

### Describe the bug

1) TypeScript needs to be installed manually for type checking, the documentation doesn't mention this.
2) `typeCheck: true` in `defineNuxtConfig` isn't working.

### Additional context

I see the issue was already raised and closed here and the linked ticket is merged to rc5. However the issue still exists:

https://github.com/nuxt/framework/issues/5109

**Comment by Arideno** [comment]
Hi, the issue still exists on rc6

**Comment by danielroe** [comment]
@Arideno The fix will be included in the next RC, or you can test it now with the edge channel: https://v3.nuxtjs.org/guide/going-further/edge-channel/.

**Comment by StefanCardnell** [comment]
Hi @danielroe I seem to be having issues with `typecheck: true` in a brand new project.

```ts
// nuxt.config.ts
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  typescript: {
    strict: true,
    typeCheck: true
  }
})
```

Running `npm run build` produces the following error:

![image](https://user-images.githubusercontent.com/11324477/184546369-6c9babdc-b920-42a3-9f57-a06b9ac33cca.png)

Additionally `npm run dev` seems to pass, making me think typecheck on dev still isn't working. 

- Operating System: `Linux`
- Node Version:     `v18.5.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

**Comment by StefanCardnell** [comment]
Hi @danielroe seems to work now with `npm run dev` so thanks.

I noticed it won't work when using `ssr: false` in `nuxt.config.ts` - is this a known limitation?
