### ISSUE TITLE
Allow preventing `useFetch`/`useAsyncData` from firing immediately

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/framework#5942]
### Environment

n/a

### Reproduction

n/a

### Describe the bug

In my use case I'd find it particularily useful to prevent the `useFetch`/`useAsyncData` from firing immediately, as it has been implemented in the `useFetch` from VueUse:

https://vueuse.org/core/usefetch/#prevent-request-from-firing-immediately

... e.g. I'd still want to declare/prepare the call in the top level, but in scenarios when there is no logged in user and the request is only for the authorized ones, I can save the client from making an unnecessary request without having to wrap the call in a conditional statement.

**Comment by TheDutchCoder** [comment]
I think this is quite an essential feature to have, because currently you can't call data "on demand".

For example: saving data when clicking a "save" button. You can't actually do a post on demand currently with any of the composables.

**Comment by DamianGlowala** [comment]
What about introducing `use[Delayed/Deferred/OnDemand]Fetch` and `use[Delayed/Deferred/OnDemand]AsyncData`? My concern is, that the `useLazyFetch`/`useLazyAsyncData` might be often confused in combination with these.

@pi0, would you have any better solution nicely complimenting the set of already existing composables?

**Comment by pi0** [comment]
More thinking, if purpose is really the refrashable behavior of asyncData having an option wouldn't be a bad start at the end (otherwise we will end of with dosens of aliases).

**Comment by DamianGlowala** [comment]
completed in https://github.com/nuxt/framework/pull/5500

**Comment by sig9** [comment]
somewhat related..
I have a useFetch call that sets a watch and an  onRequest function in the options parameter.
When my onRequest function throws an error, the fetch function does not fetch anything. It fails silently. 
It is great because I didn't want it to fire without setting the right headers via the onRequest function.
