### ISSUE TITLE
Nuxt 3 rc.5 doesnt work with Vuetify!  Please help!

### ISSUE THREAD

**Issue by modys** [nuxt/framework#5948]
### Environment

- Nuxt v.3 rc.5 +
- Vuetify v.2.6.7 actually

### Reproduction

https://codybontecou.com/how-to-use-vuetify-with-nuxt-3.html#configure-nuxt-3-to-use-our-new-plugin

### Describe the bug

After install succesfull Nuxt 3. Everything working well. I saw the start screen "Welcome to Nuxt App" etc.. console without mistakes.. The next steps for using Vuetify, i found some Documentation from thirdparty who show how to install Vuetify and Nuxt 3.
But he use the Nuxt "rc1" edition.. And may this working for him, but not with my "rc5" edition.
Any ideas how to force this working?
Would be very thankful!

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by huang-julien** [comment]
should'nt you use vuetify 3 beta instead of 2.6.7 ?

**Comment by modys** [comment]
> Would you provide a reproduction? 🙏

Im not sure that i understand what i should do..  what meaning with "reproduction"?
Other way i can do it.

**Comment by danielroe** [comment]
Show what isn't working using https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz.

**Comment by modys** [comment]
> Show what isn't working using https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz. See https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction.
> 
> If this isn't a bug report, then it should probably be a discussion, where you can ask questions. I'm sure you've already checked out whether there are any example Vuetify projects posted by people there?

Actually i not found a working tandem of Nuxt + Vuetify. Each examples of this is Nuxt version 2+ with vuetify2. And that working fine.. But want to use new Technologies and for now i not found working dependencies. 
I guess that how [huang-julien] written above may this not working cuz Vuetify release was 2.6.7 but need to use it with Vuetify 3.. But in Vuetify 3 Docs, is written that 3 version is beta etc.. ohh that so difficult.. once working, other is not working!  https://ibb.co/jZFdkLT
https://ibb.co/fqQnJ1P

**Comment by huang-julien** [comment]
vuetify 3 is in beta ... for now. The release should be soon, vuetify 2 is only compatible with vue2/nuxt2 so you have to update to vuetify 3 to use it with nuxt 3 but you can already use the beta version.

**Comment by modys** [comment]
> vuetify 3 is in beta ... for now. The release should be soon, vuetify 2 is only compatible with vue2/nuxt2 so you have to update to vuetify 3 to use it with nuxt 3 but you can already use the beta version.

Yeahh i saw it right now. Thanks all for the help! Will try to install compatible version. Hope this work!
Thanks! :)
