### ISSUE TITLE
`h3` needs to be installed when using `pnpm install` without `--shamefully-hoist`

### ISSUE THREAD

**Issue by essarn** [nuxt/framework#5949]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `pnpm@7.5.1`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/essarn/nuxt-h3-pnpm

### Describe the bug

Everything should work as expected when using `pnpm` according to https://github.com/nuxt/framework/issues/5411 but this is not the case. The typing is incorrect for global shortcuts from `h3` such as `defineEventHandler` (in `server/api/test.ts`).

The solution is to install `h3` and the typing works correctly.

### Logs

```shell
Parameter '_event' implicitly has an 'any' type, but a better type may be inferred from usage.ts (7044)
```

**Comment by danielroe** [comment]
let's track in #5411
