### ISSUE TITLE
Not wrapping contents of `app.vue` in a single parent element allows Nuxt to render arbitrary files on the FS that would match the request URI

### ISSUE THREAD

**Issue by Voltra** [nuxt/framework#5960]
### Environment

RootDir: D:\tmp\napp                                                                                                                                                              21:58:47
Nuxt project info:                                                                                                                                                                21:58:47

------------------------------
- Operating System: `Windows_NT`
- OS Version : Windows 11 Family 21H2
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `npm@8.9.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Since I need to manipulate the file system on a pretty restricted area (aka its root), I don't think I could find anything to provide simple reproduction besides listing the steps.

1. Have a `/playlists/index.js` file
2. Run `npx nuxi init` anywhere (on Windows it must be on the same Disk/Drive)
3. `cd` in the project directory
4. Install dependencies
5. Change the template of `app.vue` to `<NuxtLayout><NuxtPage/></NuxtLayout>`
6. Create a `pages` folder
7. Make a `pages/index.vue` that just contains a script setup with `await navigateTo('/playlists');`
8. Make a `pages/playlists.vue` that contains a template with some sample content (anything)
9. `npm run dev`
10. Go to `localhost:3000`
11. Notice that you're redirected on `localhost:3000/playlists` as expected but what's displayed is the contents of the file at `/playlists/index.js` in the file system

### Describe the bug

When the "default" content of the `app.vue` file is not wrapped in a single parent element:
```html
<NuxtLayout>
  <NuxtPage/>
</NuxtLayout>

<!-- Instead of -->
<div>
  <NuxtLayout>
    <NuxtPage/>
  </NuxtLayout>
</div>
```

Nuxt can have a very weird behavior to say the least: if a JS filepath from the root of your FS matches the request URI, it will show the contents of that file instead of rendering the appropriate route's content.

I'm not so much concerned about having to wrap the contents of `app.vue` in a div, I'm extremely concerned about the fact that such behavior is even possible: Nuxt is reading a file that is outside of the project/current directory and displaying its content instead of using the known routes' components.

**Comment by danielroe** [comment]
This is Vite's behaviour - and don't worry - it's only in dev only.

**Comment by danielroe** [comment]
resolved by https://github.com/nuxt/framework/pull/7234.
