### ISSUE TITLE
500 Cannot set properties of undefined (setting 'pinia')

### ISSUE THREAD

**Issue by akahon** [nuxt/framework#5965]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `ssr`, `modules`, `modern`, `css`, `buildModules`, `runtimeConfig`, `preset`, `vite`, `builder`, `server`
- Runtime Modules:  `~/modules/home/index.ts`
- Build Modules:    `@pinia/nuxt@0.1.9`

### Reproduction

I can't provide a reproduction link 

### Describe the bug

I have successfully built project using `yarn build`. But when I ` yarn preview` Got an error!
![image](https://user-images.githubusercontent.com/34656195/179503081-ae84c0c7-5968-4f91-a82f-03953707d9f2.png)

### Additional context

I wanted to build the project and optimize it. When the project was successfully built vite builder generated only one CSS file. All the CSS files imported into the project were merged into one. But in the nuxt.config.ts file, I set csscodesplit to true inside vite config (build config) 
![image](https://user-images.githubusercontent.com/34656195/179504204-a7566998-1fbe-40da-a6eb-47c0510b9706.png)
Same problem with js files. Problem occurred on all nuxt versions: - Nuxt Version:     `3.0.0-rc.4` `3.0.0-rc.5` `3.0.0-rc.6`

**Comment by ImamAlfariziSyahputra** [comment]
You have to upgrade `@pinia/nuxt` package to the latest version, it would fix that error. https://github.com/nuxt/framework/issues/5955#issuecomment-1186442401

**Comment by danielroe** [comment]
Yes, things seem fine to me with your original reproduction. Feel free to raise a new issue and reproduction about what you are now experiencing.
