### ISSUE TITLE
Assets missing from final build if not directly imported in scss.

### ISSUE THREAD

**Issue by StefanCardnell** [nuxt/framework#5974]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.5.0`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I hope the image suffices. I started a new nuxt 3 project. I have `test.scss` importing `test2.scss` from a higher directory. `test2.scss` itself uses `images/test-img.png`. _However_ `test-img.png` does not appear in the final build files.

![image](https://user-images.githubusercontent.com/11324477/179620311-3d8a15a6-d66b-46cb-8ae5-73e12e408797.png)

If I move `test2.scss` in to the same directory as `test.scss`, then the image is included in the build files.

### Describe the bug

If a `scss` file imports another `scss` file in another directory, none of the asset files used in the second file are included in the final build.

### Additional context

I provide the minimal example but my real-world scenario is more complex. In reality `test2.scss` for me is a node module scss file and I have no control over changing its image path behaviour. So I have no control over updating `test2.scss`.

**Comment by danielroe** [comment]
**reproduction**: https://stackblitz.com/edit/github-16wtui-xvqtgv.

As far as I can tell this doesn't even work on dev, and it might possibly be an upstream issue with webpack's `enhanced-resolve` rather than Nuxt.

**Here's a reproduction without Nuxt**: https://stackblitz.com/edit/github-kzuz7c.

Would you raise an upstream issue with webpack? 🙏

**Comment by StefanCardnell** [comment]
Thanks @danielroe. For the record I'm using Vite build but I guess at some point during the build process `enhanced-resolve` is used?

With Vite builder `npm run build` passes without error. But with webpack builder `npm run build` produces an error indicating the image can't be resolved. Is the error being supressed with the Vite builder?

**Comment by danielroe** [comment]
Oh, my mistake. Looks like I used a spare reproduction from a webpack project. Let me look again.
