### ISSUE TITLE
`useFetch` does not account for params change

### ISSUE THREAD

**Issue by nlhkh** [nuxt/framework#5993]
### Environment

Nuxt CLI v3.0.0-rc.6                                                                                              16:22:47
RootDir: *                                  16:22:47
Nuxt project info:                                                                                                16:22:47

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `build`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-brbcqx?file=pages/index.vue

### Describe the bug

When we use useFetch with the same URL, but with different query string parameters, changing the parameters does not trigger a new fetch. As you can see in the repo, navigating from Page One to Page Two, and back, does trigger the composable `useData`, but the data is not fetch given new params. If you navigate to `/` or `/page2` directly, then we can see the correct data.

Additionally, using the querystring directly in the URL also results in the same bug.

**Comment by agracia-foticos** [comment]
Same problem!!! The fetch function returns always data from first fetch!

**Comment by KubesDavid** [comment]
Try adding a unique key to each `useFetch` call like this:
```typescript
export function useData(param: string) {
  console.log('useData called');
  return useFetch<string>('/api/data', {
    params: {
      page: param,
    },
    key: param,
  });
}
```

**Comment by nlhkh** [comment]
> Try adding a unique key to each `useFetch` call like this:
> 
> ```ts
> export function useData(param: string) {
>   console.log('useData called');
>   return useFetch<string>('/api/data', {
>     params: {
>       page: param,
>     },
>     key: param,
>   });
> }
> ```

Yes, that is the way I handle this at the moment. However, as per the description of `useFetch`, the key is automatically generated based on the options, so either we take into account query parameters as well, or change the description.

**Comment by agracia-foticos** [comment]
I am launching useFetch with these parameters and it keeps failing me

return useFetch(url, options);


options {
  params: {
    lang: 'es',
    order: '-DATE',
    rating: '4,5',
    limit: 3,
    expand: 'images,web_user'
  },
  initialCache: false,
  key: '1658326110838' //ITS A TIMESTAMP
}

**Comment by danielroe** [comment]
@agracia-foticos That is likely a different issue from this one... Would you create a new issue with a reproduction? 🙏

**Comment by agracia-foticos** [comment]
> @agracia-foticos That is likely a different issue from this one... Would you create a new issue with a reproduction? pray


It is the same incidence.

When I use multiple useFetch, it always returns the result of the first one.

As you have commented, I have added the initialCache and the key but it still gives me the same error

**Comment by nlhkh** [comment]
> Resolved! I use this code:
> 
> 
> 
> import { hash } from 'ohash'
> 
> 
> 
> and send key with this code
> 
> 'key' : hash(['api-fetch', url, params]),
> 
> 
> 
> 
> 
> 
> 
> 

This seems like a good candidate to auto-generate a key.

**Comment by ROBJkE** [comment]
> Resolved! I use this code:
> 
> import { hash } from 'ohash'
> 
> and send key with this code 'key' : hash(['api-fetch', url, params]),

In my opinion that whole key stuff comes with rc5 is a downgrade. To handle random key generation by yourself is bad DX.  
But thanks for this workaround. My workaround is stay with rc4.
