### ISSUE TITLE
UseFetch problem with returned data

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/framework#6011]
### Environment

"devDependencies": {
    "@nuxt/postcss8": "^1.1.3",
    "@nuxtjs/tailwindcss": "^5.2.0",
    "autoprefixer": "^10.4.7",
    "postcss": "^8.4.14"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^6.1.1",
    "@headlessui/vue": "^1.6.7",
    "@pinia/nuxt": "^0.1.9",
    "nuxt": "3.0.0-rc.6",
    "pinia": "^2.0.14",
    "vue": "^3.2.37",
    "vue-i18n": "^9.1.10"
  },

### Reproduction

Launching many useFetch

### Describe the bug

We are throwing several useFetch in a row to different urls.

The problem is that currently the useFetch is returning for all the result of the first useFetch

**Comment by danielroe** [comment]
What is your code?

**Comment by danielroe** [comment]
Ah. Let's track in https://github.com/nuxt/framework/issues/5993 in that case.
