### ISSUE TITLE
`event.req.headers.cookie` Returns `undefined` Even When Defined on `event.req.headers`

### ISSUE THREAD

**Issue by Angad-The-Coder** [nuxt/framework#6015]
### Environment
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-tqtf46?file=server/api/profiles/select.post.ts

### Describe the bug

I've set up a route at `~/server/api/login.post.ts` that needs to query another route I set up at `~/server/api/profiles/select.post.ts` with some cookies. The way I have done so is by writing the following code in `login.post.ts`:
```ts
// ...
export default defineEventHandler(async (event) => {
  // ...
  await $fetch("/api/profiles/select", {
    method: "POST",
    headers: {
      cookie: cookies, // cookies corresponds to a string containing valid cookies
    },
    body: {
      // request body
    },
  });
  // ...
}
// ...
```
I then *attempt* to use the cookie passed from `login.post.ts` in my `profiles/select.post.ts` file like so:
```ts
// ...
export default defineEventHandler(async (event) => {
  const cookie = event.req.headers.cookie;
  // code that uses this cookie
}
// ...
```
In my `select.post.ts` file above, `event.req.headers.cookie` returned `undefined`, so I ran `console.log(event.req.headers)` to see what was going on. The output was
```js
{
  accept: "application/json",
  'content-type': 'application/json',
   cookie: '{my cookie (not undefined)}'
}
```
So, even though the cookie key clearly shows up upon printing `event.req.headers`, for whatever reason, `event.req.headers.cookie` returns `undefined`. I attempted to use the [`useCookie` utility](https://www.jsdocs.io/package/h3#useCookie) but that also returned `undefined`. Using the [`useCookies` utility](https://www.jsdocs.io/package/h3#useCookies) returned an empty object.

Would greatly appreciate any insight into what may be going on.

### Additional context

The bug seems to come about the moment I add a `body` to my `$fetch` request in `login.post.ts`. You can see that commenting out [lines 11-13 in my `login.post.ts` file](https://stackblitz.com/edit/nuxt-starter-tqtf46?file=server%2Fapi%2Flogin.post.ts%3AL11-L13) removes the bug as `event.req.headers.cookie` no longer returns `undefined` and corresponds to its appropriate value. That being said, the `useCookie` and `useCookies` utilities continue to return incorrect values.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/5718, where you can also see a workaround.
