### ISSUE TITLE
[nuxt] [request error] __vite_ssr_import_1__ is not defined #10591

### ISSUE THREAD

**Issue by amine-elghazali** [nuxt/framework#6018]
### Environment

```
Nuxt CLI v3.0.0-rc.6                                                                                                         21:50:58
RootDir: C:\Users\dell\Desktop\NEWPROJS\Barreau_App_Web                                                                      21:51:07
Nuxt project info:                                                                                                           21:51:07

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `head`, `css`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                             21:51:07

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org
```

### Reproduction

Can't provide a repository cause it's a private one

### Describe the bug

I have an error when trying to implement FullCalendar in my Nuxt3js project , the error is :
![image](https://user-images.githubusercontent.com/81489914/180079527-62b13937-d65b-49a9-af40-05fc1d4413d9.png)

I have no clue what I have to do , please some help

### Logs

![image](https://user-images.githubusercontent.com/81489914/180080009-21f2ce62-fbfa-46e4-9e04-04b320bfed95.png)

**Comment by danielroe** [comment]
Please provide a minimal reproduction using https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz.

**Comment by amine-elghazali** [comment]
https://stackblitz.com/edit/github-psxsqf

**Comment by danielroe** [comment]
Several comments.

1. if you register a component in a client-only plugin, you can't render it on SSR. instead, it needs a client only wrapper. (Or you can enable `experimental.treeshakeClientOnly` if you are on edge releases to tree-shake out the children/slots of `<ClientOnly>`.
2. You shouldn't use a nuxt plugin to 'provide' the component - instead you can just use `nuxtApp.vueApp.component()` function.
3. If you do use provide, it gets prefixed with `$`.

**Comment by amine-elghazali** [comment]
Well, I tested somethings , but it doesn't seems to work :/ I still got the same issue , also the <ClientOnly> Doesn't seems to work, I tried to wrap my component in a <client-only> </client-only> , But Nothing seems to work.
Also, I'm new to Nuxt , that's my first project ever dealing with Nuxt  😞 so can u clarify more please 🙏🏾

**Comment by amine-elghazali** [comment]
The problem is that I was wrapping the div inside the component where I have the FullCalendar Tag , When I wrap the whole Component before calling it , the error removed finally , and now it's seems every thing is working right . 
Thank u so much for ur help 👍🏾 💯
