### ISSUE TITLE
NuxtLayout causes error in layouts

### ISSUE THREAD

**Issue by mtskf** [nuxt/framework#6021]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `ssr`, `buildModules`, `modules`, `plugins`, `storyblok`, `algolia`, `app`, `loading`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.0`
- Build Modules:    `@storyblok/nuxt@4.0.1`, `@nuxtjs/algolia@1.0.3`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-2upr7p?file=layouts%2Fdefault.vue

### Describe the bug

NuxtLayout in layout/default.vue causes error:
```
[nuxt] [request error] Maximum call stack size exceeded
```

**Comment by danielroe** [comment]
You are loading the default layout within your default layout, which causes an infinite rendering loop. If you explain what you are trying to do, perhaps I can give some advice.

**Comment by vanling** [comment]
@mtskf try changing layout into this.
```
<template>
<div>
  
    <NuxtLoadingIndicator />
    <nav class="flex align-center gap-4 p-4">
      <NuxtLink to="/" class="n-link-base"> Home </NuxtLink>
      <NuxtLink to="/about" class="n-link-base"> About </NuxtLink>
    </nav>
    <slot/>

  </div>
</template>
```

**Comment by mtskf** [comment]
Thanks, for your advice!
