### ISSUE TITLE
code splitting on build is not working

### ISSUE THREAD

**Issue by Sherzod06** [nuxt/framework#6023]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `modules`, `ssr`, `modern`, `build`, `css`, `buildModules`, `runtimeConfig`, `vite`, `builder`, `webpack`
- Runtime Modules:  `@nuxt/image-edge@1.0.0-27628766.3629b9a`, `~/modules/home/index.ts`, `~/modules/product/index.ts`, `~/modules/catalog/index.ts`, `~/modules/cart/index.ts`, `~/modules/common/index.ts`, `~/modules/productRowSlider/index.ts`, `~/modules/productCard/index.ts`,  `~/modules/header/index.ts`, `~/modules/shop/index.ts`, `~/modules/staticPages/index.ts`, `~/modules/notifications/index.ts`
- Build Modules:    `@pinia/nuxt@0.3.0`

### Reproduction

Can't provide reproduction. Cause it's private

### Describe the bug

I m developing project in DDD pattern. In my project every page is seperate module. I have imported every css (scss) files seperately on its module. In vite configs I have set build.cssTarget to true and lib mode false. I have built my project with vite bundler. But bundler generated files strangely. 
As you can see on the photo below, bundler generated only 4 css files. All the styles are merged into entry.611f2b22.css file except other 3 css files on the photo. But I have imported css files seperately inside its page or components.
![image](https://user-images.githubusercontent.com/65542674/180139617-3a56ac61-4cb5-4161-88b6-f405f8d2201e.png)

### Additional context

Actually I need to speed up project. But my performance score on Lighthouse is below 45 on average and in some pages even below 20. I need to split all the js and css files as much as possible, need to reduce unused styles on every page. That is why code splitting is very important for me. I have tried wite optimal vite config. But I think some vite configs are not working or I am using it in a wrong way. Could somebody help me with setting up vite config?
![image](https://user-images.githubusercontent.com/65542674/180141625-a07289e7-5a23-4a45-97d9-ebeb3615d3c9.png)

My nuxt config file:
![image](https://user-images.githubusercontent.com/65542674/180143150-61a2378c-dde1-490f-94cb-1a87b02e2d8a.png)

Also I have tried to build with webpack and on nuxt config set builder to 'webpack'. But it didn't help me and some errors occured during build.

**Comment by akahon** [comment]
I got the identically same problem

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by Sherzod06** [comment]
> Would you provide a reproduction? 🙏

Reproduction link:
https://stackblitz.com/edit/github-xzc73f?file=nuxt.config.ts
I leave also github link:
https://github.com/Sherzod06/modular-nuxt3-design

`yarn install`
`yarn build`
`yarn start`

In that case in generated only one css file. I can't find the problem i have imported css (scss) files in many ways. You can find it in the code. But it couldn't help me or I am doing something wrong.
Also when I built vit generated m

**Comment by Sherzod06** [comment]
Sorry I accidentally clicked to close with comment button

**Comment by akahon** [comment]
I have the same bug, no one else has come across this?

**Comment by MohammadKhalaji** [comment]
Are you sure this issue is fixed? I had the same issue and updating from RC6 to RC8 didn't change anything.

**Comment by danielroe** [comment]
@MohammadKhalaji If you are encountering something similar, or the same, please open a new issue with a reproduction. 🙏
