### ISSUE TITLE
auto import is not working on server directory codes when build

### ISSUE THREAD

**Issue by lastmirage** [nuxt/framework#6024]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.14.0`
- Builder:          `vite`
- User Config:      `typescript`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

add this to nuxt.config.ts

`typescript: {
    strict: true,
    typeCheck: true,
  },`

npm run build is fail with below message

`ERROR(TypeScript)  Cannot find name 'defineEventHandler'.`

### Describe the bug

ERROR(TypeScript)  Cannot find name 'defineEventHandler'.

1 | export default defineEventHandler(async (event) => {
   |                ^^^^^^^^^^^^^^^^^^
2 |     return 'test !'
3 | })
4 |

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by lastmirage** [comment]
@danielroe you can check with this repo

[https://github.com/lastmirage/build_error](https://github.com/lastmirage/build_error)

and I found more detail info

in nuxt.config.ts, 

if I set both option "typescript" and "build", the problem occurred

if I remove any one option, problem is not occurred
