### ISSUE TITLE
Top-level await not available for Target ES2019 - TSConfig shows ESNEXT

### ISSUE THREAD

**Issue by folson-csi** [nuxt/framework#6040]
### Environment

![nuxi-env](https://user-images.githubusercontent.com/94009693/180256667-9982da5f-16d6-44cc-a4d9-ca14d7d355a5.png)

### Reproduction

import sqlite3 from "sqlite3";
import { open } from "sqlite";

sqlite3.verbose();

const DB_FILENAME = `${process.cwd()}/server/db/ats-sample.db`;

try {
  const db = await open({
    filename: DB_FILENAME,
    driver: sqlite3.Database,
  });
} catch (e) {
  console.log("DBERR:", e);
}

### Describe the bug

I can't use top level await in my nuxt program, however ESNext is enabled in the tsconfig. The program will actually still run, but I get an error each time.

### Additional context

.nuxt/tsconfig.json

// Generated by nuxi
{
  "compilerOptions": {
    "jsx": "preserve",
    **"target": "ESNext",**
    "module": "ESNext",
    "moduleResolution": "Node",
    "skipLibCheck": true,
    "strict": false,
    "allowJs": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "types": [
      "node"
    ],
    "baseUrl": "..",
    "paths": {
      "~~": [
        "."
      ],
      "~~/*": [
        "./*"
      ],
      "@@": [
        "."
      ],
      "@@/*": [
        "./*"
      ],
      "~": [
        "."
      ],
      "~/*": [
        "./*"
      ],
      "@": [
        "."
      ],
      "@/*": [
        "./*"
      ],
      "assets": [
        "assets"
      ],
      "public": [
        "public"
      ],
      "#app": [
        "node_modules/nuxt/dist/app"
      ],
      "#app/*": [
        "node_modules/nuxt/dist/app/*"
      ],
      "vue-demi": [
        "node_modules/nuxt/dist/app/compat/vue-demi"
      ],
      "#head": [
        "node_modules/nuxt/dist/head/runtime"
      ],
      "#head/*": [
        "node_modules/nuxt/dist/head/runtime/*"
      ],
      "#components": [
        ".nuxt/components"
      ],
      "#imports": [
        ".nuxt/imports"
      ],
      "#build": [
        ".nuxt"
      ],
      "#build/*": [
        ".nuxt/*"
      ]
    }
  },
  "include": [
    "./nuxt.d.ts",
    "../**/*"
  ]
}

### Logs

```shell
ERROR  Rollup error:  Transform failed with 1 error:                                                                                                                                                                                          nitro 09:40:37  
{cwd}\server\db\dao.ts:8:13: ERROR: Top-level await is not available in the configured target environment ("es2019")

  server\db\dao.ts:8:13: ERROR: Top-level await is not available in the configured target environment ("es2019")
  at failureErrorWithLog (node_modules\esbuild\lib\main.js:1605:15)
  at node_modules\esbuild\lib\main.js:1394:29
  at node_modules\esbuild\lib\main.js:666:9
  at handleIncomingPacket (node_modules\esbuild\lib\main.js:763:9)
  at Socket.readFromStdout (node_modules\esbuild\lib\main.js:632:7)
  at Socket.emit (node:events:390:28)
  at Socket.emit (node:domain:475:12)
  at addChunk (node:internal/streams/readable:315:12)
  at readableAddChunk (node:internal/streams/readable:289:9)
  at Socket.Readable.push (node:internal/streams/readable:228:10)
```

**Comment by danielroe** [comment]
To change the esbuild target for your nitro build, you can do:

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  nitro: {
    esbuild: {
      options: {
        target: 'esnext'
      }
    }
  }
})
```

However, it is not advised to do so. Instead, I would recommend using `defineLazyEventHandler` to run the setup task for your handler.

**Comment by folson-csi** [comment]
Fantastic, thanks Daniel!

**Comment by AndrewBogdanovTSS** [comment]
Another way I was able to achieve that is by creating nitro.config.ts
```
import { defineNitroConfig } from 'nitropack'

export default defineNitroConfig({
  esbuild: {
    options: {
      target: 'esnext'
    }
  }
})
```
@danielroe but the main question: why Nitro doesn't inherit settings from projects tsconfig.json? 🤔

**Comment by danielroe** [comment]
You should not create a separate nitro config file. Instead, set any properties needed in the nitro key in your Nuxt config.

**Comment by AndrewBogdanovTSS** [comment]
@danielroe is it some outdated approach? It is still working
