### ISSUE TITLE
Fatal Error when using hot reload with specific server db connection file

### ISSUE THREAD

**Issue by folson-csi** [nuxt/framework#6041]
### Environment

![nuxi-env](https://user-images.githubusercontent.com/94009693/180257766-ce3ccaae-0cad-461c-9a13-9af5024837a8.png)

### Reproduction

The problem occurs when I have the application runnning, save the following file, and have a window open to my application on a page that uses the db connection.

import sqlite3 from "sqlite3";
import { open } from "sqlite";

sqlite3.verbose();

const DB_FILENAME = `${process.cwd()}/server/db/ats-sample.db`;

try {
  const db = await open({
    filename: DB_FILENAME,
    driver: sqlite3.Database, // maybe use cached.Database here...
  });
} catch (e) {
  console.log("DBERR:", e);
}

console.log("DAO");

export default db;

### Describe the bug

The application crashes when I am using hot reload and make changes to the application.

### Additional context

This error could be coming from the sqlite/sqlite3 imports, so feel free to ignore this if nothing is found.

### Logs

```shell
FATAL ERROR: Error::ThrowAsJavaScriptException napi_throw
 1: 00007FF7CCF2013F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112495
 2: 00007FF7CCEAF396 DSA_meth_get_flags+65526
 3: 00007FF7CCEB024D node::OnFatalError+301
 4: 00007FF7CCEAFA49 DSA_meth_get_flags+67241
 5: 00007FF7CCEDFECC napi_fatal_error+156
 6: 00007FFEBB5319D7
 7: 00007FFEBB531D96
 8: 00007FFEBB53E685
 9: 00007FF7CCEDD83C node_module_register+2636
10: 00007FF7CCF82AB0 uv_timer_stop+736
11: 00007FF7CCF82C87 uv_timer_stop+1207
12: 00007FF7CCF7F25B uv_async_send+331
13: 00007FF7CCF7E9EC uv_loop_init+1292
14: 00007FF7CCF7EB8A uv_run+202
15: 00007FF7CCF4DC95 node::SpinEventLoop+309
16: 00007FF7CCDE8660 v8::internal::wasm::SignatureMap::Freeze+35776
17: 00007FF7CCDE3CB8 v8::internal::wasm::SignatureMap::Freeze+16920
18: 00007FF7CCF6F36D uv_poll_stop+557
19: 00007FF7CDD80C60 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
20: 00007FFF19EC7034 BaseThreadInitThunk+20
21: 00007FFF1A002651 RtlUserThreadStart+33
```

**Comment by danielroe** [comment]
That error looks like a native Node error. I would guess that it was a Node ESM bug (cc: @pi0).

**Comment by pi0** [comment]
A reproduction would be nice but I've spotted same issue with other bindings (libsharp for image module) when reloading worker for multiple times. Seems a issue with native esm workers....
