### ISSUE TITLE
Auto-imports are not working with template Pre-processors (pug)

### ISSUE THREAD

**Issue by sawden** [nuxt/framework#6049]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.5.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Clone [this repository](https://github.com/sawden/nuxt-3-pug)

or

Create a new nuxt 3 project and use pug as Pre-processor ([Nuxt 2 docs](https://nuxtjs.org/docs/features/configuration/#pre-processors))
1. npx nuxi init nuxt-pug
1. cd nuxt-pug
1. npm install & npm install --save-dev pug
1. create some components

### Describe the bug

It seems that the auto imports do not work properly with template pre-processors. Built-in components like 'NuxtLink' and custom components cannot be resolved inside of pug files.

Error message when using Built-in components (NuxtLink):
```bash
...
[Vue warn]: Failed to resolve component: NuxtLink
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
...
```

Error message when using custom components:
```bash
...
[Vue warn]: Failed to resolve component: AppLogo
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: AppButton
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
...
```

**Comment by danielroe** [comment]
cc: @antfu
