### ISSUE TITLE
Duplicated path prefix with static rendering and RC6

### ISSUE THREAD

**Issue by apss-pohl** [nuxt/framework#6058]
### Environment

-----------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.6-27641313.416f98b`
- Package Manager:  `yarn@3.2.1`
- Builder:          `vite`
- User Config:      `srcDir`, `ssr`, `app`, `publicRuntimeConfig`, `nitro`, `alias`, `typescript`, `hooks`, `build`, `css`, `buildModules`, `telemetry`, `intlify`, `dayjs`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.3.0`, `@intlify/nuxt3@0.2.3`, `@vueuse/nuxt@8.9.4`, `@nuxtjs/dayjs@1.4.1`
------------------------------

### Reproduction

Run a static build with : nuxi generate

### Describe the bug

Duplicated prefix in the .output/public/index.html
```ts
<head >
  <link rel="stylesheet" href="./_nuxt/_nuxt/entry.d20389ae.css">
</head>
```

**Comment by danielroe** [comment]
Thanks @apss-pohl! Do you have a custom `app.buildDir`?

**Comment by apss-pohl** [comment]
https://stackblitz.com/edit/github-c88iyh?file=package-lock.json,package.json&theme=light

run yarn dev
then you can cat dist/index.html and find something like:
<link rel="modulepreload" href="./_nuxt/_nuxt/entry.9fef1731.mjs" as="script" crossorigin>

Root cause is setting "NUXT_APP_BASE_URL=./"

**Comment by nikolas-psaroudakis-rokoko** [comment]
This happens with the webpack builder as well

**Comment by danielroe** [comment]
@nikolas-psaroudakis-rokoko Would you open a new issue with a reproduction?

**Comment by nikolas-psaroudakis-rokoko** [comment]
I'll open a new issue in the evening, until then I would like to describe that with the webpack builder, it seems to be worse than with vite.

The generated css, js files are placed in `.output/public/_nuxt/_nuxt` but the generated `index.html` file points to `_nuxt` instead of `_nuxt/_nuxt` ( which seems to be the case with vite), so the site turns out to be broken
