### ISSUE TITLE
Pinia not working - No active Pinia

### ISSUE THREAD

**Issue by mwohlan** [nuxt/framework#6059]
### Environment

Stackblitz - Nuxt v3.0.0-rc.6-27641313.416f98b 

### Reproduction

[https://stackblitz.com/edit/github-zkrdaf?file=app.vue](https://stackblitz.com/edit/github-zkrdaf?file=app.vue)

Type something in the input and go the page dynamic [hi].vue page where the pinia store is being called

### Describe the bug

When using Pinia the following message error message appears:

> getActivePinia was called with no active Pinia. Did you forget to install pinia?

**Comment by mhsdev** [comment]
maybe forgot to use setup()

**Comment by Aleksandr-om** [comment]
@mhsdev you need to update Pinia to the latest version
```
"@pinia/nuxt": "^0.3.0",
"pinia": "^2.0.16",
```

**Comment by wadaahmad** [comment]
why u define store but never create a state.?
https://github.com/antfu/vitesse-nuxt3/blob/main/composables/user.ts
i think, it's miss used to create logic like ref or computed in pinia

**Comment by danielroe** [comment]
It seems that you need to ensure pinia is included when optimising dependencies.

```js
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
  vite: {
    optimizeDeps: {
      include: ['pinia'],
    },
  },
});
```

cc: @pi0
