### ISSUE TITLE
Checker is not works when app is in sub directory

### ISSUE THREAD

**Issue by mhfeizi** [nuxt/framework#6064]
Checker is not works when app is in sub directory:

https://github.com/nuxt/framework/blob/eff6b0c4caf7a4daff7bf0f17599caf8246b1a91/packages/vite/src/server.ts#L93

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by danielroe** [comment]
Here are two working examples:

* https://stackblitz.com/edit/github-c1nhqh
* https://stackblitz.com/edit/github-c1nhqh-imr9pw

**Comment by pi0** [comment]
(for the context this issue was happening only for production build when `vue-tsc` CLI is used)
