### ISSUE TITLE
 The const variable in **<script setup>**  doesn't expose correct  in **production** env when @nuxt/vite-builder 3.0.0-rc.3 upgrade to @nuxt/vite-builder 3.0.0-rc.6

### ISSUE THREAD

**Issue by aborn** [nuxt/framework#6065]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.4`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Here is a demo page. It's works fine when runing this demo page in **dev** env. But it works different in **production** env.
```vue
<template>
  <div>
    <h1>Demo page</h1>
    <p>{{ vMsg }}</p>
    <button @click="onClickVMsg">MsgBtn</button>
  </div>
</template>

<script setup>
const vMsg = ref("hello msg")
</script>

<script>
export default {
  methods: {
    onClickVMsg() {
      console.log(this.vMsg)
      this.vMsg = 'currentTime==>' + new Date()
    }
  }
}
</script>

```

The production deploy as follows:
```shell
yarn build
node .output/server/index.mjs
```

### Describe the bug

The **<script setup>** works different behavior between *dev* env and *production* env.  The const variable in **<script setup>**  doesn't expose correctly when nuxt upgrade from **3.0.0-rc.3** to **3.0.0-rc.6**.  I work around found out that the problem is @nuxt/vite-builder 3.0.0-rc.3 upgrade to @nuxt/vite-builder 3.0.0-rc.6 . 

The demo page const variable *vMsg* doesn't expose correctly in production env (after *yarn build*).

### Additional context

Demo source code project：
https://github.com/aborn/playgrounds/tree/main/nuxt-demo
or
https://stackblitz.com/edit/github-dfvwhg?file=pages/index.vue

**Comment by danielroe** [comment]
I think this is the behaviour you're reporting: https://github.com/vuejs/core/issues/6242.

I think we can track there, but particularly note https://github.com/vuejs/core/issues/6242#issuecomment-1179330594.
