### ISSUE TITLE
Running 2 Nuxt handlers (different projects) in the same environment mixes static urls

### ISSUE THREAD

**Issue by bros4president** [nuxt/framework#6090]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.6.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I've determined where the issue stems from. A reproduction would need deployments to AWS Lambda, but I could provide a Serverless Framework project if required.

### Describe the bug

I found myself trying to run 2 Nuxt handlers in the same AWS Lambda environment:

```node
// My custom AWS lambda handler.js

import tldjs from 'tldjs';
import { handler as nuxtHandlerA } from '../clients/A/.output/server/index.mjs';
import { handler as nuxtHandlerB } from '../clients/B/.output/server/index.mjs';

export async function handler(event, context) {

  const subdomain = tldjs.getSubdomain(event.requestContext?.domainName);
  const clientType = await clientTypeFromSubdomain(subdomain) // Arbitrary function that maps a subdomain to a clientType

  if (clientType === 'A') return await nuxtHandlerA(event, context);
  if (clientType === 'B') return await nuxtHandlerB(event, context);

  return {
    statusCode: 404,
  };
}
```

Both `.output` folders were built with the `'aws-lambda'` nitro preset and `serveStatic: true`.

The problem I'm facing is that the static path of `clientA` is getting overwritten by the static path of `clientB`, **at runtime**, resulting in requests to assets in `clientA` failing due to files not found (because they're being looked up in  the wrong static path).

**I've found that this is due to the static path being derived from `globalThis._importMeta_.url`**, where the `server/index.mjs` path for a project is stored. Being a global state, it gets overwritten up to the last imported Nuxt project.

This is where the project's `server/index.mjs` path is set globally:
```node
// .output/server/index.mjs
...
globalThis._importMeta_={url:import.meta.url,env:process.env}
export { h as handler } from './chunks/aws-lambda.mjs';
...
```

This is where the static path is derived from global state to access an asset:
```node
// .output/server/chunks/aws-lambda.mjs
...
function readAsset (id) {
  const serverDir = dirname(fileURLToPath(globalThis._importMeta_.url));
  return promises.readFile(resolve(serverDir, assets[id].path))
}
...
```
---------------------

### Additional context

Honestly I don't know if this is a bug or a feature. In the latter case then I wouldn't know what is the best way to achieve this setup.

- Manually overwriting `globalThis._importMeta_` before each handler call sounds like it would break sooner than later.
- Hosting statics in a CDN would be a good specific solution, but I have no assurance that the rest of the projects don't depend on this global state now or in the future.
- Deploying to separate lambdas is not desired since I still need one as a middleware to decide what project to run based on subdomain. This would add the latency of calling a Nuxt project in another lambda.

Also I might be incurring into the XY problem. [The underlying problem I'm trying to solve is detailed in this discussion](https://github.com/nuxt/framework/discussions/6057)

Thanks for your time :)!

**Comment by danielroe** [comment]
Source of the line in question is https://github.com/unjs/nitropack/blob/main/src/rollup/plugins/import-meta.ts.

Possibly you could use workers to run each nitro server in different context: e.g. https://github.com/unjs/nitropack/blob/main/src/dev/server.ts#L29-L54.

More generally, I think it's fair to say that we don't support multiple nitros/runtime nuxt running at the same time in the same context for reasons like this, but tagging in @pi0 for his thoughts.

**Comment by pi0** [comment]
Yes, I would also recommend using a Node.js worker to run each Nuxt server instance isolated. Both client and server side of Nuxt 3 are assuming to run in a single instance environment. Including, core of hooks that depends on a unique singleton instance in globalThis.
