### ISSUE TITLE
Vue Devtools not working with starter on Github codespace

### ISSUE THREAD

**Issue by upepo-mwindaji** [nuxt/framework#6096]
### Environment

RootDir: /workspaces/nuxt3
Nuxt project info:
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `dev`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/upepo-mwindaji/nuxt3

### Describe the bug

Chrome devtools does not work when running `yarn dev`  on starter template within Github codespace

### Additional context

I have tried running the same on local machine and everything works fine

I have tried both version of Vue Devtools: current and beta
I have tried on Google cloud VM, behavior is the same
I have tried on rc4 and rc5 also did not work
I have tried adding following configurations: 
`{
    dev: true,
    vite: {
        mode: 'development'
    }
}`
I have tried running with yarn and pnpm
No issue running Nuxt 2 on those environments

Might be related to #2284 

![Screenshot 2022-07-23 at 22 24 12](https://user-images.githubusercontent.com/5933853/180638937-6eae7bc2-eb99-4499-938c-a1019c851ad5.png)

**Comment by danielroe** [comment]
I was not able to reproduce this, though note that I did need to set vite.server.hmr.protocol to `wss`.

```js
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  vite: {
    server: {
      hmr: {
        protocol: 'wss'
      }
    }
  }
})
```

See some debugging steps [here](https://github.com/nuxt/framework/issues/2284#issuecomment-1132160740) - particularly trying using a clean Chrome profile.

**Comment by upepo-mwindaji** [comment]
I retried adapting the vite configuration as you suggested and it worked indeed.
