### ISSUE TITLE
allow interacting with build manifest via hook

### ISSUE THREAD

**Issue by ThornWalli** [nuxt/framework#6102]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.11.0`
- Builder:          `webpack`
- User Config:      `modules`, `speedkit`, `vite`, `webpack`, `build`
- Runtime Modules:  `()`
- Build Modules:    `-`
------------------------------

### Reproduction

Define a hook call to `render:resourcesLoaded` in a module.

### Describe the bug

The hook is not fired.

### Additional context

I had a look and found out that this hook is defined in the scheme of Nuxt 3. 

https://github.com/nuxt/framework/blob/8c2c80e43e80cd8f1c4246d7563214fa695a3e98/packages/schema/src/types/hooks.ts#L134

https://github.com/nuxt/framework/search?q=render%3AresourcesLoaded

But unfortunately there is no call.

**Nuxt 2 equivalent:**
https://github.com/nuxt/nuxt.js/blob/b0147772ec98568b28ae80a7e97eca3381aa6a4e/packages/vue-renderer/src/renderer.js#L133

I hope this one is just missing at the moment 🙂

**Comment by danielroe** [comment]
This hook is not present in Nuxt 3, as there have been considerable changes in the rendering lifecycle between Nuxt 2 -> 3. The hooks in that portion of the schema refer to Nuxt 2 (for use with modules that also support Nuxt 2): https://github.com/nuxt/framework/blob/8c2c80e43e80cd8f1c4246d7563214fa695a3e98/packages/schema/src/types/hooks.ts#L133-L143.

What is your desired use case - i.e. what are you trying to do within `render:resourcesLoaded`?

**Comment by ThornWalli** [comment]
We provide in `nuxt-speedkit` the option to remove the assets in the `client`/`modern` manifest. 
Thus the loading of unnecessary chunks was reduced.

The goal was to keep the number of initial scripts small.

Real example:

**Without:**

![image](https://user-images.githubusercontent.com/8287751/180789449-9ea1f145-2b69-4f86-9968-a39eeb01b945.png)

**With:**

![image](https://user-images.githubusercontent.com/8287751/180790551-1a289dc5-9a77-4666-bf76-9922796303d3.png)

Now it would be interesting to know 🙂 If there is something similar with `nuxt@3`, or we don't run into the problem anymore.

**Comment by ThornWalli** [comment]
Yes is the generating time.

**Comment by danielroe** [comment]
This is implemented with the `build:manifest` hook.
