### ISSUE TITLE
`useFetch` cache is lost after hibernation

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/framework#6113]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@3.1.1`
- Builder:          `vite`
- User Config:      `ssr`, `runtimeConfig`, `nitro`, `typescript`, `css`, `intlify`, `modules`, `alias`, `vite`
- Runtime Modules:  `unplugin-icons/nuxt`, `@vueuse/nuxt@8.9.4`, `@intlify/nuxt3@0.2.3`
- Build Modules:    `-`
------------------------------

### Reproduction

As stated, a bit hard to reproduce the invalidation, but I guess the problem is that the fetched data is stored in-memory, while instead it should be stored in some session storage.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/6900
