### ISSUE TITLE
[Webpack: SSR false] unexpected token '<' issue

### ISSUE THREAD

**Issue by ThomasRalee** [nuxt/framework#6115]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6-27641313.416f98b`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `ssr`, `target`, `builder`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Reproduction [repo](https://github.com/ThomasRalee/test-nuxt-3) setup using the `npx nuxi init nuxt-app` command with the following config:
```
export default defineNuxtConfig({
  ssr: false,
  target: "static",
  builder: "webpack",
})
```

### Describe the bug

Browser throws `unexpected token '<' issue` error on `yarn preview`.
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/10151054/180729381-5332dcf7-6888-43db-a4e6-d2a9b5fe30f5.png">
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/10151054/180729482-d613a5e8-bb7c-41f1-896e-475b223a96db.png">

### Additional context

The issue is probably related to Webpack config:
- [Uncaught SyntaxError: Unexpected token < #205](https://github.com/webpack/webpack-dev-middleware/issues/205)

**Comment by danielroe** [comment]
The issue here is that you are using a prereleased version of nuxt3 but not a matching version of `@nuxt/webpack-builder`.

Update your package.json to:
```diff
  "devDependencies": {
-   "@nuxt/webpack-builder": "^3.0.0-rc.6",
+   "@nuxt/webpack-builder": "npm:@nuxt/webpack-builder-edge@3.0.0-rc.6-27641313.416f98b",
    "nuxt": "npm:nuxt3@3.0.0-rc.6-27641313.416f98b"
  }
```

You should be good to go!

**Comment by ThomasRalee** [comment]
Thanks @danielroe , tested and it works!
