### ISSUE TITLE
Failed to clone template from nuxt/starter#v3.Please check the repo is valid and that you have installed git correctly

### ISSUE THREAD

**Issue by Sudhakar-sk** [nuxt/framework#6120]
![image (12)](https://user-images.githubusercontent.com/57562716/180727435-7156a7fc-7668-415a-bee5-19d45400c71e.png)

**Comment by Aksoom-Hussain** [comment]
the issue is due to ISP provider block and then failed to download template from registry: request to https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json failed, reason: connect ETIMEDOUT 49.44.79.236:443

i switch my network and get it working fine
