### ISSUE TITLE
Improve `nuxi upgrade` or have a `nuxi cleanup`

### ISSUE THREAD

**Issue by Atinux** [nuxt/framework#6123]
When upgrading, we most of the time need to cleanup the `.nuxt`, `.output` and other generated directories to avoid errors based on cache.

One example made by @Tahul : 

```bash
/* .bash_profile */
function refresh() {
	find . -name ".nuxt" -type d -prune -exec rm -rf '{}' +
	find . -name ".output" -type d -prune -exec rm -rf '{}' +
	find . -name "dist" -type d -prune -exec rm -rf '{}' +
	find . -name "node_modules" -type d -prune -exec rm -rf '{}' +

	if [ -f yarn.lock ]; then
		rm -rf yarn.lock
		touch yarn.lock
	fi

	if [ -f pnpm-lock.yaml ]; then
		rm -rf pnpm-lock.yaml
		touch pnpm-lock.yaml
	fi

	if [ -f package-lock.json ]; then
		rm -rf package-lock.json
		touch package-lock.json
	fi

	ni
}
```

I think it would be nice to expose a `nuxi cleanup` command to achieve something similar (not everyone is using `nuxi upgrade` also).

**Comment by pi0** [comment]
We allow the script above with `nuxi upgrade --force` to cleanup and remove lockfiles. Would be nice adding a reusable utility and command indeed to only cleanup generated `.nuxt`, `.output` and `node_modules/vite`.
