### ISSUE TITLE
definePageMeta pageTransition does not produce a nice exit animation.

### ISSUE THREAD

**Issue by StefanCardnell** [nuxt/framework#6132]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.5.0`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Please fork the following repo and run `npm run install && npm run dev`:

https://github.com/StefanCardnell/nuxt-animation-issue

### Describe the bug

1) Without specifying `definePageMeta` to override the animation name in `about.vue` and `preferences.vue`, the animation is as expected when pressing the links: as one box slides out, the other slides in.

2) By specifying `pageTransition` in `definePageMeta` by uncommenting the code in `about.vue` and `preferences.vue`, the animation appears strangely. One box appears at the bottom before the other transitions out. Note that this actually isn't doing anything different from the default, the same animation classes `page--...` are used.

![image](https://user-images.githubusercontent.com/11324477/180816654-4e0f22ad-45db-42c4-8f14-7845265f5f13.png)

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/3200.
