### ISSUE TITLE
useFetch fetches value on first call

### ISSUE THREAD

**Issue by aslero** [nuxt/framework#6138]
### Environment

useFetch

### Reproduction

useFetch

### Describe the bug

Hi. Made a repository

```
import { Repository } from '~/repositories/repository';
import { UrlGenerator } from '~/repositories/url-generator';

export class HttpRepository implements Repository {
  constructor(
    private urlGenerator: UrlGenerator
  ) {
  }

  async getExcursionBySlug(slug: string): Promise<any> {
    return await useAsyncData(() => $fetch(this.urlGenerator.getExcursionBySlug(slug), { baseURL: 'http://localhost:3030' }));
  };
}
```

When I open the tour page for the first time, I get the data of this tour, but when I open other tours, I always display the first open tour until I reload the page

```
<script lang="ts" setup>
import IconBannerFavorite from '~/assets/icons/banner/favorite.svg?component';
import IconFinish from '~/assets/icons/finish.svg?component';
import IconReplace from '~/assets/icons/replace.svg?component';

import useResponsive from '~/composables/useResponsive';

import { computed, inject, ref } from '#imports';
import { useRoute } from '#app';

import dayjs from 'dayjs';

const {
  isMobile,
  isTabled,
  isDesktop
} = useResponsive();
const repositoryService = inject('repositoryService');
const route = useRoute();

const isReviewBanner = ref(false);
const isReviews = ref(false);

const {
  data: excursion,
  pending
} = await repositoryService.repository.getExcursionBySlug(route.params.slug);

const daysWeek = computed(() => {
  const days = Object.values(excursion.value.daysWeek);

  return days.map((item: number) => {
    return dayjs()
      .locale('ru')
      .day(item - 1)
      .format('dddd');
  });
});

const people = computed(() => {
  return Array.from(excursion.value.excursionPeople)
    .map((item: any) => {
      item.peopleId = item.people?.id ?? 0;
      item.title = item.people?.title ?? null;
      item.description = item.people?.description ?? null;
      delete item.people;
      return item;
    });
})

useHead({
  title: excursion.value.seoTitle,
  meta: [
    {
      name: 'description',
      content: excursion.value.seoDescription
    }
  ]
});
</script>
```

**Comment by aslero** [comment]
```
async getExcursionBySlug(slug: string): Promise<any> {
    return await useAsyncData(slug, () => $fetch(this.urlGenerator.getExcursionBySlug(slug), { baseURL: 'http://localhost:3030' }));
  };
```
Understood, it was necessary to substitute the key. But how to reset the cache? and what if there is sorting or filtering?

**Comment by hacknug** [comment]
> When I open the tour page for the first time, I get the data of this tour, but when I open other tours, I always display the first open tour until I reload the page

I think this is a regression on RC's 5 and 6. Seems like the key for the request isn't being generated correctly and that's why only the first request works and seems to end up in all other ones. If I remember correctly this was working as expected on RC 4.

> Understood, it was necessary to substitute the key. But how to reset the cache? and what if there is sorting or filtering?

This won't fix the issue with the last RC's but just in case you've missed it, `useFetch` and `useAsyncData` return an object that also includes a `refresh` method for this purpose: https://v3.nuxtjs.org/api/composables/use-fetch#type

**Comment by danielroe** [comment]
In general I would observe that you should not be using `useAsyncData` as you are doing. It is a composable meant to be called directly in setup, not a fetcher function. Instead, use `$fetch` directly:

```js
import { Repository } from '~/repositories/repository';
import { UrlGenerator } from '~/repositories/url-generator';

export class HttpRepository implements Repository {
  constructor(
    private urlGenerator: UrlGenerator
  ) {
  }

  async getExcursionBySlug(slug: string): Promise<any> {
    return await $fetch(this.urlGenerator.getExcursionBySlug(slug), { baseURL: 'http://localhost:3030' });
  };
}
```

A further note: with `useAsyncData`, you need to provide a key directly. If you do not, a unique key will be assigned based on the location within your codebase. That means you _must_ assign a key for any kind of wrapper around `useAsyncData` or they will all end up resolving to the same data in your payload. This behaviour change with keys needs to be documented separately, and we can follow that in #5838.
