### ISSUE TITLE
H3Error: require is not defined in ES module scope, you can use import instead

### ISSUE THREAD

**Issue by mklueh** [nuxt/framework#6144]
### Environment

Nuxt CLI v3.0.0-rc.6                                                                                                                         09:55:47
RootDir: /home/user/workspace/`my-project                                                                                09:55:53
Nuxt project info:                                                                                                                           09:55:53

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@3.2.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                             09:55:53

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

My setup is an NX project, one Nuxt 3 app and one TypeScript library that I'm trying to import and use in the app.

### Describe the bug

Nuxt starting with an error and I'm unsure if it is related to something of the Nitro engine, or if I have caused that with something (like the imported library)

### Logs

```shell
ℹ Vite client warmed up in 1701ms
ℹ Vite server warmed up in 263ms
✔ Vite server built in 1976ms
✔ Nitro built in 1153 ms
[h3] [unhandled] H3Error: require is not defined in ES module scope, you can use import instead
    at createError (file:///home/user/workspace/my-project/node_modules/h3/dist/index.mjs:191:15)
    at Server.nodeHandler (file:///home/user/workspace/my-project/node_modules/h3/dist/index.mjs:381:21) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}


```
```

**Comment by danielroe** [comment]
This is almost certainly an imported library using `require()`. You can add this library to your `build.transpile` to transform that to an import.

**Comment by mklueh** [comment]
@danielroe thanks. Is there generally a way to improve the stacktrace so the causing library gets pointed out immediately?

**Comment by mklueh** [comment]
I was using firebase admin in my library. It worked after adding this https://github.com/nuxt/framework/issues/3598
