### ISSUE TITLE
createClientOnly return a component that cannot transfer the ref of its child

### ISSUE THREAD

**Issue by huang-julien** [nuxt/framework#6145]
### Environment

nuxt rc 6

### Reproduction

https://github.com/nuxt/framework/blob/25ac6526522077bdc77ed8568c745f4436cc002a/packages/nuxt/src/app/components/client-only.mjs#L21-L35

### Describe the bug

this is a small issue since we can workaround using the `<client-only />` wrapper with the slot. If we set a ref on `<HelloWorld ref="yahoo" />` and if HelloWorld is defined by a file with .client, nuxt use `createClientOnly()` that return a component wrapping the HelloWorld. So the ref retrieved in yahoo isn't HelloWorld's ref but instead it is the ClientOnlyWrapper's ref.
 Shouldn't the createClient only modify the component like defineNuxtComponent() ? the setup could return an object with a mounted value and the render function would wrap the render function of the component, rendering the component after the mounted hook.

**Comment by danielroe** [comment]
Let's wrap this into a single issue with https://github.com/nuxt/framework/issues/5867. Improvement here would be welcome.
