### ISSUE TITLE
redirect via navigateTo() not working with nuxt generate

### ISSUE THREAD

**Issue by codeflorist** [nuxt/framework#6150]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-zaokyb?file=pages/index.vue

### Describe the bug

having a page redirect to another page via the `navigateTo` helper does not work with `nuxt generate`.

e.g.
```js
<script setup lang="ts">
await navigateTo('/target', { replace: true })
</script>
```

gets rendered as a white page with the text `Redirecting to /target`.

see attached stackblitz-project for an example.

**Comment by danielroe** [comment]
What do you expect to happen? Should the page not be generated?

**Comment by codeflorist** [comment]
> What do you expect to happen? Should the page not be generated?

I would expect it to behave exactly like `nuxt build` or `nuxt dev` - meaning it should load the full page, then redirect to `/target`.

**Comment by danielroe** [comment]
A server-side redirection can't be rendered as an HTML page _as such_. But what we _could_ do is return a minimal blank white HTML page that immediate redirects to the target location on client-side, which seems reasonable and better than at present.

**Comment by danielroe** [comment]
~> https://github.com/unjs/h3/pull/153

**Comment by codeflorist** [comment]
> A server-side redirection can't be rendered as an HTML page _as such_. But what we _could_ do is return a minimal blank white HTML page that immediate redirects to the target location on client-side, which seems reasonable and better than at present.

ah, of course. i understand. many thanks for the clarification and the super fast reaction!

imho a workable solution would also be:
```js
<script setup lang="ts">
onMounted(() => {
	navigateTo('/target', { replace: true })
})
</script>
```

**Comment by danielroe** [comment]
Should already be implemented in h3 and you'll get the benefit in next h3 release 😊

**Comment by pi0** [comment]
Please use `npx nuxi upgrade --force` to update lockfile and have latest h3.
