### ISSUE TITLE
Pages not working

### ISSUE THREAD

**Issue by v3nt** [nuxt/framework#6160]
Just setup a new nuxt 3 app.
Added pages but can't access for example `/working/`

Its always loading the `App.vue`

<img width="290" alt="Screenshot 2022-07-26 at 16 32 50" src="https://user-images.githubusercontent.com/6348562/181048352-e29d6d41-82d2-4a57-bb07-2f65111a2ccc.png">

**Comment by danielroe** [comment]
This should be resolved on the edge channel through https://github.com/nuxt/framework/pull/6038. For now, you can restart the dev server.
