### ISSUE TITLE
transitions/keepalive config via `<NuxtPage>` props

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#6161]
In Vue-Router, it's possible to perform transition for particular `router-view` usages:

https://router.vuejs.org/guide/advanced/transitions.html#transitions

```html
<router-view v-slot="{ Component }">
  <transition name="fade">
    <component :is="Component" />
  </transition>
</router-view>
```

So any child component which appears in the `router-view` will have the same transition. 

With `NuxtPage` I don't see if this is possible. There is `pageTransition` setting for `definePageMeta` but this means defining the same transition for every possible page - and also you may not wish that these pages always produce animations.

This feature request is for `NuxtPage` to provide a property which allows changes the default page animation for any page which appears under it.

_Originally posted by @StefanCardnell in https://github.com/nuxt/framework/discussions/6127_

**Comment by vis97c** [comment]
@danielroe I was just about to request this feature. Any insight in how to best approach it so I can start working on a proposal?
