### ISSUE TITLE
Environment Variables don't load if there is a number in the name

### ISSUE THREAD

**Issue by akeemphilbert** [nuxt/framework#6172]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `build`, `vite`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/akeemphilbert/nuxt-issue-reproduction

### Describe the bug

If a public runtime configuration name has a number in it (e.g. api1Base) then the corresponding environment variable does not load (`NUXT_PUBLIC_API1_BASE`)

**Comment by danielroe** [comment]
The key is split like this: `NUXT_PUBLIC_API_1BASE`.

**Comment by danielroe** [comment]
Actually this has already been fixed upstream but never released.

cc: @pi0 - we don't seem to have 0.3.0 on npm despite https://github.com/unjs/scule/commit/91fd6abca1126cf1db73ae877dd8adc5cf482a93

**Comment by pi0** [comment]
Thanks for reporting @akeemphilbert and investigation @danielroe ❤️ 

scule 3 is released with fix and also updated nitro which was using it.

With the current (buggy) version, you can override with `NITRO_PUBLIC_API_1BASE`.

I will updated this issue accordingly with final fixed behavior and naming.

**Comment by danielroe** [comment]
Latest behaviour is that we ignore numbers for case changing. So you would override `public.api1Base` with `NUXT_PUBLIC_API1_BASE` as you originally expected.

@pi0 shall we close this issue now, or are you planning on making further changes?
