### ISSUE TITLE
Hydration issue with Netlify deployments

### ISSUE THREAD

**Issue by stefanfrede** [nuxt/framework#6204]
### Environment

Nuxt CLI v3.0.0-rc.5                                                                                                                                                                                       15:54:14
RootDir: /home/sfrede/Sites/SabineHugo/Website                                                                                                                                                             15:54:15
Nuxt project info:                                                                                                                                                                                         15:54:15

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.5`
- Package Manager:  `npm@8.15.1`
- Builder:          `vite`
- User Config:      `css`, `modules`, `typescript`, `app`, `content`
- Runtime Modules:  `@nuxt/content@2.1.0-27630041.9582f8c`, `@vueuse/nuxt@8.9.3`
- Build Modules:    `-`
------------------------------

### Reproduction

A regular deploy on Netlify.

### Describe the bug

I realized at some point that my deploy previews on Netlify were slightly off.

For example my footer component was doubled and my slider component stopped working as expected.

At first this just affected the deploy previews but since of today this is also affecting production which renders us unable to deploy anything.

Needless to say that locally everything is working fine.

This is the repository:
https://github.com/sabinehugo189/sabinehugo

Because I'm not sure if this is a problem with Nuxt3 or with Netlify I also posted the problem on the Netlify forum:
https://answers.netlify.com/t/differences-between-deploy-previews-and-live-with-nuxt-3/71603/3.

**Comment by danielroe** [comment]
This may well be the same issue as https://github.com/nuxt/framework/issues/5921. cc: @pi0

**Comment by danielroe** [comment]
@stefanfrede Would you see if it still reoccurs with:

```diff
  function submenuRef(target) {
-   if (target.classList.contains('is-submenu') && lgNAbove.value) {
+   if (target?.classList.contains('is-submenu') && lgNAbove.value) {
      onClickOutside(target, (event) => {
        const menu = target;
        const button = menu.previousElementSibling;
        const expanded = button.getAttribute('aria-expanded') === 'true' || false;
  
        if (button !== event.target && expanded) {
          close({ button, menu });
        }
      });
    }
  }
```

**Comment by stefanfrede** [comment]
@danielroe I created a less complicated test repository: 
https://github.com/stefanfrede/nuxt3-playground

And the same problems occur:
https://deploy-preview-1--nuxt3-playground-sfr.netlify.app/

**Comment by stefanfrede** [comment]
I don't know if it is related but I realized that I get a `Hydration completed but contains mismatches.` error the moment I start to use `<NuxtPage />`.

**Comment by stefanfrede** [comment]
For testing purposes I downgraded Nuxt to RC1 and the problem persists.

Sadly the developer from Netlify who is looking into it is also baffled by the behaviour:

> I’m still not sure how this is something Netlify would be causing - at the same time, cannot explain the weird behaviour. All I can see is, from Netlify’s end, this appears to be a code that the developer and Nuxt is generating and Netlify is simply executing.
>
> To me it appears that, Nuxt is rendering the content on the server and in its “hydration” step, it’s adding the same content for some reason. Does this happen across various Nuxt versions?

Reading his latest comment it seems that the hydration error is a possible cause.

**Comment by danielroe** [comment]
Would you try using the [latest edge channel release](https://v3.nuxtjs.org/guide/going-further/edge-channel/) and let me know if the problem persists?

**Comment by stefanfrede** [comment]
@danielroe Sadly it is still persisting:

https://deploy-preview-1--nuxt3-playground-sfr.netlify.app/
https://github.com/stefanfrede/nuxt3-playground/pull/1

**Comment by danielroe** [comment]
Looking at this, it only reproduces in the Netlify build environment - test running:

```bash
NITRO_PRESET=netlify npm run build && ntl deploy
```

* [**GitHub main branch**](https://stunning-croquembouche-477cdf.netlify.app/)
* [**local deploy**](https://62e7d00aa86816469e120e7e--stunning-croquembouche-477cdf.netlify.app)

You can see that the `<NuxtPage>` component is entirely missing in the served HTML:

```html
<div id="__nuxt">
	<div>
		<header>Header</header>
		<!---->
		<footer>Footer</footer>
	</div>
</div>
```

Investigating.

**Comment by pi0** [comment]
After long debugging with @danielroe, we could narrow it down to a recent change in RC.5. (context: #5506)

We are still investigating but as a quick workaround, please try this in `nuxt.config`:

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  hooks: {
    'vite:extendConfig'(config, { isServer }) {
      if (isServer) {
        // Workaround for netlify issue
        // https://github.com/nuxt/framework/issues/6204
        config.build.rollupOptions.output.inlineDynamicImports = true
      }
    }
  },
})
```

**Comment by stefanfrede** [comment]
I can confirm that the workaround is working.

**Comment by baringji** [comment]
This work around also fix my issue. 

FYR, in my case, two table of contents will show. Below is the TOC component source.

```vue
<script setup>
import { useContent } from '#imports'
const { toc } = useContent()
</script>

<template>
  <aside class="toc hidden md:block w-full max-w-16rem py-8">
    <h4 class="font-bold mb-2">Table of Contents</h4>
    <ul v-if="toc && toc.links" class="pl-4">
      <li v-for="link in toc.links" :key="link.text">
        <NuxtLink :to="{ hash: `#${link.id}` }" class="block py-1">{{ link.text }}</NuxtLink>
      </li>
    </ul>
  </aside>
</template>
```

**Comment by jjjrmy** [comment]
> I don't know if it is related but I realized that I get a `Hydration completed but contains mismatches.` error the moment I start to use `<NuxtPage />`.

Having the same issue with Cloudflare Pages

**Comment by pi0** [comment]
Issue is solved in latest [nuxt edge](https://v3.nuxtjs.org/guide/going-further/edge-channel) and should land with `rc.7`. Please see https://github.com/nuxt/framework/pull/6468 for context.
