### ISSUE TITLE
createTest from @nuxt/test-utils-edge can't load nuxt

### ISSUE THREAD

**Issue by belomx** [nuxt/framework#6209]
### Environment

Nuxt CLI v3.0.0-rc.6                                                                                                         17:34:51
RootDir: /app                                                                                                                17:34:53
Nuxt project info:                                                                                                           17:34:53

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.20.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `meta`, `loading`, `build`, `modules`, `tailwindcss`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.0`, `@pinia/nuxt@0.3.1`, `@nuxtjs/style-resources@1.2.1`, `@vueuse/nuxt@8.9.4`
- Build Modules:    `-`
------------------------------

### Reproduction

Install nuxt test utils and vitest

`yarn add --dev @nuxt/test-utils-edge vitest`

Define the nuxt.config.js
`//nuxt.config.js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
})`

And create the test file
`//test/index.test.js
import { $fetch, createTest } from '@nuxt/test-utils-edge'

const test = createTest({
  testDir: './src',
  rootDir: '.',
  server: true,
  browser: true,
  configFile: './nuxt.config.js',
  dev: true
})
// WHERE THE ERROR OCCURS
await test.setup()

describe('landing page test', async () => {
  $fetch('http://localhost:31300/')  
})`

Execute test by
`vitest --dir test --run --reporter verbose --globals --config vitest.config.js`

### Describe the bug

During the test when the code call the "test.setup", the error below appears:

FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0x10d83c0e5 node::Abort() [/usr/local/bin/node]
 2: 0x10d83c268 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]

Debugging the code, the error is being throwed by the code below:

//@nuxt/kit/dist/index.mjs
async function loadNuxt(opts) {
  opts.cwd = opts.cwd || opts.rootDir;
  opts.overrides = opts.overrides || opts.config || {};
  const resolveOpts = { paths: opts.cwd };
  opts.overrides.dev = !!opts.dev;
  const nearestNuxtPkg = await Promise.all(["nuxt3", "nuxt", "nuxt-edge"].map((pkg2) => resolvePackageJSON(pkg2, { url: opts.cwd }).catch(() => null))).then((r) => r.filter(Boolean).sort((a, b) => b.length - a.length)[0]);
  if (!nearestNuxtPkg) {
    throw new Error(`Cannot find any nuxt version from ${opts.cwd}`);
  }
  const pkg = await readPackageJSON(nearestNuxtPkg);
  const majorVersion = parseInt((pkg.version || "").split(".")[0]);
  if (majorVersion === 3) {
    //Can't load nuxt for some reason
    const { loadNuxt: loadNuxt3 } = await importModule(pkg._name || pkg.name, resolveOpts);
    const nuxt2 = await loadNuxt3(opts);
    return nuxt2;
  }
  const { loadNuxt: loadNuxt2 } = await tryImportModule("nuxt-edge", resolveOpts) || await importModule("nuxt", resolveOpts);
  const nuxt = await loadNuxt2({
    rootDir: opts.cwd,
    for: opts.dev ? "dev" : "build",
    configOverrides: opts.overrides,
    ready: opts.ready,
    envConfig: opts.dotenv
  });
  return nuxt;
}

### Additional context

If an environment to reproduce the issue is required, just send a request to me :)

**Comment by danielroe** [comment]
Yes, a minimal reproduction would be appreciated. Note that you should install it as `yarn add @nuxt/test-utils` or `yarn add @nuxt/test-utils@npm:@nuxt/test-utils-edge` rather than using the edge version directly.

Finally, I think your configuration may be worth looking into. Here's an example of a test being setup:

https://github.com/danielroe/nuxt-ionic/blob/c02a54f980fe0028b2c9b8bd98cab208acb61e31/test/e2e/ssr.spec.ts#L7-L10

**Comment by belomx** [comment]
Hi Daniel,

Thanks for the swift answer. I am getting an error during the start server to run the tests.

error:
start server error -  Error: Nuxt instance is unavailable!
    at useNuxt (/app/node_modules/@nuxt/test-utils/node_modules/@nuxt/kit/dist/index.mjs:68:11)
    at Module.resolvePath (/app/node_modules/@nuxt/test-utils/node_modules/@nuxt/kit/dist/index.mjs:345:16)
    at Module.startServer (/app/node_modules/@nuxt/test-utils/dist/index.mjs:57:33)

**Comment by danielroe** [comment]
@belomx Here's a guide to what a minimal reproduction is: https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction

**Comment by belomx** [comment]
Here is the reproduction env
https://stackblitz.com/edit/github-tengoo?file=package.json,vitest.config.js,test%2Fe2e%2Fssr.spec.js
Just execute "npm run test"

**Comment by danielroe** [comment]
You shouldn't be running `setup` hook within `beforeAll`. It is the [function that itself registers hooks](https://github.com/nuxt/framework/blob/11626eea4f8801e9accc632225c6c54ed4bb69a1/packages/test-utils/src/setup/vitest.ts#L2-L9).

This is effectively [what it is doing](https://github.com/nuxt/framework/blob/2590ae39d399b8bc89b73db790dc3c5400204ac7/packages/test-utils/src/setup/index.ts#L70-L76):

```js
const hooks = createTest({
  server: true,
  dev: true,
  rootDir: fileURLToPath(new URL('../../.', import.meta.url)),
})

beforeAll(hooks.setup, 120 * 1000)
beforeEach(hooks.beforeEach)
afterEach(hooks.afterEach)
afterAll(hooks.afterAll)

// or, more simply
await setup({
  server: true,
  dev: true,
  rootDir: fileURLToPath(new URL('../../.', import.meta.url)),
})

// your tests:

describe('some fixture', () => {})
```

This works fine: https://stackblitz.com/edit/github-tengoo-1aryjx (when downloaded, as I think it may time out in stackblitz).

**Comment by danielroe** [comment]
Please do let me know if you think there is another issue with `@nuxt/test-utils` with an new reproduction and I'll very happily take a look.

**Comment by belomx** [comment]
I have executed locally with the same [setup](https://stackblitz.com/edit/github-tengoo-1aryjx) you gave me, but it can't load the fixures.

// test-utils/dist/index.mjs
async function loadFixture() {
  const ctx = useTestContext();
  ctx.options.rootDir = resolveRootDir();
  if (!ctx.options.dev) {
    const randomId = Math.random().toString(36).slice(2, 8);
    const buildDir = resolve(ctx.options.rootDir, ".nuxt", randomId);
    Object.assign(ctx.options.nuxtConfig, {
      buildDir,
      nitro: {
        output: {
          dir: resolve(buildDir, "output")
        }
      }
    });
  }
 **// Don't execute and no errors are returned**
  ctx.nuxt = await kit.loadNuxt({
    cwd: ctx.options.rootDir,
    dev: ctx.options.dev,
    overrides: ctx.options.nuxtConfig,
    configFile: ctx.options.configFile
  });
  kit.logger.level = ctx.options.logLevel;
  await promises.mkdir(ctx.nuxt.options.buildDir, { recursive: true });
}

**Comment by danielroe** [comment]
Are you still experiencing this? If so, would you provide a reproduction?

**Comment by belomx** [comment]
Yes, I am still having the issue :/
I am going to provide an environment to reproduce the problem, the environments like stackblitz are not being able to return the same output from my one.

**Comment by danielroe** [comment]
I'd be equally happy with a git repro.

**Comment by danielroe** [comment]
I'm closing this but if you provide a reproduction I will happily reopen.
