### ISSUE TITLE
Vue devtools not working.

### ISSUE THREAD

**Issue by Xkiztor** [nuxt/framework#6224]
**Nuxt.js + Vue.js is detected on this page.**
Devtools inspection is not available because it's in production mode or explicitly disabled by the author.

**Comment by danielroe** [comment]
Please see https://github.com/nuxt/framework/issues/2284#issuecomment-1132160740.

**Comment by felixdenoix** [comment]
I had the same issue;
After reinstalling the ui extension, running `npx nuxi@latest cleanup` and reinstalling the node modules, I cleared all browsing data in chrome from the dev tools. You open the prompt typing `⌘ + ⇧ + P` and you trigger the clear site data. It seems that the browser had somehow cached the localhost page after running a production build.

![Capture d’écran 2022-11-01 à 01 07 27](https://user-images.githubusercontent.com/9197243/199131763-c0fe9210-ed2b-48c2-8a75-f97bfea8b44e.png)

Hope it helps.
