### ISSUE TITLE
nuxt generate

### ISSUE THREAD

**Issue by 516310460** [nuxt/framework#6239]
### Environment

Operating System: Darwin
Node Version: v16.16.0
Nuxt Version: 3.0.0-rc.6
Package Manager: npm@8.11.0
Builder: vite
User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

https://bigeyerebellion.com/

### Describe the bug

<img width="931" alt="image" src="https://user-images.githubusercontent.com/17541676/181788377-1d10f256-aede-4e5e-a21c-abe5d6e858ea.png">

**Comment by manniL** [comment]
I don't think it is a Nuxt issue. Configure your webserver to send `mjs` files as `application/javascript` MIME type. See also https://github.com/nuxt/framework/issues/5303

**Comment by 516310460** [comment]
thenks
