### ISSUE TITLE
`vite-node` server HMR is broken

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#6243]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.6-27651720.5dc864d`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `experimental`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

(on Windows, Linux, Docker (Linux) or WSL2 environment)

- Create new project with `npx nuxi init` (swit
- Enable vite-node with `experimental
- Run dev server with `npm run dev`
- Write simple `app.vue` such as `<template><div>Hello world!</div></template>`
- Open http://localhost:3000
- Edit `app.vue` 
- Reload

### Describe the bug

Client is updated with HMR and subsequent reloads but server is not. Causing hydration error.

It might be related to the issue https://github.com/nuxt/framework/issues/2047 since now client HMR on Linux works and Server not (in current nuxt, it is otherwise). But also trying CHOKIDAR_USEPOLLING=1 I still have same issues.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/5158436/181794873-58edea85-2b03-4a4d-8a1e-a7edb1dae0b3.png">

**Comment by pi0** [comment]
I can also reproduce it on MacOS (testing on 13.1). Client HMR stops working when `viteNode` flag is set resulting in hydration mismatch: 

<img width="492" alt="image" src="https://user-images.githubusercontent.com/5158436/182356883-a51a9111-a85b-46fd-af22-fc5c8e0df35f.png">

**Comment by pi0** [comment]
@antfu Can you please check this? I can confirm on multiple mac versions it is also broken... 

Do we have a watcher still with vite-node?

**Comment by antfu** [comment]
Yes, we have Vite's watcher to invalidate the modules. I will investigate

**Comment by antfu** [comment]
I can confirm this bug in the edge build, but not in our development playground.

**Comment by antfu** [comment]
Is it still not working on Linux/Windows?

**Comment by pi0** [comment]
@antfu Yes i could constantly reproduce on Windows (Windows 11 on PC + Parallers on M2 arm64) and Randomly on Linux (WSL). Will share a screen cast of issue. It is not directly fault of vite-node BTW but when we enable vite-node, since server watcher happens first, client watcher gets broken eventually.

**Comment by pi0** [comment]
I can no longer reproduce it on rc.8. Seems an underlying library fixed the root cause!
