### ISSUE TITLE
Template refs can only be addressed correctly during initial loading

### ISSUE THREAD

**Issue by naschidaniel** [nuxt/framework#6259]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Behavior NOT OK - Nuxt Project: https://stackblitz.com/edit/nuxt-starter-qjn3ru?file=pages%2Ftest.vue

Behavior OK Vue Project: https://stackblitz.com/edit/node-25r64j?file=src%2Fviews%2FTestView.vue

### Describe the bug

When changing from the route index to the route test, the input field `<input ref="input" />` is not captured correctly. However, if the web page is reloaded, then the values of the field `<input ref="input" />` can be accessed.

I have also tested whether this is a Vue error. But I could not observe the error there.

![nuxt-app-ref](https://user-images.githubusercontent.com/6561161/181906503-fbbc6d78-a0e9-429e-a2e2-98ae3c7faddc.gif)

The two examples were created on the basis of the [VUE accessing-the-refs documentation](https://vuejs.org/guide/essentials/template-refs.html#accessing-the-refs).

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/3587. It is an upstream bug in Vue core.
