### ISSUE TITLE
[SOLVED] defineRouteMeta is not defined

### ISSUE THREAD

**Issue by angelhdzmultimedia** [nuxt/framework#6261]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.1.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.8.0`
- Builder:          `vite`
- User Config:      `srcDir`, `alias`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

No reproduction link. Just a nuxt 3 RC 6 project from scratch and a `auth.global.js` in `server/middleware`.

### Describe the bug

login.vue:

```js
<script setup>
defineRouteMeta({
  auth: true
})
</script>
```
index.vue:
```js
<template>
  <div>
     <h1>Nuxt App</h1>
     <button @click="$router.push('/login')">Login</button>
  </div>
</template>
```

app.vue:

```
<template>
    <NuxtPage/>
</template>
```

![image](https://user-images.githubusercontent.com/10191085/181914229-a33f236a-6ac7-43e7-929d-c3cb3f7726b0.png)

**Comment by danielroe** [comment]
It is `definePageMeta`. Is there an error in the docs somewhere?

**Comment by angelhdzmultimedia** [comment]
> It is `definePageMeta`. Is there an error in the docs somewhere?

I also tried definePageMeta. I've been reading the docs like crazy lol, I tought this was something pretty easy to acheive and bam hit this wall.

**Comment by angelhdzmultimedia** [comment]
Let me upload a repro real quick. Maybe I'm doing something wrong in the process of learning Nuxt (I started full with Nuxt 3, I basically jumped Nuxt.js).

**Comment by danielroe** [comment]
Just to be clear, you have a folder called `pages`, right? And `login.vue` is in there?

**Comment by angelhdzmultimedia** [comment]
> Just to be clear, you have a folder called `pages`, right? And `login.vue` is in there?

https://stackblitz.com/edit/github-s5zknb?file=README.md

**Comment by danielroe** [comment]
Move `~/server/middleware/auth.global.ts ` to `~/middleware/auth.global.ts`. And no need to configure the `@` alias.

**Comment by angelhdzmultimedia** [comment]
Silly me! Works like magic now! Appreciate your time and energy  a lot. Will keep studying Nuxt 3, it's promising!
