### ISSUE TITLE
titleTemplate is not working properly

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/framework#6305]
Hello 👋, 

The `titleTemplate` property used in `useHead` is not working as expected ([Documentation](https://v3.nuxtjs.org/guide/features/head-management)) from a fresh Nuxt app (`v3.0.0-rc.6`)

code :
```js
<script setup>
useHead({
  titleTemplate: (titleChunk) => {
    return titleChunk ? `${titleChunk} | site name` : 'site name'
  },
})
</script>
```
Output :
![output1](https://user-images.githubusercontent.com/85166574/182413209-226556c0-9c8e-4e8d-8d84-a834051f07a4.png)

even with the config below :
```js
<script setup>
  useHead({
    titleTemplate: (title) => `My App - ${title}`,
  })
</script>
```
Ouput :
![output2](https://user-images.githubusercontent.com/85166574/182413932-bd9b7865-530e-436a-aa62-2e991de8c6ac.png)

Config :
![Config](https://user-images.githubusercontent.com/85166574/182415373-46dc3dce-8cd0-4524-a12e-ab0214e1e07a.png)

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/pull/6296. You could temporarily force an earlier version of `@vueuse/head` or upgrade to edge channel.

**Comment by BenjaminOddou** [comment]
I'll wait for the next RC release ! Thank you for the update 🙂
