### ISSUE TITLE
Route query string doesn't get passed within slots

### ISSUE THREAD

**Issue by heychazza** [nuxt/framework#6307]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.20.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `target`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Source: https://github.com/heychazza/route-reproduction-repo
Live Link: https://route-reproduction-repo.vercel.app/?test-url

### Describe the bug

When browsing to the above live link, the "referrer link" should be "https://example.com/register?test-url" however it is stripped.

When using this in development it is fine, but deployed to Vercel and this doesn't work correctly.

### Additional context

The site is generated statically.

**Comment by danielroe** [comment]
My guess is that as you are statically generating the page, the href is hard coded in the HTML without a query. I would suggest updating it in a mounted hook.

**Comment by heychazza** [comment]
> My guess is that as you are statically generating the page, the href is hard coded in the HTML without a query. I would suggest updating it in a mounted hook.

Ah really, it’s strange because I can console log it fine, it’s just within the code. If I move the anchor outside of the child component, it shows fine.

will try the mounted approach
