### ISSUE TITLE
useFetch doesn't respond to state changes, unlike useAsyncData

### ISSUE THREAD

**Issue by talaxasy** [nuxt/framework#6310]
### Environment

- Operating System: Linux Ubuntu 20.04
- Node Version: v14.20.0
- Nuxt Version: 3.0.0-rc.6
- Package Manager: yarn
- Builder: Vite

### Reproduction

https://stackblitz.com/edit/github-vq3udn?file=app.vue

### Describe the bug

When I change the state of the page variable, the useFetch hook that uses this state does not react to it, unlike useAsyncData.
It is expected that when the state changes, useFetch will trigger again, although this does not happen.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/5993.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/5993.
