### ISSUE TITLE
Cant set 80 port

### ISSUE THREAD

**Issue by shmidtelson** [nuxt/framework#6322]
### Environment

dev

### Reproduction

nuxi dev --port=80

### Describe the bug

After run `nuxi dev --port=80` server starts on 3000 port
<img width="809" alt="Screenshot 2022-08-03 at 12 25 03" src="https://user-images.githubusercontent.com/6944443/182574107-11b14710-0c88-43f1-a3fe-1d66f6e82ef2.png">

### Additional context

Other any port works well

**Comment by danielroe** [comment]
`80` is a reserved port and your OS is not allowing nuxi to start on it.

**Comment by shmidtelson** [comment]
I have been using 80 port for dev about 1 year in Nuxt2. Nuxi cant use this? Enough strange

**Comment by danielroe** [comment]
Probably should have said that _probably_ this was the case. Interesting. It seems that the way we check for port (via https://github.com/unjs/get-port-please) is possibly too cautious.

**Comment by danielroe** [comment]
Would you tell me what the output of `npx serve -l tcp://127.0.0.1:80 .` is on your computer?

**Comment by shmidtelson** [comment]
<img width="950" alt="Screenshot 2022-08-03 at 17 04 14" src="https://user-images.githubusercontent.com/6944443/182628506-75cefa8a-8057-4f7d-9d3e-ddb469bc8bcf.png">

**Comment by danielroe** [comment]
Thanks! That makes sense. Located the issue upstream (we were checking for permissions on `127.0.0.1` even though we were listening on `0.0.0.0`.

**Comment by shmidtelson** [comment]
I glad to help nuxt!

**Comment by danielroe** [comment]
I believe this is now resolved with the latest `listhen`, which you can get with `yarn upgrade nuxt` or `npm upgrade nuxt`.

Let me know if not and I'll reopen.

**Comment by JasonLandbridge** [comment]
@danielroe, The problem has indeed been fixed but I get the following false warning:
![image](https://user-images.githubusercontent.com/15127381/185792940-95c9a420-e682-4694-bb76-3bf080211076.png)

However, the  `http://localhost:4000/` dev server does indeed work so the `[get-port] Unable to find an available port (tried 4000). Using alternative port: 3000` is triggered unjustly. 

`package.json`

```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxi dev --port=4000",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@nuxt/content": "npm:@nuxt/content-edge@latest",
    "nuxt": "^3.0.0-rc.4"
  }
}

```

**Comment by pi0** [comment]
@shmidtelson It seems that you have already running a dev server listening to port 4000. I've locally tested. If nothing else is listening, `--port=4000` should work as expected.

**Comment by shmidtelson** [comment]
The problem comes again! 
After i update nuxt-bridge.  (Nuxt CLI v3.0.0-rc.12)
However with Nuxt CLI v3.0.0-rc.8 works well
