### ISSUE TITLE
throw createError with fatal: true did not trigger error page

### ISSUE THREAD

**Issue by HoraceKeung** [nuxt/framework#6330]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `pnpm@7.5.2`
- Builder:          `vite`
- User Config:      `vite`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-se9xkd?file=app.vue

### Describe the bug

In a new project, added a button to app.vue that calls a function that will throw createError with fatal: true. Expect it to then navigate to the error page. But instead get error in console when button is clicked: 
![image](https://user-images.githubusercontent.com/6639120/182596361-75492ad0-a410-4507-a19e-74a49d108f98.png)

**Comment by danielroe** [comment]
Arbitrary errors won't trigger the page (e.g. in event handlers). We only can catch them in the Vue lifecycle. You should be able to use `showError` on client-side in the example you give.

**Comment by HoraceKeung** [comment]
Tried

```
const throwError = () => {
  showError({
    statusCode: 404,
    statusMessage: 'Page Not Found',
  });
};
```

But then get "showError is not defined" error.
Then tried adding "import { showError } from 'h3';" but then get "The requested module '/_nuxt/node_modules/.vite/deps/h3.js?t=1659541933284&v=3aaa334b' does not provide an export named 'showError'" error.

Also in the documentation for createError, it says "If you need to trigger a full-screen error page, then you can do this by setting fatal: true." https://v3.nuxtjs.org/guide/features/error-handling#createerror

**Comment by danielroe** [comment]
`showError` is available on the latest edge release. (In the RC it is named `throwError`.)

**Comment by HoraceKeung** [comment]
Thanks, throwError works.
