### ISSUE TITLE
useRoute() does not return reactive object

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#6348]
I have something related, when I use the route.name in a computed variable OR use the route(.name) in a watch function it doesn't get triggered after navigating.

When I output the $route.name in the template tag, this does get updated after navigating.

Some additional info, when I do the following:

In RC.6
```js
console.log(useRoute());

Output:

Proxy with computed values
```

In edge
```js
console.log(useRoute());

Output:

Regular json object with values
```

_Originally posted by @rvmourik in https://github.com/nuxt/framework/issues/6273#issuecomment-1203814035_

**Comment by rvmourik** [comment]
I can't test if it resolves the issue, the new edge release introduces two new errors:

Error 1:
```
```

Resolved this with:

```
```

Error 2: 
```
Cannot start nuxt:  nuxtCtx.tryUse is not a function 
```

**Comment by danielroe** [comment]
@rvmourik Try with `yarn upgrade` to ensure that new dependencies are included.

**Comment by rvmourik** [comment]
I always update with that command and after experiencing the issues I removed the node_modules, yarn..lock and .nuxt folder and issue still persisted. Any other clues?

**Comment by rvmourik** [comment]
Ah I see the Pr of @pi0 regardinf esmresolve. I will upgrade tonight and let you know

**Comment by rvmourik** [comment]
fixed! Thanks 🙏
