### ISSUE TITLE
Page Route not refresh the template request data

### ISSUE THREAD

**Issue by JamieDIng** [nuxt/framework#6361]
### Environment

Nuxt CLI v3.0.0-rc.6 
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `components`, `modules`, `css`, `plugins`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.4`, `@nuxtjs/color-mode@3.0.3`, `nuxt-lodash@2.2.0`
- Build Modules:    `-`
------------------------------

### Reproduction

npm run dev

[stackblitz link](https://stackblitz.com/edit/nuxt-starter-uwg9ug)

### Describe the bug

Page Route not refresh the template request data
When I link to jump to another page
 I don't have this problem when I use version 3.0.0-rc.1
Upgrade to 3.0.0-rc.6 There will be this problem
useFetch request { data }  data  not refresh (Always the first requested data)
Is the method changed?
I use usefetch to request

**Comment by danielroe** [comment]
Would you try the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) first? We've pushed a few fixes on this. And if that doesn't resolve it, would you provide a reproduction? 🙏

**Comment by matiyin** [comment]
I can confirm the same issue, fetch data is not updated when changing routes in rc6. rc1 works, the current edge channel does not solve the issue.

/pages/[slug].vue:

```<template>
  <main>
    <div v-if="pending">
      Loading ...
    </div>
    <div v-else >
      {{post}}
    </div>
  </main>
</template>

<script setup>
const { pending, data: post } = useLazyFetch('https://xxx')
</script>`

**Comment by JamieDIng** [comment]
> I can confirm the same issue, fetch data is not updated when changing routes in rc6. rc1 works, the current edge channel does not solve the issue.
> 
> /pages/[slug].vue:
> 
> ```
>   <main>
>     <div v-if="pending">
>       Loading ...
>     </div>
>     <div v-else >
>       {{post}}
>     </div>
>   </main>
> </template>
> 
> <script setup>
> const { pending, data: post } = useLazyFetch('https://xxx')
> </script>`
> ```
yes
rc1 is no problem

**Comment by JamieDIng** [comment]
> 
I try to create one stackblitz link ..Please wait

**Comment by JamieDIng** [comment]
> Would you try the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) first? We've pushed a few fixes on this. And if that doesn't resolve it, would you provide a reproduction? 🙏

[stackblitz link](https://stackblitz.com/edit/nuxt-starter-uwg9ug)

**Comment by qyn980427** [comment]
I think we can solve this problem if we set the useFetch initialCache option to false

**Comment by matiyin** [comment]
> I think we can solve this problem if we set the useFetch initialCache option to false

I can confirm using the `initialCache: false` option 'solves' the issue, but results in the pages always loading content again and showing a 'pending/loading' state because the payload is ignored. Not very desirable in my opinion.

@JamieDIng  I've updated the stackblitz accordingly https://stackblitz.com/edit/nuxt-starter-b3ut3j?file=pages/[id].vue
