### ISSUE TITLE
Duplicate response when calling a composable with useLazyFetch inside

### ISSUE THREAD

**Issue by lucassimines** [nuxt/framework#6365]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-16xwyo?file=app.vue,composables%2FuseApiFetch.ts

### Describe the bug

The bug is that, when using `useLazyFetch` inside a composable, and then call multiple different requests using the `custom function`, it returns the same data as the first request.

It is not generating an unique `key`

**Comment by aerksn** [comment]
any workaround for this one?

**Comment by manniL** [comment]
> any workaround for this one?

The workaround is to set the key manually for now (different for each usage where state shouldn't be shared)

**Comment by aerksn** [comment]
> > any workaround for this one?
> 
> The workaround is to set the key manually for now (different for each usage where state shouldn't be shared)

cool, thanks for quick reply! :)
