### ISSUE TITLE
If import composable in server/api the process.client and process.server is undefined

### ISSUE THREAD

**Issue by max5432112345** [nuxt/framework#6383]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.6-27660452.463c15e`
- Package Manager:  `npm@8.16.0`
- Builder:          `vite`
- User Config:      `auth`, `autoImports`, `buildModules`, `components`, `css`, `head`, `i18n`, `modules`, `router`, `runtimeConfig`, `target`, `telemetry`, `titleTemplate`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-alpha.0-27654621.987d743`, `@nuxt/image-edge@1.0.0-27657146.da85542`, `@pinia/nuxt@0.3.1`
- Build Modules:    `@nuxtjs-alt/auth@1.2.12`

### Reproduction

 https://github.com/nuxt/framework/blob/main/examples/other/locale/composables/locale.ts

### Describe the bug

In example[locale]( https://github.com/nuxt/framework/blob/main/examples/other/locale/composables/locale.ts)
is used process.server and process.client. Is that for SSR?
But it is undefined if import composable in server/api.

```
if (process.server) {

  } else if (process.client) {
  }
  ```

**Comment by danielroe** [comment]
Yes. `process.server` and `process.client` are for the Vue portion of your app, which might be running in either context. No such double context exists within Nitro routes, which are always only server.

I would also very strongly advise against using Vue composables in your Nitro routes.

**Comment by max5432112345** [comment]
@danielroe  and what to do if compossable is only for server/api (work with data base), throw an error with createError

**Comment by danielroe** [comment]
If it's only for `~/server/api`, then I would add it in `~/server/utils/some-file.ts`. And yes, you can throw an error with createError, which is auto-imported from `h3` within your Nitro server.

**Comment by max5432112345** [comment]
> If it's only for `~/server/api`, then I would add it in `~/server/utils/some-file.ts`. And yes, you can throw an error with createError, which is auto-imported from `h3` within your Nitro server.

@danielroe  but I cant determine is server or is client to throw error in such case

**Comment by max5432112345** [comment]
and process.server is not refer to server but to ssr, then is need proces.nuxt_vue and process.nuxt_nitro :)

**Comment by danielroe** [comment]
I would advise against sharing code between your Nitro + Vue bundles in this way.

**Comment by max5432112345** [comment]
> I would advise against sharing code between your Nitro + Vue bundles in this way.

ok, I understand. not sure but in as i made code for back end will go in front end bundle
