### ISSUE TITLE
add typings for `MetaObject`

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#6388]
`useHead` is currently not type-hinted for meta tags, links, and so on. It will be a good enhancement to port across the good TS work from https://github.com/nuxt/framework/pull/6251, as well as excluding viewport and charset from possible keys in `meta` tags.

See https://github.com/nuxt/framework/pull/6378#discussion_r938962711_

**Comment by harlan-zw** [comment]
This should be good to close
