### ISSUE TITLE
nuxt@3.0.0-rc.6 requires parse-path@^4.0.0 via a transitive dependency on parse-url@6.0.5

### ISSUE THREAD

**Issue by acidjazz** [nuxt/framework#6405]
### Environment

All

### Reproduction

https://github.com/advisories/GHSA-3j8f-xvm3-ffx4

### Describe the bug

https://github.com/advisories/GHSA-3j8f-xvm3-ffx4

**Comment by pi0** [comment]
Hi! The affected dependency is updated in the latest `@nuxt/telemetry` version. You can update lock file to get rid of this issue (BTW nothing to worry about. This issue was a false positive report and does not affect any usage in Nuxt since we only use it for build time and hash result)
