### ISSUE TITLE
Route middleware not working correctly when defined on a client side plugin

### ISSUE THREAD

**Issue by CodoPixel** [nuxt/framework#6414]
### Environment

Nuxt CLI v3.0.0-rc.6
RootDir: /Users/thomas/Documents/tests/nuxt-middleware-bug
Nuxt project info:

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Please, see a complete reproduction here (with Stackblitz link in README): https://github.com/CodoPixel/nuxtjs-issue-report

### Describe the bug

As you can see, on the reproduction, everything seems to be working fine if you're starting your app on `index.vue`. However, if you go to `page2.vue` and reload the page, it will raise a 500 error at the middle of the page.: 

```
500
Unknown route middleware: 'named-test'. Valid middleware: .
```

And a scary error in the terminal of VSC:

```
[Vue Router warn]: uncaught error during route navigation:
Error: Unknown route middleware: 'named-test'. Valid middleware: .
    at eval (file:///home/projects/github-55ybba/.nuxt/dist/server/server.mjs:2544:17)
[h3] [unhandled] H3Error: Unknown route middleware: 'named-test'. Valid middleware: .
    at createError (file:///home/projects/github-55ybba/node_modules/h3/dist/index.mjs:254:15)
    at Server.nodeHandler (file:///home/projects/github-55ybba/node_modules/h3/dist/index.mjs:444:21) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
[nuxt] [request error] Unknown route middleware: 'named-test'. Valid middleware: .
  at createError (./node_modules/h3/dist/index.mjs:254:15)  
  at Server.nodeHandler (./node_modules/h3/dist/index.mjs:444:21)
[Vue Router warn]: uncaught error during route navigation:
Error: Unknown route middleware: 'named-test'. Valid middleware: .
    at eval (file:///home/projects/github-55ybba/.nuxt/dist/server/server.mjs:2544:17)
[Vue Router warn]: uncaught error during route navigation:
Error: Unknown route middleware: 'named-test'. Valid middleware: .
    at eval (file:///home/projects/github-55ybba/.nuxt/dist/server/server.mjs:2544:17)
[h3] [unhandled] H3Error: Unknown route middleware: 'named-test'. Valid middleware: .
    at createError (file:///home/projects/github-55ybba/node_modules/h3/dist/index.mjs:254:15)
    at Server.nodeHandler (file:///home/projects/github-55ybba/node_modules/h3/dist/index.mjs:444:21) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
[nuxt] [request error] Unknown route middleware: 'named-test'. Valid middleware: .
  at createError (./node_modules/h3/dist/index.mjs:254:15)  
  at Server.nodeHandler (./node_modules/h3/dist/index.mjs:444:21)
[Vue Router warn]: uncaught error during route navigation:
Error: Unknown route middleware: 'named-test'. Valid middleware: .
    at eval (file:///home/projects/github-55ybba/.nuxt/dist/server/server.mjs:2544:17)
```

According to my tests, the problem comes from the fact that I am using `addRouteMiddleware` inside a client side plugin `test.client.ts`. The problem goes away when I remove `.client` from the file name.

Therefore, as the [documentation](https://v3.nuxtjs.org/guide/directory-structure/middleware#adding-middleware-dynamically) doesn't say anything about a difference between client side and server side plugin, I guess it's an issue.

You're probably wondering why I'm not using `middleware` directory instead as a work-around, well, see [this question on stackoverflow](https://stackoverflow.com/questions/73261158/impossible-to-use-middlewares-with-firebase-and-nuxtjs-3) and you'll understand my despair.

### Additional context

I'm trying to use Firebase with NuxtJS 3. Authentication seems to be working fine... but if I want to prevent users from accessing a specific part of the website with a middleware (which would abort the navigation if the user is not admin or if he's not authenticated) it doesn't work. More details on [stackoverflow](https://stackoverflow.com/questions/73261158/impossible-to-use-middlewares-with-firebase-and-nuxtjs-3).

I hope you'll help me find a work-around for my project I'd like to finish before September.
A work around I had found is to use `await navigateTo('/')` in setup script on secret pages but it doesn't work when accessing the page via the URL, as you can see on this other [stackoverflow question](https://stackoverflow.com/questions/73262789/how-to-abort-navigation-to-a-page-with-nuxtjs-3).

If the behaviour I described is indeed an issue you didn't know, then I'm glad I could help.

**Comment by danielroe** [comment]
Yes, I would expect doing this to throw an error if you are defining it on server also. You could conceivably only use the middleware on client though:

```js
definePageMeta({
  middleware: process.client ? 'named-test' : undefined
})
```

Or you could also add a server-only _version_ of the middleware without the full functionality of the client-side one.

I would expect you would _want_ this middleware defined on server side. Is there a reason you are defining it in a client-only plugin?

**Comment by CodoPixel** [comment]
I need client side for Firebase, because as far as I know Firebase needs to be initialized on the client side, am I right?

**Comment by CodoPixel** [comment]
> Yes, I would expect doing this to throw an error if you are defining it on server also. You could conceivably only use the middleware on client though:
> 
> ```js
> definePageMeta({
>   middleware: process.client ? 'named-test' : undefined
> })
> ```
> 
> Or you could also add a server-only _version_ of the middleware without the full functionality of the client-side one.
> 
> I would expect you would _want_ this middleware defined on server side. Is there a reason you are defining it in a client-only plugin?

Your method works, but not if i enter the URL localhost:3000/login directly...

**Comment by danielroe** [comment]
It will still run, but on the client-side only. If you want it to run on the server side, then you should add a server implementation of the plugin.

**Comment by CodoPixel** [comment]
> It will still run, but on the client-side only. If you want it to run on the server side, then you should add a server implementation of the plugin.

I cannot define a server side plugin for Firebase Authentication. It must be done on client side only, and if I try I get "500 - component auth has not been registered yet"

All I want is to redirect the user if he tries to access a page he's not authorized in. As far as I know, the best way to do that is to use middlewares. However, they won't load after the plugin that initialises the authentication, therefore it is impossible to check whether the user is authorised or not.

Using a condition as proposed (using process.client) doesn't seem to be working when writing the URL via the web browser itself. Why this difference?

Besides, trying to redirect the user with another method (like using the value of a useState having the user instance and then use 'await navigateTo') doesn't work either and throws a weird error, again only when accessing the page via the URL of the browser.

For me, it seems like an issue smarter people could save in NuxtJS directly.

**Comment by danielroe** [comment]
It makes sense that you need this middleware on the server, yes. But as firebase auth only works on the client, you have a challenge. What is the right behaviour in your project for a server-side rendered page that needs auth? I'm afraid I can't solve that for you, but once you decide on the right behaviour (maybe you just refuse to render it on SSR, or you just render a shell of a page?) you can then implement it. But it's very specific to the logic of your individual project.

**Comment by CodoPixel** [comment]
> It makes sense that you need this middleware on the server, yes. But as firebase auth only works on the client, you have a challenge. What is the right behaviour in your project for a server-side rendered page that needs auth? I'm afraid I can't solve that for you, but once you decide on the right behaviour (maybe you just refuse to render it on SSR, or you just render a shell of a page?) you can then implement it. But it's very specific to the logic of your individual project.

Indeed, it's been a challenge for several days, without any answer yet. But I don't understand why you say it's "very specific to the logic of your individual project". Firebase is used by many developers and an admin section that needs to stay secret, yet open to some users, should be an important part of a lot of websites. Am I wrong?

**Comment by danielroe** [comment]
Ah, yes, that certainly is true. We will be adding a `spa` route rule that allows you to mark all paths matching a certain pattern as client-only. (And that is likely the best solution in your case too.)

**Comment by mweber06** [comment]
I believe the issue boils down to requiring Firebase Authentication to execute safely on the client's side while communicating to the server and Firebase that the user's login credentials are valid. To do this while still allowing the use of SSR, Firebase provides admin controls that can validate auth tokens passed via cookies. Firebase admin can also perform privileged actions on behalf of the user as long as this is done server-side with protected APIs; this can be more flexible than rule sets so it might be worth considering.

A complete implementation can be found here [nuxt-firebase-auth-starter](https://github.com/wobsoriano/nuxt-firebase-auth-starter) sans actually reading or writing data. In general, Firebase is for the client while Firebase admin is for the server.

Though heads up, this requires the experimental vite-node to be enabled, so proceed with caution as things might be bumpy with that on.

**Comment by CodoPixel** [comment]
Thanks for the ideas, but for my project I will use something safer. I came up with a work-around using layouts.

First, instead of passing the value of User instance from Firebase via the hook `useFirebaseUser`, I'm adding a `loading` state:

`composables/useFirebaseUser.ts`
```typescript
import type {User} from "firebase/auth";

interface FirebaseUser {
    loading: boolean,
    user: User | null,
}

export const useFirebaseUser = () => useState<FirebaseUser>("user", () => ({ loading: true, user: null }));
```

`loading` property is important because if the user is indeed signed in, the `getAuth().currentUser` will get its value once `onAuthStateChanged` will have been executed the first time:

`plugins/firebase.client.ts`
```typescript
import { initializeApp } from "firebase/app";
import { onAuthStateChanged, getAuth } from "firebase/auth";

export default defineNuxtPlugin(() => {
    const firebaseConfig = {
        // ...
    };

    const app = initializeApp(firebaseConfig);
    const auth = getAuth(app); // .currentUser is null for now, we need to wait for `onAuthStateChanged` to get the value
    const firebaseUser = useFirebaseUser();
    onAuthStateChanged(auth, (user) => {
        firebaseUser.value = {
            loading: false,
            user,
        };
    });
});
```

By default, on the first mount, the state will have `loading` set to true which allows us to display a loading animation on the pages that use the following layout:

`layouts/restricted.vue`
```html
<script setup lang="ts">
const state = reactive({ authorized: false, loading: true });
const user = useFirebaseUser();

watchEffect(async () => {
  if (!user.value.loading) {
    await isAuthorized();
  }
});

async function isAuthorized() {
  const userData = await getUserData(user.value.user.uid); // fetch the document associated with the user in Firestore, from  the custom composables/useFirestore.ts
  if (userData && userData.isAdmin) { // which contains an `isAdmin` property
    state.authorized = true;
  }
  state.loading = false;
}
</script>

<template>
  <div>
    <div v-if="state.loading" class="loading-container">
      <div class="circle" />
    </div>
    <div v-else-if="!state.authorized">
      <h1>Not authorized</h1>
      <NuxtLink to="/"><button>Go back</button></NuxtLink>
    </div>
    <div v-else>
      <slot />
    </div>
  </div>
</template>

<style scoped>
.loading-container {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 2000;
  background-color: rgba(0, 0, 0, 0.6);
  display: flex;
  justify-content: center;
  align-items: center;
  pointer-events: all;
}

.circle {
  cursor: default;
  pointer-events: none;
  position: relative;
}

.circle::after {
  position: absolute;
  content: "";
  top: 50%;
  left: 50%;
  margin: -1.5em 0 0 -1.5em;
  width: 3em;
  height: 3em;
  animation: segment-spin 0.6s linear infinite;
  border-radius: 100%;
  border-color: #767676 rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1);
  border-style: solid;
  border-width: 0.2em;
  box-shadow: 0 0 0 1px transparent;
  visibility: visible;
}

@keyframes segment-spin {
  from {
    transform: rotate(0);
  }
  to {
    transform: rotate(360deg);
  }
}
</style>
```

Pages requiring admin restrictions won't load the protected content.

**Comment by szulcus** [comment]
@danielroe For me, middleware only works when placed in one of the pages from `~/pages`. Putting this in an `app.vue`, layout or nuxt configuration file doesn't work. I am using RC8 (so far, this is the only "working" version for me). Is this the expected behavior?

**Comment by danielroe** [comment]
@szulcus Yes. You can use `definePageMeta` only in a page, not in `app.vue` or a layout. For use cases, you can use global route middleware or register middleware in a plugin.

**Comment by szulcus** [comment]
@danielroe So that's right. Thanks!

**Comment by szulcus** [comment]
Route middleware like this? This, unfortunately, does not work for me:
```ts
defineNuxtConfig({
	// ...
	router: {
		middleware: ['auth'],
	},
});

```
I'll try to do it with a plug. Thank you for your response.

**Comment by danielroe** [comment]
No. Global middleware you simply create in `~/middleware/auth.global.ts` and it is automatically registered.

**Comment by szulcus** [comment]
@danielroe Indeed, I overlooked it in the documentation. Everything works now. Thank you very much for your answer.
