### ISSUE TITLE
head does not add preload links

### ISSUE THREAD

**Issue by rwwagner90** [nuxt/framework#6416]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `target`, `ssr`, `css`, `head`, `image`, `modules`, `vite`, `content`
- Runtime Modules:  `@nuxt/content@2.0.1`, `@nuxt/image-edge@1.0.0-27621400.93ce78a`, `@nuxtjs/tailwindcss@5.1.3`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/shipshapecode/website-nuxt-3

### Describe the bug

Preload links in `head` in nuxt.config.ts are not added to the head. Things like this:

```js
    link: [
      {
        rel: 'preload',
        href: '~/assets/fonts/PierSans-Bold.woff2',
        as: 'font',
        type: 'font/woff2',
      },
      {
        rel: 'preload',
        href: '~/assets/fonts/PierSans-Light.woff2',
        as: 'font',
        type: 'font/woff2',
      },
      {
        rel: 'preload',
        href: '~/assets/fonts/PierSans-Regular.woff2',
        as: 'font',
        type: 'font/woff2',
      },
    ],
    ```

If the same thing is added to `useHead` it is added to the head, but then the paths will be wrong because if you put it in app.vue, it changes the path for every page. We need a way to do this one time globally.

**Comment by Aareksio** [comment]
I think current key for meta properties is `app.head`:

```js
export default defineNuxtConfig({
  app: {
    head: { link: [] }
  }
})
```

It is a mess and changes every other moon phase, so be sure to check `app.head`, `app.meta`, `head` and `meta`, one should work.

**Comment by rwwagner90** [comment]
@Aareksio ah, so it is! Silly me for following the documentation for Nuxt 3 😛

**Comment by TixieBorg** [comment]
I was wondering if there was a way to resolve assets paths into metal/link tags?

I see @rwwagner90 did like me by prefixing paths with `~/assets` (cf [assets doc](https://v3.nuxtjs.org/guide/features/assets#example-1)) but it doesn't seem to work for me. Either in defineNuxtConfig or with [built-in Meta components](https://v3.nuxtjs.org/migration/meta#example-built-in-meta-components) inside App.vue.

I may have miss something in documentation but I haven't found any example with assets path inside head config. Did you had better luck than me on that?
