### ISSUE TITLE
iphone7 safari vue hook mounted no run

### ISSUE THREAD

**Issue by liuzycc** [nuxt/framework#6425]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.4`
- Builder:          `webpack`
- User Config:      `builder`, `app`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

My attempts to create a template project also failed
// form: app.vue
<template>
  <div>
    <p>{{a}}</p>
    <NuxtWelcome />
  </div>
</template>
<script lang="ts" setup>
import { onMounted } from "vue";
let a = ref("111")
console.error('111')
onMounted(async()=>{
  console.error('444444')
  a.value = '222'
})
</script>

### Describe the bug

iphone7 safari vue hook mounted no run  chrome/iphone 12 safari is ok

**Comment by liuzycc** [comment]
“444444” The content is not printed in iphone7 safari

**Comment by danielroe** [comment]
would you provide more information? What Safari version are you running on that phone?

**Comment by liuzycc** [comment]
> 你会提供更多信息吗？您在该手机上运行的 Safari 版本是什么？

ios versions 13.3 safari 13.0

**Comment by liuzycc** [comment]
> 你会提供更多信息吗？您在该手机上运行的 Safari 版本是什么？

ios versions 13.3 safari 13.0

**Comment by liuzycc** [comment]
> would you provide more information? What Safari version are you running on that phone?

import { useMounted } from '@vueuse/core';
const mounted = useMounted(); // false
iphone7 safari  and part android phone

**Comment by liuzycc** [comment]
> would you provide more information? What Safari version are you running on that phone?

hello  
Do we have any solutions to the above problems at present

**Comment by liuzycc** [comment]
> would you provide more information? What Safari version are you running on that phone?

https://stackblitz.com/edit/github-n3gwu6?file=package.json,app.vue
