### ISSUE TITLE
Dynamic routing as a request body parameter is inconsistent between client and server

### ISSUE THREAD

**Issue by poemtalent** [nuxt/framework#6426]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

none

### Describe the bug

I want to make the dynamic route a request body parameter, Such as below:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/48041365/183341240-5d966de7-5de4-4b51-bf36-4b286b52b915.png">
It is normal in the browser, but always 'favicon.ico' on the server.
<img width="387" alt="image" src="https://user-images.githubusercontent.com/48041365/183341494-55e458c0-fdf4-4e7e-817d-4507dda353c9.png">
<img width="288" alt="image" src="https://user-images.githubusercontent.com/48041365/183341554-4e8d6443-69c3-4a75-b99b-cd907ac91ef5.png">
The /server/ API file is edited like this
<img width="287" alt="image" src="https://user-images.githubusercontent.com/48041365/183341873-0f6ec97d-e1d2-4ee4-aa0f-bd0f043d1c33.png">
However, the server obtains the request body as shown in the following figure:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/48041365/183342164-e787c63e-6461-439d-a78f-ba7140a78472.png">

**Comment by danielroe** [comment]
I suspect this is your browser just making a request for `/favicon.ico`. If you don't have one in your public folder, and you have a dynamic route that would match it, your app will try to render html for that request.

**Comment by poemtalent** [comment]
> I suspect this is your browser just making a request for `/favicon.ico`. If you don't have one in your public folder, and you have a dynamic route that would match it, your app will try to render html for that request.

But when I use String，such as "params = {test:'test'}", I can get the right params with event.req.body in api file

**Comment by danielroe** [comment]
Would you provide a reproduction that makes clear what the issue is? 🙏

**Comment by poemtalent** [comment]
> Would you provide a reproduction that makes clear what the issue is? 🙏

I solved it, and the main reason is what you mentioned above.Thanks a lot
