### ISSUE TITLE
The data returned by useFetch has contents, but the value is null where  lazy is true

### ISSUE THREAD

**Issue by qyn980427** [nuxt/framework#6427]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.17.5`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@6.14.14`
- Builder:          `vite`
- User Config:      `alias`, `runtimeConfig`, `css`, `modules`, `postcss`, `autoImports`, `hooks`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.1`, `@pinia/nuxt@0.3.1`, `@vueuse/nuxt@8.9.4`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-svkc8u?file=pages%2Findex.vue,pages%2Ftest.vue

### Describe the bug

When you go to the test page and you go back to the index page through nuxtLink, you get this situation that I just described, 
![Uploading image.png…]()

### Additional context

I am not sure if this problem occurs only when lazy is true. I have encountered the situation that the data has content but the value cannot be obtained for several times. At present, it will occur in the demo I provided 

step:
1.The URL directly accesses /test 
2.Go back to Index via Nuxtlink 
3.To view the log

**Comment by qyn980427** [comment]
![image](https://user-images.githubusercontent.com/65841456/183348894-07ef6cc5-60dd-4c39-a22d-4d3ae2182178.png)

**Comment by CapitaineToinon** [comment]
You're getting confused by how the developer console is working on your browser. Objects are evaluated by the console when you expand them, not when they're being logged. Consider the following example:

```js
let test = {};

setTimeout(() => {
  test.exists = 'Yes!';
}, 1000);

console.log(test);
```

If you expand the object in the console before the setTimeout has a chance to run, the object will be empty. However if you expand after the setTimeout, the `exists` key will be there. 

<img width="182" alt="image" src="https://user-images.githubusercontent.com/15376923/183357925-c66fc00a-5e99-4b77-80aa-ef2bd162d7d6.png">

`useFetch` with the lazy `flag` means both your console logs will happen before the fetch call so there is no bug here. When logging reactive variables, it's usually a good idea to always wrap your console log in a `watchEffect` call.

**Comment by qyn980427** [comment]
Thank you. Your reply has solved my confusion, but it seems that this is not the best way to deal with it. Is there any other way?

**Comment by CapitaineToinon** [comment]
I suggest you read the [data fetching](https://v3.nuxtjs.org/guide/features/data-fetching) section of nuxt 3's documentation for ways to deal with this. Either you will rely on a lazy solution, in which case you will need to deal with the data being null for a while, or you don't use a lazy solution but your fetch will block navigation until data is there.

**Comment by qyn980427** [comment]
I appreciate that, brother!
