### ISSUE TITLE
Module "child_process" has been externalized for browser compatibility. Cannot access "child_process.spawn" in client code

### ISSUE THREAD

**Issue by Sitronik** [nuxt/framework#6438]
### Environment

* Operating System: MacOS Catalina
* Node Version: v16.15.1
* Nuxt Version: v3.0.0-rc.6-27665998.e40286e
* Package Manager: yarn@1.22.19
* Builder: vite
* Modules: bootstrap-vue-3/nuxt
* BuildModules: @nuxtjs/eslint-module, unplugin-icons/nuxt, @intlify/nuxt3, @nuxtjs/svg, @vueuse/nuxt
* transpile: @headlessui/vue, vue-datepicker-next

### Reproduction

```"nuxt": "npm:nuxt3@v3.0.0-rc.6-27665998.e40286e"```
``` "socket.io-client": "^2.2.0"```

### Describe the bug

When I start development, nuxt dev the build succeeds but in the browser I get an error.
But in the production build there is no such error in the browser
I found the same issue:
https://github.com/socketio/socket.io-client/issues/1549
Maybe it has something to do with vite?

```"nuxt": "npm:nuxt3@v3.0.0-rc.6-27665998.e40286e"```
```"socket.io-client": "^2.2.0"```

But if I installed ```npm:nuxt3@v3.0.0-rc.5-27635619.296c552``` I have no error

```js 
browser-external:child_process:9 Uncaught Error: Module "child_process" has been externalized for browser compatibility. Cannot access "child_process.spawn" in client code.
    at Object.get (browser-external:child_process:9:13)
    at node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js (XMLHttpRequest.js:16:13)
    at __require2 (chunk-S5KM4IGW.js?v=5dce256d:18:50)
    at node_modules/engine.io-client/lib/transports/index.js (index.js:5:22)
    at __require2 (chunk-S5KM4IGW.js?v=5dce256d:18:50)
    at node_modules/engine.io-client/lib/socket.js (socket.js:5:18)
    at __require2 (chunk-S5KM4IGW.js?v=5dce256d:18:50)
    at node_modules/engine.io-client/lib/index.js (index.js:2:18)
    at __require2 (chunk-S5KM4IGW.js?v=5dce256d:18:50)
    at node_modules/socket.io-client/lib/manager.js (manager.js:6:11)```

**Comment by danielroe** [comment]
Yes, I think this is likely a vite 3 issue. You might try configuring `vite.optimizeDeps` and `build.transpile`.

**Comment by Sitronik** [comment]
> Yes, I think this is likely a vite 3 issue. You might try configuring `vite.optimizeDeps` and `build.transpile`.

Thanks for the quick response. I tried  configuring ```vite.optimizeDeps``` and ```build.transpile``` but didn't help
I solved this problem by updating the modules to the latest version

```"socket.io-client": "^4.5.1"```
```"socket.io": "^4.5.1"```

Now everything works correctly and without errors
