### ISSUE TITLE
Why nuxt-i18n edge not work in SSR 

### ISSUE THREAD

**Issue by max5432112345** [nuxt/framework#6450]
### Environment

"nuxt": "npm:nuxt3@latest"
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",

### Reproduction

https://github.com/max5432112345/nuxt-error-1 (I also added Pinia, axios-alt, and auth-alt)

1 chage in nuxt config to SSR
  target: 'static',

  // ssr: false,

2 npm run dev

### Describe the bug

text what is need to be translate disappeared

### Additional context
```
// @nuxtjs/i18n configuration
{

i18n: {
    defaultLocale: 'en',
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected'
      // onlyOnRoot: true
    },
    langDir: 'locales/',
    lazy: true,
    locales: [
      {
        code: 'en',
        file: 'en.json',
        iso: 'en-US',
        name: 'US'
      },
      {
        code: 'gb',
        file: 'gb.json',
        iso: 'en-GB',
        name: 'GB'
      }
    ],
    noPrefixDefaultLocale: false,
    parsePages: false,
    seo: false,
    strategy: 'prefix',
    vueI18n: {
      fallbackLocale: 'en',
      // silentFallbackWarn: true
    },
    vueI18nLoader: true
  },

  target: 'static',

  // ssr: false,
}
```

**Comment by max5432112345** [comment]
https://github.com/nuxt-community/i18n-module/issues/1484

**Comment by danielroe** [comment]
Please see https://github.com/nuxt/framework/issues/6300#issuecomment-1205815525. Here is a working stackblitz: https://stackblitz.com/edit/github-ktzuls?file=package.json.

**Comment by max5432112345** [comment]
@danielroe  I read it prior, and switched to  "npm:nuxt3@latest" (i also get name of the most rc compiled at that moment from npmjs.com but not help) and the problem #6300 disappear. 
All was good until I not try SSR mode yesterday.
Today I your example is dependencies  "@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge" and devDependencies  "nuxt": "npm:nuxt3@3.0.0-rc.6-27667209.03cd671"

Thank you, I will try with that versions.
_____________________________________________________
Sorry and one more question with pinia https://github.com/vuejs/pinia/issues/1530

**Comment by max5432112345** [comment]
@danielroe I think it not work, i make a new repo

**Comment by max5432112345** [comment]
@danielroe I found what is problem 
https://github.com/nuxt/framework/issues/6466
