### ISSUE TITLE
builder:webpack  dev failed 

### ISSUE THREAD

**Issue by liuzycc** [nuxt/framework#6453]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.4`
- Builder:          `webpack`
- User Config:      `builder`, `app`, `css`, `typescript`, `vite`, `runtimeConfig`, `webpack`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

How can I extend it to solve this problem

### Describe the bug

Module not found: Error: Can't resolve './ModelTVVideoPlugin' in '/node_modules/@realsee/dnalogel/libs'
Did you mean 'index.js'?
BREAKING CHANGE: The request './ModelTVVideoPlugin' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

Also see https://v3.nuxtjs.org/guide/going-further/esm.

**Comment by liuzycc** [comment]
> Would you provide a reproduction? 🙏
> 
> Also see https://v3.nuxtjs.org/guide/going-further/esm.

I created a replica with the same error

https://stackblitz.com/edit/github-lc4ebw?file=nuxt.config.ts,app.vue

**Comment by danielroe** [comment]
You can see the issue here is with the upstream library using ESM in a `.js` file: https://unpkg.com/browse/@realsee/dnalogel@2.0.0-alpha.41/libs/index.js

You can resolve it by adding the library to your transpile array:

```js
import { defineNuxtConfig } from 'nuxt';

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  builder: 'webpack',
  build: { transpile: [/@realsee/] },
});
```

**Comment by liuzycc** [comment]
> 

It solved my problem🙏 thanks
