### ISSUE TITLE
Add 3rd party loader to Webpack

### ISSUE THREAD

**Issue by mannok** [nuxt/framework#6456]
### Describe the feature

From Nuxt 3 document, we can only configure for Nuxt integrated Webpack loaders https://v3.nuxtjs.org/api/configuration/nuxt.config#loaders and the loaders used by Nuxt have already been defined.

May I know if it is possible to add my custom loader or any 3rd party loader in my project like how orginal Webpack offer us? https://webpack.js.org/concepts/loaders/

For instance, what should I do if I need to use this loader in Nuxt3?
https://github.com/Ansimorph/decryption-loader

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
You can use the `webpack:config` hook to get direct access to update and change the webpack config used in your app.
