### ISSUE TITLE
404 page nuxt3

### ISSUE THREAD

**Issue by brunokunace** [nuxt/framework#6457]
### Environment

Nuxt CLI v3.0.0-rc.6-27667279.0b22079                                      08:01:53
RootDir: /home/projects/github-2ahkgu                                      08:01:57
Nuxt project info:                                                         08:01:57

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6-27667279.0b22079`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/ui@0.2.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-2ahkgu?terminal=dev

access a invalid route like

https://github-2ahkgu--3000.local.webcontainer.io/invalid

### Describe the bug

i trying to create a 404 custom page, like in v2, but have only the default 404 nuxt page.

**Comment by danielroe** [comment]
Don't create `~/layouts/error.vue`. Instead, you create `~/error.vue`. See https://v3.nuxtjs.org/guide/features/error-handling#rendering-an-error-page.
