### ISSUE TITLE
Client only components

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#646]
Related: #315, #648, #413

- [ ] Support `<ClientOnly>` component similar to Nuxt 2 (we can inspire from [egoist/vue-client-only](https://github.com/egoist/vue-client-only))
- [ ] Support `Foo.client.vue` to be removed from SSR bundle

Discussion: When using `<Foo>` without a `<ClientOnly>` wrapper, should we still support placeholder attribute and slot similar to `<ClientOnly>`? If not we are basically going to use a null element until hydration that can significantly affect client performance and make layout shifts.

**Comment by andysay** [comment]
ClientOnly not work now ?

**Comment by bountyx** [comment]
> ClientOnly not work now ?

Yeah, it seems to be the case that its not yet working.

**Comment by Atinux** [comment]
It is not yet implemented

**Comment by webfansplz** [comment]
mark

**Comment by webfansplz** [comment]
@pi0 Hi, do we have any plans to support it recently ?

**Comment by Gyurmatag** [comment]
Hey! When this will be available?

**Comment by birdlavv** [comment]
Hey @Gyurmatag, it looks like it may be already available in the newer releases.
Check out: https://v3.nuxtjs.org/docs/directory-structure/components/#clientonly-component
