### ISSUE TITLE
useFetch disabling/pausing queries

### ISSUE THREAD

**Issue by amit548** [nuxt/framework#6461]
### Describe the feature

If we want to disable a query from automatically running how we can do that by just using useFetch hook?
I am not sure about this, I want to call useFetch when one API called finished and then start to calling another useFetch to fetch some more related data.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by amit548** [comment]
Yes

**Comment by pi0** [comment]
Lets track via linked issue
