### ISSUE TITLE
routes parameters 404

### ISSUE THREAD

**Issue by okxiaoliang4** [nuxt/framework#6463]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `pnpm@7.7.0`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `runtimeConfig`
- Runtime Modules:  `@unocss/nuxt@0.45.5`, `@vueuse/nuxt@9.1.0`
- Build Modules:    `-`

### Reproduction

https://github.com/okxiaoliang4/nuxt-repo

### Describe the bug

visit the `http://localhost:3000/u/xxx` will got a 404 https status, not 302 Redirect.

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/issues/6465#issuecomment-1209897058.

```diff
	  import { defineEventHandler, sendRedirect } from "h3";
	  
	  export default defineEventHandler(async (event) => {
	    await new Promise((resolve, reject) => {
	      setTimeout(resolve, 1000);
	    });
-	    sendRedirect(event, 'https://google.com');
+	    return sendRedirect(event, 'https://google.com');
	  });
```

**Comment by okxiaoliang4** [comment]
> See [#6465 (comment)](https://github.com/nuxt/framework/issues/6465#issuecomment-1209897058).
> 
> ```diff
> 	  import { defineEventHandler, sendRedirect } from "h3";
> 	  
> 	  export default defineEventHandler(async (event) => {
> 	    await new Promise((resolve, reject) => {
> 	      setTimeout(resolve, 1000);
> 	    });
> -	    sendRedirect(event, 'https://google.com');
> +	    return sendRedirect(event, 'https://google.com');
> 	  });
> ```

Thanks, But i tried it the request always pending.
<img width="928" alt="image" src="https://user-images.githubusercontent.com/22525904/183940592-04fe60d7-bdc7-473d-9f09-062a76ac49e5.png">

**Comment by danielroe** [comment]
Seems to be working for me: https://stackblitz.com/edit/github-1csxni?file=server%2Froutes%2Fu%2F[id].ts
