### ISSUE TITLE
ERR_STREAM_WRITE_AFTER_END when using sendRedirect in server API

### ISSUE THREAD

**Issue by crtr-luke** [nuxt/framework#6465]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```js
export default defineEventHandler(async (event) => {
    const query = useQuery(event);
    const uniqueKey = 1234;
    const authRoute = `https://www.google.com/search?q=${uniqueKey}`;
    console.log(authRoute);
    sendRedirect(event, authRoute, 300);
})
```

### Describe the bug

Try to redirect the user via [h3's sendRedirect function](https://www.jsdocs.io/package/h3#sendRedirect) but get an ERR_STREAM_WRITE_AFTER_END error instead.

### Logs

```shell
[nitro] [dev] [uncaughtException] Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (internal/errors.js:322:7)
    at writeAfterEnd (_http_outgoing.js:694:15)
    at ServerResponse.end (_http_outgoing.js:815:7)
    at ServerResponse.res.end (file:///[cwd]/.nuxt/dev/index.mjs:77:10)
    at Immediate._onImmediate (file:///[cwd]/node_modules/h3/dist/index.mjs:138:17)
    at processImmediate (internal/timers.js:464:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
```

**Comment by danielroe** [comment]
`sendRedirect` is an async function. So you need to await it or return it.
