### ISSUE TITLE
The data displayed on the page was not what I expected

### ISSUE THREAD

**Issue by poemtalent** [nuxt/framework#6474]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[click to reproduction](https://stackblitz.com/edit/github-dszswy?file=app.vue)

### Describe the bug

Can someone tell me why the value of variable title or titleReactive output on the server terminal is exactly what I want, but "Mount changed title" instead of the initial value "Mount Everest"  on the browser console.The 'titleReactive' displayed on the page was not what I expected. I hope it is "Mount Everest"
```vue
// app.vue
<template>
  <div>
    <div>Fetched from
      <pre>/api/mountain</pre>
      the data is: {{ mountain }}
      <div>{{titleReactive}}</div>
    </div>
  </div>
</template>

<script setup>
import {reactive} from "vue"
const {data: mountain} = await useFetch('/api/mountain');
console.log("initial data is:", JSON.stringify(mountain))
console.log("data is:", mountain)
const title = mountain.value.title;
console.log("title is:", title);
console.log('typeof title is:', typeof title);
const titleReactive = reactive(title)
mountain.value.title = 'Mount changed title'
// console.log("title is:", title);
// console.log("data is:", mountain)
// console.log("data.value is:", mountain.value)
// console.log("data.value.title is:", mountain.value?.title)
</script>
```
```javascript
// /server/api/mountain.js
export default defineEventHandler(() => {
    return {
        title: 'Mount Everest',
    }
})
```

### Logs

```shell
# the terminal log
initial data is: {"__v_isShallow":false,"__v_isRef":true,"_rawValue":{"title":"Mount Everest"},"_value":{"title":"Mount Everest"}}
value cannot be made reactive: Mount Everest
data is: RefImpl {
  __v_isShallow: false,
  dep: undefined,
  __v_isRef: true,
  _rawValue: { title: 'Mount Everest' },
  _value: { title: 'Mount Everest' }
}
title is: Mount Everest
typeof title is: string
initial data is: {"__v_isShallow":false,"__v_isRef":true,"_rawValue":{"title":"Mount Everest"},"_value":{"title":"Mount Everest"}}
value cannot be made reactive: Mount Everest
data is: RefImpl {
  __v_isShallow: false,
  dep: undefined,
  __v_isRef: true,
  _rawValue: { title: 'Mount Everest' },
  _value: { title: 'Mount Everest' }
}
title is: Mount Everest
typeof title is: string




# the browser console log
initial data is: {"__v_isShallow":false,"__v_isRef":true,"_rawValue":{"title":"Mount changed title"},"_value":{"title":"Mount changed title"}}
app.vue:15 data is: RefImpl {__v_isShallow: false, dep: undefined, __v_isRef: true, _rawValue: {…}, _value: Proxy}
app.vue:17 title is: Mount changed title
app.vue:18 typeof title is: string
```

**Comment by danielroe** [comment]
reactive can only take an object, not a string. See https://vuejs.org/api/reactivity-core.html#reactive.

The data object returned from useFetch is a Ref, https://vuejs.org/api/reactivity-core.html#ref, which is what you are seeing logged.

I am not sure what you are trying to achieve, but possibly `const titleReactive = computed (() => mountain.value.title)`

---

FYI, next time, this would be better as a discussion as it is neither a bug or a feature request.

**Comment by poemtalent** [comment]
Maybe I didn't describe the problem clearly.I have updated the reproduction. The /api/mountain  returned title "**Mount Everest**".  when I get the data returned from useFetch,  **const titleConst = mountain.value.title;** and I think the typeof titleConst is String. After that , **mountain.value.title = 'Mount changed title';**. Therefore, I think the titleConst should be **Mount Everest**,But titleConst is actually **Mount Changed Title in** Google Chrome.  Please notice the difference between the WebStorm terminal and the Google console that I've highlighted/
```vue
// app.vue
<template>
  <div>
    <div>
      Fetched from
      <pre>/api/mountain</pre>
      the data is: {{ mountain }}
      <div>{{ titleReactive }}</div>
    </div>
  </div>
</template>

<script setup>
import { reactive, ref } from 'vue';
const { data: mountain } = await useFetch('/api/mountain');
console.log('mountain.value:', JSON.stringify(mountain.value));
console.log('mountain.value.title:', mountain.value.title);
const titleConst = mountain.value.title;
console.log('titleConst is:', titleConst);
console.log('typeof titleConst is:', typeof titleConst);
const titleReactive = ref(titleConst);
mountain.value.title = 'Mount changed title';
</script>
```
```javascript
// /server/api/mountain.js
export default defineEventHandler(() => {
    return {
        title: 'Mount Everest',
    }
})
```
![image](https://user-images.githubusercontent.com/48041365/183861605-3323b81c-78e2-4fbd-b8ff-dcbf2e0272eb.png)

**Comment by poemtalent** [comment]
The point is that constTitle is different in the webStorm terminal than in the Google console.I'm sorry to disturb you. Is it convenient for you to have a look

**Comment by poemtalent** [comment]
> reactive can only take an object, not a string. See https://vuejs.org/api/reactivity-core.html#reactive.
> 
> The data object returned from useFetch is a Ref, https://vuejs.org/api/reactivity-core.html#ref, which is what you are seeing logged.
> 
> I am not sure what you are trying to achieve, but possibly `const titleReactive = computed (() => mountain.value.title)`
> 
> FYI, next time, this would be better as a discussion as it is neither a bug or a feature request.

Maybe I didn't describe the problem clearly.I have updated the reproduction. The /api/mountain  returned title "**Mount Everest**".  when I get the data returned from useFetch,  **const titleConst = mountain.value.title;** and I think the typeof titleConst is String. After that , **mountain.value.title = 'Mount changed title';**. Therefore, I think the titleConst should be **Mount Everest**,But titleConst is actually **Mount Changed Title in** Google Chrome.  Please notice the difference between the WebStorm terminal and the Google console that I've highlighted/
```vue
// app.vue
<template>
  <div>
    <div>
      Fetched from
      <pre>/api/mountain</pre>
      the data is: {{ mountain }}
      <div>{{ titleReactive }}</div>
    </div>
  </div>
</template>

<script setup>
import { reactive, ref } from 'vue';
const { data: mountain } = await useFetch('/api/mountain');
console.log('mountain.value:', JSON.stringify(mountain.value));
console.log('mountain.value.title:', mountain.value.title);
const titleConst = mountain.value.title;
console.log('titleConst is:', titleConst);
console.log('typeof titleConst is:', typeof titleConst);
const titleReactive = ref(titleConst);
mountain.value.title = 'Mount changed title';
</script>
```
```javascript
// /server/api/mountain.js
export default defineEventHandler(() => {
    return {
        title: 'Mount Everest',
    }
})
```
![image](https://user-images.githubusercontent.com/48041365/183861605-3323b81c-78e2-4fbd-b8ff-dcbf2e0272eb.png)

**Comment by poemtalent** [comment]
The point is that constTitle is different in the webStorm terminal than in the Google console.I'm sorry to disturb you. Is it convenient for you to have a look

**Comment by danielroe** [comment]
You have changed the value on _server_, which means that it then gets put into the payload and on client `useFetch` returns the _changed_ value when it is initially run.
