### ISSUE TITLE
Warn needs to be much more specific when there's no root element in <template>

### ISSUE THREAD

**Issue by somedaycode** [nuxt/framework#6476]
### Describe the feature

these are vue components in my pages directory
```html
// pages/index.vue
<template>
  <h1>Home</h1>
  <NuxtLink to="some-route/1">page 1</NuxtLink>
</template>
```

```html
// pages/some-route/[id].vue
<script lang="ts" setup>
import { useRoute } from 'vue-router';

const route = useRoute();
</script>

<template>
  <p>{{ route.params.id }}</p>
</template>
```

I was trying to follow tutorial Nuxt3 and I struggled with this kind of warning

what i struggled with was **the words which are 'Transition' and 'animated**'.

**I just wanted `route.params.id` to be displayed**

```
runtime-core.esm-bundler.js:38 [Vue warn]: Component inside <Transition> renders non-element root node that cannot be animated. 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=1 > 
  at <NuxtRoot>
```

For example,
when i use jsx in React, it give me this warning 
![image](https://user-images.githubusercontent.com/71962505/183857891-9df6319a-4a77-4b64-862a-53f28ff80864.png)

I think It is very clear for what i should fix.

Even though, I finally got answer after exploring the Internet,
the warning should be modified as to be more specific 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/4598. See the linked PR as well.
