### ISSUE TITLE
Server only components

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#648]
Related: #646, #10
Pending for: #666

- `ServerOnly` component to avoid hydration on client-side
- Support `Foo.server.vue` to automatically remove from client bundle

Discussion: For making this work, we need to ensure the page is loaded from the server-side which is not always the case when doing client-side navigations and for supporting code-removal, we cannot have client-side fallback because probably people start _assuming_ this code is depending on server-only logic like access to a secret.

**Comment by adityar15** [comment]
To clarify, does it mean that any component with .server.vue extension is completely server-side rendered and it is safe to pass on secrets like DB creds? Similar to React server component in Next 13?

**Comment by pi0** [comment]
@adityar15 Yes. The logic would be only included in server-bundle and not the client side. You can btw always use runtime config for secrets like DB credentials. And for time being, guarding part of logic with `if (process.server) {}` guards it to omit from client bundle. Server-only components makes it easier to build such components that are only included in server bundle.

**Comment by adityar15** [comment]
Thanks @pi0 for the clarification.
