### ISSUE TITLE
Server crash in production if use chart.js package

### ISSUE THREAD

**Issue by cawa-93** [nuxt/framework#6489]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Open https://stackblitz.com/edit/github-qegxpj-9nkyob?file=components%2FDoughnutChart.ts,app.vue
2. In dev mode you should see red-green doughnut chart. 
3. But if you run it in prod by `npm run build && npm start` then server will crash. 

### Describe the bug

Server crash in production mode if I use `vue-chartjs` with `chart.js`

**Comment by huang-julien** [comment]
Hi you have to transpile chart.js
````ts
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
  build: {
    transpile: ['chart.js'],
  },
});

````
