### ISSUE TITLE
Wrong version used, useFetch not working properly

### ISSUE THREAD

**Issue by patryk406** [nuxt/framework#6500]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/patryk406/nuxt-fetch-version

### Describe the bug

after removing node-modules and reinstalling one of the packages forces the use of rc.6, despite being specified in package.json eg rc.4. After using the yarn dev command in the terminal, the message Nuxt CLI v3.0.0-rc.6 is displayed.

use fetch stops working properly after such a procedure, it is called only once, if additional options are passed, it also does not detect them.

there is also a problem with using the component without import, eg the component is in the folder "button", the component is named "NewsButton" so using this component it could be saved as 'ButtonNewsButton' in rc. 6 is reported as a bug (unknown html tag). In the lower versions, I had no problem with that. Also, this component cannot be navigated to, the error is only reported in the IDE, the component displays correctly in the view. I work on the webstorm

**Comment by danielroe** [comment]
You would need to disable `initialCache`, or it will reuse the previous fetch result.

Here's a sandbox with the latest version which seems not to have the component issue you report: https://stackblitz.com/edit/github-mbrwf5.
