### ISSUE TITLE
missing `nuxt/dist/app/nuxt.d.ts` file in 3.0.0-rc.7

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#6516]
https://unpkg.com/browse/nuxt%403.0.0-rc.7/dist/app/

This means that no `NuxtApp` types or augments will work. Also broken will be `useRuntimeConfig()` and any types that are based on `NuxtApp` or inferred from `useNuxtApp()`.

---

Update: We are investigating this issue. Please use [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel) in the meantime

**Comment by pi0** [comment]
Seems a bug with npm `8.10.0` (npm pack works) ~> `8.11.0` (npm pack ignored file!)

**Comment by pi0** [comment]
Related changelogs:
- https://github.com/npm/cli/releases/tag/v8.11.0
- https://github.com/npm/cli/blob/latest/workspaces/libnpmpack/CHANGELOG.md

**Comment by pi0** [comment]
Found...It... npm>libnpmpack>npm-packlist>https://github.com/npm/npm-packlist/commit/da1ba4a3051ea822d9625347e00c186677247a45. It uses workspace `.gitignore` and we have [`.nuxt.d.ts`](https://github.com/nuxt/framework/blob/0cd4349b0d859240940c5848a41aa28e97542839/.gitignore#L26) in it.

![](https://c.tenor.com/0GKuTe1xfUkAAAAC/math-problems-thinking.gif)
