### ISSUE TITLE
NuxtLink retains scroll position

### ISSUE THREAD

**Issue by chrisnoden** [nuxt/framework#6524]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.7`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `build`, `buildModules`, `css`, `googleFonts`, `modules`, `nitro`, `runtimeConfig`
- Runtime Modules:  `@storyblok/nuxt@4.1.0`
- Build Modules:    `@nuxtjs/tailwindcss@5.3.1`, `@nuxtjs/google-fonts@1.3.0`

### Reproduction

`<NuxtLink :to="/page2">Link</NuxtLink>`

### Describe the bug

If you have reasonably long pages and common links near the bottom, clicking a link loads the target page content, but the scroll position no longer goes to the top of the new page.

### Additional context

Reverting to `rc.6` reverts the behaviour to the expected "jump to top of new page".

**Comment by BenjaminOddou** [comment]
Did you check the [app/router.option](https://v3.nuxtjs.org/guide/directory-structure/pages/#using-approuteroptions) documentation ? You can change the [scrollBehavior](https://router.vuejs.org/api/interfaces/routeroptions.html#scrollbehavior) by creating a config file `app/router.options.ts` :

```ts
import type { RouterConfig } from '@nuxt/schema'

// https://router.vuejs.org/api/#routeroptions
export default <RouterConfig>{
 const router = createRouter({
  scrollBehavior(to, from, savedPosition) {
    // always scroll to top
    return { top: 0 }
  },
 })
}
```

Alternatively why not trying to create a plugin like a `plugins/router.ts` file :

```ts
import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.$router.options.scrollBehavior = (to, from, savedPosition) => {
    // always scroll to top
    return { top: 0 }
  }
})
```

**Comment by chrisnoden** [comment]
Thanks @BenjaminOddou I will give it a try.

However, the normal (globally accepted) response in a browser when clicking a link without a `#` reference, would be to show the top of the new page. I would therefore consider this to be the default requirement and as such consider `rc.7` to have a bug. Downgrading only nuxt to rc.6 and the bug goes away.

I should not have to configure anything to achieve the normally expected behaviour when navigating to a new resource.

**Comment by 516310460** [comment]
> ```ts
> scrollBehavior
> ```

Can I create a link: https://stackblitz.com

I think scrollbrowser should default to "0,0"`

**Comment by danielroe** [comment]
Would you provide a reproduction? :pray

**Comment by jshimkoski** [comment]
Here is a solution that checks for saved position and hashes, defaulting to scrolling to the top of the page.

```javascript
import type { RouterConfig } from '@nuxt/schema'

// https://router.vuejs.org/api/#routeroptions
export default <RouterConfig> {
  scrollBehavior(to, _from, savedPosition) {
    return new Promise((resolve, _reject) => {
      setTimeout(() => {
        if (savedPosition) {
          resolve(savedPosition)
        } else {
          if (to.hash) {
            resolve({
              el: to.hash,
              top: 80
            })
          } else {
            resolve({ top: 0 })
          }
        }
      }, 100)
    })
  }
}
```

You might not need the `setTimeout` anymore, but I haven't tested thoroughly without it.

**Comment by chrisnoden** [comment]
Thanks @jshimkoski - a useful bit of code.

However, as already mentioned, we shouldn't have to write a hack for this. The default functionality when clicking a link to a new resource is to show the resource from the top. This is a bug in Nuxt rc 6.

**Comment by chrisnoden** [comment]
Fixed in rc7

**Comment by manniL** [comment]
> Not fixed!
> 
> Still seeing this unexpected problem in rc8

Please attach a minimal reproduction (e.g. via CodeSandbox or StackBlitz) so it is easier to tackle the issue ☺️

**Comment by chrisnoden** [comment]
Here's a minimal project to demonstrate the issue @manniL 

https://github.com/chrisnoden/nuxt3-bug

Here is a video of what happens:

https://user-images.githubusercontent.com/2600554/184929397-97e614d2-73c2-4b77-a946-fd0af52bc975.mov

**Comment by chrisnoden** [comment]
> Would you provide a reproduction? 🙏

Reproduced in a minimal project above @danielroe

**Comment by anjali89r** [comment]
@danielroe is this address in RC-9 , RC-8 had the issue.

**Comment by silvio-e** [comment]
It still happens for me in RC-9.

And in combination with #5152 it's quite a faulty navigation experience atm..

**Comment by cfab** [comment]
Same here with RC-11 for information

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/2817.

**Comment by Nvironmental** [comment]
Can confirm this issue still persist as of RC-12

**Comment by danielroe** [comment]
It is resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

**Comment by richgcook** [comment]
> It is resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

Can you confirm what exactly the resolution is? What's the default? What happens?

**Comment by danielroe** [comment]
https://github.com/nuxt/framework/pull/3851

**Comment by chrisnoden** [comment]
I've updated to rc.13 and this bug is not resolved for me.

**Comment by danielroe** [comment]
@chrisnoden Please do raise a new issue with a reproduction. 🙏

**Comment by chrisnoden** [comment]
> @chrisnoden Please do raise a new issue with a reproduction. 🙏

done as https://github.com/nuxt/framework/issues/8696 🤞
