### ISSUE TITLE
Multiple useAsyncData invocations with the same key don't resolve during SSR

### ISSUE THREAD

**Issue by fabis94** [nuxt/framework#6531]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/fabis94/nuxt-useasyncdata-cache-issue

see readme for more info, but basically just run the app and you'll see the issue

### Describe the bug

**What I expect to happen:** If I use the same key for multiple invocations of useAsyncData, then during SSR the promise should only be invoked once, and once its finished the resolved data should be put into the 'data' Ref of all invocations.

**What is happening:** Only the first invocation receives the resolved data, subsequent invocations will await the same promise, but once it resolves they wont update their own 'data' Ref with the resolved data

### Additional context

Judging from the source code it seems that once the 1st invocations promise resolves, it only fills out the data object of that first invocation: https://github.com/nuxt/framework/blob/7a846a829209828c9c13508856e78f686293d1bc/packages/nuxt/src/app/composables/asyncData.ts#L149

the 2nd invocation is awaiting the same promise, but once it resolves, it just returns its own asyncData, without actually putting the results of the promise into it before hand the same way it's done for the original invocation (see previous link): https://github.com/nuxt/framework/blob/7a846a829209828c9c13508856e78f686293d1bc/packages/nuxt/src/app/composables/asyncData.ts#L204

**Comment by danielroe** [comment]
This will probably be resolved in https://github.com/nuxt/framework/pull/5738

**Comment by fabis94** [comment]
@danielroe is there any ETA for when it could be merged?

**Comment by danielroe** [comment]
This was resolved in https://github.com/nuxt/framework/pull/7055 - you can try it out on the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/).

https://stackblitz.com/edit/github-rtvk2f?file=composables%2FuseAsyncTest.ts
