### ISSUE TITLE
^3.0.0-rc.6 ----- useAsyncData or useFetch . 

### ISSUE THREAD

**Issue by root-lxq** [nuxt/framework#6540]
### Environment

<template>
  <div class="">
    <h1>获取数据</h1>
    <div>
      <div v-for="item of lists" :key="item.id">{{ item.title }}</div>
      <hr />
      <div>{{ lists }}</div>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";
const url = `xxx`;

const { data } = await useFetch(url);
console.log(data);
const lists = ref(data);
</script>

<style scoped></style>

### Reproduction

<template>
  <div class="">
    <h1>获取数据</h1>
    <div>
      <div v-for="item of lists" :key="item.id">{{ item.title }}</div>
      <hr />
      <div>{{ lists }}</div>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";
const url = `http://121.36.81.61:8000/getTenArticleList`;

const { data } = await useFetch(url);
console.log(data);
const lists = ref(data);
</script>

<style scoped></style>

### Describe the bug

When we first went to a page that used both apis to get data, it was fine. However, when the refresh occurs, the error 500 useFetch or useAsyncData is not defined is displayed

**Comment by 516310460** [comment]
Would you provide a reproduction? 🙏

**Comment by danielroe** [comment]
There's not enough info to investigate, but if you provide a reproduction, I'll happily reopen 🙏
