### ISSUE TITLE
rc.7 fails to build with @vue-leaflet/vue-leaflet 0.6.1 installed

### ISSUE THREAD

**Issue by nevil2** [nuxt/framework#6547]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.1.0`
- Nuxt Version:     `3.0.0-rc.7`
- Package Manager:  `npm@8.12.2`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `app`, `buildModules`, `components`, `nitro`, `runtimeConfig`, `serverHandlers`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.3.1`

### Reproduction

package.josn

{
  "private": true,
  "scripts": {
    "dev": "nuxi dev --port 8000",
    "build": "nuxi build ",
    "start": "cross-env PORT=8000 node .output/server/index.mjs"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config-typescript": "^10.0.0",
    "@types/bcrypt": "^5.0.0",
    "@types/cookie-parser": "^1.4.3",
    "@types/express": "^4.17.13",
    "@types/jsonwebtoken": "^8.5.8",
    "@types/multer": "^1.4.7",
    "@types/multer-s3": "^3.0.0",
    "@types/node": "^18.6.1",
    "@types/node-fetch": "^2.6.1",
    "@types/nodemailer": "^6.4.4",
    "@types/pg": "^8.6.5",
    "@types/request-ip": "0.0.37",
    "@types/sqlite3": "^3.1.8",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "^5.31.0",
    "@typescript-eslint/parser": "^5.31.0",
    "eslint": "^8.15.0",
    "eslint-plugin-vue": "^9.3.0",
    "nuxt": "^3.0.0-rc.6",
    "typescript": "^4.6.4",
    "vite-plugin-eslint": "^1.6.0"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.110.0",
    "@aws-sdk/lib-storage": "^3.118.0",
    "@aws-sdk/s3-presigned-post": "^3.110.0",
    "@aws-sdk/s3-request-presigner": "^3.113.0",
    "@pinia/nuxt": "^0.3.1",
    "@vue-leaflet/vue-leaflet": "^0.6.1",
    "bcrypt": "^5.0.1",
    "cookie-parser": "^1.4.6",
    "cross-env": "^7.0.3",
    "docx": "^7.3.0",
    "dotenv": "^16.0.0",
    "exifr": "^7.1.3",
    "express": "^4.18.1",
    "helmet": "^5.1.1",
    "jsdom": "^20.0.0",
    "jsonwebtoken": "^8.5.1",
    "leaflet": "^1.8.0",
    "multer": "^1.4.5-lts.1",
    "multer-s3": "^3.0.1",
    "node-fetch": "^3.2.4",
    "node-schedule": "^2.1.0",
    "nodemailer": "^6.7.5",
    "pg": "^8.7.3",
    "request-ip": "^3.3.0",
    "sharp": "^0.30.7",
    "sqlite3": "^5.0.7",
    "uuid": "^8.3.2",
    "vue-tippy": "^6.0.0-alpha.62"
  }
}

### Describe the bug

All builds OK with rc.6.  However, with rc.7, the following error occurs if @vue-leaflet/vue-leaflet 0.6.1 is installed.

ERROR  [commonjs--resolver] Failed to load plugin 'prettier' declared in 'node_modules/@vue-leaflet/vue-leaflet/package.json': Cannot find module 'eslint-plugin-prettier'

Installing 'eslint-plugin-prettier' does not help, as it then wants the another package, and so on.

### Logs

```shell
Require stack:
#14 14.17   - node_modules/@vue-leaflet/vue-leaflet/__placeholder__.js
#14 14.17   Referenced from: node_modules/@vue-leaflet/vue-leaflet/package.json
#14 14.17   at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
#14 14.17   at Function.resolve (node:internal/modules/cjs/helpers:108:19)
#14 14.17   at Object.resolve (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2325:46)
#14 14.17   at ConfigArrayFactory._loadPlugin (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3376:33)
#14 14.17   at ConfigArrayFactory._loadExtendedPluginConfig (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3196:29)
#14 14.17   at ConfigArrayFactory._loadExtends (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3117:29)
#14 14.17   at ConfigArrayFactory._normalizeObjectConfigDataBody (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3058:25)
#14 14.17   at _normalizeObjectConfigDataBody.next (<anonymous>)
#14 14.17   at ConfigArrayFactory._normalizeObjectConfigData (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3003:20)
#14 14.17   at _normalizeObjectConfigData.next (<anonymous>)
```

**Comment by danielroe** [comment]
This is likely an upstream issue rather than with nuxt. I am surprised that vue-leaflet seems to be loading `prettier` into your vue app - likely something to be avoided!

Would you provide a [minimal reproduction](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz)? :pray:

**Comment by nevil2** [comment]
Thanks for quick response.  I’m stuck because my code will not build with rc.7 (it does with rc.6) and despite specifying rc.6 in package.json and package-lock.json, docker is installing rc.7 and won’t build.

**Comment by danielroe** [comment]
Please check that leaflet or related dependencies didn't also upgrade when you updated Nuxt.

If you need to pin to a previous RC, ou can specify package versions like this: https://github.com/nuxt/framework/issues/5621#issuecomment-1184341930.

**Comment by pi0** [comment]
Hi @nevil2 I've made a sandbox with working vue-leaflet against rc7: https://stackblitz.com/edit/github-b8ms66?file=app.vue,components%2FMyMap.client.vue

Note: In order to ensure no strange server issues happen, please create a component with `.client` suffix such as `MyMap.client` this way it will not be included in server bundle.

**Comment by nevil2** [comment]
Thanks for your help and explaining how to specify previous version.  Forcing build with rc.6 is not helping.

 

The sandbox example shows @vue-leaflet/vue-leaflet 0.6.1 is building with rc.7.

 

Whilst in my setup @vue-leaflet/vue-leaflet 0.6.1 has not changed, I think it must be update this morning to another library which is causing the issue.

 

Suggest you close the issue.

**Comment by pi0** [comment]
Please ping us to reopen if you still had issues with latest.

**Comment by nevil2** [comment]
It is an issue with vite-plugin-eslint 1.8.0.  This was upgraded from 1.7.0 yesterday.  A similar issue has already been raised.  I added my example as comment.

 

Thanks for help.  Would not have found source of problem without you.

**Comment by nevil2** [comment]
Thanks for your help and explaining how to specify previous version.  Forcing build with rc.6 is not helping.

 

The sandbox example shows @vue-leaflet/vue-leaflet 0.6.1 is building with rc.7.

 

Whilst in my setup @vue-leaflet/vue-leaflet 0.6.1 has not changed, I think it must be update this morning to another library which is causing the issue.

 

Suggest you close the issue.
