### ISSUE TITLE
use yarn add:nuxt3.0.0-rc.6  use nuxt dev or nuxt build log print Nuxt CLI v3.0.0-rc.7 

### ISSUE THREAD

**Issue by liuzycc** [nuxt/framework#6548]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.4`
- Builder:          `webpack`
- User Config:      `builder`, `app`, `css`, `build`, `vite`, `runtimeConfig`, `hooks`, `webpack`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

nuxt3.0.0-rc.6  use nuxt dev or nuxt build log print Nuxt CLI v3.0.0-rc.7 

### Describe the bug

nuxt3.0.0-rc.6  use nuxt dev or nuxt build log print Nuxt CLI v3.0.0-rc.7 
result:
builder:webpack
![image](https://user-images.githubusercontent.com/36906904/184330883-f40a1cbb-e29f-4592-bbdb-321ed155f6fa.png)
expect

![image](https://user-images.githubusercontent.com/36906904/184331020-77002b41-6ba7-4ead-8d8e-7c77b9244759.png)

**Comment by geyermichael** [comment]
I encountered the same issue.

**Comment by danielroe** [comment]
Would you clarify - what is the problem you are encountering?

**Comment by pi0** [comment]
If for any reason you need to use a specific RC (<7) version, please refer to this instruction: https://github.com/nuxt/framework/discussions/6554

**Comment by pi0** [comment]
Closing issue as apprears the title is answered. Please ping to reopen if your question was different @liuzycc 🙏🏼
