### ISSUE TITLE
[unhandled] [500] Named export 'addListener' not found: Error after upgrading to rc7 (still present in rc8)

### ISSUE THREAD

**Issue by ahoiroman** [nuxt/framework#6564]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Checkout https://github.com/ahoiroman/nuxt-app
2. Install dependencies using `npm install`
3. Run `npm run build`
4. Run `node .output/server/index.mjs`
5. Open http://0.0.0.0:3000 using your browser
6. Check out node-output

### Describe the bug

Once I add vue-echarts to a Nuxt-version > rc6, the following error will be thrown and the page will not load:

```
[nuxt] [request error] [unhandled] [500] Named export 'addListener' not found. The requested module 'resize-detector' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'resize-detector';
const { addListener, removeListener } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:541:24)  
  at async ./.output/server/chunks/handlers/renderer.mjs:11089:24  
  at async ./.output/server/chunks/handlers/renderer.mjs:11143:64  
  at async ./.output/server/chunks/handlers/renderer.mjs:14:22  
  at async ./.output/server/node_modules/h3/dist/index.mjs:492:19  
  at async Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:438:7)
```

### Additional context

There seems to be somebody else having similar issues related to another package at https://github.com/nuxt/framework/issues/6534 .

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Named export 'addListener' not found. The requested module 'resize-detector' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'resize-detector';
const { addListener, removeListener } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:541:24)  
  at async ./.output/server/chunks/handlers/renderer.mjs:11089:24  
  at async ./.output/server/chunks/handlers/renderer.mjs:11143:64  
  at async ./.output/server/chunks/handlers/renderer.mjs:14:22  
  at async ./.output/server/node_modules/h3/dist/index.mjs:492:19  
  at async Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:438:7)
```
```

**Comment by danielroe** [comment]
Have you tried doing what the message suggests? You can also likely add it to `build.transpile`.

See https://v3.nuxtjs.org/concepts/esm.

**Comment by ahoiroman** [comment]
Hi Daniel,

I sure hope I did it the intended way: https://github.com/ahoiroman/nuxt-app/blob/main/nuxt.config.ts

```
build: {
        transpile: [/echarts/, 'vue-echarts'],
    },
```

**Comment by danielroe** [comment]
The issue here is like a change in behaviour between Vite 2 -> Vite 3 upgrade.

We have a useful Nuxt 3 feature for client-only components that can help in the example of your repository: https://stackblitz.com/edit/github-vst7tq?file=components%2Fgraph.client.vue,package.json.

In your original case though, just adding `resize-detector` to your transpile solves the issue (and installing `echarts` which seems not to be in the repro).

**Comment by yeonjulee1005** [comment]
@danielroe your solution is so useful 👍
