### ISSUE TITLE
Accessing rendered HTML in Nuxt hook in order to process and potentially modify final HTML output

### ISSUE THREAD

**Issue by tylerforesthauser** [nuxt/framework#6566]
### Describe the feature

There was a brief moment during RC7 where the `app:rendered` hook was called with the constructed HTML output at which point we were able to access the output and modify it if necessary. In Nuxt 2, we made use of the `vue-renderer:ssr:templateParams` hook for this purpose. Our specific use-case is to process the final HTML with [Twind](https://twind.style/) to transform our CSS classes and to inject a stylesheet into the head. We're not interested in modifying the ssrContext at this point. 

If there is a way to bring back this functionality, it would be greatly appreciated.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Have you considered using a nitro hook?

**Comment by pi0** [comment]
Hi dear @tylerforesthauser. Hooks were not removed but renamed in the latest version and accessible from nitro hooks. In Nuxt 2, we had them in build namespace, in Nuxt 3, they are available from runtime. 

I've created an example sandbox here meanwhile the hooks are not documented: https://github.com/nuxt/framework/issues/6571

**Comment by tylerforesthauser** [comment]
> Have you considered using a nitro hook?

I will admit that I'm not sure how Nitro hooks work. I currently have a Nuxt plugin set up in which I'm providing a global class instance to use throughout my app and it's this class I need to process the constructed HTML with. Is that possible with a Nitro hook?

**Comment by pi0** [comment]
(check ny comment above :) Linked to an issue with example)

**Comment by tylerforesthauser** [comment]
@pi0 Do we have access to nuxtApp inside of Nitro plugins? Or would I have to include my class instance in ssrContext or something?

**Comment by pi0** [comment]
Inside the `render:html` hook, you can inject classes via `html.htmlAttrs[]` or `html.bodyAttrs[]` to the final rendered response like Nuxt 2. The context is different tough from the one used _during_ rendering (it is `nitroApp`). 

Can you please point out to the API you are trying use from twind? I can probably help better known usage.

**Comment by pi0** [comment]
Here you are an example with `twind@next` and Nuxt 3 (SSR): https://stackblitz.com/edit/github-86cqr7-b2d17k?file=package.json,app.vue,server%2Fplugins%2Ftwind.ts


```js
import { extract, install } from 'twind';
import presetTailwind from '@twind/preset-tailwind';

// Based on https://github.com/tw-in-js/twind/blob/next/packages/gatsby-plugin/src/gatsby-ssr.ts

install(
  {
    presets: [presetTailwind()],
  },
  process.env.NODE_ENV == 'production'
);

export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('render:html', (html, { event }) => {
    html.body = html.body.map((chunk) => {
      const r = extract(chunk);
      if (r.css) {
        html.head.push(`<style>${r.css}</style>`);
      }
      return r.html;
    });
  });
});
```

**Comment by pi0** [comment]
Update: 845110

**Comment by tylerforesthauser** [comment]
OK, first off, you are amazing @pi0 ! I find it hilarious that I wake up this morning to see that you've come so far as to create a Nuxt module for Twind integration 😄 

I am excited to try it out! In the meantime, I just wanted to say thank you for looking into this and let you know a brief rundown of how I'm using Twind. I'm using it in [Library Mode](https://twind.style/docs/reference#library-mode) where I've created a plugin to build my global utility that I use to apply styles to all of my components. 

The plugin code looks a little something like this:

```js
import { twind, injectGlobal, tx, getSheet } from 'twind'
import { config } from '~/twind.config'
import { globalStyles } from '~/twind.global'

export default defineNuxtPlugin((nuxtApp) => {
  const instance = twind(config, getSheet())

  const tw = tx.bind(instance)

  const injectGlobalStyles = injectGlobal.bind(instance)
  injectGlobalStyles(globalStyles)

  nuxtApp.provide('twind', { tw, instance })
})
```

This does a few things for me: 

1. Creates a Twind instance  that I can use to access my config, theme, etc on demand.
2. Creates a [tx utility](https://twind.style/docs/reference#utilities) which accepts virtually any assortment of Twind classes/functions, creates the appropriate class and injects the styles into the instance stylesheet. 
3. Adds some global styles for things like custom fonts, etc.
4. Then, of course, provides this information to my app context.

My intention with the `app:rendered` hook was to provide this instance to the [extract](https://twind.style/docs/reference#mostly-server-side) function (that you've used for your module) in order to process my app's HTML output. 

The reason why I believed using the same instance is important is because Twind's [virtual sheet](https://twind.style/docs/reference#sheets) (used server-side) includes "resume data" that the Twind runtime can use to avoid duplicating the work client-side. What I'm not sure of is whether or not this data is unique to the instance or is generated in a way that simply creating another instance for the Nitro plugin with the same config would be enough...

So when I get a chance, I'll fire up a sandbox and test some stuff out with your module. I honestly believe you've given me all the tools I'd need to make this work. Thank you so much! 🙏 

I'll report back with my findings. 👍

**Comment by pi0** [comment]
Glad you liked the module 😊 And sure your usecase makes sense and we can make it working using event context. Do you mind to open an issue in my moduls? i can give more details if you like to help on implementing this mode 👍
