### ISSUE TITLE
DOM is sometimes destroyed when navigating between routes

### ISSUE THREAD

**Issue by fabis94** [nuxt/framework#6568]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@3.2.2`
- Builder:          `vite`
- User Config:      `head`, `typescript`, `modules`, `runtimeConfig`, `hooks`, `build`, `alias`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.1`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/fabis94/djw3c-frontend-nuxt/commit/3c7f0f7a54be28da7856ac4091ff3e826029865c

### Describe the bug

1. yarn dev
2. go to http://localhost:4000/about
3. then switch to /releases through the navbar 
4. the body of the page is gone, even when you continue switching to other routes, the DOM Is destroyed and you get errors about this in the console
4b. if nothing happened, just try walking around the website through the nav bar a few times and you'll def see the issue

**Comment by danielroe** [comment]
You have multiple root nodes in your news pages.

**Comment by fabis94** [comment]
@danielroe i pushed a fix in the latest master, the underlying issue still is there tho https://github.com/fabis94/djw3c-frontend-nuxt/commit/ea12058bc530db8984f0cf75a0e15125be526414

**Comment by ojvribeiro** [comment]
> You have multiple root nodes in your news pages.

Wrapping the contents in a `div` did solve the issue for me. Wasn't multiple root nodes allowed before though?

- Operating System: `Windows 10 Pro 21H2`
- Node Version: `v16.16.0`
- Nuxt Version: `3.0.0-rc.8`
- Package Manager: `npm@6.14.9`
- Builder: `Vite`

**Comment by danielroe** [comment]
No, multiple root nodes are not allowed in pages or layouts unless you disable transitions.

See https://v3.nuxtjs.org/guide/directory-structure/pages.

**Comment by ojvribeiro** [comment]
Before rc8, it was just returning a warning on the console, not breaking everything. Also, shouldn't transitions be disabled by default? It is weird to wrap everything inside a div, a React-like fragment would be nice to have, but I think it's more of a Vue thing than Nuxt's.

I'm loving Nuxt and this is just my two cents. Thank you guys for the hard work on making the best framework. ❤️

**Comment by danielroe** [comment]
I don't believe there was any change in RC that should affect this. We have a pending PR to improve DX on this: https://github.com/nuxt/framework/pull/5469.

We also have a PR to allow disabling transitions by default in Nuxt: https://github.com/nuxt/framework/pull/5859

**Comment by fabis94** [comment]
@danielroe i'm confused about the reason for closing this issue - the DOM being destroyed seems to have nothing to do with multiple root nodes, I removed the ones you pointed out (and don't see any others) and the issue still persists, as mentioned here: https://github.com/nuxt/framework/issues/6568#issuecomment-1213356885

**Comment by danielroe** [comment]
@fabis94 Would you provide a [minimal reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction) please in that case? 🙏 I can't run yours; contentful returns unauthorized.

**Comment by fabis94** [comment]
@danielroe sorry, I didn't provide the `.env` file values, here they are:

```
CONTENTFUL_SPACE_ID=q8ohhsmisuat
CONTENTFUL_ACCESS_TOKEN=T6nKoKloFnk6diAxv8sT49QY_0XgacLE4JWrdI1ptZs
BASE_URL=http://localhost:4000
BG_VIDEO_ID=SVJKbFRoW_M
```

That's the only thing you need to prepare to be able to run the app (which can be ran as any other Nuxt 3 app).

**Comment by danielroe** [comment]
The issue is that one of your pages has `<AboutMe :full="true" />` as the root element. But within this component, there are multiple root nodes:

```vue
<template>
  <!-- AboutMe -->
  <CommonCard v-if="aboutMe" as="section">
</template>
```

(I would also potentially be worried about the `v-if` but in this case that doesn't seem to be the issue. Removing `<!-- AboutMe -->` fixes the issue.)

**Comment by danielroe** [comment]
Gotchu! https://github.com/nuxt/framework/pull/5469
