### ISSUE TITLE
Build using baseURL stopped working on production

### ISSUE THREAD

**Issue by lucassimines** [nuxt/framework#6572]
### Environment

My application stopped working after upgrading to rc.8, I use a baseURL:

```
app: {
    baseURL: '/admin'
 },
```

Running a dev server it works, but when running `npm run start` I get the following errors.

![Screen Shot 2022-08-12 at 15 03 37](https://user-images.githubusercontent.com/12851638/184417329-f6a21b15-d12c-41eb-b785-5b7d895805e1.png)

### Reproduction

.

### Describe the bug

Mjs files are not found

**Comment by pi0** [comment]
Would you please provide a reproduction? 🙏🏼 

/cc @danielroe

**Comment by LeoTuet** [comment]
Facing the same issue.
While setting up the reproduction I noticed that this bug only occurs when creating an additional page.
Otherwise it only occurs on first page load while working when refreshing the page.

Reproduction: https://codesandbox.io/s/twilight-architecture-9f7olx?file=/nuxt.config.ts

**Comment by lucassimines** [comment]
> Facing the same issue. While setting up the reproduction I noticed that this bug only occurs when creating an additional page. Otherwise it only occurs on first page load while working when refreshing the page.
> 
> Reproduction: https://codesandbox.io/s/twilight-architecture-9f7olx?file=/nuxt.config.ts

Nice! Thanks for the reproduction. I'm still using the `rc.6` because of this issue.

**Comment by danielroe** [comment]
Would you try on the edge channel? https://v3.nuxtjs.org/guide/going-further/edge-channel/

I believe this may have been resolved in https://github.com/nuxt/framework/pull/6637.

**Comment by lucassimines** [comment]
> Would you try on the edge channel? https://v3.nuxtjs.org/guide/going-further/edge-channel/
> 
> I believe this may have been resolved in #6637.

Changed to the edge channel and I got this `error` while running `npm run build`

![Screen Shot 2022-08-18 at 17 24 31](https://user-images.githubusercontent.com/12851638/185488213-61987172-ad0f-407e-a013-b8a1f8cb3891.png)

**Comment by danielroe** [comment]
Yes, I can confirm that the reproduction above doesn't show the same issue. @lucassimines please do create a new issue with a reproduction for this rather odd issue. (Might be worth running `nuxi cleanup` first). 🙏

**Comment by lucassimines** [comment]
> Yes, I can confirm that the reproduction above doesn't show the same issue on the edge channel. @lucassimines please do create a new issue with a reproduction for this rather odd issue. (Might be worth running `nuxi cleanup` first). 🙏

After many attempts, I found what is causing the odd issue. I will create another issue with the reproduction.
