### ISSUE TITLE
runtimeConfig is broken for objects passed in env. vars when there is a hash in a value

### ISSUE THREAD

**Issue by arthur-bri** [nuxt/framework#6574]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `telemetry`, `typescript`, `vite`, `css`, `serverMiddleware`, `build`, `modules`, `buildModules`, `components`, `runtimeConfig`
- Runtime Modules:  `./modules/nuxt/i18n`, `@nuxt/image-edge@1.0.0-27657146.da85542`
- Build Modules:    `@vueuse/nuxt@8.9.4`, `@pinia/nuxt@0.3.1`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-85uwj1?file=app.vue,.env,nuxt.config.ts

Env. variables used for reproduction  
```sh
NUXT_PUBLIC_THEME={ "primary": "#FFF", "secondary": "blue" }
NUXT_PUBLIC_THEME_OK={ "primary": "white", "secondary": "blue" }
```

### Describe the bug

When using an object as runtime config environment variable, all values of this object looks to be discarded if a hash is set anywhere in a value.

### Additional context

In our project, we want to pass some JSON that handles the website theme (including colors) in the runtimeConfig. Hence the reproduction of this really strange bug!

**Comment by danielroe** [comment]
I believe you need to quote the value:

```bash
NUXT_PUBLIC_THEME='{ "primary": "#FFF", "secondary": "blue" }' NUXT_PUBLIC_THEME_OK='{ "primary": "white", "secondary": "blue" }' npm run dev
```

Seems to work fine. I don't think this is about Nuxt, just shell behaviour: https://stackblitz.com/edit/github-85uwj1-k16hxu?file=package.json.

**Comment by arthur-bri** [comment]
Oh yes it should be that, sorry for the issue! Thank's a lot @danielroe
