### ISSUE TITLE
Import from `#components` broken because of error in `components.d.ts`

### ISSUE THREAD

**Issue by johannschopplich** [nuxt/framework#6579]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `pnpm@7.9.0`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`, `typescript`
- Runtime Modules:  `@vueuse/nuxt@9.1.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

### Describe the bug

Nuxt (`mlly`?) adds a `,` to the end of `export const` statements.

Now, I can't `import { ... } from '#components'`.

### Additional context

Example: 

```ts
export const NuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@0.3.1/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.8/node_modules/nuxt/dist/app/components/layout")['default'],
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.8/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.0.0-rc.8/node_modules/nuxt/dist/app/components/client-only")['default'],
```

**Comment by zavvla** [comment]
Does it affect the "Failed to resolve component"?

I made a mistake: 
`[Vue warn]: Failed to resolve component: GlobalHeader
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
`

But if you forcibly specify the folder with the component, then everything is ok.
`export default defineNuxtConfig({
    components: {
        global: true,
        dirs: ["~/components"],
    },
`

Or did I miss something in the updates? thx

**Comment by danielroe** [comment]
Ah - that's unrelated! See https://github.com/nuxt/framework/issues/6569#issuecomment-1213354175.

**Comment by zavvla** [comment]
> Ah - that's unrelated! See [#6569 (comment)](https://github.com/nuxt/framework/issues/6569#issuecomment-1213354175).

thanks, missed a few releases
