### ISSUE TITLE
Usage of slots in client-only components throwing errors in production

### ISSUE THREAD

**Issue by ffxsam** [nuxt/framework#6581]
### Environment

Nuxt CLI v3.0.0-rc.8
RootDir: /Users/samh/wow
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/ffxsam/repro-nuxt3-broken-slots

1. `yarn build`
2. `yarn preview`

### Describe the bug

Using slots in client-only components throws an error in production only:

```
TypeError: Cannot read properties of undefined (reading 'test')
```

**Comment by huang-julien** [comment]
@ffxsam sorry i've made a mistake in a previous PR for the client-only component 🙏 .  A PR is pending now.
About your app.vue, is it intentionnal to wrap your Boom.client component with a client-only wrapper ?

**Comment by ffxsam** [comment]
@huang-julien Thanks! And yes, it's intentional in my application code.. kind of a weird use case.
