### ISSUE TITLE
After adding onMounted in App.vue, the href of modulepreload has no baseURL prefix

### ISSUE THREAD

**Issue by Tzdy** [nuxt/framework#6586]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `app`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-xje7sv?file=nuxt.config.ts

### Describe the bug

After adding onMounted in App.vue, the href of modulepreload has no baseURL prefix. Running a dev server it works, but when running npm run build I get the following errors.
```
npm run build
node .output/server/index.mjs
```
![屏幕快照 2022-08-13 上午10 58 23](https://user-images.githubusercontent.com/49274160/184466644-33a4a2e6-1d23-48eb-9c72-856230a48fd0.png)

**Comment by Tzdy** [comment]
I fell back to rc.6 and it works

**Comment by ErickLuis00** [comment]
I detected the same problem, but missing the "cdnURL" .

https://stackblitz.com/edit/github-xje7sv-n28wxr?file=package.json&terminal=build,cdn&terminal

Just run "node .output/server/index.mjs" in the second terminal after the first one starts listening.

You can clearly see that "modulepreload" does not use cdnURL.

similar issue
https://github.com/nuxt/framework/issues/3932
