### ISSUE TITLE
[rc.8] Error when building with some Eslint settings

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/framework#6588]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@3.2.2`
- Builder:          `vite`
- User Config:      `ssr`, `runtimeConfig`, `nitro`, `typescript`, `css`, `intlify`, `modules`, `alias`, `vite`
- Runtime Modules:  `unplugin-icons/nuxt`, `@vueuse/nuxt@8.9.4`, `@intlify/nuxt3@0.2.3`
- Build Modules:    `-`
------------------------------

### Reproduction

One easy way could be to add the following dependency to your package.json:

```json
{...
    "devDependencies": {
         "nuxt": "3.0.0-rc.8"
    },
    "dependencies": {
         "@aws-amplify/auth": "^4.6.1"
    }
...
}
```

### Describe the bug

When building or generating, the following error pops up:

```
Cannot read config file: /.../node_modules/amazon-cognito-identity-js/.eslintrc.yaml 
  Error: unidentified alias ".test.js" (10:19)
  
  7 | settings:
  8 |   import/resolver: webpack
  9 | overrides:
  10 |   files: *.test.js
  ------------------------^
  11 |   rules: jest/valid-expect
  12 | rules:
  at generateError (node_modules/js-yaml/lib/loader.js:183:10)

```

### Additional context

The error is not present in `rc.6`

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by ennioVisco** [comment]
> Would you provide a reproduction? 🙏

You mean by providing a sandbox link? The problem is that AFAIK sandboxes don't run the `build` command but only run it in dev mode (where the issue is not present).

Is there a way to force them to execute another command?

**Comment by danielroe** [comment]
In a stackblitz you can run any command in the terminal. You can also update the dev command in package.JSON.

Start with https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

**Comment by ennioVisco** [comment]
I think it was dependant to some Vite update. Anyway, it is solved in [`rc.9`](https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.9).
