### ISSUE TITLE
Can you spend more time on finishing framework, not on starting splash screen

### ISSUE THREAD

**Issue by aokihu** [nuxt/framework#6591]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.0.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `css`, `build`, `modules`, `i18n`
- Runtime Modules:  `@nuxt/content@2.0.1`, `8n`
- Build Modules:    `-`
------------------------------

### Reproduction

you can run on Safari by yourself!

### Describe the bug

Hey, Nuxt is a great framework, but I don't like the splash screen, because it is not work on Safari, it is useless!

**Comment by pi0** [comment]
You are welcome to contribute to [nuxt/ui](https://github.com/nuxt/ui) improving browser support and reporting issues.
