### ISSUE TITLE
Vite plugins (transforms) not run in SSR

### ISSUE THREAD

**Issue by Tahul** [nuxt/framework#6597]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.8-27673198.b4bea51`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cmbd9g

### Describe the bug

Seems like Vite transforms are not run in SSR in development mode, leading to a blink on these transforms while developing / booting the server.

### Additional context

Not sure about transforms outside of Vue SFCs, but this one specifically occurs in <style> templates of Vue components which might (maybe?) receive a different treatment?

**Comment by Atinux** [comment]
Related to https://github.com/nuxt-community/design-tokens-module/issues/8

**Comment by pi0** [comment]
Regex `/\?vue&type=style/` in `tranaformInclude` was not covering all cases. Some server transform ids look like this:

```
!! /Users/pooya/tmp/nuxt-starter-cmbd9g/app.vue?direct&vue&type=style&index=0&lang.css                                                      
!! /Users/pooya/tmp/nuxt-starter-cmbd9g/app.vue?direct&vue&type=style&index=1&scoped=938b83b0&lang.css
```

Simply changing to `/vue&type=style/` fixes issue but I would suggest using `ufo` parser.

**Comment by pi0** [comment]
For grater safetly you might also want to handle encoding. Here is better example for parsing: https://github.com/nuxt/framework/blob/1b2304b632ed8d44da17cc767d213e8dfc10ff7c/packages/nuxt/src/auto-imports/transform.ts#L29

Updated example https://stackblitz.com/edit/nuxt-starter-mbgzbh?file=module.ts

**Comment by antfu** [comment]
Not so sure if it's general enough to go in `unplugin`. But if you mean to solve this particular case, the Vite team discussed about this once if we should provide a utility to parse SFC queries in `@vitejs/plugin-vue` or an official vue tool. Since we don't actually yet have a spec of how Vue handles those queries, Vue 2 and 3, Vite and Webpack all use a slightly different approach to it.

**Comment by pi0** [comment]
Normalizing and parsing queies (id) in general, could be useful for both bundlers I believe. But indeed, how we interpret them (based on each loader query) is probably out of the scope.
