### ISSUE TITLE
HMR on looping component

### ISSUE THREAD

**Issue by aryraditya** [nuxt/framework#6599]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `pnpm@7.6.0`
- Builder:          `vite`
- User Config:      `modules`, `experimental`, `plugins`, `unocss`, `colorMode`
- Runtime Modules:  `@vueuse/nuxt@9.1.0`, `@unocss/nuxt@0.45.6`, `@pinia/nuxt@0.4.0`, `@nuxtjs/color-mode@3.1.4`
- Build Modules:    `-`

### Reproduction

Step to reproduce

1. go to https://stackblitz.com/edit/nuxt-starter-6n3h4t?file=app.vue,components%2FComp.vue
2. Update Comp.vue component, eg. update the text on component
3. on the browser, only the last component is updated

![ezgif-5-9bd11659ce](https://user-images.githubusercontent.com/8693368/184507273-a9c8665d-8bc1-48ee-9847-7d2a76910c3a.gif)

### Describe the bug

HMR for the looped components only updates the last component

**Comment by danielroe** [comment]
I've raised https://github.com/vitejs/vite/issues/9679 to track - this originates upstream.

**Comment by danielroe** [comment]
This should be resolved in the latest version of Vue.
