### ISSUE TITLE
Add response headers to data fetching return values

### ISSUE THREAD

**Issue by codeflorist** [nuxt/framework#6600]
### Describe the feature

Many APIs return valuable information inside the resonse headers (e.g. total row count).

It would be great, if the response headers could be made available within the return value of nuxt's data fetching composables.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
If you need access to headers you can get it with `$fetch.raw`:

```js
const res = await $fetch.raw('https://jsonplaceholder.typicode.com/todos/1');
console.log(res.headers)
```

In general, I don't think it would be a good idea to expose the return value from `useFetch` by default, as this would mean (for consistency) we would be taking the headers from server side and passing them to client, which could expose secrets.

But you can always use `useAsyncData` and `$fetch.raw` above to save the headers yourself:

```js
const { data, error } = await useAsyncData(async () => {
  const res = await $fetch.raw('https://jsonplaceholder.typicode.com/todos/1')
  return {
    data: res._data,
    count: res.headers.get('count')
  }
})
```

**Comment by codeflorist** [comment]
ah, this makes sense. many thanks for the explanation and the solution, daniel!
