### ISSUE TITLE
useFetch do not refetch data when use Dynamic Routes 

### ISSUE THREAD

**Issue by TangsWang** [nuxt/framework#6604]
### Environment

nuxt rc6

### Reproduction

none

### Describe the bug

/pages
  -- [jsn].vue
/server
 -- /api
     -- [jsn].get.ts

in [jsn].vue <script setup>...

const { data, error } = await useFetch(`/api/${route.params.jsn}`)

when  route from `/test_1` to `/test_2`,   data is not changed.

what should i do? or there's something wrong with that?

**Comment by mahdiboomeri** [comment]
dynamic route should be a function that returns a string
```typescript
const { data, pending } = await useFetch(
	() => `/api/data/${props.variable}`,
	{
		method: 'get',
	}
);
```

There is also an [example](https://v3.nuxtjs.org/examples/composables/use-fetch) in the docs

**Comment by TangsWang** [comment]
> dynamic route should be a function that returns a string
> 
> ```ts
> const { data, pending } = await useFetch(
> 	() => `/api/data/${props.variable}`,
> 	{
> 		method: 'get',
> 	}
> );
> ```
> 
> There is also an [example](https://v3.nuxtjs.org/examples/composables/use-fetch) in the docs

`const { data: journal_data } = await useFetch(() => `/api/journals/${useRoute().params.jsn}`, { method: 'Get' })`

thanks, but it doesn't work for me.

**Comment by mahdiboomeri** [comment]
> > dynamic route should be a function that returns a string
> > ```ts
> > const { data, pending } = await useFetch(
> > 	() => `/api/data/${props.variable}`,
> > 	{
> > 		method: 'get',
> > 	}
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There is also an [example](https://v3.nuxtjs.org/examples/composables/use-fetch) in the docs
> 
> ```ts
> const { data: journal_data } = await useFetch(() => `/api/journals/${useRoute().params.jsn}`, { method: 'Get' })
> ```
> 
> thanks, but it doesn't work for me.

Sorry for responding a bit late
i forgot to mention that you have to disable cache
try adding `initialCache: false` to the useFetch options

**Comment by TangsWang** [comment]
> > > dynamic route should be a function that returns a string
> > > ```ts
> > > const { data, pending } = await useFetch(
> > > 	() => `/api/data/${props.variable}`,
> > > 	{
> > > 		method: 'get',
> > > 	}
> > > );
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > There is also an [example](https://v3.nuxtjs.org/examples/composables/use-fetch) in the docs
> > 
> > 
> > ```ts
> > const { data: journal_data } = await useFetch(() => `/api/journals/${useRoute().params.jsn}`, { method: 'Get' })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > thanks, but it doesn't work for me.
> 
> Sorry for responding a bit late i forgot to mention that you have to disable cache try adding `initialCache: false` to the useFetch options

it works, so thank you very much.
