### ISSUE TITLE
error using <center> and content querying

### ISSUE THREAD

**Issue by kristus123** [nuxt/framework#6605]
### Environment / Reproduction

First, create a new project with content extension:

```bash
npx nuxi init bug -t content

cd bug

npm install && npm run dev
```

Create `pages/x.vue` (this is just a random name):

```vue
<script setup>
    const { data } = await useAsyncData('home', () => queryContent('/').findOne())
</script>

<template>
    <h1>this works</h1>

    <div>
        <h1>this works</h1>
    </div>
    
    <center>
        <h1>this does not work. Remove the center block to make it work</h1>
    </center>
    
    {{ data }}
</template>
```

video
https://discord.com/channels/473401852243869706/897487139888062506/1008386040949637140

### Describe the bug

i get this error When adding a center 'block':

```
500
Invalid value used as weak map key
```

### Logs

```shell
[Vue warn]: Failed to resolve component: center
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nuxt] [request error] [unhandled] [500] Invalid value used as weak map key
  at WeakMap.set (<anonymous>)  
  at normalizePropsOptions (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3966:11)  
  at createComponentInstance (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6957:23)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)  
  at _sfc_ssrRender (./.nuxt/dist/server/server.mjs:5518:31)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)  
  at ./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:185:29  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async unrollBuffer (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:405:24)
```

**Comment by random-webdeveloper** [comment]
<center> element is deprecated https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

**Comment by danielroe** [comment]
As above, this is not supported out-of-the-box in Vue.

You can enable support if you really need to with something like:

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  vue: {
    compilerOptions: {
      isCustomElement: tag => ['center'].includes(tag)
    }
  }
})
```

**Comment by kristus123** [comment]
Where would i add that config?

And even though center is deprecated it is still widelt used.

I will definitely not be the only one facing this problem.

The error message was not clear at all, so it took an hour of scratching my head.

Also, i can use center in nuxt, but not in combination with nuxt content for some reason

**Comment by kristus123** [comment]
I am not sure if it is correct to just close this ticket so quickly.

**Comment by danielroe** [comment]
This is upstream vue behaviour - see https://github.com/vuejs/core/issues/4347. The config I've posted can be used in your `nuxt.config` if you want, but I would advise not using `<center>`.

**Comment by kristus123** [comment]
O i see. Then i will shut up.
