### ISSUE TITLE
Custom output and srcDir dirs. Build and Generate commands failed

### ISSUE THREAD

**Issue by mihail727** [nuxt/framework#6609]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `modules`, `vite`, `css`, `tailwindcss`, `nitro`, `root`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`, `@vueuse/nuxt@9.1.0`
- Build Modules:    `-`
------------------------------

### Describe the bug

I'm trying to use the changed project structure, but after a series of recent updates, the `build` and `generate` commands stopped running

<details>
<summary>Project structure</summary>

![](https://i.imgur.com/z1C9U4D.png) ![](https://i.imgur.com/AUgL90c.png)
</details>

<details>
<summary><code>nuxt.config.ts</code></summary>

```ts
import { defineNuxtConfig } from 'nuxt';
import modulesConfig from './configs/nuxt.modules.config';

export default defineNuxtConfig({
	...modulesConfig,
	nitro: {
		output: {
			dir: '~~/build',
		},
	},
	srcDir: './src',
});
```
</details>

in dev mode all works fine, but when i'm trying to build or generate i get this errors:
<details>
<summary><code>yarn generate</code></summary>

![](https://i.imgur.com/B7RaFpm.png)
</details>
<details>
<summary><code>yarn build</code></summary>

![](https://i.imgur.com/aOt07x8.png)
</details>

-----
i'm working at private project but if u need i can give u access to repository...

**Comment by 516310460** [comment]
Would you please provide a reproduction?

**Comment by mihail727** [comment]
> Would you please provide a reproduction?

if u ready to help and ready to connect with me in discord - i will give access to repo....

**Comment by 516310460** [comment]
> > Would you please provide a reproduction?
> 
> if u ready to help and ready to connect with me in discord - i will give access to repo....

Or you can directly provide a ` stackblitz '`

**Comment by mihail727** [comment]
> > > Would you please provide a reproduction?
> > 
> > 
> > if u ready to help and ready to connect with me in discord - i will give access to repo....
> 
> Or you can directly provide a ` stackblitz`

i found a bug..... problems with `build` and `generate` commands start when there are russian folders in the project path
for example my project path is `/home/supp/Документы/dev/adrenaline-swap` when i moved project folder to `/home/supp/adrenaline-swap` - everything worked

**Comment by mihail727** [comment]
The question is what can be done to store the project in a folder with a Russian name?

**Comment by 516310460** [comment]
> > > > Would you please provide a reproduction?
> > > 
> > > 
> > > if u ready to help and ready to connect with me in discord - i will give access to repo....
> > 
> > 
> > Or you can directly provide a ` stackblitz`
> 
> i found a bug..... problems with `build` and `generate` commands start when there are russian folders in the project path for example my project path is `/home/supp/Документы/dev/adrenaline-swap` when i moved project folder to `/home/supp/adrenaline-swap` - everything worked

why not use english name

**Comment by mihail727** [comment]
> Contributor



> > > > > Would you please provide a reproduction?
> > > > 
> > > > 
> > > > if u ready to help and ready to connect with me in discord - i will give access to repo....
> > > 
> > > 
> > > Or you can directly provide a ` stackblitz`
> > 
> > 
> > i found a bug..... problems with `build` and `generate` commands start when there are russian folders in the project path for example my project path is `/home/supp/Документы/dev/adrenaline-swap` when i moved project folder to `/home/supp/adrenaline-swap` - everything worked
> 
> why not use english name

it just came as a surprise .... before this problem did not arise .... but in general it seems to me this strange behavior

**Comment by 516310460** [comment]
Okey

**Comment by danielroe** [comment]
I investigated briefly biut couldn't reproduce with the example directories you gave. Would you provide a reproduction please? 🙏

**Comment by mihail727** [comment]
> I investigated briefly but couldn't reproduce with the example directories you gave. Would you provide a reproduction please? pray

I don't know how to do it in online editors stackblitz or codesandbox, but u can do it locally
clone this `git clone https://github.com/mihail727/nuxt-template.git` in folder with russian chars

**Comment by 516310460** [comment]
https://stackblitz.com/edit/github-wcnwfc?file=src%2Fapp.vue,src%2Flayouts%2Fdefault.vue,package.json
Looks normal

**Comment by mihail727** [comment]
> https://stackblitz.com/edit/github-wcnwfc?file=src%2Fapp.vue,src%2Flayouts%2Fdefault.vue,package.json Looks normal

ok... then i dont know what a problem... maybe my OS?
sorry

**Comment by 516310460** [comment]
> > https://stackblitz.com/edit/github-wcnwfc?file=src%2Fapp.vue,src%2Flayouts%2Fdefault.vue,package.json Looks normal
> 
> ok... then i dont know what a problem... maybe my OS? sorry

no problem

**Comment by mihail727** [comment]
i just move my project to `home/supp/Dev/adrenaline-swap` and enough
