### ISSUE TITLE
vite fs access can conflict with api/page routes (`/app`, `/error`, etc.)

### ISSUE THREAD

**Issue by silencerspirit** [nuxt/framework#6626]
After delete .lock file and update dependencies got in console:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/22055696/184605810-92f6963f-c667-47b0-afa2-e16bf24692ee.png">

1) old .lock https://tppr.me/MNVYK
2) new .lock https://tppr.me/VpKDC

Vite .lock changes https://tppr.me/bpWqq

**On server side is ok.**

Maybe this bug need post to vite issue, but i not sure.

**Comment by 516310460** [comment]
would you please provide a reporduction?

**Comment by silencerspirit** [comment]
Can't reproduction it on https://stackblitz.com/ =(
But it not reproduce if i rename my folder from **api** to another name(for example **endpoints** or **API**)

<img width="667" alt="image" src="https://user-images.githubusercontent.com/22055696/184614164-c85ea4f0-2cb2-4800-96ce-213ffebff2fe.png">

<img width="412" alt="image" src="https://user-images.githubusercontent.com/22055696/184614212-6a3daea7-732f-4e1d-b716-b2bfb9ce77d3.png">


Maybe **api** folder name reserved?

**Comment by 516310460** [comment]
not use stackblitz.com

**Comment by silencerspirit** [comment]
> Unable to use stackblitz.com
@danielroe @516310460 
I find the bug: if i defined in nuxt.config.ts: 

```
vite: {
    server: {
      proxy: {
        '/api/': 'https://jsonplaceholder.typicode.com/',
      },
    },
  }
```

^ that broken imports on client from 'api' folder.

**Reproduction link** - https://github.com/silencerspirit/vite-proxy-bug

**Comment by DamianGlowala** [comment]
Have you considered using https://github.com/wobsoriano/nuxt-proxy instead?

**Comment by silencerspirit** [comment]
> Have you considered using https://github.com/wobsoriano/nuxt-proxy instead?

No, I prefer to use everything "out of the box"

**Comment by DamianGlowala** [comment]
Well, Nitro hasn't got a built-in proxy support yet and `nuxt-proxy` is a recommended choice for the time being: https://github.com/unjs/nitro/issues/113#issuecomment-1180621076

Had issues in the past trying to proxy requests in the way you outlined above, which the library I shared nicely resolved. This, to me, is an "out of the box" example.

**Comment by 516310460** [comment]
> > Unable to use stackblitz.com
> 
> @danielroe @516310460 I find the bug: if i defined in nuxt.config.ts:
> 
> ```
> vite: {
>   server: {
>     proxy: {
>       '/api/': 'https://jsonplaceholder.typicode.com/',
>       },
>   },
> }
> ```
> 
> ^ that broken imports on client from 'api' folder.
> 
> **Reproduction link** - https://github.com/silencerspirit/vite-proxy-bug

There seems to be a problem using 'API' as the name of the folder

**Comment by 516310460** [comment]
@danielroe 
This may be a 'vite' error
The problem is that the root directory does not seem to be able to use 'api' as the folder name

**Comment by 516310460** [comment]
> @danielroe This may be a 'vite' error The problem is that the root directory does not seem to be able to use `api` as the folder name

I tried it in vite, but there is no such problem. I don't know how to find this problem

**Comment by silencerspirit** [comment]
@danielroe @pi0 Hi!

Please take a look at this case when you have time and maybe add this case to `vite` issue?

**Comment by danielroe** [comment]
I would advise against using the vite devServer proxy options for this reason - they may not behave as expected. And indeed this doesn't work in vite itself either: https://stackblitz.com/edit/vitejs-vite-vbbq96.

Having said that, I believe it is worth considering whether we can add a prefix in dev mode to ensure assets + page/api urls don't collide. (We already have issues with `/app` and `/error`, for example.)
