### ISSUE TITLE
Cannot find module '#components' or its corresponding type declarations.

### ISSUE THREAD

**Issue by cawa-93** [nuxt/framework#6631]
### Environment
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
- 
### Reproduction

https://stackblitz.com/edit/github-mgw8bo?file=getComponent.ts

### Describe the bug

After upgrading from rc-6 to rc-8, I get a type error, even though there is actually no error in the runtime
```ts
// Cannot find module '#components' or its corresponding type declarations.
import { HelloWorld } from '#components';
```

**Comment by danielroe** [comment]
You should be able to import from '#build/components' for now.

A related issue has been resolved in https://github.com/nuxt/framework/pull/6580, and is available on the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/).
