### ISSUE TITLE
not able to overwrite compilerOptions

### ISSUE THREAD

**Issue by boostie** [nuxt/framework#6651]
### Environment

mac os

### Reproduction

adding the following values into tsconfig.json

```
"compilerOptions": {
    "lib": [
      "es2020", "esnext"
    ],
    "module": "commonjs",
    "target": "es2020"
  }
```

Does not override the .nuxt/tsconfig.json file and keeps target as ESNext

### Describe the bug

I need to overwrite the compilerOptions because during the "nuxi run dev" I am unable to load a package that requires a different target. When using the following code for the main tsconfig.json file at the root of the project, it does not overwrite the changes and resulting target is always as its set initially by nuxi. 

```
{
  // https://v3.nuxtjs.org/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "lib": [
      "es2020", "esnext"
    ],
    "module": "commonjs",
    "target": "es2020"
  }
}

```

There needs to be a way to overwrite this. If I build the project, the imported module does not give errors. During the development, I am getting compilation errors for 

`Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)`

which should be corrected by changing the target during the compilation.

**Comment by danielroe** [comment]
You can set this in your Nuxt config, within `typescript.tsConfig`.

**Comment by boostie** [comment]
> 

Thanks, I was actually able to change it using that setting, the error still remains thought. Does someone know the difference between building and running as dev for the error below? (when built, no error is popping up)

```
Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)

    node_modules/@solana/web3.js/lib/index.browser.esm.js:4466:20:
      4466 │     const U64_MAX = 2n ** 64n - 1n;
```

Thanks

**Comment by danielroe** [comment]
Likely your issue is not about your tsconfig, but maybe esbuild or rollup target. Would you provide a reproduction? 🙏

**Comment by Redemption198** [comment]
I also encountered this issue while testing [wasm-vips](https://github.com/kleisauke/wasm-vips) with Nuxt 3, the issue seems to be caused by Vite/esbuild as mentioned here https://github.com/vitejs/vite/issues/9062.

A Nuxt 3 reproduction is available [here](https://stackblitz.com/edit/nuxt-starter-ogfbih?file=app.vue).

**Comment by kleisauke** [comment]
@Redemption198 To fix the dev server you can exclude wasm-vips from pre-bundling and set the required COOP and COEP headers, for example:

```ts
// nuxt.config.ts
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
    serverMiddleware: ['./middleware/coop-coep-headers.ts'],
    vite: {
        optimizeDeps: {
            exclude: ['wasm-vips']
        }
    }
})
```
```ts
// middleware/coop-coep-headers.ts
export default function (req: any, res: any, next: any) {
    res?.setHeader('Cross-Origin-Embedder-Policy', 'require-corp')
    res?.setHeader('Cross-Origin-Opener-Policy', 'same-origin')
    next();
}
```

The production build is (unfortunately) currently broken, as you noticed. This is due to issue https://github.com/vitejs/vite/issues/7015, which causes an infinite loop when it tries to transform/bundle `lib/vips-es6.worker.js`.

**Comment by Redemption198** [comment]
> @Redemption198 To fix the dev server you can exclude wasm-vips from pre-bundling and set the required COOP and COEP headers, for example:
> 
> 
> 
> ```ts
> 
> // nuxt.config.ts
> 
> // https://v3.nuxtjs.org/api/configuration/nuxt.config
> 
> export default defineNuxtConfig({
> 
>     serverMiddleware: ['~/middleware/coop-coep-headers.ts'],
> 
>     vite: {
> 
>         optimizeDeps: {
> 
>             exclude: ['wasm-vips']
> 
>         }
> 
>     }
> 
> })
> 
> ```
> 
> ```ts
> 
> // middleware/coop-coep-headers.ts
> 
> export default function (req: any, res: any, next: any) {
> 
>     res?.setHeader('Cross-Origin-Embedder-Policy', 'require-corp')
> 
>     res?.setHeader('Cross-Origin-Opener-Policy', 'same-origin')
> 
>     next()
> 
> }
> 
> ```
> 
> 
> 
> The production build is (unfortunately) currently broken, as you noticed. This is due to issue https://github.com/vitejs/vite/issues/7015, which causes an infinite loop when it tries to transform/bundle `lib/vips-es6.worker.js`.

Thanks, I'll try that again in the future 👍

**Comment by danielroe** [comment]
Closing this to track the feature request in https://github.com/nuxt/framework/issues/7471. The remaining issue here appears to be an upstream vite bug and is not the one described in the issue.
