### ISSUE TITLE
当我在useFetch headers里面添加大写开头的请求头时，并且请求格式为applications/json时，他会自动转换为小写开头，比如Authorization会被自动转换为authorization，我当前nuxt版本为3.0.0-rc.7

### ISSUE THREAD

**Issue by usertangxin** [nuxt/framework#6657]
### Describe the feature

当我在useFetch headers里面添加大写开头的请求头时，并且请求格式为applications/json时，他会自动转换为小写开头，比如Authorization会被自动转换为authorization，我当前nuxt版本为3.0.0-rc.7

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by 516310460** [comment]
would you please provide a reproduction?

**Comment by usertangxin** [comment]
> 

useFetch<T>('http://127.0.0.1:3000', {
    server: false,
    headers: {
      Authorization: 'ffffffffff',
    },
    method: 'post',
    body: { name: 'fff' },
  });

**Comment by 516310460** [comment]
Link: https://stackblitz.com/

**Comment by 516310460** [comment]
> 

Http/2 and HTTP/1.X also use ASCII character sets, but the HTTP/2 header must use lowercase, unlike http/1.X, which can use both case and case

**Comment by 516310460** [comment]
The keys in the custom 'headers' will be wrapped by the' headers' object and automatically converted to lowercase

**Comment by danielroe** [comment]
Thanks @516310460 - that's right.

Node lower-cases incoming headers. 

Note that by specification, http headers are caseless, so it should also be safe to lower-case outgoing headers too. If there is a provider you are using that is case-sensitive, please do let us know.
