### ISSUE TITLE
[rc.8] NuxtPage with keepalive on page + conditional root element results in weird errors

### ISSUE THREAD

**Issue by stenet** [nuxt/framework#6679]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.7.0`
- Builder:          `vite`
- User Config:      `app`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Open [https://stackblitz.com/github/stenet/nuxt-keep-alive](https://stackblitz.com/github/stenet/nuxt-keep-alive) and click on "sub 123". After the page is displayed click on "index" => you will see the following error in the console and a corrupted page. Navigating now doesn't work anymore.

![image](https://user-images.githubusercontent.com/1838511/184888354-82fbae74-0cea-40ae-811f-50a840e322dc.png)

### Describe the bug

The problem occurs when the following conditions are true:

- NuxtPage in app.vue
- definePageMeta with keepalive in /index.vue
- root element in /sub/[id].vue has a v-if

The problem does not happen when I use RouterView/KeepAlive/Component instead of NuxtPage in app.vue or if I disable keepalive.

Also this case maybe isn't that common (?) it would definitely be helpful if the console error message has some better information.

**Comment by 516310460** [comment]
Using `v-if` on the outermost layer and having a page setting `keepalive: true` will cause an error

**Comment by 516310460** [comment]
Link: https://github.com/vuejs/core/issues/5657
At present, `v-show` can be used to replace `v-if`

**Comment by stenet** [comment]
@516310460 thanks! ```v-show``` is no option in my case, as some data needs to be fetched. A temporary solution is to add another div and add ```v-if``` on the nested div.

**Comment by 516310460** [comment]
> @516310460 thanks! `v-show` is no option in my case, as some data needs to be fetched. A temporary solution is to add another div and add `v-if` on the nested div.

Or you should use ` TSX`

```tsx
const temp = () => {
  return <div>
    <h1>Level 01/Page 01</h1>
    <input type="text" />
  </div>
}
```

```vue
<template>
  <temp v-if="visible"/>
</template>
```

**Comment by 516310460** [comment]
I hope you have something to gain

**Comment by stenet** [comment]
@516310460 haha, nice solution. 

My problem was not the v-if, for which there are some solutions, but that I did not know where the error comes from and I have now spent an afternoon trying everything until I got it out.

I think it would help if the Vue team could come up with a better error message. This might save someone else the same work :)

**Comment by danielroe** [comment]
Closing as this is not something we can resolve in Nuxt.
