### ISSUE TITLE
[rc.8] keep alive components get destroyed when navigating to a component with keep alive false

### ISSUE THREAD

**Issue by stenet** [nuxt/framework#6682]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.7.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Open [https://stackblitz.com/github/stenet/nuxt-keep-alive-demo?file=app.vue](https://stackblitz.com/github/stenet/nuxt-keep-alive-demo?file=app.vue) and click through the navigation links (not "no keep alive" - as this page has keepAlive not configured) and enter some values in the inputs. Until now everything works as excepted:

![image](https://user-images.githubusercontent.com/1838511/184897786-9fad35dd-4167-41ed-a98c-2ebfa34263e4.png)

As soon as you click on "no keep alive" all keep alive components are destroyed:

![image](https://user-images.githubusercontent.com/1838511/184897939-355ea2af-7ffe-4589-bd40-c3749ce44298.png)

### Describe the bug

I'm not sure if this behavior was done on purpose. But I can say that Vue handles include/exclude differently and does not destroy the cache. Therefore it would make sense to me that Nuxt behaves the same way.

**Comment by stenet** [comment]
@danielroe If you find a minute, could you please tell me if I'm doing (or misunderstood) something wrong here or if this is something that will be changed/fixed in Nuxt in the future?

**Comment by danielroe** [comment]
`keepalive` is meant to fully disable the parent `<keepalive>` component. If you want to configure what is included, you can pass an object with options:

```js
definePageMeta({
  keepalive: {
    include: [/* */]
  }
})
```

Moreover, you can now configure it directly on `<NuxtPage>` if you want to configure `include` in a single place: https://github.com/nuxt/framework/pull/7492.
