### ISSUE TITLE
Client-only useFetch only resolving once when called multiple times

### ISSUE THREAD

**Issue by LouisHaftmann** [nuxt/framework#6698]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `pnpm@7.9.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-bt5m64?file=app.vue

### Describe the bug

When calling a client-only useFetch-hook (server: false) multiple times only the first call resolves. All other calls are 'stuck' in pending state. This happens regardless of where the hook is called as long as it is called on page load.

### Additional context

This problem existed since 3.0.0-rc.3

**Comment by LouisHaftmann** [comment]
Related to #6531 #6704. Probably fixed by #5738

**Comment by danielroe** [comment]
cc: @pi0

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/6704.
