### ISSUE TITLE
Problem when using 'TSX' rendering template

### ISSUE THREAD

**Issue by 516310460** [nuxt/framework#6700]
### Environment

- Operating System: MacOS
- Node Version: v16.13.0
- Nuxt Version: 3.0.0-rc.8-27677607.a3a8706
- Package Manager: pnpm@7.5.2
- Builder: vite
- User Config: vite
- Runtime Modules: -
- Build Modules: -

### Reproduction

https://stackblitz.com/edit/github-jjxw1t?file=pages%2Fsub%2F[id].vue,pages%2Findex.vue

### Describe the bug

If you are using 'TSX' rendering and do not add it, an error will be reported

```ts
definePageMeta({
  // keepalive: true
})
```

Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### Additional context

definePageMeta({
  // keepalive: true
})

### Logs

```shell
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

**Comment by 516310460** [comment]
@danielroe

**Comment by danielroe** [comment]
You have more than one root node in `sub/[id].vue`. (Comments count.)

**Comment by 516310460** [comment]
> You have more than one root node in `sub/[id].vue`. (Comments count.)

It may not be caused by this problem. You can check `room.tsx`

**Comment by 516310460** [comment]
Use Link: https://v3.nuxtjs.org/guide/directory-structure/pages#usage
// https://vuejs.org/guide/extras/render-function.html#jsx-tsx
export default defineComponent({
  render () {
    return <h1>Index page</h1>
  }
})

Just refresh the page and an error will be reported

**Comment by 516310460** [comment]
If 'keepalive' is not used, 'sub' will report an error

https://stackblitz.com/edit/github-jjxw1t?file=pages%2FtestTsx2.tsx,pages%2FtestTsx1.tsx,app.vue,pages%2Findex.vue

**Comment by 516310460** [comment]
@pi0

**Comment by danielroe** [comment]
seems to work fine when the page I mentioned is removed: https://stackblitz.com/edit/github-jjxw1t-rda88t.

**Comment by 516310460** [comment]
Please check `/testtsx4/testtsx5` and switch back and forth with other pages, and then open the console

https://stackblitz.com/edit/github-jjxw1t-c8e12q?file=pages%2FtestTsx3%2Findex.tsx,app.vue,pages%2Findex.vue,pages%2FtestTsx4%2Findex.vue,pages%2FtestTsx4%2FtestTsx5%2Findex.vue

**Comment by danielroe** [comment]
They _ALSO_ have multiple root elements. That is the issue. Wrap them in a single root element and you will be fine. Example: https://stackblitz.com/edit/github-jjxw1t-kx8pvw?file=pages%2FtestTsx2.tsx,pages%2FtestTsx1.tsx,app.vue,pages%2Fsub%2Findex.vue

**Comment by 516310460** [comment]
I still don't understand one point. Why is it feasible to set `keepalive: true`

**Comment by 516310460** [comment]
It's mainly that this question has puzzled me for a long time. I haven't found the relevant answer. Thank you
