### ISSUE TITLE
rc8 issue with `typeorm` cannot destructure property `ConnecitionOptionsReader`

### ISSUE THREAD

**Issue by aschojz** [nuxt/framework#6702]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `css`, `build`, `intlify`, `serverMiddleware`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction
https://stackblitz.com/edit/github-huzzpl?file=plugins%2Ftypeorm-plugin.server.ts

<img width="711" alt="image" src="https://user-images.githubusercontent.com/25245331/185077290-f67168cb-c1f3-44c7-8c36-1610a7c08554.png">

### Describe the bug

I had a running app with RC4, but with the current RC all sub-dependencies link to RC8, so I had to update and my app now breaks.

In the dev-mode the console logs that `__vite_ssr_import_0__.default` is undefined which is imported by typeorm.

`const __vite_ssr_import_0__ = await __vite_ssr_import__("/node_modules/typeorm/index.js");`

Could this be an issue with vite@3 ? I would be very glad, if someone has any ideas or if it would be possible to use the RC4 until then.

**Comment by pi0** [comment]
Would you please provide a reproduction? 🙏🏼

**Comment by aschojz** [comment]
I will try to do a reproduction.

Until then I just logged `__vite_ssr_import_0__` and it seems to have all the needed functions, but not the default-property:

<img width="279" alt="image" src="https://user-images.githubusercontent.com/25245331/185088265-6561157d-c9d4-4f9c-96a4-2d0ef8effde3.png">

**Comment by aschojz** [comment]
> Would you please provide a reproduction? 🙏🏼

https://stackblitz.com/edit/github-huzzpl?file=plugins%2Ftypeorm-plugin.server.ts

**Comment by pi0** [comment]
Thanks for reproduction @aschojz. Checking `typeorm` [package.json](https://unpkg.com/browse/typeorm@0.3.7/package.json) is only [valid ESM](https://v3.nuxtjs.org/guide/going-further/esm) with `node` condition and it is not a condition we use to import for (universal) app files such as Nuxt plugins.

If you migrate to [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel) this issue should be solved as we enabled `vite-node` by default and seems applying `node` condition. (you use `experimental: { viteNode: true }` in `nuxt.config` for RC.8)

An alternative solution is explicitly import from `'typeorm/index.mjs'`

**Comment by aschojz** [comment]
thanks for the input @pi0 

the fix with `typeorm/index.mjs` works for me
