### ISSUE TITLE
Rollup error: Unexpected character '' (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by bieric** [nuxt/framework#6703]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-2ebtve

Open a new terminal and run `yarn run build`

### Describe the bug

When I run `yarn run build` the following error appears:

```
 WARN  rollup-plugin-inject: failed to parse /home/projects/github-2ebtve/node_modules/@emurgo/cardano-serialization-lib-browser/cardano_serialization_lib_bg.wasm. Consider restricting the plugin to particular files via options.include


 ERROR  Rollup error: Unexpected character '' (Note that you need plugins to import files that are not JavaScript)


 ERROR  Unexpected character '' (Note that you need plugins to import files that are not JavaScript)

  at error (node_modules/rollup/dist/es/shared/rollup.js:1888:30)
  at Module.error (node_modules/rollup/dist/es/shared/rollup.js:12458:16)
  at Module.tryParse (node_modules/rollup/dist/es/shared/rollup.js:12835:25)
  at Module.setSource (node_modules/rollup/dist/es/shared/rollup.js:12740:24)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/rollup.js:22182:20)
```

I'm loading a wasm package like in the example.
I've already opened an issue in the `vite-wasm-plugin` repo (https://github.com/Menci/vite-plugin-wasm/issues/10) but the author stated that this is a bug in nuxt itself. 

He said: "It seems that vendor packages in node_modules are skipped processing by Nuxt-Vite. I don't know which configuration did this. Maybe you should open an issue at Nuxt."

**Comment by danielroe** [comment]
You should add the package exporting `.wasm` to your `build.transpile`.

**Comment by danielroe** [comment]
Note: if you want to enable wasm on server side, you will need to add the following to your nuxt config:

```js
  nitro: {
    experimental: {
      wasm: true
    }
  },
```

**Comment by bieric** [comment]
Perfect, that's it. Thank you very much 🤞
