### ISSUE TITLE
Auto import of `onMounted` is not working

### ISSUE THREAD

**Issue by YIngChenIt** [nuxt/framework#6705]
### Environment

Operating System: Linux
Node Version: v16.14.2
Nuxt Version: 3.0.0-rc.8
Package Manager: npm@7.17.0
Builder: vite

### Reproduction

https://stackblitz.com/edit/github-pkcf1z?file=app.vue

### Describe the bug

If both exist `class="xx"` and `//` , page not working ! 

I think the problem is caused by compile `//` 

```
<template>
  <div class="abc">123</div>
</template>

<script setup>
const a = `//`

onMounted(() => {
  console.log('hello')
})
</script>

```

```
[Vue warn]: Unhandled error during execution of setup function 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >
[nitro] [dev] [unhandledRejection] ReferenceError: onMounted is not defined
```

**Comment by pi0** [comment]
Thanks for reporting the issue @YIngChenIt. Adding manual `import { onMounted } from '#imports'` (or `vue`) makes it working.

It seems an issue with auto imports and `const a = `//`;` line.

@antfu Would you please check this issue?

**Comment by Cogitoergo** [comment]
Can confirm, two backslashes breaks autoImports functionality, nothing after those lines work, ref, useFetch, useAsyncData etc. Even if it's an URL. What works is always using baseURL parameter with the double slashes, that seem to work just fine.

switching from:

`
<script setup>
const url = 'https://apiurl/endpoint'
await useFetch(url)
</script>
`

to

`
<script setup>
const url = '/endpoint'
await useFetch(url, { baseURL: 'https://apiurl' })
</script>
`

solves the problem.

**Comment by danielroe** [comment]
I believe this is resolved upstream; I can't reproduce on a new nuxt project.
