### ISSUE TITLE
resolveComponent() not working, when variable is passed to it

### ISSUE THREAD

**Issue by codeflorist** [nuxt/framework#6711]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-1bx833?file=app.vue

### Describe the bug

Here comes a weird one. 🤪

I guess this code describes the problem quite well:

```js
<script setup>
const thisIsWorking = resolveComponent('FooBar');

const componentName = 'FooBar';
const thisIsNotWorking = resolveComponent(componentName);

const thisIsAlsoNotWorking = resolveComponent('Foo' + 'Bar');
</script>
<template>
  <div>
    <component :is="thisIsWorking" />
    <component :is="thisIsNotWorking" />
    <component :is="thisIsAlsoNotWorking" />
  </div>
</template>
```

`resolveComponent()` only works, if the full component-name is handed to the function. It is not working in any other case. E.g.:
- Handing a variable containing the component-name.
- Handing a concatenated string.
- Calling a function, that returns the component-name.

**Comment by danielroe** [comment]
Nuxt auto imports will only be able to automatically import where a simple string is passed to `resolveComponent`. If you want fully dynamic components that are globally registered across your app, follow the steps here: https://v3.nuxtjs.org/guide/directory-structure/components#dynamic-components.

**Comment by codeflorist** [comment]
hmm, i guess this will cause some head-scratching, since it goes against some very basic assumptions about programming.

also, imho it makes `resolveComponent()` pretty useless, because if i already know the name of the component i can simply write...

```js
<FooBar />
```

...instead of...

```js
<component :is="resolveComponent('FooBar')" />
```

**Comment by danielroe** [comment]
It's shorthand for making auto-imports work in code, for example:

```js
const componentMap = {
  link: resolveComponent('NuxtLink'),
  // ...
}
```

If you need to programmatically resolve a component, then nuxt can't know at _build_ time which one it is, which is why you need to declare them globally, which you can either do with `.global` suffix or `~/components/global` directory. (Registering them globally is what Vue would require you to do anyway.)

**Comment by codeflorist** [comment]
ah, ok. that makes sense. many thanks!
