### ISSUE TITLE
Document `<NuxtWelcome />`

### ISSUE THREAD

**Issue by BD103** [nuxt/framework#6715]
It would be nice if the API docs included the `<NuxtWelcome />` component under the components tab. ([https://v3.nuxtjs.org/api/components/](https://v3.nuxtjs.org/api/components/nuxt-page)) This will let people know that this component exists, and provide a brief explanation of how it's used.

This may be a small change, but they add up in the end. Thanks for creating such a great framework!

**Comment by pi0** [comment]
Would you like to make a PR? 👍🏼

**Comment by BD103** [comment]
I'm quite busy at the moment, so I can't right now. My apologies.
