### ISSUE TITLE
Slots break extend, if extend-folder is side by side with project-folder

### ISSUE THREAD

**Issue by fabianwohlfart** [nuxt/framework#6720]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@6.14.16`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/fabianwohlfart/test__nuxt-3-extend

```
cd extend
npm install

cd base
npm install
npm run build
npm run preview
```

### Describe the bug

If you move the extend-folder out of the project-folder, to be a separate repo, and use `<slots>` it throws an error regarding `isCE` and `Hydration`. Only in build mode.

```
entry.4c2179d9.mjs:1 TypeError: Cannot read properties of null (reading 'isCE')
    at Q (TestButton.b9bd506a.mjs:1:1182)
    at Proxy.<anonymous> (TestButton.b9bd506a.mjs:1:5029)
    (...)

entry.4c2179d9.mjs:1 Hydration completed but contains mismatches.

```

### Additional context

I want to have my extension as a separate repo to use it for multiple projects.
Therefor I moved the extension folder out of the root folder.
The extend-folder also needs a `node_modules` as it is separated from the projects-folder.
I assume this is the problem, as it is _another_ nuxt instance?

Removing the `<slot>` works, as does including the extend-folder inside the projects-folder without it's own  `node_modules`.

**Comment by danielroe** [comment]
For now, you can add this to your nuxt config. Will investigate to see if we should make this the default (there was an issue blocking this last time I checked, but it seems to be working well with vite 3).

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  // ...
  vite: {
    resolve: {
      dedupe: ['vue']
    }
  }
})
```
