### ISSUE TITLE
The following error occurred when nuxt added the request module. Have you ever encountered it

### ISSUE THREAD

**Issue by boyGdm** [nuxt/framework#6726]
### Environment

Nuxt CLI v3.0.0-rc.8

### Reproduction

modules: [
        ['@nuxtjs/axios', { proxyHeaders: false}]
    ],

### Describe the bug

[nuxt] [request error] [unhandled] [500] _createApp is not a function
  at Object.renderToString (/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com+vue-bundle-renderer@0.4.2/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:25)
  at async /C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/.nuxt/dev/index.mjs:516:21
  at async /C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/.nuxt/dev/index.mjs:106:22
  at async /C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com+h3@0.7.15/node_modules/h3/dist/index.mjs:492:19
  at async Server.nodeHandler (/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com+h3@0.7.15/node_modules/h3/dist/index.mjs:438:7)
[nitro] Error while generating error response FetchError: 500  (/__nuxt_error?url=/&statusCode=500&statusMessage=Internal+Server+Error&message=_createApp+is+not+a+function&description=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+Object.renderToString+(/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com%2Bvue-bundle-renderer@0.4.2/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:25)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/.nuxt/dev/index.mjs:516:21%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/.nuxt/dev/index.mjs:106:22%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com%2Bh3@0.7.15/node_modules/h3/dist/index.mjs:492:19%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+Server.nodeHandler+(/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com%2Bh3@0.7.15/node_modules/h3/dist/index.mjs:438:7)%3C/span%3E%3C/pre%3E&data)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.errorhandler [as onError] (file:///C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/.nuxt/dev/index.mjs:354:16)
    at async Server.nodeHandler (file:///C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com+h3@0.7.15/node_modules/h3/dist/index.mjs:445:9)
[nuxt] [request error] [unhandled] [500] _createApp is not a function
  at Object.renderToString (/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com+vue-bundle-renderer@0.4.2/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:25)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async /C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/.nuxt/dev/index.mjs:516:21
  at async /C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/.nuxt/dev/index.mjs:106:22
  at async /C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com+h3@0.7.15/node_modules/h3/dist/index.mjs:492:19
  at async Server.nodeHandler (/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com+h3@0.7.15/node_modules/h3/dist/index.mjs:438:7)
[nitro] Error while generating error response FetchError: 500  (/__nuxt_error?url=/&statusCode=500&statusMessage=Internal+Server+Error&message=_createApp+is+not+a+function&description=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+Object.renderToString+(/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com%2Bvue-bundle-renderer@0.4.2/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:25)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+processTicksAndRejections+(internal/process/task_queues.js:93:5)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/.nuxt/dev/index.mjs:516:21%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/.nuxt/dev/index.mjs:106:22%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com%2Bh3@0.7.15/node_modules/h3/dist/index.mjs:492:19%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+Server.nodeHandler+(/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com%2Bh3@0.7.15/node_modules/h3/dist/index.mjs:438:7)%3C/span%3E%3C/pre%3E&data)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.errorhandler [as onError] (file:///C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/.nuxt/dev/index.mjs:354:16)
    at async Server.nodeHandler (file:///C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com+h3@0.7.15/node_modules/h3/dist/index.mjs:445:9)

 WARN  [SSR] Error transforming /@fs/C:/Users/xqx/desktop/study/nuxt/nuxt3/nuxtDemoTwo/node_modules/.pnpm/registry.npmmirror.com+nuxt@3.0.0-rc.8/node_modules/nuxt/dist/app/entry: filename.split is not a function

**Comment by 516310460** [comment]
Please refer to the documentation
Link: https://axios.nuxtjs.org/

**Comment by boyGdm** [comment]
I know how to read documents. The problem is that I just introduced the @ nuxt / Axios module code and reported an error. If the module code is removed, no error will be reported. This should be a bug

**Comment by boyGdm** [comment]
I haven't tried other versions. My version is nuxt cli v3.0.0-rc 8. Is there any other way.

**Comment by 516310460** [comment]
Please use a module that supports `Nuxt3`
Link: https://modules.nuxtjs.org/
Or
If you want to use `axios`. you can write one yourself. or use the official `usefetch`

**Comment by boyGdm** [comment]
I have tried to customize Axios. My requirements are different environments and different request paths. If usefetch or customization is used, it seems that proxy can not be used to proxy forwarding addresses in useasyncdata. Is there a better way.

**Comment by 516310460** [comment]
Please use
Link: https://github.com/wobsoriano/nuxt-proxy

**Comment by danielroe** [comment]
@516310460 is right. `@nuxtjs/axios` is not compatible (as a module) with Nuxt 3. But you can use axios directly, even within `useAsyncData`, or write a composable yourself that wraps `useAsyncData` but uses axios under the hood.

There are also direct ports of the axios module, like https://github.com/Teranode/nuxt-module-alternatives.
