### ISSUE TITLE
Some styles are missing after css is compiled, and it is normal for development.

### ISSUE THREAD

**Issue by amihhs** [nuxt/framework#6727]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `modules`, `experimental`, `unocss`, `colorMode`, `hooks`
- Runtime Modules:  `@vueuse/nuxt@9.1.0`, `@unocss/nuxt@0.45.7`, `@pinia/nuxt@0.4.0`, `@nuxtjs/color-mode@3.1.4`
- Build Modules:    `-`
------------------------------

### Reproduction

[https://github.com/amihhs/github-xtzryz](https://github.com/amihhs/github-xtzryz)

1. pnpm i 
2. pnpm build
3. pnpm start

file: /layouts/default.vue

### Describe the bug

I use unocss
```scss
.default-header{
  @apply fixed w-full top-0 z-999 shadow-lg backdrop-blur-md;
  @apply bg-white bg-opacity-60 dark:bg-dark-800;
  @apply h-15 sm:h-20;
}
```
It has some less styles at compile time.
- Normal(dev)
![image](https://user-images.githubusercontent.com/59364234/185274580-7dd772ab-10b7-4859-a46c-c53dcdd8a6c0.png)

- Error(build)
![image](https://user-images.githubusercontent.com/59364234/185274684-9d270bb9-c3ec-47d3-a0ea-1ab23c2c9c6a.png)

**Comment by amihhs** [comment]
// layouts/default.vue

At execution time in unocss/transformer-directives 
content:
```css
.default-header,.default-header-place{@apply w-full top-0 z-1 h-15 sm:h-20}.header-hidden{transform:translate3d(0,-100%,0)}
````
The problem should have been before that.

**Comment by 516310460** [comment]
Please add `npm i -D @unocss/transformer-directives`
Link: https://github.com/unocss/unocss/tree/main/packages/transformer-directives

**Comment by amihhs** [comment]
This is irrelevant, unocss and some tools are already installed when `@ unocss/ nuxt` is installed.
It works during dev, which means that `transformer-directives` is already in effect. 
According to what I said [before](https://github.com/nuxt/framework/issues/6727#issuecomment-1218917464). It has been processed by other tools before `transformer-directives` processing, resulting in the lack of some styles

**Comment by 516310460** [comment]
https://stackblitz.com/github/amihhs/github-xtzryz?file=package.json
No error

**Comment by amihhs** [comment]
I can't do build on stackblitz. I'm too sure I can reproduce it on it, but I can reproduce it steadily on my computer.
Maybe you should first.
- npm run build / pnpm build.
- npm run start / pnpm start.

It doesn't go wrong in the process, but there is a problem with the later product of build

**Comment by 516310460** [comment]
No problems were found

**Comment by danielroe** [comment]
Try running `nuxi cleanup`. Do you only enounter this with unocss? What makes you think this is a Nuxt issue?

**Comment by amihhs** [comment]
I'm not sure if this is a problem with nuxt. I created a use case with vite that doesn't have this problem.

I debug found that the code changed after a vite:css plug-in execution.
``` css
/* vite:css  */                                                                                                                    
.ISSUE {
  @apply fixed w-full top-0 z-999 shadow-lg backdrop-blur-md bg-white bg-opacity-60 dark:bg-dark-800 h-15 sm:h-20;
}

.default-header-place {
  @apply w-full top-0 z-1 h-15 sm:h-20;
}

/* vite:esbuild */
.ISSUE,.default-header-place{@apply w-full top-0 z-1 h-15 sm:h-20}   
```

vite:[https://github.com/amihhs/vite-test](https://github.com/amihhs/vite-test)
nuxt:[https://github.com/amihhs/github-xtzryz](https://github.com/amihhs/github-xtzryz)

**Comment by 516310460** [comment]
You can use `tailwindcss` or a custom `css` to see if it is related to `nuxt`. I don't think it is related to `nuxt`

**Comment by amihhs** [comment]
In the course of testing, I found that if there is a normal css in class, it will work properly.
example:
```css
.ISSUE {
   postions:fixed;
  @apply fixed w-full top-0 z-999 shadow-lg backdrop-blur-md bg-white bg-opacity-60 dark:bg-dark-800 h-15 sm:h-20;
}
```

It should not have much to do with nuxt. It may be the problem with vite3. Before, vite2 was able to work normally.
