### ISSUE TITLE
docs: demo add missing `setup`

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/framework#6729]
sorry, i don't know why i can't pr ,so i post here

link: https://github.com/nuxt/framework/blame/main/docs/content/2.guide/3.directory-structure/7.layouts.md#L72
demo need add missing `setup` in   pages/index.vue

**Comment by danielroe** [comment]
In fact, that is meant to be an example of `definePageMeta` working in a normal `<script>` block.

**Comment by baixiaoyu2997** [comment]
ok , i see
