### ISSUE TITLE
Can't dynamically render `nuxt-link` without importing it into the component

### ISSUE THREAD

**Issue by aluarius** [nuxt/framework#6747]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Build Modules:    `-`

### Reproduction

```vue
<component is="nuxt-link" to="/">Link</component>
```

### Describe the bug

It is rendered as `<nuxt-link to="/">Link</nuxt-link>` instead of `<a href="/">Link</a>`.

### Additional context
Hi!

As a `router-link` it should be rendered in a proper way without direct component importing. This `component is` initially is provided by Vue 3 UI framework button component and should work without additional actions.

Thank you for your attention.

**Comment by danielroe** [comment]
If you need to use it dynamically, then you can use `const NuxtLink = resolveComponent('NuxtLink')`. See https://v3.nuxtjs.org/guide/directory-structure/components/#dynamic-components.
