### ISSUE TITLE
useState not as SSR-friendly as expected?

### ISSUE THREAD

**Issue by Morpheu5** [nuxt/framework#6754]
### Environment

Nuxt CLI v3.0.0-rc.8                                                                                                                                                                                        21:46:49
RootDir: /Users/morpheu5/web/mre                                                                                                                                                                            21:46:50
Nuxt project info:                                                                                                                                                                                          21:46:50

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.3.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `target`, `ssr`, `generate`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/Morpheu5/nuxt3-hydration-mre

### Describe the bug

`useState` produces a client-side hydration mismatch warning when used to exchange data between children and parent – I can't exclude other cases but this is my use case. The warning reads:

```
[Vue warn]: Hydration text content mismatch in <h1>:
- Client: 
- Server: Some page title 
  at <Default > 
  at <AsyncComponentWrapper > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="layout" mode="out-in" > 
  at <Anonymous> 
  at <App key=1 > 
  at <NuxtRoot>
```

If I disable JS in the browser, I can see that the server renders the wrong text. However, when running with JS, the correct text is shown, but this means it is substituted subsequently client-side.

**Comment by danielroe** [comment]
On server render, you can't share data 'up' from child to parent as the parent HTML has already been rendered.

The hydration error is caused by the fact that the child-set data doesn't match the data the parent had access to when rendering.

**Comment by Morpheu5** [comment]
> The hydration error is caused by the fact that the child-set data doesn't match the data the parent had access to when rendering.

Yes, this much is clear.

> On server render, you can't share data 'up' from child to parent as the parent HTML has already been rendered.

Then the documentation should probably say something different than

> Nuxt provides useState composable to create a reactive and SSR-friendly shared state across components.

The way I read it implied that this was possible.

Given that this is not planned, is there another way of achieving this?

**Comment by danielroe** [comment]
Absolutely! You can set use state in the parent component. Or in a plugin, or middleware.

The only limitation with Vue SSR (and this is a general limitation of Vue SSR in general, rather than specific to Nuxt) is that it is not reactive. So once the parent setup function is run it won't reactively update to children. This would be true using a store, or a any other form of global state: you can't set it in a child and have it update in a parent.

**Comment by Morpheu5** [comment]
OK, so one of my use cases is that I want a `pages/page.vue` to set its own title to be shown in a banner which is included in `layouts/default.vue` so I don't have to repeatedly include the banner in each page. If I understand you correctly, this is not possible in Vue SSR at all, so if I want to do this I'll just have to live with the warning, right?

**Comment by danielroe** [comment]
In that case, you could use `<NuxtLayout>` with a slot within the page: https://v3.nuxtjs.org/guide/directory-structure/layouts/#overriding-a-layout-on-a-per-page-basis.

Or you can use `<client-only>` to wrap the part of the layout that is dependent on the individual page.

But you can't ignore the warning; it will result in a broken site if you deploy with it.

**Comment by Morpheu5** [comment]
> In that case, you could use `<NuxtLayout>` with a slot within the page: https://v3.nuxtjs.org/guide/directory-structure/layouts/#overriding-a-layout-on-a-per-page-basis.

OK, that could work. It's a bit clunkier that I'd have liked but not much clunkier than what I have now. One problem is that the layout has a component for the banner and it doesn't look like placing a `<slot name="headline">` in a child of the layout works. Is there a way of maybe passing its content as a prop of the banner component? This is more or less what I have in my layout:

```html
<template>
  <div>
    <TopBanner />
    <slot name="headline">Default headline</slot> <!-- This works just fine -->
    ...
  </div>
</template>
```

> Or you can use `<client-only>` to wrap the part of the layout that is dependent on the individual page.

I could, it does get rid of the warning, but if the other trick gives me a nicer SSR experience, I'd rather take that solution instead of this.

> But you can't ignore the warning; it will result in a broken site if you deploy with it.

OK, this is where I'm lost. When I build and start the production version, I get no warnings (I assume they are hidden by some flag) and everything "works" just fine. Only if I disable JS in the browser do I get a diminished experience (though the rest of the page sort of works because SSR). In what way exactly is the site broken?

Thanks for your time so far!

**Comment by Morpheu5** [comment]
I think [I got it](https://github.com/Morpheu5/nuxt3-hydration-mre/tree/slots) in the end. A bit convoluted but not that bad. I just needed to wrap my head around named slots used like this.
