### ISSUE TITLE
nuxt3.rc-8 not suppport element-plus

### ISSUE THREAD

**Issue by KahrLu** [nuxt/framework#6760]
### Environment

any enviroment

### Reproduction

![image](https://user-images.githubusercontent.com/76502123/185528267-7fab6b5f-174e-4294-8355-3b780bafd7c2.png)
![image](https://user-images.githubusercontent.com/76502123/185528284-36ab7a65-fd3e-4caf-9163-07e7f7d9c8e4.png)

### Describe the bug

When nuxt3.rc-7 and nuxt3.rc-8 are upgraded to vite3, element plus cannot be used normally. Element plus itself supports vite3. Is there a special configuration on nuxt3 that causes the error?

**Comment by 516310460** [comment]
would you please provide a reproduction?

**Comment by KahrLu** [comment]
https://codesandbox.io/s/silly-elgamal-60u8tx?file=/app.vue
@516310460 , here is a demo

**Comment by 516310460** [comment]
Link: https://github.com/element-plus/element-plus-nuxt-starter
This and `nuxt3` authorization, can be linked with `element-plus`

**Comment by KahrLu** [comment]
> Link: https://github.com/element-plus/element-plus-nuxt-starter This and `nuxt3` authorization, can be linked with `element-plus`

I also submit a issue at that repo

**Comment by 516310460** [comment]
You should file the bug in the relevant `ui` library

**Comment by danielroe** [comment]
You can track https://github.com/nuxt/framework/issues/4084.

For now, you can add `element-plus` to `build.transpile`: https://stackblitz.com/edit/github-1wmsan

**Comment by lvbaiying** [comment]
If necessary, import automatically and on demand

**Comment by lvbaiying** [comment]
If necessary, import automatically and on demand

**Comment by lvbaiying** [comment]
If necessary, import automatically and on demand & ssr

// nuxt.config.ts
export default defineNuxtConfig({
  ...
  ssr: true,
  vite: {
    plugins: [
      AutoImport({
        resolvers: [
          ElementPlusResolver({ ssr: process.env.NODE_ENV === 'development' }),
        ],
      }),
      Components({
        dts: true,
        resolvers: [
          ElementPlusResolver({ ssr: process.env.NODE_ENV === 'development' }),
        ],
      }),
    ],
  },
  build: {
    transpile: process.env.NODE_ENV === 'development' ? [] : ['element-plus'],
  }
  ...
})

// entry-server.ts
import { ID_INJECTION_KEY } from 'element-plus'
...
app.provide(ID_INJECTION_KEY, {
  prefix: Math.floor(Math.random() * 10000),
  current: 0,
})
...
