### ISSUE TITLE
cannot read properties of null (reading 'setupContext')

### ISSUE THREAD

**Issue by KahrLu** [nuxt/framework#6763]
### Environment

live

### Reproduction

![image](https://user-images.githubusercontent.com/76502123/185563591-ee1e673b-2b92-4c01-a609-5de1e84e8495.png)

### Describe the bug

when I upgrade the version to rc-8, I can start the app local successfully.
and build also is succeed. but when I start the built files on live, the error is coming out.

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by KahrLu** [comment]
> Would you provide a reproduction? 🙏

[Git repo](https://github.com/KahrLu/nuxt-setupContext-issue)
Hi @danielroe , I use element-plus in nux3.rc-8
normal when I run "yarn dev"
but error comes out when "yarn preview"

**Comment by danielroe** [comment]
Issue to follow is https://github.com/nuxt/framework/issues/4084. You can add `element-plus` to your `build.transpile` (or possibly enable `experimental.externalVue` and all should work well.

https://stackblitz.com/edit/github-1wmsan
