### ISSUE TITLE
webstorm can't detected auto-import-component when updating to nuxt@3.0.0-rc.8

### ISSUE THREAD

**Issue by decba78b** [nuxt/framework#6771]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.21.1`
- Builder:          `vite`

### Reproduction

[this one](https://github.com/decba78b/nuxt3-comp-enable) can detected
[this one](https://github.com/decba78b/nuxt3-comp-disable) can't detected

### Describe the bug

I update `nuxt@3.0.0-rc.4` to `nuxt@3.0.0-rc.8`, Webstorm shows different support.How can I fix it? Webstorm's version is `2022.2`
`rc4`
![rc4](https://user-images.githubusercontent.com/107607249/185579532-ada8a4f5-2be7-40fc-88a0-a35ce5fd4ef3.png)
`rc8`
![rc8](https://user-images.githubusercontent.com/107607249/185579616-d7a7ce2f-befa-4d2c-b79f-a03750fb6adb.png)

**Comment by 516310460** [comment]
This has nothing to do with `nuxt3`, restart your compiler

**Comment by danielroe** [comment]
I believe this has been addressed in https://github.com/nuxt/framework/pull/6580. Would you try the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/)?
