### ISSUE TITLE
Unable to define key on config.globalProperties which has only a getter

### ISSUE THREAD

**Issue by clowNay** [nuxt/framework#6773]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.4.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `modules`, `ui`, `payment`, `runtimeConfig`
- Runtime Modules:  `@spilnu/ui@0.0.1-rc349`, `@spilnu/payment@0.0.1-rc135`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-remeb1-hjgmtg

### Describe the bug

I am unable to set globalProperties in a custom vue plugin, if done through a nuxt plugin using nuxtApp.vueApp.use(CustomVuePlugin).

**Comment by danielroe** [comment]
`nuxtApp.provide` already sets the relevant globalProperties. But it respects anything already set. So you can just move it after your plugin.

https://stackblitz.com/edit/github-remeb1-makp8o
