### ISSUE TITLE
Reflect Metadata wasnt imported into production build

### ISSUE THREAD

**Issue by oleghalin** [nuxt/framework#6782]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modern`, `alias`, `css`, `runtimeConfig`, `httpApi`, `modules`, `buildModules`, `vite`, `build`, `intlify`
- Runtime Modules:  `@pinia/nuxt@0.3.1`, `./modules/uikit`, `./api/module`, `@vueuse/nuxt@8.9.4`
- Build Modules:    `floating-vue/nuxt`
------------------------------

### Reproduction

I was using `reflect-metdata` in global middleware in nuxt-rc6 and it was working perfectly. After upgrade to rc8 i face issue after production build (using `nuxt build`) and `nuxi preview` i see next error: 

```
[nuxt] [request error] [unhandled] [500] Reflect.getMetadata is not a function
```

### Describe the bug

I was using `reflect-metdata` in global middleware in nuxt-rc6 and it was working perfectly. After upgrade to rc8 i face issue after production build (using `nuxt build`) and `nuxi preview` i see next error: 

```
[nuxt] [request error] [unhandled] [500] Reflect.getMetadata is not a function
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/2561.

**Comment by dmitryT93** [comment]
@oleghalin Were you able to solve the problem? I Have the same

**Comment by oleghalin** [comment]
@dmitryT93 yeah, you need to make dummy check for import

```
import * as Reflect from "reflect-metadata";

export default () => {
  if (!Reflect) {
    throw new Error("Reflect wasnt imported");
  }
};

```

**Comment by dmitryT93** [comment]
@oleghalin Thank a lot! And one more question please) Do you have only one entrance reflect-metadata in you app or in different places?
Now I try to use your code in `middleware/reflect.global.ts` but it don't work correctly

**Comment by danielroe** [comment]
Please see instead https://github.com/nuxt/framework/issues/2561#issuecomment-1233047751.
