### ISSUE TITLE
When a cdnURL is supplied in nuxt config, the ErrorComponent disregards this setting

### ISSUE THREAD

**Issue by ffxsam** [nuxt/framework#6790]
### Environment

Nuxt CLI v3.0.0-rc.8
RootDir: /Volumes/SuperData/Sites/reelcrafter/v2-presentation-nuxt3
Nuxt project info: 

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@3.2.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Putting together a repro will be a little tricky with this one since it requires a deploy to a valid URL. I can set one up later and add it to the issue, but I wanted to file this while it was fresh in my mind.

### Describe the bug

I have this in my Nuxt config:

```ts
export default defineNuxtConfig({
  app: {
    ...(process.env.CDN_URL ? { cdnURL: process.env.CDN_URL } : {}),
```

When deployed, the Nuxt app correctly accesses all JS/CSS files from the CDN. However, when the app throws an error, it disregards the CDN setting and tries to use the `error-component` JS & CSS files from the app's server URL.

### Additional context

Might be because this line isn't taking into consideration the `cdnURL` setting?
https://github.com/nuxt/framework/blob/c72093b1f2e6f6f7f2cab7d2e5af8fee3243906a/packages/nuxt/src/app/components/nuxt-root.vue#L12

**Comment by danielroe** [comment]
Would you confirm whether this is also true when you use the edge channel? https://github.com/nuxt/framework/pull/6637 migth well resolve this issue, but I can't confirm without a reproduction.

**Comment by ffxsam** [comment]
@danielroe Yep, edge channel works great! Will this fix be in RC9?

**Comment by danielroe** [comment]
Yes, absolutely. You can also work around it for now with:

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  hooks: {
    'vite:extendConfig' (config, { isClient }) {
      if (isClient) {
        config.base = './'
      }
    }
  }
})
```

**Comment by ffxsam** [comment]
@danielroe Perfect, that'll work great. Thank you!
