### ISSUE TITLE
error when setheader, but server is ok

### ISSUE THREAD

**Issue by TangsWang** [nuxt/framework#6793]
### Environment

rc8

### Reproduction

can't

### Describe the bug

![image](https://user-images.githubusercontent.com/39163972/185726200-a1080b97-d0da-4f59-9c69-280cc8b523d1.png)

**Comment by danielroe** [comment]
It's difficult to say exactly what, but you are perhaps redirecting after the initial HTML response has been made.

Try searching the issues, or providing a reproduction.
