### ISSUE TITLE
Nuxt 3 gives Vite HMR error for page named `app.vue`

### ISSUE THREAD

**Issue by mkalvas** [nuxt/framework#6794]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.17.0`
- Builder:          `vite`
- User Config:      `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/weathered-bush-71xd6q?file=/pages/other.vue

Inside the sandbox router, navigating to `/` or `/other` through the sandbox browser URL bar always works. Navigating to the `/app` route always fails when navigating using the URL bar. Sometimes (I can't tell the rhyme or reason) using `NuxtLink` from a different page will allow the `/app` route to render successfully.

I have not tried this in a production build or different runtime.

### Describe the bug

A page named `app.vue` in the `/pages` folder rendered through `NuxtPage` in the main `app.vue` does not work.

### Additional context

I think if this is an issue, it might be worth seeing if other expected files could cause a similar problem.

I've seen a few different errors here, but they all look similar to the error I pasted in the logs below. I suspect the differences are just surrounding code/env things that I was trying while troubleshooting this.

### Logs

```shell
import { createHotContext as __vite__createHotContext } from "/@vite/client";import.meta.hot = __vite__createHotContext("/app.vue");const _sfc_main = {}
import { resolveComponent as _resolveComponent, openBlock as _openBlock, createBlock as _createBlock } from "/node_modules/.vite/deps/vue.js?v=fc41dfde"

function _sfc_render(_ctx, _cache) {
  const _component_NuxtPage = _resolveComponent("NuxtPage")

  return (_openBlock(), _createBlock(_component_NuxtPage))
}


_sfc_main.__hmrId = "938b83b0"
typeof __VUE_HMR_RUNTIME__ !== 'undefined' && __VUE_HMR_RUNTIME__.createRecord(_sfc_main.__hmrId, _sfc_main)
export const _rerender_only = true
import.meta.hot.accept(mod => {
  if (!mod) return
  const { default: updated, _rerender_only } = mod
  if (_rerender_only) {
    __VUE_HMR_RUNTIME__.rerender(updated.__hmrId, updated.render)
  } else {
    __VUE_HMR_RUNTIME__.reload(updated.__hmrId, updated)
  }
})
import _export_sfc from '/@id/__x00__plugin-vue:export-helper'
export default /*#__PURE__*/_export_sfc(_sfc_main, [['render',_sfc_render],['__file',"/sandbox/app.vue"]])
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9zYW5kYm94L2FwcC52dWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7d0JBQ0UsYUFBWSIsImZpbGUiOiIvc2FuZGJveC9hcHAudnVlIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXNDb250ZW50IjpbIjx0ZW1wbGF0ZT5cbiAgPE51eHRQYWdlIC8+XG48L3RlbXBsYXRlPlxuIl19
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/6626.
