### ISSUE TITLE
Add delay to auto-refresh of use async data

### ISSUE THREAD

**Issue by Luffyyy** [nuxt/framework#6795]
### Describe the feature

So essentially you are able to do the following:

```vue
<template>
    <input v-model="mountain">
    The chosen mountain: {{data}}
</template>

<script setup>
const mountain = ref('aconcagua');

const { data } = await useAsyncData(() => $fetch(`https://api.nuxtjs.dev/mountains/${mountain.value}`), { watch: [mountain] });
</script>
```

However, there's a slight issue with how Nuxt handles this, it will call it in the slightest change for the mountain ref, this is of course not ideal as there is no reason to spam the API before the user finished typing or at least wrote some words and not just a single letter.

The solution is adding a new option named `delay` or `autoRefreshDelay` that would delay the auto refreshing feature by the given milliseconds. So the code above would be: 

```js
const { data } = await useAsyncData(() => $fetch('https://api.nuxtjs.dev/mountains'), { watch: [mountain], delay; 250 });
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by DamianGlowala** [comment]
I suggest the following approach for your use case, which introduces an intermediate, debounced and reactive variable, which is then watched by the `useAsyncData`:

```
<script setup>
const mountain = ref('aconcagua')

const mountainDebounced = refDebounced(mountain, 250)

const { data } = await useAsyncData(
  () => $fetch(`https://api.nuxtjs.dev/mountains/${mountain.value}`), { watch: [mountainDebounced] }
)
</script>
```

`refDebounced` comes from the VueUse library, which is a collection of utility functions based on [Composition API](https://v3.vuejs.org/guide/composition-api-introduction.html). Check out its [installation guide for Nuxt](https://vueuse.org/guide/#nuxt).

**Comment by danielroe** [comment]
Agreed. You can take full manual control as well, by using Vue's native watch function, which is probably what I would use if you need fine-grained control:

```js

const mountain = ref('aconcagua')
const { data, refresh } = await useAsyncData(() => $fetch(`https://api.nuxtjs.dev/mountains/${mountain.value}`))
watch(
  mountain,
  () => { /* handle calling refresh yourself - this function can also be debounced, of course */ },
  { /* vue's watch options */ }
)
