### ISSUE TITLE
How to compile the built results into .js instead of .mjs ?

### ISSUE THREAD

**Issue by sunnywanggit** [nuxt/framework#6802]
### Describe the feature

How to compile the built results into .js instead of .mjs ?

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
This is already implemented by default on the edge channel: https://v3.nuxtjs.org/guide/going-further/edge-channel/

See https://github.com/nuxt/framework/pull/6505

**Comment by sunnywanggit** [comment]
![image](https://user-images.githubusercontent.com/53786183/188097329-c702b700-551d-432a-a7ff-4e75bfe0a0f2.png)
The server code still ends with .mjs

**Comment by sunnywanggit** [comment]
The server code still ends with .mjs
![image](https://user-images.githubusercontent.com/53786183/188097470-b93b038b-b54d-441c-ae08-cb16c7a25c63.png)

**Comment by pi0** [comment]
@sunnywanggit Those assets are not served to the browser. Nitro output is ESM by default because it requires ESM features. Why you would need `.js` extension for them?

**Comment by sunnywanggit** [comment]
@pi0 Mainly for compatibility, Lower versions of node do not support mjs

**Comment by danielroe** [comment]
Nuxt 3 requires the latest LTS node version.
