### ISSUE TITLE
Cannot start the server since RC 8 upgrade from RC 6

### ISSUE THREAD

**Issue by NADESHIKON** [nuxt/framework#6811]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `pnpm@7.7.0`
- Builder:          `vite`
- User Config:      `experimental`, `modules`, `buildModules`, `components`, `ssr`, `css`, `runtimeConfig`, `windicss`, `supabase`, `vueuse`, `link`, `app`
- Runtime Modules:  `nuxt-windicss@2.5.0`, `@nuxtjs/supabase@0.1.23`
- Build Modules:    `@nuxt-modules/compression@0.1.0`
------------------------------

### Reproduction

Upgrade from RC 6 to RC 8

### Describe the bug

Server crashes with 500 error code

### Additional context

It does not happen in RC 6. I tried deleting and reinstalling ``node_modules`` but still no luck.

### Logs

[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')
  at _sfc_main.setup

**Comment by CodeDredd** [comment]
Have the same error. But strangly the error doesnt occur on codesandbox

**Comment by CodeDredd** [comment]
Workaround: @NADESHIKON Using nuxt version `v3.0.0-rc.8` instead of the edge version solves the problem with `dev`. But if you use `build` you probably get a new error which i posted

**Comment by danielroe** [comment]
I would imagine that you are using a Vue 3 library that you will need to add to your `build.transpile` array. Let's track the underlying issue in https://github.com/nuxt/framework/issues/4084.

(Please feel free to post a reproduction if it's not the same issue, and I'll reopen.)
