### ISSUE TITLE
Change default layout programmatically

### ISSUE THREAD

**Issue by ILLuMiNaTe7** [nuxt/framework#6824]
### Describe the feature

In Nuxt 2 there is a very nice method called ``$nuxt.setLayout('layout2')``. Sadly in Nuxt 3, this functionality is nowhere to be found. 

The following method works but you cannot access any variables in this function. So you won't be able to set it dynamically.
```
<script setup>
definePageMeta({
  layout: 'layout2',
});
</script>
```

And this option won't be executed on SSR but only when the page is loaded. The page source won't show anything about the layout.

```
<script setup>
const route = useRoute()
route.meta.layout = "layout2"

definePageMeta({
  layout: false,
});
</script>
```

So I'm going to assume this functionality isn't in the build yet or it isn't in the documentation.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by 516310460** [comment]
Great idea, I'll submit a function of this later to help with changes

**Comment by 516310460** [comment]
https://github.com/nuxt/framework/pull/6826

**Comment by danielroe** [comment]
If you want the layout updated on SSR, you will need to change it before the layout starts rendering, which means it needs to be changed within a plugin or a middleware rather than within a page. (By the time a page renders on server, the layout has already been rendered 'around' it, so it's too late to change it.)

On client, things are reactive so you don't need to worry so much about order.

It might be worth adding a very brief note about this to the documentation, though we do document that setting `route.meta.layout` is the way to update the layout dynamically: https://v3.nuxtjs.org/guide/directory-structure/layouts/#changing-the-layout-dynamically.

**Comment by ILLuMiNaTe7** [comment]
> If you want the layout updated on SSR, you will need to change it before the layout starts rendering, which means it needs to be changed within a plugin or a middleware rather than within a page. (By the time a page renders on server, the layout has already been rendered 'around' it, so it's too late to change it.)

I've tried setting the ``route.meta.layout`` inside a plugin sadly this did not work as it becomes undefined once the page starts loading resulting in a page without a layout.

**Comment by danielroe** [comment]
Yes, sorry for the misleading tip. Middleware is where you'd want to be if you're doing it on server.

And note that you will have to ensure that you are setting layout on client too to ensure the page hydrates. You could use `useState` for that purpose.

See https://stackblitz.com/edit/github-jcup64 for an example.

**Comment by ILLuMiNaTe7** [comment]
> Yes, sorry for the misleading tip. Middleware is where you'd want to be if you're doing it on server.
> 
> And note that you will have to ensure that you are setting layout on client too to ensure the page hydrates. You could use `useState` for that purpose.
> 
> See https://stackblitz.com/edit/github-jcup64 for an example.

This indeed works! Thanks a lot for clearing up the confusion and for providing a solution.

**Comment by danielroe** [comment]
This is now added to docs (and `setPageLayout` utility also added): https://github.com/nuxt/framework/pull/7075.
