### ISSUE TITLE
Failed to install the app using the CLI

### ISSUE THREAD

**Issue by cesarecaoduro** [nuxt/framework#6825]
### Environment

Nuxt CLI v3.0.0-rc.8                                                                                          14:28:05
RootDir: C:/Users/caoduroc/Documents/GitHub/RevitAddinTemplate/src                                            14:28:05
Nuxt project info:                                                                                            14:28:05

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.7.0`
- Nuxt Version:     `0.0.0`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/cesarecaoduro/RevitAddinTemplate/tree/main/src/revit-addin-ui-web

### Describe the bug

Failed to install the app using the CLI

### Additional context

the installation process doesn't conclude successfully

### Logs

```shell
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

C:\Users\caoduroc\AppData\Local\Yarn\Data\global\node_modules\sao\lib\installPackages.js:108
        throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
        ^

SAOError: Failed to install packages in C:\Users\caoduroc\Documents\GitHub\RevitAddinTemplate\src\revit-addin-ui-web
    at ChildProcess.<anonymous> (C:\Users\caoduroc\AppData\Local\Yarn\Data\global\node_modules\sao\lib\installPackages.js:108:15)
    at ChildProcess.emit (node:events:513:28)
    at cp.emit (C:\Users\caoduroc\AppData\Local\Yarn\Data\global\node_modules\sao\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  __sao: true
}

Node.js v18.7.0
error Command failed.
Exit code: 1
Command: C:\Users\caoduroc\AppData\Local\Yarn\bin\create-nuxt-app
Arguments: revit-addin-ui-web
Directory: C:\Users\caoduroc\Documents\GitHub\RevitAddinTemplate\src
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by danielroe** [comment]
I'm not entirely sure what command you're running, but `create-nuxt-app` is for Nuxt 2. For Nuxt 3, follow the instructions here to get going: https://v3.nuxtjs.org/getting-started/quick-start#new-project
