### ISSUE TITLE
Add typescript path for #components meta import

### ISSUE THREAD

**Issue by fieteboerner** [nuxt/framework#6828]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.3.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=app.vue,.nuxt%2Ftsconfig.json

### Describe the bug

By importing Components from the meta import `#components` typescript complains about it because it did not know it at all.

A workaround is to add the following lines to the `nuxt.config.ts`

```ts
typescript: {
            tsConfig: {
                compilerOptions: {
                    paths: {
                        '#components': [
                            '.nuxt/components',
                        ],
                    },
                },
            },
        },
```

So it would be great if nuxt would add this configuration by itself like for `#imports`

Another sidenote:
It would be really great if the `#components` thing would be documented on the website. I only figured out to import from that by searching through issues and PRs.

Thanks a lot!

**Comment by danielroe** [comment]
This is fixed in https://github.com/nuxt/framework/pull/6634.
