### ISSUE TITLE
useCookie() can't keep reactive sometimes

### ISSUE THREAD

**Issue by jwhgzs** [nuxt/framework#6834]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `components`, `runtimeConfig`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```vue
<!-- or you can see: https://www.jwhgzs.com/nuxt_bug_01 -->
<script setup>
    onMounted(() => {
        document.cookie = 'jwhgzs_com='
        
        let a = useCookie('jwhgzs_com')
        let b = useCookie('jwhgzs_com')
        a.value = 'test'
        
        setTimeout(() => 
            console.log(`a.value = '${a.value}'\n` +
                        `b.value = '${b.value}'\n` +
                        `useCookie('jwhgzs_com').value = '${useCookie('jwhgzs_com').value}'`)
        , 1000)
        
        /* output:
                    a.value = 'test'
                    b.value = ''
                    useCookie('jwhgzs_com').value = 'test'
         */
    })
</script>
```

### Describe the bug

`useCookie()` won't be completely reactive when you define more than one refs as you can see.
I think it should run like `useState()`.

### Additional context

It can be in both Composition-API and Options-API.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/2416
