### ISSUE TITLE
useAsyncData is not blocking navigation

### ISSUE THREAD

**Issue by some-user123** [nuxt/framework#6872]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `pnpm@7.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/some-user123/nuxt3-lazy

### Describe the bug

- Run `pnpm install --frozen-lockfile`
- Run `pnpm dev`
- Open `http://localhost:3000`
- Click the link to navigate to `http://localhost:3000/slow`
- Actual: new page is display instantly with `pending: true`, after 2s pending goes to `false` and 42 is displayed.
- Expected: Navigation is blocked until `useAsyncData` returns.

**Comment by danielroe** [comment]
To block navigation, you need to await `useAsyncData`.
