### ISSUE TITLE
inject/provide API broken when building a Netlify preset build

### ISSUE THREAD

**Issue by fabis94** [nuxt/framework#6874]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@3.2.2`
- Builder:          `vite`
- User Config:      `head`, `typescript`, `modules`, `runtimeConfig`, `components`, `hooks`, `build`, `alias`, `vite`
- Runtime Modules:  `~/lib/core/nuxt-modules/storyblok/module.ts`, `@nuxtjs/tailwindcss@5.3.1`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/fabis94/djw3c-frontend-nuxt/pull/2

Only thing you need to set up to run this is create an .env file with the values specified in the PR.

Then do:
`yarn build:netlify` and `yarn start:netlify`

### Describe the bug

My app relies on a [Vue plugin](https://www.npmjs.com/package/@marvr/storyblok-rich-text-vue-renderer) that uses the inject & provide API (through the Composition API) to carry around some data.

The problem that occurs when running Nuxt built using the Netlify preset is that the injected data can't be found - you'll see a "Rich Text Renderer not provided." error message. And from my investigation it appears that it can't be found, because `getCurrentInstance()` of `@vue/runtime-core` returns null - it can't resolve the active Vue instance being set up.

And that seems to happen, because there are 2 versions of `@vue/runtime-core` being used during runtime. One is `./node_modules/@vue/runtime-core` and the other one is `./.netlify/functions-internal/server/node_modules/@vue/runtime-core`. I'm guessing that because of that only one of the @vue/runtime-core versions has access to the active Vue instance and the data that was injected into it.

**Comment by danielroe** [comment]
I believe the issue is probably https://github.com/nuxt/framework/issues/4084. Would you try setting `experimental.externalVue` to true (or adding your plugin to `build.transpile`)?

**Comment by fabis94** [comment]
Ah yep, adding it to build.transpile resolved it. Thanks!
