### ISSUE TITLE
double catch-all doesn't work (both `[...slug].vue` and a `404.vue`)

### ISSUE THREAD

**Issue by talaxasy** [nuxt/framework#6895]
### Environment

- Operating System: Linux
- Node Version: v16.17.0
- Nuxt Version: 3.0.0-rc.8
- Package Manager: npm@8.11.0
- Builder: vite
- User Config: -
- Runtime Modules: -
- Build Modules: -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-87chgu?file=pages/[...slug].vue

### Describe the bug

Catch-all routes don't work like in documentation - https://v3.nuxtjs.org/guide/directory-structure/pages#catch-all-route

**Comment by SebbeJohansson** [comment]
I can confirm that it doesnt work for me either.
https://stackblitz.com/edit/nuxt-starter-w3dcms?file=pages%2F404.vue,pages%2F[...slug].vue

**Comment by danielroe** [comment]
The issue is that `[...slug].vue` _and_ a `404.vue` _both_ produce catchall routes and the 'first' one will handle the request.

I'll look into this and see if there's a way we can improve the DX here, or add something to the docs to make this clearer.

https://v3.nuxtjs.org/guide/directory-structure/pages/#catch-all-route

**Comment by SebbeJohansson** [comment]
@danielroe 
> The issue is that `[...slug].vue` _and_ a `404.vue` _both_ produce catchall routes and the 'first' one will handle the request.

So if I understand it correctly, the only option is to remove the 404.vue and make a custom solution for the 404?

**Comment by jonnyparris** [comment]
In case you were facing this issue while trying to use Nuxt Content like I was then you might also want to use the [#not-found slot](https://content.nuxtjs.org/api/components/content-doc#slots) to render your custom 404 content instead of using 404 as a page.

**Comment by danbohea** [comment]
Just hit this myself. Why is this only priority 3? Catch-all routes are very common in CMS driven Nuxt sites, as are the need for 404 pages.

**Comment by danielroe** [comment]
https://github.com/nuxt/framework/issues/6895#issuecomment-1225452978

The issue isn't that catch-all routes don't work, but that adding _two_ catch-all routes leads to unexpected results.

**Comment by danbohea** [comment]
> The issue isn't that catch-all routes don't work, but that adding two catch-all routes leads to unexpected results.

I get that. That's also my point: having both a catch-all route and a 404 provision (another form of catch-all route) is very common, especially in CMS driven sites.

**Comment by manniL** [comment]
Instead of using a separate route, you could also render a `404.vue` component in your `[...slug].vue` route when it doesn't match anything ☺️

**Comment by danbohea** [comment]
> Instead of using a separate route, you could also render a `404.vue` component in your `[...slug].vue` route when it doesn't match anything relaxed

That's exactly what I've had to do for now.
