### ISSUE TITLE
Docs structure update

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#6904]
(Collabrated with @Atinux @danielroe @clemcode to set new structure)

Notes:
 - Items in (...) indicate old name.
 - I've removed [new] sections to make it a fast structure refactor

----

- **Landing**
- **Getting Started**
    - Intro (Concepts/What is Nuxt)
    - Installation (Getting Started>Quick Start)
    - Views (Features>Views)
    - Assets & Styles (features> assets)
    - SEO & Meta (Features>Head)
    - Data Fetching (Features>Data Fetching)
    - State Management  (Features State Management)
    - Error Handling (Features>Error Handling)
    - Testing (Features/Testing)
    - Deployment (Deploy/* merged)
    - Upgrade guide
        - Upgrade from Nuxt 2 (Getting Started>Migration Guide)
        - Edge Channel
- **Guide**
    - Key Concepts
        - Core Architecture (Advanced > How Nuxt Works + Life Cycle Hooks)
        - Auto Imports (Concepts > Auto Imports)
        - Development in Nuxt (Concepts/Vue.js Development)
        - Modules (Features/Modules)
        - Rendering Modes (Concepts > Rendering Modes)
        - ES Modules (Advanced > ES Modules)
        - **Server** (Features/Server Routes)
    - Directory structure
        - [auto-loaded files and dirs]
    - Module Guide
        - Get started (module author guide)
        - Nuxt Kit
- **API Reference**
    - Composables
    - Components
    - Utils
    - **Advanced**
        - **Lifecycle Hooks**
        - **Kit utils**
    - Commands
    - Configuration
- **Examples**
    - [categories]
- **Community**
    - **Getting help**
    - **Reporting bugs**
    - **Contribution**
    - **Roadmap**

**Comment by pi0** [comment]
```
/features/app-config (API reference > Configuration)
/features/runtime-config (API reference > Configuration)
/features/teleports (API Reference > Components)
/going-further/nuxt-app (API reference > Configuration)
```

There are not API references. Please keep them somewhere within Guide in Key Concepts or Going Furthor. We need to discuss more for placement and _content_ refactors.

**Comment by AndreyYolkin** [comment]
Idk should I create separate issue for that, but link inside https://v3.nuxtjs.org/community/framework-contribution/ page is broken. 
![image](https://user-images.githubusercontent.com/11289484/187201945-491e21b9-6f74-4746-a983-c9ffd631e4bc.png)
We need to replace [it](https://v3.nuxtjs.org/community/framework-contribution/contribution) with https://v3.nuxtjs.org/community/contribution/

If needed I can create issue and PR for this, but might be it will be solved after resolving this issue

**Comment by pi0** [comment]
Thanks for notice @AndreyYolkin. Feel free to directly open PR for quick docs.
