### ISSUE TITLE
External redirection improvements

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#6906]
It is possible (currently in edge) now to use `navigateTo` for external URL redirections

- [x] Base PR #5022 by @manniL 
- [x] Avoid async logic going on during redirection (https://github.com/nuxt/framework/pull/5022#discussion_r953972549) 
- [x] Document `navigateTo(URL, { external: true })` (https://github.com/nuxt/framework/pull/7188)

**Comment by danielroe** [comment]
> One last thing to ensure: In nuxt 2, we had this problem with external navigations that during navigation, rest of logic goes on. And solution was a custom made error because it was sync. I think we could do something like a never resolving promise that avoids this. (will make a reproduction and implement in later PR btw need more testing)

@pi0 Would you explain a bit more about this? Does https://github.com/nuxt/framework/pull/8821 resolve it?
