### ISSUE TITLE
cdnURL not respected for composables

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/framework#6912]
### Environment

```
RootDir: /Users/reinierkaper/projects/remx/apps/nuxt-app                                        15:53:03
Nuxt project info:                                                                              15:53:03

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `app`, `css`, `build`, `dev`, `modules`, `nitro`, `runtimeConfig`, `typescript`, `vite`
- Runtime Modules:  `nuxt-graphql-client@0.1.12`
- Build Modules:    `-`
------------------------------
```

### Reproduction

See description (I think that should be enough), but I can attempt a repro if required

### Describe the bug

After building a Nuxt3 project (`aws-lambda` in my case), everything works, except composables, which seem to be resolved against the server's URL, instead of the provided `cdnURL`.

Screenshot of the request:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/1668207/186510985-0f34cd50-2aee-47bb-a49a-769e28a45f6d.png">

Request URL (uses the server, instead of the CDN): `https://g9tki5l42a.execute-api.us-east-1.amazonaws.com/_nuxt/RemxSubscribe.vue_vue_type_script_setup_true_lang.e66fb1e7.mjs`

Expected URL (provided in nuxt config and working for all other assets): `https://d1syj3gsfc4cfd.cloudfront.net/_nuxt/RemxSubscribe.vue_vue_type_script_setup_true_lang.e66fb1e7.mjs`

**Comment by danielroe** [comment]
I believe this is the same issue as https://github.com/nuxt/framework/pull/6637. Would you [try with the edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) to confirm whether it is resolved?

**Comment by TheDutchCoder** [comment]
> I believe this is the same issue as #6637. Would you [try with the edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) to confirm whether it is resolved?

I'll take a look into the edge channel tomorrow and will report back!

**Comment by TheDutchCoder** [comment]
@danielroe unfortunately I can't test this on the edge channel.

Locally you can't run `preview` and the generated code throws a 500 on aws-lambda with no traces in the log, so I assume something internally goes wrong.

dev works fine, but there's no way for me to test if the server works properly

**Comment by TheDutchCoder** [comment]
@danielroe Yes on the edge channel this seems to be fixed!
