### ISSUE TITLE
useAsyncData's data._rawValue is null

### ISSUE THREAD

**Issue by HochinChan** [nuxt/framework#6921]
### Environment

3.0.0-rc.8

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qfirv9?file=app.vue

### Describe the bug

When I send the first request using useAsyncData, and then send the second request when the first request is not finished, the data._rawValue of the first request will be null

**Comment by HochinChan** [comment]
> What makes you say this is a bug? `._rawValue` is an internal property of a ref. You also should not be programmatically calling `useAsyncData` outside of the setup function itself.
> 
> Would you update your reproduction? 🙏
> 
> Note that a recently-merged PR - #7055 - has changed the behaviour slightly and it would be worth updating your reproduction using the edge channel.

Yes, I am using `useAsyncData` inside setup.
Open this reproduction https://stackblitz.com/edit/nuxt-starter-qfirv9?file=app.vue, wait a few seconds after the page appears and you will see the error report in the console.
![image](https://user-images.githubusercontent.com/65072526/187575310-4e44785b-4dd4-4016-b6ec-e65c02d744a3.png)

**Comment by danielroe** [comment]
Ah, took me a moment to see it. The issue here is that on the _first load on the client_ (ie. before hydration) we cannot await fetching async data (or there will be a hydration error).

So we instead will fetch the data immediately after mounting. You will need to check if `pending.value` is truthy.

**Comment by HochinChan** [comment]
> Ah, took me a moment to see it. The issue here is that on the _first load on the client_ (ie. before hydration) we cannot await fetching async data (or there will be a hydration error).
> 
> So we instead will fetch the data immediately after mounting. You will need to check if `pending.value` is truthy.

Sorry, I don't quite understand what you mean.
Do you mean I can't `await` a `useAsyncData` on the client?
