### ISSUE TITLE
post request error

### ISSUE THREAD

**Issue by caohenghu** [nuxt/framework#6922]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@6.14.16`
- Builder:          `vite`
- User Config:      `srcDir`, `meta`, `postcss`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-i2nngy

### Describe the bug

one post request in the browser, or two post request in the server, response error. but only in dev mode, build mode is ok.

![image](https://user-images.githubusercontent.com/7547646/186600411-f8c9bc07-759d-4125-9717-719994bf7967.png)

### Additional context

#6869

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by danielroe** [comment]
This is an issue with your backend API, triggered by the fact that you are proxying all headers through to it. Just delete the following and you should be good to go. (But please do consider using an allowlist rather than proxying everything through.)

```js
    delete headers.origin
    delete headers.referer
```

**Comment by caohenghu** [comment]
It's work, thanks.
