### ISSUE TITLE
Different layout handovers cause setup to execute twice

### ISSUE THREAD

**Issue by amihhs** [nuxt/framework#6934]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.8-27689472.403e0e6`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[https://stackblitz.com/edit/github-48hdxh?file=app.vue](https://stackblitz.com/edit/github-48hdxh?file=app.vue)

### Describe the bug

Different layout handovers cause setup to execute twice
![image](https://user-images.githubusercontent.com/59364234/186642715-d77a9005-f6cf-4366-a2f5-8b87bf69fe30.png)

Maybe relevant：
[#6318](https://github.com/nuxt/framework/issues/6318)

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/6592
