### ISSUE TITLE
Typescript/typechecking failing on recursive components

### ISSUE THREAD

**Issue by some-user123** [nuxt/framework#6947]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-md1jod?file=components%2FRecursiveComponent.vue

### Describe the bug

A component that uses itself causes `error TS7022: 'default' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.` when typechecking.

It sometimes works when incrementally writing the SFC and generating types in the background. However, as soon as you delete `.nuxt` and run `nuxi prepare`, typechecking will fail.

**Comment by danielroe** [comment]
This may be worth raising upstream with https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc.

**Comment by some-user123** [comment]
Seems like somebody did that already ;-) https://github.com/johnsoncodehk/volar/issues/1708

It's solved in the latest version of `vue-tsc`.
