### ISSUE TITLE
When building buildAssetsDir is duplicated /_nuxt/_nuxt/

### ISSUE THREAD

**Issue by mi-wa-ro** [nuxt/framework#6956]
### Environment

Nuxt CLI v3.0.0-rc.8                                                                                                                                                                                            17:04:46

RootDir: /app                                                                                                                                                                                                   17:04:52
Nuxt project info:                                                                                                                                                                                              17:04:52

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.20.0`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `publicRuntimeConfig`, `srcDir`, `css`, `modules`, `app`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`, `@pinia/nuxt@0.4.1`
- Build Modules:    `-`
------------------------------

### Reproduction

Difficult to provide as we're experimenting trying to find a solution, so our env might change.

### Describe the bug

When we attempt to build the site, the buildAssetsDir is duplicated.
eg.
Files that should be in .output/public/_nuxt are instead in 
output/public/_nuxt/_nuxt

It then attempts to load the files in _nuxt/ so returns 404s. Any attempt to manually copy the files from /_nuxt/_nuxt/ into _nuxt/ has no affect.

We have tried the following in nuxt.config.ts 

- Changing public path, but did nothing

build: {
  publicPath: '/_another/'
}

- changing buildAssetsDir with no affect

build: {
  buildAssetsDir: '/_another/'
}

- changing buildAssetsDir in app
build: {
  buildAssetsDir: '/_another/'
}

that one worked, but created the same problem on files now being in .output/public/_another/_another/

**Comment by Aareksio** [comment]
Could you please update to latest rc and see if the error persists? You are also using yarn@1.x, a lot of factors to consider. Unless you manage to provide minimal reproduction ([create here](https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz)) or someone from the team correctly guesses what's the issue, it may be very hard to debug and fix.

**Comment by danielroe** [comment]
Almost certainly you have rc4 but your `@nuxt/vite-builder` dep is rc8.

I would recommend updating to rc8 all the way, or using resolutions/overrides to pin your dependencies.

I'm also happy to have a look if you provide a reproduction. Let me know and I'll reopen this issue.

**Comment by xiaojieajie** [comment]
I also met this problem, do not know how to solve it

**Comment by danielroe** [comment]
See my comment above.

**Comment by xiaojieajie** [comment]
Mine has always been
<img width="288" alt="image" src="https://user-images.githubusercontent.com/39750199/188123762-785cd797-7aae-43b2-919f-91bb2219501a.png">
But my reliance is on the RC-6
I don't know using resolutions/overrides to pin your dependencies. What is the meaning of
thx。

**Comment by danielroe** [comment]
You are using Nuxi rc6 but your vite-builder version is rc8. See https://github.com/nuxt/framework/discussions/6554 for how to pin.

**Comment by xiaojieajie** [comment]
Thank you so much
