### ISSUE TITLE
use two await fetch in the server, Error: nuxt instance unavailable

### ISSUE THREAD

**Issue by caohenghu** [nuxt/framework#6963]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@6.14.16`
- Builder:          `vite`
- User Config:      `srcDir`, `meta`, `postcss`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-arpgcj

### Describe the bug

when I use two await fetch in the server, will throw Error: nuxt instance unavailable

<img width="767" alt="image" src="https://user-images.githubusercontent.com/7547646/186831872-6f3a4f8f-aee0-44b9-9fd0-67d7b0cba213.png">

**Comment by Aareksio** [comment]
You are not awaiting `onInit` call, which means the code after await (or rather first async operation) executes outside of nuxt context.

**Comment by caohenghu** [comment]
> You are not awaiting `onInit` call, which means the code after first async operation executes outside of nuxt context.

But if I use `await onInit()`, it is the same error on browser. And the server log is: [Vue warn]: Unhandled error during execution of setup function.

**Comment by caohenghu** [comment]
who can help me

**Comment by danielroe** [comment]
Please see https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529. You should not await async composables within a function but directly within `<script setup>`, nuxt plugins or nuxt route middleware.

**Comment by caohenghu** [comment]
@danielroe I still don't understand, can you show me the code with my reproduction, thank you very much!

**Comment by danielroe** [comment]
https://stackblitz.com/edit/nuxt-starter-tjbh9r.

**Comment by caohenghu** [comment]
![image](https://user-images.githubusercontent.com/7547646/187878453-0bf2f4e4-e4ef-43aa-81fd-246cc36920b2.png)

I change you code, it has the same problem.
@danielroe

**Comment by danielroe** [comment]
As I explained, you will lose the Nuxt instance if you await a composable in a function rather than directly in `<script setup>`, a nuxt plugin or route middleware. I realise it is running at the same 'time' but it makes a difference, which https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529 should explain a little more.

**Comment by caohenghu** [comment]
e..., I understand now, but this usage is too popular.

**Comment by caohenghu** [comment]
directly in <script setup>, a nuxt plugin or route middleware, it seems not the best practice, I have some common params, where should I deal with?
@danielroe
