### ISSUE TITLE
Automatically import components, transform.exclude has no effect

### ISSUE THREAD

**Issue by amihhs** [nuxt/framework#6964]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `components`, `extensions`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[https://stackblitz.com/edit/github-48hdxh?file=nuxt.config.ts](https://stackblitz.com/edit/github-48hdxh?file=nuxt.config.ts)

### Describe the bug

component
 |- comp.vue
 |- comp.ts
Made a few settings. I want it to ignore * .ts
```js
components: {
    dirs: ['components'],
    transform: {
      exclude: [/(\.ts)$/],
    },
},
extensions: ['.jsx', '.tsx', '.vue']
```
It doesn't seem to work. I don't know if there's something wrong with my configuration.
```
 WARN  Two component files resolving to the same name Header:                                    14:44:12

 - /home/projects/github-48hdxh/components/header/index.vue
 - /home/projects/github-48hdxh/components/header/index.ts
```

**Comment by 516310460** [comment]
https://github.com/nuxt/framework/issues/6920

**Comment by 516310460** [comment]
PR: https://github.com/nuxt/framework/pull/6930

**Comment by danielroe** [comment]
The `transform.exclude` feature allows disabling what the component is auto-imported _into_, not what is considered a component.

Here's how you would ignore `.ts` files in the components directory: https://stackblitz.com/edit/github-48hdxh-lzpnb7
