### ISSUE TITLE
Pages are created 2 times when navigating between pages with different layouts

### ISSUE THREAD

**Issue by roamiiing** [nuxt/framework#6965]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

https://stackblitz.com/edit/github-55pbvb?file=pages/sample.vue

Logs in the console:
```
Creating default layout
Creating /
Mounted /
Time to navigate to /sample
Creating /sample
Mounted /sample
Creating sample layout
Creating /sample
Mounted /sample
```

### Describe the bug

A page is being created and mounted 2 times when navigating with `navigateTo` for the first time to a page with a different layout. I think this is somehow related to #6704 because when this bug happens I also do not get `data` or `error` from `useAsyncData`

**Comment by amihhs** [comment]
let's track in https://github.com/nuxt/framework/issues/6592
