### ISSUE TITLE
yarn build hang with no error!!!

### ISSUE THREAD

**Issue by TangsWang** [nuxt/framework#6993]
### Environment

rc.8

### Reproduction

can't, but my proj is down, aslo on vercel.   Building Server forever....

### Describe the bug

D:\NodeJsWS\my-nuxt3-app>yarn build
yarn run v1.22.18
$ nuxt build
Nuxt CLI v3.0.0-rc.8                                                                                                                           20:55:25

 WARN  Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification                                  20:55:44  

 WARN                                                                                                                                          20:55:53  
(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

i Client built in 16936ms                                                                                                                      20:55:53
i Building server...                                                                                                                           20:55:53
√ Server built in 5497ms                                                                                                                       20:55:58
√ Generated public .output/public                                                                                                        nitro 20:56:00
start Building server...

**Comment by pi0** [comment]
Hi @TangsWang. Is it possible to make a reproduction of your issue? 🙏🏼  I an understand you are on windows but without reproduction it is hard to tell what's wrong.

**Comment by TangsWang** [comment]
@pi0 thanks a lot, i am trying,  i found the file who let it down.  but i do not know why...

![图片](https://user-images.githubusercontent.com/39163972/187031392-4f772ca3-025c-4ad1-85cc-84e64c138e33.png)

**Comment by TangsWang** [comment]
@pi0  i found where is wrong.

<client-only>
      <m-modal-win v-model:trigger="modal_trigger">
        <component :is="modal_com" :data="modal_com_data" />
      </m-modal-win>
  </client-only>

m-modal-win use <teleport> as root.

when i drop this,  yarn build is ok.

**Comment by TangsWang** [comment]
@pi0  i found the reason, thanks.

<teleport> as root in component will cause that.

**Comment by 516310460** [comment]
Please provide a https://stackblitz.com/
