### ISSUE TITLE
Error details LOGs not shows up on PROD

### ISSUE THREAD

**Issue by anime777** [nuxt/framework#7001]
### Environment

Nuxt project info:                                                                                                                                                                                                    18:13:54

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.9.5`
- Builder:          `vite`
- User Config:      `meta`, `runtimeConfig`, `css`, `build`, `typescript`, `modules`, `components`, `vueuse`, `unocss`
- Runtime Modules:  `@vueuse/nuxt@8.4.2`, `@unocss/nuxt@0.33.2`, `@pinia/nuxt@0.1.9`, `@nuxtjs/color-mode@3.1.4`
- Build Modules:    `-`
------------------------

### Reproduction

yarn install
yarn build

**node .output/server/index.mjs** 

### Describe the bug

CMD   `node .output/server/index.mjs`

Error details LOGs looks good on local  but the details did not show up on PROD

**Page error logs  on local**
```
500
request to http://localhost:8080/fo/list?pageNum=1&pageSize=10 failed, reason: connect ECONNREFUSED 127.0.0.1:8080 ()

```
**Page error logs  on Prod(remote server with the same .output folder files  )**
```
500
fetch failed ()
```

### Logs

```shell
####PROD
[nuxt] [request error] fetch failed ()
  at async $fetchRaw2 (./.output/server/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
FetchError: fetch failed ()
    at async $fetchRaw2 (file:///app/prod/bin/cms-admin-ssr/.output/server/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
[Vue warn]: Component  is missing template or render function.
[nuxt] [request error] fetch failed ()

####local


[Vue warn]: Component  is missing template or render function.
[nuxt] [request error] request to http://localhost:8080/fo/list?pageNum=1&pageSize=10 failed, reason: connect ECONNREFUSED 127.0.0.1:8080 ()
  at async $fetchRaw2 (./.output/server/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
FetchError: request to http://localhost:8080/fo/list?pageNum=1&pageSize=10 failed, reason: connect ECONNREFUSED 127.0.0.1:8080 ()
    at async $fetchRaw2 (file:///home/root7/Desktop/project/git/cms-web-ssr/.output/server/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
[Vue warn]: Component  is missing template or render function.
[nuxt] [request error] request to http://localhost:8080/fo/list?pageNum=1&pageSize=10 failed, reason: connect ECONNREFUSED 127.0.0.1:8080 ()
  at async $fetchRaw2 (./.output/server/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
```

**Comment by 516310460** [comment]
Would you please provide a reproduction?

**Comment by MikkoKarvonen** [comment]
Have you tried this [https://www.storyblok.com/faq/setting-up-https-on-localhost-in-nuxt-3](https://www.storyblok.com/faq/setting-up-https-on-localhost-in-nuxt-3)?
