### ISSUE TITLE
"#build/app.config.mjs" is not defined in package imports

### ISSUE THREAD

**Issue by m0ksem** [nuxt/framework#7002]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.8-27692155.9db2229`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `vuestic`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- Create new nuxt app `npx nuxi init nuxt-app`
- Use latest nuxt3  `"nuxt": "npm:nuxt3@latest",`
- Change app.vue to:
  ```vue
  <template>
    <div>
    </div>
  </template>
  
  <script setup lang="ts">
  import { defineNuxtPlugin } from 'nuxt/app'
  
  console.log(defineNuxtPlugin)
  </script>
  ```
  We need any import from nuxt/app to get `nuxt` in server's node_modules.

- Build and preview app.  `nr build && nr preview`

---
We faced this issue in `@vuestic/nuxt` module which use `defineNuxtPlugin`. (see https://github.com/epicmaxco/vuestic-ui/issues/2315)

### Describe the bug

In server node_modules `nuxt`'s `config.js` imports `#build/app.config.mjs` which is not defined in package.json imports.

```ts
import __appConfig from "#build/app.config.mjs";
```

### Logs

```shell
TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#build/app.config.mjs" is not defined in package /home/m0ksem/projects/temp/nuxt-app/.output/server/node_modules/nuxt/package.json imported from /home/m0ksem/projects/temp/nuxt-app/.output/server/node_modules/nuxt/dist/app/config.mjs
```

**Comment by lolbyaka** [comment]
Faced with the same issue today. Try to replace 'nuxt/app' to '#imports' and everything should work great.

**Comment by 516310460** [comment]
The correct usage should be:
```ts
<script setup lang="ts">
  import { defineNuxtPlugin } from '#app'
  console.log(defineNuxtPlugin)
</script>
``

**Comment by gspgsp** [comment]
> 

this solved my problem ,just replace 'nuxt/app' to '#imports'

**Comment by gspgsp** [comment]
> Faced with the same issue today. Try to replace 'nuxt/app' to '#imports' and everything should work great.

this solved my problem, greet

**Comment by gspgsp** [comment]
> Faced with the same issue today. Try to replace 'nuxt/app' to '#imports' and everything should work great.

this solved my problem,  in my utils/utils.js file:
import {useCookie} from "nuxt/app";

export default {
 ...
 ...
}

just replace 'nuxt/app' to '#imports',  then run npx nuxi dev , no error message.
