### ISSUE TITLE
options api support for data fetching

### ISSUE THREAD

**Issue by debasispanigrahi** [nuxt/framework#7013]
### Describe the feature

In Nuxt 2, There are provision of app.html for defining layout of complete web page. But it is not present in nuxt 3.  Additionally vue 3 has both option api and composition api feature. But Nuxt 3 does not give any features of fetch and asyncData  using in option api. Developers are binded to use composition api even if they are proficient in option api. Can u give any guidance how to implement these features. 

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by MorevM** [comment]
Related: [Issue about app.html](https://github.com/nuxt/framework/issues/5565)

**Comment by debasispanigrahi** [comment]
@MorevM any idea regarding how to add features of fetch, asyncData in option api

**Comment by debasispanigrahi** [comment]
@danielroe it is possible to add fetch for option api like asyncData

**Comment by vedmant** [comment]
Also having problems with Nuxt 3 due to lack of options API documentation and proper support for fetch() and asyncData()
