### ISSUE TITLE
client manifest is included in `public/`

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#7020]
I could not run PWA on production mode because PWA manifest get replaced by Nuxt manifest. 
is there any way to change the name of Nuxt manifest?

_Originally posted by @mjzarrin in https://github.com/nuxt/framework/discussions/7017_

**Comment by pi0** [comment]
Can you please elaborate more on task before converting to issue and self-assign?

**Comment by danielroe** [comment]
Didn't see this until PR raised - more info there:  #7020.
