### ISSUE TITLE
Hydration children mismatch with simple `input` of type `email`

### ISSUE THREAD

**Issue by larbish** [nuxt/framework#7023]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-fpnxxl?file=app.vue,pages%2Findex.vue

### Describe the bug

An hydratation warn appears when using an `input` of type `text` or `email` inside `index.vue` file. 

### Additional context

It does not occur if moving code in `app.vue` without `pages` folder.

It does not occur with type `date`.

### Logs

```shell
vue.js?v=cd7cae4a:1268 [Vue warn]: Hydration children mismatch in <form>: server rendered element contains more child nodes than client vdom. 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/" routeProps= {Component: {…}, route: {…}} pageKey="/" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="page" mode="out-in" > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=1 > 
  at <NuxtRoot>
```

**Comment by danielroe** [comment]
I cannot reproduce this in the stackblitz. What browser are you using? Can you give any more information? Do you experience the same thing with [pure Vue SSR](https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main?file=src%2FApp.vue&terminal=dev)?

**Comment by larbish** [comment]
I'm using Chrome Chrome 104.0.5112.101 (up to date)

Yes I have the same issue with https://stackblitz.com/edit/github-pshyzc?file=src%2Fpages%2FHome.vue&terminal=dev

I can see the warn by opening the stackblitz in a new tab and checking the console:
<img width="1664" alt="Screenshot 2022-08-29 at 13 45 17" src="https://user-images.githubusercontent.com/7290030/187193928-8efb7cdd-e0db-4572-b5d8-bd0a9ee9ea5f.png">

**Comment by pi0** [comment]
Could it be possible because of a chrome extension trying to modify the DOM at same time of hydration? (Can you reproduce in incognito with all exts disabled?)

**Comment by pi0** [comment]
(This is off topic but just to mention: CDN providers such as cloudflare often do some notifications too like obfusticating email causing similar hydration)

**Comment by larbish** [comment]
Indeed !  I found the guilty, it was caused by a Chrome extension (NordPass).
