### ISSUE TITLE
default color of the file tree

### ISSUE THREAD

**Issue by caohenghu** [nuxt/framework#7052]
### Describe the feature

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/7547646/187399798-84e1da00-414c-49c5-93dd-8c22655845f3.png">
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/7547646/187399934-ee993ebc-161c-4cb7-ac2d-c7a32ce42dbe.png">

Could change the default color of the file tree, when I npm run build, I can't see it. Only if I select all, or change theme of iTerm2, then see it.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
I think this is an issue with your iTerm2 theme, not an issue with Nuxt/Nitro.

**Comment by caohenghu** [comment]
@danielroe why not use color as other log info, like white, blue, grey...

**Comment by danielroe** [comment]
It is using gray: https://github.com/unjs/nitropack/blob/45f48a35d693316463f05ab4887b54b24dae88d7/src/utils/tree.ts#L44
