### ISSUE TITLE
Feat : Router Alias capability extended (Dynamically)

### ISSUE THREAD

**Issue by kevcomparadise** [nuxt/framework#7059]
### Describe the feature

Hi, 

I'm trying to migrate Nuxt2 to Nuxt3, we had implemented alias management by API which is then implemented in extendRoutes (n2).

In Nuxt3 the aliases are to be put directly in the page files with `definePageMeta` but this restricts the use.

Method to Reproduce :

- Use the `page:extend` hook (in nuxt.config) or use Module like [Doc](https://v3.nuxtjs.org/examples/server/routes)
- Implement aliases dynamically

```js
export default defineNuxtModule({
    setup () {
        extendPages(async (routes) => {
                routes.forEach((route) => {
                    routes.alias = ['/a', '/b']
                });
            })
        })
    }
})
```
- Today this way doesn't work.

This is due to : `packages/nuxt/src/pages/utils.ts` (alias property)

```js
export function normalizeRoutes (routes: NuxtPage[], metaImports: Set<string> = new Set()): { imports: Set<string>, routes: string } {
  return {
    imports: metaImports,
    routes: genArrayFromRaw(routes.map((route) => {
      const file = normalize(route.file)
      const metaImportName = genSafeVariableName(file) + 'Meta'
      metaImports.add(genImport(`${file}?macro=true`, [{ name: 'meta', as: metaImportName }]))
      return {
        ...Object.fromEntries(Object.entries(route).map(([key, value]) => [key, JSON.stringify(value)])),
        children: route.children ? normalizeRoutes(route.children, metaImports).routes : [],
        meta: route.meta ? `{...(${metaImportName} || {}), ...${JSON.stringify(route.meta)}}` : metaImportName,
        alias: `${metaImportName}?.alias || []`,
        component: genDynamicImport(file, { interopDefault: true })
      }
    }))
  }
}
```

I have already made the fix on my project

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
I think it makes sense to allow customisation of a route `alias` via `pages:extend` just as we do for `meta`.

**Comment by 516310460** [comment]
Will the use of TSX be affected
E.g 
const a = ()=><div>this is a a.tsx</div>
a.displayName=‘b’
export default a

**Comment by kevcomparadise** [comment]
> Will the use of TSX be affected
> E.g 
> 
> ```ts
> const a = ()=><div>this is a a.tsx</div>
> a.displayName=‘b’
> export default a
> ```

I don't understand, is this a problem?
