### ISSUE TITLE
Tailwind CSS classes not imported to CSS without nuxt restart

### ISSUE THREAD

**Issue by bf** [nuxt/framework#7062]
### Environment

Nuxt CLI v3.0.0-rc.8                                                                                                                                                                 
Nuxt project info:                      

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `build`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```
<template>
 <div class="">test</div>
</template>
```

then change it to 

```
<template>
 <div class="p-5">test</div>
</template>
```

and save your file.

### Describe the bug

 Nuxt server will reload but the CSS for p-5 is not shown in the browser.

### Logs

```shell
✔ Vite server built in 500ms
```

**Comment by bf** [comment]
package.json:

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "nuxt": "^3.0.0-rc.8"
  },
  "dependencies": {
    "@headlessui/vue": "^1.6.7",
    "@heroicons/vue": "^1.0.6",
    "autoprefixer": "^10.4.7",
    "bcryptjs": "^2.4.3",
    "cookie-signature": "^1.2.0",
    "pg": "^8.7.3",
    "postcss": "^8.4.14",
    "tailwindcss": "^3.1.6",
    "vue3-dropzone": "^2.0.1"
  }
}
```

```
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  build: {
    transpile: ['@heroicons/vue'],
    postcss: {
      postcssOptions: {
        plugins: {
          tailwindcss: {},
          autoprefixer: {},
        },
      },
    },
  },
  runtimeConfig: {
    cookieName: '__session',
    cookieSecret:'foobar'
  },
});
```

**Comment by bf** [comment]
I sometimes get this error, but I'm not sure if it is related:

```
 ✔ Vite server built in 472ms
 [nitro] [dev] [uncaughtException] Error: listen EADDRINUSE: address already in use /tmp/nitro/worker-51-2.sock
     at Server.setupListenHandle [as _listen2] (node:net:1468:21)
     at listenInCluster (node:net:1533:12)
     at Server.listen (node:net:1632:5)
     at file:///home/node/app/.nuxt/dev/index.mjs:559:8
     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
     at async Promise.all (index 0)
     at async ESMLoader.import (node:internal/modules/esm/loader:528:24)
     at async loadESM (node:internal/process/esm_loader:91:5)
     at async handleMainPromise (node:internal/modules/run_main:65:12) {
   code: 'EADDRINUSE',
   errno: -98,
   syscall: 'listen',
   address: '/tmp/nitro/worker-51-2.sock',
   port: -1

```

**Comment by bf** [comment]
My nuxt is running within docker container:

Dockerfile
```
FROM node:18-buster-slim

RUN apt-get update && apt-get install -y git graphicsmagick

ENV HOST 0.0.0.0
EXPOSE 3000

WORKDIR /home/node/app
RUN chown -R node:node /home/node/app

USER node
CMD yarn install && yarn dev -o

```

**Comment by Joaojack** [comment]
If i were you I would try to uninstall tailwindcss  and install `@nuxtjs/tailwindcss`  in devDependencies. 
Works flawlessly with Nuxt 3. https://tailwindcss.nuxtjs.org/
Config is good as it is (if you had a tailwind.config.js you can keep it too).

**Comment by bf** [comment]
I replaced `tailwindcss` with `@nuxtjs/tailwindcss` and it did not resolve the issue. Every time I change CSS class, e.g. from `border-gray-300` to `border-gray-200`, the new CSS is not loaded. If I restart nuxt server, it is there.

After saving the file, every time I see `✔ Vite server built in 352ms` in the console, so it seems to be rebuilding the server.

**Comment by bf** [comment]
Okay, I was missing the "buildModules" option in my nuxt config.

New nuxt config which works:

```
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  build: {
    transpile: ['@heroicons/vue'],
    postcss: {
      postcssOptions: {
        plugins: {
          tailwindcss: {},
          autoprefixer: {},
        },
      },
    },
  },
  buildModules: ['@nuxtjs/tailwindcss'],
  runtimeConfig: {
    cookieName: '__session',
    cookieSecret:'foo'
  },
});
```

@Joaojack thanks for your kind help!

**Comment by karimh777** [comment]
This issue still exists with nuxt ` v3.0.0-rc.8` not importing Tailwindcss classes
