### ISSUE TITLE
Hot reload is not working across a network in development

### ISSUE THREAD

**Issue by OyewoleOyedeji** [nuxt/framework#7068]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `app`, `buildModules`, `googleFonts`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`
- Build Modules:    `@nuxtjs/google-fonts@3.0.0-0`
------------------------------

### Reproduction

[Link to project](https://github.com/OyewoleOyedeji/discord-profiler)

### Describe the bug

Hot reload doesn't work across a network. I allowed the port `3000` which my app was running on in my firewall and can access the project normally. But when I make changes to the code, I have to manually reload the page.

### Additional context

The tool I used to allow the port `3000` is `ufw` which comes by default on the Linux distro I'm using

**Comment by danielroe** [comment]
The port used for HMR by vite is 24678 by default and needs to be allowed as well as 3000. You can also find some discussions in this repository about people who are proxying this port - worth taking a look.

**Comment by OyewoleOyedeji** [comment]
Thanks @danielroe, please where can I find the discussion for proxying the port
