### ISSUE TITLE
[vercel] `too many redirects` when URL parameter contains `+` (encoded space)

### ISSUE THREAD

**Issue by henningko** [nuxt/framework#7086]
### Environment

```
------------------------------
- Operating System: `Darwin/macOS 12.5.1`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/supabase@0.1.23`
- Build Modules:    `-`
------------------------------
```

### Reproduction

Find Stackblitz (default minimun starter template with a single page) here:

https://stackblitz.com/edit/github-gmakpg

Deployed using Vercel via Github, all default settings:
https://nuxt3-min.vercel.app/

Fails when queried with the following parameters:
https://nuxt3-min.vercel.app/?scope=https://www.googleapis.com/auth/calendar.events.readonly+https://www.googleapis.com/auth/calendar.readonly
and
https://nuxt3-min.vercel.app/?scope=abc+def

### Describe the bug

When deploying `Nuxt@3.0.0-rc.8` to Vercel and using pages/routes, it is not possible to access URLs that contain a space encoded as a `+` in the URL parameters, such as:
`?query=abc+def`

This results in a redirect error: `ERR_TOO_MANY_REDIRECTS`.

This could, of course, also be a bug on Vercel's side (no error is logged).

### Additional context

I have encountered this issue because Google's OAuth redirect separates scopes using `+`:
`https://nuxt3-min.vercel.app/?scope=https://www.googleapis.com/auth/calendar.events.readonly+https://www.googleapis.com/auth/calendar.readonly`

**Comment by pi0** [comment]
Thanks for reporting the issue and reproduction. Interestingly it can only happen when `pages/` directory is used. It seems an encoding conflict between `vue-router` and Vercel.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/5902.
