### ISSUE TITLE
runtimeConfig will not be updated after "yarn build"

### ISSUE THREAD

**Issue by andretw** [nuxt/framework#7091]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `typescript`, `head`, `runtimeConfig`, `modules`, `css`, `styleResources`, `plugins`, `components`, `experimental`, `vite`, `hooks`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`
- Build Modules:    `-`

### Reproduction

1. Create a .env file at the project's root dir.
2. Follow the instruction to use the runtimeConfig.
3. `yarn build` to build the artifacts.
4. `yarn start` to see the current NUXT_ABC value.
5. Stop or kill the process
6. Change the value of NUXT_ABC you have set by `source .env` or NUXT_ABC=123 directly.
7. `yarn start` again and you will see the value hasn't been changed.

### Describe the bug

runtimeConfig does not behave as I expected as a "runtime" config. The configs were set after `yarn build`. And you can not change them via any solutions since they were already determined in .output/server/chunks/nitro/node-server.mjs.

### Additional context

I want to use the same container image and apply the env configs for every environment by using 'yarn build' and `yarn start`. Or I can only use `yarn dev` and customize the other settings for achieving the goal?

**Comment by danielroe** [comment]
You can override them, but it requires using an environment variable that matches the key of the runtime config value. See https://v3.nuxtjs.org/api/configuration/nuxt.config#runtimeconfig.

**Comment by andretw** [comment]
@danielroe same issue here: https://stackoverflow.com/questions/73111883/why-is-runtimeconfig-doesnt-see-environment-variables-in-nuxt-3

**Comment by danielroe** [comment]
You haven't provided a reproduction so I can't help more specifically, but in the code you have quoted is the code that allows overriding runtime config. (Look at the overrideConfig function.)

**Comment by andretw** [comment]
@danielroe I made a reproduction here: https://stackblitz.com/edit/nuxt-starter-varvsy?file=app.vue

And I use this command to run the app:
`export NUXT_MY_ABC=11111 && node .output/server/index.mjs`

What I got on the frontend site:
```
window.__NUXT__={data:{},state:{},_errors:{},serverRendered:true,config:{public:{myAbc:"22222"},app:{baseURL:"\u002F",buildAssetsDir:"\u002F_nuxt\u002F",cdnURL:""}}}
```
The number `22222` hasn't been changed to `11111`. 

Or anything I did wrong? Thank you for the reply. :)

**Comment by danielroe** [comment]
@andretw It should be `NUXT_PUBLIC_MY_ABC` in your case.

**Comment by andretw** [comment]
@danielroe Thank you, I didn't realize that there is a convention between them. Thanks a lot!
