### ISSUE TITLE
Page component initiates twice after layout change

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt/framework#7097]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-lxsrmg?file=pages/index.vue

1. Visit Index
2. Visit A
3. Visit Index
4. Visit B
5. Visit Index

Observe console messages

### Describe the bug

If we navigate between pages with different layouts it looks like the `setup` method runs twice, including useAsyncData.

I was not able to reproduce it, but additionally in my private project `data` is always `null` after the second run, which completely crashes the page.

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/6592
