### ISSUE TITLE
OnMounted twice when layout change

### ISSUE THREAD

**Issue by mohammad-ashrafi2020** [nuxt/framework#7099]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `typescript`, `buildModules`, `vite`, `css`, `image`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.4.0`, `@nuxt/image-edge@1.0.0-27657146.da85542`

### Reproduction

https://codesandbox.io/s/u1dwk1

### Describe the bug

When we go from one Layout to another, OnMounted called twice
This problem was not in version Rc-4, but now it is in version Rc-8

**Comment by lukaszflorczak** [comment]
It has been already reported: https://github.com/nuxt/framework/issues/6592
