### ISSUE TITLE
Support memory history from Vue Router in client side (createMemoryHistory)

### ISSUE THREAD

**Issue by jonyw4** [nuxt/framework#7122]
### Describe the feature

I want to choose the history method of Vue Router in nuxt config file (in my case, to use specifically the `createMemoryHistory`). 

In Nuxt 2 we had that available via [router mode](https://nuxtjs.org/docs/configuration-glossary/configuration-router#mode). Although [we can config vue router](https://github.com/nuxt/framework/pull/3485), we can't change the history method [because is based on `process.client` boolean](https://github.com/nuxt/framework/blob/main/packages/nuxt/src/pages/runtime/router.ts#L57-L60).

### Proposal

Accept a new `router.history` prop in `nuxt.config.ts`
```ts
defineNuxtConfig({
  router: {
    history: 'memory'
  }
})
```

That can accept both strings or a router history implementation, using the `RouterHistory` interface from Vue Router
```ts
'memory' | 'web-hash' | 'web-html5' |  RouterHistory
```

This can override the default ternary in the current router runtime

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by 516310460** [comment]
See: https://v3.nuxtjs.org/guide/directory-structure/pages#router-options

**Comment by jonyw4** [comment]
That looks great. Thank you @danielroe 🙇🏻‍♂️
