### ISSUE TITLE
Vue components html is included twice in production build

### ISSUE THREAD

**Issue by denniswiemer** [nuxt/framework#7126]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.19.2`
- Builder:          `vite`
- User Config:      `build`, `css`, `components`, `runtimeConfig`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `-`
- Default Nuxt 3 config with universal rendering

### Reproduction

- create a basic Vue component with only some html and no script or style
- include the component in a layout

### Describe the bug

When looking into the final build I expect the component html to be serverside rendered and only included in the server/index.mjs once. Currently the html from a component is indeed included in the server/index.mjs but also a chunk is loaded in the client which includes the same html dom.  Of course we don't want that duplication as it's bad for performance.

**Comment by 516310460** [comment]
Would you please provide a reproduction?

**Comment by danielroe** [comment]
This is how Vue SSR hydration normally works. However, we are looking to add some new enhancements here, particularly with the introduction of server components, which won't have a corresponding chunk in client-side JS: https://github.com/nuxt/framework/pull/5688.
