### ISSUE TITLE
useFetch with url function does not re-fetch data

### ISSUE THREAD

**Issue by bf** [nuxt/framework#7136]
### Environment

Nuxt CLI v3.0.0-rc.8                                                                                       13:40:47
Nuxt project info:                                                                                         13:40:49

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `build`, `buildModules`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.3.2`
------------------------------

### Reproduction

components/ProjectName.vue:

```
<template>
  <span>
  	{{props.projectId}}
  	<span>{{project}}</span>
  </span>
</template>

<script setup>
const props = defineProps({
	projectId: String
})

const projectId = ref(props.projectId)

const { data: project, pending, refresh } = await useFetch(
	() => {  
		const url = '/api/projects/' + projectId.value; 
		console.log(url);
		return url
	}, {
	  headers: useRequestHeaders(['cookie']),
	  watch: [projectId],
	  lazy: false,
	  cache: false
	})

</script>
```

pages/[projectId].vue

```
<template>
<ProjectName :projectId=$route.params.projectId />
</template>
```

### Describe the bug

If "projectId" prop of the ProjectName.vue component changes, the useFetch url() generation function is called and writes the new url via console.log(url) to console. However, no new data is fetched from the backend.

### Additional context

Might be related to https://github.com/nuxt/framework/issues/6273

**Comment by bf** [comment]
After spending several hours on this problem, I finally found a workaround. 

in components/ProjectName.vue:

```
<script setup>
const props = defineProps({
	projectId: String
})

const projectId = ref(props.projectId)

const { data: project, pending, refresh } = await useAsyncData(
	"project" + projectId.value, 
	() => {  
		const url = '/api/projects/' + projectId.value; 
		console.log(url);
		return $fetch(url, { headers: useRequestHeaders(['cookie']) })
	}, {
	  watch: [projectId],
	})
</script>
```

I don't know why it wouldn't work with useFetch() natively

**Comment by AndersNielsen85** [comment]
@bf You might consider a shorter "workaround" with useFetch. 
Adding the key made it work in my case at least. :)

But agreed the documentation says it should refresh using a function

`const { data } = await useFetch('/api/projects/' + projectId.value, { key: projectId.value });
`

**Comment by bf** [comment]
Thanks, let me try it. The funny thing about this bug is that it calls the function for the new url, but it never calls the new url.

**Comment by bf** [comment]
Thanks @AndersNielsen85 so this also works:

```
const { data: project, pending, refresh } = await useFetch(
	'/api/projects/' + projectId.value, { 
		headers: useRequestHeaders(['cookie']),
		key: "project-" + projectId.value
	})

const { data: project, pending, refresh } = await useFetch(
	() => '/api/projects/' + projectId.value, { 
		headers: useRequestHeaders(['cookie']),
		key: "project-" + projectId.value
	})
```

but these variants don't work:

```
const { data: project, pending, refresh } = await useFetch(
	() => '/api/projects/' + projectId.value, { 
		headers: useRequestHeaders(['cookie'])
	})


const { data: project, pending, refresh } = await useFetch(
	() => '/api/projects/' + projectId.value, { 
		headers: useRequestHeaders(['cookie']),
		watch: [projectId]
	})
```

**Comment by bf** [comment]
So my assumption about useFetch() would be that if a url function is given as first parameter, and the url function generates a *new* url, then also the data would be re-fetched. That is currently not happening.

**Comment by ennioVisco** [comment]
AFAIK this is not a bug but intended, the URL should not be prefetched if it is exactly the same (unless another key is passed).
The problem seems instead on key generation for useFetch, which, if I remember correctly it was already reported before, most recently I think in https://github.com/nuxt/framework/issues/5993.

**Comment by StefanCardnell** [comment]
See #3985

I am also not sure that caching all API payloads is ideal default behaviour. I think it will be very confusing, especially for users of other http libraries like axios.

**Comment by danielroe** [comment]
Yes, we can track in #5993. At the moment the URL is not used as the key for `useFetch`.

**Comment by panle666** [comment]
> @bf您可能会考虑使用 useFetch 使用更短的“解决方法”。 添加密钥使其至少在我的情况下工作。:)
> 
> 但同意文档说它应该使用函数刷新
> 
> `const { data } = await useFetch('/api/projects/' + projectId.value, { key: projectId.value }); `



> @bf您可能会考虑使用 useFetch 使用更短的“解决方法”。 添加密钥使其至少在我的情况下工作。:)
> 
> 但同意文档说它应该使用函数刷新
> 
> `const { data } = await useFetch('/api/projects/' + projectId.value, { key: projectId.value }); `

nice
