### ISSUE TITLE
Nuxt3 Docker Building EACCES Error

### ISSUE THREAD

**Issue by BlackYuzia** [nuxt/framework#7145]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `modules`, `build`, `vite`, `runtimeConfig`, `app`
- Runtime Modules:  `@pinia/nuxt@0.4.1`
- Build Modules:    `-`
------------------------------

### Reproduction

- Use docker file:
```docker
# Build
FROM node:lts-alpine as builder

# ENV NODE_ENV production
WORKDIR /home/node

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build 

# Run
FROM node:lts-alpine as prod

ENV NODE_ENV production
USER node
WORKDIR /home/node

COPY --from=builder --chown=node:node /home/node/package*.json ./
COPY --from=builder --chown=node:node /home/node/.output/ ./.output/

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
```
- Try build image (I use docker-compose for it)
- Get error

### Describe the bug

When you try to build application with `npm run build` command inside docker container (Docker file) you could get error:

```
ERROR  Rollup error: EACCES: permission denied, stat '/root/.node_modules/file:/home/node/node_modules/unenv/runtime/mock'
ERROR  EACCES: permission denied, stat '/root/.node_modules/file:/home/node/node_modules/unenv/runtime/mock'
```

### Additional context

Too late, so I go to sleep. If you can't reproduce it and require reproduce code, tag me, I will try make it later

**Comment by 516310460** [comment]
Error: permission denied?
sudo docker-compose up -d

**Comment by BlackYuzia** [comment]
> Error: permission denied?
> sudo docker-compose up -d

I already run  it with sudo, this didn't help, but I made it again for this screenshot :eyes:

![image](https://user-images.githubusercontent.com/25010528/188095172-48da97ed-0ac4-4558-a29f-636d881bd6e1.png)

Suppose I should create reproduce code, I will try to make it as fast as I can

**Comment by 516310460** [comment]
Would you please pervide a reproduction?

**Comment by BlackYuzia** [comment]
> Would you please pervide a reproduction? Or see e.g: https://github.com/516310460/nuxt3-docker

Tested, get the same error, try this:
https://gitlab.com/BlackYuzia/nuxt3-docker-reproduce

**Comment by 516310460** [comment]
permission denied

**Comment by 516310460** [comment]
If you don't have permission, how to operate?

**Comment by BlackYuzia** [comment]
> If you don't have permission, how to operate?

What do you mean?

**Comment by BlackYuzia** [comment]
@danielroe reproduction code - https://gitlab.com/BlackYuzia/nuxt3-docker-reproduce

**Comment by HendrikJan** [comment]
This is also an issue in nuxt/bridge

**Comment by HendrikJan** [comment]
Another reproduction can be found here: https://github.com/nuxt/framework/issues/6200

**Comment by danielroe** [comment]
I can no longer reproduce on latest nuxt + nitro.
