### ISSUE TITLE
Middleware doesn't support `provide/inject`

### ISSUE THREAD

**Issue by genu** [nuxt/framework#7148]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.4.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `pnpm@7.5.1`
- Builder:          `vite`
- User Config:      `modules`, `nitro`, `typescript`, `app`, `css`, `autoImports`, `runtimeConfig`, `build`, `tailwindcss`, `formkit`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`, `@formkit/nuxt@1.0.0-beta.10`, `@pinia/nuxt@0.4.0`, `@vueuse/nuxt@9.1.1`, `nuxt-graphql-codegen@0.3.3`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ly4gwk?file=middleware/sample.ts

### Describe the bug

In a middleware, `inject` and `provide` are not available and throw warnings:

 `[Vue warn]: inject() can only be used inside setup() or functional components.`
 `[Vue warn]: provide() can only be used inside setup().`
 
It's not clear from the docs if this is supposed to be supported or not, or in what context middlewares run.

### Additional context

I'm using `@urql/vue` and its configured through a plugin. 

The `@urql/vue` plugin provides a client with `provide(...)` so that the instantiated client can be used throughout the application.

In a middlware, when I try to use `urql` to query for a user profile, it fails:
```ts
const { data } = await useMyProfileQuery()
```

**Comment by 516310460** [comment]
I think the problem is well described
Need to be used in `setup`
