### ISSUE TITLE
`navigateTo` has no effect when a plugin is declared

### ISSUE THREAD

**Issue by Baloche** [nuxt/framework#7169]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `css`, `vite`, `typescript`, `modules`, `unocss`
- Runtime Modules:  `@unocss/nuxt@^0.44.7`, `@vueuse/nuxt@9.1.1`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/nuxt-3-navigateto-with-usefetch-15ihel

### Describe the bug

To intercept every 401 error I receive from my API, I created a wrapper method of `useFetch` : 

```ts
export function useApi(request) {
  return useFetch(request, {
    async onResponseError(ctx) {
      if (ctx.response.status === 401) {
        await navigateTo("/login", { replace: true, redirectCode: 401 });
      }
    }
  });
}
```

But somehow, it only works if I don't have any plugins declared.
If you comment every line of [this file](https://codesandbox.io/s/nuxt-3-navigateto-with-usefetch-15ihel?file=/plugins/guilty.ts), the redirection works well, but as long as the `defineNuxtPlugin` function is called, the redirection does not work. Why ?

**Comment by pi0** [comment]
Hi @Baloche sorry for answering late. I have made updated working example for you:


https://stackblitz.com/edit/github-yjetdx?file=server%2Fapi%2Fme.get.ts,composables%2Findex.ts,pages%2Findex.vue

Please see https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529 and https://github.com/nuxt/framework/issues/6996 for better context.

**Comment by Baloche** [comment]
Thanks for the answer @pi0 :) 
Unfortunately, it is working because there is no plugin 😄 
It doesn't work if you create the file `plugins/guilty.ts`
```ts
export default defineNuxtPlugin(() => {
  return {
    provide: {
      hello: (msg: string) => `Hello ${msg}!`,
    },
  };
});

```

**Comment by pi0** [comment]
Right! Try this updated sandbox: https://stackblitz.com/edit/github-yjetdx?file=composables%2Findex.ts (https://github.com/nuxt/framework/issues/7235)

**Comment by Baloche** [comment]
Thank you! I was trying the same lead ! [It works!](https://codesandbox.io/s/nuxt-3-navigateto-with-usefetch-15ihel?file=/composables/index.ts)

**Comment by pi0** [comment]
Happy hearing this! Let's track improvements from linked issues.
