### ISSUE TITLE
pinia error on RC8 build

### ISSUE THREAD

**Issue by caio-emidio** [nuxt/framework#7179]
### Environment

Nuxt project info:                                                                                                                                                                                     02:11:39

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `modules`, `nitro`, `buildModules`, `css`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`
- Build Modules:    `@pinia/nuxt@0.3.1`
------------------------------

### Reproduction

When i am trying to build (npm run build) :

npm run build

> build
> nuxt build

Nuxt CLI v3.0.0-rc.8                                                                                                                                                                                   02:12:47
i Using Tailwind CSS from ~/assets/css/tailwind.css                                                                                                                                   nuxt:tailwindcss 02:12:56
i Client built in 3678ms                                                                                                                                                                               02:13:02
i Building server...                                                                                                                                                                                   02:13:02
√ Server built in 1608ms                                                                                                                                                                               02:13:03
√ Generated public .output/public                                                                                                                                                                nitro 02:13:03
start Building server...                                                                                                                                                                         nitro 02:13:04

 ERROR  Rollup error: Could not load C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open 'C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs'

 ERROR  Could not load C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open 'C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs'

### Describe the bug

When i am trying to run this npm run build . On my machine or on vercel. I receive the same errors.

npm run build

 ERROR  Rollup error: Could not load C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open 'C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs'

 ERROR  Could not load C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open 'C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs'

### Additional context

package json:

{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/tailwindcss": "^5.1.2",
    "@pinia/nuxt": "^0.3.0",
    "axios": "^0.27.2",
    "nuxt": "^3.0.0-rc.6"
  }
}

### Logs

```shell
npm run build

> build
> nuxt build

Nuxt CLI v3.0.0-rc.8                                                                                                                                                                                   02:12:47
i Using Tailwind CSS from ~/assets/css/tailwind.css                                                                                                                                   nuxt:tailwindcss 02:12:56
i Client built in 3678ms                                                                                                                                                                               02:13:02
i Building server...                                                                                                                                                                                   02:13:02
√ Server built in 1608ms                                                                                                                                                                               02:13:03
√ Generated public .output/public                                                                                                                                                                nitro 02:13:03
start Building server...                                                                                                                                                                         nitro 02:13:04


 ERROR  Rollup error: Could not load C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open 'C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs'


 ERROR  Could not load C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs (imported by .nuxt/dist/server/server.mjs): ENOENT: no such file or directory, open 'C:\Users\husen\code\FuracaoDublin2\node_modules\pinia\dist\pinia.mjs\dist\pinia.mjs'
```

**Comment by MorevM** [comment]
@caio-emidio you need to install `pinia` itself alongside the `@pinia/nuxt` :)

**Comment by productdevbook** [comment]
pinia is working -> check https://github.com/productdevbook/oku-nuxt3-template

**Comment by caio-emidio** [comment]
Just one thing... on RC6 its building normal. The error occurs on RC8.

**Comment by pi0** [comment]
@caio-emidio Would pyou please create a stackblit reproduction and against last rc.9?

**Comment by caio-emidio** [comment]
> @caio-emidio Would you please create a stackblitz reproduction and against the last rc.9? 🙏🏼

Sorry @pi0 , i dont have any idea how to do it.

**Comment by pi0** [comment]
Here is a basic example: https://stackblitz.com/edit/github-vmafic?file=app.vue

Pina seems working with rc.9 (and no explicit `pinia` dep is installed) But it might be a difference in your project setup that makes an issue.

I would suggest you to use `npx nuxi-edge@latest upgrade --force`. This _might_ help.

**Comment by caio-emidio** [comment]
@pi0 i created this one:
https://stackblitz.com/edit/piniaerror-rc8-rc9-build

if you go there in a new terminal and type: "npm run build" you will find the issue. Thanks a lot for your help.

**Comment by caio-emidio** [comment]
![image](https://user-images.githubusercontent.com/5342402/188310365-78c5b58c-63b5-4185-adf0-9c11380f6b5f.png)

**Comment by productdevbook** [comment]
@caio-emidio 

> pinia is working -> check https://github.com/productdevbook/oku-nuxt3-template

The is here I posted a link to check. Looking from there, your mistakes are visible.

1.  "pinia": "2.0.21" install
2. buildModules: ['@pinia/nuxt'], change -> modules: ['@nuxtjs/tailwindcss', '@pinia/nuxt'],

https://stackblitz.com/edit/piniaerror-rc8-rc9-build-qp6dzu?file=nuxt.config.ts

** I don't understand why you didn't check. Everyone here said the same thing.

**Comment by caio-emidio** [comment]
Ok , thanks.

**Comment by pi0** [comment]
@caio-emidio I hope your issue is solved but if didn't don't hesitate to DM me ib discord.

**Comment by caio-emidio** [comment]
It's solved based in the devbooks's repository. Thanks for everything.
