### ISSUE TITLE
avoid double-downloading of inlined css

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#7195]
Possibly we could move CSS resource hints from preload -> prefetch, and/or change stylesheet to load after site is interactive, maybe following one of [these strategies](https://github.com/GoogleChromeLabs/critters#preloadstrategy).

**Comment by pi0** [comment]
Maybe we can find a way to map client styles with server ids in order to remove them from manifest when inlining is enabled for them? Currently, on edge and after (#7160), there are duplicated styles (both inline `<style>` and external `<link>`)
