### ISSUE TITLE
Module nuxt-icons is disabled due to incompatibility issues

### ISSUE THREAD

**Issue by shba007** [nuxt/framework#7196]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`, `@vueuse/nuxt@9.1.1`, `nuxt-icons@2.0.1`, `@pinia/nuxt@0.4.1`
- Build Modules:    `-`

### Reproduction

use `npx nuxi update` to upgrade from RC8 to RC9

Reproduction link: https://stackblitz.com/edit/github-wdogcw

### Describe the bug

After Upgrading from RC8 Nuxt Icon Module are not working anymore.

### Additional context

In Node Console

![image](https://user-images.githubusercontent.com/48382105/188270731-0591055d-3339-44e2-ba98-47e99303107f.png)

![image](https://user-images.githubusercontent.com/48382105/188270834-21f8d9c9-9b64-47d9-9c51-abbb90c0b377.png)

In Browser Console

![image](https://user-images.githubusercontent.com/48382105/188270868-73f1d5ef-bd8f-4a02-80b0-78585349d009.png)

**Comment by pi0** [comment]
Hi. I've made a PR to fix it in upstream https://github.com/gitFoxCode/nuxt-icons/pull/9

**Comment by danielroe** [comment]
@daver987 And which modules are those?

**Comment by tobychidiu** [comment]
I have this same issue with Vue Use Motion and FormKit

**Comment by danielroe** [comment]
This is now resolved in v2.0.2 of `nuxt-icons`.
