### ISSUE TITLE
test-utils failing to find `styles.mjs` on first run

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#7198]
```
git clone git@github.com:nuxt-community/harlem-module.git
cd harlem-module
rm -rf playground/.nuxt playground/.output
pnpm dev:prepare
pnpm test:e2e
```

error:

```
Error: Could not load playground/.nuxt/yu0q90/dist/server/styles.mjs (imported by node_modules/.pnpm/nuxt3@3.0.0-rc.10-27703516.b97cc27_eslint@8.23.0+vite@3.0.9/node_modules/nuxt3/dist/core/runtime/nitro/renderer.mjs): ENOENT: no such file or directory, open 'playground/.nuxt/yu0q90/dist/server/styles.mjs'
```

**Comment by danielroe** [comment]
This is actually a case of mismatching `@nuxt/vite-builder` version within the project.

**Comment by danielroe** [comment]
This might be a pain for module authors testing edge.

Do you think we could implement a workaround, e.g. set a nitro virtual and override if we emit the actual file? @pi0

**Comment by pi0** [comment]
I'm thinking to disable inline behavior. It was probably to early enabling flag out of the box. 

BTW there is a virtual file. What is breaking it? Do you mind to make a stackblitz?

**Comment by danielroe** [comment]
The virtual file is only if inline styles is disabled.

The issue is different versions of Nuxt and vite builder.
