### ISSUE TITLE
Socket.io not working in Nuxt Production

### ISSUE THREAD

**Issue by jeky1950** [nuxt/framework#7199]
### Environment

Nuxi 3.0.0-rc.9   
RootDir: C:/Users/petal/Desktop/Work/loyalty-points-system
Nuxt project info:

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `css`, `build`, `buildModules`, `modules`
- Runtime Modules:  `~/modules/socket`
- Build Modules:    `@pinia/nuxt@0.4.0`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org      

### Reproduction

Great work guys !!!. I have created a stack on stack over flow with the steps to recreate the bug [here](https://stackoverflow.com/questions/73592619/socket-io-websocket-not-working-in-nuxt-3-when-in-production). And I have also created a export and run locally [.](https://replit.com/@anthonyanth/Socketio-Nuxt-3-Production-Error)

### Describe the bug

When I run socket.io in development mode it runs perfectly however when I run it in production mode it stops working

**Comment by danielroe** [comment]
I see you've found the issue in your stackoverflow link. Nuxt modules are build-time only and do not run in production.
