### ISSUE TITLE
sendRedirect() corrupting urls containing %2F

### ISSUE THREAD

**Issue by rohrig** [nuxt/framework#7200]
### Environment

Linux (fedora)
Node LTS
yarn dev

### Reproduction

https://github.com/jurassicjs/nuxt-url-bug-demo

https://youtu.be/4_YZVv0IwNM

### Describe the bug

sendRedirect() appears to be corrupting long URLs

### Additional context

The but did not exists in rc4 

I first noticed after upgrading to rc9

the reproduction is rc8

**Comment by pi0** [comment]
This is because of a recent security fix to unjs/h3 preventing XSS by encoding URI. Regardless of length, it seems `%2F` get's corrupted wrongly: `encodeURI('https://test.com/foo%2Fbar')` => `https://test.com/foo%252Fbar`

**Comment by pi0** [comment]
Should be fixed in latest h3. Please try upgrading lockfile and let me know if still having issues to reopen.

**Comment by rohrig** [comment]
fix verified. Your guys are awesome. :1st_place_medal: 

Seriously, that reaction time is world class!
