### ISSUE TITLE
cannot import package @vue/composition-api 

### ISSUE THREAD

**Issue by gurpindersinghgill** [nuxt/framework#7201]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `app`, `buildModules`, `modules`, `build`, `css`, `typescript`, `vite`, `auth`, `router`
- Runtime Modules:  `@nuxtjs-alt/auth@2.0.6`, `@nuxtjs-alt/http@1.2.10`, `@nuxtjs-alt/proxy@1.3.3`, `@pinia/nuxt@0.4.1`, `@vueuse/nuxt@9.1.1`
- Build Modules:    `@nuxtjs/tailwindcss@5.3.2`, `@vueuse/nuxt@9.1.1`
------------------------------

### Reproduction

not able to provide

### Describe the bug

After upgrading from rc.8 o rc.9 , unable to find the package @vue/composition-api thrown in console

### Additional context

Upgrading form rc.8 to rc.9 throws this error. 

### Logs

```shell
ℹ Vite server warmed up in 101ms                                                                                               00:26:14
✔ Nitro built in 692 ms                                                                                                  nitro 00:26:15
ℹ Vite client warmed up in 5607ms                                                                                              00:26:17
[nuxt] [request error] [unhandled] [500] Cannot find package '@vue/composition-api' imported from /Users/gurpinder/node_modules/vue-demi/lib/index.mjs
  at new NodeError (node:internal/errors:372:5)  
  at packageResolve (node:internal/modules/esm/resolve:954:9)  
  at moduleResolve (node:internal/modules/esm/resolve:1003:20)  
  at defaultResolve (node:internal/modules/esm/resolve:1218:11)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)  
  at link (node:internal/modules/esm/module_job:78:36)
```

**Comment by ennioVisco** [comment]
Could you clarify in which cases you would need that (or provide a reproduction)?

**Comment by skaaptjop** [comment]
Interestingly I experience the same scenario when upgrading from RC9 to RC10

**Comment by manniL** [comment]
> Could you clarify in which cases you would need that (or provide a reproduction)?

Check out https://v3.nuxtjs.org/community/reporting-bugs#create-a-minimal-reproduction ☺️

**Comment by skaaptjop** [comment]
Resolved. Was a Pinia related issue.

**Comment by rhengles** [comment]
> Resolved. Was a Pinia related issue.

@skaaptjop  What was the fix ? I'm getting this error, all I did was this:

```
// from https://github.com/antfu/vitesse-nuxt3
npx degit antfu/vitesse-nuxt3 my-nuxt3-app
cd my-nuxt3-app
pnpm i
pnpm dev

// Error:
// Cannot find package '@vue/composition-api' imported from /home/user/my-nuxt3-app/node_modules/.pnpm/vue-demi@0.13.11/node_modules/vue-demi/lib/index.mjs
```

@danielroe
