### ISSUE TITLE
How to use $ref macro in Nuxt3?

### ISSUE THREAD

**Issue by JordashTalon** [nuxt/framework#7209]
### Describe the feature

I'm trying to follow this example of using $ref for primitive variables in Nuxt3 but when I try and use this line:

import { $ref } from "vue/macros";

I get this error:

SyntaxError: ambiguous indirect export: $ref

Would like for there to be someway to use the Vue Macros as they are very useful.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by Luffyyy** [comment]
Add this in your nuxt.config.ts/.js: 

```ts
experimental: {
  reactivityTransform: true
},
```
