### ISSUE TITLE
https for dev-server

### ISSUE THREAD

**Issue by Mechse** [nuxt/framework#7218]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.2.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `css`, `build`, `modules`, `buildModules`, `googleFonts`
- Runtime Modules:  `@pinia/nuxt@0.4.1`
- Build Modules:    `@nuxtjs/google-fonts@3.0.0-0`
------------------------------

### Reproduction

1. Start a new project:
https://v3.nuxtjs.org/getting-started/quick-start

2. Install mkcert:
https://github.com/FiloSottile/mkcert

3. Create ssl -certificate:
`mkcert localhost`

4. Rewrite package.json:
`"dev": "nuxt dev --https --ssl-cert localhost.pem --ssl-key localhost-key.pem"`

### Describe the bug

I tested it within a valid project and the default boilerplate.
The results are the same.

### Logs

```shell
500 
fetch failed ()

at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
at async ./.nuxt/dev/index.mjs:457:20
at async ./.nuxt/dev/index.mjs:520:64
at async ./.nuxt/dev/index.mjs:106:22
at async ./node_modules/h3/dist/index.mjs:592:19
at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:538:7)
```

**Comment by chrisnoden** [comment]
This problem still exists in `rc10` but has evolved:
```[nuxt] [request error] [unhandled] [500] request to https://0.0.0.0:3000/__nuxt_vite_node__/manifest failed, reason: unable to verify the first certificate ()
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
```

**Comment by pi0** [comment]
With RC.10, you still need `NODE_TLS_REJECT_UNAUTHORIZED=0` environment variable to be set for vite working. It should work out of the box with RC.11+ (via #7547). You can use [edge channel](https://v3.nuxtjs.org/getting-started/upgrade-guide/edge-channel) to try this.
