### ISSUE TITLE
Running dev server in https results in error

### ISSUE THREAD

**Issue by chrisnoden** [nuxt/framework#7221]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Run any nuxt v3 project with the `--https` option.

### Describe the bug

It appears part of the nuxt/vite code is trying to connect to http for a manifest file even though https has been selected.

### Additional context

This is reproducible with the most simple code, eg https://github.com/chrisnoden/nuxt3-bug

Run you run `yarn dev` (which equates to `npx nuxi dev --https --ssl-cert localhost.pem --ssl-key localhost-key.pem`) you will get the error after the Vite client warmed up message.

### Logs

```shell
[nuxt] [request error] [unhandled] [500] request to http://0.0.0.0:3000/__nuxt_vite_node__/manifest failed, reason: socket hang up ()
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)  
  at async ./.nuxt/dev/index.mjs:457:20  
  at async ./.nuxt/dev/index.mjs:520:64  
  at async ./.nuxt/dev/index.mjs:106:22  
  at async ./node_modules/h3/dist/index.mjs:592:19  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:538:7)
```
```

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/7218.
