### ISSUE TITLE
Client only components (`x.client.vue`) force remount on prop change

### ISSUE THREAD

**Issue by warflash** [nuxt/framework#7226]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-akmejo?file=app.vue,components%2FChild.client.vue,components%2FParent.vue

### Describe the bug

If props passed to a client only component (https://v3.nuxtjs.org/guide/directory-structure/components/#client-components)
change it forces a remount/rerender of the entire component, which really kills performance in many cases. If you remove the .client from the child component and refresh it works as expected.
Happy I found figured it out now but man that one was painful to find😭

**Comment by 516310460** [comment]
This does have a big performance impact

**Comment by 516310460** [comment]
Using 
```ts
import { Child } from '#components'
```
Show import is ok

Problems with automatic import

@antfu Please help

**Comment by huang-julien** [comment]
The issue is caused by the fact that `createClientOnly()` is always called when the component holding the .client component rerender
![image](https://user-images.githubusercontent.com/63512348/188432216-ab91d5c9-3564-425e-9175-ec7fe28b18f8.png)

This is the compiled render function of your parent.vue

```ts
function _sfc_render(_ctx, _cache, $props, $setup, $data, $options) {
  const _component_Child = /*#__PURE__*/ createClientOnly(__nuxt_component_0)

  return (_openBlock(), _createElementBlock("div", null, [
    _createElementVNode("button", { onClick: $setup.increment }, "Click me"),
    _createVNode(_component_Child, { number: $setup.counter }, null, 8 /* PROPS */, ["number"])
  ]))
}
```
Each times it re-render, createClientOnly is called. Even removing the prop from <Child /> trigger a remount of Child.client

**Comment by huang-julien** [comment]
> Using
> 
> ```ts
> import { Child } from '#components'
> ```
> 
> Show import is ok
> 
> Problems with automatic import
> 
> @antfu Please help
> 
> See: https://stackblitz.com/edit/github-akmejo-pg7azf?file=app.vue,components%2FChild.client.vue,components%2FParent.vue `Error: Hydration completed but contains mismatches.`

related to #7085

**Comment by antfu** [comment]
Working on it
