### ISSUE TITLE
why the class `nuxt-link-exact-active` or `nuxt-link-active` have not set other style when selected

### ISSUE THREAD

**Issue by hexiaokang** [nuxt/framework#7230]
### Describe the feature

As you can see, I selected API, But there is no any flag style,So i don't know which nav i has selected.Thanks!

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/16911432/188371118-063d7239-85e0-4e94-9b9a-5004b84d0079.png">

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by 516310460** [comment]
Defaults to `/api/composables/use-async-data`

**Comment by 516310460** [comment]
Thanks.

**Comment by pi0** [comment]
Thanks.

**Comment by hexiaokang** [comment]
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/16911432/188392788-2d107772-a802-4587-b8a7-bbf8ce436134.png">

**Comment by danielroe** [comment]
No. The Nuxt 3 docs are ironically not yet using Nuxt 3.

The question you're raising is to do with an underlying change in Vue router: https://router.vuejs.org/guide/migration/index.html#removal-of-the-exact-prop-in-router-link.

**Comment by bf** [comment]
Ok I found workaround described in https://github.com/nuxt/framework/issues/5087#issue-1243705222
