### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". 

### ISSUE THREAD

**Issue by konradsienkowski** [nuxt/framework#7285]
### Environment

```
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.19.1`
- Builder:          `vite`
- User Config:      `app`, `buildModules`, `css`, `modules`, `runtimeConfig`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.4.2`, `@nuxt/image-edge@1.0.0-27706054.395f7ae`, `@nuxtjs/color-mode@3.1.4`, `@nuxtjs/strapi@1.5.1`
- Build Modules:    `@averjs/nuxt-compression@1.2.2`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-9fqinn (only with `npm run build`)

### Describe the bug

After updating to the RC 9 running` npm run dev` works fine, but trying to use `npm run build` and preview the build results with an error in the console:
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

**Comment by konradsienkowski** [comment]
My bad - turns out [@averjs/nuxt-compression](https://github.com/exreplay/nuxt-compression) module was causing the bug in my case. Somehow I overlooked it before adding the issue

**Comment by liangxianh** [comment]
view your baseurl config，  the last maybe have ‘/’；
