### ISSUE TITLE
Nuxt 3 RC9 - Exclude routes during generate

### ISSUE THREAD

**Issue by AVIIIVII** [nuxt/framework#7291]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `i18n`, `runtimeConfig`, `router`, `generate`
- Runtime Modules: `@nuxtjs/i18n@8.0.0-alpha.1`
- Build Modules:    `-`

### Reproduction

1. Install Nuxt RC9.
2. Install Nuxt i18n v8.
4. Create some pages in the `pages`dir.
5. In your Nuxt config, configure `generate.exclude` with some RegExps corresponding to the pages you don't want to generate.
6. `nuxi generate`

### Describe the bug

The exclude parameter doesn't do anything. It is like none of the routes are filtered during generation.

### Additional context

In Nuxt 3 documentation, there is nothing about SSG and the options available to us to test it.

**Comment by danielroe** [comment]
Yes, the `generate` key does not apply to Nuxt 3; it's a typing for Nuxt 2. Here's how you would ignore routes:

```js
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  nitro: {
    prerender: {
      ignore: []
    }
  }
})
```

**Comment by AVIIIVII** [comment]
Thank you @danielroe 🙏

In the [Server Engine](https://v3.nuxtjs.org/guide/concepts/server-engine) part of Nuxt 3 doc, Nuxt Team should consider clarifying what Nitro does and does not do.

I read every pages of the documentation. For now it let us think that Nitro is mainly used to handle custom API routes in the server dir.

I was at Vue Nation and Nuxt Nation. By listening to all of your talks, I know that Nitro does way more than this.
It is too bad people can't grasp the potential that Nuxt 3, UnJs and Nitro offer.

I really think that by completing the first version of the doc people could help you fix issues faster.

**Comment by AVIIIVII** [comment]
While trying to define `nitro.prerender.ignore` I got:

`Type 'RegExp[]' is not assignable to type '(string | undefined)[]'.`

Sometimes we'll need to ignore a set of routes based on a part of a given url.

Imagine that Nuxt generates:
`/blog/`
`/blog/category-1/`
`/blog/category-1/slug-1/`
`/blog/category-1/slug-2/`
`/en/blog/`
`/en/blog/category-1/`
`/en/blog/category-1/slug-1/`
`/en/blog/category-1/slug-2/`

How can I ignore all the routes based on `/en/blog/`?

**Comment by luaz** [comment]
`nitro.prerender.ignore` is check using `startsWith`, so `/en/blog/` should work.
