### ISSUE TITLE
Nuxt 3 RC9 - layout warning

### ISSUE THREAD

**Issue by EmilyFlocc** [nuxt/framework#7292]
### Environment

"nuxt": "3.0.0-rc.9",

### Reproduction

I just upgraded from rc-8 to rc-9 and I now get this warning

### Describe the bug

New warning in browser:
[nuxt] `default` layout does not have a single root node and will cause errors when navigating between routes.

![Screenshot 2022-09-06 at 16 51 43](https://user-images.githubusercontent.com/72082422/188680333-e07ed58c-abb6-45b1-a04f-d8c028b57cb2.png)

My app.vue looks like this to include the header and footer components on each page:
![Screenshot 2022-09-06 at 17 08 03](https://user-images.githubusercontent.com/72082422/188683853-f4af3e3a-9dc9-4ec8-beb5-0afe74976059.png)

**Comment by Gruce** [comment]
Hello @EmilyFlocc ,
Seems like your `default.vue` does not have single root node. Could you provide your `default.vue` code?

**Comment by AndersNielsen85** [comment]
@EmilyFlocc 
I suspect you don't have a layout file since you are using app.vue ?
- If this is the case you can workaround this by making a /layouts/default.vue with the following content.

I seems like the default nuxt is using when not having a default.vue layout might have more root nodes.

Background:
https://github.com/nuxt/framework/pull/5469

```
<template>
  <div class="default-layout">
    <slot />
  </div>
</template>```

**Comment by EmilyFlocc** [comment]
Hi both, correct I don't have a layouts file, i have app.vue in root and error.vue in root. I thought in Nuxt 3 you didn't use layouts in the same way as nuxt 2?

**Comment by danielroe** [comment]
If you do not have any layouts, then you do not need to have `<NuxtLayout>` in your `app.vue` file. (If you do have a `<NuxtLayout>` then you should also create a default layout as suggested above.)

**Comment by EmilyFlocc** [comment]
Thank you for explaining!

**Comment by adammo94** [comment]
I recieve same error however I want to use layout :/

my `layouts/default.vue`:
```
<template>
  <div>
    <slot />
  </div>
</template>
```

my `/app.vue`:
```
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
```

**Comment by danielroe** [comment]
Thanks for reporting @ckald :heart:

**Comment by andreas83** [comment]
Mhm not sure if its related but i have the same issue:

`full` layout does not have a single root node and will cause errors when navigating between routes.

layout/full.vue


```
<template> 
            <div>
                  <slot />
            </div>
</template>
```

and my app.vue:

```
<template>

    <NuxtLayout>
        <NuxtLoadingIndicator />
        <NuxtErrorBoundary>

            <template #error="{ error }">
                <p>An error occurred: {{ error }}</p>
            </template>

           
            <NuxtPage />
        </NuxtErrorBoundary>

    </NuxtLayout>
</template>
```


------------------------------
- Operating System: `Linux`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.12-27746784.92ff066`
- Nitro Version:    `0.5.4-27726613.640c2b7`
- Package Manager:  `yarn@1.21.1`
- Builder:          `vite`
- User Config:      `buildModules`, `pageTransition`, `layoutTransition`, `publicRuntimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.5.2`
------------------------------

**Comment by jacobfogolyan** [comment]
Sounds like this one is related to my issue. I was able to re-create this simply by putting `<!-- -->` at the same level as the root node. Simply removing or adding this comment toggles this error.

**Comment by danielroe** [comment]
@jacobfogolyan That's unrelated to the issue. The warning you get is right. That will break transitions, which rely on a single root node.
