### ISSUE TITLE
Error saying "no such file or directory" from nuxt.config.ts when file exists

### ISSUE THREAD

**Issue by ZiadJ** [nuxt/framework#7301]
### Environment

Nuxi 3.0.0-rc.10-27707547.a4fa070   

### Reproduction

1. Install the [Vite Vue Inspector plugin](https://github.com/webfansplz/vite-plugin-vue-inspector)
2. npm run dev

### Describe the bug

The following error message shows up:

[vite] Internal server error: ENOENT: no such file or directory, open 'C:\ . . . \node_modules\vite-plugin-vue-inspector\src\load.js?v=707afc2d'

However, clicking on the link in VSCode does open the file so the file under the specified path exists.

**Comment by danielroe** [comment]
Would you raise the issue there instead with a reproduction? Seems to work fine for me: https://stackblitz.com/edit/github-vx8ucw...
