### ISSUE TITLE
Tailwind CSS not included in `<head>` in HTML in Production (GitHub Pages)

### ISSUE THREAD

**Issue by harvanchik** [nuxt/framework#7302]
### Environment

Nuxi 3.0.0-rc.9                                                                                               14:05:20
RootDir: C:/Websites/songuessr                                                                                14:05:23
Nuxt project info:                                                                                            14:05:23

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.18.0`
- Builder:          `vite`
- User Config:      `typescript`, `target`, `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`
- Build Modules:    `-`

### Reproduction

https://github.com/harvanchik/songuessr

### Describe the bug

When running `nuxt dev`, the styles **are working** as expected.  However, when deploying to GitHub Pages, the CSS is not even included in the `<head>` in the HTML.  The page is completely unstyled.
![image](https://user-images.githubusercontent.com/66141166/188738506-a2954cf1-6120-4da7-8295-131583ab8ebd.png)

I am using [Nuxt Tailwind](https://tailwindcss.nuxtjs.org/) for the CSS. I am following Nuxt's [suggested GitHub Pages deployment method](https://nuxtjs.org/deployments/github-pages/#github-actions): GitHub Actions.  I've done a lot of searching to see if anyone has resolved this issue, and have to yet find anything that works.

### Additional context

This is a for a school project, so I need help ASAP.  Thank you!

**Comment by manniL** [comment]
This is not related to Nuxt. You don't check your `app.vue` for tailwind classes in you [`tailwind.config.js`](https://github.com/harvanchik/songuessr/blob/master/tailwind.config.js)

**Comment by manniL** [comment]
This seems to be a deployment issue, not an issue with Nuxt itself. When running `npm run generate` locally, the styles are rendered correctly.

**Comment by danielroe** [comment]
(unrelated) you should likely move your assets out of `~/assets/img` and into `~/public/img` and then refer to them as `/img` rather than `~/assets/img`.

When running nuxt generate the links to styles are present in `<head>` and they are in [your index.html](https://github.com/harvanchik/songuessr/blob/gh-pages/index.html) but they are not on your site https://songuessr.com. Do you have any intermediate CDN filtering it? Is your website pointing to the correct deploy (and not, for example, an earlier one)?

**Comment by harvanchik** [comment]
> (unrelated) you should likely move your assets out of `~/assets/img` and into `~/public/img` and then refer to them as `/img` rather than `~/assets/img`.
> 
> When running nuxt generate the links to styles are present in `<head>` and they are in [your index.html](https://github.com/harvanchik/songuessr/blob/gh-pages/index.html) but they are not on your site https://songuessr.com. Do you have any intermediate CDN filtering it? Is your website pointing to the correct deploy (and not, for example, an earlier one)?

I am not sure about the "intermediate CDN filtering."  It didn't really do anything extra that I can think of that would result in this happening.  As for the website pointing to the correct deploy, I would assume that it is, because I literally copy-pasted the GitHub Actions scripts that [Nuxt suggested](https://nuxtjs.org/deployments/github-pages/#github-actions).  You can view those scripts [here](https://github.com/harvanchik/songuessr/tree/master/.github/workflows).

**Comment by harvanchik** [comment]
> This seems to be a deployment issue, not an issue with Nuxt itself. When running `npm run generate` locally, the styles are rendered correctly.
> 
> Please be aware that the linked deployment method guide was written for Nuxt2.
> 
> **Update**:
> 
> The [gh pages branch](https://github.com/harvanchik/songuessr/tree/gh-pages) also shows the correct CSS entry points containg [tailwind](https://github.com/harvanchik/songuessr/blob/gh-pages/_nuxt/entry.2acccd04.css) 🤔 it is also linked correctly in the `index.html`.

Is there a guide for Nuxt3 somewhere?  I could not find one.

I see that the [gh pages branch](https://github.com/harvanchik/songuessr/tree/gh-pages) branch contains the css file.  That is very odd to me that the styles are not working still.

Is there another place I should be asking for help on this?  Where would you suggest?

**Comment by harvanchik** [comment]
It appears that the CSS Link is getting removed, because the browser thinks that the file doesn't exist.  I suppose that the path is wrong (which I'm not sure how that's possible).  I generated the output myself, and the CSS didn't work.  When I added a `.` in front of the path, the CSS then worked.

Didn't work: `<link rel="preload" as="style" href="/_nuxt/entry.2acccd04.css" />`
Worked: `<link rel="preload" as="style" href="./_nuxt/entry.2acccd04.css" />`

Now my question is, why is the generated output setting an incorrect path?  How could I change this without having to change it manually everytime?

**Comment by danielroe** [comment]
You can set `app.baseURL` to `./` or indeed the specific baseURL of your site, e.g. `/songuessr`.

I am not convinced that your GH pages branch matches your domain, and I suspect is your GH pages configuration. If you inspect the contents of the HTML files, they are not the same.

**Comment by harvanchik** [comment]
Someone brought up that it's not working because GitHub Pages only works for a static site; and, Nuxt3 doesn't work for static sites yet.  Is that true?  What is the timeline for Nuxt3 supporting static sites?

**Comment by danielroe** [comment]
Yes, Nuxt 3 works fine with static sites.

**Comment by harvanchik** [comment]
> I am not convinced that your GH pages branch matches your domain, and I suspect is your GH pages configuration. If you inspect the contents of the HTML files, they are not the same.

How could I show you this information to determine if this is the issue?  I'm unsure if this information is of any use, but here's my GitHub Pages settings. 
![image](https://user-images.githubusercontent.com/66141166/188979597-726f3f9c-7738-457c-b10c-328076488b6d.png)

**Comment by harvanchik** [comment]
The issue is finally resolved.  The problem lied within the GitHub Workflow file(s).  I was using workflows written for an outdated version of Nuxt.  I have since updated them to work with Nuxt3.  You can see what I put in there [here](https://github.com/harvanchik/songuessr/blob/master/.github/workflows/gh-pages.yml).

This was tricky since there is no official documentation for how to deploy with GitHub Pages for Nuxt3 at the time this issue occurred.  But at last, with the kind help of @danielroe, we were able to resolve it.

**Comment by danielroe** [comment]
@pi0 It might be worth some nitro documentation on this; wdyt?
