### ISSUE TITLE
hot reload not working on rc9

### ISSUE THREAD

**Issue by craigharman** [nuxt/framework#7308]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `0.0.0`
- Package Manager:  `npm@8.11.0`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Start nuxt
Create a page in the `/pages/` folder
Visit that page in the browser

### Describe the bug

The page does not display.
Stop nuxt and restart and the page will display.

### Additional context

This was fixed in rc7/8 and re-introduced in rc9.

**Comment by dpmango** [comment]
Same here. Downgrade to rc8 helped

**Comment by danielroe** [comment]
Would you check if this is resolved on [the edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/)? I think this may be another report of issue solved in https://github.com/nuxt/framework/pull/7347, but it would be good to have confirmation.
