### ISSUE TITLE
ipv6 host is not supported for `nuxi dev`

### ISSUE THREAD

**Issue by some-user123** [nuxt/framework#7315]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.8.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.18.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```bash
npx nuxi init nuxt-app
npm install
```

Add
```
    "devlocal": "nuxt dev --host localhost",
```
as script in `package.json`.

`npm run dev` and open `http://localhost:3000`  --> ✅

`npm run devlocal` and open `http://localhost:3000` -->❌
```
Failed to parse URL from http://::1:3000/__nuxt_vite_node__/manifest ()
at async $fetchRaw2 (/C:/XXX/nuxt-app/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
at async /C:/XXX/nuxt-app/.nuxt/dev/index.mjs:457:20
at async /C:/XXX/nuxt-app/.nuxt/dev/index.mjs:520:64
at async /C:/XXX/nuxt-app/.nuxt/dev/index.mjs:106:22
at async /C:/XXX/nuxt-app/node_modules/h3/dist/index.mjs:592:19
at async Server.nodeHandler (/C:/XXX/nuxt-app/node_modules/h3/dist/index.mjs:538:7)
```

### Describe the bug

`nuxt dev --host localhost` does not work

### Additional context

Introduced in `rc.9`.

`--host 127.0.0.1` works, `--host ::1` doesn't.

**Comment by danielroe** [comment]
This should be resolved in RC10. Let me know if not and I'll reopen.

**Comment by some-user123** [comment]
Sorry, problem is still there :-(

**Comment by danielroe** [comment]
I believe it is fixed. You may need to upgrade your dependencies with `nuxi upgrade`.

(Note:  I tested with `nuxt dev --host localhost`.)

**Comment by prescience-data** [comment]
Not sure if you prefer a fresh issue or to continue this one, but I am receiving this error on `rc12` on Linux (Ubuntu 22.04) host.

Interestingly, it wasn't until I rolled back from node 19 -> 18 -> 16 that the true error message surfaced. 

On Node 18+, there is no error context just a `"fetch failed ()"` message which was fairly hard to reason about.

https://github.com/unjs/ohmyfetch/issues/156

**Comment by danielroe** [comment]
A new issue would be appreciated 🙏
