### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] [vite-node] Failed to load

### ISSUE THREAD

**Issue by together-mcar** [nuxt/framework#7322]
### Environment

windows 10
node v16.17.0
nuxt 3.0.0.rc9

### Reproduction

https://v3.nuxtjs.org/api/configuration/nuxt.config#css

### Describe the bug

Global introduction of css styles leads to error reporting

### Additional context

my config：
`export default defineNuxtConfig({
    modules: ['@nuxtjs/color-mode'],
    srcDir: 'src',
    alias: {
        '@': '/src'
    },
    typescript: {
        strict: true
    },
    css: [
        '@/assets/css/index.scss'
    ],
    postcss: {
        plugins: {
            tailwindcss: {},
        },
    },
    vite: {
        css: {
            preprocessorOptions: {
                scss: {
                    quietDeps: true,
                    additionalData: ''
                }
            }
        }
    }
})`
![image](https://user-images.githubusercontent.com/52190592/188875023-027320c9-1ad7-46e1-80ac-80cc0ebdbf00.png)

### Logs

```shell
[nuxt] [request error] [unhandled] [500] [vite-node] Failed to load /src/assets/css/index.scss
  at ViteNodeRunner.directRequest (/D:/code/mix_website/node_modules/vite-node/dist/client.mjs:165:13)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async ViteNodeRunner.cachedRequest (/D:/code/mix_website/node_modules/vite-node/dist/client.mjs:113:12)
  at async request (/D:/code/mix_website/node_modules/vite-node/dist/client.mjs:136:16)
  at async virtual:nuxt:D:/code/mix_website/.nuxt/css.mjs:1:238
  at async ViteNodeRunner.directRequest (/D:/code/mix_website/node_modules/vite-node/dist/client.mjs:217:5)
  at async ViteNodeRunner.cachedRequest (/D:/code/mix_website/node_modules/vite-node/dist/client.mjs:113:12)
  at async request (/D:/code/mix_website/node_modules/vite-node/dist/client.mjs:136:16)
  at async D:/code/mix_website/node_modules/nuxt/dist/app/entry.mjs:9:31
  at async ViteNodeRunner.directRequest (/D:/code/mix_website/node_modules/vite-node/dist/client.mjs:217:5)
```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by together-mcar** [comment]
ok,

export default defineNuxtConfig({
    modules: ['@nuxtjs/color-mode'],
    srcDir: 'src',
    alias: {
        '@': '/src'
    },
    typescript: {
        strict: true
    },
    postcss: {
        plugins: {
            tailwindcss: {},
        },
    },
    vite: {
        css: {
            preprocessorOptions: {
                scss: {
                    quietDeps: true,
                    additionalData: ''
                }
            }
        }
    }
})

**Comment by danielroe** [comment]
Would you use https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz to create the reproduction?

**Comment by danielroe** [comment]
Note that the issue is likely your `@` alias - try removing that line. Nuxt already adds an alias from `@` to your source directory.

**Comment by together-mcar** [comment]
Thanks, the address is this: https://stackblitz.com/edit/github-bp8usj?file=nuxt.config.ts

**Comment by danielroe** [comment]
Yes, the issue is the incorrect alias. Just remove it 😊

https://stackblitz.com/edit/github-bp8usj-dhfwvm?file=nuxt.config.ts,package.json

**Comment by together-mcar** [comment]
Okay, I'll try

**Comment by together-mcar** [comment]
Yes, the problem is solved, thanks
