### ISSUE TITLE
Plugin import fails with RC9

### ISSUE THREAD

**Issue by gluebi** [nuxt/framework#7326]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `yarn@1.22.19`

### Reproduction

https://stackblitz.com/edit/github-vdyjzf

### Describe the bug

Since RC9 it is not possible to use this plugin anymore.

Running `yarn dev` works fine but running `yarn build && yarn preview` results in a 500 only.

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Named export 'Vue3Mq' not found. The requested module 'vue3-mq' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue3-mq';
const { Vue3Mq, useMq } = pkg;

  at _instantiate (https://github-vdyjzf.w-corp.staticblitz.com/blitz.2920c879366045e9300c0e5685ed32a2f19795be.js:6:986472)  
  at <anonymous> (<anonymous>)
```

**Comment by danielroe** [comment]
You can add `vue3-mq` to your `build.transpile`: https://stackblitz.com/edit/github-vdyjzf-n7xysf

We can track issue in https://github.com/nuxt/framework/issues/7206.
