### ISSUE TITLE
Issue with running dev server on https mode.

### ISSUE THREAD

**Issue by valiknet18** [nuxt/framework#7331]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `css`, `build`, `postcss`, `components`, `vite`, `env`, `publicRuntimeConfig`, `tailwindcss`, `server`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.9-f64c966`, `@pinia/nuxt@0.4.2`, `@nuxtjs/tailwindcss@5.3.2`, `@valentynchik/web-components@1.0.8`
- Build Modules:    `-`
------------------------------

### Reproduction

Create application with following config

```
server: {
    https: true,
},
vite: {
        plugins: [
        ],
        optimizeDeps: {
        },
        server: {
            https: true,
            hmr: {
                protocol: 'wss',
                clientPort: 443,
            }
        }
    },
```

and run
`nuxt dev --https --ssl-cert ./cert-path --ssl-key ./key-path --host=host.test --port=80`

### Describe the bug

Hey. I'm trying to run my application with enabled https and with passing path to certs in args. But application run with error 
`request to https://127.0.0.1:3000/__nuxt_vite_node__/manifest failed, reason: unable to verify the first certificate ()`
It's so strange why application try to request 127.0.0.1 in case when my app running on custom host. May be i forgot to pass any additional configs? 
I tried to google any info about this, but i didn't found anything. 
Also i've tried to do hardcode replace host in built files to right values, and test with it, but it also fails with the same error, however direct go to this link loading a page right (after replace error display right url).
I will be appreciated if anybody helps me.

**Comment by danielroe** [comment]
See note in https://github.com/nuxt/framework/pull/7271.
