### ISSUE TITLE
infinite redirects detected in rc.9, works perfectly in rc.8

### ISSUE THREAD

**Issue by noxz-dev** [nuxt/framework#7332]
### Environment

"nuxt": "3.0.0-rc.9"

### Reproduction

```ts
// middleware/auth.global.ts 

type AuthCookie = {
  accessToken: string;
  expiresIn: number;
};

export default defineNuxtRouteMiddleware((to, from) => {
  const authCookie = useCookie<AuthCookie>('x-spotify-auth');
  const isHomePath = to.path == '/';

  if (isHomePath && !authCookie.value) return;

  if (!authCookie.value?.expiresIn && !isHomePath) return navigateTo('/');

  const expired =
    new Date().getTime() - new Date(authCookie.value.expiresIn).getTime() >
    10 * 60 * 1000;

  if (!expired && from.path !== '/dashboard') {
    return navigateTo('/dashboard');
  } else if (expired) {
    authCookie.value = null;
    return navigateTo('/');
  }
});
```

### Describe the bug

I want to auto redirect the user to /dashboard if the user is logged in, the middleware works perfectly fine in rc.8 but since upgraded to rc.9 it throws an error of infinite redirects

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by noxz-dev** [comment]
Sure .. main branch is rc8 .. rc9 branch is the same code just with the rc9 version

https://github.com/noxz-dev/nuxt3-middleware-repro/tree/main

when visiting "/ " rc8 works fine, ... rc9 throws the error

**Comment by danielroe** [comment]
I think you need to change:

```diff
- if (!expired && from.path !== '/dashboard') {
+ if (!expired && to.path !== '/dashboard') {
```

It is this that causes the circular reference, because you are redirecting from `/` to `/dashboard`. This wasn't caught in rc8 because of a bug in how we processed route middleware.
