### ISSUE TITLE
NuxtConfig: `vite.build.sourcemap = "hidden"` won't output source map files.

### ISSUE THREAD

**Issue by nndnha** [nuxt/framework#7336]
### Environment

-----------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.10-27709424.bb8942a`
- Nitro Version:    `0.5.2-27709289.11cc5cd`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-wtf9vy?file=nuxt.config.ts

### Describe the bug

Build the project by running `yarn build` then run `ls .output/public/_nuxt/` to show the result files: no source map files are generated! 

It was working fine in earlier versions before [3.0.0-rc.10-27709172.ec21019](https://www.npmjs.com/package/nuxt3/v/3.0.0-rc.10-27709172.ec21019)

**Comment by 516310460** [comment]
Everything looks ok

**Comment by nndnha** [comment]
> Everything looks ok
> 
> The problem is not reproduced

![nnsm](https://user-images.githubusercontent.com/12961516/189021472-865c3820-f80d-4be7-aa41-9410206d369a.png)

There are no *.map files in the build result.

**Comment by 516310460** [comment]
Why do you want `.map`

**Comment by nndnha** [comment]
@516310460 Thanks for your instructions however I just want source map files in the 'hidden' mode https://vitejs.dev/config/build-options.html#build-sourcemap

Like I said earlier this was working fine in earlier versions, here is the one of example https://stackblitz.com/edit/github-wtf9vy-on5gic?file=package.json
