### ISSUE TITLE
vite-node server watcher not invalidating files

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#7345]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `yarn@3.2.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

This issue is not easily reproducible but I'm encountering it across apps/repos in my system.

### Describe the bug

The server SSR response does not take into account latest changes to files, often causing a hydration issue as the client response is correct.

cc: @antfu

**Comment by pi0** [comment]
(added edge because i could only reproduce on edge but might be related to previous issues)
