### ISSUE TITLE
require is not defined in ES module scope, you can use import instead

### ISSUE THREAD

**Issue by Erica-lyj** [nuxt/framework#7351]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.20.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@6.14.17`
- Builder:          `vite`
- User Config:      `css`, `runtimeConfig`, `app`, `build`, `buildModules`, `alias`, `modules`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.4.1`

### Reproduction

// package.json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "generate:dev": "nuxt generate",
    "preview": "nuxt preview",
    "lint": "eslint --ext .js,.vue,.ts --ignore-path .gitignore .",
    "lintfix": "eslint --fix --ext .js,.vue,.ts --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config-typescript": "^10.0.0",
    "@nuxtjs/proxy": "^2.1.0",
    "@typescript-eslint/eslint-plugin": "^5.35.1",
    "@typescript-eslint/parser": "^5.35.1",
    "ali-oss": "^6.17.1",
    "co": "^4.6.0",
    "eslint": "^8.23.0",
    "eslint-plugin-vue": "^9.4.0",
    "gulp": "^4.0.2",
    "less-loader": "^11.0.0",
    "nuxt": "3.0.0-rc.8",
    "path": "^0.12.7",
    "through2": "^4.0.2",
    "typescript": "^4.8.2",
    "vue-tsc": "^0.40.1"
  },
  "dependencies": {
    "@nuxt/webpack-builder": "^3.0.0-rc.8",
    "@pinia/nuxt": "^0.4.1",
    "less": "^4.1.3",
    "normalize.css": "^8.0.1",
    "pinia": "^2.0.21",
    "vue-lazyload": "^3.0.0-rc.2",
    "vuex": "^4.0.2"
  }
}

// nuxt.config.ts
import { defineNuxtConfig } from 'nuxt'

const isProduction = process.env.NODE_ENV === 'production'
const cdnUrl = 'xxxxxxx'

let config = defineNuxtConfig({
  css: [
    'assets/styles/base.less',
    'assets/styles/main.less'
  ],
  runtimeConfig: {
    public: {
      cdnUrl: isProduction ? cdnUrl : '/'
    }
  },
  app: {
    head: {
      script: [
        { src: '/script/changeRootFontSize.js', async: true }
      ],
      meta: [
        { charset: 'utf-8' },
        {
          name: 'viewport',
          content: 'width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0,viewport-fit=cover'
        },
        {
          name: 'apple-mobile-web-app-capable',
          content: 'yes'
        },
        {
          name: 'full-screen',
          content: 'true'
        },
        {
          name: 'x5-fullscreen',
          content: 'true'
        },
        {
          name: '360-fullscreen',
          content: 'true'
        }
      ]
    }
  },
  build: {
    transpile: []
  },
  buildModules: ['@pinia/nuxt'],
  alias: {
    '@vue/devtools-api': '@vue/devtools-api'
  },
  modules: []
})

// error 
<img width="895" alt="image" src="https://user-images.githubusercontent.com/57788867/189110567-1332a885-0e2e-4f7e-8be5-d20c6ceb45cf.png">

<img width="1564" alt="image" src="https://user-images.githubusercontent.com/57788867/189110686-c3b09906-b393-49c4-8daa-1147c14624aa.png">

export default config

### Describe the bug

It was no problem to run on the window yesterday, but today I changed the mac and reported this error directly

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by Erica-lyj** [comment]
> Would you provide a reproduction? 🙏

ok，i updated

**Comment by danielroe** [comment]
This is what I mean by a reproduction: https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction

**Comment by danielroe** [comment]
Having said that, from the screenshot, it looks like you have run Nuxt 2 at some point in this project. Would you remove your `.nuxt` folder and retry?

**Comment by Erica-lyj** [comment]
> Having said that, from the screenshot, it looks like you have run Nuxt 2 at some point in this project. Would you remove your `.nuxt` folder and retry?

yes, you are right.  sorry for taking up your time😢，I am working on upgrading nuxt2 to nuxt3.

**Comment by danielroe** [comment]
No problem - glad to find the issue!
