### ISSUE TITLE
Welcome component will stay when no `nuxt.config.ts` exists

### ISSUE THREAD

**Issue by manniL** [nuxt/framework#7355]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ytp3rx?file=app.vue

### Describe the bug

When you create a minimal application without a `nuxt.config.ts` (so just `app.vue` for example), the "default `app.vue`" will be shown forever.

This can only be resolved by adding back a `nuxt.config.ts` (or js)

**Comment by pi0** [comment]
Nice find! Actually, this bug seems more serious. Entire config layers are empty without a default config and it could potentially caused other issues.

**Comment by danielroe** [comment]
Presumably we want to be able to extend a theme folder without a `nuxt.config` in it? Or is that a definite requirement?

**Comment by pi0** [comment]
Currently, themes structure should have a config file to be valid layer.
