### ISSUE TITLE
Using local https breaks HMR for server-side plugins

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/framework#7356]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.10-27708028.1ca294e`
- Nitro Version:    `0.5.2-27707788.763585c`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `app`, `css`, `build`, `imports`, `modules`, `nitro`, `runtimeConfig`, `typescript`, `vite`
- Runtime Modules:  `nuxt-graphql-client@0.1.15`
- Build Modules:    `-`
------------------------------

### Reproduction

This might be hard to repro, as it involves https and self-signed certs, but if need be I can probably help set one up.
(This is fairly edge-casey)

### Describe the bug

When running the dev server in https mode with self-signed certs (`NODE_TLS_REJECT_UNAUTHORIZED=0 npx nuxi dev --https --ssl-cert localhost.crt --ssl-key localhost.key`), HMR works fine for things like components, but whenever I change a server-side plugin, the plugin won't actually be updated (even though an HMR event is triggered and sources are reloaded).

I need to restart the server to see changes in server-side plugins.

Not sure if it happens for other files too (Vue files work fine so far), I might update this issue if I find more file types that don't get properly updated.

**Comment by TheDutchCoder** [comment]
> This might be resolved by #7347.

Awesome, once it's merged I'll give it a go and report back!

**Comment by danielroe** [comment]
Merged now, if you want to give it a go 👍

**Comment by TheDutchCoder** [comment]
> Merged now, if you want to give it a go 👍

Seems to work for me now, thanks!
