### ISSUE TITLE
useFetch API breaks after page transition

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/framework#7366]
Hello,

I am facing an issue with `useFetch()` composable. I am calling my data like so :

```ts
// mypage.vue
const config = useRuntimeConfig()
const { data: images } = await useFetch<ImageKit[]>(
  'https://api.imagekit.io/v1/files',
  {
    method: 'GET',
    headers: {
      Accept: 'application/json',
      Authorization: 'Basic ' + config.IMAGEKIT_B64_API
    }
  }
)
```

When loading directly the URL `http://localhost:3000/mypage` the API is working as expected. However, when coming from another page, I have the following error :
![Safari Error](https://user-images.githubusercontent.com/85166574/189198064-3b26cce5-ddf9-4a0f-aed1-ecfde29617cb.png)
I also have a this in Firefox + Chrome
![Cors](https://user-images.githubusercontent.com/85166574/189198360-dd50ddfd-4d64-4232-a0dd-af0e52c0dbcc.png)

I tried the solution posted [here](https://github.com/nuxt/framework/discussions/4498) without success.

**Comment by danielroe** [comment]
The issue is that that API does not add the correct headers for a browser fetch request. 

See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.

**Comment by BenjaminOddou** [comment]
Thanks for your response @danielroe, is there a way to fix this problem ?
I already tried to put this in the useFetch without any success.

```ts
    headers: {
      'Access-Control-Allow-Origin': '*'
    }
```

**Comment by danielroe** [comment]
You could access it in a server route which could serve as a kind of proxy. Or check their documentation about CORS (which has to be added at their end, not yours).

You can also try removing the application/json header to make a simple request.

**Comment by BenjaminOddou** [comment]
Thank you @danielroe ! When you say `server route which could serve as a kind of proxy`, do you mean I have to create a file under `~/server/api` directory ? If that's the case, what could be the correct syntax ? 🙂

**Comment by danielroe** [comment]
Yes, that's exactly the kind of thing you could do. Up to you how to implement it; it depends a bit on your use case.

**Comment by BenjaminOddou** [comment]
@danielroe I've tied with something like this but not sure how to return `response._data`

```ts
// ~/server/api/imgkit.ts
export default defineEventHandler(async () => {
  const config = useRuntimeConfig()
  await useFetch('https://api.imagekit.io/v1/files', { // I also tried return await ...
    method: 'GET',
    headers: {
      Authorization: 'Basic ' + config.IMAGEKIT_B64_API
    },
    // eslint-disable-next-line require-await
    async onResponse({ response }) {
      return response._data
    }
  })
})
```

I've tried this without sucess 😅
```ts
// mypage.vue
const { data: images } = useFetch<ImageKit[]>('api/imgkit')
```

I've also thought about writing a `json` file on the server (with a plugin maybe ?) => not sure how to do it 

and then reference it in an API endpoint like
```ts
// ~/server/api/imgkit.ts
import stuff from '@/tmp/imgkit.json' // file written with a plugin

export default defineEventHandler(() => {
  return stuff
})
```

It's terrible to be able to see the response the first time I am calling API but not after page transition 😔

**Comment by BenjaminOddou** [comment]
> `useFetch` is a Vue composable and should not be used in your server routes. You can instead use `$fetch` directly.

oh I didn't know for that ! Now if I call `$fetch` directly in my proxy (`~/server/api/imgkit.ts`) it is working when navigating between pages but not if load the page directly 😰 This problem makes me `nu(x)ts` 😅

```ts
// mypage.vue
const { data: images } = useFetch<ImageKit[]>('api/imgkit')
console.log(images) // returning good data after HMR or page transition but returning null after full reload
```

```ts
// ~/server/api/imgkit.ts
export default defineEventHandler(async () => {
  const config = useRuntimeConfig()
  const response = await $fetch('https://api.imagekit.io/v1/files', {
    method: 'GET',
    headers: {
      Authorization: 'Basic ' + config.IMAGEKIT_B64_API
    }
  })
  return response
})
```

**Comment by danielroe** [comment]
Check the error object on full reload...

**Comment by BenjaminOddou** [comment]
I have this :

```sh
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:564:9)
    at new URL (node:internal/url:640:5)
    at new Request (file:///Users/user/Documents/nuxt_app/node_modules/node-fetch-native/dist/chunks/abort-controller.mjs:5964:16)
    at file:///Users/user/Documents/nuxt_app/node_modules/node-fetch-native/dist/chunks/abort-controller.mjs:6274:19
    at new Promise (<anonymous>)
    at fetch (file:///Users/user/Documents/nuxt_app/node_modules/node-fetch-native/dist/chunks/abort-controller.mjs:6272:9)
    at ufetch (file:///Users/user/Documents/nuxt_app/node_modules/unenv/runtime/fetch/index.mjs:6:14)
    at $fetchRaw2 (file:///Users/user/Documents/nuxt_app/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:26)
    at $fetch2 (file:///Users/user/Documents/nuxt_app/node_modules/ohmyfetch/dist/chunks/fetch.mjs:157:12) {
  input: 'api/imgkit',
  code: 'ERR_INVALID_URL'
}
```

**Comment by danielroe** [comment]
It should probably be:

```diff
- const { data: images } = useFetch<ImageKit[]>('api/imgkit')
+ const { data: images } = useFetch<ImageKit[]>('/api/imgkit')
```

**Comment by BenjaminOddou** [comment]
indeed... It's working now ! I don't know what to say... Thank you so much for your time 🙏🙏🙏. I tried so many workarounds and stuffs that I didn't remarked that. 🤦
