### ISSUE TITLE
500 error only on production(netlify)

### ISSUE THREAD

**Issue by favourwright** [nuxt/framework#7367]
### Environment

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@iconify-json/akar-icons": "^1.1.3",
    "@iconify-json/bx": "^1.1.2",
    "@iconify-json/ri": "^1.1.1",
    "@nuxtjs/tailwindcss": "^5.3.2",
    "nuxt": "3.0.0-rc.9",
    "unplugin-icons": "^0.14.3"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.1",
    "firebase": "^9.9.2",
    "xlsx": "^0.18.5"
  }
}
```

### Reproduction

https://github.com/favourwright/miunify

### Describe the bug

The only terminal error I get is ```Sourcemap for "C:/wamp1/www/miunify/node_modules/@firebase/util/dist/node-esm/index.node.esm.js" points to missing source files```

Everything **works fine on dev** environment but when deployed on **netlify**, all **GET** requests hits the custom error page.

During page navigation without reload, everything works fine(in production)

### Additional context

the error object contains:
```
error code: 500
error message: window is not defined
```

I have no reference to the window object in any part of my code
live site: https://631a3294e413af0008e7d5c2--snazzy-kitsune-cd5de8.netlify.app/

**Comment by danielroe** [comment]
This is an issue with firebase/analytics. Try this:

```diff
- nuxtApp.provide('firebase_analytics', getAnalytics(app))
+ nuxtApp.provide('firebase_analytics', process.client ? getAnalytics(app) : undefined)
```

Note there is still an issue which we can track in https://github.com/nuxt/framework/issues/7325.

**Comment by favourwright** [comment]
> This is an issue with firebase/analytics. Try this:
> 
> ```diff
> - nuxtApp.provide('firebase_analytics', getAnalytics(app))
> + nuxtApp.provide('firebase_analytics', process.client ? getAnalytics(app) : undefined)
> ```
> 
> Note there is still an issue which we can track in #7325.

Damn! that was a smooth one!🥳🕺

I can confirm that that fixed the issue. Thank you @danielroe, supper helpful
