### ISSUE TITLE
Allow type declarations from extend layers

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#7373]
Adding type augmentations from the main layer is possible using top-level `index.d.ts` (and what we [recommend in docs](https://v3.nuxtjs.org/guide/directory-structure/plugins#advanced). We could also support it for all layers for augmenting `NuxtApp` (plugin injections) and `AppConfigInput` (`app.config` from themes).

**Comment by pi0** [comment]
What do you think @danielroe?

**Comment by danielroe** [comment]
I think it's a nice idea (and possibly worth implementing), but I think there are better solutions to consider first:

1. **Use other files**. Any declarations you add in any file within the layer that is used in the nuxt build should already work for this purpose, and in fact I would personally recommend co-locating the definition with the usage.
2. **Prefer inference**. For example, plugins or app config can work this way.

For app config, the following might do it (though I haven't yet tested):

```js
export default defineAppConfig({
  myTheme: {} as Partial<MyThemeConfig>
})
```

**Comment by pi0** [comment]
1. I initially thought too and suggested https://github.com/nuxt-themes/starter/issues/6 that similar to modules we define in `module.ts`, use `app.config`. I guess it should already work since we are importing their types right?
2. For plugin injections, using inference is nice but the purpose of the declaration is when we don't want it for any reason (simplest: not using type script or module-builder for plugins). 

In both cases, I'm thinking since is possible to use `index.d.ts` from top level, would be nice if we make same possibility for all layers.

**Comment by danielroe** [comment]
Allow `index.d.ts` as an escape hatch seems good, but I would recommend instead augmenting plugin types within the plugin file, which means that the type is conveniently next to the implementation.
