### ISSUE TITLE
Autoimported components (~~/.nuxt/components) are not reliable code-wise

### ISSUE THREAD

**Issue by Tails128** [nuxt/framework#7379]
### Environment

➜ npx nuxi info
Nuxi 3.0.0-rc.9                                                                                                                               11:55:40
RootDir: /Users/angurias/Developer/helium/sp-product-frontend-2                                                                               11:55:42
Nuxt project info:                                                                                                                            11:55:42

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `ssr`, `typescript`, `srcDir`, `modules`, `css`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.3`
- Build Modules:    `-`
------------------------------

### Reproduction

- Have lots of components
- Try to import lots of components (not necessarily all of them) via code in a ts file E.G:
```
import {
    IconBasicArrowBottomSmall,
    IconBasicArrowDown,
    IconBasicArrowLeftSmall,
    IconBasicArrowLeft,
    IconBasicArrowRightSmall,
    IconBasicArrowRight,
    IconBasicArrowTopSmall,
    IconBasicArrowTop,
    IconBasicCalculator,
    IconBasicCalendar,
    IconBasicCheck,
    IconBasicDashboard,
    IconBasicEdit,
    IconBasicEnter,
    IconBasicExit,
    IconBasicHelp,
    IconBasicHide,
    IconBasicShow,
    IconBasicTrash,
    IconBasicUpload,
    IconBasicAlertCircle,
    IconBasicCarretDown,
    IconBasicCarretLeft,
    IconBasicCarretRight,
    IconBasicCarretUp,
    IconBasicCheckCircle,
    IconBasicComment,
    IconBasicCreditCard,
    IconBasicDots,
    IconBasicErrorCircle,
    IconBasicHome,
    IconBasicInfoCircle,
    IconBasicLockClose,
    IconBasicLockOpen,
    IconBasicMoney,
    IconBasicPlusCircleLight,
    IconBasicPlus,
    IconBasicSlider,
    IconBasicTimesCircleLight,
    IconBasicTimesCircle,
    IconBasicTimes,
    IconCalendarCopy,
    IconCalendarModFreeze,
    IconCalendarModMarkup,
    IconCalendarModMax,
    IconCalendarModMin,
    IconCalendarEuroSmall,
    IconCalendarMinusSmall,
    IconCalendarPercentSmall,
    IconCalendarPlusSmall,
    IconCalendarUserAlt,
    IconCalendarUser,
    IconDashboardBarGraph,
    IconDashboardLineGraph,
    IconLangDe,
    IconLangEn,
    IconLangIt,
} from '~~/.nuxt/components'
```

(In my specific case I'm making a `Map` containing them)

### Describe the bug

Multiple errors can be triggered:
 1. Sometimes it will compile, but an error stating the import is not an html will be triggered
 2. Sometimes it will fail before compile time, stating that one (or multiple) of the components needs to be initialized

**Comment by danielroe** [comment]
You should not import from `~/.nuxt/components` but from `#components` if you need to import explicitly. Does that make a difference?

**Comment by Tails128** [comment]
@danielroe while it solves the issue it creates a series of different issues:

- "cannot find module or its corresponding declarations"
- issues with the autoimport(s)
- having to manually import every file anyway as nuxt's naming is defined by path

**Comment by danielroe** [comment]
If you are experiencing problems importing from `#components`, please provide a reproduction and I'll happily look at it.

**Comment by Tails128** [comment]
Just to get on the same page:

do you mean something as:
```
import aComponent from '~/components/AComponent'
```

or is there something I'm missing?

**Comment by danielroe** [comment]
No, I mean:

```js
import { IconBasicHelp } from '#components'
```

**Comment by then3rdman** [comment]
Sorry to jump in on an issue butt i think there is a related issue potentially. 

Importing thecomponents explicitly from `#components` works however when trying to use the import as a type, the `typeof` opperator is required. explicitly importing as type doesnt seem to work either, eg

```ts
import type { LayoutHamburger } from '#components'
```

Maybe I am missunderstanding something but as the components are exported as typeof, should i not be able to consume them as such?

**Comment by danielroe** [comment]
I'm closing this but if you are experiencing a bug please do let me know with a reproduction and I'll reopen it.

FYI, there is this known issue, which we will resolve soon: https://github.com/nuxt/framework/issues/7085.
