### ISSUE TITLE
Missing JSDocs for nuxt3 Composables

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#739]
We don't have docs for: `useAsyncData`, `useState` and `useFetch`

**Comment by f3ltron** [comment]
Just to be sure here you mean inside `packages/nuxt3/src/app/composables` ?  I can see some already but not for all of them

**Comment by ennioVisco** [comment]
Not very relevant anymore, I'd recommend to close this in favor of https://github.com/nuxt/framework/issues/4104. cc @pi0
