### ISSUE TITLE
Functional Component has type 'any'

### ISSUE THREAD

**Issue by f3oall** [nuxt/framework#7401]
### Environment

nuxi info
------------------------------
- Operating System: `Linux`
- Node Version:     `v18.8.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.18.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

VSCode + Volar + TakeOver mode 4.8.2

### Reproduction

https://github.com/f3oall/nuxt3-functional-component

### Describe the bug

Autoimported Functional Components have type 'any'.

You can see that I explicitly typed component in reproduction. If it's not a bug and I'm doing something wrong, explanation is welcome.

Screenshot:

![image (2)](https://user-images.githubusercontent.com/1751835/189456655-1805afd0-16aa-4698-886e-42adaa7c3fb9.png)

**Comment by danielroe** [comment]
Have you tried without Nuxt, or via an explicit import, to see whether this is an issue with Volar?

**Comment by f3oall** [comment]
I tried explicit import and it works as expected.

**Comment by danielroe** [comment]
It does not seem to work (in template) with explicit import, meaning this is a Volar issue rather than a Nuxt one:

![CleanShot 2022-09-12 at 11 06 54](https://user-images.githubusercontent.com/28706372/189628041-ff55ec6d-48da-4b19-ae0b-c184ce5d16a5.png)

Would you [raise an issue there](https://github.com/johnsoncodehk/volar)?

**Comment by f3oall** [comment]
Sure, will do that. Thanks!

**Comment by xiaoxiangmoe** [comment]
@danielroe See 
![image](https://user-images.githubusercontent.com/8111351/191176307-a7705486-0830-4604-b1dc-74758b4725e8.png)

If we change 
`'Functional': typeof import("../components/Functional.ts")['default']`
to
`'Functional': typeof import("../components/Functional")['default']`

![image](https://user-images.githubusercontent.com/8111351/191176483-0a056818-6f00-4560-9842-3384886c81d3.png)

This will works well.
