### ISSUE TITLE
Adding full programmatic (non file based) routing functionality for server app

### ISSUE THREAD

**Issue by cpt-n3mo** [nuxt/framework#7405]
### Describe the feature

 [this](https://github.com/nuxt/framework/issues/4235) solution is not perfect.
it would be nice if one would have access over the app instance that is created by nuxt. or be able to push one of your own, so that it merges with the one nuxt creates,

this would allow one to  `app.use("someBase", someRouter)`  as the h3 docs say.
this makes it allot cleaner to create multiple nested routes with different basses.

as for the solution/workaround above one would need to add the base the the actual request. as
exporting `useBase("someBase",someRouter)`
 
will not work with multiple bases, as exporting a array with multiple bases and routers  will only take the first in the array dropping the rest, this might be also be a solution, allowing for a array of handlers be exported not just a single function. 

when one creates a app instance using 
```javascript
const app = createApp()
const router = createRouter()
app.use("/api/items/item1",router1)
app.use("/api/items/item2",router2)
```
one can have full control but, this seems to overwrite the default completely and will not allow for file based routing anymore from the server directory.

so in general it would be nice to have  a bit more control over the router, file based is very nice but it makes it quite annoying to do anything programmatically, like creating crud routes for multiple items, from a single file like shown above.

kind regards  

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by cpt-n3mo** [comment]
as usual just after one posts a issue..
it seems that its already possible to do this, while not documented, after allot of tinkering it seems when on does the following,,

`/some/file/location.ts`
```javascript

const app = createApp()
const router = createRouter()

...

app.use("itemAPI/item1",router1)
app.use("itemAPI/item2",router2)
app.use("itemAPI/item3",router3)

export default app

``` 

`nuxt.config.ts`
```javascript
export default defineNuxtConfig({
  serverHandlers:[
    {
      route: "/itemAPI/**",
      handler: 'above/handler/location.ts',
    }
  ]
})
```

this keeps the file based routing intact and allows for full programmatic route creation.

**Comment by danielroe** [comment]
You can also use a nitro plugin to interact directly with `router` and `app`:  see https://github.com/nuxt/framework/issues/5527#issuecomment-1160789814.
