### ISSUE TITLE
definePageMeta not working

### ISSUE THREAD

**Issue by nazar1ua** [nuxt/framework#7415]
### Environment

❯ npx nuxi info
Nuxi 3.0.0-rc.9
RootDir: /home/projects/nuxt-color-mode-gqmr51
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/color-mode@3.1.5`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

https://stackblitz.com/edit/nuxt-color-mode-gqmr51?file=pages/index.vue

### Describe the bug

In terminal, you can see, that `route.meta.title` is `Hello`, but
![image](https://user-images.githubusercontent.com/74293442/189531655-79c322f7-9dbb-43f3-8e19-348b80780f21.png)

### Logs

```shell
❯ npm install && npm run dev
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/4] 🔍  Resolving dependencies
└ Completed in 0.931s
┌ [2/4] 🚚  Fetching dependencies
│ info pruneDeps Excluding 25 dependencies. For more information use
│ `--verbose`.
└ Completed in 0.004s
┌ [3/4] 🔗  Linking dependencies
└ Completed in 0.007s
info security We found `install` scripts which turbo skips for security
Nuxi 3.0.0-rc.9
Nuxt 3.0.0-rc.9 with Nitro 0.5.1

  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.104:3000/

ℹ Vite server warmed up in 1492ms
✔ Nitro built in 4772 ms
ℹ Vite client warmed up in 16611ms
Hello
Hello
Hello
Hello
```

**Comment by TheDutchCoder** [comment]
I can confirm this issue on the latest edge version too (Nuxt 3.0.0-rc.10-27710784.e22bbcc)

**Comment by danielroe** [comment]
`definePageMeta` sets metadata associated with a route but does not affect head tags. You can use them together but that is up to you: http://v3.nuxtjs.org/guide/features/head-management/#example-usage-with-definepagemeta.

**Comment by nazar1ua** [comment]
Thanks
