### ISSUE TITLE
nuxt.generate.routes with function returning promise

### ISSUE THREAD

**Issue by kakka0903** [nuxt/framework#7424]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@6.14.17`
- Builder:          `vite`
- User Config:      `generate`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

[repo with minimal reproduction](https://github.com/kakka0903/nuxt3-generate-routes-issue)

### Describe the bug

[The Nuxt2 docs](https://nuxtjs.org/docs/configuration-glossary/configuration-generate/#function-which-returns-a-promise) as well as the [config schema file in Nuxt3](https://github.com/nuxt/framework/blob/main/packages/schema/src/config/generate.ts) explain that the `nuxt.generate.routes` config option can be given a function that returns a promise.

> You can pass a function that returns a promise or a function that takes a callback. It should return an array of strings or objects with `route` and (optional) `payload` keys.

However when running `npx nuxi generate` the following error is raised:
```
ERROR  nuxt.options.generate.routes is not iterable
```

### Additional context

Unlike the (Nuxt2 config schema)[https://github.com/nuxt/nuxt.js/blob/dev/packages/types/config/generate.d.ts]
```js
routes?: NuxtOptionsGenerateRoute[] | NuxtOptionsGenerateRoutesFunction | NuxtOptionsGenerateRoutesFunctionWithCallback
```

the [current one](https://github.com/nuxt/framework/blob/main/packages/schema/src/config/generate.ts) seems to only accept arrays?
```js
routes: [],
```

### Logs

```shell
$ npx nuxi generate
Nuxi 3.0.0-rc.9                                                                                                                                
Nuxt 3.0.0-rc.9 with Nitro 0.5.1                                                                                                               

 ERROR  nuxt.options.generate.routes is not iterable                                                                                           

  at initNitro (node_modules/nuxt/dist/index.mjs:1324:81)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1559:3)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:1581:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:714:19)
  at async Object.invoke (node_modules/nuxt/node_modules/nuxi/dist/chunks/build.mjs:33:18)
  at async Object.invoke (node_modules/nuxt/node_modules/nuxi/dist/chunks/generate.mjs:31:5)
  at async _main (node_modules/nuxt/node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by marcel-wtfoxtrot** [comment]
Hi @kakka0903 

You should be using a hook instead. Try this:
`
hooks: {
        'nitro:config': async function extendNitroConfig(nitroConfig) {
            const addRoute = (route) => {
                if (!nitroConfig.prerender.routes.includes(route)) {
                    nitroConfig.prerender.routes.push(route)
                }
            }

            const res = await axios.get('https://tools.learningcontainer.com/sample-json.json').then((res) => {
                res.data.phoneNumbers.forEach((number) => addRoute(`/${number.type}`))
            })
        },
    }`

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/4919.

**Comment by kakka0903** [comment]
Thanks guys! The hook worked great.
