### ISSUE TITLE
dependency missing in latest caniuse-lite

### ISSUE THREAD

**Issue by usulix** [nuxt/framework#7425]
### Environment

Nuxi 3.0.0-rc.9
RootDir: /home/projects/aoninxprq.github
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Create a new project on stackblitz
install the latest caniuse-lite
run npm run dev
see fatal error

![Uploading Screen Shot 2022-09-11 at 4.32.45 PM.png…]()

### Describe the bug

https://github.com/Fyrd/caniuse/commit/40a057c6a865d7b1587a5c8701edec84bc3de91c removes css-unicode-bidi from the caniuse-db

the latest caniuse-lite ingests the caniuse-db changes

this causes the build to fail

### Additional context

May be a non-issue as maintainers at caniuse-lite say they may fix it.

Here is the issue there if you care to monitor.

https://github.com/browserslist/caniuse-lite/issues/100

**Comment by warflash** [comment]
The maintainers of the dependency already fixed the issue here: https://github.com/postcss/autoprefixer/commit/07c3cf10a297419d7747c9238a8dfa6c37e8e484. 
You might have to remove your package-lock and or node_modules
