### ISSUE TITLE
Only file and data URLs are supported by the default ESM loader

### ISSUE THREAD

**Issue by warflash** [nuxt/framework#7426]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.9`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `css`, `build`, `nitro`, `modules`, `i18n`, `vite`, `sourcemaps`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-alpha.1-27710980.d1ee9d2`, `@pinia/nuxt@0.4.2`, `~/modules/localeRegionRoutes`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/warflash/nuxt_7426

### Describe the bug

I tried updating from rc8 to rc9 today and got the error message below when trying to start in dev mode.
Tried deleting .nuxt, node_modules as well as package-lock.json to get a fresh install but it all resulted in the same error. Same story for edge rc10. 

### Additional context

Possibly related: https://github.com/nuxt/framework/issues/6146
### Logs

```shell
500
Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'f:'

at new NodeError (node:internal/errors:371:5)
at defaultResolve (node:internal/modules/esm/resolve:1016:11)
at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
at ModuleWrap. (node:internal/modules/esm/module_job:76:40)
at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

(I realise it might not reproduce in stackblitz, but a minimal repository you have verified has this behaviour on your machine would be helpful.)

**Comment by warflash** [comment]
@danielroe Seems like the issue comes from some weird interactions between ^rc.9 and nuxt-i18n.
Heres the repro that throws the same error mentioned above on my windows machine: https://github.com/warflash/nuxt_7426.
The nuxt config here https://github.com/nuxt/framework/issues/6146 also mentions using i18n so my guess would be that those are related

**Comment by warflash** [comment]
fyi the issue also persists with rc.10, sort of expected but figured I'd mention it

**Comment by danielroe** [comment]
Nice spot. This is a bug in i18n; it generates some code with an absolute import:

```js
import locale_en from "C:/nuxt_7426/locales/en.json";
export const localeCodes = ["en"]

export const localeMessages = {
  "en": () => Promise.resolve(locale_en),
}
```

This needs to be instead:

```js
import locale_en from "file:///C:/nuxt_7426/locales/en.json";
export const localeCodes = ["en"]

export const localeMessages = {
  "en": () => Promise.resolve(locale_en),
}
```
