### ISSUE TITLE
TS2307: Cannot find module '#imports' or its corresponding type declarations. with webstorm

### ISSUE THREAD

**Issue by simllll** [nuxt/framework#7434]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.19.1`
- Builder:          `vite`
- User Config:      `srcDir`, `typescript`, `head`, `loading`, `css`, `middleware`, `runtimeConfig`, `tailwindcss`, `modules`, `env`, `build`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.3`, `~/modules/dashboardcore.ts`, `~/modules/auto-import-eslint.ts`
- Build Modules:    `-`
------------------------------

### Reproduction

as this is IDE related, there is no classical reproduction script possible. But it happens also with a plain nuxt3 project.
What I have in my setup:
```
#tsconfig.json 
{
        "extends": "./.nuxt/tsconfig.json",
        "compilerOptions": {
                "resolveJsonModule": true,
    "noImplicitAny": false,
                "paths": {
                        "~/*": ["src/*"],
                        "@/*": ["src/*"]
                },
                "types": ["@nuxt/types"]
        },
        "exclude": ["node_modules", "cypress"]
}

```

.nuxt/tsconfig.josn even has paths in it with "#imports":
![image](https://user-images.githubusercontent.com/5757263/189610541-05d97d6f-ca93-4ffc-bcbb-79f4abd3afcd.png)

### Describe the bug

IDE doesn't resolve types anymore:
![image](https://user-images.githubusercontent.com/5757263/189610613-a62a53b0-5e60-457a-a9d0-a85f08d600b8.png)

the funny thing is, if  open the imports.d.ts, types are working in there. So it seems it's just not picking up the initial tsconfig settings. Maybe an IDE bug?

### Additional context

tested in WebStorm 2022.2.1
Build #WS-222.3739.57, built on August 16, 2022
also restarted the typescript engine and other stuff,

**Comment by simllll** [comment]
Okay, and just by opening a bug report, I found my issue ;-) I still had paths overwritten in my tsconfig. Removing this, fixes the issue ;-)

my tsconfig is now just:
```
{
	"extends": "./.nuxt/tsconfig.json",
	"compilerOptions": {
		"resolveJsonModule": true,
		"noImplicitAny": false
	},
	"exclude": ["node_modules", "cypress"]
}

```

**Comment by zoujiawei6** [comment]
I have a different situation, my directory structure is "~/nuxt/demo1":

1. This error was also generated when I opened the "~/nuxt/" directory in vscode;
2. But when I open "~/nuxt/demo1" directory in vscode, it works fine.

nuxtjs/i18n: useI18n(), useLocalePath()
