### ISSUE TITLE
current working directory (__dirname and process.cwd()) etc has different results in dev and build mode

### ISSUE THREAD

**Issue by simllll** [nuxt/framework#7441]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.19.1`
- Builder:          `vite`
- User Config:      `srcDir`, `typescript`, `head`, `loading`, `css`, `middleware`, `runtimeConfig`, `tailwindcss`, `modules`, `env`, `build`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.3`, `~/modules/dashboardcore.ts`, `~/modules/auto-import-eslint.ts`
- Build Modules:    `-`
------------------------------

### Reproduction

I'm trying to load a file which is placed in the current working directory (the path where I execute the command):

```
// take 1
const __dirname = url.fileURLToPath(new URL('.', import.meta.url));
// take 2
const __dirname = process.cwd();
console.log('__dirname', __dirname);
const currentStateFilePath = resolve(__dirname, 'last-state');

```

this works in dev mode, but when building it resolved to differnt paths

### Describe the bug

**const __dirname = url.fileURLToPath(new URL('.', import.meta.url));**

resolves to: 
```
dev: /home/simon/Dev/hokify/hokify-dashboard/src/modules <-- I could work with that
build: / <-- ?

```

**const __dirname = process.cwd();**
resolve to:
```
dev: /home/simon/Dev/hokify/hokify-dashboard <-- correct (y)
build: /home/simon/Dev/hokify/hokify-dashboard/.output <-- .output?

```

differnt behaviour between dev and build mode is not ideal, is there any (internal) helper that returns the current working directory?

**Comment by danielroe** [comment]
In general you should not rely on the directory structure of your deployed project, as this is an implementation detail that may change. But there may be some other possible solutions. What kind of file are you trying to access? Is this within your Vue app or a nitro endpoint?

**Comment by simllll** [comment]
I see, 
it's a "state" file which is only accessed by the server (nitro), and then sent to the client via api endpoint and/or a socket.io stream.

I agree, a cleaner solution would be some sort of database, but I can think of other situations where this is more relevant..e.g. by allowing the user some config files that can be used when starting an app.

**Comment by danielroe** [comment]
I think maybe using `useStorage()` in your app would be best - see https://nitro.unjs.io/guide/introduction/storage. You can use a fs-driver.
