### ISSUE TITLE
Server (Nitro) routes should match trailing slash in path by default

### ISSUE THREAD

**Issue by maaattg** [nuxt/framework#7458]
### Describe the feature

Nuxt 3 server routes should ideally match trailing slashes by default, since this would be consistent with [the default Vue Router behaviour](https://nuxtjs.org/docs/configuration-glossary/configuration-router/#trailingslash). For example, a route `/server/routes/hello.ts` should be reachable at both `/hello` and `/hello/`.

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by hecktarzuli** [comment]
@danielroe if this gets attention, would this work with catchalls as well?
`/api/homes/[..].js` would match `/api/homes/user` and `/api/homes` ?
Currently, only the first one matches the catchall with RC11.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

Let me know if not and I'll reopen.

@hecktarzuli No, the catchall does not match `/api/homes` or `/api/homes/`, only `/api/homes/{slug}`

**Comment by pi0** [comment]
Ref: https://github.com/unjs/radix3/pull/17

**Comment by tobiasdiez** [comment]
I can confirm this is fixed indeed. Thanks a lot!
