### ISSUE TITLE
Error occurs when enabling https on dev in Nuxt3

### ISSUE THREAD

**Issue by cwe-spb** [nuxt/framework#7468]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `telemetry`, `build`, `modules`, `components`, `vueuse`, `runtimeConfig`, `vite`
- Runtime Modules:  `@vueuse/nuxt@9.2.0`, `@pinia/nuxt@0.4.0`
- Build Modules:    `-`
------------------------------

### Reproduction

after update project to v3.0.0-rc.9 problem inited

### Describe the bug

I use composable useFetch

```
[nuxt] [request error] [unhandled] [500] fetch failed ()
  at async $fetchRaw2 (/D:/project/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
  at async /D:/project/.nuxt/dev/index.mjs:2411:20
  at async /D:/project/.nuxt/dev/index.mjs:2472:64
  at async /D:/project/.nuxt/dev/index.mjs:135:22
  at async /D:/project/node_modules/h3/dist/index.mjs:492:19
  at async nodeHandler (/D:/project/node_modules/h3/dist/index.mjs:438:7)
  at async ufetch (/D:/project/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async $fetchRaw2 (/D:/project/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
  at async Object.errorhandler [as onError] (/D:/project/.nuxt/dev/index.mjs:383:16)
  at async nodeHandler (/D:/project/node_modules/h3/dist/index.mjs:445:9)
```

### Additional context

same issue in ohmyfetch:
https://github.com/unjs/ohmyfetch/issues/120

**Comment by palaxius** [comment]
Same problem

**Comment by BlackHunfer** [comment]
Same problem

**Comment by staneque** [comment]
Same for me running freshly initialised project with local certificates

**Comment by danielroe** [comment]
Have you enabled `NODE_TLS_REJECT_UNAUTHORIZED=0`? https://v3.nuxtjs.org/api/commands/dev/#nuxi-dev

**Comment by rnenjoy** [comment]
Upgraded to the latest nuxt rc 11 via edge channel but still getting this error. And its a letsencrypt cert, not a self signed one.

**Comment by danielroe** [comment]
Would you open a new issue with reproduction? 🙏

**Comment by rnenjoy** [comment]
Adding NODE_TLS_REJECT_UNAUTHORIZED=0  worked. Weird, i thought it wasnt for me since i didnt use a self signed cert. I'll try with a reproduction. But im a bit of a n00b, and dont know how to do a reproduction with my certs.
