### ISSUE TITLE
pick option documentation

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/framework#7516]
Hello,

I am currently struggling with the `pick` option of `useFetch()`. I am returning an array of objects from an API with lot of properties and I'd like to only pick some of them as I don't need them all.

```json
[
  {
    "type": "file",
    "name": "0086.webp",
    "tags": [ "test", "*" ],
    "AITags": null,
    "filePath": "/0086.webp",
    "mime": "image/webp"
  }, {}
]
```

the following syntax is returning an error. Is this the correct way to do it ? There is not lot of documentation / example about this.

```ts
const { data: images } = useFetch<ImageKit[]>('/api/imgkit', {
  pick: ['filePath', 'name', 'tags']
})
```

**Comment by danielroe** [comment]
`pick` picks properties of a single object. Instead, you can use `transform` to do whatever you need.
