### ISSUE TITLE
`<ClientOnly>` with `<template #fallback>` always results in hydration error in RC10

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/framework#7517]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-kmye2r?file=components%2FTestThing.vue,components%2FTestThing2.vue,app.vue

### Describe the bug

When using a ClientOnly component with a fallback templates, as described in the docs, you will always get hydration errors.

**Comment by danielroe** [comment]
For now, you can workaround by setting:

```js
export default defineNuxtConfig({
  experimental: {
    treeshakeClientOnly: false
  }
})
```
