### ISSUE TITLE
Add `"vite/client"` to tsconfig.json

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/framework#7529]
### Describe the feature

Static asset imports (like images) result in TS errors (in the IDE) if this is not defined in the tsconfig.
Would be good to include it (at least for those that use Vite).

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/5351.
