### ISSUE TITLE
Default layout styles are getting ignored in app.vue

### ISSUE THREAD

**Issue by TechAkayy** [nuxt/framework#7531]
### Environment

------------------------------ From the stackblitz repo
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
------------------------------On my local laptop
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-2svdvu?file=app.vue

### Describe the bug

Styles from default layout gets ignored in app.vue. Only way the styles show up is by adding NuxtWelcome to app.vue. 

Once the app is up and running in the repo, in app.vue, uncomment NuxtWelcome and you can see the styles restored. 

Please advise if I'm missing any nuxt rules/conventions w.r.t layouts.

**Comment by danielroe** [comment]
As you can see, the style properties are applied and respected by the browser.

![CleanShot 2022-09-15 at 09 34 35](https://user-images.githubusercontent.com/28706372/190356344-2172b77c-e88c-4cba-9b76-84aced4b825a.png)

You're missing `border-style: solid` I think.
