### ISSUE TITLE
__vite_ssr_import_2__.createMemoryHistory is not a function on RC.9 RC.10

### ISSUE THREAD

**Issue by pinnnguyen** [nuxt/framework#7532]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.9.0`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `0.5.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `ssr`, `components`, `nitro`, `css`, `modules`, `runtimeConfig`, `googleAnalytics`, `vueuse`, `windicss`
- Runtime Modules:  `nuxt-icon@0.1.5`, `nuxt-windicss@2.5.2`, `nuxt-full-static@0.2.1`, `@nuxt/image-edge@1.0.0-27719579.87dcdf2`, `@pinia/nuxt@0.4.2`
- Build Modules:    `-`
- Device: Mac M1
- Homebrew 3.6.1
------------------------------

### Reproduction

- git clone https://github.com/viandwi24/nuxt3-awesome-starter.git
- yarn install
- yarn dev

### Describe the bug

no response

### Additional context

no response

### Logs

```shell
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_2__.createMemoryHistory is not a function
  at ./node_modules/nuxt/dist/pages/runtime/router.mjs:42:256  
  at fn (./node_modules/nuxt/dist/app/nuxt.mjs:128:27)  
  at Object.callAsync (/Users/bonn/Documents/node_modules/unctx/dist/index.mjs:49:19)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:130:23)  
  at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:74:29)  
  at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:84:11)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)  
  at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:18)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
```

**Comment by danielroe** [comment]
What version of vue-router do you have in your node_modules?

Would you provide a reproduction please? 🙏

**Comment by pinnnguyen** [comment]
@danielroe 1. git clone `https://github.com/viandwi24/nuxt3-awesome-starter.git`
2.yarn install
3. yarn dev
This only happens on mac M1
Package manager: yarn@1.22.19
Node: v16.14.2

**Comment by richardeschloss** [comment]
This can also be reproduced easily if you have Nuxt2 in a root project, and Nuxt3 in a yarn workspace.  (Below example uses yarn 3.2.3, but the issue was also observed on yarn 1.2.2)

Project root: 
```js
{
 ..., 
 "workspaces": {
    "packages": [
      "./src3" // see below
    ]
  },
  "dependencies": {
    "nuxt": "^2.15.8"
  }
}
```

"./src3" workspace:
```js
{
  "name": "src3",
  "dependencies": {
    "nuxt": "npm:nuxt3@latest" // Nuxt 3.0.0-rc.11-27720979.b933015 with Nitro 0.5.4-27719614.c3af02d
  },
  "nmHoistingLimits": "workspaces", // Limit the hoisting to the workspace
  "installConfig": {
    "hoistingLimits": "workspaces"
  },
  "scripts": {
    "dev": "nuxi dev"
  }
}
```

The error is reproducible if there is a page in "src3/pages/index.vue". 

---

A natural question: why might people structure their project like this? They may have a Nuxt 2 app, but want to have a experimental workspace for Nuxt3 stuff. This could be a fast way to switch between the two frameworks.

**Comment by richardeschloss** [comment]
FWIW, I was able to get to a working state, even though my solution may not be reliable because it relies on experimental node features to work:

I had to enable `import.meta.resolve` and use the following experimental loader to ignore node_modules that would be part of the parent's dependencies:

./src3/customLoader.js
```js
import { resolve as pResolve } from 'path';

const parentDir = pResolve('..');
const ignoreDir = `file://${parentDir}/node_modules`;

export async function resolve(specifier, context, nextResolve) {
  let localPkg
  if (specifier.startsWith(ignoreDir)) { // If the dep is tin the parent...
    const pkg = specifier.match(/node_modules\/([^\/]+)\//)[1] // pull out the pkg name...
    localPkg = await import.meta.resolve(pkg).catch(() => {}) // and only use the local one, not the parent's
  }
  return nextResolve(localPkg || specifier); // return the local one if found, otherwise carry on...
}
```

> cd src3
> export NODE_OPTIONS="--experimental-import-meta-resolve --experimental-loader=./customLoader.js"
> yarn nuxi dev # loads with the experimental node features now.

**Comment by richardeschloss** [comment]
Is there a way to control `vite_node`'s search to include just the workspace and not the parent?

**Comment by pi0** [comment]
We might tune `options.node_modules`. @richardeschloss is it possible to make a github repo with above setup of nuxt 2 + nuxt 3 in same monorepo?

**Comment by pi0** [comment]
Let's move it to https://github.com/nuxt/framework/issues/7609. @richardeschloss nice guess about `vite-node` issue 💚
