### ISSUE TITLE
Nitro azure-functions png file issue

### ISSUE THREAD

**Issue by markgibbons25** [nuxt/framework#7533]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/vigilant-orla-7k8swr?file=/app.vue

1. Deploy above repro to azure functions - follow https://nitro.unjs.io/deploy/providers/azure#azure-functions
2. The navigate to the site /favicon-32x32.png file

Expected:
The file is displayed in browser

Actual:
502 Bad Gateway

### Describe the bug

Not sure if it is a particular problem with this png file but it works fine on my local machine. It is only a problem when nitro builds and is hosted on azure functions.

**Comment by danielroe** [comment]
Let's track in https://github.com/unjs/nitro/issues/100.
