### ISSUE TITLE
console errors occur when build with no-ssr mode

### ISSUE THREAD

**Issue by kaaaanon** [nuxt/framework#7542]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `ssr`, `target`, `app`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. create a new project by using `npx nuxi init nuxt-app`
2. edit nuxt.config.ts as below
```
import { defineNuxtConfig } from 'nuxt'
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  ssr: false,
  target: 'static',
  app: {
    baseURL: '/',
  }
})
```
3. `npm run build`
4. deploy `.outopt/public/*` on web server root (linux server using Apache)

### Describe the bug

When accessing the server on the browser, no contents are shown on the page and I can see several errors.
```
GET https://example.com/index.html/_payload.js net::ERR_ABORTED 404
```
```
Refused to apply style from 'https://example.com/_nuxt/entry.3571d144.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
```
entry.7d6d0124.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'baseURL')
    at fa (entry.7d6d0124.js:1:65263)
    at entry.7d6d0124.js:1:100806
```

Is there any miss-settings on the nuxt.config.ts?

### Additional context

I could deploy by the same way until `3.0.0-rc.5`.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) via https://github.com/nuxt/framework/pull/7535.

**Comment by danielroe** [comment]
Confirmed, the other issues are also resolved. 👍

**Comment by kaaaanon** [comment]
@danielroe 
Thank you for confirmation.  
Does it mean all issues will be resolved on the next release?  
(I am worried that my configuration is wrong.)

**Comment by danielroe** [comment]
Yes, they will, and you can also try it out now on the edge channel (docs in previous comment).

**Comment by kaaaanon** [comment]
Understand! Thank you!
