### ISSUE TITLE
can't install Nuxt 3, npx nuxi init nuxt3-test gives 'ERROR  No such built-in module'

### ISSUE THREAD

**Issue by v3nt** [nuxt/framework#7558]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.20.0`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `npm@6.14.17`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

run `npx nuxi init nuxt3-test-02` and you will get errors immediately.

```
ERROR  No such built-in module: node:stream/promises                                                                14:04:11

  at new NodeError (internal/errors.js:322:7)
  at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11)
  at new ModuleJob (internal/modules/esm/module_job.js:63:26)
  at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)
  at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)
  at async Promise.all (index 17)
  at async link (internal/modules/esm/module_job.js:83:9)
```

### Describe the bug

can't setup a Nuxt 3 project

**Comment by danielroe** [comment]
Would you try `npx nuxi@latest init nuxt3-test-02`? I think you may have an outdated version of nuxi in your npm cache.

**Comment by jxlstudio** [comment]
> npx nuxi@latest init nuxt3-test-02

Having the same issue and tried your command. Did not work.

**Comment by danielroe** [comment]
Thank you for this. Raised an upstream issue at https://github.com/unjs/giget/issues/17.

**Comment by brocard** [comment]
News?

**Comment by danielroe** [comment]
You can work around by using node 16+, and track upstream issue in previous comment.

**Comment by kazuki-komori** [comment]
It works well by using node 16+

you should try
```sh
volta install node@16
```

**Comment by brocard** [comment]
that's the problem many guys still using node 14+ as LTS and as default

**Comment by danielroe** [comment]
We are very aware, and this issue will be fixed in the next RC.

**Comment by pi0** [comment]
@danielroe is there any unfixed issue?

**Comment by danielroe** [comment]
No. Only assigned to myself to remember to close it when RC is released.

**Comment by danielroe** [comment]
This should be resolved in rc11.

**Comment by pi0** [comment]
A side note: Please consider moving from 14 to 16. We will start soft deprecating 14.x soon. https://github.com/nuxt/framework/issues/7648
