### ISSUE TITLE
[rc.10] static payload replaces current state

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#7562]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Minimal: https://stackblitz.com/edit/github-vz4xcz-wjzklq?file=app.vue,nuxt.config.ts (updated v3)

Original reproduction by @Atinux with content module: https://github.com/Atinux/nuxt-dd-bug

### Describe the bug

With https://github.com/nuxt/framework/pull/6455, we extract page payloads and assign new state on navigation. This overrides any previous `useState` value with new one. We could instead support a merging strategy or by default avoid **overriding** any initialized state. or introduce an explicit composable for it https://github.com/nuxt/framework/issues/7568 (useData)

**Comment by pi0** [comment]
@Floppy012 It is fixed via https://github.com/nuxt/framework/pull/7535

**Comment by danielroe** [comment]
@Floppy012 It is a different issue, but already resolved on the edge channel.
