### ISSUE TITLE
404 on https://v3.nuxtjs.org/

### ISSUE THREAD

**Issue by rashidpathiyil** [nuxt/framework#7571]
### Environment

-

### Reproduction

Open https://v3.nuxtjs.org/ on Edge Browser

### Describe the bug

https://user-images.githubusercontent.com/15140041/190496805-a64ae550-ebc1-42d2-ae04-ab9e20c699f0.mp4

**Comment by danielroe** [comment]
I can't reproduce.

**Comment by aesyondu** [comment]
It happens from time to time. I'm guessing it's when a new version of the website is deployed.

**Comment by danielroe** [comment]
Thanks for reporting. Hopefully this will be a thing of the past when https://github.com/nuxt/framework/pull/5479 merges.
