### ISSUE TITLE
[nitro] [dev] [unhandledRejection] TypeError: Cannot create property 'server' on string '$KxdiLPLTek'

### ISSUE THREAD

**Issue by zengshine** [nuxt/framework#7578]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-rc.10-27709424.bb8942a`
- Nitro Version:    `0.5.2-27709289.11cc5cd`
- Package Manager:  `yarn@1.22.10`
- Builder:          `webpack`
- User Config:      `builder`, `modules`, `proxy`, `hooks`, `postcss`, `build`, `webpack`, `css`
- Runtime Modules:  `nuxt-proxy@0.2.4`
- Build Modules:    `-`
------------------------------

### Reproduction

repository: 
https://gitlab.com/zengshine/nuxt-web-app.git

yarn dev and open the test page: 
http://localhost.qizhidao.com:3000/useAsyncTest

### Describe the bug

[nitro] [dev] [unhandledRejection] TypeError: Cannot create property 'server' on string '$KxdiLPLTek'

![image](https://user-images.githubusercontent.com/18556375/190535582-9981cd7d-e1bc-4416-8523-d79ef9f3ef59.png)

**Comment by danielroe** [comment]
I'm afraid your repository is private.

**Comment by zengshine** [comment]
> I'm afraid your repository is private.

really sorry!! visible now

**Comment by danielroe** [comment]
Minimal reproduction: https://stackblitz.com/edit/github-5qqbff.
