### ISSUE TITLE
Using custom host with https not possible

### ISSUE THREAD

**Issue by chrisnoden** [nuxt/framework#7591]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Using `rc10` if you run the dev server with a custom host the websocket server runs in insecure (`ws:`) mode resulting in loss of development functionality.

Example:
`NODE_TLS_REJECT_UNAUTHORIZED=0 npx nuxi dev --host nuxt.wip --https --ssl-cert nuxt.wip.pem --ssl-key nuxt.wip-key.pem`

An example project is available at https://github.com/chrisnoden/nuxt3-bug

### Describe the bug

If you launch the dev server without `--host` option everything works fine and the websocket server starts under secure mode (`wss://`). eg `NODE_TLS_REJECT_UNAUTHORIZED=0 npx nuxi dev --https --ssl-cert localhost.pem --ssl-key localhost-key.pem`

If you specify a host the websocket starts under insecure mode which results in loss of functionality in the browser for development.

### Additional context

I have also tried with the latest edge release today (16th Sep 2022) and this presents a new problem. Specifying a custom `--host` creates an additional bug.

Under the edge release, if you use a command such as:
`npx nuxi dev --host nuxt.wip --https --ssl-cert nuxt.wip.pem --ssl-key nuxt.wip-key.pem -o`
The browser opens `https://localhost:3000` instead of the chosen host (with a certificate error, of course). This is a new bug in the edge release, but the websocket server is still in insecure mode!

### Logs

```shell
Browser console:

`Mixed Content: The page at 'https://nuxt.wip:3000/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://nuxt.wip:24678/_nuxt/'. This request has been blocked; this endpoint must be available over WSS.`
```

**Comment by danielroe** [comment]
cc: @pi0

**Comment by cretueusebiu** [comment]
Getting the same error when using it with a Nginx proxy with Laravel Valet.
