### ISSUE TITLE
500  [vite-node] [plugin:vite:import-analysis] ./node_modules/nuxt/dist/app/entry.mjs

### ISSUE THREAD

**Issue by Wan-xh** [nuxt/framework#7637]
![image](https://user-images.githubusercontent.com/24729021/190965476-d99768d5-84d5-4f0b-b53e-bcfda02c64d6.png)
<img width="638" alt="image" src="https://user-images.githubusercontent.com/24729021/190970189-faafbb0d-45f3-4836-9bb2-0d3ca0b518e5.png">

**Comment by 516310460** [comment]
`@nuxtjs/axios` only supports `nuxt2`
