### ISSUE TITLE
rc.10 build server cause port problem when deploy on azure app service

### ISSUE THREAD

**Issue by annndddy** [nuxt/framework#7641]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `yarn@1.22.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

using a rc.10 nuxt 3 project
yarn run build and deploy to a azure app service

### Describe the bug

RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. 
Received \\.\pipe\8fdffe6b-11ec-435a-8240-a90d6391fabe.at new NodeError (node:internal/errors:372:5)at validatePort (node:internal/validators:217:11)at Server.listen (node:net:1500:5)at file:///D:/home/site/wwwroot/.output/server/chunks/node-server.mjs:575:18at ModuleJob.run (node:internal/modules/esm/module_job:198:25)at async Promise.all (index 0)at async ESMLoader.import (node:internal/modules/esm/loader:385:24)at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)

process.env.PORT = \\.\pipe\8fdffe6b-11ec-435a-8240-a90d6391fabe from azure app service

### Additional context

the problem can be fix if i change the build file
.output/server/chunks/node-server.mjs
from rc.10 build server listen
const s = server.listen({ host, port }, (err) => {
to rc.9 build server listen
const s = server.listen(port, host, (err) => {

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) via https://github.com/unjs/nitro/commit/35af2091f7f78b8de63523911b5d072714467fe8, or in the next RC.

Let me know if not and I'll reopen.

**Comment by danielroe** [comment]
This should be resolved in nitropack v0.5.4. which you can get with `yarn upgrade nuxt` or `npm upgrade nuxt`.

Let me know if not and I'll reopen.
