### ISSUE TITLE
support `--dotenv` for `nuxi dev` and `nuxi build`

### ISSUE THREAD

**Issue by NeroThroN** [nuxt/framework#7646]
### Describe the feature

On Nuxt2 there was a  --dotenv to specify a different .env file in production, staging or development environments.

On Nuxt3 only the .env at the root directory is used and there is no configuration to use another file.

[Nuxt2 doc](https://nuxtjs.org/docs/directory-structure/nuxt-config/#env-support)
[Nuxt3 doc](https://v3.nuxtjs.org/api/configuration/nuxt.config#runtimeconfig)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Makes sense 👍
