### ISSUE TITLE
defineAsyncComponent in module fail in build app nuxt3 rc.9+

### ISSUE THREAD

**Issue by mkacem** [nuxt/framework#7653]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/p/github/mkacem/nuxt3-modules/main?file=%2Fmodules%2Fmodule-a%2Fpages%2Findex.vue&selection=%5B%7B%22endColumn%22%3A38%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A18%2C%22startLineNumber%22%3A9%7D%5D

### Describe the bug

defineAsyncComponent dynamic imports used in modules works fine in dev mode but when i try yarn build or yarn generate it's fail. still works with nuxt3 <= rc.8

### Additional context

nuxt3 rc.9+

### Logs

```shell
ERROR  [vite:esbuild-transpile] Transform failed with 1 error:                                               16:32:26
_nuxt/entry.679c1b10.js:12232:117: ERROR: Expected "meta" but found "meta$1"
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/6781.
