### ISSUE TITLE
Auto-import (composable) breaks when comments contain `export default function`

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/framework#7658]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-1wqbue-7nfm99?file=composables/useMain.ts

```ts
const refMain = ref(null);

export default function useMain() {
  return {
    refMain,
  };
}

// export default function useMain() {
//   return {
//     refMain,
//   };
// }
```

Remove the comments, restart the server, and it will work again.

### Describe the bug

This took me a while to find out, but if you have a composable that has comments that contain the default export, Nuxt will break and won't be able to auto-import the composable

**Comment by danielroe** [comment]
cc: @antfu
