### ISSUE TITLE
Error page lost pinia state

### ISSUE THREAD

**Issue by senher** [nuxt/framework#7669]
### Environment

"nuxt": "3.0.0-rc.10",
"@pinia/nuxt": "^0.4.2",

### Reproduction

"nuxt": "3.0.0-rc.10",
"@pinia/nuxt": "^0.4.2",

### Describe the bug

I get global data in app.vue, verify user in middleware global.global and save them in pinia (for example get token in cookie and save in pinia);
When I get to an error page and try to refresh it with keyboard F5;
At this time I click the back to home button on the page, pinia will disappear,
All state data will be lost;
They work fine if I don't refresh the error page;

**Comment by aesyondu** [comment]
I think you will have to use local storage to persist state on client side.

Maybe this package will help https://github.com/prazdevs/pinia-plugin-persistedstate

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by Kolobok12309** [comment]
If you get error-page while ssr, you lost all your headers and also cookie, mb it help with it #7339

**Comment by senher** [comment]
> Would you provide a reproduction? 🙏



> Would you provide a reproduction? 🙏

https://stackblitz.com/edit/github-7egzqc?file=middleware/global.global.ts

**Comment by danielroe** [comment]
Thank you. Yes, I think this is the same issue as https://github.com/nuxt/framework/issues/7339. Error pages are meant to be cacheable so they are rendered in a separate, internal request without the original request headers. And in general, they need to handle unforeseen errors, so I would suggest making them as free of dependencies on other parts of your app as possible.
