### ISSUE TITLE
Support for unit testing in nuxt environment

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/framework#7672]
### Describe the feature

Unit testing (e.g. [parts of ]composables or server functions) doesn't require a full built of nuxt. 

_Originally posted by @pi0 in https://github.com/vitest-dev/vitest/issues/2044#issuecomment-1251939691_

> We plan to support also unit testing with `nuxi test` but properly in a Nuxt environment. Exposing vite config only is not enough for doing that and in past similar approach made lots of headaches for testing in Nuxt 2. However, probably will expose as a `@nuxt/kit` utility anyway as an alternative to current usage that needs replicating vite config for aliases.

Related: https://github.com/nuxt/framework/issues/2465 (auto-import issues when testing components)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Also linking in https://github.com/nuxt/framework/issues/6496 (for the comments regarding unit testing).

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/2465.
