### ISSUE TITLE
Css fails after packaging

### ISSUE THREAD

**Issue by Wan-xh** [nuxt/framework#7675]
after building， Inconsistent  css  property selectors

<img width="588" alt="image" src="https://user-images.githubusercontent.com/24729021/191208216-6868f6e2-8850-4290-8c55-9fb2dcc62a5e.png">
<img width="810" alt="image" src="https://user-images.githubusercontent.com/24729021/191208295-0944462a-20ff-4011-98ca-260919d79ee4.png">

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by Wan-xh** [comment]
> 你能提供一个复制品吗？🙏

[app.zip](https://github.com/nuxt/framework/files/9606768/app.zip)

**Comment by danielroe** [comment]
Thanks! Minimal reproduction for my future use: https://stackblitz.com/edit/github-k4lob5.

**Comment by danielroe** [comment]
If it helps, for now, a workaround is to disable `experimental.treeshakeClientOnly`.

**Comment by Wan-xh** [comment]
> 如果它有帮助，目前，一种解决方法是禁用`experimental.treeshakeClientOnly`.

I have solved，thanks

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/8397.
