### ISSUE TITLE
How to not send cookie header

### ISSUE THREAD

**Issue by rin4ik** [nuxt/framework#7684]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

-

### Describe the bug

I have a backend on django(the same domain but it has /api prefix) and client app on nuxt 3
I need ssr and I run pm2 for client app (just for the sake of ssr and dynamic content)
currently when I make request to my backend it sends all cookies I use. (I use cookies with persistedstate) it attaches everything. if I set **ssr:false** it is not sending cookie header
1. how to prevent sending cookies in request headers ? 
2. if I use baseUrl and set different domain for that,  it doesnt send cookies
3. I have problems on backend regarding to this as well. I shouldnt send cookies. 
4. I dont need **servers/api servers/middleware** at all. I also get warnings regarding it cant find a route
I spent a lot of time to find out the solution for this problem but I couldnt find. please help

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by rin4ik** [comment]
@danielroe I am so sorry but it is under NDA. and creating separate reproduction will be a bit difficult I think.
so basically useFetch looks first **servers/api** folder then it decided to make api request to the real api and because it is the same domain it attaches the cookies. I just don't want those cookies to be attached. (because I get csrf problems on django)

**Comment by sevillaarvin** [comment]
Have you tried adding `{ credentials: "omit" }` to useFetch options?

**Comment by danielroe** [comment]
☝️ That is the right answer. See https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#sending_a_request_with_credentials_included.

**Comment by rin4ik** [comment]
![image](https://user-images.githubusercontent.com/25279578/191267774-e83946e1-0b07-4950-9fa8-fb7f11a3f516.png)
@sevillaarvin  I tried that as well didnt help

**Comment by rin4ik** [comment]
@danielroe is there any possibility to change this server path **/api** to something else so it won't look for it and make an external request directly?

**Comment by danielroe** [comment]
Have you accidentally added it to your headers? You should do it like:

```js
await $fetch('/api/test', {
  credentials: 'omit'
})
```

**Comment by rin4ik** [comment]
@danielroe omg definitely thanks for the help.
