### ISSUE TITLE
useFetch() does not forward server-side createError()

### ISSUE THREAD

**Issue by bf** [nuxt/framework#7686]
### Environment

rc10

### Reproduction

server-side route.get.js: 
`return createError({ statusCode: 500, statusMessage: 'foo some details' })`

client-side template.vue:

```
<script server>
const { data,  error } = await useFetch('/api/route')

if (error) {
// error does not contain any of the details that were in the response message that was created with createError
}
</script>
```

### Describe the bug

useFetch() does not forward server-side createError()

current behavior: generic error message appears in template

expected: full createError() message that is also visible when going to /api/route should be available in the vue template

### Additional context

My current workaround is as follows: in useFetch() onResponseError(), re-throw the actual response data via createError. 
Then the error check `if(error)` will work and we can re-throw the error.

Ideally, both the `onResponseError()` and the `if(error){throw error.value}` should not be needed.

```
<script server>
const { data,  error } = await useFetch('/api/route',
  {
    headers: useRequestHeaders(['cookie']),
    onResponseError({ request, response, options }) {
      throw createError(response._data)
    }
  }
)

if (error) {
  throw error.value
}
</script>
```

**Comment by danielroe** [comment]
I think we can follow in https://github.com/nuxt/framework/issues/2122.
