### ISSUE TITLE
slow server response in many connections

### ISSUE THREAD

**Issue by Sherzod06** [nuxt/framework#7688]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.4.24`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `devtools`, `modules`, `components`, `auth`, `build`, `css`, `buildModules`, `runtimeConfig`, `modern`, `vite`, `builder`, `vue`, `webpack`
- Runtime Modules:  `@nuxt/image-edge@1.0.0-27719579.87dcdf2`, `auth-nuxt@1.0.34`
- Build Modules:    `@pinia/nuxt@0.4.2`

### Reproduction

I cannot give reproduction link. It's somehow complicated

### Describe the bug

I built project using vite. And tested this build with benchmarking tool ['hey'](https://github.com/rakyll/hey). I send simultaneously 100 requests and total 1000 requests. Server response came too slow. Even some requests catch 504 error. On my pages I have used average 5-6 server side requests. But I think problem is not on backend. More info on photo below. 
![image](https://user-images.githubusercontent.com/65542674/191257820-f96f2603-31c3-4d47-b164-fbe8497df030.png)
[video](https://skr.sh/vG1GYUy3dUp)
Am I doing something wrong or is it a bug? Or should I set some config to nitro server? Now I haven't write any configs to nitro. Can somebody help me? Is there somebody with similar problem?

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by Sherzod06** [comment]
Minimal reproduction link: https://stackblitz.com/edit/nuxt-starter-usu43z

**Comment by danielroe** [comment]
In this case the slowness you are experiencing is the API calls to this external API `http://92.204.254.100:4900`. The solution is likely to cache them, which you can easily do by creating a nitro endpoint using `defineCachedEventHandler` that wraps a call to them. And, if you can avoid it, never _chain_ API calls but use `Promise.all` to resolve them in parallel.

**Comment by Sherzod06** [comment]
Now in this external API requests are 100 percent cached on backend side. We also sent many parallel requests to directly to these API endpoints. And results were normal. We are in actual project used `Promise.all`. But I think 50-100 parallel requests to one exactly route is not to be so hard. Moreover, when we doubled parallel requests, server response time also doubled. I think response time is increased like an arithmetic progression. Now we changed nitro's default preset to `'node-cluster' `.  It helped a little bit but it's not so good enough for our case. We sent 100 paralell requests and CPU is working on 100% load.  How many requsts can nitro handle by default? And how we can increase this number? We are cached some routes but we cannot cache all routes.

**Comment by danielroe** [comment]
I am suggesting you cache them _within_ nitro as I suggested above, which will change the number of outbound network requests you need. I don't believe the limitation here is Nitro. It could be the available outbound connections available to you on your server, or your external API's response time.

Try entirely removing those external API requests or inlining a sample response and rerunning your benchmark.
