### ISSUE TITLE
Starting in https with a custom host uses untrusted certs

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/framework#7699]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

N/A

### Describe the bug

When running in https with a custom host, the used certificates are untrusted, resulting in Chrome blocking the page and there's no way to trust the certificate either.

For now, I'll still use openssl to generate my own, which work fine (but you need to manually trust them in your keychain).

**Comment by pi0** [comment]
Auto-generated certificated is indeed untrusted and intentionally with a short-lived root certificate issued to avoid security issues. BTW the issued host is indicated for custom hosts as well. It is via extended attributes (Certificate Subject Alternative Name):

<img width="558" alt="image" src="https://user-images.githubusercontent.com/5158436/191352018-76b889b2-ed7b-4de0-bfc2-ae548b6bf75d.png">


If you need a trusted local certificate, you can try [mkcert](https://github.com/Subash/mkcert) and install a local trusted root certificate.

**Comment by TheDutchCoder** [comment]
Ah ok, so the hostname does get propagated, that looks good, however untrusted certificates aren't very useful, are they?
Chrome will hard block the page and there's no way to trust the certificate.

**Comment by pi0** [comment]
There was trust issue with previous RCs because auto-generated certificates were not secure enough but with RC.11 it can be bypassed locally 👍🏼  (testing on chrome 105.0.5195.125(

**Comment by pi0** [comment]
Hmm this is strange. Testing on MacOS, latest chrome and `yarn dev --https --host local.reinier.remx.xyz` it works: (maybe restarting browser or leftover HTS rules?)

<img width="625" alt="image" src="https://user-images.githubusercontent.com/5158436/191355340-8fe3ab8c-527f-4f53-9320-cc40ca6c3f1a.png">

But anyway if you plan to have long term development, your own cert is probably best idea 👍🏼  (closing issue as seems

**Comment by TheDutchCoder** [comment]
Ah, I think the issue is I run `npx nuxi dev`, not `npm run dev`.
Let me test with npm quickly.
