### ISSUE TITLE
rc.11 Static Site Generation

### ISSUE THREAD

**Issue by swapnilnandgave08** [nuxt/framework#7739]
When you hit generate command then it shows below message
`You can now deploy .output/public to any static hosting! ` 

I have deployed that code on server but it is not working because of 404 error messages in console. I have checked index.html file and observed nuxt folder path is not correct. 

Generated path for js file
`/_nuxt/web.8527e9a2.js`

It should be
`./_nuxt/web.8527e9a2.js` or `_nuxt/web.8527e9a2.js`

Thanks

**Comment by sevillaarvin** [comment]
Hi, since it works with relative path my guess is you are deploying your app somewhere not in the root of your domain.

In that case, you need to use `app.baseURL` (https://v3.nuxtjs.org/api/configuration/nuxt.config#baseurl)

nuxt.config:
```js
export default defineNuxtConfig({
  app: {
    baseURL: "/foo",
  },
  ssr: false,
})
```

index.html:
```html
<head><link rel="modulepreload" as="script" crossorigin href="/foo/_nuxt/entry.9e6abb22.js"> ...etc
```

**Comment by swapnilnandgave08** [comment]
Thanks for quick reply. I am using `nuxt3.rc.11` and below is updated nuxt config
`// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
    typescript: {
        shim: false
    },
    components: {
        global: true,
        dirs: ['~/components'],
    },
    modules: ['@nuxtjs/tailwindcss'],
    tailwindcss: {
        cssPath: '~/assets/css/main.css',
        configPath: 'tailwind.config.js',
        exposeConfig: true,
        injectPosition: 0,
        viewer: true,
    },
    app: {
        baseURL: "./",
    }
})
`

When i tried to generate build using `npx nuxi generate` then index.html is not generate. I can see only `_nuxt` folder
I have attached screenshot for reference

![Screenshot 2022-09-22 at 12 44 15 PM](https://user-images.githubusercontent.com/28770022/191682269-ed02f363-f944-43f2-86cb-aad9a7af5d61.png)

**Comment by sevillaarvin** [comment]
I am unable to reproduce the issue.

What's the output of the terminal after you execute `npx nuxi generate`? Are there any errors?

If you remove the `app.baseURL` and run the command again is the `index.html` generated again? And if you add back is it gone again?

Try to cleanup local caches with `npx nuxi@latest cleanup` and execute the generate command again.

It would be best if you could provide a repository so that we can reproduce the issue.

**Comment by danielroe** [comment]
Would you provide a reproduction? :pray:

**Comment by swapnilnandgave08** [comment]
You can see below detailed screenshots for everything
1. Generate
![Screenshot 2022-09-22 at 2 47 26 PM](https://user-images.githubusercontent.com/28770022/191712429-6d5ea4d4-b7c5-4355-85b2-85784dbbbd07.png)
2. Copy to htdocs
![Screenshot 2022-09-22 at 2 49 39 PM](https://user-images.githubusercontent.com/28770022/191712447-407c320a-481c-47a9-9d47-332a1acf9d20.png)
3. Folder Copied
![Screenshot 2022-09-22 at 2 50 03 PM](https://user-images.githubusercontent.com/28770022/191712452-a3db5af1-fd85-4231-bfd2-5dee96335e37.png)
4. Not working as getting 404
![Screenshot 2022-09-22 at 2 48 59 PM](https://user-images.githubusercontent.com/28770022/191712489-d78730d8-0cf7-42c8-ae0f-6a10ceb5b28b.png)

I am sharing public repository and you can try to reproduce

https://github.com/swapnilnandgave/nuxt3app.git

**Comment by sevillaarvin** [comment]
>     4. Not working as getting 404
>        ![Screenshot 2022-09-22 at 2 48 59 PM](https://user-images.githubusercontent.com/28770022/191712489-d78730d8-0cf7-42c8-ae0f-6a10ceb5b28b.png)

Based on the repo, if you want to have `/combine` route you will need to add a `pages/combine/index.vue` file:

```
<template>
  <div>
    Hello from combine
  </div>
</template>
```

![image](https://user-images.githubusercontent.com/33614172/191717110-33b4d11b-1edd-4fad-826a-3a94154ef757.png)

Also for the **nuxt.config**, `baseURL: "./"` won't work if you have pages other than `pages/index.vue`.

If you are deploying to `mydomain.com/app`, you can set `baseURL: "/app"`

**Comment by swapnilnandgave08** [comment]
Can you share some help what needs to be add in baseUrl for above case?

and how will be pages directory structure?

**Comment by sevillaarvin** [comment]
> Can you share some help what needs to be add in baseUrl for above case?
> 
> and how will be pages directory structure?

I made a pull request in your repository. I added some explanation as well

https://github.com/swapnilnandgave/nuxt3app/pull/1

**Comment by swapnilnandgave08** [comment]
Thanks for quick reply and pull request. I am very clear what needs to be done
