### ISSUE TITLE
nuxt.config.ts nitro output error

### ISSUE THREAD

**Issue by motea927** [nuxt/framework#7744]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-tnyrw6?file=nuxt.config.ts

### Describe the bug

When I change nitro.output in `nuxt.config.ts`,  output directory will change to `server/.output/`, even I use default value 
```
output: {
      dir: '.output',
      serverDir: '.output/server',
      publicDir: '.output/public',
},
```

### Additional context

I'm not sure this is `nitro` or `nuxt config` issue

**Comment by danielroe** [comment]
Try instead:

```js
export default defineNuxtConfig({
  nitro: {
    output: {
      dir: '~/.output',
      serverDir: '~/.output/server',
      publicDir: '~/.output/public'
    }
  }
})
```

These paths need to be absolute or use aliases, or it will resolve them relative to the nitro source directory, which is `~/server`.
