### ISSUE TITLE
More obvious deprecation of Nuxt 2 settings in `nuxt.config.js`

### ISSUE THREAD

**Issue by manniL** [nuxt/framework#7753]
### Describe the feature

Hey 👋🏻

right now, it seems difficult for several people to realize which config options from `nuxt.config.js`/`nuxt.config.ts` are actually used in Nuxt 3 (e.g. `target`). Right now, the only hint is the `@version` tag in the JSDocs which isn't very prominent though.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/640208/191731365-9767d2da-8846-4f28-9760-2223662df543.png">

It'd be nice to have a better alternative (e.g. `@deprecated`?) so people can be more aware.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
This is absolutely planned, though I couldn't find an issue for it.

**Comment by manniL** [comment]
> though I couldn't find an issue for it.

I think this is usually a "side effect" in other Nuxt3 issues, e.g.:

* https://github.com/nuxt/framework/issues/7656#issuecomment-1253588137
* https://github.com/nuxt/framework/issues/7542
* Basically any issue where "target: static" is included 🙈 ([query](https://github.com/nuxt/framework/issues?q=%22target%3A+static%22))

But given the amount of people writing `target` in their Nuxt3 config, I assume that there is a good potential for improving DX 😋

**Comment by pi0** [comment]
Thanks for making issue @manniL. Indeed we need to move Nuxt 2 types to bridge and mark them as never for 3+ schema to avoid accidentally using them. I had planned to work on this soon.
