### ISSUE TITLE
GSAP ScrollTrigger is causing a scroll to top on iOS 16 Safari

### ISSUE THREAD

**Issue by o1y** [nuxt/framework#7768]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-gwd8gb?file=app.vue

### Describe the bug

On iOS 16 Safari with GSAP ScrollTrigger and `scroll-behavior: smooth;` in my stylesheet, the page automatically scrolls back to top when the scroll animation has finished. I'm absolutely not sure if this is related to Nuxt, but this issue only occurs on Nuxt rc.11 (I had no issues on rc.8) which is the reason for filling this report:

**Workaround**
Remove `scroll-behavior: smooth;` _or_ downgrade to an older Nuxt release _or_ use an older iOS version.

**Screencast**
_On the left side you'll see an older iOS 14.x release, on the right side the latest iOS 16.0._
https://user-images.githubusercontent.com/1102712/191813194-b7d8b2d5-08e8-4c42-bfc8-18bd5440872f.mov

### Additional context

I can only reproduce this behaviour on iOS 16.0 Safari.

**Comment by BenjaminOddou** [comment]
Hello @o1y 👋 

I don't think that it is specific to nuxt 3. I am using GSAP in nuxt 3 and I had some weird bugs with ScrollTrigger even with older versions of Safari and nuxt rc (like rc6-7).

See this [bug](https://mega.nz/file/TtoWTTxB#q9yX4808y9TB8COqvUk_vLXJpcwc0MutfGM_gSsR0sg)https://mega.nz/file/TtoWTTxB#q9yX4808y9TB8COqvUk_vLXJpcwc0MutfGM_gSsR0sg)

Maybe we should wait the update of [Nuxt GSAP module](https://github.com/ivodolenc/nuxt-gsap-module).

**Comment by riddla** [comment]
Same here with `scroll-behavior: smooth;`, ScrollTrigger, Nuxt 3 (`rc.10`) and iOS. You just saved me a lot of time fixing this "bug", @o1y. Thanks a lot!

**Comment by o1y** [comment]
Sorry, as @BenjaminOddou mentioned, this is not an Issue related to Nuxt. Instead it is not a good idea to mix ScrollTrigger with the `scroll-behavior: smooth` property.

**Comment by BenjaminOddou** [comment]
Release note from GSAP 3.11.2 ![image](https://user-images.githubusercontent.com/85166574/192475014-72f35040-ed1e-4293-ab3e-33d7c3d5bd37.jpeg)
