### ISSUE TITLE
Page with redirect not generated, causing "Cannot load payload  ..._payload.js TypeError: Failed to fetch dynamically imported module"

### ISSUE THREAD

**Issue by some-user123** [nuxt/framework#7769]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xyxale

### Describe the bug

The page `redirect.vue` just contains a redirect:
```html
<template>
  <div />
</template>

<script setup>
navigateTo('/target');
</script>
```

When running `nuxi generate` there is no corresponding static page generated.

But scripts try to fetch the corresponding `/redirect/_payload.js` causing warnings in the console:
```
entry.d2c112ae.js:5 [nuxt] Cannot load payload  /redirect/_payload.js TypeError: Failed to fetch dynamically imported module: https://nuxt-starter-xyxale--3000.local.webcontainer.io/redirect/_payload.js
```

**Comment by danielroe** [comment]
Apologies for the errors in console. They are not fatal. The issue is simply that those pages were not generated in advance and we couldn't get the payload for them. You can disable by setting `experimental.payloadExtraction` to false.

You can track continued progress on the payload extraction feature at https://github.com/nuxt/framework/issues/6411.

**Comment by some-user123** [comment]
It's certainly not a big issue. But isn't it a bug, that the page is not generated at all?

**Comment by danielroe** [comment]
It was reported in https://github.com/nuxt/framework/issues/7656, so we can track there.
