### ISSUE TITLE
(SSG) Using dynamic components to load a page creates a page flicker

### ISSUE THREAD

**Issue by cedricbloem** [nuxt/framework#7783]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.4`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I created a new nuxt app with the minimalistic setup required to reproduce this bug.
Do read the additional context, because there's a chance you won't be able to reproduce this even with this setup (although I could).

[nuxt-app.zip](https://github.com/nuxt/framework/files/9631900/nuxt-app.zip)

#### How I reproduce this
Because the above example is so lightweight, you might not see the flicker. 
After generating the app for SSG and uploading it to our host, this is how I reproduce the issue by doing the following:

1. Run the application in Chrome
2. Open devtools
3. Go to the Lighthouse tab
4. Run Lighthouse and wait until it's done
5. Click on the "View Original Trace" button underneath the Lighthouse metrics
6. You'll be redirected to the "Performance" tab. 
7. Follow all the screenshots generated in the Performance tab, notice how it goes from blank - content - blank - content.

![image](https://user-images.githubusercontent.com/66309261/191918201-8998a8e7-af06-46ad-8922-9287102592d0.png)

#### Quick Introduction
I use Nuxt 3 to create a full SSG website based on content received from our CMS ([Prismic](https://prismic.io/)).
There's only one page: `[...uid].vue`, which fetches the current page data from our CMS and renders a column of components based on the information it receives. 

For example, if - according to our CMS - our page looks like this:

- navigation
- landing_hero
- heading
- footer

The respective component is loaded instead.

`[...uid].vue`
```vue
<template>
  <component
    :is="sliceList[slice.slice_type]"
    v-for="(slice, index) in page.body"
    :key="`${uid}-${slice.slice_type}-${index}`"
    :slice="slice"
  />
</template>

<script setup>
const route = useRoute();
const uid = ref(route.params.uid[0] || "home");
// Create the prismic endpoint.
const prism = usePrismic({ type: "page", uid: uid.value });
const { data: page } = await useFetch(prism.endpoint, {
  key: uid.value,
  params: prism.params,
  transform: (data) => {
    let result = data.results[0].data;
    // Remove unwanted special characters from the Prismic body.
    result = JSON.stringify(result);
    result = result.replace(/[\u2028]/g, "");
    result = JSON.parse(result);
    return result;
  },
});

// Prepare the async loading of the slices.
const sliceList = {
  navigation: defineAsyncComponent(() => import("~/components/Navigation.vue")),
  landing_hero: defineAsyncComponent(() => import("~/components/LandingHero.vue")),
  heading: defineAsyncComponent(() => import("~/components/Heading.vue")),
  footer: defineAsyncComponent(() => import("~/components/Footer.vue")),
};
</script>
```

During SSG, all the content coming from Prismic is properly rendered as HTML, which is awesome.

#### The issue 

However, after building and uploading the page to production, a "flicker" appears when visiting the page.
When I say flicker, what I mean is: the page is visible, the page disappears, the page re-appears. 

This is how it looks like on mobile:

![image](https://user-images.githubusercontent.com/66309261/191910542-9fb8c2d5-38a7-4b2c-83ab-df4b231bf0b4.png)

I don't encounter the issue when avoiding to dynamically load the components, like this:

```vue
<template>
  <Flex direction="col">
     <template
       v-for="(slice, index) in page.body"
       :key="`${uid}-${slice.slice_type}-${index}`"
     >
       <Navigation v-if="slice.slice_type === 'navigation'" :slice="slice" />
       <LandingHero v-if="slice.slice_type === 'landing-hero'" :slice="slice" />
       <Heading v-if="slice.slice_type === 'heading'" :slice="slice" />
       <Footer v-if="slice.slice_type === 'footer'" :slice="slice" />
    </template>
  </Flex>
</template>

<script setup>
const route = useRoute();
const uid = ref(route.params.uid[0] || "home");
// Create the prismic endpoint.
const prism = usePrismic({ type: "page", uid: uid.value });
const { data: page } = await useFetch(prism.endpoint, {
  key: uid.value,
  params: prism.params,
  transform: (data) => {
    let result = data.results[0].data;
    // Remove unwanted special characters from the Prismic body.
    result = JSON.stringify(result);
    result = result.replace(/[\u2028]/g, "");
    result = JSON.parse(result);
    return result;
  },
});
</script>
``` 

However, this is of course not maintainable when you have a longer list of components.

### Additional context

Time to share you additional information. Which is where I'm _really_ scratching my head.

#### @nuxtjs/prismic
I'm aware that what I'm doing is a custom made solution, since @nuxtjs/prismic has a v3 version. However, at the time I was using this, it was still unstable and now the [https://v3.prismic.nuxtjs.org/](https://v3.prismic.nuxtjs.org/) seems to be completely down.

#### An impact of CloudFlare?
On production, there are 2 urls. For the sake of privacy, I'm gonna invent some domain names here that aren't related to this project.

The first is the official URL created by [CloudFlare pages](https://pages.cloudflare.com/) - which is how we deploy our website.
This could look like: `my-website-name.pages.dev`
The second url is added to our DNS. The path is: `nuxt.our-domain.com`, which is proxied to `my-website-name.pages.dev`

On the first URL, the flicker doesn't appear, but it does happen on the second url (`nuxt.our-domain.com`)

Those who know about CloudFlare would probably ask: Did you [disable "Rocket Loader"](https://community.cloudflare.com/t/rocket-loader-causes-blink-flicker-on-page-load/27181)?
The flickering happens even with Rocket Loader disabled.

Due to this, I'm not sure if it's a Nuxt 3 or a CloudFlare issue. So I do apologize if it ends up being the latter.

Remember, I can resolve the issue with the second block in the above mentioned bug description, so maybe it's the way the components are loaded dynamically?

#### Possibly a related issue
This may or may not be related to this open issue: [useHead causes flicker when hydrating SSR-rendered page](https://github.com/nuxt/framework/issues/5735). I still encounter the issue without using `useHead`, but since this user is also encountering flickering,

**Comment by cedricbloem** [comment]
So we were able to resolve the issue through Cloudflare, although I would love to know why the issue happend.

Cloudflare minification was enabled for JS, CSS and HTML. By disabling minification for HTML, I noticed that the issue didn't happen.

### So what's the difference?
HTML minification removes comments such as `<!--]-->`, which then seems to create the above mentioned issue.

What is the impact of those comments?
Why does removing them have the potential of creating issues in an SSG website? 🤔

**Comment by danielroe** [comment]
Yes, those comments represent 'fragments' and Vue needs them to be there. This is what enables Vue 3 not to require a single root element.

**Comment by cedricbloem** [comment]
Alright, thanks for the explanation @danielroe ! Glad it wasn't a Nuxt 3 issue 😄 thanks!

**Comment by danielroe** [comment]
Thank you for your very full issue by the way - much appreciated!
