### ISSUE TITLE
Allow dynamic route for index pages with optional parameter

### ISSUE THREAD

**Issue by mklueh** [nuxt/framework#7795]
### Describe the feature

I don't know if this is a feature or rather a bug.

My blog has pagination on it's root page and I need to make the dynamic page parameter optional.
However, when I do not provide any route parameter, it will lead to a 404 error immediately.

In my opinion this should be possible, because otherwise there might be no other option than making a redirect from the root to the root + route param, which is bad for SEO as far as I know.

There is already a discussion, but I've decided to better create an issue as well

https://github.com/nuxt/framework/discussions/7526

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
I think this is already possible using the `[[slug]].vue` syntax - check out https://stackblitz.com/edit/github-rs6nww.

**Comment by mklueh** [comment]
@danielroe Thank you, this indeed did the trick 👍

**Comment by danielroe** [comment]
Optional parameters _should_ be evaluated last - if not, it's a bug.

You can check vue-router behaviour with https://paths.esm.dev. Please do raise an issue with more details if it's not behaving that way and I'll look at it straight away 🙏

**Comment by mklueh** [comment]
@danielroe thanks. I've looked into it a bit more and I think only external routes are affected, such as sitemap.xml where no router entry exists and the router isn't aware of it. 

The [[page]] will intercept it assuming its a parameter, so it's unreachable for search engine crawlers.

Am I missing something?

**Comment by danielroe** [comment]
Oh, I understand now what you mean. For these you can pass the `external` prop to `<NuxtLink>` so it won't handle it with the router.

**Comment by mklueh** [comment]
@danielroe I see. I currently don't have any links to the sitemap on my site, so I guess whenever I have such a case it's always mandatory to actively link it and register it with the router? 

And for example, I'd had expected now that the robots.txt is also inaccessible, but it seems it's dependent on the file type

**Comment by danielroe** [comment]
No, you don't need to link to it. Guess I'm still misunderstanding. Do you have a sitemal.xml in your `public` directory and you can't load it?

**Comment by mklueh** [comment]
> No, you don't need to link to it. Guess I'm still misunderstanding. Do you have a sitemal.xml in your `public` directory and you can't load it?

I'm currently letting it generate by a Netlify Plugin, and I wanted to verify if it works, which lead to this issue here. So I honestly have no idea and need to verify, but in theory it should be in the directory. Otherwise I'd expect to get the error page being called, but it seems this is also impossible if whatever is passed is interpreted as a page route parameter

**Comment by mklueh** [comment]
Me again. 
The double bracket syntax on the root index will also intercept all server routes.
Is there any chance to get around that without using **NuxtLink**?

**Comment by danielroe** [comment]
If you want to force a reload when clicking a link so it can be handled with a server route then you can pass the `external` prop to `<NuxtLink>`.

**Comment by danielroe** [comment]
You should locate that API in `~/server/api`

**Comment by mklueh** [comment]
> You should locate that API in `~/server/api`

It is located there and it would be reachable if `[[slug]].vue` would not capture it

**Comment by danielroe** [comment]
`[[slug]].vue` runs after all server middleware runs so it's not capturing it _instead_ of the endpoint. Would you provide a reproduction?
