### ISSUE TITLE
`useAsyncData` with `{ immediate: false }` skips server fetching entirely

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/framework#7803]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-1wqbue-64m2pd?file=composables%2FuseMain.ts,app.vue,components%2FMyHeader.vue

### Describe the bug

When setting `{ immediate: false }` on useAsyncData, the query correctly doesn't fire yet, however when the execute function is called at a later time _while still performing the setup_ the execution should still be fired on the server and not be handed off to the client.

`{ immediate: false, server : false }` should hand it off to the client.

The use case for this is quite simple: A profile page where you can get the profile either by ID or username (e.g. `/profile/0x123456` vs `/profile/JohnSmith`, which fetch the same record).

One could define it as follows:
```ts
const route = useRoute()
const isUsername = !(route.params.id as string).startsWith('0x')

// You don't want both of these firing. In the real world this might not even
// work when passing a conditional variable for example (like a GraphQL call).
const { data: dataId, execute: executeId } = await useAsyncData(
  'profileById',
  () => $fetch('https://some-api.dev/profileById/0x123456'),
  { immediate: false }
)

const { data: dataUser, execute: executeUser } = await useAsyncData(
  'profileByUser',
  () => $fetch('https://some-api.dev/profileByUser/JohnSmith'),
  { immediate: false }
)

// Still taking advantage of the useAsyncData composable's returns.
const userdata = computed(() => {
  return isUsername ? dataUser.value : dataId.value
})

// The server should still execute this (it doesn't).
if (isUsername) {
  await executeId
} else {
  await executeUser
}
```

**Comment by danielroe** [comment]
I can't reproduce this - it seems to be working fine in your reproduction: https://stackblitz.com/edit/github-1wqbue-imfp6e.

Any chance the issue is the one in your description, where `executeId` and `executeUser` are not in fact called?

**Comment by TheDutchCoder** [comment]
Strange, I see the call happening in the front-end as well. I think my description is incorrect. I will have to reconfirm in a minute, but I think it actually executes both on the server and client.

I will get back to you in a bit!

**Comment by TheDutchCoder** [comment]
@danielroe Yes this is the issue:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1668207/192097239-b083c12a-ff8a-4b54-984b-8289f160d215.png">

I'll update my issue. It gets called on both the server and client and should _only_ be called on the server.

**Comment by TheDutchCoder** [comment]
I just wanted to add to this that there's a decent workaround for this as well:
```ts
const route = useRoute()

// Wether to fetch by username or by id.
const isUsername = !(route.params.id as string).startsWith('0x')

// Conditionally set `immediate` only for the query that should run
const { data: dataUser } = await useAsyncGql('getAccountByUsername', { username: route.params.id as string }, { immediate: isUsername })
const { data: dataId } = await useAsyncGql('getAccountFull', { id: route.params.id as string }, { immediate: !isUsername })

// Computed the `account` based on either query
const account = computed(() => isUsername ? dataUser.value?.getAccountByUsername : dataId.value?.getAccount)
```

This seems quite elegant and at least works well. You'd just have to deal with re-assigning the destructured properties.

**Comment by danielroe** [comment]
I believe the thing you are seeing in the browser console is actually the SSR API call, because stackblitz fully runs within your browser. I've added some console logs in the reproduction to make that clear.

Try cloning it locally and running it. At least for me, it's doing what it should do.

**Comment by TheDutchCoder** [comment]
Okay, that's very interesting, let me see if I can reproduce that locally, you're probably right.
Let me do some more digging locally and see if there's a difference when using `() => process.server && $fetch('https://api.nuxtjs.dev/mountains'),` vs `() => $fetch('https://api.nuxtjs.dev/mountains'),`

**Comment by danielroe** [comment]
(That change is just to prove it can't be fetching on client side.)

**Comment by TheDutchCoder** [comment]
> (That change is just to prove it can't be fetching on client side.)

Yeah I understand that, so let me add/remove it to see if it doesn't show up in the network tab in both cases ;)

**Comment by TheDutchCoder** [comment]
@danielroe Ok, I think you're right and I think I understand why I'm confused: when developing locally, the requests show up in the network panel, because the server and client are both ran by the browser.

After building and previewing, this isn't the case, and the call never show up in the network tab 🤦 

Pardon my poor understanding of the internals, I'll close the issue!

**Comment by danielroe** [comment]
No problem at all!
