### ISSUE TITLE
return navigateTo in route middleware, but page component is not changed.

### ISSUE THREAD

**Issue by keymasroy** [nuxt/framework#7819]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

None

### Describe the bug

I made route middleware in custom plugin.
In the plugin, check the meta option and when authentication is reqired, it will validate authenticated information. When validation has failed, replace route path to login page by navigateTo function.
In the case router url is changed but page component is not changed...
Please check below source code.

```typescript
// add middleware
addRouteMiddleware(
  'ustra:auth',
  async (to, from) => {
    const $ustra = useUstra()
    const meta = useCurrentPageMeta(to)

    if (!meta.auth?.required) {
      return
    }

    let validationResult = null
    if (meta.auth?.validateAuthentication) {
      validationResult = await meta.auth?.validateAuthentication($ustra.nuxtApp, $ustra)
    }

    if ($ustra.utils.core.isEmpty(validationResult)) {
      if (meta.auth.required === true && !$ustra.auth.isAuthenticated) {
        validationResult = false
      } else if (meta.auth.required === 'exits' && !$ustra.auth.existsUser) {
        validationResult = false
      }

      if (validationResult !== false) {
        if (meta.auth.roles && meta.auth.roles.length > 0) {
          if (!meta.auth.roles.some(role => $ustra.auth.store.roles.has(role))) {
            validationResult = false
          }
        }
      }
    }

    // when fail validation
    if (validationResult === false) {
      return navigateTo('/login')
    }
  },
  { global: true },
)
```

Browser url is changed. but page component is not replaced...
![image](https://user-images.githubusercontent.com/41324713/192194499-6a26b5cd-07a0-49f3-9a12-4410a7c247de.png)

After reload browser, page component is replaced...
![image](https://user-images.githubusercontent.com/41324713/192194744-edb1348d-c8a2-40b8-8e34-f8bf83a711bc.png)

Please let me know any solution. Thanks..

**Comment by sevillaarvin** [comment]
Are there any console errors?

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by ustraframework** [comment]
> Are there any console errors?
Not have errors.

**Comment by edgarsn** [comment]
Same happened to me, but this bug mysteriously disappeared for me. Apologies, but I can't reproduce it anymore.

While I was looking what's happening, there were no errors in console.

**Comment by danielroe** [comment]
I am very happy to investigate if someone can provide a reproduction.

**Comment by keymasroy** [comment]
I found the scpecfic case.
When layout page meta to connected page component is different to page with navigationTo function, page component is not changed.

Could you find any solution??

**Comment by danielroe** [comment]
@keymasroy Can you replicate in a stackblitz?

**Comment by keymasroy** [comment]
> @keymasroy Can you replicate in a stackblitz?

I found the reason. Default layout component has not NuxtPage component.
It was my mistake.
But this action is correct?
My project has some page to have only layout component without NuxtPage.

So, I made NuxtPage tag and set v-show to false.
Thanks.

**Comment by danielroe** [comment]
A layout should have a `<slot />` and not include `<NuxtPage />`. `v-show` on the slot is fine, I would think. Perhaps on that route, you can just have a page with a single `<div />` at its root.

**Comment by keymasroy** [comment]
> danielroe

Thanks, danielroe..
