### ISSUE TITLE
How to disable nuxt logo page loader?

### ISSUE THREAD

**Issue by hirenramoliyaiwb** [nuxt/framework#7827]
### Describe the feature

@danvega

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Would you explain a little bit more about your use case for this? :pray:

**Comment by hirenramoliyaiwb** [comment]
@danielroe First thanks for the reply.   When we install nuxt js and we preview the app then the one initial loader is coming with nuxt 3 logo, I want to disable this! 
I think this is nuxt 3 default loader and its coming only when we start `npm run dev` command and the app restarts automatically.

**Comment by danielroe** [comment]
Just to be clear, the loader is only in development mode. It is not included in your app. Would you explain why you want to disable the Nuxt logo when you are running Nuxt locally in development?

**Comment by hirenramoliyaiwb** [comment]
@danielroe ohh I thought I will also appear in the live app, BTW thank you for the help. I am learning nuxt 3 that's why I am asking stupid questions, hope you don't mind 😀

**Comment by danielroe** [comment]
No problem at all :blush:
