### ISSUE TITLE
Nuxt-img tag is not working!

### ISSUE THREAD

**Issue by hirenramoliyaiwb** [nuxt/framework#7830]
### Environment

$ npx nuxi info
Nuxi 3.0.0-rc.11                                                                                                                                                  16:16:02  
RootDir: D:/hiren/nuxtjs/Nuxt-tailwind-starter                                                                                                                    16:16:03
Nuxt project info:                                                                                                                                                16:16:03

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                  16:16:03

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

Its in local environment server

### Describe the bug

@danielroe  Whenever I want to use the `<nuxt-img src="/img/avatar-anisha.png" />` component then this error is throwing `Unhandled error during execution of setup function`

**Comment by danielroe** [comment]
Would you provide a reproduction? 🙏

**Comment by hirenramoliyaiwb** [comment]
@danielroe I have not yet pushed on production

Nuxt 3.0.0-rc.11 with Nitro 0.5.4                                                                                                                                 16:18:53
i Using default Tailwind CSS file from runtime/tailwind.css                                                                                      nuxt:tailwindcss 16:18:54
i Client built in 3391ms                                                                                                                                          16:18:59
i Building server...                                                                                                                                              16:18:59
√ Server built in 2103ms                                                                                                                                          16:19:01
√ Generated public .output/public                                                                                                                           nitro 16:19:01
i Building Nitro Server (preset: node-server)                                                                                                               nitro 16:19:01
√ Nitro server built                                                                                                                                        nitro 16:19:17
  ├─ .output/server/package.json (947 B) (406 B gzip)
  ├─ .output/server/index.mjs (485 B) (262 B gzip)
  ├─ .output/server/chunks/TheHeader.810ea1f0.mjs.map (3.09 kB) (726 B gzip)
  ├─ .output/server/chunks/TheHeader.810ea1f0.mjs (5.39 kB) (1.55 kB gzip)
  ├─ .output/server/chunks/styles.mjs.map (698 B) (319 B gzip)
  ├─ .output/server/chunks/styles.mjs (14 kB) (3.49 kB gzip)
  ├─ .output/server/chunks/server.mjs.map (76 kB) (10.9 kB gzip)
  ├─ .output/server/chunks/server.mjs (59 kB) (15.1 kB gzip)
  ├─ .output/server/chunks/renderer.mjs.map (19.6 kB) (3.4 kB gzip)
  ├─ .output/server/chunks/renderer.mjs (15.5 kB) (4.75 kB gzip)
  ├─ .output/server/chunks/node-server.mjs.map (65 kB) (4.94 kB gzip)
  ├─ .output/server/chunks/node-server.mjs (24.6 kB) (7.38 kB gzip)
  ├─ .output/server/chunks/index.22787790.mjs.map (5.9 kB) (1.6 kB gzip)
  ├─ .output/server/chunks/index.22787790.mjs (5.65 kB) (2.07 kB gzip)
  ├─ .output/server/chunks/hello.mjs.map (192 B) (159 B gzip)
  ├─ .output/server/chunks/hello.mjs (163 B) (147 B gzip)
  ├─ .output/server/chunks/features.1a16a43a.mjs.map (813 B) (397 B gzip)
  ├─ .output/server/chunks/features.1a16a43a.mjs (1.72 kB) (843 B gzip)
  ├─ .output/server/chunks/error-component.123eb819.mjs.map (2.35 kB) (810 B gzip)
  ├─ .output/server/chunks/error-component.123eb819.mjs (2.01 kB) (894 B gzip)
  ├─ .output/server/chunks/error-500.mjs.map (1.06 kB) (387 B gzip)
  ├─ .output/server/chunks/error-500.mjs (4.26 kB) (1.83 kB gzip)
  ├─ .output/server/chunks/error-500.b06f14bf.mjs.map (1.7 kB) (621 B gzip)
  ├─ .output/server/chunks/error-500.b06f14bf.mjs (3.22 kB) (1.42 kB gzip)
  ├─ .output/server/chunks/error-500-styles.ad145178.mjs.map (370 B) (229 B gzip)
  ├─ .output/server/chunks/error-500-styles.ad145178.mjs (2.22 kB) (864 B gzip)
  ├─ .output/server/chunks/error-404.10e2e7ae.mjs.map (2.36 kB) (806 B gzip)
  ├─ .output/server/chunks/error-404.10e2e7ae.mjs (4.08 kB) (1.71 kB gzip)
  ├─ .output/server/chunks/error-404-styles.3db9fdd2.mjs.map (370 B) (229 B gzip)
  ├─ .output/server/chunks/error-404-styles.3db9fdd2.mjs (3.92 kB) (1.25 kB gzip)
  ├─ .output/server/chunks/default.54a74c81.mjs.map (1.84 kB) (704 B gzip)
  ├─ .output/server/chunks/default.54a74c81.mjs (2.29 kB) (999 B gzip)
  ├─ .output/server/chunks/custom.52667358.mjs.map (1.07 kB) (455 B gzip)
  ├─ .output/server/chunks/custom.52667358.mjs (1.54 kB) (675 B gzip)
  ├─ .output/server/chunks/contact.be76bffa.mjs.map (1.1 kB) (494 B gzip)
  ├─ .output/server/chunks/contact.be76bffa.mjs (3.97 kB) (1.64 kB gzip)
  ├─ .output/server/chunks/client.manifest.mjs.map (7.44 kB) (1.03 kB gzip)
  ├─ .output/server/chunks/client.manifest.mjs (9.74 kB) (1.26 kB gzip)
  ├─ .output/server/chunks/blog.41e87212.mjs.map (2.74 kB) (880 B gzip)
  ├─ .output/server/chunks/blog.41e87212.mjs (4.08 kB) (1.54 kB gzip)
  ├─ .output/server/chunks/blog-styles.e70161bd.mjs.map (498 B) (260 B gzip)
  ├─ .output/server/chunks/blog-styles.e70161bd.mjs (2.5 kB) (819 B gzip)
  ├─ .output/server/chunks/about.dace543a.mjs.map (1.61 kB) (629 B gzip)
  ├─ .output/server/chunks/about.dace543a.mjs (2.33 kB) (986 B gzip)
  ├─ .output/server/chunks/about-styles.9974f7df.mjs.map (358 B) (225 B gzip)
  └─ .output/server/chunks/about-styles.9974f7df.mjs (1.19 kB) (494 B gzip)

**Comment by danielroe** [comment]
Here's some info about how to create a reproduction: https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction

**Comment by hirenramoliyaiwb** [comment]
@danielroe  [https://stackblitz.com/edit/nuxt3-repro-7s91r1?file=pages/index.vue](https://stackblitz.com/edit/nuxt3-repro-7s91r1?file=pages/index.vue)

**Comment by danielroe** [comment]
You need to follow the instructions at https://v1.image.nuxtjs.org/ to add and enable the `@nuxt/image` module in your project.
