### ISSUE TITLE
@nuxt/content breaks nuxt 3.0.0-rc.11 - 500 nuxt instance unavailable

### ISSUE THREAD

**Issue by kumalg** [nuxt/framework#7836]
### Environment

Nuxi 3.0.0-rc.11                                                                                                                        14:02:01
RootDir: /home/kamil/projects/nuxt-bug                                                                                                  14:02:01
Nuxt project info:                                                                                                                      14:02:01

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/kumalg/nuxt-bug

### Describe the bug

Using `useHead` below `useAsyncData` causing error (500 nuxt instance unavailable) when `@nuxt/content` module is imported.

### Logs

```shell
[Vue warn]: Unhandled error during execution of setup function 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >
```

**Comment by danielroe** [comment]
If you want to use nuxt or vue composables after an await, you will need to do this in a `<script setup>` block as Vue does a transform to restore the vue context: https://vuejs.org/api/sfc-script-setup.html#top-level-await.
