### ISSUE TITLE
Error when using `--dotenv` flag

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/framework#7840]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.12-27736489.2e080c2`
- Nitro Version:    `0.5.4-27726613.640c2b7`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `ssr`, `modules`, `css`, `typescript`, `alias`, `build`, `runtimeConfig`, `vue`, `vite`, `proxy`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.3`, `floating-vue/nuxt`, `@pinia/nuxt@0.4.2`, `@vueuse/nuxt@9.2.0`, `unplugin-icons/nuxt`, `@formkit/nuxt@1.0.0-beta.11-c95e605`, `nuxt-proxy@0.2.4`
- Build Modules:    `-`
------------------------------

### Reproduction

![image](https://user-images.githubusercontent.com/48835293/192336241-d8760a1e-dba4-4c4c-9ce3-a2b601543311.png)

![image](https://user-images.githubusercontent.com/48835293/192336590-ea3e5670-71d6-4674-87dc-e01406a58458.png)

### Describe the bug

I cannot use a `--dotenv` flag with `.env.production` when building for production (even though the file exists).

**Comment by danielroe** [comment]
To pass arguments to an npm script comment, use `--` before them.

**Comment by danielroe** [comment]
@DamianGlowala Try `npm run build -- --dotenv .env.production`.

**Comment by DamianGlowala** [comment]
Thank you both 🙏 adding `--` to an npm command works like a charm.
