### ISSUE TITLE
ClientSide scope doesn't set data-v-{id} properly when inlineSSRStyles is set to true.

### ISSUE THREAD

**Issue by kstraszewski** [nuxt/framework#7841]
### Environment

Nuxi 3.0.0-rc.11                                                                                                                                                  19:06:28
RootDir: /Users/konradstraszewski/WebstormProjects/lendi-b2c                                                                                                      19:06:29
Nuxt project info: (copied to clipboard)                                                                                                                          19:06:29

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.0`
- Builder:          `vite`
- User Config:      `app`, `ssr`, `experimental`, `postcss`, `nitro`, `css`, `meta`, `modules`, `image`, `unocss`, `publicRuntimeConfig`, `vite`, `nuxtTypedRouter`, `plugins`
- Runtime Modules:  `nuxt-typed-router@1.2.2`, `@unocss/nuxt@0.45.22`, `@nuxt/image-edge@1.0.0-27707824.1028381`, `nuxt-jsonld@2.0.5`, `@pinia/nuxt@0.4.1`, `@vueuse/nuxt@8.9.2`, `()`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-w6cj1g-1libb7?file=nuxt.config.ts

`npm run serve-demo`

### Describe the bug

ClientSide scope doesn't set data-v-{id} properly when inlineSSRStyles is set to true.

You can see that the CSS write in pages/index.vue doesn't work properly (card should be `height: 200px`). It is because this line of code loaded from index.css refers to different data-v-{id}. When inlineSSRStyles switched to false, everything works great

**Comment by danielroe** [comment]
I can't reproduce this in rc12: https://stackblitz.com/edit/github-w6cj1g-5fg3cf. Let me know if it's still occurring for you.
