### ISSUE TITLE
Support using textContent of <Script> head component

### ISSUE THREAD

**Issue by MiniDigger** [nuxt/framework#7853]
### Describe the feature

When trying to setup my metadata, I need to inject some JS (GTM stuff), so I did use the <Script> tag, but was surprised to see, that you are required to use the children prob and cant use the textContent/default slot, is there any reason for that?

I tested locally that adding 
```js
  setup: setupForUseMeta((props, { slots }) => {
    const script = { ...props };
    const textContent = (slots.default?.() || []).filter(({ children }) => children).map(({ children }) => children).join("");
    if (textContent) {
      script.children = textContent;
    }
    return {
      script: [script]
    };
  })
```
into the setup function of the script component (https://github.com/nuxt/framework/blob/2e080c259fc5068fcc71e3790b4f5b75cef83eea/packages/nuxt/src/head/runtime/components.ts#L94, similarly to the noscript or style tags below) works just fine, so I would PR that as a solution if this feature request is accepted, but I want to hear your thoughts first before I setup a workspace.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
My one worry is that Vue (either now or in future) might escape the text content of the slot. And FWIW, you really don't want scripts to be reactive - so this might create a bit of a footgun.

However, those thoughts are also the case for `<NoScript>` and `<Style>`. It makes sense for all three to behave the same way .... so PR welcome!
