### ISSUE TITLE
Downgrade engine checks to Node v16.10+ (Node v16.11+ has a memory leak with jest)

### ISSUE THREAD

**Issue by jcao02** [nuxt/framework#7861]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `-`
- Package Manager:  `pnpm@7.12.1`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

- Use Node v16.10.x
- Install `@nuxtjs/tailwindcss@5.3.3` and `webpack@4.46.0`

### Describe the bug

In the package `@nuxt/kit`, the latest RC (rc.11) has an engine check for `^16.11.x` (see [here](https://github.com/nuxt/framework/blob/2e080c259fc5068fcc71e3790b4f5b75cef83eea/packages/kit/package.json#L41)). This is a problem because Jest has a [known memory leak](https://github.com/facebook/jest/issues/11956) from Node v16.11.x.

This poses a problem to organisations that use Nuxt + Jest at scale, where CI instances run out of memory (or they become very expensive to support the vertical scaling).

**Comment by danielroe** [comment]
**Related**: https://github.com/nuxt/framework/discussions/1234.

I'm not sure why 16.11 vs 16.10 was chosen. Tests seem to pass fine within the monorepo on 16.10, but @pi0 may have more context on this.

For context, see [**Node v16.11 changelog**](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V16.md#2021-10-08-version-16110-current-danielleadams)
