### ISSUE TITLE
Async Component - Resolve Component + Child Page Property

### ISSUE THREAD

**Issue by tada5hi** [nuxt/framework#7862]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.4.1`
- Builder:          `vite`
- User Config:      `css`, `alias`, `vite`, `runtimeConfig`, `modules`
- Runtime Modules:  `@nuxtjs/google-fonts@^3.0.0-0`, `@pinia/nuxt@^0.4.2`
- Build Modules:    `-`
------------------------------

### Reproduction

**[id].ts**
```typescript
import { defineNuxtComponent, navigateTo, useRoute } from '#app';
import { resolveComponent } from '#imports';

export default defineNuxtComponent({
    async setup() {
        const entity = await /** some async api call **/
        const nuxtPage = resolveComponent('NuxtPage');

        return () => h('div', [
            h('div', [
                h(nuxtPage, {
                    entity,
                }),
            ]),
        ]);
    },
});
;
```

**[id]/index.ts**
```typescript
import { defineNuxtComponent, navigateTo, useRoute } from '#app';
import { resolveComponent } from '#imports';

export default defineComponent({
    props: {
        entity: {
            type: Object,
            required: true,
        },
    },
    setup(props) {
        console.log(props.entity); 
        /** component is renedered two times. First time with null value and second time with the actual value **/
   })
});
```
### Describe the bug

There are actually two problems.
1. **Resolve Component**:
The `resolveComponent` method is not working in an **async** setup function, but in a normal one it is. So it is not possible to resolve the NuxtPage Component.
The error code in the console is the following one: 

```typescript
runtime-core.esm-bundler.js:38 [Vue warn]: resolveComponent can only be used in render() or setup().
```
2. **Child Page Property**
When i created an extra Component which is a wrapper for the NuxtPage component, which is just passing the $attr object to the NuxtPage component, i got around the first problem, because i am now able to import the wrapper component directly via an import statement. 
The child page component is rendered two times and the first time with null property values and the second time with the actual value.
In the reproduction section it is for example the **entitiy** property.

**Comment by manniL** [comment]
Could you kindly create a StackBlitz or CodeSandbox out of the reproduction (e.g. via https://nuxt.new)? 😋

**Comment by danielroe** [comment]
The issue here is that Vue (and Nuxt) need _synchronous_ access to the context. If you have an async setup, then you need to ensure that any functions that need access to the context - such as resolveComponent - should be before your first `await`.

Normally, Vue (and Nuxt) perform some transforms to allow you to access the context _after_ await. However, for a setup function, this only works within `<script setup>` blocks - see [vue documentation](https://vuejs.org/api/sfc-script-setup.html#top-level-await).

However, there's good news in your case - `resolveComponent` can _also_ be called within your render function.

[Here's some code](https://stackblitz.com/edit/github-vga5kg?file=app.ts,pages%2Findex.vue) that hopefully explains the issue:

```js
import { defineComponent, resolveComponent } from '#imports';

export default defineComponent({
  async setup() {
    await Promise.resolve();
    // this will fail (and print a warning) as there is no accessible context
    resolveComponent('NuxtPage');

    return () => {
      // this will succeed as render functions are synchronous
      // and it is specifically designed to be called in a render function
      const nuxtPage = resolveComponent('NuxtPage');

      return h('div', [h(nuxtPage)]);
    };
  },
});
```

**Comment by tada5hi** [comment]
You are the man @danielroe. This solved my first problem, but the second one is sadly still present.

**Comment by danielroe** [comment]
I'd need to see some code to understand a bit more about what you mean.

**Comment by danielroe** [comment]
I can't reproduce your second issue: https://stackblitz.com/edit/github-vga5kg-vv1onx.

I'll happily have a look if you can provide a reproduction.

**Comment by tada5hi** [comment]
Yeah, i'm also trying to reproduce the issue on stackblitz, but sadly it just occours on the frontend package of my monorepo.
I am working at the moment on a authentication & authorization application, which is split in different standalone packages. Recently i refactored the vue2 library to vue3 and i am now creating the frontend application.
If you do not mind installing the application, i can give you introductions on how to reproduce the issue in this context.

And thank you very much again for your efforts and your time ☺️ .

**Comment by danielroe** [comment]
Ideally I would like a minimal reproduction, even if it's not a stackblitz.

**Comment by danielroe** [comment]
Ah, likely that is because when you _switch_ routes there's a moment when it's not resolved. You should set `required: false` and confirm that the prop is passed before using it. You can also follow a potentially related issue here: https://github.com/nuxt/framework/issues/6592.

**Comment by tada5hi** [comment]
Yeah i already worked around that, before like that, but that felt so wrong... and it was kinda annoying to repeat that in each child page.

```typescript
// ...
setup(props) {
        // todo: remove this when this is fixed in vue/nuxt
        if (!props.entity) {
            return () => h('div', []);
        }

       // ......
},
// ....
```
Thank you for the reference :)
