### ISSUE TITLE
Top Level Await useFetch not working as expected

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/framework#7867]
Config :

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.18.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

Hello 👋,

I'd like to report a bug I am facing with `useFetch` composable. In my code I am returning an Array of object from my API (working fine). Then I'd like to split this response into different arrays (`const result`). This `const result` should look like the `const sets`.

```vue
<script setup lang="ts">
const { data: images } = await useFetch<ImageKit[]>('/api/imgkit', {
  transform: (images) => {
    return images
      .filter((image) => image.filePath.includes('navbar'))
      .sort((imageA, imageB) => (imageA.name > imageB.name ? 1 : -1))
  }
})

const result = ref<ImageKit[][]>([])
for (let i = 2; i > 0; i--) {
  result.value.push(images.value.splice(0, Math.ceil(images.value.length / i)))
}

const sets = ref([
  [
    { name: 'test', w: 10 },
    { name: 'string', w: 30 },
    { name: 'strong', w: 32 }
  ],
  [
    { name: 'n-1', w: 1120 },
    { name: 'n-2', w: 3000 }
  ]
])
</script>

<template>
<!-- WORKING -->
      <div v-for="(row, j) in sets" :key="j">
        <div v-for="(ar, i) in row" :key="i">
          {{ ar.name }}
        </div>
      </div>
<!-- NOT WORKING -->
      <div v-for="(row, j) in result" :key="j">
        <div v-for="(ar, i) in row" :key="i">
          {{ ar.name }}
        </div>
      </div>
</template>
```

When referencing result in template it triggers the following error :
![Capture d’écran 2022-09-27 à 15 52 57](https://user-images.githubusercontent.com/85166574/192545534-ea3ed05a-9a68-4c29-8004-b234db18804d.png)

Please note that the code is working as expected if referencing `const sets` directly.

**Comment by danielroe** [comment]
Would you provide a reproduction please? :pray:

**Comment by BenjaminOddou** [comment]
Hallo @danielroe ! I created a minimal repro [here](https://stackblitz.com/edit/github-1wqbue-pwzxac?file=components/MyHeader.vue) ! Please see also a video of the problem

https://user-images.githubusercontent.com/85166574/192626735-6dc9efde-4e8a-4241-bd9c-d9b1cfe0f039.mp4

Note that the `const result` is an `Array of an Array of Objects` so I can't put it under `useFetch transform` as my API is returning a simple `Array of Objects`

**Comment by danielroe** [comment]
A `transform` can process any kind of result. It's only `pick` that can only process an object.

Here you go: https://stackblitz.com/edit/github-1wqbue-2vbezu?file=components%2FMyHeader.vue.

The reason you are having an issue is that splice _mutates_ an array - so when you are running that transform function you are also changing the contents of the payload. So on client-side, you now have no images because on the server you removed them all. More about Array.splice: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice.

**Comment by BenjaminOddou** [comment]
Thank you @danielroe for the explanation. Indeed it makes more sense. I still have a small question regarding the syntax :

I would expect the following code to be correct because the API is returning Array of Object but the transform is returning array of array which cause typescript conflict 🧐

```sh
Impossible to assign type 'ImageKit[][]' to type 'ImageKit[]'.ts(2322)
```

```ts
const { data: images } = await useFetch<ImageKit[]>('/api/imgkit', { // putting <ImageKit[][]> here would cause typescript error on imageA and imageB name property
  transform: (images) => {
    const tmp = images
      .filter((image) => image.filePath.includes('navbar'))
      .sort((imageA, imageB) => (imageA.name > imageB.name ? 1 : -1))
    const result: ImageKit[][] = []
    for (let i = 3; i > 0; i--) {
      result.push(tmp.splice(0, Math.ceil(tmp.length / i)))
    }
    return result
  }
})
```

as a workaround I am using `flat()` which allow me to access to the properties of objects so no more error but I am not sure if it is the right way to do it.

```diff, ts
! const { data: images } = await useFetch<ImageKit[][]>('/api/imgkit', {
  transform: (images) => {
    const tmp = images
+     .flat()
      .filter((image) => image.filePath.includes('navbar'))
      .sort((imageA, imageB) => (imageA.name > imageB.name ? 1 : -1))
    const result: ImageKit[][] = []
    for (let i = 3; i > 0; i--) {
      result.push(tmp.splice(0, Math.ceil(tmp.length / i)))
    }
    return result
  }
})
```
