### ISSUE TITLE
nuxt preview renders existing routes as 404

### ISSUE THREAD

**Issue by P4sca1** [nuxt/framework#7892]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@3.2.3`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/P4sca1/th-koeln-was/tree/9493a77f559177eddd7fb8d907a0effeb55c51df

### Describe the bug

1. Clone the repository
2. Run `yarn` to install dependencies
3. Run `yarn generate` to generate the page
4. Run `yarn preview` to serve the generated page

Visit http://localhost:3000. The home page shows without any issues (SSR). Notice that client-side navigation also works without any issues.

Now navigate to any page except the home page using the sidebar and reload the page. Notice that all the other pages do not work when they are rendered on the server. They will show the home page for a short amount of time and render the `DocumentDrivenNotFound` component afterwards.

### Additional context

Everything works fine in development mode.

**Comment by P4sca1** [comment]
The vercel build at https://th-koeln-was.vercel.app/fuer-waehlende works without a problem.
Maybe this is related due to web server configuration and an issue with the `nuxt preview` command?

**Comment by danielroe** [comment]
I think that is likely. Try `npx server .output/public` instead of `nuxi preview`. Does that make a difference?

**Comment by P4sca1** [comment]
Running `npx serve .output/public` does make a difference. The website now works without a problem.

**Comment by P4sca1** [comment]
The issue is the `-s` flag of the serve command, that nuxt / nitro uses.
> -s, --single                        Rewrite all not-found requests to `index.html`

https://app.warp.dev/block/ZZ2t6vJXUY1mBsepPBfKc1

**Comment by danielroe** [comment]
In that case we can track in https://github.com/nuxt/framework/issues/6226 and https://github.com/vercel/serve/issues/722.
