### ISSUE TITLE
Nuxt does not include router functionality when a module calls extendPages unless the project has its own pages directory

### ISSUE THREAD

**Issue by dan-hammond** [nuxt/framework#7901]
### Environment

Nuxt project info:                                                                                                                                                           

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- Create a Nuxt module project:

```
npx nuxi init -t module my-module
cd my-module
npm i 
npm run dev:prepare
```

- Make a call to `extendPages` within `module.ts` to add a page:

```ts [module.ts]
extendPages((pages) => {
   pages.push({
     name: 'module-page',
     path: '/:slug(.*)*',
     // @ts-ignore
     file: resolve(runtimeDir, './MyPage.vue')
   })
})
```
- Add a page `~/src/runtime/MyPage.vue`:

```vue [MyPage.vue]
<template>
  <div>Hello!</div>
</template>
```

- Update `app.vue` to add `<NuxtLayout>` and `<NuxtPage>`:

```vue [app.vue]
<template>
  <div>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
```

- Run the project with `npm run dev` and note that the page has not loaded:
```
Plugin by my-module!
√ Vite server hmr 4 files in 50.259ms
[Vue warn]: Failed to resolve component: NuxtPage
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Plugin by my-module!
[Vue warn]: Component <Anonymous> is missing template or render function.
√ Vite server hmr 4 files in 143.147ms
[Vue warn]: Failed to resolve component: NuxtPage
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Plugin by my-module!
```

### Describe the bug

Nuxt cleverly strips out all router functionality if a project does not have a pages directory. However, this functionality is still removed if an installed module calls 'extendPages', so modules can't actually provide pages unless the project itself already has some, which may not always be the case.

I think router functionality should be preserved by Nuxt if `extendPages` is called.

### Additional context

I am creating a module which creates a catch all page so I can do my own routing. I don't want to need to create a page in every project in order for my module's page to take effect. I can imagine other modules will want to act similarly, even if they're only providing more specific routes/pages.

**Comment by danielroe** [comment]
You can enable routing functionality manually. Here's how `@nuxt/content` does it:

https://github.com/nuxt/content/blob/main/src/module.ts#L465-L466
