### ISSUE TITLE
[pinia] use of store in server endpoint throws an error when built for production

### ISSUE THREAD

**Issue by sevillaarvin** [nuxt/framework#7910]
### Environment

Nuxi 3.0.0-rc.11
RootDir: /tmp/example-nuxt-3
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `css`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@pinia/nuxt@0.4.2`

### Reproduction

https://github.com/cyberaesthete/example-nuxt-3-pinia

commit for rc11 reproduction
https://github.com/cyberaesthete/example-nuxt-3-pinia/commit/f9a96e543af526d96ec029671a9220ea81fd97de

commit for rc10 reproduction
https://github.com/cyberaesthete/example-nuxt-3-pinia/commit/ee5fb837704380572da89ce56688e4b1ec74de91

### Describe the bug

Not sure if this is a pinia or nuxt3 issue, but pinia throws an error when a server endpoint uses a pinia store.

This commit (https://github.com/cyberaesthete/example-nuxt-3-pinia/commit/ee5fb837704380572da89ce56688e4b1ec74de91) shows the minimal changes to use pinia in the server endpoint.

To reproduce the bug:
```
git clone https://github.com/cyberaesthete/example-nuxt-3-pinia &&
  cd example-nuxt-3-pinia &&
  npm install &&
  npm run build &&
  node .output/server/index.mjs
```

Then open in browser. Error logs should show when rendering `/`

### Additional context

Original discussion here: https://github.com/nuxt/framework/discussions/7282

According to a pinia developer: https://github.com/vuejs/pinia/issues/1688#issuecomment-1261339449
> It works without Nuxt so I suspect you need to add support for mjs files like at https://github.com/piniajs/vue-3-cli-webpack-4
Not sure how this is applicable.

The example is cloned from: https://github.com/piniajs/example-nuxt-3

### Logs

```shell
✔ You can preview this build using node .output/server/index.mjs              nitro 00:13:29
Listening http://[::]:3000
[nuxt] [request error] [unhandled] [500] Cannot find module '/tmp/example-nuxt-3/.output/server/node_modules/pinia/dist/pinia' imported from /tmp/example-nuxt-3/.output/server/chunks/hello.mjs
  at new NodeError (node:internal/errors:387:5)
  at finalizeResolution (node:internal/modules/esm/resolve:404:11)
  at moduleResolve (node:internal/modules/esm/resolve:965:10)
  at defaultResolve (node:internal/modules/esm/resolve:1173:11)
  at nextResolve (node:internal/modules/esm/loader:173:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:852:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by danielroe** [comment]
You can't use pinia outside your Vue app in a nitro API route. Pinia is written to be consumed in a Vue environment. It might be possible to add this functionality to `@pinia/nuxt` though. Feel free to open a feature request there.
