### ISSUE TITLE
Documentation for "ssr" config still refers to "static" target

### ISSUE THREAD

**Issue by TechAkayy** [nuxt/framework#7919]
### Environment

Nuxt 3 Documentation

### Reproduction

https://v3.nuxtjs.org/api/configuration/nuxt.config#ssr

### Describe the bug

"target" top level config was removed in nuxt 3, but documentation for "ssr" config still refers to "static" target in its description.

https://v3.nuxtjs.org/api/configuration/nuxt.config#ssr

Whether to enable rendering of HTML - either dynamically (in server mode) or at generate time. If set to `false` and combined with `static` target, generated pages will simply display a loading screen with no content.

**Comment by manniL** [comment]
PR welcome!

**Comment by TechAkayy** [comment]
Thank you. I'm closing this as I just realised it's a duplicate of https://github.com/nuxt/framework/issues/7757 and this documentation gap is getting addressed as part of https://github.com/nuxt/framework/issues/7753 types/schema work. Will still dig up the code to see if I can contribute in some way.
