### ISSUE TITLE
Cannot catch error with $fetch (ohmyfetch)

### ISSUE THREAD

**Issue by david4bou** [nuxt/framework#7941]
### Environment

Nuxt project info:

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.5.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```vue
<script lang="ts" setup>
import axios from 'axios'

const props = defineProps({
    image: {
        type: String
    }
})

const isExist = ref(false)

const isFileExist = async (filepath: string) => {
    try {
        await $fetch(filepath)
        return true
    } catch (e) {
        return false
    }
}

onMounted(async () => {
    isExist.value = await isFileExist(props.image)
})
</script>

<template>
    <img :src="isExist ? image ? '../assets/images/default.jpg'" />
</template>
```

### Describe the bug

Hello everyone ! I want to make a function that check if an image exist in my project folder. My function works but when I use try catch statement, I have error 404 (when image is not found) display on the console. I want to catch this error with my catch sattement but it doesn't work.

**Comment by yufanzheng0723** [comment]
You can try to use node's fs.exists in nitro

**Comment by manniL** [comment]
Works fine on [my end](https://stackblitz.com/edit/nuxtframeworkissues7941?file=server%2Fapi%2F404.ts,pages%2Findex.vue).
Ensure you do not use an `app.vue` or Nuxt's catch-all route `[...].vue` as it'd catch the call otherwise. In this case, use `$fetch.raw` and check for headers/type of the response.

**Comment by david4bou** [comment]
> Works fine on [my end](https://stackblitz.com/edit/nuxtframeworkissues7941?file=server%2Fapi%2F404.ts,pages%2Findex.vue). Ensure you do not use an `app.vue` or Nuxt's catch-all route `[...].vue` as it'd catch the call otherwise. In this case, use `$fetch.raw` and check for headers/type of the response.

No I see error on the console

**Comment by manniL** [comment]
> No I see errors on the console

Because it is a failing XHR request. It still goes into the `catch` block and returns `false` as expected ☺️ 
(See the added `debugger` statement)

**Comment by david4bou** [comment]
> > No I see errors on the console
> 
> Because it is a failing XHR request. It still goes into the `catch` block and returns `false` as expected ☺️ (See the added `debugger` statement)

But I want to hide this console error what I can do ?

**Comment by manniL** [comment]
You [cannot](https://stackoverflow.com/a/7041565/3975480).

The only workaround would be using an API endpoint (e.g. via Nitro and `server/api/check` that does the check itself and returns true/false together with a 200 status code).

**Comment by david4bou** [comment]
> You [cannot](https://stackoverflow.com/a/7041565/3975480).
> 
> The only workaround would be using an API endpoint (e.g. via Nitro and `server/api/check` that does the check itself and returns true/false together with a 200 status code).

And I do a $fetch in my server/api/check.ts file?

**Comment by david4bou** [comment]
> You [cannot](https://stackoverflow.com/a/7041565/3975480).
> 
> The only workaround would be using an API endpoint (e.g. via Nitro and `server/api/check` that does the check itself and returns true/false together with a 200 status code).

How can I doi this ?

**Comment by manniL** [comment]
See [updated StackBlitz](https://stackblitz.com/edit/nuxtframeworkissues7941?file=pages%2Findex.vue,server%2Fapi%2Fcheck%2F%3Afilename.ts)

**Comment by david4bou** [comment]
Thanks man
