### ISSUE TITLE
npx nuxi init nuxt-app: Failed to download template from registry: request to https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json failed, reason: getaddrinfo  ENOTFOUND raw.githubusercontent.com

### ISSUE THREAD

**Issue by subhash26dec** [nuxt/framework#7942]
### Environment

npx nuxi info

### Reproduction

run ==> npx nuxi init nuxt-app

![image](https://user-images.githubusercontent.com/50915253/193397012-12a33358-11f5-4ea4-9a34-52aa01624831.png)

### Describe the bug

During Installation When i run the npx nuxi init nust-app I'm getting an error

git and node installed

node version: v16.17.1

git version 2.37.3.windows.1

**Comment by manniL** [comment]
See https://github.com/nuxt/framework/issues/7678#issuecomment-1264272974
This is not a nuxt issue but more related to your network/firewall and similar. It can't access GitHub ☺️
