### ISSUE TITLE
need ctrl+f5 if u wants see changes because css  not loading

### ISSUE THREAD

**Issue by ezioadf2** [nuxt/framework#7947]
### Environment

Nuxi 3.0.0-rc.11                                                                                                                                          17:44:49
RootDir: C:/Ideal/idealo                                                                                                                                  17:44:50
Nuxt project info:                                                                                                                                        17:44:50

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `publicRuntimeConfig`, `privateRuntimeConfig`, `buildModules`, `css`, `app`, `script`, `head`
- Runtime Modules:  `-`
- Build Modules:    `nuxt-windicss@2.5.2`
------------------------------

### Reproduction

[repo](https://gitlab.com/sajad.z7877/pezeshki)

### Describe the bug

when i use "npm run dev" if i want load page i have to use ctrl+f5
if i use just f5 chrom load nothing from css
and it will show me this errors
`
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
fontawesome.min.css:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
brands.min.css:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
regular.min.css:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
IRANYekan.css:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
IRANYekanBakh.css:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
solid.min.css:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
`

**Comment by steklopod** [comment]
I have a similar error when I go back to the local dev's browser history (prev. page). mode:
<img width="1252" alt="Снимок экрана 2022-10-29 в 13 46 28" src="https://user-images.githubusercontent.com/29500153/198829694-9c06a7a1-80b3-498e-9a80-9dcaab95270d.png">
