### ISSUE TITLE
Memory leak on Server side

### ISSUE THREAD

**Issue by akahon** [nuxt/framework#7957]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.4.24`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-4bykrc?file=app.vue

### Describe the bug

As you can see in the photos heapTotal and heapUsed are increasing so fast. We benchmarked the project with benchmarking tool and sent 200 total, 100 parallel requests. Memory usage results are on photos.

On the first screenshot, you can see memory usage on the first 7 requests. 
![image](https://user-images.githubusercontent.com/34656195/193471465-d6d15fcb-4f69-4177-ac91-8ea0687b7173.png)

On the second memory usage on the last 9 requests
![image](https://user-images.githubusercontent.com/34656195/193471475-cb934696-6996-45bd-9c27-fcea7cc2f891.png)

**Comment by danielroe** [comment]
I don't see a memory leak when I test the reproduction. Even trying with 56k concurrent requests in 10s (200 request concurrency), the heap does not seem to show a memory leak to me... Rather, memory usage grows to handle requests, and then falls back down to a baseline.

You can also constrain the memory usage by running `node --max-old-space-size=50 .output/server/index.mjs` to see node's behaviour in more aggressively garbage collecting when it is constrained. (Otherwise it might not choose to GC a mere 57Mb immediately.)

**Comment by akahon** [comment]
Thanks for your answer. In the above reproduction link, I tried only a small part of my project.  My real project is much larger than it. I have tested my project with the node flag that you wrote above. 

`node --max-old-space-size=50 .output/server/index.mjs`

I have sent 500 requests in total (100 concurrently). Also, I have video recorded my testing progress. If you can please watch the video below. In my case, some requests caught strange errors. You can see these error logs on the video.

`07FF6C4E16F4D node::OnFatalError+301
 4: 00007FF6C574B1EE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6C57357CD v8::SharedArrayBuffer::Externalize+781
 6: 00007FF6C55D8B9C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF6C55D5CB4 v8::internal::Heap::CollectGarbage+4244
 8: 00007FF6C55DDD3B v8::internal::Heap::GlobalSizeOfObjects+331
 9: 00007FF6C56244AB v8::internal::StackGuard::HandleInterrupts+891`

video: https://vimeo.com/756434767

Actually when I deployed the project on the server. I have tested it with sitechecker.pro. I think when the robot tried to open all the links on the website, it is sending a large number of requests. That's why memory load is so high on the server.  My server RAM is 4GB. And when I tested with sitechecker, memory loading is high. The screenshot below:

![image](https://user-images.githubusercontent.com/34656195/193642553-f3a32648-2949-4ffa-966e-c71eb343f1f5.png)

**Comment by danielroe** [comment]
It's entirely possible you do have a memory leak in your app, but I can't see it in the reproduction.

The `50Mb` limit was chosen for the reproduction you shared; your app may require more when under heavier load. You also seem to be using the `node-cluster` preset; trying that with your original repro, I also can't reproduce.
