### ISSUE TITLE
Can't change paths for all folders of nuxt and nitro

### ISSUE THREAD

**Issue by n4an** [nuxt/framework#7962]
### Environment

---

### Reproduction
https://github.com/n4an/nuxt_dirs

```

export default defineNuxtConfig({
  pages: 'api',
  // plugins: ['~/plugins/client/'],
  // middleware: ['~/middleware/client/'],
  imports: {
  	dir: [
  	  '~/plugins/client/',
         '~/middleware/client/',
  	  '~/server/middleware/',
  	  '~/server/plugins/'
  	]
  },
  nitro: {
  	imports: {
	  	dir: [
                  //  '~/plugins/server/',
	  	  // '~/middleware/server/',
	  	  '~/server/middleware/',
	  	  '~/server/plugins/'
	  	]
	  },
  	middleware: ['~/server/middleware/'],
  	plugins: ['~/server/plugins/'],
  	rootDir: '~/',
  	scanDirs: ['~/components/']
  }
})
```

Need to change all path to custom values for Nuxt pages, plugins, middlewares and nitro api, plugins, middlewares.
Some are hard coded? Some can be changed but produce errors with auto import.

>  is imported by virtual:#internal/nitro/virtual/plugins, but could not be resolved – treating it as an external dependency

### Describe the bug

---

**Comment by n4an** [comment]
If use custom path for pages I get 
> Failed to resolve component: NuxtPage

**Comment by manniL** [comment]
Hey 👋 
Could you kindly add a reproduction (e.g. via StackBlitz, see https://nuxt.new/)?

**Comment by danielroe** [comment]
You can configure most internal nuxt directories with `dir.pages`, `dir.middleware`, etc. Is there any specific directory you are having trouble with configuring?

**Comment by n4an** [comment]
> If use custom path for pages I get
> 
> > Failed to resolve component: NuxtPage

If use custom path for pages I get

Failed to resolve component: NuxtPage

**Comment by n4an** [comment]
@danielroe  can't change nitro middleware and api, in nuxt dir not indicated plugins
And
> plugins/server' is imported by virtual:#internal/nitro/virtual/plugins, but could not be resolved – treating it as an external dependency

https://github.com/n4an/nuxt_dirs

**Comment by danielroe** [comment]
Let's track nitro directories in the separate issue you already opened there: https://github.com/unjs/nitro/issues/541. In general, no need to open duplicate issues across repositories maintained by the same people.

Here's a stackblitz showing how to configure the dirs: https://stackblitz.com/edit/github-cgrw9y.

The only Nuxt directory you mentioned that isn't configurable is `plugins` and I've opened a PR to do that.
