### ISSUE TITLE
Possibility to configure extension of files from server/api

### ISSUE THREAD

**Issue by n4an** [nuxt/framework#7963]
### Environment

---

### Reproduction

---

### Describe the bug

Possibility to configure extension of files from server/api, to load from .vue files not only ts. To make one file in which will be code for client and server and to remove parts of code on run dev/build with vite plugins

**Comment by danielroe** [comment]
Would you provide some more information about what you are asking? Why would you want to add a Vue file in the server API rather than in your pages directory?

**Comment by n4an** [comment]
> Would you provide some more information about what you are asking? Why would you want to add a Vue file in the server API rather than in your pages directory?

I want the vue page component to contain the code for the server handler to not have api root but only pages like remix.run. 
And on build stage with vite plugins to delete unneeded  server or client part.
Also I want to eliminate server dir completely and to have plugins/serve and plugins/client and so on.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/7889 in that case.
