### ISSUE TITLE
correct typings missing for `defineNitroPlugin` inside `server/plugins`

### ISSUE THREAD

**Issue by leifmarcus** [nuxt/framework#7979]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@6.14.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I created a simple implementation of a nitro plugin inside the server plugins. The types are all resolved to any: https://stackblitz.com/edit/github-xuiv1i?file=server%2Fplugins%2FNitroPlugin.ts

### Describe the bug

When creating a plugin inside `/server/plugins`, there are no types defined for `defineNitroPlugin`. In comparison if I'm using `defineNuxtPlugin`, it will be typed correctly.

**Comment by danielroe** [comment]
For now you can use:

```ts
import type { NitroAppPlugin } from 'nitropack'

export default <NitroAppPlugin> function (nitroApp) {
  
}
```

**Comment by danielroe** [comment]
This is now resolved.
