### ISSUE TITLE
useFetch/$fetch and external URLs is broken when used in an app configured with a baseUrl

### ISSUE THREAD

**Issue by kiddicodes** [nuxt/framework#7983]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-fsyggj?file=app.vue

Having a hard time reproducing the exact issue that I'm having. But this basic setup isn't working either so hopefully related.

Added two examples in App.vue (one of the commented out). 

### Describe the bug

When using baseUrl config (either by ENV or nuxt.config) useFetch / $fetch isn't working properly with external URLs.

Not entirely sure what is going on, basically what happens locally in my own project is that when using an external url (e.g. https://graphql.contentful.com/content/[...]) it gets called with a starting '/' which makes the url relative and of course resulting in a 404 (e.g. /https://graphql.contentful.com/content/[...]).

I can't reproduce this in stackblitz, what happens there instead is that the call is made over and over again, never returning any data. It is like it's stuck in a recursive loop. Removing the baseUrl configuration resolves the issue.

**Comment by n4an** [comment]
Not working if have port conflict and app use not default (not 3000) and when call $fetch('/api/test') it call localhost:3000/api/test not  localhost:3456/api/test

**Comment by danielroe** [comment]
This seems like an upstream bug to me, and we should likely resolve in ufo or ohmyfetch.

Previously we had a similar bug which was resolved in https://github.com/unjs/ufo/pull/68.

**Comment by kiddicodes** [comment]
@danielroe @Araneline I can confirm that once I've created a new package-lock file I now get ufo@0.8.6 as a dependency and everything seems to be working fine. Also solves the repro linked initially.
Thanks for your help 👍 😎
