### ISSUE TITLE
in #imports missed up CSSProperties from vue

### ISSUE THREAD

**Issue by vasilyman** [nuxt/framework#7986]
### Environment

in #imports missed up CSSProperties from vue

### Reproduction

in #imports missed up CSSProperties from vue

### Describe the bug

in #imports missed up CSSProperties from vue

**Comment by manniL** [comment]
Could you please write a few sentences what the actual issue is?

**Comment by vasilyman** [comment]
> Could you please write a few sentences what the actual issue is?

As example:

```
  CSSProperties,
} from 'vue';

const cardStyle: CSSProperties = {
  width: '100%',
  maxWidth: '500px'
}
```

Also missing defineEmits and Ref type:
```
import { defineEmits } from 'vue';
import type { Ref } from 'vue';

interface Emits {
  (e: 'main-height', item: number): void,
}

const emit = defineEmits<Emits>();

const mainHeight: Ref<number> = ref(0);
```

**Comment by danielroe** [comment]
Auto imports don't support type imports.

And defineEmits is a compiler macro and shouldn't be imported.
