### ISSUE TITLE
 request to https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json failed

### ISSUE THREAD

**Issue by wz20206** [nuxt/framework#7998]
### Environment

1

### Reproduction

1

### Describe the bug

Nuxi 3.0.0-rc.11                                                                                                                            10:29:00

 ERROR  Failed to download template from registry: request to https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json failed, reason: connect ECONNREFUSED 0.0.0.0:443

### Additional context

1

### Logs

```shell
1
```

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/issues/7942#issuecomment-1264290112.
