### ISSUE TITLE
Nuxt 3: SSR `computed()` memory leak, because the ` isInSSRComponentSetup` variable is set to `false` on the server

### ISSUE THREAD

**Issue by mrauhu** [nuxt/framework#8003]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```ts
<script setup lang="ts">
import { computed } from 'vue';

// ...

debugger;
const result = computed(() => processor(props.input));
</script>
```

Then run with debugger, and step into `computed()` function, you will see the `isInSSRComponentSetup` variable is set to `false` on the server.

![image](https://user-images.githubusercontent.com/2821574/193991243-c4fe0260-9bec-4326-8a25-535006209e46.png)

### Describe the bug

Nuxt 3 SSR is not setting the `isInSSRComponentSetup` variable to `true` on the server, that used in the `computed()` function, see:

* https://github.com/vuejs/core/commit/f4f0966b33863ac0fca6a20cf9e8ddfbb311ae87
* https://github.com/vuejs/core/issues/5208

#### Temporary fix

```ts
<script setup lang="ts">
// Importing original `computed()` function with three arguments, to use latest, the `isSSR`
// eslint-disable-next-line vue/prefer-import-from-vue
import { computed } from '@vue/reactivity';

// ...

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const result = computed(() => processor(props.input), undefined, process.server);
</script>
```

#### Memory consumption

Production build of an application, 60 requests per second, 10 minutes of load (36 000 requests).

##### Before fixes

![image](https://user-images.githubusercontent.com/2821574/193991955-11f1ea36-93d2-4e2a-b44e-0c07058911f0.png)

##### After fixes

Includes fix from https://github.com/nuxt/framework/issues/8004.

![image](https://user-images.githubusercontent.com/2821574/193992122-dbf4ddc2-7cf4-4fed-ab1f-1fa657f11a0f.png)

##### Flame graph

![image_2022-10-04_22-44-30](https://user-images.githubusercontent.com/2821574/193992686-a0f009aa-5940-4eed-86d5-4b747206239f.png)

##### Table

![image_2022-10-04_22-42-43](https://user-images.githubusercontent.com/2821574/193992594-c9b3d86a-060c-4974-ac84-831c0a6c7421.png)

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/8004 as that's the presenting cause

**Comment by mrauhu** [comment]
@danielroe would you reopen this issue after #8004 is closed?

**Comment by danielroe** [comment]
I believe my comment is relevant here as well: https://github.com/nuxt/framework/issues/8004#issuecomment-1290032909

If you are still experiencing an issue would you provide a reproduction please? 🙏

**Comment by mrauhu** [comment]
> If you are still experiencing an issue would you provide a reproduction please?

I will check current Nuxt behavior of calling the `computed()` function on the server.
