### ISSUE TITLE
Nuxt 3: SSR memory leak in `useHead()` with computed getter on the server

### ISSUE THREAD

**Issue by mrauhu** [nuxt/framework#8004]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```ts
<script setup lang="ts">
import { useHead } from '#head';

// ...

useHead(() => getMeta(meta.value));
</script>
```

### Describe the bug

Using a computed getter (`() => ...)`) as an argument of the `getHead()` results to memory leak on the server.

See also: https://github.com/nuxt/framework/issues/8003.

#### Temporary fix

```ts
<script setup lang="ts">
import { useHead } from '#head';

// ...

if (process.server) {
  useHead(getMeta(meta.value));
} else {
  useHead(() => getMeta(meta.value));
}
</script>
```

#### Memory consumption

Production build of an application, 60 requests per second, 10 minutes of load (36 000 requests).

##### Before fix

![image](https://user-images.githubusercontent.com/2821574/193991955-11f1ea36-93d2-4e2a-b44e-0c07058911f0.png)

##### After fix

![image](https://user-images.githubusercontent.com/2821574/193996756-3c744099-6307-42ad-a12d-a7a52d53dadf.png)

##### Flame graph

![image](https://user-images.githubusercontent.com/2821574/194616254-d11ad90c-a7c5-4d7f-a9c4-fa8d62cabd96.png)

##### Table

![image](https://user-images.githubusercontent.com/2821574/194616169-d9ab7c39-2375-456c-8845-b82446568bc3.png)

**Comment by harlan-zw** [comment]
Hey @mrauhu, thanks for the detailed audit.

Worth noting that the current version of @vueuse/head in Nuxt RC 12 does not officially support computed getter syntax.

It was introduced in https://github.com/vueuse/head/releases/tag/v0.8.0.

As there's no reproduction, would it be possible for you to test out https://github.com/harlan-zw/nuxt-hedge and see if it has the same issue? This uses the latest @vueuse/schema-org, which I'm working to get into the core (https://github.com/nuxt/framework/pull/8000/files).

**Comment by mrauhu** [comment]
Hi @harlan-zw.

> As there's no reproduction, would it be possible for you to test out https://github.com/harlan-zw/nuxt-hedge and see if it has the same issue?

Checked `nuxt-hedge` with latest `@vueuse/head`. Tested it.

> Also, could you share your getMeta function so we can rule out it being a ref loop

Basically it's just converter from a flat object of metatags to `MetaObject`. There is no references inside, just one array:

```ts
// Simplified version
export function getMeta(meta: Record<string, string>) {
  const result = {
    meta: [],
  } as MetaObject;
  
  for (const [key, value] of Object.entries(meta)) {
    result.meta.push({
        name: key,
        key: key,
        content: value,
    });
  }
  
  return result;
}
```

## Computed getter in `useHead()` from `nuxt-hedge`

Production build of an application, 60 requests per second, 10 minutes of load (36 000 requests).

### Memory consumption

![image](https://user-images.githubusercontent.com/2821574/194115766-210cb418-88c7-4046-9c59-94ab76e63a21.png)

### Memory difference

#### Computed getter in original `useHead()` versus `nuxt-hedge`

Same code, different libraries for `useHead()`:

* no fix, `@vueuse/head@0.7.12`
* no fix, `nuxt-hedge@0.2.3` and `@vueuse/head@0.9.6`.

##### Flamegraph

![image_2022-10-05_19-53-11](https://user-images.githubusercontent.com/2821574/194117666-f19b5bfc-6864-4324-a4f3-5b906b72cca9.png)

##### Table

![image_2022-10-05_19-53-54](https://user-images.githubusercontent.com/2821574/194117729-a7b91fd1-ec6d-47f8-ab85-d6a5bdd09b12.png)

#### Client-only computed getter in original `useHead()` versus `nuxt-hedge`

Different code, different libraries for `useHead()`:

* temporary fix, `@vueuse/head@0.7.12`;
* no fix, `nuxt-hedge@0.2.3` and `@vueuse/head@0.9.6`.

##### Flamegraph

![image_2022-10-05_19-39-23](https://user-images.githubusercontent.com/2821574/194119072-482de113-1205-459f-9056-649d4a076abf.png)

##### Table

![image_2022-10-05_19-39-44](https://user-images.githubusercontent.com/2821574/194119243-85481bc6-6b32-4245-a827-eeb12d38bc0b.png)

## Total system memory usage

Production build of application, 100 requests per second, 10 minutes of load (60 000 requests).

### 5.02 GB, client-only computed getter in original `useHead()`

![image](https://user-images.githubusercontent.com/2821574/194126078-1771d4c1-98e8-4993-b9ac-a8f10374684f.png)


### 6.23 GB, computed getter in `useHead()` from `nuxt-hedge`

![image](https://user-images.githubusercontent.com/2821574/194126653-01eb8174-59a7-46ed-ac42-0645b34a8145.png)

Difference: **+ 1.23 GB**

## Conclusion

So using the `nuxt-hedge` is better than no fix, but the temporary fix is the best:

```ts
if (process.server) {
  useHead(getMeta(meta.value));
} else {
  useHead(() => getMeta(meta.value));
}
```

**Comment by harlan-zw** [comment]
Thank you @mrauhu 

I have some ideas on how to improve this, but it includes some risky changes around reactivity so it may not be available until @vueuse/head v1.

Will give you a ping when there's something to test

**Comment by antlionguard** [comment]
> ### Environment
> 
>     * Operating System: `Linux`
> 
>     * Node Version:     `v16.15.0`
> 
>     * Nuxt Version:     `3.0.0-rc.11`
> 
>     * Nitro Version:    `0.5.4`
> 
>     * Package Manager:  `npm@8.5.5`
> 
>     * Builder:          `vite`
> 
>     * User Config:      `-`
> 
>     * Runtime Modules:  `-`
> 
>     * Build Modules:    `-`
> 
> 
> ### Reproduction
> 
> ```ts
> <script setup lang="ts">
> import { useHead } from '#head';
> 
> // ...
> 
> useHead(() => getMeta(meta.value));
> </script>
> ```
> 
> ### Describe the bug
> 
> Using a computed getter (`() => ...)`) as an argument of the `getHead()` results to memory leak on the server.
> 
> See also: #8003.
> #### Temporary fix
> 
> ```ts
> <script setup lang="ts">
> import { useHead } from '#head';
> 
> // ...
> 
> if (process.server) {
>   useHead(getMeta(meta.value));
> } else {
>   useHead(() => getMeta(meta.value));
> }
> </script>
> ```
> 
> ### Additional context
> #### Memory consumption
> 
> Production build of an application, 60 requests per second, 10 minutes of load (36 000 requests).
> ##### Before fix
> 
> ![image](https://user-images.githubusercontent.com/2821574/193991955-11f1ea36-93d2-4e2a-b44e-0c07058911f0.png)
> ##### After fix
> 
> ![image](https://user-images.githubusercontent.com/2821574/193996756-3c744099-6307-42ad-a12d-a7a52d53dadf.png)
> #### Memory difference
> ##### Flame graph
> 
> ![image](https://user-images.githubusercontent.com/2821574/194616254-d11ad90c-a7c5-4d7f-a9c4-fa8d62cabd96.png)
> ##### Table
> 
> ![image](https://user-images.githubusercontent.com/2821574/194616169-d9ab7c39-2375-456c-8845-b82446568bc3.png)
> ### Logs
> 
> _No response_

I have a question off topic. What is the name of the program/application you use to track of memory?

**Comment by mrauhu** [comment]
> I have a question off topic. What is the name of the program/application you use to track of memory?

@antlionguard Datadog APM with Continuous profiler.

**Comment by harlan-zw** [comment]
Hey @mrauhu 

I have worked on the performance improvements, they are available in nuxt-hedge 0.5.0.

The client-side performance should be improved, the server performance should be a bit more stable but hard to say if it's solved the memory leak issue as I don't know the full scope of how the ssrContext is used.

**Comment by harlan-zw** [comment]
Potential fix is also available in `npm:nuxt3@latest`

**Comment by leanmiguel** [comment]
@mrauhu What application are you using that shows the memory usage and flamegraph?

**Comment by danielroe** [comment]
The issue here was not actually (IIRC) the use of `useHead` within the component but rather that Nuxt itself was calling use head in a plugin meaning that `computed` was being called outside of component setup.

I believe this is resolved as computed is no longer being called by `@vueuse/head`, and functional/computed types are excluded from `app.head` in `nuxt.config`.

Let me know if not and I'll happily reopen.
