### ISSUE TITLE
Cannot create crawlable deployment

### ISSUE THREAD

**Issue by tandrew** [nuxt/framework#8006]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Please check the problem text. I will have to work on a reproduction otherwise.

### Describe the bug

I am unable to create a static site which can be crawled (SEO). Site is working in general but crawlers do not identify individual pages. Sorry, that I cannot explain it better.

I have tried all sorts of combinations when it comes to tweaking the potentially relevant parameters in `nuxt.config`, scanned all issues and discussions on gitHub, but nothing seems to work. Scanning DOES work, however, when running the site in dev mode locally using `nuxt dev`.

Here is my current config:
```js
export default defineNuxtConfig({
    target: 'static',
    ssr: false,
    generate: {
        crawler: true
    },
    nitro: {
        serveStatic: true,
        prerender: {
            crawlLinks: true,
            routes: ['/']
        },
        preset: 'service-worker',
        // preset: 'browser'
    },
```

The site is being deployed on Netlify. I have tried both `nuxt build` and `nuxt generate` there. Both to no avail when it comes to the issue described above.

Please note that this site is also serving `nuxt/content`, in case that's relevant. `nuxt/content` has recommendations when it comes to static hosting (https://content.nuxtjs.org/guide/deploy/static-hosting), which make no difference here.

**Comment by danielroe** [comment]
If you have set `ssr: false` then there is no crawlable HTML generated. In most cases you do not want to set `ssr: false` when generating a static site.
