### ISSUE TITLE
App config cannot be parsed when srcDir is changed

### ISSUE THREAD

**Issue by brownsugar** [nuxt/framework#8012]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@3.2.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-rtfk6z-3ufhp4

### Describe the bug

1. Define the app config in `app.config.ts`

``` ts
export default defineAppConfig({
  foo: 'bar'
})
```

2. Set `srcDir` to `src/`

``` ts
export default defineNuxtConfig({
  srcDir: 'src/'
})
```

3. Tried to get `foo`
``` ts
const { foo } = useAppConfig()
console.log(foo) // undefined
```

**Comment by dsvgl** [comment]
It needs to be `export default defineAppConfig({ ... })` inside app.config.ts instead of `defineAppConfig({ ... })`.
See working Blitz: https://stackblitz.com/edit/github-rtfk6z-pumagr?file=app.config.ts
Also look at the docs: https://v3.nuxtjs.org/guide/directory-structure/app.config

**Comment by brownsugar** [comment]
@dsvgl Oh thanks I didn't notice that..
But it still return undefined when `srcDir` is changed, it seems they find app.config in srcDir not rootDir.

**Comment by danielroe** [comment]
This isn't a bug. It's meant to be in the `srcDir`.
