### ISSUE TITLE
useState doesn't work as expected when multiple components are injected into the DOM

### ISSUE THREAD

**Issue by yungsilva** [nuxt/framework#8024]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/yungsilva/dvs-ref-nuxt-3

### Describe the bug

I'm working on a project where I need to dynamically inject a component into the DOM... The problem happens when this component repeats itself, the state seems to be shared between the same components.

`/components/Counter.vue`

```vue
<template>
  <div class="counter">
    <p>counter: {{ count }}</p>
    <button @click="count++">increment</button>
  </div>
</template>

<script setup lang="ts">
const count = useState('count', () => 0)
</script>
```

`/app.vue`

```vue
<template>
  <div class="page">
    <pre></pre>
    <pre></pre>
    <pre></pre>
  </div>
</template>

<script setup lang="ts">
import { onMounted, createApp } from 'vue'
import Counter from './components/Counter.vue'

onMounted(() => {
  document.querySelectorAll('pre').forEach((preElement) => {
    const wrapper = document.createElement('div')

    const componentApp = createApp(Counter)

    componentApp.mount(wrapper)

    preElement.append(wrapper)
  })
})
</script>
```

Result: when clicking on any of the buttons, the state updates in all components, as shown in the image below.

![ex](https://i.ibb.co/6PyLQJg/Screen-Shot-2022-10-06-at-19-11-42.png)

If in the `Counter.vue` component you use `ref` instead of `useState`, everything works fine

```ts
const count = ref(0)
```

![ex](https://i.ibb.co/NpbzZyZ/Screen-Shot-2022-10-06-at-19-10-51.png)

**Comment by codeflorist** [comment]
as far as i understand it, `useState`'s central use case is exactly when you want to share a state over the whole app. it is an alternative to a store (e.g. `vuex` or `pinia`). so imho it is working as expected.

**Comment by manniL** [comment]
If the key used for `useState` is the same, then the state will be shared. This is intended.
