### ISSUE TITLE
Dynamic routes break when deploying built nuxt 3 app (boiler plate)

### ISSUE THREAD

**Issue by samuelkilada** [nuxt/framework#8042]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I created a boiler plate nuxt 3 project like so:

`npx nuxi init test-build`
`cd test-build`
`npm i`

I then made a few small changes. In nuxt.config.js, I added:

`ssr: false`

I also added a pages folder, with a structure like so:

`pages/products/[id].vue`

Inside that file, I put:

```
<template>
  <div>
    <p>hello world</p>
  </div>
</template>
```
Finally, in app.vue, I changed it to:

```
<template>
  <div>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
```

Now, do an "npm run build". I took the contents of the build (public output directory) and deployed it to an Azure static website (since ssr = false this should work). When navigating to a dynamic route like /products/123, you get a 404 even though the page shows "hello world" when running "npm run dev".

### Describe the bug

Dynamic routes show a 404 when deployed. I should note that non-dynamic routes (pages in the top level of the pages directory) load just fine.

**Comment by danielroe** [comment]
You should almost never set `ssr: false` for a static site. It means you are rendering un-rendered HTML, that can't be crawled by the Nuxt prerenderer.

Do you mind if I ask where you got the idea to set `ssr: false`? I see a lot of people doing this, and we either need to improve our docs or I need to track down some tutorial that's spreading misinformation.

**Comment by samuelkilada** [comment]
Thanks for the reply. I'm a bit confused because I thought that a static site was by nature not server-side rendered? That is the benefit of this approach, because it can be deployed to places like Azure static website and even Amazon S3 buckets.

**Comment by danielroe** [comment]
SSR means 'rendering HTML', which (if you are running `nuxt generate`) happens at build time.

(Which is another point - if you are deploying to a static site you should run `nuxt generate` and not `nuxt build`.)

**Comment by samuelkilada** [comment]
@danielroe I guess I must still be missing something. If I remove the "ssr: false" line in the above example and run "npm run generate" I end up with a project that can't be deployed. It doesn't create an index.html file, only a 200.html file along with a _nuxt folder. This won't even deploy to an Azure static site because an index file is required. Putting ssr: true resolves the problem, though I still have the original issue with dynamic pages.

**Comment by danielroe** [comment]
I'll happily look at it if you provide a reproduction.

**Comment by danielroe** [comment]
If you wish to generate dynamic routes without any links to them from the rest of your site, you need to specify them in `nitro.prerender.routes`.

**Comment by samuelkilada** [comment]
I think I see what you mean. The problem is, imagine if I have a thousands upon thousands of products (and that is the case in our app.....it's a massive number). I don't want to have to specify them each like so:

`/products/123`
`/products/456`
`/products/789`
...etc

Do you see my problem now?

**Comment by samuelkilada** [comment]
Testing out the fallback option....

**Comment by danielroe** [comment]
@samuelkilada If you are rendering static pages with a dynamic route, how would Nuxt know which slugs to render if you do not tell it and there are no links to give hints?

You might want to follow https://github.com/nuxt/framework/issues/4919. Note that you can use a hook to extend them programmatically.

**Comment by samuelkilada** [comment]
I've done some looking into hooks but unfortunately, I cannot add all of the routes in advance, and if I did it could literally be millions. Our goal is to make the main pages of the site like the home page, terms, etc. all static, but not the products page. This would behave basically as an SPA. We had thought that since we can excluder routes in nuxt config under the "generate" property, that this would work, but it seems unable to make that distinction.

**Comment by danielroe** [comment]
The good news is there are two possible solutions for your situation.

1. There's an Azure SWA integration for server rendering non static routes. That might be worth investigating, and there will likely be improvements coming soon in the way of incremental generation.

2. If you want a purely static deployment, then the `200.html` fallback is what you need; it's about configuring your provider. All Nuxt can do is produce this file; there's no way to do any more.

**Comment by samuelkilada** [comment]
Thanks very much for the help. I finally got this working! Note that I had to put ssr: false back because the thing simply won't work without it. But as you said I added an Azure config setting for the static website. For those wondering how I did this, you need a staticwebapp.config.json file in your root www folder with the following:

```
{
  "routes": [
    {
      "route": "/*",
      "serve": "/index.html",
      "statusCode": 200
    }
  ],
  "navigationFallback": {
      "rewrite": "index.html"
  },
}
```

Thank you @danielroe for your advice.

**Comment by danielroe** [comment]
You can add `/200.html` to your `nitro.prerender.routes` with SSR: true.

**Comment by samuelkilada** [comment]
Thank you, I'll keep that in mind.

**Comment by mustafaosta** [comment]
i had the same issue and your answer for navigationFallback with Azure is correct but i was using Apache, 

here is my `.htaccess` file that i would just add to `.output/public`

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^ index.html [L]
```
