### ISSUE TITLE
Show sponsors in Readme

### ISSUE THREAD

**Issue by Atinux** [nuxt/framework#8050]
Leverage https://github.com/antfu/sponsorkit to generate the main SVG image with links.

**Comment by Atinux** [comment]
@antfu could you open a PR to see how it looks like?

**Comment by antfu** [comment]
What are the sources we would use? GitHub & OC?

**Comment by Atinux** [comment]
GitHub and OpenCollective yes

**Comment by n4an** [comment]
who need that?

**Comment by Atinux** [comment]
Any update @antfu ?

**Comment by Atinux** [comment]
It is now on https://nuxt.com/support/us (but we need to fix that page 😅 )
