### ISSUE TITLE
All styles from layouts and pages being loaded in dev mode – Nuxt 3

### ISSUE THREAD

**Issue by ashleynolan** [nuxt/framework#8053]
### Versions

- nuxt: nuxt3@3.0.0-27276275.abfbd2f
- node: 14.17.0

### Reproduction

In short, the issue is that CSS from different pages & layouts is included on all pages, resulting in pages being styled incorrectly. This only happens in dev mode in Nuxt 3 – when building for prod, the CSS is included as expected.

I've [set up a repo that shows the issue](https://github.com/ashleynolan/nuxt-style-demo) (and goes through the expected and actual behaviour).

A similar issue was [reported for Nuxt 2](https://github.com/nuxt/nuxt.js/issues/3877), where one of the team said that the issue would be looked at for Nuxt 3 – which is why I set up this test repo, as we're seeing this issue on our project.

### Steps to reproduce

- Check out [this repo](https://github.com/ashleynolan/nuxt-style-demo)
- Go to the `nuxt3-app` folder in command line, install dependencies (`yarn`) and run `yarn dev` to reproduce the issue.
- The test site has 4 pages – `/`, `/search`, `/menu` and `/checkout` – and the expected/actual results are documented in the [README of the repo](https://github.com/ashleynolan/nuxt-style-demo/blob/master/README.md).

### What is Expected?

When rendering a page, styles from irrelevant layouts and other pages do not also load on the page.

### What is actually happening?

Currently, in dev mode, it looks like all styles from all layouts and pages are included in the head of each page, resulting in issues with the page displaying styles that aren't intended for the current page.

**Comment by theguriev** [comment]
@ashleynolan Did you find any workaround?

**Comment by jevgenigavrilov** [comment]
I am also interested if there is any workaround to this. Have the same issue in my app

**Comment by ashleynolan** [comment]
I haven't managed to find a workaround for this yet – I haven't tested with the latest Nuxt 3 release, so will try and update when I get chance, but as far as I'm aware the same issue is present

**Comment by theguriev** [comment]
@ashleynolan Yep. I just checked. Looks like the issue is still there. :(
