### ISSUE TITLE
Global route middleware with navigateTo not changing url

### ISSUE THREAD

**Issue by FlorianWerndl** [nuxt/framework#8080]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.3.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

// e.g. removing trailing slash
https://stackblitz.com/edit/nuxt-starter-ab61ni?file=middleware/redirect.global.js

// e.g. navigate to different path
https://stackblitz.com/edit/nuxt-starter-utn8lv?file=middleware%2Fredirect.global.js

### Describe the bug

When using a global route middleware with navigateTo the URL doesn't change after navigation.

### Additional context

Maybe this issue is only related to stackblitz?

**Comment by danielroe** [comment]
Try this:

```diff
  export default defineNuxtRouteMiddleware((to, from) => {
    if (to.path !== '/' && to.path.endsWith('/')) {
      const nextPath = to.path.replace(/\/+$/, '') || '/';
      console.log('nextPath', nextPath);
-     return navigateTo('/', {
+     return navigateTo(nextPath, {
        redirectCode: 301,
      });
    }
  });
```

But yes, Stackblitz doesn't update the URL in the iframe. Try locally and it should be fine.
