### ISSUE TITLE
globalName - change __nuxt id as it was in NUXT2

### ISSUE THREAD

**Issue by 53rg0** [nuxt/framework#8099]
### Describe the feature

Please, return globalName param, its very important for customers and developers for a lot of reasons!

Thank you!

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by manniL** [comment]
> Its very important for customers and developers for a lot of reasons!

Can you provide some then? I always felt it more as a burden than something useful...

**Comment by 53rg0** [comment]
> > Its very important for customers and developers for a lot of reasons!
> 
> Can you provide some then? I, personally, always felt it more as a burden than something useful...

First of all - security reason. 
It is very important to protect the site from scripts that automatically scan technologies. Nuxt3 uses the Nitro server part and it is enough to find the __nuxt id in the code to already know what the site is running on. If any bugs are found in the future, scripts that scan websites will quickly find vulnerable ones.

Nuxt3 is great for me! I will definitely talk about this technology in my portfolio and will do my best to make as many people as possible learn about it.
Another thing is customers, especially very large ones, who very often have a requirement to remove any mention of other brands and their team includes those who check the project for such "Easter eggs". Already on the first demo with Nuxt 3, I received such a remark and knew that it could be removed, but later I realized that this was no longer possible.

Analysis of competitors. Often before development, an analysis of competitor solutions is carried out and we would not like to make it obvious to other developers what we use during the analysis. We don't mind talking about it in the portfolio, but we don't mind making it obvious.

Having this feature is very important, I don’t want to switch back to Nuxt 2 having a wonderful Nuxt 3 because of such a trifle, but still the last word is not with me, but with the clients.

**Comment by manniL** [comment]
> First of all - security reason. It is very important to protect the site from scripts that automatically scan technologies. Nuxt3 uses the Nitro server part and it is enough to find the __nuxt id in the code to already know what the site is running on. If any bugs are found in the future, scripts that scan websites will quickly find vulnerable ones.

This sounds like security through obscurity. You will always be able to find out if a site was built with Nuxt, simply by scanning the `.js`/`.mjs` files and match the code vs. what Nuxt produces. Especially for built-in names.

**Comment by manniL** [comment]
Related: https://github.com/nuxt/framework/issues/1254

**Comment by 53rg0** [comment]
Yes, but here you don’t even need to compare, you don’t need to write complex scripts, just press F12. Nuxt2 has the ability and everyone uses it for sure, but Nuxt3 does not, so if there is a __nuxt id in the code, then this is 100% nuxt3 framework. 

In Nuxt2, everyone uses it, the feature is very important to return it. Moreover, it has already been implemented.

**Comment by 53rg0** [comment]
Of course, for your own projects, this is not very important when you can decide for yourself what is needed and what is not. But when there is a requirement to "hide obvious traces of the engine" and I understand why there is such a requirement, then I have to choose another technology. 

But I really like Nuxt3, I hope my opinion (and many others) will be heard.

**Comment by manniL** [comment]
> Yes, but here you don’t even need to compare, you don’t need to write complex scripts, just press F12. 

Okay, so the effort is basically pushing F12 vs. doing a string search for "Nuxt" in the `.js` assets. I would not consider this another magnitude of effort to be honest 👀 

> If there is a __nuxt id in the code, then this is 100% nuxt3 framework.

No, either Nuxt2 or Nuxt3 with quite a high chance.


> In Nuxt2, everyone uses it, the feature is very important to return it. Moreover, it has already been implemented.

I can say for certain that quite a number of projects, also "larger"/"enterprise" projects, do not use it. 👀 

> But when there is a requirement to "hide obvious traces of the engine" and I understand why there is such a requirement, then I have to choose another technology.

If the requirement is to hide obvious traces of the framework/tech, then you might not use any framework - or something that compiles down to "pure" JS. You can always detect frameworks, even the basic ones like Vue.js, with ease. Everything in the frontend is human readable eventually ☺️

Anyway, I'm curious about more arguments except "don't make it too obvious we are using Nuxt"!

**Comment by 53rg0** [comment]
I'm sure you won't mind seeing a big Nuxt3 project :)
Last argument is also very important, in addition, the ability to change the Id is also important for development

I really hope that this opportunity will be returned in the near future.

**Comment by manniL** [comment]
>  Last argument is also very important, 

Which?

> The ability to change the Id is also important for development

What influence does that have on app development?

**Comment by 53rg0** [comment]
> > Last argument is also very important,
> 
> Which?
> 
This one ->  Anyway," I'm curious about more arguments except "don't make it too obvious we are using Nuxt"!"
> > The ability to change the Id is also important for development
> 
> What influence does that have on app development?
Flexibility. This creates some rules from which you must repel while writing styles. I don’t understand why it was removed, it was a great opportunity that everyone used

**Comment by 53rg0** [comment]
We are not asking for everything, we are asking for the most obvious, especially when Nuxt 2 has it)
Many people prefer other engines because of this, as I said there are many reasons why people are waiting for the return of this feature

**Comment by 53rg0** [comment]
Should we wait for globalName to appear?

**Comment by danielroe** [comment]
I would be opposed to customising `nuxt` everywhere it appears in the codebase, as this greatly decreases stability and interoperability across the modules ecosystem, as @manniL has rightly said. Nothing along these lines is at all effective in terms of concealing what framework an app is built with.

But as for customising the ID of the root `<div>`, I think this might be reasonable, along with other customisations of this element, such as perhaps changing the HTML tag to which Nuxt mounts.

**Comment by 53rg0** [comment]
> I would be opposed to customising `nuxt` everywhere it appears in the codebase, as this greatly decreases stability and interoperability across the modules ecosystem, as @manniL has rightly said. Nothing along these lines is at all effective in terms of concealing what framework an app is built with.
> 
> But as for customising the ID of the root `<div>`, I think this might be reasonable, along with other customisations of this element, such as perhaps changing the HTML tag to which Nuxt mounts.

Thanks a lot for your answer! Look forward to :)

**Comment by weo3dev** [comment]
We aren't asking for `nuxt` to be changed everywhere. We are literally asking for control to be given back to us where we had said control in Nuxt 2. Please give it back. It is useful to us, as developers, not only to satisfy the needs of our clients in terms of security and code compliance, but also is an _anchor of flexibility_ that makes our lives easier in orders of magnitude. This is serious enough that I would rather go with Next or Angular rather than argue this point to death. 

Please give back the control and flexibility we had with Nuxt2 when it has to do with root level app and HTML structure.

**Comment by 53rg0** [comment]
Is it worth waiting for the ID change on release?

**Comment by danielroe** [comment]
As you can see, there is an open PR to implement this.
