### ISSUE TITLE
scss additionalData

### ISSUE THREAD

**Issue by cone41** [nuxt/framework#8103]
### Environment

Nuxi 3.0.0-rc.11                                                                                                                                           15:29:56
Nuxt project info:                                                                                                                                         15:29:57

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

`css: {
			preprocessorOptions: {
				scss: {
					additionalData: '@use "./assets/scss/_variables.scss" as *;',
				},
			},
		},`

` ERROR  [sass] Module loop: this module is already being loaded.                                                                                                          15:24:31  
  ╷
1 │ @use "./assets/scss/_variables.scss" as *;$primary-color: #D38A3D;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  assets\scss\_variables.scss 1:1  root stylesheet`

### Describe the bug

When I want to reference my scss variable globally, the command line prompts me 

'
 ERROR  [sass] Module loop: this module is already being loaded.                                                                                                          15:24:31  
  ╷
1 │ @use "./assets/scss/_variables.scss" as *;$primary-color: #D38A3D;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  assets\scss\_variables.scss 1:1  root stylesheet`
It looks like the variable file is referencing itself causing the error, how can I avoid this problem?

**Comment by dsvgl** [comment]
needs to be in vite config section:
```js
vite: {
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: '@use "./assets/scss/_variables.scss" as *;',
      },
    },
  },
},
```

**Comment by cone41** [comment]
> 需要在 vite 配置部分：
> 
> ```js
> vite: {
>   css: {
>     preprocessorOptions: {
>       scss: {
>         additionalData: '@use "./assets/scss/_variables.scss" as *;',
>       },
>     },
>   },
> },
> ```

This code is already in my configuration, but it still prompts me with this error:
Module loop: this module is already being loaded.

**Comment by dsvgl** [comment]
Must something with your setup then.
Here is a minimal working example: https://stackblitz.com/edit/github-cgmzx4?file=app.vue

**Comment by rafifn** [comment]
it works for me
```
vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@import "@/assets/scss/_mixins.scss"; @import "@/assets/scss/_variables.scss";',
        },
      },
    },
  },
 ```
