### ISSUE TITLE
Watchpack Error (initial scan): Error: ENOTDIR: not a directory, scandir

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#811]
https://github.com/productfrontenddeveloper/nuxt3_bug

###  Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.0`
- Nuxt Version:     `2.16.0-27226092.034b9901`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `components`, `css`, `head`, `router`, `loading`, `buildModules`, `image`, `modules`, `build`, `plugins`, `pwa`, `i18n`, `auth`, `server`, `axios`, `apollo`, `publicRuntimeConfig`
- Runtime Modules:  `@nuxtjs/auth-next@5.0.0-1624817847.21691f1`, `nuxt-tailvue@1.0.91`, `@nuxtjs/axios@5.13.6`, `@nuxtjs/i18n@7.0.3`, `@nuxtjs/sentry@5.1.3`, `nuxt-viewport@0.0.7`, `@nuxt/image@0.6.0`, `@nuxtjs/apollo@4.0.1-rc.5`, `@nuxtjs/universal-storage@0.5.9`, `@nuxtjs/pwa@3.3.5`
- Build Modules:    `nuxt-use-motion@2.0.0-beta.5`, `@nuxtjs/date-fns@1.5.0`, `@pinia/nuxt@0.0.4`, `@nuxt/bridge@3.0.0-27234169.3c132a8`
------------------------------

### Describe the bug and expected behavior

![CleanShot 2021-10-12 at 19 52 58@2x](https://user-images.githubusercontent.com/38668796/136999048-563f380a-8d70-4618-9c00-93b38204df86.png)

### Steps to
yarn install
yarn dev

**Comment by productfrontenddeveloper** [comment]
@danielroe thank you danial, fixed vue-filepond but date-fns problem some.
iam update my repo.

**Comment by jlowgren** [comment]
Hey everyone. Very excited to upgrade our web application to Nuxt 3, but this one's still a blocker for us. Any work being done on `@nuxtjs/date-fns` to resolve the above mentioned issues?

If not, any pointers on what we could do to help out?

**Comment by zulvkr** [comment]
Hi, @productdevbook, I know this is old. Care to share your solution for vue-filepond? I thought I will use filepond core instead if I can't make it work.
