### ISSUE TITLE
Form submits after input is active

### ISSUE THREAD

**Issue by sduncan-mbt** [nuxt/framework#8126]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/sduncan-mbt/form-www.git

### Describe the bug

When I click on the input field the form is submitted without any other action being taken.

**Comment by antlionguard** [comment]
Because you add `@click.prevent` event into your form. Form will submit wherever you click into form. You should change  `@click.prevent` to `@submit.prevent`.

**Comment by sduncan-mbt** [comment]
Hahaha :o) oh dear the amount of time I spent looking at that and didn't notice, my bad. Cheers.
