### ISSUE TITLE
Routes not registered when page file created

### ISSUE THREAD

**Issue by MaiShe** [nuxt/framework#8130]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.12.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. install a new nuxt 3 project
2. change app.vue `<template><NuxtPage><template/>`
3. create index.vue file in pages/ directory
``<template><div>home</div><template/>``
5. Visit http://localhost:3000 show 404 page not found
6. stop the serve and restart  with `npm run dev`
7. http://localhost:3000 works. show home
8. then create test.vue in pages/
``<template><div>test</div><template/>``
9. Visit http://localhost:3000 show 404 page not found

### Describe the bug

#4522 #4318
I saw that someone created the same issue six months ago. but the problem still exist

**Comment by ojvribeiro** [comment]
I think this one is related too: https://github.com/nuxt/framework/issues/7855
