### ISSUE TITLE
add vite/client to compilerOptions.types in tsconfig.json for nuxt3

### ISSUE THREAD

**Issue by nymphaea-v1** [nuxt/framework#8132]
### Describe the feature

Since Nuxt 3 uses Vite v3 I suggest adding vite's client types to extended `tsconfig` when using vite as described [here](https://vitejs.dev/guide/features.html#client-types). 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/5351.
