### ISSUE TITLE
navigateTo causes hydration errors from route middleware (client only)

### ISSUE THREAD

**Issue by Kapcash** [nuxt/framework#8135]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-pednm9?file=README.md

### Describe the bug

When loading the app from server side, any `navigateTo` called in a **route middleware** client side will likely cause **hydration errors**.
Hydration hasn't kicked in yet when the app is redirected to another page, so the DOM structure can be really different.

It kind of loses the interrest of making route guards with redirects on the initial render.

I would maybe expect that the hydration stops, and the targeted page to render in normal SPA mode to avoid having mismatches?

### Additional context

Maybe related to https://github.com/nuxt/framework/issues/6439 ?

**Comment by sweetroll** [comment]
I have a similar error that could be related where navigateTo doesn't stop execution of the page it is supposed to be navigating away from.

[https://stackblitz.com/edit/github-rfzcwh?file=README.md](https://stackblitz.com/edit/github-rfzcwh?file=README.md)

Middleware successfully navigates away from my index page but causes errors in the terminal as it tries to run the protected code.

**Comment by danielroe** [comment]
Yes, you should not redirect on client-side initial load. You should either redirect on server, render that page as client-only, or wait to hydrate the app before performing a redirection.

**Comment by docmattman** [comment]
@sweetroll, did you ever solve your issue above?  I'm hitting the same thing as you.  When I return `navigateTo` in my middleware it doesn't stop the execution of the template and shows errors in the console from missing data when running the protected code.

Returning `abortNavigation` appears to work fine and avoids the errors as it doesn't seem to try to run the protected template code.  But `navigateTo` looks like it's still trying to execute the protected template/code.

**Comment by sweetroll** [comment]
@docmattman no unfortunately. I refactored my code a bit to avoid fatal errors which involved duplicating some of the checks done in the middleware. Not ideal so it is something I want to revisit when I have time.
