### ISSUE TITLE
@types/node version

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/framework#8142]
Hello 👋,

How can we fix this issue for nuxt 3 ? I assume `vue` version and `@types/node` are linked to nuxt version 🧐

See the GitHub issue [here](https://github.com/johnsoncodehk/volar/issues/1985)

![volar](https://user-images.githubusercontent.com/85166574/195441007-4231d953-d653-4b87-8a24-0fa90b941b10.png)

**Comment by manniL** [comment]
You can use yarn resolutions or npm overrides in your projects already ☺️ 

```json
  "resolutions": {
    "@types/node": "18.8.0"
  }

**Comment by anburocky3** [comment]
Waiting for the fix.

**Comment by manniL** [comment]
> Waiting for the fix.

No need to wait, see my post from above ☺️

**Comment by danielroe** [comment]
This is also not a direct dependency of Nuxt, but via `nitropack > rollup-plugin-terser > jest-worker > @types/node`. So it is not possible for Nuxt to resolve this issue.

The workaround provided above is a good solution until it the conflict between `vue` and `@types/node` is resolved.
