### ISSUE TITLE
Vite has a global css issue and the only know work around nuxt3 doesnt support

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt/framework#8143]
### Environment

vite has this nasty issue of duplicating global css into every component used.  This means that if your global variable file is over a 100 lines long and you use 10 components, your outputed file with have 10,000 lines of duplicated css on it.   
The Vite issue is found here https://github.com/vitejs/vite/issues/4448

the problem is NUXT3 doesnt support the only known work around for this issue.  and that is to include your css globally in your main.js.   So in other words nuxt3/vite  cannot support and projects with shared variables and remain performant.

### Reproduction

the vite issue is logged here, they also provided a minimal project to show the issue. 
https://github.com/tastytea-github/vite-global-import-issue-reproduction

### Describe the bug

this bug causes massive files of duplciated css.   in our current project our exported files went from more or less 1.6 mb in gridsome to 6.3 mb in the new nuxt3 RC11.

**Comment by danielroe** [comment]
Could you explain a bit more about your solution?

**Comment by dsvgl** [comment]
@danielroe see answer in corresponding discussion here: https://github.com/nuxt/framework/discussions/8139#discussioncomment-3864265

**Comment by danielroe** [comment]
Oops - cross edit/posted 😄
