### ISSUE TITLE
I made an so called upgrade-downgrade :)

### ISSUE THREAD

**Issue by n4an** [nuxt/framework#8154]
### Environment

nuxt 3

### Reproduction

When I executed command `npx nuxi@latest upgrade --force` I get

> ✔ Successfully upgraded nuxt from 3.0.0-rc.12-27752119.1477d37 to 3.0.0-rc.11    

### Describe the bug

Its an downgrade

**Comment by danielroe** [comment]
Currently `nuxi upgrade` always upgrades to the latest RC, not edge releases. You can follow a PR to add that functionality in https://github.com/nuxt/framework/pull/6998.

**Comment by n4an** [comment]
I don't achieve such level in that to have deals with PR.
