### ISSUE TITLE
Different behavior when call  /api and  /api/

### ISSUE THREAD

**Issue by n4an** [nuxt/framework#8158]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.12-27759910.9e6d292`
- Nitro Version:    `0.5.5-27758232.d90c938`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

`http://localhost:3000/api/` return `{"url":"/api/","statusCode":404,"statusMessage":"Page not found","message":"Page not found","stack":""}

`http://localhost:3000/api` return  html page`

```404
Page not found: /api

[Go back home](http://localhost:3000/)
```

I have catch all file in api `[...].ts`

```
/**
 * @file
 */ 

import { createError, defineEventHandler } from 'h3'

export default defineEventHandler(() => {
  return createError({
    statusCode: 404,
    statusMessage: 'Page not found'
  })
})
```

### Describe the bug

Different behavior when call  /api and  /api/

But if I will have in  api `[...].ts` some code like https://github.com/nuxt/framework/issues/8020

```
import { createRouter, useBase } from 'h3';

const router = createRouter()
.get('/', () => {
  return 'Hello Nuxt3';
});

export default useBase('/api', router.handler);

```

It return 404 in one case and data in other.

**Comment by n4an** [comment]
That will not return json 404 error but html `404 Cannot find any route matching /.`

```
import { createRouter, useBase } from 'h3';

const router = createRouter()
.get('*', () => {
  return 'Hello Nuxt3';
});

export default useBase('/api', router.handler);
```

**Comment by danielroe** [comment]
I think we can track in https://github.com/nuxt/framework/issues/7458.
