### ISSUE TITLE
`useHead` styles innerHTML clears when repeating router push on currently set route

### ISSUE THREAD

**Issue by Kasparas-G55** [nuxt/framework#8181]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12-27761401.9fa147d`
- Nitro Version:    `0.5.5-27758232.d90c938`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[Repository](https://github.com/Kasparas-G55/usehead-styles-bug)

### Describe the bug

Clicking on `NuxtLink` that has the current set route will clear styles innerHTML.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

Let me know if not and I'll reopen.

**Comment by Kasparas-G55** [comment]
> This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.
> 
> Let me know if not and I'll reopen.

In the next RC as in rc.13 or when rc.12 fully releases? Because this bug is on the edge channel.

**Comment by danielroe** [comment]
cc: @harlan-zw

**Comment by harlan-zw** [comment]
Hey @Kasparas-G55 

Thanks for the issue and reproduction. I've investigated this and have sent a PR to resolve it
