### ISSUE TITLE
typescript error with event handlers in tsx

### ISSUE THREAD

**Issue by robozevel** [nuxt/framework#8200]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-xemd3s?file=app.tsx

### Describe the bug

getting this typescript error when using an onClick handler in a tsx file:

> Type '() => void' is not assignable to type 'MouseEvent'.(2322)
> runtime-dom.d.ts(1407, 15): The expected type comes from property 'onClick' which is declared here on type 'ElementAttrs<ButtonHTMLAttributes>'

**Comment by cuebit** [comment]
Tracking:
- vuejs/core#6855
- johnsoncodehk/volar#1985
- DefinitelyTyped/DefinitelyTyped#62729

**Comment by danielroe** [comment]
This seems to have been resolved upstream.
