### ISSUE TITLE
Pages are ignored when a server route is placed at top level and set to catch-all

### ISSUE THREAD

**Issue by Redemption198** [nuxt/framework#8215]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Reproduction is available [here](https://stackblitz.com/edit/nuxt-starter-6nruup).

Visit `/` and the server route responds with `undefined` (which is technically correct as there's no parameter).

### Describe the bug

Pages are ignored when a server route is placed at `server/routes/[parameter].ts`

Expected behaviour (based on reproduction):
- `http://localhost:3000/` -> `pages/index.vue`
- `http://localhost:3000/test` -> `pages/test.vue`
- `http://localhost:3000/<parameter>` -> Nuxt Server Route responds with `<parameter>`

Actual behaviour (based on reproduction):
- `http://localhost:3000/` -> Nuxt Server Route responds with `undefined`
- `http://localhost:3000/test` -> Nuxt Server Route responds with `test`
- `http://localhost:3000/<parameter>` -> Nuxt Server Route responds with `<parameter>`

I don't know if am I using it wrong or there's some configuration for this.

**Comment by danielroe** [comment]
Nitro routes are 'first' in priority and the 'vue routes' are lower down in the stack. This is because Nitro doesn't know what routes are registered by the vue app and so as long as nothing responds from the nitro routes, it's left up to vue-router to handle the response, whatever kind of response it is.

So the actual behaviour is correct. In your case you may be able to resolve by using a nitro middleware.

**Comment by Redemption198** [comment]
> 

Thanks for the explanation, I've modified the [reproduction](https://stackblitz.com/edit/nuxt-starter-6nruup) and added a simple check for `event.context.params.a` and return `a` only if it exists, when visiting `/` (or also `/test`) a `404 Cannot find any route matching /.` is returned.

**Comment by danielroe** [comment]
The issue is that the route _handles_ those routes too. If you need to handle only a defined list of parameters and can't register a more specific pattern, a middleware will likely to what you want.

**Comment by Redemption198** [comment]
I'm trying to use a middleware as suggested, I'm not sure how to redirect to the Vue routes
```
export default defineEventHandler((event) => {
  if (event.req.url === '/' || event.req.url === '/test') {
    // Use Vue Route Here
  }
});
```

**Comment by danielroe** [comment]
Like this: https://stackblitz.com/edit/nuxt-starter-6nruup.

**Comment by Redemption198** [comment]
That's what I was trying but with the catch-all route (which is missing from your fork) it still gets through it and none of the vue pages are rendered. Updated [reproduction](https://stackblitz.com/edit/nuxt-starter-9uqdzg?file=server/routes/[a].get.ts).

**Comment by danielroe** [comment]
The point is that _instead_ of `~/routes/[a].get.ts` you handle it all in the middleware.

**Comment by Redemption198** [comment]
I'm sorry I didn't get it, now I've managed to get it to work like I wanted. Thanks!
