### ISSUE TITLE
Unable to call nuxt kit in Nest.js

### ISSUE THREAD

**Issue by hnviradiya** [nuxt/framework#8220]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------[](url)

### Reproduction

Install npm packages and do `npm run start`

[nest-with-nuxt.zip](https://github.com/nuxt/framework/files/9792898/nest-with-nuxt.zip)

### Describe the bug

Nuxt kit is not allowed with typescript (nestjs) and gives the following error.

```
const kit_1 = require("@nuxt/kit");
              ^
node_modules/source-map-support/source-map-support.js:496
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\meera\Desktop\nest-with-nuxt\nest-with-nuxt\node_modules\@nuxt\kit\dist\index.mjs not supported.
Instead change the require of C:\Users\meera\Desktop\nest-with-nuxt\nest-with-nuxt\node_modules\@nuxt\kit\dist\index.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\meera\Desktop\nest-with-nuxt\nest-with-nuxt\dist\src\main.js:5:15)
```

### Additional context

We are serving nuxt app from nest js, so no separate hosting is needed.

### Logs

```shell
const kit_1 = require("@nuxt/kit");
              ^
node_modules/source-map-support/source-map-support.js:496
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\meera\Desktop\nest-with-nuxt\nest-with-nuxt\node_modules\@nuxt\kit\dist\index.mjs not supported.
Instead change the require of C:\Users\meera\Desktop\nest-with-nuxt\nest-with-nuxt\node_modules\@nuxt\kit\dist\index.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\meera\Desktop\nest-with-nuxt\nest-with-nuxt\dist\src\main.js:5:15)
```
```

**Comment by danielroe** [comment]
This isn't an issue with TS or with kit. The issue is that `@nuxt/kit` is ESM (`type: module`) and you are requiring it from a CJS context.

**Comment by hnviradiya** [comment]
Thank you @danielroe I am attaching a working project for any other who is facing the same problem and is based on the solution you provided. 
[nest-with-nuxt.zip](https://github.com/nuxt/framework/files/9794134/nest-with-nuxt.zip)
