### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by jacky-yanglei** [nuxt/framework#8244]
### Environment

Operating System: Window 11
Node Version: v16.18.0
Nuxt Version: 3.0.0-rc.11
Package Manager: yarn@1.22.17
Builder: vite
User Config: css, modules, experimental, runtimeConfig
Runtime Modules: 
"@nuxtjs/strapi": "^1.5.1",
"@ant-design/icons-vue": "^6.1.0",
"@esbuild-plugins/node-globals-polyfill": "^0.1.1",
"@esbuild-plugins/node-modules-polyfill": "^0.1.4",
"@rollup/plugin-inject": "^4.0.4",
"@toruslabs/torus-embed": "^1.36.1",
"@walletconnect/web3-provider": "^1.8.0",
"ant-design-vue": "^3.2.12",
"buffer": "^6.0.3",
"echarts": "^5.3.3",
"ethers": "^5.7.1",
"events": "^3.3.0",
"less": "^2.7.3",
"less-loader": "^11.0.0",
"moment": "^2.29.4",
"nprogress": "^0.2.0",
"random-js": "^2.1.0",
"rollup-plugin-node-polyfills": "^0.2.1",
"set.js": "^0.6.0",
"streams": "^0.0.9",
"sweetalert2": "^11.4.33",
"url": "^0.11.0",
"vue-i18n": "^9.2.2",
"walletlink": "^2.5.0",
"web3": "^1.8.0",
"web3modal": "^1.9.9"
Build Modules: -

### package.json
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/strapi": "^1.5.1",
    "nuxt": "3.0.0-rc.11",
    "vite-plugin-require-transform": "^1.0.3"
  },
  "dependencies": {
    "@ant-design/icons-vue": "^6.1.0",
    "@esbuild-plugins/node-globals-polyfill": "^0.1.1",
    "@esbuild-plugins/node-modules-polyfill": "^0.1.4",
    "@rollup/plugin-inject": "^4.0.4",
    "@toruslabs/torus-embed": "^1.36.1",
    "@walletconnect/web3-provider": "^1.8.0",
    "ant-design-vue": "^3.2.12",
    "buffer": "^6.0.3",
    "echarts": "^5.3.3",
    "ethers": "^5.7.1",
    "events": "^3.3.0",
    "less": "^2.7.3",
    "less-loader": "^11.0.0",
    "moment": "^2.29.4",
    "nprogress": "^0.2.0",
    "random-js": "^2.1.0",
    "rollup-plugin-node-polyfills": "^0.2.1",
    "set.js": "^0.6.0",
    "streams": "^0.0.9",
    "sweetalert2": "^11.4.33",
    "url": "^0.11.0",
    "vue-i18n": "^9.2.2",
    "walletlink": "^2.5.0",
    "web3": "^1.8.0",
    "web3modal": "^1.9.9"
  }
}
```
### nuxt.config.ts
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill';
``` 
export default defineNuxtConfig({
    alias: {
    },
    hooks: {
    },
    vite: {
        plugins: [
            {
                name: 'process-env-transformer',
                transform(code, id) {
                    let transformedCode = code.replace(/process.env/g, 'import.meta.env');
    
                    return {
                        code: transformedCode
                    }
                },
                enforce: 'pre'
            },
        ],
        optimizeDeps: {
            esbuildOptions: {
                define: {
                    global: 'globalThis',
                },
                plugins: [
                    NodeGlobalsPolyfillPlugin({
                        process: true,
                        buffer: true,
                    }),
                    // NodeModulesPolyfillPlugin()
                ],
            },
        },
    },
    router: {
        scrollBehavior (to, from, savedPosition) {
            return {x: 0, y: 0};
        }
    },
    
    meta: {
        link: [
            {
                rel: 'stylesheet',
                href: '/sweetalert2/dist/sweetalert2.min.css',
            }
        ],
        script: [
            {
                type: "text/javascript",
                src: "/sweetalert2/dist/sweetalert2.min.js",
            },
        ]
    },
    plugins: [
        {
            mode: 'client',
            src: '~/plugins/wallet_helper.ts',
        },
    ],
    css: [
        '@/assets/css/custom.less',
    ],
    modules: [
        '@nuxtjs/strapi'
    ],
    strapi: {
        url: 'http://localhost:2337',
        prefix: '/api',
        version: 'v4',
        cookie: {},
        cookieName: 'strapi_jwt'
    }
})
```
![image](https://user-images.githubusercontent.com/17645850/196088360-d5b21fe2-96e2-4198-9fc8-0b293b78216b.png)
![image](https://user-images.githubusercontent.com/17645850/196088384-91dbad38-4b47-4b95-9946-e4254907f91c.png)

### Describe the bug
Running the project in local dev mode is no problem。
After building the project, the error "process is not defined" appears in the browser console, and all events in the page cannot be executed

**Comment by danielroe** [comment]
Likely you have a node dependency bundled in your browser code. It's impossible to say without a reproduction, but I would search through your node modules to find the piece of code concerned, and add the library to your `build.transpile` array.
