### ISSUE TITLE
I can't read environment variables in http.ts

### ISSUE THREAD

**Issue by jianxing-xu** [nuxt/framework#8269]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12-27767306.96a8807`
- Nitro Version:    `0.6.0-27767213.0be380d`
- Package Manager:  `yarn@1.22.4`
- Builder:          `vite`
- User Config:      `modules`, `server`, `runtimeConfig`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-q1hk7e-bnz2rb?file=package.json,http.js

### Describe the bug

How do i get the environment variables `http.ts`

**Comment by danielroe** [comment]
You should instead use `useRuntimeConfig()` - Nuxt does not guarantee you can access any arbitrary environment variable in the built version of your site.
