### ISSUE TITLE
postInstall `ts` script can't work, because of miss `tsconfig.json`

### ISSUE THREAD

**Issue by chris-zhu** [nuxt/framework#8276]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `pnpm@7.13.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

There is a [reproduction](https://github.com/chris-zhu/chris.me), but not minimal, sorry.

You can catch that error with use `ni`.

### Describe the bug

Hi, i have a ts script, it's run at `postInstall`, but there is no `.output` dir and `tsconfig.json` file when installed.
So, i catch this error `Error: File './.nuxt/tsconfig.json' not found.`.

Unless change the file type, has anyway to resolve it?

**Comment by manniL** [comment]
Running `nuxi prepare` before the postinstall script should create the necessary `.nuxt` folder including the tsconfig ☺️
