### ISSUE TITLE
nuxt instance unavailable with useAsyncData - explained

### ISSUE THREAD

**Issue by misaon** [nuxt/framework#8290]
Related https://github.com/nuxt/framework/issues/5238

### Environment

```
- Operating System: `Linux`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

https://stackblitz.com/edit/github-eusand

### Describe the bug

Greetings to the Nuxt development team and thank you so much for the great work. I'm trying to create a module that will communicate with our store's API. However, I ran into a problem that has been addressed here a few times. It is about using useAsyncData after await. This is because Nuxt prints the error "nuxt instance unavailable". I understand the reason why this is the case (series of https://www.vuemastery.com/blog/coding-better-composables-1-of-5). I can only use it in the setup part. However, I can't find a way in the Nuxt ecosystem to achieve currency retrieval (see stackblitz reproduction). If I just use $fetch, I lose the great functionality that useAsyncData offers. There is no way in composables or plugins to make two async requests in one method, which is often enough needed.

### Additional context

Is there a way to deal with this issue at the Nuxt level?

### Logs

```shell
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable
    at Module.useNuxtApp (/home/misaon/PhpstormProjects/nuxt-async/node_modules/nuxt/dist/app/nuxt.mjs:142:13)
    at Module.useAsyncData (/home/misaon/PhpstormProjects/nuxt-async/node_modules/nuxt/dist/app/composables/asyncData.mjs:26:38)
    at Object.get (/home/misaon/PhpstormProjects/nuxt-async/composables/useHttp.ts:16:34)
    at Object.getShopBaseCurrency (/home/misaon/PhpstormProjects/nuxt-async/composables/useShop.ts:9:17)
    at /home/misaon/PhpstormProjects/nuxt-async/plugins/bootstrap.ts:13:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by andymark-by** [comment]
After update from `3.0.0-rc.11` to `3.0.0-rc.12`

Have the same issue, use `useAsyncData()` outside `<script setup>` as a part of the helper to get the post data

**Comment by danielroe** [comment]
Let's include this explanation in https://github.com/nuxt/framework/issues/6996.
