### ISSUE TITLE
 WARN  [h3] Implicit event handler conversion is deprecated.  Route: /_tailwind 

### ISSUE THREAD

**Issue by andysay** [nuxt/framework#8302]
### Environment

Nuxi 3.0.0-rc.12                                                                                                                                                                                                   22:06:35
RootDir: /Users/andreyleonov/Desktop/ddrw/client                                                                                                                                                                   22:06:35
Nuxt project info: (copied to clipboard)                                                                                                                                                                           22:06:35

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `modules`, `progress`, `vue`, `runtimeConfig`, `css`, `buildModules`, `build`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.5`, `nuxt-progress@0.1.6`
- Build Modules:    `@pinia/nuxt@0.4.3`
------------------------------

### Reproduction

updated from 11 to 12 rc.

### Describe the bug

```

 WARN  [h3] Implicit event handler conversion is deprecated. Use eventHandler() or fromNodeMiddleware() to define event handlers.                                                                                  
     Route: /_tailwind 
     Handler: (req, res) => {
        if (req.originalUrl === withoutTrailingSlash(route)) {
          res.writeHead(301, { Location: withTrailingSlash(req.originalUrl) });
          return res.end();
        }
        _viewerDevMiddleware(req, res);
      }
```

**Comment by rogadev** [comment]
I'm also getting this warning.
```js
import { CompatibilityEvent } from 'h3'

export default async (event: CompatibilityEvent) => {
  return 'Testing...'
}
```
Wondering if it's something to do with the way I did it or a bug. Any insight?

**Comment by misaon** [comment]
Create issue on https://github.com/nuxt-modules/tailwindcss/issues

@rogadev 
![image](https://user-images.githubusercontent.com/15806356/196634077-5ea44dc7-2d87-4d5b-8c68-5a97e5db4b6b.png)

**Comment by vanling** [comment]
https://github.com/nuxt-modules/tailwindcss/pull/545
There is already a PR for this :) coming soon i hope <3

**Comment by vanling** [comment]
https://github.com/nuxt-modules/tailwindcss/releases/tag/v6.0.0 Just released :) can be closed now.

**Comment by andysay** [comment]
> https://github.com/nuxt-modules/tailwindcss/releases/tag/v6.0.0 Just released :) can be closed now.

thanks

**Comment by WalterKstro** [comment]
I was update the version of module nuxt tailwindcss to v6.0.1
