### ISSUE TITLE
Getting error after updating nuxt 3 latest version 3.0.0-rc.12

### ISSUE THREAD

**Issue by hirenramoliyaiwb** [nuxt/framework#8316]
### Environment

`
 WARN  [h3] Implicit event handler conversion is deprecated. Use eventHandler() or fromNodeMiddleware() to define event handlers.                                15:32:37  
     Route: /_tailwind
     Handler: (req, res) => {
        if (req.originalUrl === withoutTrailingSlash(route)) {
          res.writeHead(301, { Location: withTrailingSlash(req.originalUrl) });
          return res.end();
        }
        _viewerDevMiddleware(req, res);
      }
`

### Reproduction

[https://stackblitz.com/edit/github-znnnqs-aafb4f?file=package.json](https://stackblitz.com/edit/github-znnnqs-aafb4f?file=package.json)

### Describe the bug

Getting below error while starting server:

``
 WARN  [h3] Implicit event handler conversion is deprecated. Use eventHandler() or fromNodeMiddleware() to define event handlers.                                15:32:37  
     Route: /_tailwind
     Handler: (req, res) => {
        if (req.originalUrl === withoutTrailingSlash(route)) {
          res.writeHead(301, { Location: withTrailingSlash(req.originalUrl) });
          return res.end();
        }
        _viewerDevMiddleware(req, res);
      }
``

### Additional context

efwef

```

**Comment by hirenramoliyaiwb** [comment]
@danielroe could you please help me?

**Comment by danielroe** [comment]
Upgrade to v6 of the tailwind module and you should be fine.

**Comment by hirenramoliyaiwb** [comment]
@danielroe That's fine but how to upgrade v6 any command?

**Comment by danielroe** [comment]
You can update your package.json and rerun your package manager's install command.

**Comment by hirenramoliyaiwb** [comment]
@danielroe 
getting this error : 

`[Vue warn]: Unhandled error during execution of setup function 
  at <Anonymous key="default" name="default" hasTransition=true >`

**Comment by danielroe** [comment]
Please create a new issue with a reproduction. 🙏

**Comment by hirenramoliyaiwb** [comment]
@danielroe ok

**Comment by hirenramoliyaiwb** [comment]
@danielroe please check my reproduction here 
[https://stackblitz.com/edit/nuxt-starter-3nbzan?file=package.json](https://stackblitz.com/edit/nuxt-starter-3nbzan?file=package.json)
