### ISSUE TITLE
Static : True not working on route rules

### ISSUE THREAD

**Issue by TomDoFuture** [nuxt/framework#8320]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.12.2`
- Builder:          `vite`
- User Config:      `vite`, `vue`, `routeRules`, `typescript`, `buildModules`, `modules`, `runtimeConfig`, `plugins`, `head`, `build`, `components`, `css`, `publicRuntimeConfig`
- Runtime Modules:  `nuxt-graphql-client@0.1.19`
- Build Modules:    `@nuxtjs/tailwindcss@5.3.3`

### Reproduction

Define a route rule with    {static : true}

### Describe the bug

Documentation says static html file is generated on demand, meaning if I visit the page it will generate the html then keep that file.

Doesn't happen, tried npm run dev and npm run build. Checked the client folder inside of .output and no html is generated

**Comment by danielroe** [comment]
`static` currently only has an effect in netlify environment, with node/vercel/etc coming soon.

**Comment by danielroe** [comment]
I've opened https://github.com/unjs/nitro/issues/603 and https://github.com/unjs/nitro/issues/604 to track.

**Comment by TomDoFuture** [comment]
You can close this then!
