### ISSUE TITLE
Getting the error while updating nuxt 3 rc 12 and tailwind 6 

### ISSUE THREAD

**Issue by hirenramoliyaiwb** [nuxt/framework#8323]
### Environment

nuxt 3 rc12
tailwind v6

### Reproduction

[https://stackblitz.com/edit/nuxt-starter-3nbzan?file=package.json](https://stackblitz.com/edit/nuxt-starter-3nbzan?file=package.json)

### Describe the bug

@danielroe @misaon @vanling
  While starting the server then getting this error :

`[Vue warn]: Unhandled error during execution of setup function 
  at <Anonymous key="default" name="default" hasTransition=true >`

**Comment by danielroe** [comment]
Your reproduction has a couple of dependencies (particularly `@nuxtjs/pwa`) which are not nuxt 3 compatible and are bringing in outdated dependencies (namely `defu`). When I remove them, I don't get any issue, cloning it locally.

**Comment by hirenramoliyaiwb** [comment]
@danielroe  now check reproduction, I have changed and removed unnecessary dependencies

**Comment by danielroe** [comment]
Are you actually getting that error while running the stackblitz?

With that stackblitz, I don't get any errors at all, either in dev or in build+start. (Note that I currently have to add `experimental.writeEarlyHints: false` to get sb to run; they are fixing this.)

See https://stackblitz.com/edit/nuxt-starter-h6bfru - it's working fine.

Just for your information (though none of these is the issue):

* in rc12 `viewport` and `charset` shortcuts only work in `nuxt.config`
* postcss plugins should not need to be configured if you are using tailwindcss module
* if you _were_ to configure them they live under a new top-level `postcss` property in nuxt.config
