### ISSUE TITLE
mounted/onMounted hook never fires

### ISSUE THREAD

**Issue by paddotk** [nuxt/framework#8328]
### Versions
- nuxt: 3.0.0-rc.8
- node: 16.14.2

### Reproduction
Load a component in your app with a `mounted()` hook, e.g.

```javascript
<script lang="js">
export default {
  created() {
    console.log('foo');
  },
  mounted() {
    console.log('bar');
  }
}
</script>
```

When loading the page, I see `foo` twice in the terminal. But never `bar`. So hooks like `created` and `setup` work just fine. There seem to be no issues in the template and everything in the DOM renders as expected.
I've also tried with the different ways of structuring/defining a component, and e.g. using `onMounted` with Vue's composition API. That doesn't work either...

**Comment by danielroe** [comment]
Great. I'll mark that as resolved then!
