### ISSUE TITLE
[Error] WebSocket connection to 'ws://[::]:4000/ws' failed

### ISSUE THREAD

**Issue by ahoiroman** [nuxt/framework#8330]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.9.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.1`
- Builder:          `vite`
- User Config:      `experimental`, `build`, `buildModules`, `modules`, `publicRuntimeConfig`, `privateRuntimeConfig`, `globalName`, `app`, `intlify`, `http`, `proxy`, `auth`, `tailwindcss`, `googleFonts`
- Runtime Modules:  `@nuxtjs-alt/auth@2.0.20`, `@nuxtjs-alt/http@1.3.18`, `@nuxtjs-alt/proxy@1.3.5`, `@nuxt/content@2.2.0`, `@nuxtjs/tailwindcss@5.3.5`, `@nuxtjs/google-fonts@3.0.0-0`, `@intlify/nuxt3@0.2.4`, `@pinia/nuxt@0.4.3`
- Build Modules:    `@intlify/nuxt3@0.2.4`
------------------------------
```

### Reproduction

Upgrade from rc11 to rc12 and run `npm run dev`

### Describe the bug

The error:

```
[Error] WebSocket connection to 'ws://[::]:4000/ws' failed: The Internet connection appears to be offline.
```

appears in the debug console over and over again. It seems like Nuxt tries to use IPv6 here, which doesn't seem to work on my macOS env. Before, if used "localhost" as hostname.

### Additional context

<img width="725" alt="Bildschirmfoto 2022-10-19 um 16 05 09@2x" src="https://user-images.githubusercontent.com/23051150/196714008-32e350b5-c0e6-4b76-9292-dbefe04480a1.png">
<img width="737" alt="Bildschirmfoto 2022-10-19 um 16 05 28@2x" src="https://user-images.githubusercontent.com/23051150/196714017-9c3421ef-d9a2-4fe7-a34c-f2400be09778.png">

**Comment by ahoiroman** [comment]
Seems to be an issue in nuxt/content, so if no one objects, I'd close this issue.

**Comment by Suniron** [comment]
I'm using `@nuxt/content` since yesterday, and i see the same problem tomorrow..
