### ISSUE TITLE
how to use imports in nuxt.config.ts via paths ?

### ISSUE THREAD

**Issue by m0dch3n** [nuxt/framework#8336]
### Environment

Nuxi 3.0.0-rc.10                                                                                                                                                                       14:35:32
RootDir: /home/workspace/app/packages/app/web                                                                                                                                    14:35:33
Nuxt project info:                                                                                                                                                                     14:35:33

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.9.1`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.19.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

`import { createBackendConfig } from '@mypath/common-api/config/backendConfig'` in your `nuxt.config.ts`

### Describe the bug

 Will result in:

`ERROR  Cannot start nuxt:  Cannot find module '@mypath/common-api/config/backendConfig'`

Which is obvious because, it doesn't know `@mypath` in the context of `nuxt.config.ts`

In Vite I can define this for `vite.config.ts` in `tsconfig.node.json` because this tsconfig is responsible for the `vite.config.ts` due to `  "include": ["vite.config.ts", "./vite.ts"],`

How do I do in nuxt environment for `nuxt.config.ts` ?

**Comment by danielroe** [comment]
you can register `@mypath/common-api` as a package in your `package.json`, either using the `file:` or `link:` protocols.

**Comment by robmontesinos** [comment]
Trying to generate dynamic routes in a static site and I keep getting the error: 'useFetch is not defined.'

**Comment by danielroe** [comment]
Nuxt composables should not be used in your Nuxt config; they are only meant to be used in a Vue context.

You can import `$fetch` from `ohmyfetch` though.

**Comment by robmontesinos** [comment]
Thank you so much @danielroe - you are correct. Unfortunately I received the following error trying to generate dynamic routes for a static site with the above method in the config file - pulling my hair out:

```
 ERROR  Invalid URL ()                                                                                                  16:27:48

  at async $fetchRaw2 (node_modules/ohmyfetch/dist/shared/ohmyfetch.fb8dc89e.mjs:132:20)
  at async getElectionRoutes (nuxt.config.ts:12:35)
  at async nitro:config (nuxt.config.ts:45:21)
  at async initNitro (node_modules/nuxt/dist/index.mjs:1475:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1692:3)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:1718:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:737:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:34:18)
  at async Object.invoke (node_modules/nuxi/dist/chunks/generate.mjs:32:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by danielroe** [comment]
You need to fetch from a full URL. Fetching from `/api/test` only works within Nuxt; elsewhere, you need to use a URL like `https://path.to/my/backend/api/test`.

**Comment by robmontesinos** [comment]
@danielroe Duh!! You da man Dan - thanks so much
