### ISSUE TITLE
Favicon not found when NUXT_APP_BASE_URL is set

### ISSUE THREAD

**Issue by kperont** [nuxt/framework#8345]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `css`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Set the NUXT_APP_BASE_URL environment variable (i.e. `NUXT_APP_BASE_URL=/my-path`)
2. Place favicon in public folder (i.e. `~/public/favicon.ico`)
3. Run server (i.e. `nuxt dev`)

### Describe the bug

When the NUXT_APP_BASE_URL environment variable is set, all public assets located in the `public` directory are accessible through the new base URL. For example, with `NUXT_APP_BASE_URL=/my-path` and `favicon.ico` in `~/public/favicon.ico` (or any other file), the favicon is accessible via `http://localhost:3000/my-path/favicon.ico`.

This is fine for most static files, but is problematic with the favicon given that it is supposed to be automatically consumed/injected. Instead, I receive the following error: `GET http://localhost:3000/favicon.ico 404 (Cannot find any route matching /favicon.ico.)`. This is because the favicon is served at `http://localhost:3000/my-path/favicon.ico`, but it appears Nuxt is ignoring the NUXT_APP_BASE_URL when looking for the favicon.

**Comment by danielroe** [comment]
It's not Nuxt; it's your browser that automatically performs a request to that location.
