### ISSUE TITLE
Global transition with JS hooks

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/framework#8346]
Hello 👋,

I am trying to port my "vue syntax transition" to a more "nuxt friendly" solution. For now I have :

```vue
<script setup lang="ts">
const onBeforeLeave = (el) => {}
const onLeaver = (el, done) => {}
const onEnter = (el, done) => {}
const onAfterEnter = (el) => {}
</script>

<template>
        <router-view v-slot="{ Component }">
          <Transition
            mode="out-in"
            :css="false"
            @before-leave="onBeforeLeave"
            @leave="onLeave"
            @enter="onEnter"
            @after-enter="onAfterEnter"
          >
            <component :is="Component" />
          </Transition>
        </router-view>
</template>
```

that is working quite well. however, the following config coming from [the doc](https://v3.nuxtjs.org/getting-started/transitions#javascript-hooks) doesn't seems to work in `app.vue`:

```js
<script setup lang="ts">
definePageMeta({
  pageTransition: {
    name: 'custom-flip',
    mode: 'out-in',
    onBeforeEnter: (el) => {
      console.log('Before enter...')
    },
    onEnter: (el, done) => {},
    onAfterEnter: (el) => {}
  }
})
</script>
```

**Comment by danielroe** [comment]
`definePageMeta` only works in routes - so in your `pages/` directory. You can pass those same properties directly to `nuxtPage` if you like - it accepts a `transition` prop.

**Comment by BenjaminOddou** [comment]
@danielroe not sure that this syntax with transition prop can help in my case 😕 :

![Capture d’écran 2022-10-19 à 22 15 29](https://user-images.githubusercontent.com/85166574/196794796-6eb91ae7-f0b4-45dd-969e-d00c9bb67a83.png)

**Comment by danielroe** [comment]
try defining the props in your setup function.

**Comment by BenjaminOddou** [comment]
I think it could be great to have an example in the doc because even if the following syntax seems correct to me, it's not working 😅

```vue
<script setup lang="ts">
const onBeforeLeave = (_el) => {}
const onLeaver = (_el, done) => {}
const onEnter = (_el, done) => {}
const onAfterEnter = (_el) => {}
</script>

<template>
        <NuxtPage
          :css="false"
          :transition="{
            mode: 'out-in',
            onBeforeLeave: (_el : HTMLDivElement) => {
              onBeforeLeave(_el)
            },
            onLeave: (_el: HTMLDivElement, done: any) => {
              onLeave(_el, done)
            },
            onEnter: (_el: HTMLDivElement, done: any) => {
              onEnter(_el, done)
            },
            onAfterEnter: (_el: HTMLDivElement) => {
              onAfterEnter(_el)
            },
          }"
        />
</template>
```

**Comment by danielroe** [comment]
I was thinking more:

```vue
<script setup lang="ts">
const transitionProps = {
  mode: 'out-in',
  onBeforeLeave: (_el) => {},
  onLeave: (_el, done) => {},
  onEnter: (_el, done) => {},
  onAfterEnter: (_el) => {}
}

</script>

<template>
  <NuxtPage
    :css="false"
    :transition="transitionProps"
  />
</template>
```

**Comment by danielroe** [comment]
I don't think it's my _syntax_. I think it's the same issue as https://github.com/nuxt/framework/issues/3587.

**Comment by BenjaminOddou** [comment]
> I don't think it's my _syntax_. I think it's the same issue as https://github.com/nuxt/framework/issues/3587.

@danielroe interesting 🤔 so global transitions with JS hooks aren't available for nuxt then

**Comment by danielroe** [comment]
it's an upstream bug in vue. workaround at the moment is to await a nextTick().
