### ISSUE TITLE
Going to a page with app.vue produces a "No match found for location with path "/"" error

### ISSUE THREAD

**Issue by SebbeJohansson** [nuxt/framework#8347]
### Environment

Nuxt project info:                                                                                                                                            21:31:25

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13-27769897.0f2ef5d`
- Nitro Version:    `0.6.0-27768582.4603279`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `telemetry`, `ssr`, `runtimeConfig`, `nitro`, `app`, `css`, `modules`, `storyblok`, `postcss`, `vite`, `i18n`
- Runtime Modules:  `@storyblok/nuxt@4.4.1`, `nuxt-jsonld@2.0.6`, `@nuxtjs/i18n@8.0.0-alpha.2`
- Build Modules:    `-`
------------------------------

### Reproduction

Here is a reproduction version of the issue:
https://stackblitz.com/edit/github-ovnqsy?file=app.vue

### Describe the bug

Going to any route causes a 404 when using app.vue.
Not sure if there is something in my code that does it. Started happening today.

I am hoping its something obvious that I have just missed.

### Additional context

I think it has something to do with how I am running nuxt in my version but I wasn't able to pinpoint what it was despite removing parts of the site.

If needed I can look into making a smaller reproduction version.

### Logs

```shell
vue-router.mjs?v=5a8718be:35 [Vue Router warn]: No match found for location with path "/"
warn @ vue-router.mjs?v=5a8718be:35
storyblok-vue.mjs?v=5a8718be:572 You need to provide an access token to interact with Storyblok API. Read https://www.storyblok.com/docs/api/content-delivery#topics/authentication
at @ storyblok-vue.mjs?v=5a8718be:572
5vue-router.mjs?v=5a8718be:35 [Vue Router warn]: No match found for location with path "/"
warn @ vue-router.mjs?v=5a8718be:35
chunk-Q5TZPECP.js?v=5a8718be:2288 <Suspense> is an experimental feature and its API will likely change.
2vue-router.mjs?v=5a8718be:35 [Vue Router warn]: No match found for location with path "/"
```

**Comment by danielroe** [comment]
The issue is that now, `app/router.options` enables the vue-router integration. (Previously, it did nothing on its own.) And with the vue-router integration, if you have no routes, then you will always have 404s.

Just remove `app/router.options` and you should be good to go. (It was doing nothing for you previously.) Or add a catch-all route.

**Comment by SebbeJohansson** [comment]
@danielroe just to be clear, since my `app/router.options` does stuff, how do I handle the router and scroll behavior when I have an app.vue file? Wouldnt doing a catch all route defeat the purpose of doing the app.vue file to keep the size smaller? 

Maybe I am misunderstanding the reason for it, but couldn't find anything in the docs that helped me.

Removing it didn't help actually. Locally (in the full project) it is doing the same thing:
![image](https://user-images.githubusercontent.com/5083273/196790348-c16a51e7-d05f-479e-bc03-bfdd37cff598.png)
and in the stackblitz, it is just not outputting the contents of the app.vue file, but that might be unrelated.

**Comment by SebbeJohansson** [comment]
I will keep looking at this tomorrow :)

**Comment by danielroe** [comment]
I don't believe it did anything previously.

**Comment by SebbeJohansson** [comment]
@danielroe What do you mean "it did nothing previously"? It literally did stuff! It has code that was functioning as I wanted it to.

Stackblitz doesn't seem to work with nuxt anymore. That is why it is empty when I try to debug my issue there. Same thing is happening to https://v3.nuxtjs.org/examples/composables/use-state for example.

**Comment by danielroe** [comment]
On SB: Yes, we're aware; they are hoping to roll out a fix soon.

On `router.options.ts` - it is _only_ loaded by the Nuxt vue-router integration (= 'pages'. If you did not have a pages folder, or set `pages: true`, or enable pages with nuxt content's document driven mode, then it did nothing unless you manually imported it somewhere.

**Comment by SebbeJohansson** [comment]
Okay thanks for clarifying!

Okay so thats weird. I could have sworn it was doing stuff, but maybe I'm thinking of a different project. I'll have to do some more testing then to see what the issue is since it isn't working even tho I removed the router.options file.

**Comment by SebbeJohansson** [comment]
@danielroe I get that you might not believe me, but I cant figure out any reason why it is still not working even tho I removed `router.options.ts`.

![image](https://user-images.githubusercontent.com/5083273/197030111-3c47b67a-ae72-4cbb-b50a-fb3f44264588.png)

I am out of ideas. I downgraded to rc11 and it is still not working.

**Comment by danielroe** [comment]
I totally believe you. Would you provide a repro of it working?

**Comment by SebbeJohansson** [comment]
Actually, I think i confused it with my old nuxt3 project that is running on http://sebbejohansson.com/. That one is running pages, so that is probably why it has been working! https://github.com/SebbeJohansson/sebbejohansson-front/blob/main/app/router.options.ts

As for a version where it is not working, my full project is having this issue. I have made it public (since its not anything special anyways). Here is the repo: https://github.com/SebbeJohansson/Vrtx.ContentSystem

I made some small changes so that it starts in stackblitz and it is still not showing the contents of app.vue:
https://stackblitz.com/edit/github-ldkbrf?file=nuxt.config.ts,app.vue,package.json

Let me know if I need to do any changes to it so that we can debug it! Could be a completely different issue now, not sure.

**Comment by danielroe** [comment]
The issue in your stackblitz as far as I can tell is that you haven't enabled the i18n module but you are trying to use a composable from it.

![CleanShot 2022-10-21 at 09.24.01.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2022_10_21_at_09_24_01_7880a92096.png)

**Comment by SebbeJohansson** [comment]
Good catch. Looks like a lot of stuff has broken. I will have to revisit this.
