### ISSUE TITLE
Dynamic component not rendering correctly when SSR

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/framework#8359]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `vite-plugin-vue-type-imports/nuxt`
- Build Modules:    `-`

### Reproduction

https://github.com/Rigo-m/markdown-ssr-repro

### Describe the bug

`<component :is="..." v-html="..." />` doesn't print content correctly when loaded from SSR. If we trigger an HMR update, the content gets shown correctly.

Using a simple render function (as you can see in the reproduction) works correctly.

**Comment by danielroe** [comment]
Would you check with Vite SSR (without Nuxt) to see whether this is Vue behaviour? You can start from https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main.

**Comment by Rigo-m** [comment]
On my way!

**Comment by Rigo-m** [comment]
I guess it's a Vue SSR behaviour https://stackblitz.com/edit/github-tkrltv?file=src/pages/Home.vue. Opening a new issue in the correct repository

**Comment by Rigo-m** [comment]
For reference: https://github.com/vuejs/core/issues/6921
