### ISSUE TITLE
Meta tags show in browser but don't work

### ISSUE THREAD

**Issue by darrenpaul** [nuxt/framework#8372]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `target`, `css`, `modules`, `runtimeConfig`, `sanity`, `meta`, `sitemap`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.3`, `@nuxtjs/google-gtag@1.0.4`, `@funken-studio/sitemap-nuxt-3@3.2.0`
- Build Modules:    `-`

### Reproduction

https://alicia-chamaille-portfolio.pages.dev/

### Describe the bug

I have added meta tags to the nuxt.config.ts.

These data can be see when viewing the head from the elements, but when trying to validate they are working, I get errors say no description etc.
These are the sites I'm trying to test on
https://cards-dev.twitter.com/validator
https://rushax.com/tools/meta-description-checker/
https://totheweb.com/learning_center/tool-test-google-title-meta-description-lengths/
https://www.heymeta.com/url/www.thaliarabie.com/

<img width="1114" alt="Screenshot 2022-10-20 at 16 17 15" src="https://user-images.githubusercontent.com/27204436/197059946-eeb6cb33-7acd-4bb0-b413-83595ac50736.png">

No one of them work, any help would be greatly appreciated.

I've done the exact same approach on nuxt v2 and it works

**Comment by danielroe** [comment]
You have set your site to `ssr: false` and so these meta tags are not present in your HTML. If you check the actual HTML returned by your site, it is:

```html

**Comment by darrenpaul** [comment]
> You have set your site to `ssr: false` and so these meta tags are not present in your HTML. If you check the actual HTML returned by your site, it is:
> 
> ```
> <!DOCTYPE html>
> <html >
> <head><link rel="modulepreload" as="script" crossorigin href="/_nuxt/entry.fea502fe.js"><link rel="preload" as="style" href="/_nuxt/entry.7f572e9f.css"><link rel="prefetch" as="script" crossorigin href="/_nuxt/admin.16bf938a.js"><link rel="prefetch" as="script" crossorigin href="/_nuxt/error-component.09ca0da0.js"><link rel="prefetch" as="script" crossorigin href="/_nuxt/default.a012625c.js"><link rel="prefetch stylesheet" href="/_nuxt/default.d5a3909d.css"><link rel="prefetch" as="script" crossorigin href="/_nuxt/routes.0cae0aa5.js"><link rel="prefetch" as="script" crossorigin href="/_nuxt/copy.8b3833bf.js"><link rel="prefetch" as="script" crossorigin href="/_nuxt/no-navigation.4333021b.js"><link rel="prefetch stylesheet" href="/_nuxt/no-navigation.1368caa0.css"><link rel="stylesheet" href="/_nuxt/entry.7f572e9f.css"></head>
> <body ><div id="__nuxt"></div><script>window.__NUXT__={serverRendered:false,config:{public:{},app:{baseURL:"\u002F",buildAssetsDir:"\u002F_nuxt\u002F",cdnURL:""}},data:{},state:{}}</script><script type="module" src="/_nuxt/entry.fea502fe.js" crossorigin></script></body>
> </html>
> ```

Thanks for the reply, unfortunately this doesn't help.
ssr is set to false, the site is also hosted on cloudflare pages.

```import { defineNuxtConfig } from 'nuxt'
import { SITE_OWNER_COPY } from './constants/copy'

const metaTitle = '....'
const metaDescription =
  '....'

const host = '....'
const imageHost = '....'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  ssr: false,
  target: 'static',
  css: ['~/assets/css/global.scss'],
  modules: ['@nuxtjs/tailwindcss', '@nuxtjs/google-gtag', '@funken-studio/sitemap-nuxt-3'],
  runtimeConfig: {
    sanity: {
      token: process.env.NUXT_SANITY_TOKEN
    }
  },
  sanity: {
    projectId: '....'
  },
  meta: {
    title: metaTitle,
    htmlAttrs: {
      lang: 'en',
      amp: true
    },
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/branding.ico' }],
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      {
        hid: 'description',
        name: 'description',
        content: metaDescription
      },
      // Schema.org markup for Google+
      {
        itemprop: 'name',
        content: metaTitle
      },
      {
        itemprop: 'description',
        content: metaDescription
      },
      {
        itemprop: 'image',
        content: imageHost
      }, // Twitter Card
      {
        name: 'twitter:title',
        content: metaTitle
      },
      {
        name: 'twitter:card',
        content: metaDescription
      },
      {
        name: 'twitter:image',
        content: imageHost
      }, // Open Graph data
      {
        hid: 'og:title',
        property: 'og:title',
        content: metaTitle
      },
      {
        hid: 'og:type',
        property: 'og:type',
        content: 'article'
      },
      {
        hid: 'og:url',
        property: 'og:url',
        content: host
      },
      {
        hid: 'og:image',
        property: 'og:image',
        content: imageHost
      },
      {
        hid: 'og:description',
        property: 'og:description',
        content: metaDescription
      }
    ]
  },
  sitemap: {
    hostname: SITE_OWNER_COPY.domain,
    gzip: true,
    exclude: ['/admin'],
    routes: ['/', '/gallery', '/blog', '/about', '/contact'],
    cacheTime: 1
  }
})
```

**Comment by darrenpaul** [comment]
Please can you reopen this issue

**Comment by danielroe** [comment]
The reason they are not there is _because_ you have disabled rendering them by setting SSR to false.

**Comment by danielroe** [comment]
Also note that the correct config is to place them in `app.head`, not in `meta`.

For supporting rendering meta tags when ssr is false, you can follow https://github.com/nuxt/framework/issues/5734.

But probably the best solution is for you to set `ssr: true`.

**Comment by darrenpaul** [comment]
I have tried the app.head and without both, work. I know app.head is the recommended way.

I don't have an issue with the meta tags being rendered. They are being rendered. Something is preventing them from being accessed.

<img width="837" alt="Screenshot 2022-10-21 at 10 58 56" src="https://user-images.githubusercontent.com/27204436/197238817-456cad8a-1aa2-4041-9560-051a411fa3d6.png">

**Comment by danielroe** [comment]
@darrenpaul I don't believe they are being rendered until _client-side_. That is why you see them in the browser. Try loading your site without JavaScript, or performing a curl request:

```bash
curl https://alicia-chamaille-portfolio.pages.dev/
```

You will see that they are not server-rendered.

**Comment by darrenpaul** [comment]
Thanks so much for the help. I'm going to have to find some way to inject the meta data into the page when generating.

**Comment by danielroe** [comment]
You are welcome. You should check out the issue I linked earlier. It may have an example of a workaround. But if not, and you have an operational requirement not to have SSR, then you can inject chunks of html into the head via a nitro plugin.

A final note. I've come across a lot of people who have the idea that they need to disable `ssr` in order to statically generate their sites. That may not be you, but just in case, it is absolutely not true and in fact it's almost the reverse situation.

**Comment by darrenpaul** [comment]
Thanks I might try the nitro method. 

I did some further research and I think bridge is causing the issue. I saw some other tickets that matched my issues.

So I rather going to go back to Nuxt 2 with composition api and leave bridge out. This method has worked for me in the past.

Appreciate all the help 🙂
