### ISSUE TITLE
Generation with SSR and target:static produces incorrect markup.

### ISSUE THREAD

**Issue by ckald** [nuxt/framework#8373]
### Environment

Nuxi 3.0.0-rc.12                                                                                                                                                                         00:36:52
RootDir: /Users/d/Repositories/nuxt-debug/nuxt-app                                                                                                                             00:36:53
Nuxt project info: (copied to clipboard)                                                                                                                                                 00:36:53

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `ssr`, `target`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/ckald/nuxt3-rc12-ssr-bug

### Describe the bug

There are only 2 pages. 

When using `npm run dev` both are rendered and both client-side navigation and URL navigation work.

When trying to compile to static with SSR on, in this example only the main page renders for both URLs. In my website Nuxt mixes up the markup of both pages (and the result varies with the changes in templates).

Looks like Nuxt cannot find the correct root node to render the page in.

**Comment by danielroe** [comment]
Pages need a single root node unless you have disabled transitions.

FYI, `target: static` is only used in Nuxt 2.

**Comment by ckald** [comment]
Then please consider updating your documentation :) https://v3.nuxtjs.org/bridge/overview#static-target

I added a single root node to both pages and updated the repo. The behaviour is the same

**Comment by ckald** [comment]
To be precise, `npm run generate && npm run preview` exhibits the bug.

**Comment by danielroe** [comment]
That is documentation for migrating to Nuxt Bridge, not Nuxt 3.

If you're still experiencing an issue, it might be an issue with the library Nuxt uses to preview your built site: https://github.com/nuxt/framework/issues/6226. Try running `npx serve .output/public` and let me know if that doesn't resolve the issue for you.

**Comment by ckald** [comment]
> That is documentation for migrating to Nuxt Bridge, not Nuxt 3.

Wow the website is confusing. I got to that page by searching "static" on v3.nuxtjs.org. I have no idea what Bridge is.

You are right, without `-s` my example app works. Still very confusing and docs should have prevented this :(

Thanks for the help

**Comment by danielroe** [comment]
You're welcome.
