### ISSUE TITLE
Using useFetch, how to refresh the request with the new body content when the properties within the body change?

### ISSUE THREAD

**Issue by fatcarter** [nuxt/framework#8378]
Nuxt version: 3.0.0-rc.12

```ts
const activeOrder = ref("down")
let {data, refresh, execute} = await useFetch<Page<SoftItem>>(`/api/categories/${props.cateKey}/softs`,{
  method: 'post',
  body:  {
    orderBy: activeOrder.value,
    page: 1,
    pageSize: 5
  }
});
const handleChangle = (value)=>{
  activeOrder.value = value;
  refresh();
}
```
I got old result when call `handleChangle` function.
How do I refresh the request with the new parameters?

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

You would update your code as follows.

```js
const activeOrder = ref("down")
let {data, refresh, execute} = await useFetch<Page<SoftItem>>(`/api/categories/${props.cateKey}/softs`,{
  method: 'post',
  body:  {
    orderBy: activeOrder,
    page: 1,
    pageSize: 5
  }
});
const handleChangle = (value)=>{
  activeOrder.value = value;
  refresh();
}
```

Let me know if not and I'll reopen.

**Comment by YYCarl** [comment]
How to get new request after "page" parameter is updated

**Comment by YYCarl** [comment]
> 这应该在[边缘通道](https://v3.nuxtjs.org/guide/going-further/edge-channel/)中解决，或者在下一个 RC 中解决。
> 
> 您将按如下方式更新您的代码。
> 
> ```js
> const activeOrder = ref("down")
> let {data, refresh, execute} = await useFetch<Page<SoftItem>>(`/api/categories/${props.cateKey}/softs`,{
>   method: 'post',
>   body:  {
>     orderBy: activeOrder,
>     page: 1,
>     pageSize: 5
>   }
> });
> const handleChangle = (value)=>{
>   activeOrder.value = value;
>   refresh();
> }
> ```
> 
> 如果没有，请告诉我，我会重新打开。


How to get new request after "page" parameter is updated

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/pull/8374#issuecomment-1292134096.

**Comment by YYCarl** [comment]
> 请参阅[#8374（评论）](https://github.com/nuxt/framework/pull/8374#issuecomment-1292134096)。

Using is to post the page in the request body, no response

**Comment by danielroe** [comment]
@YYCarl You are welcome to open a discussion or post on discord with some code and people can help you debug it :-)
