### ISSUE TITLE
[nuxt] [request error] [unhandled] [500], "npm run dev"

### ISSUE THREAD

**Issue by Tweniee** [nuxt/framework#8379]
### Environment

npx nuxi info, 

### Reproduction

No a fancy way i just initialized a new project >> then npm i >> then npm run dev >> now refresh localhost:3001
![Screenshot from 2022-10-21 10-32-45](https://user-images.githubusercontent.com/93429474/197116113-e46417d8-7504-4a0c-9b7f-a2b774066d39.png)
![Screenshot from 2022-10-21 10-32-31](https://user-images.githubusercontent.com/93429474/197116119-4b8c14ac-f631-45d1-8a7f-e8ce05d40862.png)

then this is the final result only poping up 

### Describe the bug

[nuxt] [request error] [unhandled] [500] request to http://[::]:3001/__nuxt_vite_node__/manifest failed, reason: connect ENETUNREACH :::3001 - Local (:::0) ()
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/shared/ohmyfetch.fb8dc89e.mjs:132:20)  
  at async ./.nuxt/dev/index.mjs:537:20  
  at async ./.nuxt/dev/index.mjs:608:64  
  at async ./.nuxt/dev/index.mjs:107:22  
  at async Object.handler (./node_modules/h3/dist/index.mjs:567:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:631:7)
[nuxt] [request error] [unhandled] [500] request to http://[::]:3001/__nuxt_vite_node__/manifest failed, reason: connect ENETUNREACH :::3001 - Local (:::0) ()
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/shared/ohmyfetch.fb8dc89e.mjs:132:20)  
  at async ./.nuxt/dev/index.mjs:537:20  
  at async ./.nuxt/dev/index.mjs:608:64  
  at async ./.nuxt/dev/index.mjs:107:22  
  at async Object.handler (./node_modules/h3/dist/index.mjs:567:19)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:631:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/shared/ohmyfetch.fb8dc89e.mjs:132:20)  
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:432:29)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:638:9)
[nuxt] [request error] [unhandled] [500] request to http://[::]:3001/__nuxt_vite_node__/manifest failed, reason: connect ENETUNREACH :::3001 - Local (:::0) ()
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/shared/ohmyfetch.fb8dc89e.mjs:132:20)  
  at async ./.nuxt/dev/index.mjs:537:20  
  at async ./.nuxt/dev/index.mjs:608:64  
  at async ./.nuxt/dev/index.mjs:107:22  
  at async Object.handler (./node_modules/h3/dist/index.mjs:567:19)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:631:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/shared/ohmyfetch.fb8dc89e.mjs:132:20)  
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:432:29)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:638:9)

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

At the _very_ least, we do need some information about your environment.

**Comment by scottyzen** [comment]
I had the same problem. Updating node fixed it for me.

**Comment by karageee** [comment]
I had similar problem as well, it kept spitting out these error messages. I can't visit any other site on a new tab while it was running.
`
[nuxt] [request error] request to http://[::]:3000/__nuxt_vite_node__/invalidates failed, reason: connect ENOBUFS :::3000 - Local (undefined:undefined) ()
  at async $fetchRaw2 (/D:/Hobby/portfolio/node_modules/ohmyfetch/dist/shared/ohmyfetch.fb8dc89e.mjs:132:20)
  at async default (/D:/Hobby/portfolio/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:16:23)
  at async Object.renderToString (/D:/Hobby/portfolio/node_modules/vue-bundle-renderer/dist/index.mjs:264:19)
  at async /D:/Hobby/portfolio/.nuxt/dev/index.mjs:473:20
  at async /D:/Hobby/portfolio/node_modules/h3/dist/index.mjs:592:19
  at async Server.nodeHandler (/D:/Hobby/portfolio/node_modules/h3/dist/index.mjs:538:7)
`

**Comment by danielroe** [comment]
A reproduction, even if minimal, would be appreciated.

**Comment by karageee** [comment]
> A reproduction, even if minimal, would be appreciated.

hey daniel. uuh...
This is a bit embarrassing. I might know why it spews that error code. here's my package.json
```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@nuxt/postcss8": "^1.1.3",
    "autoprefixer": "^10.4.7",
    "nuxt": "3.0.0-rc.3",
    "postcss": "^8.4.14",
    "tailwindcss": "^3.1.2"
  }
}
```
as you can see it was rc3, not rc12. I changed the version to rc12 and it's now running smoothly, I'm very sorry about this. 🙇

**Comment by danielroe** [comment]
No problem at all 😊

**Comment by ion0658** [comment]
I have same problem using it with docker.
It happen from rc11 and rc10 is fine.
It not happen without docker.

- docker version: 20.10.19, build d85ef84

dockerfile
```Dockerfile
FROM node:18.11.0

RUN npx nuxi init app

WORKDIR /app

RUN npm install 

CMD npm run dev

EXPOSE 3000 24678
```

package.json
```Json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.12"
  }
}
```

**Comment by m0dch3n** [comment]
I'm also experiencing this within Docker, since I updated from rc10 to rc12.

Outside of Docker the same project works without any issue.

**Comment by m0dch3n** [comment]
Steps to reproduce:

Install Docker, then

```bash
mkdir nuxt-docker

cd nuxt-docker

echo "FROM node:18.11.0

RUN npx nuxi init app

WORKDIR /app

RUN npm install

CMD npm run dev

EXPOSE 3000 24678" > Dockerfile

docker build -t nuxt-rc12-image .

docker run -d -p 3000:3000 -p 24678:24678 --name nuxt-rc12 nuxt-rc12-image

docker exec -it nuxt-rc12 curl localhost:3000

docker logs nuxt-rc12

docker exec -it nuxt-rc12 npx nuxi info
```

**Comment by nearlyheadless** [comment]
> A reproduction, even if minimal, would be appreciated.
@danielroe 

After updating from rc.11 to rc.12 I ran into the same problem. "GET http://localhost:3000/ 503 (Service Unavailable)"

When using server routes with matching route parameters, it seems that the error occurs when calling the root slash "/". 

So "/api-test/data/home" works
"/api-test/data/" does not work

Reproduction: https://stackblitz.com/edit/github-w7kpzw?file=app.vue

Hope this helps.

**Comment by m0dch3n** [comment]
this is same issue https://github.com/nuxt/framework/issues/7828

**Comment by danielroe** [comment]
Thanks. Let's track there.

**Comment by Asxer** [comment]
Why is it closed? I have the same problem on rc14 so the bug is still there. Did anybody solved it?

**Comment by danielroe** [comment]
Please update to v3.0.0. If you are experiencing an issue, then please create a new issue with a minimal reproduction.

**Comment by joppe2001** [comment]
I still have this issue with nuxt -v 3.0.0

**Comment by danielroe** [comment]
Then please create a new issue with a minimal reproduction. 🙏

**Comment by joppe2001** [comment]
> Then please create a new issue with a minimal reproduction. 🙏

its the exact same thing as the first message in this thread, but now im having it with version 3.0.0

**Comment by joppe2001** [comment]
im running:
 npx nuxi init <filename> 
mkcert localhost
yarn
nuxt dev --https --ssl-cert localhost.pem --ssl-key localhost-key.pem

**Comment by joppe2001** [comment]
> Why is it closed? I have the same problem on rc14 so the bug is still there. Did anybody solved it?

did u ever solve it @Asxer ?

**Comment by JackEdwardLyons** [comment]
> im running: npx nuxi init mkcert localhost yarn nuxt dev --https --ssl-cert localhost.pem --ssl-key localhost-key.pem yarn dev

Yep, I'm running into the same issue when trying to use `https` with `mkcert`.

**Comment by joppe2001** [comment]
> > im running: npx nuxi init mkcert localhost yarn nuxt dev --https --ssl-cert localhost.pem --ssl-key localhost-key.pem yarn dev
> 
> Yep, I'm running into the same issue when trying to use `https` with `mkcert`.

yeah I put out a new issue, but havent heard back yet. my company uses vue and rn its not even possible to use https with localhost on nuxt. kinda annoying

**Comment by danielroe** [comment]
Is it an issue with your certificate? Can you try with just `nuxt dev --https`?

**Comment by joppe2001** [comment]
> Is it an issue with your certificate? Can you try with just `nuxt dev --https`?

ill give that a shot, one sec

**Comment by joppe2001** [comment]
still getting the fetch() error

**Comment by joppe2001** [comment]
could very well be that I am doing something wrong, rn all I did was 
nix nuxi init <filename>
yarn
mkcert localhost
yarn dev --https

**Comment by danielroe** [comment]
Are you using windows?

**Comment by joppe2001** [comment]
> Are you using windows?

no, macOs

**Comment by danielroe** [comment]
I'm proposing running exactly these commands, with no other arguments:

```bash
npx nuxi init some-project
cd some-project
yarn
yarn dev --https
```

**Comment by joppe2001** [comment]
> 

so no mkcert?

**Comment by joppe2001** [comment]
> I'm proposing running exactly these commands, with no other arguments:
> 
> ```shell
> npx nuxi init some-project
> cd some-project
> yarn
> yarn dev --https
> ```

still gives me the error 😅
