### ISSUE TITLE
VSCode Instellisense not wroking on Pinia this keyword

### ISSUE THREAD

**Issue by shba007** [nuxt/framework#8394]
### Environment

Nuxi 3.0.0-rc.12                        
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `modules`, `imports`, `app`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.0.1`, `@pinia/nuxt@0.4.3`, `@vueuse/nuxt@9.3.1`, `nuxt-icons@2.0.2`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-c5k9wv?file=stores/user.ts

### Describe the bug

In pinia actions `this.` does not give proper intellisense 

### Additional context

Change the strict type to true in ./nuxt/tsconfig and then restart the IDE gives intellisense

**Comment by danielroe** [comment]
This isn't a Nuxt error; it's TypeScript behaviour + how pinia is typed.

You can enable strict mode by setting `typescript.strict` to true in your `nuxt.config`.
