### ISSUE TITLE
Page do not scroll to top when navigating with `NuxtLink`

### ISSUE THREAD

**Issue by ojvribeiro** [nuxt/framework#8398]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-z2frqa?file=pages/index.vue

### Describe the bug

Page does not scroll to top when navigating between views with `NuxtLink`, instead it just keeps the scroll position (which is generally not desirable unless when we press the back button).

## Steps to reproduce

- Scroll down to the `TEST` link and click it;
- Scroll down and click `HOME`.

You should see that the home page kept the last scroll position.

**Comment by emaia** [comment]
It's working fine in the edge channel

**Comment by ojvribeiro** [comment]
I tested a clean install of rc12. Both local and Stackblitz showed the same problem.

**Comment by danielroe** [comment]
This fix was merged in https://github.com/nuxt/framework/pull/8327, which was after rc12. You can try it out in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

**Comment by ojvribeiro** [comment]
Oh I got it. Thanks for the clarification.
