### ISSUE TITLE
Render in nuxt 3

### ISSUE THREAD

**Issue by hnviradiya** [nuxt/framework#8409]
### Describe the feature

As in nuxt 2, we were able to do `nuxt.render(req, res)` where nuxt is instance of `import { Nuxt } from 'nuxt'`;

But we are unable to do the same in nuxt 3. I need to serve nuxt app from Nest.js due to security thing, I am only serving the app if a user is authenticated already as for sign in we have a separate project.

Had one open discussion/question as well below.
https://github.com/nuxt/framework/discussions/8233

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
~> #8233.
