### ISSUE TITLE
Using tsx extension in server/api

### ISSUE THREAD

**Issue by walmartwarlord** [nuxt/framework#8417]
### Describe the feature

Hi, I understand that tsx is supported via `@vitejs/plugin-vue-jsx` but I was wondering if it's possible to use tsx files in server/api? Something like `/server/api/generate.tsx`. 

Thanks!

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
No, it's not possible at the moment. Nitro server routes are not built using vite. However, it's possible you could implement a rollup plugin that would do what you want.
