### ISSUE TITLE
Complex runtimeConfig values become `{}` inside the app 

### ISSUE THREAD

**Issue by BracketJohn** [nuxt/framework#8419]
### Environment

```
Nuxi 3.0.0-rc.12                                                                                     14:16:13
RootDir: /home/projects/nuxt-runtimeconfig-complex-objects                                           14:16:14
Nuxt project info:                                                                                   14:16:14

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-runtimeconfig-complex-objects?file=nuxt.config.ts,app.vue

### Describe the bug

When passing a complex object into the runtime config it comes out as an empty object (`{}`) on the other side.

1. When passing in:
```ts
import redisDriver from 'unstorage/drivers/redis';

const driver = redisDriver();
console.log('driver should be: ', driver);

export default defineNuxtConfig({
  runtimeConfig: {
    driver,
  },
});
```

we get:
```sh
driver should be:  {                                                                                 14:18:56
  hasItem: [Function: hasItem],
  getItem: [Function: getItem],
  setItem: [Function: setItem],
  removeItem: [Function: removeItem],
  getKeys: [Function: getKeys],
  clear: [AsyncFunction: clear],
  dispose: [Function: dispose]
}
   
```

2. And then inspecting `driver` inside the `app.vue`:
```vue
<template>
  <div>Checkout the console.logs</div>
</template>

<script setup lang="ts">
if (process.server) {
  const config = useRuntimeConfig();
  console.log('driver is: ', config.driver);
}
</script>
```

we get:
```sh
driver is:  {}
```

Here, I'd expect `driver is: ...` to say the same thing as `driver should be: ...`

### Additional context

This first arose in this [`nuxt-session` PR](https://github.com/sidebase/nuxt-session/pull/7#issue-1419525408) by @Twitch0125. I could imagine that this is due to some de-/serialization happening. I checked [the current runtime config docs](https://v3.nuxtjs.org/guide/going-further/runtime-config) and couldn't find anything about this happening. If some de-/serialization prevents us from using non-primitive config values, I have some ideas for improvements:
1. document it in the runtime config docs
2. use typescript to disallow config values that will not make it through "whole"

Thanks ❤️

**Comment by danielroe** [comment]
Yes, runtime config values set in the Nuxt config file are serialised and deserialised. That is intentional. Any values meant to be more complex can be set in a nitro plugin or other runtime code.

**Comment by BracketJohn** [comment]
Alright, got it - that's what we guessed. 

I've opened https://github.com/nuxt/framework/pull/8432 to clarify this in the docs. Do you think it's worth merging?

**Comment by BracketJohn** [comment]
Sure thing :+1:

**Comment by BracketJohn** [comment]
> Any values meant to be more complex can be set in a nitro plugin or other runtime code.

@danielroe as I'm writing modules I sometimes want the user to be able to non-serializable things. Ideally I would not want them to create a nitro plugin / other runtime code to do this as then it becomes error prone (think: "you need to create file X in location Y and paste in code Z").

Do you have any proposals on how I can pass data from the `nuxt.config` -> `module` -> `runtime` without the data being de-/serialized along the way?

**Comment by danielroe** [comment]
We don't really want users to pass non-serialisable data from `nuxt.config` to the runtime part of the app as it blurs the boundary between configuration and runtime code.

As a module author, you can inject the nitro plugin yourself based on the user's configuration of your module. (Or do various other things depending on your use case.) It's difficult to say in the abstract, but feel free to drop me a line and I'll happily assist.

**Comment by wobsoriano** [comment]
@BracketJohn we also have a Nuxt integration for next still in private because of some upcoming Request/Response changes. And yes, we did not go with passing config via `nuxt.config` because of serialization. 

<img width="563" alt="Screen Shot 2022-10-30 at 11 19 34 PM" src="https://user-images.githubusercontent.com/13049130/198943999-541356c4-abe8-4865-88b6-86900d9ac995.png">

**Comment by BracketJohn** [comment]
Wow, this looks cool! I saw at some point that you were working on this, but also didn't see any further updates (the last one being months ago).

I'm on vacay at the moment, but will reach out!
