### ISSUE TITLE
codesandbox examples are not working

### ISSUE THREAD

**Issue by keithn** [nuxt/framework#8428]
### Environment

no idea

### Reproduction

go to the examples, eg https://v3.nuxtjs.org/examples/routing/layouts

### Describe the bug

it does this...

![image](https://user-images.githubusercontent.com/86080/197431159-bff84dcd-90d2-4a19-82dc-6a5c012f8d6c.png)

**Comment by pi0** [comment]
Thanks for reporting the issue.

We might use nuxt-edge for the meantime (alternative is providing CSB config for each example but might be overkill for temporary fix)

**Comment by danielroe** [comment]
This is now resolved in RC13.
