### ISSUE TITLE
i18n not work any more

### ISSUE THREAD

**Issue by n4an** [nuxt/framework#8433]
### Environment

nuxt 3 edge linux

### Reproduction

https://github.com/n4an/nuxt-error-7

### Describe the bug

[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'locale')
at getLocale (./node_modules/vue-i18n-routing/dist/vue-i18n-routing.mjs:103:229)

**Comment by n4an** [comment]
with en.js error

500
[vite-node] [VITE_ERROR] /.nuxt/i18n.options.mjs

**Comment by n4an** [comment]
https://github.com/nuxt-community/i18n-module/issues/1580

**Comment by danielroe** [comment]
Let's track in the upstream issue first unless it's confirmed this is a nuxt issue.
