### ISSUE TITLE
GET http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=d17c36b2 net::ERR_ABORTED 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by ChurikiTenna** [nuxt/framework#8437]
### Environment

Nuxi 3.0.0-rc.12                                                                                                                         18:24:27
RootDir: /Users/tenna/Desktop/tchersWeb                                                                                                  18:24:27
Nuxt project info: (copied to clipboard)                                                                                                 18:24:27

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.0.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@3.2.3`
- Builder:          `vite`
- User Config:      `ssr`, `components`, `loadingIndicator`, `head`, `css`, `publicRuntimeConfig`, `privateRuntimeConfig`, `plugins`, `modules`, `intlify`, `bootstrapVue`, `build`, `transpile`
- Runtime Modules:  `bootstrap-vue/nuxt`, `@intlify/nuxt3@0.2.4`
- Build Modules:    `-`
------------------------------

### Reproduction

Don't know how to reproduce..
I can give the repository access if that'll help.

### Describe the bug

yarn install
yarn dev
starts to run successfully.
But when I open http://localhost:3000/ on Chrome, it only show blank page.
On console, there are two errors:

GET http://localhost:3000/_nuxt/@vite/client net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/_nuxt/node_modules/.vite/deps/ufo.js?v=c20be8f0 net::ERR_ABORTED 504 (Gateway Timeout)

### Logs

Nuxi 3.0.0-rc.12                                                                                                                         19:30:28
Nuxt 3.0.0-rc.3                                                                                                                          19:30:28
                                                                                                                                         19:30:29
  > Local:    http://localhost:3000/ 
  > Network:  http://169.254.167.183:3000/
  > Network:  http://169.254.193.38:3000/
  > Network:  http://169.254.214.216:3000/
  > Network:  http://169.254.248.35:3000/
  > Network:  http://192.168.1.3:3000/
  > Network:  http://[240b:10:27a2:7e00:413:2357:40f0:c01b]:3000/
  > Network:  http://[240b:10:27a2:7e00:bd3a:ea37:dc9d:30b7]:3000/
  > Network:  http://[240b:10:27a2:7e00:d802:780b:5d63:9841]:3000/
  > Network:  http://[fd6a:92a3:bf0:428c:486:119c:175a:352a]:3000/

ℹ Vite client warmed up in 8226ms                                                                                                        19:30:38
✔ Nitro built in 4564 ms

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by ChurikiTenna** [comment]
@danielroe 
Hi! I have sent you an invitation just now.

**Comment by danielroe** [comment]
You have a number of dependencies that require vue@2 in their peerDependencies, including:

- "portal-vue@npm:^2.1.7"
- "vue-social-sharing@npm:^3.0.9"
- "vue-toastification@npm:^1.7.14"
