### ISSUE TITLE
RC12 header overflow

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt/framework#8441]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Iv been struggling to reproduce this on smaller projects, but its definitely only a problem on RC 12, RC 11 works fine.

I noticed on larger projects that when requesting the router page nuxt RC12 produces a header overflow error on h3. which then causes the entire dev server to crash

### Describe the bug

it seems sometimes when going to routes we get a header overflow error from h3. 

this also seems to only be a problem on nuxt dev, nuxt generate seems to handle everything ok for some reason

### Additional context

![image](https://user-images.githubusercontent.com/93583336/197527137-b631a412-d7fe-4cb9-b6cc-b0ef5576a3ff.png)
![image](https://user-images.githubusercontent.com/93583336/197527153-4ec740da-42d5-490d-9bfb-5e6ff7114d8d.png)

### Logs

```shell
ERROR  [h3] [unhandled] Parse Error: Header overflow                                                                                                                                   13:58:55

  at Socket.socketOnData (node:_http_client:534:22)
  at Socket.emit (node:events:513:28)
  at Socket.emit (node:domain:489:12)
  at addChunk (node:internal/streams/readable:315:12)
  at readableAddChunk (node:internal/streams/readable:289:9)
  at Socket.Readable.push (node:internal/streams/readable:228:10)
  at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by jgupta** [comment]
You may try disabling early hints. Please see https://github.com/nuxt/framework/issues/8306 if that is relevant to you.

```
export default defineNuxtConfig({
  ...
  experimental: {
    writeEarlyHints: false,
  },
  ...
})
```
