### ISSUE TITLE
[RC11] Expected ">" but found "lang"

### ISSUE THREAD

**Issue by szulcus** [nuxt/framework#8444]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `target`, `ssr`, `css`, `buildModules`, `modules`, `vite`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-beta.1`, `nuxt-icons@2.0.2`
- Build Modules:    `unplugin-vue-setup-extend/nuxt`

### Reproduction

I can't create this reproduction error. If it is necessary, I will try to join during the weekend.

### Describe the bug

Today I migrated from RC8 to RC11 and after running `yarn build` I get this error:
```
 ERROR  [vite:esbuild] Transform failed with 1 error:                                                                                                                  16:35:03  
C:/....vue?vue&type=script&lang.ts:1:8: ERROR: Expected ">" but found "lang"
file: C:/.....vue?vue&type=script&lang.ts:1:8

Expected ">" but found "lang"
1  |  <script lang="ts"> export default {name: 'PageCalendarWeekly'}</script><script setup lang="ts" name="PageCalendarWeekly">
   |          ^
2  |  </script>
3  |
```
I'm not sure if it's a Nuxt bug or a Vite bug, but given that it did design before, I assume it's Nuxt. I am using the unplugin-vue-setup-extend package which gives me the appropriate name field for the components. After removing it from the configuration file, the construction proceeds successfully.

### Additional context
To cause this error, delete the `.nuxt` folder

**Comment by manniL** [comment]
A [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction) would be more than appreciated 🙏

**Comment by danielroe** [comment]
I'm going to close this as I think it's likely not an issue with Nuxt itself. Please feel free to provide a reproduction and I'll happily reopen.
