### ISSUE TITLE
`htmlAttrs` and `bodyAttrs` gets overwritten by lowest position tag

### ISSUE THREAD

**Issue by Kasparas-G55** [nuxt/framework#8446]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[GitHub Branch](https://github.com/Kasparas-G55/usehead-styles-bug/tree/htmlAttrs)
[Stackblitz](https://stackblitz.com/github/Kasparas-G55/usehead-styles-bug/tree/htmlAttrs?file=pages/index.vue)

### Describe the bug

useHead `htmlAttrs` and `bodyAttrs` get overwritten even if it's an empty object based on where it is set, priority seems to go like this:

`app.vue` > `layouts` > `pages`

It also applies current pages useHead attribute tags on page reload.

Not sure if this was intended behaviour, but based on previous knowledge how it worked in 3.0.0-rc.11, the attribute tags were only overwritten if they had a value and had attributes set based on this priority:

`pages` > `layouts` > `app.vue` 

### Additional context

_On page reload:_

https://user-images.githubusercontent.com/69148771/197609872-f662ebfe-95bd-4403-b97f-f5be36cda9d6.mp4

https://user-images.githubusercontent.com/69148771/197610947-39bbca38-75da-4813-915a-cad07597c601.mp4

_Tag without props:_

![Capture](https://user-images.githubusercontent.com/69148771/197610196-30404d3a-6786-4d21-9bcf-01072837d90e.PNG)

**Comment by harlan-zw** [comment]
Hey @Kasparas-G55 

Thanks for taking the time to document this issue. I have merged the fix in this [PR](https://github.com/vueuse/head/pull/149).

The fix is available in @vueuse/head 1.0.0-rc.13
