### ISSUE TITLE
why rc.12 does not support node version v14.x

### ISSUE THREAD

**Issue by caohenghu** [nuxt/framework#8449]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@6.14.16`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

-

### Describe the bug

I create a new demo app, then `npm run dev`, When I use node version with v16.x, it's ok. But not work with v14.x.

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/7547646/197667807-9031abb0-5664-4271-b6e4-ced01bad0dab.png">

**Comment by HigherOrderLogic** [comment]
https://github.com/nuxt/framework/pull/8299
https://github.com/nuxt/framework/issues/8335
https://github.com/nuxt/framework/pull/8408

**Comment by danielroe** [comment]
This is resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.
