### ISSUE TITLE
Can't add headers(or in general rules) via routeRules to files in public directory

### ISSUE THREAD

**Issue by xjeventures** [nuxt/framework#8454]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `meta`, `routeRules`, `modules`, `plugins`, `css`, `ionic`
- Runtime Modules:  `@nuxtjs/supabase@0.2.1`, `@nuxtjs/ionic@0.8.0`
- Build Modules:    `-`

### Reproduction

1. Add a file (i.e. `apple-app-site-association`) to` /public/.well-known`
2. Add routeRules to nuxt.config.ts:
```
  routeRules: {
    '/.well-known/apple-app-site-association': { headers: { 'content-type': 'application/json' } },
  }
```

### Describe the bug

Trying to set the mime-type of a static file in the public directory via routeRules fails. It seems routeRules cannot be applied to existing files in the public directory.

I tried different variants of identifying the route (i.e.` '/.well-known/**'`) and different routeRules (i.e. redirect) but nothing seems to work for existing files in the `public/.well-known` directory. For nonexistent files the route  '/.well-known/**' works with a redirect.

**Comment by danielroe** [comment]
This should be resolved in rc13. which you can get with `yarn upgrade nuxt` or `npm upgrade nuxt`.

Let me know if not and I'll reopen.
