### ISSUE TITLE
KeepAlive doesn't work on pages

### ISSUE THREAD

**Issue by mitow7821** [nuxt/framework#8460]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-8d2nyn?file=app.vue,pages%2Findex.vue,pages%2Ftest.vue
- Click toggle value should change to true 
- Change route to home then go back to test 

### Describe the bug

Despite of `definePageMeta({
  keepalive: true,
});` test route state isn't cached

**Comment by danielroe** [comment]
See https://github.com/nuxt/framework/issues/8367#issuecomment-1286628219. You would not want to set it on just one page or it will not keep the page alive when transitioning to another page that does not have it set. You need to set the config across all pages where keepalive is meant to work, or set it directly via `<NuxtPage :keepalive="{}" />`.

There is an outstanding issue with include/exclude: https://github.com/nuxt/framework/issues/8367#issuecomment-1286628219.

**Comment by danielroe** [comment]
Absolutely! A PR would be welcome.

**Comment by mitow7821** [comment]
@danielroe https://github.com/nuxt/framework/pull/8491

**Comment by danielroe** [comment]
Thanks! ❤️
