### ISSUE TITLE
Issue using programmatic addition of Nitro Plugins on a windows machine 

### ISSUE THREAD

**Issue by twuncher** [nuxt/framework#8461]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.10.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `build`, `runtimeConfig`, `modules`, `router`, `auth`
- Runtime Modules: `@pinia/nuxt@0.4.3`   
- Build Modules:    `-`
------------------------------

### Reproduction

On a windows machine when attempting to add a nitro plugin programmatically 

e.g. nitro.plugins.push(pathToNitroPlugin);

### Describe the bug

If you use an absolute path format e.g. 'c:/linktopath' it will complain in the '.nuxi/dev/index.mjs' that the plugin is not in windows file format. e.g. 'file://c:/linktopath'

If you put the path as 'file://c:/linktopath' it will turn the link in '.nuxi/dev/index.mjs'   into '../../../../../server/file:/C:/linktopath' (basically a relative path to the server folder).

The issue is caused by the pathe module not handling the file:// prefix and is treating it like a non absolute path.

The regex to check for absolute

const _IS_ABSOLUTE_RE = /^[\\/](?![\\/])|^[\\/]{2}(?!\.)|^[a-zA-Z]:[\\/]/; ``

does not check for a file path

**Comment by danielroe** [comment]
I believe this is now fixed with the latest release of `ufo@1.0.1` via https://github.com/unjs/ufo/pull/106. 

Would you try regenerating your lockfile or running `npx nuxi upgrade` or `npm up ufo` or equivalent?

If you can still reproduce and your lockfile only contains ufo 1.0.1, please let me know with a new reproduction and I'll reopen.

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.
