### ISSUE TITLE
Route.params not accessible pertaining to use of router-view / nuxtpage component

### ISSUE THREAD

**Issue by GithubMitch** [nuxt/framework#8468]
### Environment

Nuxi 3.0.0-rc.12                                                                                               15:06:13
RootDir: /Users/mse/Projects/router-test                                                                  15:06:13
Nuxt project info: (copied to clipboard)                                                                       15:06:13

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                               15:06:13

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

https://github.com/GithubMitch/router-test.git

### Describe the bug

Nuxt 3 starter in sandbox does not start up so i just made public repo wich u can clone :
https://github.com/GithubMitch/router-test.git

When using router-view in my app.vue to render pages  :
Initial page loads cant access route.params they are undefined.
So Nuxt starts my project and i navigate to a dynamic url >  /type-[type].
On the index page of type-[type] i can't acces route.params, im using useRoute() for this.
The weird thing is when i use $route.params in html it does represents the current type params correctly.
I reproduced the issue with some basic steps in it.

Solution: 
As you can see route.params are not set when using router-view unless you navigate and re-render the same component?

Swapping out <router-view> for <NuxtPage/> component solved the issue, but i don't know why ?
I've seen dozen implementations of router-view that give more depth than nuxtv3 docs on this particular subject.

Nonetheless, 

Way to go Nuxt Team keep up the good work, im enjoying nuxt alot !

best regards, 

Mitch

**Comment by danielroe** [comment]
It is important that you use `<NuxtPage>` rather than `<RouterView>` in nuxt. Among other things, we inject different routes in the two different forks of `<Suspense>` so that there isn't a flicker when changing routes. (To ensure this stays up-to-date, we call a hook in `<NuxtPage>` that updates it.)

If you want to use `<RouterView>` you should explicitly import `useRoute` from `vue-router`.

**Comment by GithubMitch** [comment]
Quick and proper reply Daniel !
Thank alot !
