### ISSUE TITLE
Nuxt Bridge breaks imported dependencies

### ISSUE THREAD

**Issue by DerYeger** [nuxt/framework#848]
###  Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.5.0`
- Nuxt Version:     `2.16.0-27226092.034b9901`
- Package Manager:  `Yarn`
- Bundler:          `Webpack`
- User Config:      `target`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`, `env`, `colorMode`, `fontLoader`, `i18n`, `loading`, `pwa`, `sitemap`
- Runtime Modules:  `@nuxtjs/i18n@7.0.3`, `@nuxtjs/pwa@3.3.5`, `@nuxtjs/sitemap@2.4.0`
- Build Modules:    `@nuxtjs/stylelint-module@4.0.0`, `@nuxtjs/color-mode@2.1.1`, `nuxt-font-loader@1.1.3`, `@nuxt/bridge@3.0.0-27234211.2a0afbd`

### Describe the bug and expected behavior

I upgraded to Nuxt Bridge following the instructions found [here](https://v3.nuxtjs.org/getting-started/bridge/).
While `nuxt dev` starts just fine, the entire project breaks whenever a package is imported.

For an example, check the `feat/nuxt-bridge` branch of [this](https://github.com/DerYeger/noted/tree/feat/nuxt-bridge) repository.
After upgrading, the following error is thrown.
```
marked.ts?b24f:32 Uncaught TypeError: marked__WEBPACK_IMPORTED_MODULE_5__.setOptions is not a function
    at eval (marked.ts?b24f:32)
    at Module../plugins/marked.ts (app.js:3029)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (index.js:65)
    at Module../.nuxt/index.js (app.js:201)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at Module.eval (client.js:48)
    at eval (client.js:1298)
```
This error does not occur without Nuxt Bridge.
It also results in similar errors for other dependencies.
Removing the affected package (Prism) does not help.

It also breaks during `nuxt generate` (see `Build` job [here](https://github.com/DerYeger/noted/runs/3873128117?check_suite_focus=true)).

### Steps to reproduce

1. Install Nuxt Bridge.
2. Import any dependency.

**Comment by danielroe** [comment]
This is likely related to https://v3.nuxtjs.org/concepts/esm and is a consequence of using native ES modules. Feel free to raise a new issue with reproduction if you think it's not related to ESM.
