### ISSUE TITLE
compression not work with some pages

### ISSUE THREAD

**Issue by RezaErfani67** [nuxt/framework#8484]
### Environment

nuxt 3 rc-12
node 18

### Reproduction

https://doctorjs.ir/course/jwt-course

### Describe the bug

after adding this code to nuxt.config, i have compression on some pages but not all...

```
 nitro: {
    compressPublicAssets: true,
    prerender: {
      crawlLinks: true
    }
  },
```

it is ok on the root site: for example here:
https://doctorjs.ir/
or here:
https://doctorjs.ir/course/group/frontend

but it doesnt work on some pages like this:
https://doctorjs.ir/course/jwt-course

all pages are in src/pages...
![Uploading image.png…]()

**Comment by danielroe** [comment]
I'm closing this as I can't access any of the links. If you are able to provide a minimal [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction), I'd be very happy to reopen.
