### ISSUE TITLE
useAsyncData with comma breaks

### ISSUE THREAD

**Issue by Tragio** [nuxt/framework#8499]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.19.1`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `telemetry`, `ssr`, `app`, `modules`, `formkit`, `purgeCSS`, `pwa`, `css`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.4.3`, `@kevinmarrec/nuxt-pwa@0.9.1`, `nuxt-font-metrics@0.2.1`, `nuxt-purgecss@2.0.0`, `@nuxtjs/html-validator@1.1.0`, `@vueuse/nuxt@9.3.1`, `@formkit/nuxt@1.0.0-beta.11`
- Build Modules:    `-`

### Reproduction

Not working:
```js
const data = await useAsyncData(() =>
  $fetch('https://api.nuxtjs.dev/mountains'),
)
```

Working:
```js
const data = await useAsyncData(() =>
  $fetch('https://api.nuxtjs.dev/mountains')
)
```

### Describe the bug

If I have a `,` at the end of the `$fetch` it does not work, if I remove, it works.

If I have the `,` I have this on the console `Uncaught SyntaxError: Unexpected token ',' (at edit.vue?macro=true:14:1)`

![CleanShot_2022-10-26_at_14 02 30](https://user-images.githubusercontent.com/5109593/198033645-56693139-e1e4-4324-aaa5-b6b40d6359cf.jpg)

**Comment by antlionguard** [comment]
that's not an issue. you should not use extra comma if you don't pass extra params into function.

**Comment by manniL** [comment]
> that's not an issue. you should not use extra comma if you don't pass extra params into function.

Actually it is because trailing commas, even for function parameters, are valid. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#function_calls

**Comment by antlionguard** [comment]
> > that's not an issue. you should not use extra comma if you don't pass extra params into function.
> 
> Actually it is because trailing commas, even for function parameters, are valid. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#function_calls

that's not a same thing. the trailing comma that you used is return value of arrow function. see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions 

```js
() => $fetch('something')
```

**Comment by manniL** [comment]
Anyway, I cannot reproduce the issue with the latest version, see [my StackBlitz](https://stackblitz.com/edit/https-github-comnuxtframeworkissues8499?file=app.vue,.vscode%2Fsettings.json)
