### ISSUE TITLE
Dev server frequently freezes when using NX and Prisma

### ISSUE THREAD

**Issue by joshmossas** [nuxt/framework#8514]
### Environment

Nuxt project info: 
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `srcDir`, `css`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/joshmossas/nuxt-api-freezing-minimal-reproduction

### Describe the bug

When saving changes in `server/api` the nuxt server will frequently start to freeze / hang. Specifically this seems to be happening in a monorepo setting (we use NX) when `@prisma/client` has been imported into the `server/api` directory.

I have some video examples below:
- [Example with Prisma (Server Freezes)](https://drive.google.com/open?id=1IJQ76O6WeANHa6QSkdL8nQKjOc6l3AfX&authuser=josh%40sogmi.org&usp=drive_fs)
- [Example without Prisma (Server Doesn't Freeze)](https://drive.google.com/open?id=1IHWRx3aSBNZVOtK6eCUsUP5XHFvdZgAM&authuser=josh%40sogmi.org&usp=drive_fs)

### Additional context

The way that we've been dealing with this is basically the following:
- Change is made to `server/api` directory and nuxt starts hanging
- Stop nuxt dev server
- Run nuxt clean
- Restart nuxt dev server

(not exactly an ideal situation)

For my minimal reproduction I basically created a small nx project with nuxt and started adding and removing things until I could reproduce. The error started showing up again when I introduced prisma to the `server/api` directory. It could be the case that other large dependencies could also lead to this bug. (For example we are also using `firebase-admin`) 

I did try reproducing without using NX but could not. So my theory is it's a combination of the node_modules being in the root directory (which is how NX works) + a large dependency being imported into `server/api`

**Comment by joshmossas** [comment]
Upon further investigation this issue seems to be related to the following issues:
- https://github.com/unjs/nitro/issues/257
- https://github.com/unjs/nitro/issues/376

The mentioned workaround of using WSL seems to be working for me as well.

**Comment by danielroe** [comment]
Closing to track in https://github.com/nuxt/framework/issues/4696.
