### ISSUE TITLE
useAsyncData doesn't block navigation with lazy: false

### ISSUE THREAD

**Issue by Kapcash** [nuxt/framework#8515]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `keepAlive`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

Also reproduced with nuxt@3.0.0-rc.8.

### Reproduction

https://stackblitz.com/edit/github-u1c32p?file=pages/async.vue

The `async` page uses `useAsyncData` composable with a timeout of 3s to force a delay.
Try to navigate from home page (`/`) to async page (`/async`).

### Describe the bug

The composable `useAsyncData` doesn't block **client side navigation** while resolving the Promise. So it renders the page with `data` to `null`, even though the option `lazy: false` has been used.

That means the `lazy` options doesn't change the composable behaviour whatever its value is.

This is expected on server rendering, but not on client side navigation.

**Comment by manniL** [comment]
You have to `await` the call ☺️

**Comment by Kapcash** [comment]
I should stop coding & opening issues late... 🤦‍♂️
Thanks @manniL !

**Comment by manniL** [comment]
> I should stop coding & opening issues late... 🤦‍♂️ Thanks @manniL !

I can relate a lot - happened to me too often too 😄 
No problem! ☺️
