### ISSUE TITLE
GTmetrics error Analyze

### ISSUE THREAD

**Issue by RezaErfani67** [nuxt/framework#8516]
### Environment

Nuxi 3.0.0-rc.12
node 18.4.0

### Reproduction

[Nuxi 3.0.0-rc.12](https://doctorjs.ir/course/jwt-course)

### Describe the bug

Analysis Error
The URL did not appear to be an HTML page (missing or empty Content-Type)

GTmetrix only analyzes HTML pages and could not confirm that the URL is a HTML page.

![image](https://user-images.githubusercontent.com/24381986/198196330-6d9ccc50-7a54-4b01-a7c8-801c490d8b61.png)

### Additional context

nuxt.config.js

npm run build 

```
export default defineNuxtConfig({
  nitro: {
    sourceMap:false,
    minify:true,
    compressPublicAssets: { gzip: true, brotli: true },
    prerender: {
      crawlLinks: true
    },
  },
    srcDir: 'src/',
    components: true,
    modules: [ '@pinia/nuxt'],
    css: ["@/assets/css/main.css"],
    vite:{
      build:{
        chunkSizeWarningLimit:3000
      }
    },
    build: {
      transpile: ['vue-toastification'],
        postcss: {
          postcssOptions: require("./postcss.config.js"),
        },
      },
});
```

**Comment by danielroe** [comment]
The Content-Type header is properly set, but I wonder if GTmetrics doesn't support Early Hints? You can disable them by setting `experimental.earlyHints` to false.

```
HTTP/1.1 200 OK
Content-Type: text/html;charset=UTF-8
X-Powered-By: Nuxt
Server-Timing: -;dur=0;desc="Generate"
Date: Thu, 27 Oct 2022 06:24:47 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 118627
```

**Comment by RezaErfani67** [comment]
excuseme,
how can i disable earlyHints ? (i am using nginx)

**Comment by RezaErfani67** [comment]
yeah...
its worked fine :)
