### ISSUE TITLE
Documentation on providing a plugin through a module

### ISSUE THREAD

**Issue by cco3** [nuxt/framework#8517]
### Describe the feature

There is documentation on providing a plugin through a module, but I would love to have a more complete example:
https://v3.nuxtjs.org/guide/going-further/modules#provide-nuxt-plugins

For example, there's some magic that involves the plugin existing in the runtime directory that lets you import from `#app`, but I don't totally understand what this is all about.  I've dug through a bunch of other modules and attempted to duplicate what they are doing but with no success.  Is there some additional config setting that's needed?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
You need to ensure your runtimeDir is included in `build.transpile` if you want to import from `#app` and other aliases.

**Comment by danielroe** [comment]
Any PRs are of course welcome, but I think we can track more extensive module documentation via https://github.com/nuxt/framework/issues/4104.
