### ISSUE TITLE
Use TSX component Error

### ISSUE THREAD

**Issue by IceyWu** [nuxt/framework#8518]
### Environment

- Operating System: Windows10
- Node Version: v18.0.0
- Nuxt Version: 3.0.0-rc.12
- Nitro Version: 0.6.0
- Package Manager: npm@8.19.2

### Reproduction

Use TSX component Error or page goto 500

### Describe the bug

When I am in a local development environment, use tsx components  components page display
```
500
[vite-node] [ERR_MODULE_NOT_FOUND] /__vue-jsx-ssr-register-helper
at /__vue-jsx-ssr-register-helper (imported from F:/Demo/nuxt/nuxt-blog/components/MyComponent.tsx)
```
But there are no warnings and errors after building,No problem in codesandbox either

When I comment out tsx and open it again,Console output
```
Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 

runtime-core.esm-bundler.js:4613 Hydration completed but contains mismatches.
```
- this is my tsx Component Content
```
export default defineComponent({
  props: {
    message: String
  },
  render: (props) => {
    return (
    <div>
      { props.message }
    </div>
    )
  }
})

```

**Comment by danielroe** [comment]
I believe we can track this in https://github.com/nuxt/framework/issues/2349. It's an upstream bug in vue. More info in https://github.com/nuxt/framework/issues/2349#issuecomment-1032653916.
