### ISSUE TITLE
[RC12] UnoCSS Inspector is gone

### ISSUE THREAD

**Issue by samydoesit** [nuxt/framework#8522]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `pnpm@7.14.0`
- Builder:          `vite`
- User Config:      `experimental`, `app`, `modules`, `css`, `alias`, `components`, `typescript`, `ssr`, `vite`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.4.3`
- Build Modules:    `-`

```

### Reproduction

[Reproduction on Stackblitz](https://stackblitz.com/edit/github-ncxynv-q4oa7f?file=package.json)

### Describe the bug

Hello since Nuxt rc.12 the [UnoCSS Inspector](https://github.com/unocss/unocss/tree/main/packages/inspector) is gone.

Can somebody help?

## Steps to reproduce:
Open Stackblitz wait until it fully loads
append `/__unocss` to the url.

## Expected behavior:
Unocss Inspector should show up.

When you downgrade to Nuxt rc.11 UnoCSS Inspector will be back.

**Comment by danielroe** [comment]
This should probably be tracked in unocss rather than in Nuxt. There was a breaking change in https://github.com/nuxt/framework/pull/8218 which is likely the cause of this.

Would you open an issue there instead?

cc: @antfu
