### ISSUE TITLE
Generic ERROR Reloading Server after RC12 upgrade

### ISSUE THREAD

**Issue by tiborpino** [nuxt/framework#8525]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `buildModules`, `modules`, `dev`, `build`, `css`, `app`, `schemaOrg`, `runtimeConfig`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.11`
- Build Modules:    `./modules/pages`, `nuxt-schema-org@1.1.0-beta.5`

### Reproduction

Upgraded to RC12 from RC11 via npx nuxi@latest upgrade --force command

### Describe the bug

Running yarn dev in console logs these error and browser is stacked on Reloading server... screen with loading animation

```
ERROR
undefined
```

### Additional context

Here are screenshots
[http://files.freshidea.sk/nuxt1.png](http://files.freshidea.sk/nuxt1.png)
[http://files.freshidea.sk/nuxt2.png](http://files.freshidea.sk/nuxt2.png)

**Comment by tiborpino** [comment]
I don't know how? Are there any server logs or something. As you can see there is a generic error, nothing specific I can share with you.

**Comment by danielroe** [comment]
It's difficult to say. I would start to debug this by deleting your `.nuxt` and `node_modules/.vite` folders. Then disable all modules you have enabled; there were [breaking changes](https://github.com/nuxt/framework/pull/8218) in rc12 regarding nitro/h3 and likely this is the cause of this error.

**Comment by tiborpino** [comment]
I've solved the issue. Refactor all defineEventHandler functions, getCookie helpers and stack is working properly.
