### ISSUE TITLE
injection "Symbol(route location)" not found

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#8526]
This started happening after an upgrade from [3.0.0-rc.13-27778536.1d795f0](https://www.npmjs.com/package/nuxt3/v/3.0.0-rc.13-27778536.1d795f0) to [3.0.0-rc.13-27779883.2284525](https://www.npmjs.com/package/nuxt3/v/3.0.0-rc.13-27779883.2284525). And yes, I do use pages in the project.

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.13-27779883.2284525`
- Nitro Version:    `0.6.1-27779851.28e2880`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `app`, `ssr`, `modules`, `css`, `typescript`, `alias`, `build`, `runtimeConfig`, `vue`, `vite`, `proxy`, `headlessui`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.1`, `floating-vue/nuxt`, `@pinia/nuxt@0.4.3`, `@vueuse/nuxt@9.4.0`, `unplugin-icons/nuxt`, `@formkit/nuxt@1.0.0-beta.11-c95e605`, `nuxt-proxy@0.3.0`, `@nuxtjs/critters@0.3.3`, `nuxt-icon@0.1.7`, `nuxt-headlessui@1.0.1`
- Build Modules:    `-`
------------------------------

![image](https://user-images.githubusercontent.com/48835293/198250160-00ec9bbf-198a-4ca4-8e49-cc86f75ab219.png)
![image](https://user-images.githubusercontent.com/48835293/198250344-343f9ae9-8644-4da2-ba61-5882239c2b1b.png)

_Originally posted by @DamianGlowala in https://github.com/nuxt/framework/issues/8520#issuecomment-1293263890_

**Comment by max5432112345** [comment]
> Apologies everyone for that.
For that it not work always, or what I cause troubles?
Who will report problems if i am in ban :)?

**Comment by nndnha** [comment]
I have the same issue after an upgrade from [3.0.0-rc.13-27776679.4536242](https://www.npmjs.com/package/nuxt3/v/3.0.0-rc.13-27776679.4536242) to [3.0.0-rc.13-27776685.6bcd9cd](https://www.npmjs.com/package/nuxt3/v/3.0.0-rc.13-27776685.6bcd9cd) so I think the problem comes from [this](https://github.com/nuxt/framework/commit/6bcd9cdeb191794c719eb82220aa84dcbd992d60)

**Comment by danielroe** [comment]
Yes, but the tricky bit is solving it without a reproduction.

Does adding `vue-router` to vite.optimizeDeps.include help?

**Comment by nndnha** [comment]
Yes, the error is gone.

**Comment by Maxp777** [comment]
That not really help - fix(nuxt): add vue-router to optimized deps #8544

```
[Vue warn]: inject() can only be used inside setup() or functional components.
[log error] TypeError: Cannot read properties of undefined (reading 'modules')
    at _sfc_main.setup (/home/michael/Projects/nuxt3/src/node_modules/nuxt/dist/app/components/nuxt-root.vue:67:16)
```

And is not hammer minor-bug, data from api is not displayed

**Comment by danielroe** [comment]
@Maxp777 From the error message, you may have multiple versions of Vue or vue-router, in your project.

**Comment by Maxp777** [comment]
> @Maxp777 From the error message, you may have multiple versions of Vue or vue-router, in your project.

may be that is when csurf return 403, because nuxtjs-alt-http return on first call request.method = 'get' and on toher calls 'GET'

**Comment by Maxp777** [comment]
> @Maxp777 From the error message, you may have multiple versions of Vue or vue-router, in your project.

I don't know what i have, but it work in one dir and not work in other dir (if i move the whole code with node modules)

**Comment by Maxp777** [comment]
@danielroe ad csurf+nuxtjs-alt-http cause me trouble because at the first request the verb is 'get' but need to be 'GET'. And csurf throw error 403 and nuxt throw other error like 

> onServerPrefetch is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
FetchError: 403
> [Vue warn]: inject() can only be used inside setup() or functional components.
> [log error] TypeError: Cannot read properties of undefined (reading 'modules')

**Comment by Maxp777** [comment]
@danielroe 
If csurf is patched i get
> onServerPrefetch is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

**Comment by danielroe** [comment]
Please do open a new issue with a reproduction and some instructions. I don't think it's the same one as this.

You may find that deleting your .nuxt folder helps. Do you have any node_modules folders in a parent directory? Previously we had an issue in a sub dependency where they were wrongly being detected as part of your workspace.

**Comment by Maxp777** [comment]
@danielroe the error is different if project is located in `/home/user/Projects/nuxt3/src/` or `/home/michael/Downloads/src`

**Comment by danielroe** [comment]
Okay, I'm pretty sure it's the same issue as https://github.com/nuxt/framework/issues/7609. Let's continue our conversation there.

**Comment by Maxp777** [comment]
@danielroe and that also is the same

> 2089 vue-router.mjs:35 [Vue Router warn]: No match found for location with path "/login"

all other routes are ok

**Comment by Maxp777** [comment]
don't know about what you talk because that not help
```
  vite: {
    devBundler: 'legacy',
    optimizeDeps: {
      include: 'vue-router'
    }
  }
```

**Comment by SebbeJohansson** [comment]
I am pretty sure i just encountered this error, but I'm not sure if its because of something weird I'm doing.

From what I can tell it has to do with me using app.vue and a custom layout that is set based on a fetch.
![image](https://user-images.githubusercontent.com/5083273/199068488-b45d628c-2fe6-4125-b7d3-9cac9a2defbb.png)

Reproduction: https://stackblitz.com/edit/github-ryjngg?file=nuxt.config.ts,config%2Fi18n.config.ts

Let me know if its not related to this.
