### ISSUE TITLE
https with custom domain and -o flag fails to open custom domain

### ISSUE THREAD

**Issue by chrisnoden** [nuxt/framework#8532]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `build`, `buildModules`, `css`, `googleFonts`, `hooks`, `modules`, `nitro`, `runtimeConfig`
- Runtime Modules:  `@storyblok/nuxt@4.4.2`, `@pinia/nuxt@0.4.3`
- Build Modules:    `@nuxtjs/tailwindcss@5.3.5`, `@nuxtjs/google-fonts@1.3.0`

### Reproduction

`yarn nuxi dev playground --host nuxt.fbi.com --https -o`

The browser opens to localhost and not the provided host.

Introduced in #7680

### Describe the bug

Using a custom host with hmr and the `-o` flag to open in browser does not open the custom host URL.

### Additional context

[#7680](https://github.com/nuxt/framework/pull/7680)

**Comment by danielroe** [comment]
This was resolved upstream in https://github.com/unjs/listhen/pull/40 and at last will be fixed in the edge channel when https://github.com/nuxt/framework/pull/8616 merges.

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/framework/pull/8616
