### ISSUE TITLE
`definePageMeta()` warning when defined inside `defineComponent()`

### ISSUE THREAD

**Issue by illumws** [nuxt/framework#8533]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `target`, `modules`, `build`, `css`, `googleFonts`
- Runtime Modules:  `@nuxtjs/google-fonts@3.0.0-1`, `@pinia/nuxt@0.4.3`
- Build Modules:    `-`

### Reproduction

_~/pages/index.tsx_
```
export default defineComponent(() => {
    definePageMeta({
        middleware: 'auth',
    });

    return () => <h1>hello</h1>;
});
```

_~/middleware/auth.ts_
```
export default defineNuxtRouteMiddleware((to, from) => {
    console.log('hello from middleware');
});
```

### Describe the bug

when i define the `definePageMeta` on inside of `defineComponent` as function or options i get a log error on browser console

_browser console_
![image](https://user-images.githubusercontent.com/40471268/198308040-90144971-c537-4617-a8a3-3f37b9845e59.png)

apparently the error is only in the console does not reflect in the code.

### Additional context

the error is only in the browser console, it does not return any error when run `yarn dev`

**Comment by Maxp777** [comment]
definePageMeta cause troubles but not only warnings

 definePageMeta({
   auth: 'guest',
   middleware: ['auth']
 })
