### ISSUE TITLE
Tailwind CSS module error

### ISSUE THREAD

**Issue by nndnha** [nuxt/framework#8546]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13-27781123.265db50`
- Nitro Version:    `0.6.1-27781459.72c912e`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.1`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-846kga?file=package.json

### Describe the bug

Unable to start the dev server after an upgrade from [3.0.0-rc.13-27779883.2284525](https://www.npmjs.com/package/nuxt3/v/3.0.0-rc.13-27779883.2284525) to [3.0.0-rc.13-27781123.265db50](https://www.npmjs.com/package/nuxt3/v/3.0.0-rc.13-27781123.265db50)

**Comment by DamianGlowala** [comment]
See https://github.com/nuxt-modules/tailwindcss/pull/553.

**Comment by danielroe** [comment]
Let's track there. This is an intentional breaking change in https://github.com/nuxt/framework/pull/8487.
