### ISSUE TITLE
inline middleware is not called with global middleware

### ISSUE THREAD

**Issue by peterkimzz** [nuxt/framework#8548]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `tailwindcss`, `build`, `sitemap`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.0.1`, `@nuxt/content@2.2.0`, `~/modules/sitemap`
- Build Modules:    `-`

### Reproduction

Here is my folder structure,

```
my-nuxt3-project/
|-- middleware/
|---- me.global.ts
|---- loginRequired.ts
|-- pages/
|---- profile/
|------ index.vue
```

And here is my page that is needed to be logged in.

```vue
<script setup lang="ts">
definePageMeta({
  middleware: ["login-required"],
});
</script>
```

### Describe the bug

The inline-middleware is not called when I use inline-middleware and global middleware on a single page.

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by peterkimzz** [comment]
Thanks @manniL ,

I've created the reproduction project for https://stackblitz.com/edit/github-6svt1g?file=app.vue,pages%2Findex.vue,middleware%2F1.first.global.ts

But, I've found the reason why all of the middlewares are not called. Because I early return `true` in middleware (you can see the actual code in the `1.me.global.ts` file in my stackblitz that finishes the entire middleware flows.

So is there any solution I can call the `next()` function in Express.js?

**Comment by manniL** [comment]
As denoted in [the docs](https://v3.nuxtjs.org/guide/directory-structure/middleware#middleware-directory), returning nothing is similar to "`next()`" in other middleware scenarios. If you want to abort the navigation, please use `abortNavigation(error)` ☺️
