### ISSUE TITLE
Can't build the app with preset cloudflare and using pnpm without option shamefully-hoist

### ISSUE THREAD

**Issue by hlassiege** [nuxt/framework#8550]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `pnpm@7.13.2`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://gitlab.com/maltcommunity/public/singapore-prototypes/-/tree/master/issue-cloudflare

### Describe the bug

I have an SSR application I want to deploy on Cloudflare.
For this app, I'm using pnpm **without the option --shamefull-hoist**. It worked until then as we add the dependency manually.

When we build the app (with preset : cloudflare), 
it fails with the following error : 

 ERROR  Cannot resolve "source-map-support/register.js" from "\u0000virtual:#internal/nitro/virtual/polyfill" and externals are not allowed!      

![image](https://user-images.githubusercontent.com/666123/198586602-59e34538-19ac-44df-b9af-dfb38a156269.png)

I suppose I have a missing dependency but I don't figure it what dependencies are missing?

**Comment by manniL** [comment]
PNPM without `shamefully-hoist` is not supported yet. Please follow #5411 along ☺️
