### ISSUE TITLE
After updating to RC12 I get a Vue Router warning

### ISSUE THREAD

**Issue by stefanfrede** [nuxt/framework#8555]
👋,

After updating from `RC11` to `RC12` I get a lot of warnings:
```
[Vue Router warn]: No match found for location with path "/"
```
Wnen I open the page I get a 404.

Did I miss something?

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by stefanfrede** [comment]
It took me a bit but here it is: https://codesandbox.io/s/nuxt3-starter-template-c103vw

[![CodeSandbox](https://i.postimg.cc/kgSKYx1w/Screenshot-from-2022-10-29-14-58-52.png)](https://postimg.cc/v4Q4c6d6)

**Comment by stefanfrede** [comment]
@danielroe I did some more testing.

I reliably get the mentioned error locally and on [CodeSandbox](https://codesandbox.io/s/nuxt3-starter-template-c103vw) with `3.0.0-rc.12` and above.

When I downgrade to `3.0.0-rc.11` the error is gone.

I can't reproduce the error on [Stackblitz](https://stackblitz.com/edit/node-odrtnf), there it is working fine.

**Comment by stefanfrede** [comment]
I got an :bulb:  and found the cause for the error.

In the `app` folder I have a `router.options.ts` with the following content:
```
import type { RouterConfig } from '@nuxt/schema';

// https://router.vuejs.org/api/#routeroptions
export default <RouterConfig>{
  scrollBehavior(to) {
    return new Promise((resolve) => {
      setTimeout(() => {
        if (to.hash) {
          resolve({
            el: to.hash,
            behavior: 'smooth',
          });
        } else {
          resolve({
            top: 0,
            behavior: 'smooth',
          });
        }
      }, 100);
    });
  },
};
```
If I remove the `app` folder the error is gone.
