### ISSUE TITLE
404 page is broken on Windows

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/framework#8557]
Hello I am experiencing an issue with 404 page. The content is not displayed on the screen when I am on a windows machine.

On Mac OS (I tested Edge, Chrome, Firefox and Safari):
![Mac](https://user-images.githubusercontent.com/85166574/198705759-736255f6-2e4b-4eaa-836d-849d3b4166e6.png)

On Windows (I tested Edge and Chrome):
![Capture](https://user-images.githubusercontent.com/85166574/198705909-3e56bce4-3d9c-4025-8967-5da8436edb72.PNG)

Reproduction :
My [repository](https://github.com/BenjaminOddou/portfolio)
The [link](https://www.benjaminoddou-photographe.com/de) to the 404 page of my site

EDIT : I am using nuxt3.0.0-rc.12

**Comment by danielroe** [comment]
This looks like a CSS issue and I doubt it's caused by Nuxt.

Rather, you seem to be using 100svh which does not work in Edge. I had to manually set a couple of elements to 100vh to get them to display.
