### ISSUE TITLE
Why `router.options.ts` should be placed inside `./app` folder?

### ISSUE THREAD

**Issue by pavloniym** [nuxt/framework#8560]
### Describe the feature

Good evening!
It is great that Nuxt can resolve routing automatically, but sometimes you need full-control on routing.
In docs I found a way to create manual router config (thanks!), but ... why it is in `app` folder? I mean — your have `app.vue` in root, `app.config.ts` in root, `nuxt.config.ts` in root ... That is the main idea to keep `router.options.ts` inside `app` folder?

Maybe it will be better and more consistent  to make it `router.config.ts` and keep it in root folder, near `app.config.ts` and other?

Thank you!

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by manniL** [comment]
The `app` folder is used to replace "internal" files that are present by default through Nuxt (same was the case in Nuxt 2).
They replace a specific "internal" part of Nuxt.

The two config files, `app.config.ts` and `nuxt.config.ts` are defining configs for the whole app, `app.vue` and  `error.vue` can be seen as entrypoints for each request going through the app.

In this case, the separation makes sense to also avoid cluttering of the project root.

**Comment by pavloniym** [comment]
But `router.options.ts` is also config for the whole app ... imho, Nuxt is frontend framework first of all, and should be convenient for frontend development. `server` part of Nuxt should be for advanced usage (and everything about server is placed inside `server` folder, as I can see in docs).
I don't like auto-resolving of my routes, and there should be way to create routing explicitly (by `router.options.ts`), but why it should be placed inside `app`?
Using this logic all other directories (connected with frontend part) should be placed inside `app`, and final structure should be `app` (frontend), `server` (server), `nuxt.config.ts` and `app.config.ts`...
I do not understand ...
