### ISSUE TITLE
setPageLayout causes hydration mode mismatch and nuxt warning

### ISSUE THREAD

**Issue by chrisnoden** [nuxt/framework#8561]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

see https://github.com/chrisnoden/nuxt3-bug

Create a couple of layouts, choose one of them using the code example from https://v3.nuxtjs.org/guide/directory-structure/layouts#changing-the-layout-dynamically 

eg:
```
definePageMeta({
    layout: false,
});
setPageLayout('minimal');
```

### Describe the bug

You get 2 warnings that do appear to be definitely unwanted.

1. a Vue warn about `Hydration mode mismatch` implying the SSR render differs from the browser render.
2. a nuxt warn that your chosen layout "does not have a single root node..." when it does.

This bug does not appear if you are able to use one of the other methods to change layout.

### Additional context

The chosen layout DOES get used, but the warnings are reasonably concerning

**Comment by Maxp777** [comment]
definePageMeta({
   auth: 'guest',
   middleware: ['auth']
})


definePageMeta cause troubles also

**Comment by manniL** [comment]
Hey 👋🏻
This is [a documented limitation](https://v3.nuxtjs.org/api/utils/set-layout/).

> If you choose to set the layout dynamically on the server side, you must do so before the layout is rendered by Vue (that is, within a plugin or route middleware) to avoid a hydration mismatch.

**Comment by chrisnoden** [comment]
> Hey 👋🏻 This is [a documented limitation](https://v3.nuxtjs.org/api/utils/set-layout/).
> 
> > If you choose to set the layout dynamically on the server side, you must do so before the layout is rendered by Vue (that is, within a plugin or route middleware) to avoid a hydration mismatch.

Thanks @manniL but in my example nothing should be rendered because no content has yet been defined - only structural (nuxt). With this limitation I would have to define the layout in `app.vue` yet I have no control of what appears within the <NuxtLayout> or <NuxtPage> because this is down to nuxt at this early stage.

**Comment by manniL** [comment]
@chrisnoden For using `setPageLayout` yes. You can also look into other options, e.g. using the `NuxtLayout` component directly

```vue
<template>
  <NuxtLayout :name="layout">
    <NuxtPage />
  </NuxtLayout>
</template>

<script setup>
const layout = "custom"; // Or from some API call
</script>
```

**Comment by chrisnoden** [comment]
@manniL Ok, thanks.

For my use case I'll look at a global middleware. I'm trying to avoid having expensive API response based logic in 2 places. Since I need to fetch API response in the main page component I wanted to make the decision about layout there.
