### ISSUE TITLE
Error on production build within any css included on the application that isn't inside a .vue sfc

### ISSUE THREAD

**Issue by igortrinidad** [nuxt/framework#8572]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.17.1`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.5.4`
- Builder:          `vite`
- User Config:      `modules`, `tailwindcss`, `runtimeConfig`, `build`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.4`, `@pinia/nuxt@0.4.2`
- Build Modules:    `-`

### Reproduction

Create a project using rc-10 (the rc-12 are giving an error that i didn't found a solution yet to update to the latest... https://github.com/nuxt/framework/discussions/8296#discussioncomment-3959331)

Add .css files on the project the project, not in .vue sfc, see my example below.

`npm run build`

Check the builded (event locally) `node ./output/server/index.mjs`

````
<template>

  <Html lang="pt-br">
    <Body id="body" class="w-screen h-screen font-sans bg-slate-100 text-zinc-700 overflow-x-hidden scrolling-touch relative">

      <NuxtLayout>
        <NuxtPage/>
      </NuxtLayout>

    </Body>
  </Html>
</template>

<script setup>
  import '@/assets/css/main.scss'
 
</script>

</style>


````

````

@import url('https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined');
@import url('https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp');
@import url('https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&display=swap');
@import './text.scss';
@import './scrollbar.scss';
@import './transitions.css';
@import './breakdowns.scss';
@import './menu-toggle.css';
@import './table.scss';
@import './colors.scss';
@import 'pell/dist/pell.css';


@tailwind base;
@tailwind components;
@tailwind utilities;


````

### Describe the bug

My application uses Tailwind and the build is removing / ignoring any css of the page that isn't inside a .vue sfc, inclusing Tailwind @apply helpers,Google Fonts and icons, see in the attachment...

I don't know how to inspect it better, the build didn't output any error at all but the css isn't included in the source of the page on the production build, i tested locally and this is happening on the production env (Vercel) too...

![2022-10-29 21_19_52-Cálculo e Previdência](https://user-images.githubusercontent.com/13478652/198857343-c654b2d1-4a6b-41f2-9db0-4b9328017696.png)

**Comment by Atinux** [comment]
Can you confirm with RC13 please?

**Comment by igortrinidad** [comment]
@Atinux thanks for the reply, it works in one project (my portfolio) but it breaks the pageTransition on this project.

Do you know if the api or specs to use pageTransition changed on this version? I took a look on the release of the version and the docs of pageTransition and didn't found anything new about that...

I'm using the pageTransition like this:

````
// app.vue
<script setup>

definePageMeta({
    pageTransition: {
      mode: 'out-in'
    }
  })

</script>

<style lang="scss">
  .page-enter-from, .layout-enter-from {
    opacity: 0;
  }

  .page-enter-active,
  .page-leave-active,
  .layout-enter-active, 
  .layout-leave-active {
    transition: all 0.3s;
  }
  .page-enter,
  .page-leave-to,
  .layout-enter, 
  .layout-leave-active {
    opacity: 0;
    transform: translateX(-100px);
  }

</style>
````

Check it out the application after updating to rc-13 (and other dependencies that was need to update too like @nuxt/kit and @nuxt/tailwindcss)

[https://pp-frontend-dxpb0vd86-previdenciario.vercel.app](https://pp-frontend-dxpb0vd86-previdenciario.vercel.app/)

**Comment by Atinux** [comment]
Actually the page transitions are disabled by default now with the RC13 to minimize the bundle size.

You can activate them back in your `nuxt.config`: https://v3.nuxtjs.org/getting-started/transitions#page-transitions

**Comment by igortrinidad** [comment]
@Atinux thanks a lot bro, It works perfectly now! Have a great week!
