### ISSUE TITLE
about nginx proxy

### ISSUE THREAD

**Issue by kuangke9527** [nuxt/framework#8575]
### Environment

nginx:v1.17.8
nuxt:v3.0.0-rc.12

### Reproduction

nothing

### Describe the bug

use `npx nuxi init nuxt-app` create project. next no change.

Running development mode nginx proxy everything works fine

but. Running compiled version. nginx proxy will be slow。

Wait for the response for 5s as shown in the figure
![image](https://user-images.githubusercontent.com/31085204/198870060-af233f0e-f438-471e-8c95-61d207557f64.png)

### Additional context

```

map $sent_http_content_type $expires {
    "text/html"                 epoch;
    "text/html; charset=utf-8"  epoch;
    default                     off;
}

server {
    listen          80;             # the port nginx is listening on
    server_name    www.local.com;    # setup your domain here

    gzip            on;
    gzip_types      text/plain application/xml text/css application/javascript;
    gzip_min_length 1000;
client_max_body_size 300M;
    location / {
       try_files $uri @backend;
    }
    location @backend {
        proxy_pass  http://172.17.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_redirect                      off;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_read_timeout          1m;
        proxy_connect_timeout       1m;
    }
    error_log  /www/wwwlogs/www.local.com.error.log;
}
```

### Logs

```shell
nothing
```

**Comment by sewalsh** [comment]
I'm thinking the new Early Hints feature is causing this for you.

Try https://github.com/nuxt/framework/issues/8503#issuecomment-1292092951

**Comment by danielroe** [comment]
As @sewalsh says. Note that this fix is already in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.
