### ISSUE TITLE
ERROR  Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by darthf1** [nuxt/framework#8578]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `pnpm@7.14.0`
- Builder:          `vite`
- User Config:      `telemetry`, `imports`, `head`, `css`, `plugins`, `components`, `modules`, `router`, `googleFonts`, `htmlEditor`, `i18n`, `typescript`, `hooks`, `vite`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.1`, `@nuxt/image-edge@1.0.0-27768165.4b0219a`, `@nuxtjs/google-fonts@3.0.0-0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-4aztu6?file=nuxt.config.ts

### Describe the bug

I am trying to push an entry to nitro's config moduleSideEffects. Although there is no typescript error, I get a build error `moduleSideEffects` is undefined.

![image](https://user-images.githubusercontent.com/17253332/198881458-f77edd77-350d-4f09-bd16-32553932e1e3.png)

![image](https://user-images.githubusercontent.com/17253332/198881476-96a3e096-1423-4372-a19b-a03fb58e4ff8.png)

**Comment by danielroe** [comment]
```diff
+ config.moduleSideEffects = config.moduleSideEffects || []
  config.moduleSideEffects.push('@abraham/reflection')
```

Note that moduleSideEffects _is_ typed correctly as possibly being undefined:

<img width="434" alt="CleanShot 2022-10-30 at 14 55 59@2x" src="https://user-images.githubusercontent.com/28706372/198885457-ef5b80f2-3cf0-41c7-a6d0-e16e83bf8445.png">

Although in this case you can just set the config:

```js
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  nitro: {
    moduleSideEffects: ['@abraham/reflection']
  }
});
```
