### ISSUE TITLE
Cant acess public folder from server

### ISSUE THREAD

**Issue by gregg-cbs** [nuxt/framework#8589]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

If you need one let me know

### Describe the bug

I am trying to query a json file from the public folder (or any folder) using useFetch in the setup hook.
I keep getting 404 page not found.

paths I have tried:
`/public/data/some-file.json`
`/data/some-file.json`

error i get:
`404 Page not found: /data/reinsurance-landing.json`

example of my code:
```
<script>
export default {
  async setup() {
    const {path} = useRoute()

    const dataUrl = `/data${path}.json`; // /data/some-json-file.json

    const { data, pending, error, refresh } = await useFetch(dataUrl)

    console.log(data, pending, error);
    return {data}
  }
}
</script>
```

**Comment by ennioVisco** [comment]
Did you also try `~/some-file.json`?

**Comment by gregg-cbs** [comment]
Yup, get:
`FetchError: Invalid URL ()`

**Comment by manniL** [comment]
See [this stackblitz](https://stackblitz.com/edit/https-github-comnuxtframeworkissues8589). Should work fine via `public` folder and `useFetch` for example.

If you need to read files on the server-side, check out as @sewalsh said (and also https://github.com/manniL/nuxt3-nitro-unstorage-api-routes-example)
