### ISSUE TITLE
How to dynamically import components?

### ISSUE THREAD

**Issue by gregg-cbs** [nuxt/framework#8590]
### Describe the feature

In nuxt 3 you can reference any component in the component folder without having to import it. This feature is called auto import.

However this nifty dynamic feature does not work with `<component :is="someComponent" />`. I would expect the example in this discussion to work:
https://github.com/nuxt/framework/discussions/8095

How would one go about dynamically importing components based off some dataset?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by tylerforesthauser** [comment]
I apologize as I am away from a computer at the moment but I think you may just need to wrap the component name in "resolveComponent" before providing it as a prop.

**Comment by gregg-cbs** [comment]
Thanks, I managed to get it working like this:
```
<template>
  <div>
    <component 
      v-for="component in page.components" 
      :key="component.sectionName"
      :is="component.component"
    />
  </div>
</template>

<script setup>
import { ref, defineAsyncComponent } from 'vue';

const page = await import('~/static/data/reinsurance-landing.json')

page.components.map((component)=> {
   const {type} = component;
   component.component = defineAsyncComponent(() => import(`../components/${type}.vue`))
})
</script>
```

Thanks to source:
https://www.webmound.com/lazy-loading-and-dynamic-import-in-vue-3/

**Comment by Rigo-m** [comment]
This is already documented @gregg-cbs https://v3.nuxtjs.org/guide/directory-structure/components#dynamic-components
