### ISSUE TITLE
Nuxt3 RC-12 version, production deployment, using Nginx reverse proxy, becomes very slow

### ISSUE THREAD

**Issue by dada188** [nuxt/framework#8595]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.5.4`
- Package Manager:  `pnpm@7.14.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
- Nginx version:    `1.18.0`
------------------------------

### Reproduction

none

### Describe the bug

Developing with **RC12**, deploying to production, and using the Nginx reverse proxy, the access speed becomes extremely slow (**HTML takes about 5 seconds to respond, but static JS file access speed is normal**) , if access directly through the port, the speed is normal. After I dropped the NUXT version to **RC11**, didn't have this problem

使用rc12版本进行开发，部署到生产环境，使用Nginx反向代理，访问速度变得特别慢（html需要5秒左右才能有响应，但是静态js文件访问速度是正常的），如果直接通过端口进行访问，则速度正常。我把nuxt版本降到rc11之后，就没有这个问题。

### Additional context

none

### Logs

```shell
none
```

**Comment by dada188** [comment]
I wonder if this is a bug in NUXT3 RC12 @antfu

**Comment by zenonux** [comment]
same issue

**Comment by dada188** [comment]
> same issue

Did you encounter this problem too?
---
你也遇到这个问题了吗？

**Comment by zenonux** [comment]
> 



> > same issue
> 
> ## Did you encounter this problem too?
> 你也遇到这个问题了吗？

是啊

**Comment by sewalsh** [comment]
Try disabling Early Hints - https://github.com/nuxt/framework/issues/8503#issuecomment-1292092951

**Comment by dada188** [comment]
> Try disabling Early Hints - [#8503 (comment)](https://github.com/nuxt/framework/issues/8503#issuecomment-1292092951)



> Try disabling Early Hints - [#8503 (comment)](https://github.com/nuxt/framework/issues/8503#issuecomment-1292092951)

Thank you. That solves my problem

**Comment by dada188** [comment]
> Try disabling Early Hints - [#8503 (comment)](https://github.com/nuxt/framework/issues/8503#issuecomment-1292092951)

Thank you. That solves my problem

**Comment by dada188** [comment]
> 
@zenonux 
This can be done by adding the following configuration
[#8575](https://github.com/nuxt/framework/issues/8306)
``` 
export default defineNuxtConfig({
  ...
  experimental: {
    writeEarlyHints: false,
  },
  ...
})
```

**Comment by jilv220** [comment]
Same problem. The speed becomes normal again if I use port-forwarding instead.

**Comment by dada188** [comment]
> 

@jilv220

**Comment by dada188** [comment]
```
export default defineNuxtConfig({
  ...
  experimental: {
    writeEarlyHints: false,
  },
  ...
})
```
You can use this configuration to solve this problem because NGINX does not support a 103 status code, but this feature is enabled by default in RC12
@jilv220
