### ISSUE TITLE
pages route params error

### ISSUE THREAD

**Issue by xjccc** [nuxt/framework#8597]
### Environment

nuxt: rc-12
node: v16.18.0
pnpm: 7.14.0
apple m1 max
macos: 13.0

### Reproduction

https://stackblitz.com/edit/github-pespjr?file=pages%2Fprice_[nid]_[sid].vue,pages%2Findex.vue

### Describe the bug

route params error

### Additional context

in my mind 
price_[nid]_[sid].vue
/price_123_456 
get {nid: 123, sid: 456}

### Logs

```shell
get { "nid_": "1", "sid": "23_456" }
```

**Comment by phu-go2joy** [comment]
![image](https://user-images.githubusercontent.com/81737706/199387241-542e674d-1970-41e5-9267-e43b4f13f1d6.png)

**Comment by xjccc** [comment]
> ![image](https://user-images.githubusercontent.com/81737706/199387241-542e674d-1970-41e5-9267-e43b4f13f1d6.png)
its seo link rules for me
not this

**Comment by phu-go2joy** [comment]
Always use hyphens (-) and not underscores (_) because underscores cannot be seen when the URL is published as a bare link, ... Somewhere on google

**Comment by xjccc** [comment]
> Always use hyphens (-) and not underscores (_) because underscores cannot be seen when the URL is published as a bare link, ... Somewhere on google

how u diff this
[city-code].vue   like /beijing/ or /shanghai/
[car-type].vue    like /zixie/ or /zhongka/

routes middleware? or diff component?

**Comment by manniL** [comment]
Even if not ideal for SEO, using underscores should not affect params though
