### ISSUE TITLE
Nuxt RC12 throws error in production built code when providing mapBox library via plugin

### ISSUE THREAD

**Issue by Schetnan** [nuxt/framework#8610]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `nitro`, `runtimeConfig`, `vue`, `app`, `serverMiddleware`, `routes`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Given the following plugin - mapbox.client.js

```
import mapBox from 'mapbox-gl'

export default defineNuxtPlugin(() => {
    console.log("In mapBox plugin")
    return {

      provide: {
        mapBox: mapBox
      }
    }
  })
```

The application will work fine using the mapBox plugin or not when running with nuxt dev.  However, first building with the following npm script:

`"build": "NITRO_PRESET=node nuxt build",`

Then running with the following script, the application will fail.  

```
const { handler } = await import('./.output/server/index.mjs')

import express from 'express'
var app = express()
const port = 3100

app.use(handler)

app.listen(port, () => {
    console.log(`Example app listening on port ${port}`)
```

I have seen a couple of different errors in different apps.  In a simple hello world app, I see the following in the browser and the component that uses the map fails.

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

In one of the larger apps, the entire app fails as one of the entry.js files fails with the following:

```
Error: Parse Error: Invalid character in chunk size
    at HTTPParser.execute (<anonymous>)
    at Socket.socketOnData (node:_http_client:534:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Describe the bug

Application fails when loading production built scripts when trying to load the mapBox library via a client plugin.

### Additional context

This code worked fine in previous Nuxt release candidates.

**Comment by Schetnan** [comment]
@manniL   I have been trying to whittle down a large app to something that I could send you.  I was able to narrow down the problem to the usage of the node "compression" library.   When compression was used, INVALID CHUNK type events were being thrown and the javascript would not load correctly

However, this morning, I got the RC13 release, and my problems seem to have gone away.

**Comment by manniL** [comment]
Glad to hear that it got resolved with RC13 🙌🏻
