### ISSUE TITLE
Routing - Define custom regex for dynamic page params

### ISSUE THREAD

**Issue by manniL** [nuxt/framework#8619]
### Describe the feature

Right now, dynamic urls generated via file-based routing in `pages` use the "default" regex from vue router for their params. To change that, hooks like `pages:extend` would be necessary.

Instead of that, it would be great to provide the regex otherwise, e.g. via page meta or (maybe even file-name), if possible.

Related: #8597 

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
I think it would be good to support this via `definePageMeta`. See also https://github.com/nuxt/framework/issues/3352 for previous discussion about doing this via FS.
