### ISSUE TITLE
[Vue Router warn]: No match found for location with path "/robots.txt"

### ISSUE THREAD

**Issue by anick-xs** [nuxt/framework#8628]
### Environment

When I run nuxt there is a warning

### Reproduction

https://github.com/anick-xs/nuxt3

### Describe the bug

[Vue Router warn]: No match found for location with path "/robots.txt"
<img width="973" alt="image" src="https://user-images.githubusercontent.com/17721593/199517943-005b7f09-21eb-4245-b3a4-325190531d9b.png">

**Comment by danielroe** [comment]
You can safely ignore this warning. It would be nice to hide it (and we may do so) but it's just telling you that your browser is looking for this file but it is not present in your `public/` directory.

**Comment by VournPhorn** [comment]
how can i hide that error log in "npm run build" when page not found ?
