### ISSUE TITLE
[ERROR] Could not resolve "#build/app.config.mjs"

### ISSUE THREAD

**Issue by XiaoLi-sach** [nuxt/framework#8629]
### Environment

  "devDependencies": {
    "@types/node": "^18.11.2",
    "nuxt": "3.0.0-rc.12",
    "prettier": "^2.7.1",
    "sass": "^1.53.0",
    "vite-plugin-vue-setup-extend": "^0.4.0"
  },
  "dependencies": {
    "@nuxt/kit": "3.0.0-rc.12",
    "@pinia/nuxt": "^0.4.0",
    "@vueuse/motion": "^2.0.0-beta.23",
    "axios": "^0.27.2",
    "element-plus": "^2.2.6",
    "highlight.js": "^11.6.0",
    "mockjs": "^1.1.0",
    "unplugin-auto-import": "^0.9.1",
    "unplugin-icons": "^0.14.6",
    "unplugin-vue-components": "^0.20.1",
    "vite-plugin-mock": "^2.9.6"
  }

### Reproduction

X [ERROR] Could not resolve "#build/app.config.mjs"

~~~
    node_modules/.pnpm/nuxt@3.0.0-rc.12_sass@1.53.0/node_modules/nuxt/dist/app/config.mjs:3:24:
      3 │ import __appConfig from "#build/app.config.mjs";
        ╵                         

  The package import "#build/app.config.mjs" is not defined in this "imports" map:
    at failureErrorWithLog (F:\mine-project\pgcm\pgcm-dashboard\node_modules\.pnpm\esbuild@0.15.11\node_modules\esbuild\lib\main.js:1566:15)
    at F:\mine-project\pgcm\pgcm-dashboard\node_modules\.pnpm\esbuild@0.15.11\node_modules\esbuild\lib\main.js:1024:28
    at runOnEndCallbacks (F:\mine-project\pgcm\pgcm-dashboard\node_modules\.pnpm\esbuild@0.15.11\node_modules\esbuild\lib\main.js:1438:61)
    at buildResponseToResult (F:\mine-project\pgcm\pgcm-dashboard\node_modules\.pnpm\esbuild@0.15.11\node_modules\esbuild\lib\main.js:1022:7)
    at F:\mine-project\pgcm\pgcm-dashboard\node_modules\.pnpm\esbuild@0.15.11\node_modules\esbuild\lib\main.js:1134:14
    at responseCallbacks.<computed> (F:\mine-project\pgcm\pgcm-dashboard\node_modules\.pnpm\esbuild@0.15.11\node_modules\esbuild\lib\main.js:671:9)
    at handleIncomingPacket (F:\mine-project\pgcm\pgcm-dashboard\node_modules\.pnpm\esbuild@0.15.11\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (F:\mine-project\pgcm\pgcm-dashboard\node_modules\.pnpm\esbuild@0.15.11\node_modules\esbuild\lib\main.js:647:7)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
~~~

### Describe the bug

I run a project,  but, No content is displayed on the page, then I check the console,  An error was found: [ERROR] Could not resolve "#build/app.config.mjs";

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by XiaoLi-sach** [comment]
> Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

yes, You can check this out. https://github.com/pgcm-community/pgcm-dashboard

**Comment by manniL** [comment]
> > Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> yes, You can check this out. [pgcm-community/pgcm-dashboard](https://github.com/pgcm-community/pgcm-dashboard)

Could you please provide a *minimal* reproduction so business logic is stripped down and only the moving parts needed to reproduce the error are in the repo? That will help a lot to pin down the bug ☺️

**Comment by XiaoLi-sach** [comment]
> > > Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> > 
> > 
> > yes, You can check this out. [pgcm-community/pgcm-dashboard](https://github.com/pgcm-community/pgcm-dashboard)
> 
> Could you please provide a _minimal_ reproduction so business logic is stripped down and only the moving parts needed to reproduce the error are in the repo? That will help a lot to pin down the bug ☺️

However, I get this error when I start the project, and I don't know where it came from. I used before rc.4, there was no such mistake then.

**Comment by XiaoLi-sach** [comment]
Hi, I have solved this problem， I  Change "nuxt/app" to "#imports",  then modify tsconfig.json 
`
"paths": {
      "#imports": [
        ".nuxt/imports"
      ]
    }
`

This error is gone.
