### ISSUE TITLE
Enable TypeScript strict mode by default

### ISSUE THREAD

**Issue by P4sca1** [nuxt/framework#8631]
### Describe the feature

It is considered a best practice and a requirement when using Pinia (the de-facto standard store for Vue 3, replacing Vuex).

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Personally, I would agree with this. I think it's a better default. The only downside is that it's less permissive by default which might be confusing (but not breaking) for those not using TypeScript.

wdyt @pi0?

**Comment by P4sca1** [comment]
Since type check would still be disabled by default, I don't think there are noticeable downsides.
The big plus is that you get additional useful hints in your editor related to typing, and you can use pinia (and other packages that require strict type checking) out of the box.

**Comment by pi0** [comment]
Typescript itself is not strict out of the box as of today and is marketed as a progressive programming language. While I also (as a typescript user) personally opt for strict type checking whenever possible, I believe it is negative DX for users who want to only partially benefit from typescript features.  

If we want to advocate using `lang=ts` and `.ts` for a wider range of users, the default is more sensible that we don't force users to add `@types/` packages and **type everything** just to get rid of red highlights in IDE. 

At the time that we made `strict: false` decision, type support for Nuxt 3 was not stable (specially API route types that are now really better!) and i personally found it hard to have a starter project running without caring less about types. Types are better now and at this point, I'm not really biased. We can check with @yyx990803 too about his vision and idea for default.

In the meantime, and before v3 release, we can try enabling `strict` by default and see how is the feedback and especially with the starter users experience.
