### ISSUE TITLE
Access-Control-Allow-Origin header is always set

### ISSUE THREAD

**Issue by P4sca1** [nuxt/framework#8638]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@3.2.4`
- Builder:          `vite`
- User Config:      `ssr`, `dev`, `typescript`, `runtimeConfig`, `app`, `sourcemap`, `css`, `modules`, `content`, `colorMode`, `robots`
- Runtime Modules:  `@nuxt/content@2.2.1`, `@nuxtjs/tailwindcss@6.1.2`, `@nuxtjs/color-mode@3.1.8`, `@nuxtjs/robots@2.5.0`, `@pinia/nuxt@0.4.3`, `@vueuse/nuxt@9.4.0`, `nuxt-headlessui@1.0.1`
- Build Modules:    `-`

### Reproduction

Create a file `server/api/ping.ts`
```ts
export default defineEventHandler(() => {
	return 'Pong!'
})
```

Now visit `http://localhost:3000/api/ping` in your browser with Network Devtools open, or call it via Postman. 

### Describe the bug

Notice that the header `Access-Control-Allow-Origin: *` is set, without enabling CORS anywhere explicitly.
CORS should not be enabled automatically in my opinion, but should be opt-in instead, for security reasons.
Also, using `*` will not work, when calling the endpoint using `fetch` in the browser with `credentials: 'include'`:

>  The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

A common trick to circumvent this (if you really want to allow every origin! - again, this should not be the default) is to return the request origin instead.

### Additional context

https://github.com/nuxt/framework/issues/4009

**Comment by P4sca1** [comment]
This does not seem to come from Nitro route rules, because as fas as I know, nitro never writes only the `access-control-allow-origin` header alone, but always with other `access-control-*` headers.
Adding ```ts
routeRules: {
	'/**': { cors: false },
},
``` to my `nuxt.config.ts` does not remove the header, which proves that this does not seem to come from nitro (if route rule overwriting and the cors option work as expected).

**Comment by danielroe** [comment]
This is only reproducible in dev mode because it is set by the vite dev server. You can [change the behaviour](https://vitejs.dev/config/server-options.html#server-cors):

```js
export default defineNuxtConfig({
  vite: {
    server: {
      cors: false
    }
  }
})
```
