### ISSUE TITLE
`$fetch` is not respecting/handling `Content-Type: multipart/form-data` or `application/x-www-form-urlencoded`

### ISSUE THREAD

**Issue by ivanempire** [nuxt/framework#8643]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Requires Reddit app credentials for this, but I do have a sample app I can upload/paste into the provided sandbox if people want to give it a go with their own tokens 🚀 

Non-working example:

```typescript
let encodedAuthorization = btoa(`${REDDIT_CLIENT_ID}:${REDDIT_CLIENT_SECRET}`);
let authHeaders = {
    "Authorization": `Basic ${encodedAuthorization}`,
    "Content-Type': "application/x-www-form-urlencoded" // no combination of this or body below works
};

let response = await $fetch(REDDIT_URL_ACCESS_TOKEN, {
    method: 'POST',
    headers: authHeaders,
    body: {
        "grant_type": "authorization_code",
        "code": requestCode,
        "redirect_uri": APP_URL_CALLBACK
    }
});
```

Working example:

```typescript
let encodedAuthorization = btoa(`${REDDIT_CLIENT_ID}:${REDDIT_CLIENT_SECRET}`);
let authOptions = {
    method: "POST",
    url: REDDIT_URL_ACCESS_TOKEN,
    headers: {
        "Authorization": `Basic ${encodedAuthorization}`,
        "Content-Type": "application/x-www-form-urlencoded" // the crucial bit
    },
    data: querystring.stringify({
        "grant_type": "authorization_code",
        "code": requestCode,
        "redirect_uri": APP_URL_CALLBACK
    })
};

axios(authOptions).then(function(tokenResponse) {
    console.log("Works just fine here");
});
```

### Describe the bug

The API I am working with (Reddit) requires a content-type header to be set to `application/x-www-form-urlencoded` for retrieving an access token. The recommended approach from Nuxt3 documentation states that the `$fetch` function should be used with all of the relevant headers + body information. However, in doing so, I get various errors from the API. Combinations I have tried:

1. `$fetch` with `'Content-Type': 'application/x-www-form-urlencoded'`, and a simple `body: {}` object
2. `$fetch` with the same content-type, but with `FormData` as the body
3. `$fetch` with the same content-type, but with `querystring.stringify()` as the body
4. `$fetch` with `'Content-Type': 'multipart/form-data'` (because why not), and a simple `body: {}` object
5. `$fetch` with `'Content-Type': 'multipart/form-data'`, but with `FormData` as the body

In doing so , I either get a 500 error from the API (cases 3, 4, 5), or simply `unsupported grant type` (cases 1 and 2) because the API just can't process the incoming data. I would toss this up to an issue on the API side, however, executing the exact same query using `axios` + `querystring.stringify()` as the body gives me the correct response (and the header is `application/x-www-form-urlencoded`, as expected).

### Additional context

It's worth noting that the Reddit API is a little outdated, however, as mentioned above, everything works as expected when using `axios`. Things start to fall apart when `$fetch` is used to make the POST request.

### Logs

```shell
The two error messages returned are:

Best case:

{ error: 'unsupported_grant_type' }
```

Worst case:
```
FetchError: 500 Internal Server Error (https://www.reddit.com/api/v1/access_token)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/7722.
