### ISSUE TITLE
Can't import vue 3 plugin

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt/framework#8644]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `colorMode`, `css`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.5`, `@pinia/nuxt@0.4.3`, `@nuxtjs/color-mode@3.1.8`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-exxruu?file=app.vue

### Describe the bug

Can't import vue3-ace-editor in nuxt3. Tried all method of using [vue plugin in nuxt 3](https://v3.nuxtjs.org/guide/directory-structure/plugins#vue-plugins)

https://www.npmjs.com/package/vue3-ace-editor

Error - window is not defined

**Comment by danielroe** [comment]
It is an issue with that plugin - namely, it expects to be imported on client side only. I would raise an issue requesting SSR support.

I see what you're trying to do by only registering the component on client-side, but you then try to _use_ the component in the server render. One solution would be to create a wrapper component `~/components/MyEditor.client.vue` - the .client suffix will handle providing a server-side fallback for you.

Unrelated, I would also suggest not registering the component globally in a plugin but directly importing it in the component that uses it.
