### ISSUE TITLE
Package import specifier "#build/app.config.mjs" is not defined in package

### ISSUE THREAD

**Issue by floriankapaun** [nuxt/framework#8646]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[Reproduction Repo](https://github.com/floriankapaun/define-nuxt-plugin-import-issue-reproduction)

### Describe the bug

When running my test suite (`yarn vitest`) I get the following error: `Package import specifier "#build/app.config.mjs" is not defined in package /Users/.../reproduction/node_modules/nuxt/package.json imported from /Users/.../reproduction/node_modules/nuxt/dist/app/config.mjs`.

This happens because I'm importing and testing a method from a nuxt plugin file where `defineNuxtPlugin` is imported.

If I do not `import { defineNuxtPlugin } from "#app"` in `plugins/my-plugin.ts`, vitest is giving me an `ReferenceError: defineNuxtPlugin is not defined`.

Following are the most important excerpts, but you can check out the [reproduction repo](https://github.com/floriankapaun/define-nuxt-plugin-import-issue-reproduction) for details.

### Additional context

plugins/my-plugin.ts
```typescript
import { defineNuxtPlugin } from "#app";

export const xyz = 'xyz';

export default defineNuxtPlugin(() => {
    console.log('RUNNING THE PLUGIN');
})
```

tests/plugins/my-plugin.test.ts
```typescript
import { expect, it, vi } from 'vitest';

import { xyz } from '~~/plugins/my-plugin';

it('works', () => {
    expect(xyz).toEqual('xyz');
});

```

Current workaround:

tests/plugins/my-plugin.test.ts
```typescript
import { expect, it, vi } from 'vitest';

import { xyz } from '~~/plugins/my-plugin';

// Mocking the #app import helps to mitigate the error
vi.mock('#app', () => ({
    defineNuxtPlugin: vi.fn(),
}));

it('works', () => {
    expect(xyz).toEqual('xyz');
});
```

**Comment by danielroe** [comment]
I think we can track this in https://github.com/nuxt/framework/issues/2465.
