### ISSUE TITLE
[RC11] The `validate` field in `definePageMeta` doesn't work

### ISSUE THREAD

**Issue by szulcus** [nuxt/framework#8658]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction
```ts
import { definePageMeta } from '#imports';

definePageMeta({
	validate: async () => {
		console.log('validation...');
		return false;
	},
});
```

### Describe the bug

There is no "validation..." string in the console and the page renders correctly. Server reset doesn't help either.

### Additional context

https://v3.nuxtjs.org/getting-started/routing/

**Comment by dargmuesli** [comment]
I tried to create a reproduction, but everything works as expected in it: https://stackblitz.com/edit/github-a11wqg-4sfxcd?file=pages/index.vue

**Comment by szulcus** [comment]
The problem seems to be only in RC11. I have upgraded the original design to RC12 and so far everything seems to be working. It's possible that this has already been fixed, so I'm closing the issue, but as a curiosity I'm also sending a reproduction:
[Params reproduction.zip](https://github.com/nuxt/framework/files/9936266/Params.reproduction.zip)

**Comment by danielroe** [comment]
This feature was only introduced in rc12.
