### ISSUE TITLE
`definePageMeta` throws an error 500 as "is not defined" for external data

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/framework#8676]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13-27789756.491d02f`
- Nitro Version:    `0.6.1-27791756.086802d`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-a11wqg-luz3oz?file=package.json%3AL11

### Describe the bug

A variable declared outside `definePageMeta` is not defined inside `definePageMeta`.

### Additional context

This is the bug we had a chat about this morning, @danielroe.

**Comment by Zlatex** [comment]
The release version still has this problem when using something like this

![image](https://user-images.githubusercontent.com/19894225/213396064-92085bcb-f040-454d-81c7-8f44396712ec.png)
![image](https://user-images.githubusercontent.com/19894225/213396183-6de20d6a-922b-4ed9-9c4e-4d0bd856368b.png)

**Comment by danielroe** [comment]
`definePageMeta` is a macro and can't reference anything else that is defined _within_ the setup function.
