### ISSUE TITLE
`definePageMeta`'s layout property errors when computed

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/framework#8678]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13-27789756.491d02f`
- Nitro Version:    `0.6.1-27791756.086802d`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-s6twqp?file=pages%2Findex.vue

### Describe the bug

It [appears to me](https://v3.nuxtjs.org/api/utils/define-page-meta#parameters) that one can use a computed layout in `definePageMeta`. But apparently (see minimal reproduction) that does not work and prints `proxy set handler returned false for property '"layout"'` instead.

That error only appears on client side though, the initial ssr page displays correctly. Try reloading the page.

### Additional context

I receive the same error on RC12.

**Comment by danielroe** [comment]
Yes, I can confirm that is the effect, though I've not investigated further. You can work around like this:

```js
definePageMeta({
  layout: computed({
    get: () => 'default',
    set: () => {}
  }
})
```
