### ISSUE TITLE
`v-bind` HTML output missing on SSR if used within CSS expressions

### ISSUE THREAD

**Issue by szymonlicau** [nuxt/framework#8689]
### Environment

Nuxi 3.0.0-rc.13
RootDir: /home/projects/nuxt-starter-phmbfs
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-phmbfs?file=components/TestBinding1.vue

Try to refresh the preview window and see the content changing after hydration:
1. `TestBinding1` - flex container missing the gap on initial load, and applying that after hydration.
2. `TestBinding2` - CSS grid missing proper columns definition and changing that after hydration.

The color binding works fine in both cases.

### Describe the bug

HTML rendered on SSR is missing the binding for values used in `calc(...)` or `repeat(...)` expressions.
For anything else - the inlined `style` contains appropriate properties.

This may lead to content jumping around or changing after hydration.
For example in case of `repeat` - if we have a CSS grid which has a number of columns based on a prop.

**Comment by manniL** [comment]
Hey! Could you check with Vite SSR (plain, no Nuxt) to see whether this is an issue with Vue SSR itself? Feel free to start from [stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main](https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main).

**Comment by szymonlicau** [comment]
Turns out it also doesn't work with plain Vite SSR!
I even downloaded the project and ran it locally to check the returned HTML (FYI - https://stackblitz.com/edit/github-ne553q?file=README.md).
Seems like it might be an issue with how Vue itself handles these 🤔

**Comment by manniL** [comment]
Interesting! I didn't expect that either.

Feel free to raise an issue in https://github.com/vuejs/core/ then ☺️

**Comment by danielroe** [comment]
This is now fixed in vue [v3.2.43](https://github.com/vuejs/core/releases/tag/v3.2.43).
