### ISSUE TITLE
useFetch is not using new value from reactive object

### ISSUE THREAD

**Issue by Aietes** [nuxt/framework#8692]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `ssr`, `runtimeConfig`, `nitro`, `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@vueuse/nuxt@9.4.0`
- Build Modules:    `-`

### Reproduction

Does not works as expected, the API call does not reflect a change in the ref. When `rfid` changes, the API call fired keeps using the old value.

```
const rfid = ref("Value1")
rfid.value = "Value2"

const { data, refresh } = await useFetch<IOrderPopulated[]>(
  `/api/orders/find?rfid=${rfid.value}`,
  { watch: [rfid] }
)
```

The same setup works with useAsynchData, the API call does reflect a change in the ref. 
```
const rfid = ref("Value1")
rfid.value = "Value2"

const { data, refresh } = await useAsyncData<IOrderPopulated[]>(
  () => $fetch(`/api/orders/find?rfid=${rfid.value}`),
 { watch: [rfid] } 
)
```

### Describe the bug

The ref value is not updating in useFetch. The request url keeps using the same value, not reflecting the updated value from the ref. The same ref value does work when using useAsynchData. I'm not sure if I'm using useFetch in a wrong way, but since  useAsynchData works fine, I'm suspecting a bug in useFetch. The problem is occurring also when not using `watch` and manually triggering the refresh.

**Comment by danielroe** [comment]
That is not reactive because you are 'freezing' the value of the url when you call `useFetch`. Instead, try this:

```js
const rfid = ref('Value1')
rfid.value = 'Value2'

const { data, refresh } = await useFetch<IOrderPopulated[]>(
  '/api/orders/find',
  { query: { rfid } }
)
```

**Comment by Aietes** [comment]
Just tested it, works with multiple objects. Thank you!
