### ISSUE TITLE
Imported enum no longer available within the page middleware

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/framework#8698]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.13-27789756.491d02f`
- Nitro Version:    `0.6.1-27789681.ce7cc73`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `typescript`, `alias`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/DamianGlowala/nuxt-8536-bug-repro

### Describe the bug

An imported enum is no longer available within the page middleware since https://github.com/nuxt/framework/pull/8536.

**Comment by danielroe** [comment]
I think we can track in https://github.com/nuxt/framework/issues/8676.
