### ISSUE TITLE
defineNuxtComponent doesn't support layout property

### ISSUE THREAD

**Issue by vedmant** [nuxt/framework#8702]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `build`, `modules`, `buildModules`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.11`
- Build Modules:    `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/eslint-module@3.1.0`

### Reproduction

Try using different layout on the page:
```
<script lang="ts">
export default defineNuxtComponent({
  layout: 'admin',
})
</script>
```

### Describe the bug

Hi, I'm migrating the project on options API to Nuxt 3, and looks like `layout` option doesn't work when using options API.

**Comment by danielroe** [comment]
This is true. You need to use `definePageMeta`. This works with options API as well. There is more info in the migration docs.

**Comment by vedmant** [comment]
@danielroe I couldn't find proper info in migration docs. Also how I can use both options api and composition api in the same time?

**Comment by danielroe** [comment]
Try this:

```vue
<script lang="ts">
definePageMeta({
  layout: 'admin'
})

export default defineComponent({
})
</script>
```

A PR to improve docs would be welcome 🙏

**Comment by vedmant** [comment]
@danielroe Thanks, there is no different between using `defineNuxtComponent` and `defineComponent` in Nuxt project?

**Comment by danielroe** [comment]
The current difference is support for Options API-style `asyncData`: see https://v3.nuxtjs.org/api/utils/define-nuxt-component.
