### ISSUE TITLE
No response returned from render handler [upgraded from RC.12 to 13] 

### ISSUE THREAD

**Issue by Pamavoc** [nuxt/framework#8706]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `build`, `buildModules`, `vite`
- Runtime Modules:  `@vueuse/nuxt@9.4.0`
- Build Modules:    `@vueuse/nuxt@9.4.0`
------------------------------

### Reproduction

I will edit this section with a template asap

### Describe the bug

Just upgraded from RC.12 to RC.13, nothing changed in my repo. Was perfectly working with RC.12, but now I'm getting this white text with a grey background :

`No response returned from render handler: /__nuxt_error?url=/&statusCode=500&statusMessage=Vite+Error&message=[vite-node]+[ERR_INVALID_URL_SCHEME]+/node_modules/ufo/dist/index.mjs&stack=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+/node_modules/ufo/dist/index.mjs%3C/span%3E%3C/pre%3E&data`

### Additional context

Package.json 

{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "dependencies": {
    "@theatre/core": "^0.5.0",
    "@theatre/studio": "^0.5.0",
    "@vueuse/nuxt": "^9.3.1",
    "glslify": "^7.1.1",
    "gsap": "^3.11.3",
    "howler": "latest",
    "mitt": "^3.0.0",
    "nuxi": "^3.0.0-rc.13",
    "postprocessing": "^6.29.0",
    "three": "latest",
    "tweakpane": "latest",
    "vite-plugin-glsl": "^0.5.2"
  },
  "devDependencies": {
    "@tweakpane/core": "latest",
    "@types/three": "latest",
    "sass": "^1.49.8"
  }
}

### Logs

```shell
Nuxi 3.0.0-rc.13                                                                                                                                  20:17:52
Nuxt 3.0.0-rc.13 with Nitro 0.6.1                                                                                                                 20:17:52
                                                                                                                                                  20:17:53
  > Local:    http://localhost:3000/ 

i Vite client warmed up in 3591ms                                                                                                                 20:17:59
√ Nitro built in 698 ms                                                                                                                     nitro 20:18:00
(node:1512) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by shtse8** [comment]
I have the same issue.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by luabraggion** [comment]
estou com o mesmo problema ao atualizar

No response returned from render handler: /__nuxt_error?url=/&statusCode=500&statusMessage=Vite+Error&message=[vite-node]+[ERR_INVALID_URL_SCHEME]+/node_modules/ufo/dist/index.mjs&stack=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+/node_modules/ufo/dist/index.mjs%3C/span%3E%3C/pre%3E&data

**Comment by fabrizioiacobucci** [comment]
@danielroe I have the same issue but I have an empty app. I just ran "npx nuxi init <appname>" -> "nuxi add page index" -> changed <NuxtWelcome /> to <NuxtPage /> in app.vue -> "npm run dev -- -o" and getting the error on any browser

**Comment by fabrizioiacobucci** [comment]
@danielroe I solved it but not sure of the root cause. My root folder had 1 space in the name, I renamed it deleting the space. 
After this change VS Code asked again to Trust the Author and fodler content and also which browser to use when ran NPM RUN DEV.
Not sure if it is related to any cached info in VS Code or something else.

**Comment by shtse8** [comment]
> Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

I tried my best to find the cause. but still no idea and don't know how to reproduce. no matter what I tried, after upgrading to rc13, the error exists.

**Comment by danielroe** [comment]
Likely related to https://github.com/nuxt/framework/pull/8673.

cc: @pi0.

**Comment by actuallywitcher** [comment]
> Likely related to #8673.
> 
> cc: @pi0.

@shtse8 , @Pamavoc @fabrizioiacobucci  
It appears that the error arises from using JavaScript files instead of Typescript files in the Plugins directory. In my case, changing the plugin file to a Typescript file solved the problem for me.

**Comment by shtse8** [comment]
> > Likely related to #8673.
> > cc: @pi0.
> 
> @shtse8 , @Pamavoc @fabrizioiacobucci It appears that the error arises from using JavaScript files instead of Typescript files in the Plugins directory. In my case, changing the plugin file to a Typescript file solved the problem for me.

But I don't have any JavaScript file in my project. All are typescripts.

**Comment by Pamavoc** [comment]
Hi everyone, thanks for your answers.

The bug seems to be related to the path my project is in.

1. Moved folder from `D:\Gobelins\Année-4` to `C:\Users\me\Desktop` 
2. Removed node_modules folder and yarn.lock file
3. Ran again `yarn install`
4. Lastly, I ran `npx nuxi@latest upgrade --force`

These steps fixed the bug. I suspect the path name "Année-4". Maybe check the path where your project is located and see if there are any special characters.

**Comment by phenomenal-hardy** [comment]
any update on this? still having this same error after upgrading to rc13, cant make any of the posible solutions to get it working :(

**Comment by MuhammadM1998** [comment]
I had the same problem after upgrading from rc12 to rc13, the problem was fixed after I removed the spaces from my project name. If this didn't work for you there could be spaces in a parent folder of your project.

**Comment by phenomenal-hardy** [comment]
> I had the same problem after upgrading from rc12 to rc13, the problem was fixed after I removed the spaces from my project name. If this didn't work for you there could be spaces in a parent folder of your project.

Thank you very much, got it working, i had a space in a parent folder


this was my project path ( space in "software development" )
C:\Users\pheno\Documents\Software Development\Proyectos\ferreteria-nuxt-app

created a new project folder in desktop and got it working right away

**Comment by AKreiker** [comment]
I have neither spaces in the directory nor parent folder and I still get this error 🤔

**Comment by shtse8** [comment]
> I have neither spaces in the directory nor parent folder and I still get this error 🤔

Same here. My project path is `D:\project\`. The error still exists.

**Comment by muhni97** [comment]
> > I had the same problem after upgrading from rc12 to rc13, the problem was fixed after I removed the spaces from my project name. If this didn't work for you there could be spaces in a parent folder of your project.
> 
> Thank you very much, got it working, i had a space in a parent folder
> 
> this was my project path ( space in "software development" ) C:\Users\pheno\Documents\Software Development\Proyectos\ferreteria-nuxt-app
> 
> created a new project folder in desktop and got it working right away

That's the whole thing. I moved my folder to the desktop and it's fixed

**Comment by Maxp777** [comment]
> > > I had the same problem after upgrading from rc12 to rc13, the problem was fixed after I removed the spaces from my project name. If this didn't work for you there could be spaces in a parent folder of your project.
> > 
> > 
> > Thank you very much, got it working, i had a space in a parent folder
> > this was my project path ( space in "software development" ) C:\Users\pheno\Documents\Software Development\Proyectos\ferreteria-nuxt-app
> > created a new project folder in desktop and got it working right away
> 
> That's the whole thing. I moved my folder to the desktop and it's fixed

dance with folder place :)
i say that here is something unclear
now i always run npm run nuxi clean and after dev

**Comment by shtse8** [comment]
Currently, it still can work with rc12, but not rc13. any progress on this issue?

**Comment by Maxp777** [comment]
@shtse8 Nuxt 3.0.0-rc.14-27796957.b60f136

**Comment by shtse8** [comment]
> 

For Nuxt 3.0.0-rc.14-27799756.453ce78, I still get the same error.
```
No response returned from render handler: /__nuxt_error?url=/&statusCode=404&statusMessage=Cannot+find+any+route+matching+/.&message=Cannot+find+any+route+matching+/.&stack&data
```

PLUS.... even more...
```
 WARN  Failed to resolve dependency: vue-router, present in 'optimizeDeps.include'                                                                                                                                                                                                                         17:20:06


 ERROR  Failed to resolve import "vue-router" from "virtual:nuxt:D:\project\.nuxt\pages.mjs". Does the file exist? 
```

**Comment by Maxp777** [comment]
@shtse8 a ha ha ha, i don't havr such troubles, i am more lucky 

you have something with optimizeDeps.include in nuxt config? remove may be?

**Comment by shtse8** [comment]
> @shtse8 a ha ha ha, i don't have such troubles, i am more lucky
> 
> you have something with optimizeDeps.include in nuxt config? remove may be?
> 
> i play now with ssr, not spa or ssg

No, I don't have this setting, and even don't know what this setting is. Almost all settings are default. This is my first time to see this setting in an error. I don't play around manually with `vue-router` as I know `nuxt` handles all stuffs internally.

**Comment by Maxp777** [comment]
you have special character in root path (diacritics)?

**Comment by manniL** [comment]
I think there are multiple issues combined here:

* An error with special characters in file paths
* The problem that the error handler is not rendered at all (for all kind of `vite-node` errors)

**Comment by TechieStephen** [comment]
Well I have been able to work around this on my end. Like @Pamavoc suggested this seems to be caused by white space or special characters not just in the project name but also in the project directory and PC username.

For example my project was in `C:\users\Techie Stephen\desktop\nuxt-app`

This was what got it working:
- move project to my c drive to `C:\nuxt-app`
- delete node_modules and `yarn.lock` or `package-lock.json` file
- run `yarn install` or `npm install`
- run `yarn dev` or `npm run dev`

**Comment by Maginobion** [comment]
I can confirm the error occurs if any folder it is included in has a space or special character

**Comment by shtse8** [comment]
> Well I have been able to work around this on my end. Like @Pamavoc suggested this seems to be caused by white space or special characters not just in the project name but also in the project directory and PC username.
> 
> For example my project was in `C:\users\Techie Stephen\desktop\nuxt-app`
> 
> This was what got it working:
> 
> * move project to my c drive to `C:\nuxt-app`
> * delete node_modules and `yarn.lock` or `package-lock.json` file
> * run `yarn install` or `npm install`
> * run `yarn dev` or `npm run dev`

but my project doesn't include any space or special characters and even my pc username is just "kyle". nothing special. but it still shows the error.

**Comment by shtse8** [comment]
After upgrading to `Nuxi 3.0.0-rc.14-27801543.b4d7d62`,

the error message changed to

<img width="952" alt="image" src="https://user-images.githubusercontent.com/8020099/201137877-0c418492-5b78-495e-b0d7-7e62ae5576a5.png">

**Comment by shtse8** [comment]
x

> Would you open a new issue with a reproduction? 🙏

I am thinking if something in rc13 and rc14 breaks `unocss` in rc13 and rc14. I opened an issue there: https://github.com/unocss/unocss/issues/1869

**Comment by yesworld** [comment]
same problem :(

Reproducing:
```bash
pnpm dlx nuxi init nuxt-app
```

package.json
```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.13"
  }
}
```

```bash
pnpm install

pnpm run dev
```

Console:
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/6162264/201466501-28c8df37-812e-4e41-9414-08209d1fc041.png">

I **downgraded to version rc 9** and all is well.

**Comment by pyncz** [comment]
@yesworld 
It's related to #5411, not this one. Check that issue.

Using nuxt with pnpm, you should install deps like this:
```
pnpm install --shamefully-hoist
```
OR add `vue` and `ufo` (and whatever you see in similar errors) in deps manually.

**Comment by Maxp777** [comment]
> @yesworld It's related to #5411, not this one. Check that issue.
> 
> Using nuxt with pnpm, you should install deps like this:
> 
> ```
> pnpm install --shamefully-hoist
> ```
> 
> OR add `vue` and `ufo` (and whatever you see in similar errors) in deps manually.

or use npm

**Comment by yesworld** [comment]
```
npm install
npm run dev
```
console:
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/6162264/201469886-c666ec11-a1af-46d0-aa83-9257caba0ac5.png">

browser:
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/6162264/201469933-f3d922a8-3fc1-4fcc-8bf6-8890d1107101.png">

**Comment by Maxp777** [comment]
I use 3 days ago old version `@3.0.0-rc.14-27799761.3839dba`, and no such problem.
Thank, I will not update!

**Comment by MaciekCelinski** [comment]
Hi, if that would help anyone I did this:

inside of **nuxt.config.ts** i have added this line: 

`import { defineNuxtConfig } from 'nuxt';`

then in **pakage.json** I have changed:

```
  "devDependencies": {
    "nuxt": "3.0.0-rc.13"
  },
```
  
  into this:
  
```
    "devDependencies": {
    "nuxt": "3.0.0-rc.13"
  },
  "overrides": {
    "nuxt": "3.0.0-rc.5",
    "nuxi": "3.0.0-rc.5",
    "@nuxt/vite-builder": "3.0.0-rc.5",
    "@nuxt/kit": "3.0.0-rc.5",
    "@nuxt/schema": "3.0.0-rc.5"
  }
```
  
  after this "npm run dev" worked correctly

**Comment by chrisw786** [comment]
I was getting the same error, but managed to get it working on rc 11.

**Comment by Maxp777** [comment]
as I say, it work well for me with nuxt@3.0.0-rc.14-27799761.3839dba

**Comment by nathannye** [comment]
Solved my issue with renaming every folder in the path. D:\Dev\Projects\ProjectName. ProjectName originally had a space (Project Name).

**Comment by Szymon-dziewonski** [comment]
@pyncz Thank you very much for your reply, I spent so much time trying to figure it out, on `yarn` it works, but with `pnpm` it does not. `shamefully-hoist=true` is fixing issue, for me personally it shows how bad Nuxt iscompare to other frameworks like `Next` etc, with `Nuxt` there are always problems with it :/

**Comment by spokik** [comment]
> @danielroe I solved it but not sure of the root cause. My root folder had 1 space in the name, I renamed it deleting the space. After this change VS Code asked again to Trust the Author and fodler content and also which browser to use when ran NPM RUN DEV. Not sure if it is related to any cached info in VS Code or something else.

Thanks! Removing a space from the directory helped me

**Comment by devmnj** [comment]
No spaces allowed in root 📂

**Comment by crunchwrap89** [comment]
I also had the same issue when upgrading from RC 12 to 3.0.0 stable.
Changing my rootfolder path in C://code/wg projects/myapp/  to C://code/wg-projects/myapp/ solved the issue. No need to reinstall / clean inbetween.

**Comment by danielroe** [comment]
yes, the issue is linked above.

**Comment by Szymon-dziewonski** [comment]
> @Szymon-dziewonski You can track #5411 - we do not support pnpm without `--shamefully-hoist` at the moment, but it's coming very soon.

Thank already doing it, appreciate info :)

**Comment by Vasejke** [comment]
> Well I have been able to work around this on my end. Like @Pamavoc suggested this seems to be caused by white space or special characters not just in the project name but also in the project directory and PC username.
> 
> For example my project was in `C:\users\Techie Stephen\desktop\nuxt-app`
> 
> This was what got it working:
> 
> * move project to my c drive to `C:\nuxt-app`
> * delete node_modules and `yarn.lock` or `package-lock.json` file
> * run `yarn install` or `npm install`
> * run `yarn dev` or `npm run dev`

Thank you, in my case it helped. I don't know what the error was related to, I just recreated the project on disk C and the error disappeared. The error was - 500
[vite-node] [ERR_INVALID_URL_SCHEME] /node_modules/ufo/dist/index.mjs.

**Comment by manniL** [comment]
Yes, see https://github.com/nuxt/framework/issues/9074
