### ISSUE TITLE
Page title and other metadata set using definePageMeta not updating on page transition via NuxtLink

### ISSUE THREAD

**Issue by jimhlad** [nuxt/framework#8717]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

**Reproduction**: https://github.com/jimhlad/nuxt-use-page-meta

**Reference Docs**: https://v3.nuxtjs.org/getting-started/seo-meta/#usage-with-definepagemeta

### Describe the bug

When transitioning between pages via `NuxtLink`, page titles and other metadata (e.g. og:title) don't seem to be updating.

Steps to re-create:

1. Clone the reproduction
2. `npm run dev` (or `npm run generate` and `npx serve .output/public`)
3. Visit localhost:3000/page-one
4. Observe that "I am page one" appears in the browser title bar as well as in the HTML head for title and og:title (Chrome inspector tool)
5. Click link to Page 2

Expected:
Page title and og:title value dynamically change to "I am page two"

Actual:
Page title and og:title remain as "I am page one"

If you hard-refresh the page, the values will then change to "I am page two" as expected.

### Additional context

Totally possible I am misunderstanding the use case here.

However I seem to be using `definePageMeta` in conjunction with `useHead` in the way that the docs suggest. Any help would be appreciated!

**Comment by danielroe** [comment]
The issue is that you are removing reactivity when you call `useHead`. If you want to preserve it, you can pass in a ref/computed or a function that returns a result, for example:

```js
const route = useRoute()
useHead({
  title: () => route.meta.title,
  meta: () => [{ name: 'og:title', content: `App Name - ${route.meta.title}` }],
})
```

**Comment by jimhlad** [comment]
Ah thanks for the quickly reply.

Could have sworn I tried ref, but the computed approach works perfectly!
