### ISSUE TITLE
API Router with params

### ISSUE THREAD

**Issue by frbuceta** [nuxt/framework#872]
### Environment

npx nuxi init nuxt3-app

### Describe the bug and expected behavior

Unable to create urls with parameters in API folder calls

### Steps to reproduce

Sandbox Link: https://codesandbox.io/s/blissful-mayer-zollx

Just create a tree to create a logical url with parameters in the url

### Additional context

#828

**Comment by Atinux** [comment]
Hi @frbuceta 

Currently it is not supported to define parameters in the filename like in `pages/` for performances reason (we code split each api route).

We are thinking of a matchParams() utility for H3 at the moment: https://github.com/unjs/h3/issues/4

@pi0 shall we move this into an RFC discussion?

**Comment by jasontheiler** [comment]
Are there any news on this topic? Having the ability to use parameters in the API endpoints seems quite important to me and I can't see anything about it on the roadmap. I mean if the `pages` support it, for example to access a specific item with an ID (`/posts/[id]`), then so the API endpoints should, too. Or would you use another paradigm for the API endpoints? For a REST API it's basically mandatory.

**Comment by Pwuts** [comment]
> Are there any news on this topic?

Yes, see #64 :)

**Comment by jasontheiler** [comment]
I'm actually not really sure how one would use this with Nuxt. Are you supposed to create a router in the endpoint and return the handle to it? Because that doesn't work since the default export is expected to be a function...

**Comment by Pwuts** [comment]
@jasontheiler: last I checked, Nitro (and thus also Nuxt 3) used `unjs/h3` internally for API routing. I haven't checked, but I would suspect it is now possible to make routes with `_id.ts` or `:id.ts` files. Maybe @pi0 can comment on this?

**Comment by pi0** [comment]
This feature is landing soon with Nitropack. We need to use new router for API router.

**Comment by pi0** [comment]
https://v3.nuxtjs.org/guide/features/server-routes
