### ISSUE TITLE
That will kill me someday

### ISSUE THREAD

**Issue by Maxp777** [nuxt/framework#8724]
### Environment

nuxt 3 edge

### Reproduction

It work when I try to make minimal reproduction.

https://www.veed.io/view/642fb7b0-49ad-4f11-b73a-4352f2e1022c

### Describe the bug

Not navigate login and register page, only if type direct link to login page and when i can go to register page and back to login page.

**Comment by manniL** [comment]
If it works fine when creating a minimal reproduction, it is not a Nuxt issue but one with your own code / business logic 🙈
From there it is tough to help without actual code.

Feel free to create a [discussion](https://github.com/nuxt/framework/discussions) with some boiled down example (e.g. strip down as much as you can but the error is still there) though!

**Comment by Maxp777** [comment]
If i delete all node modules and lock file ant reinstall all, it not work.
I copy all code to new installed nuxt 3 and it work. 
@manniL  How is problem with my code if i go to login page and no wanings?

**Comment by Maxp777** [comment]
and if is here an erro in my code, why console log need to output thousand times the same warning?

**Comment by Maxp777** [comment]
@manniL, @danielroe, @pi0  a ha ha ha i moved code from place where i try to make a reproduction to old place and reproduction not work again.
It works very strangely!!!!!!!

**Comment by Maxp777** [comment]
@manniL, @danielroe, @pi0  why the nuxt work depend on place where i put it?

**Comment by Maxp777** [comment]
now, now warnings, but it not go to login page but stay on the same but without content loaded from api

**Comment by danielroe** [comment]
@Maxp777 Please do not post multiple responses like this. It results in multiple email notifications to every participant in an issue and is extremely bad manners.

The issue might be related to the fact that Nuxt hard codes absolute paths to dependencies in the `.nuxt` directory (and vite may well do the same in `node_modules/.vite`). You can try running `npx nuxi cleanup` to see if that makes a difference.

**Comment by Maxp777** [comment]
@danielroe i try, but no difference from last experience. No console warnings like was when i open issue but pages not opening.
is is opening only if i remove

```
definePageMeta({
  auth: 'guest',
  middleware: ['auth']
})
```

**Comment by danielroe** [comment]
I suspect that is an issue with one of your dependencies, not with Nuxt, as I've commented here: https://github.com/nuxt/framework/issues/8738#issuecomment-1304745633.

**Comment by Maxp777** [comment]
@danielroe I think I found problem, that not work any more

import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.$auth.onRedirect((to: any) => {
    console.log(nuxtApp.$localePath(to)) // <-----------------------it output infinite times
    return nuxtApp.$localePath(to)
  })
})
