### ISSUE TITLE
run code in comment

### ISSUE THREAD

**Issue by mortifia** [nuxt/framework#8726]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v19.0.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `modules`, `content`
- Runtime Modules:  `@pinia/nuxt@0.4.3`, `@nuxt/content@2.2.0`
- Build Modules:    `-`
------------------------------

### Reproduction

![image](https://user-images.githubusercontent.com/22671054/200120264-314ddcc1-bf61-45fb-96ee-dd47e4d31514.png)

![image](https://user-images.githubusercontent.com/22671054/200120315-7b756b0a-b4ae-4fb3-9090-c03c29a5d7e7.png)

### Describe the bug

pages/404.vue

run commented in script setup

### Additional context

all to reproduct is in two screen (layout, page)

**Comment by danielroe** [comment]
This should be resolved in rc13. If not, please provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by mortifia** [comment]
tested and it's looks resolved in rc13
Thanks !
