### ISSUE TITLE
No match found for location with path ...

### ISSUE THREAD

**Issue by nasirDoe** [nuxt/framework#873]
### Environment

- windows 10
- brave browser
- nuxt 3

### Describe the bug and expected behavior
I created folder pages in my project and then i created 2 files `index.vue` and `about.vue`. the problem is, when i use `<nuxt-link to="/about">About Page</nuxt-link>` its will show  error `404`

**Comment by hieungochoangit** [comment]
I also had the same problem. I tried creating about folder with index file but the path seems to be broken.

**Comment by danielroe** [comment]
This is likely a duplicate of #1367, which is now resolved.
