### ISSUE TITLE
Not navigate to some page and warning onServerPrefetch is called when there is no active component instance to be associated with.

### ISSUE THREAD

**Issue by Maxp777** [nuxt/framework#8738]
### Environment

nuxt 3 edge

### Reproduction

https://github.com/Maxp777/nuxt3

### Describe the bug

[Vue warn]: onServerPrefetch is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

also not navigate to login and register page which use dfineMetaPage to set auth middleware (nuxtjs-alt-auth)

https://www.veed.io/view/642fb7b0-49ad-4f11-b73a-4352f2e1022c

**Comment by danielroe** [comment]
If this does not occur without `@nuxtjs-alt/auth`, then I would suggest raising the issue first in that repository. The error message sounds like a library is importing vue but is not added to `build.transpile`, meaning that multiple instances of vue are included in your app.

**Comment by danielroe** [comment]
Would you provide a [minimal reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏 (If not, I'll need to close it as this has a lot of third-party dependencies which are likely the source of this issue.)
