### ISSUE TITLE
Typescript error for useFetch in strict mode

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/framework#8747]
Hello 👋,

Since RC13 enables strict mode by default, I discovered that `useFetch` composable was throwing me typescript errors.

in pages
```ts
const { data: images } = await useFetch<ImageKit[]>('/api/imgkit')
const maxImageNumber = images.value.length // The object can have the value 'null'.ts(2531)
```

This comes from the `data` property definition :

```ts
export interface _AsyncData<DataT, ErrorT> {
    data: Ref<DataT | null>; // here. No error without "| null"
    pending: Ref<boolean>;
    refresh: (opts?: AsyncDataExecuteOptions) => Promise<void>;
    execute: (opts?: AsyncDataExecuteOptions) => Promise<void>;
    error: Ref<ErrorT | null>;
}
```

**Comment by ExEr7um** [comment]
I think you just need to use `images.value?.length`

**Comment by BenjaminOddou** [comment]
@ExEr7um but then it creates other problems later in my code (see below).

```sh
const maxImageNumber = images.value?.length
The object can have value 'undefined'.ts(2532)
```

```vue
          <button
            v-show="imageNumber < maxImageNumber"
            @click="handleClick"
          >
            See more
          </button>
```

Maybe there is a good reason why `data` and `error` should be union type with `null` but it causes ts conflicts by default which I found weird.

**Comment by manniL** [comment]
Workaround would be `const maxImageNumber = images.value?.length ?? 0`.
