### ISSUE TITLE
Allow fallback slot server side for .client components

### ISSUE THREAD

**Issue by huang-julien** [nuxt/framework#8748]
### Describe the feature

https://github.com/nuxt/framework/pull/8713#discussion_r1014787331

Currently, the treeshake module treeshakes the non-fallback slots within `<ClientOnly>` components.
But fallback slot does not exists in [`ServerPlaceholder`](https://github.com/nuxt/framework/blob/main/packages/nuxt/src/app/components/server-placeholder.ts) that is used server-side for .client component that are converted with [`createClientOnly()`](https://github.com/nuxt/framework/blob/fe433a4222dd9248ec04bd17b366ffa1aa00f94e/packages/nuxt/src/app/components/client-only.mjs#L23-L-74). We can add a `fallback` slot to `ServerPlaceholder`  so the users can have a fallback if they wish instead of a `<div>` with inherited attributes

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Apologies for my misdirection on this - I'm not sure whether this would be a good feature or confusing. After all, `.client` components aren't indicated as client-only at the point of use. And the current implemented way of providing a fallback is to create a corresponding `.server` component to match.

What do you think?

**Comment by huang-julien** [comment]
I agree that this might be confusing since `.server` components already exists.
Should #8713 treeshake fallback slots on `.client` components instead ? We would leave fallback/placeholder slots only for `<ClientOnly>`

**Comment by danielroe** [comment]
Yes, exactly. We would then treeshake _all_ slots from `.client` components.

**Comment by huang-julien** [comment]
closed, see https://github.com/nuxt/framework/issues/8748#issuecomment-1315163417
