### ISSUE TITLE
Issue with serving static file html with public dir after rc13

### ISSUE THREAD

**Issue by itsmnthn** [nuxt/framework#8749]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `pnpm@7.14.2`
- Builder:          `vite`
- User Config:      `extends`, `meta`, `runtimeConfig`, `modules`, `unocss`, `vueuse`, `ssr`, `pageTransition`, `vue`, `nitro`, `sourcemap`, `vite`, `build`, `typescript`
- Runtime Modules:  `@pinia/nuxt@0.4.3`, `@vueuse/nuxt@9.4.0`, `@unocss/nuxt@0.46.3`
- Build Modules:    `-`

### Reproduction

1. Create stand alone html file with resources inside `public/magic` dir
2. Use the created html file in i frame inside any component of page

Reproduction : https://stackblitz.com/edit/nuxt-starter-tf7qkb?file=pages/index.vue

### Describe the bug

I am using trading view charting library which requires to put all the related file to public dir and serve them as it is and library uses relative path to get other assets.

This was working fine. But after updating to pnpm and rc13 it return 404 

### Additional context

Screenshot from private project
![Screenshot 2022-11-06 at 9 38 26 PM](https://user-images.githubusercontent.com/25129674/200181547-a1e8c9e3-a0ca-43da-843c-cf3c4e0ba205.png)

**Comment by manniL** [comment]
1. It seems that you have a typo (bundle/bundles) in your reproduction
2. You need to use `src` instead of `href`

[Fixed stackblitz](https://stackblitz.com/edit/nuxtframeworkissues8749)

**Comment by itsmnthn** [comment]
Thank you @manniL 
My bad, I was in hurry and not able to replicate what is shown in above attached screenshot.

The issue is I'm not able to access this public file without using `.html` see below reproduction.

[Updated stackblitz](https://stackblitz.com/edit/nuxtframeworkissues8749-ndgqnx?file=pages/index.vue)

**Comment by manniL** [comment]
But when you use the full name of the file, with the `.html` ending, it works fine, right? Why not sticking to using the full filename then?

**Comment by itsmnthn** [comment]
Yeah setting nitro redirect works in production but in dev it still returns `404` even though the iframe src is with `.html` and nitro redirect rule is also present. Cannot reproduce minimal reproduction for the same thing

**Comment by itsmnthn** [comment]
Hey @manniL 
If you can tell me any possible reason for this to happen it would help a lot I need this working locally as well in order to add more interaction to chart.

**Comment by manniL** [comment]
Sadly I can't. Maybe @danielroe knows more. But regarding `.html` files + public folder, I suppose this is the currently intended behavior.

**Comment by itsmnthn** [comment]
I've got solution. this was problem of caching clearing browser cache worked. It is strange I did not configure anything to cache things.
