### ISSUE TITLE
Dynamic Files in directories display a Vue component with similar name as directory is present.

### ISSUE THREAD

**Issue by JWPapi** [nuxt/framework#8752]
### Environment

Nuxi 3.0.0-rc.13                                                                                                20:22:58
RootDir: /home/projects/github-qzrjux-htpepl                                                                    20:23:00
Nuxt project info:                                                                                              20:23:00

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
### Reproduction

https://github.com/JWPapi/github-qzrjux-htpepl

### Describe the bug

In the `pages` directory I’ve created a file `test.vue` and a folder `test` with a file `[handle].vue` When now visiting `/test/hello` I would expect to see the component in `[handle].vue`, but I see the component `test.vue`

Maybe that’s how it’s supposed to be, but not from my understanding and not from @maj3stik from Discord.

![image](https://user-images.githubusercontent.com/4718469/200190823-f09a483e-7c79-46e5-a9a4-32e4177cf6b6.png)

**Comment by danielroe** [comment]
This is how nested routes are constructed.

You can display the contents of `[handle].vue` within `test.vue` by adding `<NuxtPage>`. Or you can rename it to `test/index.vue` if it should be parallel.

See https://v3.nuxtjs.org/guide/directory-structure/pages/#nested-routes for more info.

**Comment by JWPapi** [comment]
Thank You!
