### ISSUE TITLE
Page Transitions doesn't work when layout was set dynamic

### ISSUE THREAD

**Issue by Intevel** [nuxt/framework#8753]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `app`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `nuxt-icon@0.1.7`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-s1wt9f?file=app.vue

### Describe the bug

Noticed that page transitions doesn't work for pages which have a dynamic layout. 
CC: @manniL  
Probably caused by the same reason of #8493

**Comment by danielroe** [comment]
You can set `app.pageTransition` to true. It is no longer enabled by default.
