### ISSUE TITLE
new nitro devProxy not working

### ISSUE THREAD

**Issue by huuhait** [nuxt/framework#8763]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`, `experimental`, `css`, `colorMode`, `nitro`
- Runtime Modules:  `@vueuse/nuxt@9.4.0`, `@unocss/nuxt@0.46.3`, `@pinia/nuxt@0.4.3`, `@nuxtjs/color-mode@3.1.8`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-5pp8lm?file=nuxt.config.ts,package.json

### Describe the bug

i'm always get 404 in proxy url
![image](https://user-images.githubusercontent.com/40519768/200271227-b0442493-3faf-46b0-94c3-f550725d504a.png)

**Comment by manniL** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/640208/200272788-1845c407-e81d-45ea-ab8b-2c7aa14725ee.png">

Looks fine in your StackBlitz (except that nothing is running on 3001)

**Comment by huuhait** [comment]
> <img alt="image" width="1080" src="https://user-images.githubusercontent.com/640208/200272788-1845c407-e81d-45ea-ab8b-2c7aa14725ee.png">
> 
> Looks fine in your StackBlitz (except that nothing is running on 3001)

![image](https://user-images.githubusercontent.com/40519768/200273183-dc22cb84-68cc-4a4b-b06a-31de53ea2adf.png)
i'm running good
pls try to make a fork

**Comment by huuhait** [comment]
> No, I meant that the `/proxy/test` route works fine proxying to 3001.

I dont think so
can u try the `/proxy/example` route?

![image](https://user-images.githubusercontent.com/40519768/200274031-885d24df-5d3c-4a45-b510-b88b5573f4cf.png)

i always get 404

**Comment by manniL** [comment]
Yes, I see the 404. Please check my previous comment ☺️

**Comment by huuhait** [comment]
> ```ts
> '/proxy/example': {
>     target: 'https://api.albionstatus.com/',
>     prependPath: true,
>     changeOrigin: true,
>   },
> ```

it's working good with your example
but i've try with example.com or somethings else it's not working...
```js
      '/api/v2': {
        target: 'http://demo.zsmartex.com/',
        prependPath: true,
        changeOrigin: true,
      },
```

https://demo.zsmartex.com/api/v2/trade/public/timestamp

**Comment by huuhait** [comment]
I hope i will get solution very soon

**Comment by huuhait** [comment]
i'll try again and report here

**Comment by huuhait** [comment]
Hi @manniL i've tested in local
but it's not working at all... :(

Error:
![image](https://user-images.githubusercontent.com/40519768/200761657-ce6c1300-c260-42b2-a0c8-4dc481aa3e07.png)
Config
![image](https://user-images.githubusercontent.com/40519768/200761681-8be2cbbb-e107-4f46-bd5f-5fa44803daaf.png)

**Comment by huuhait** [comment]
ahh it's work
just the config very hard
not like vitejs

**Comment by onenameneo** [comment]
> <img alt="image" width="1080" src="https://user-images.githubusercontent.com/640208/200272788-1845c407-e81d-45ea-ab8b-2c7aa14725ee.png">
> 
> Looks fine in your StackBlitz (except that nothing is running on 3001)

Thanks a lot.

**Comment by lixiaofa** [comment]
I don't understand.
I set it like this.
![image](https://user-images.githubusercontent.com/23230215/205657940-b1578c10-b307-4e45-9752-1f852c9a12b3.png)
but ,  nitro devProxy not working 
![image](https://user-images.githubusercontent.com/23230215/205658622-3dd09f1b-6cc0-43da-bf01-1285650ba604.png)
@manniL @onenameneo

**Comment by poncianodiego** [comment]
maybe dumb but might help someone make sure you add the config to the `nitro` key:

```
  nitro: {
    devProxy: {
      '/api': { 
        target: "http://localhost:8000", 
        changeOrigin: true 
      }
    },
  },
```
