### ISSUE TITLE
Docs example fail ❌: https://v3.nuxtjs.org/examples/experimental/wasm/ 

### ISSUE THREAD

**Issue by chinanf-boy** [nuxt/framework#8764]
### Environment

Chrome

[https://v3.nuxtjs.org/examples/experimental/wasm/](https://v3.nuxtjs.org/examples/experimental/wasm/)

### Reproduction

-

### Describe the bug

SyntaxError: The requested module 'file:///home/projects/llqilqgoa.github/node_modules/h3/dist/index.mjs' does not provide an export named 'defineLazyHandler'
    at async Promise.all (index 0)

## Fix

https://github.com/nuxt/framework/blob/main/examples/experimental/wasm/server/api/sum.ts#L1

```ts
import { defineLazyHandler } from 'h3'

export default defineLazyHandler(async () => {
```

[`defineLazyHandler `=> `lazyEventHandler` ](https://github.com/unjs/h3/commit/333a4cab3c278d3749c1e3bdfd78b9fc6c4cefe9#diff-841254fe75488c1bd4cd7f68f00b4be0e48dcfbc4a16b45847b68295e0e3b27bL8)

```ts
import { lazyEventHandler } from 'h3'

export default lazyEventHandler(async () => {
```

Done

**Comment by manniL** [comment]
PR Welcome ☺️

**Comment by manniL** [comment]
It is weird though because [`defineLazyHandler`](https://www.jsdocs.io/package/h3#defineLazyEventHandler) should exist 🤔

**Comment by suruaku** [comment]
I think h3 docs are outdated. See this:

https://github.com/unjs/h3/search?q=lazyEventHandler

**Comment by manniL** [comment]
Yes, my bad. I mean `defineLazyEventHandler` and it should be preferred ☺️
