### ISSUE TITLE
Cookies not being sent with ssr

### ISSUE THREAD

**Issue by maksimdrosdov** [nuxt/framework#8791]
### Environment

useAsyncData

### Reproduction

useAsyncData

### Describe the bug

`credentials: 'include',`

if ssr is enabled, no cookies are sent
```

const { data, error } = await useAsyncData('getUserCart', () => httpRepository.getUserCart(),
    {
      initialCache: false
    }
  );
```

**Comment by danielroe** [comment]
See https://v3.nuxtjs.org/getting-started/data-fetching/#isomorphic-fetch-and-fetch.
