### ISSUE TITLE
useLazyFetch doesn't work on page refresh

### ISSUE THREAD

**Issue by JohnnyEvo** [nuxt/framework#8798]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `typescript`, `build`, `modules`, `css`, `runtimeConfig`
- Runtime Modules:  `@lewebsimple/nuxt3-svg@0.1.1`, `@nuxtjs/tailwindcss@6.1.3`, `@pinia/nuxt@0.4.3`
- Build Modules:    `-`

### Reproduction

[Demonstration](https://stackblitz.com/edit/github-4qfxry?file=app.vue,server%2Fapi%2Fquestions.ts)

`@/server/api/questions.ts` : 

```ts
import {questions} from "../../api";

export let useApiQuestions = async () => {
    const config = useRuntimeConfig()

    return useLazyFetch(questions, {
        baseURL: config.public.apiBase,
        initialCache: false
    });
}
```

My component : 

```ts
import {useApiQuestions} from "@/server/api/questions";
import {watch} from "vue";

let {data, error} = await useApiQuestions();

watch(error, (data) => {
  console.log('e', data);
})
watch(data, (data) => {
  console.log('d', data);
})
```

### Describe the bug

In development mode, when I pass from route A to route B, my data is fetching. When I update my code and HMR loads, my data is fetching.
But when I reload my page, my data is not fetching.

### Additional context

I'm in dev mode `npm run dev`.

**Comment by danielroe** [comment]
The reproduction seems to work fine to me.

**Comment by JohnnyEvo** [comment]
When you load the demo, alerts are displayed ? Alerts are display when I change route or update code, but not loading (or reloading)

**Comment by danielroe** [comment]
When you load the demo, the initial fetch happens on the server, not on the client. So no alert happens on the client side. If you want to trigger a watch immediately, you can pass `{ immediate: true }` as an option:

```js
watch(data, (data) => {
  console.log('d', data);
  alert('data changed');
}, { immediate: true });
```

**Comment by JohnnyEvo** [comment]
Oh, thank you 👍
