### ISSUE TITLE
Expose `isExternal` prop of <NuxtLink> via scoped slot API

### ISSUE THREAD

**Issue by manniL** [nuxt/framework#8799]
### Describe the feature

Hey all 👋🏻

It is amazing that `<NuxtLink>` can handle external links by now (thanks @lihbr for the RFC back then)! One thing that would be helpful is exposing the `isExternal` property to the scoped slots attributes so users don't have to rewrite the logic and can still customize their Link as they like

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by pi0** [comment]
Merged via #8800
