### ISSUE TITLE
Generic response type not working with `useFetch`

### ISSUE THREAD

**Issue by szulcus** [nuxt/framework#8807]
### Versions

- nuxt: 3.0.0-rc.12 & 3.0.0-rc.13
- node: v16.11.0

### Reproduction
https://stackblitz.com/edit/github-itsfns?file=app.vue

Works fine (`asyncData` is a `_AsyncData<{ title: string }, true | FetchError<any> | null>`:
```ts
const customApi = async () => {
	const asyncData = await useFetch<{ title: string }>('https://api.nuxtjs.dev/mountains', {
		pick: ['title'],
		method: 'GET',
	});
	return asyncData;
};
const result  = await customApi();
console.log(result.data.value?.title);
```
Not working (`asyncData` is a `_AsyncData<PickFrom<_ResT, KeyOfRes<Transform>>, true | FetchError<any> | null>`):
```ts
const customApi = async <T>() => {
	const asyncData = await useFetch<T>('https://api.nuxtjs.dev/mountains', {
		pick: ['title'],
		method: 'GET',
	});
	return asyncData;
};
const result  = await customApi<{ title: string }>();
console.log(result.data.value?.title);
```

Additionally, setting the `pick1 field causes an error.

<details open>
<summary>Additional Details</summary>
<br>
I would like to add that everything worked very well before. Unfortunately, now even undoing the Nuxt version doesn't help.
</details>

### Steps to reproduce
Copy and paste code above.

### What is Expected?
I want to create a custom `useFetch` and be able to type a response ([link1](https://stackoverflow.com/questions/72041740/how-to-set-global-api-baseurl-used-in-usefetch-in-nuxt-3), [link2](https://github.com/nuxt/framework/issues/2122#issuecomment-1085668327))

### What is actually happening?
I am getting a weird type causing my application to fail.

**Comment by szulcus** [comment]
@danielroe I set now 'strict' to 'false', reload editor and still have the same problem:
![image](https://user-images.githubusercontent.com/48328739/200564162-ca6976f4-c3f2-4231-80df-3ece94181b1b.png)
![image](https://user-images.githubusercontent.com/48328739/200564179-18eb802a-89e2-4631-9af9-034cf71be423.png)

**Comment by danielroe** [comment]
(The correct solution, from a TypeScript point of view, is the code I provided above.)

**Comment by szulcus** [comment]
I find it hard to believe because it is a bit contradictory to the idea of using generics. Especially since I was able to define any type successfully before. It turns out that from now on, every response from api must be `any`?

**Comment by danielroe** [comment]
No; it's still fully typed. Your custom composable just specifies that any valid type must have a title field, because we're going to pick the title field.

**Comment by szulcus** [comment]
The problem is that composable similar to `customApi`, where I defined `baseURL`, response parsing, error handling and a lot of other additions, I keep in a separate file. I wish I could use this anywhere in the app. In short, my code looks like this:
```ts
const customApi = async <T>(request: NitroFetchRequest, options: UseFetchOptions<T extends void ? unknown : T, (res: T extends void ? unknown : T) => T extends void ? unknown : T, KeyOfRes<(res: T extends void ? unknown : T) => T extends void ? unknown : T>>) => {
	const statusCode = ref<number>(200);
	const asyncData = await useFetch<T>(request, {
		initialCache: false,
		baseURL: <url>,
		headers: { ...headers, authorization: localStorage['auth-token'] }, // current localStorage
		onResponseError: async (ctx) => {
			statusCode.value = ctx.response.status;
			await onResponseError(ctx);
		},
		onRequest,
		parseResponse,
		...options,
	});
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	return { ...asyncData as any, statusCode };
};
```
As you can see, I can't extends T here, because wherever I try to use this composable it will be a different type. Is there any other way for `customApi` to be fully typed?

**Comment by danielroe** [comment]
In that case, you can copy the types from `useFetch` with their inference. It's a complex type but it needs to be for the inference:

https://github.com/nuxt/framework/blob/bdacfa6ffe65d8887e4830fa0d4c8ef2f424698c/packages/nuxt/src/app/composables/fetch.ts#L23-L33

The other alternative is to simply override them, e.g.:

```ts
const customApi = async <T>(request: NitroFetchRequest, options: UseFetchOptions<T extends void ? unknown : T, (res: T extends void ? unknown : T) => T extends void ? unknown : T, KeyOfRes<(res: T extends void ? unknown : T) => T extends void ? unknown : T>>) => {
	const statusCode = ref<number>(200);
	const asyncData = await useFetch(request, {
		initialCache: false,
		baseURL: <url>,
		headers: { ...headers, authorization: localStorage['auth-token'] }, // current localStorage
		onResponseError: async (ctx) => {
			statusCode.value = ctx.response.status;
			await onResponseError(ctx);
		},
		onRequest,
		parseResponse,
		...options,
	}) as AsyncData<T, FetchError | null>;
	return { ...asyncData, statusCode };
};
```

**Comment by danielroe** [comment]
You are very welcome 😊

**Comment by danielroe** [comment]
Yes, the error type is the second generic - `AsyncData<T, MyCustomFetchError | null>;
`

**Comment by szulcus** [comment]
Yes, I know. I mean a ready type with missing fields returned by `useFetch` (`status`, `statusCode`, `statusMessage`, `statusText`). These fields are not dependent on me. I hope this can be completed in the future. Temporarily I'll do it manually like this:
```ts
AsyncData<T, (FetchError<ApiError> & { status: number }) | null>
```
I'm not bothered anymore, thank you for your time and help.
