### ISSUE TITLE
[Doc] Use layouts with `<script setup>`

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/framework#882]
The doc is not very clear. https://v3.nuxtjs.org/docs/directory-structure/layouts
There should probably be an exemple for both `<script setup>` and the options API for every Nuxt feature.
I'd think I'd have to use the new <NuxtLayout> component, but the it says you have to disable something using the option API.
```
<script>
export default {
  layout: false,
};
</script>
```

**Comment by huynl-96** [comment]
I think you misunderstand the functionality of `<script setup>`. This is just another way to express the `setup()` function in Vue 3. Just simply combine `<script setup>` with normal `<script>` (for any additional component options).

e.g.:
```vue
<script>
export default {
  layout: false,
  inheritAttrs: false,
  ...
};
</script>

<script setup>
// your setup script
</script>
```

You can look more into this in the below link
https://v3.vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script

**Comment by mrleblanc101** [comment]
Does that mean we can still use `asyncData` inside the option API like in Nuxt2 instead of `useAsyncData` inside a script setup ?

**Comment by mrleblanc101** [comment]
I don't know what you mean by that. I guess I'll learn when I switch from Vue 2 / Nuxt 2 and when the doc is more complete.

**Comment by danielroe** [comment]
There's an additional piece of functionality here that can be followed up on https://github.com/nuxt/framework/issues/782.
