### ISSUE TITLE
HMR doesn't work for pages (3.0.0-rc.13)

### ISSUE THREAD

**Issue by yura3d** [nuxt/framework#8820]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-mwpzkm?file=app.vue,pages%2Findex.vue

### Describe the bug

Any change made to files in `pages` directory causes to page reload.

But changes made to app.vue (for example) are applied through HMR correctly.

**Comment by minkoonim** [comment]
god... 
I thought it was my problem,
tried adding /removing all the plugins and packages to check what caused this for hours..

**Comment by minkoonim** [comment]
Just tried downgrading to rc12 and HMR works fine.

when upgrading back to latest (rc.14-27799862.1496d3a),
any change in pages will fully reload the whole app.
