### ISSUE TITLE
Poor performance of rc.13 (response time)

### ISSUE THREAD

**Issue by maxtomczyk** [nuxt/framework#8823]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.4.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@3.2.0`
- Builder:          `vite`
- User Config:      `sourcemap`, `imports`, `experimental`, `css`, `modules`, `app`, `typescript`, `nitro`, `buildModules`, `build`, `plugins`, `vite`, `runtimeConfig`, `routeRules`
- Runtime Modules:  `normalizedModule()`, `normalizedModule()`, `normalizedModule()`
- Build Modules:    `@pinia/nuxt@0.4.3`

### Reproduction

No reproduction available

### Describe the bug

Today I updated my project from rc.12 to rc.13 and deployed it. I noticed that average response time is now much higher.
I marked update time on this graph:
![image](https://user-images.githubusercontent.com/20241462/200627839-16729d4b-c84e-482b-92a8-5e9e15a98864.png)

It it correct behaviour of rc.13 update?

**Comment by danielroe** [comment]
No, it's not expected that response time would increase. With such a high response time, I would think you are performing API calls on server-side and I would think it's more likely that this is the issue.

Please feel free to provide a minimal reproduction and I will very happily reopen and investigate this.
