### ISSUE TITLE
RC13: layouts with named slots can't be used in transitioned pages

### ISSUE THREAD

**Issue by TheDutchCoder** [nuxt/framework#8829]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `app`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-1wqbue-5yfh9s?file=layouts%2Ftest.vue,pages%2Ftest.vue,pages%2Findex.vue,app.vue,nuxt.config.ts

### Describe the bug

When you have a layout with multiple named slots, and a page that uses that layout and puts content in those slots, you lose the "single root node" in that page (you can't simple wrap it in a div, for example, due to the slots).

When you use page transitions, Nuxt will complain about missing root nodes.

**Comment by danielroe** [comment]
In this case, you need to wrap `<NuxtLayout>` in a div: https://stackblitz.com/edit/github-1wqbue-ambsdh?file=layouts%2Ftest.vue

**Comment by TheDutchCoder** [comment]
Ah, interesting, thanks that solved it.
I just had to do it on the page level instead for it to work.
