### ISSUE TITLE
[Nuxt3.0.0-rc.13] UseFetch() when calling multiple request, only the last data is fetched.

### ISSUE THREAD

**Issue by yeonjulee1005** [nuxt/framework#8840]
### Environment

Nuxi 3.0.0-rc.13
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `ssr`, `target`, `meta`, `css`, `plugins`, `vite`, `build`, `modules`, `buildModules`, `typescript`, `components`, `vueuse`, `publicRuntimeConfig`
- Runtime Modules:  `@vueuse/nuxt@9.5.0`
- Build Modules:    `@pinia/nuxt@0.4.3`, `unplugin-icons/nuxt`
------------------------------

### Reproduction

Page
     L component_1.vue
     L component_2.vue
     L conponent_3.vue

component_1
`
onMounted(() => {
   request('firstUrl')
})

const request = async (url:string) => {
   const { data } = await useFetch(url, options)
   console.log(data)
}
`

component_2
`
onMounted(() => {
   request('secondUrl')
})

const request = async (url:string) => {
   const { data } = await useFetch(url, options)
   console.log(data)
}
`

component_3
`
onMounted(() => {
   request('thirdUrl')
})

const request = async (url:string) => {
   const { data } = await useFetch(url, options)
   console.log(data)
}
`

### Describe the bug

My pages folder tree

in each component(tabs), 
Each component requested the following api calls in the onMounted lifecycle.

However, among the above three requests, 
I found that the data of the last request data goes into each result(component_1, component_2 result).

useFetch() <- not working Async / await ? 

you can find my log below, 

As I expected, the response value should come right below each url,
but the last data comes 3 times after all url have been delivered.
(see, logs)
what should i do? help me:)

useFetch() can use 3.0.0-rc.8.

### Logs

```shell
orders/usim/delivery/before/1/20
orders/usim/delivery/after/1/20
orders/usim/1/20
Proxy {success: true, data: {…}}[[Handler]]: Object[[Target]]: Objectdata: {list: Array(20), count: 1649}success: true[[Prototype]]: Object[[IsRevoked]]: false
Proxy {success: true, data: {…}}[[Handler]]: Object[[Target]]: Objectdata: {list: Array(20), count: 1649}success: true[[Prototype]]: Object[[IsRevoked]]: false
Proxy {success: true, data: {…}}[[Handler]]: Object[[Target]]: Objectdata: {list: Array(20), count: 1649}success: true[[Prototype]]: Object[[IsRevoked]]: false
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

Please note you should not call `useFetch` in an event handler but use `$fetch` directly.

**Comment by yeonjulee1005** [comment]
I'm currently using nuxt3 for a commercial project,
so I can't 'reproduction' it. 😢

you're right! $fetch() works normally.
However, i did not use useFetch() as an event handler,
This is only problem the part that uses method: 'get' in the onMounted lifecycle😢

in event handler, Others, 'post', 'patch', and 'del' all work normally.😢

At the same time, there seems to be only a problem with useFetch(url, { method: 'GET'}) .

Should I unconditionally use $fetch() when fetching data from onMounted ? 😢

**Comment by danielroe** [comment]
Please see the link I posted. I don't need your project, but I do need a stackblitz that shows the issue.

**Comment by yeonjulee1005** [comment]
Thank you for helping me!
I'll write it up and post it!

**Comment by yeonjulee1005** [comment]
@danielroe 
Thank you your help! :D
I solve this problem like this! 👍 
i'll close this issue!!

const get = async (url:string) => {
    const { data, pending, error, refresh } = await useFetch(url, {
      method: 'GET',
      baseURL: getApiUrl(),
      credentials: 'include',
      initialCache: false,
      headers: {
        'content-type': 'application/json',
        authorization: `Bearer ${useCookie('accessToken').value}`
      },
      onResponse ({ response }) {
        return response._data
      },
      onResponseError ({ response }) {
        return response._data
      }
    })
    const resData = data.value
    const resPending = pending.value
    const resError = error.value
    return { resData, resPending, resError, refresh }
  }
