### ISSUE TITLE
Parent page with <NuxtPage /> is not showing `index.vue` content when accessed by it's router name

### ISSUE THREAD

**Issue by lucassimines** [nuxt/framework#8863]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.14-27799862.1496d3a`
- Nitro Version:    `0.6.2-27796963.837f894`
- Package Manager:  `npm@8.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ksjnki?file=pages%2Fposts.vue,pages%2Fposts%2Findex.vue,pages%2Findex.vue

Click on "Posts", then "Go to post", and then "Go back", you see that, using `NuxtLink` with the page name, will show a `blank` page, but it works using `<NuxtLink to="/posts">` as you see on the `index.vue` file.

### Describe the bug

When using <NuxtPage /> inside a parent page "posts.vue", doesn't show the content of `posts/index.vue` when accessed by it's name. That used to work until `rc.12`.

**Comment by danielroe** [comment]
I think this is working as expected; there is just no content on that page when it is rendered in isolation (as you are doing by giving it a name _apart_ from its default child). You should probably move the `definePageMeta` block to add the name to the `posts/index.vue` file, and you will likely get the result you're looking for: https://stackblitz.com/edit/github-ksjnki?file=pages%2Fposts.vue,pages%2Fposts%2Findex.vue,pages%2Findex.vue.

**Comment by lucassimines** [comment]
Yes, but I was using `posts.vue` metaData for both `index.vue` and `post.vue`, was working on previous versions before `rc.13`, wouldn't you think this might a good feature?

**Comment by lucassimines** [comment]
Yes @danielroe! I know what is happening now, I was using `name` as my `model` name, before you add the `name` property on commit 496fa14468c3585fc466052cfa31754fc7194193, so I have to change that `name` property to my child! Sorry for the misunderstanding 😉
