### ISSUE TITLE
Feature request: Have `nuxi preview` respect server port options in config, or support a `--port` option.

### ISSUE THREAD

**Issue by mattgilbertnet** [nuxt/framework#8896]
### Discussed in https://github.com/nuxt/framework/discussions/8831

<div type='discussions-op-text'>

<sup>Originally posted by **mattgilbertnet** November  8, 2022</sup>
I'm working with `nuxt-edge` as recommended in the Nuxt Bridge migration docs. There are a couple of other discussions about production mode and SSG generally, but none seem to provide a way to run a generated site locally on a specified port.

- `server` options in `nuxt.config.js` are ignored.
- `nuxi dev` has a `--port` option, but `nuxi preview` does not.
- The port selected by `nuxi preview` changes every time the server is started, if 3000 is already being used. (Making it useless for, say, bookmarked links or links generated by another app.)
- By manually editing `.output/nitro.json`, you can add a port option to the `npx` command with something like `-l 8000`. But this file is replaced the next time `nuxi generate` is run.

Is there any way to specify a port for `nuxi preview` that I haven't tried?</div>

**Comment by danielroe** [comment]
You can run `PORT=3000 nuxi preview` if you are running the built _node_ server, for what it's worth. But there are lots of different output formats, which have different ways of configuring a port so this may be more complex to implement.

**Comment by mattgilbertnet** [comment]
That works! Thank you so much @danielroe , that addresses at least my use case.
