### ISSUE TITLE
Undefined route in Nuxt layout component in prod build

### ISSUE THREAD

**Issue by misaon** [nuxt/framework#8897]
### Environment

```
- Operating System: `Linux`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `pnpm@7.15.0`
- Builder:          `vite`
- User Config:      `modules`, `oxyshopNuxt`, `i18n`, `experimental`
- Runtime Modules:  `normalizedModule()`, `normalizedModule()`
- Build Modules:    `-`
```

### Reproduction

Build to prod

### Describe the bug

In the dev environment everything works fine, once the application build to production. on the client side Nuxt RC-13 crashes on the error that the route is undefined.
https://github.com/nuxt/framework/blob/59d8c51b5bd8d8f7de66f83494d9d39110e43c44/packages/nuxt/src/app/components/layout.ts#L73
On Nuxt RC-12 it works fine.

### Additional context

![image](https://user-images.githubusercontent.com/15806356/201121574-38366738-1d2d-4889-ae41-2a534cf3afb2.png)

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'meta')
    at zc.fn (entry.6b774f36.js:78:63198)
    at zc.run (entry.6b774f36.js:1:4282)
    at get value [as value] (entry.6b774f36.js:1:12410)
    at Proxy.<anonymous> (entry.6b774f36.js:78:63258)
    at fl (entry.6b774f36.js:1:15833)
    at St (entry.6b774f36.js:1:49906)
    at zc.V [as fn] (entry.6b774f36.js:1:49994)
    at zc.run (entry.6b774f36.js:1:4282)
    at G.T.update (entry.6b774f36.js:1:50299)
    at G (entry.6b774f36.js:1:50325)
nE @ entry.6b774f36.js:1
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by misaon** [comment]
> Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

Unfortunately, it's part of a commercial project.
It happened after we switched from RC-12 to RC-13. We are currently fixing to RC-12, hopefully we can fix the problem.

**Comment by misaon** [comment]
@danielroe 

module:
```ts
import { fileURLToPath } from 'node:url'
import { addPlugin, addServerHandler, defineNuxtModule, installModule, useLogger } from '@nuxt/kit'
import { defu } from 'defu'
import { resolve } from 'pathe'
import { version } from '../package.json'
import { isOxyPluginEnabledOnAnyChannel } from './utils'

export interface ChannelOptions {
  code: string
  configuration: {
    imgproxy: Record<string, string | number>
    imageSizes: {
      sm: string
      md: string
      lg: string
    }
    taxon: {
      numberOfMainTaxons: number
    }
  }
  plugins: Record<string, { [key: string]: any; enabled: boolean }>
}

export interface ModuleOptions {
  /**
   * Global configuration
   */
  replicaId: string
  objectStorageInternalUrl: string
  objectStoragePublicUrl: string
  imgproxyKey: string
  imgproxySalt: string

  /**
   * Per-channel configuration
   */
  channels: ChannelOptions[]
}

export interface ModuleHooks {
  'oxy:blog:visit': any
  'oxy:channel:ready': any
  'oxy:currency:onSwitch': any
  'oxy:order-shippingAndPayment:visit': any
  'oxy:page:visit': any
  'oxy:product:addToCart': any
  'oxy:product:beforeAddToCart': any
  'oxy:product:beforeAddToComparer': any
  'oxy:product:visit': any
  'oxy:search:visit': any
  'oxy:taxon:visit': any
  'oxy:user:loggedIn': any
  'oxy:user:loggedOut': any
}

export interface ModulePublicRuntimeConfig {
  REPLICA_ID: string
  IMGPROXY_KEY: string
  IMGPROXY_SALT: string
  OBJECT_STORAGE_INTERNAL_URL: string
  OBJECT_STORAGE_PUBLIC_URL: string
}

const defaultChannelOptions: ModuleOptions['channels'] = [
  {
    code: '',
    configuration: {
      imgproxy: {
        fit: 'fill',
        width: 0,
        height: 0,
        gravity: 'no',
        enlarge: 1,
        format: 'webp',
      },
      imageSizes: {
        sm: '100x100',
        md: '300x300',
        lg: '600x600',
      },
      taxon: {
        numberOfMainTaxons: 7,
      },
    },
    plugins: {
      cookieConsent: {
        enabled: false,
      },
      foxentry: {
        enabled: false,
        key: undefined,
      },
      gtm: {
        enabled: false,
      },
      heurekaBadge: {
        enabled: false,
        key: undefined,
        type: undefined,
        companyName: undefined,
        domain: undefined,
        shopId: undefined,
      },
      heurekaConversion: {
        enabled: false,
      },
      instagramFeed: {
        enabled: false,
        authToken: undefined,
        slug: undefined,
        showCaption: false,
      },
      recaptcha: {
        enabled: false,
        siteKey: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI', // Testing key
        secretKey: '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe', // Testing key
      },
      smartemailing: {
        enabled: false,
      },
      luigisBoxAutocomplete: {
        enabled: false,
        key: '', // LBX-######
        trackId: '', // ######-######
      },
      luigisBoxSearch: {
        enabled: false,
        key: '', // LBX-######
        trackId: '', // ######-######
      },
      ares: {
        enabled: false,
      },
      vies: {
        enabled: false,
      },
    },
  },
]

const logger = useLogger('@oxyshop/nuxt')

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-oxyshop-nuxt',
    version,
    configKey: 'oxyshopNuxt',
    compatibility: { nuxt: '^3.0.0-rc.12' },
  },
  defaults: {
    /**
     * Global configuration
     */
    replicaId: '<REPLICA_ID>',
    objectStorageInternalUrl: '<OBJECT_STORAGE_INTERNAL_URL>',
    objectStoragePublicUrl: '<OBJECT_STORAGE_PUBLIC_URL>',
    imgproxyKey: '<IMGPROXY_KEY>',
    imgproxySalt: '<IMGPROXY_SALT>',

    channels: [],
  },
  async setup(options, nuxt) {
    const nuxtOptions = nuxt.options
    const runtimeDirectory = fileURLToPath(new URL('runtime', import.meta.url))

    logger.info(`Using oXyShop Nuxt module v${version}`)

    // Define config usable in Oxy plugin (SSR)
    for (const [index, channel] of options.channels.entries()) {
      options.channels[index] = defu(channel, defaultChannelOptions[0])
    }

    nuxtOptions.runtimeConfig.public.oxy = options

    // Issue: https://github.com/nuxt/framework/issues/8306
    nuxtOptions.experimental = defu(
      {
        writeEarlyHints: false,
      },
      nuxtOptions.experimental
    )

    nuxtOptions.vite = defu(
      {
        server: {
          hmr: {
            protocol: 'wss',
            clientPort: 443,
            path: '/hmr',
          },
        },
        optimizeDeps: {
          include: ['crypto-es', 'geolib'],
        },
      },
      nuxtOptions.vite
    )

    nuxtOptions.build = defu(
      {
        transpile: ['geolib'],
      },
      nuxtOptions.build
    )

    // @TODO: resolve configuration on plugins
    // nuxtOptions.nitro = defu(
    //   {
    //     routeRules: {
    //       '/order/**': { ssr: false },
    //     },
    //   },
    //   nuxtOptions.nitro
    // )

    nuxtOptions.app = defu(
      {
        head: {
          viewport: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no',
          meta: [
            { name: 'description', content: '' },
            { name: 'format-detection', content: 'telephone=no' },
          ],
        },
      },
      nuxtOptions.app
    )

    // @ts-expect-error missing interface
    nuxtOptions.schemaOrg = defu(
      {
        canonicalHost: '/',
      },
      // @ts-expect-error missing interface
      nuxtOptions.schemaOrg
    )

    // @ts-expect-error missing interface
    nuxtOptions.i18n = defu(
      {
        baseUrl: '/',
        lazy: true,
        langDir: 'lang/',
        vueI18n: {
          legacy: false,
        },
      },
      // @ts-expect-error missing interface
      nuxtOptions.i18n
    )

    // Add assets types in SFC imports
    nuxt.hook('prepare:types', ({ references }) => {
      references.push({
        path: resolve(fileURLToPath(new URL('../', import.meta.url)), 'types/assets.d.ts'),
      })
    })

    // Install external modules
    for await (const module of ['@nuxtjs/fontaine', '@nuxtjs/i18n', '@vueuse/nuxt', 'nuxt-schema-org']) {
      await installModule(module)
    }

    // ...

    // Add $oxy client/server composables
    nuxt.hook('imports:dirs', (directories) => {
      directories.push(resolve(runtimeDirectory, 'composables/*/index.ts'))
    })

    // Register predefined oxy pre definitions
    for (const predefined of ['blog', 'orderShippingAndPayment', 'page', 'product', 'search', 'taxon']) {
      addPlugin(resolve(runtimeDirectory, `plugins/predefined/${predefined}.ts`))
    }

    // Register core oxy plugins
    for (const plugin of [
      '0.middleware',
      '1.http',
      '2.channel',
      '3.currency',
      '4.auth',
      '5.order',
      '6.shop',
      'comparer',
      'image',
      'i18n.client',
      'lastVisitedProducts.client',
      'wishlist',
      'scrollToTop.client',
      'directive',
    ]) {
      addPlugin(resolve(runtimeDirectory, `plugins/${plugin}.ts`))
    }

    // Register optional client oxy plugins
    for (const clientPlugin of [
      'cookieConsent',
      'foxentry',
      'gtm',
      'heurekaBadge',
      'heurekaConversion',
      'luigisBoxSearch',
      'luigisBoxAutocomplete',
      'smartemailing',
    ]) {
      if (isOxyPluginEnabledOnAnyChannel(clientPlugin, options.channels)) {
        addPlugin(resolve(runtimeDirectory, `plugins/external/${clientPlugin}.client.ts`))
      }
    }

    addServerHandler({
      handler: resolve(runtimeDirectory, `server/middleware/ip-fallback.js`),
    })

    // AddServerHandler({
    //  handler: resolve(runtimeDirectory, `server/middleware/url-case-redirect.js`),
    // })

    if (isOxyPluginEnabledOnAnyChannel('instagramFeed', options.channels)) {
      addServerHandler({
        route: `/instagram-media-feed`,
        method: 'get',
        handler: resolve(runtimeDirectory, `server/routes/instagram-media-feed.get.js`),
      })
    }

    if (isOxyPluginEnabledOnAnyChannel('recaptcha', options.channels)) {
      addServerHandler({
        route: `/recaptcha-verify`,
        method: 'post',
        handler: resolve(runtimeDirectory, `server/routes/recaptcha-verify.post.js`),
      })

      addPlugin(resolve(runtimeDirectory, `plugins/external/recaptcha.client.ts`))
    }

    // ...
  },
})
```

layout.vue
```ts
<template>
  <div>
    <NuxtLoadingIndicator color="#ea580c" />
    <Html :lang="head.htmlAttrs.lang" :dir="head.htmlAttrs.dir">
      <Head>
        <Meta property="replica-id" :content="runtimeConfig.public.oxy.replicaId" />
        <template v-for="meta in head.meta" :key="meta.id">
          <Meta :id="meta.id" :property="meta.property" :content="meta.content" />
        </template>
      </Head>
      <Body>
        <TheHeader />

        <main class="pb-10 md:pb-20">
          <LazyNgBanner />

          <slot />
        </main>

        <ClientOnly>
          <LazyTheFooter />
        </ClientOnly>
      </Body>
    </Html>
  </div>
</template>

<script lang="ts" setup>
import { useHead, useRuntimeConfig, useLocaleHead, useNuxtApp } from '#imports'

const nuxtApp = useNuxtApp()
const runtimeConfig = useRuntimeConfig()
const {
  $channel: { current: currentChannel },
  $order: { refreshOrder },
  $comparer: { refreshComparer },
  $wishlist: { refreshWishlist },
} = nuxtApp

await Promise.all([refreshOrder(), refreshComparer(), refreshWishlist()])

/**
 * Set meta tags
 */
const head = useLocaleHead({
  addDirAttribute: true,
  identifierAttribute: 'id',
  addSeoAttributes: true,
})

useHead({
  titleTemplate: `%s | ${currentChannel.value.name}`,
})
</script>
```

**Comment by danielroe** [comment]
I'm not asking for your full app, just a minimal reproduction of the issue via https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz.

**Comment by misaon** [comment]
Could it be related? https://github.com/nuxt/framework/issues/3587

![image](https://user-images.githubusercontent.com/15806356/201141180-4cbaee6e-80b3-4d95-89fc-785a31ba2b7a.png)

**Comment by misaon** [comment]
@danielroe this is what causes it https://github.com/nuxt/framework/pull/8421

**Comment by misaon** [comment]
`const route` falls to `undefined` in prod

**Comment by misaon** [comment]
> Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

https://github.com/nuxt/framework/issues/8904

**Comment by danielroe** [comment]
Would you try upgrading your version of vue-router to 4.1.6 manually?

**Comment by michealroberts** [comment]
@danielroe Confirmed that upgrading to `vue-router` version 4.1.6 has fixed this issue. 🙏

**Comment by dargmuesli** [comment]
I am on v4.1.6 since it was released and yet I still face this error on Nuxt edge.

**Comment by danielroe** [comment]
@dargmuesli Any chance of a reproduction? 🙏

**Comment by dargmuesli** [comment]
Oh well, I spent way too many hours deep inside code just to find out I had to update my `vue` dependency to at least `3.2.45`!

**Comment by misaon** [comment]
> Oh well, I spent way too many hours deep inside code just to find out I had to update my `vue` dependency to at least `3.2.45`! The error is gone now.
Does it really work?

**Comment by misaon** [comment]
For me `vue 3.2.45` and `vue-router 4.1.6` still throw an error with an undefined route.

**Comment by dargmuesli** [comment]
Make sure all your other dependencies are up to date as well, @misaon.
If you're using `pnpm` that would be a `pnpm upgrade --interactive --latest` and a `pnpm upgrade`.

**Comment by paolooo** [comment]
What I did is to resolve this issue is, I deleted my `yarn.lock` file, node_modules, .output, and .nuxt directories. Then, installed nuxt again.

```
$ rm -rf node_modules .output .nuxt yarn.lock
$ yarn install
$ yarn build
$ node .output/server/index.mjs
```

**Comment by misaon** [comment]
Upgrade to RC-14 solved this issue 🙏

**Comment by MichaelPrecel** [comment]
I didn't encounter this issue until upgrading from rc-12 to 1.0.0. In dev and in local build it works fine, but as soon as it is deployed to Netlify I'm hit with the error `cannot read properties of undefined (reading 'meta')`. The page loads for a split second and then the error is encountered and the page goes white. 

Looking at `pnpm-lock.yaml`, vue router and vue are at the latest versions as above. 

@danielroe Any ideas? Could it have something to do with the fact that this project only uses one template, ie the `pages` folder only contains two files `[[slug]].vue` and `404.vue`? Still strange that it's only on production in Netlify that it's occuring.

Have had to revert to rc-12 in the meantime until resolved.

**Comment by misaon** [comment]
> I didn't encounter this issue until upgrading from rc-12 to 1.0.0. In dev and in local build it works fine, but as soon as it is deployed to Netlify I'm hit with the error `cannot read properties of undefined (reading 'meta')`. The page loads for a split second and then the error is encountered and the page goes white.
> 
> Looking at `pnpm-lock.yaml`, vue router and vue are at the latest versions as above.
> 
> @danielroe Any ideas? Could it have something to do with the fact that this project only uses one template, ie the `pages` folder only contains two files `[[slug]].vue` and `404.vue`? Still strange that it's only on production in Netlify that it's occuring.
> 
> Have had to revert to rc-12 in the meantime until resolved.
> 
> <img alt="Screen Shot 2022-11-21 at 1 38 02 pm" width="456" src="https://user-images.githubusercontent.com/27719652/202954715-56508c5d-eb50-429c-9065-088ccd896cc0.png">

Show me your package.json deps list.

**Comment by littlejon85** [comment]
> > I didn't encounter this issue until upgrading from rc-12 to 1.0.0. In dev and in local build it works fine, but as soon as it is deployed to Netlify I'm hit with the error `cannot read properties of undefined (reading 'meta')`. The page loads for a split second and then the error is encountered and the page goes white.
> > Looking at `pnpm-lock.yaml`, vue router and vue are at the latest versions as above.
> > @danielroe Any ideas? Could it have something to do with the fact that this project only uses one template, ie the `pages` folder only contains two files `[[slug]].vue` and `404.vue`? Still strange that it's only on production in Netlify that it's occuring.
> > Have had to revert to rc-12 in the meantime until resolved.
> > <img alt="Screen Shot 2022-11-21 at 1 38 02 pm" width="456" src="https://user-images.githubusercontent.com/27719652/202954715-56508c5d-eb50-429c-9065-088ccd896cc0.png">
> 
> Show me your package.json deps list.

I have an observation which might help to narrow it down a bit.  
I encountered this issue also when going from rc.12 to ^rc.14 and 1.0.0. It only happened when using `pnpm install --shamefully-hoist`. Using `npm` didn't produce this problem.  
The cause of it for me was our internal components library. It was enough for it to be included in `package.json` of a clean nuxt project. I'd get the error event without importing any part of it.  Been trying to make a reproduction, but couldn't.  
Adding `auto-install-peers=true` to `.npmrc` solved the issue.

**Comment by misaon** [comment]
One possible problem could be that one of your deps has a dependency on Vue 2. For example, the presence of the `@gtm-support/vue-gtm` package in `package.json` is causing this particular error.

**Comment by Katerinka28** [comment]
> I didn't encounter this issue until upgrading from rc-12 to 1.0.0. In dev and in local build it works fine, but as soon as it is deployed to Netlify I'm hit with the error `cannot read properties of undefined (reading 'meta')`. The page loads for a split second and then the error is encountered and the page goes white.
> 
> Looking at `pnpm-lock.yaml`, vue router and vue are at the latest versions as above.
> 
> @danielroe Any ideas? Could it have something to do with the fact that this project only uses one template, ie the `pages` folder only contains two files `[[slug]].vue` and `404.vue`? Still strange that it's only on production in Netlify that it's occuring.
> 
> Have had to revert to rc-12 in the meantime until resolved.
> 
> <img alt="Screen Shot 2022-11-21 at 1 38 02 pm" width="456" src="https://user-images.githubusercontent.com/27719652/202954715-56508c5d-eb50-429c-9065-088ccd896cc0.png">

just upgrate vue-router to 4.1.6! It`s work perfect for me(nuxt 3.0.0)

**Comment by MichaelPrecel** [comment]
Thanks everyone for your suggestions, a lot of good avenues to explore here. @misaon You could be on the money, I'm using `vue-gtag-next`, so perhaps that has a Vue 2 dep. I'll try See package below. I'll try some of these solutions and report back.

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@vueuse/core": "^9.1.1",
    "@vueuse/nuxt": "^9.1.1",
    "include-media": "^1.4.10",
    "nuxt": "3.0.0-rc.12",
    "sass": "^1.51.0",
    "sass-loader": "^13.2.0"
  },
  "dependencies": {
    "@nuxtjs/sanity": "1.3.2",
    "@sanity/image-url": "^1.0.1",
    "flickity": "^3.0.0",
    "flickity-as-nav-for": "^3.0.0",
    "lazysizes": "^5.3.2",
    "reset-css": "^5.0.1",
    "vh-check": "^2.0.5",
    "vue-gtag-next": "^1.14.0"
  }
}
```
