### ISSUE TITLE
WindiCSS classes are not inlined with "inlineSSRStyles: true"

### ISSUE THREAD

**Issue by enkot** [nuxt/framework#8918]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`, `experimental`
- Runtime Modules:  `nuxt-windicss@2.5.3`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-encemj

### Describe the bug

Nuxt doesn't inline WindiCSS classes with "inlineSSRStyles: true".

**Comment by manniL** [comment]
AFAIK WindiCSS classes are loaded as global styles.
Nuxt does not inline global styles anymore since https://github.com/nuxt/framework/pull/8666

**Comment by daguitosama** [comment]
Hi @manniL i pretty much will like to keep my critical styles on the html head, im setting: 
```js
experimental: {
        inlineSSRStyles: true,
    },
```
But it doesn't do it, #8666 remove it completely? The experimental key is still present in `rc-13` and IntelliSense says is on `true` by default.

**Comment by manniL** [comment]
@daguitosama From my understanding, the option it will still inline *component* styles but not *global* styles.
