### ISSUE TITLE
Middleware + pinia not working

### ISSUE THREAD

**Issue by maksimdrosdov** [nuxt/framework#8926]
### Environment

middleware

### Reproduction

middleware

### Describe the bug

When I reload the page, it throws me to the authorization page, although the user is authorized

```
import { useAuthStore } from '~/store/auth';

export default defineNuxtRouteMiddleware(async () => {
  const { loggedIn } = useAuthStore();

  if (!loggedIn) {
    return navigateTo('/auth');
  }
});
```

**Comment by HigherOrderLogic** [comment]
This doesn't looks like a Nuxt error. Can you provide a minimum reproduction?

**Comment by Dodje** [comment]
I believe that happens because you need to connect your [pinia](https://pinia.vuejs.org/core-concepts/outside-component-usage.html) instance with app store. 

In your vue components pinia can get store context from app's context (this.$store) via some magic, but there is no such a thing in a simple general function. But you can get it from `ctx.app.$store` Sadly I've not worked with pinia closely, but I guess a little trick from Vuex-smart-modue might help you to find easy solution, You need to connect you store manager with store context manually:
```
// vuex-smart-module example
// Get module context
const ctx = yourModule.context(store);
```
So if there is no such a thing for pinia, there is an issue in the pinia lib.

And actually we can find similar [issue](https://github.com/vuejs/pinia/discussions/1212) there

**Comment by maksimdrosdov** [comment]
`console.log('loggedIn = ', loggedIn);`

shows that true, but everything exactly redirects to auth

**Comment by maksimdrosdov** [comment]
@danielroe sent an invite

**Comment by manniL** [comment]
@maksimdrosdov Please be aware that a full-blown project is no reproduction 🙈 

The goal is to have as little "moving pieces" as possible and a project that is as small as possible to reproduce the bug so contributors can pin it down easily and it is not caused by any custom userland logic

**Comment by maksimdrosdov** [comment]
<img width="562" alt="Снимок экрана 2022-11-14 в 23 54 24" src="https://user-images.githubusercontent.com/114719453/201718997-ee617666-db30-43a0-b296-957cef54f388.png">

```
import { storeToRefs } from 'pinia';
import { useAuthStore } from '~/store/auth';

export default defineNuxtRouteMiddleware(() => {
  const authStore = useAuthStore();

  console.log({...authStore});

  const { loggedIn } = storeToRefs(authStore);

 if (!loggedIn.value) {
  //return navigateTo('/auth');
 }
});
```

**Comment by typhoon11** [comment]
This problem is still there please fix it. In middleware pinia data is empty

**Comment by manniL** [comment]
@typhoon11 Can you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)?

**Comment by typhoon11** [comment]
> @typhoon11 Can you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)?

So I made a getter in pinia 
![image](https://user-images.githubusercontent.com/66431066/206728510-da5f5c12-3533-40a3-93bd-46bff4d907d9.png)
and tried them on middleware and a page 
![image](https://user-images.githubusercontent.com/66431066/206728579-af564380-02b4-45c9-bcf6-027617b36da2.png)

So it's visible that pinia is empty for the files in the middleware directory

**Comment by manniL** [comment]
@typhoon11 Please provide a repository or use Stackblitz or Codesandbox as linked above. This is the best way to make it easy for maintainers to help you. I highly recommend to read the linked paragraph above.

**Comment by typhoon11** [comment]
> @typhoon11 Please provide a repository or use Stackblitz or Codesandbox as linked above. This is the best way to make it easy for maintainers to help you. I highly recommend to read the linked paragraph above.

Sorry for late reply. https://stackblitz.com/edit/github-nf9a2f

**Comment by manniL** [comment]
@typhoon11 In your middleware, you should not trigger `navigateTo` in the "default"/"happy" case. Instead, just not return anything and the middleware will "succeed".

**Comment by typhoon11** [comment]
> @typhoon11 In your middleware, you should not trigger `navigateTo` in the "default"/"happy" case. Instead, just not return anything and the middleware will "succeed".
> 
> ```ts
> import { useDiscordUser } from '~/stores/auth';
> 
> export default defineNuxtRouteMiddleware(async (to, from) => {
>   const app = useNuxtApp();
>   const user = await useDiscordUser(app.$pinia);
> 
>   if (!user.user) {
>     console.log('User not logged in');
>     return navigateTo('/');
>   }
> });
> ```

In my actual code if the user is not logged in I have to send the user to an external api for login so I need navigateTo for that

**Comment by manniL** [comment]
@typhoon11 Yes, that's fine. But before, you called `navigateTo` in both cases, if the user exists and not. in the default case (logged-in), you should not ☺️

**Comment by typhoon11** [comment]
> @typhoon11 Yes, that's fine. But before, you called `navigateTo` in both cases, if the user exists and not. in the default case (logged-in), you should not ☺️

Nope it didn't fixed on doing refresh the data becomes null my code:
![image](https://user-images.githubusercontent.com/66431066/210221252-8ff14aa0-2a96-479a-8903-d91cf3e7946f.png)

**Comment by manniL** [comment]
You don't even need the `else` and return there.

Be aware that the middleware is executed on server on the first request (and no `window` will be available there)

**Comment by typhoon11** [comment]
> You don't even need the `else` and return there.
> 
> Be aware that the middleware is executed on server on the first request (and no `window` will be available there)

Even if I remove the else it's the same, like when I am doing page navigation the pinia data is there and it allows me to open but whenever I press refresh on that page the data is gone

**Comment by typhoon11** [comment]
> You don't even need the `else` and return there.
> 
> Be aware that the middleware is executed on server on the first request (and no `window` will be available there)

I am guessing the pinia code I have written is wrong, can you help me with that?
`export const useDiscordUser = defineStore('discord_user', {
    state: () => {
        return {
            user: null as UserPartial | null
        }
    }, 
    getters: {
        isUserLoaded: (state) => {
            return state.user !== null
        }
    }
})`

**Comment by manniL** [comment]
Doesn't look wrong to me but depends how you fetch the user.
I've [adapted your example](https://stackblitz.com/edit/nuxtframeworkissues8926?file=stores%2Fauth.ts,middleware%2Fauth.ts). When you switch the user as null/actual user, you see the middleware works as expected

**Comment by typhoon11** [comment]
> Doesn't look wrong to me but depends how you fetch the user. I've [adapted your example](https://stackblitz.com/edit/nuxtframeworkissues8926?file=stores%2Fauth.ts,middleware%2Fauth.ts). When you switch the user as null/actual user, you see the middleware works as expected

I am fetching the user details from an external API and that's done in the header component, so when the page loads and the middleware gets initiated the user value becomes null, so I had to save the user details as local storage and keep the pinia data hydrated.

**Comment by manniL** [comment]
> I am fetching the user details from an external API and that's done in the header component, so when the page loads and the middleware gets initiated the user value becomes null, so I had to save the user details as local storage and keep the pinia data hydrated.

The server has no access to localstorage as mentioned above. Instead, you could e.g. use a cookie *or* do the request in the middleware instead?
