### ISSUE TITLE
Hydration completed but contains mismatches when access web via domain

### ISSUE THREAD

**Issue by chaule97** [nuxt/framework#8935]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Using node v18.12.1 on Ubuntu Server.

### Describe the bug

I am deploy my app project, when I access web app via IP, the app worked fined. But when I access web app via domain, I have a error: Hydration completed but contains mismatches. I don't know why
```
Hydration completed but contains mismatches.
    NuxtJS 5
        u
        mount
        mount
        Ak
        <anonymous>
```

**Comment by fabianwohlfart** [comment]
Same problem, different scenario.

## Environment
- Operating System: `Darwin`
- Node Version:     `v18.10.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

## Description 
With 2 pages after `generate` the other page always loads the index page.

## Reproduction
https://github.com/fabianwohlfart/test__nuxt-3-hydration
`generate` -> `preview`

**Comment by danielroe** [comment]
There is currently a bug with `nuxi preview` for generated sites that results in `index.html` always being used to render the site. (This will not occur when you deploy it.)

Let's track in https://github.com/nuxt/framework/issues/6226.
