### ISSUE TITLE
head.addEntry is not a function

### ISSUE THREAD

**Issue by tomleo** [nuxt/framework#8936]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.3.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Followed the installation guide at https://v3.nuxtjs.org/getting-started/installation

1. `npx nuxi init nuxt-app`
2. `code nuxt-app`
3. `npm install`
4. `npm run dev -- -o`

### Describe the bug

`npm run dev` fails out the box with rc13

### Additional context

Seems to also be an issue on linux per https://github.com/nuxt/framework/issues/8929

### Logs

```shell
Nuxi 3.0.0-rc.13                                                             11:59:43
Nuxt 3.0.0-rc.13 with Nitro 0.6.1                                            11:59:43
                                                                             11:59:44
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.88.134:3000/

ℹ Vite client warmed up in 298ms                                             11:59:44
✔ Nitro built in 195 ms                                                nitro 11:59:45
[Vue warn]: Unhandled error during execution of setup function 
  at <ErrorDev statusCode=500 statusMessage="Internal Server Error" description="head.addEntry is not a function"  ... >
[nuxt] [request error] [unhandled] [500] head.addEntry is not a function
  at ./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8  
  at fn (./node_modules/nuxt/dist/app/nuxt.mjs:148:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:49:19)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:150:23)  
  at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:94:29)  
  at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:104:11)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)  
  at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
[Vue warn]: Unhandled error during execution of setup function 
  at <ErrorDev statusCode=500 statusMessage="" description="head.addEntry is not a function"  ... >
```

**Comment by gangsthub** [comment]
Same on a Mac with rc13 and rc12.

Same on the starter template in:
- Codesandbox: https://codesandbox.io/s/sharp-shtern-om6sgk?file=/package.json
- Stackblitz: https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz?file=README.md

**Comment by gangsthub** [comment]
I think it would be solved by changing

https://github.com/nuxt/framework/blob/7677eec372198bbd7b0c9e57577ad081c7be6fcd/packages/nuxt/src/head/runtime/lib/vueuse-head.plugin.ts#L12

for:

```diff
- head.addEntry(appHead, { resolved: true })
+ head.push(appHead, { resolved: true })
```

Reference: https://unhead.harlanzw.com/api/core/create-head#types

Also here:
https://github.com/nuxt/framework/blob/7677eec372198bbd7b0c9e57577ad081c7be6fcd/packages/nuxt/src/head/runtime/lib/vueuse-head.plugin.ts#L41


```diff
- head.addEntry(_meta, options)
+ head.push(_meta, options)
```

But I haven't tested it thoroughly 🙏🏽

**Comment by HochinChan** [comment]
same problem on rc13

**Comment by minhtu6825** [comment]
I experienced the similar issues, however I discovered that everything was OK once I stopped changing the file "package-lock.json." 
[package-lock-old.txt](https://github.com/nuxt/framework/files/9995620/package-lock-old.txt)
[package-lock-new.txt](https://github.com/nuxt/framework/files/9995621/package-lock-new.txt)

**Comment by AlexBa** [comment]
same problem with rc13 (Mac OS)

**Comment by makkarpov** [comment]
**package.json**:
```
 "@vueuse/head": "1.0.0-rc.14"
```

works for me. Currently it installs just `1.0.0`, and it seems to be causing that issue.

**Comment by afflexux** [comment]
This is what worked for me.
https://github.com/vueuse/head/issues/163#issuecomment-1312557451

**Comment by harlan-zw** [comment]
Oops sorry guys, fix will be out in shortly

**Comment by malgamves** [comment]
Thanks for communicating on the fix! ran a new project on rc13 and it wouldn't start because of this.

**Comment by harlan-zw** [comment]
Should be now fixed. 

If not, try deleting your lock file and `node_modules` and re-install, it should install version 1.0.2 of @vueuse/head which has the fix for this error.

This was entirely my fault, didn't realize bumping a v1 major would update the Nuxt dependency :clown_face: Sorry about that

**Comment by AlexBa** [comment]
For me it's working again!

**Comment by manniL** [comment]
Thanks @harlan-zw ☺️
