### ISSUE TITLE
Nested Layouts ? like layout: (h, page) => h(Layout, () => child), 

### ISSUE THREAD

**Issue by Aksoom-Hussain** [nuxt/framework#8950]
### Discussed in https://github.com/nuxt/framework/discussions/5177

<div type='discussions-op-text'>

<sup>Originally posted by **bloor** May 27, 2022</sup>
I have my main layout (header, body[content] , footer)
And then I`m trying to make a sub-layout for the account-user pages, that has a sidebar-menu
![image](https://user-images.githubusercontent.com/1420653/170740651-3af94ef9-5f38-497c-9339-2a9896ed20c9.png)

```
user/account
user/settings
user/billing
etc
```

How I implemented my nested Layout:
![image](https://user-images.githubusercontent.com/1420653/170740569-1a10a496-7619-46f7-9950-f25948293e53.png)

The issue I face is:
Whenever I switch between a `default-layout path/page` .. to a `user-layout path/page` .. the whole page is re-rendered.
The SPA fluidity breaks for some reason. **I'm considering using a Component instead of the `user-layout`.**

So am I doing something wrong when doing nested layouts ?
Nuxt v3.0.0-rc.3 (latest)

Here's the LIVE DEMO:
https://d1map.netlify.app/
```
test-user: antonebogdan@gmail.com
pass: asdasd123
```
When you commute between `features` , `platforms`, `about` everything is fluid, when you go to `account` it breaks.</div>

**Comment by fosterdouglas** [comment]
I'm having this same issue with nesting layouts.

**Comment by Aksoom-Hussain** [comment]
https://nuxt.com/docs/guide/directory-structure/pages#nested-routes 

found solution by using the parent page with child by insert the <NuxtPage> component inside pages/parent.vue:
pages/parent.vue
