### ISSUE TITLE
page prefetch extra resource that use from other pages (middleware, layouts)

### ISSUE THREAD

**Issue by annndddy** [nuxt/framework#8995]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@1.22.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/annndddy/test2

yarn run build
yarn run preview
visit http://localhost:3000/

### Describe the bug

![prefetch](https://user-images.githubusercontent.com/66762687/201815923-b18415f9-652d-48ea-97f6-1d4f6bf085fc.PNG)
when visit the index page, the middleware and layouts used by other page (admin.vue, which is not prefetched) is prefetched

### Additional context

tried to add below render options to nuxt.config.ts but not works

 render: {
    resourceHints: false,
    bundleRenderer: {
      shouldPrefetch: () => {
        return false
      }
    }
  }

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/6638.
