### ISSUE TITLE
useFetch amazing behavior, change innerText

### ISSUE THREAD

**Issue by RezaErfani67** [nuxt/framework#8998]
### Environment

rc-13
node 18

### Reproduction

i have paginate component...
```javascript
<paginate v-model="page" :page-range="limit" :page-count="pages" :click-handler="getAllItems" prev-text="Prev" next-text="Next" container-class="pagination" page-class="page-item"> </paginate>
```

```javascript
async function getAllItems() {
    let response = await myfetch('/store/storeCourses', {
            method: 'GET',
            query:{
                page:page.value ,
                storeCourseGroup:storeCourseGroup.value,
                limit:limit.value
            }
        });
        
    if (response.data)
        list.value = response.data.docs;
    pages.value = response.data.pages;
}
const myfetch = async (url,options,emits) => { 

    const { data, pending, error, refresh } = await useFetch(url, {
      key : hash(['api-fetch', url, options]),
      baseURL: useRuntimeConfig().API_URL, 
      initialCache: false,
      headers: new Headers({  'authorization': (process.client)?localStorage.getItem("token"):''}),
      ...options,
    onResponse ({ response }) {
    return response._data
    },
    onResponseError ({ response }) {
    return response._data
    }
    });
    const resData = data.value;
    return resData;
 
  }

```

### Describe the bug

on page load it shows  { 2 } instead of { Next }
![image](https://user-images.githubusercontent.com/24381986/201845264-d7fa469f-67bf-4821-87c7-a629a74640ac.png)

but if i go to other page and come back to home site, it shows correctly
![image](https://user-images.githubusercontent.com/24381986/201845426-f5e7dce6-a442-49ed-a7f0-54f2e7f2f19f.png)

**Comment by RezaErfani67** [comment]
if i put <paginate> tag in  <client-only> it works good!
what is its reasons?

**Comment by manniL** [comment]
This is most likely a hydration error because the state on the server (without authorization header) is different from the one on the client (with authorization header).

You should see something like "hydration mismatch" in the console.

[Further read](https://blog.lichter.io/posts/vue-hydration-error/)
