### ISSUE TITLE
route.params is undefined when navigating between pages

### ISSUE THREAD

**Issue by u007** [nuxt/framework#9004]
### Environment

Nuxi 3.0.0-rc.13                                                                                                                                  17:31:32
RootDir: /Users/james/www/aaa                                                                                                                     17:31:32
Nuxt project info: (copied to clipboard)                                                                                                          17:31:32

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `pnpm@7.16.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/u007/nuxt-params

### Describe the bug

when i navigate to: 
```
http://localhost:3000/hi/abcme
```
it works.

but if I navigate from http://localhost:3000. and navigate to /hi/abcme by clicking on the link,
the name is undefined

**Comment by manniL** [comment]
`$route` is automatically available in the template. Don't provide it via `const $route = useRoute()` and the examples work as expected.

**Comment by u007** [comment]
oh i just watch $route.params without defining it?

**Comment by u007** [comment]
if i tried to use in script, I get undefined $route.

<img width="289" alt="Screenshot 2022-11-15 at 5 55 44 PM" src="https://user-images.githubusercontent.com/388813/201889869-8b560531-e662-4567-9ab1-9d04207a73e5.png">

if I useRoute, I get this bug

**Comment by manniL** [comment]
Then use a different name, e.g. `const route = useRoute()` 😋

**Comment by u007** [comment]
i use another name and get that bug

**Comment by manniL** [comment]
Then please share a reproduction. In [this updated StackBlitz](https://stackblitz.com/edit/nuxtframeworkissues9004?file=pages%2Fhi2%2F[name].vue,pages%2Fhi%2F[name]%2Findex.vue,app.vue), the problem is gone.

All I did:

1. `app.vue` - use `NuxtPage` instead of `RouterView`
2. Page components - use `route` instead of `$route`.

**Comment by u007** [comment]
thank you, NuxtPage solved it

**Comment by u007** [comment]
i also face some inconsistencies in my other repository, but realised rc13 fixed it.

**Comment by manniL** [comment]
No problem @u007 ☺️
