### ISSUE TITLE
`utils/` are not being auto-imported

### ISSUE THREAD

**Issue by ashish141199** [nuxt/framework#9005]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Create a file named `general.ts` in `utils/` directory.
2. Not being auto-imported for usage in components. 

### Describe the bug

Auto-import is enabled for `utils/` directory - as mentioned in the documentation: https://v3.nuxtjs.org/guide/directory-structure/utils . Still, it isn't working. Please let me know where am I going wrong.

**Comment by pi0** [comment]
Hi. This feature is only available for RC.14 (unreleased). You can try it with nuxt edge https://v3.nuxtjs.org/guide/going-further/edge-channel
