### ISSUE TITLE
nuxt rc.15 troubles 

### ISSUE THREAD

**Issue by Maxp777** [nuxt/framework#9039]
### Environment

Nuxi 3.0.0-rc.15-27809445.55c9deb                                                                                                                           11:02:06
Nuxt 3.0.0-rc.15-27809445.55c9deb with Nitro 1.0.0-27809308.dc3383b  

### Reproduction

old project worked with rc.13. with rc.14 and  rc.15 not

https://github.com/Maxp777/nuxt4

### Describe the bug

- ERROR  [unhandledRejection] EMFILE: too many open files, watch '/home/user/Project/nuxt3/store/user.store.ts'  at FSWatcher.<computed> (node:internal/fs/watchers:244:19)

-  Cannot start nuxt:  (0 , _nuxt.defineNuxtConfig) is not a function

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by Maxp777** [comment]
@danielroe hmm with code that i attached here is not reproduced, but other erro remain
> Cannot start nuxt:  (0 , _nuxt.defineNuxtConfig) is not a function

**Comment by danielroe** [comment]
That's a breaking change in rc14 - you should either not import it or import from `nuxt/config`

**Comment by Maxp777** [comment]
With nuxt rc.14 i not see that error, I think

**Comment by zuramai** [comment]
Hi @Maxp777, how did you fix it? Because I had the same error since I upgraded the Nuxt version

**Comment by Maxp777** [comment]
@zuramai what error:
- with nux config, when import it from nuxt/config as Daniel roe say
- with too many open file, when try  `sudo  unlim -n 2048`
