### ISSUE TITLE
You should use slots with <ContentRenderer> https://nuxt.com/guide/going-further/runtime-config 

### ISSUE THREAD

**Issue by gustawdaniel** [nuxt/framework#9047]
### Environment

On your website:

https://nuxt.com/docs/getting-started/configuration#runtimeconfig-vs-appconfig

there is link to:

https://nuxt.com/guide/going-further/runtime-config

that shows

```
{
  "message": "You should use slots with <ContentRenderer>",
  "value": {
    "_path": "/guide/going-further/runtime-config",
    "layout": "default"
  },
  "excerpt": false,
  "tag": "div"
}
```

instead of docs

### Reproduction

check

https://nuxt.com/guide/going-further/runtime-config

### Describe the bug

I expected to see more docs about runtime-config

**Comment by gustawdaniel** [comment]
this page works:

https://nuxt.com/docs/guide/going-further/runtime-config/

but this

https://nuxt.com/guide/going-further/runtime-config

no

**Comment by gustawdaniel** [comment]
I wanted to fix it so on page

https://nuxt.com/docs/getting-started/configuration#runtimeconfig-vs-appconfig

clicked "edit on github", and was redirected on

https://github.com/nuxt/framework/edit/main/docs/1.content/1.getting-started/3.configuration.md

then seen:

> The 'nuxt/framework' repository doesn't contain the 'docs/1.content/1.getting-started/3.configuration.md' path in 'main'.

**Comment by chz** [comment]
Also "[https://nuxt.com/bridge/overview](https://nuxt.com/bridge/overview)" shows

@pi0

**Comment by Triloworld** [comment]
This will hurt in long run: 
https://nuxt.com/robots.txt
https://nuxt.com/sitemap.xml

One page is missing:
https://nuxt.com/docs/guide/directory-structure/app.config

Nice website btw :)

**Comment by shintaii** [comment]
MIgration from 2 to 3 pages is also broken with same error:

https://nuxt.com/migration/overview

**Comment by Atinux** [comment]
Fixed in next deploy (might take 10 minutes), in the meantime: https://framework-9q7jx3swq-nuxt-js.vercel.app/
