### ISSUE TITLE
[3.0.0-rc.14] Pinia is not working with rc.14

### ISSUE THREAD

**Issue by maxtomczyk** [nuxt/framework#9052]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.4.0`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@3.2.0`
- Builder:          `vite`
- User Config:      `sourcemap`, `imports`, `experimental`, `css`, `modules`, `app`, `typescript`, `nitro`, `buildModules`, `build`, `plugins`, `vite`, `runtimeConfig`, `routeRules`
- Runtime Modules:  `normalizedModule()`, `normalizedModule()`, `normalizedModule()`
- Build Modules:    `@pinia/nuxt@0.4.3`

### Reproduction

no reproduction yet

### Describe the bug

After upgrading to rc.14 (with rc.13 everything was ok) pinia in our project is not working. Trying to access any page that uses pinia throws error:
```
[🍍]: getActivePinia was called with no active Pinia. Did you forget to install pinia?
const pinia = createPinia()
app.use(pinia)
This will fail in production.
at Module.useStore (./node_modules/pinia/dist/pinia.mjs:1696:19)
at __vite_ssr_exports__.default (./composables/use-cookie-store-watcher/index.ts:12:45)
at setup (./layouts/default.vue:41:34)
```

Also this can be found in server logs:
```
[Vue warn]: injection "Symbol(pinia)" not found.                                                                                                                                                                                    12:36:42
[Vue warn]: Unhandled error during execution of setup function                                                                                                                                                                      12:36:42
  at <Default > // this is default layout probably
[Vue warn]: injection "Symbol(pinia)" not found.                                                                                                                                                                                    12:36:42
[Vue warn]: Unhandled error during execution of setup function                                                                                                                                                                      12:36:42
  at <Szukaj > // this is page name
```

I already tried with newest versions of @pinia/nuxt (0.4.3) and pinia (2.0.23) packages but it's still not working.

**Comment by pnzz7** [comment]
i have the same issue 👀

**Comment by pnzz7** [comment]
it seems like putting `pinia/nuxt@0.4.3` from `buildModules` to `modules` fixed it for me

**Comment by Intevel** [comment]
> it seems like putting `@pinia/nuxt` from `buildModules` to `modules` fixed it for me

`buildModules` was deprecated many releases ago.

**Comment by maxtomczyk** [comment]
> > it seems like putting `@pinia/nuxt` from `buildModules` to `modules` fixed it for me
> 
> `buildModules` was deprecated many releases ago.

Exactly, just opened this issue to write about it

**Comment by Jozaguts** [comment]
Same error, and when I try to deploy as a static site I got this: 
` ERROR  [🍍]: getActivePinia was called with no active Pinia. Did you forget to install 
pinia?
        const pinia = createPinia()
        app.use(pinia)
This will fail in production.
`
