### ISSUE TITLE
error in the documentation search bar.

### ISSUE THREAD

**Issue by andrenunes01** [nuxt/framework#9077]
### Environment

- Nuxt Version:     `3.0.0-rc.14`

### Reproduction

Survey link: https://nuxt.com/guide/directory-structure/components/#components-directory
Correct page: https://nuxt.com/docs/guide/directory-structure/components/#components-directory

### Describe the bug

When I search with DocSearch in the official documentation, the link is incorrect.

**Comment by vanling** [comment]
Yeah links of search results are missing /docs/ at the start

**Comment by danielroe** [comment]
This should now be resolved.
