### ISSUE TITLE
Migration guide for Nuxt 2 -> 3 is 404

### ISSUE THREAD

**Issue by yacoob** [nuxt/framework#9078]
### Environment

n/a

### Reproduction

n/a

### Describe the bug

https://nuxt.com/docs/getting-started/upgrade links to https://nuxt.com/docs/migration/overview - which is currently 404.

**Comment by dargmuesli** [comment]
Well not really for me. Opening https://nuxt.com/docs/migration/overview redirects me to https://nuxt.com/migration/overview, which gives a 404 :thinking:
