### ISSUE TITLE
Upgrade from v13 Blew Up

### ISSUE THREAD

**Issue by misterproton** [nuxt/framework#9088]
### Environment

n/a

### Reproduction

n/a

### Describe the bug

I had a working Nuxt3 project, which had upgraded successfully (and easily) for many of the release candidates.  However, something that was published very recently has crushed my app.

It's more than just the Nuxt itself though, even if keep it at v13 and simply remove node_modules then "npm install" it seems there have been some major scope issues introduced whereby variables defined in script setup are undefined when referenced from computed, which was working fine before.  Even the CSS is totally different.

I saw a new Vite was released yesterday.  Only a minor version upgrade, but could that be it?

Right now I am stuck with the node_modules and version 13.

**Comment by chrisnaadhi** [comment]
got the same result when trying to upgrade nuxt, even tried to use any methods :
- Upgrade methods in the web `npx nuxi upgrade`
- Upgrade methods from the past release candidate : `npx nuxi@latest upgrade --force`
- Delete node_modules and manually change the deps to `^3.0.0`

The result is now config file can't read the defineNuxtConfig :
![image](https://user-images.githubusercontent.com/29543851/202348557-1e2568ad-2533-4470-b206-50f27f4202ac.png)
