### ISSUE TITLE
Vite dev proxy doesn't work after upgrade to v3.0.0

### ISSUE THREAD

**Issue by ppodds** [nuxt/framework#9098]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.16.1`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

`nuxt.config.ts`

```typescript
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  vite: {
    server: {
      proxy: {
        "/api": {
          target: "https://www.google.com/",
          changeOrigin: true,
        }
      }
    }
  }
})
```

### Describe the bug

Vite dev server proxy doesn't work, but it works correctly in v3.0.0-rc.8.

### Additional context

After testing multiple versions of nuxt, I found this bug was introduced after rc.12.
It might be related to #7989 or the route rules update. I hope it is useful to you.

**Comment by ppodds** [comment]
Nuxt rewrite request url like this:

`/api` => `/__url/api`

Vite server can't handle `/__url` prefix automatically, so the proxy setting not match.

## Workaround

```typescript
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  vite: {
    server: {
      proxy: {
        "/__url/api": {
          target: "https://www.google.com/",
          changeOrigin: true,
        }
      }
    }
  }
})
```

**Comment by ninebolt6** [comment]
use `nitro.devProxy` instead. https://nitro.unjs.io/config#devproxy

https://github.com/nuxt/framework/issues/8303#issuecomment-1307246514
