### ISSUE TITLE
Algolia searches in the documentation lead to 404 error pages

### ISSUE THREAD

**Issue by nicolaspayot** [nuxt/framework#9101]
### Environment

https://nuxt.com/docs/

### Reproduction

Go to https://nuxt.com/docs/getting-started/introduction for example, and perform a search from the top bar. Any result from the dropdown leads to a 404 page.

### Describe the bug

Algolia searches from the top bar within https://nuxt.com/docs/ lead to 404 error pages.

https://user-images.githubusercontent.com/463319/202392560-61b4c680-08bc-45c5-b5ed-c7c2881502c8.mov

**Comment by danielroe** [comment]
This should now be resolved.

**Comment by nicolaspayot** [comment]
It is! Thanks so much
