### ISSUE TITLE
Custom useFetch hook in component and child component with condition on pending causes infinite fetching loop

### ISSUE THREAD

**Issue by Feelixe-tin** [nuxt/framework#9122]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `modules`, `css`, `build`, `vite`, `devServer`
- Runtime Modules:  `@nuxtjs/supabase@0.2.5`, `@vueuse/nuxt@9.5.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ioxz7i

1. Open your browser's console. (Will not be visible in the server-side console)
2. Click on "refresh" to refresh the useFetch hook.
3. Look in the console. `FetchComponent` is rendered over and over again.

### Describe the bug

When defining a custom hook in composable like:
```
export function useSomething() {
  return useFetch(`/api/something`, { key: 'something' });
}
```

If you then use that hook in a component and in one of its child components while conditioning the rendering of the child component on `!pending` of the hook. Then the request will execute over and over again.

This can be resolved by conditionally rendering on `data !== null ` instead. But I would expect that conditally rendering on `data !== null` and `!error && !pending` should have the same result.

**Comment by danielroe** [comment]
`useFetch` shares state by key (but at the moment, it will always refetch the data as we removed the `initialCache` feature - cc: @pi0). So when you start rendering the child component, pending is momentarily true, which stops rendering the child component. Then the response finishes, pending becomes true in the parent component and the child component is triggered. etc. etc.

I think in your particular case you should not conditionally render the child based on _pending_ but on whether there is data or not.
