### ISSUE TITLE
useFetch sends double Request in nested component ( Under some conditions )

### ISSUE THREAD

**Issue by rohrig** [nuxt/framework#9139]
### Environment

Ubuntu LTS
Node LTS
Yarn 
Nuxt 3.0 Stable (but the behavior was the same before upgrading)

### Reproduction

I made a quick unlisted video to show what I'm seeing : https://youtu.be/HLVo4bKutDc

here is the commit where I swapped useFetch() for $fetch which solved my problem 
[commit changing to $fetch](https://github.com/jurassicjs/nuxt3-fullstack-tutorial/commit/6285fd209826c9b706e907da51e92c62203c97a0#diff-cf165891da9c918972cea091125793e19b138cd81b25bde2b3236f604d7fd8ddR18)

I wasn't able to reproduce the error on stackblitz. 

### Describe the bug

useFetch() sends doubled, but swapping useFetch() for $fetch does not. 
 
changing useFetch() to $fetch caused to duplicate sending to stop. 

### Additional context

The component where the-double-sending-useFetch() is located is nested, and the parent component also contains a useFetch() 

Possibly related: https://github.com/nuxt/framework/issues/3168

**Comment by danielroe** [comment]
Yes, you should only use `useFetch` within setup directly, not within a helper function later on. `$fetch` is correct.
