### ISSUE TITLE
Nuxt Website Search Shows White Text on White Background

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/framework#9145]
### Environment

n/a

### Reproduction

Go to nuxt.com
Set theme to dark
Search for something

### Describe the bug

When using the dark theme, you can't see what you are typing when you search because it uses white text on a white background.

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/2112282/202603628-d596de1e-2b6c-49ef-87cc-824b50035684.png">

**Comment by Intevel** [comment]
Actually I don't have this:
![image](https://user-images.githubusercontent.com/59223342/202657014-5e80b7c1-e20f-4fe2-9aab-d699615fa323.png)

**Comment by hecktarzuli** [comment]
Mine is fixed now too
