### ISSUE TITLE
on edge channel now is installed rc.0

### ISSUE THREAD

**Issue by Maxp777** [nuxt/framework#9159]
### Environment

npm
nide 16
nuxt 3 rc 15 edge

### Reproduction

Nuxi 3.0.1-rc.0-27810184.d991a55                                                                                                                             13:17:44
Nuxt 3.0.1-rc.0-27810184.d991a55 with Nitro 1.0.0-27809308.dc3383b                                                                                           

### Describe the bug

Not update `npx nuxt@latest upgrade --force` and `npx nuxi upgrade -f`.
So that `"nuxt": "npm:nuxt3@latest"` is not valid any more?
Now only `"nuxt": "^3.0.0"`?

**Comment by danielroe** [comment]
It's the rc-edge version of 3.0.1, so `npm:nuxt3@latest` is still correct if you want edge releases.

**Comment by Maxp777** [comment]
@danielroe  But error 
> SyntaxError: The requested module 'node_modules/nitropack/node_modules/h3/dist/index.mjs' does not provide an Buexport named 'useBody'

**Comment by danielroe** [comment]
`useBody` has been renamed to `readBody`

**Comment by samlinck** [comment]
> `useBody` has been renamed to `readBody`

@danielroe Hi I searched for this error for days.. Where can I find all this changes?

**Comment by danielroe** [comment]
It has been deprecated for some time but if you are upgrading to 3.0.0 the best thing is to check `~/.nuxt/imports.d.ts` to see what is exposed from each helper package.
