### ISSUE TITLE
TailwindCSS doesn't seem to work with Nuxt v.3.0.0

### ISSUE THREAD

**Issue by Aybee5** [nuxt/framework#9163]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-nlp6fz?file=app.vue

### Describe the bug

I don't know if this is the right place to ask this, but I have been trying to use tailwind with nuxt 3.0.0 but it doesn't seem to work.

I have tried both using the `nuxt/tailwind` and the `tailwindcss` package but doesn't work, hence why I suspect this has to do with nuxt.

### Additional context

![image](https://user-images.githubusercontent.com/42099896/202711910-60cd5015-c9d7-405e-bc57-0b707e82f2f2.png)
The applied class appears as a plain text

_No response_

**Comment by danielroe** [comment]
you need to add the module to your nuxt.config

**Comment by Aybee5** [comment]
Yes, thank you. 
It is working now, what triggers me to open the issue, is that after upgrading to v.3.0.0 from rc11 my tailwind stopped working(I was using the tailwindcss package), I guess I will just use the module since that works
