### ISSUE TITLE
Template refs in .client components not available at `onMounted()`

### ISSUE THREAD

**Issue by fkammer** [nuxt/framework#9185]
### Environment

```
❯ npx nuxi info
Nuxi 3.0.0

RootDir: /home/projects/github-dpyktf-owfxvw
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-dpyktf-owfxvw?file=app.vue

### Describe the bug

[Template refs](https://vuejs.org/guide/essentials/template-refs.html) are not available on [client-side only components](https://nuxt.com/docs/guide/directory-structure/components#client-components) defined in `.client` files.

It works as expected on components not having `.client` in their file name. It makes no difference if SSR is enabled or not. As long as a components file name ends with `.client` the ref is not set as expected on `onMounted`.

### Logs

Console logs from the linked StackBlitz example:

```
{component: 'FocusInput', ref: input}
{component: 'FocusInputBroken', ref: null}
```

**Comment by huang-julien** [comment]
Hi 👋 thanks for reporting this ! 
Currently .client components await for the component to be mounted before rendering it so you have to `await nextTick()` .
it's like this : 

````
- vue render .server or div
-- vue mount your component and call `onMounte()` hook, but the template defined in your component in not rendered yet
-- next tick
- vue render your component
````

changing your `onMounted` to: 
````ts
onMounted(async () => {
    await nextTick()
  console.log({
    component: 'FocusInputBroken',
    ref: input.value,
  });
  // input.value?.focus();
  refValue.value = input.value ? 'HTMLInputElement' : 'null';
});
````
should work. 

@danielroe I'm not sure if we can delay the `onMounted()` hook of a `.client` component at runtime. What do you think about adding a `await nextTick()` in all `.client` `onMounted()` through a plugin ?

**Comment by fkammer** [comment]
Hi, thanks for having a look at this! Awaiting the next tick works well.

I would expect `onMounted()` to behave the same on a `.client` component as it does on a "regular" component. If that would cause other side-effects, we should at least add a warning to the documentation, that a `.client` component isn't rendered when `onMounted()` is called and mention the `await nextTick()` trick.

**Comment by huang-julien** [comment]
I agree if we don't add it automatically through a unplugin. :+1: I'd just like to have a confirmation from the team :heart:

**Comment by danielroe** [comment]
I think I agree - let's document this rather than transforming `onMounted` hooks.
