### ISSUE TITLE
ERROR  Cannot start nuxt:  Cannot destructure property 'Server' of '_engineIo.default' as it is undefined. 

### ISSUE THREAD

**Issue by Kazion500** [nuxt/framework#9199]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Create a module for socket.io and import it into the nuxt.config.ts file.

![image](https://user-images.githubusercontent.com/64147010/202905134-f2b47bc6-d4c3-4dae-81a8-654c40d007f6.png)

![image](https://user-images.githubusercontent.com/64147010/202905159-fee32965-33d1-44af-b0a7-7f827da94ea4.png)

### Describe the bug

When trying to import module with socket configured, the nuxt server crashes and throw the error  ""ERROR  Cannot start nuxt:  Cannot destructure property 'Server' of '_engineIo.default' as it is undefined. "". 

![image](https://user-images.githubusercontent.com/64147010/202905219-eac5ba40-0c25-412b-9684-2e85328bdc44.png)

**Comment by sharkfin009** [comment]
hmm, have the same thing happening with @nuxt/image module

**Comment by SuleymanQ** [comment]
I have the same problem.

**Comment by SuleymanQ** [comment]
https://stackblitz.com/edit/github-ahlfuf?file=modules/socket.ts more detailed

**Comment by manniL** [comment]
Let's track this in https://github.com/nuxt/framework/issues/8703

**Comment by SuleymanQ** [comment]
ok. thanks
