### ISSUE TITLE
Docs: code blocks aren't displayed correctly on modules documentations

### ISSUE THREAD

**Issue by damevin** [nuxt/framework#9219]
### Environment

This issue relates to documentation

### Reproduction

This issue relates to documentation

### Describe the bug

On documentation module, when i am on a module page : I have a problem when i want to see code blocks. Colors rendering is weird.

For exemple here on [nuxt/webvitals module docs](https://nuxt.com/modules/web-vitals)
![image](https://user-images.githubusercontent.com/72107589/202988804-6c15e9a2-941c-42c7-b270-44e8f33d180e.png)

### Additional context

My configuration: 
- Mozilla Firefox v 107.0 (64 bits)
- Macbook Pro M2 2022

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/9141.
