### ISSUE TITLE
Project dependency cannot be installed

### ISSUE THREAD

**Issue by message163** [nuxt/framework#9223]
### Environment

nuxt": "3.0.0"
node 14.18.2
npx 6.14.15

### Reproduction

npx nuxi init nuxt3-app

pnpm i  

### Describe the bug

<img width="585" alt="image" src="https://user-images.githubusercontent.com/32630999/203006066-7f19faa5-d9c9-4fe4-a5e7-f39b07fd021f.png">

**Comment by harlan-zw** [comment]
Works fine for me with `pnpm@7.14.0`.

Not sure why it would throw this error, possibly pnpm is using an offline cache on your system? Not sure the best way to test that.

Worth checking if other package managers work, if so then you should try upgrading your pnpm or using it `--shamefully-hoist`

**Comment by message163** [comment]
pnpm   Just upgrade to the latest version
