### ISSUE TITLE
Hydration text content mismatch 

### ISSUE THREAD

**Issue by mkierdev** [nuxt/framework#9250]
### Environment

- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`

### Reproduction

```js
<script setup lang="ts">
const randomNumber: number = Math.floor(Math.random() * 1000000000);
</script>

<template>
  <p>{{ randomNumber }}</p>
</template>
```

### Describe the bug

Hydration text content mismatch in <p>:
- Client: 807910065
- Server: 36586442 

### Additional context

During development we had to implement number generator in order to create _unique_ ID (reproduction is simplified, but it still shows the same error). However, every time we use it, we get server/client mismatch as described above.

Component is always used as single-root element and it's wrapped in a div.

Shouldn't already generated number on the server-side be directly provided into client-side? Is this expected behavior?
If so, how can we make sure that randomly generated content remain the same both on server and client? I do not believe that generating those numbers only on clientside (onMounted) is a way to go..

**Comment by manniL** [comment]
Yes, this is *expected* because you do not transfer state from server to client. Thus, generation will happen on both sides and create a mismatch.

Instead, create your id's on the server and pass them, e.g. by using `useState`.

**Comment by mkierdev** [comment]
@manniL I understand, however in my case it does not seem to provide a solution.

If I follow the example with useState, I will get the same uid in every component. What I'm trying to achieve is to get different uid in each component (I use multiple instances of the same component on one page).
```
const uid = useState("counter", () => Math.round(Math.random() * 1000)); // the result will be the same across all components that are using it
```

**Comment by danielroe** [comment]
You might find https://github.com/danielroe/vue-bind-once useful in this situation.

**Comment by mkierdev** [comment]
Thanks for your link, however I need to access that variable in <script setup> as well.
I do not remember this kind of problem in nuxt 2. We used uuid library and it was working fine.

ID generation has so much use-cases and I just cannot believe there isn't any reasonable way to to it
