### ISSUE TITLE
Cannot pass props to NuxtLayout

### ISSUE THREAD

**Issue by v-romanyuk** [nuxt/framework#9253]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-dskmfq?file=pages%2Findex.vue

### Describe the bug

Passing props to NuxtLayout stopped working after rc-13. Browser shows 2 warnings

- Extraneous non-props attributes were passed to component but could not be automatically inherited because component renders fragment or text root nodes

- Missing required prop

**Comment by v-romanyuk** [comment]
Well it worked until rc.13, and I have couple of projects that use that behavior. So now I have to either stay on rc.12 or change a lot of logic. I would really appreciate if you can roll it back. Thanks!😊

**Comment by kstraszewski** [comment]
Same here :)

**Comment by manniL** [comment]
> Same here :)

Please don't post "+1" or "Same problem".
Instead, upvote issues or comments.

**Comment by xjccc** [comment]
> This was not an explicitly supported behaviour but I think it makes sense. 👍

i wish in layout component can control the common . it could be easier(like load-more event\common components on content)
could u support it also thanks(pass props\events or use defineExpose?)

**Comment by quintus-luis** [comment]
Unfortunately, it looks like it's broken again with the latest Edge version (in the meantime, after merging it worked):

Here is the [reproduction](https://stackblitz.com/edit/nuxt-starter-79smx8?file=layouts%2Fdefault.vue)

Unfortunately, I can't determine what broke this feature again :( Can someone have a look?

**Comment by danielroe** [comment]
It seems that your stackblitz isn't using the edge release - examine the lockfile and you will see:

```json
