### ISSUE TITLE
routeRules static with NuxtLink not working correctly

### ISSUE THREAD

**Issue by AscaL** [nuxt/framework#9257]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.14.2`
- Builder:          `vite`
- User Config:      `routeRules`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/AscaL/nuxt-rendering/tree/28e735a75b3cb0e564e513cd237d42767d0ac779 (not working)

https://github.com/AscaL/nuxt-rendering/tree/84d2ddce6560e899f709308a6460954a3a502d7a (working)

### Describe the bug

I have the root page set up with 3 `NuxtLink` that point to `/static`, `/swr` and `/ssr` with the following rules:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/8880943/203352125-619b4ae0-cf3e-4238-80b8-204f63e7fac7.png">

on each page i `await useFetch('https://worldtimeapi.org/api/ip')` to get a time.
 
after uploading to netlify, the `/static` page shows the correct (cached version) on refresh, but entering it via a `NuxtLink` from the root `/`, runs the fetch getting me my current time. If i then refresh the page i get the correct cached version.
By replacing the `NuxtLink` with an `<a>` it works as intended.

**Comment by ndragun92** [comment]
The same is happening to me. Not sure if that is intended or not. But feels weird to get new data on nuxt link navigation and then on refresh get cached one. Could confuse the user in case he navigates on the site and then refreshes a page...
In that case, he could see two different contents.

**Comment by idflood** [comment]
I got the same behaviour with a full static website. On navigation there are backend calls but on page refresh it correctly load the payload.

Also the payload get preloaded but are not really used when clicking on NuxtLinks.

I created an issue on nuxt-graphql-client but maybe this is more of a nuxt issue: https://github.com/Diizzayy/nuxt-graphql-client/discussions/276

**Comment by danielroe** [comment]
You need to have `experimental.payloadExtraction` enabled if you are running `nuxt build`.

**Comment by idflood** [comment]
My issue was related to inconsistent slug handling in my catchall page, and probably different and/or wrong response from the graphql backend.

After making sure the "full slug" has leading and trailing slashes the static site generation is working as expected.
