### ISSUE TITLE
[GitHub Pages Deployment] Renaming a repository can result in a broken deploy

### ISSUE THREAD

**Issue by larbish** [nuxt/framework#9280]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.0.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `css`, `strapi`, `ui`, `colorMode`
- Runtime Modules:  `@vueuse/nuxt@9.5.0`, `@nuxthq/ui@0.1.8`, `@nuxtjs/strapi@1.6.3`, `@nuxt/content@2.2.2`, `@nuxthq/studio@0.1.5`, `nuxt-plausible@0.1.2`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Fork this repo: https://github.com/larbish/content-wind-studio-local
2. It will automatically deploy on `https://{{github-owner}}.github.io/content-wind-studio-local/`
3. Rename your repository
4. `https://{{github-owner}}.github.io/{{renamed-name}}/` is broken because of the `NUXT_APP_BASE_URL` set in the [ci](https://github.com/larbish/content-wind-studio-local/blob/main/.github/workflows/pages.yml#L62)
5. Need to trigger the build workflow manually to fix it.

### Describe the bug

When deploying a Nuxt project on github pages on the default github url (`https://{{github-owner}}.github.io/{{repo-name}}/`, we need to set `NUXT_APP_BASE_URL` as env var to fix routing navigation.

Because of it when we are renaming the project, navigation is broken after github has been deployed. We need to trigger the build workflow manually to fix it. 
I don't know if it's fixable it but I think we should at least display a warning in the generate log or a note in the documentation concerning github pages deployment. 

I can help to update documentation if needed. 

### Logs

```shell
yarn generate
  shell: /usr/bin/bash -e {0}
  env:
    NUXT_PUBLIC_STUDIO_API_URL: http://localhost:1337
    NUXT_APP_BASE_URL: /content-wind-studio-local
```

**Comment by Atinux** [comment]
Redeploying is necessary for static websites with SSR otherwise it demands tricky logic in runtime.
