### ISSUE TITLE
Hydration node mismatch when Router Middleware redirect in process.client

### ISSUE THREAD

**Issue by TutorFx** [nuxt/framework#9283]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `css`, `build`, `modules`
- Runtime Modules:  `@nuxt/image-edge@1.0.0-27809804.194d2d6`, `@nuxtjs/tailwindcss@6.1.3`, `@pinia/nuxt@0.4.5`
- Build Modules:    `-`

### Reproduction

```js
export default defineNuxtRouteMiddleware(async (to, from) => {
  if (process.client) return navigateTo('/any-existing-route');
});
```

### Describe the bug

When we paste directly the url to the browser we got a "Hydration node mismatch" error

### Additional context

This only happens if you are using the client-side to navigateTo() and access the middleware-protected URL manually

### Logs

```shell
runtime-core.esm-bundler.js:40 [Vue warn]: Hydration node mismatch:
- Client vnode: span 
- Server rendered DOM: "bbbbb" (text) 
  at <ClientOnly placeholder="Buscando usuario..." > 
  at <Usuario onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/usuario" routeProps= {Component: {…}, route: {…}} pageKey="/usuario"  ... > 
  at <Anonymous > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <Default > 
  at <Anonymous key="default" name="default" hasTransition=false > 
  at <Anonymous > 
  at <Anonymous> 
  at <App key=1 > 
  at <NuxtRoot>
```

**Comment by ExEr7um** [comment]
Isn't this an expected behavior?

When you open page by pasting url, it renders on the server, and it doesn't execute code in `if` with `process.client`.

But then it tries to hydrate that page on a client. It executes that code and navigates to a different page, so you get two completely different pages, one from server, and one from client. And because of it you get hydration mismatch error.

**Comment by TutorFx** [comment]
Thank you for the rich example @ExEr7um !
