### ISSUE TITLE
Returned values get mutated for useState() composable

### ISSUE THREAD

**Issue by OyewoleOyedeji** [nuxt/framework#9284]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@vueuse/nuxt@9.6.0`
- Build Modules:    `-`
------------------------------

### Reproduction

<https://stackblitz.com/edit/vueuse-usestorage-bug?file=app.vue>

### Describe the bug

I have this returned from storage object

```json
{
    useLocation: true,
    useSuggestions: false,
}
```
When I use `useState()` to store the object, I get a mutated object, like the one below

```json
{
    useLocation: true,
    useSuggestions: true,
}
```

### Additional context

But when you pass the object as a prop it doesn't get mutated

**Comment by danielroe** [comment]
This doesn't seem to be a bug to me - rather a consequence of using the same object in two different contexts. If you need to, you can clone it, e.g.:

```js
const settingsModified = useState('settings', () => ({ ...settings.value }));
```

**Comment by OyewoleOyedeji** [comment]
Thanks
