### ISSUE TITLE
vercel + cloudflare with proxy   .well-known route problem

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#9293]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.17.0`
- Builder:          `vite`
- User Config:      `alias`, `nitro`, `modules`, `extends`, `github`, `colorMode`, `plausible`, `huntersofbook`, `i18n`
- Runtime Modules:  `@nuxtlabs/github-module@1.5.3`, `@huntersofbook/plausible-nuxt@0.5.2`, `nuxt-icon@0.1.7`, `@huntersofbook/core-nuxt@0.4.1`, `@nuxtjs/i18n@8.0.0-beta.4`, `@nuxtjs/tailwindcss@6.1.3`, `@vueuse/motion/nuxt@2.0.0-beta.25`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/huntersofbook/huntersofbook/tree/main/docs

### Describe the bug

url: https://opensource.huntersofbook.com/.well-known/acme-challenge

vercel docs: https://vercel.com/guides/using-cloudflare-with-vercel#cloudflare-access

article: https://levelup.gitconnected.com/how-to-set-up-cloudflare-with-zeit-93daa7d45dd

![image](https://user-images.githubusercontent.com/38668796/203726162-c63b50c2-3705-4da1-bf3a-1930da930144.png)

**Comment by danielroe** [comment]
What do you feel the bug is?

**Comment by productdevbook** [comment]
It seems that it should show the result returned directly from the server in that url. But it seems like nuxt is getting in the way.

**Comment by danielroe** [comment]
what server?

**Comment by productdevbook** [comment]
vercel

**Comment by danielroe** [comment]
I don't believe this is a nuxt issue but more likely to do with how you've configured cloudflare. I have had no issues setting up nuxt with this combination (cloudflare cname -> vercel).

**Comment by danielroe** [comment]
I'm going to close this as an issue but feel free to ask questions in discord or open a discussion.

**Comment by productdevbook** [comment]
https://levelup.gitconnected.com/how-to-set-up-cloudflare-with-zeit-93daa7d45dd

like here

You can turn off proxy(is work). But I need to process proxy open writes. 

![image](https://user-images.githubusercontent.com/38668796/203771892-aea73384-38ae-44bf-aefb-eb0b30cf07a1.png)

**Comment by danielroe** [comment]
I don't believe that is the issue, or something Nuxt could fix. if vercel really is requesting that url then it needs to be intercepted _before_ it hits the nuxt endpoint. there's no way for nuxt to handle that as part of a dynamic handshake for issuing a certificate.

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/203773159-353d0dd2-aec9-433a-b142-f5397774410e.png)

**Comment by danielroe** [comment]
If you are using Access, then you _must_ use cloudflare's proxy. That would be true regardless of using nuxt or not.

**Comment by productdevbook** [comment]
okay thats true, iam cloudflare pages same used :D and cloudflare pages delete website and fixed
