### ISSUE TITLE
docs: plugins/ directory are auto-registered? why 

### ISSUE THREAD

**Issue by icai** [nuxt/framework#9295]
### Environment

no

### Reproduction

All plugins in your plugins/ directory are auto-registered, so you should not add them to your nuxt.config separately.
But in [Nuxt Configuration Reference](https://nuxt.com/docs/api/configuration/nuxt-config#nuxt-configuration-reference),  all demo is in the `plugins` directory.

----

<img width="807" alt="image" src="https://user-images.githubusercontent.com/1061012/203744560-b5bd01b3-46e6-4273-85cc-8c1dabadf35b.png">

https://nuxt.com/docs/api/configuration/nuxt-config#plugins-1

### Describe the bug

documentation is unclear

**Comment by danielroe** [comment]
You're quite right, that's unhelpful. (It's a hold-over from Nuxt 2 docs, and I'd welcome a PR to fix it.)

**Comment by pi0** [comment]
`plugins` config is still supported in Nuxt 3. It is useful for custom order and also adding plugins not in `plugins/` directory needed to be added. Also good to point that all plugins are deduplicated by their src path. If listing into config and auto registering, they won't be added twice and custom order is preserved.

I think we can clarify the docs that plugins are auto-registered from plugins/ directory and do not need to be listed unless custom options/order is required.

**Comment by manniL** [comment]
Note: Custom order could be achieved by prefixing them with numbers.

**Comment by danielroe** [comment]
> Custom order could be achieved by prefixing them with numbers.

Yes, that's what I'd recommend.

**Comment by pi0** [comment]
This option shall keep documented and supported for Nuxt 3. PR to improve auto-scanning behavior is welcome (or we can simply point the docs to the [plugins directory](https://nuxt.com/docs/guide/directory-structure/plugins).

**Comment by danielroe** [comment]
Just to be clear, I'm not suggesting we get rid of the docs, just update them to a more helpful example as the issue suggested. 😊

**Comment by BetonZM** [comment]
I have opened PR.  https://github.com/nuxt/framework/pull/9815

It would be wise to remove "Edit on Github" button on configuration page as redirects to non-existing Github path due to auto-generated content...
