### ISSUE TITLE
"Cannot use 'in' operator to search for 'catch' in undefined" when using pinia in the plugin

### ISSUE THREAD

**Issue by vedmant** [nuxt/framework#9310]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `runtimeConfig`
- Runtime Modules:  `@pinia/nuxt@0.4.5`, `@nuxtjs/tailwindcss@6.1.3`
- Build Modules:    `-`

### Reproduction

```ts
// plugins/auth.ts
import { defineNuxtPlugin, useCookie } from '#imports'
import { useAuthStore } from '~/store/auth'

export default defineNuxtPlugin(async (nuxtApp) => {
  if (process.server) {
    const token = useCookie('sso-auth').value
    if (token) {
      const authStore = useAuthStore(nuxtApp.$pinia)
      await authStore.setToken(token)
    }
  }
})
```

```ts
// store/auth.ts
import { defineStore } from 'pinia'

export const useAuthStore = defineStore('auth', {
  state: () => ({
    token: null,
    user: null,
  }),

  actions: {
    setToken (data) {
      this.token = data.token
      this.user = data.user
      if (useRuntimeConfig().isDev) {
        useCookie('sso-auth', { path: '/', maxAge: 60 * 60 * 24 * 30 }).value = data
      }
    },

    logout () {
      this.token = null
      this.user = null
      if (useRuntimeConfig().isDev) {
        useCookie('sso-auth').value = null
      }
    },
  },
})

```

### Describe the bug

I'm trying to set authentication token from cookies to pinia in the plugin, but getting error: "Cannot use 'in' operator to search for 'catch' in undefined"

### Logs

TypeError: Cannot use 'in' operator to search for 'catch' in undefined                                                                                                        12:00:25
    at Module.executeAsync (file:///Users/me/project/node_modules/unctx/dist/index.mjs:93:15)
    at /Users/me/project/plugins/auth.ts:12:53
    at fn (/Users/me/project/node_modules/nuxt/dist/app/nuxt.mjs:151:27)
    at Object.callAsync (file:///Users/me/project/node_modules/unctx/dist/index.mjs:49:19)
    at callWithNuxt (/Users/me/project/node_modules/nuxt/dist/app/nuxt.mjs:153:23)
    at applyPlugin (/Users/me/project/node_modules/nuxt/dist/app/nuxt.mjs:97:29)
    at Module.applyPlugins (/Users/me/project/node_modules/nuxt/dist/app/nuxt.mjs:107:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createNuxtAppServer (/Users/me/project/node_modules/nuxt/dist/app/entry.mjs:29:7)
    at async default (file:///Users/me/project/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

I suppose that `useRuntimeConfig().isDev` should be `useRuntimeConfig().public.isDev` or similar. The stacktrace points to this line (line 3 of it) 😋

**Comment by vedmant** [comment]
@manniL No, it's not the case, I was able to console.log() after `if (useRuntimeConfig().isDev) {` block, and it doesn't throw there. Also `useRuntimeConfig()` doesn't need `.public` to access public variables. In my case that variable available on both `useRuntimeConfig().isDev` and `useRuntimeConfig().public.isDev`. In any case that would just return undefined and not throw error.

Here I added reproduction
https://stackblitz.com/edit/github-q4opji?file=plugins%2Fauth.ts,app.vue,nuxt.config.ts

**Comment by manniL** [comment]
You are right. Problem is likely related to https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529 again. if you remove the `await` in `plugin/auth.ts`, things work smooth and the StackTrace points to the nuxt part of

```
const nuxtAppInstance = nuxtAppCtx.tryUse();
  if (!nuxtAppInstance) {
 ```

**Comment by manniL** [comment]
As a workaround, you can move that logic into your `App.vue`.

**Comment by manniL** [comment]
**Update**: Because your action is not async (I assume it is in the real setup), this error appears as the function is not returning nothing.

In this exact example, `await` is not necessary and can be removed, then the issue won't pop up at all.

**Comment by vedmant** [comment]
@manniL Thanks, but using `await` with anything should not throw exception, this are valid and should not cause any errors:
await 5
await 'A'
await {}
await null
await undefined 

I'm using await when calling actions by convenience in case actions may be refactored with async. Also the error itself is so cryptic, I'd never guest from the error that await could cause this.

**Comment by manniL** [comment]
> @manniL Thanks, but using `await` with anything should not throw exception

Generally it should not, because it is legal in JS.

Reason here is that the code transformation to keep Nuxt's context (https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529, ) will cause it to fail.

I'll send in a PR that will fix it so you can keep `async` there.
