### ISSUE TITLE
[error] Cannot destructure property 'nuxt' of 'this' as it is undefined.

### ISSUE THREAD

**Issue by procrates** [nuxt/framework#9314]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `runtimeConfig`, `supabase`, `modules`, `postcss`, `nitro`, `build`, `vite`, `alias`
- Runtime Modules:  `@nuxtjs/supabase@0.2.6`, `@formkit/nuxt@1.0.0-beta.12`, `@nuxt/image-edge@1.0.0-27821548.ab054e4`
- Build Modules:    `-`

### Reproduction

Reproduction not possible

### Describe the bug

Working fine on dev. When deploying to vercel it fails:

[error] Cannot destructure property 'nuxt' of 'this' as it is undefined.

Might be related to this: [https://github.com/nuxt/framework/issues/9115](https://github.com/nuxt/framework/issues/9115)

### Additional context

Been running fine on RC.13. Fails on RC.14 and Nuxt latest.

### Logs

```shell
Vercel CLI 28.5.6
Injecting Nuxt.js analytics plugin "@nuxtjs/web-vitals" to `/vercel/path0/.nuxtrc`
Adding "@nuxtjs/web-vitals" to `package.json` "dependencies"
Installing dependencies...
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
warning " > @fullcalendar/vue3@5.11.3" has unmet peer dependency "vue@^3.0.11".
warning "@formkit/nuxt > @formkit/vue@1.0.0-beta.12" has unmet peer dependency "vue@^3.2.1".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 19.91s.
Running "yarn run build"
yarn run v1.22.17
$ nuxt build
[log] Nuxi 3.0.0
[log] Nuxt 3.0.0 with Nitro 1.0.0
[error] Cannot destructure property 'nuxt' of 'this' as it is undefined.
  at webVitalsModule (node_modules/@nuxtjs/web-vitals/dist/index.js:47:11)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1825:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:1857:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:493:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:34:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1
```

**Comment by harlan-zw** [comment]
This is a vercel bug, they shouldn't activate this module for >= RC 14 

You'll need to disable the performance analytics or deploy without using the vercel CLI

**Comment by oikewll** [comment]
> This is a vercel bug, they shouldn't activate this module for >= RC 14
> 
> You'll need to disable the performance analytics or deploy without using the vercel CLI
> 
> Alternatively, the web vitals module needs to be updated

I tried deploying on my local computer and got the same error

**Comment by nor1c** [comment]
same thing happened to me after installed `@nuxt/image` module 🤔

![image](https://user-images.githubusercontent.com/7555972/203899487-91163e74-d080-4251-b0e3-9e0a010bb234.png)

**Comment by procrates** [comment]
> This is a vercel bug, they shouldn't activate this module for >= RC 14
> 
> You'll need to disable the performance analytics or deploy without using the vercel CLI
> 
> Alternatively, the web vitals module needs to be updated

So this caused the error... Thanks! I was confused because builds work with it on pre Nuxt stable.

And also i did update @nuxtjs/web-vitals, didnt work. 

Solution: **Disable analytics in vercel and other hosts that injects "@nuxtjs/web-vitals" into package.js**
