### ISSUE TITLE
uesHead is not woking properly with reactive  data.

### ISSUE THREAD

**Issue by 72pranjal** [nuxt/framework#9320]
### Environment

i can use  npx nuxi for creating a nuxt app.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-g7zex2?file=plugins/SetHead.ts

Using This link you can reproduce the bug.

### Describe the bug

**UserHead** is not working properly with reactive data when rapping in defineNuxtPlugin.
when we use useHead under the rapping of defineNuxtPlugin then its reactiveness is destroyed, it could not update the title in head.

**In this link you  can see**
https://stackblitz.com/edit/nuxt-starter-g7zex2?file=plugins/SetHead.ts

**Comment by bot08** [comment]
Try this: `title: () => title.value`

**Comment by 72pranjal** [comment]
wrong
