### ISSUE TITLE
[Nuxt 3] Nuxt instance unavailable in async actions during SSR

### ISSUE THREAD

**Issue by LudoFont** [nuxt/framework#9329]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Create new project and add a new plugin  (/plugins/init.server.js) with the following code : 

```
export default defineNuxtPlugin(async () => {
  await test();
})

const test = async () => {
  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("done!"), 1000)
  });
  const nuxtApp1 = useNuxtApp();
  await promise;
  const nuxtApp2 = useNuxtApp();
  return Promise.resolve();
};
```

### Describe the bug

An error is triggered on the second call of the useNuxtApp, because it is after an await call.

```
[nuxt] [request error] [unhandled] [500] nuxt instance unavailable                                                                                                                      
  at Module.useNuxtApp (./node_modules/nuxt/dist/app/nuxt.mjs:165:13)  
  at test (./plugins/init.server.js:16:42)  
  at async ./plugins/init.server.js:7:73  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:53:16)  
  at async applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:97:23)  
  at async Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:107:5)  
  at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:29:7)  
  at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)  
  at async ./.nuxt/dev/index.mjs:630:21
```

### Additional context

I encountered this bug while migrating my website from Nuxt 2 to Nuxt 3.
The same bug happen in a asyncData method of a page component, like this : 

app.vue : 
```
<script>
import { test } from "@/utils/test"

export default defineNuxtComponent({
  async asyncData() {
    await test();
    return {};
  }
});
</script>
<template>
  <div>
    <NuxtWelcome />
  </div>
</template>
```

utils/test.js :
```
export const test = async () => {
  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("done!"), 1000)
  });
  const nuxtApp1 = useNuxtApp();
  await promise;
  const nuxtApp2 = useNuxtApp();
  return Promise.resolve();
}
```

**Comment by mmis1000** [comment]
It works as intended.
Hooks after await works only at top level of setup script at first place.

And it works only because vue injected some magic into the compiled template script.
Your custom function don't have that, thus it don't work.

[sfc playground, look at the js tab of compile result](https://sfc.vuejs.org/#eNo9ULtuwzAM/BVWixOgttDVsA1069itixbXoRMF1gMiHQ+G/r2UU2Tj3fFIHnf1GWPzWFG1qqMp2chAyGscjLcuhsSwQ8IZMswpOKiktTJ+3EbL4HGDb2Et4SlBP0A6nc/GT8ETg6Mr9MV6qr5wWQL8hLRc3ipp6PRzk+wQwOjiMjIKAuhuH8O+H+acOy3oYK2PK8OjduGCS2+U6EaJ1OmXW72r58G1G2Nzp+Al0l7c5l8go1o4mMJJkIKNujFHarWmeSqPuFMT0lVL1aTVs3XYILn6N4WNMMlgo8qIbHxW+Q8vDG0P)
