### ISSUE TITLE
Something like Astro.js

### ISSUE THREAD

**Issue by papadi166** [nuxt/framework#9336]
### Describe the feature

Could you make an feature like Astro.js has? I dont't know how performance compares between nuxt3 and Astro, but I heard Astro is the fastest, cause it doesn't load js. I would like to see rendering mode like that if it's possible.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by mctweb** [comment]
There is a plugin in development:
https://github.com/danielroe/nuxt-zero-js

**Comment by danielroe** [comment]
This is already possible in Nuxt itself:

```js
export default defineNuxtConfig({
  experimental: {
    noScripts: true
  },
})
```
