### ISSUE TITLE
cannot install with "frozen-lockfile" because pnpm-lock.yaml 

### ISSUE THREAD

**Issue by productdevbook** [nuxt/framework#9349]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.17.0`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `build`, `unocss`, `i18n`, `typescript`, `colorMode`, `vite`, `tailwindcss`, `plausible`
- Runtime Modules:  `@vueuse/nuxt@9.6.0`, `@nuxtjs/tailwindcss@6.1.3`, `@pinia/nuxt@0.4.5`, `@unocss/nuxt@0.46.5`, `@nuxtjs/i18n@8.0.0-beta.4`, `@nuxtjs/color-mode@3.2.0`, `@huntersofbook/plausible-nuxt@0.5.2`, `@nuxtjs/partytown@1.2.2`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/productdevbook/productdevbook.com/pull/69

### Describe the bug

![image](https://user-images.githubusercontent.com/38668796/204120521-ff563bca-52b4-4091-8798-c343f6a879ed.png)

**Comment by ExEr7um** [comment]
I think it happens because of
```sh
Adding "@nuxtjs/web-vitals" to `package.json` "dependencies"
```

Don’t know why does it happen, maybe because of Vercel, but you can try installing `@nuxtjs/web-vitals` manually.

**Comment by danielroe** [comment]
This is a Vercel + pnpm issue rather than a nuxt one.

**Comment by uma-uc** [comment]
so - is there a resolution/workaround please?

**Comment by danielroe** [comment]
Install it in your own package.json.
