### ISSUE TITLE
please support plain handler function like nuxt2

### ISSUE THREAD

**Issue by icai** [nuxt/framework#9352]
### Describe the feature

please support plain handler function like nuxt2

```
    // Normalize plain function
    if (typeof middleware === 'function') {
      middleware = { handle: middleware }
    }

```

https://github.com/nuxt/nuxt.js/blob/40521d0a0d2b3f9308e0c2df033f21b3ede76c7e/packages/server/src/server.js#L201

just say, nuxt support the following config for serverHandlers. That would be  better for old project upgrade to nuxt 3. for old project, I really don't want to change the service layer code. in Nuxt 2 support cjs __dirName based on `requireModule` import the server layer.

**example module code in nuxt 2**
```

  let app
  
  const handle = (req, res, next) => {
    app.handle(req, res, next)
  }

  const requireModule = this.nuxt.resolver.requireModule


  app = express()
  if (isRequire(setupPath)) {
    requireModule(setupPath)(app)
  } else {
    app.use((req, res, next) => {
      requireModule(routesPath)(req, res, next)
    })
  }

  this.addServerMiddleware(handle)

```

but in Nuxt 3. all  handler should be  the string path,  that is  not very friendly for cjs  server layer.

**example module midlleware for server layer**
```

import path from 'path'

import dotenv from 'dotenv'
import * as middlewares from './middleware/index'
import * as routes from './routes/index'

const configdir = path.resolve(__dirname, '../config')

const configPath = path.resolve(configdir, `.env.${process.env.NODE_ENV}`)

dotenv.config({ path: configPath })

export default (app) => {
  middlewares.configure(app)
  routes.init(app)
  // development error handler
  // will print stacktrace
  if (app.get('env') === 'development') {
    app.use(function (err, req, res, next) {
      res.status(err.status || 500)
    })
  }

  // no stacktraces leaked to user
  app.use(function (err, req, res, next) {
    res.end('error', err)
  })
}

```
just support the nuxt config api like the following:

```
serverHandlers: [
  { middleware: true, handler: (event)=> {} }, // h3
 { middleware: true, handler: (req, res, next)=> {} }  // express ?
]

```

https://github.com/unjs/nitro/issues/700

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
For module-injected dev-only handlers, you can use `devHandlers`. For production builds, you _must_ pass a string because the source for the handler needs to be included in the build, and your `nuxt.config` will not be.
