### ISSUE TITLE
`useHead` meta type issue

### ISSUE THREAD

**Issue by huang-julien** [nuxt/framework#9364]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

tested with a fresh project and with the playground of the repository

### Reproduction

````ts
useHead({
  meta: [
    {
      description: 'test'
    }
  ]
})
````

### Describe the bug

There seems to be a type issue (upstream ?) with `useHead`. 
This log is showing up on VsCode :  
`Type '{ description: string; }' is not assignable to type 'Meta<{} | undefined>'.`

**Comment by pascalwengerter** [comment]
Just tried locally and I think what you're trying to fit into a `<meta>` tag just doesn't fit into the `<meta>`'s API (hence the type error - my IDE suggests
```
Type '{ description: string; }' is not assignable to type '{ [x: `data-${string}`]: Stringable | undefined; content?: Stringable | (Stringable | undefined)[] | undefined; id?: string | undefined; charset?: { ...; } | "utf-8" | undefined; ... 13 more ...; textContent?: undefined; } | { ...; } | undefined'.
```

and I don't see "description" mentioned anywhere [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta). If you put a valid option (e.g. `{ name: "robots", content: "noindex" }` into the meta array it should run fine :)
