### ISSUE TITLE
Unable to get started with tailwind css - Cannot destructure property 'nuxt' of 'this' as it is undefined

### ISSUE THREAD

**Issue by prabhatsharma** [nuxt/framework#9373]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

npx create-nuxt-app w1

create-nuxt-app v5.0.0
✨  Generating Nuxt.js project in w1
? Project name: w1
? Programming language: TypeScript
? Package manager: Npm
? UI framework: Tailwind CSS
? Template engine: HTML
? Nuxt.js modules: Axios - Promise based HTTP client
? Linting tools: ESLint
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Static (Static/Jamstack hosting)
? Development tools: (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Continuous integration: None
? Version control system: Git

### Describe the bug

Cannot start when trying to create a project with tailwind css

### Additional context

Issue does not happen with other UI frameworks

### Logs

```shell
(base) prabhatsharma@paradise2 ~/projects/nuxtjs1 % cd w1
(base) prabhatsharma@paradise2 ~/projects/nuxtjs1/w1 % npm run dev

> w1@1.0.0 dev
> nuxt

ℹ Using default Tailwind CSS file from runtime/tailwind.css                                                                                       nuxt:tailwindcss 03:14:51

 FATAL  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                                                           03:14:51

  at postcss8Module (node_modules/@nuxt/postcss8/dist/index.js:15:10)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async setup (node_modules/@nuxtjs/tailwindcss/dist/module.mjs:186:7)
  at async ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)


   ╭─────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                 │
   │   ✖ Nuxt Fatal Error                                                            │
   │                                                                                 │
   │   TypeError: Cannot destructure property 'nuxt' of 'this' as it is undefined.   │
   │                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by manniL** [comment]
**Important**: If you want to use Nuxt 3, please use `npx nuxi init` and *not* `create-nuxt-app`.

Regarding the issue you see, let's track in https://github.com/nuxt/framework/issues/9115
