### ISSUE TITLE
New context for each route change

### ISSUE THREAD

**Issue by breizhwave** [nuxt/framework#9380]
### Describe the feature

Hi, I would like to reset all nuxt data on each route change, just as if I was loading full client side in SSG context : need to have the setup event run on each page . I have tried using a watcher on route change combined with clearNuxtData but, still no coming back to setup hook, and cleaer all async calls ... any idea ? thks

```

watch(() => route.name, () => {
  console.log(` welcome ${route.name}`);
  clearNuxtData ()
  waveChoixStore.$reset()
  waveResultStore.$reset()
  waveAppStore.$reset();waveAppStore.fetchWaveTabs();
});
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by breizhwave** [comment]
Found : https://stackoverflow.com/questions/58284001/how-can-i-refresh-the-whole-page-on-link-visit-in-nuxtjs

replace nuxtlink by a href

**Comment by manniL** [comment]
Be aware that you lose most SPA capabilities then 👀

**Comment by breizhwave** [comment]
@manniL Thks I m' well aware that there's a lot of potential there on SPA with nuxt but I appreciate it for its compatibility with the good old web html paradigm

**Comment by danielroe** [comment]
You can also set the `external` prop in a `<NuxtLink>` to force a hard reload.
