### ISSUE TITLE
Can't write an efficient http to https redirect

### ISSUE THREAD

**Issue by Joaojack** [nuxt/framework#9388]
### Discussed in https://github.com/nuxt/framework/discussions/9387

<div type='discussions-op-text'>

<sup>Originally posted by **Joaojack** November 28, 2022</sup>
Hello,
I really need your help here. My nuxt 3 website is hosted on heroku, and my SSL certs are ok for my domain in https://domain.com and https://www.domain.com.
But when typing www.domain.com or domain.com, the page is not securized.

In order to try  a http to https redirect I've tried three things :

**The ssl redirect way (version 1)**
After installing redirect-ssl, I try in nuxt config : 
```
import redirectSSL from 'redirect-ssl'
export default ({
(...)
serverMiddleware: [redirectSSL],
(...)
})
```
-> doesn't work

**The ssl redirect way (version2)**
```
const isProd = process.env.NODE_ENV === 'production'od)
const redirectMiddleware = (req: IncomingMessage, res: ServerResponse<IncomingMessage>, next: Function) => {
  const ua = req.headers['user-agent'] || ''
const enabled = isProd && /Mozilla|Chrome|Firefox|Safari/.test(ua)
  if (enabled) {
  return enabled ? redirectSSL(req, res, next) : next()
  }
}
import redirectSSL from 'redirect-ssl'
export default ({
(...)
serverMiddleware: [redirectMiddleware]
(...)
})
```
--> doesn't work

**The ssl redirect way (version3)**
```
import redirectSSL from 'redirect-ssl'
export default ({
(...)
serverMiddleware: redirectSSL.create({enabled: process.env.NODE_ENV === 'production'})],
(...)
})
```
--> doesn't work

** The heroku way**

tried to put this .htaccess file in my root folder : 
```
##Force SSL 

#Normal way (in case you need to deploy to NON-heroku)
RewriteCond %{HTTPS} !=on

#Heroku way
RewriteCond %{HTTP:X-Forwarded-Proto} !https 

#If neither above conditions are met, redirect to https
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# If header is present in the request
RewriteCond %{HTTP:X-Forwarded-Proto} .
```
--> doesn't work

**Solution i made up for a temporary but dirty fix**

Forced a hard redirection in my middleware folder when session token is not detected :
```
export default defineNuxtRouteMiddleware(async (to, from) => {
  const myUser = useUser()
  const tokenCookie= useStatefulCookie('tokenCookie')
  if(tokenCookie.value?.access_token)
  { const authorization_middleware=`Bearer ${tokenCookie.value.access_token}`
    if(myUser.value===false&&tokenCookie.value.access_token){
      const user = await $fetch('/api/something',{method:'POST',body:{authorization: authorization_middleware}})
      myUser.value=user
    }}
  else {
    **return navigateTo('https://foobar/login', {external:true})**
}})```

Can some generous soul please help me ? I can't believe setting this redirect is taking me so many time...
thanks</div>

**Comment by wobsoriano** [comment]
https://github.com/nuxt/framework/discussions/9387

**Comment by wobsoriano** [comment]
https://github.com/nuxt/framework/discussions/9387#discussioncomment-4257340

**Comment by manniL** [comment]
> [#9387 (comment)](https://github.com/nuxt/framework/discussions/9387#discussioncomment-4257340)

Closed in favor of this discussion
