### ISSUE TITLE
Install error nuxt3

### ISSUE THREAD

**Issue by nuwanvc** [nuxt/framework#9394]
### Environment

Windows 11
NODE 18.12.1
VS Code

### Reproduction

Fresh install ( npx nuxi init nuxt-app)

### Describe the bug

Hello, 

When I run the command `npx nuxi init nuxt-app` to install a fresh copy of NUXT.

I get below error.
" /AppData/Local/npm-cache/_npx/a95e0f536cf9a537/node_modules/.bin/nuxi: exec: line 11: node: not found"

### Additional context

I tried clearing the cache.
Installing npm globally
installing npx globally
Switched off the windows firewall.

Nothing worked so far

Thanks.

**Comment by manniL** [comment]
For some reason, `node` cannot be found on your device. Maybe it is not available in your PATH? See eg. [here on SO](https://stackoverflow.com/a/13593981/3975480)

As this is not a nuxt bug, I'm closing here though.
