### ISSUE TITLE
404 NotFound server(SSR) handler

### ISSUE THREAD

**Issue by mhf-ir** [nuxt/framework#9399]
### Discussed in https://github.com/nuxt/framework/discussions/9398

<div type='discussions-op-text'>

<sup>Originally posted by **mhf-ir** November 29, 2022</sup>
Any guide or document for 404 handler on server. on SSR.

```js

// sample of fastify
// https://www.fastify.io/docs/latest/Reference/Server/#setnotfoundhandler

app.setNotFoundHandler(function async (request, reply) {
    const newURL = await httpClient('https://server.tld/api/found-redirect', 'POST', { url: request.url });
    if (newURL) {
      // do redirect
    } else {
      // insert into log system for check later
      // and throw typical 404 response
    }
  });

```

Use case many of 404 URL seen by end user via google search console or another mechanism and with interface user can add it into database for process.

In case of URL of page change by any regex or even slug. better to handle in this layer.</div>

**Comment by manniL** [comment]
Closing here in favor of the linked discussion.
