### ISSUE TITLE
Relative pages

### ISSUE THREAD

**Issue by uktamka** [nuxt/framework#9400]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-hhhuas?file=pages%2Fposts%2F[[id]].vue,app.vue

### Describe the bug

**/posts/ Doesn't open index.vue** 
![image](https://user-images.githubusercontent.com/39945349/204545762-abdc09c4-a4cf-4b27-b92a-29bbef89b821.png)

**Comment by danielroe** [comment]
This is `vue-router` behaviour - would you open an issue there?

**Comment by danielroe** [comment]
https://paths.esm.dev/?p=AAMsIPQg4AAM9hfgQHoEXAmw-IEBBRQYIFc.&t=/posts#
