### ISSUE TITLE
Can't set head using options api

### ISSUE THREAD

**Issue by RifatMahmudno-1** [nuxt/framework#9417]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.1.1`
- Builder:          `vite`
- User Config:      `app`, `postcss`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

`<script>
export default{
  head:{
    title:"my website"
  }}
</script>`

### Describe the bug

Can't set head using options api

**Comment by danielroe** [comment]
You need to use `defineNuxtComponent` for head options API support.

**Comment by RifatMahmudno-1** [comment]
Can I set title for each page using options api??

**Comment by danielroe** [comment]
I'm not sure what you're asking.

**Comment by RifatMahmudno-1** [comment]
In pages folder I've an about page. So, I want to title the page "About"
How can I do that using options api??

<script>
	export default {
		head: {
				title: 'about'
		}
	}
</script>

**Comment by danielroe** [comment]
As I said above, you would use `defineNuxtComponent`.

**Comment by RifatMahmudno-1** [comment]
Thanks a lot
