### ISSUE TITLE
useFetch automatic request after first request

### ISSUE THREAD

**Issue by maximilian-schwarz** [nuxt/framework#9422]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.3`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `postcss`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-wmbccm?file=app.vue

### Describe the bug

I have created a separate component for an input field, which is structured as follows:

```vue components/form/app/TextField.vue
<template>
  <div>
    <label
        v-if="label"
        :for="name"
        class="block text-sm pl-0.5">
      {{ label }}
      <span
          class="text-accent-blue"
          v-if="required">
        *
      </span>
    </label>
    <div
        class="relative mt-1 flex items-center">
      <input
          class="block w-full pl-4 py-3 outline-0 rounded-[4px] border transition-all duration-400 border-gray-300 focus:border-primary-light focus:drop-shadow"
          :type="type"
          :value="modelValue"
          :name="name"
          :id="name"
          :class="{
            'pr-12': prefix,
            'pr-4': !prefix
          }"
          :required="required"
          @input="$emit('update:modelValue', $event.target.value);">
      <div
          v-if="prefix"
          class="absolute inset-y-0 right-[1px] top-[1px] bottom-[1px] flex">
        <span class="inline-flex items-center bg-gray-50 border-l border-gray-300 px-4 text-sm font-medium rounded-tr-[4px] rounded-br-[4px]">
          {{ prefix }}
        </span>
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  name: {
    type: [String],
    required: true
  },
  type: {
    type: [String],
    default: 'text'
  },
  required: {
    type: [Boolean],
    required: false,
    default: false
  },
  label: {
    type: [String, Boolean],
    required: false
  },
  prefix: {
    type: [String, Boolean],
    required: false
  },
  modelValue: {
    type: [String],
    default: ''
  }
})
</script>
```

I then included this in the app.vue. The input field and a button are displayed here. This button has a binding @click="save()" to call the save() function.

```vue app.vue
<template>
  <div>
    <input
      name="email"
      label="Email"
      type="email"
      v-model="form.data.email"
      required
    />

    <button @click="save()">Check</button>
  </div>
</template>

<script setup>
const form = ref({
  data: {
    email: '',
  },
});

const save = async () => {
  const { data, error } = await useFetch('/api/hello', {
    method: 'POST',
    body: form.value.data,
  });

  return true;
};
</script>
```

**Reproduction:**
1. go to https://githubwmbccm-mhyg--3000.local-credentialless.webcontainer.io/ and open the Developer Tools -> Network.
2. next enter a string in the input field. e.g. email@email.de
3. click on the button "Check".

Now you can see that a request is sent to "/api/hello" as expected. Everything is correct and as expected. (see screenshot)
![Bildschirm­foto 2022-11-30 um 14 45 42](https://user-images.githubusercontent.com/63093230/204816307-3e3bcfcb-e343-49b4-ac96-b96688ebe983.png)

**The error:**
If you now click in the input field and add a letter, exactly the same request is automatically sent again without clicking on the "Check" button. A new request is sent for each letter. (see screenshot)
![Bildschirm­foto 2022-11-30 um 14 45 55](https://user-images.githubusercontent.com/63093230/204816355-9fb170c9-73ca-4bc2-ba01-c2ce8f0beaf5.png)

It is noticeable that this behaviour only occurs with a POST request. If you useFetch() with GET, this behaviour does not occur. If you use $fetch instead of useFetch() everything works as expected even with a POST request.

**Comment by thegouge** [comment]
I am also having this issue, and I think it's tied to useFetch watching for updates in the data it's given for the initial request

**Comment by timyourivh** [comment]
I was also experiencing this rather strange behavior when creating an register form.

Here's a GIF to demonstrate what's happening:
![nuxt3-usefetch-issue](https://user-images.githubusercontent.com/60601502/210378240-4c7de9f1-3474-43a5-b72f-128a15689501.gif)
<sup>Repro used above: https://codesandbox.io/s/nuxt3-usefetch-post-issue-7xg9nq?file=/app.vue</sup>

### Docs

After looking into the docs this is actually intended behavior:
https://nuxt.com/docs/api/composables/use-fetch#params

![image](https://user-images.githubusercontent.com/60601502/210378761-90f48263-9fbf-4ab7-af7d-09afb97caed7.png)

### Workaround (omit behavior):

Stringify-ing or spreading the reactive object or ref value works, but kind of defeats the point "body: Request body - automatically stringified (if an object is passed)." mentioned in [params](https://nuxt.com/docs/api/composables/use-fetch#params).

```diff
const response = await useFetch('/api/myendpoint', {
  method: 'POST'
- body: fromData // reactive or ref
+ body: JSON.stringify(formData) // or formData.value if ref
// or
+ body: {...formData} // or formData.value if ref
})
```
