### ISSUE TITLE
Display Vitest output when running `nuxi test`

### ISSUE THREAD

**Issue by Atinux** [nuxt/framework#9434]
Note: you need to run `pnpm build` in order to run the test command in the framework repo

Example with `pnpm nuxi test examples/advanced/testing`:

![CleanShot 2022-11-30 at 16.37.09@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2022_11_30_at_16_37_09_2x_45fe074983.png)

Also, it would be nice to show at the beginning something like:

```bash
ℹ Building Nuxt project...
// ...
ℹ Starting Nuxt server...
Listening http://[::]:64405
ℹ Running tests...
// Vitest output
```

@antfu could you be up to take this task?

**Comment by antfu** [comment]
It's weird. The test actually didn't run at all, the process is terminated before Vitest starts. 

It happened somewhere between these:
https://github.com/nuxt/framework/blob/62bbb9144628a10b0c91f88f580c66a07d108dfd/packages/test-utils/src/nuxt.ts#L55-L64

Investigating deeper
