### ISSUE TITLE
Yarn Dev Error (node_modules/.bin/nuxt: line 12: node: not found)

### ISSUE THREAD

**Issue by nuwanvc** [nuxt/framework#9444]
### Environment

Windows 11
Node 18.12.1
VS Code
Yarn

### Reproduction

Fresh install

### Describe the bug

Hello, 

When I install nuxt and run the development server using "yarn dev"
I get this error every time. 

`node_modules/.bin/nuxt: line 12: node: not found`

Tried several Nodejs versions. 
Still can't find the solution.

Thanks.

**Comment by manniL** [comment]
This looks like `node` is not in your PATH variables. Can you run try running `node -v` in e.g. windows terminal / power shell?

Because it is not a Nuxt issue per sè, I am closing here.

**Comment by nuwanvc** [comment]
@manniL this is the result I got from running node -v
node -v
v18.12.1

I'm new to development. Sorry about the trouble.
Trying to get this work for days. 

Thanks.
