### ISSUE TITLE
[Doc] nuxt.config.ts page 404s on server

### ISSUE THREAD

**Issue by donovanglover** [nuxt/framework#945]
This is a separate issue for the 404 I found after investigating #943.

Currently https://v3.nuxtjs.org/docs/directory-structure/nuxt.config 404s server-side even though Nuxt renders it just fine.

![image](https://user-images.githubusercontent.com/2374245/137132715-cbdaa6b0-a95c-4704-b51c-aac77c1d52d7.png)

![image](https://user-images.githubusercontent.com/2374245/137133281-857a0778-c3d0-464e-8bae-ccacaeca26ae.png)

**Comment by ennioVisco** [comment]
Not sure when this was solved exactly, but this works well now, so the issue can be closed :)

**Comment by pi0** [comment]
This page is still buggy https://v3.nuxtjs.org/api/configuration/nuxt.config

Docus rewrite probably solves it anyway
