### ISSUE TITLE
'this' is undefined when using head as method in nuxt.config.js

### ISSUE THREAD

**Issue by kane-mason** [nuxt/framework#9459]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `-`
- Package Manager:  `npm@8.1.0`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/delicate-sky-y1rb7n?file=/nuxt.config.js

### Describe the bug

In `nuxt.config.js`  we have the option to define the `head` node as a function. 

For my case i am using the `@nuxtjs/i18n` package and attempting apply the following code taken directly from the documentation
```js
export default {
  // ...other Nuxt options...
  head () {
    return this.$nuxtI18nHead({ addSeoAttributes: true })
  }
}
```

All works fine in `ssr:true`, but for `ssr:false` mode `this` is undefined and causes an error

**Comment by Aareksio** [comment]
Hey! This is a repository of Nuxt 3. Nuxt 2 is tracked [here](https://github.com/nuxt/nuxt.js).

I do not know of a reason why the docs suggest using `this` from within `nuxt.config.js`. I do not recall it ever working, but maybe... Anyway, easy fix would be to move the `head()` contents to your layout component.

**Comment by kane-mason** [comment]
Thanks i logged in nuxt 2 repo https://github.com/nuxt/nuxt.js/issues/10843
