### ISSUE TITLE
Plain form parsing not working

### ISSUE THREAD

**Issue by nopeless** [nuxt/framework#9465]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-vzedx2?file=pages%2Findex.vue

### Describe the bug

It shouldn't be this hard to get form data. Also, there seems to be an error in the browser, but I believe that's a separate issue. 

I believe this bug is rather high priority, because I believe Nuxt should work well for people who learn from a plain html and js background. 

The easiest fix for this problem would convert it into a `@submit.prevent` and turn it into a `useFetch` call, but I don't feel like that is a solution

### Additional context

The post request from the browser appears to result in a 404, method not found/not found

This shouldn't be the case if page serving is dealt with like middleware. Apparently, there are many things going on behind the scenes that I currently don't quite realize.

### Logs

```shell
/submit
The body is {}
The params are {}
The readBody is {}
The getQuery is {}
```

**Comment by manniL** [comment]
This [works fine eventually](https://stackblitz.com/edit/nuxtframeworkissues9465?file=server%2Froutes%2Fsubmit.post.ts,pages%2Fsubmit.vue). There were a couple of things:

* Express is not needed, Nitro + h3 will do good
* I've enabled SSR again
* It seems like you cannot use an API route as middleware - Thus I've added a redirect to a "thank you" page
	* This could be added as a separate issue - please feel free to do so! ☺️

**Comment by nopeless** [comment]
So the main issue was that simply processing the `event.node.req.body` altered its contents so that `readBody` doesn't work correctly... what kind of issue even is this issue 😞 

Still, thanks for helping me with this issue. Hope you have a great day
