### ISSUE TITLE
`defineNuxtPlugin` is not defined in plugin context

### ISSUE THREAD

**Issue by mubaidr** [nuxt/framework#9466]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v19.0.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.17.1`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `app`, `imports`, `modules`, `typescript`, `css`, `vite`, `experimental`
- Runtime Modules:  `@vueuse/nuxt@9.6.0`, `@pinia/nuxt@0.4.6`, `nuxt-lodash@2.4.1`, `()`
- Build Modules:    `-`
- pnpm: latest version

### Reproduction

```ts
import vuetify from 'vite-plugin-vuetify'

export default defineNuxtConfig({
  runtimeConfig: {
    // The private keys which are only available server-side
    apiSecret: process.env.NUXT_API_SECRET,
    databaseUrl: process.env.NUXT_DATABASE_URL,
    apiSecretTimeout: process.env.NUXT_API_SECRET_TIMEOUT,
    // Keys within public are also exposed client-side
    public: {
      apiBase: process.env.NUXT_PUBLIC_API_BASE || '/api',
    },
  },
  app: {
    pageTransition: { name: 'page', mode: 'out-in' },
  },
  imports: {
    dirs: [
      './composables/',
      './store/',
    ],
    addons: {
      vueTemplate: true,
    },
    presets: [
      'vue',
      'vue/macros',
      'pinia',
    ],
  },
  modules: [
    '@vueuse/nuxt',
    '@pinia/nuxt',
    'nuxt-lodash',
    // '@nuxt/content',
    // '@nuxt/image-edge',
    async (options, nuxt) => {
      nuxt.hooks.hook('vite:extendConfig', (config) => {
        config.plugins?.push(
          vuetify(),
        )
      })
    },
  ],
  typescript: {
    shim: false,
    typeCheck: true,
  },
  css: [
    '/styles/main.scss',
  ],
  vite: {
    ssr: {
      noExternal: ['vuetify'],
    },
  },
  experimental: {
    reactivityTransform: true,
    inlineSSRStyles: false,
  },
})

```

### Describe the bug

`defineNuxtPlugin` is not defined in plugin context. Seems like auto-imports for `nuxt` are not working. 

```bash
ERROR(vue-tsc)  Parameter 'nuxtApp' implicitly has an 'any' type.
```

![Capture](https://user-images.githubusercontent.com/2222702/205210231-47a6a2ed-cef6-4c6c-9158-1529012f7109.PNG)

### Additional context

- tried cleaning up `pnpm` store and `node_modules`
- could this be related to using some `vite` plugin (in this case `vite-plugin-vuetify`)

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by mubaidr** [comment]
Just to add more information, same thing is working fine on `linux` but issue exists on windows. (Even after re-clone repo, clearing pnpm cache etc)

I am creating a repo with the settings.

**Comment by manniL** [comment]
@mubaidr Thanks for the link! Could you reduce the app to the minimal to reproduce the issue? Else it'll be tough to look for the actual problem ☺️

**Comment by mubaidr** [comment]
I have been trying to fix this issue, and while looking into tsconfig file genrated by `nuxi`

```json
"#app": [
        "../../../H:/ors-beta/application/node_modules/.pnpm/nuxt@3.0.0_pwpk577hwtuwgvziewj6f5zxl4/node_modules/nuxt/dist/app"
      ],
```
But that specific path does not exists on file system. Any guesses?

(I have already tried cleaning node_modules and re-installing)

**Comment by mubaidr** [comment]
Another update, looks like `tsconfig` `path`s are not being identified by the typescript, somehow. 

Relative, Absolute imports are resolved, but the imports using the `paths` (like `#head`, `#app`) are not working. 

Or then `application/node_modules/.pnpm/nuxt@3.0.0_pwpk577hwtuwgvziewj6f5zxl4/node_modules/nuxt/dist/pages/runtime/composables` fails to be resolved. and other `paths` also following the same package.

So maybe `pnpm` is causing some issue?

**Comment by mubaidr** [comment]
I see lot of weird paths in imports typings files, like this: 

```bash
`../../../../../H:/ors-beta/application/node_modules/.pnpm/nuxt@3.0.0_pwpk577hwtuwgvziewj6f5zxl4/node_modules/nuxt/dist/app`
```

Should not this be relative to config file or if absolute then start from root directory?

**Comment by mubaidr** [comment]
So looks like if I enable symlinks `git config --global core.symlinks true` the imports are generated from `node_modules` base path and issue is fixed for now.
