### ISSUE TITLE
NuxtLink or underlying RouterLink renders "text" property on client instead of children

### ISSUE THREAD

**Issue by oliver-heeger** [nuxt/framework#9469]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-c3ahyl?file=app.vue

### Describe the bug

The `<NuxtLink>` or `<RouterLink>` renders its children as expected on Server, but the contents of the `text` property on client hydration. 

```
<NuxtLink to="/" text="this should never been displayed">
  Child
</NuxtLink>
```

### Additional context

This does'nt happen in a Vue Project: 
https://stackblitz.com/edit/vue-gaz9tb?file=src%2FApp.vue

**Comment by oliver-heeger** [comment]
Interesting: Only `<a>`, `<title>` and `script` Elements have a (undocumented) `text` attribute. 
```
document.querySelectorAll('*').forEach((el) => {
  el.text = 'foo'
});
```
Anyway, this does'nt happen in Nuxt2 with CompositionApi or vue.

**Comment by danielroe** [comment]
`<NuxtLink>` doesn't have a `text` prop, so you shouldn't pass it to it.

You can see this isn't just limited to NuxtLink or RouterLink but to any SSR-rendered `<a>` link:

- Nuxt: https://stackblitz.com/edit/nuxt-starter-ccjcvx?file=app.vue
- Vue SSR: https://stackblitz.com/edit/github-egnlta?file=src%2FApp.vue&terminal=dev

If you feel this is a bug, feel free to raise it at https://github.com/vuejs/core.
