### ISSUE TITLE
Installation Failing - Cannot start nuxt:  The requested module '@nuxt/kit' does not provide an export named 'addServerMiddleware'

### ISSUE THREAD

**Issue by rogadev** [nuxt/framework#9479]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.3.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.5`
- Builder:          `vite`
- User Config:      `modules`, `tailwindcss`, `colorMode`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.0-4`, `@nuxtjs/color-mode@3.2.0`  
- Build Modules:    `-`
------------------------------

### Reproduction

Run `npx nuxi init app`

Take everything in `/app`, dump into root.

Run `yarn install`

Run `yarn add -D @nuxtjs/tailwindcss@5.0.0-4 @nuxtjs/color-mode`

In `nuxt.config.ts` update to the following:

```ts
export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss', '@nuxtjs/color-mode'],
  tailwindcss: {
    cssPath: '~/assets/css/tailwind.css',
    configPath: 'tailwind.config.js',
    exposeConfig: false,
    config: {},
    injectPosition: 0,
    viewer: true,
  },
  colorMode: {
    classSuffix: '',
    preference: 'dark',
  },
})
```

Create `assets/css/tailwind.css` in project root.

Add the following to `assets/css/tailwind.css`:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

In root, create `tailwind.config.js`

Add the following to `tailwind.config.js`:

```js
module.exports = {
	darkMode: 'class',
	content: [],
	theme: {
		plugin: [],
	},
}
```

Update `app.vue` to the following:

```html
<template>
  <div>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>
```

Create basic `layouts/default.vue` and 'pages/index.vue`.

Make sure your default layout has a `<slot />`.

Run `yarn dev -o`.

Error:

```
 ERROR  Cannot start nuxt:  The requested module '@nuxt/kit' does not provide an export named 'addServerMiddleware'

  import { defineNuxtModule, resolvePath, resolveAlias, createResolver, requireModule, addTemplate, isNuxt2, installModule, addServerMiddleware } from '@nuxt/kit';
  ^^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'addServerMiddleware'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)      
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async importModuleDynamicallyWrapper (node:internal/vm/module:435:15)     
  at async installModule (/E:/LocalDevelopmentFiles/mapbox-distance-project/node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (/E:/LocalDevelopmentFiles/mapbox-distance-project/node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (/E:/LocalDevelopmentFiles/mapbox-distance-project/node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (/E:/LocalDevelopmentFiles/mapbox-distance-project/node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (/E:/LocalDevelopmentFiles/mapbox-distance-project/node_modules/nuxi/dist/cli.mjs:50:20)
  ```

### Describe the bug

Clean install is throwing this error. Attempted the following Google-search fixes:

---

`npm update @nuxt/kit`

Did not fix.

---

`npx nuxi upgrade --force`

Did not fix.

---

Remove all files.

Retrace steps.

2/2 clean installs failed.

---

**Comment by danielroe** [comment]
It sounds like you have an old module which is using a kit utility that does not exist in Nuxt 3 - `@nuxtjs/tailwindcss` is at least a major version higher than the one you are using, for example.
