### ISSUE TITLE
useAsyncData not cache

### ISSUE THREAD

**Issue by lyoko515** [nuxt/framework#9493]
### Environment

Nuxi 3.0.0                                                                                                                        09:55:06
                                                                                                                                  09:55:07
RootDir: /app                                                                                                                     09:55:07
Nuxt project info:                                                                                                                09:55:07

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `app`, `typescript`, `runtimeConfig`, `build`, `modules`, `dayjs`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@nathanchase/nuxt-dayjs-module@1.0.11`, `@nuxt/image-edge@1.0.0-27827328.bc9ddc0`
- Build Modules:    `-`
------------------------------

### Reproduction

<script setup>
const { data:datanew, pending, refresh } = await useAsyncData('testDataNew', () => $fetch(`https://api.nuxtjs.dev/mountains`))
const callapinew = async () => {
    datanew.value = await useAsyncData('testDataNew', () => $fetch(`https://api.nuxtjs.dev/mountains`))
}
</script>

<template>
  <div>
    <div class="flex justify-center gap-2">
      <button style="margin-bottom: 30px" @click="callapinew()">
        Call api
      </button>
    </div>
    {{ datanew }}
    
  </div>
</template>

### Describe the bug

AsyncData does not cache even if the key is present. Is AsyncData not caching anymore?

**Comment by danielroe** [comment]
That's right, useAsyncData does not cache by default. You can implement your own cache if you would like.

**Comment by talaxasy** [comment]
@danielroe  Could you show in what place and when did they decide to change it?

**Comment by manniL** [comment]
> @danielroe Could you show in what place and when did they decide to change it?

https://github.com/nuxt/framework/pull/8885

**Comment by kirtan403** [comment]
How provide the caching mechanism then? For the static site, if on client-side navigation, the cache is not being fetched, the site breaks and starts throwing error as the fetch failed. Any other options? or examples to implement custom cache?

**Comment by talaxasy** [comment]
> How to provide the caching mechanism then? For the static site, if on client-side navigation, the cache is not being fetched, the site breaks and starts throwing error as the fetch failed. Any other options? or examples to implement custom cache (as @danielroe mentioned)?

I think it can be provided via useSWRV + $fetch in theory

**Comment by talaxasy** [comment]
It might look smth like this `const {data, pending } = useSWRV('myUniqKey', () => $fetch('api/getPosts'))`. But you won't be able to enjoy the benefits of using use(Lazy)AsyncData or use(Lazy)Fetch 😒
