### ISSUE TITLE
site not working https://nuxt.com/

### ISSUE THREAD

**Issue by borodadada** [nuxt/framework#9499]
### Environment

https://nuxt.com/

### Reproduction

https://nuxt.com/

### Describe the bug

site open empty

**Comment by smares** [comment]
Works for me in Germany using Edge 107.0.1418.62 under Windows 11.

**Comment by borodadada** [comment]
after 1 sec - white screen

**Comment by manniL** [comment]
Can't reproduce either.
Please make a quick video and show output of the browser console

**Comment by ojvribeiro** [comment]
Works fine for me in Brazil on Chrome 107.0.5304.123 Windows 10

**Comment by borodadada** [comment]
image 1 - https://ibb.co/CvLH0YC
image 2 - https://ibb.co/tDpQ2LV

**Comment by antlionguard** [comment]
> image 1 - https://ibb.co/CvLH0YC image 2 - https://ibb.co/tDpQ2LV

did you tried with disabling your all extensions? or easy way trying in incognito mode.

**Comment by borodadada** [comment]
okey, all fine, problem was in VeePN extension, very strange. Thx all!
