### ISSUE TITLE
nuxt-edge+ nuxt/bridge and @nuxtjs/composition-api methos useStore, useRoute

### ISSUE THREAD

**Issue by Andrevoks** [nuxt/framework#950]
I try to migrate from nuxt 2 to nuxt / bridge, removed pakage @ nuxtjs / composition-api, and have trouble with this methods where can I get these methods? useStore from "vuex" doesn't work

**Comment by pi0** [comment]
Hi @Andrevoks. A compatibily layer will be added when using `@nuxt/bridge` so `import { useStore } from '@nuxtjs/composion-api`` should keep working ([src](https://github.com/nuxt/framework/blob/main/packages/bridge/src/runtime/capi.legacy.mjs#L259)). But i advice to change it to `getCurrentInstance().$store` and remove imports.
