### ISSUE TITLE
Broken code is displayed on website

### ISSUE THREAD

**Issue by zakuro9715** [nuxt/framework#9508]
### Environment

website

### Reproduction

Open https://nuxt.com/docs/api/composables/use-async-data#useasyncdata

![](https://i.gyazo.com/1c28bd9c5af5df773cdba902669923b8.png)

### Describe the bug

Broken type is displayed. Seems to be broken when code contains `?`

**Comment by manniL** [comment]
Thanks! Let's track in https://github.com/nuxt/framework/issues/9141
