### ISSUE TITLE
 ERROR  (node:44673) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time

### ISSUE THREAD

**Issue by hermesalvesbr** [nuxt/framework#9524]
### Environment

```
npx nuxi info
Nuxi 3.0.0

RootDir: /home/hermes/Projetos/nuxt/bodoco-site-prefeitura
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.2.2`
- Build Modules:    `-`
------------------------------

```
----
Linux  PopOS 6.0.6-76060006-generic #202210290932~1669062050~22.04~d94609a SMP PREEMPT_DYNAMIC Mon N x86_64 x86_64 x86_64 GNU/Linux

### Reproduction

A fresh instalation show me this warning after yarn install or yarn dev: 

![image](https://user-images.githubusercontent.com/379850/205687585-19198a06-6b6a-4365-856b-d541376c62a2.png)

I have tried this: 

```
node -e "require('https').get('https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json')"
npx nuxi upgrade
```

I haven´t a network error with node. 

### Describe the bug

Everything works fine, but it keeps telling me this error in the terminal.

```
 ERROR  (node:44905) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

ℹ Vite client warmed up in 616ms
✔ Nitro built in 512 ms
(node:44905) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

### Additional context

Is this error problematic? I couldn't see something not working because of this alert in the terminal.

**Comment by manniL** [comment]
No, this is not a problem. Just a note that Node's Fetch API is experimental ☺️
