### ISSUE TITLE
Middleware NavigateTo does not work properly

### ISSUE THREAD

**Issue by nhatimme** [nuxt/framework#9525]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `build`, `postcss`, `modules`, `app`, `css`
- Runtime Modules:  `@pinia/nuxt@0.4.3`, `@nuxt/image-edge@1.0.0-27809804.194d2d6`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ylpjcg-qoy1cr?file=middleware/auth.ts

### Describe the bug

Try to navigate between the pages (Login and Private). Private should gives an redirect to /login which does not work.

**Comment by zloylos** [comment]
you should return navigateTo(…), not just call it.
https://nuxt.com/docs/guide/directory-structure/middleware#format

**Comment by nhatimme** [comment]
Thanks @zloylos. I just made a mistake on this, thanks!
