### ISSUE TITLE
Functional component hydration error when using text nodes with expressions inside one tag

### ISSUE THREAD

**Issue by vladeiko** [nuxt/framework#9538]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

- Create index page
- Create `components` folder
- Create some functional component (.tsx file)
- In functional component: `<div>Text node {'expression'}</div>`
- Check console. Will see: `[Vue warn]: Hydration children mismatch in <div>`

[https://stackblitz.com/edit/github-v1eh1z-fhq8al?file=pages%2Findex.vue,app.vue,components%2FFunctionalComponent.tsx](Example)

### Describe the bug

If you put in functional component text node and jsx expression inside one tag you recieve `hydration` error.

### Logs

```shell
[Vue warn]: Hydration text mismatch:
- Client: "Text node expression"
- Server: "Text node " 
  at <Anonymous> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/" routeProps= {Component: {…}, route: {…}} pageKey="/"  ... > 
  at <Anonymous > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=1 > 
  at <NuxtRoot>
```

```
[Vue warn]: Hydration children mismatch in <div>: server rendered element contains fewer child nodes than client vdom. 
  at <Anonymous> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/" routeProps= {Component: {…}, route: {…}} pageKey="/"  ... > 
  at <Anonymous > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=1 > 
  at <NuxtRoot>
```
```

**Comment by danielroe** [comment]
This is an upstream (Vue SSR) bug/behaviour. See https://stackblitz.com/edit/github-zgzicn. Please feel free to raise an issue at https://github.com/vuejs/core.
