### ISSUE TITLE
@nuxt/kit version does not allow same versioning as @nuxt/test-utils-edge

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/framework#9542]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Nuxt 3 defined the packages `@nuxt/kit` and `@nuxt/schema` as `3.0.0`

When using the recommended package for testing `@nuxt/test-utils-edge` - this package specifies:
```
"@nuxt/kit": "npm:@nuxt/kit-edge@3.0.1-rc.0-27838671.5f935aa"
 "@nuxt/schema": "npm:@nuxt/schema-edge@3.0.1-rc.0-27838671.5f935aa"
``` 

### Describe the bug

I get type mis-matches for `NuxtModule` and `NuxtModuleOptions` in development because 2 separate versions are installed

I think updating the Nuxt 3 package.json version to `^3.0.0` would possibly allow just one version of @nuxt/kit and @nuxt/schema to be installed so that my Playground and setup in my testing will have the same types and my module will not cause type errors when defining it in my nuxt.cong file.

**Comment by danielroe** [comment]
Yes, I think we should update the test-utils recommendation to `^3.0.0`.

**Comment by silverbackdan** [comment]
Thanks for such a prompt response

**Comment by silverbackdan** [comment]
TBH there are some big usability bugs resolved in `@nuxt/test-utils-edge` which aren't present in `@nuxt/test-utils` yet. Using `vitest` it's seemingly impossible (at least for now) to get the typescript aliases in place (e.g. `#imports` `#app` ) that are auto-generated in the /.nuxt/imports file.
Some docs on setting up vitest would be extremely useful, been struggling through that.
Just as a note, I'm not sure if there's an issue to raise as the edge version seems to work ok with a plugin that a contributor made `vite-plugin-nuxt-test`

**Comment by danielroe** [comment]
I'm working on https://github.com/nuxt/framework/issues/2465 which should improve things on that front 😊

**Comment by silverbackdan** [comment]
Ah ok fab. I had my tests running with `test-utils-edge` as least yesterday and because I was messing with packages and now the next version is gone it's all broken. Is there a temp workaround you could suggest. I'm using the plugin to map the aliases into vite but now getting `[vite-node] Failed to load /.nuxt/imports` :( it's a sticking point to continue writing tests today now, so if there's a quick fix just for now that'd be amazing.

**Comment by silverbackdan** [comment]
I'll move the discussion to that thread :)
