### ISSUE TITLE
Nuxt 3 documentation rendering issue for snippets

### ISSUE THREAD

**Issue by piyush-multiplexer** [nuxt/framework#9563]
### Environment

NA

### Reproduction

Visit this link and inside snippets: 
https://nuxt.com/docs/guide/directory-structure/server#example

### Describe the bug

It seems opening/left curly braces `{` is not generating and rendering in examples code snippet in documentation, first i thought it was typo but code is correctly types but not visible correctly in website.

https://nuxt.com/docs/guide/directory-structure/server#example

### Additional context

Missing left/opening braces `{`.

![image](https://user-images.githubusercontent.com/18528418/206107993-ec6a1fdb-1fb2-4689-bd74-f7af40aa6959.png)
![image](https://user-images.githubusercontent.com/18528418/206108088-7c1d4348-601f-4301-ae62-cbf8ebb9118a.png)

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/framework/issues/9141.
