### ISSUE TITLE
fix(module): no type information on runtime components

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/framework#9576]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qspr4q?file=src%2Fruntime%2Fcomponents%2FTest.vue,playground%2Fnuxt.config.js

### Describe the bug

This bug is about vscode type hints. Because I get no type hints at all on Stackblitz, it appears to be required to download the stackblitz repo and check it out manually, I'm afraid. Here are the steps required after download and extraction:

- run `npm i` and `npm run prepare`
- hover `ref` in line 8 of `src/runtime/components/Test.vue` and see that there are no type hints popping up
- uncomment the 4th line in `playground/nuxt.config.js` and run `npm run prepare` again
- see that the type hints from before are now shown

I'd expect the type hints to show right away. @danielroe once fixed this in https://github.com/nuxt/framework/pull/7726 I believe, but apparently there is more to it, maybe a misunderstanding.

**Comment by danielroe** [comment]
That PR led to unwanted behaviour in monorepos so we now have a specific option for module authors and others who want types to be applied across a workspace:

```js
  export default defineNuxtConfig({
    typescript: {
+     includeWorkspace: true,
      tsConfig: {
        // include: ['../../**/*'], // https://github.com/nuxt/framework/pull/7726
      },
    },
  });

```

**Comment by dargmuesli** [comment]
Thank you for that information! <3 I missed that.
