### ISSUE TITLE
useFetch not executed on SSR (Using Pinia to handle useFetch)

### ISSUE THREAD

**Issue by nhatimme** [nuxt/framework#9597]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `build`, `postcss`, `modules`, `app`, `css`
- Runtime Modules:  `@pinia/nuxt@0.4.3`, `@nuxt/image-edge@1.0.0-27809804.194d2d6`
- Build Modules:    `-`

### Reproduction

[link](https://stackblitz.com/edit/github-hxyxnk?file=pages/login.vue)

### Describe the bug

I'm trying to execute a useFetch within a Pinia state function, which works. But is being executed client side, instead of server side.

When I click on the button (Login.vue), it does fires useFetch and retrieves the data. The problem is, it runs client side. How to make sure this runs server side? I'm a little bit lost.

**Comment by danielroe** [comment]
In this case you shouldn't use `useFetch` but `$fetch` directly.

**Comment by nhatimme** [comment]
Hi @danielroe. I also tried that. I run `const { data: user }: any = await $fetch('https://test.com/api/user/create-token', requestOptions);`

But still I see the request clientside. What can cause this?

**Comment by danielroe** [comment]
Why shouldn't it be running on client-side? You're clicking the login button on client-side.

**Comment by nhatimme** [comment]
Let me ask this question differently to understand what my goal is. I want to run this fetch server side. What should be the correct way to handle the fetch server side within NUXT? I understand that the client clicks the button when it comes to UI.

**Comment by danielroe** [comment]
In that case you should:

* call your own server api like this `$fetch('/api/login', { body: someData })`
* within your server api (`~/server/api/login.ts`) you can then call the api you wish to call on server side

**Comment by nhatimme** [comment]
I understand the application of the API server. If I understand (and I just implemented it) I can see the api server (api/login) is still providing an XHR (fetch request (from the client)), which is logic.

For clarity:
- I don't want to create a public API that people can navigate to. Like localhost/api/<name>
- What I wish is that when someone has entered their username and password (Login.vue), no data can be seen via client side (XHR, the fetch request). I want the server to complete the entire request and no data is visible to the client.

Is this possible within NUXT? If yes, how can I manage this?

**Comment by danielroe** [comment]
I'm a bit confused. The user clicks a button in the browser. But you don't want any network request to be made at that point from the browser, even to the Nuxt server? But you wish a network request to be made from the Nuxt server? How could the server know to make the request?

**Comment by nhatimme** [comment]
Things to know:
- External API Endpoint: app.com/get-token (POST username + password)
- External API Endpoint: app.com/user (GET + Authorization (Token) header)

1. So if I understand correctly the best flight path for a login is:
- email, password are sent as parameters to an API Endpoint (visible at client level). The token you get back from the API as a response is then stored as a client-level cookie.

2. If a user goes to a certain route, Middleware (Not serverMiddleware right?) is applied. (middleware/auth.ts). The Token is retrieved from the Cookie and the external endpoint app.com/user (is consulted) to verify that the user is actually authorized. This all happens on client side correct?

Or is it possible to also perform step 2 completely server side? Can you indicate to me what the best way of working is and of course also the safest?
