### ISSUE TITLE
Start wrong port number

### ISSUE THREAD

**Issue by XiaoLi-sach** [nuxt/framework#9605]
### Environment

- Operating System: Windows
- Node Version: v18.0.0
- Nuxt Version: 3.0.0-rc.12 
- Package Manager: pnpm@7.8.0 
- Builder: vite 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

### Reproduction

- 

### Describe the bug

I want set the project to start on port `3000`, but boot on a different port.
Then I checked that the port I wanted to start was not occupied. I'm sure this port is not occupied.

This my config: 
```typescript
export default defineNuxtConfig({
  ssr: true,
  server: {
    url: 'http://localhost:3000',
    host: 'localhost',
    port: 3000,
  },
....
})
```

It doesn't feel like this configuration is working.
I don't understand why it always starts in  port `24679` or `24678`?

**Comment by manniL** [comment]
You don't need any configuration to start on port 3000. If it is not available, other ports will be picked. Be aware that the vite HMR server will run on 24XXX

**Comment by XiaoLi-sach** [comment]
> You don't need any configuration to start on port 3000. If it is not available, other ports will be picked. Be aware that the vite HMR server will run on 24XXX

Oh,  Even though I didn't set it in config, it still doesn't start on port 3000.

**Comment by manniL** [comment]
Can you provide a reproduction? Working fine on my end.

**Comment by XiaoLi-sach** [comment]
![image](https://user-images.githubusercontent.com/55753927/206677973-665c641b-c07a-459e-92fd-9c6db02643d0.png)

I removed all server config.  It's fine if it doesn't change, but it always changes port `24xxx`.

**Comment by manniL** [comment]
Can you check if you expose a `PORT` env variable by any chance?

**Comment by XiaoLi-sach** [comment]
I checked, and I deleted it as well
