### ISSUE TITLE
detect updated deployment and handle (for example, by refreshing app)

### ISSUE THREAD

**Issue by koronowicz** [nuxt/framework#9623]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.2.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.9.0`
- Builder:          `vite`
- User Config:      `modules`, `image`, `sitemap`, `build`, `css`, `schemaOrg`, `app`
- Runtime Modules:  `@nuxt/content@2.2.2`, `@funken-studio/sitemap-nuxt-3@4.0.4`, `nuxt-schema-org@2.0.0`,
- Build Modules:    `-`

### Reproduction

It can be reproduce in every instance of Nuxt app.

### Describe the bug

After deploying new version of app to Netlify I found that having older version od app opened in browser doesn't work. Nuxtlinks are broken and throwing console errors.

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (_template_.c41376b3.js, line 0)
[Error] TypeError: Importing a module script failed.
	ae (entry.e47db422.js:5:21169)
	promiseReactionJob
```

I understand that it's because assets are rebuild with new hash names. I'm wondering is there is a safe way of detecting this error and refreshing website?

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/framework/issues/6648
