### ISSUE TITLE
ServerSide NavigateTo is not defined 

### ISSUE THREAD

**Issue by lasrol** [nuxt/framework#9652]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `app`, `css`, `build`, `modules`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- add an endpoint under server/
- return navigateTo(example.com, { external: true })

### Describe the bug

According to the documentation `navigateTo` is available both client and server side. 
When trying to call navigateTo from a server endpoint it returns navigateTo is not defined. 

`

### Logs

```shell
[nuxt] [request error] [unhandled] [500] navigateTo is not defined
```

**Comment by danielroe** [comment]
It is only usable in the Vue part of your app. In server endpoints, use sendRedirect.

**Comment by lasrol** [comment]
Thanks for the quick reply, feel the documentation was unclear about this.

**Comment by manniL** [comment]
> Thanks for the quick reply, feel the documentation was unclear about this.

PR welcome! ☺️
