### ISSUE TITLE
Nuxt 3 with Electron.js - 404 Page not found

### ISSUE THREAD

**Issue by zavodnyrichard** [nuxt/framework#9663]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `ssr`
- Runtime Modules: 
- Build Modules: 

### Reproduction

https://github.com/gurvan-guss/nuxt-electron-sample

### Describe the bug

When building the application for production using the `ssr: false` flag, it result in **404 Page not found** on start-up of the Electron application. If you click on the "Go back home" button everything then works properly. It works fine when you don't have a pages directory but when you specify one you get this initial 404 Page not found.

**Comment by zavodnyrichard** [comment]
Details are also in https://github.com/nuxt/framework/discussions/4569

**Comment by danielroe** [comment]
I think this is about configuring electron rather than a nuxt issue per se, so let's track in the discussion.

**Comment by gurvan-guss** [comment]
I managed to find the problem, you need to setup the hashMode to true in the router option, here is the configuration in `nuxt.config.ts`:
```ts
  ssr: false,
  router: {
    options: {
      hashMode: true,
    },
  },
  app: {
    baseURL: './',
  },
```
I updated the repository here: https://github.com/gurvan-guss/nuxt-electron-sample

**Comment by zavodnyrichard** [comment]
> I managed to find the problem, you need to setup the hashMode to true in the router option as explained in the documentation: https://nuxt.com/docs/guide/directory-structure/pages#hash-mode-spa. It will solve the problem of 404 not found at start-up and the problem of reloading the App in production. Here is the configuration in `nuxt.config.ts`:
> 
> ```ts
>   ssr: false,
>   router: {
>     options: {
>       hashMode: true,
>     },
>   },
>   app: {
>     baseURL: './',
>   },
> ```
> 
> I updated the repository here: https://github.com/gurvan-guss/nuxt-electron-sample

Great, it works! You are the best Gurvan!
