### ISSUE TITLE
`error.vue` page not shown when using `throw createError()` in `[...slug].vue` during development

### ISSUE THREAD

**Issue by Anoesj** [nuxt/framework#9668]
### Environment

Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.18.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-dynamic-slug-error?file=README.md

### Describe the bug

I have a catch-all route, `[...slug].vue`, that I use to dynamically resolve routes to backend content. If no content is found in the backend, I want to show the 404 page, which is the `error.vue` file in my Nuxt root dir. I do this as follows:
```ts
if (!content) {
  throw createError({
    statusCode: 404,
    message: `Could not find content with route “${fullPath}”`,
    fatal: true,
  });
}
```

I added a `<NuxtLink>` to my main navigation that intentionally points at a non-existing route to test this behavior. It took me a while to figure out that my code was working perfectly in production, because during development, Nuxt behaves differently than in a generated build:

#### Full reload on non-existing route
When browsing directly to the non-existing route (full reload on route):
- ✔️ **Development:** 404 page, as expected.
- ✔️ **Production (generated build):** 404 page, as expected.

#### Navigation to non-existing route
When starting on any working page, then navigating to the non-existing route using the `NuxtLink`:
- ❌ **Development:** uncaught errors in the console, no 404 page is shown.
- ✔️ **Production (generated build):** 404 page, as expected.

### Thoughts
In Vue runtime core, function `logError` has a parameter called `throwInDev`. This parameter is set to `true` by default and seems to control whether an error is thrown when handling errors in Vue components during development. It seems to me that this should have been set to `false` in order to be able to show `error.vue` after throwing `createError` inside `[...slug].vue`, but I haven't tested this myself.

**Comment by GadQ** [comment]
I can confirm, I got this error independently in my own repo.

**Comment by awacode21** [comment]
Same here!

**Comment by mferraco** [comment]
I am also seeing the same thing.

**Comment by danielroe** [comment]
let's track this in https://github.com/nuxt/framework/issues/8880
