### ISSUE TITLE
docs(plugins): Typo into - Using Composables Within Plugins - Example

### ISSUE THREAD

**Issue by jessefilho** [nuxt/framework#9689]
### Environment

doc

### Reproduction

Manual mouse selection from [Using Composables Within Plugins](https://nuxt.com/docs/guide/directory-structure/plugins#using-composables-within-plugins)

```
export default defineNuxtPlugin((NuxtApp) =>
  const foo = useFoo()
})
```

### Describe the bug

When we do not click over the button `Copy to clipboard` and do a manual selection the left bracket is missing.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/9141.
