### ISSUE TITLE
Page transition throw error and break application when changing page before ending current transition:

### ISSUE THREAD

**Issue by igortrinidad** [nuxt/framework#9690]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.5.4`
- Builder:          `vite`
- User Config:      `app`, `modules`, `tailwindcss`, `build`, `vite`, `alias`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`
- Build Modules:    `-`
------------------------------

### Reproduction

Go to: [test Nuxt application](https://testing-page-transition-error.vercel.app/app)?

Toggle between App and Profile routes multiple times, the error will happen if you changed quickly enough, the problem isnt the error it self, but the application breaks all content after that...

### Describe the bug

DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node

### Additional context

https://www.loom.com/share/2c285d6b5050426aaccf3e278bb96f5f

### Logs

```shell
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

**Comment by danielroe** [comment]
We can track in https://github.com/nuxt/framework/issues/3141.
