### ISSUE TITLE
Per-page layouts broken in edge channel

### ISSUE THREAD

**Issue by thijsw** [nuxt/framework#9694]
### Environment

Nuxi 3.0.1-rc.0-27848798.0cb9a4c  
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.1-rc.0-27848798.0cb9a4c`
- Nitro Version:    `2.0.0-27847631.8186a02`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

I copied this example layout structure from the [docs](https://nuxt.com/docs/guide/directory-structure/layouts#setting-another-layout), and ran the code in this Stackblitz:

![Screenshot 2022-12-13 at 15 35 07](https://user-images.githubusercontent.com/28638/207361780-054fbea3-4622-4ad1-a5a1-1cf3496bc90d.png)

**Reproduction:**
https://stackblitz.com/edit/nuxt-starter-as8e2b

### Describe the bug

Instead of the page I get an error:

> 500
> Cannot read properties of undefined (reading 'meta')

**Comment by danielroe** [comment]
I believe that is an upstream issue in vue/vue-router. It should be resolved if you refresh your lockfile and ensure that only one version of `vue-router` is installed.

**Comment by thijsw** [comment]
I have deleted the lock file and ran `yarn install`, when I run `yarn why vue-router` it looks like only a single version is installed:

```
$ yarn why vue-router
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "vue-router"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "vue-router@4.1.6"
info Reasons this module exists
   - "nuxt" depends on it
   - Hoisted from "nuxt#vue-router"
info Disk size without dependencies: "832KB"
info Disk size with unique dependencies: "1016KB"
info Disk size with transitive dependencies: "1016KB"
info Number of shared dependencies: 1
```

**Comment by thijsw** [comment]
I cannot reproduce the issue with a fresh install anymore, maybe the Vite 4.0.2 solved the issue? Anyway, glad it is not a problem anymore :)
