### ISSUE TITLE
Adding ".value" is required when using useState in a v-if or v-show directive

### ISSUE THREAD

**Issue by eyeruleall** [nuxt/framework#9718]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-slqvqh?file=app.vue

### Describe the bug

Adding ".value" is required when using useState in a v-if or v-show directive.

As we all know, we do not need to add .value when using a ref inside of a template. useState, as a ref replacement, should follow that same convention.

**Comment by huang-julien** [comment]
Hi! This is because Vue will only unref variables that are initialized in the setup and not call expressions. Here you are calling directly `useState()` within the template.

**Comment by manniL** [comment]
I did not know that either, thanks for the explanation @huang-julien ☺️

Closing here 👍
