### ISSUE TITLE
`useFetch` for post api don't work in `onMounted`

### ISSUE THREAD

**Issue by mogi86** [nuxt/framework#9721]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.6`
- Build Modules:    `-`
------------------------------

### Reproduction

- Repository: https://github.com/mogi86/study-nuxt3-v2/blob/v0.0.5/src/pages/api_from_client.vue
- local URL: http://localhost:3000/api_from_client/

### Describe the bug

It seems that `useFetch` for `post api` don't work in `onMounted` . Do you know what the cause is?
BTW, `useFetch` for `get api` work in `onMounted`.
I'm not sure that this is bug or nuxt feature. sorry.

### Logs

- console.log

```shell
response1: null
response2: Hello, World!
```

`response1` is response of post api.

**Comment by Thenafi** [comment]
Same

**Comment by Amirali-Yavari** [comment]
Hi dear you use asyncData for post method

**Comment by mogi86** [comment]
@Amirali-Yavari 
Do you know how to call `post api` after rendering?

**Comment by Amirali-Yavari** [comment]
You can use 
`$fetch('url',{options}).then((res) => {
  Console.log(res)
})`

**Comment by mogi86** [comment]
Thanks. `post api` worked when use `$fetch()`.
https://github.com/mogi86/study-nuxt3-v2/blob/v0.0.6/src/pages/api_from_client.vue

I still don't understand `$fetch()` exactly, I’ll see the documentation.

**Comment by Amirali-Yavari** [comment]
Your welcome dear

**Comment by manniL** [comment]
Using the `server: false` option + calling it during setup should work too
