### ISSUE TITLE
Select box with v-model updates lazy when mounting the component

### ISSUE THREAD

**Issue by leorott** [nuxt/framework#9735]
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

Here is a minimal reproduction:
[https://stackblitz.com/edit/github-u8yyoy?file=app.vue](https://stackblitz.com/edit/github-u8yyoy?file=app.vue)

### Describe the bug

`v-model` is behaving weirdly when a value is already set while mounting the component.

In the following example the select box initially shows option `A` then the Component re-renders and shows the correct option `B`. However the selected ref is set to `3` from the beginning according to the output in the console when I'm logging the `selected` ref.

``` vue
<template>
  <div>
    <select v-model="selected">
      <option value="2">A</option>
      <option value="3">B</option>
      <option value="4">C</option>
    </select>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue';
const selected = ref('3');
</script>
```

When using the `v-bind` directive and `@change`, everything works fine.

``` vue
<template>
  <div>
    <select @change="(e) => selectedValue = e.target.value">
      <option value="4" :selected="isSelected('4')">A</option>
      <option value="5" :selected="isSelected('5')">B</option>
      <option value="6" :selected="isSelected('6')">C</option>
    </select>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue';
const selected = ref('6');
const isSelected = (value) => selectedValue.value === value
</script>
```

Moreover, this error occurs only when using a select box. Other types of input fields (checkbox, radio button, text input) work. Also when doing the same in plain Vue 3 it works.

**Comment by danielroe** [comment]
Would you check to see if this is reproducible for you on Vue 3 SSR: https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main?file=src%2FApp.vue&terminal=dev

**Comment by leorott** [comment]
Yes, it's also happening on Vue 3 SSR: [https://stackblitz.com/edit/github-vd1slr?file=src/pages/Home.vue](https://stackblitz.com/edit/github-vd1slr?file=src/pages/Home.vue)

**Comment by danielroe** [comment]
So I think that's an upstream vue enhancement issue in that case. Feel free to open an issue on https://github.com/vuejs/core. Maybe we could hardcode the displayed value in the rendered HTML so there isn't that flash on hydration.

**Comment by leorott** [comment]
I just noticed that the nuxt contributor Vue3 SSR starter has the follwing issue that I hadn't considered on Friday: ``Setting server.middlewareMode to 'ssr' is deprecated, set server.middlewareMode to `true` and appType to 'custom' instead``. I have fixed this problem in my example and also opened a pull request here: https://github.com/nuxt-contrib/vue3-ssr-starter

With these changes, the select box now updates correctly on Vue3 SSR, so it would make sense to reopen this issue here, as it doesn`t seem to be a Vue bug anymore. Here is an working minimal reproduction with Vue3 SSR:
https://stackblitz.com/edit/github-vd1slr-6jstcm?file=src/pages/Home.vue

**Comment by danielroe** [comment]
I think you've misconfigured the vite server; it's not doing SSR any more. See https://github.com/nuxt-contrib/vue3-ssr-starter/commit/d6464a64559be504b5c2e1f5282b86e0e92b7d7b and let me know if it still replicates when you make that change in your repro.

**Comment by leorott** [comment]
Oops... you're right, thanks for pointing that out. I will create an issue on vuejs tomorrow.
