### ISSUE TITLE
Tcmg

### ISSUE THREAD

**Issue by tcmg77** [nuxt/framework#9750]
### Describe the feature

Look forward for improvement 

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by manniL** [comment]
I am not sure what exactly this issue is about? 🙈 

Closing here
