### ISSUE TITLE
nuxt generate (MPA SSG) adds the vue-router to the entry.js increasing the bundle size

### ISSUE THREAD

**Issue by HummingMind** [nuxt/framework#9751]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.3.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `experimental`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

The issue is obvious.

### Describe the bug

I would like to have an SSG MPA with the smallest possible starting bundle size.

When I run nuxt generate with just the app.vue file, the entry.js file is 37.2 kb gzipped (includes vue3 and nuxt3 runtimes).
When I delete this file and create the pages folder with an index.vue file, the new entry.js file size goes up to 50.1 kb gzipped. It seems like the vue-router is getting added to the bundle. But why? There is no SPA/client-side routing being used.

Is this a bug? Is there a way to stop the router from being added to the bundle?

Thank you!

**Comment by manniL** [comment]
When you use the `pages` folder, routing is always assumed. If you have "just a landing page, you can stick to using solely `app.vue` ☺️

**Comment by HummingMind** [comment]
But why would client-side routing be needed for a static MPA?
I'd like to have a bunch of pre-rendered (SSG) pages that just get hydrated at a later point. Similar to Next.js, similar to Astro, etc.

The bundle size is increasing for no reason, as the router will never be used. Or am I missing something?

**Comment by HummingMind** [comment]
I guess I'll have to roll with something other than Nuxt for my scenario.

Thank you!

**Comment by HummingMind** [comment]
Ended up picking ilies.
Much better. 21.1 kb main bundle that doesn't grow in size. Lazy-loading for the rest of the components (islands).

**Comment by HummingMind** [comment]
Looks like it's not a true SSG. It's a hybrid where the pages are prerendered, but after the hydration, the app turns into a SPA.
That is why the router is included in the bundle.

**Comment by danielroe** [comment]
If you want a static MPA, you can enable this flag:

```js
export default defineNuxtConfig({
  experimental: {
    noScripts: true
  },
})
```

**Comment by HummingMind** [comment]
@danielroe 
Thank you for the response. That is not where the confusion came from. What you have suggested would disable JS entirely for the app.

What I initially was wondering is why an MPA that doesn't use the NuxtLink component would need the vue-router in the bundle. Using regular a tags between pages would have been sufficient for a true SSG.

But as posted above, generate doesn't produce a fully static site. It still turns into a SPA after full hydration. So client side routing is still needed.

Thank you!
