### ISSUE TITLE
npm run generate does not generates 404.html

### ISSUE THREAD

**Issue by mpincipientinfo** [nuxt/framework#9760]
I added error.vue which works fine in local. But while generating my repo. The 404.html does not reflects in dost folder. I also added   generate : {
      fallback: '404.html'
  }, in nuxt.config.ts but no avail. 

SSR: true
target: static

**Comment by danielroe** [comment]
That config is for nuxt 2. You can add `/404.html` to `nitro.prerender.routes`.

**Comment by mpincipientinfo** [comment]
Can you please send me the steps. Would be helpful.

**Comment by danielroe** [comment]
```js
export default defineNuxtConfig({
  nitro: {
    prerender: {
      routes: ['/404.html']
    }
  })

**Comment by mpincipientinfo** [comment]
I did this & I added error.vue file in root folder. It works fine in development. But not working in prod environment. I am not getting what's wrong. I tried 404.vue & directly adding 404.html in public folder too. Nothing worked for me in prod. When I run "npm run generate" There is no such file "404.html" in dist folder.

**Comment by Raklon181995** [comment]
export default defineNuxtConfig({
  nitro: {
    prerender: {
      routes: ['/404.html']
    }
  }
})
I'm facing same issue. it is not working

**Comment by notflip** [comment]
> I did this & I added error.vue file in root folder. It works fine in development. But not working in prod environment. I am not getting what's wrong. I tried 404.vue & directly adding 404.html in public folder too. Nothing worked for me in prod. When I run "npm run generate" There is no such file "404.html" in dist folder.

Did you find a solution? I'm running into the exact same problem

**Comment by notflip** [comment]
Found a working solution
- Create the page `pages/[...slug].vue`

Set the following content
```
<template>
  <div>Woops!</div>
</template>

<script setup>
setResponseStatus(404)
</script>
```

**Comment by LeonBuchner** [comment]
Both solutions not working when using SSR 
Any Ideas?
