### ISSUE TITLE
Deployment Nuxt Application on Linux KO

### ISSUE THREAD

**Issue by kaboume** [nuxt/framework#9772]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `modules`, `css`, `build`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@pinia-plugin-persistedstate/nuxt@1.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

pm2 restart /var/www/dev2.my-app.fr/pm2.json

### Describe the bug

My Nuxt3 applciation works fine on my windows laptop but after deployed on linux server, this is impossible de run the application.
Here is my .env file : 
```
PORT=3015
NITRO_PORT=3015
```

I'm using Gitlab CI to deploy and execute the pm2 runner : 
Here is my Gitlab CI conf file : 

```
script:
    - chmod +x ./setup_env_dev.sh
    - ./setup_env_dev.sh
    - npm install
    - npm run build
    # Inject the remote's private key
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Append keyscan output into known hosts
    - ssh-keyscan -H 79.137.36.159  >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # Synchro
    - rsync -rpl -e "ssh -p 1234" --exclude='.git/' --exclude='.gitlab-ci.yml' ./ xxx@xxx.xxx.xxx.xx:/var/www/my-app.fr/
    - ssh xxx@xxx.xxx.xxx.xxx -p 1234  "pm2 restart /var/www/my-app.fr/pm2.json --only my-app.fr"
```

The pm2 logs are : 

```
17|dev2.st | npm ERR! path /var/www/my-app.fr
17|dev2.st | npm ERR! command failed
17|dev2.st | npm ERR! command sh -c node .output/server/index.mjs
17|dev2.st | npm ERR! code 1
```

And when I want ton execute manually the process : 

`node .output/server/index.mjs`

```
file:///var/www/my-app.fr/.output/server/node_modules/h3/dist/index.mjs:48
  const err = new H3Error(input.message ?? input.statusMessage, input.cause ? { cause: input.cause } : void 0);
                                         ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)

```

**Comment by DanSnow** [comment]
I guess that is because the Node.js version on your server does not match the one on your laptop.

**Comment by kaboume** [comment]
Thanks !
I no longer have the error after updating the version of node.
On the other hand, it does not take into account the port that I indicated in the .env file

`[nitro] [dev] [uncaughtException] Error: listen EADDRINUSE: address already in use :::3000`

I am having the same problem locally after an npm run build & npm run start

**Comment by kaboume** [comment]
For information, my pm2.json file 
```

{
    "apps": [
      {
        "name": "my-app.fr",
        "exec_mode": "cluster",
        "script": "npm",
        "cwd": "/var/www/my-app.fr",
        "port": 3015,
        "args": "start",
        "instances": 1,
        "autorestart": true,
        "watch": false,
        "max_memory_restart": "1G",
        "env": {
          "NODE_ENV": "development"
        },
        "env_production": {
          "NODE_ENV": "production"
        }
      }      
    ]
  }
```

**Comment by danielroe** [comment]
Your `.env` file will not be read when you run `.output/server/index.mjs` so you need to set the environment variable yourself, for example, in your `pm2.json` file.

**Comment by kaboume** [comment]
Thank you !
I think everyone, like me, coming from Nuxt2 will encounter the same problem. It would be desirable to specify it in the Nuxt3 doc: https://nuxt.com/docs/getting-started/deployment

Indeed, when I execute in the terminal:

`PORT=3015 npm run start`

The application launches correctly.
However when I run the application from pm2 :

`pm2 restart /var/www/my-app.fr/pm2.json --only my-app.fr`


```
{
    "apps": [
      {
        "name": "my-app.fr",
        "exec_mode": "cluster", // enables clustering
        "script": "PORT 3015 npm",
        "cwd": "/var/www/my-app",
        "port": 3015,
        "args": "start",
        "instances": 1,
        "autorestart": true,
        "watch": false,
        "max_memory_restart": "1G",
        "env": {
          "NODE_ENV": "development"
        },
        "env_production": {
          "NODE_ENV": "production"
        }
      }      
    ]
  }
```

The application does not launch and I have the following error stack:

```
17|dev2.st |     at help (/usr/share/nodejs/npm/lib/help.js:41:5)
17|dev2.st |     at Object.[_runCmd] (/usr/share/nodejs/npm/lib/npm.js:119:7)
17|dev2.st |     at Proxy.fn (/usr/share/nodejs/npm/lib/npm.js:46:40)
17|dev2.st |     at Object.<anonymous> (/usr/share/nodejs/npm/lib/cli.js:62:20)
17|dev2.st | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
17|dev2.st | TypeError: Cannot read property 'length' of undefined
17|dev2.st |     at leven (/usr/share/nodejs/leven/index.js:14:11)
17|dev2.st |     at /usr/share/nodejs/npm/lib/utils/did-you-mean.js:5:20
17|dev2.st |     at Array.filter (<anonymous>)
17|dev2.st |     at didYouMean (/usr/share/nodejs/npm/lib/utils/did-you-mean.js:5:6)
17|dev2.st |     at module.exports (/usr/share/nodejs/npm/lib/utils/npm-usage.js:38:12)
17|dev2.st |     at help (/usr/share/nodejs/npm/lib/help.js:41:5)
17|dev2.st |     at Object.[_runCmd] (/usr/share/nodejs/npm/lib/npm.js:119:7)
17|dev2.st |     at Proxy.fn (/usr/share/nodejs/npm/lib/npm.js:46:40)
17|dev2.st |     at Object.<anonymous> (/usr/share/nodejs/npm/lib/cli.js:62:20)
```

**Comment by danielroe** [comment]
I believe you should specify the variable lower down in the `env` and `env_production` sections.

**Comment by kaboume** [comment]
All my excuses...
I just understood: I mounted the version of node but pm2 kept the old version!
So when I updated the version of pm2 and node used by pm2, everything worked!!

[](https://pm2.keymetrics.io/docs/usage/update-pm2/
)
Thank you!

**Comment by kaboume** [comment]
I understood why this command line didn't work : 

`source .env && node .output/server/index.mjs `

because I had to add EXPORT at the beginning of each line in my .env file like that : 

```
EXPORT PORT=3015
EXPORT NITRO_PORT=3015
```
