### ISSUE TITLE
deploy nuxt 3 on plesk

### ISSUE THREAD

**Issue by mohamad68** [nuxt/framework#9789]
### Environment

ssr

### Reproduction

null

### Describe the bug

how can I deploy Nuxt 3 on Plesk? 
there is no guide on the official site for deploying on Plesk plz give me a step-by-step guide to deploy Nuxt 3 on Plesk.

**Comment by jimpatrick** [comment]
more than 2 million users are using Plesk but there is not any guide in document . this is really annoying
plz tell us how to deploy nuxt 3 on Plesk

**Comment by SarahGhorbani** [comment]
I have this problem too

**Comment by pi0** [comment]
Unfortunately i no longer have a running plesk to test and write docs for Nuxt 3 but you can inspired much from https://github.com/pi0/nuxt-plesk-example. Output of Nuxt 3 should be fully compatible. Inside `server.js`, you can use `import('./.output/server/index.mjs'`. 

Also PR welcome to add page in nitro and nuxt docs 👍🏼

**Comment by mohamad68** [comment]
> Unfortunately i no longer have a running plesk to test and write docs for Nuxt 3 but you can inspired much from https://github.com/pi0/nuxt-plesk-example. Output of Nuxt 3 should be fully compatible. Inside `server.js`, you can use `import('./.output/server/index.mjs'`.
> 
> Also PR welcome to add page in nitro and nuxt docs 👍🏼

thank you Poya, my problem is solved 
I deploy Nuxt3 on Plesk successfully via your guide
thank you for making this magnificent framework
