### ISSUE TITLE
`watch` not work in server side

### ISSUE THREAD

**Issue by xtoolkit** [nuxt/framework#9791]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-p2mkbv?file=pages/index.vue

### Describe the bug

hi
`watch` ref in server side not fire. `watchEffect` fire, but not currect.

### Logs

```shell
watchEffect RefImpl {                                                                                             
  __v_isShallow: false,
  dep: undefined,
  __v_isRef: true,
  _rawValue: 'bar',
  _value: 'bar'
}
```

**Comment by huang-julien** [comment]
Hi! i think this is probably because [Vue is not reactive server side](https://vuejs.org/guide/scaling-up/ssr.html#reactivity-on-the-server). You can add `{ immediate: true }` to trigger it server-side
