### ISSUE TITLE
nitro seems to have an issue with `pnpm` symlink

### ISSUE THREAD

**Issue by rootblack45** [nuxt/framework#980]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.9.1`
- Nuxt Version:     `3-3.0.0-27235451.ece0e01`
- Package Manager:  `unknown`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
- pnpm Version: `6.17.0`

### Describe the bug

Start by creating a new Nuxt project and install modules by using `pnpm i`. By default, `pnpm` uses symlinked `node_modules` structure unlike `yarn` and `npm`. So the problem is symlinked `node_modules` structure as you can see in the output when running `pnpm dev` `$PROJECT_ROOT/.nuxt/nitro/index.mjs` file required `unenv` but it's not defined in `package.json`. It is a common mistake caused by flat `node_modules`.

### Reproduction

To avoid this warning I am trying to solve this using the [solution](https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here) written by pnpm. The first solution and the second solution are too cumbersome, it might crash again if nitro has a new update. So back to basic, I'm using the third solution to creates a flat `node_modules` structure similar to the one created by `npm` or `yarn`.

### Additional context

The third solution that pnpm provided. Is not a good option to use with a big workspace and the project has a lot of conflicts.

### Logs

```shell
Nuxt CLI v3.0.0-27235451.ece0e01
                                                                                                                                                        
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.0.222:3000/

ℹ Vite warmed up in 486ms
✔ Vite server built in 665ms
✔ Nitro built in 156 ms
✔ Vite server built in 22ms
✔ Generated nuxt.d.ts

WARN [worker] Cannot find package 'unenv' imported from $PROJECT_ROOT/.nuxt/nitro/index.mjs
Did you mean to import unenv@0.3.10/node_modules/unenv/runtime/polyfill/fetch.node.js?

  Did you mean to import unenv@0.3.10/node_modules/unenv/runtime/polyfill/fetch.node.js?
  at new NodeError (node:internal/errors:371:5)
  at packageResolve (node:internal/modules/esm/resolve:845:9)
  at moduleResolve (node:internal/modules/esm/resolve:890:18)
  at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:1004:11)
  at Loader.resolve (node:internal/modules/esm/loader:89:40)
  at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)

✔ Vite server built in 11ms
```

**Comment by pi0** [comment]
Hi @rootblack45 and thanks for reporting the issue. Currently, pnpm is not supported. Please track this discussion: https://github.com/nuxt/framework/discussions/939
