### ISSUE TITLE
Dev server error while using in Turborepo.

### ISSUE THREAD

**Issue by therealokoro** [nuxt/framework#9804]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.3.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.18.2`
- Builder:          `vite`
- User Config:      `modules`, `nitro`
- Runtime Modules:  `@myturborepo/ui@0.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

Reproduction: [Turborepo Nuxt Boilerplate](https://github.com/gurvan-guss/turborepo-nuxt-boilerplate)

It's worth mentioning that even without making a single tweak on this repo, the issues still occured.

### Describe the bug

So I was looking to use nuxt with turborepo. The plan is to have a full-fledged nuxt 3 web app as part of the `apps` workspace and a minimal nuxt 3 project as a shared package in the `packages` workspace which I can then extend in the web app.

Luckily for me, I found this [repo](https://github.com/gurvan-guss/turborepo-nuxt-boilerplate) that does something similar.

I cloned the repo and tweaked it to my needs. And when I ran the dev command, everything worked fine. But on checking my browser, I was met with the infamous error

`[vite-node] [ERR_INVALID_URL_SCHEME] /@fs/C:/Users/Okoro Redemption/Documents/DevWorld/My Apps/app-name/node_modules/.pnpm/ufo@1.0.0/node_modules/ufo/dist/index.mjs`.

I remember this error being very common a while ago and it was fixed, so I was so surprised to see it's ugly head again(very frustrating 😖).

### Additional context

#9110 This was the original issue which was opened a while ago that saw it fixed by @danielroe.

It was understood that this error was caused by the whitespaces present in the filepath which if you look closely, you'll see that its indeed the case here too

`[vite-node] [ERR_INVALID_URL_SCHEME] /@fs/C:/Users/Okoro Redemption/Documents/DevWorld/My Apps/app-name/node_modules/.pnpm/ufo@1.0.0/node_modules/ufo/dist/index.mjs`.

Now my guess is that this has to do with how turborepo symlinks the packages in the different workspaces 🤷‍♂️.

**Comment by manniL** [comment]
Follow https://github.com/nuxt/framework/issues/9074#issuecomment-1330691425 - you still use ufo@v1.0.0
