### ISSUE TITLE
Provide `useAsyncAction` helper function

### ISSUE THREAD

**Issue by cawa-93** [nuxt/framework#9818]
### Describe the feature

Common use case: performing some asynchronous actions, but not when the component is loaded, but in response to user actions. It would be very useful to have a utility that offers the same api as `useAsyncData`, but writes the callback function not when the component is mounted, but only when it is explicitly called

```vue
<script setup>
const { error, pending, execute, data } = useAsyncAction(
  // The first argument is nuxt context to be consistent with useAsyncData. 
  // All next arguments passed from `execute` call
 (ctx, event) => $fetch('api/save-data', new FormData(event.target)) 
) 
</script>

<template>
<form @submit.prevent="execute">
  <div v-if="error">Failed to save data to server {{error}}</div>
  <div v-else-if="pending">Saving ...</div>
  <div v-else-if="data">Succesfully saved</div>
</form>
</template>
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
This is possible by setting the `immediate: false` option with `useAsyncData`.

**Comment by cawa-93** [comment]
@danielroe Actually not. 
1. `useAsyncData` with `immediate: false` still return `pending: true` even if `execute` was never call. 
2. `execute` from `useAsyncData` doesn't accept any arguments. 
3. `useAsyncData` can't accept `key` as reactive string.  Which does not allow you to dynamically change the key depending on the parameters to avoid caching
