### ISSUE TITLE
Rectivity lost / hydration mismatch in ssr for parent component

### ISSUE THREAD

**Issue by Kasheftin** [nuxt/framework#9828]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Repro link: https://github.com/Kasheftin/nuxt-ssr-reactivity-issue
Repro steps:
 - go to http://localhost:3000/users/5604
 - console shows `[Vue warn]: Hydration text content mismatch in <div> (- Client:  Navbar: users > #5604 - Server:  Navbar: )`

### Describe the bug

Any application might consist on general/common components (side menu, navbar) and pages. Usually navbar have to match the page. In my [minimal repro](https://github.com/Kasheftin/nuxt-ssr-reactivity-issue) navbar shows breadcrumbs. There's a global variable (e.g. pinia/vuex or just a global ref) used for communication between the page and the navbar.  

[User details page](https://github.com/Kasheftin/nuxt-ssr-reactivity-issue/blob/master/pages/users/%5Bid%5D.vue) is responsible for loading the data using `useAsyncData` helper accordingly to `route.params.id` parameter. When the data is loaded, it updates the breadcrumbs variable:

````typescript
import { breadcrumbs } from '@/stores/breadcrumbs'
const route = useRoute()
const id = computed(() => route.params.id)
const { data, refresh } = useAsyncData<{id: number; title: string}>('user', async () => {
  const result = await fetch(`https://gorest.co.in/public/v2/users/${id.value}`)
  return await result.json()
})
watch(id, refresh)
watch(() => [id.value, data.value?.id], () => {
  breadcrumbs.value = ['users', data.value?.title || '#' + id.value]
}, { immediate: true })
````

This works just fine on the client. 

However, there's an issue with SSR. It looks like anything that was rendered before the page (layout components or parent pages) stops being reactive at the point when user details is being received. Logging shows that `breadcrumbs` was updated correctly, every child component is being rendered correctly as well, but everything from the parent context does not respond to changes.

### Logs

```shell
[Vue warn]: Hydration text content mismatch in <div>:
- Client:  Navbar: users > #5604
- Server:  Navbar:  
  at <Users onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <Anonymous key="/users" routeProps= {Component: {…}, route: {…}} pageKey="/users"  ... > 
  at <Anonymous > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <App key=1 > 
  at <NuxtRoot>
```

**Comment by manniL** [comment]
Hey! I'd say this is a limitation of SSR. See https://github.com/nuxt/framework/issues/9001#issuecomment-1314927266
