### ISSUE TITLE
Nuxt config variable has always default value when its name is different from env variable

### ISSUE THREAD

**Issue by scrtechnologies** [nuxt/framework#9839]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

You want to set anuxt.config variable from env variable. The nuxt.config variable has different name as env variable. Then nuxt.config variable doesn't have value from env variable

1. Nuxt config

```
runtimeConfig: {
    public: {
      a: {
        b: process.env.MY_ENV_VAR || 'default',
      },
    },
  },
```
2. run build
`yarn build`

3. run production
`MY_ENV_VAR=value-from-env yarn start`

And the value of nuxt.config variable is "default"  not "value-from-env" as you would exptected.

Reproduction on  https://stackblitz.com/edit/nuxt-starter-p6uraz?file=nuxt.config.ts

### Describe the bug

You can't set value from env variable to nuxt.config variable with different name.

**Comment by dsvgl** [comment]
Try `NUXT_PUBLIC_ MY_ENV_VAR=value-from-env yarn start`
see https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables

**Comment by danielroe** [comment]
Env variables that override at runtime need to match the path, so in your case it must be `NUXT_PUBLIC_A_B`. This is required to avoid having to keep/parse your `nuxt.config` file in production, which would hinder performance.
