### ISSUE TITLE
Route rules swr/caching not working 

### ISSUE THREAD

**Issue by LouisHaftmann** [nuxt/framework#9841]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.18.2`
- Builder:          `vite`
- User Config:      `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/LouisHaftmann/nuxt3-ssr-caching-issue

### Describe the bug

The `swr`/`static` nitro route rules don't work.

### Additional context

This issue occurs when building with the `node-server` preset (haven't tried other presets). I believe the problem is caused by [this line](https://github.com/unjs/nitro/blob/4ed8efe7b95bb75e7b579f0843a9c8ddc6faf126/src/runtime/app.ts#L58) from nitro because it only matches the `/**` route. So all the other route rules are ignored.

**Comment by manniL** [comment]
Node server preset does not support static nor SWR yet. Follow along https://github.com/unjs/nitro/issues/603 for that ☺️
