### ISSUE TITLE
close `Nitro`

### ISSUE THREAD

**Issue by evanlong0926** [nuxt/framework#9857]
### Describe the feature

No longer starts `Nitro`

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by manniL** [comment]
I am not sure what you trying to say. Could you please elaborate on your issue description?

**Comment by pi0** [comment]
Let's close issue in the meantime.
