### ISSUE TITLE
Hydration causes incorrect rendering for dark mode even though all variables have correct values

### ISSUE THREAD

**Issue by alexgrozav** [nuxt/framework#9887]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `plugins`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

1. Set dark mode
2. Refresh
3. Values are updated correctly, but component markup still renders visually for light mode

https://stackblitz.com/edit/nuxt-starter-kkazxz?file=app.vue

### Describe the bug

I've run into this issue when working on dark mode for https://github.com/inkline/inkline. 

Everything works correctly except setting dark mode, storing to localStorage and then refreshing:
- The component variables have the correct values
- The component markup renders incorrectly

=> The view renders as light mode even though all the variable values

**Comment by huang-julien** [comment]
that's because your plugin is setting the colorMode to dark before the hydration is completed.

To avoid a hydration mismatch, you can change the value after the app is mounted client side.
````ts
   app.$nuxt.hook('app:mounted', () => {
        const storedColorMode = localStorage.getItem(colorModeLocalStorageKey);

        if (storedColorMode) {
          options.colorMode = storedColorMode;
        }
      })
````
However this will cause the colorMode to be set after the app is rendered.

**Comment by alexgrozav** [comment]
@huang-julien thank you so much for the clarification! Would there be any realistic way to render it correctly on both client and server?

**Comment by huang-julien** [comment]
i might try through cookies. But why don't you use [@nuxtjs/color-mode](https://color-mode.nuxtjs.org/) ?
