### ISSUE TITLE
Unexpected token import in old browser

### ISSUE THREAD

**Issue by rafifn** [nuxt/framework#9895]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.1-rc.0-27863365.da6fa9a`
- Nitro Version:    `2.0.0-27860563.409fe2b`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/rafifn/repro-nuxt-issue

<img width="486" alt="Screen Shot 2023-01-01 at 02 05 01" src="https://user-images.githubusercontent.com/34232700/210153468-6128ccfb-47cd-402d-952f-6f6fbff90270.png">

https://user-images.githubusercontent.com/34232700/210149125-5e1c985b-caf2-4527-840f-b06d03c874a7.mov

### Describe the bug

HTML rendered with perfect but can't do anything in client side even `console.log` not show when button is click

**Comment by rafifn** [comment]
anyone can help me @pi0 @danielroe ?

**Comment by danielroe** [comment]
With Vite, we currently only support browsers that support native ES modules: https://vitejs.dev/guide/#browser-support.

**Comment by rafifn** [comment]
@danielroe , how about `@vitejs/plugin-legacy` ? in vite [docs](https://www.npmjs.com/package/@vitejs/plugin-legacy) the legacy browser can be supported using it

**Comment by danielroe** [comment]
Yes, indeed that is a potential solution, but it's not built in to Nuxt 3 so you will need to configure it on your own.

**Comment by rafifn** [comment]
noted @danielroe 
is this already planned to be fixed by the nuxt team?

**Comment by rafifn** [comment]
hey @danielroe, with vite currently only support browser that support native ES modules right ?
how about webpack ? I have some errors
`Uncaught SyntaxError: Unexpected token ?`
`Uncaught SyntaxError: Unexpected token {`
`Uncaught SyntaxError: Unexpected token .`

and can you give me temporary solutions to handle the old browsers?
thanks a lot for your help

https://user-images.githubusercontent.com/34232700/211992170-7a4c8a9c-b501-457a-b9e3-0aae482cf8ef.mp4
