### ISSUE TITLE
useFetch(url,form)执行一次post请求后，form中数据发生变化时，useFetch(url,form)会重复执行多次

### ISSUE THREAD

**Issue by ryiot** [nuxt/framework#9905]
### Environment

useFetch(url,form)执行一次post请求后，form中数据发生变化时，useFetch(url,form)会执行多次

### Reproduction

useFetch(url,form)执行一次post请求后，form中数据发生变化时，useFetch(url,form)会重复执行多次

### Describe the bug

useFetch(url,form)执行一次post请求后，form中数据发生变化时，useFetch(url,form)会重复执行多次

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

嘿！ 能否请您提供复制品？ 🙏

**Comment by ryiot** [comment]
> 嘿！你能提供一个[复制品](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)吗？🙏
> 
> 嘿！ 能不能请您提供复制品？🙏

https://github.com/ryiot/nuxt3-bug

**Comment by manniL** [comment]
You better use `$fetch` instead of useFetch in your scenario (https://github.com/ryiot/nuxt3-bug/blob/main/src/pages/index.vue#L14) as you only want to trigger the call when calling `loginHandle` and not based on e.g. reactivity.

```ts
const loginHandle = async () => {
  const { data } = await $fetch('/api/login', { method: 'POST', body: form })
  console.log('data=',data)
}
```

**Comment by ryiot** [comment]
> You better use `$fetch` instead of useFetch in your scenario (https://github.com/ryiot/nuxt3-bug/blob/main/src/pages/index.vue#L14) as you only want to trigger the call when calling `loginHandle` and not based on e.g. reactivity.
> 
> ```ts
> const loginHandle = async () => {
>   const { data } = await $fetch('/api/login', { method: 'POST', body: form })
>   console.log('data=',data)
> }
> ```
> 
> Reason why this "anomaly" happens: After initializing `useFetch`, you pass the reactive `form` as body. When updating it, the fetch all will be executed again. With `$fetch`, this does not happen.

thanks
