### ISSUE TITLE
Data in Script Setup isn't readable

### ISSUE THREAD

**Issue by bastianhilton** [nuxt/framework#9907]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `extends`, `css`, `modules`, `auth`, `apollo`, `session`, `monacoEditor`, `build`, `vite`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.12`, `@nuxtjs/apollo@5.0.0-alpha.5`, `@sidebase/nuxt-auth@0.3.0`, `@sidebase/nuxt-session@0.2.6`, `nuxt-highcharts@3.0.8`, `nuxt-monaco-editor@1.1.1`, `@nuxt/content@2.3.0`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/meeovi/alternateframework

1.  Install Nuxt 3
2.  Following Nuxt 3 guide to add const { data: apitables } = await useAsyncData("api", () => $fetch("/api/read")); within script setup tag and getting 'apitables' is declared but its value is never read

### Describe the bug

i'm not able to read any data within the script setup tag

### Additional context

```
<template>
    <div>
        <v-navigation-drawer permanent class="contentLeft">
            <v-list>
                <h4>Content Manager</h4>
                <LeftCreateTable />
                <v-divider></v-divider>
                <h6>Tables ()</h6>
                <div>
                    <v-list-item :title="apitables" :value="apitables">{{ apitables }}</v-list-item>
                </div>
            </v-list>
        </v-navigation-drawer>
    </div>
</template>

<script>
import LeftCreateTable from './LeftCreateTable'

    export default {
        components: { LeftCreateTable }
    }
</script>

<script setup>
const { data: apitables } = await useAsyncData("api", () => $fetch("/api/read"));
</script>
```

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by jeky1950** [comment]
Try this:

```
<template>
    <div>
        <v-navigation-drawer permanent class="contentLeft">
            <v-list>
                <h4>Content Manager</h4>
                <LeftCreateTable />
                <v-divider></v-divider>
                <h6>Tables ()</h6>
                <div>
                    <v-list-item :title="apitables" :value="apitables">{{ data }}</v-list-item>
                </div>
            </v-list>
        </v-navigation-drawer>
    </div>
</template>

<script setup>
         const { data } = await useAsyncData(() => $fetch("/api/read"));
</script>
```
And I dont thing you need to import the component script tag

**Comment by manniL** [comment]
> Try this:
> 
> ```
> <template>
>     <div>
>         <v-navigation-drawer permanent class="contentLeft">
>             <v-list>
>                 <h4>Content Manager</h4>
>                 <LeftCreateTable />
>                 <v-divider></v-divider>
>                 <h6>Tables ()</h6>
>                 <div>
>                     <v-list-item title="apitables" :value="data">{{ data }}</v-list-item>
>                 </div>
>             </v-list>
>         </v-navigation-drawer>
>     </div>
> </template>
> 
> <script setup>
>          const { data } = await useAsyncData(() => $fetch("/api/read"));
> </script>
> ```

Please provide a CodeSandbox, StackBlitz or git repo with as little dependencies as possible ☺️

**Comment by jeky1950** [comment]
Sorry https://stackblitz.com/edit/nuxt-starter-lroa77?file=app.vue

**Comment by manniL** [comment]
> Sorry [stackblitz.com/edit/nuxt-starter-lroa77?file=app.vue](https://stackblitz.com/edit/nuxt-starter-lroa77?file=app.vue)

Thanks! Can you explain what the issue is exactly? Data is being fetched and shown as I'd expect 👀

**Comment by bastianhilton** [comment]
it must be something in my project that is preventing data from being read, when i copied the exact code I have into stackblitz above it work and read the file. But in my project I get this still: 'data' is declared but its value is never read

**Comment by bastianhilton** [comment]
actually just tested it and although I got that message in visual studio code, the data is still rendered on the frontend

```
<template>
    <div>
        <v-navigation-drawer permanent class="contentLeft">
            <v-list>
                <h4>Content Manager</h4>
                <LeftCreateTable />
                <v-divider></v-divider>
                <h6>Tables ({{ count }})</h6>
                <div v-for="data in data" :key="data">
                    <v-list-item  :value="data">{{ data }}</v-list-item>
                </div>
            </v-list>
        </v-navigation-drawer>
    </div>
</template>

<script>
import LeftCreateTable from './LeftCreateTable'

    export default {
        components: { LeftCreateTable }
    }
</script>

<script setup>
    const { data } = await useAsyncData(() => $fetch("/api/read"));
</script>
```

So looks like the issue is resolved, my read.ts had data that wasn't correct that is why the data wasn't showing on the frontend
