### ISSUE TITLE
Comma-separated `const`'s produces error in SFC

### ISSUE THREAD

**Issue by k16e-me** [nuxt/framework#9913]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `app`, `runtimeConfig`, `lodash`
- Runtime Modules:  `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/tailwindcss@6.2.0`, `@nuxtjs/supabase@0.3.0`, `nuxt-icon@0.1.8`, `nuxt-lodash@2.4.1`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

https://gitlab.com/k16e/c.food/-/blob/main/components/CardProduct.vue

### Describe the bug

I'm used to declaring multiple `const`'s as comma separated lines like so

```
const
    { product } = defineProps(['product']),
    store = useProductStore(),
    msg = 'Hello',
    log = () => console.log(msg)
```

Now, for over 2 days I couldn't figure why I kept getting errors like "[Vue warn]: Property "msg" was accessed during render but is not defined on instance." And I couldn't see where I was doing any stuff wrong. Just when I wanted to report it on the Discord, I tried explicitly defining ever line with the const keyword like so

```
const { product } = defineProps(['product'])
const store = useProductStore()
const msg = 'Hello'
const log = () => console.log(msg)
```

and voila everything worked fine. Why? I find it a pain and just no longer used to having to manually type out the const keyword for every variable line. 

What might cause Nuxt to error in this regard? 

### Additional context

By the way, in a page file I have similar const declaration like so

```
const
    { id } = useRoute().params,
    sku = id.substr(-8),
    supabase = useSupabaseClient(),
    { data: product, error } = await useAsyncData('products',
        async () => {
            const { data } = await supabase
                .from('products')
                .select('*')
                .match({ sku })
            return data
        }
    )
```

and it works just fine. So, what is happening?

**Comment by huang-julien** [comment]
Hi 👋 can you try 
````ts
const
    store = useProductStore(),
    msg = 'Hello',
    log = () => console.log(msg),
    { product } = defineProps(['product'])
````
instead ?

**Comment by avinean** [comment]
It's definitely a bug.
But what's the benefit of using such expressions?
It doesn't look cleaner as for me.

**Comment by manniL** [comment]
As @huang-julien pointed out, this is an upstream Vue bug. Feel free to follow https://github.com/vuejs/core/issues/7460 for updates ☺️
