### ISSUE TITLE
[Docs] `app.config.ts` must be in the source directory, which is not necessarily the root

### ISSUE THREAD

**Issue by jsulpis** [nuxt/framework#9914]
Hi, I see that there is a [closed issue](https://github.com/nuxt/framework/issues/8012) about that, but I still think the documentation is misleading:

The [documentation](https://nuxt.com/docs/getting-started/configuration#app-configuration) clearly says that `app.config.ts` must be located at the root of a project. But as Daniel said in the previous issue, it must be in the `srcDir`, so if we change it in `nuxt.config.ts`, it is no more the root.

Here is what I suggest:
- reword slightly the paragraph in `Get Started > Configuration > App Configuration` (or add a little "info panel" ?) to mention the source directory instead of root
- update the folder structure in the [nuxt config reference](https://nuxt.com/docs/api/configuration/nuxt-config#srcdir) to show the `app.config.ts` in the `src` folder (and maybe `app.vue` too ?)

I would be happy to do the PR if you want

**Comment by pi0** [comment]
Surely PR welcome to clarify app configuration section it is in the source directory not root. 

Regarding folder structure, i belive to keep it simple, we can add a note before/after that this structure is relative to `srcDir` option. 

BTW regarding why, rootDir defines the build time root of a Nuxt project while src is the runtime. And `app.config` is a runtime configuration and compiled same as other source code and `.ts`/`.vue` files.

**Comment by jsulpis** [comment]
Thank you for your feedback and explaination, here is the PR. 
I don't understand _"we can add a note before/after that this structure is relative to srcDir option."_  (not sure we talk about the same thing), so I only reworded the sentence in the configuration section. Tell me if you want me to update something else.
