### ISSUE TITLE
When I use the method from composable twice, it works weird

### ISSUE THREAD

**Issue by sangemi** [nuxt/framework#9942]
### Environment

        "nuxt": "^3.0.0",

### Reproduction

I created a composable as follows to attach a header whenever I use the useFetch function.

```
export const useCommon = () => {
    async function useFetchToken(api: string, option: useFetchTokenTyle){
        const autoOption:any = {
            headers: (option.headers) ?? { Authorization: 'Bearer ' + ado_token.value }
        }
        ...
        return await useFetch(api, {...option,...autoOption})   
    }
    return {
        useFetchToken
    }
}
```
and I use this useFetchToken composable twice in one

```
<script setup lang="ts">
const { useFetchToken } = useCommon()
let {data:category_lists, refresh:cateRefresh} = await useFetchToken('/api/action', { 
    baseURL: CATEGORY_API,
    method: 'post',
    body: {
        action: 'DoSomeThing',
    }
})

let {data:section_lists, refresh:sectionRefresh} = await useFetchToken('/api/action', { 
    baseURL: CATEGORY_API,
    method: 'post',
    body: {
        action: 'DoSomeThing2',
    }
})
```
Then, a strange result occurs.

"category_lists" affect from second useFetchToken composable. "category_lists" is overwritten by 2nd useFetchToken composable.

### Describe the bug

The 2 fetchs are return different results.

But when I refresh, category_lists is equals to section_lists.

When I run cateRefresh, category_lists get right result.
When I delete 2nd useFetchToken part, "category_lists" work correctly.
When I change useFetchToken to useFetch, it will work well all.

**Comment by Saeed1112** [comment]
isn't that because you set both request base Url to CATEGORY_API? 
they have same endpoints?
and try to remove await in useFetchToken function.

**Comment by manniL** [comment]
As @Saeed1112 mentioned.

Because the URL is the same and no custom `key` for `useFetch` is defined, this is internally handled via the same ref and thus you see the result.
