### ISSUE TITLE
Create error with fatal does not redirect to error page

### ISSUE THREAD

**Issue by mkierdev** [nuxt/framework#9953]
### Environment

Nuxt 3.0, 
Linux
Node 16
Development environment

### Reproduction

In page that you want to navigate, inside setup, put up this code:

```js
throw createError({ statusCode: 404, statusMessage: 'Page Not Found', fatal: true })
```

### Describe the bug

If page is SSR (on first render), the error page shows correctly. It doesn't matter if it's default nuxt error page or custom error.vue page.

However, if we land on one page and navigate to another containing throw createError (so the pages are rendered on client), we can only observe that error is being logged to console, but no redirect to error page is happening.

### Additional context

createError with fatal set to true should redirect to error page.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/framework/issues/8880.
