### ISSUE TITLE
Add --dotenv support for nuxi generate command

### ISSUE THREAD

**Issue by dionearle** [nuxt/framework#9966]
### Describe the feature

Similar to what has already been done in this issue request (https://github.com/nuxt/framework/issues/7646) and subsequently this pull request (https://github.com/nuxt/framework/pull/7660), would it be possible if this functionality was also added to the `nuxi generate` command?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Yes, I think it makes sense (it's confusing otherwise) :+1:

**Comment by huang-julien** [comment]
Isn't this already supported ? I think this is just missing in the documentation.
