### ISSUE TITLE
Handling Requests with Body not working

### ISSUE THREAD

**Issue by damchap** [nuxt/framework#9976]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.1.2`
- Builder:          `vite`
- User Config:      `modules`, `routeRules`, `robots`, `sitemap`, `unlighthouse`, `webVitals`, `tailwindcss`, `app`, `router`, `css`, `script`, `build`, `runtimeConfig`
- Runtime Modules:  `@nuxt/image-edge@1.0.0-27827328.bc9ddc0`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/web-vitals@0.2.2`, `~/modules/sitemap`, `@unlighthouse/nuxt@0.4.4`, `@nuxtjs/robots@3.0.0-2`, `nuxt-icon@0.1.7`
- Build Modules:    `-`
------------------------------

### Reproduction

I created a file in `/server/api/` with the name `contact.post.ts`.

In this file I create event Handler with readBody from H3 for return http body : 
```ts
export default defineEventHandler(async (event) => {
    const body = await readBody(event)
    return { body }
})
```
This code is taken from the documentation of nuxt 3 
[Handling Requests with Body](https://nuxt.com/docs/guide/directory-structure/server#handling-requests-with-body)

### Describe the bug

the code from the documentation does not work
[Handling Requests with Body](https://nuxt.com/docs/guide/directory-structure/server#handling-requests-with-body)

```ts
export default defineEventHandler(async (event) => {
    const body = await readBody(event)
    return { body }
})
```
the http body is not recovered

<img width="821" alt="Capture d’écran 2023-01-06 à 16 32 17" src="https://user-images.githubusercontent.com/64602545/211044159-f4c61dd4-9340-447c-b000-1532e262463b.png">

**Comment by danielroe** [comment]
You appear to be making the request to `/api/test` not `/api/contact`

**Comment by danielroe** [comment]
Would you provide a reproduction?

I can't reproduce: https://stackblitz.com/edit/github-cse5nk

**Comment by damchap** [comment]
I reproduced the bug : 

https://stackblitz.com/edit/github-cse5nk-tjz4zs

**Comment by danielroe** [comment]
It doesn't reproduce for me.

**Comment by damchap** [comment]
The problem comes from the configuration of `routeRules` in the file `nuxt.config.ts` that comes from my side.
