### ISSUE TITLE
How to get rid of Cannot find name 'Ammo' when importing with config head script tag?

### ISSUE THREAD

**Issue by dataexcess** [nuxt/framework#9984]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `nitro`, `typescript`, `modules`, `css`, `components`, `runtimeConfig`, `build`, `server`, `app`, `alias`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@pinia/nuxt@0.4.6`, `nuxt-directus@3.2.2`, `@nuxt/image-edge@1.0.0-27821548.ab054e4`
- Build Modules:    `-`
------------------------------

### Reproduction

/

### Describe the bug

I am importing the Ammo.js library using the head tag of the nuxt 3 config file like so:

```
app: {
        head: {
            script: [
                {
                    src: 'libs/ammo/ammo.wasm.js'
                }
            ]
        }
    },
```

The good thing is that it works, but somehow typescript is complaining that it cannot recognise the name when I initialise the library.

```
onMounted(async () => {
    await nextTick()
    Ammo().then(function (_ammo:any) {
       console.log(_ammo)
        setupPhysics(_ammo)
    })
})
```

My file becomes red in VSCode and the error reads: 
`Cannot find name 'Ammo'.ts(2304)`

When I console.log the _ammo object  it prints out the object correctly. So somehow nuxt isn't picking up the Ammo object while it does actually work. Can I somehow surpress this in vscode? or what is going on?

Thank you!!

**Comment by manniL** [comment]
You can try `window.Ammo` instead.
Alternatively, you can also provide types or use the `// @ts-ignore` comment.

**Comment by dataexcess** [comment]
Trying with window.Ammo give me this:
`Property 'Ammo' does not exist on type 'Window & typeof globalThis'.ts(2339)
Using // @ts-ignore does not work. Could you explain how I could make types for this? I'm still relatively new to typescript.
Thnx!

**Comment by dataexcess** [comment]
Ok nevermind i found it!

wrote this in a ~/types/index.ts file ...

```
export { }

declare global {

    // surpress Ammo not found error
    let Ammo: any
}
```
